### ISSUE TITLE
Create filesystem mock utilities

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#10009]
**What would you like Renovate to be able to do?**

- Mock `__fixtures__` folders and its subfolders as the entire filesystem via [mock-fs library](https://github.com/tschaub/mock-fs)
- Inherit from base folder for the entire `*.spec.ts` file, being able to add/remove/change some file for particular test case
  - manually
  - folder structure like `__fixtures__/base`, `__fixtures__/case-1`, `__fixtures__/case-2`, etc

In the further PRs, gradually rewrite tests, that
- contain fragments like `fs.exists.mockResolvedValueOnce(...)`
- rely on creating and writing to tmp dirs

**Did you already have any implementation ideas?**

Leverage current `testUtil.loadFixture` resolving mechanism and make a thin wrapper around `mock-fs` lib.

**Comment by pret-a-porter** [comment]
@zharinov @HonkingGoose I have already introduced using `mock-fs` in repository. I would like to take this issue.
