### ISSUE TITLE
Error updating branch ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by aishwarya257** [renovatebot/renovate#10079]
**What Renovate type, platform and version are you using?**

**Renovate type**

- Self hosted

**Renovate platform**

-  GitLab (gitlab.com, self-hosted)
- 

**Renovate version (if self hosting)**

I'm self hosting Renovate with version: `renovate/renovate:25.21.13`

**Describe the bug**

I have setup the renovate runner. But, no new merge request is triggered and I get this error which I pasted below.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
 WARN: Error updating branch (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/serverless-2.x)
       "err": {
         "code": "ERR_INVALID_ARG_TYPE",
         "message": "The \"path\" argument must be of type string. Received undefined",
         "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received undefined\n    at validateString (internal/validators.js:124:11)\n    at Object.join (path.js:1110:7)\n    at Object.join (/usr/src/app/node_modules/upath/build/code/upath.js:51:33)\n    at Object.getAdditionalFiles (/usr/src/app/node_modules/renovate/lib/manager/npm/post-update/index.ts:456:35)\n    at Object.processBranch (/usr/src/app/node_modules/renovate/lib/workers/branch/index.ts:276:29)\n    at Object.writeUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/write.ts:38:17)\n    at Object.update (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:129:11)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:47:17)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:112:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
       }

```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I don't have time for that, and cannot share my private repository

**Additional context**

**Comment by viceice** [comment]
Aleady fixed, you need a manual update to v25.21.16

**Comment by aishwarya257** [comment]
Now that error is gone, I have a new error now
`
 INFO: Branch created (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/node-14.x)
       "commitSha": "1459628"
 INFO: PR created (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/node-14.x)
       "pr": 2,
       "prTitle": "Update dependency @types/node to v14.17.0"
 WARN: artifactErrors (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/node-14.x)
       "artifactErrors": [
         {
           "lockFile": "yarn.lock",
           "stderr": "unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n"
         }
       ]
 WARN: Could not remove Docker container (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/aws-sdk-2.x)
       "image": "node",
       "containerName": "renovate_node",
       "cmd": "docker ps --filter name=renovate_node -aq",
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "docker ps --filter name=renovate_node -aq",
         "stdout": "",
         "stderr": "unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n",
         "message": "Command failed: docker ps --filter name=renovate_node -aq\nunable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n",
         "stack": "Error: Command failed: docker ps --filter name=renovate_node -aq\nunable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n\n    at ChildProcess.exithandler (child_process.js:319:12)\n    at ChildProcess.emit (events.js:376:20)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
       }
 WARN: Could not remove Docker container (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/aws-sdk-2.x)
       "image": "node",
       "containerName": "renovate_node",
       "cmd": "docker ps --filter name=renovate_node -aq",
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "docker ps --filter name=renovate_node -aq",
         "stdout": "",
         "stderr": "unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n",
         "message": "Command failed: docker ps --filter name=renovate_node -aq\nunable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n",
         "stack": "Error: Command failed: docker ps --filter name=renovate_node -aq\nunable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n\n    at ChildProcess.exithandler (child_process.js:319:12)\n    at ChildProcess.emit (events.js:376:20)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
       }
 INFO: Branch created (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/aws-sdk-2.x)
       "commitSha": "2b6e508"
 INFO: PR created (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/aws-sdk-2.x)
       "pr": 3,
       "prTitle": "Update dependency aws-sdk to v2.910.0"
 WARN: artifactErrors (repository=catalyst2/sftp/sftp-account-manager, branch=renovate/aws-sdk-2.x)
       "artifactErrors": [
         {
           "lockFile": "yarn.lock",
           "stderr": "unable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n"
         }
       ]`

**Comment by viceice** [comment]
Please format your code. Which version are you using now?

**Comment by aishwarya257** [comment]
Now I use v25.26.1, the latest version

**Comment by viceice** [comment]
how are you running renovate? Looks like you use `binarySource=docker` ? so you changed something for it?
