### ISSUE TITLE
Label configuration for security change sets 

### ISSUE THREAD

**Issue by clok** [renovatebot/renovate#10124]
**What would you like Renovate to be able to do?**

Similar to the options that are available for `major` and `minor`, I would like the ability to configure the GitHub label that is applied to a security patch PR. 

**Did you already have any implementation ideas?**

Within the configuration block, add a `security` option that is similar to `major` and `minor`. I would only implement the ability to set labels at first.

I am interested in implementing this and contributing to the project. I wanted to post first to make sure I wasn't missing something in the documentation or Issues list.

**Comment by rarkins** [comment]
I think this might work:

```json
{
  "vulnerabilityAlerts": {
    "labels": ["security"]
  }
}
```

**Comment by clok** [comment]
🥇 @rarkins  Thanks! I was looking in the docs for "security" and just missed the `vulnerabilityAlerts` block.

Linking to the docs here for future reference: https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts

**Comment by clok** [comment]
Just following up to confirmed that it worked exactly as I had hoped. 💯 
![image](https://user-images.githubusercontent.com/1429775/119600294-60bdad00-bdac-11eb-8b6d-6e4a1d83c859.png)
