### ISSUE TITLE
Renovate not upgrading .nvmrc to 16.2.0

### ISSUE THREAD

**Issue by CareLuLu-Gabriel** [renovatebot/renovate#10130]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com

**Describe the bug**

Renovate isn't creating PRs to bum `.nvmrc` version. It should have created a PR for version `16.2.0`.
```
{
  "extends": [
    "config:base"
  ],
  "semanticCommits": true,
  "automerge": true,
  "major": {
    "automerge": false
  },
  "node": {
    "supportPolicy": "current"
  },
  "masterIssue": true
}
```

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
"nvm": [
  {
    "packageFile": ".nvmrc",
    "deps": [
      {
        "depName": "node",
        "currentValue": "16.1.0",
        "datasource": "github-tags",
        "lookupName": "nodejs/node",
        "depIndex": 0,
        "warnings": [],
        "sourceUrl": "https://github.com/nodejs/node",
        "currentVersion": "16.1.0",
        "fixedVersion": "16.1.0",
        "updates": []
      }
    ]
  }
]
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository: https://github.com/CareLuLu/renovate-test

**Comment by rarkins** [comment]
If you add `"ignoreUnstable": false,` to your config then it will work. Currently Renovate only upgrades unstable->unstable if they are the same major.minor.patch, e.g. for npm updates like v1.2.3-alpha.1 -> v1.2.3-pre.0
