### ISSUE TITLE
Changelog containing '</details>' breaks pr formatting

### ISSUE THREAD

**Issue by dsbert** [renovatebot/renovate#10143]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: 25.21.12

**Describe the bug**

The renovate changelog contains `</details>`. This is not escaped so when the PR is created, the collapsed changelog formatting breaks. This could happen with any other project obviously, but this projects changelog is an easy example. I'm not sure if it makes sense to scan the changelogs and escape this everywhere, but it might at least make sense to escape that somehow in this specific changelog.

...

**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

https://gitlab.com/dsbert/renovate-bot/-/merge_requests/2

**Additional context**

![image](https://user-images.githubusercontent.com/1320090/119508538-d179b080-bd3d-11eb-87ba-af14eccfbe36.png)

**Comment by rarkins** [comment]
Are you aware of any open source package which has included this in a recent changelog?

**Comment by dsbert** [comment]
I created an example

https://gitlab.com/dsbert/renovate-bot/-/merge_requests/2

**Comment by viceice** [comment]
I think this is already fixed in newer renovate https://github.com/renovatebot/renovate/commit/80e3e6ac782b6b3420d421cb1e3f6f434f23e48a, so please update to [`v25.26.5`](https://github.com/renovatebot/renovate/releases/tag/25.26.5)  or higher

**Comment by viceice** [comment]
You should also checkout our gitlab pipeline templates for at https://gitlab.com/renovate-bot/renovate-runner

**Comment by rarkins** [comment]
Which version did you run?

**Comment by HonkingGoose** [comment]
> Which version did you run?

From the top post it seems they used:

> Renovate version: 25.21.12

So their version is **older** than the (presumed fixed) version v25.26.5.

**Comment by dsbert** [comment]
I ran it again with a local version of `renovate@25.31.0` and the result is the same, so I do not think this issue has been resolved.

**Comment by viceice** [comment]
@dsbert Did you checked the rebase checkbox before you run with latest version, so renovate did a force update?

**Comment by rarkins** [comment]
I think Renovate will always update PR bodies regardless of whether it's rebasing
