### ISSUE TITLE
Renovate ignores "ignorePresets" options

### ISSUE THREAD

**Issue by dannyyy** [renovatebot/renovate#10161]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [x] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25

**Describe the bug**

In the main config the `extends: ["config:base"]` is set together with `ignorePresets: [":ignoreModulesAndTests"]`. This has been done in accordance to the documentation: https://docs.renovatebot.com/configuration-options/#ignorepresets

Even the renovate log says that this preset will be ignored, it actually does not.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: Combined config
         "endpoint": "https://***@dev.azure.com/***/",
         "token": "***",
         "gitAuthor": "Renovate <renovate@***>",
         "onboarding": false,
         "requireConfig": true,
         "extends": ["config:base"],
         "ignorePresets": [":ignoreModulesAndTests"],
         "platform": "azure",
         "enabledManagers": ["npm", "nuget", "pip_requirements"],
         "recreateClosed": true,
         "packageRules": [
           {
             "matchDatasources": ["nuget"],
             "registryUrls": [
               "https://api.nuget.org/v3/index.json",
               "https://***.pkgs.visualstudio.com/_packaging/***/nuget/v3/index.json"
             ]
           }
         ],
         "hostRules": [
           {
             "hostType": "nuget",
             "username": "",
             "password": "***",
             "baseUrl": "https://***.pkgs.visualstudio.com"
           },
           {"hostType": "github", "domainName": "github.com", "token": "***"}
         ],
         "repositories": ["***/***"]
       }

...

# Looks good so far
DEBUG: Ignoring preset :ignoreModulesAndTests in [config:base]

...

# It says it's ignoring some line above, but actually it does not
DEBUG: Found repo ignorePaths (repository=***/***)
       "ignorePaths": [
         "**/node_modules/**",
         "**/bower_components/**",
         "**/vendor/**",
         "**/examples/**",
         "**/__tests__/**",
         "**/test/**",
         "**/tests/**",
         "**/__fixtures__/**"
       ]
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
Please note:

- Here are Renovate's default `ignorePaths`: https://github.com/renovatebot/renovate/blob/0b287c763d07ef42ff17cd8186fdc6faffbeb05a/lib/config/definitions.ts#L668 (these are ignored even if you have no presets)
- Here is the extended list from `:ignoreModulesAndTests`: https://github.com/renovatebot/renovate/blob/0b287c763d07ef42ff17cd8186fdc6faffbeb05a/lib/config/presets/internal/default.ts#L39-L47

**Comment by kalimerre** [comment]
Hello,
I can confirm that ignorePresets seems to be ignored .. 
This is the config we're using
```
         "extends": ["config:base"],
         "ignorePresets": [":prHourlyLimit2"],
```
We can see the following line
```DEBUG: Ignoring preset :prHourlyLimit2 in [config:base]```

Neverthless when Renovate starts the process to create branches it doesn't create anything because he considers that the prHourlyLimit is reached and therefore the prsRemaining & branchesRemaining is set at 0.

```
DEBUG: Calculating hourly PRs remaining (repository=organisation.name/dependabot-test)
DEBUG: currentHourStart=2021-06-01T08:00:00.000+00:00 (repository=organisation.name/dependabot-test)
DEBUG: PR hourly limit remaining: 0 (repository=organisation.name/dependabot-test)
DEBUG: Calculating prConcurrentLimit (20) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/package1-1.x) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/package1-1.x, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/iban-0.x) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/iban-0.x, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/fontsource-monorepo) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/fontsource-monorepo, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/vue-monorepo) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/vue-monorepo, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: 0 PRs are currently open (repository=organisation.name/dependabot-test)
DEBUG: PR concurrent limit remaining: 20 (repository=organisation.name/dependabot-test)
DEBUG: Calculated maximum PRs remaining this run (repository=organisation.name/dependabot-test)
       "prsRemaining": 0
DEBUG: PullRequests limit = 0 (repository=organisation.name/dependabot-test)
DEBUG: Calculating hourly PRs remaining (repository=organisation.name/dependabot-test)
DEBUG: currentHourStart=2021-06-01T08:00:00.000+00:00 (repository=organisation.name/dependabot-test)
DEBUG: PR hourly limit remaining: 0 (repository=organisation.name/dependabot-test)
DEBUG: Calculating branchConcurrentLimit (20) (repository=organisation.name/dependabot-test)
DEBUG: 0 already existing branches found:  (repository=organisation.name/dependabot-test)
DEBUG: Branch concurrent limit remaining: 20 (repository=organisation.name/dependabot-test)
DEBUG: Calculated maximum branches remaining this run (repository=organisation.name/dependabot-test)
       "branchesRemaining": 0
DEBUG: Branches limit = 0 (repository=organisation.name/dependabot-test)
```

On renovate version 24 the current configuration is working fine and is giving me the following result
```
DEBUG: Calculating prConcurrentLimit (20) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/package1-1.x) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/package1-1.x, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/fontsource-material-icons-4.x) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/fontsource-material-icons-4.x, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/fontsource-roboto-4.x) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/fontsource-roboto-4.x, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/iban-0.x) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/iban-0.x, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: getBranchPr(renovate/vue-monorepo) (repository=organisation.name/dependabot-test)
DEBUG: findPr(renovate/vue-monorepo, undefined, open) (repository=organisation.name/dependabot-test)
DEBUG: 0 PRs are currently open (repository=organisation.name/dependabot-test)
DEBUG: PR concurrent limit remaining: 20 (repository=organisation.name/dependabot-test)
DEBUG: Calculated maximum PRs remaining this run (repository=organisation.name/dependabot-test)
       "prsRemaining": 20
DEBUG: PullRequests limit = 20 (repository=organisation.name/dependabot-test)
DEBUG: Calculating branchConcurrentLimit (20) (repository=organisation.name/dependabot-test)
DEBUG: 2 already existing branches found: renovate/iban-0.x,renovate/vue-monorepo (repository=organisation.name/dependabot-test)
DEBUG: Branch concurrent limit remaining: 18 (repository=organisation.name/dependabot-test)
DEBUG: Calculated maximum branches remaining this run (repository=organisation.name/dependabot-test)
       "branchesRemaining": 18
DEBUG: Branches limit = 18 (repository=organisation.name/dependabot-test)
```

**Comment by kalimerre** [comment]
Hello @rarkins 
Are my debug logs enough to confirm the issue ? Is there something I am doing wrong here which could explain why prHourlyLimit2 is not taken into ignorePresets and it applies ?

**Comment by rarkins** [comment]
> Are my debug logs enough to confirm the issue ? 

No, unfortunately not, please see https://github.com/renovatebot/renovate/issues/10161#issuecomment-848556946

**Comment by kalimerre** [comment]
Unfortunately I can't provide a repo as it's on a private gitlab self hosted instance but I could give you the content of my config file
```
module.exports = {
    platform: 'gitlab',
    labels: ['renovate'],
    rebaseWhen: 'behind-base-branch',
    automerge: false,
    automergeType: 'branch',
    semanticCommits: 'enabled',
    stabilityDays: 3,
    prCreation: 'not-pending',
    major: {
        automerge: false,
        addLabels: ['major']
    },
    minor: {
        addLabels: ['minor']
    },
    patch: {
        addLabels: ['patch']
    },
    extends: [
        'config:base'
        //,":preserveSemverRanges"
        //,":pinAllExceptPeerDependencies"
    ],
    "ignorePresets": [":prHourlyLimit2"],
    // supportPolicy: ['lts_latest'],
    vulnerabilityAlerts: {
        "labels": ["security"],
    },
    commitMessagePrefix: "[dependency scanning]"
};
```
I'm just wondering why on Renovate v24 I don't have any prHourlyLimit and why on Renovate v25 there is some according to the logs. Don't you have any ideas ? 

The ignorePresets is used like described in the documentation : https://docs.renovatebot.com/configuration-options/#ignorepresets

**Comment by rarkins** [comment]
My recommendations:

1. Don't put presets/ignorePresets in your backend config and instead have them in repository config (e.g. `renovate.json`)
2. If there's a sub-preset you don't like, remove `config:base` and replace it with the ones you do want from https://docs.renovatebot.com/presets-config/#configbase

I will close this issue now due to lack of reproduction. We don't work on bugs we can't reproduce unless they're service impacting, so if we can't work on it then we don't leave them open.

**Comment by dannyyy** [comment]
I don't see any reason to close this bug report. The behavior is 100% reproducible and backed with appropriate config files and logs. And it's breaking from v24 to v25.

If `ignorePresets` shouldn't be used anymore, then please update your docs. Just leaving it there while it's broken seems to be misleading and bad practice.

I understand your action @rarkins to close this issue due to laziness to fix and not because of lacking any reproducibility.
If you close this again, I feel compelled to open a new issue with the same content as long as it exists. If you think the bug doesn't deserve to be treated appropriately, then leave this issue open for transparency that other users can find the issue and know there won't be a fix even there's this bug.

**Comment by rarkins** [comment]
I have explained our policy towards bug report reproducibility both here and in the linked docs. Wilful disregarding of this repository's policies or maintainers will result in being blocked from the renovatebot org.

**Comment by kalimerre** [comment]
Hey,

I can confirm that ignorePresets is not passed from a backend config to a repository config but only the extends, that's why the ignorePresets was not taken in each repository (@rarkins maybe it could be more precise in the doc ?).
So my solution was to add the following rule inside the backend config of extends to be able to ignore the prHourlyLimit (and also include the prCreation to not pending)

```
    extends: [
        'config:base',
        ':prHourlyLimitNone',
        ':prNotPending'
    ],
```

**Comment by rarkins** [comment]
If anyone can provide precise reproduction instructions according to the earlier-provided instructions then we can treat it as a bug and fix it instead of document it, because right now I don't know exactly what's going on or going wrong. I suggest picking a more easily demonstrable preset from `config:base` to ignore, such as `group:monorepos` because you can repeat it over and over.
