### ISSUE TITLE
Python: support PEP621

### ISSUE THREAD

**Issue by wwuck** [renovatebot/renovate#10181]
This is a feature request for supporting [PEP621](https://www.python.org/dev/peps/pep-0621/#dependencies-optional-dependencies) with `pyproject.toml`.

**Comment by HonkingGoose** [comment]
Hi @wwuck,

Please copy/paste this issue template into your post, and fill it out in full: https://raw.githubusercontent.com/renovatebot/renovate/main/.github/ISSUE_TEMPLATE/feature_request.md.

**Comment by rarkins** [comment]
Easier if you recreate a new issue while selecting the feature request template. I'll delete this one.
