### ISSUE TITLE
`status`/`triage` label via GH Action, `type:` via GitHub template

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10192]
We could maybe use an Action to apply triage/status labels to new Issues and only apply `type:` labels automatically by GitHub, that way you only have to change one label and not 3 when you are creating issues? Could help for all types of issues, not just refactor

_Originally posted by @rarkins in https://github.com/renovatebot/renovate/issues/10037#issuecomment-843895223_

**Comment by HonkingGoose** [comment]
I've rescued this comment from the previous issue, as that issue is about to get closed. 😉

**Comment by HonkingGoose** [comment]
I found a action that we could use to add/remove labels: `andymckay/labeler`. It's made by a GitHub Staff member.

It looks like it would do most of what we want: adding/removing labels on `issues` and/or `pull_request` events.
There's a open issue that requests support to remove all labels.

The README of the action is easy to understand, and the project seems to be stable enough for production use.
The repository has Dependabot enabled for security updates (there's a Dependabot security PR for `lodash` that's not merged yet).

Link to action repository: https://github.com/andymckay/labeler

I'll wait for your review on the safety/suitability of this action before proceeding.

**Comment by rarkins** [comment]
It doesn't seem to support the sophistication we need. Eg we want to "assign triage priority if none set" and "assign requirements status if none set"
