### ISSUE TITLE
Use better monorepo names in `monorepo.ts`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10210]
**What would you like Renovate to be able to do?**

I made a PR to add a new monorepo to the list, and saw that @viceice changed the name of the repo from `fontsource` -> `Fontsource`. But other names in this list use lowercase, so we're not consistent with capitalization of the mono repo names.

I'd like to use proper names and make things consistent again, but that's a potentially breaking change. 😄 

**Did you already have any implementation ideas?**

I'd like some feedback from the Renovate team on what the proper names are, and if we want this change at all. 😄 

If I know what we want, and if we want it, I'll then make a draft PR with the `breaking` label.

**Comment by HonkingGoose** [comment]
> We should check the spelling on target repos

Agree, the spelling should be correct at least. 😄 

> Some monorepos are correct in lowercase.

How do we choose between lowercase and Capitalized name? Do we look at how the repository capitalizes their "brand name", or how it's used on their website?

---

@rarkins What do you think of this idea? Do you have input/ideas/wishes?

**Comment by viceice** [comment]
I mostly take their "brand name".

* [`remark`](https://github.com/remarkjs/remark)
* [`System.IO.Abstractions`](https://github.com/System-IO-Abstractions/System.IO.Abstractions)

https://github.com/renovatebot/renovate/blob/3a1980811c335edaaee8814f9b54fd34851a5ee5/lib/config/presets/internal/group.ts#L116-L116

Maybe it's better to only use lowercase? But for sure we should force some consistency.

**Comment by viceice** [comment]
@rarkins  This rule is missing the group name?
https://github.com/renovatebot/renovate/blob/3a1980811c335edaaee8814f9b54fd34851a5ee5/lib/config/presets/internal/group.ts#L129-L138

So here we use the monorepo name as preset name, so we should go to lowercase without spaces.
https://github.com/renovatebot/renovate/blob/3a1980811c335edaaee8814f9b54fd34851a5ee5/lib/config/presets/internal/group.ts#L581-L591

**Comment by HonkingGoose** [comment]
Hi @rarkins, can you provide some feedback on the things discussed above?

**Comment by rarkins** [comment]
I prefer lower case without spaces where possible

**Comment by HonkingGoose** [comment]
@rarkins Shall I make a PR that checks the spelling and uses lowercase throughout? Any exceptions to the rule can then be changed in the PR by you. 😄

**Comment by rarkins** [comment]
I don't think we need to automate this one, unless @viceice thinks so

**Comment by HonkingGoose** [comment]
> I don't think we need to automate this one, unless @viceice thinks so

Oh maybe I'm confusing things here by talking about exceptions to rules. I'm not writing code to automate this change. 😉 

I'm thinking of manually adjusting the monorepo names so that they all use "lowercase without spaces".

Did you mean that you don't really care about the naming?

**Comment by rarkins** [comment]
Changing to lower-case is OK, but branch names will change unless the spaces are replaced by hyphens `-`, and we'd like to avoid that unnecessarily.

**Comment by HonkingGoose** [comment]
We fixed the monorepo names on the `v26` version of Renovate, so this issue can be closed.

Related PRs:

- https://github.com/renovatebot/renovate/pull/10243
- https://github.com/renovatebot/renovate/pull/11319
