### ISSUE TITLE
[Python] Version range narrows when using `~` (tilde)

### ISSUE THREAD

**Issue by ofir123** [renovatebot/renovate#10268]
**How are you running Renovate?**

- [X] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

**Describe the bug**

We've started using `~=` ranges in our `setup.cfg` files, in order to stick to minor updates in some of our repos.
Renovate identifies these, but when it opens a PR, it narrows our range by adding a patch version. For example:

![image](https://user-images.githubusercontent.com/4647811/120368214-ce536700-c2df-11eb-8dbd-0a42423f5928.png)

![image](https://user-images.githubusercontent.com/4647811/120383477-ea143880-c2f2-11eb-8810-d6e4ce41f50c.png)

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

https://github.com/ofir123/renovate-bug-10268-reproduce

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [X] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

We have tried using two different configurations, and it happened with both:

```
"packageRules": [
    {
      "languages": [
        "python"
      ],
      "updateTypes": [
        "patch"
      ],
      "groupName": "all non-patch dependencies",
      "groupSlug": "all-major-minor",
      "enabled": false
    }
  ],
```

```
  "packageRules": [
    {
      "languages": [
        "python"
      ],
      "updateTypes": [
        "major",
        "minor"
      ],
      "groupName": "all non-patch dependencies",
      "groupSlug": "all-major-minor"
    }
  ],
```

**Comment by ofir123** [comment]
Hi @rarkins ,
I've created a minimal reproduction per your request:
https://github.com/ofir123/renovate-bug-10268-reproduce

**Comment by rarkins** [comment]
@ofir123 the reproduction repo demonstrates the expected behavior when you configure `rangeStrategy=bump`. It will bump the range to be greater than or equal to upgraded version, as you're seeing:

![image](https://user-images.githubusercontent.com/6311784/120436276-03fb5d00-c37f-11eb-8c7c-12d1a72d8700.png)

Another way of putting it, `bump` pretty much always "narrows" the range. If you were to have your range like `~=7.1.0` and leave `rangeStrategy=replace` then you'd see PRs for `~=7.2.0` and `~=8.0.0`.
