### ISSUE TITLE
No docker.io/renovate/node releases found

### ISSUE THREAD

**Issue by amimas** [renovatebot/renovate#10286]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.31.12

**Describe the bug**

Renovate bot exits with following error:

```
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "9UK5inKlx",
           "repository": "project-group/renovate-bot",
           "branch": "renovate/pin-dependencies",
           "msg": "No docker.io/renovate/node releases found"
         },
         {
           "name": "renovate",
           "level": 50,
           "logContext": "9UK5inKlx",
           "repository": "project-group/renovate-bot",
           "branch": "renovate/renovate-25.x",
           "msg": "No docker.io/renovate/node releases found"
         }
       ]
```

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
{
    "name": "renovate",
    "hostname": "runner-3cmumr3a-project-201-concurrent-0",
    "pid": 113,
    "level": 30,
    "logContext": "9UK5inKlx",
    "loggerErrors": [
        {
            "name": "renovate",
            "level": 50,
            "logContext": "9UK5inKlx",
            "repository": "***/renovate-bot",
            "branch": "renovate/pin-dependencies",
            "msg": "No docker.io/renovate/node releases found"
        },
        {
            "name": "renovate",
            "level": 50,
            "logContext": "9UK5inKlx",
            "repository": "***/renovate-bot",
            "branch": "renovate/renovate-25.x",
            "msg": "No docker.io/renovate/node releases found"
        }
    ],
    "msg": "Renovate is exiting with a non-zero code due to the following logged errors",
    "time": "2021-06-01T21:56:55.654Z",
    "v": 0
}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

The above error started appearing as of yesterday. There was no change to the configurations and the bot is processing other repos successfully.  Other repositories (non nodejs based project) are being scanned and processed successfully.

I'm also encountering 404 Not Found error when I try to browse the `renovate/node` docker images in public docker registry. It seems the image no longer exists.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16211767/120493939-60637a00-c389-11eb-9a61-289f7855cc36.png">

**Comment by rarkins** [comment]
https://hub.docker.com/repository/docker/renovate/node/tags?page=1&ordering=last_updated
