### ISSUE TITLE
Regexmanager rejects valid registry urls 

### ISSUE THREAD

**Issue by henrysachs** [renovatebot/renovate#10304]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: latest

**Describe the bug**

I have the following regex to match a docker image:

```
[iI]mage: \\{\\s.*?repository:\\s*\\'(?<registryUrl>.*?)\\/(?<depName>.*?)\\',\\s.*?tag: \\'(?<currentValue>.*?)\\'
```

This is a sample line 

```
              image: {
                repository: 'quay-docker-remote.artifactory.internal.host.redacted.de/prometheus-operator/prometheus-operator',
                tag: 'v0.46.0',
              },
```

this matched my host: quay-docker-remote.artifactory.internal.host.redacted.de as registry url but renovate rejects this url.

**Relevant debug logs**
```
 WARN: Invalid regex manager registryUrl (repository=seec-mop/mop-base/renovate-test-repo)
       "value": "quay-docker-remote.artifactory.internal.host.redacted.de"
```

**Have you created a minimal reproduction repository?**

no This is kinda hard because i think because of the amount of subdomains included the url is rejected

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by rarkins** [comment]
You've captured a hostname, and it's not a valid url. Keep it all as part of depName.
