### ISSUE TITLE
Enable GitHub automerge functionality if allowed

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#10309]
**What would you like Renovate to be able to do?**

When Renovate automerging, set github automerge to true if it's enabled/allowed for the repository.

**Did you already have any implementation ideas?**

Apparently it's possible to do via the GraphQL API and not REST, using `enablePullRequestAutoMerge`

**Comment by rarkins** [comment]
Should it be opt-in or at least configurable though?

**Comment by HonkingGoose** [comment]
> Should it be opt-in or at least configurable though?

Renovate bot has a lot of toggles/config options, and it can be confusing to figure out where the bot behavior is coming from. Do we _need_ the end user to have configuration for this?

I think it will be easier to deal with supporting automerge if we know that there's just **one way** to automerge on GitHub. Having just **one way** to do things also makes it easier for end-users to learn/reason about the bot behavior from the docs.

---

Would this change also make using automerge with branch protection rules easier, or do you still need a second bot to "approve" the PR with this feature?

**Comment by rarkins** [comment]
> Renovate bot has a lot of toggles/config options, and it can be confusing to figure out where the bot behavior is coming from.

Users mostly get confused when they start *changing* things. They change things because Renovate's sophisticated features are necessary or at least welcome by most. Because they get *confused* by advanced features does not mean they'd prefer the advanced features didn't exist.

> Do we _need_ the end user to have configuration for this?

No if both these conditions are met:
- 100% of users would be happy with implicitly enabling GitHub's native automerge
- It never produces undesirable behavior that users would need a way around

But if the answer is that some users want Renovate's automerge only or that there are some edge cases where people need the ability to disable it, then we need it configurable.
 
> Would this change also make using automerge with branch protection rules easier, or do you still need a second bot to "approve" the PR with this feature?

No, you'd still need the approve bot if you have mandatory approvals on PRs. But it would make thigns much *faster* (e.g. might enable one automerged branch per every 10-12 minutes instead of ever 1-2 hours at best).

**Comment by rarkins** [comment]
I think this might be the third platform which we support a native automerge function though - after GitLab and Azure DevOps - so we should look into whether we can combine them into a generic option.

**Comment by HonkingGoose** [comment]
> Users mostly get confused when they start _changing_ things. They change things because Renovate's sophisticated features are necessary or at least welcome by most. Because they get _confused_ by advanced features does not mean they'd prefer the advanced features didn't exist.

Maybe having the advanced features is not the root problem, but that people apply parts of their config in a bad/non-sensical way. It can be hard to create your own custom config based on the docs alone. What if we had some explicit "best practices" or "recommended way" to set things up, complete with a "drag/drop" config preset?

Say we created a "full-fat" preset config with our recommendations for GitHub-native-automerge, we could then have a document like this:

1. Go to GitHub repo, configure branch protection like this, turn on GitHub automerge, etc.
2. Extend `config:basic-github-automerge`
3. Enjoy automerge on GitHub with Renovate bot

And for somebody who uses branch protection with required PR reviews, we could create another `config:github-automerge-required-reviews` preset, with a separate set of instructions.

I don't know if this idea is something you like. I know we have instructions on automerge and presets, so maybe it's just a case of creating a good simple document that puts all relevant information in an easy to read format?

Reference current docs:

- https://docs.renovatebot.com/automerge-configuration/
- https://docs.renovatebot.com/presets-config/

---

> > Would this change also make using automerge with branch protection rules easier, or do you still need a second bot to "approve" the PR with this feature?
> 
> No, you'd still need the approve bot if you have mandatory approvals on PRs. But it would make thigns much _faster_ (e.g. might enable one automerged branch per every 10-12 minutes instead of ever 1-2 hours at best).

That would speed up our Renovate PR merges on our repository a lot! Wow!

**Comment by travi** [comment]
i've been meaning to follow up on https://github.com/renovatebot/app-support/issues/39 being archived, but it seems more appropriate to mention it here since this seems like a great solution to that need.

**Comment by travi** [comment]
> No if both these conditions are met:
>
> * 100% of users would be happy with implicitly enabling GitHub's native automerge
> * It never produces undesirable behavior that users would need a way around

does the native automerge work when a PR is not involved (the branch-merge scenario)? i think it would be fine to fall back to renovate's automerge in that scenario, but mention it since it is another variable in the equation that could increase confusion around a configuration item, if added. 

i'm in the camp of removing the delay before merging being a good thing, so i may be biased, but my vote would be that enabling automerge in my renovate config would always result in using the native automerge, but recognizing that there may be some cases where that is not possible and the renovate feature is used instead.

**Comment by rarkins** [comment]
Branch merging would still need to be done directly by Renovate.

**Comment by rarkins** [comment]
Duplicate of #8386
