### ISSUE TITLE
Support for Bearer token when connecting to Docker registry

### ISSUE THREAD

**Issue by nielsbasjes** [renovatebot/renovate#10317]
**What would you like Renovate to be able to do?**

I would like to be able to directly configure a Bearer token for authenticating against a docker registry because the registry I have only support this way of authenticating.

**Long version: The context**
I have the situation that a private Gitlab is running in the Google cloud and is using the Google Container Registry (GCR) for the internal docker images.

I have extended the renovate docker image to include the google cloud sdk to facilitate authentication.
At this point running `gcloud auth print-access-token` prints the Bearer token needed to connect.

Simply put; this works (when I put in a real project and image name):
```bash
curl -i --header "Authorization: Bearer $(gcloud auth print-access-token)"  https://eu.gcr.io/v2/projectname/dockerimagename/tags/list 
```

What I did as an experiment in gitlabci is to have this run just before starting renovate
```yaml
  script:
    - 'echo "module.exports = { secrets: { GOOGLE_ACCESS_TOKEN: ''"$(gcloud auth print-access-token)"'' , }, };" > config.js'
    - renovate
```
and in the renovate.json do this fragment
```json
"hostRules": [{
  "matchHost": "eu.gcr.io",
  "token": "{{ secrets.GOOGLE_ACCESS_TOKEN }}",
  "authType": "Bearer"
}],
```
Although this does seem to load the intended values; as far as I can see they are simply not used by the docker component.
I get a `Datasource unauthorized` when it tries to fetch the tags,

**Did you already have any implementation ideas?**

I think (have not tried) something as simple as this should do it:
```diff
diff --git a/lib/datasource/docker/common.ts b/lib/datasource/docker/common.ts
index 14d9d1468..9370e9eb4 100644
--- a/lib/datasource/docker/common.ts
+++ b/lib/datasource/docker/common.ts
@@ -81,6 +81,9 @@ export async function getAuthHeaders(
         'base64'
       );
       opts.headers = { authorization: `Basic ${auth}` };
+    } else if (opts.token && opts.authType) {
+      opts.headers = { authorization: `${opts.authType} ${opts.token}` };
+      return opts.headers;
     }
     delete opts.username;
     delete opts.password;
```

Note: I spotted this typo while looking through the code:
```diff
diff --git a/lib/datasource/docker/types.ts b/lib/datasource/docker/types.ts
index a5a2834a8..72f45fd37 100644
--- a/lib/datasource/docker/types.ts
+++ b/lib/datasource/docker/types.ts
@@ -3,7 +3,7 @@
  * https://docs.docker.com/registry/spec/manifest-v2-2/#media-types
  */
 export enum MediaType {
-  manifestV1 = 'pplication/vnd.docker.distribution.manifest.v1+json',
+  manifestV1 = 'application/vnd.docker.distribution.manifest.v1+json',
   manifestV2 = 'application/vnd.docker.distribution.manifest.v2+json',
   manifestListV2 = 'application/vnd.docker.distribution.manifest.list.v2+json',
 }
```

**Comment by HonkingGoose** [comment]
@nielsbasjes Did you know that you can use syntax highlighting in your codeblocks? Put the programming language/file type/program name directly after the 3 backticks (don't add whitespace!).

```markdown
```diff
```

For example, you can highlight your `diff` output:

```diff
diff --git a/lib/datasource/docker/types.ts b/lib/datasource/docker/types.ts
index a5a2834a8..72f45fd37 100644
--- a/lib/datasource/docker/types.ts
+++ b/lib/datasource/docker/types.ts
@@ -3,7 +3,7 @@
  * https://docs.docker.com/registry/spec/manifest-v2-2/#media-types
  */
 export enum MediaType {
-  manifestV1 = 'pplication/vnd.docker.distribution.manifest.v1+json',
+  manifestV1 = 'application/vnd.docker.distribution.manifest.v1+json',
   manifestV2 = 'application/vnd.docker.distribution.manifest.v2+json',
   manifestListV2 = 'application/vnd.docker.distribution.manifest.list.v2+json',
 }
```

Read the [GitHub docs, Creating and highlighting code blocks, syntax highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) to learn more.

**Comment by HonkingGoose** [comment]
By the way the diff really looks like a typo on our end, I'm making a PR to fix the typo now.

**Comment by nielsbasjes** [comment]
I didn't know the syntax highlighting. Thanks for explaining.

What do you think of my feature request of support for a Bearer token?

Thanks for fixing the typo.

**Comment by HonkingGoose** [comment]
> I didn't know the syntax highlighting. Thanks for explaining.

You're welcome! ❤️ 

> What do you think of my feature request of support for a Bearer token?

I don't know enough about this to decide, you'll have to wait for the other members of the Renovate team to give their input. 😉

**Comment by rarkins** [comment]
Seems like a good idea

**Comment by nielsbasjes** [comment]
Has been implemented and released.
