### ISSUE TITLE
Replace `nock` with `http test utils`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10315]
**What would you like Renovate to be able to do?**

Replace `nock` with `http test utils` to prevent memory issues with the tests.

> FYI
> ![image](https://user-images.githubusercontent.com/6311784/120839909-d7576900-c569-11eb-8af3-e11f4ecb4cba.png)

Based on discussion between @rarkins and @viceice in #10313.

**Did you already have any implementation ideas?**

Refactor so that only `http test utils` is used.

**Comment by HonkingGoose** [comment]
Based on discussion between @rarkins and @viceice in #10313.

**Comment by viceice** [comment]
fixed in #10451
