### ISSUE TITLE
[Python] Version range narrows when using `~` (tilde)

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#10354]
### Discussed in https://github.com/renovatebot/renovate/discussions/10278

<div type='discussions-op-text'>

<sup>Originally posted by **ofir123** June  1, 2021</sup>

**How are you running Renovate?**

- [X] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

**Describe the bug**

We've started using `~=` ranges in our `setup.cfg` files, in order to stick to minor updates in some of our repos.
Renovate identifies these, but when it opens a PR, it narrows our range by adding a patch version. For example:

![image](https://user-images.githubusercontent.com/4647811/120368214-ce536700-c2df-11eb-8dbd-0a42423f5928.png)

![image](https://user-images.githubusercontent.com/4647811/120383477-ea143880-c2f2-11eb-8810-d6e4ce41f50c.png)

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

https://github.com/ofir123/renovate-bug-10268-reproduce

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [X] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

We have tried using two different configurations, and it happened with both:

```
"packageRules": [
    {
      "languages": [
        "python"
      ],
      "updateTypes": [
        "patch"
      ],
      "groupName": "all non-patch dependencies",
      "groupSlug": "all-major-minor",
      "enabled": false
    }
  ],
```

```
  "packageRules": [
    {
      "languages": [
        "python"
      ],
      "updateTypes": [
        "major",
        "minor"
      ],
      "groupName": "all non-patch dependencies",
      "groupSlug": "all-major-minor"
    }
  ],
```</div>

**Comment by hasanwhitesource** [comment]
I think the bug in this case is here where we go and straight away return the highest value from the releases https://github.com/renovatebot/renovate/blob/b0ce30b59a2c31a58b2f71972b89ad13832cde9f/lib/workers/repository/process/lookup/filter-checks.ts#L34

@rarkins would you kindly assign this to me and lets continue investigating a solution ?

**Comment by rarkins** [comment]
I think this was the problematic update:
![image](https://user-images.githubusercontent.com/6311784/155329961-6ef0569c-b095-43c3-89d7-908ead7c2b56.png)

It goes from a "major width" (>=7.1 <8) to a "minor release" (>=8.0.1 <8.1).

I think instead it should be updated to `~=8.0`

**Comment by hasanwhitesource** [comment]
@rarkins Do we handle or take into account when there is `~=`?
Shouldn't https://github.com/renovatebot/renovate/blob/c5d50f6da3502d9f2a8f805fb65292a98246a6bf/lib/workers/repository/process/lookup/filter.ts#L12 take care of filtering the incompatible new versions according to the versioning api ? 
I see here that we are always taking the higher versions : 
https://github.com/renovatebot/renovate/blob/c5d50f6da3502d9f2a8f805fb65292a98246a6bf/lib/workers/repository/process/lookup/filter.ts#L41

**Comment by rarkins** [comment]
@hasanwhitesource I think you're maybe misunderstanding the issue, or I don't understand your question.

The upgrade is valid. `8.0.1` does not satisfy `~=7.1`. Therefore it's correct to offer an upgrade. The problem is that the `newValue` should be `~=8.0` and not `~=8.0.1`. Does that make sense?
