### ISSUE TITLE
Clean up further references to master issue in code

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10416]
**What would you like Renovate to be able to do?**

I found some more references to master issue or variants of that name in our code.

```
masterissue
ensureMasterIssue()
masterissueapproval
master-issue
``` 

**Did you already have any implementation ideas?**

Replace "master issue" with a suitable variant of "dependency dashboard".

**Comment by HonkingGoose** [comment]
Quote from the changes section of PR #10426:

> ## Changes:
>
> Removes non-breaking references to `masterIssue` (and variants). The final references are related to migrations from `masterIssue` to `dependencyDashboard` (see [here](https://github.com/renovatebot/renovate/blob/39c079610e25aa3e6df57739a7e391f9e9d1eba2/lib/config/migration.ts#L77-L83)) and can't be removed without a breaking change.

So there's still a bit of work that can be done to remove the references, but we'd need a config migration PR for that, see issue #1502.

**Comment by rarkins** [comment]
I don't think we need to keep individual issues open for migrations though, so unless anyone objects or I'm misunderstanding then we can close this one now

**Comment by HonkingGoose** [comment]
The idea was to capture the "todo" in some way. But we could also put a TODO comment in the code next to the `masterIssue` to `dependencyDashboard` migration, and close the issue.

**Comment by rarkins** [comment]
I think all migrations are "TODO" implicitly

**Comment by HonkingGoose** [comment]
Let's close the issue then. 😀
