### ISSUE TITLE
Dry run should not request github token

### ISSUE THREAD

**Issue by strowk** [renovatebot/renovate#10441]
**How are you running Renovate?**

- [+ ] Self hosted

Please select which platform you are using:

Just running on my machine locally

Renovate version: 25.41.4

**Describe the bug**

When I run `renovate --dry-run` to define what would be the actions tool would take, I receive error 

```
You must configure a GitHub personal access token
```

There should not be a need for access token in dry run, since dry run mode is not supposed to make any authorized calls.

**Comment by rarkins** [comment]
More generally: we might need a token if it's private but it does not need to be a write-enabled token.

**Comment by rarkins** [comment]
Unfortunately GitHub's GraphQL isn't allowed unless you're authenticated, even for read-only data of a public repo. It errors with:

```
         "response": {
           "statusCode": 401,
           "statusMessage": "Unauthorized",
           "body": {
             "message": "This endpoint requires you to be authenticated.",
             "documentation_url": "https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql"
           },
```

Therefore closing this as it's not possible.

**Comment by strowk** [comment]
I am not using Github in any capacity with or without dry-run. Our code is stored on private Github. Why does renovate have to ask anything from Github at all?

I think this ticket is closed wrongly without enough investigation. @rarkins , please reopen

**Comment by rarkins** [comment]
It's the same APIs and same limitation regardless of GitHub.com or self hosted.

**Comment by strowk** [comment]
Why API is needed in the first place? I think dry-run could do without it.

**Comment by strowk** [comment]
Specifically I do not understand why tool is trying to connect to Github in the first place. 

Our code is not connected to Github. There is literally nothing that connects it to Github and no infromation that could be retrieved from there regarding it.
Code is stored in Bitbucket, dependencies are in NPM.

**Comment by rarkins** [comment]
Maybe you forgot to specify the platform

**Comment by rarkins** [comment]
If you run `renovate --dry-run` then it will default to GitHub.com.

You wrote earlier:

> Please select which platform you are using:

> Just running on my machine locally

You wrote just now:

> I expect it to not require even Bitbucket

You misunderstand how Renovate works. There is no concept of running locally and I should have asked you to be more specific originally when you provided an invalid answer to that question.

Finally, my previous comment of "regardless of GitHub.com or self hosted" was based on your original post where you said you are running GitHub not Bitbucket, before you edited it:

![image](https://user-images.githubusercontent.com/6311784/132958175-278f41d3-47fa-472c-8fe8-2f81085b5852.png)

This issue is closed, especially because it was based on a misunderstanding of Renovate to begin with.

**Comment by strowk** [comment]
You still did not explain why API is needed when dry-run is selected. I believe it should not be required, but you evade that question. Would you be so kind to answer?

**Comment by rarkins** [comment]
I directly answered you that "there is no concept of running locally". Renovate always runs against an API, it does not run against local files. There is a feature request #3609 open for this capability.
