### ISSUE TITLE
Renovate 'lock file maintenance' does not respect package-lock.json indent

### ISSUE THREAD

**Issue by babich-a** [renovatebot/renovate#10496]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [x] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: ...

**Describe the bug**

https://github.com/DevExpress/devextreme-cli/pull/340/files in this PR renovate update `package-lock.json` properly, but for `packages/devextreme-cli/package-lock.json` change indent from 2 to 8 spaces.

**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by rarkins** [comment]
Renovate performs lock file maintenance by first deleting the lock file and then running `npm install`, so `npm` has no existing file to "respect" when it runs. On the other hand I'm surprised to see it behaving differently between files - I'd expect that you'd see the same npm default on both files.
