### ISSUE TITLE
refactor: allow common base datasource classes

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#10532]
**What would you like Renovate to be able to do?**

Extract base classes out to separate directories.

In #10486 and #10531 I extracted a common abstract base class for Terraform and Git datasources. Currently this abstract class is in a file called `base.ts` adjacent to one of the datasources, but it should be extracted out to a separate directory, or a directory hierarchy.

**Did you already have any implementation ideas?**

Currently Renovate expects every directory under the `datasource` directory to be a concrete datasource, but this should be adjusted to allow common abstract datasource classes that allow common methods to be shared across several datasources easily.

**Comment by rarkins** [comment]
Before when we autogenerated datasources then we needed each for to be a real datasource, but is it still the case?

**Comment by JamieMagee** [comment]
It's not a requirement to build or run, but our test setup still expects this. I think this is a small change, but I'd prefer to finish #8647 first and come back to this afterwards.

**Comment by HonkingGoose** [comment]
I'll consider this `status:blocked` until issue #8647 is done then. 😉
