### ISSUE TITLE
Wrong Header for Credentials for Gitlab Maven Packageregistry

### ISSUE THREAD

**Issue by eifinger** [renovatebot/renovate#10536]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: 25.41.2

**Describe the bug**

Trying to look up private Maven packages in a self-hosted GitLab package registry leads to a HTTP 404. 
This is because the header is malformed.

---

Confirming the URL with curl by hand.

Following the [GitLab docs](https://docs.gitlab.com/ee/api/packages.html#within-a-group):

Trying to access the url `https://<private-gitlab>/api/v4/groups/40/-/packages/maven/<my-package>/maven-metadata.xml`

1. `curl --header "PRIVATE-TOKEN: <CORRECT_TOKEN>" https://<private-gitlab>/api/v4/groups/40/-/packages/maven/<my-package>/maven-metadata.xml` -> HTTP 200
1. `curl --header "PRIVATE-TOKEN: <INVALID_TOKEN>" https://<private-gitlab>/api/v4/groups/40/-/packages/maven/<my-package>/maven-metadata.xml` -> HTTP 401
1. `curl --header "Basic PRIVATE-TOKEN: <CORRECT_TOKEN>" https://<private-gitlab>/api/v4/groups/40/-/packages/maven/<my-package>/maven-metadata.xml` -> HTTP 404

---

The relevant config from renovate.json:

```json
"packageRules": [
        {
          "matchManagers": ["gradle-lite"],
          "registryUrls": [
            "https://repo.maven.apache.org/maven2",
            "https://<private-gitlab>/api/v4/groups/40/-/packages/maven"
          ]
        }
      ]
```

The relevant env variables:

```bash
MAVEN_<PRIVATE>_USERNAME: PRIVATE-TOKEN
MAVEN_<PRIVATE>_PASSWORD: $CORRECT_TOKEN
```

The header is set in the sourcecode with the prefix `Basic` [here](https://github.com/renovatebot/renovate/blob/d004ca5fa88842dc565aa14a8e664bc212c9c948/lib/util/http/auth.ts#L49)

It should be handled like the GitLab token [here](https://github.com/renovatebot/renovate/blob/d004ca5fa88842dc565aa14a8e664bc212c9c948/lib/util/http/auth.ts#L34)

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
...
"hostRules":[{"timeout":60000},{"hostType":"github","matchHost":"github.com","token":"***********"},{"hostType":"maven","matchHost":"<private-gitlab>","password":"***********","username":"PRIVATE-TOKEN"},{"hostType":"gitlab","matchHost":"<private-gitlab>","token":"***********"}]
...
{"name":"renovate","hostname":"runner-f8xxppxv-project-73-concurrent-0m2rwr","pid":14,"level":10,"logContext":"aJ06flW-j","repository":"<PRIVATE>","url":"https://<private-gitlab>/api/v4/groups/40/-/packages/maven/<my-package>/maven-metadata.xml","options":{"method":"get","hostType":"maven","hooks":{"beforeRedirect":[null]},"headers":{"user-agent":"https://github.com/renovatebot/renovate","authorization":"***********"},"timeout":60000},"msg":"got request","time":"2021-06-22T12:58:06.115Z","v":0}
{"name":"renovate","hostname":"runner-f8xxppxv-project-73-concurrent-0m2rwr","pid":14,"level":10,"logContext":"aJ06flW-j","repository":"<PRIVATE>","failedUrl":"https://<private-gitlab>/api/v4/groups/40/-/packages/maven/<my-package>/maven-metadata.xml","msg":"Url not found","time":"2021-06-22T12:58:06.372Z","v":0}
{"name":"renovate","hostname":"runner-f8xxppxv-project-73-concurrent-0m2rwr","pid":14,"level":20,"logContext":"aJ06flW-j","repository":"<PRIVATE>","msg":"Content is not found for Maven url: https://<private-gitlab>/api/v4/groups/40/-/packages/maven/<my-package>/maven-metadata.xml","time":"2021-06-22T12:58:06.372Z","v":0}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by eifinger** [comment]
It would be great if I don't have to supply the registryUrls and credentials at all since I am already using the platform `gitlab`.
But when I leave out the mentioned configuration it results in a HTTP 404 as well.

**Comment by viceice** [comment]
Did you tried: `curl --header "Authorization: Bearer <CORRECT_TOKEN>" https://<private-gitlab>/api/v4/groups/40/-/packages/maven/<my-package>/maven-metadata.xml`

**Comment by eifinger** [comment]
Thanks @viceice that worked.

Setting the env vars to `MAVEN_<PRIVATE>_TOKEN: $CORRECT_TOKEN`
