### ISSUE TITLE
Renaming issue

### ISSUE THREAD

**Issue by rajatagarwal** [renovatebot/renovate#10535]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [x] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.31.0

**Describe the bug**
Found a bug while upgrading the renovate version from 25.31.0 to 25.31.1

There is a refactoring issue while moving from 25.31.0 to 25.31.1, in this code: https://github.com/renovatebot/renovate/compare/25.31.0...25.31.1#diff-922b65de7866726a28ede70241c7f637072005518289aa3755070398bc5b1db7L112

Ideally, `repository` should be renamed to `dockerRepository` not `registryHost`. Due to this bug while upgrading the renovate version our build pipeline is failing and giving `Datasource 404` error along with `Failed to look up depdency ...` error. 

...

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by viceice** [comment]
fixed in #10537
