### ISSUE TITLE
"pip_setup/extract.ts" not setting PythonAlias properly to Python3

### ISSUE THREAD

**Issue by rajatagarwal** [renovatebot/renovate#10559]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [x] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: ...

**Describe the bug**

I am getting the `Failed to read setup.py` message with `python: command not found error`, as shown in the logs below. 

The problem seems to be in this function: https://github.com/renovatebot/renovate/blob/1b6ecd87c0b9e3e2a872d023857e2ed018c43e7c/lib/manager/pip_setup/extract.ts#L24

It checks for the following `pythonVersions: ['python', 'python3', 'python3.8', 'python3.9']`

In the logs, if you see it was able to find `Python 3.6.8` but it couldn't set the `pythonAlias` to `python3` because of this line where it checks for Python version greater than or equals to 3.7 only. https://github.com/renovatebot/renovate/blob/1b6ecd87c0b9e3e2a872d023857e2ed018c43e7c/lib/manager/pip_setup/extract.ts#L33

Hence it tries to execute `setup.py` file with `python` rather than `python3` and failed.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: Found a multistage build stage name (repository=<repo-name>)
DEBUG: Found a multistage build stage name (repository=<repo-name>)
DEBUG: Skipping alias COPY --from (repository=<repo-name>)
       "image": "compile-image"
DEBUG: pip_setup.extractPackageFile() (repository=<repo-name>)
DEBUG: Running python via global command (repository=<repo-name>)

DEBUG: Executing command (repository=<repo-name>)
       "command": "python --version"
DEBUG: python alias not found (repository=<repo-name>)

DEBUG: Executing command (repository=<repo-name>)
       "command": "python3 --version"
DEBUG: exec completed (repository=<repo-name>)
       "cmd": "python3 --version",
       "durationMs": 29,
       "stdout": "Python 3.6.8\n",
       "stderr": ""
       
DEBUG: Executing command (repository=<repo-name>)
       "command": "python3.8 --version"
DEBUG: python3.8 alias not found (repository=<repo-name>)

DEBUG: Executing command (repository=<repo-name>)
       "command": "python3.9 --version"
DEBUG: python3.9 alias not found (repository=<repo-name>)

DEBUG: python command (repository=<repo-name>)
       "cmd": "python",
       "args": [
         "\"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\"",
         "\"setup.py\""
       ]
DEBUG: Executing command (repository=<repo-name>)
       "command": "python \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\" \"setup.py\""
DEBUG: Failed to read setup.py file (repository=<repo-name>, packageFile=setup.py)
       "err": {
         "killed": false,
         "code": 127,
         "signal": null,
         "cmd": "python \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\" \"setup.py\"",
         "stdout": "",
         "stderr": "/bin/sh: python: command not found\n",
         "message": "Command failed: python \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\" \"setup.py\"\n/bin/sh: python: command not found\n",
         "stack": "Error: Command failed: python \"/tmp/renovate/cache/others/pip_setup/renovate-pip_setup-extract.py\" \"setup.py\"\n/bin/sh: python: command not found\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:467:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Socket.<anonymous> (internal/child_process.js:439:11)\n    at Socket.emit (events.js:315:20)\n    at Socket.EventEmitter.emit (domain.js:467:12)\n    at Pipe.<anonymous> (net.js:673:12)"
       },
       "content": "[content]"
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by viceice** [comment]
How are you running renovate? Our `pip_setup` manager requires python 3.7 which should be preinstalled in our official docker 
 image

ref #3397

**Comment by rajatagarwal** [comment]
`npm run renovate` and using renovate version `25.49.2`

**Comment by viceice** [comment]
> `npm run renovate` and using renovate version `25.49.2`

Can you extend this some more? If you are using github actions, i suggest to use our official github action

https://github.com/renovatebot/github-action
