### ISSUE TITLE
GitHub tasklists interfere with Dependency Dashboard

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10572]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: `25.49.5`

**Describe the bug**

GitHub just released a new beta feature, it's called tasklists.
It seems to detect that there are Markdown checkboxes, and offers to "convert to issue" on a checkbox item if you hover over it.

This also "works" on the Renovate Dashboard. If you hover over a item on the Dependency Dashboard you can click on "Convert to issue".

Steps to reproduce:

1. Create throwaway repo, because it will get messed up...
2. Put a small `package.json` file in it with some outdated dependencies.
3. Create `renovate.json` config with the dashboard enabled.
4. Go to dashboard issue
5. Hover over item with checkbox, notice there's a grey background now, go to the right of the container, and click on "convert to issue".
6. Edgecases galore!

There's seemingly no way to opt out that I can find right now, and if you mis-click, you're now stuck with a "tasklist" on your dependency dashboard.

I think the only way to get back to normal is to "nuke" the dashboard somehow.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

https://github.com/HonkingGoose/renovate-repro-10572

**Additional context**

Maybe we should ask the GitHub engineers for a way to opt-out on our Dependency Dashboard issues.
This will cause problems for a lot of Renovate users if they mis-click when doing things on the Dependency Dashboard.

GitHub has documentation on "tasklists", (it doesn't yet mention the convert to issue functionality): https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/about-task-lists

**Comment by rarkins** [comment]
I think you can simply close a dashboard and it will be recreated fresh on the next run? You only lose the comment history, but that's probably outdated

**Comment by HonkingGoose** [comment]
> I think you can simply close a dashboard and it will be recreated fresh on the next run?

I'll try that. 😄 Managed to mess up a production dashboard... 😄

**Comment by HonkingGoose** [comment]
> > I think you can simply close a dashboard and it will be recreated fresh on the next run?
> 
> I'll try that. 😄 Managed to mess up a production dashboard... 😄

Well Renovate re-opened the dashboard that was already there, instead of giving me a new issue. 😄 

I've opened a discussion on the GitHub Issue Feedback discussion forum to ask for a way to disable this behavior: https://github.com/github/feedback/discussions/4261

**Comment by rarkins** [comment]
Close and rename?

**Comment by HonkingGoose** [comment]
I've tried some things on the reproduction repository to see if I can break things, and so far Renovate keeps working as it should. 😄 

I was worried there was some edge-case when you miss-click on the dashboard and then try to force the update PR, or later merge a PR with a issue from the miss-click open.

What I tried:

1. Create issue from "convert to issue" miss-click on the Renovate dashboard,
2. Tick checkbox to get Renovate to create the corresponding PR right away.
3. Merge PR corresponding PR.
4. Issue created from miss-click stays open until manually closed. (I sorta-kinda expected it to get closed via some automagic link, but that's not the case... 😄 )

Also the Renovate Dashboard can self-heal by by renaming the issue and waiting until Renovate bot creates a replacement, or waiting until the next time Renovate bot updates the dashboard body text.

I guess I was overreacting a bit... sorry for the noise!

I don't think there's anything we can do on the Renovate side to disable this "convert to issue from checkbox" feature on our dashboards... I've already raised a discussion post on the GitHub side to ask for a way to turn this "feature" off.

Do you want to keep the issue around or do you want to close it?

**Comment by rarkins** [comment]
I think we can close unless it turns out to be more of a problem
