### ISSUE TITLE
Provide option to create separate PRs for multiple minor versions of a specific dependecy

### ISSUE THREAD

**Issue by karfau** [renovatebot/renovate#10629]
**What would you like Renovate to be able to do?**

For dependecies that do not stick to semver and/or tend to introduce breaking changes on minor releases, I would like that renovate creates a separate PR for each minor release, similar to what `:separateMultipleMajor` does. (I'm not sure right now if this is only availabe as a preset or also as an option inside `packageRulea` already.)

**Did you already have any implementation ideas?**

The name for the option could be `separateMultipleMinor`.

**Comment by HonkingGoose** [comment]
I don't think we can implement this feature with just a preset, as for as I understand, when we get a new patch level update, we clobber over the branch that contains the previous patch level update.

---

Maybe you can work around the issue for now by using the "Dependency Dashboard approval workflow".
The config below will:

- Enable `dependencyDashboard` for the repository
- Tell Renovate to only create a PR for the naughty package when you click on a checkbox in the Dependency Dashboard issue

```json
{
  "dependencyDashboard": true,
  "packageRules": [
    {
      "matchPackagePatterns": ["put-naughty-not-semver-following-package-here"],
      "dependencyDashboardApproval": true
    }
  ]
}
```

**Comment by karfau** [comment]
I just checked: [`separateMultipleMajor`](https://docs.renovatebot.com/configuration-options/#separatemultiplemajor) is also an option, not just a preset, so it can be applied to packageRules, right?

@HonkingGoose I think the workaround would not work, since it would still create a PR updating multiple minor versions in one go if they are available:

Assume the naughty package is at 4.3.x and the repo is at 4.0.x, so three times breaking changes are in our way. The PR created would still update to 4.3.x and not to 4.1.x, right?

**Comment by rarkins** [comment]
Implement as new option, the logic will need to be added in both the lookup "bucket" logic as well as on the branch naming logic, similar to how separateMinorPatch works

**Comment by karfau** [comment]
Regarding `separateMinorPatch`: I am of course intending to combine it with the new option. But I was thinking you might want to consider this option being active implicitly (or at least some behaviour of it is in place explicitly)?

I mean what would it mean to have `separateMinorPatch` set to `false` and `seperateMultipleMinor` set to `true`?
Should it still create patch level PRs for the current minor, before providing the PR for the next minor?

I guess this question can/should be answered the same way that it has been answered for `seperateMultipleMajor` and `separateMajorMinor`.

I tried to understand those combinations and I'm quite certain I might have missed something:
https://docs.google.com/spreadsheets/d/1KhN38sFGdc1NGbDUAfUwure1fMyndsTp0MQAEzt3IPU/edit?usp=sharing
Some combinations are really hard to imagine, how it is supposed to behave. Maybe `separateMinorPatch` implies `separateMajorMinor`, that would get rid of some of those weird combinations :wink: ?
We can extend the table with the new feature if that helps, but now that I realized how complex the topic already is (?) ...

**Comment by HonkingGoose** [comment]
> I just checked: [`separateMultipleMajor`](https://docs.renovatebot.com/configuration-options/#separatemultiplemajor) is also an option, not just a preset, so it can be applied to packageRules, right?

What I meant was that we need new code before any new preset can be made, because we're missing the necessary logic right now. 😉 

> @HonkingGoose I think the workaround would not work, since it would still create a PR updating multiple minor versions in one go if they are available:
> 
> Assume the naughty package is at 4.3.x and the repo is at 4.0.x, so three times breaking changes are in our way. The PR created would still update to 4.3.x and not to 4.1.x, right?

Yeah, it's a _partial_ workaround at best... the dashboard would still show the latest version of the naughty package, so you would still get an update proposal for `4.3.x`. At least with the approval workflow you can choose when you want to be bothered by the naughty package upgrade. 😄 

> Implement as new option, the logic will need to be added in both the lookup "bucket" logic as well as on the branch naming logic, similar to how separateMinorPatch works

That would be the proper fix. 😄 

> Man this is not simple to think about ...

I also get headaches thinking about all possible dependency things, so don't feel too bad! 😉 

I guess most people are happy with the current Renovate defaults, so I think we leave the defaults alone, but give the option with a preset/option to get separate updates for certain naughty packages. 😉

**Comment by HonkingGoose** [comment]
I found a related issue: https://github.com/renovatebot/renovate/issues/6576, that wants a new `separateMultiplePatch` option.

@rarkins Is this issue a duplicate of that one?

**Comment by karfau** [comment]
@HonkingGoose I fully agree that #6576 a duplicate, even though I was only requesting one of the options described there.

So I will continue the discussion there.
Since it will be harder to read it there and follow the thread from here and I don't want to copy our whole thread there, I will also leave my text here:

And the underlying "issue" with all those options is that it get's harder and harder to understand what should happen. So thinking about a different way of configuring and describing it (and most likely also implementing it) makes sense.
E.g. there could be one option for all of it, e.g. `separateVersions` in which you would define the lowest or multiple levels at which you want to receive PRs and whether you want to join multiple by setting it to values like `patchEach`, `patchMultiple` (or `patchJoined`?), `minorEach`, `minorMultiple`, `majorEach`, `majorMultiple`.
The way I imagine it, the current defaults would reflect this property to be set to `["minorMultiple", "majorMultiple"]` and only setting `separateMultipleMajor` to true would become `["minorMultiple", "majorEach"]`. Or maybe this way of thinking about the option name leads to something even more easy to understand, even if there is one option for each level (that can be set to `ignore`, `each`, `multiple`).

**Comment by viceice** [comment]
Duplicate of #6576
