### ISSUE TITLE
Remove composer memory limit

### ISSUE THREAD

**Issue by mikepsinn** [renovatebot/renovate#10624]
**What would you like Renovate to be able to do?**

I love renovate, but it doesn't work anymore because 
```
Command failed: docker run --rm --name=renovate_composer --label=renovate_child -v "/mnt/renovate/gh/mikepsinn/qm-api":"/mnt/renovate/gh/mikepsinn/qm-api" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w "/mnt/renovate/gh/mikepsinn/qm-api" docker.io/renovate/composer:1.10.22 bash -l -c "composer update doctrine/dbal --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader"
Loading composer repositories with package information
������������������������������������������������������                                                      ������������������������������������������������������Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 83886080 bytes) in phar:///usr/local/composer/1.10.22/bin/composer/src/Composer/DependencyResolver/RuleSet.php on line 90
```

**Did you already have any implementation ideas?**

Are you able to prefix some PHP arguments when you call your composer update command like:
`php -d memory_limit=-1 composer.phar ...`
or
`php composer.phar COMPOSER_MEMORY_LIMIT=-1 ...`
?

https://stackoverflow.com/questions/49212475/composer-require-runs-out-of-memory-php-fatal-error-allowed-memory-size-of-161

Thanks for all your great work! :D

**Comment by rarkins** [comment]
What happens if the limit is disabled (-1) and then it truly hits the limit? Presumably it could take down the entire Renovate process with it?

**Comment by HonkingGoose** [comment]
I found some prior discussion about removing the Composer memory limit over on this issue: https://github.com/renovatebot/renovate/issues/6295.

**Comment by mikepsinn** [comment]
@rarkins I would think the PHP process would crash, but that's what's already happening. 

I guess the worst-case scenario would be crashing the container so maybe it would crash renovate and prevent Renovate from creating a PR comment saying `PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted`?  

What is the maximum we could safely set [`COMPOSER_MEMORY_LIMIT`](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors)` to?

**Comment by rarkins** [comment]
In the hosted app we use 4GB RAM, of which some needs to be available for Renovate itself, naturally. This type of change would definitely need to be controlled by the Renovate bot admin and not by repos. And I think it can maybe be done already too using our custom env capability. 

How much RAM does your composer install need?

**Comment by HonkingGoose** [comment]
@mikepsinn I think we're waiting on a response for you on this question from the Renovate bot maintainer:

> How much RAM does your composer install need?

So I'm pinging you to see if that will get us moving again. 😉
