### ISSUE TITLE
Generic datasource

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#10622]
**What would you like Renovate to be able to do?**

Support the concept of a "generic" datasource, so that users can create an API matching its schema to massage unsupported datasources into something Renovate understands.

**Did you already have any implementation ideas?**

We take our existing "internal" datasource schema - i.e. the type definition for how datasources return results - and make that external/public in the form of a JSON schema potentially. Then users can e.g. scrape sources and publish them to a static website for Renovate to read.

Example:

Let's say we want to know the version of python supported by `pyenv`, and those are kept internal to their repo. So we create our own repo, called `pyenv-versions` and add a GitHub Action to run hourly and "scrape" the pyenv repo and generate a simple JSON file representing the versions, and then publish that to GitHub pages.

I can see two structures being supported:
1. One JSON file per package, so then you fetch `<registryUrl><lookupName>.json` and use the result directly
2. A single JSON file for all packages, so you fetch `<registryUrl>` and then use the result which exists inside the `lookupName` key in the JSON.

**Comment by rarkins** [comment]
@JamieMagee this was inspired by the vcpkg discussion and could open up some new possibilities for custom datasources without requiring much work from us or users.

**Comment by JamieMagee** [comment]
Yeah, I've been thinking that something like this might be the end goal of #8647. Once we abstract so much away, there'll be a lot less required to implement a new datasource.

**Comment by fgreinacher** [comment]
I like this a lot, see also https://github.com/renovatebot/renovate/issues/4674

**Comment by SirUli** [comment]
I've started to do something similar by faking a pypi registry for totally different software (some internal repositories). Didn't get far enough at the moment but i would definitely favor this approach. Looking forward to it!

**Comment by NargiT** [comment]
definitely something I will use, right now I forked the project and maintain a custom datasource in order to achieve this. it's very painful specially when upstream code is refactored.

**Comment by rarkins** [comment]
Adding a plugin architecture would extend our "public API" to areas which are today considered internal. Doing so would make it harder to refactor when we need to and ultimately slow us down for the 99%+ who don't need plugins. We are still evolving our internal interfaces regularly.

I think we'll do it some day, but for now the tradeoff isn't worth it.

**Comment by viceice** [comment]
@NargiT you can do something like our `internal-tools`[^1] action. It is using renovate from npm and adding versionings / datasource extensions. It's probably a lot easier to maintain for you instead to build the whole renovate 😉 


[^1]: https://github.com/renovatebot/internal-tools

**Comment by rarkins** [comment]
Related: https://github.com/flathub/flatpak-external-data-checker#json-checker

**Comment by reitzig** [comment]
Use Case: As-code config of $softwareA depends on version of $softwareB _that actually runs_. Ops would have to store that version of B in a digestable, maintainable format for Renovate to pick up and inject into the config of A (via magic comment).
