### ISSUE TITLE
Datasource gitlab-releases

### ISSUE THREAD

**Issue by andreabettich** [renovatebot/renovate#10645]
**What would you like Renovate to be able to do?**

Currently there is only the datasource gitlab-tags, which checks for new tags. But maybe not every tag should be a release which should get upped in other repositories.

**Did you already have any implementation ideas?**

It looks like that we can copy `github-releases` datasource and do a gitlab flavor of it.

I will try to do a PR myself.

**Comment by secustor** [comment]
Duplicate of https://github.com/renovatebot/renovate/issues/7534

**Comment by andreabettich** [comment]
Thanks and sorry. I searched but didn't see this issue.

**Comment by rarkins** [comment]
@andreabettich no problem at all! Hope you're not deterred from submitting a PR.. and yes I think it can be modelled on the GitHub releases datasource.

**Comment by HonkingGoose** [comment]
Duplicate of #7534
