### ISSUE TITLE
Setting rangeStrategy to bump doesn't update package.json

### ISSUE THREAD

**Issue by keeganwitt** [renovatebot/renovate#10663]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: 25.51.4

**Describe the bug**

Renovate had been run once on a repo, then it was decided we'd like Renovate to update the package.json in addition to the package-lock.json, so `"rangeStrategy": "bump"` was added at the root level of the config. But the MR didn't update the package.json file, only the package-lock.json file.  You can see from the debug statement, the `newValue` was _not_ updated.

Are we misunderstanding the intent of this configuration option?

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```json
{
    "depType": "devDependencies",
    "depName": "@types/node",
    "currentValue": "^15.6.1",
    "datasource": "npm",
    "prettyDepType": "devDependency",
    "lockedVersion": "15.12.2",
    "depIndex": 54,
    "updates": [
    {
        "bucket": "non-major",
        "newVersion": "15.12.5",
        "newValue": "^15.6.1",
        "releaseTimestamp": "2021-06-27T03:01:51.296Z",
        "newMajor": 15,
        "newMinor": 12,
        "updateType": "patch",
        "isRange": true,
        "isLockfileUpdate": true,
        "branchName": "renovate/node-15.x-lockfile"
    }
    ],
    "warnings": [],
    "versioning": "npm",
    "sourceUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped",
    "sourceDirectory": "types/node",
    "currentVersion": "15.12.2",
    "isSingleVersion": true,
    "fixedVersion": "15.12.2"
},
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by keeganwitt** [comment]
I didn't create a public repository where this could be reproduced, but I'd guess it should be pretty easy to reproduce if it'd be helpful. I just didn't want to spend the time on that if I was not understanding the config correctly or the issue was easy figure out already.

**Comment by keeganwitt** [comment]
I just discovered our default file has
```json
"npm": {
    "rangeStrategy": "update-lockfile",
    "depTypeList": [
        "dependencies",
        "devDependencies",
        "optionalDependencies",
        "peerDependencies"
    ]
}
```

Which may be the culprit. Although I also can't find `depTypeList` in the documentation.

**Comment by HonkingGoose** [comment]
> ~Although I also can't find `depTypeList` in the documentation.~
> Edit: discovered that that configuration is failing validation, `depTypeList` shouldn't be there.

That's because `depTypeList` is deprecated now. 😉 

We're thinking about migrating outdated Renovate configurations automatically, but this feature has not landed yet. So until then, you need to check the config file manually from time to time.

**Comment by keeganwitt** [comment]
Thanks, I figured that's what happened.

Confirmed this issue was because of our default config. Sorry for the noise.
