### ISSUE TITLE
New regex option: `matchPackageSuffixes`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10672]
**What would you like Renovate to be able to do?**

Say you get the following updates proposed by Renovate bot:

| Package | Type | Update | Change |
| --- | --- | --- | --- |
| node | final | major | `14-alpine -> 16-alpine` |
| node | final | major | `14.16-alpine` -> `16.3-alpine` |

And you want to make a new packageRule, so that major `-alpine` updates require Dashboard approval first.
Right now you have to figure out the regex to match the `-alpine` suffix yourself. And I'm bad at RegEx... 🙈 😄

I'd like an `matchPackageSuffixes` option, that's like the current `matchPackagePrefixes` option, but different.
That would make configuring the capture of the suffix even easier. 😄 

```json
{
  "packageRules": [
    {
      "matchPackageSuffixes": ["-alpine"],
      "matchDatasources": ["docker"],
      "matchUpdateTypes": ["major"],
      "dependencyDashboardApproval": true
    }
  ]
}
```

**Did you already have any implementation ideas?**

I'll let somebody competent with RegEx work on this. 😄

**Comment by viceice** [comment]
@HonkingGoose `-alpine` is not part of the package name it's part of current value, so your `matchPackageSuffixes` will never match.

It will match docker images like `abc-alpine` or `renovatebot/node-alpine` but not `renovatebot/node:12-alpine`

**Comment by rarkins** [comment]
`matchPackagePatterns` can be used instead. `matchPackagePrefixes` was added as a convenience because of how common it is to match on prefixes.
