### ISSUE TITLE
Incorrect diff link in PR summary table

### ISSUE THREAD

**Issue by AlCalzone** [renovatebot/renovate#10696]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [x] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: ...

**Describe the bug**

This update PR contains a diff link in the summary table
https://github.com/zwave-js/node-zwave-js/pull/2947#issue-682534242
The link text is correct, but the URL tries to compare v7.29.0 with itself instead of v7.28.0..v7.29.0
The same happens for other dependencies aswell

**Relevant debug logs**

Can't find eslint in the linked log

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by AlCalzone** [comment]
Not sure if the issue wasn't updated, but this is now fixed.

**Comment by rarkins** [comment]
I'm not aware of any changes made actually. Please let us know if you discover any problem again

**Comment by AlCalzone** [comment]
Will do

**Comment by rarkins** [comment]
Could be that certain types have the wrong link. Eg I noticed it looked like a "bump" rangeStrategy
