### ISSUE TITLE
`jestPlusTSJest` not combining `jest` and `ts-jest` major updates into single PR as expected

### ISSUE THREAD

**Issue by travi** [renovatebot/renovate#10702]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: ...

**Describe the bug**

based on the [addition of the `jestPlusTSJest` group and enabling it by default](https://github.com/renovatebot/renovate/pull/10596), my understanding is that updating `jest` and `ts-jest` from v26 to v27 should be handled in a single PR, assuming the project extends `config:base`. however, the two packages are being updated in separate PRs. 

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: branchifyUpgrades
DEBUG: Using group branchName template
DEBUG: Dependency jest is part of group jest monorepo
DEBUG: 2 flattened updates found: jest, ts-jest
DEBUG: Returning 2 branch(es)
DEBUG: Fetching changelog: https://github.com/facebook/jest (26.6.3 -> 27.0.6)
DEBUG: Fetching changelog: https://github.com/kulshekhar/ts-jest (26.5.6 -> 27.0.3)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "github-actions": [
      {
        "packageFile": ".github/workflows/node-ci.yml",
        "deps": [
          {
            "depName": "actions/checkout",
            "currentValue": "v2",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "pinDigests": false,
            "depIndex": 0,
            "warnings": [],
            "sourceUrl": "https://github.com/actions/checkout",
            "currentVersion": "v2",
            "fixedVersion": "v2",
            "updates": []
          },
          {
            "depName": "actions/setup-node",
            "currentValue": "v2",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "pinDigests": false,
            "depIndex": 1,
            "warnings": [],
            "sourceUrl": "https://github.com/actions/setup-node",
            "currentVersion": "v2",
            "fixedVersion": "v2",
            "updates": []
          },
          {
            "depName": "bahmutov/npm-install",
            "currentValue": "v1",
            "commitMessageTopic": "{{{depName}}} action",
            "datasource": "github-tags",
            "versioning": "docker",
            "depType": "action",
            "pinDigests": false,
            "depIndex": 2,
            "warnings": [],
            "sourceUrl": "https://github.com/bahmutov/npm-install",
            "currentVersion": "v1",
            "fixedVersion": "v1",
            "updates": []
          }
        ]
      }
    ],
    "npm": [
      {
        "packageFile": "package.json",
        "deps": [
          {
            "depType": "devDependencies",
            "depName": "jest",
            "currentValue": "26.6.3",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "26.6.3",
            "depIndex": 0,
            "warnings": [],
            "versioning": "npm",
            "sourceUrl": "https://github.com/facebook/jest",
            "homepage": "https://jestjs.io/",
            "currentVersion": "26.6.3",
            "isSingleVersion": true,
            "fixedVersion": "26.6.3",
            "updates": [
              {
                "bucket": "major",
                "newVersion": "27.0.6",
                "newValue": "27.0.6",
                "releaseTimestamp": "2021-06-28T17:06:18.626Z",
                "newMajor": 27,
                "newMinor": 0,
                "updateType": "major",
                "branchName": "renovate/major-jest-monorepo"
              }
            ]
          },
          {
            "depType": "devDependencies",
            "depName": "ts-jest",
            "currentValue": "26.5.6",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "26.5.6",
            "depIndex": 1,
            "warnings": [],
            "versioning": "npm",
            "sourceUrl": "https://github.com/kulshekhar/ts-jest",
            "homepage": "https://kulshekhar.github.io/ts-jest",
            "currentVersion": "26.5.6",
            "isSingleVersion": true,
            "fixedVersion": "26.5.6",
            "updates": [
              {
                "bucket": "major",
                "newVersion": "27.0.3",
                "newValue": "27.0.3",
                "releaseTimestamp": "2021-06-06T15:59:18.498Z",
                "newMajor": 27,
                "newMinor": 0,
                "updateType": "major",
                "branchName": "renovate/ts-jest-27.x"
              }
            ]
          }
        ],
        "packageJsonName": "@travi/jest-ts-reproduction",
        "packageFileVersion": "0.0.1",
        "packageJsonType": "library",
        "npmLock": "package-lock.json",
        "managerData": {},
        "skipInstalls": true,
        "constraints": {
          "npm": "<7"
        },
        "lockFiles": [
          "package-lock.json"
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 2 branches: renovate/major-jest-monorepo, renovate/ts-jest-27.x
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

reproduction repo: https://github.com/travi-test/jest-ts-reproduction/

jest PR: https://github.com/travi-test/jest-ts-reproduction/pull/2
ts-jest PR: https://github.com/travi-test/jest-ts-reproduction/pull/3

**Additional context**

see discussion: https://github.com/renovatebot/renovate/discussions/10698

**Comment by HonkingGoose** [comment]
Hi @travi thank you for your bug report!

> updating `jest` and `ts-jest` from v26 to v27 should be handled in a single PR, assuming the project extends `config:base`.

That's the intended behavior: group `major` versions of `jest` and `ts-jest` together, as they should be upgraded at the same time together. It seems something is going wrong here... 😞

I can't see the content at your reproduction repository link, clicking on your links leads to GitHub's 404 page. Is the repository visible to the public? Maybe it's still set to private?

**Comment by viceice** [comment]
@HonkingGoose i think the issue is that the new preset is not added to `base` preset automatically. 
That was why I told you in pr that we should enable this by default.
Maybe i wasn't clear enough and you thought this preset will enabled automatically via `base` preset

**Comment by HonkingGoose** [comment]
This is the config we ended up with at the end of my PR: https://github.com/renovatebot/renovate/pull/10596/files

**Comment by viceice** [comment]
🤔 so we need a proper reproduction.

**Comment by travi** [comment]
Sorry, looks like I did make the reproduction repo private initially :facepalm:. It is public now.

**Comment by travi** [comment]
Not sure if a specific change was made, but both repos that had separate PRs had the ones for `ts-jest` auto close today and `ts-jest` is now included in the PRs for for "jest monorepo". It seems to me like this is now resolved. Is anything else needed before closing this issue?

**Comment by rarkins** [comment]
Oh whoops.. I think the change just wasn't live in the app yet. We can close!

**Comment by HonkingGoose** [comment]
@travi Thank you for the reproduction repository. Now we know things are working as intended! 😄 

I hope you enjoy this new functionality on your production repositories! 😉

**Comment by travi** [comment]
> Oh whoops.. I think the change just wasn't live in the app yet.

no worries. appears to be all sorted now. i think i got confused by [this release notification](https://github.com/renovatebot/renovate/pull/10596#issuecomment-868951140). does that mean that making new changes live requires additional steps after a new version is released?

**Comment by viceice** [comment]
Yes, it's manually approved. So the app is always a little bit behind. But normally should catch up each day.
