### ISSUE TITLE
Bitbucket Cloud - Updating existing PRs with deactivated reviewers causes HTTP 400

### ISSUE THREAD

**Issue by setchy** [renovatebot/renovate#10700]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [x] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.52.1 at time of report (always pulls latest released version)

**Describe the bug**

We have been seeing the below error throughout our `renovate-bot` logs recently.  

We have triaged this down to the following situation:
* Renovate creates the initial branches and PRs, assigning the default reviewers for that repository
* After this, one of the default reviewers Bitbucket Cloud user account has been `deactivated` as part of their employment offboarding
* Any subsequent run of Renovate tries to update the existing branches and PRs
* Renovate errors out with a `mailformed reviewers list` HTTP 400 error as shown in the below excerpt

If I go through and manually remove the deactivated user from the PRs, then renovate will run successfully on its next run.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
         "message": "Response code 400 (Bad Request)",
         "stack": "HTTPError: Response code 400 (Bad Request)\n    at Request.<anonymous> (/root/.npm/_npx/05eeecd92f4e18e0/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/25.52.1 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "6709",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://api.bitbucket.org/2.0/repositories/{org}/{repo}/pullrequests/18",
           "username": "",
           "password": "",
           "method": "PUT",
           "http2": false
         },
         "response": {
           "statusCode": 400,
           "statusMessage": "Bad Request",
           "body": {
             "type": "error",
             "error": {
               "fields": {"reviewers": ["Malformed reviewers list"]},
               "message": "reviewers: Malformed reviewers list"
             }
           },
```

</details>

**Have you created a minimal reproduction repository?**

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Our shared default configuration (local preset)

<details><summary>Click to see local default config</summary>

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    "schedule:nonOfficeHours",
    "group:definitelyTyped",
    "group:linters",
    "github>whitesource/merge-confidence:beta",
    ":prConcurrentLimit10"
  ],
  "packageRules": [
    {
      "matchUpdateTypes": ["patch", "pin", "digest"],
      "automerge": true
    }
  ],
  "automergeType": "branch",
  "separateMinorPatch": true,
  "separateMultipleMajor": true
}
```

</details>

**Comment by rarkins** [comment]
Can you include your config?

IIRC Renovate intentionally "puts back" the same list of reviewers when it updates existing PRs so that they're not unintentionally removed. So the list comes from BB. The question is whether we should:
- somehow determine if any in that existing list are deactivated before any update, or
- try, fail and then strip out the deactivated ones (does the API error response reliably include them in a parseable way?)
- try, fail and then set the default set of reviewers now (ignore what was there)
- try, fail and then remove all reviewers if there's a problem with any

**Comment by rarkins** [comment]
@setchy Please reformat this using our bug template and use logs. And out of interest, did you delete the template manually?

**Comment by setchy** [comment]
I've reformatted to use the bug template.  This didn't come across for me yesterday, though it has in the past 🤷‍♂️ ...


Re: your 4 suggested courses of action @rarkins - I'm leaning towards the 3rd variation `try, fail and then set the default set of reviewers now (ignore what was there)` in conjunction with a PR comment explaining that the PR reviewers have been reset as the default due to a Bitbucket error.

**Comment by HonkingGoose** [comment]
@setchy By the way, you can remove this part from your config, we now show the Merge Confidence badges for everybody.

```json
    "github>whitesource/merge-confidence:beta",
```

**Comment by setchy** [comment]
Thanks @HonkingGoose - I thought as much - will do some tidy up

**Comment by setchy** [comment]
#11834 Draft implementation of Option 1 as suggested above by @rarkins

**Comment by rarkins** [comment]
@setchy sounds like try/catch would be the most pragmatic approach to save API calls

**Comment by setchy** [comment]
I agree @rarkins 

Updated PR to use try/catch for inactive account/reviewer handling (ie: Option 2 as above)
