### ISSUE TITLE
NuGet v3 feeds without PackageBaseAddress endpoint fail silently

### ISSUE THREAD

**Issue by ccopsey** [renovatebot/renovate#10712]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [x] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.50.0

**Describe the bug**

It appears renovate expects NuGet v3 feeds to provide a `PackageBaseAddress` endpoint, however not all feeds provide this - notably JFrog Artifactory.  Also, the error message is hidden in DEBUG logs so the failure passes silently.  As a result only v2 Artifactory endpoints can be used.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: nuget registry failure: can't get PackageBaseAddress (repository=***/***)
        "err": {
          "message": "Cannot destructure property 'serviceId' of 'services.pop(...)' as it is undefined.",
          "stack": "TypeError: Cannot destructure property 'serviceId' of 'services.pop(...)' as it is undefined.\n    at getResourceUrl (/usr/src/app/node_modules/renovate/lib/datasource/nuget/v3.ts:72:13)\n    at Object.getReleases (/usr/src/app/node_modules/renovate/lib/datasource/nuget/v3.ts:160:32)\n    at getRegistryReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:69:15)\n    at mergeRegistries (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:137:19)\n    at fetchReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:230:15)\n    at Object.getPkgReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:284:7)\n    at Object.lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:62:30)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:39:13)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
        },
        "url": "https://artifactory.***/artifactory/api/nuget/v3/nuget-***"
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I suspect any public facing Artifactory NuGet feed would exhibit this behavior, but it might be of more interest to note that Dependabot added a fix for this a couple of days ago and they include an index.json fixture in their tests:

https://github.com/dependabot/dependabot-core/pull/3972

**Comment by viceice** [comment]
needs a conditional before this:
https://github.com/renovatebot/renovate/blob/b8e36daa87e4275caa5b66bffa6fe3f4d5d8a77e/lib/datasource/nuget/v3.ts#L72-L72

eg:
```ts
if (services.length === 0) {
    await packageCache.set(cacheNamespace, resultCacheKey, null, 60);
    return null;
}

and some tests of cause.

**Comment by viceice** [comment]
🤔  It should work even without `PackageBaseAddress`, the only missing thing then is `sourceUrl` .

https://github.com/renovatebot/renovate/blob/b8e36daa87e4275caa5b66bffa6fe3f4d5d8a77e/lib/datasource/nuget/v3.ts#L165-L175

**Comment by ccopsey** [comment]
I can’t produce a public feed to reproduce this, but I have found a feed on jfrog’s own domain that exhibits the problem. Is this sufficient?

https://grpc.jfrog.io/artifactory/api/nuget/v3/grpc-nuget-dev

**Comment by viceice** [comment]
Sure, of you can reproduce it in a minimal repo. See issue template link for details.

**Comment by ccopsey** [comment]
I have attempted to create a minimal reproduction, and while I continue to see the error locally I don't see it when run through the hosted GitHub app.  The hosted GitHub app correctly created the PR.

I need to find time to continue to investigate/reproduce the local vs hosted discrepancy, but it feels like the this logged issue isn't the root problem after all.  Thanks for taking the time to help.
