### ISSUE TITLE
Support dependency dashboard in Azure DevOps

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/renovate#10725]
**What would you like Renovate to be able to do?**

Have a dependency dashboardin Azure DevOps since this seems to not be supported yet:

> WARN: ensureIssue() is not implemented
> ...
> WARN: findIssue() is not implemented

**Did you already have any implementation ideas?**

N/A

**Comment by rarkins** [comment]
Would this function ok as a "work item" though?

**Comment by tomkerkhove** [comment]
Definately

**Comment by viceice** [comment]
Duplicate of #9592

**Comment by tomkerkhove** [comment]
Sorry!
