### ISSUE TITLE
Using Github Token to request github-tags from repository in another organization is not working. 

### ISSUE THREAD

**Issue by jeskosda** [renovatebot/renovate#10737]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com

<details><summary>Click me to see logs</summary>

```
DEBUG: Adding token authentication for https://github.com/ORG-B/ to hostRules
DEBUG: Adding token authentication for https://api.github.com/repos/ORG-B/ to hostRules
…
DEBUG: GitHub 404
{
  "url": "https://api.github.com/repos/ORG-B/REPO/tags?per_page=100"
}
DEBUG: Datasource 404
{
  "datasource": "github-tags",
  "lookupName": "ORG-B/REPO",
  "url": "https://api.github.com/repos/ORG-B/REPO/tags?per_page=100"
}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository

https://github.com/jeskosda/renovate-reprod

**Additional context**

The issue is based on the discussion: https://github.com/renovatebot/renovate/discussions/10605 with the following input:

<details><summary>Click here to the discussion base</summary>

Hey guys, I have some problems when it comes to authenticating with running Github App Renovate in ORG-A accessing private Repository in ORG-B using the specific hostRule  (also tried out only using hostType=github-tags):

```
"hostRules": [
    {
      "matchHost": "github.com",
      "encrypted": {
        "token": "ENCRYPTED_TOKEN"
      }
    }
]

```

The PAT is from a bot user having access to both github orgs.
When checking the Rate-Limit and the request with that token with the following pattern locally, there is no problem:
`curl -X GET -H "Authorization: token  TOKEN"  "https://api.github.com/repos/ORG-B/REPO/tags?per_page=100"
`

```
DEBUG: GitHub 404
{
  "url": "https://api.github.com/repos/ORG-B/REPO/tags?per_page=100"
}
DEBUG: Datasource 404
{
  "datasource": "github-tags",
  "lookupName": "ORG-B/REPO",
  "url": "https://api.github.com/repos/ORG-B/REPO/tags?per_page=100"
}
DEBUG: Failed to look up dependency ORG-B/REPO (ORG-B/REPOl)(packageFile="bases/some-base/kustomization.yaml", dependency="ORG-B/REPO")
```

The funny thing is that this seems to be flaky because it has worked twice since two days:
`DEBUG: Fetching changelog: https://github.com/ORG-B/REPO (0.14.1 -> 0.14.3)` and the PR was created, but after the next job it was autoclosed again.

Do you have any thoughts about that? Is something miss-configured? 
</details>

**Comment by rarkins** [comment]
matchHost=github.com is not something we plan to support if the endpoint itself is api.GitHub.com. You do not want to override the app's own token. I'd be open to supporting matchHost=https://api.github.com/repos/org-b/ as a feature request if it doesn't already work

**Comment by rarkins** [comment]
Needs someone to debug it and check what hostRules are matched and applied for the tags lookup (shouldn't matter that it gets a 404 as we went to inspect the headers before the request is sent)

**Comment by jeskosda** [comment]
>  I'd be open to supporting matchHost=https://api.github.com/repos/org-b/ as a feature request if it doesn't already work

Also tested only with this `hostRule`. It's the same result, a few times of the runs the lookup doesn't fail, but most of the time I receive: 
```
{
  "datasource": "github-tags",
  "lookupName": "org-b/someRepo",
  "url": "https://api.github.com/repos/org-b/someRepo/tags?per_page=100"
}
```

**Comment by jeskosda** [comment]
I tried to reproduce the hostRule issue with some tests: https://github.com/jeskosda/renovate/commit/06b47c6c134a5d93854c53d04aa58c33d39a8573
Some outcomes/learnings are, that the token from the platform (Github App) is used, when the hostType is not configured to `"github"`for the specific `matchHost: "https://api.github.com/repos/org-b/"`, because the initialization of platform configuration adds the hostRule: `{ "hostType": "github", "matchHost": "https://api.github.com"}` first. So the find method returns the platform hostRule, when the hostType of the desired hostRule isn't set to `"github"`
What I found out is that the default `hostType: "github"` is used to find the configured hostRule for the datasource. The problem relies on the`GithubHttp` class which sets the default `"github"` hostType. So when configuring the hostType to the more specific datasource `"github-tags"`, the hostRule wouldn't be found during the lookup. So if we want to achieve:

> hostType is another way to filter rules and can be either a platform such as github and bitbucket-server, or it can be a datasource such as docker and rubygems. 

we need to somehow pass the datasource to the GithubHttp constructor like in this small suggestion: 
https://github.com/jeskosda/renovate/commit/ebc401962b6c570861de4104156c0202ce29fc7d

**Comment by rarkins** [comment]
Sorry, I've got a bit lost following this.

Would it help if we automatically added hostRules for `github-tags` and `github-releases` in addition to `github`? Or perhaps a host rule for api.github.com without any `hostType`?

**Comment by jeskosda** [comment]
> Would it help if we automatically added hostRules for github-tags and github-releases in addition to github?

Not sure, I thought the problem is the constant `hostType=github` of `GithubHttp`. So when ever a hostType is specified for the datasources `github-tags/releases` in the hostRules, it will never find the configured hostRule when making a `api.github .com` request. Tried to emphazise this here: https://github.com/jeskosda/renovate/commit/ebc401962b6c570861de4104156c0202ce29fc7d

The automatically added hostRules for `github-tags` and `github-releases` would then use the Github App token, right? In that case the token has no acess to the `org-b` and we still would have the problem.

**Comment by rarkins** [comment]
Good point. So if you set your custom hostRules entry to be hostType=github then does it work as expected?

**Comment by jeskosda** [comment]
Yes!

**Comment by jeskosda** [comment]
If my proposed changes are appropriate or in the right direction, I would be happy to contribute.

**Comment by rarkins** [comment]
Do you mean passing the custom datasource ID through to the GitHubHttp class? If so then we'd need to add the extra "automatic" hostRules at the same time

**Comment by jeskosda** [comment]
Yes, that's right!

**Comment by rarkins** [comment]
Sounds good

**Comment by HonkingGoose** [comment]
@rarkins are we `status:ready` on this now? It seems you and @jeskosda reached consensus on how to proceed?

**Comment by jeskosda** [comment]
Yes, at least I have enough information to start on that this week 👍🏻

**Comment by HonkingGoose** [comment]
I'll assign this issue to you then @jeskosda, so that we know you'll be working on it soon! 😄

**Comment by rarkins** [comment]
@jeskosda would it help if Renovate set a "generic" hostRule with the token for github.com? i.e.

```
{
  "matchHost": "github.com".
  "token": "..........."
}
```

We need to keep the existing rule with hostType=github because our application looks for such a rule at times, but we can "duplicate" it to have this generic one, which would mean it should get passed through to any https lookup that's done to api.github.com even if it's for github-tags, etc.
