### ISSUE TITLE
gradle-lite: support repository extraction from init.gradle inside Gradle wrapper

### ISSUE THREAD

**Issue by EndzeitBegins** [renovatebot/renovate#10774]
**What would you like Renovate to be able to do?**

In a corporate environment, access to public repositories may be restricted 
or internal repositories (e.g. Sonatype Nexus) may be used in addition to existing public repositories (e.g. maven central).

To consolidate configuration of these repositories, in Gradle one can use initialization scripts
either inside the user's Gradle home or inside the Gradle wrapper used itself.
This way, corporate wide configuration can be shared easily without duplication inside every project repository.

While trying to migrate to gradle-lite I've encountered, 
that repositories denoted in the init.gradle inside our Gradle wrapper are not taken into consideration.

Just to make clear, I'm not talking about authentication, which works perfectly fine via some host rules.
Instead, the repository url's themselves are not taken into account, when moving to gradle-lite.

**Did you already have any implementation ideas?**

I'm not sure how to achieve this behaviour, 
since the whole point of gradle-lite is to not rely on invoking Gradle (wrapper) anymore.
However, as of now this is stopping us from moving to gradle-lite.

Is there a way to define additional repositories to use via host rules or other configuration?
That way we'd still have to duplicate the repository information, but just once for our self-hosted Renovate instead of copy-pasting it into every repository.

Thanks in advance!

**Comment by rarkins** [comment]
Is there any convention yo the file and field names you use? If so then we should add a parsing rule to it. I would hope Gradle has a standard way to define custom registries..

If not, have you tried adding a packageRules entry with matchDatSources and `registryUrls` defined?

**Comment by EndzeitBegins** [comment]
Thanks for the quick response @rarkins.

The [official gradle documentation](https://docs.gradle.org/current/userguide/init_scripts.html) names several locations, where a initalization script can be located, namely:
- `init.gradle(.kts)` inside `USER_HOME/.gradle/`
- `*.gradle(.kts)` inside `USER_HOME/.gradle/init.d/`
- `*.gradle(.kts)` inside `GRADLE_HOME/init.d/`
This last option allows for inclusion of arbitrary initalization files inside a custom Gradle wrapper distribution.

The repository declaration may look along the lines of:
```kotlin
repositories {
    maven {
        url = uri("http://repo.mycompany.com/maven2")
    }
}
```

The crucial problem I see in this is that in contrast to other build tools 
Gradle uses scripts (Kotlin / Groovy) instead of configuration files, e.g. npm oder Maven. 
Thus, a declaration can also be more dynamic, e.g.:
```kotlin
val repositories = mapOf(
	"repoA" to "https://repo-a.tld/repo",
	"repoB" to "https://repo-b.tld/repo"
)

repositories {
    repositories.forEach { (repoName, repoUri) ->
        maven {
            name = repoName
            url = uri(repoUri)
        }
    }
}
```
I think analyzing this via static analysis instead of invoking Gradle itself will be quite hard.
Also, the wrapper needs to be downloaded anyway to retrieve access to the init-script in the first place. 

---

Additionally providing the repository URLs once inside the self-hosted configuration of Renovate via `registryUrls` seems like a good compromise.
This way, the abovementioned analysis can be avoided. 

I will try this sometime the next week.
If I understand the documentation correctly, 
I should be able to add something along the lines of:
```json
{
  "packageRules": [
    {
      "matchDatasources": ["maven"],
      "registryUrls": ["https://repo-a.tld/repo", "https://repo-a.tld/repo"]
    }
  ]
}
```
to the bot's configuration, to achive the desired output with gradle-lite, is that right?

**Comment by rarkins** [comment]
Yes, your proposed config is what I'd recommend. It should work for you if you add it either to:
- Your bot config (`config.js`), or
- Any shared config which all repos extend

**Comment by EndzeitBegins** [comment]
> Yes, your proposed config is what I'd recommend. It should work for you if you add it either to:
> 
> * Your bot config (`config.js`), or
> * Any shared config which all repos extend

Worked like a charm. 

Thank you once more for the fast and helpful responses. 👍🏻
