### ISSUE TITLE
Cannot find preset's package after upgrade to v1.5

### ISSUE THREAD

**Issue by vladh91** [renovatebot/renovate#10842]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [x] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [x] GitLab self-hosted

Renovate version: 1.5.0

**Describe the bug**
After upgrading Renovate from v1.3.1 to 1.5.0 we have started to notice that Renovate is not able to get custom presets.

...

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
INFO: Repository has invalid config (repository=pixel/panel-components)
       "error": {
         "validationError": "Cannot find preset's package (workfront:default)",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:265:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.mergeRenovateConfig (/usr/src/app/node_modules/renovate/dist/workers/repository/init/merge.js:210:50)\n    at async Object.getRepoConfig (/usr/src/app/node_modules/renovate/dist/workers/repository/init/config.js:12:14)\n    at async Object.initRepo (/usr/src/app/node_modules/renovate/dist/workers/repository/init/index.js:26:14)\n    at async Object.renovateRepository (/usr/src/app/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async e (/usr/src/app/src/server.js:1:40055)\n    at async startWorker (/usr/src/app/src/server.js:1:39258)"
       }
 INFO: Repository finished (repository=pixel/panel-components)

```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

This is our configuration for module
```module.exports = {
      // Enter self-hosted configuration options here.
      // https://docs.renovatebot.com/self-hosted-configuration
      platform: "gitlab",
      prCommitsPerRunLimit: 5,
      prFooter: "This MR has been generated by [Renovate Bot](https://renovatebot.com).\nPlease [log an issue](https://gitlab.workfront.tech/core-platform/devtools/renovate-helm/issues) if you encounter any.",
      // Default Onboarding Config
      onboardingConfig: {
        "extends": [
          "workfront:default",
          "workfront:phoenix",
          "workfront:devDependencies",
          "workfront:dashboard"
        ]
      },
      // Preserve repos between runs.
      // Reduces load by running `git fetch` instead of `git clone`
      persistRepoData: true,
      // Set this to "enabled" to have Renovate maintain a JSON file cache per-repository to speed up extractions.
      // WARN: This is experimental and could be removed.
      repositoryCache: "enabled",
    }
```
 We have also custom configured presets for internal use. We have those custom presets stored as a npm package and building it via package.json

**Comment by rarkins** [comment]
Please raise an issue in https://github.com/whitesource/renovate-on-prem instead. Also it looks like you are leaving out relevant config, and before/after logs would be best to add.

**Comment by vladh91** [comment]
Created new issue with more description in provided repository.
