### ISSUE TITLE
Proposal: config terminology refactor

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#10887]
I don't think we've managed to distinguish clearly enough between "bot/admin config" and "user/repo config" in the past and would benefit from consistent terminology. What if we were to repurpose some terms and use them consistently?
- Bot/admin config becomes "global config"
- User/repo config remains as "repo config"

The alternative to "global config" would be "admin config", but I'm leaning towards global config.

One other complexity is that there are really two ways you can distinguish config:
- Whether it was configured by the bot admin or in the repo (global config vs repo)
- Whether it is *allowed* to be configured by users or not. Global config can contain all user-configurable config

If we were to use the global vs repo terminology then it means we would also use the term "global only" options instead of "admin options".

@HonkingGoose @viceice @JamieMagee @secustor @fgblomqvist WDYT?

**Comment by viceice** [comment]
Sounds good to me. We should document this on the options pages, so it's more clear which options can be used globally or on repo.

**Comment by rarkins** [comment]
We already split between admin-only options vs user configurable

**Comment by viceice** [comment]
Yes, i think we should simply add a note to clarify that repo options can but shouldn't be used in global config 🙃

**Comment by HonkingGoose** [comment]
> I don't think we've managed to distinguish clearly enough between "bot/admin config" and "user/repo config" in the past and would benefit from consistent terminology. What if we were to repurpose some terms and use them consistently?

I'm always in favor of making things consistent! 😄 

> The alternative to "global config" would be "admin config", but I'm leaning towards global config.

I like global config best.

> One other complexity is that there are really two ways you can distinguish config:
> 
>     * Whether it was configured by the bot admin or in the repo (global config vs repo)
> 
>     * Whether it is _allowed_ to be configured by users or not. Global config can contain all user-configurable config
> 
> 
> If we were to use the global vs repo terminology then it means we would also use the term "global only" options instead of "admin options".

I like this explanation, it should go in the docs somewhere suitable.

---

Making this change won't be as easy as find/replace, as we will need to check all our docs for outdated terms. We should be sure our new terms are better than what we have now, before we start doing the migration work.

So measure twice, cut once. 😄

**Comment by secustor** [comment]
What also can lead to confusion is the usage of configuration repos at the organization/group level.      
The user could understand `global` in this context as global for their organization. `admin` is here also not ideal as this could mean configurations for the admin of the RenovateBot for the organization.

IMHO there is no ideal solution, but the best way is probably to use     
`global` --> `organizational` ( :thinking:  I think there is no difference to repo configuration ATM ) --> `repo`    
and highlight the meanings of the configurations options at the top of the `configuration options` doc.

**Comment by fgblomqvist** [comment]
I agree with `global` and `repo` configs, and I also agree that this change needs to happen, it can certainly be a bit confusing atm (especially the `admin` terminology 😄 ).

@secustor not sure I'm following, could you give an example perhaps?

**Comment by secustor** [comment]
ATM you have three layers to configure RenovateBot, at least if I'm not mistaken.  
- Admin/Global configs which are available only if you self host RenovateBot. 
- It is possible to create a [RenovateBot configuration repository in an organisation](https://docs.renovatebot.com/config-presets/#organization-level-presets) which will affect all repositories inside of the Github organization/ Gitlab group / ... 
- and the (end)user configuration inside of a repository which only affect the specific repo

I assume here three roles: 
- BotAdmin: which manages the RenovateBot installation proper
- OrganizationalAdmin: which manages the settings for the organization
- EndUser: which creates the repository and manages his project. 

Now if the end user reads global or admin it can be understand ambiguous as "global" could mean global for their organization or "admin" for the organizational admin.   

This is maybe a niche problem for bigger organizations, but I had to explain this a few times :smile:

**Comment by viceice** [comment]
Organizational and Repo configs are the same type of configs. Organizational configs need to be explicit references as preset in repo config to have an effect. But renovate can use it for the onboarding if available.

**Comment by rarkins** [comment]
Technically the only organisation config is the "default onboarding config". While many do end up having a single org-wide preset, that's not semantically enforced and it's no difference to having different types of shared presets within one org or having one preset shared between multiple orgs. But we can reserve the term for possible future use.
