### ISSUE TITLE
Add a Gitlab Generic Package datasource

### ISSUE THREAD

**Issue by samdolt** [renovatebot/renovate#10892]
**What would you like Renovate to be able to do?**

I would like Renovate to have a datasource for [Gitlab Generic Package](https://docs.gitlab.com/ee/user/packages/generic_packages/)

We have a custom format containing version information that our build system use to fetch from:
- git (using tag)
- Gitlab Generic Package
- Gitlab Pipeline Artifacts

We would use the regex manager to parse our custom file, but we need to add the support to Gitlab Generic Package (at first) and then maybe Gitlab Pipeline Artifacts.

**Did you already have any implementation ideas?**

Some code can by inspired by https://github.com/renovatebot/renovate/tree/main/lib/datasource/gitlab-tags

I'm interested in contributing this new feature

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by olegkrivtsov** [comment]
Hi @rarkins it seems the pull request https://github.com/renovatebot/renovate/pull/10909 was already merged and presents in `lib/datasource/gitlab-packages`. Maybe this issue needs to be closed?
