### ISSUE TITLE
Artefact error with cweagans/composer-patches and composer > 2.1.1

### ISSUE THREAD

**Issue by pmelab** [renovatebot/renovate#10934]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [x] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: Latest

**Describe the bug**

Since composer 2.1.2, the `--no-scripts` flag [does not disable plugins any more](https://github.com/composer/composer/blob/master/CHANGELOG.md#212-2021-06-07). This causes [`renovate/composer`](https://hub.docker.com/r/renovate/composer) to attempt to apply patches with [cweagans/composer-patches](https://github.com/cweagans/composer-patches), which fails with `sh: patch: not found`, since the docker image does not contain a `patch` executable.

Could be solved by adding `patch` to the image, but similar problems may appear with any other composer plugin. I suppose the best way to go is to add `--no-plugins` flag to composer execution. This will disable any composer plugins during updates, but up until `2.1.2` they have not been executed anyways 🤷‍♂️ 

~**Workaround**~

~Lock the composer version renovate uses by `composer require composer/composer:2.1.1` and exclude it from major updates by adding a package rule:~

```json5
     {
       paths: ["path/to/composer.json"],
       packageNames: [
         "composer/composer",
       ],
       updateTypes: ["major"],
       enabled: false,
     }
```

**Edit:** The workaround does not work because it only allows to control the major version.

**Comment by viceice** [comment]
Will older composer ignore `--no-plugins` option or do we need to distinguish?

**Comment by pmelab** [comment]
`--no-plugins` also existed in older versions. According to the composer changelog `--no-scripts` pre 2.1.2 disabled the event system for plugins. `--no-plugins` will disable them entirely. Most functionality of composer plugins is implemented through events, but I can't speak for all of them. I guess `activate`, `deactivate` and `uninstall` have still been called. There might be some exotic edge cases where somebody relied on them being executed during `--no-scripts`.

**Comment by pmelab** [comment]
As updated in the issue description, there is no workaround. This issue is currently full blocking renovate on composer projects that use patches.

**Comment by rarkins** [comment]
PRs welcome. https://github.com/renovatebot/renovate/blob/9882cfd0afe301624436d0785a91774cf80d49f4/lib/manager/composer/artifacts.ts#L127

**Comment by HonkingGoose** [comment]
PR #10989 added the `--no-scripts` flag to the `composer update` and `composer install` commands. Does that close/fix this issue, or do we want/need to do more work before this issue can be closed?

**Comment by pmelab** [comment]
I did fix it on our end.
