### ISSUE TITLE
Installation fails in nodeenv

### ISSUE THREAD

**Issue by andormarkus** [renovatebot/renovate#10977]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [X] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [X] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: 25.58.0

**Describe the bug**

Installation fails in nodeenv

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/markus/git_projects_os/renovate/nenv/lib/node_modules/renovate/dist/renovate.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/markus/git_projects_os/renovate/nenv/lib/node_modules/renovate/dist/renovate.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/markus/.npm/_logs/2021-07-26T19_36_43_447Z-debug.log
```

</details>

**Have you created a minimal reproduction repository?**

- [ ] I have provided a minimal reproduction repository
- [X] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

How to reproduce the bug
```bash
git clone https://github.com/renovatebot/renovate.git
cd renovate
nodeenv nenv
. nenv/bin/activate
npm i npm-run-all
npm install -g .
```

Content of  nenv/lib/node_modules/renovate
```bash 
▶ ls nenv/lib/node_modules/renovate
SECURITY.md        jest.config.ts     package-lock.json  tmp                yarn.lock
bin                lib                package.json       tools
codecov.yml        license            readme.md          tsconfig.app.json
data               nenv               renovate.json      tsconfig.json
docs               node_modules       test               tsconfig.lint.json
```

**Comment by rarkins** [comment]
I don't really know what I'm looking at here or if it's something we should have an interest in supporting. Can you provide more details?

**Comment by andormarkus** [comment]
I started to work on the pre-commit hook integration. Pre-commit install all of the packages into virtual environments. Renovate is node base package it will tires to install it to [nodenv](https://github.com/ekalinin/nodeenv).

When it npm runs inside nodeenv it does not generate the `dist` directory. (see in the logs)

**Comment by andormarkus** [comment]
I have added this line to `package.json` and solved the issue.
```json
  "scripts": {
    "preinstall": "npm run-script build"
}
```

**Comment by rarkins** [comment]
Wouldn't that `preinstall` script need to be deleted before publish to npmjs though?

**Comment by andormarkus** [comment]
I made further investigation and it looks like `npm` has [issue](https://github.com/npm/cli/issues/1264). I was able to reproduce it in docker.

Working example (non global install)
```dockerfile
FROM node:stretch

RUN cd /home/node \
    && git clone https://github.com/renovatebot/renovate.git \
    && cd renovate \
    && mkdir nenv

RUN export NPM_CONFIG_PREFIX=/home/node/renovate/nenv \
   && npm i npm-run-all \
   && npm install .
```

Non-working example (global install)
```dockerfile
FROM node:stretch

RUN cd /home/node \
    && git clone https://github.com/renovatebot/renovate.git \
    && cd renovate \
    && mkdir nenv

RUN export NPM_CONFIG_PREFIX=/home/node/renovate/nenv \
   && npm i npm-run-all \
   && npm install -g.
```

Logs:
```bash
#5 98.36 npm ERR! code ENOENT
#5 98.36 npm ERR! syscall chmod
#5 98.36 npm ERR! path /home/node/renovate/nenv/lib/node_modules/renovate/dist/renovate.js
#5 98.36 npm ERR! errno -2
#5 98.37 npm ERR! enoent ENOENT: no such file or directory, chmod '/home/node/renovate/nenv/lib/node_modules/renovate/dist/renovate.js'
#5 98.37 npm ERR! enoent This is related to npm not being able to find a file.
#5 98.37 npm ERR! enoent
```

**Comment by rarkins** [comment]
Is there anything we can or need to do?

**Comment by andormarkus** [comment]
Nope, it's an npm issue
