### ISSUE TITLE
Make link to WhiteSource Renovate Dashboard open in new browser tab/window

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#11010]
**What would you like Renovate to be able to do?**

Make link to WhiteSource Renovate Dashboard open in new browser tab/window

When I want to know why I'm not getting an update from Renovate bot I usually go to one of the earlier PRs and click on the link to the Whitesource Renovate Dashboard to go the Renovate bot logs for my repository. But clicking on the link takes me away from my position on GitHub. This makes it harder to get back to the source repo when you're done checking the logs.

_Steps to reproduce problem:_

1. Go to a repository with Renovate bot enabled
2. Go to a Renovate PR on the repo.
3. Click on `View repository job log here.`
4. Link opens in _current_ browser tab.
5. Click around in logs.
6. Open new tab to get back to GitHub.
7. Bad user experience.

**Did you already have any implementation ideas?**

Set `target="_blank"` on the link, or maybe `noopener` is better.

Documentation for both properties:

- [MDN web docs, `target`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target)
- [MDN web docs, `noopener`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener)

**Comment by viceice** [comment]
I don't think this is possible as we only use markdown links 🤔

**Comment by HonkingGoose** [comment]
> I don't think this is possible as we only use markdown links 🤔

Markdown supports using HTML inline according to the specs.

Maybe we can use something like `<a href="#" target="_blank"</a>` to fix this problem?
Not sure if all platforms support this though...

https://daringfireball.net/projects/markdown/syntax#html

**Comment by rarkins** [comment]
The question is whether github supports it or sanitizes it

**Comment by HonkingGoose** [comment]
```markdown
<a href="https://github.com/renovatebot/renovate/issues/11010" target="_blank">
```

Real link: <a href="https://github.com/renovatebot/renovate/issues/11010" target="_blank">

I think GitHub santizes this, at least it won't work when commenting things.

**Comment by viceice** [comment]
```markdown
<a href="https://app.renovatebot.com/dashboard" target="_blank">
```

Real link: <a href="https://app.renovatebot.com/dashboard" target="_blank">

I think GitHub santizes this, at least it won't work when commenting things.

**Comment by viceice** [comment]
Yes, github is sanitizing `target="_blank"`

```html
<p>Real link: <a href="https://app.renovatebot.com/dashboard" rel="nofollow">dashboard</a></p>
```

**Comment by viceice** [comment]
So i close this as it's not possible.

**Workaround:** use middle mouse button or shift+click 😉

**Comment by HonkingGoose** [comment]
```markdown
<a href="https://app.renovatebot.com/dashboard" rel="noopener">Link to dashboard with noopener</a>
```

<a href="https://app.renovatebot.com/dashboard" rel="noopener">Link to dashboard with noopener</a>

Let's try `noopener` then... 😄

**Comment by HonkingGoose** [comment]
`noopener` is sanitized also. Well let's keep things as they are then, as we have no easy way to fix this. 😄
