### ISSUE TITLE
Pre-commit: Tag not on default branch suggested

### ISSUE THREAD

**Issue by skycaptain** [renovatebot/renovate#11044]
**How are you running Renovate?**

- [ ] WhiteSource Renovate hosted app on github.com
- [X] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [ ] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [X] GitLab self-hosted

Renovate version: 25.59.1

**Describe the bug**

Renovate suggested to update [editorconfig-checker.python](https://github.com/editorconfig-checker/editorconfig-checker.python) in my `.pre-commit-config.yaml` from 2.3.5 to 2.3.51. However 2.3.51 is not on their default branch. Pre-commit's own autoupdater hence does also not suggest updating from 2.3.5 to 2.3.51. Instead, after updating pre-commit dependencies with renovate-bot, `pre-commit autoupdate` suggests to _downdate_ to 2.5.3 again:

`.pre-commit-config.yaml`:

```yaml
repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.3.51'
    hooks:
      - id: editorconfig-checker
```

```shell
$ pre-commit --version
pre-commit 2.13.0

$ pre-commit autoupdate
Updating https://github.com/editorconfig-checker/editorconfig-checker.python ... updating 2.3.51 -> 2.3.5.
```

I would expect renovate to behave like `pre-commit autoupdate` and only suggest tags that are on the default branch.

See https://github.com/pre-commit/pre-commit/issues/1994

**Relevant debug logs**

Are already rotated out.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by rarkins** [comment]
Documentation of the auto update command: https://pre-commit.com/#pre-commit-autoupdate

Looks like we might need even a new datasource for this, to return only the latest tag on default branch. We should also clarify with the pre commit authors about edge cases, such as latest tag not being a valid version

**Comment by skycaptain** [comment]
@rarkins Responding to bot comment. Is the issue and solution understood enough or would you still like to have an example repository?

**Comment by rarkins** [comment]
@skycaptain we need a reproduction repository, please see https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md for instructions
