### ISSUE TITLE
Support SQL-based lookup cache

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11088]
## What would you like Renovate to be able to do?

Use an SQL backing store for more efficient cached lookups.

## Did you already have any implementation ideas?

There are three main drivers for this:

#### Cache lookup efficiency

Today when we use key-based caching like Redis, it means that if there are 200 dependencies to look up then we do 200 Redis queries. Instead, I'd prefer to do one SQL SELECT statement with 200 deps in a WHERE clause.

#### Private dependency caching

Today, we don't cache private dependencies, because we don't want to accidentally "leak" them from the cache to another user who doesn't have the required credentials. Using an SQL model, we can use this logic:
- Before lookup, apply hostRules against the registryUrl to determine if there's auth
- Calculate one-way hash of that auth, and include it in the SQL query
- The SQL query essentially says "Give me results for this package IF it's either public OR if it's private and the stored hash matches this hash"
- If no cached result or cached result is expired, perform a direct lookup using the credentials
- Store lookup result using the hashed credentials

The IF/OR logic mentioned above is impractical to implement using key-based lookup but very simple when using SQL.

#### External host error robustness

Today when a cached lookup expires, it's deleted from the cache. Then if the external host is flaking (e.g. down, or rate limiting) then the whole run is abandoned. It would be much nicer to fall back to using the "expired" cached value and continuing. While we could probably do this using the existing cache, it's a good time to make the change.

## Local vs Remote

We could use SQLite as a replacement for our existing cacache-based cache and support Postgresql first for remote.

We need to think if we still want to support Redis or not - I'd prefer not.

**Comment by rarkins** [comment]
As a first step, I'd want to refactor how we do lookups so that we have a function which receives *all* deps and then returns *all* cached results. Using the existing solution it will still do those queries in semi-parallel but once we implement the new solution then it would replaced with the concept of putting every package+registryUrl in a combined SQL query.

**Comment by rarkins** [comment]
I think this would need to move the cache lookup and writing into the datasource manager. It would need to first resolve the full list of URLs before they could be queried

**Comment by JamieMagee** [comment]
Regarding "External host error robustness", what you're describing sounds like a multi-level cache. When writing, we write to both level 1 and level 2. When reading, level 1 expires after 30 minutes, and level 2 never expires. Or something like that.

**Comment by rarkins** [comment]
Yeah.. we probably want to clean up private ones after a limited time but public ones can have a pretty long timeout before we purge them.

**Comment by rarkins** [comment]
Closed to focus on #11232 first
