### ISSUE TITLE
Optimise rangeStrategy=update-lockfile

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11143]
**What would you like Renovate to be able to do?**

Support rangeStrategy=update-lockfile without needing to run the package manager every time.

**Did you already have any implementation ideas?**

Today we rerun npm/yarn then compare to the existing branch to decide whether to update or not. This is costly as well as more noisy (it will rebase any time the lock file on base branch changes even if not conflicted).

Options:
- run our extract against the existing branch, check if the locked version is already updated, and skip the update if so
- cache branch status to shortcut the above check whenever possible

**Comment by rarkins** [comment]
This is important as a prerequisite to setting rangeStrategy=update-lockfile as default behaviour and making our range strategy more intuitive.

Our existing npm transitive remediation feature already does something similar.

**Comment by rarkins** [comment]
I only see `isLockFileUpdate` in npm and yarn logic:

![image](https://user-images.githubusercontent.com/6311784/130792438-a57e44a9-9db6-43b0-b318-2e25ce10021d.png)

On the other hand I'm seeing `update-lockfile` in not just `npm` versioning but also `composer` and `ruby`:

![image](https://user-images.githubusercontent.com/6311784/130792781-d3aa03d8-6b75-4957-ad42-f82931f29ee5.png)

Other managers support update-lockfile indirectly partly through the combination of this logic in workers:

https://github.com/renovatebot/renovate/blob/d260dbf2d970b2d097b45b59cb3067ac532916a7/lib/workers/branch/get-updated.ts#L115-L118

And then calling `getArtifacts()` and they use the `updatedDeps` array like these:

https://github.com/renovatebot/renovate/blob/d260dbf2d970b2d097b45b59cb3067ac532916a7/lib/manager/bundler/artifacts.ts#L104-L107

https://github.com/renovatebot/renovate/blob/3505508c9c03599eb64cbd9792018a18de4db42d/lib/manager/composer/artifacts.ts#L131-L134

**Comment by rarkins** [comment]
Two complementary options:
1. Cache branch state, use it as our source of truth. If it says the update was already done, then skip it
2. Instead of running commands and then diffing to decide if it needs updating or not, parse/extract the contents of the existing branch and determine if the dependency needing updating is already sufficiently updated

The downside of (1) is that the single source of truth *could* be wrong and not self-heal automatically. But I think the benefits outweigh that downside, and you can rebase a branch on demand if you like.

**Comment by rarkins** [comment]
Each manager which supports rangeStrategy=update-lock file should also support a updateLockedDependency() function. We need to gather the list of managers which support update-lock file and confirm once each one is at least capable of detection already-updated branches.

**Comment by rarkins** [comment]
Poetry and Terraform seem to be the only two left

**Comment by RahulGautamSingh** [comment]
> Today we rerun npm/yarn then compare to the existing branch to decide whether to update or not. This is costly as well as more noisy (it will rebase any time the lock file on base branch changes even if not conflicted).

It should rebase when the lockfile on base branch changes, since it means that branch is behind base?

**Comment by RahulGautamSingh** [comment]
> Today we rerun npm/yarn then compare to the existing branch to decide whether to update or not. This is costly as well as more noisy (it will rebase any time the lock file on base branch changes even if not conflicted).

It should rebase when the lockfile on base branch changes, since it means that branch is behind base?

Or do we want to skip `npm install` whenever possible even when branch is being rebased except for when conflict occurs.

**Comment by rarkins** [comment]
If it needs to rebase then it needs to rebase - that shouldn't change.

But what should change is that we should never run a third party tool like `npm` _just to see if the branch needs updating_. This has been done for most now, but as noted above Poetry and Terraform remain

**Comment by RahulGautamSingh** [comment]
Will adding an `updateLockedDependecy` function to the manager do the job, or is there more to it?

**Comment by rarkins** [comment]
Yes, so maybe it's just Terraform remaining as I see a merged PR for Poetry
