### ISSUE TITLE
Clarify preset handling in global config 

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11159]
Plenty of users have put “extends” arrays in their global config (e.g. config.js). I think not all expect them to operate in the same way. For example:
- if they contain any global settings then users obviously need them resolved immediately
- If they want users to be able to ignore parts of them using ignorePresets then they need to be resolved lazily only as part of the repo config resolution
- If they are resolved lazily then it means they are treated as part is the repo config, not global config. So settings in the global config presets will override the other global config settings

We should either:
- clarify and limit how to use presets in global now, or
- Add global config options which lets users decide which mode of resolution they are expecting

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/issues/11159

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/discussions/11158

**Comment by rarkins** [comment]
Resolved by `globalExtends`
