### ISSUE TITLE
 SBT not scan build.properties

### ISSUE THREAD

**Issue by snehal-kolte** [renovatebot/renovate#11212]
### What would you like Renovate to be able to do?

We are using sbt manger and it is not scanning build.properties(sbt.version=1.4.9) and creating PR.
Looks like it scan only ".sbt$" and "project/[^/]*.scala$" not .properties.

```
sbt: {
description: "Configuration object for the sbt manager",
type: "object",
default: {
fileMatch: [
".sbt$",
"project/[^/]*.scala$"
],
versioning: "ivy"
},
$ref: "#"
},
```

### If you have any ideas on how this should be implemented, please tell us here.

```
sbt: {
description: "Configuration object for the sbt manager",
type: "object",
default: {
fileMatch: [
".sbt$",
"project/[^/]*.scala$",
"project/[^/]*.properties$"
],
versioning: "ivy"
},
$ref: "#"
},
```

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Please also format the above using ``` code blocks so that it's more readable

**Comment by snehal-kolte** [comment]
**Minimal reproduction detail:**

Renovate doesn't seem to update sbt version when updating drone sbt version

Renovate update sbt image version in drone file like below
`from image: mozilla/sbt:8u232_1.4.9 to image: mozilla/sbt:8u292_1.5.4`

But we also need to update sbt version in project/build.poperties. Like below 
`from sbt.version = 1.4.5 to sbt.version = 1.5.4`

Please let me know if you need any more information.

**Comment by rarkins** [comment]
Yes, please follow the minimal reproductions link above to see what we need. Snippets is not enough

**Comment by snehal-kolte** [comment]
@rarkins , Would you please explain what else information i need to provide ? I think above snippet is more informative and i doubt to provide any more detail about issue other than snippet.

**Comment by snehal-kolte** [comment]
@rarkins Please refer fork to recreate issue https://github.com/snehal-kolte/scala-sbt-example. Hope it helps

**Comment by rarkins** [comment]
The next question is: where can Renovate get a list of sbt versions?

**Comment by rarkins** [comment]
I don't see anything on those pages which describes how to get a list of all versions which exist

**Comment by viceice** [comment]
RUN install-tool sbt v1.5.5

**Comment by rarkins** [comment]
Great. Then in that case don't ned any new datasource and just need an extra extract logic in the existing sbt manager

**Comment by snehal-kolte** [comment]
@rarkins Do have any ETA when this feature will be available for use?

**Comment by rarkins** [comment]
No

**Comment by snehal-kolte** [comment]
@rarkins Any updates :) ?
