### ISSUE TITLE
New issue form: request new package manager support

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#11215]
### What would you like Renovate to be able to do?

Right now we ask people to copy/paste a Markdown template into a new comment when they want to propose new package manager support.

It might be nicer and easier to make a new form out of the template? That way it reads as less of a wall of text, and we can add helpful `description` to the fields. And we can be sure all fields are actually filled in.

### If you have any ideas on how this should be implemented, please tell us here.

Refactor [Markdown template](https://github.com/renovatebot/renovate/blob/main/docs/development/new-package-manager-template.md) into a _new_ form, that users can select from the issue screen.

Remove the code that tells our label bot to comment on `new package manager` type issues: https://github.com/renovatebot/renovate/blob/3d1ea66f887edc8470a0847200e011fd88ace03c/.github/label-actions.yml#L104-L121

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
So would this be a new option/button when creating an issue?

The concern I have is whether this is too intimidating and we'll have people skip it altogether. It is OK by me if someone raises an "incomplete" new manager suggestion and it sits there for a year until someone else is motivated enough to fill out the form. In the meantime maybe collecting some thumbs ups too.

**Comment by rarkins** [comment]
I'm happy for now but will revive this issue if I change my mind :)

It just seems like a bit too much of a barrier to entry for now
