### ISSUE TITLE
Renovate Application-level Proxy

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11232]
### What would you like Renovate to be able to do?

Support the concept of a Renovate-specific proxy, inspired by Go's proxy. It should support both datasource lookups as well as changelogs.

### If you have any ideas on how this should be implemented, please tell us here.

This would probably mean a new repository which depends on Renovate code, but also require some features in Renovate too, such as:
- Configuring the proxy address
- "No proxy" capability
- Configurable retry codes (e.g. defaults to 429, 5xx but could add any 4xx)

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
First thing I'd add is that we should stand on the shoulders of giants as much as possible and reuse as many existing concepts as possible. If anyone is aware of other similar concepts such as Go's proxy, or features within it which I have missed, then please point them out.

**Comment by rarkins** [comment]
The more open the better, but I'm pretty sure if we had a public proxy with both the following characteristics, then we'd end up with huge spam problems pretty quickly:
- Unauthenticated access/querying
- Unrestricted package/registry URL querying

(I know Renovate itself kind of allows this today.. but that's another matter)

It's also not my intention that people could hammer or scrape the proxy even for "legitimate" purposes (e.g. university research or simply individual curiosity) because I think that would also make the service difficult to maintain.

We could "lock down" such a proxy to only default registry URLs, but for some datasources with a more distributed approach that would be too restrictive - e.g. missing many go modules, Docker images, and Helm charts.

Another difference to note is between a private proxy which would essentially "trust" all clients versus a public proxy which needs to defend itself against untrusted. I anticipate that self-hosted users might have a private proxy which pulls from the upstream public proxy.

**Comment by rarkins** [comment]
Renovate would need to be designed so that users could configure whether to fall back to direct datasource lookups or not in failure conditions, and we should try to make the proxy ever avoid 404 false positives.

**Comment by JamieMagee** [comment]
Would something like [Squid Proxy](https://github.com/squid-cache/squid) be sufficient? It's a 'dumb' HTTP caching proxy, but the lowest common denominator across all datasources is caching HTTP responses.

**Comment by rarkins** [comment]
Not fully sufficient, although it would still provide some benefits if you added it to any application proxy. The main gaps are:
- Just like with the go proxy, one aim is that clients don't need to perform multiple queries or paginate through responses just to extract out the small data we use. Squid wouldn't reduce the number of requests or data sent between Renovate and it
- More importantly, any use of authentication would really mess with it. For example each GitHub org and sometimes repo will have a unique token, which will in addition be rotated at least every hour. In theory Squid can't reuse any results if the token differs, so it would cache very little across orgs/repos whenever auth is in use, such as GitHub and Docker. An application-aware proxy can determine "this result is from a public repo so I will make it available for everyone else too"

**Comment by rarkins** [comment]
BTW there's two fairly different use cases which I'm hoping to combine into a single concept:
- As a self-hosted user, I would prefer to use a Renovate proxy for open source releases and changelogs instead of having to open up my firewall to many hosts plus configure Docker and GitHub tokens due to rate limiting
- As a Renovate admin, I want to reduce bandwidth and decrease latency by using a shared cache which is shareable by all Renovate nodes I run

The second would be implemented sufficiently by Redis I think, but I think if I'm already going to implement due to the first point then we may as well combine the concepts.

**Comment by rarkins** [comment]
Duplicate of #8420
