### ISSUE TITLE
Release v26

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11247]
### Describe the proposed change(s).

- [ ] Add Dependency Dashboard documentation page
- [x] Default `dependencyDashboard` to true

**Comment by secustor** [comment]
@rarkins WDYT about moving Terraform lock file maintenance out of the experimental state with v26?

**Comment by rarkins** [comment]
Sure, can you PR it?

**Comment by secustor** [comment]
Done: https://github.com/renovatebot/renovate/pull/11264
