### ISSUE TITLE
Failed to sign in to Renovate Dashboard

### ISSUE THREAD

**Issue by 417-72KI** [renovatebot/renovate#11266]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Describe the bug

On https://app.renovatebot.com/dashboard, I select `Sign in with GitHub`.
Though GitHub authorization has been succeeded, it didn't transit to dashboard page.

### Relevant debug logs

<details><summary>Logs</summary>

```
Access to XMLHttpRequest at 'https://v1.renovateapi.com/github/user' from origin 'https://app.renovatebot.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
There is a terms and conditions page you need to accept on the first sign in. Maybe try in another browser or enable developer tools to look for errors.

**Comment by DawidJanczak** [comment]
We're running into the same issue and no T&Cs are visible on the initial sign in. Tested on different browsers and different machines. After initial sign in with Github the sign-in popup disappears, but nothing else changes. Clicking on the sign in button pop ups a window again, but that immediately closes and again nothing happens. We're using 2FA if that makes any difference :)

**Comment by rarkins** [comment]
What does the browser tools logs say? e.g. are there any 404s?

**Comment by rarkins** [comment]
Here's an example from a successful login. Note that I have checked the "Preserve log" box so that it records all network activity even after redirects:

![image](https://user-images.githubusercontent.com/6311784/129514161-d137812b-a952-406e-9a9b-c41bdecabd54.png)

**Comment by rarkins** [comment]
Something else you can try is manually going to https://app.renovatebot.com/register and submit the form

**Comment by DawidJanczak** [comment]
@rarkins I don't know if you changed anything, but it's working now. Thanks!

**Comment by esetnik** [comment]
After logging out of renovate and attempting to log back in I am also unable to login. The error is:

```
dashboard:1 Access to XMLHttpRequest at 'https://v1.renovateapi.com/github/user' from origin 'https://app.renovatebot.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by rarkins** [comment]
Sorry for the troubles on this. It seems intermittent so hard to work out what's going wrong. And *of course* I can never reproduce it myself no matter how many different times I log in/out or change browsers
