### ISSUE TITLE
yarn.lock files no longer updating

### ISSUE THREAD

**Issue by tim-field** [renovatebot/renovate#11272]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

This happened about ~7 days ago for a mono repo that has been working fine until now.  I'm unable to get logs out of the dashboard to provide more information as that is also down see #11266

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by sachinraja** [comment]
Having the same issue with Yarn 3 and I'm also unable to view the logs.
