### ISSUE TITLE
Go 1.17 module/tidy compatibility

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11294]
### What would you like Renovate to be able to do?

Support go 1.17 while also keeping backwards compatibility for users on earlier versions.

### If you have any ideas on how this should be implemented, please tell us here.

Release notes for go1.17: https://golang.org/doc/go1.17#go-command

It indicates we should consider adding a flag to `go mod tidy` if the existing go version is earlier than go1.17

### Is this a feature you are interested in implementing yourself?

No

**Comment by proton-ab** [comment]
I don't believe that is the case. The documentation says

> To facilitate the **upgrade** to Go 1.17 pruned module graphs, the go mod tidy subcommand now supports a -go flag to **set or change** the go version in the go.mod file.

Setting the flag will perform normal `go mod tidy` operation as well as change Go version requirement in the `go.mod` (for example, running `go mod tidy -go=1.17` on a module that has defined `go 1.14` will upgrade it to `go 1.17` and perform `tidy` operation as for `1.17`. As such, a I believe that this functionality is reserved to developer themselves and should not be used by renovate here.

All that should be changing for us here is that there are now two `require` blocks, one exclusively for indirect dependencies (which we already ignore as I can see in the source code based on `// indirect`).

Further, documentation also states:
> if the main module specifies go 1.17

indicating that Go itself is backwards compatible with modules that declare older than 1.17 version in their `go.mod` without any specific flags or changes needed on user-side. As such, I believe that currently we are compatible with 1.17 and there are no changes required.

**Comment by fgblomqvist** [comment]
What's the latest on this? I agree with @proton-ab, there shouldn't be a need to do anything special here other than just bump Renovate's go version?

**Comment by rarkins** [comment]
Already done in the full image: https://github.com/renovatebot/docker-renovate-full/blob/e08a39c7cd68b80692996be39f54bcb14c0e62fd/Dockerfile#L64

And the app dynamically selects.

I haven't heard any complaints so I agree we can close this.
