### ISSUE TITLE
Support Gradle catalog versions

### ISSUE THREAD

**Issue by mirland** [renovatebot/renovate#11311]
### What would you like Renovate to be able to do?

Update dependencies using the new [gradle way](https://docs.gradle.org/current/userguide/platforms.html). It'll be the new way of sharing dependencies between modules and projects, so it would be great if you can add it to the roadmap.  

### If you have any ideas on how this should be implemented, please tell us here.

Parse the [toml file](https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml) and update the dependencies based on that.

If you need an example, [Gong](https://github.com/xmartlabs/gong) is a project that is using it right now (and the dependencies are not updated anymore).

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Duplicate of #8692
