### ISSUE TITLE
Gradle deepExtract /certs/client/ca.pem: no such file or directory

### ISSUE THREAD

**Issue by t-kulmburg** [renovatebot/renovate#11315]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

26.1.2

### Describe the bug

I am running renovate on gitlab.com with GitLab CI. When running gradle deepExtract, there is an issue pulling the renovate/gradle docker image. 

I am not sure if this is a real certificate error, or if it is trying to pull the wrong image `docker.io/renovate/gradle\nunable`.
I am using the https://gitlab.com/renovate-bot/renovate-runner/ runner as base.

Yesterday  I started having this issue with 25.x, and today updating to 26 didn't help.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Start gradle command (repository=...)
       "cmd": "./gradlew --init-script renovate-plugin.gradle renovate"
DEBUG: Using docker to execute (repository=...)
DEBUG: No tag or tagConstraint specified (repository=...)
       "image": "docker.io/renovate/gradle"
DEBUG: Fetching Docker image: docker.io/renovate/gradle (repository=...)
 WARN: Gradle extraction failed (repository=...)
       "errMessage": "Command failed: docker pull docker.io/renovate/gradle\nunable to resolve docker endpoint: open /certs/client/ca.pem: no such file or directory\n"
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
It seems like `docker pull` has failed. Is/was this working on v25 previously?
