### ISSUE TITLE
Use If-Modified-Since for GitHub Pull Request fetching

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11419]
### What would you like Renovate to be able to do?

Cache the ETag and PR list so that they can be reused if unchanged on future runs on the same repo.

### If you have any ideas on how this should be implemented, please tell us here.

Conversation started in #11418

I think next step is to confirm if this also works with the GraphQL queries we use to fetch GitHub repo PRs.

Assuming it does, next step is to determine if we still need both GraphQL as well as REST approaches to PR list retrieval. IIRC we needed to keep REST fallback because GitHub would return server errors for some very large repos, however we also added an automatic page size backoff routine so maybe don't need it anymore?

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Repo cache: https://github.com/renovatebot/renovate/tree/main/lib/util/cache/repository

**Comment by rarkins** [comment]
I think we can add `pulls?` to https://github.com/renovatebot/renovate/blob/1de7834d56e8d0ae202709dc960526f9d505123d/lib/util/cache/repository/types.ts#L34 and then utilize it in https://github.com/renovatebot/renovate/blob/main/lib/platform/github/index.ts

Our util/http layer may need some modifying to pass etags back and forth and use correctly

**Comment by rarkins** [comment]
I think let's cache the closed PR list and open PR list plus their etags, and see if we can skip fetching them all each time

**Comment by rarkins** [comment]
Unfortunately I'm not seeing etag on responses from GitHub's GraphQL:

![image](https://user-images.githubusercontent.com/6311784/151690197-15a9a26a-0ab5-42ca-b0d2-582ca060553b.png)

@JamieMagee any chance you can confirm this limitation?

**Comment by rarkins** [comment]
We could possibly switch back to the REST API, although it would require one additional GET per PR to get the comments we fetch with GraphQL: https://github.com/renovatebot/renovate/blob/368903ab814f5b19117eaab6c2cb33382be6cad6/lib/platform/github/graphql.ts#L22-L53

**Comment by JamieMagee** [comment]
> @JamieMagee any chance you can confirm this limitation?

Yes, ETag headers are only supported on REST API right now.

**Comment by rarkins** [comment]
We could revert back to using REST for querying PRs if we don't have a concern about the impact of comment fetching.

## We current ensure comments in a PR in these circumstances

### When a PR was closed unmerged, to acknowledge that it will be ignored

We would need to check PR comments for each closed/blocking PR, which could e.g. be 5 API calls per run if the repo has 5 ignored PRs. Alternatives:
- Use a label to indicate that the PR is blocking, because it can be fetched with the PR. But I'm not sure this is descriptive enough or that people want us to create another label
- Add a note in the PR body itself. I'm not sure people will notice?
- Don't comment at all. We now recommend Dependency Dashboard to give visibility of blocked PRs, and of course there's always logs.

BTW it would be a further performance improvement if we didn't need to fetch each closed PR's body either, but the REST interface doesn't allow you to suppress body (unlike GraphQL, which does).

### When there's a commit pushed and there was an artifact error

This only happens on a run when there's a commit, so could justify the extra API call.

### When automergeType = prComment

We might need to fetch this every run, but this is a narrow use case so maybe OK. Also we could use our cache to remember which ones we'd already commented for.

### When the PR was raised as a result of a branch automerge failure

I think this is also a one-time check, so OK.

### When a PR can't be autoclosed because it was modified

I was thinking we could switch from adding a comment here to instead appending "- abandoned" to the PR title.

### When an onboarding PR is closed unmerged

We'd need to check one PR each run in this case, and also could cache it.


## Conclusion

So therefore it's only the first case of closed/ignored PRs which would be inefficient. Could we drop comments from them, or perhaps don't make them by default for platforms supporting Dashboards so that it's opt-in?

**Comment by JamieMagee** [comment]
This is a little bit complicated by the fact that GraphQL[^1] and REST API rate limits are separate values. GraphQL calls are the number of points a query cost, whereas REST limits are the number of calls. Also, rate limits for the are _per installation_ [^2]. 

The simplest thing might be to switch back to REST for everything, and just cache heavily using `ETag` or `If-Modified-Since` headers. That could probably solve your issue with multiple closed PRs, at the cost of increasing the size of your Redis cache.

Also, if you're optimizing for speed you can make `HEAD` requests with an `ETag`/`If-Modified-Since` header, followed by an optional GET if your cache has expired. It works well when you have data that updates infrequently. For example

```ts
const { status } = octokit.request("HEAD ...", {
	headers: {
		'If-Modified-Since": ...
	}
});
if (status === 304) {
	// cache up to date
} else {
	// cache out of date
}
```

I've seen `HEAD` requests take ~20ms, where the equivalent `GET` request takes ~200ms on github.com 😱 

[^1]: https://docs.github.com/en/graphql/overview/resource-limitations#rate-limit
[^2]: https://docs.github.com/en/developers/apps/building-github-apps/rate-limits-for-github-apps#default-server-to-server-rate-limits-for-githubcom

**Comment by rarkins** [comment]
Thanks for the tip about HEAD vs GET. With 304s for such a query I had thought in both cases the "impact" of the request on the API backend would be similar and it's mostly just a saving of bytes over the network. Interesting that somehow the HEAD is so much faster.

Can you think of any scenario where if-modified-since works better for us than ETag? I was thinking these optimizations work best for lists (PRs, issues, tags, etc) and that we cache the list plus the ETag. Does if-modified-since ever work at an "application" level, e.g. so that you can only get PRs modified since X date? I assumed not and that such filtering can only occur if it's supported as part of the query itself.

**Comment by rarkins** [comment]
Maybe a better solution: instead of removing PR comments for blocked PRs, we keep them - but we make sure our repo cache records if we've added a comment already so that we don't try again (assuming cache is in use).

**Comment by rarkins** [comment]
Blocked by #14617

**Comment by zharinov** [comment]
Seems like we have to stick to `ETag` usage instead of `If-Modified-Since`.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1239644/161950180-773bf820-0db5-4b06-9e61-e709f3d322c7.png">

When setting `If-Modified-Since` header with the properly formatted date (e.g. value of the `date` response headers), I still receive `200` response.

Also I can't see `Last-Modified` header which should be logical to use for such cache control.

🤔

**Comment by viceice** [comment]
yeah, it seems github doesn't support that yet. did you tried the etag?

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

**Comment by zharinov** [comment]
> did you tried the etag?

Yes, I already updated both PRs for `etag` usage. Seems like `ApiCache` class now is generic enough to be used more than in one place 🙂

**Comment by zharinov** [comment]
I don't see `Last-Modified` for pull list responses, yes. Didn't check it for other endpoints yet.

![image](https://user-images.githubusercontent.com/1239644/161999864-e7fbfae3-aea0-45ac-9d64-24f3d9b5cd62.png)

As I can see from the code in those twitter thread, they try to reverse default HTTP priorities (i.e. `ETag` over `Last-Modified`). We can do this as well, but all I've seen so far is that `ETag` worked for me while `Last-Modified` didn't (I've managed to generate it correctly on my own).

**Comment by JamieMagee** [comment]
Yes, the issue is that `ETag` headers are not always stable, so `Last-Modified` should be the preferred method for caching. However, `Last-Modified` is not available for all requests.

@zharinov Can you implement the same fallback logic? `Last-Modified` with a fallback to `Etag`?
