### ISSUE TITLE
Manager fingerprinting

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#11426]
### What would you like Renovate to be able to do?

Use more granular cache-busting of extract caches, and do so automatically. The goal is to have more reliable yet targeted cache-busting.

Currently we have this `CACHE_REVISION`: https://github.com/renovatebot/renovate/blob/d260dbf2d970b2d097b45b59cb3067ac532916a7/lib/util/cache/repository/index.ts#L12

It serves two purposes:
- Invalidating the cache if the cache structure changes, and
- Invalidating the cache if any manager extract results change in a way which means the cache shouldn't be reused

In both cases that validation is *manual*, and we have forgotten to increment it in many cases.

### If you have any ideas on how this should be implemented, please tell us here.

I would like it to ideally be automated, and granular. If any logic in a manager's extract logic changes, I want the cached extract results for that manager automatically invalidated.

It means that cache invalidation should not just be done centrally, but also per-manager within the worker. But it also means we need a way to fingerprint each manager's function for fingerprinting.

I'm not sure if an AST-based solution is possible, but it would be ideal. Also not sure how or where to implement that. For example I'm not sure that JS can "introspect" at runtime, or if it's feasible to somehow calculate it and embed it in the JS during TS->JS transformation?

BTW it's ok to cache-bust the entire extract cache if one manager changes. After all, the extra cost of JS-based extract is not too high once we already cloned.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
More thinking:
- We could possibly hash all `*.ts` files in each manager instead of trying to identify the extract ones
- We should only invalidate a cache if one of the managers which has changed hash was in the cache

**Comment by rarkins** [comment]
We don't want to invalidate the entire cache if an unused manager is changed, or perhaps a new one is added. Therefore the invalidation of cache should be based on each manager and:
- manager .TS contents hash
- fileMatch
- manager config of those with matches

So:
- if fileMatch changes then we invalidate the cache. 
- We also invalidate it if the config for a matched manager is different
- We invalidate it if the .TS contents hash of a matched manager is different

**Comment by rarkins** [comment]
Proposal for manager fingerprinting:
- Do not separate out extract from update fingerprinting and instead fingerprint the whole
- Use a managers *tests* to fingerprint it, not its code. i.e. if spec or snapshot files change, then consider the manager changed

**Comment by rarkins** [comment]
@RahulGautamSingh would you like to take this?

**Comment by RahulGautamSingh** [comment]
> @RahulGautamSingh would you like to take this?

Yes, please.😁

**Comment by RahulGautamSingh** [comment]
We can close this and start #14623, sorry I forgot to add "Closes" on related PR.

**Comment by rarkins** [comment]
Let's close it once it's applied to extract cache busting

**Comment by rarkins** [comment]
Actually we have a separate issue for extract cache busting. so we can close this already
