### ISSUE TITLE
Refactor migrations

### ISSUE THREAD

**Issue by pret-a-porter** [renovatebot/renovate#11457]
### Describe the proposed change(s).

After merge PR https://github.com/renovatebot/renovate/pull/11355 I would like to:
1.  Refactor all migrations by new approach, therefore each migration will be in separate class
2. Refactor migrations unit tests, therefore each migration unit test will be in separate file as well

It will increase maintainability of migrations greatly

**Comment by rarkins** [comment]
Blocked by #11459. I don't want to invest time in refactoring migrations until we have that feature worked out.

**Comment by pret-a-porter** [comment]
#9611 can be done as part of this refactoring

**Comment by RahulGautamSingh** [comment]
This can be closed right?
