### ISSUE TITLE
GitHub release notes do not work when GOPROXY is set

### ISSUE THREAD

**Issue by oschwald** [renovatebot/renovate#11465]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of Renovate you run.

26.5.1

### Describe the bug

In 26.0.0, support was added to use the `GOPROXY` environment variable. However, when using a proxy, it appears that GitHub release notes are not added to the pull requests. There is no mention of this in the pull request itself, the debug log, or the documentation.

In our case, we had `GOPROXY` set for our all of our CI build types and didn't set it explicitly for Renovate. After upgrading to a newer version of Renovate, the release notes disappeared and it took us a bit to figure out the cause.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Please provide an example repo with a minimal go.mod etc which needs a PR and which definitely should have release notes.
