### ISSUE TITLE
rust-toolchain version updates

### ISSUE THREAD

**Issue by Turbo87** [renovatebot/renovate#11488]
### What would you like Renovate to be able to do?

[rustup](https://rustup.rs) (the Rust toolchain manager) has support for [toolchain files](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file), which can set the default toolchain version that is used by `cargo` and `rustc`.

It looks like these files are mainly used in two ways:
- pin to a specific stable release (e.g. `1.54.0`)
- pin to a specific nightly release (e.g. `nightly-2021-08-29`)

It would be awesome if renovatebot could automatically update these versions whenever a new version is released.

### If you have any ideas on how this should be implemented, please tell us here.

The data for this could be loaded from https://static.rust-lang.org/dist/channel-rust-stable.toml and https://static.rust-lang.org/dist/channel-rust-nightly.toml (extracted from https://github.com/rust-lang/rustup-components-history) and/or https://github.com/rust-lang/rust/releases.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment]
It seems we can reuse the `github-releases` datasource.

So i think we only need to extend the cargo manager?

**Comment by Turbo87** [comment]
> It seems we can reuse the `github-releases` datasource.

yeah, for `stable` channel updates that would likely be sufficient, not sure about `nightly` though, since those apparently don't show up on the GitHub releases page

**Comment by viceice** [comment]
Ok, so let's start with existing datasource, so you only need to extend the manager.

**Comment by Turbo87** [comment]
sounds like the `cargo` manager is primarily responsible for looking at the `Cargo.toml/lock` files, but not `rust-toolchain.toml`. maybe it would be better to create a dedicated `rustup` manager instead?

**Comment by viceice** [comment]
Ok, but the cargo manager needs an option to use the toolchain version as constraint. So it can use the right rust docker image to update the lock files.

**Comment by Turbo87** [comment]
> the cargo manager needs an option to use the toolchain version as constraint. So it can use the right rust docker image to update the lock files.

wouldn't it be easier to have the docker image use rustup and automatically choose the right version?

**Comment by viceice** [comment]
Currently no. The above way is the current renovate way to suppress unneeded downloads.

**Comment by Turbo87** [comment]
# New package manager questionnaire

**Did you read our documentation on adding a package manager?**

- [x] I've read the [adding a package manager](/renovatebot/renovate/blob/HEAD/docs/development/adding-a-package-manager.md) documentation.

## Basics

### Name of package manager

rustup

### What language does this support?

Rust

### How popular is this package manager?

It's the recommended default for Rust and is used by the majority of Rust developers

### Does this language have other (competing?) package managers?

- [ ] Yes (give names)
- [x] No

Technically the **package** manager for Rust is cargo, while rustup is the
**toolchain** manager. I'm not aware of other toolchain and/or package managers
for it though.

---

## Package File Detection

### What type of package files and names does it use?

`rust-toolchain` and `rust-toolchain.toml` (see https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)

### What [fileMatch](https://renovatebot.com/docs/configuration-options/#filematch) pattern(s) should be used?

`(^|\/|\\)rust-toolchain(\.toml)?$`

### Is it likely that many users would need to extend this pattern for custom file names?

- [ ] Yes
- [x] No

### Is the fileMatch pattern likely to get many "false hits" for files that have nothing to do with package management?

- [ ] Yes
- [x] No

---

## Parsing and Extraction

### Can package files have "local" links to each other that need to be resolved?

- [ ] Yes
- [x] No

### Is there a reason why package files need to be parsed together (in serial) instead of independently?

- [ ] Yes
- [x] No

### What format/syntax is the package file in?

- [ ] JSON
- [x] TOML
- [ ] YAML
- [x] Custom (explain below)

It is either a TOML file, or a legacy format which only contains the
version/channel. This can probably be detected by looking for `[toolchain]` in
the content of the file.

### How do you suggest parsing the file?

- [x] Off the shelf parser
- [ ] Using regex
- [ ] Custom-parsed line by line
- [x] Other

A regular TOML file parser if `[toolchain]` is detected, otherwise the first
line of the content can be taken directly as the version/channel value.

### Does the package file structure distinguish between different "types" of dependencies? e.g. production dependencies, dev dependencies, etc?

- [ ] Yes, production and development dependencies
- [x] No, all dependencies are treated the same

### List all the sources/syntaxes of dependencies that can be extracted

I'm not sure what this means... 🤔

### Describe which types of dependencies above are supported and which will be implemented in future

There is only a single dependency at this point, which is the toolchain
version/channel.

---

## Versioning

### What versioning scheme does the package file(s) use?

There are multiple valid values:

- `stable`
- `beta`
- `nightly`
- SemVer value (e.g. `1.56.0` or `1.56.0-beta.9`) for the `stable` and `beta` releases
- Datetime with `nightly-` prefix (e.g. `nightly-2020-08-29`)

### Does this versioning scheme support range constraints, e.g. `^1.0.0` or `1.x`?

- [ ] Supports range constraints (e.g `^1.0.0` or `1.x`)
- [ ] No

Very good question... I suppose the answer is "No", although channel specifiers
like `stable` could count as range constraints? 🤔

### Is this package manager used for applications, libraries, or both? If both, is there a way to tell which is which?

- [ ] Applications
- [ ] Libraries
- [x] Both (explain how to tell which is which)

rustup is used by both types, though I suspect that it might be more useful for
applications to use this package manager, since libraries might want to stay
on their minimum supported Rust version.

For detection: applications usually have a `src/main.rs`, while libraries usually
have a `src/lib.rs` file.

### If ranges are supported, are there any cases when Renovate should pin ranges to exact versions if rangeStrategy=auto?

It might make sense to replace e.g. `stable` with a pinned version, and
similar for `beta` and `nightly`.

---

## Lookup

### Is a new datasource required? Provide details

- [x] Yes, provide details.
- [ ] No.

The files at:

- https://static.rust-lang.org/dist/channel-rust-stable.toml
- https://static.rust-lang.org/dist/channel-rust-beta.toml
- https://static.rust-lang.org/dist/channel-rust-nightly.toml

provide metadata on the most recent releases of the corresponding release
channels (see https://github.com/rust-lang/rustup-components-history).

https://github.com/rust-lang/rust/releases has changelog information for the
releases of the `stable` channel. I'm not aware of changelog information for
the other channels at the moment.

### Will users need the capability to specify a custom host/registry to look up? Can it be found within the package files, or within other files inside the repository, or would it require Renovate configuration?

Not as far as I am aware.

### Do the package files contain any "constraints" on the parent language (e.g. supports only v3.x of Python) or platform (Linux, Windows, etc) that should be used in the lookup procedure?

It is possible to specify `targets` in the toolchain file, but I don't think
applies to this question.

### Will users need the ability to configure language or other constraints using Renovate config?

I don't think so.

---

## Artifacts

### Are lock files or checksum files used? Are they mandatory?

No

### If so, what tool and exact commands should be used if updating one or more package versions in a dependency file?

### If applicable, describe how the tool maintains a cache and if it can be controlled via CLI or env? Do you recommend the cache be kept or disabled/ignored?

### If applicable, what command should be used to generate a lock file from scratch if you already have a package file? This will be used for "lock file maintenance"

## Other

### Is there anything else to know about this package manager?

Anything else can be found at https://rust-lang.github.io/rustup/index.html

**Comment by Turbo87** [comment]
some more information on where to get a list of Rust releases is here: https://github.com/foresterre/rust-releases

**Comment by Turbo87** [comment]
As it turns out, this can be achieved using the existing `regex` manager.

I've created a shareable preset that implements this: https://github.com/Turbo87/renovate-config/blob/7cc52ff9/rust/updateToolchain.json

It can be used in other projects via:

```json
{
  "extends": [
    "github>Turbo87/renovate-config//rust/updateToolchain"
  ],
}
```

and will result in PRs like:

- https://github.com/Turbo87/segelflug-classifieds/pull/144
