### ISSUE TITLE
Detect terraform modules stored in private (GHE) GIT repos when using SSH

### ISSUE THREAD

**Issue by ocofaigh** [renovatebot/renovate#11571]
### What would you like Renovate to be able to do?

It seems renovate cannot detect terraform modules from private github (GHE) repos over SSH. 
Minimal reproduction repository created -> https://github.com/ocofaigh/private-terraform-module-ssh-example

### If you have any ideas on how this should be implemented, please tell us here.

Some conversation here -> https://github.com/renovatebot/renovate/discussions/11556

### Is this a feature you are interested in implementing yourself?

No

**Comment by ocofaigh** [comment]
By changing the syntax I managed to get this working - see https://github.com/renovatebot/renovate/discussions/11556#discussioncomment-1279208

Probably not such a priority now, but would be cool if renovate could do this under the hood some how. Although it may be a terraform limitation.

**Comment by secustor** [comment]
In that case please adapt the issue to represent the new scope.  The title/text should reference the `SCP` style Git addresses.

**Comment by ocofaigh** [comment]
The syntax is actually what terraform have in their documentation (see https://www.terraform.io/docs/language/modules/sources.html#generic-git-repository) so it may be an anti-pattern to make any changes in renovate. I am going to close this.
