### ISSUE TITLE
Gradle wrapper task should run two times in a row to update all files

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [renovatebot/renovate#11610]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Describe the bug

>Note that running the wrapper task once will update `gradle-wrapper.properties` only, but leave the wrapper itself in `gradle-wrapper.jar` untouched. This is usually fine as new versions of Gradle can be run even with ancient wrapper files. If you nevertheless want all the wrapper files to be completely up-to-date, you’ll need to run the wrapper task a **second time**.

https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

Not sure why but in my public repo I can't reproduce it (but not only with Renovate, manually I can't reproduce it), but in a private repo I am getting this issue with Renovate.

Because it is documented, is it necessary to add a minimal repro? The fix is just running the task two times in a row instead of only one time.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
So renovate should first update the properties so we only need one Gradle run.

**Comment by JavierSegoviaCordoba** [comment]
Personally, renovate should upgrade both or at least has an option to force it, because if not, I have to update it manually.

**Comment by viceice** [comment]
Currently renovate will already update the properties, but assets update function resets it and calls Gradle to update it.

So we should simply stop resetting and this issue would be resolved.

**Comment by Churro** [comment]
@JavierSegoviaCordoba, this issue should be fixed since PR https://github.com/renovatebot/renovate/pull/14495 and renovate v32.0.5. Can you please confirm?
