### ISSUE TITLE
"Target directory is expected to be absolute" for .terraform.lock.hcl

### ISSUE THREAD

**Issue by alkoclick** [renovatebot/renovate#11641]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

26.21.2

### Describe the bug

Hey folks!

At Zivver we've expanded our usage of Renovate to target infrastructure repositories built on Terraform. Last night Renovate targeted a fair amount of them, but for one repository we saw the issue below:

![image](https://user-images.githubusercontent.com/9469549/132502769-43d2b599-f4f0-4c28-b81e-a5465e9dba34.png)

This resulted in Renovate only committing a change to the required providers, but not in the lockfile, which then crashes on the pipelines as Terraform complains that:

```
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/vault: locked provider registry.terraform.io/hashicorp/vault
│ 2.22.1 does not match configured version constraint 2.23.0; must use
│ terraform init -upgrade to allow selection of new versions
╵
```

I haven't quite fully figured out what's causing this, but I can understand that this issue only shows up when trying to update providers, because that requires a lockfile update.

I can't quite share the entire repository, but the structure is like this:

- .terraform.lock.hcl
- versions.tf
- ...
- modules
  - module-1

Module-1 does have a required providers block, so I was thinking if for some reason renovate was trying to update a `.terraform.lock.hcl` file for it?

<details><summary>.terraform.lock.hcl</summary>

```
provider "registry.terraform.io/gitlabhq/gitlab" {
  version     = "3.7.0"
  constraints = "3.7.0"
  hashes = [
    "h1:89Pa83NutpdjTeiZbBk3hCM7iFAqtMBWM+3v1Wfm6Y0=",
    "zh:16addba6bda82e6689d21049392d296ce276cb93cbc5bcf3ad21f7d39cd820fd",
    "zh:1e9dd3db81a38d3112ddb24cec5461d919e7770a431f46ac390469e448716fd4",
    "zh:252c08d473d938c2da2711838db2166ecda2a117f64a10d279e935546ef7d991",
    "zh:2e0c83da0ba44e0521cb477dd60ea7c08b9edbc44b607e5ddb963becb26970a5",
    "zh:396223391782f1f809a60f045bfdcde41820d0d6119912718d86fc153fc28969",
    "zh:3a6b3c0901b81bc451d1ead2a2f26845d5db6b6253758c1f0aa0bad53fb6b4bd",
    "zh:51010e8f1d05f4979f0e10cf0e3b56cec13c731d99f373dda9fd9561ddb2826b",
    "zh:53ef55edf7698cbb4562265a6ab9e261716f62a82590e5fb6ad4f7f7458bdc5c",
    "zh:6c2db10e6226cc748e6dd5c1cbc257fda30cd58a175a32fc95a8ccd5cebdd3e7",
    "zh:91627f5af7e8315479a6c45cb1ae5db3c0a91a18018383cd409f3cfa04408aed",
    "zh:b5217a81cfc58334278831eacb2865bd8fc025b0cb1c576e9da9c4dc3a187ef5",
    "zh:c70afea4324518b099d23abc189dff22e6706ca0936de39eca01851e2550af7e",
    "zh:e62c212169ef9aad3b01f721db03b7e08d7d4acbbac67a713f06239a3a931834",
  ]
}

provider "registry.terraform.io/hashicorp/vault" {
  version     = "2.22.1"
  constraints = "2.22.1"
  hashes = [
    "h1:JTW2/i6KvsOaZ2XBP2At5tP0GZyENJ+a5W7EcBhrevQ=",
    "zh:0354ae21e4b53490c3a532004e817c8becdd0debdcdf4fc954bc70f267f3dfda",
    "zh:09477c72b8cbb3ffed58f8666f130685e5f3c99f91467c696174cdf118500d49",
    "zh:0f00c6b960e0cab4301cda379818079d2998cc0cc1a7eafd69395d1e6588e618",
    "zh:2fac74c205fc1e0c4b1d800fb7fd8091a4bbeaae254b5e98bdeed8757b53a115",
    "zh:620bf9b6e2ec0094e564f2668e4faddc9b557314d7725114b0cc33069933e8e3",
    "zh:aec176654fd7f30c012dfbed58b20f08286e8499150b80e280e70b33f3a4da58",
    "zh:b0ff022d70996170d43e8d1983404df85aea41eda1352453226d1f73f1b68897",
    "zh:bbaea8145b302717b3e7be1155820fc5ee486b002f1562ef40fd2f21e4303447",
    "zh:c9add1aeebef54418550338308f27926e1baae22f095ca53289f11a173dbf40b",
    "zh:cde7538aaf01b83656cf8b1f70ca7259eac41a586f2c2fbcc7bf4a384dcade26",
    "zh:f07a9a32366d33a7d2ad763c099563ea547f3e208b77ae3fb9e5894fd92a696a",
  ]
}
```

</details>

<details><summary>versions.tf</summary>

```
terraform {
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = "2.22.1"
    }
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "3.7.0"
    }
  }
  required_version = ">= 1.0"
}

```

</details>

### Relevant debug logs

<details><summary>Logs</summary>

```
 INFO: Autodiscovered repositories
       "length": 1,
       "repositories": ["infra/gitlab-root"]
 INFO: Repository started (repository=infra/gitlab-root)
       "renovateVersion": "26.21.2"
 INFO: Dependency extraction complete (repository=infra/gitlab-root)
       "baseBranch": "main",
       "stats": {
         "managers": {"terraform": {"fileCount": 10, "depCount": 33}},
         "total": {"fileCount": 10, "depCount": 33}
       }
 INFO: Branch updated (repository=infra/gitlab-root, branch=renovate/vault-2.x)
       "commitSha": "0dd392f"
 INFO: PR updated (repository=infra/gitlab-root, branch=renovate/vault-2.x)
       "pr": 54,
       "prTitle": "Update Terraform vault to v2.23.0"
 WARN: artifactErrors (repository=infra/gitlab-root, branch=renovate/vault-2.x)
       "artifactErrors": [
         {
           "lockFile": ".terraform.lock.hcl",
           "stderr": "Target directory is expected to be absolute"
         }
       ]
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by alkoclick** [comment]
Hey, I don't think I can provide a reproducible example here because I don't quite understand what is needed to reproduce the issue and I was hoping for at least some clues :/ . I don't mind doing the legwork to investigate further, but I'd appreciate some basic direction because I couldn't even find any relevant results when googling

**Comment by viceice** [comment]
We don't know either whats going on. 🤷‍♂️  So we need a simple reproducer.

So please create a new public repo with the lockfile and the versions files. That should hopefully reproduce the issue

**Comment by secustor** [comment]
Please also add your global Renovate config as you are using a self hosted instance. 

I have the feeling that you are overwriting the temporary folders with a relative path.

**Comment by alkoclick** [comment]
> Please also add your global Renovate config as you are using a self hosted instance.

This one I can do immediately, for a repro repo I will need some time.

<details><summary>config.js</summary> 

```
const project = process.env.PROJECT;

if(project === undefined) {
	console.error('Please provide a PROJECT variable to update');
	process.exit(1);
}

module.exports = {
    platform: 'gitlab',
    endpoint: 'https://redacted/api/v4/',
    token: process.env.ZBOT_TOKEN,
    cacheDir: './cache/renovate',
    autodiscover: true,
    autodiscoverFilter: project,
    logLevel: 'debug',
    requireConfig: true,
    onboarding: true,
    onboardingConfig: {
        extends: ['config:base'],
        prConcurrentLimit: 3,
    },
    enabledManagers: [
        'npm', 'sbt', 'terraform'
    ],

	branchPrefix: "renovate/",
	labels: ["type :: dependency-updates"],

    packageRules: [
        {
            "matchPackageNames": ["@zivver/webapp","@zivver/api"],
            "enabled": false
        }
    ],
};
```

</details>

We pass in the PROJECT arg in this way from gitlab-ci:

```
infra:
  extends:
    - .renovate_job
  variables:
    PROJECT: "infra/gitlab-root*"
```

**Comment by alkoclick** [comment]
> I have the feeling that you are overwriting the temporary folders with a relative path.

That may have been quite spot on, I see that without the cache in my config, it works successfully

**Comment by alkoclick** [comment]
I can confirm that we've solved the problem by removing the use of the relative path `cacheDir: './cache/renovate',` in conjunction with Gitlab caches. I don't know if this falls within some existing known issue. 

Let me know if you'd still appreciate some repro repo to investigate this deeper. 

Either way, thank you very, very much for the prompt help to both and I'm sorry I couldn't initially be as useful as I'd like :)

**Comment by viceice** [comment]
https://gitlab.com/renovate-bot/renovate-runner

Checkout our gitlab templates for best catching settings.
