### ISSUE TITLE
Badly spelled words in code `versionings`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#11694]
### Describe the proposed change(s).

We use `versionings` and `versionig` in our code in some places, both of which are spelled wrong... 🙈 

I found them by doing a search for both these strings in our `*.ts` files. But we might have more instances lurking somewhere.

`versionings` is not a proper English word, or at least my spell checker doesn't think so.

I think we have two options:

1. Use singular noun: `versioning`
2. Use plural noun: `versions`

I originally found this problem in PR: https://github.com/renovatebot/renovate/pull/11429#discussion_r697326021

I already opened a PR to fix the `versionig` in a spec file: #11693, so that's one of the bad spellings gone.
But we still need to decide what to do with `versionings`... 😉

**Comment by RahulGautamSingh** [comment]
I found ```versionings``` in these 3 files:
1. ```/workspaces/renovate/lib/versioning/index.spec.ts```
2.  ```/workspaces/renovate/lib/versioning/versioning-metadata.spec.ts```
3.  ```/workspaces/renovate/lib/workers/repository/init/vulnerability.ts```
Do you want them changed or let them be for now?

**Comment by rarkins** [comment]
We can use eg allVersioning

**Comment by RahulGautamSingh** [comment]
Can you assign it to me , I will start working on it.

**Comment by RahulGautamSingh** [comment]
> We can use eg allVersioning

allVersioning is already in use.

**Comment by RahulGautamSingh** [comment]
I googled ```versioning``` and it turns out that we cannot use ```versions``` inplace of ```versionings``` because ```versionings``` is not a word and even if we want to use it then it will have different meaning to ```versions```.

**Comment by rarkins** [comment]
I prefer we move on, this issue is really not important as these variable names are entirely internal. "Versioning" is a Renovate term
