### ISSUE TITLE
Onboarding commit message and semantic commits

### ISSUE THREAD

**Issue by sfirmery** [renovatebot/renovate#11716]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

docker image `renovate/renovate:27.6.4`

### Describe the bug

Onboarding commit message is not using semantic commit format although the repository use it.

I use a git repository with more than 10 commit using semantic commit and `conventional-commits-detector` detect it as `angular`.

In debug, we can see that the pull request and the onboarding commit are done before detecting semantic commits. And that  `detectSemanticCommits()` detect `angular` as expected.

I make it working by editing `lib/workers/repository/init/config.ts` and moving `detectSemanticCommits()` before `checkOnboardingBranch()`. I can create a merge request for this change.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Need to create onboarding PR (repository=renovate_test/renovate_test)
DEBUG: createOnboardingBranch() (repository=renovate_test/renovate_test)
...
DEBUG: Creating onboarding branch (repository=renovate_test/renovate_test)
DEBUG: Committing files to branch renovate/configure (repository=renovate_test/renovate_test)
DEBUG: git commit (repository=renovate_test/renovate_test)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/configure",
         "commit": "9e63dcd",
         "root": false,
         "summary": {"changes": 1, "insertions": 3, "deletions": 0}
       }
...
DEBUG: detectSemanticCommits() (repository=renovate_test/renovate_test)
DEBUG: getCommitMessages (repository=renovate_test/renovate_test)
DEBUG: Semantic commits detection: angular (repository=renovate_test/renovate_test)
DEBUG: angular semantic commits detected (repository=renovate_test/renovate_test)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
Running renovate from source is not supported for production workloads! It's should only used for test / development.
