### ISSUE TITLE
Retrieve changelog from Gitlab `git::ssh://` urls (in Terraform manager?)

### ISSUE THREAD

**Issue by syphernl** [renovatebot/renovate#11757]
### What would you like Renovate to be able to do?

We make use of a lot of custom (in-house developed) Terraform modules we refer to like so:

```
module "foo" {
source = "git::ssh://git@gitlab.com/ORG/NAMESPACE/some-terraform-module.git?ref=v0.2.0"
....
}
```

These repo's have been tagged with semantic versions and releases available for them, but unfortunately Renovate does not retrieve the changelogs to add to the MR. 
It would be nice if it would be able to do so.

### If you have any ideas on how this should be implemented, please tell us here.

Retrieve the changelogs by using the `gitlab.com/ORG/NAMESPACE/some-terraform-module.git` portion

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Please create a reproduction so we can see how they are extracted or skipped today. The host/org/repo can be sanitized if necessary as long as it reproduces the problem.
