### ISSUE TITLE
Add retry/rebase checkbox to the onboarding (configure renovate) pull requests

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#11770]
### What would you like Renovate to be able to do?

Add retry/rebase checkbox to the onboarding (configure renovate) pull requests

### If you have any ideas on how this should be implemented, please tell us here.

Add retry/rebase checkbox to the onboarding (configure renovate) pull requests

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
What problem are you needing to solve? e.g. onboarding PR is not up to date with main branch, or you wish to reset/discard any custom config changes you've made?

**Comment by ChipWolf** [comment]
> What problem are you needing to solve? e.g. onboarding PR is not up to date with main branch, or you wish to reset/discard any custom config changes you've made?

The former, sometimes I don't get around to configuring renovate, and the base branch is ahead of the PR.
The dependency update PRs have a checkbox to retry/rebase whereas the onboarding PR does not @rarkins

**Comment by HonkingGoose** [comment]
Closed by PR:

- #17633
