### ISSUE TITLE
prHourlyLimit is not working on 25+ version of renovate docker image

### ISSUE THREAD

**Issue by XFNeo** [renovatebot/renovate#11782]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:27-slim

### Describe the bug

I'm using you docker image [renovate/renovate:27-slim](https://hub.docker.com/layers/renovate/renovate/27-slim/images/sha256-d2894e1390151dcce3f9ec41ed10f2519bfbb00f682752ad5d2b7ef2df9235b8?context=explore). 
I have property "prHourlyLimit": 20 in config, but renovate always сalculating hourly PRs remaining = 2 for all my repository. If I remove this property nothing changes. 
I have tried to run renovatebot in next our - the same result.
On renovate/renovate:24-slim it works properly.

My config:
{
    "labels": ["Dependency Bot"],
    "repositories": [
        ${REPOSITORIES}
    ],
    "extends": ["config:base"],
	"prHourlyLimit": 20,
	"branchConcurrentLimit": 20,
	"prConcurrentLimit": 20,
	"commitMessagePrefix": "PSUP-0000",
    "packageRules": [
	  {
        "matchPackagePatterns": ["*"],
        "allowedVersions": "!/redhat|composite|groovyless|jboss|atlassian/"
      },
	  {
        "matchPackageNames": ["org.reflections:reflections"],
        "allowedVersions": "!/0.9.12|redhat/"
      },
      {
        "matchPackageNames": ["com.xxx.cloud.junit:cloud-extension"],
        "allowedVersions": "!/^3.*/"
      },
	  {
        "matchPackageNames": ["org.jboss.arquillian.junit:arquillian-junit-standalone", "io.undertow:undertow-core"],
        "enabled": false
      },	  
      {
        "groupName": "spring",
        "matchPackagePatterns": [
          "^org.springframework*"
        ],
        "separateMinorPatch": false
      },
      {
        "groupName": "quarkus",
        "matchPackagePatterns": [
          "^io.quarkus"
        ],
        "separateMinorPatch": false
      },
      {
        "groupName": "com.xxx.cloud",
        "matchPackagePatterns": [
          "^com.xxx.cloud"
        ],
        "separateMinorPatch": false
      },
      {
        "matchManagers": ["maven"],
        "registryUrls": [
            "https://artifactory.xxx.com/pd.saas-release.mvn.group"
        ]
      },
      {
        "matchUpdateTypes": ["major"],
        "labels": ["Dependency Bot","UPDATE-MAJOR"]
      },
      { 
        "matchUpdateTypes": ["minor", "patch", "pin", "digest"], "automerge": false 
    }],
    "recreateClosed": true,
    "separateMinorPatch": true,
    "gitLabAutomerge": true,
    "rebaseWhen": "behind-base-branch"
}

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Processing 0 branches:  (repository=PROD/config-server)
DEBUG: Calculating hourly PRs remaining (repository=PROD/config-server)
DEBUG: currentHourStart=2021-09-16T15:00:00.000+00:00 (repository=PROD/config-server)
DEBUG: PR hourly limit remaining: 2 (repository=PROD/config-server)
DEBUG: Calculating prConcurrentLimit (20) (repository=PROD/config-server)
DEBUG: 0 PRs are currently open (repository=PROD/config-server)
DEBUG: PR concurrent limit remaining: 20 (repository=PROD/config-server)
DEBUG: Calculated maximum PRs remaining this run (repository=PROD/config-server)
       "prsRemaining": 2
DEBUG: PullRequests limit = 2 (repository=PROD/config-server)
DEBUG: Calculating hourly PRs remaining (repository=PROD/config-server)
DEBUG: currentHourStart=2021-09-16T15:00:00.000+00:00 (repository=PROD/config-server)
DEBUG: PR hourly limit remaining: 2 (repository=PROD/config-server)
DEBUG: Calculating branchConcurrentLimit (20) (repository=PROD/config-server)
DEBUG: 0 already existing branches found:  (repository=PROD/config-server)
DEBUG: Branch concurrent limit remaining: 20 (repository=PROD/config-server)
DEBUG: Calculated maximum branches remaining this run (repository=PROD/config-server)
       "branchesRemaining": 2
DEBUG: Branches limit = 2 (repository=PROD/config-server)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
It's because you're extending config:base, which is evaluated later than the prHourlyLimit setting in your global config.

**Comment by XFNeo** [comment]
@rarkins thanks for quick answer, where I can inspect this config?

**Comment by rarkins** [comment]
@XFNeo You can see it's subcomponents here: https://docs.renovatebot.com/presets-config/#configbase
