### ISSUE TITLE
RenovateBot not able to git clone private repo on same host 

### ISSUE THREAD

**Issue by thomasLeclaire** [renovatebot/renovate#11781]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Hello, 

I allowed renovatebot on all my github orga and configured it one repo. 
This repo is a rails app which use bundler, ie some Gemfile and Gemfile.lock. 
In this Gemfile, I use some gem created into some other private repo of my orga. 

Renovate is not able to git clone this private repo. It's working with some public repos (in or outside of the orga). 

According to the doc here : https://docs.renovatebot.com/modules/manager/bundler/#authenticating-private-registry
I understand I should not need to add anything more to be able to execute renovate. 

### Relevant debug logs

<details><summary>Logs</summary>

```
`  "err": {
    "killed": false,
    "code": 11,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/Effilab/fb-trust\":\"/mnt/renovate/gh/Effilab/fb-trust\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/Effilab/fb-trust\" docker.io/renovate/ruby:2.6.5 bash -l -c \"ruby --version && gem install bundler -v 2.1.2 && bundle lock --update \"",
    "stdout": "ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]\nSuccessfully installed bundler-2.1.2\n1 gem installed\nFetching https://github.com/Effilab/bonita.git\nFetching https://github.com/effilab/fea.git\n\n\n\n\n",
    "stderr": "fatal: could not read Username for 'https://github.com': No such device or address\nRetrying `git clone 'https://github.com/effilab/fea.git' \"/tmp/renovate-cache/others/bundler/cache/bundler/git/fea-e822a0dee4b146ac2eafd5437fa38a6479e7954d\" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/effilab/fea.git' \"/tmp/renovate-cache/others/bundler/cache/bundler/git/fea-e822a0dee4b146ac2eafd5437fa38a6479e7954d\" --bare --no-hardlinks --quiet` in directory ...````

</details>


### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Are they both private repos?

**Comment by thomasLeclaire** [comment]
yes, both repos are private

**Comment by thomasLeclaire** [comment]
I know it's a bot reply but as said no possible public reproduction. 

as workaround, I explictly declare some github account thanks to host rule.

**Comment by rarkins** [comment]
What we would need is this:

- Create a two new private repos: one to be the upstream and one the downstream
- Configure the downstream repo so that it works for you locally
- Install the bot into both repos (presumably it then reproduces the failure)
- Save the log of the bot's failure to update (app.renovatebot.com)
- Uninstall the bot from both repos
- Switch the repos to both be public

If the OP has already solved it another way and prefers not to do this, then we should close this issue as it won't get worked on by anyone without a reproduction first.
