### ISSUE TITLE
Support `packageManager` property in `package.json` for JavaScript projects

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#11808]
### What would you like Renovate to be able to do?

I created this new issue based on discussion #11800.

Comment from @travi:

> The [release notes of v16.9.0 of node.js](https://github.com/nodejs/node/releases/tag/v16.9.0) highlight Corepack for helping projects specify and simplify use of the preferred package manager for the project.
> 
> This is driven by a [`packageManager` property in the package.json](https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#packages_packagemanager). the property enables specifying both the name of the package manager and the version. i see this as a potentially very helpful way to encourage a team to use the same version across the team, but I am wondering if that value growing stale over time could have negative impacts.
> 
> Have you considered management of this version number through renovate so that it could be updated as new versions of the [supported package managers](https://nodejs.org/dist/latest-v16.x/docs/api/corepack.html#corepack_supported_package_managers) become available? (npm is not yet supported by corepack, but is a valid value for the packageManager property. I would find it valuable to apply similar updates when npm is specified, in hopes that it will be added to the corepack supported managers list at some point.)

### If you have any ideas on how this should be implemented, please tell us here.

Quote from @rarkins:

> Yes, I think that's a good idea and should be able to be added to the `npm` package manager in Renovate pretty easily. Alternatively it could be split into a new manager if anyone feels strongly

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
I think this is now supported.

- #12088

**Comment by travi** [comment]
just to clarify, is the current implementation limited to yarn, like the title of that PR suggests? if so, is there a plan to support pnpm or npm? pnpm is already a [supported package manager](https://nodejs.org/dist/latest-v16.x/docs/api/corepack.html#corepack_supported_package_managers) through corepack and npm is a [valid option for the `packageManager` property](https://nodejs.org/dist/latest-v16.x/docs/api/corepack.html#how-does-corepack-currently-interact-with-npm).

is it worth keeping this open for supporting package managers beyond yarn, if they arent already included in the implementation?

**Comment by travi** [comment]
i think the desired update behavior would be the same across managers, so if the existing implementation already handles that correctly for the defined manager, i'd bet this is good to go. the PR didnt make it clear to me if the update was limited to yarn or would apply to all. thanks for the clarification!
