### ISSUE TITLE
Renovatebot hangs on "git commit"

### ISSUE THREAD

**Issue by Turbo87** [renovatebot/renovate#11813]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.14.0 (previously 26.21.7)

### Describe the bug

After updating renovatebot to v27 it hangs forever on the `git commit` step, unfortunately without any kind of error message.

I expect this to be related to https://github.com/renovatebot/renovate/pull/11401, but I'm not sure what to do about it.

We are currently running renovatebot on the `node:16` Docker image, in case that matters. Sadly, I've not been able to reproduce this outside of our setup here yet.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found 4 comments (repository=npm-packages/qonto-ui-kit, branch=deps-bf52376594)
DEBUG: 2 file(s) to commit (repository=npm-packages/qonto-ui-kit, branch=deps-bf52376594)
DEBUG: Committing files to branch deps-bf52376594 (repository=npm-packages/qonto-ui-kit, branch=deps-bf52376594)
DEBUG: Setting git author name (repository=npm-packages/qonto-ui-kit, branch=deps-bf52376594)
       "gitAuthorName": "Renovate Bot"
DEBUG: Setting git author email (repository=npm-packages/qonto-ui-kit, branch=deps-bf52376594)
       "gitAuthorEmail": "bot@renovateapp.com"
DEBUG: git commit (repository=npm-packages/qonto-ui-kit, branch=deps-bf52376594)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "deps-bf52376594",
         "commit": "9d9d346d",
         "root": false,
         "summary": {"changes": 2, "insertions": 84, "deletions": 42}
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by Turbo87** [comment]
now that I think about it, since the debug output already has a `commit` value, maybe it's the step **after** `git commit` that freezes, not the `git commit` itself 🤔

**Comment by rarkins** [comment]
Perhaps the `git push` stage? Are you able to get logs from GitLab?

BTW we don't support / have not tested against Node 16

**Comment by Turbo87** [comment]
> we don't support / have not tested against Node 16

interesting. we ran into different issues when still running renovatebot on Node 14, which is why we upgraded to 16. unfortunately I don't recall what exactly these issues were.

> Are you able to get logs from GitLab?

only the debug logs from renovatebot and those stop after the `git commit` output

**Comment by viceice** [comment]
also please verify that you have git > v2.33

best is you use our `renovate/node:14` image it has required git version installed.

**Comment by Turbo87** [comment]
> best is you use our `renovate/node:14` image it has required git version installed.

I will try that. thanks :)

one other thing to note is that unfortunately the dry run does not experience the same problem, but it looks like that also never runs the `git commit` command, so it won't catch that issue.

**Comment by viceice** [comment]
@rarkins I think we can movwe this to discussions, as i don't see a renovate bug here. I'm using renovate v27.12.0 successfully on gitlab v14.2.3.

**Comment by Turbo87** [comment]
we can actually close it, apparently. using `renovate/node:14` with v27 does seem to resolve the issue. thanks @viceice! :)
