### ISSUE TITLE
renovatebot ignores semanticCommitTypeAll

### ISSUE THREAD

**Issue by dirien** [renovatebot/renovate#11815]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

I set up semantic comitts acording the doc -> https://docs.renovatebot.com/semantic-commits/ 

But somehow renovatebot ignores the `semanticCommitTypeAll` and don't use a semantic commit message...

The public repo ist: https://github.com/dirien/minectl

renovate.json
```json
{
  "extends": [
    "config:base",
    ":semanticCommitTypeAll(chore)"
  ],
  "postUpdateOptions": [
    "gomodTidy"
  ],
  "dependencyDashboard": false,
  "labels": [
    "dependencies"
  ]
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
    "**/__fixtures__/**"
  ]
}
DEBUG: detectSemanticCommits()
DEBUG: No vulnerability alerts found
DEBUG: No vulnerability alerts found
DEBUG: No baseBranches
DEBUG: extract()
DEBUG: Found cached extract
{
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Looks like you need to set `"semanticCommits": true` in your config too.

**Comment by dirien** [comment]
@rarkins, that helped much! Thx ❤️ !

![image](https://user-images.githubusercontent.com/38325136/134713066-cf4eac72-3e0f-4ce9-a389-ffb3506c28fb.png)

It was not clear, that this is missing from the docs -> https://docs.renovatebot.com/semantic-commits/

**Comment by rarkins** [comment]
PR welcome

**Comment by rarkins** [comment]
Actually I think the docs are pretty clear about manually enabling semantic commits
