### ISSUE TITLE
Failing to detect and update some package.json files

### ISSUE THREAD

**Issue by Methuselah96** [renovatebot/renovate#11823]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Describe the bug

It appears that Renovate is failing to update some of the `package.json` files within [the `redux-devtools` repository](https://github.com/reduxjs/redux-devtools). It seems like the `package.json`s that are failing to update are the private ones included as a Yarn Workspace but that could be a coincidence. For example it's failing to update [this `package.json` file](https://github.com/reduxjs/redux-devtools/blob/main/packages/react-json-tree/examples/package.json) in [this PR](https://github.com/reduxjs/redux-devtools/pull/860) (`eslint-plugin-react` and `@types/node` are examples of two dependencies it's failing to update). This has been happening for all the logs listed in the dashboard (the past 3 days). As far as I can tell, it's always failed to update these.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Writing package.json files(branch="renovate/all-minor-patch")
{
  "packageFiles": [
    "extension/package.json",
    "package.json",
    "packages/d3-state-visualizer/package.json",
    "packages/d3tooltip/package.json",
    "packages/map2tree/package.json",
    "packages/react-base16-styling/package.json",
    "packages/react-dock/package.json",
    "packages/react-json-tree/package.json",
    "packages/redux-devtools-app/package.json",
    "packages/redux-devtools-chart-monitor/package.json",
    "packages/redux-devtools-cli/app/package.json",
    "packages/redux-devtools-cli/package.json",
    "packages/redux-devtools-dock-monitor/package.json",
    "packages/redux-devtools-extension/package.json",
    "packages/redux-devtools-inspector-monitor-test-tab/package.json",
    "packages/redux-devtools-inspector-monitor-trace-tab/package.json",
    "packages/redux-devtools-inspector-monitor/package.json",
    "packages/redux-devtools-instrument/package.json",
    "packages/redux-devtools-log-monitor/package.json",
    "packages/redux-devtools-rtk-query-monitor/package.json",
    "packages/redux-devtools-serialize/package.json",
    "packages/redux-devtools-slider-monitor/package.json",
    "packages/redux-devtools-ui/package.json",
    "packages/redux-devtools-utils/package.json",
    "packages/redux-devtools/package.json"
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
If you locate the `packageFiles with updates` log, what does it say about `eslint-plugin-react` in the particular package file you've picked out?

**Comment by Methuselah96** [comment]
Sorry, the full log was too big for me to post in the description. [Here](https://gist.github.com/Methuselah96/213b92c4da9fc9281232bc268439d5c4)'s the full text.

The logs don't include anything in the `packageFiles with updates` for the particular package file that it's failing to update.

**Comment by Methuselah96** [comment]
Figured it out, it's because one of the default ignore paths is `"**/examples/**"`. I'm curious why those are ignored as part of the `:ignoreModulesAndTests` preset? Thanks for your help. Sorry for the bother.

**Comment by rarkins** [comment]
Because most people don't want examples updated.
