### ISSUE TITLE
mix.lock not updated when using an Elixir umbrella app

### ISSUE THREAD

**Issue by tpbowden** [renovatebot/renovate#11851]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Describe the bug

When using an Elixir/Mix umbrella application, Renovate is not updating the `mix.lock` file when updating dependencies in the `mix.exs` file of any of the apps within the umbrella, only when it changes the root `mix.exs` file. I believe the issue originated here: https://github.com/renovatebot/renovate/pull/10689. 

Minimal reproduction repo here:
https://github.com/tpbowden/renovate-umbrella-reproduction

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: mix.getArtifacts(apps/demo_app/mix.exs)(branch="renovate/plug-1.x")
DEBUG: No mix.lock found(branch="renovate/plug-1.x")
DEBUG: Updated 1 package files(branch="renovate/plug-1.x")
DEBUG: No updated lock files in branch(branch="renovate/plug-1.x")
DEBUG: 1 file(s) to commit(branch="renovate/plug-1.x")
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment]
Looks like we need to search in current and parent dirs for lockfile.

**Comment by tpbowden** [comment]
I think this should fix it: https://github.com/renovatebot/renovate/pull/11854
