### ISSUE TITLE
Decrease `:prConcurrentLimit` from 20 to 10 in our `config:base` preset

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#11909]
### What would you like Renovate to be able to do?

We recently changed our documentation to recommend that most people set their `prConcurrentLimit` to something lower than the default of 20 that comes with our `config:base` present.

It might be good to change the `config:base` preset so that end-users follow this new recommendation automatically.

See this comment from the head maintainer: https://github.com/renovatebot/renovate/pull/11879#discussion_r715500459

### If you have any ideas on how this should be implemented, please tell us here.

We already have a `:prConcurrentLimit10` preset that we could extend from in our `config:base` preset.
We could change this line here to use that lower limit:

https://github.com/renovatebot/renovate/blob/42bef1e9398e5ef87a883ac2dd2755a0ec679e20/lib/config/presets/internal/config.ts#L12

I tried doing this without changing anything else, and it breaks the Jest tests, so we probably need to do a bit more than just changing this line... 😄 😉 

We would also need to change the documentation again, as we mention the number 20 in this file: https://github.com/renovatebot/renovate/blob/main/docs/usage/configuration-options.md

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment]
@rarkins How do you feel about lowering the `:prConcurrentLimit` in our `config:base` preset from 20 to 10?

**Comment by rarkins** [comment]
Let's do it next breaking change

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by rarkins** [comment]
Let's combine this with our next major release
