### ISSUE TITLE
Composer: problem with locked versions without patch part (x.y.Z)

### ISSUE THREAD

**Issue by mbrodala** [renovatebot/renovate#11952]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Having a Composer dependency locked with a `version` without patch part lets Renovate fail to process any updates for this package.

Example: https://github.com/mbrodala/renovate-composer-lock-without-patch

Here [`php-parallel-lint/php-console-highlighter`](https://packagist.org/packages/php-parallel-lint/php-console-highlighter) is installed via `^0.4.0` which ends up as `v0.4` in the `composer.lock`:

https://github.com/mbrodala/renovate-composer-lock-without-patch/blob/22e9377849265e6b8c5005d3e7bce77b523a0cb7/composer.lock#L59

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: getNewValue error
{
  "err": {
    "message": "Invalid Version: 0.4",
    "stack": "TypeError: Invalid Version: 0.4\n    at new SemVer (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/semver/classes/semver.js:38:13)\n    at major (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/semver/functions/major.js:2:29)\n    at replaceCaretValue (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/npm/range.js:11:45)\n    at Object.getNewValue (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/npm/range.js:178:20)\n    at getNewValue (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/composer/index.js:131:30)\n    at Object.getNewValue (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/composer/index.js:90:16)\n    at generateUpdate (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/generate.js:26:38)\n    at lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:188:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async fetchDepUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/fetch.js:39:21)\n    at async /home/ubuntu/renovateapp/node_modules/p-map/index.js:57:22"
  },
  "currentValue": "^0.4.0",
  "rangeStrategy": "update-lockfile",
  "currentVersion": "0.4",
  "newVersion": "0.5"
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment]
I think we have an open PR to update the composer versioning. Can you try it?

**Comment by mbrodala** [comment]
Sure, if you let me know which PR it is an how I can test with the Github Renovate app.

**Comment by viceice** [comment]
Ok, seems i was wrong with open PR. 🤦‍♂️

 You can't test renovate source with hosted app. 😅

**Comment by mbrodala** [comment]
I can also test with a self-hosted GitLab instance if that helps.

**Comment by viceice** [comment]
Ok, thanks. I think we need to do some more coerce on composer ranges before passing to semver.

**Comment by PhilipAbed** [comment]
problem is on this line in semver
![image](https://user-images.githubusercontent.com/42116482/159156293-4c01481f-3584-4ed7-b329-a964fa49718a.png)

**Comment by PhilipAbed** [comment]
do you mean that we need to convert the `0.4` to `0.4.0` in this case?

**Comment by mbrodala** [comment]
@PhilipAbed That would be a sensible normalization since the `.0` is indeed implicit here. (as would be `1.0.0` for `1`)

**Comment by PhilipAbed** [comment]
@mbrodala The Expected results are important to understand, After reading and investigating this issue, i found out that this can be solved with just converting the `0.4` to `0.4.0`, 
if this is all that's expected then we can start solving this.
but i asked for clarification just to make sure This is the right way to solve the issue..
there might be other ways im not familiar with.

**Comment by mbrodala** [comment]
Technically `0.4` is [not a valid SemVer version](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions).

So the actual behavior is undefined, but Composer chose to fall back to `0` if any part of a version is missing:

https://github.com/composer/semver/blob/3953f23262f2bff1919fc82183ad9acb13ff62c9/src/VersionParser.php#L137-L141

**Comment by PhilipAbed** [comment]
i see, Thanks for the info and clarifications!

**Comment by MaronHatoum** [comment]
hi @mbrodala 
is this the expected PR?
https://github.com/MaronHatoum/renovate-composer-lock-without-patch/pull/2

**Comment by mbrodala** [comment]
@MaronHatoum I've linked the repository in the OP, so yes, your fork looks similar.

Not sure how I could test your fix though ...

**Comment by mbrodala** [comment]
Thanks a lot, that did the trick!

See:

- https://github.com/mbrodala/renovate-composer-lock-without-patch/pull/5/files
  
  ![image](https://user-images.githubusercontent.com/5037116/171122615-143b475f-8846-4223-84ac-5ece0e9dc294.png)

- https://github.com/mbrodala/renovate-composer-lock-without-patch/pull/6/files

  ![image](https://user-images.githubusercontent.com/5037116/171122707-17e82a69-aef8-47b2-98b2-db6d7e4e5996.png)
