### ISSUE TITLE
Unable to use docker registry URLs that aren't based at the server root

### ISSUE THREAD

**Issue by zer0keefie** [renovatebot/renovate#11981]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

Bitbucket Cloud (bitbucket.org)

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.25.0

### Describe the bug

After updating from version 24.119, I noticed that our Docker images weren't being suggested as updates. It seems that after https://github.com/renovatebot/renovate/pull/10996, the custom registry URL I'm using is being rewritten incorrectly. We use JFrog Artifactory as our internal docker registry, and it wants urls to be of the form https://artifactory-host/artifactory/api/docker/docker/v2/etc. With the URL rewrite, the /v2 is being added to the start of the path, while we need it at the end.

I've temporarily worked around the issue by patching out the `ensurePathPrefix` call at https://github.com/renovatebot/renovate/blob/02f7253638c07923b2c7f23c4621db7b1b1d2158/lib/datasource/docker/index.ts#L71 and updating the registryUrls setting to have the /v2 in the right place.

### Relevant debug logs

<details><summary>Logs</summary>

Renovate log:
```
DEBUG: Datasource 404 (repository=<omitted>)
       "datasource": "docker",
       "lookupName": "grafana/grafana",
       "url": "https://internal.artifactory.url/v2/artifactory/api/docker/docker/grafana/grafana/tags/list?n=10000"
DEBUG: Failed to look up dependency grafana/grafana (repository=<omitted>, packageFile=resources/grafana/common/grafana.yaml, dependency=grafana/grafana)
```

Curl, with the corrected URL:
```
# curl -v 'https://internal.artifactory.url/artifactory/api/docker/docker/v2/grafana/grafana/tags/list' --header 'Authorization: Bearer <token>'
> GET /artifactory/api/docker/docker/v2/grafana/grafana/tags/list HTTP/1.1
> Host: sensus-artifactory-community.lab.sensus.net
> User-Agent: curl/7.73.0
> Accept: */*
> Authorization: Bearer <token>
>

< HTTP/1.1 200 OK
< Date: Fri, 01 Oct 2021 18:18:00 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: Artifactory/6.23.30
< X-Artifactory-Id: <omitted>
< Docker-Distribution-Api-Version: registry/2.0

[body omitted]
```

Relevant part of config.json:
```
{
  "packageRules": [ {
    "matchDatasources": ["docker"],
    "registryUrls": ["https://internal.artifactory.url/artifactory/api/docker/docker/v2"]
  } ]
}
```
</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
That `v2` in middle of an url violates docker api. Im pretty use it won't work for docker cli.

I've recently verified current renovate behavior against free hosted artifactory.
