### ISSUE TITLE
Configurable Shareable Config Preset Branch

### ISSUE THREAD

**Issue by 56KBs** [renovatebot/renovate#12005]
### What would you like Renovate to be able to do?

We're heavily making use of [shareable config presets](https://docs.renovatebot.com/config-presets/#local-presets) to reduce duplicate configuration - However, testing the changes for these configuration presets prove difficult before merging them to our main branch.

It would be nice to be able configure the branch name to load for a shareable config, so that it can more easily be tested, rather than having to create an entirely new repository in order to test the changes.

### If you have any ideas on how this should be implemented, please tell us here.

Potential example: `local>abc/foo^branch-name` Where `^` signifies the branch name you want to use

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment]
I think #11565 will solve your request

**Comment by karlhorky** [comment]
@viceice to use the new GitHub default branch `main`, does #11565 mean that a configuration of the following is needed?

```
| GitHub default with a tag   | `github>abc/foo#main` 
```

Or is the default `main` branch supported by default?

**Comment by viceice** [comment]
Renovate uses the default branch, so `main` should work as is.

- fixed in #11565

**Comment by karlhorky** [comment]
> Renovate uses the default branch, so `main` should work as is.

Yep it does, confirmed now, thanks!
