### ISSUE TITLE
helm-requirements - support private git repositories

### ISSUE THREAD

**Issue by dudicoco** [renovatebot/renovate#12093]
### What would you like Renovate to be able to do?

https://github.com/renovatebot/renovate/pull/8316 documented the use of a private helm repository.

We are a hosting a private helm repository within GitHub - https://blog.softwaremill.com/hosting-helm-private-repository-from-github-ff3fa940d0b7

Since we are using the renovate app, renovate already has access to that github repository, so I would expect it to be able to access the helm repository without providing it with credentials.

As a side note, I think the docs were added in the wrong file - `docs/usage/docker.md`, instead of within the `helm-requirements` docs.

### If you have any ideas on how this should be implemented, please tell us here.

Perhaps the github token can be taken from an environment variable and passed as credentials when adding the helm repo.

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment]
> As a side note, I think the docs were added in the wrong file - `docs/usage/docker.md`, instead of within the `helm-requirements` docs.

Can you give some more details and links? What published page has the wrong information? And where do you think the information should go?

**Comment by dudicoco** [comment]
> > As a side note, I think the docs were added in the wrong file - `docs/usage/docker.md`, instead of within the `helm-requirements` docs.
> 
> Can you give some more details and links? What published page has the wrong information? And where do you think the information should go?
> 
> EDIT: I think you mean that the information from PR #8316 should go into `helm-requirement` docs?

@HonkingGoose correct

**Comment by dudicoco** [comment]
so it seems that even with the `hostRules` configured per https://github.com/renovatebot/renovate/pull/8316/files renovate does not work with a helm private repository:
```json
{
  "extends": [
    "config:base"
  ],
  "helm-requirements": {
    "aliases": {
      "helm-packages": "https://raw.githubusercontent.com/my-org/helm-packages/master/"
    }
  },
  "hostRules": [
    {
      "hostName": "https://raw.githubusercontent.com/my-org/helm-packages/master/",
      "username": "my-user",
      "encrypted": {
        "password": "my-pass"
      }
    }
  ]
}
```

Getting:
```
DEBUG: Datasource 404
{
  "datasource": "helm",
  "lookupName": "base",
  "url": "https://raw.githubusercontent.com/DynamicYield/helm-packages/master/index.yaml"
}
```

```
      {
        "packageFile": "chart/requirements.yaml",
        "deps": [
          {
            "depName": "base",
            "currentValue": "2.4.15",
            "registryUrls": [
              "https://raw.githubusercontent.com/my-org/helm-packages/master/"
            ],
            "depIndex": 0,
            "updates": [],
            "warnings": [
              {
                "topic": "base",
                "message": "Failed to look up dependency base"
              }
            ],
            "versioning": "semver"
          }
        ],
        "datasource": "helm"
      },
```

**Comment by viceice** [comment]
Closing, since helm v2 is EOL since more than 2 years and most helm charts are migrated to helm v3 too, so they are not usable either.
