### ISSUE TITLE
Onboarding branch changes overwritten when no onboarding PR is open 

### ISSUE THREAD

**Issue by ste93cry** [renovatebot/renovate#12157]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

The Renovate hosted GitHub app got activated for a private repository in the organization I work for. We have a Docker Hub account which contains some private repositories, and various references to such images in files like the `Dockerfile`. The bot immediatly created the onboarding Git branch, however since it has no way to authenticate with the Docker registry it fails to create the onboarding PR. To solve the issue, I pushed a new commit to the same branch with an adjusted onboarding config. However, as soon as I do this, the bot overwrites everything I did, and basically I'm stuck in a endless loop for this reason. Looking at the source code, the issue seems to be here:

https://github.com/renovatebot/renovate/blob/7e069f4adce758bef94fc31ea4db8984f3169da9/lib/workers/repository/onboarding/branch/index.ts#L50-L69

As you can see, if the onboarding PR doesn't exist yet it doesn't matter what's in the branch, it always get created from scratch. What I would expect is that the branch content is taken into consideration, at least if there is a valid `renovate.json` file

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: config file not found
DEBUG: findPr(renovate/configure, Configure Renovate, !open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 0 Pull Requests
DEBUG: Found no closed onboarding PR
DEBUG: Repo is not onboarded
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, undefined, open)
DEBUG: findPr(renovate/configure, undefined, closed)
DEBUG: Onboarding PR does not exist
DEBUG: No default org/owner preset found, so the default onboarding config will be used instead. Note: do not be concerned with any 404 messages that preceded this.
DEBUG: onboarding config
{
  "config": {
    "extends": [
      "config:base"
    ]
  }
}
DEBUG: No renovate config file found
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "config:base"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "config:base"
    ]
  }
}
DEBUG: Need to create onboarding PR
DEBUG: createOnboardingBranch()
DEBUG: No default org/owner preset found, so the default onboarding config will be used instead. Note: do not be concerned with any 404 messages that preceded this.
DEBUG: onboarding config
{
  "config": {
    "extends": [
      "config:base"
    ]
  }
}
DEBUG: Creating onboarding branch
DEBUG: Committing files to branch renovate/configure
INFO: Branch created(branch="renovate/configure")
WARN: docker registry failure: unauthorized
WARN: Host error
INFO: External host error causing abort - skipping
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
I'd prefer to find a way to skip the host error, so that the onboarding PR can be created. Is it something you can reproduction a public repo?

**Comment by ste93cry** [comment]
Just to demonstrate better the issue, I've merged a PR and as you can see the commit got removed immediatly after

**Comment by ste93cry** [comment]
Any news about this?

**Comment by viceice** [comment]
@ste93cry You can manually create a pr and add the required `renovate.json` with your needs.



> @viceice @JamieMagee do you think the appropriate solution would be to absorb these types of external host errors if onboarding?

Yes, I think we can make them warning only if onboading?

**Comment by entscheidungsproblem** [comment]
> @ste93cry You can manually create a pr and add the required `renovate.json` with your needs.

Should this method show the same details as the "Configure Renovate" initial PR or produce logs in the Renovate Dashboard?

I have the same issue where I am getting `external-host-error` for a new repo and any changes I make to the config file in the initial PR, `renovate/configure`, are immediately wiped by `renovate-bot`.

Is there any way I can verify my config works before merging?

Thanks, and let me know if I can provide more details.

**Comment by rarkins** [comment]
For now, fork or duplicate the repo and test against that

**Comment by entscheidungsproblem** [comment]
Thanks @rarkins! Although not ideal, that did work for me to test my config when the default initial config was failing. 

It would be great if the default config included `abortOnError = false` for an easier onboarding process.

**Comment by ste93cry** [comment]
I don't know what changed, but in the repo I created for reproducing this issue, the Onboarding PR has just been opened by the bot 🥳

**Comment by ste93cry** [comment]
I got confirmation that it works as expected for the repos the organization I belongs to. Time to close this, finally!
