### ISSUE TITLE
lib/manager/regex/readme.md typo

### ISSUE THREAD

**Issue by micah** [renovatebot/renovate#12222]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

28

### Describe the bug

On https://docs.renovatebot.com/modules/manager/regex/ which comes from `lib/manager/readme.md` in the Advanced Capture section, there is this regexp in the second code block, and it *seems* to me to have a stray character at the end:

`"ARG IMAGE=(?<depName>.*?):(?<currentValue>.*?)@(?<currentDigest>sha256:[a-f0-9]+)s"`

its capturing: 

`ARG              IMAGE=node:12@sha256:6e5264cd4cfaefd7174b2bc10c7f9a1c2b99d98d127fc57a802d264da9fb43bd`

But the regex has a 's' at the end... this means match the character 's' literally. Is this supposed to be a `\s` or even `\\s` (I'm unsure which, because its not obvious from the context).

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment]
Feel free to create a pull request to fix the typo! 😉 

The file you'd need to edit is here: https://github.com/renovatebot/renovate/blob/main/lib/manager/regex/readme.md

**Comment by HonkingGoose** [comment]
This issue is still present in the published docs.

Do we know what the proper regex should be?

**Comment by secustor** [comment]
I think this is fixed with https://github.com/renovatebot/renovate/pull/13945
