### ISSUE TITLE
Automerge Blocked

### ISSUE THREAD

**Issue by esetnik** [renovatebot/renovate#12362]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Automerge appears to have stopped working since https://github.com/renovatebot/renovate/issues/12202

### Relevant debug logs

https://app.renovatebot.com/dashboard#github/ProdigyEMS/prodigy/493247712

<details><summary>Logs</summary>

```
DEBUG: PR is not ready for merge(branch="renovate/ramda-0.x")
{
  "canMergeReason": "mergeStateStatus = BLOCKED"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by esetnik** [comment]
![image](https://user-images.githubusercontent.com/664434/139594161-3dc8488f-430d-4c13-a8b1-0d78069e0025.png)

**Comment by rarkins** [comment]
That screenshot shows that *you* aren't blocked, but it doesn't test whether `renovate[bot]` is blocked. Can you take a screenshot of your branch protection rules for `develop`?

**Comment by esetnik** [comment]
It seems that renovate was no longer able to merge due to branch protection rules. I'm not sure why it got removed but this issue was fixed by adding the renovate bot back to the list of who can push to the branch under branch protection rules.

![image](https://user-images.githubusercontent.com/664434/139711344-13a2242a-0ac7-478b-a71b-f3a3283b2a48.png)
