### ISSUE TITLE
Auto-merge using GitHub native auto-merge doesn't work in some scenarios

### ISSUE THREAD

**Issue by danewilson** [renovatebot/renovate#12363]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Auto-merge no longer works in our repos since [Renovate switched to using GitHub native auto-merge](https://github.com/renovatebot/renovate/pull/12045).

When we approve the PR and trigger auto-merge, this error occurs:
![image](https://user-images.githubusercontent.com/2070695/139167906-1f050717-a355-4d84-aae3-ab834b75d3e4.png)

There don't seem to be any errors in the Renovate logs.

I believe this is happening because our repos generally allow merge commits (for our master branch) and squash merges (for our develop branch), but we have a branch protection rule to **Require linear history** for our develop branch to prevent accidental merge commits.

Given [automergeStrategy](https://docs.renovatebot.com/configuration-options/#automergestrategy) doesn't appear to be supported for GitHub, there doesn't seem to be a way for us to avoid this error in our repos.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Pending closure unless confirmed not fixed

**Comment by danewilson** [comment]
I recreated a Renovate PR and it seemed to detect the correct auto-merge type without any changes on our end, so I think this can be closed. Thanks for the quick turnaround.
![image](https://user-images.githubusercontent.com/2070695/139562645-4e2c7fa6-ffca-403a-89e3-b11243287cb6.png)
