### ISSUE TITLE
Fix for #10464 added arbitrary constraints

### ISSUE THREAD

**Issue by astellingwerf** [renovatebot/renovate#12417]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

28.20.0

### Describe the bug

With the commit 10ca7b3 for #10464, the addition of filtering of tags puts arbitrary constraints on what's considered the latest tag, while (as [product documentation states](https://docs.renovatebot.com/modules/versioning/#docker-versioning)) the versioning is a bit vague for Docker.

The filtering in `findLatestStable` always uses the Docker versioning, instead of the versioning that's configured for the dependency. With version numbers for JVM containers like `11.0.10_9.202103.181959-jre`, they would not be considered stable, whereas the `config.versioning` with a regex for this package (set via a package rule) would.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment]
@viceice Can you triage this issue please? I'm not sure if the new behavior is a regression or intended.

**Comment by viceice** [comment]
This is currently by design. 🤷‍♂️

**Comment by astellingwerf** [comment]
Looks like someone has hit by the same design decision, and is working around it: #12646

**Comment by HonkingGoose** [comment]
> This is currently by design. 🤷‍♂️

If the new behavior is intended, maybe we can close the issue, if we're not going to change things?

What do you think @rarkins?

**Comment by astellingwerf** [comment]
I don't understand the design: "Despite versioning on Docker being extremely muddy, we must enforce some rules to find a few tags on a reliably but rather arbitrarily selected image, and that hope they make any sense for the image that is selected based on actual in-depth knowledge and configuration."
