### ISSUE TITLE
Current docker image ships a broken poetry installation

### ISSUE THREAD

**Issue by languitar** [renovatebot/renovate#12459]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v28.20.0

### Describe the bug

Recent Docker images contain a version of CacheControl inside the venv containing poetry that renders poetry unusable in some cases. The respective upstream bugs in poetry and CacheControl are https://github.com/python-poetry/poetry/issues/4688 and https://github.com/ionrock/cachecontrol/issues/263.

To make poetry usable again in all cases, a temporary workaround inside the docker image of renovate would be needed that downgrades CacheControl inside the poetry venv as proposed in the first issue.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Thanks for the heads-up, although it's not something we can fix here so I will close this issue.

The full image is built here: https://github.com/renovatebot/docker-renovate-full

And that is built using scripts from https://github.com/containerbase/buildpack

As I'm not familiar with CacheControl so not sure where would be best to raise a fix. If you can work it out, can you raise an issue in the correct repo?

**Comment by languitar** [comment]
Sorry, I didn't know about that repository. Can you transfer this issue to the correct repository. I can try to come up with a fix then.
