### ISSUE TITLE
Disable platform automerge for unsupported GHE versions

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#12464]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### Describe the bug

Renovate should not attempt platform automerge on unsupported GHE versions

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by zharinov** [comment]
Have #12473 fixed this one?

**Comment by rarkins** [comment]
No, it just disables the autoMergeEnabled check in the graphql. Does not stop Renovate from trying platform-native automerge

**Comment by zharinov** [comment]
Okay, I get it
