### ISSUE TITLE
Respect `prettier` formatting in the onboarding PR

### ISSUE THREAD

**Issue by latipun7** [renovatebot/renovate#12463]
### What would you like Renovate to be able to do?

I'd like renovate to respect `prettier` formatting when doing onboarding PR.

---

This issue occurs in repo with [`prettier`](https://prettier.io/) and configure the Github Actions to check the formatting on every pull request.

### Step to Reproduce
1. Create repository with the `prettier` with [prettier config files](https://prettier.io/docs/en/configuration.html) or without the config files (default prettier config).
2. Set `scripts` in `package.json` with `"format": "prettier --check ."`
3. Configure Github Actions to check the formatting (`-run: yarn format`) on every `pull_request`
4. Let renovate create the onboarding PR

### Expected Behavior
PR successfully and `renovate.json` created with these contents:
```json
{
  "extends": ["config:base"]
}
```

### Actual Behavior
PR CI error, "Some checks were not successful"
```bash
Run yarn format
yarn run v1.22.15
$ prettier --check .
Checking formatting...
[warn] renovate.json
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
`renovate.json` created with:
```json
{
  "extends": [
    "config:base"
  ]
}
```

### If you have any ideas on how this should be implemented, please tell us here.

I guess first check if the project has [prettier configuration files](https://prettier.io/docs/en/configuration.html). If not found, then check if `package.json` has `prettier` installed (using default prettier configuration).
If prettier found, run [`prettier --write`](https://prettier.io/docs/en/cli.html#--write) in the onboarding file.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Sorry, but I prefer not to do this:
- possibility of running malicious code
- complexity (including if trying to work around malicious code)
