### ISSUE TITLE
Add Typescript to source

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#1261]
TODO's

- [x] convert all lib  files to ts
- [x] convert all test files to ts
- [ ] convert all bin files to ts (excerpt yarn)?
- [ ] cleanup eslint
- [ ] remove js from tsconfig

**Comment by zephraph** [comment]
:wave: I might poke this. The Ruby PR @yuki24 and I am working on could definitely some help from type checking 😄

**Comment by ViceIce** [comment]
@JamieMagee @rarkins Should we convert the test fixture files to ts too?

**Comment by JamieMagee** [comment]
Yeah, I'd say so.

**Comment by rarkins** [comment]
@viceice anything left to do here?

**Comment by viceice** [comment]
I think this is done
