### ISSUE TITLE
Renovate specifying non-existing PyPI version

### ISSUE THREAD

**Issue by lpfann** [renovatebot/renovate#12664]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

27.19.2

### Please select which platform you are using if self-hosting.

github.com

### Describe the bug

We are self-hosting Renovate and found an issue with one of the dependency updates.
Renovate wanted to update the package `PyMuPDF==1.19.1` to `PyMuPDF==1.19.1.1`, which does not [exist](https://pypi.org/project/PyMuPDF/#history).

We are using a private AWS Codeartifact Python Index with the public PyPI as upstream repository. All those repositories did not contain the unknown version.

The logs below show where renovate wanted to increase the version.

The bug happens again after specifying the correct version, so its not some kind of repository fluke.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: packageFiles with updates (repository=repo123)
       "config": {
         "pip_requirements": [
           {
             "packageFile": "requirements.txt",
             "deps": [
               {
                 "depName": "PyMuPDF",
                 "currentValue": "==1.19.1",
                 "datasource": "pypi",
                 "currentVersion": "1.19.1",
                 "depIndex": 8,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "1.19.1.1",
                     "newValue": "==1.19.1.1",
                     "newMajor": 1,
                     "newMinor": 19,
                     "updateType": "patch",
                     "isRange": true,
                     "branchName": "renovate/pymupdf-1.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "pep440",
                 "isSingleVersion": true,
                 "fixedVersion": "1.19.1"
               }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
The chances that Renovate "invents" a version which doesn't exist - especially one so feasible as 1.9.1.1 - is close to zero. If you cannot reproduce the problem with the public registry but it reproduces internally, it means there's something strange going on with your private registry. *Maybe* it's still a Renovate bug, but the only chance for it to be fixed is if you debug it.

Therefore we need either:
- public reproduction, or
- debugging of the lookup from within your network
