### ISSUE TITLE
Fail to update Spring Boot Maven project

### ISSUE THREAD

**Issue by patrickuhlmann** [renovatebot/renovate#12695]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

29.6.0

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

Atlassian Bitbucket v7.16.0

### Describe the bug

When I run renovate the following error occurs:
`WARN: Error updating branch: update failure`

How to reproduce:
1. Visit https://start.spring.io/, click on Generate and download the zip.
2. Edit the pom.xml contained in the example and set the spring boot version from (currently) 2.5.6 to 2.5.5. Commit
2. Import the content of the zip in BitBucket
3. Configure and Run renovate
4. Merge the on-boarding PR
5. Run renovate again
=> it will fail to update spring-boot to the new version

Here my configuration (renovate.js):
```
module.exports = {
  endpoint: 'http://code.mycompany.ch/',
  platform: 'bitbucket-server',
  username: 'myuser',
  password: 'mybitbuckettoken',
  onboarding: true,
  gitAuthor: "Renovate Bot <bot@renovateapp.com>",
  prHourlyLimit: 10,
  prConcurrentLimit: 20,
  branchPrefix: "renovate/",
  onboardingConfig: {
    extends: ['config:base', ":disableDependencyDashboard"],
  },
  repositories: ['myproject/renovate-experiment'],
  hostRules: [
    {
      hostType: "maven",
      matchHost: "myartifactory",
      username: "myuser",
      password: "myartifactorytoken"
    },
	{"hostType": "github", "matchHost": "github.com", "token": "mygithubtoken"}
  ],
  packageRules: [
    {
      matchManagers: [
        "maven"
      ],
      registryUrls: [
        "https://mymavencentralmirror/mvn/",
	"https://myprojectmirror/project.mvn/"
      ]
    }
  ],
};
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Branch needs creating (repository=myproject/renovate-experiment, branch=renovate/spring-boot)
DEBUG: Using reuseExistingBranch: false (repository=myproject/renovate-experiment, branch=renovate/spring-boot)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=myproject/renovate-experiment, branch=renovate/spring-boot)
DEBUG: Unknown value (repository=myproject/renovate-experiment, branch=renovate/spring-boot)
       "depName": "org.springframework.boot:spring-boot-starter-parent",
       "version": "/version>\n\t\t<relativePath /> <!-- lookup parent from repository -->",
       "currentValue": "2.5.5",
       "newValue": "2.5.6"
DEBUG: Error updating file (repository=myproject/renovate-experiment, branch=renovate/spring-boot) ...
```

You can clearly see that it somehow fails to detect the version. In a larger project it was able to create 1 out of 5 pull requests but the pull request that it generated was messed up. It contained lines like this:
```
<version>2.4.5<2.5.6
```
Which indicates that it is somehow not detecting the proper spot where the version number should be inserted.

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by patrickuhlmann** [comment]
In one case it was unable to create a branch and pull request, in another example it could create the pull request but the pom was invalid (as shown in the debug logs)

**Comment by rarkins** [comment]
Hi, can you create the reproduction repository on github.com so that we can fork it into our reproductions org?

**Comment by rarkins** [comment]
It does not reproduce. Maybe you meant to use version 2.5.5 instead of 2.5.6?
