### ISSUE TITLE
Packages not grouped with "update-lockfile" range strategy

### ISSUE THREAD

**Issue by mbrodala** [renovatebot/renovate#12763]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Given the following `renovate.json`:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base"
  ],
  "rangeStrategy": "update-lockfile",
  "packageRules": [
    {
      "matchPackagePrefixes": [
        "phpstan/"
      ],
      "matchPackageNames": [
        "jangregor/phpstan-prophecy",
        "saschaegerer/phpstan-typo3",
        "rector/rector"
      ],
      "groupName": "PHPStan"
    }
  ]
}
```

And the following `composer.json`:

```json
{
    "require-dev": {
        "jangregor/phpstan-prophecy": "^0.8.0",
        "phpstan/phpstan": "^0.12.30",
        "rector/rector": "^0.11.57",
        "saschaegerer/phpstan-typo3": "^0.13"
    }
}
```

As can be seen, there's a package rule to group all PHPStan packages and related 3rd party packages. Strangely the `rector/rector` package is not part of the _PHPStan_ package group update:

![image](https://user-images.githubusercontent.com/5037116/142647112-1bacfd94-64b1-423a-9aa1-d4c75d2af096.png)

Since `rector/rector` 0.12.x depends on `phpstan/phpstan` 1.x both update pull requests are broken.

See https://github.com/mbrodala/renovate-phpstan-package-group/pull/1 for a live example.

What am I missing?

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Dependency rector/rector is part of group PHPStan
DEBUG: Using group branchName template
DEBUG: Dependency saschaegerer/phpstan-typo3 is part of group PHPStan
DEBUG: 4 flattened updates found: jangregor/phpstan-prophecy, phpstan/phpstan, rector/rector, saschaegerer/phpstan-typo3
DEBUG: Returning 2 branch(es)
DEBUG: Fetching changelog: https://github.com/sascha-egerer/phpstan-typo3 (0.13.3 -> 1.0.0)
DEBUG: Fetching changelog: https://github.com/phpstan/phpstan (0.12.99 -> 1.2.0)
DEBUG: Fetching changelog: https://github.com/Jan0707/phpstan-prophecy (0.8.1 -> 1.0.0)
DEBUG: Fetching changelog: https://github.com/rectorphp/rector (0.11.60 -> 0.12.4)
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Groups are split between major and minor by default. If you really want them to be combined, you could try setting separateMajorMinor=false

**Comment by mbrodala** [comment]
That makes sense, and indeed adding `separateMajorMinor: false` to the `PHPStan` package group made Renovate behave like expected:

![image](https://user-images.githubusercontent.com/5037116/142820588-ee012437-08e9-4666-a517-a58d6d457f59.png)

Maybe this fact should be mentioned in the docs for `separateMajorMinor`.
