### ISSUE TITLE
package age policy

### ISSUE THREAD

**Issue by tennox** [renovatebot/renovate#12762]
### What would you like Renovate to be able to do?

In thinking about recent npm package malware I thought it would be great to be able to only install upgrades that are older than X (e.g. 1 month) - and have no reported security issues.

### If you have any ideas on how this should be implemented, please tell us here.

The only way I found will reading through existing issues and docs is maybe a custom version API that checks npm but only reports updates that meet the requirements.

But that would probably need custom implementation for each registry (e.g. docker, composer, ...)

So a package policy that checks minAge , when available would be way better.
Would be ready to implement when I get a rough sketch.

Or even custom filter plug-in / API that send package info and allows any custom check. But that's probably overkill.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment]
https://docs.renovatebot.com/configuration-options/#stabilitydays ?

**Comment by HonkingGoose** [comment]
We already have this feature, it's called `stabilityDays` [^docs]. 😉 

You can set `stabilityDays` to `31` so that you'll only ever get updates for packages that are a month old:

```json
{
  "packageRules": [
    {
      "stabilityDays": 31
    }
  ]
}
```

[^docs]: https://docs.renovatebot.com/configuration-options/#stabilitydays

**Comment by HonkingGoose** [comment]
If you're going to follow the route of "delay all updates for 31 days" I recommend you check that you have:

- [ ] Turned on the Dependency Graph (if using GitHub)
- [ ] Enabled Dependabot alerts (if using GitHub)

Or you may miss critical security updates.

https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts

**Comment by HonkingGoose** [comment]
> only install upgrades that are older than X (e.g. 1 month) - and have no reported security issues.

@rarkins Not sure if we want to keep this issue for the `and have no reported security issues` part?

I don't think Renovate currently checks things like GitHub Vulnerability Warnings or `npm audit` output when it creates a PR?
