### ISSUE TITLE
Support for updating docker images in jib maven plugin

### ISSUE THREAD

**Issue by andrein** [renovatebot/renovate#12772]
### What would you like Renovate to be able to do?

Renovate should be able to update the base image used by the [jib maven plugin](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin)

Example `pom.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
[...]
	<build>
		<plugins>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<from>
						<image>openjdk:11.0.10-jre</image> <!-- this should be updated -->
					</from>
					<to>
						<image>myimage</image>
					</to>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

### If you have any ideas on how this should be implemented, please tell us here.

I'm thinking of changing [depFromNode()](https://github.com/renovatebot/renovate/blob/main/lib/manager/maven/extract.ts#L40) to return `PackageDependency[] | null` and returning an extra dependency if depName is `com.google.cloud.tools:jib-maven-plugin`

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment]
As workaround you can use regex manager for now

**Comment by andrein** [comment]
I've thought of that, but I have about a hundred apps to keep up to date :) I'd rather implement this in renovate directly.

**Comment by viceice** [comment]
What about shared presets? we recommend to use them when you need same settings for multiple repos. 
We do so ourself. :wink

**Comment by rarkins** [comment]
Is this (`plugin.configuration.from.image`) standardized in any way or essentially a proprietary?

**Comment by andrein** [comment]
> What about shared presets? we recommend to use them when you need same settings for multiple repos. We do so ourself. 😉

I think we could use that. If we add it to onboardingConfig, is it possible to tell renovate to update all the repos with the new config?

> Is this (`plugin.configuration.from.image`) standardized in any way or essentially a proprietary?

I don't think it is standardized. I've only seen it used by the jib plugin so far.
