### ISSUE TITLE
Wrong yarn lockfile version commited in every pr

### ISSUE THREAD

**Issue by ZetraDev** [renovatebot/renovate#12771]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Everytime renovate bot create a new pull request, it commits the lockfile that was generated by yarn classic version (v1) instead of berry version (v2 - v3)

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: exec completed(branch="renovate/all")
{
  "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/ZetraBot/ZetraDashboard\":\"/mnt/renovate/gh/ZetraBot/ZetraDashboard\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_CACHE_FOLDER -w \"/mnt/renovate/gh/ZetraBot/ZetraDashboard\" docker.io/renovate/node bash -l -c \"npm i -g yarn && yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\"",
  "durationMs": 132006,
  "stdout": "\n> yarn@1.22.17 preinstall /home/ubuntu/.npm-global/lib/node_modules/yarn\n> :; (node ./preinstall.js > /dev/null 2>&1 || true)\n\n/home/ubuntu/.npm-global/bin/yarn -> /home/ubuntu/.npm-global/lib/node_modules/yarn/bin/yarn.js\n/home/ubuntu/.npm-global/bin/yarnpkg -> /home/ubuntu/.npm-global/lib/node_modules/yarn/bin/yarn.js\n+ yarn@1.22.17\nadded 1 package in 1.754s\nyarn install v1.22.17\n[1/4] Resolving packages...\n[2/4] Fetching packages...\n[3/4] Linking dependencies...\n[4/4] Building fresh packages...\nDone in 126.21s.\n",
  "stderr": "warning \"@emotion/styled > @emotion/babel-plugin@11.3.0\" has unmet peer dependency \"@babel/core@^7.0.0\".\nwarning \"@emotion/styled > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.0\" has unmet peer dependency \"@babel/core@^7.0.0-0\".\nwarning \"next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5\" has unmet peer dependency \"@babel/core@^7.0.0-0\".\nwarning \" > eslint-config-next@12.0.4\" has incorrect peer dependency \"eslint@^7.23.0\".\nwarning \"eslint-config-next > @typescript-eslint/parser@4.33.0\" has incorrect peer dependency \"eslint@^5.0.0 || ^6.0.0 || ^7.0.0\".\nwarning Ignored scripts due to flag.\n"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by ZetraDev** [comment]
here is the link of the reproduction repo:
https://github.com/ZetraDev/Temp-NextJS-App

The typescript version is 4.4 (which is not latest) to test renovate

**Comment by viceice** [comment]
You're repo is missing the yarn executable.

**Comment by ZetraDev** [comment]
what do you mean?

**Comment by viceice** [comment]
And the yarnrc. How do you invoke yarn manually?

**Comment by ZetraDev** [comment]
yarn cretae next-app

**Comment by viceice** [comment]
Normally yarn V2+ will install itself to the `.yarn` folder

**Comment by viceice** [comment]
> yarn cretae next-app

Please create a github workflow so we can see the required command to restore deps and build the app.

**Comment by ZetraDev** [comment]
`yarn install` to install deps and `yarn build` to build the app

**Comment by ZetraDev** [comment]
and i have initialize yarn v3 in the repo

**Comment by viceice** [comment]
Can you now enable renovate on that repo to see the reproduction

**Comment by ZetraDev** [comment]
I have installed renovate and let it run check, for some reason it actually use yarn v3 to run check

**Comment by viceice** [comment]
I tend to move this to a discussion, as it seems you repo config was wrong if you can't create a reproduction.
