### ISSUE TITLE
Disabling Github via host rules has no effect on release notes retrieval for Github

### ISSUE THREAD

**Issue by mzeijen** [renovatebot/renovate#12843]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

29.23.3

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

not relevant

### Describe the bug

When disabling Github via `hostRules` configuration, I expect that the Github release notes retrieval is be skipped, without any warnings being logged. 
But this is currently not the case, instead we see the warning `No github.com token has been configured. Skipping release notes retrieval` in the logs and in the dependency dashboard.  This warning is because we don't have that token configured (we also don't want to, because we can't access Github), but if I would enter a dummy token then Renovate crashes because it can't access Github. This warning currently confuses our colleagues that use Renovate, because they believe something is incorrectly configured, which is not the case.

To clarify, when I set the following in the config:

```
"hostRules": [{
  "hostType": "github",
  "enabled": false
}]
```

or 

```
"hostRules": [{
  "matchHost": "github.com",
  "enabled": false
}]
```

the `getChangeLogJSON` method in the `lib/workers/pr/changelog/source-github.ts` file should simply `return null`. 

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: No github.com token has been configured. Skipping release notes retrieval (repository=myproject)
       "manager": "maven",
       "depName": "io.ktor:ktor-bom",
       "sourceUrl": "https://github.com/ktorio/ktor"
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=myproject)
       "manager": "maven",
       "depName": "io.ktor:ktor-bom",
       "sourceUrl": "https://github.com/ktorio/ktor"
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=myproject)
       "manager": "maven",
       "depName": "io.ktor:ktor-bom",
       "sourceUrl": "https://github.com/ktorio/ktor"
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=myproject)
       "manager": "maven",
       "depName": "io.ktor:ktor-bom",
       "sourceUrl": "https://github.com/ktorio/ktor"
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=myproject)
       "manager": "maven",
       "depName": "org.mockito.kotlin:mockito-kotlin",
       "sourceUrl": "https://github.com/mockito/mockito-kotlin"
 WARN: No github.com token has been configured. Skipping release notes retrieval (repository=myproject)
       "manager": "maven",
       "depName": "org.mockito.kotlin:mockito-kotlin",
       "sourceUrl": "https://github.com/mockito/mockito-kotlin"
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
So your "real requirement" is the ability to tell Renovate "I intentionally don't want to access GitHub.com, so please stop warning me"? For example if we allowed something like GITHUB_COM_TOKEN=disabled as a special value that would also serve the same purpose?

**Comment by viceice** [comment]
👉 https://docs.renovatebot.com/configuration-options/#fetchreleasenotes

**Comment by rarkins** [comment]
Please create a minimal reproduction repo

**Comment by rarkins** [comment]
gitlab.com will be ok

**Comment by mzeijen** [comment]
Disabling fetching release notes is not the fix. We do want it to fetch release notes, but only from sources that it can actually access, like our own Gitlab instance.

With all due respect, but creating a reproduction path to me seems a bit unnecessary. It will take me more time to do so, then it takes to implement the actual fix. 

Adding an if statement just before [this](https://github.com/renovatebot/renovate/blob/main/lib/workers/pr/changelog/source-github.ts#L55) line should do the trick:

```
if (!config.enabled) {
    logger.debug(
      { manager, depName, sourceUrl },
      'Github host is disabled via hostRule setting - skipping changelog retrieval'
    );
    return null;
}
```

And of course a test needs to be written. 

I would send in a PR but I have little experience with the NodeJS ecosystem so that would be a lot of work for me as well. I would appreciate if we can get this fixed without all that. Thanks!

**Comment by viceice** [comment]
I think we instead should catch the host disabled error at appropriate line of code.
