### ISSUE TITLE
renovate cannot get npm dependencies from private registry (npm)

### ISSUE THREAD

**Issue by ymajoros** [renovatebot/renovate#12844]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

29.23.3

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14..12

### Describe the bug

Renovate tries to look up a package in our private npm repository (nexus).

Specifically, it tries to get that url:
http://nexus.yyyy.be:8081/repository/npm-all/@angular%2Fanimations

But it gets a 404. Same if do that manually.

URLs like this, to download a specific package version, do work: https://nexus.yyyy.be/repository/npm-all/%40angular/animations/-/animations-10.0.9.tgz

What is it exactly trying to get at that URL? Is information on that package supposed to be there? Or is there another URL that we should configure somewhere for that kind of information?

This is all anonymous, no credentials required in our configuration to browse or download packages. 

.npmrc in any case:
`registry=http://nexus.yyyy.be:8081/repository/npm-all/`

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Dependency lookup failure: not found (repository=zzzz/yyyy)
       "err": {
         "name": "HTTPError",
         "timings": {
           "start": 1637853697521,
           "socket": 1637853697521,
           "lookup": 1637853697542,
           "connect": 1637853697543,
           "upload": 1637853697543,
           "response": 1637853697544,
           "end": 1637853697545,
           "phases": {
             "wait": 0,
             "dns": 21,
             "tcp": 1,
             "request": 0,
             "firstByte": 1,
             "download": 1,
             "total": 24
           }
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/29.23.3 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "http://nexus.yyyy.be:8081/repository/npm-all/@angular%2Fanimations",
           "hostType": "npm",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 404,
           "statusMessage": "Not Found",
           "body": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /repository/npm-all/@angular/animations was not found on this server.</p>\n</body></html>\n",
           "headers": {
             "date": "Thu, 25 Nov 2021 15:21:37 GMT",
             "server": "Apache/2.4.6 (Red Hat Enterprise Linux)",
             "content-length": "236",
             "connection": "close",
             "content-type": "text/html; charset=iso-8859-1"
           },
           "httpVersion": "1.1"
         }
       },
       "packageName": "@angular/animations"
DEBUG: Failed to look up dependency @angular/animations (repository=zzzz/yyyy, packageFile=yyyy-ui/package.json, dependency=@angular/animations)```

</details>


### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
This is not a renopvate bug, it's a nexus issue, as we fetch the package metadata with the first request, which other known registries supports.

see `curl -s https://registry.npmjs.org/@angular%2Fanimations`

**Comment by ymajoros** [comment]
@viceice is there a specification for that, so that I can file a Nexus issue, or is this just some common practise? Any workaround in the meantime?

**Comment by viceice** [comment]
No workaround, sorry.

Here's some api documentation: https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md

**Comment by viceice** [comment]
@rarkins It looks like we can reduce the npm metadata payload a lot by sending this herader `Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*`

**Comment by ymajoros** [comment]
Actually, the request works in Nexus. The URL above that I extracted from the logs just works when tried locally:
`curl -s https://nexus.yyyy.be/repository/npm-all/%40angular/animations`

Now, I don't understand why _renovate_ says it's a 404 then.

**Comment by viceice** [comment]
@ymajoros you're suing another package encoding than renovate.

@rarkins We can't use the short version, release times are missing there 😕

**Comment by ymajoros** [comment]
@viceice what do you mean by _package encoding_? How can I solve this?

**Comment by viceice** [comment]
Compare my url and your url. I've url encoded the slash in package name.

**Comment by ymajoros** [comment]
`curl https://nexus.vdab.be/repository/npm-all/%40angular%2Fanimations` also works. Or any combination.

**Comment by ymajoros** [comment]
@viceice any idea why it doesn't work from renovate taking that last info into account?

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/143554622-137a27e3-e64d-4d18-bfaf-3bcc94f94f17.png)

**Comment by ymajoros** [comment]
@rarkins yeah, it's either http on port 8081 or https on default. They both work the same with all encoding combinations of / and @. Any idea why I get a 404?

**Comment by viceice** [comment]
What about `curl -H 'Accept: application/json' https://nexus.yyyy.be/repository/npm-all/%40angular%2Fanimations`?

Can you run the curl from the same envoronment, where your bot runs? mayybe you've some proxy between, so that fails on renovate env?

**Comment by rarkins** [comment]
Or does the port trip up our hostRules? Can experiment with removing it from the `.npmrc`

**Comment by viceice** [comment]
> Or does the port trip up our hostRules? Can experiment with removing it from the `.npmrc`

I don't think so, as he told, that all access is anonymous.

**Comment by ymajoros** [comment]
Seems we get a redirect to https from port 8081, and renovate isn't following redirects. Looks like that was the issue, I don't get the error anymore. I still don't get why it gets misreported as a 404, as it seems that that never happens.

**Comment by ymajoros** [comment]
@rarkins @viceice my problem is solved, but should renovate follow redirects?

**Comment by rarkins** [comment]
It sounds like it should, but unless you can reproduce it publicly somehow, we have little chance of being able to solve it. If you can reproduce it, please raise it as a new issue with description relating to redirects.

**Comment by ymajoros** [comment]
@rarkins @viceice It's rather costly for me, not knowing the internals of your project, to provide a reproducer, which I guess would involve an rpm repository, a test project using it, a reverse proxy with redirect, and renovate. OTOH, you probably have all of that in your test setup already. I'd suggest to add a rule in your existing setup in your server config to redirect from a path to another, and see if it works (seems it doesn't).

If that helps, I'll be happy to provide you with whatever is feasible for me without investing days, e.g. a reverse proxy config or even a docker image for it, with some guidelines about your test setup.

**Comment by rarkins** [comment]
For now we're not aware of the problem affecting anyone else, so without a reproduction and with a workaround I frankly don't see anyone looking into it.
