### ISSUE TITLE
Refactor and add tests for npm/extract and post-update

### ISSUE THREAD

**Issue by ylemkimon** [renovatebot/renovate#12858]
### Describe the proposed change(s).

Currently, dependency extraction logic is too complex and spread across: https://github.com/renovatebot/renovate/blob/4fef60daaf30c4e176b14c3db4e424955b8ad5b8/lib/manager/npm/extract/index.ts#L169 https://github.com/renovatebot/renovate/blob/4fef60daaf30c4e176b14c3db4e424955b8ad5b8/lib/manager/npm/extract/locked-versions.ts#L8 https://github.com/renovatebot/renovate/blob/4fef60daaf30c4e176b14c3db4e424955b8ad5b8/lib/manager/npm/post-update/index.ts#L454

Some logics are duplicated, e.g., #12570. Furthermore, `getAdditionalFiles` is not tested: https://github.com/renovatebot/renovate/blob/4fef60daaf30c4e176b14c3db4e424955b8ad5b8/lib/manager/npm/post-update/index.ts#L453-L454

**Comment by viceice** [comment]
Do you like to start on this? We should first try to  add tests to get full coverage, so we can verify code changes
