### ISSUE TITLE
refactor: coverage issues when using re2

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#12873]
### Describe the proposed change(s).

When we use re2 at these 2 instances, it causes coverage issues.
Instance 1
https://github.com/renovatebot/renovate/blob/04d161252fb2e3eb60a937e16448f372a351dc9f/lib/util/template/index.ts#L14-L16
Instance 2
https://github.com/renovatebot/renovate/blob/04d161252fb2e3eb60a937e16448f372a351dc9f/lib/util/template/index.ts#L150

**Comment by viceice** [comment]
i think we should fix the template helper as soon as possible because we are vulnerable to malcious user regexes.
- #26014
