### ISSUE TITLE
Add the ability to automatically re-trigger a GitLab pipeline if it fails.

### ISSUE THREAD

**Issue by liangshengzhong** [renovatebot/renovate#12903]
### What would you like Renovate to be able to do?

Sometimes GitLab pipeline may fail for some reason (no available resource to run), it doesn't actually need someone to do a real fix. We just need to re-trigger the pipeline. It would be great if renovate can allow the pipeline to be automatically triggered again after the pipeline fails for a period of time.

### If you have any ideas on how this should be implemented, please tell us here.

Provide some configuration items to enable this function, how many times can be retried after the pipeline fails for a long time

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Sorry, but I don't like this idea. If your pipelines are flaky then you're going to need a human to retry them.
