### ISSUE TITLE
Link to GitLab Release page in MR is wrong

### ISSUE THREAD

**Issue by Stefan-J-Hanke** [renovatebot/renovate#12918]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

29.2.6

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.5.1

### Describe the bug

Renovate created an MR in a GitLab repository for a dependency hosted on the same instance. 
That MR contained a link to the GitLab release page which unfortunately seems to be wrong.

Actual: `https://self.hosted/group1/group2/project/releases/4.0.1`
Should: `https://self.hosted/group1/group2/project/-/releases/4.0.1`

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Please paste the markdown of the MR here as closely as possible to the original

**Comment by Stefan-J-Hanke** [comment]
Unsure what you mean by _the markdown_. The MR just contains the HTML directly created by Renovate?

**Comment by rarkins** [comment]
Renovate should be sending markdown to gitlab, not html. You can usually see it by clicking the "edit" icon on the MR body description. You wrote "contained a link" but that's too vague so I want to see the full thing.

**Comment by Stefan-J-Hanke** [comment]
Oh my 🤣  trying a lame excuse: actually I'm distracted by a meeting. Will do.

**Comment by Stefan-J-Hanke** [comment]
This MR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [DotNetNugetPackageName](https://self.hosted/group1/group2/project1) | nuget | major | [`3.1.4` -> `4.0.1`](https://self.hosted/group1/group2/project1/-/compare/3.1.4...4.0.1) |

---

### Release Notes

<details>
<summary>group1/group2/project1</summary>

### [`v4.0.1`](https://self.hosted/group1/group2/project1/releases/4.0.1)

[Compare Source](https://self.hosted/group1/group2/project1/compare/3.1.4...4.0.1)

<DESCRIPTION OF THE RELEASE>

</details>

---

### Configuration

📅 **Schedule**: At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever MR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this MR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this MR, click this checkbox.

---

<FOOTER>

**Comment by viceice** [comment]
I think this happens, when the links are relative, I've seen this too

```md
### Release Notes

<details>
<summary>gitlab-org/gitlab-foss</summary>

### [`v14.5.1`](https://gitlab.com/gitlab-org/gitlab-foss/blob/master/CHANGELOG.md#&#8203;1451-2021-12-01)

[Compare Source](https://gitlab.com/gitlab-org/gitlab-foss/compare/v14.5.0...v14.5.1)

##### Fixed (4 changes)

-   [Check validation for license only if new record](gitlab-org/gitlab@3e34c2dc431a2b1c1828f5154a4d2be350359b16) ([merge request](gitlab-org/gitlab!75498)) **GitLab Enterprise Edition**
-   [Fix for hexadecimal branch deletion](gitlab-org/gitlab@eb74cd44edac0c16c44aa11d710b742586c31741) ([merge request](gitlab-org/gitlab!75498))
-   [Fix the SSL_CERT_DIR logging on git operations](gitlab-org/gitlab@6ef3b63ad5e58baa0e0e0a922fe43a2fb4494508) ([merge request](gitlab-org/gitlab!75498))
-   [Support Action Cable on GCP Memorystore](gitlab-org/gitlab@d62aa5bcbad5851209a9d248ca267d0c46d1e7c9) ([merge request](gitlab-org/gitlab!75498))

</details>
```

**Comment by Stefan-J-Hanke** [comment]
@viceice unsure why this is linking to the CHANGELOG.md file and not the release page (https://gitlab.com/gitlab-org/gitlab-foss/-/releases/v14.5.0)?

**Comment by viceice** [comment]
I think because they also have a changelog.md in repo root and renovate somehow prefers that. 🤷‍♂️

**Comment by Stefan-J-Hanke** [comment]
good guess - indeed it looks like that's the case.

**Comment by rarkins** [comment]
I don't see any `/project/-/releases/` in the above, only a `/project/-/compare/`

**Comment by Stefan-J-Hanke** [comment]
Just browsed the code a bit and I'd like to change [this line of code](https://github.com/renovatebot/renovate/blob/e8e99ef5b74a1117f9dc840dc01a4778a7c459ee/lib/workers/pr/changelog/release-notes.ts#L112). Never ran renovate locally let's see ...

> `${baseUrl}${repository}/releases/${release.tag}`

**Comment by rarkins** [comment]
Should work in gitpod too
