### ISSUE TITLE
Exceptions are swallowed on PR merge for BitBucket integration

### ISSUE THREAD

**Issue by osigida** [renovatebot/renovate#12923]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v29.29.2

### Please select which platform you are using if self-hosting.

Bitbucket Cloud (bitbucket.org)

### Describe the bug

Exceptions on PR merge are swallowed for Bit Bucket integration

check out this code:
https://github.com/renovatebot/renovate/blob/b3252ae86cd4d1d219afcec9787cf19fd2af6a31/lib/platform/bitbucket/index.ts#L812-L822

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Branch status green (repository=repository_name_here, branch=renovate/gradle-7.3.x)
DEBUG: Automerging #468 with strategy fast-forward (repository=repository_name_here, branch=renovate/gradle-7.3.x)
DEBUG: mergePr(468, renovate/gradle-7.3.x, fast-forward) (repository=repository_name_here, branch=renovate/gradle-7.3.x)
DEBUG: Setting current branch to master (repository=repository_name_here, branch=renovate/patch-sharedgradlepluginsversion)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by setchy** [comment]
@rarkins - this issue can be closed - looks like it was resolved via https://github.com/renovatebot/renovate/pull/12940
