### ISSUE TITLE
Bug(lock-file): Renovate creates out of schedule lock file PRs

### ISSUE THREAD

**Issue by erezrokah** [renovatebot/renovate#13014]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Related to https://github.com/renovatebot/renovate/discussions/9726

Renovate has been creating (for a few weeks now) out of schedule lock file PRs for a bunch of our repos.
See example here:
https://github.com/netlify/netlify-cms/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate+lock

![image](https://user-images.githubusercontent.com/26760571/145228135-0cfea08b-eb15-4045-8851-678641219c08.png)

The config is using the weekly schedule, see:
https://github.com/netlify/netlify-cms/blob/0053ebbb46f189469c86518eb458daa34a8fec4d/renovate.json#L2
https://github.com/netlify/renovate-config/blob/1cb5cafdb879e7285991f3e23f94c3888c73f1a4/default.json#L2

### Relevant debug logs

<details><summary>Lock file logs</summary>

```
DEBUG: recreateClosed is true(branch="renovate/lock-file-maintenance")
DEBUG: Checking schedule(null, null)(branch="renovate/lock-file-maintenance")
DEBUG: No schedule defined(branch="renovate/lock-file-maintenance")
DEBUG: Branch needs creating(branch="renovate/lock-file-maintenance")
DEBUG: Using reuseExistingBranch: false(branch="renovate/lock-file-maintenance")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/lock-file-maintenance")
DEBUG: No package files need updating(branch="renovate/lock-file-maintenance")
DEBUG: Getting updated lock files(branch="renovate/lock-file-maintenance")
```

</details>

<details><summary>Non lock file logs</summary>

```
DEBUG: Checking schedule(before 3am on Monday, null)(branch="renovate/major-gatsby-monorepo")
DEBUG: Checking 1 schedule(s)(branch="renovate/major-gatsby-monorepo")
DEBUG: Checking schedule "before 3am on Monday"(branch="renovate/major-gatsby-monorepo")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          10800
        ],
        "d": [
          2
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: Package not scheduled(branch="renovate/major-gatsby-monorepo")
DEBUG: Skipping PR creation out of schedule(branch="renovate/major-gatsby-monorepo")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
The log says `DEBUG: No schedule defined(branch="renovate/lock-file-maintenance")`, so it seems pretty clear that Renovate doesn't think it's weekly. Are you seeing the same for any other branches or just the lock file maintenance?

**Comment by rarkins** [comment]
I've done a dry run locally with `printConfig: true` option and the resolved config looks "right":

```
         "lockFileMaintenance": {
           "enabled": true,
           "recreateClosed": true,
           "rebaseStalePrs": true,
           "branchTopic": "lock-file-maintenance",
           "commitMessageAction": "Lock file maintenance",
           "commitMessageTopic": null,
           "commitMessageExtra": null,
           "schedule": ["before 5am on monday"],
           "groupName": null,
           "prBodyDefinitions": {"Change": "All locks refreshed"}
         },
```

*Maybe* this other reference could be interfering, but I don't expect so:

```
         "pip-compile": {
           "fileMatch": [],
           "lockFileMaintenance": {
             "enabled": true,
             "branchTopic": "pip-compile-refresh",
             "commitMessageAction": "Refresh pip-compile outputs"
           }
         },
```

So now we need to work out why the schedule is somehow getting "lost".

BTW the schedule field controls when the branch is created, not when the PR is created. So if the branch already existed, then the schedule is essentially bypassed. This might be what's happened, but I'm also suspicious about the "No schedule defined" log message.

**Comment by erezrokah** [comment]
Thanks @rarkins for the quick replies, we delete branches on merge so we should not have old branches.

I merged https://github.com/netlify/netlify-cms/pull/6040 just in case to see if a new one is created

**Comment by erezrokah** [comment]
It's not recreating the PR since there are not changes, but the logs are the same:

```
DEBUG: No schedule defined(branch="renovate/lock-file-maintenance")
DEBUG: Branch needs creating(branch="renovate/lock-file-maintenance")
DEBUG: Using reuseExistingBranch: false(branch="renovate/lock-file-maintenance")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/lock-file-maintenance")
DEBUG: No package files need updating(branch="renovate/lock-file-maintenance")
DEBUG: Getting updated lock files(branch="renovate/lock-file-maintenance")
DEBUG: Writing package.json files(branch="renovate/lock-file-maintenance")
```

**Comment by erezrokah** [comment]
Ok, so this has gotten worse, see https://github.com/erezrokah/netlify-plugin-epsagon/pulls?q=is%3Apr+is%3Aclosed

![image](https://user-images.githubusercontent.com/26760571/146193595-2d116def-8213-4fe9-90ea-3d6467433e1b.png)

**Comment by rarkins** [comment]
I suggest you disable automerge or requiredStatusChecks=null. Npm is generating a different random string each run and then you have configured it to automerge immediately.

**Comment by erezrokah** [comment]
Going to close this as I haven't experienced this in a while
