### ISSUE TITLE
Export an async function from `config.js`

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#13035]
### What would you like Renovate to be able to do?

I like to do some async stuff in the `config.js`, so i should be able to export an async function.

### If you have any ideas on how this should be implemented, please tell us here.

see https://github.com/renovatebot/renovate/discussions/13033

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
@rarkins @JamieMagee Comments? Suggestions?

**Comment by rarkins** [comment]
I hadn't realised it would be so simple. If it works, I can't think of any problems

**Comment by viceice** [comment]
we can first use `is.function` to check if it's a plain object or function. 
If it's a function, we can simply invoke and await it.
maybe ca can also await the expoted value, so the export can also be a simple promise.

**Comment by rarkins** [comment]
A plain object could contain a function too though?

**Comment by pmorch** [comment]
What use case would benefit from being able to return an async function that is already not served by being able to return a `Promise` of a config?

**Comment by pmorch** [comment]
Perhaps my example would've been clearer to read like this :

```javascript
async function getConfig() {
    const projectsResult = await got(endpoint + '/projects', { ... });
    const repositories = projectsResult.body.map(r => { return r.path_with_namespace });
    return {
        token,
        endpoint,
        platform: 'gitlab',
        onboarding: false,
        dryRun: true,
        repositories
    }
}

module.exports = getConfig()
```

**Comment by pmorch** [comment]
> If it works, I can't think of any problems

:-) It works. The example in #13033 works against our internal gitlab where `repositories` ends up with exactly the projects containing the `helm` topic.

**Comment by viceice** [comment]
I like to also support exporting a function directly, which makes code not much more complicated.

**Comment by pmorch** [comment]
And it does make `config.js` a little simpler to read:

```javascript
module.exports = async function () {
  const projectsResult = await got(endpoint + '/projects', { ... });
  ...
  return { ... }
}
```

So now it could be a function or not, that returns/is a promise or a plain object. The diff becomes a little larger and more test cases are required, but yes, not by much:

```diff
diff --git a/lib/workers/global/config/parse/file.ts b/lib/workers/global/config/parse/file.ts
index 103d24d86..b0be39886 100644
--- a/lib/workers/global/config/parse/file.ts
+++ b/lib/workers/global/config/parse/file.ts
@@ -5,6 +5,7 @@ import { migrateConfig } from '../../../../config/migration';
 import type { AllConfig, RenovateConfig } from '../../../../config/types';
 import { logger } from '../../../../logger';
 import { readFile } from '../../../../util/fs';
+import is from 'is';
 
 export async function getParsedContent(file: string): Promise<RenovateConfig> {
   switch (upath.extname(file)) {
@@ -18,7 +19,14 @@ export async function getParsedContent(file: string): Promise<RenovateConfig> {
       return JSON5.parse(await readFile(file, 'utf8'));
     case '.js': {
       const tmpConfig = await import(file);
-      return tmpConfig.default ? tmpConfig.default : tmpConfig;
+      let config = tmpConfig.default ? tmpConfig.default : tmpConfig;
+      // Allow the config to be a function
+      if (is.fn(config)) {
+        config = config()
+      }
+      // and/or a promise
+      config = await config;
+      return config;
     }
     default:
       throw new Error('Unsupported file type');
```
(I've used `is.fn` instead of `is.function` because `is.function` is deprecated)

**Comment by JamieMagee** [comment]
I agree with Rhys on this. The changes look minimal, easily tested, and yet enables a lot for Renovate users. It gets a 👍 from me.

**Comment by pmorch** [comment]
@viceice : you write in the original post: 

> **Is this a feature you are interested in implementing yourself?**
> Maybe

Do you want to do it or would you like me to prepare a PR? 

If you'd like me to do it, would this be an appropriate commit message?

```
feat(config)!: allow exporting async config (#13035)

module.exports can now be a function and it can be/return a Promise, allowing the results of
asynchronous operations to be used in the configuration.
```

**Comment by rarkins** [comment]
Please go ahead with a PR.

Is it really breaking though? I thought it would be backwards compatible.

**Comment by pmorch** [comment]
Breaking? I'm glad I asked. Is there some convention in the commit message that implies that the change is breaking? As far as I can see it is backwards compatible.

**Comment by viceice** [comment]
I think it's not breaking, so remove `!` from the message header

**Comment by rarkins** [comment]
Yes `feat(config)!` denotes a breaking change due to the `!`

**Comment by pmorch** [comment]
Ok, I'll use this:
```
feat(config): allow exporting async config (#13035)

module.exports can now be a function and it can be/return a Promise, allowing the results of
asynchronous operations to be used in the configuration.
```

**Comment by pmorch** [comment]
As described in #13075, it runs out that 9aa97af5b346f82b48564c20c66783b51c3022d9 introduced around the same time as my original discussion in #13033 also did an extra `await` so `Promises` are now handled, so I didn't have to. But #13075 now tests both Promises and functions, even though it actually only handles functions.
