### ISSUE TITLE
Wrong links in our own autogenerated Renovate `30.0.0` release notes

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#13038]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

**Steps to reproduce:**

1. Go to the Renovate `30.0.0` release-notes [^renovate-30]
1. Hover over `#12644` link, see `https://github.com/renovatebot/renovate/issues/12644`.
1. Click on `#12644` link, end up at a GitHub 404 page.
1. Problem is with the link itself, it should link to: `https://github.com/renovatebot/renovate/pull/12644`.
1. Link fragment is wrong, it uses `/issues/` but should be `/pull/`
1. All links with `#number` pattern are broken, the commit links are okay.

**Discussion:**

I don't know if we're doing something wrong or if this is a bug in the `semantic-release` package.

[^renovate-30]: https://github.com/renovatebot/renovate/releases/tag/30.0.0

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
I thought that github used to redirect all `/issues/x` urls to `/pull/x` if it was a PR.

I'm pretty sure `semantic-release` generates the text fully itself.

FYI here is the raw markdown:

```
## [29.0.0](https://github.com/renovatebot/renovate/compare/28.26.0...29.0.0) (2021-11-05)


### ⚠ BREAKING CHANGES

* **automerge:** Platform automerge is no longer enabled by default.
* **go:** Go modules lookups will now no longer fallback to Renovate native lookups if GOPROXY is configured and without "direct" explicitly configured.
* **manager/regex:** allow arbitrary regex groups for templates (#12296)
* **config:** `hostRules` are no longer automatically derived from env variables such as `NPM_X_TOKEN`. Set `detectHostRulesFromEnv=true` in config to re-enable same functionality.

### Features

* **config:** make host rule detection configurable and opt-in ([#12294](https://github.com/renovatebot/renovate/issues/12294)) ([70700ee](https://github.com/renovatebot/renovate/commit/70700eedae5b28076ab0ce7c29a7526b21c92390))
* **manager/regex:** allow arbitrary regex groups for templates ([#12296](https://github.com/renovatebot/renovate/issues/12296)) ([1b84c52](https://github.com/renovatebot/renovate/commit/1b84c5282a1e02528f3f2cc464fb41a65e5ecf4b))


### Bug Fixes

* **automerge:** default platformAutomerge to false ([#12487](https://github.com/renovatebot/renovate/issues/12487)) ([2735ac3](https://github.com/renovatebot/renovate/commit/2735ac3e806ba947168bc6524750623ed41e29f8))
* **go:** Don't fallback if GOPROXY used ([#12407](https://github.com/renovatebot/renovate/issues/12407)) ([f759f16](https://github.com/renovatebot/renovate/commit/f759f165204cee62666693d75d474345c696dc85))


### Documentation

* improve descriptions ([4eadba6](https://github.com/renovatebot/renovate/commit/4eadba6458cc7a1806d5b05f945f6ea4743829b6))
```

**Comment by viceice** [comment]
I think GitHub disable the redirect. Not sure if it's intentional.

**Comment by rarkins** [comment]
FYI @travi @gr2m, have you seen this before? I've been browsing the semantic-release repos and don't see mention of something

**Comment by travi** [comment]
> I thought that github used to redirect all `/issues/x` urls to `/pull/x` if it was a PR.

this is the behavior that i remember as well. if might be worth starting by reaching out to github support to see if the redirects were removed accidentally before effort is put into working around this.

**Comment by rarkins** [comment]
@JamieMagee Jamieeeeeeeeeeeeeeeeee

**Comment by travi** [comment]
for some context, [`@semantic-release/release-notes-generator`](https://github.com/semantic-release/release-notes-generator) uses [`conventional-changelog-writer`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer) to generate the notes. 

i found [an issue](https://github.com/conventional-changelog/conventional-changelog/issues/655) there where someone was asking about the notes always using `issues` instead of `pull`, which confirms that this is intentional behavior that relies on the redirects, in case that needs confirmation.

**Comment by JamieMagee** [comment]
> @JamieMagee Jamieeeeeeeeeeeeeeeeee

It wasn't me 👀

**Comment by viceice** [comment]
> > @JamieMagee Jamieeeeeeeeeeeeeeeeee
> 
> It wasn't me 👀 

Do you know something? 🤭

**Comment by wwuck** [comment]
https://github.com/github/feedback/discussions/8623

**Comment by travi** [comment]
saw [this](https://github.com/github/feedback/discussions/8691#discussioncomment-1798886) today and confirmed that things seem to be working again. i think this can be closed

**Comment by HonkingGoose** [comment]
Closing this issue, the problem is resolved now!

Thank you everybody for helping debug the problem and providing helpful links! 🥳
