### ISSUE TITLE
[Node] Lock file maintenance gets stuck in conflicted (outdated) state

### ISSUE THREAD

**Issue by aaronadamsCA** [renovatebot/renovate#13126]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Job ID 530403537, branch `renovate/lock-file-maintenance`.

<details><summary><code>.renovaterc.json</code></summary>

```json
{
  "extends": [
    "config:js-app",
    ":disableRateLimiting",
    ":dependencyDashboard",
    ":label(type: dependencies)",
    ":enableVulnerabilityAlertsWithLabel(type: security)",
    ":maintainLockFilesWeekly",
    ":automergePatch",
    ":automergeLinters",
    ":automergeTesters",
    ":automergeTypes"
  ],
  "postUpdateOptions": ["yarnDedupeHighest"],
  "prCreation": "not-pending",
  "stabilityDays": 2
}
```

</details>

Steps to reproduce:

- Check that branch `renovate/lock-file-maintenance` already exists, but no PR has been opened.
  - I think this is expected behaviour when using `:maintainLockFilesWeekly`; Renovate maintains a branch, but doesn't open a PR until the end of the week.
- Manually regenerate the lockfile and merge to main.
- Check the box on the dependency dashboard to create a lock file maintenance PR.

Expected: Renovate deletes branch `renovate/lock-file-maintenance`, since no maintenance is currently required.
Actual: Renovate opens a PR to merge the now-outdated contents of `renovate/lock-file-maintenance`.

I think it's just a matter of tweaking the logic when the branch exists, but yarn.lock hasn't changed vs. main.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: yarn.lock hasn't changed(branch="renovate/lock-file-maintenance")
DEBUG: No updated lock files in branch(branch="renovate/lock-file-maintenance")
DEBUG: No files to commit(branch="renovate/lock-file-maintenance")
DEBUG: Checking if we can automerge branch(branch="renovate/lock-file-maintenance")
DEBUG: mergeStatus=no automerge(branch="renovate/lock-file-maintenance")
DEBUG: Ensuring PR(branch="renovate/lock-file-maintenance")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/lock-file-maintenance")
DEBUG: Found existing PR(branch="renovate/lock-file-maintenance")
DEBUG: resolveBranchStatus(branchName=renovate/lock-file-maintenance, ignoreTests=false)(branch="renovate/lock-file-maintenance")
DEBUG: getBranchStatus(renovate/lock-file-maintenance)(branch="renovate/lock-file-maintenance")
DEBUG: branch status check result(branch="renovate/lock-file-maintenance")
{
  "state": "pending",
  "statuses": []
}
DEBUG: check runs result(branch="renovate/lock-file-maintenance")
{
  "checkRuns": [
    {
      "name": "check",
      "status": "completed",
      "conclusion": "success"
    }
  ]
}
DEBUG: Branch status green(branch="renovate/lock-file-maintenance")
DEBUG: Processing existing PR(branch="renovate/lock-file-maintenance")
DEBUG: resolveBranchStatus(branchName=renovate/lock-file-maintenance, ignoreTests=false)(branch="renovate/lock-file-maintenance")
DEBUG: getBranchStatus(renovate/lock-file-maintenance)(branch="renovate/lock-file-maintenance")
DEBUG: branch status check result(branch="renovate/lock-file-maintenance")
{
  "state": "pending",
  "statuses": []
}
DEBUG: check runs result(branch="renovate/lock-file-maintenance")
{
  "checkRuns": [
    {
      "name": "check",
      "status": "completed",
      "conclusion": "success"
    }
  ]
}
DEBUG: Branch status green(branch="renovate/lock-file-maintenance")
DEBUG: Branch status is: green(branch="renovate/lock-file-maintenance")
DEBUG: updatePr(1441, Lock file maintenance, body)(branch="renovate/lock-file-maintenance")
DEBUG: PR updated(branch="renovate/lock-file-maintenance")
{
  "pr": 1441
}
INFO: PR updated(branch="renovate/lock-file-maintenance")
{
  "pr": 1441,
  "prTitle": "Lock file maintenance"
}
DEBUG: PR is configured for automerge(branch="renovate/lock-file-maintenance")
DEBUG: PR is conflicted(branch="renovate/lock-file-maintenance")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Can you create a repo which is in this state?

**Comment by aaronadamsCA** [comment]
> Can you create a repo which is in this state?

That might be more difficult than it's actually worth. As soon as one sub-dependency released and Renovate re-ran, this issue cleared itself, because "yarn.lock hasn't changed vs. main" was no longer the case.

It lasted long enough for me to fiddle around with it, get frustrated, and file the bug; but not much longer than that.

To create a stable minimal reproduction, I think I would need to publish my own version-controlled package.

So this is probably just a doc note, or even a closed issue that might help someone else later.
