### ISSUE TITLE
Fetching changelogs from github.com fails when the source URL contains "gitlab"

### ISSUE THREAD

**Issue by mmslkr** [renovatebot/renovate#13139]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.2.2

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

31.2.2

### Describe the bug

When fetching changelogs, Renovate checks the source URL to decide which API to call, see https://github.com/renovatebot/renovate/blob/74d7691befa635c1220d8569936273bfb950e748/lib/workers/pr/changelog/index.ts#L30-L38

This breaks when fetching a URL from github.com which includes the string "gitlab", see debug logs.

A workaround right now is to uppercase "gitlab" while setting the depName.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Fetching changelog: https://github.com/voxpupuli/puppet-gitlab_ci_runner (3.0.0 -> v4.2.0) (repository=lkr/test-repo)
DEBUG: Multiple candidates for changelog file, using CHANGELOG.md (repository=lkr/test-repo)
DEBUG: GitLab API 404 (repository=lkr/test-repo)
       "url": "https://github.com/api/v4/projects/voxpupuli%2fpuppet-gitlab_ci_runner/repository/tags?per_page=100"
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
I think it's possibly the combination of also running *on* gitlab self-hosted too

**Comment by mmslkr** [comment]
In my case, it really is just the check for
```
args.sourceUrl?.includes('gitlab')
```
because changing the `depName` from `voxpupuli/puppet-gitlab_ci_runner` to `voxpupuli/puppet-GITLAB_ci_runner` solves it. But thanks for looking into it.

**Comment by viceice** [comment]
That code is already refactored and this should be fixed
