### ISSUE TITLE
GitHub Action Updates Should Update Files Outside .github Directory

### ISSUE THREAD

**Issue by RehanSaeed** [renovatebot/renovate#13136]
### What would you like Renovate to be able to do?

I have project templates which contain GitHub Actions `.yml` files. These files do not live under the `.github/workflows` directory and so currently Renovate does not update them.

I would like Renovate to look for GitHub Actions `yml` files across the entire repo and update them.

### If you have any ideas on how this should be implemented, please tell us here.

This is just extending the existing GitHub Actions updates to scan the entire repo instead of just the `.github/workflows` directory.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
It's not a good idea to scan every yml file in every repo just in case they are an actions file. If it's the same format then you can use `fileMatch` to extend the existing patterns. Does that work for you?

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/146340680-d780e214-f0b8-4f07-b9c2-6df8cefe4da2.png)

https://docs.renovatebot.com/modules/manager/github-actions/

**Comment by RehanSaeed** [comment]
That works, thanks.

**Comment by RehanSaeed** [comment]
Wait, would it make sense to scan for `**/.github/workflows/**/*.yml` instead of `.github/workflows/**/*.yml`?

**Comment by HonkingGoose** [comment]
I think the default/recommended path [^path] to put your workflow files is in the `.github/workflows` directory, if I'm reading the GitHub Docs correctly:

> Workflow files use YAML syntax, and must have either a `.yml` or `.yaml` file extension. If you're new to YAML and want to learn more, see "Learn YAML in Y minutes."
> 
> You must store workflow files in the `.github/workflows` directory of your repository.

[^path]: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

**Comment by RehanSaeed** [comment]
Yes thats correct.

I have a repo containing project templates which means I need to keep them elsewhere.

**Comment by rarkins** [comment]
> Wait, would it make sense to scan for `**/.github/workflows/**/*.yml` instead of `.github/workflows/**/*.yml`? That way we'd still be constraining the files to be searched.

I think we could widen our default `fileMatch` in that way too. The main point is that we won't check every yml file in every repository "just in case". If you can ensure they are always within a ".github/workflows/" directory - whether at the root or not - would seem like a suitable compromise.

**Comment by RehanSaeed** [comment]
Potential PR to fix this issue:

https://github.com/renovatebot/renovate/pull/13143
