### ISSUE TITLE
Onboarding PR configuration summary doesn't handle contradictory presets

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#1317]
I've updated our onboarding PR (mozilla/treeherder#3025) to include:
```js
  "extends": [
    "config:js-app",
    ":maintainLockFilesWeekly",
    ":prNotPending",
    ":unpublishSafe"
  ],
```

The onboarding summary then says:
```
* Raise PRs immediately (after branch is created)
...
* Wait until branch tests have passed or failed before creating the PR
```

...which are complete opposites.

This is presumably since `config:base` uses `:prImmediately`, whereas I've then added `:prNotPending` to reverse it - and the onboarding PR summary just concatenates the descriptions, not realising that the former is cancelled out by the latter.

This is probably actually a pain to fix, unless all presets have some concept of which others they overwrite. The more I think about this topic, the more I think these long-form human readable descriptions don't belong in presets, but in renovate's `definitions.js` instead?

**Comment by rarkins** [comment]
Yes, this is expected but undesirable. Cosmetic problem only (description, not actual code). Kind of related to #841.

We either need to:

1. Be *super* smart in detecting at a code level if one preset has overridden another.
2. Allow presets to define which others they override functionally (#841) - this could be both a functional and cosmetic "fix"
3. Allow presets to define description override only, i.e. cosmetic solution only

The reason for #841 existing is more for use cases like this:

1. User has `"config:base"`
2. User does not want to group monorepos
3. User does not want to remove "config:base" and add every sub-preset individually

So it would allow you to take a full preset like `"config:base"` but then selectively disable any features. If we did this, then we could probably solve the onboarding description problem at the same time, e.g. if `":prNotPending"` is defined to disable `":prImmediately"`.

**Comment by destroyerofbuilds** [comment]
We recently ran into this issue ourselves on a pull request, though with slightly different cosmetic results.

Our configuration was/is:

```json
{
  "extends": [
    "config:base"
  ],
  "automerge": true
}
```

In the _Configuration Summary_ we have the following line:

```
Disable automerging feature - wait for humans to merge all PRs
```

This is because `config:base` sets `:automergeDisabled`.

It's not apparent from the pull request description that Renovate will respect the `"automerge": true` option in our configuration.

**Comment by edmorley** [comment]
Many thanks :-)
