### ISSUE TITLE
Private GitLab Go Module Authentication Broken

### ISSUE THREAD

**Issue by 56KBs** [renovatebot/renovate#13214]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### Describe the bug

When using Renovate with GitLab containing modules that require authentication in order to clone - You are unable to clone the repository via `go get`:

```
Command failed: go get -d ./...
go: gitlab.organisation.com/group/repo@v0.0.0-20210720093222-840405cb7fed: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/361ab0bd9e389a79bc433dfa617b65adaaf3bb82a53ca917e31147d966f30064: exit status 128:
	fatal: could not read Password for 'https://**redacted**@gitlab.organisation.com': terminal prompts disabled
```

I believe this issue appeared from #11077 being introduced. Previously we would configure `~/.netrc` within our Docker image for Renovate, which worked without issue.

Renovate will automatically add the GitLab token configured in your configuration as a host rule for convenience (`[2021-12-21T08:55:51.839Z] DEBUG: Adding token authentication for gitlab.organisation.com to hostRules`), resulting in the following within the host rules:

```json
"hostRules": [
  {"timeout": 60000},
  {"hostType": "github", "matchHost": "github.com", "token": "***********"},
  {
    "matchHost": "gitlab.organisation.com",
    "token": "***********",
    "hostType": "gitlab"
  }
],
```

However now that #11077 uses these host rules to inject git configuration, this configures the following environment variables when running `go` commands:

```
GIT_CONFIG_KEY_0=url.https://this-is-a-token@gitlab.organisation.com/.insteadOf
GIT_CONFIG_VALUE_0=https://gitlab.organisation.com
GIT_CONFIG_COUNT=1
```

This configuration overrides the `~/.netrc` configuration, using the configured `GIT_CONFIG_X` values for authentication - GitLab requires a username with the token in order for it to function with git commands (This does not apply for GitLab API calls using the `Authorization` header).

The end result here is that GitLab private repositories cannot be `go get`'d , causing Renovate to fail.

References discussion #12552

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
.netrc was never supported or documented. Please resubmit this as a feature request if the current capability does not meet your needs.

**Comment by rarkins** [comment]
What I mean is that we don't intend to "unbreak" something as a bug fix which wasn't an intentional feature to begin with. If it can be supported properly as a feature because our current approach doesn't work then let's discuss.

**Comment by 56KBs** [comment]
> .netrc was never supported or documented. Please resubmit this as a feature request if the current capability does not meet your needs.
> What I mean is that we don't intend to "unbreak" something as a bug fix which wasn't an intentional feature to begin with. If it can be supported properly as a feature because our current approach doesn't work then let's discuss.


Ah I was unaware that `~/.netrc` was never intended as a functional feature. It looks like #12912 would resolve my issue.
