### ISSUE TITLE
Renovate does not (re)create a PR when using rebaseWhen=never

### ISSUE THREAD

**Issue by annuh** [renovatebot/renovate#13219]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Describe the bug

Renovate does not automatically create PR's when using `rebaseWhen=never`. It does create a [new branch](https://github.com/annuh/renovate-no-pr/tree/renovate/major-symfony) with the expected changes, but the PR is never opened.

Triggering PR's via the dashboard does work as expected.

In the reproduction repo I'm using the following config:
```
{
    "extends": [
        "config:base"
    ],
    "enabledManagers": [
        "composer"
    ],
    "prCreation": "not-pending",
    "rangeStrategy": "update-lockfile",
    "rebaseWhen": "never",
    "updateNotScheduled": false
}
```

The reproduction repo can be found here: https://github.com/annuh/renovate-no-pr

FYI: When we delete the `rebaseWhen` config, Renovate will rebase all branches it created when something is committed to the main branch. This is something we would like to avoid.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/major-symfony
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 1 Pull Requests
DEBUG: currentHourStart=2021-12-21T15:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating prConcurrentLimit (10)
DEBUG: getBranchPr(renovate/major-symfony)
DEBUG: findPr(renovate/major-symfony, undefined, open)
DEBUG: findPr(renovate/major-symfony, undefined, closed)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 10
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 2
}
DEBUG: PullRequests limit = 2
DEBUG: Calculating hourly PRs remaining
DEBUG: currentHourStart=2021-12-21T15:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating branchConcurrentLimit (10)
DEBUG: 1 already existing branches found: renovate/major-symfony
DEBUG: Branch concurrent limit remaining: 9
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 2
}
DEBUG: Branches limit = 2
DEBUG: Setting current branch to main(branch="renovate/major-symfony")
DEBUG: latest commit(branch="renovate/major-symfony")
{
  "branchName": "main",
  "latestCommitDate": "2021-12-21T16:22:32+01:00"
}
DEBUG: getBranchPr(renovate/major-symfony)(branch="renovate/major-symfony")
DEBUG: findPr(renovate/major-symfony, undefined, open)(branch="renovate/major-symfony")
DEBUG: findPr(renovate/major-symfony, undefined, closed)(branch="renovate/major-symfony")
DEBUG: branchExists=true(branch="renovate/major-symfony")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/major-symfony")
DEBUG: recreateClosed is false(branch="renovate/major-symfony")
DEBUG: findPr(renovate/major-symfony, Update dependency symfony/console to v6, !open)(branch="renovate/major-symfony")
DEBUG: prAlreadyExisted=false(branch="renovate/major-symfony")
DEBUG: Checking if PR has been edited(branch="renovate/major-symfony")
DEBUG: Branch has not been modified(branch="renovate/major-symfony")
{
  "branchName": "renovate/major-symfony"
}
DEBUG: Checking schedule(at any time, null)(branch="renovate/major-symfony")
DEBUG: No schedule defined(branch="renovate/major-symfony")
DEBUG: Branch already exists(branch="renovate/major-symfony")
DEBUG: getBranchPr(renovate/major-symfony)(branch="renovate/major-symfony")
DEBUG: findPr(renovate/major-symfony, undefined, open)(branch="renovate/major-symfony")
DEBUG: findPr(renovate/major-symfony, undefined, closed)(branch="renovate/major-symfony")
DEBUG: Skipping stale branch check due to rebaseWhen=never(branch="renovate/major-symfony")
DEBUG: Branch does not need rebasing(branch="renovate/major-symfony")
DEBUG: Using reuseExistingBranch: true(branch="renovate/major-symfony")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=true(branch="renovate/major-symfony")
DEBUG: Found composer lock file(packageFile="composer.json", branch="renovate/major-symfony")
DEBUG: Found composer lock file(packageFile="composer.json", branch="renovate/major-symfony")
DEBUG: Branch dep is already updated(packageFile="composer.json", branch="renovate/major-symfony")
{
  "depName": "symfony/console"
}
DEBUG: No content changed(packageFile="composer.json", branch="renovate/major-symfony")
{
  "depName": "symfony/console"
}
DEBUG: No package files need updating(branch="renovate/major-symfony")
DEBUG: No updated lock files in branch(branch="renovate/major-symfony")
DEBUG: Skipping commit (rebaseWhen=never)(branch="renovate/major-symfony")
DEBUG: getBranchPr(renovate/major-symfony)
DEBUG: findPr(renovate/major-symfony, undefined, open)
DEBUG: findPr(renovate/major-symfony, undefined, closed)
DEBUG: Ensuring Dependency Dashboard
INFO: Blocked PR
{
  "result": "no-work"
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Interesting, I have an existing fix PR related to rebaseWhen=never here: https://github.com/renovatebot/renovate/pull/13218

It was solving another problem, but may help with yours.

I will try to test it against your reproduction to see if it already fixes it.

**Comment by rarkins** [comment]
Actually that's quite an edge case. I recommend you don't use `rebaseWhen=never` in general, but definitely not with prCreation=not-pending.

**Comment by annuh** [comment]
Thanks for the tip! I've removed those settings and now I'm back to the original problem (why we needed `rebase=never` in the first place), but I've created a new issue for that 🙂

**Comment by SashRaven** [comment]
I want to raise this issue and ask for help (or clarification) with rebaseWhen=never.
I need to use rebaseWhen=never cause my repo has a long ci test and rebase triggers a lot of ci jobs that prevent deploying features, cause ci queue is occupied by renovate.
No, I'm not using prCreation=not-pending.
And yes, with rebaseWhen=auto - renovate creates PRs as expected.
With rebase=never renovate:
- does create branches with updates
- does trigger ci for new branches
- does create dependency dashboard 
- does update dependency dashboard, but all branches are under "Other Branches".
- dependency dashboard says "These updates are pending. To force MRs open, click the checkbox below.". However, clicking on the checkbox does nothing. On next, the next run renovate simply removes all checkboxes.
- doesn't create PR for branches that have passed ci.

Maybe we understand it wrong and "rebaseWhen=never." means "turn off PR creation at all"?
Thanks.

**Comment by rarkins** [comment]
@SashRaven Please create a separate issue with minimal reproduction repo as this current one is classified as a dashboard problem while you are describing something different
