### ISSUE TITLE
Gradle Wrapper should update the version in the wrapper task as well

### ISSUE THREAD

**Issue by kennethjor** [renovatebot/renovate#13251]
### What would you like Renovate to be able to do?

Many people define a `wrapper` task in their Gradle files like

```
wrapper {
	gradleVersion = "7.1.1"
	distributionType = "ALL"
}
```
Renovate correctly updates the `gradle-wrapper.properties` file with the new version, but it would be neat if it could also detect this wrapper task definition and update that in the same way.

### If you have any ideas on how this should be implemented, please tell us here.

I don't.

### Is this a feature you are interested in implementing yourself?

No

**Comment by kennethjor** [comment]
Sorry for the delay. Holidays and whatnot. Minimal repo created here: https://github.com/kennethjor/renovate-bot-gradle-build-minimal-repo - please let me know if it's not sufficient.

**Comment by rarkins** [comment]
We need to decide if this should be detected as part of our `gradle` manager or `gradle-wrapper`

**Comment by kennethjor** [comment]
A quick workaround for this, if anyone else happens to look for it: you can just remove the version from the build file. Renovate Bot will handle the upgrade in the properties file and install new wrapper files, so this task is not needed any longer.
