### ISSUE TITLE
Support scan buildSrc's Dependencies?

### ISSUE THREAD

**Issue by logosmjt** [renovatebot/renovate#13295]
### What would you like Renovate to be able to do?

```
buildSrc     
├── src    
│ └── main   
│ ─└── kotlin   
│ ──└── Dependencies.kt   
├── build.gradle.kts
```

There are many projects that manage dependencies in this way. 
Renovate could support this way to scan?

### If you have any ideas on how this should be implemented, please tell us here.

Scan `Dependencies.kt` and `build.gradle.kts`.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
It sounds like something we might be able to add support for. Can you create a reproduction to begin with?

**Comment by logosmjt** [comment]
According to these two issues, 
https://github.com/renovatebot/renovate/pull/4086
https://github.com/renovatebot/renovate/issues/5480
is it recommended to update fileMatch?

**Comment by logosmjt** [comment]
I migrated this [small sample](https://github.com/logosmjt/JetpackComposeSample) to `buildSrc`.

**Comment by Goooler** [comment]
Also link #12397, #9410.

**Comment by Goooler** [comment]
I added `fileMatch` to `renovate.json` like this:
```json
"regexManagers": [
  {
    "fileMatch": [
      "(^|/)buildSrc/.*"
    ],
    "datasourceTemplate": "gradle"
  }
],
```
But renovate bot told me an syntax error: `Each Regex Manager must contain a non-empty matchStrings array`, how can I add the `matchStrings` for all deps under `buildSrc`?

**Comment by rarkins** [comment]
This feature is not the right place to discuss regex manager howto's. Please raise a discussion instead, but I recommend you read more on regex manager first because I suspect you misunderstand it and shouldn't be using it for this
