### ISSUE TITLE
Migrate packagist API to v2

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#13359]
### What would you like Renovate to be able to do?

Currently renovate uses the old composer / packagist v1 API, with will soon no longer updated on packagist.org

- https://blog.packagist.com/deprecating-composer-1-support/
- composer/composer#10340
- #13188

### If you have any ideas on how this should be implemented, please tell us here.

Sure, read docs and use new endpoints

- https://packagist.org/apidoc

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by RahulGautamSingh** [comment]
Hey @viceice I would like to work on this issue, can I be assigned to this please?

**Comment by rarkins** [comment]
Do we need to retain fallback if there are registries which only support v1?

**Comment by viceice** [comment]
Yes, we should cache per registry which api version is supported. So we don't retry failing api for each package.

**Comment by RahulGautamSingh** [comment]
We extract the releases using this function which takes input of type RegistryFile but actually it takes in an object as per APIv1 and in the APIv2 it needs to be changed to an array type. Can I add a new interface as per the returned value of new API?

https://github.com/renovatebot/renovate/blob/ac9b270a823def7dc115ebdda8a07bbdb1c0b83d/lib/datasource/packagist/index.ts#L115-L135

**Comment by viceice** [comment]
@RahulGautamSingh We need to support both api versions, as probably all other custom registries still only support v1.

I think only `packagist.org` supports the v2 api, so we should start with that and target other in a later issue /PR.

**Comment by RahulGautamSingh** [comment]
> 

Okay. In that case we will have to send `regUrl` as argument to the function `extractDepReleases`.

**Comment by RahulGautamSingh** [comment]
> @RahulGautamSingh We need to support both api versions, as probably all other custom registries still only support v1.
Okay. In that case we will have to send `regUrl` as argument to the function `extractDepReleases`.

**Comment by viceice** [comment]
No, we should create different child datasources, like we do in rubygems.

**Comment by RahulGautamSingh** [comment]
Before making any changes I wanted to confirm somethings:
1. Will only changing the URL to v2 syntax be a temporary fix or not?
2. Should I change the folder structure to something similar to `rubygems` by introducing new files `get.ts` and `get-packagist-org.ts` and use functionality/logic similar to `rubygems`?

**Comment by rarkins** [comment]
Yes so refactor current code to (mostly) live under a `apiv1/` subdirectory.
Add an `apiv2/` subdirectory too, and have a hardcoded rule to use it for `packagist.org`.
Later, add a way to detect/fall back, and remember the result.

**Comment by RahulGautamSingh** [comment]
Currently if `regUrl === https://packagist.org` then the function `packagistOrgLookup` handles it. So, adding code to the this function to check in new-v2-datasource like we were doing with v1 and incase of any problem falling back to old code, should work right? 
```js
async function packagistOrgLookup(name: string): Promise<ReleaseResult> {
  //check for cached results in v2-datasource
  const v2CacheNamespace = 'datasource-packagist-org-v2';
  let cachedResult = await packageCache.get<ReleaseResult>(
    v2CacheNamespace,
    name
  );
  //if found return
  if (cachedResult) {
    return cachedResult;
  }
  //else try to fetch new info
  let dep: ReleaseResult = null;
  const regUrl = 'https://packagist.org';
  let pkgUrl = URL.resolve(regUrl, `/p2/${name}.json`);
  let res = (await http.getJson<any>(pkgUrl)).body.packages[name];
  if (res) {
    //cache it in apiv2 sub-dir + return
    //might need to update this
    dep = extractDepReleases(res);
    logger.trace({ dep }, 'dep');
    const cacheMinutes = 10;
    await packageCache.set(v2CacheNamespace, name, dep, cacheMinutes);
    return dep;
  }
  
  //else fallback to old code
  const cacheNamespace = 'datasource-packagist-org';
  cachedResult = await packageCache.get<ReleaseResult>(cacheNamespace, name);
  // istanbul ignore if
  if (cachedResult) {
    return cachedResult;
  }
  pkgUrl = URL.resolve(regUrl, `/p/${name}.json`);
  // TODO: fix types (#9610)
  res = (await http.getJson<any>(pkgUrl)).body.packages[name];
  if (res) {
    dep = extractDepReleases(res);
    logger.trace({ dep }, 'dep');
  }
  const cacheMinutes = 10;
  await packageCache.set(cacheNamespace, name, dep, cacheMinutes);
  return dep;
}
```

**Comment by viceice** [comment]
We shouldn't fallback to V1 for packagist.org. if there is any error, the fallback would fail too.

**Comment by rarkins** [comment]
Do we have a plan for now to detect when non packagist hosts support v2?

**Comment by RahulGautamSingh** [comment]
> Do we have a plan for now to detect when non packagist hosts support v2?

Not to my knowledge. We will need to create a new issue to discuss it
