### ISSUE TITLE
Make the name “Renovate” configurable

### ISSUE THREAD

**Issue by infraredgirl** [renovatebot/renovate#13388]
### What would you like Renovate to be able to do?

We are running RenovateBot internally wrapped with our own tooling, our custom configuration, our own machine user, and so on. We’d like to use the internal tool name everywhere, which mostly happens through the configuration and machine user changes, but there are a few places where the name “Renovate” is hard-coded, so we’d like to request that the name is also configurable.

### If you have any ideas on how this should be implemented, please tell us here.

The implementation has started in the PR #13369 and consists of adding a config option to specify the project name.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment]
Please describe more in detail where you want changes.

**Comment by infraredgirl** [comment]
- Example 1: by artifact update failure, comments gets posted referencing "Renovate". This is hard-coded in Renovate source code and cannot currently be configured with existing configuration options.
<img width="716" alt="Screenshot 2022-01-05 at 16 30 56" src="https://user-images.githubusercontent.com/1786860/148244144-166b1a81-2625-4587-bfb2-97bf15efc9e8.png">

- Example 2: also by artifact update failure, the machine user name is hard-coded and references "renovate".
<img width="286" alt="Screenshot 2022-01-05 at 16 32 47" src="https://user-images.githubusercontent.com/1786860/148244341-16f405f7-fa68-4b5c-8022-b5c01dad5c7d.png">

- There are probably other places in the codebase where the string "Renovate" is hard-coded. We'd like to make all such occurrences configurable.

**Comment by rarkins** [comment]
I'm ok with this approach. A while ago I tried to remove a lot of the user-facing hard coding where it made sense to say "the bot" etc.

**Comment by infraredgirl** [comment]
Thanks @rarkins! In that case, could we move forward with the PR https://github.com/renovatebot/renovate/pull/13369 - i.e. remove the `draft` flag and review it? /cc @viceice

**Comment by viceice** [comment]
That PR is far from complete.

@rarkins i think we have a user strings config object, which should be used for this?

**Comment by infraredgirl** [comment]
With regard to using the `userStrings` config for this, thus far [the `userStrings` config object](https://docs.renovatebot.com/configuration-options/#userstrings) has been limited only to the the strings that pertain to the comment that gets posted when a PR is closed. I can certainly work on expanding that scope if that is the desired way forward!

With regard to your other comment @viceice, I'd really appreciate more specific feedback on what else needs addressing the existing PR.

Thanks!

**Comment by rarkins** [comment]
@infraredgirl I'm ok with adding `projectName` to the `userStrings` object

**Comment by rarkins** [comment]
Actually I need to take that back. While ignore text in PRs can be user configurable, I don't think we want the bot name to be user configurable - only admin configurable. So the choice is either to keep `projectName` as an admin option or create a new `globalStrings` with `projectName` inside if we think there will be more admin-only customization.
