### ISSUE TITLE
Incorrect update action files

### ISSUE THREAD

**Issue by splincode** [renovatebot/renovate#13424]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Describe the bug

if I have comments in my action files then renovate mutate code

https://github.com/Angular-RU/angular-ru-sdk/pull/1197/files

![image](https://user-images.githubusercontent.com/12021443/148552420-f454a7f5-c8f3-4061-a426-0deabb95e92b.png)

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

https://github.com/Angular-RU/angular-ru-sdk

**Comment by viceice** [comment]
Move the comments before or after the line as workaround.

**Comment by rarkins** [comment]
Link is to a public repository, not a minimal reproduction

**Comment by splincode** [comment]
@rarkins oh, sorry - https://github.com/Angular-RU/angular-ru-sdk

**Comment by rarkins** [comment]
Please see the autogenerated comment above for our definition of minimal reproduction

**Comment by HonkingGoose** [comment]
Re-opening this issue.

I made a minimal reproduction: https://github.com/renovate-reproductions/13424

I've confirmed this works on a private copy/paste of the repository. I don't know why Renovate bot is not running on the `renovate-reproductions/13424` repo, maybe it needs to be enabled by an administrator of the `renovate-reproductions` organization?

**Comment by HonkingGoose** [comment]
Duplicate of #12260
