### ISSUE TITLE
Update banner SVG 

### ISSUE THREAD

**Issue by mxdvl** [renovatebot/renovate#13432]
### What would you like Renovate to be able to do?

The [banner on the Renovate PRs](https://app.renovatebot.com/images/banner.svg) does not support dark mode.

![renovate banner](https://app.renovatebot.com/images/banner.svg)

### If you have any ideas on how this should be implemented, please tell us here.

This can easily be fixed by changing the first three elements (a `rect`angle and two `polygon`s) into a single polygon:

```svg
<polygon class="cls-1" points="777,41 810,0 834,0 43,0 6,40" />
```

![renovate banner on dark mode](https://now.mxdvl.com/banner.svg)

We could push this logic a bit further and have the white squares be used as a mask.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by mxdvl** [comment]
Comparison on a dark background:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/76776/148656008-f6c887dc-044a-4c8b-9fd5-6a28feca116b.png">

**Comment by rarkins** [comment]
Thanks, that would be very welcome! It may be another repo/location but if you paste the svg code here then I'll make the change

**Comment by mxdvl** [comment]
@rarkins I have pasted the relevant line change above already. If you want the whole thing, I’ve hosted it (temporarily) at this address: https://www.mxdvl.com/banner.svg

There’s a lot more you can do to improve that SVG, but I thought this one was the highest priority.

Thanks for Renovate!

**Comment by rarkins** [comment]
Now published, thanks.
