### ISSUE TITLE
Terraform kubernetes image 

### ISSUE THREAD

**Issue by bodinsamuel** [renovatebot/renovate#13461]
### What would you like Renovate to be able to do?

Hello,

I would like renovate to update kubernetes' Terraform definition.
The same way renovate currently update kubernetes yaml file. I don't know if this update should belong to kubernetes manager or terraform manager, but since this could go beyond just kubernetes I guess it's more logical to be handled by terraform manager.

It should match:
`image(\s*)?=(\s*)?(['"]{1})([a-zA-Z0-9-_.:\/]+)['"]`
https://regex101.com/r/IOH952/2

Non exhaustive list of resources:
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod_v1
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment_v1
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/stateful_set
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/stateful_set_v1
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/daemonset
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/daemon_set_v1
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/job
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/job_v1
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/cron_job
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/replication_controller
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/replication_controller_v1
- ...

### If you have any ideas on how this should be implemented, please tell us here.

I don't know how it's implemented in the kubernetes manager, but I guess a regex should be a fairly simple v1.
But not bulletproof since image could be stored in variable, and could create false positive.

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment]
Quote from the head maintainer [^quote]:

> In that case this needs a feature request, a definitive spec for this resource, and reproduction repo with all examples needing support

We have a feature request, and part of the specifications, but we're missing the reproduction repository.

[^quote]: https://github.com/renovatebot/renovate/discussions/13405#discussioncomment-1924570

**Comment by bodinsamuel** [comment]
Please find a repo with 2 examples: 
https://github.com/bodinsamuel/renovate-terraform-kubernetes

I did not put every possible kubernetes resources since it's the same strategy everytime.

**Comment by rarkins** [comment]
I agree with this being part of the terraform manager.

If we simply look for `image = ` lines, and try to validate that the contents are a valid docker image format, do you think that will reduce false positives enough to be usable?

**Comment by secustor** [comment]
To be in line of the current implementation, `depType` should reflect the Terraform resource, therefore a simple search for image is not enough.

**Comment by rarkins** [comment]
Do we currently have sufficient "parsing" of terraform syntax that we can know the path?

**Comment by secustor** [comment]
We detect the type ( `resource` ) and kind ( `kubernetes_deployment` ), but no blocks inside these upper level definitions e.g. `container`.
