### ISSUE TITLE
Fully remove `deepExtract` from Gradle

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#13490]
### Describe the proposed change(s).

Relevant part of quote by head maintainer @rarkins:

> We are planning to remove Gradle deep functionality in a future major release, perhaps the next one. ...snip...

Todo:

- [ ] Warn user ahead of time in the docs about deprecation, see #13487 
- [ ] Remove `deepExtract` functionality from the renovate
- [ ] Migrate `deepExtract` config
- [ ] Probably some other things that I'm forgetting about now

Feel free to edit the todo's to match the work that needs to be done. 😉

**Comment by rarkins** [comment]
Closed by #14490
