### ISSUE TITLE
bitbucket-cloud: Improve PR auto merge message with updated package/version

### ISSUE THREAD

**Issue by maxbrunet** [renovatebot/renovate#13528]
### What would you like Renovate to be able to do?

The auto-merge message is hard-coded:
https://github.com/renovatebot/renovate/blob/0c977e47f742d0202b50b125a6a24dc96fc9dcb1/lib/platform/bitbucket/utils.ts#L71-L74

With "Squash" as merge strategy, the resulting Git messages are not very insightful:
```
* 28c3a1cc1 - auto merged (5 hours ago) <Renovate>
* a417ee3e7 - auto merged (23 hours ago) <Renovate>
* 70f1db890 - auto merged (2 days ago) <Renovate>
* e1eaf3cf8 - auto merged (2 days ago) <Renovate>
```

It would be preferable to have the minimal information about which package and version is the update about.

This was already reported in #7184, but only the configurable merge strategy has been addressed.

### If you have any ideas on how this should be implemented, please tell us here.

I have not looked in what context the function is called yet, but I think it should get the PR title and use it as message, potentially append `- auto merged` to it similarly to how `- autoclosed` is appended:

https://github.com/renovatebot/renovate/blob/9d61bd9678afcb4c33b4c7198abb9fb4c7b48f69/lib/workers/repository/finalise/prune.ts#L54-L57

It does necessarily need to be configurable.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
Can somebody check if `/2.0/repositories/${config.repository}/pullrequests/${prNo}/merge` needs the message body? Or can we leave it blank and it works like on other platforms?

Otherwise we need to fetch the pr before here:
https://github.com/renovatebot/renovate/blob/05d88a567de0967c59e13aa3abdff2586d1fcf91/lib/platform/bitbucket/index.ts#L813-L818

And pass to `mergeBodyTransformer`, where the message is set.

**Comment by rarkins** [comment]
Let's go with empty message to start with

**Comment by maxbrunet** [comment]
I have solved my issue with using semantic commits, there is a `mergePattern`[^mergePattern] parser option which allows to use the Bitbucket merge message as-is:

```yaml
parserOpts:
  mergePattern: '^Merged in (\S+) \(pull request #(\d+)\)$'
  mergeCorrespondence: ['branch', 'prId']
```

So #13567 is enough for now, the full message format being:

```
Merged in <branch> (pull request #<pr-id>)

<pr-title>

* <commit-1>
...
* <commmit-n>
```

[^mergePattern]: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser#mergepattern
