### ISSUE TITLE
[Feature Request] Add an option to install git submodules before installing dependencies

### ISSUE THREAD

**Issue by emmenko** [renovatebot/renovate#1356]
This is a follow up of this tweet: https://twitter.com/emmenko/status/950122765394366464

### Background
Sometimes you might need to define some dependencies as a git submodule, meaning you checkout the repository through `git submodule` and point the dependency in `package.json` to a local path:

```json
"dependencies": {
  "foo-bar": "file:./my-local-version-of-foo-bar"
}
```

### When would you do something like this?
You might need to do this when you want to install a custom version of a library (e.g. from a fork) and the repository does not contain the package folder on the root level (e.g. with a monorepo setup).
Obviously you want to point npm to the exact location of the package that you want to install but you can't do that if you want to use _github_ as a version url.

```json
"foo-bar": "repo/name#branch
```

So you need to checkout the repository as a submodule, then point the dependency to the correct folder location inside that submodule.

### Proposal
I guess the proposal for this feature would be to have a configuration option to instruct the bot to run `git submodule sync && git submodule update --init` before running `yarn/npm install`.

---
NOTE: I wouldn't consider this a high priority feature and I don't know how many people are actually interested in this. 

Thanks 🙏

**Comment by rarkins** [comment]
Thanks @emmenko for the detailed description to go with this feature request. It's useful for me to understand the "why" too, e.g. forked monorepo. It's a pity you can't specify a subdirectory path in a git reference.

FYI, something Renovate doesn't do yet is a full "git clone" of repositories. In fact we don't run *any* `git x` command at all. We selective pluck files we need via the API, write them to the correct relative location and then run `npm` or `yarn`. Doing a full clone is not something I ever wanted to do, although I think the day is approaching, e.g. so we can do some advanced features like run `eslint --fix` after any eslint upgrade and save you the work.

**Comment by emmenko** [comment]
> so we can do some advanced features like run eslint --fix after any eslint upgrade and save you the work

Uh, that would be a neat feature!

Anyway, thanks for your feedback. Like I said, I wouldn't consider this a high priority feature (unless many other people want this) and I don't want you guys to start doing workarounds.
So whatever you decide is fine for me personally 😉

**Comment by bilby91** [comment]
We are having the same issue here. Is there any workaround for the `Lock file problem` in this situation ?

Thanks!

**Comment by rarkins** [comment]
@bilby91 you also need `git submodule x` to be run prior to install?

**Comment by emmenko** [comment]
FYI: short update from my side. I don't need this anymore to be honest as I removed submodules from my repo. Thought it might be helpful for you to decide on prioritization 😉

**Comment by bilby91** [comment]
@rarkins yes, we need to do that before installing npm dependencies. I'm fine if there is a workaround for this.
