### ISSUE TITLE
Update dependencies in `kotlin-js-store/yarn.lock`

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [renovatebot/renovate#13573]
### What would you like Renovate to be able to do?

Recently, Kotlin Multiplatform added a `yarn.lock` file allowing to update versions. Recently I received a dependabot alert that one version can be vulnerable, and I am not getting updates from Renovate so I guess Renovate is not finding this file.

### If you have any ideas on how this should be implemented, please tell us here.

I guess just adding that path to Renovate finder, if any hint is provided I can try to implement it.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by JavierSegoviaCordoba** [comment]
The file is autogenerated and I am not sure if it safe to edit it. I will reopen if it is

**Comment by rarkins** [comment]
If it's autogenerated then it would probably be a fit for artifacts updating

**Comment by JavierSegoviaCordoba** [comment]
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
```

In Slack, I got a reply about how to update them: https://github.com/rjaros/kvision/blob/master/build.gradle.kts#L36

It doesn't look like something Renovate can handle easily.

The other way to update them is to wait until those transitive dependencies are updated from the real dependencies I am using.
