### ISSUE TITLE
nuget repositoryUrls from config should be added by renovate step

### ISSUE THREAD

**Issue by horihel** [renovatebot/renovate#13591]
### What would you like Renovate to be able to do?

please refer to the discussion in #13589 for the root problem.

Generally it looks like nuget repos configured via config.js:nuget:repositoryUrls are not handled at all, despite being documented in https://docs.renovatebot.com/nuget/#Alternate%20feeds

My wish would be that repos configured this way should be added the same way as the default repo is added - by calling "nuget add source" with the configured URL and authentication if configured.

### If you have any ideas on how this should be implemented, please tell us here.

one way to add this would probably be enhancing [getDefaultRegistries](https://github.com/renovatebot/renovate/blob/a6af88eb231a6f990b1f055c772228856425b5c5/lib/manager/nuget/util.ts#L25).

Currently this function is hardcoded to return only `https://api.nuget.org/v3/index.json`. Ideally, this would return the array configured in the configuration files and only fall back to the hardcoded default if that doesn't exist. This would mean configuring config.js:nuget.repositoryUrls would replace the default registry.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Big thumbs down to the idea of changing `getDefaultRegistries()`

**Comment by rarkins** [comment]
Here is the code currently: https://github.com/renovatebot/renovate/blob/a6af88eb231a6f990b1f055c772228856425b5c5/lib/manager/nuget/artifacts.ts#L36-L44

It reads "configure" repositories from files found in the repo, which is our recommended workaround/solution to avoid needing this requested feature.

**Comment by horihel** [comment]
could you then please consider changing https://docs.renovatebot.com/nuget/#Alternate%20feeds accordingly?

The documentation suggests that it is possible to provide alternate feeds via renovate config, but there's no code actually implementing it.

**Comment by rarkins** [comment]
You're welcome to submit a PR improving it. The contents are taken from https://github.com/renovatebot/renovate/blob/main/docs/usage/nuget.md

The documentation is still correct when no lock file is present. For a lock file to work, it requires a `nuget.config` file with registries listed within

**Comment by viceice** [comment]
I like the idea of parsing a repo `nuget.config`, as we do in other managers too.

So your idea of code change is nearly right. We should change this code here:
https://github.com/renovatebot/renovate/blob/2fd071cadf24e4c21a5255f25bc8b521f838d3ff/lib/manager/nuget/artifacts.ts#L36-L38

**Comment by rarkins** [comment]
@viceice I think they don't have a `nuget.config` in the repo, and would prefer not to have one. So, would it be "safe" for us to run the `dotnet nuget add source` command for every matching `hostRules` entry for every NuGet project in a repo, if a `nuget.config` does not exist? I think it's wrong to assume that every nuget host would be used for every nuget project, but 95-99% of the time that would be the case, or at least harmless to assume. The question is what to do about the remaining percent if:
- Using every nuget host causes problems, and
- No `nuget.config` file in the repo

**Comment by viceice** [comment]
This shouldn't harm, as nuget will also use a hunt strategy and I think you can set hostrules per `repisitories` global config option or a repo config to scope for the 5% ?

**Comment by horihel** [comment]
the only edge case I see is things like Azure Artifacts view, where the same package can appear in several views.
But if someone configures this in renovate.json or globally, is it safe to assume they are aware of the implications? The current documentation already says that the config will be merged.
(btw - it won't be merged if _any_ nuget.config in the repo contains a /clear/ statement. - but that's a different problem)

**Comment by horihel** [comment]
i'm having trouble getting a minimal reproduction going with all cases covered (private, with auth).

a sample project with public repos might be enough though, just doesn't cover the authentication path then. Bear with me, i'm trying to carve out the time to learn how to do it on github :)

**Comment by rarkins** [comment]
It doesn't necessarily need to be a fully working reproduction. We just need it to get to the "update artifacts" stage with necessary configuration to be able to run the additional CLI commands. So I think you can e.g. have no private packages but still add some dummy hostRules to simulate it

**Comment by horihel** [comment]
https://github.com/horihel/renovate-csproj
this should allow replicating my problem - but without the errors i get in prod. but you can still see in the debug log that constructing the nuget config for "nuget restore" currently only adds the default registry in my special case

**Comment by rarkins** [comment]
OK so to clarify, your request is that Renovate runs `nuget add source` for each URL in `registryUrls`, if they're not already in a `nuget.config`? No name, username or password required?

**Comment by horihel** [comment]
hmm... no, if hostrules define authentication, that should also be added to `nuget add source` - basically it sohuld handle registryUrls the same as a nuget.config.
i forgot the hostRules to simulate authentication... let me add those

**Comment by rarkins** [comment]
Please be sure that the reproduction and requirements are fully clear :)

**Comment by horihel** [comment]
Thank you - i'll try and clarify the readme

**Comment by horihel** [comment]
I didn't test it yet, but I think the newly introduced "defaultRegistryUrls" might solve my problem.

i'll try and get a second repro set up quickly

**Comment by horihel** [comment]
nevermind - defaultRegistryUrls is not used in [getDefaultFeed](https://github.com/renovatebot/renovate/blob/356fdcb3f5783a94a1b0e01c49587a7476118bf7/lib/datasource/nuget/v3.ts#L27), so it stays on the hardcoded default.

that means - at least when lockfiles are in play - defaultRegistryUrls will be treated the same way as registryUrls.
