### ISSUE TITLE
Include additional install artefacts for specific packages

### ISSUE THREAD

**Issue by AndrewLeedham** [renovatebot/renovate#13674]
### What would you like Renovate to be able to do?

I would like to be able to specify files for renovate to commit outside of the usual eg: `package.json`/`yarn.lock`. For example the `msw` library updates a generated `mswServiceWorker.js` file in your project with the new version number. This is done during `yarn install` so after merging the renovate PR, the next `yarn install` run by a user adds this new file.

### If you have any ideas on how this should be implemented, please tell us here.

Perhaps a new `renovate.json` option along the lines of `fileIncludes` which is an array of files, or globs for renovate to commit if they have changed?

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
If you are self-hosting, you can likely do this with `postUpgradeTasks` if you are self-hosting. You can add a dummy command (e.g. `pwd`) and then set `fileMatch` to be your custom file(s).

If using the app, we can think about a way to allow it (e.g. perhaps whitelisting `pwd`)

**Comment by AndrewLeedham** [comment]
@rarkins I am using the app, I did consider the `postUpgradeTasks` with a no-op command until I saw the self-host requirement.

**Comment by rarkins** [comment]
I should be able to whitelist that in the app, if you think the solution would work for you

**Comment by rarkins** [comment]
I've added `config.allowedPostUpgradeCommands = ['^pwd$'];` to the bot's config - can you give it a try?

**Comment by AndrewLeedham** [comment]
@rarkins I tried with the following option in my config, but It did not update the file. Are `fileFilters` relative to the root, or should they start with `./`?
```
"packageRules": [
    {
      "matchPackageNames": [
        "msw"
      ],
      "postUpgradeTasks": {
        "commands": [
          "pwd"
        ],
        "fileFilters": [
          "tools/storybook/static/mockServiceWorker.js"
        ]
      }
    }
  ]
```

**Comment by AndrewLeedham** [comment]
@rarkins have I got the syntax right in the above?

**Comment by rarkins** [comment]
I looked up the source code to check: https://github.com/renovatebot/renovate/blob/25e62d54a47ba9d08580a47358079c53eca5b1a3/lib/workers/branch/execute-post-upgrade-commands.ts#L100-L102

It indicates it's a relative path.

I suggest running it locally where you might be able to debug it (or at least add old fashioned `console.log` messages) to work out how close it's getting. It may not even get into that inner for loop

**Comment by AndrewLeedham** [comment]
Thanks @rarkins. I managed to recreate the issue locally, the path is correct. However, it would seem that the file is not being updated because it is done so via a `"postinstall"` script. So using `--alow-scripts --skip-installs=false` flags I got it to work.

Am I right in thinking the GitHub App version does not enable these flags/options and I would need to self-host? 

Also is there some way to know what global options are enabled for the GitHub App?

**Comment by rarkins** [comment]
It's mostly default settings. As a general rule, we don't opt into any of the options related to "trust" of repositories, such as allowing scripts, full installs, exposing env variables, etc.

**Comment by AndrewLeedham** [comment]
Thanks again @rarkins. I'll close this out.

For anyone coming across this issue, for `msw` updating its worker file per version you would need to do the following:
- Use the self-hosted runner (as the GitHub App does not run scripts, `msw` uses a `postinstall` script here)
  - pass `--allow-scripts` flag to enable said scripts.
  - pass `--skip-installs=false` so renovate does not use the `--package-lock-only` flag which also stops script execution.
- Add the following `postUpgradeTasks` option to your renovate config:
  - ```json
    "packageRules": [
      {
        "matchPackageNames": [
          "msw"
        ],
        "postUpgradeTasks": {
          "commands": [
            "pwd"
          ],
          "fileFilters": [
            "public/mockServiceWorker.js"
          ]
        }
      }
    ]
    ```
