### ISSUE TITLE
Support binarySource=install for cargo

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#13685]
### What would you like Renovate to be able to do?

Allow dynamic switching of cargo version at runtime

### If you have any ideas on how this should be implemented, please tell us here.

It seems like we don't dynamically install `cargo` today, so maybe there is nothing to be done: https://github.com/renovatebot/renovate/blob/ec723e3e076f46424fe5d4fd34ba12e5cce18625/lib/manager/cargo/artifacts.ts#L17-L29

If so then we should note this here for the record before closing.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
Maybe allow installing rust dynamically? So it can also use for runtime install mode?

**Comment by rarkins** [comment]
Yes, but I was thinking to do all the managers first and then languages in second phase

**Comment by viceice** [comment]
ok, so `cargo` is included in `rust` so nothing to do here.
