### ISSUE TITLE
Provide container image of renovate for aarch64 and armv7

### ISSUE THREAD

**Issue by volker-raschek** [renovatebot/renovate#13758]
### What would you like Renovate to be able to do?

Hi, 
I deployed renovate on a kubernetes multi-arch cluster. The cluster consists not only on x86_64 nodes, but also aarch64 and armv7 nodes. 

To get renovate running, I must shrink the deployment only on the x86_64 nodes, because currently is no container image for the other architectures available. This is quite stupid, since renovate is supposed to run on aarch64 nodes as well.

For this reason I would ask you to provide the appropriate container images for armv7 and aarch64. 
 

### If you have any ideas on how this should be implemented, please tell us here.

Push the renovate container image for each architecture in your repository and use container image manifests to group images. We use a drone plugin to group deployed container images via manifest files: https://plugins.drone.io/drone-plugins/drone-manifest/  Maybe there is also a plugin for your CI/CD

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Docker images are not built from this repository, and it's also much harder than you think.

**Comment by viceice** [comment]
Duplicate of #9229
