### ISSUE TITLE
Forking Renovate: replace `istanbul ignore if` with real test

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#13811]
### Describe the proposed change(s).

I'm rescuing this comment chain from getting lost in the PR. 😉 

---

From `@rarkins`, https://github.com/renovatebot/renovate/pull/13808#discussion_r791808373:

> I don't have time to figure out how to test this and need a test for forking-renovate ASAP

And response from `@viceice`

> Maybe `@zharinov` or `@JamieMagee` can help.

**Comment by rarkins** [comment]
Code was reverted

**Comment by viceice** [comment]
We should have a general issue to remove the coverage skip as much as possible.
