### ISSUE TITLE
Unable to force security updates from dependency dashboard

### ISSUE THREAD

**Issue by frbuceta** [renovatebot/renovate#13852]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

RenovateBot does not force open PR for other branches.

![Screenshot 2022-01-27 at 13 15 59](https://user-images.githubusercontent.com/13822438/151357151-e6796dc3-79c6-4479-99a1-c5f8c5b1f78f.png)

![Screenshot 2022-01-27 at 13 16 45](https://user-images.githubusercontent.com/13822438/151357236-cb26ad6a-7a7b-4c0f-b712-ec5d5a6d603a.png)

See https://github.com/loopbackio/loopback-next/issues/8150

### Relevant debug logs

It's too big for Github

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Some updates are impossible to remediate, so therefore a branch is not created. Please log into app.renovatebot.com and review the logs for any of the branches and paste the lines for that specific branch here.

**Comment by frbuceta** [comment]
[renovate.log](https://github.com/renovatebot/renovate/files/7950522/renovate.log)

**Comment by rarkins** [comment]
No, what I asked for is this:

> review the logs for any of the branches and paste the lines for that specific branch here

Instead you've dumped the entire log

**Comment by rarkins** [comment]
The answer is this line: `DEBUG: Only lockfileVersion 1 is supported`

We should ideally not show those branches at all if the lock file is not compatible with our transitive remediation. This is the bug, although I'm not sure how easy it is to fix

**Comment by frbuceta** [comment]
@rarkins It would be interesting to support version v2 if it is also affected

**Comment by rarkins** [comment]
PRs are always welcomed

**Comment by frbuceta** [comment]
> PRs are always welcomed

in which part of the project is the code... I'll take a look.

**Comment by wrslatz** [comment]
Cross-posting issue for lock file v2 support: https://github.com/renovatebot/renovate/issues/10371

**Comment by rarkins** [comment]
FYI any of these branches which can't be opened will usually be fixed with a lock file maintenance PR instead.
