### ISSUE TITLE
Add digest, lockFileMaintenance update types to group:allNonMajor preset

### ISSUE THREAD

**Issue by nejch** [renovatebot/renovate#13864]
### What would you like Renovate to be able to do?

Currently, `group:allNonMajor` will group minor/patch dependencies but send individual PRs for other non-major updates, even though they are even less likely to break functionality (digests, maintenance etc).

Would it make sense to add all these to the default non-major preset? Or would you prefer another one - not sure how to name it - `allNonMajorWithMaintenance` sounds weird :grin: 

### If you have any ideas on how this should be implemented, please tell us here.

Either change the existing one as a breaking change:
https://github.com/renovatebot/renovate/blob/91a3a971bb3edac8c33430af066dfa8e2c998bac/lib/config/presets/internal/group.ts#L23-L33

Or add a similar preset that covers more.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by nejch** [comment]
Ah, I've removed `pin` as that really doesn't make sense, true. It's mostly a one-time thing anyway.

Ok, I have not thought about both tag and digest updates creating conflicts, I assumed it would always just go with the tag if there is a new one available. But maybe I'm not getting the point completely, I'd probably need to see an example.

Our use case was more that we want to reduce noise in smaller tooling/service repos, but there are certain images used in CI that get frequent rebuilds so only their digests change, and they end up in individual PRs unlike minor/patch, so there's still quite a lot of noise despite the preset.

**Comment by viceice** [comment]
I use shedules and automerge for ci docker digest updates, so they are only updated at nighly cycles 😉

**Comment by rarkins** [comment]
I think that this might be possible if we added de-dupe logic where if a branch/group contains both a digest and non-digest update for the same currentValue then the digest one is removed.

**Comment by rarkins** [comment]
I think due to the problems that can occur, we don't want to include this by default in the preset
