### ISSUE TITLE
Not updating package

### ISSUE THREAD

**Issue by The-Code-Monkey** [renovatebot/renovate#13919]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Doesn't seem to be picking up a new version of my package
This is the package name that I updated about 10 hrs ago as of writing this
@aw-web-design/theme

And my repo components doesn't get updated with a pr.

### Relevant debug logs

I have looked at the logs and it doesn't pick up in the updates array for the package.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Issues lacking in details like this will be deleted. Please start a discussion instead, with improved details.
