### ISSUE TITLE
Set assignee via regex capture

### ISSUE THREAD

**Issue by bachp** [renovatebot/renovate#13973]
### What would you like Renovate to be able to do?

I have a file with multiple version fields defined, similar to the example in https://docs.renovatebot.com/modules/manager/regex/#advanced-capture.

I would like to assign the merge requests generated for each version filed to different people. But currently I only found a way to do this for the whole file.

### If you have any ideas on how this should be implemented, please tell us here.

I think it should be possible to extend the regex manager to set the assignee field from a regex capture

```
 # renovate: datasource=github-tags depName=nodejs/node versioning=node assignee=XYZ
ENV NODE_VERSION=10.19.0
```

So that one could use the following regex to extract the assignee.

```
"datasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?(assignee=(?<assignee>.*?)\\sENV .*?_VERSION=(?<currentValue>.*)\\s"
```

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
If this are different deps, then you should be able to use package rules with file and depName matchers

**Comment by HonkingGoose** [comment]
I see that @rarkins and @viceice have given this issue a thumbs-down.

What do you maintainers want to do with this issue, close it `won't do` or keep it around?

**Comment by rarkins** [comment]
Sorry but yes, we don't think this feature's benefit would outweigh the complexity it would add. Managers do not today return `assignees` and we don't wish to add that.
