### ISSUE TITLE
Terraform modules gitTagsRefMatchRegex does not match Gitlab.com-s ssh format

### ISSUE THREAD

**Issue by da3mon-01** [renovatebot/renovate#13974]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

31.66.1

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

**Story:**
I have been trying to implement renovate with Terraform modules hosted on gitlab.com, however Renovate will not skip updating the modules with the `invalid-value` error noted in the debug logs.

I was able to track down the error to the following:
- Using Gitlab ssh urls, like `git@gitlab.com:schafferg/tf-module.git`,  will work with Terraform fine, but Renovate will throw an error.
- Gitlab.com ssh urls do not match with [gitTagsRefMatchRegex in modules.ts](https://github.com/renovatebot/renovate/blob/31.66.1/lib/manager/terraform/modules.ts#L19)
- Gitlab https urls, like `https://gitlab.com/schafferg/tf-module.git`, will match just fine, and RenovateBot will update the module
- Terraform does support SCP-like addressing: https://www.terraform.io/language/modules/sources#scp-like-address-syntax

**How to test / reproduce:**

Regex demo: https://regex101.com/r/rkfVRi/1
I have prepared a small environment for reproduction:
Module source: https://gitlab.com/schafferg/tf-module
Sourcing  code: https://gitlab.com/schafferg/renovate-tf-demo

**Workaround**

Like I said, https urls still work, but if you want to still use ssh authentication you have to use something like:
```
git config --global url."git@gitlab.com:schafferg".insteadOf https://gitlab.com/schafferg
```

### Relevant debug logs

<details><summary>Logs</summary>

Please note, the log has been edited and cut for brevity and securiy.

```
{
        "packageFile": "/main.tf",
        "deps": [
          {
            "depType": "module",
            "depName": "git::git@gitlab.com:schafferg/tf-module.git?ref=0.0.1",
            "datasource": "terraform-module",
            "depIndex": 1,
            "updates": [],
            "warnings": [],
            "versioning": "hashicorp",
            "skipReason": "invalid-value"
          }
        ]
      }

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment]
This is currently simply not supported and is not but , so please reopen as feature request. Next time please open a discussion first to clarify current and expected behavior.
