### ISSUE TITLE
maven: parent project in pom is not updated

### ISSUE THREAD

**Issue by ezloj** [renovatebot/renovate#14063]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

30.1.0

### Please select which platform you are using if self-hosting.

Bitbucket Cloud (bitbucket.org)

### If you're self-hosting Renovate, tell us what version of the platform you run.

5.16.5

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Given a following pom.xml:

`\<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.fiction</groupId>
	<artifactId>awesome_artie</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>awesome</name>
	<description>Generates awesomeness</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.11.RELEASE</version>
	</parent>
</project>`

I expect the `2.1.11.RELEASE` version to be updated (2.6.3 is the latest at the time of writing this). It doesn't update, however.

See https://github.com/renovatebot/renovate/discussions/14001 for original discussion

To reproduce, run renovate on this public repository:
https://github.com/bitmc/spring-boot-starter-parent

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Please reduce to a standalone *minimal* reproduction
