### ISSUE TITLE
Yamllint triggered by comments after pinned action versions

### ISSUE THREAD

**Issue by soenkeliebau** [renovatebot/renovate#14093]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We just enabled Renovate for all our repositories and it created the inital pull requests to lock github action dependencies down to a specific hash.

We are also running yamllint on all our PRs, and the suggested changes by Renovate trigger the [comments](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments) lint, more specifically the default setting for `min-spaces-from-content` is 2, but Renovate only leaves one whitespace (see attached image or [this pr](https://github.com/stackabletech/regorule-operator/pull/201/files) for result).

This is an easy fix be changing the mentioned config, so not a large issue, I just wanted to briefly mention it, since the default value probably is some sort of best practice that it might be worthwhile observing.

I am happy to look at the code and create a PR if this is something people are interested in.

![image](https://user-images.githubusercontent.com/1070361/152990896-ea7c3c96-0926-48be-aaab-ccc522eaf3b3.png)

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Thanks for alerting us to this. On a related note, I was thinking whether we can drop the `renovate:` prefix of the comment too, so that it's a "generic" way to indicate tag and could e.g. be supported by other tools too. Even though we'd no longer be explicitly annotating with `renovate:` I think that a `#  tag=v2.4.0` after an actions hash is pretty unequivocal about what it's for.

A PR would be welcome to change the default spacing at the very least!

**Comment by soenkeliebau** [comment]
Since yamllint and prettier have different viewpoints on what well-formed yaml should look like a fix for this issue might break more things than it fixes.

I have opened https://github.com/adrienverge/yamllint/issues/443 to see if there is a specific reason for 2 being the yamllint default value here.
