### ISSUE TITLE
Allow proxy configs

### ISSUE THREAD

**Issue by jperkelens** [renovatebot/renovate#1411]
Currently it is impossible to run renovate behind a proxy. The tool should allow the user to configure proxy settings in one of two ways:

 1. pass proxy settings in via config (CLI or otherwise)
 1. read proxy environment variables with and apply them to requests

Personally, I prefer the latter. Depending if there's an appetite to add this I'm happy to open a PR that conforms to whichever method you prefer.

**Comment by rarkins** [comment]
The way our config works, every config option can be configured by config file, env or cli parameters, so you kind of get them all for free. 

Where would the proxy sit between? Eg bot and repositories, bot and registries, or bot and everything?

**Comment by jperkelens** [comment]
I would suggest bot and everything since it's impossible to guess what about a user's project sits inside the network vs outside the network.

**Comment by rarkins** [comment]
We use [got](github.com/sindresorhus/got) (npmjs, docker hub), [gh-got](github.com/sindresorhus/gh-got) for GitHub, `gl-got` for GitLab, and something else altogether for VSTS and BitBucket. I haven't looked up proxyWhich platform(s) would you be using on? Seems like `got` has a quick solution for the proxy: https://github.com/sindresorhus/got/blob/a49dcafd4268784cf6d1529a3c5a40cea9df0582/readme.md#proxies

**Comment by jperkelens** [comment]
Personally, my needs only require a proxy for npmjs, and docker hub, and I already have a forked version of renovate that's working for me. But to be a useful feature, I believe that the proxy config should be universal and allow you to configure a proxy url for both HTTP and HTTPS and a list of exceptions to bypass the proxy.

**Comment by rarkins** [comment]
I think a proxy setting that applies to "everything" would be much quicker to implement and test than one that's "highly configurable" and with different settings per lookup type. Due to the common use of `got`, it sounds like supplying some simple connection options should be all that's required to work for npmjs, docker, github and gitlab.

**Comment by jperkelens** [comment]
I agree. To be clear, i meant that the settings (lets call them `httpProxy`, `httpsProxy`, and `noProxy`) should apply to everything and not be configurable per registry or repo source.

**Comment by rarkins** [comment]
So in your use case, your proxy would still bounce connections “back” to the internal hosts that you don’t *need* them for? Ie such a solution would help you get off your fork?

**Comment by jperkelens** [comment]
Yes that's correct.

**Comment by rarkins** [comment]
Proposal: allow a configuration object for proxy that is passed to `got`

**Comment by jperkelens** [comment]
Yeah that makes sense to me.

**Comment by rarkins** [comment]
Related to #1500

**Comment by spk83** [comment]
@rarkins is there any update to this issue? Would be happy to help with some guidance on changes required for this issue.

**Comment by rarkins** [comment]
What is your exact use case?
