### ISSUE TITLE
Use GitHub repo for conan datasource

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#14170]
### What would you like Renovate to be able to do?

Use GitHub conan repo for datasource fetching.

### If you have any ideas on how this should be implemented, please tell us here.

See advice:
- https://github.com/renovatebot/renovate/pull/12009#issuecomment-1036014602
- https://github.com/renovatebot/renovate/pull/12009#issuecomment-1036025522

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Here's one example of where we use git in a datasource: https://github.com/renovatebot/renovate/blob/0786775005ae1382d4789f7690faba63af17eaa5/lib/datasource/crate/index.ts#L211-L245

I'm pretty sure though that `--depth=1` (i.e. "shallow" clone) is not efficient for long-living fetching and we'd be better with blobless clone.

**Comment by rarkins** [comment]
The conan datasource seems to return a pretty simple result currently: https://github.com/renovatebot/renovate/blob/0786775005ae1382d4789f7690faba63af17eaa5/lib/datasource/conan/index.spec.ts#L89-L115

Using `poco` as an example, here's the `config.yaml`: https://github.com/conan-io/conan-center-index/blob/master/recipes/poco/config.yml

And a more detailed `all/conandata.yaml`: https://github.com/conan-io/conan-center-index/blob/master/recipes/poco/all/conandata.yml

**Comment by mhetzel** [comment]
Does it matter that renovate is using the v2 api and [conan issue](https://github.com/conan-io/conan/issues/10298) is on the v1 api? @memsharded

**Comment by memsharded** [comment]
> Does it matter that renovate is using the v2 api and https://github.com/conan-io/conan/issues/10298 is on the v1 api? @memsharded

No, it is basically the same backend for that endpoint, that one didn't change really between v1 and v2 apis.

**Comment by HonkingGoose** [comment]
This issue is closed with PR #14176 and released as Renovate version `31.81.0`.
