### ISSUE TITLE
looping upgrade and downgrade of `ansi-regex` from competing `ansi-regex` and `node-fetch` vulnerability fixes

### ISSUE THREAD

**Issue by travi** [renovatebot/renovate#14196]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

I have [one project](https://github.com/travi-org/matt.travi.org-components/) where I've seen competing vulnerability fixes for `node-fetch` and `ansi-regex`. 

for example, the project will receive a renovate [PR to fix an `ansi-regex` vulnerability](https://github.com/travi-org/matt.travi.org-components/pull/1432/files), which updates `ansi-regex` in the lockfile from `6.0.0` to `6.0.1`. Interestingly, the `resolved` and `integrity` properties get removed from that lockfile entry as part of the upgrade.  then, in a [PR reported to fix a `node-fetch` vulnerability](https://github.com/travi-org/matt.travi.org-components/pull/1427/files), `ansi-regex` is downgraded from `6.0.1` back to `6.0.1`. note that (at least in its final form) there is no mention of `node-fetch` in the changes involved in the PR. 

once both PRs have been auto-merged, the process starts over. this has been repeating in a loop since Feb 9th, as you can see from the [commit history](https://github.com/travi-org/matt.travi.org-components/commits/master).

### Relevant debug logs

<details><summary>Logs</summary>

```
I'm open to looking through the logs for more details, but am unsure what details would be relevant in this case and which side of the pairs of PRs would be most informative. If you could provide some guidance about what would be useful, I'm happy to dig.
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
I believe that this type of problem will be resolved by https://github.com/renovatebot/renovate/pull/14173, which I just put live in the app today. Sorry for the noise you've received before that.

BTW I'm not 100% sure what will happen to PRs in existence prior to this fix - I couldn't work out an easy way to remove them so I think they'll remain open/orphaned for now.

Unfortunately npm no longer validates `package-lock.json` files and repairs/fills them in like npm@6 used to. Previously we could change version and delete resolved and integrity fields and npm would happily fill it all in for us (as well as any dependencies change, plus flow-on effects). With the new npm, it's only reliable if we make a change to `package.json`.

**Comment by travi** [comment]
ah, ok. i missed the previous report. i appreciate the explanation. do you think there is an opportunity to encourage bringing that behavior back to npm?

i'll close this for now and just keep an eye on things, assuming #14173 resolves the issue. thanks!

**Comment by rarkins** [comment]
I had hoped the behaviour would come back (essentially it can leave you with invalid lock files too, which npm ci doesn't complain about) but I haven't raised it yet because my use case is pretty edgy
