### ISSUE TITLE
docs: show env and cli names for config options

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#14190]
### Describe the proposed change(s).

`redisUrl` example: https://github.com/renovatebot/renovate/blob/e92ef1ac455b748965eee7efe4028649763b7dce/lib/config/options/index.ts#L279-L285

https://docs.renovatebot.com/self-hosted-configuration/#redisurl

Currently looks like:

![image](https://user-images.githubusercontent.com/6311784/153705273-4ce795b6-7338-470b-b4ee-95dedd35119b.png)

Unless `env` or `cli` are `false` (example: `force`) then we should add rows to the above table to show the equivalent in env (e.g. `RENOVATE_REDIS_URL`) and cli (`e.g. `--redis-url`).

These docs are currently generated in `tools/generate-docs.ts`

**Comment by StinkyLord** [comment]
@rarkins  now that i read and seen the classes (index.ts and generate-docs.ts) i would like to ask you to add the Expected result to the ticket for a single flag, 
you said "add rows" to the table, but im not sure what to add or how to do it can you please give me an example of how it should look like?

**Comment by rarkins** [comment]
If you run `yarn build:docs` then you can find the generated docs in tmp/docs

Using this as an example from `self-hosted-configuration.md`, I'd expect this example to then look like:

Raw:

```md
## allowPlugins
Configure this to true if repositories are allowed to run install plugins.

| Name       | Value   |
| ---------- | ------- |
| globalOnly | true    |
| type       | boolean |
| default    | `false` |
| env        | `RENOVATE_ALLOW_PLUGINS` |
| cli        | `--allow-plugins` |
```

Converted:

## allowPlugins
Configure this to true if repositories are allowed to run install plugins.

| Name       | Value   |
| ---------- | ------- |
| globalOnly | true    |
| type       | boolean |
| default    | `false` |
| env        | `RENOVATE_ALLOW_PLUGINS` |
| cli        | `--allow-plugins` |

**Comment by StinkyLord** [comment]
Thank you, i'm on it!

**Comment by PhilipAbed** [comment]
@rarkins should i do this only for the self hosted? or for both   
 `configuration-options.md`;
  `self-hosted-configuration.md`;

**Comment by rarkins** [comment]
I think let's do both. Not all options support cli config so let's see how it looks

**Comment by PhilipAbed** [comment]
i said i think its only for self hosted because i see the implementation for cli params are only for self hosted
![image](https://user-images.githubusercontent.com/42116482/154290549-0c58226f-8409-4afe-9b60-97fe7088b26f.png)

see code, 
in that case i will have to remove that "if" but i dont know the consequences :D and thats why im asking

**Comment by rarkins** [comment]
I didn't realise that we already had it in self hosted actually

**Comment by astellingwerf** [comment]
Well, we don't, as "env" and "cli" are both in the array of `ignoredKeys` in `tools/docs/config.ts`'s `genTable` function.

**Comment by PhilipAbed** [comment]
@rarkins Please change the assignee to this account :D,

I do see half the implementation there, but it was in Ignored, see what i did in the PR
