### ISSUE TITLE
Support Docker credential helpers

### ISSUE THREAD

**Issue by remal** [renovatebot/renovate#14207]
### What would you like Renovate to be able to do?

We run out GitLab CI pipelines in [EKS](https://aws.amazon.com/eks/) environment. To authenticate in [ECR](https://aws.amazon.com/ecr/) we use [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper). This [Docker credential helper](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers) works absolutely transparently without any additional configuration. We don't have to provide the helper with any secrets and so on. Just to configure Docker to use the helper for our ECR instance.

Could you please integrate Renovate with Docker credential helpers of most known clouds like [AWS](https://github.com/awslabs/amazon-ecr-credential-helper), [GCP](https://github.com/GoogleCloudPlatform/docker-credential-gcr), [Azure](https://github.com/Azure/acr-docker-credential-helper)?

### If you have any ideas on how this should be implemented, please tell us here.

1. Add binaries of different credential helpers to Renovate Docker image.
    * There is an issue here with [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper). The problem is that Amazon stopped publishing [Linux releases](https://github.com/awslabs/amazon-ecr-credential-helper#debian-buster-and-future-versions) (see awslabs/amazon-ecr-credential-helper#275). And it means that the binary should be taken directly from the repository's releases or built from the sources.
2. Use an appropriate helper if a registry URL matches a specific regex.
3. Allow configuring credential helper for registries with custom URLs in environments like [AWS Outposts](https://aws.amazon.com/outposts/).

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
We would prefer solutions to authentication which don't require running binaries, because otherwise they cannot be configured in hosted scenarios like the app.

It would be OK for us to consider supporting these if it's a fallback/fallthrough solution if no credentials are available in config.

To start with, can you describe why the existing ECR credentials support we have isn't suitable for you?

**Comment by remal** [comment]
We have a lot of repositories and don't set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` for our CI jobs. So, we just use amazon-ecr-credential-helper that authenticate us in ECR automatically.

We have [AWS MFA](https://aws.amazon.com/iam/features/mfa/) enabled for all AWS accounts and it will be really hard to get some service accounts that will allow using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` without MFA. Our security team just doesn't want to create service account for this purpose.

**Comment by rarkins** [comment]
I thought that the ECR library we use would already take care of this when we call this function: https://github.com/renovatebot/renovate/blob/f2bffdad3ae1d4126aa2e20df949e414d1665031/lib/datasource/docker/index.ts#L207

**Comment by remal** [comment]
@rarkins, you're right - Renovate correctly works with ECR repositories in EKS environment. Closing the issue.
