### ISSUE TITLE
`dep.depName?.trim is not a function`

### ISSUE THREAD

**Issue by dominik-bln** [renovatebot/renovate#14338]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v31.81.2

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.7.3

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When trying to update renovate from `v31.81.0` we start to see logs `dep.depName?.trim is not a function` for three of our repos that fail the renovate run with a non-zero exit code.

Potentially related to:

https://github.com/renovatebot/renovate/pull/14037

### Relevant debug logs

<details><summary>Logs</summary>

```json
{"name":"renovate","hostname":"runner-75ezaujp-project-705-concurrent-0b66sg","pid":16,"level":20,"logContext":"pIEw3R1pxQaZN_itWjmOj","repository":"alpha/msgraph","msg":"Dependency $$REPLACED$$:7070/alpha/msgraph has unsupported value latest","time":"2022-02-21T11:58:12.100Z","v":0}
{"name":"renovate","hostname":"runner-75ezaujp-project-705-concurrent-0b66sg","pid":16,"level":50,"logContext":"pIEw3R1pxQaZN_itWjmOj","repository":"alpha/msgraph","err":{"message":"dep.depName?.trim is not a function","stack":"TypeError: dep.depName?.trim is not a function\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:19:39)\n    at /usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:59:7\n    at /usr/src/app/node_modules/p-all/index.js:4:67\n    at /usr/src/app/node_modules/p-map/index.js:57:28"},"msg":"Repository has unknown error","time":"2022-02-21T11:58:12.118Z","v":0}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by dominik-bln** [comment]
I've just tried changing a dependency in a `values.yaml` for Helm from `latest` to a version like `v1.0.2`, but that just gets rid of the first log message and still fails with the error. Now it seems pretty hard to narrow down which dependency is causing the issue from the log messages 🤔

**Comment by rarkins** [comment]
Relevant code: https://github.com/renovatebot/renovate/blob/15c393f79115c0a5fe6429396c5a9e51127ffc67/lib/workers/repository/process/fetch.ts#L13-L21

I'm guessing `depName` is not a string

**Comment by rarkins** [comment]
We should skip any dep where `depName` is not a string. Ideally even earlier in the flow though, before lookups

**Comment by dominik-bln** [comment]
Yup, I added a log statement now and am getting `{ '[object Object]': null }` on:

```json
{
  depName: { '[object Object]': null },
  skipReason: 'local-chart',
  depIndex: 0,
  updates: []
}
```

**Comment by dominik-bln** [comment]
The three failing repos are using `helmfile` and contain a local Helm chart, so my guess would be that the following line is where the problem is coming from:

https://github.com/renovatebot/renovate/blob/a859c7f279863028414377f5660e7bff15b94bcd/lib/manager/helmfile/extract.ts#L39

**Comment by rarkins** [comment]
Thanks. I'll add a fix to the exception but the root cause appears to be in `helmfile`, so if you can submit a separate bug with reproduction for `helmfile` extract functionality then it would be great

**Comment by dominik-bln** [comment]
I'll try to come up with something.
