### ISSUE TITLE
Support bumpVersion for nuget package manger

### ISSUE THREAD

**Issue by jobubo** [renovatebot/renovate#14348]
### What would you like Renovate to be able to do?

Hi, first i would like to thank you for renovate. It is awesome! I really like how configurable it is.

Quoting from the detailed [docs](https://docs.renovatebot.com/configuration-options/#bumpversion):

> Currently this setting supports helmv3, npm, maven and sbt only, so raise a feature request if you have a use for it with other package managers.

I would love the [bumpversion](https://docs.renovatebot.com/configuration-options/#bumpversion) feature for Nuget Package manager. So, here's the feature request you asked for :-)

### If you have any ideas on how this should be implemented, please tell us here.

Implement it like you did for helm, npm, ...

### Is this a feature you are interested in implementing yourself?

No

**Comment by CleanCodeDeveloper** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;net5.0;net6.0;</TargetFrameworks>
    <Version>1.1.4</Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.21" />
  </ItemGroup>

</Project>
```

Increment `<Version>` field from 1.1.4 to 1.1.5 when updating a dependency.

**Comment by jobubo** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;net5.0;net6.0;</TargetFrameworks>
    <Version>1.1.4</Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.21" />
  </ItemGroup>

</Project>
```

Increment `<Version>` field from 1.1.4 to 1.1.5 when updating a dependency.

**Comment by rarkins** [comment]
Thanks, please create a repo with this as well as a dependency which needs updating

**Comment by jobubo** [comment]
> Thanks, please create a repo with this as well as a dependency which needs updating

Sure, there you go: https://github.com/jobubo/Support-bumpVersion-for-nuget-package-manger-14348

**Comment by rarkins** [comment]
Thanks, reproduction forked to https://github.com/renovate-reproductions/14348

**Comment by bjuraga** [comment]
@jobubo This is now implemented, hope it works out ok for your scenarios.

**Comment by jobubo** [comment]
> @jobubo This is now implemented, hope it works out ok for your scenarios.

Thank you very much :-)
