### ISSUE TITLE
Gradle-Wrapper not complete for projects in sub-directories

### ISSUE THREAD

**Issue by TobiX** [renovatebot/renovate#14371]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When a Gradle project is in a sub-directory of a repository, the "basic" update of the `gradle-wrapper.properties` works, but related changes (SHA256 sum, script updates) are not applied. This happens in a self-hosted Renovate installation, but I build a reproducer project here: https://github.com/TobiX/test-gradle-renovate

This might be related to #13081 and #5377

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: PR rebase requested=true(branch="renovate/gradle-7.x")
DEBUG: Checking if PR has been edited(branch="renovate/gradle-7.x")
DEBUG: Branch has not been modified(branch="renovate/gradle-7.x")
{
  "branchName": "renovate/gradle-7.x"
}
DEBUG: Found existing branch PR(branch="renovate/gradle-7.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/gradle-7.x")
DEBUG: No schedule defined(branch="renovate/gradle-7.x")
DEBUG: Manual rebase requested via Dependency Dashboard(branch="renovate/gradle-7.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/gradle-7.x")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/gradle-7.x")
DEBUG: Starting search at index 168(packageFile="demo/gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: Found match at index 168(packageFile="demo/gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: Contents updated(packageFile="demo/gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-7.x")
{
  "depName": "gradle"
}
DEBUG: gradle-wrapper.updateArtifacts()(branch="renovate/gradle-7.x")
[...]
INFO: No gradlew found - skipping Artifacts update(branch="renovate/gradle-7.x")
DEBUG: Updated 1 package files(branch="renovate/gradle-7.x")
DEBUG: No updated lock files in branch(branch="renovate/gradle-7.x")
DEBUG: isBranchConflicted(main, renovate/gradle-7.x)(branch="renovate/gradle-7.x")
DEBUG: 1 file(s) to commit(branch="renovate/gradle-7.x")
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by PhilipAbed** [comment]
Hi @TobiX 
do you mean that 
![image](https://user-images.githubusercontent.com/42116482/159294850-c25c822e-ae65-4abf-949e-fef43c81ec24.png)

arent updated? 
but the expected results is for them to be updated?

**Comment by TobiX** [comment]
Yes, the one thing is the SHA256 sum and the other thing is the wrapper JAR and the scripts, there should be plenty examples on GitHub, for example:
 - https://github.com/mahoganykilo/android_sample_kotlin_dsl/pull/5/files
 - https://github.com/simlar/simlar-android/pull/687/files

(Related: Finding Renovate PRs where developers actually USE the SHA256SUM to increase the security of the wrapper was the hard part here :disappointed:)

I understand that Renovate actually runs `gradle wrapper` in the repository to update "related" resources (see https://docs.gradle.org/current/userguide/gradle_wrapper.html)
