### ISSUE TITLE
Cake manager should set `depType` to `cake`

### ISSUE THREAD

**Issue by gitfool** [renovatebot/renovate#14385]
### What would you like Renovate to be able to do?

The Cake manager should set `depType` to `cake` to be able to differentiate its dependencies. It's currently not assigned.

### If you have any ideas on how this should be implemented, please tell us here.

I tried setting it via a package rule to no avail:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [ "config:base" ],
  "commitMessageAction": "Bump",
  "labels": [ "dependencies" ],
  "packageRules": [
    {
      "matchManagers": [ "cake" ],
      "depType": "cake"
    }
  ]
}
```
So it probably just needs to be set explicitly in [lib/manager/cake/index.ts](https://github.com/renovatebot/renovate/blob/0cb20ff19986af3e6d97738093e3dbcee85843c5/lib/manager/cake/index.ts#L39-L43).

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
This doesn't seem right. Manager is "cake". depType is used to distinguish between e.g. dev and test dependencies

**Comment by gitfool** [comment]
Cake is effectively a dev dependency since it's used for build orchestration.

There isn't much documentation on `devType`, but from what I've found while perusing the source, it's used to differentiate all sorts of things, not just dev and test dependencies; e.g. Docker `stage` vs `final` layers.

**Comment by rarkins** [comment]
depType is only needed to differentiate between different dependency types within one manager. If 100% of dependencies are the same type, then it's not needed

**Comment by gitfool** [comment]
I see. I'm also looking at the information in the update table in the pull request created by renovate, when grouping them into a single pull request. It would be nice for the `Type` column, which seems to come from `depType` to be `cake` instead of blank, because the cake manager is using the nuget datasource, and this would differentiate updates to cake scripts at a glance.

**Comment by rarkins** [comment]
You can already customise the columns in a PR body using config. Eg adding a manager column. Adding a redundant/unnecessary depType to cake for cosmetic reasons isn't something I'd like to do

**Comment by gitfool** [comment]
Fair enough.

**Comment by gitfool** [comment]
@rarkins I was just looking at adding a manager column as you suggested, but according to docs this is not in the [template fields](https://docs.renovatebot.com/templates/#template-fields).

**Comment by rarkins** [comment]
https://github.com/renovatebot/renovate/pull/14624
