### ISSUE TITLE
Replacements are filtered out if the version is exactly the same

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#14386]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Seen in the replacement for `@emotion/core` to `@emotion/react`. The replacement as defined in https://github.com/renovatebot/renovate/pull/14367 doesn't work when the old version and the replacement version are identical.

The replacement is added here:

https://github.com/renovatebot/renovate/blob/368903ab814f5b19117eaab6c2cb33382be6cad6/lib/workers/repository/process/lookup/index.ts#L150-L160

And then filtered out here:

https://github.com/renovatebot/renovate/blob/368903ab814f5b19117eaab6c2cb33382be6cad6/lib/workers/repository/process/lookup/index.ts#L360-L367

We need to add another condition for `update.updateType === 'replacement'`

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by setchy** [comment]
https://github.com/renovatebot/renovate/pull/20629 pending https://github.com/renovatebot/renovate/pull/20627 before it can be reviewed / merged
