### ISSUE TITLE
`gitlabci-include` manager doesn't work with wildcards

### ISSUE THREAD

**Issue by wolfgangwalther** [renovatebot/renovate#14397]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.89.5

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.7.3

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

With a `.gitlab-ci.yml` file like this:

```yaml
include: ".gitlab/jobs/*.yaml"
```

and some valid job files in that directory (CI is working), I get the following in the log:

```
DEBUG: Empty or non existent gitlabci file (repository=[...])
       "file": ".gitlab/jobs/*.yaml"
```

The wildcard is taken literally instead of being expanded to the job files.

[Wildcards are supported](https://docs.gitlab.com/ee/ci/yaml/includes.html#use-includelocal-with-wildcard-file-paths) by GitLab:

> You can use wildcard paths (`*` and `**`) with `include:local`. 

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by fancybear-dev** [comment]
test

**Comment by viceice** [comment]
This isn't a bug. This isn't simply supported by renovate.

**Comment by wolfgangwalther** [comment]
If you didn't consider this a bug, wouldn't this be a feature request then? Am I missing something fundamental why this wouldn't be possible to support?

**Comment by wolfgangwalther** [comment]
Ah, I think I understand now. `gitlabci-include` is about something different - basically everything **except** `local`.
