### ISSUE TITLE
Broken yarn lockfile update

### ISSUE THREAD

**Issue by irudoy** [renovatebot/renovate#14463]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.96.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.8.0

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

After upgrading Renovate from v31.24.0 to v31.96.0 it stopped updating yarn (berry) lockfile with `Error: spawn /bin/sh ENOENT` and `Artifact update problem`.

### Relevant debug logs

<details><summary>Logs</summary>

```
{"name":"renovate","hostname":"renovate-manual-1646113985-fdtqb","pid":9,"level":20,"logContext":"gtqehNZGg-0s9GRy8nWYa","repository":"xxx/xxx","branch":"renovate/dotenv-16.x","msg":"Generating yarn.lock for .","time":"2022-03-01T06:03:04.071Z","v":0}
{"name":"renovate","hostname":"renovate-manual-1646113985-fdtqb","pid":9,"level":20,"logContext":"gtqehNZGg-0s9GRy8nWYa","repository":"xxx/xxx","branch":"renovate/dotenv-16.x","msg":"Spawning yarn install to create /tmp/renovate/repos/gitlab/xxx/xxx/yarn.lock","time":"2022-03-01T06:03:04.072Z","v":0}
{"name":"renovate","hostname":"renovate-manual-1646113985-fdtqb","pid":9,"level":20,"logContext":"gtqehNZGg-0s9GRy8nWYa","repository":"xxx/xxx","branch":"renovate/dotenv-16.x","msg":"Enabling global cache as zero-install is not detected","time":"2022-03-01T06:03:04.072Z","v":0}
{"name":"renovate","hostname":"renovate-manual-1646113985-fdtqb","pid":9,"level":20,"logContext":"gtqehNZGg-0s9GRy8nWYa","repository":"xxx/xxx","branch":"renovate/dotenv-16.x","msg":"Using node constraint \">=16\" from package.json","time":"2022-03-01T06:03:04.073Z","v":0}
{"name":"renovate","hostname":"renovate-manual-1646113985-fdtqb","pid":9,"level":20,"logContext":"gtqehNZGg-0s9GRy8nWYa","repository":"xxx/xxx","branch":"renovate/dotenv-16.x","command":"yarn install --mode=update-lockfile","msg":"Executing command","time":"2022-03-01T06:03:04.073Z","v":0}
{"name":"renovate","hostname":"renovate-manual-1646113985-fdtqb","pid":9,"level":20,"logContext":"gtqehNZGg-0s9GRy8nWYa","repository":"xxx/xxx","branch":"renovate/dotenv-16.x","err":{"errno":-2,"code":"ENOENT","syscall":"spawn /bin/sh","path":"/bin/sh","spawnargs":["-c","yarn install --mode=update-lockfile"],"cmd":"yarn install --mode=update-lockfile","stdout":"","stderr":"","message":"spawn /bin/sh ENOENT","stack":"Error: spawn /bin/sh ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)\n    at onErrorNT (internal/child_process.js:469:16)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"msg":"rawExec err","time":"2022-03-01T06:03:04.096Z","v":0}
{"name":"renovate","hostname":"renovate-manual-1646113985-fdtqb","pid":9,"level":20,"logContext":"gtqehNZGg-0s9GRy8nWYa","repository":"xxx/xxx","branch":"renovate/dotenv-16.x","err":{"errno":-2,"code":"ENOENT","syscall":"spawn /bin/sh","path":"/bin/sh","spawnargs":["-c","yarn install --mode=update-lockfile"],"cmd":"yarn install --mode=update-lockfile","stdout":"","stderr":"","message":"spawn /bin/sh ENOENT","stack":"Error: spawn /bin/sh ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)\n    at onErrorNT (internal/child_process.js:469:16)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"type":"yarn","msg":"lock file error","time":"2022-03-01T06:03:04.096Z","v":0}
{"name":"renovate","hostname":"renovate-manual-1646113985-fdtqb","pid":9,"level":20,"logContext":"gtqehNZGg-0s9GRy8nWYa","repository":"xxx/xxx","branch":"renovate/dotenv-16.x","msg":"No updated lock files in branch","time":"2022-03-01T06:03:04.097Z","v":0}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by steffen-4s1** [comment]
Same problems seems to be with PNPM lockfile.

**Comment by viceice** [comment]
How are you running renovate (exactly)?

**Comment by steffen-4s1** [comment]
In my setup a crontab job starts renovate via a script file which contains the following command:

```bash
#!/bin/bash

docker run \
  --rm \
  -v ${PWD}/config.js:/usr/src/app/config.js \
  -e RENOVATE_ENDPOINT="https://gitlab.com/api/v4/" \
  -e RENOVATE_PLATFORM="gitlab" \
  -e RENOVATE_AUTODISCOVER="true" \
  -e RENOVATE_AUTODISCOVER_FILTER="4s1/**" \
  -e RENOVATE_TOKEN="*******************" \
  -e GITHUB_COM_TOKEN="*******************" \
  -e LOG_LEVEL=info \
  renovate/renovate:31
```

**Comment by cauterize** [comment]
Same Problem. Renovate is unable to edit yarn.lock. Had to downgrade Renovate from `31.96.0` to `31.89.8` now it works again...

**Comment by rarkins** [comment]
I've created #14464 to revert what is the most likely culprit. Would be helpful if anyone is able to confirm that it's broken on `31.94.1` exactly

**Comment by steffen-4s1** [comment]
I tried and can confirm that 31.94.1 is broken.

```
Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by rarkins** [comment]
Can you test `31.94.0`?

**Comment by viceice** [comment]
@rarkins maybe a coincidence with latest buildpack changes?

Can somebody verify that yarn is globally available in the full image?

**Comment by rarkins** [comment]
Yes, that's why I'd like to confirm first

**Comment by steffen-4s1** [comment]
> Can you test `31.94.0`?

While you are writing your message my test with 31.94.0 was running. This version works very well.

**Comment by rarkins** [comment]
I can't reproduct it in `31.94.1` this way:

```
Digest: sha256:402eea77770de803f6649d636797ffff164f2210993d7690c20819832b188411
Status: Downloaded newer image for renovate/renovate:31.94.1
ubuntu@f56ce6dd98c4:/usr/src/app$ which npm
/usr/local/bin/npm
ubuntu@f56ce6dd98c4:/usr/src/app$ which yarn
/usr/local/bin/yarn
ubuntu@f56ce6dd98c4:/usr/src/app$ yarn --version
1.22.17
```

But I think that the evidence from @steffen-4s1 of something broken in `31.94.0` seems strong enough that we may as well revert the suspected commit and see if that resolves it.

**Comment by rarkins** [comment]
#14464 is now merged, it usually takes a few hours to roll out to the full image. Hoping it resolves the problem for you and looking forward to confirmation. I will leave this issue open until then

**Comment by marcovmun** [comment]
We have the same problem in pnpm lockfile updates.

**Comment by marcovmun** [comment]
Suggestion: Maybe add stack to the output when the stdout and/or stderr is empty. Now it was very unclear what was going wrong. 
![image](https://user-images.githubusercontent.com/16606883/156174229-d5a95c2d-545e-41a8-a383-7448abe2b067.png)

**Comment by steffen-4s1** [comment]
The full images just arrived the docker registry.
31.96.2 fixes the problem, all lockfiles are in sync with `package.json`.

Thanks for your quick response.

**Comment by rarkins** [comment]
> Suggestion: Maybe add stack to the output when the stdout and/or stderr is empty. Now it was very unclear what was going wrong. 

This normally happens. If you can reproduce or fix, either contributions would be welcome.
