### ISSUE TITLE
Replace method does not update commit message topic.

### ISSUE THREAD

**Issue by mujtaba-ahmed12** [renovatebot/renovate#14569]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.89.10

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

31.89.10

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Overriding commit message using environment var `RENOVATE_COMMIT_MESSAGE='{{commitMessageAction}} {{replace "github.com" "ghe" commitMessageTopic}} {{commitMessageExtra}}'` is not producing the expected commit message. Same changes works if we use `depName` instead of `commitMessageTopic` `RENOVATE_COMMIT_MESSAGE='{{commitMessageAction}} {{replace "github.com" "ghe" depName}} {{commitMessageExtra}}'`

### Relevant debug logs

Skipping this because of private keys inside logs as `RENOVATE_TOKEN`.

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by HonkingGoose** [comment]
Hi @mujtaba-ahmed12, 👋 

I cannot find a link to your minimal reproduction repository, can you edit your post and put the link in?

**Comment by mujtaba-ahmed12** [comment]
> Hi @mujtaba-ahmed12, wave
> 
> I cannot find a link to your minimal reproduction repository, can you edit your post and put the link in?

Hi @HonkingGoose,

Since this is private repository and we are running renovate bot as cloudbuild job. I can not share link to the repo.

**Comment by rarkins** [comment]
@mujtaba-ahmed12 please click the link above to see a description of what we mean by reproduction repository. We do not mean you linking to your actual repository.
