### ISSUE TITLE
matchSourceUrls

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#14561]
### What would you like Renovate to be able to do?

Add a new `packageRules` option `matchSourceUrls`, which is similar to `matchSourceUrlPrefixes` but does exact matches only.

### If you have any ideas on how this should be implemented, please tell us here.

Per above

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by RahulGautamSingh** [comment]
Hey @rarkins  
Will these additions suffice to get things going?
1. Adding new if-block to `[package-rules.ts](https://github.com/renovatebot/renovate/blob/main/lib/util/package-rules.ts)` for `matcSourceUrls` options and adding tests for them in the test file
2. Adding `matchSourceUrls` option to type <[PackageRule](https://github.com/renovatebot/renovate/blob/72efbfff998d553c026384b2cfe5884836dcd635/lib/config/types.ts#L258)> in `lib/config/types.ts` and to [selectors](https://github.com/renovatebot/renovate/blob/72efbfff998d553c026384b2cfe5884836dcd635/lib/config/validation.ts#L291) in `lib/config/validation.ts`

**Comment by viceice** [comment]
Also needs to be added to config options and the config docs

**Comment by RahulGautamSingh** [comment]
@rarkins Can we close this one?

**Comment by rarkins** [comment]
Yes. Next time if you put "Closes #14561" in the PR body then it will defer linked and closed automatically.
