### ISSUE TITLE
package-lock.json has incorrect modifications with rangeStrategy=update-lockfile

### ISSUE THREAD

**Issue by herndlm** [renovatebot/renovate#14584]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

We previously were using lockfile version 1 with npm 6 and I did not notice it there.

Since we migrated to lockfile version 2 with npm 8 I noticed that apparently Renovate uses e.g. `npm install --package-lock-only --no-audit --ignore-scripts postcss@8.4.8` to update postcss to 8.4.8. If there is a constraint like `^8.0.0` then npm updates also the `package.json` and relevant parts of it in `package-lock.json`.

Since I'm using `rangeStrategy=update-lockfile` only the lockfile is commited, which has still modifications that should not be there. When I do a local `npm install` they get reverted again, which is a bit annoying, e.g.
```diff
--- a/package-lock.json
+++ b/package-lock.json
@@ -23,7 +23,7 @@
         "css-minimizer-webpack-plugin": "^3.0.0",
         "mini-css-extract-plugin": "^2.0.0",
         "node-sass": "^7.0.0",
-        "postcss": "^8.4.8",
+        "postcss": "^8.0.0",
         "sass-loader": "^12.0.0",
         "terser-webpack-plugin": "^5.0.0",
         "vue-loader": "^15.5.1",
```

This is basically the follow-up of https://github.com/renovatebot/renovate/discussions/14562 where I initially was confused about that.

We're actually self-hosting Renovate and I noticed the problem with versions 31 and 32 on GitLab and Bitbucket. BUT I created a simple reproduction repo at https://github.com/herndlm/renovate-npm-lockfile-diff-repro that shows the problem.
While doing that I realized that this might be a `npm` limitation that is not easy to work around. Apparently it happens whenever the npm install command is called and I (a npm novice) couldn't figure out how to update the lockfile without updating package.json.
The following line should not have been changed https://github.com/herndlm/renovate-npm-lockfile-diff-repro/pull/3/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R12

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Executing command(branch="renovate/postcss-8.x-lockfile")
{
  "command": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/herndlm/renovate-npm-lockfile-diff-repro\":\"/mnt/renovate/gh/herndlm/renovate-npm-lockfile-diff-repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/herndlm/renovate-npm-lockfile-diff-repro\" docker.io/renovate/node bash -l -c \"install-tool npm 8.5.3 && hash -d npm 2>/dev/null || true && npm install --package-lock-only --no-audit --ignore-scripts postcss@8.4.8\""
}
DEBUG: exec completed(branch="renovate/postcss-8.x-lockfile")
{
  "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/herndlm/renovate-npm-lockfile-diff-repro\":\"/mnt/renovate/gh/herndlm/renovate-npm-lockfile-diff-repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/herndlm/renovate-npm-lockfile-diff-repro\" docker.io/renovate/node bash -l -c \"install-tool npm 8.5.3 && hash -d npm 2>/dev/null || true && npm install --package-lock-only --no-audit --ignore-scripts postcss@8.4.8\"",
  "durationMs": 14150,
  "stdout": "Installing legacy tool npm v8.5.3\n\nadded 1 package, and audited 208 packages in 6s\n\n10 packages are looking for funding\n  run `npm fund` for details\n\nfound 0 vulnerabilities\n8.5.3\n\nup to date in 1s\n\n1 package is looking for funding\n  run `npm fund` for details\n",
  "stderr": "npm WARN using --force Recommended protections disabled.\nnpm notice \nnpm notice New minor version of npm available! 8.3.1 -> 8.5.3\nnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.3>\nnpm notice Run `npm install -g npm@8.5.3` to update!\nnpm notice \nnpm WARN using --force Recommended protections disabled.\nchmod: cannot access '/home/ubuntu/.npm': No such file or directory\n"
}
DEBUG: package-lock.json needs updating(branch="renovate/postcss-8.x-lockfile")
DEBUG: Updated 1 lock files(branch="renovate/postcss-8.x-lockfile")
{
  "updatedArtifacts": [
    "package-lock.json"
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
As a first simple attempt at fixing this, I'd try "massaging" the lock file entry back to what it was.
