### ISSUE TITLE
Publish the `readme.md` files for `datasources`, `versioning` and `platforms`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#14608]
## Problem

There's a [`readme.md`](https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/aws-machine-image/readme.md) file for the AWS Machine Image datasource. But the content of this readme is **not** published on the [AWS Machine Image Datasource docs page](https://docs.renovatebot.com/modules/datasource/#aws-machine-image-datasource).

This problem was found in https://github.com/renovatebot/renovate/pull/14582#discussion_r822702447.

## Proposed fix

We should edit our "build the documentation" scripts, so that we publish the `readme.md` files from:

- [ ] `datasources`
- [ ] `versioning`
- [ ] `platforms`

## Do you want to help?

I'll let a maintainer work on this. 😉

**Comment by HonkingGoose** [comment]
@viceice Is this something you want to work on? I think you know all about our docs build scripts. 😉

**Comment by viceice** [comment]
Sure, but can't estimate a time frame yet. To busy 😉

**Comment by viceice** [comment]
@HonkingGoose Can you open a new docs issue for the refactoring?

**Comment by HonkingGoose** [comment]
> @HonkingGoose Can you open a new docs issue for the refactoring?

See issue #14772. 😉
