### ISSUE TITLE
Find a more permanent home for `@jamiemagee/osv-offline` package

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#14605]
### Describe the proposed change(s).

In order to allow me to iterate quickly on #6562 I created a package `@jamiemagee/osv-offline`[^1] which is in my GitHub account[^2]. In the long run, I think it should either be owned by the `renovate` org or `ossf`[^3] org.

The OpenSSF question is still open for debate. Currently the OSV schema is owned by the OpenSSF[^4]. However, OSV the service is owned by Google[^5] right now. Discussion around donating OSV to OSSF is currently ongoing in the OpenSSF vulnerability disclosures working group[^6]

We should take a decision for the long term when we look to enable this feature by default.

[^1]: https://www.npmjs.com/package/@jamiemagee/osv-offline
[^2]: https://github.com/JamieMagee/osv-offline
[^3]: https://github.com/ossf
[^4]: https://github.com/ossf/osv-schema
[^5]: https://github.com/google/osv
[^6]: https://github.com/ossf/wg-vulnerability-disclosures

**Comment by viceice** [comment]
I think we should move it to renovate org for now. As long as we don't require review @JamieMagee should be able to push new changes pretty fast without other maintainers.

We can also add semantic release, like we do in our other npm libs to continuous deliver to npm registry.

**Comment by JamieMagee** [comment]
In order to move the package into the `renovatebot` organization you need to have the correct permissions in the old repository and the new organization[^1]. @rarkins I've invited you to be a collaborator in my repository. I may need to elevate your privileges once you accept, but then you should be able to transfer the repository.

[^1]: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by rarkins** [comment]
Accepted. Shall I move it to github.com/renovatebot/osv-offline?

**Comment by JamieMagee** [comment]
Sounds good to me.

**Comment by rarkins** [comment]
Looks like I need more permissions, because I'm not seeing the Settings tab here:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/6311784/185839947-3147ee89-3721-433d-a361-1c31f2e90c92.png">

**Comment by JamieMagee** [comment]
There doesn't appear to be any permissions to escalate to. I'll check when I'm back home. If not we can create an escrow organisation, so you don't need to escalate my permissions in the renovatebot organisation.

**Comment by viceice** [comment]
@JamieMagee you should be able to make a move request of the repo to renovate org, then @rarkins should be able to accept the request.

**Comment by rarkins** [comment]
Last time I tried that I was pretty sure the person making the request needed to be an admin of both - quite restrictive if so

**Comment by HonkingGoose** [comment]
Here's the GitHub Docs on transferring a (personal) repository to an organization account: [^quote]

> ## Repository transfers and organizations
>
> To transfer repositories to an organization, you must have repository creation permissions in the receiving organization. If organization owners have disabled repository creation by organization members, only organization owners can transfer repositories out of or into the organization.
> 
> Once a repository is transferred to an organization, the organization's default repository permission settings and default membership privileges will apply to the transferred repository.

[^quote]: [GitHub Docs: Repository transfers and organizations](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#repository-transfers-and-organizations)

**Comment by rarkins** [comment]
Now changed:

![image](https://user-images.githubusercontent.com/6311784/185881022-8e95707e-b157-4ff6-b4e4-fb60ef57c3bd.png)

**Comment by JamieMagee** [comment]
I've moved the repository: https://github.com/renovatebot/osv-offline

**Comment by viceice** [comment]
please invite me as maintainer 🙃

**Comment by JamieMagee** [comment]
I don't appear to have permissions either. @rarkins can you add us both with the same permissions we have in other repositories please?

Closing this issue as completed.
