### ISSUE TITLE
Consolidate package cache usage in datasources

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#14632]
### Describe the proposed change(s).

Most datasources now use the cache decorator. The following have direct access:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/6311784/158052431-3f9f038d-ada3-421d-8ec0-d86d3f1592d4.png">

The purpose of this task is to research and describe "why" they need direct access, and refactor any that's possible.

For example in Maven we cache the "head" results, and that makes sense. But in Docker, this bespoke caching of labels seems to make less sense: https://github.com/renovatebot/renovate/blob/010b8d81309363fb05412f4071f5b610368c8a76/lib/modules/datasource/docker/index.ts#L493-L499

My main concern is that I want each cached datasource result to use a consistent cache key.

**Comment by viceice** [comment]
In docker it makes sense to make a head request to tags, so we can easily and fast check if we need to fetch again.

**Comment by rarkins** [comment]
I think many of the datasources could benefit from storing an ETag or modified-since header and reusing it, but that's perhaps a different topic?

**Comment by viceice** [comment]
Sure, but we should think about required API changes, so we don't have to make huge work twice. 🤔

**Comment by zharinov** [comment]
Almost for each case, there is some reason that prevented us from using decorator. As the first step, I'll prepare the explicit list of those reasons in order to address them step by step.

**Comment by zharinov** [comment]
- Docker
    - Avoids caching when exception is thrown, probably can be safely converted to decorator
- Maven
    - `fetchReleasesFromMetadata` avoids caching for responses containing `Authoriazation` header
    - Decorator can be extracted from `addReleasesFromIndexPage`
    - `addReleasesUsingHeadRequests` updates cache and stores it’s TTL as the separate flag
- Npm
    - Functions using cache are outside of the class implementation
- Nuget
    - Function is outside of class
- Packagist
    - Can be converted without problems
- Bazel
    - Can be converted with little modification

**Comment by zharinov** [comment]
Starting to work on those which can be converted

**Comment by JoergSiebahn** [comment]
We have a private Nexus to store our docker images. We updated the oci labels recently in our services to benefit from the release notes in update PRs on Kustomize resources. Before that change the oci labels were taken from the base image and the source was leading to the wrong repository. Although we had a couple of releases and can confirm with `docker inspect` that `org.opencontainers.image.source` and `org.opencontainers.image.url` contain the correct GitHub URL to the repo of the image, the link in the Renovate PR is still referencing the repository of the base image. Could this be related to the cache? Will the cache be evicted? When and why? Can we do something to evict the cache? We are using the GitHub app.
