### ISSUE TITLE
Gradle repo matching does not recognize maven content pattern

### ISSUE THREAD

**Issue by ZacSweers** [renovatebot/renovate#14640]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.0.6

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitHub Actions on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We have a repositories config in our `settings.gradle.kts` file that looks like so

```kotlin
pluginManagement {
  // ...
  repositories {
    // Google/Firebase/GMS/Androidx libraries
    google {
      content {
        includeGroupByRegex("androidx.*")
        includeGroupByRegex("com\\.google.*")
        includeGroupByRegex("com\\.android.*")
        includeGroupByRegex("android\\.arch.*")
        includeGroupByRegex("org\\.chromium.*")
      }
    }
  }
}
```

While I see [there is logic for this pattern](https://github.com/renovatebot/renovate/blob/0598f1b9d2bbf0fdeca66548b5fa3fd693381d23/lib/modules/manager/gradle/parser.ts#L463), it doesn't appear to work in the above case and updates in the google maven are subsequently not indexed when renovating.

We work around it for now with this snippet just above it to trick renovate into indexing it

```kotlin
if ("false".toBoolean()) {
  // This is a super dumb trick to get Renovate to check the Google maven repo. Its parsing
  // doesn't appear to properly recognize our content repo matching syntax below. This block
  // is obviously never entered but Renovate doesn't know that.
  google()
}
```

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by ZacSweers** [comment]
I can create a reproducing repo if need be, but I figured this case was fairly simple to demonstrate just in this issue

**Comment by rarkins** [comment]
We always want to test against a real repo before / after so a reproduction would be good (without your workaround)

**Comment by viceice** [comment]
This looks like a recent gradle issue we fixed. It was something about the content parsing of buildin registries.

**Comment by ZacSweers** [comment]
Do you know which version it should be fixed in? I can test that and put together a repro repo if it's still not working

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/releases/tag/32.1.0

Looks like the fixed version

**Comment by ZacSweers** [comment]
Let me test that out!

**Comment by ZacSweers** [comment]
Apologies for the delay - looks like things are good now!
