### ISSUE TITLE
Poetry: treat python as a dependency

### ISSUE THREAD

**Issue by rhuanbarreto** [renovatebot/renovate#14649]
### What would you like Renovate to be able to do?

Today, updates proposed in Dockerfile's doesn't count on restrictions in pyproject.toml

For example:

`pyproject.toml`
```
...
[tool.poetry.dependencies]
python = ">=3.9,<3.10"
...
```
`Dockerfile`
```
FROM --platform=linux/amd64 python:3.9-slim as build
...
```

Renovate comes with a [PR](https://github.com/rhuanbarreto/renovate-test/pull/2) trying to update python in the Dockerfile to 3.10, but in pyproject.toml 3.10 is not compatible. So both dependencies should be updated together.

From the debug logs, it seems that python is not being recognized as a dependency within the poetry project as per [this reference line](https://github.com/rhuanbarreto/renovate-test/blob/4c528e45cfe9c5f4fec78d7bcf0ef4e7527cbcf2/pyproject.toml#L8-L9):

```
DEBUG: packageFiles with updates
{
  "config": {
    "dockerfile": [
      {
        "packageFile": "Dockerfile",
        "deps": [
          {
            "depName": "python",
            "currentValue": "3.9-slim",
            "replaceString": "python:3.9-slim",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "depType": "final",
            "depIndex": 0,
            "warnings": [],
            "versioning": "docker",
            "currentVersion": "3.9",
            "isSingleVersion": true,
            "fixedVersion": "3.9-slim",
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "3.10",
                "newValue": "3.10-slim",
                "newMajor": 3,
                "newMinor": 10,
                "updateType": "minor",
                "branchName": "renovate/python-3.x"
              }
            ]
          }
        ]
      }
    ],
    "poetry": [
      {
        "packageFile": "pyproject.toml",
        "deps": [
          {
            "depName": "Flask",
            "depType": "dependencies",
            "currentValue": "^2.0.3",
            "managerData": {
              "nestedVersion": false
            },
            "datasource": "pypi",
            "versioning": "poetry",
            "depIndex": 0,
            "warnings": [],
            "homepage": "https://palletsprojects.com/p/flask",
            "changelogUrl": "https://flask.palletsprojects.com/changes/",
            "currentVersion": "2.0.3",
            "updates": []
          }
        ],
        "registryUrls": null,
        "constraints": {
          "python": ">=3.9,<3.10"
        },
        "lockFiles": [
          "poetry.lock"
        ]
      }
    ]
  }
}
```

So the request is to treat python as a dependency.

A reference repo showing the behavior is available on https://github.com/rhuanbarreto/renovate-test

### If you have any ideas on how this should be implemented, please tell us here.

I think this is only being ignored by renovate somehow. It's not a matter of implementing new things.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rhuanbarreto** [comment]
Please read the referencing issue.

Repo is on https://github.com/rhuanbarreto/renovate-test/pull/2

**Comment by rarkins** [comment]
The problem should be described in full here, and until it is, it will remain labeled as `status:requirements`. To make things worse, the PR you link to is *irrelevant* to this feature request and may confuse things. You should instead be highlighting the line in the poetry file which is seemingly being ignored and not upgraded.

**Comment by rhuanbarreto** [comment]
Sorry for being a noob that don't know how to write good descriptions. Description updated. Hope it's acceptable.

**Comment by rarkins** [comment]
Actually, now that you expand on the description I think we have two different topics here getting mixed up.

"treat python as a dependency", which I suggested to you, means "if the python field in poetry says `>=3.9,<3.10` then propose to upgrade it to allow `3.10`".

What you are asking for - that we suppress an update to a Dockerfile based upon a dependency range in a poetry toml file - is not something we will support. Instead, when treating python as a dependency is done, you will have a PR which contains updates to both your Dockerfile and pyproject.toml allowing python 3.10. You can then choose to close/ignore such a PR if you like.

**Comment by rhuanbarreto** [comment]
I'm happy to have a PR from renovatebot upgrading in both places as I said in the description. But only having one can lead the developer to make the things wrong once both sides must be in sync.

**Comment by rarkins** [comment]
In this case the description and reproduction can be simplified so that we can isolate why python is not getting updated
