### ISSUE TITLE
Semantic (conventional) commits does NOT require lowercase

### ISSUE THREAD

**Issue by Wirone** [renovatebot/renovate#14712]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest renovate/renovate image (32.6.2)

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

Official image

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

In #594 it was discussed and implemented in 6c1f27f9 that conventional commits should be in lowercase. It's wrong even when considering #594's description, where we can see "Don't capitalize first letter" (first, not all!). In fact, [conventionalcommits.org](https://www.conventionalcommits.org/en/v1.0.0/#are-the-types-in-the-commit-title-uppercase-or-lowercase) states:

> ### Are the types in the commit title uppercase or lowercase?
> 
> Any casing may be used, but it’s best to be consistent.

Also commit examples contain uppercase words:
- `chore!: drop support for Node 6`
- `docs: correct spelling of CHANGELOG`
- `eat(lang): add Polish language`

There's no need to lowercase whole commit message. For us, it breaks our custom `groupName`s, because we wanted to use `PROD dependencies` and `DEV dependencies` (`require` and `require-dev` for Composer) to be more explicit in MRs. Right now, it's lowercased (`fix(composer): update prod dependencies`) and I think it's unnecessary.

### Relevant debug logs

n/a

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by Wirone** [comment]
You're quick as lightning @rarkins 😅 Sorry for duplicate, I did search but somehow didn't find it 🤔

**Comment by rarkins** [comment]
No problem, these types of ones can be hard to find with search. I knew it existed this time..
