### ISSUE TITLE
Gitlab: Support for reviewers taken from groups used in CODEOWNERS file

### ISSUE THREAD

**Issue by Wirone** [renovatebot/renovate#14777]
### What would you like Renovate to be able to do?

We use Gitlab groups as nested organisational structure, teams are assigned as code owners. It would be great if MR reviewers could be set using the same approach. Currently with `reviewersFromCodeOwners=true` and `composer.lock @team/composer`-like rules in `CODEOWNERS` file the result of Renovate pass is:

```
 INFO: PR created (repository=foo/bar, branch=feature/renovate/aws-aws-sdk-php-3.x-lockfile)
       "pr": 7922,
       "prTitle": "fix(composer): update dependency aws/aws-sdk-php to v3.215.1"
 WARN: Failed to add assignees (repository=foo/bar, branch=feature/renovate/aws-aws-sdk-php-3.x-lockfile)
       "iid": 7922,
       "assignees": ["team/composer"]
 WARN: Failed to get IDs of the new reviewers (repository=foo/bar, branch=feature/renovate/aws-aws-sdk-php-3.x-lockfile)
       "err": {
         "message": "Cannot read property 'id' of undefined",
         "stack": "TypeError: Cannot read property 'id' of undefined\n    at getUserID (/usr/src/app/node_modules/renovate/lib/modules/platform/gitlab/http.ts:10:13)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
```

Script that determines users from `CODEOWNERS` should fallback to group check if user ID can't be resolved from rule entry. Most probably [Members API](https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project) should be used for that.

### If you have any ideas on how this should be implemented, please tell us here.

For each item in `CODEOWNERS` rule entry (e.g. `@john`, `@admins`, `@team/devops`):

- check if it's user
  - if yes, use ID and set as reviewer
  - if not, check if it's a group
    - if yes, retrieve all members of a group and use their IDs for setting as reviewers
    - if not, print error and ignore reviewers' assignment

PS. I choose "Maybe" because I really would like to dig into the code and try to implement it, but I don't know if I can do it (time, knowledge).

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
Sounds good to me

**Comment by viceice** [comment]
The referenced API is only for group members, we need to get the id from name.

Is there no way to distinguish group and user from name?

**Comment by Wirone** [comment]
@viceice when you expand group to members you need to check each member just like now - retrieve ID from name.

**Comment by viceice** [comment]
I think we currently don't flatten any group before we assign them as reviewers.

That would be a different request to the original issue.

**Comment by Wirone** [comment]
@viceice but actually it's described in the issue that groups should be expanded to users list and all of them should be assigned? 🤔 So it's THE request here 😅

**Comment by viceice** [comment]
Can you please clarify it, as it wasn't really clear in the PR requirements.

Does gitlab support assigning groups as reviewers? So the first step would be to support groups and a second step would be a new platform option to expand groups before assignment.

**Comment by Wirone** [comment]
I think everything it was clarified already 🤔 Gitlab does NOT allow assigning groups as reviewers, you need to expand groups to members' list and it was described above. So instead of printing error after `Cannot read property 'id' of undefined` script needs to fallback to Members API, try to expand group into members and then remap each member to get ID (as it's done right now for each `CODEOWNERS` item). So in the end:

- error from Users API && error from Members API = "Failed to get IDs of the new reviewers"
- ID from user || IDs from group members = Assign each as reviewer

**Comment by marwin1991** [comment]
Also waiting :) maybe define reviewers as group would be amazing?

**Comment by chickenandpork** [comment]
Nailed by this; sadly it seems there's a solution by @suprememoocow but it's refused for dependencies.

Per @marwin1991 the reviewers action is now split from assignee in Gitlab.

**Comment by chickenandpork** [comment]
https://github.com/renovatebot/renovate/issues/7368 is the same issue in Github

**Comment by justinas-b** [comment]
👀 would it make sense to reopen https://github.com/renovatebot/renovate/pull/15835 ?

**Comment by Wirone** [comment]
@viceice @rarkins is it possible to re-evaluate @suprememoocow's [PR](https://github.com/renovatebot/renovate/pull/15835)? In my opinion it was great base for this feature. It could be really helpful for several people, as we see here.

**Comment by rarkins** [comment]
I think we can proceed with this but ideally this would be cached for the duration of Renovate's execution so that we don't hammer the API any more

**Comment by justinas-b** [comment]
Hey @viceice @rarkins ! Do you think it would be possible to reopen https://github.com/renovatebot/renovate/pull/15835 ? If not, I am willing to open new pull request

**Comment by rarkins** [comment]
That PR can't be reopened, so please create a new one.

**Comment by justinas-b** [comment]
Created new PR (https://github.com/renovatebot/renovate/pull/19469)

**Comment by Wirone** [comment]
I've changed our config to use Gitlab group and new MRs are created properly, with users resolved from the group 🎉. Thank you very much @justinas-b 🍻
