### ISSUE TITLE
workarounds:mavenCommonsAncientVersion no more working?

### ISSUE THREAD

**Issue by tarioch** [renovatebot/renovate#14817]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.7.5

### Please select which platform you are using if self-hosting.

Bitbucket Server

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Since a couple of days, the workarounds:mavenCommonsAncientVersion doesn't seem to work anymore, we suddenly got PRs created for those old versions. We're pulling the workaround in with "extends": ["workarounds:all"]

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by tarioch** [comment]
Checked, the PRs were created at March 25th 23:20, so I'm guessing it came in with one of the 32.7.x versions

**Comment by tarioch** [comment]
Manually adding 

```yaml
"packageRules": [
    {
      "matchDatasources": [
        "maven",
        "sbt-package"
      ],
      "matchPackagePrefixes": [
        "commons-"
      ],
      "allowedVersions": "!/^200\\d{5}(\\.\\d+)?/"
    }
  ]
```

to the config works, so it seems to really be related to loading the preset

**Comment by tarioch** [comment]
I tried to reproduce it with github:

https://github.com/tarioch/renovate-repro 

but weird enough even without any workarounds, the old commons-cli version isn't picked up, maybe there is some additional config somewhere in the github app that prevents this?

**Comment by rarkins** [comment]
This is why reproductions are alwys good. Maybe you're not using `config:base`?

**Comment by tarioch** [comment]
I was trying to first set the github project up that it doesn't have any workarounds (so it should create the PR) and then add the workaround to see if it works there. But without any config on github, it seems to already have workarounds in.

**Comment by rarkins** [comment]
Check the debug logs as it may give you a hint what's going on
