### ISSUE TITLE
Nested matchPackagePattern regex end $ anchor matching as false positive

### ISSUE THREAD

**Issue by leotm** [renovatebot/renovate#14810]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

nested [matchpackagepatterns](https://docs.renovatebot.com/configuration-options/#matchpackagepatterns) with regex $ anchor seems to be false positively matching for this part of my [renovate.json](https://github.com/leotm/react-native-template-typescript/blob/master/renovate.json#L47-L61)

```json
    {
      "matchPackagePatterns": ["^eslint", "^typescript-eslint"],
      "groupName": "eslint monorepo",
      "labels": ["devDeps", "linting"],
      "packageRules": [
        {
          "matchPackagePatterns": ["jest$"],
          "addLabels": ["jest"]
        },
        {
          "matchPackagePatterns": ["react$"],
          "addLabels": ["react"]
        }
      ]
    }
```

so an _eslint_ [PR](https://github.com/leotm/react-native-template-typescript/pull/477) shouldn't be adding _jest_ and _react_ labels (i've removed/merged then since)

whereas
- _eslint-plugin-react_ would match then add the _react_ label too
- _eslint-plugin-jest_ would match then add the _jest_ label too

---

i thought maybe `packageRules` can't be nested, but it [works fine](https://github.com/leotm/react-native-template-typescript/blob/86494153c27a608238d771628f17c284e902b04c/renovate.json#L26-L46) for my rule above it ([PR](https://github.com/leotm/react-native-template-typescript/pull/476)), however its using `matchSourceUrlPrefixes` > `matchPackageNames`

so maybe `matchpackagepatterns` can't be nested within `matchpackagepatterns`, seems to be matching then ignoring the nested pattern

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Package rules aren't meant to be nested, even if sometimes it works

**Comment by leotm** [comment]
gotcha ^ cheers
