### ISSUE TITLE
Missing source directory for bitnami helm charts

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#14820]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Some time a go i've implemented a better helm source url handling which works as expected.
But for some reason renovate ignores the `sourceDirectory` property for the links in the PR update table.

- https://github.com/renovate-reproductions/helm-chart-source-url/pull/1

### Relevant debug logs

Nothing relevant found there
<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by hasanwhitesource** [comment]
would you kindly describe the expected result in this case ?
I see there is a repo and a chart in the tf file the version isn't updated correctly or some other change is supposed to be happening ?

**Comment by viceice** [comment]
The link should go to `https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus` instead of `https://github.com/bitnami/charts` or it should have a second  `source` link which points to `https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus`

**Comment by hasanwhitesource** [comment]
Relevant logs (but with a basic renovate.json config): 
```
DEBUG: packageFiles with updates (repository=hasanwhitesource/missing-datasoource)
       "config": {
         "terraform": [
           {
             "packageFile": "prometheus.tf",
             "deps": [
               {
                 "currentValue": "6.8.2",
                 "depType": "helm_release",
                 "registryUrls": ["https://charts.bitnami.com/bitnami"],
                 "depName": "kube-prometheus",
                 "datasource": "helm",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "6.12.1",
                     "newValue": "6.12.1",
                     "releaseTimestamp": "2022-05-18T14:32:58.785Z",
                     "newMajor": 6,
                     "newMinor": 12,
                     "updateType": "minor",
                     "branchName": "renovate/kube-prometheus-6.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "hashicorp",
                 "sourceUrl": "https://github.com/bitnami/charts",
                 "sourceDirectory": "bitnami/kube-prometheus",
                 "currentVersion": "6.8.2",
                 "isSingleVersion": true,
                 "fixedVersion": "6.8.2"
               }
             ]
           }
         ]
       }
```

**Comment by viceice** [comment]
Yes, `sourceDirectory` is correctly parsed, but somehow not used in PR table 🙃

**Comment by hasanwhitesource** [comment]
The helm datasource at `getReleases`  receives a `homepage` property which is the value that is needed in this case and not the value of `sourceUrl` property.

![image](https://user-images.githubusercontent.com/90554456/174480773-765fc4bc-00bd-4876-9007-338ac963286a.png)

We could check the sourceUrl value with the homepage value and set the `sourceUrl` to `hompage`. @viceice you think the homepage should take precedence ?

**Comment by viceice** [comment]
i don't think it's a matter of precedence. on other deps renovate shows a link to Hompage and source repo. so i think we should just concider source directory when building source url in PR does table

**Comment by hasanwhitesource** [comment]
- I saw that we are already taking the `homepage` as a link for the package name incase there is one here : 
https://github.com/renovatebot/renovate/blob/73fdf0483e5e06cd977adc874af70718ac08d3b6/lib/workers/repository/update/pr/body/index.ts#L24

- And as I mentioned there is a `homepage` property from the datasource, however its being lost here :
https://github.com/renovatebot/renovate/blob/73fdf0483e5e06cd977adc874af70718ac08d3b6/lib/modules/datasource/metadata.ts#L118-L123

I think the fix should be to delete the homepage property only if we set the sourceUrl to it and not to delete it anyway
What do you think @viceice  ? 🙂

**Comment by viceice** [comment]
🤔 @rarkins looks like we only should delete `homepage` if we set `sourceUrl` ? So move the delete to inner if? 🤔 

We shopuld propably also massage the `homepage` some lines below then

**Comment by viceice** [comment]
it looks like `sourceDirectory` is lost somewhere before this
https://github.com/renovatebot/renovate/blob/edefea8db09707a55243eb6ff1c6794627f02783/lib/workers/repository/update/pr/body/index.ts#L43-L52

**Comment by hasanwhitesource** [comment]
It works as expected with source url being set to the `/bitnami/charts` beside it, when the delete homepage is moved to the inner if.
Check it out : https://github.com/hasanwhitesource/missing-datasoource/pull/9
Or do you mean something else ?
```
DEBUG: packageFiles with updates (repository=hasanwhitesource/missing-datasoource)
       "config": {
         "terraform": [
           {
             "packageFile": "prometheus.tf",
             "deps": [
               {
                 "currentValue": "6.8.2",
                 "depType": "helm_release",
                 "registryUrls": ["https://charts.bitnami.com/bitnami"],
                 "depName": "kube-prometheus",
                 "datasource": "helm",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "6.13.3",
                     "newValue": "6.13.3",
                     "releaseTimestamp": "2022-05-24T14:42:22.188Z",
                     "newMajor": 6,
                     "newMinor": 13,
                     "updateType": "minor",
                     "branchName": "renovate/kube-prometheus-6.x"
                   },
                   {
                     "bucket": "major",
                     "newVersion": "8.0.7",
                     "newValue": "8.0.7",
                     "releaseTimestamp": "2022-06-14T12:36:43.454Z",
                     "newMajor": 8,
                     "newMinor": 0,
                     "updateType": "major",
                     "branchName": "renovate/kube-prometheus-8.x"
                   }
                 ],
                 "warnings": [],
                 "versioning": "hashicorp",
                 "sourceUrl": "https://github.com/bitnami/charts",
                 "sourceDirectory": "bitnami/kube-prometheus",
                 "homepage": "https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus",
                 "currentVersion": "6.8.2",
                 "isSingleVersion": true,
                 "fixedVersion": "6.8.2"
               }
             ]
           }
         ]
       }
```

**Comment by viceice** [comment]
better to fix it here:
https://github.com/renovatebot/renovate/blob/edefea8db09707a55243eb6ff1c6794627f02783/lib/workers/repository/update/pr/body/index.ts#L24-L27

if it's `sourceUrl` also append `sourceDirectory` liek we do here
https://github.com/renovatebot/renovate/blob/edefea8db09707a55243eb6ff1c6794627f02783/lib/workers/repository/update/pr/body/index.ts#L45-L50

**Comment by rarkins** [comment]
> 🤔 @rarkins looks like we only should delete `homepage` if we set `sourceUrl` ? So move the delete to inner if? 🤔
> 
> We shopuld propably also massage the `homepage` some lines below then

Yes looks like a mistake

**Comment by hasanwhitesource** [comment]
@viceice I need to make sure that the tests which are currently failing are supposed to be fixed. 
After the fix we are deleting the `homepage` property when :
- We set `sourceUrl` value to `homepage`
- When `sourceUrl` becomes equal to `homepage` after "massaging" it here : https://github.com/renovatebot/renovate/blob/fce509762afd6d32b09b82a9a803006a1b8f5638/lib/modules/datasource/metadata.ts#L130-L150

**Comment by hasanwhitesource** [comment]
Regarding the fix :
- homepage property should is being deleted if `sourceUrl` has been set to it.
- Delete homepage if its same as `sourceUrl` after "massaging" it and its not a link to a page. 
@viceice what do you think ?

**Comment by viceice** [comment]
sounds good. assign me as reviewer when PR is ready to review 😉

**Comment by hasanwhitesource** [comment]
@viceice regarding the solution can we please clarify what is the difference between `homepage` and `sourceUrl` exactly ?
To my understanding `homepage` is the exact link to the dependency and `sourceUrl` is the source of that dependency e.g Github right?

Shouldn't this test have `sourceUrl` instead of `homepage` ?
![image](https://user-images.githubusercontent.com/90554456/178922619-6e116bc6-45d9-4221-a8ab-c5a667a72cc1.png)

**Comment by viceice** [comment]
`sourceUrl` is more important, because we use it to fetch release notes. So if `homepage` and `sourceUrl` are the same, we always shoud remove `homepage`. 

You should also use my sugggestion from comment above https://github.com/renovatebot/renovate/issues/14820#issuecomment-1171042666

Otherwise on bitnami the sourceDirectory will still be missing.

**Comment by hasanwhitesource** [comment]
@viceice yes simple logic but some tests needed fixing that's why I changed it and regarding you comment on the test there is a `sourceUrl` but its at the bottom of the snapshot maybe you've messed it 😅 .

Following the fix there are 18 tests that in need of fixing (missing `homepage`).

**Comment by viceice** [comment]
lets fix the tests instead of the bad workaround to not change tests

**Comment by hasanwhitesource** [comment]
Will push my fix soon

**Comment by hasanwhitesource** [comment]
@viceice @nabeelsaabna I will create a refactor pr for `datasoruce/meta.ts` which will use a more reliable check for url hostname before finalizing the fix.
