### ISSUE TITLE
Datasource golang-version has stopped working

### ISSUE THREAD

**Issue by maxbrunet** [renovatebot/renovate#14837]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Renovate throws a `Host error`: `Invalid file - release has empty version` when fetching releases from the `golang-version` datasource and aborts.

The line throwing the error:
https://github.com/renovatebot/renovate/blob/41fd7fbf46ca9e3a46f5ace2a1de213929d9e347/lib/modules/datasource/golang-version/index.ts#L70-L74

It seems the `release.go` file has been reformatted a week ago:
https://github.com/golang/website/commit/cc71b62800363d71df2a367575abe9913d66a045#diff-4ba9e91eadf1c81f0f23c8a0a0ed0cb6942d3d3634615980d9822ca76eb93786

From a quick look, I think it is because these characters now appear within a release block:
https://github.com/renovatebot/renovate/blob/41fd7fbf46ca9e3a46f5ace2a1de213929d9e347/lib/modules/datasource/golang-version/index.ts#L9-L10

Here is a public repo where it occurs: [maxbrunet/bitbucket-semantic-pull-requests](https://github.com/maxbrunet/bitbucket-semantic-pull-requests) (edit: switched to docker datasource)

### Relevant debug logs

<details><summary>Logs</summary>

```jsonc
WARN: Host error
{
  "hostType": "golang-version",
  "packageName": "golang",
  "err": {
    "message": "Invalid file - release has empty version",
    "stack": "Error: Invalid file - release has empty version\n    at GolangVersionDatasource.getReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/golang-version/index.js:50:71)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /home/ubuntu/renovateapp/node_modules/renovate/dist/util/cache/package/decorator.js:62:24\n    at async getRegistryReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:57:17)\n    at async fetchReleases (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/datasource/index.js:218:23)"
  }
}
INFO: External host error causing abort - skipping
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by MaronHatoum** [comment]
hi @maxbrunet 
can you please provide a minimal reproduction repo?

**Comment by MaronHatoum** [comment]
I succeeded to reproduce the issue with the repo you provided in the bug description `bitbucket-semantic-pull-requests`.
