### ISSUE TITLE
Renovate doesn't respect `enabledManagers`

### ISSUE THREAD

**Issue by okainov** [renovatebot/renovate#14848]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest docker

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Looks like this change https://github.com/renovatebot/renovate/pull/11616 has broken properly working behavior. While breaking backward compatibility as a fact is something we can put aside, I really don't understand why Renovate doesn't respect my configs.

What I *already* had in my renovate.json:
```json
  "enabledManagers": ["git-submodules", "pre-commit"],
```

And it used to work perfectly. And today it seems I'm required to add *extra* this block:
```json
  "pre-commit": {
    "enabled": true
  }
```

I'm inclined to treat this as a bug, I already mentioned I need `pre-commit` in my `enabledManagers`, why do I need anything extra for it?

P.S. Actually the same is happening with `git-submodules` fyi.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
We'll accept a PR which automatically sets X.enabled = true in config if enabledManagers.includes(X)
