### ISSUE TITLE
Referencing a preset on Azure DevOps with space in path doesn't work

### ISSUE THREAD

**Issue by kipusoep** [renovatebot/renovate#14845]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.10.2

### Please select which platform you are using if self-hosting.

Azure DevOps (dev.azure.com)

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I found out that when I'm referencing a preset in another repository with a path, and the path contains a space character, a "Preset is invalid" error is thrown.
This is because of this regex:
https://github.com/renovatebot/renovate/blob/2bfb5604dcb2a3eb1af67d747665caed4cd527ef/lib/config/presets/index.ts#L41
It should be adjusted to this (allow a space in the presetPath part):
`/^(?<repo>~?[\w\-. /]+?)\/\/(?:(?<presetPath>[\w\-. /]+)\/)?(?<presetName>[\w\-.]+)(?:#(?<tag>[\w\-./]+?))?$/`

So to be clear, this is my extends config setting:
`"extends": [ "Company/Infrastructure//reno vate/default" ]`

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
This is intended, we already had a discussion some time ago about it, check the discussions

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/issues/12595#issuecomment-969847558

**Comment by kipusoep** [comment]
To be honest I don't see the point of not supporting it and I don't think "spaces seems to be bad practice anyway to me" is a strong argument.
I'll implement a work-around for our case.

**Comment by rarkins** [comment]
> This is intended, we already had a discussion some time ago about it, check the discussions

If spaces are common in Azure *org names*, then maybe we need to reconsider the decision?

**Comment by kipusoep** [comment]
To be clear; this fix is for directories, not for preset file names.

**Comment by kipusoep** [comment]
I can live with that, already worked around it so... Just don't get it why the limitation is there in the first place, when a fix is already presented as PR. But hey, who am I :-)

**Comment by rarkins** [comment]
Conclusion: we don't want to support paths in preset files names
