### ISSUE TITLE
Update Terraform Version Management File `.terraform-version`, used by tfenv/tfswitch

### ISSUE THREAD

**Issue by imaginaryCorn** [renovatebot/renovate#14857]
### What would you like Renovate to be able to do?

We want to ensure that developers can safely make Terraform changes with the version managed automatically for them. We are planning to lock our `required_version` to a full version number so that Terraform version updates are managed across our monorepo by Renovate, however we also use `tfswitch` for ensuring that the Terraform version matches the version in Terraform state as much as we can.

To achieve fully automated Terraform version updates, we would be interested in the ability of Renovate to manage `.terraform-version` files alongside the `required_version` checks it does. This file extension is the same for `tfswitch` and `tfenv`, the main Terraform version managers available.

### If you have any ideas on how this should be implemented, please tell us here.

Not a fully experienced TS developer, but I imagine it would follow the `.node-version` [solution](https://github.com/renovatebot/renovate/tree/1d0bfada3c5641cf566978820b9c4c221d764b87/lib/manager/nodenv) structure.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
You can workaround with regex manager until we natively support this.

**Comment by imaginaryCorn** [comment]
Closing, did not realise it was handled already https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/terraform-version/index.ts many thanks!
