### ISSUE TITLE
Enable corepack in renovate/node image

### ISSUE THREAD

**Issue by jgraichen** [renovatebot/renovate#14851]
### What would you like Renovate to be able to do?

As discussed in #14797, using [`corepack`](https://github.com/nodejs/corepack) in the `renovate/node` container image could ease using the correct version for `yarn` or `pnpm` for all tasks. `corepack` will automatically use the correct package manager version specified in `packageManager` in the projects `package.json`, or fall back to a known safe version:

> * If the local project is configured for the package manager you're using, Corepack will silently download and cache the latest compatible version.
>
> * If the local project is configured for a different package manager, Corepack will request you to run the command again using the right package manager - thus avoiding corruptions of your install artifacts.
> 
> * If the local project isn't configured for any package manager, Corepack will assume that you know what you're doing, and will use whatever package manager version has been pinned as "known good release". Check the relevant section for more details.

-- https://github.com/nodejs/corepack#usage=

`corepack` is already included with Node.js 14.19.0 and 16.9.0, but needs to be opted in:

```
corepack enable
```

### If you have any ideas on how this should be implemented, please tell us here.

It might be enough to run `corepack enable` when building the `renovate/node` container image, and to remove all specific commands to install `yarn` and to set any version (`npm install -g yarn && yarn set version ...`). 

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
currently it's only useful for yarn V2+, when the binary isn't checked to repo.

all other scenarios currently work and won't make it better, instead it can make things worse  when corepack isn't used. then corepack can change lockfile versions, which we should suppress on all circumstances.
