### ISSUE TITLE
github-releases data source doesn't pick up changes if old version is too old

### ISSUE THREAD

**Issue by sarahhodne** [renovatebot/renovate#14850]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I added a regex manager to update [goreleaser](https://github.com/goreleaser/goreleaser), but noticed that Renovate wasn't opening a PR to update things.

The current version in my repository is v0.167.0, and the latest version is v1.7.0.

According to the logs, Renovate picks up the current version just fine, but seems to think that there's no new version available, or that v0.167.0 is the latest somehow.

The logs also show a single API call to https://api.github.com/repos/goreleaser/goreleaser/releases, which I notice doesn't include the `v0.167.0` release, as there's enough newer releases that this release gets bumped to a later page with pagination.

I created a manual PR to update the dependency to v0.184.0 (which _is_ listed on the first page of that API call), and after merging that Renovate then made a PR to continue forward to v1.7.0.

I don't know if the pagination issue is what's happening, but it seems likely given what I saw.

Minimal reproduction: https://github.com/sarahhodne/renovate-github-releases-bug-repro

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: packageFiles with updates
{
  "config": {
    "regex": [
      {
        "packageFile": "repro",
        "deps": [
          {
            "depName": "goreleaser/goreleaser",
            "currentValue": "v0.167.0",
            "currentDigest": "9939aabfcf20302a9569a50502f6a7000bbb5a6f5574ddc93111cbd6cc80ec3e",
            "datasource": "github-releases",
            "replaceString": "GORELEASER_VERSION=\"v0.167.0\"\nGORELEASER_CHECKSUM=\"9939aabfcf20302a9569a50502f6a7000bbb5a6f5574ddc93111cbd6cc80ec3e\"",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "versioning": "semver",
            "sourceUrl": "https://github.com/goreleaser/goreleaser",
            "currentVersion": "v0.167.0",
            "isSingleVersion": true,
            "fixedVersion": "v0.167.0"
          }
        ],
        "matchStrings": [
          "GORELEASER_VERSION=\"(?<currentValue>.*?)\"\\s+GORELEASER_CHECKSUM=\"(?<currentDigest>.*?)\""
        ],
        "depNameTemplate": "goreleaser/goreleaser",
        "datasourceTemplate": "github-releases"
      }
    ]
  }
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Either Renovate is not paginating at all, or maybe it limits pagination to e.g. 10 pages so does not paginate *enough*. Are you able to determine this from your testing/logs?

**Comment by sarahhodne** [comment]
I don't think it paginates at all, if my file contains the first version on the second page, Renovate doesn't make a PR, but if I pick the next version (i.e. the oldest one that appears on the first page), Renovate does open a PR.

**Comment by viceice** [comment]
it should paginate 🤔 
https://github.com/renovatebot/renovate/blob/143c9a67516180e364e7a0881b1d9ac4d3fb1b17/lib/modules/datasource/github-releases/index.ts#L242-L244

**Comment by viceice** [comment]
@zharinov Maybe paging is broken?

- #13416
-

**Comment by zharinov** [comment]
I don't think it's broken, I tested it today

**Comment by hasanwhitesource** [comment]
Not very familiar with this code base here : https://github.com/renovatebot/renovate/blob/0cf2ab4823dec410ed9a6e12fd8e9e10a7c219cb/lib/modules/datasource/github-releases/index.ts#L129

But I checked the assets that were fetched for the new release and none were matching the `releaseChecksumAssetName` which is being set to `'goreleaser_checksums.txt'` before the find operation, I think we were expecting the asset name to have the old version in it.
@viceice @zharinov could we be missing a case where the new asset name can be having a value that does not have to do with the version ?

**Comment by rarkins** [comment]
Is it possibly because we limit to 1000 results?

**Comment by hasanwhitesource** [comment]
I forgot to mention that an update pr isn't being created because the digests for the updates are being set to null and we are ending up with no updates after filtering here 
https://github.com/renovatebot/renovate/blob/0cf2ab4823dec410ed9a6e12fd8e9e10a7c219cb/lib/workers/repository/process/lookup/index.ts#L362

**Comment by hasanwhitesource** [comment]
Not cause of a limit or paging issue Its just we have a case where the asset name isn't as we expect.
Currently we expect the asset name to be the old asset name but with the new version instead
I suggest a fallback when no digest asset is found for a release based on digest asset name. @rarkins @zharinov what do you think?

**Comment by zharinov** [comment]
Related to #15645 (one may block or interfere with another)

**Comment by dmivankov** [comment]
Another example is https://github.com/aquasecurity/trivy-db/releases
they create releases frequently and keep only few latest ones

**Comment by hasanwhitesource** [comment]
@dmivankov thanks for the link this will be taken into account.

**Comment by rarkins** [comment]
Is this resolved after the recent changes by @zharinov to github tags and releases fetching?

**Comment by zharinov** [comment]
It should fetch at most `100 x 100 = 10000` items now 🤔

**Comment by rarkins** [comment]
I think this is now working: https://github.com/sarahhodne/renovate-github-releases-bug-repro/pull/4
