### ISSUE TITLE
composer: creates empty PRs in case the dependency isn't installable according to platform

### ISSUE THREAD

**Issue by lazka** [renovatebot/renovate#14869]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Since https://github.com/renovatebot/renovate/pull/13657 (I think) renovate no longer creates broken PRs where it updates packages that are in conflicts with the minimum PHP version.

But now it creates empty PRs for every version update of those dependencies.

For example I have 10 repos which each depend on "friendsofphp/php-cs-fixer" which dropped support for PHP 7.3 some time ago, but I still need to support PHP 7.3 and set config.platform.php.

This results in 10 empty PRs being created every time there is a new release for each of my repos.

Reproducer: https://github.com/lazka/renovate-composer-platform-test/pull/4

I personally use self-hosted on GitLab, but it's the same problem there.

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
The linked PR is not *empty*, it has this change?

![image](https://user-images.githubusercontent.com/6311784/160834604-d4353171-575e-4f89-81d6-23f100ffbafc.png)

Is that because the "wrong" version of the tool was run? 2.3.0 instead of 2.2.0?

If we ran with the correct version of Composer then we might get an *actually* empty PR, which then would never be raised.

**Comment by lazka** [comment]
Hm, yeah, I think what I see on on GitLab is that it is created in combination with other updates, but then the lock file maintenance swoops in, updates those, and what is left are lots of empty MRs:

https://gitlab.tugraz.at/dbp/relay/dbp-relay-core-bundle/-/merge_requests/107

**Comment by rarkins** [comment]
Why do you need to update transitive deps in the same PR? Shouldn't composer already update the transitive dependencies of the updated dependency without lock file maintenance?

**Comment by rarkins** [comment]
As a general comment, Renovate won't itself *create* an empty MR/PR, it should abort the branch if there's no changes.

**Comment by lazka** [comment]
> Why do you need to update transitive deps in the same PR? Shouldn't composer already update the transitive dependencies of the updated dependency without lock file maintenance?

Only in case the direct dependency changes, no? Which might never happen.

**Comment by lazka** [comment]
> As a general comment, Renovate won't itself _create_ an empty MR/PR, it should abort the branch if there's no changes.

Good to know. I could swear it did that on GitLab multiple times, I'll preserve the logs if I see it again.

To summarize: It would be nice if renovate would ignore such impossible updates, but if that's not possible feel free to close.
If I catch it opening an empty MR I can report that separately.

Thanks for renovate 🙏

**Comment by lazka** [comment]
> Why do you need to update transitive deps in the same PR?

oh, to clarify, I meant that it created a separate PR with lock file maint in the meantime and auto-merged that. Then the php-cs-fixer one was rebased -> empty.
