### ISSUE TITLE
Renovate is not assigning an AzureWorkItem to PR's

### ISSUE THREAD

**Issue by JackRhodes** [renovatebot/renovate#14872]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.6.13

### Please select which platform you are using if self-hosting.

Azure DevOps (dev.azure.com) (I cannot find a way to see a specific version number)

### If you're self-hosting Renovate, tell us what version of the platform you run.

The current version of dev.azure.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I am trying to use the AzureWorkItem environment variable ` RENOVATE_AZURE_WORK_ITEM_ID: 76617` to set the work item on PRs to the given Id, however, it is not adding it. I can see the config being merged correctly in the debug log (added to this report), and I believe the PAT should have the correct permissions.

I have tried the following:

* Mapping it via the cli, 
* Editing a repo's `renovate.json` and adding the json field

![image](https://user-images.githubusercontent.com/23398170/160882300-db7cbcec-61b4-468a-be47-c1dfab4b1296.png)

![image](https://user-images.githubusercontent.com/23398170/160882448-7d418425-cfe9-4110-9c0d-e74b15e839a4.png)

Please let me know if you need any more information or want me to try anything! I assume this is a configuration issue on my side, I am happy to update docs once we solve this.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "hostRules": [
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "token": "***********",
         "azureWorkItemId": 76617
       }
DEBUG: Combined config
       "config": {
         "platform": "azure",
         "endpoint": "[https://dev.azure.com/<redacted>/",](https://dev.azure.com/<redacted>/%22,)
         "autodiscover": true,
         "hostRules": [
           {
             "hostType": "docker",
             "matchHost": "***",
             "username": "***",
             "password": "***********"
           },
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "token": "***********",
         "azureWorkItemId": 76617
       }

```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
If it's configured then we pass it through with PR creation: https://github.com/renovatebot/renovate/blob/891bcd996097c20ed5e8c99dcb38cb4bdb9ed510/lib/modules/platform/azure/index.ts#L412-L427

Note: this means that you need to test with *newly created* PRs, and do not expect Renovate to add it to any existing ones.

If Azure is silently rejecting or ignoring it, there's not too much we can do.

**Comment by JackRhodes** [comment]
Thanks for the quick response

I've tested today, I made my renovate user PAT have full access to try and eliminate any access problems but it's still not working on newly created Pull Requests.

I had a quick look at the [Azure PR Create docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/create?view=azure-devops-rest-6.0), the only thing I can see is that Renovate code does add a Url field in the work item [ResourceRef](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/create?view=azure-devops-rest-6.0#resourceref) object, only the id.

I am going to try and clone renovate and add this field in to see if it makes a difference.

**Comment by rarkins** [comment]
I don't use Azure myself and I'm not sure how many Azure users have tried this. There's some possibility it doesn't work for anyone, but I hope not. @JamieMagee I see you wrote this, are you still using it anywhere?

**Comment by JackRhodes** [comment]
Quick update:

I tried playing around with Renovate locally and did some research into the node library Renovate uses for ado: https://github.com/microsoft/azure-devops-node-api

I decided to try the following:

1) Manually reference the work item on a Renovate Created PR
2) Try to find other places the ADO api uses work item references. I found a place where the API returns the same object as the one created in the above code snippet. I will elaborate below

I added the following code to the updatePr function (forgive my bad TS, I'm not a node developer :joy: )

```
const pr = await azureApiGit.getPullRequestById(prNo, config.project);
  logger.info(`Receivied response ${JSON.stringify(pr)}`)

  if(pr.workItemRefs) {

    for(const v of pr.workItemRefs) {
      logger.info(`PR work items: Id: ${v.id} Url: ${v.url}`)
    }
  }
  else {
    logger.info("no work items found")
  }
```

This endpoint returns the [ResourceRef](https://github.com/microsoft/azure-devops-node-api/blob/master/api/interfaces/GitInterfaces.ts#L1694) object. This is the same object sent in the PR creation call in the code snippet linked earlier.

Unfortunately, it seems that workItems was not included in the response.

This leads me to believe there's either an issue in the node library, or potentially in the setup of my user. I will create an issue in the node library to see if the maintainers may understand why. If I find anything useful, I will share my findings here and look to either make a code contribution or update the azure setup docs if it's a configuration issue.

**Comment by JamieMagee** [comment]
I'm not using this functionality on my current team, but I configured it for a previous team, and I was able to confirm that it's still working with Renovate `32.10.2`

@JackRhodes Are you able to manually link that work item to a pull request?

**Comment by JackRhodes** [comment]
@JamieMagee   - I just tested this again, it seems I had tested adding a work item to a PR from my personal user and not the renvoate user :facepalm: The renovate user is able to search for the work item in the "add work item" box, but when I try to save it errors.

It seems that the Renovate ADO User I had setup did not have project contribution group assigned to it, instead - I had given it read only access to the work items and contribution to all azure repositories. My (incorrect) assumption was that it would only need to read work items. Giving the user write contribution to work items seems to fix the issue. I guess "under the hood" ADO edits the work item to associate the relationship rather than just adding something on the PR's side.

I have tested running this from Renovate and it works fine as normal.

@rarkins Would you be ok with me making  a PR to add the correct minimal permissions to the [ADO docs page](https://github.com/renovatebot/renovate/blob/main/docs/usage/setup-azure-devops.md)? 

Thank you both for your help, I really appreciate that you've tried to help me with this rather than closing the issue and dismissing as something not in your control :bow:

**Comment by rarkins** [comment]
@JackRhodes some improved docs would be greatly appreciated. Obviously describing the permissions required in full detail should hopefully be enough to help future users, but potentially also anything you learned about how to test/debug it manually if there's a problem.
