### ISSUE TITLE
HTTP Basic Authentication with Private Composer Repositories Non-Functional

### ISSUE THREAD

**Issue by xaecors** [renovatebot/renovate#14903]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We are in the process of testing migrating from dependabot to renovate on all our repositories but have ran into an issue where it appears that renovate is not passing the necessary basic authentication credentials to private repositories hosted on packagist.com thus causing it to fail.

Our `hostRules` configuration is as follows:

```json
{
    "hostRules": [
        {
            "hostType": "packagist",
            "matchHost": "repo.packagist.com",
            "username": "token",
            "encrypted": {
                "password": "<redacted>"
            },
            "authType": "Basic"
        }
    ]
}
```

We've attempted different permutations of `matchHost` including `https://repo.packagist.com/` and `https://repo.packagist.com/company`. We know the credentials being provided are correct as we're using them with current deployment pipelines and it is HTTP Basic Authentication, not a Bearer token.

**Note:** As these repositories are corporate owned and restricted, I cannot provide a working public example.

### Relevant debug logs

<details><summary>Logs</summary>

```
<details><summary>Logs</summary>

```
DEBUG: Executing command(branch="renovate/pin-dependencies")
{
  "command": "docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/redacted/redacted-com\":\"/mnt/renovate/gh/redacted/redacted-com\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/redacted/redacted-com\" docker.io/renovate/php bash -l -c \"install-tool composer 2.3.2 && composer update ergebnis/composer-normalize markshust/magento2-module-disabletwofactorauth shipperhq/module-shipper taxjar/module-taxjar --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\""
}
DEBUG: rawExec err(branch="renovate/pin-dependencies")
{
  "err": {
    "killed": false,
    "code": 255,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/redacted/redacted-com\":\"/mnt/renovate/gh/redacted/redacted-com\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/redacted/redacted-com\" docker.io/renovate/php bash -l -c \"install-tool composer 2.3.2 && composer update ergebnis/composer-normalize markshust/magento2-module-disabletwofactorauth shipperhq/module-shipper taxjar/module-taxjar --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"",
    "stdout": "Installing legacy tool composer v2.3.2\nComposer 2.3.2 2022-03-30 20:45:25\n",
    "stderr": "Loading composer repositories with package information\nWarning from repo.packagist.com: \n======================\nAUTHENTICATION FAILURE\nUsername and authentication token required, see https://packagist.com/profile/auth - this is not your regular password\n======================\n\n\nIn AuthHelper.php line 194:\n                                                                               \n  The 'https://repo.packagist.com/redacted/packages.json' URL require  \n  d authentication.                                                            \n  You must be using the interactive console to authenticate                    \n                                                                               \n\nupdate [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]\n\n",
    "message": "Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/redacted/redacted-com\":\"/mnt/renovate/gh/redacted/redacted-com\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/redacted/redacted-com\" docker.io/renovate/php bash -l -c \"install-tool composer 2.3.2 && composer update ergebnis/composer-normalize markshust/magento2-module-disabletwofactorauth shipperhq/module-shipper taxjar/module-taxjar --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\nLoading composer repositories with package information\nWarning from repo.packagist.com: \n======================\nAUTHENTICATION FAILURE\nUsername and authentication token required, see https://packagist.com/profile/auth - this is not your regular password\n======================\n\n\nIn AuthHelper.php line 194:\n                                                                               \n  The 'https://repo.packagist.com/redacted/packages.json' URL require  \n  d authentication.                                                            \n  You must be using the interactive console to authenticate                    \n                                                                               \n\nupdate [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]\n\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/redacted/redacted-com\":\"/mnt/renovate/gh/redacted/redacted-com\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/redacted/redacted-com\" docker.io/renovate/php bash -l -c \"install-tool composer 2.3.2 && composer update ergebnis/composer-normalize markshust/magento2-module-disabletwofactorauth shipperhq/module-shipper taxjar/module-taxjar --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\nLoading composer repositories with package information\nWarning from repo.packagist.com: \n======================\nAUTHENTICATION FAILURE\nUsername and authentication token required, see https://packagist.com/profile/auth - this is not your regular password\n======================\n\n\nIn AuthHelper.php line 194:\n                                                                               \n  The 'https://repo.packagist.com/redacted/packages.json' URL require  \n  d authentication.                                                            \n  You must be using the interactive console to authenticate                    \n                                                                               \n\nupdate [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]\n\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)"
  }
}
DEBUG: Failed to generate composer.lock(branch="renovate/pin-dependencies")
{
  "err": {
    "killed": false,
    "code": 255,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/redacted/redacted-com\":\"/mnt/renovate/gh/redacted/redacted-com\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/redacted/redacted-com\" docker.io/renovate/php bash -l -c \"install-tool composer 2.3.2 && composer update ergebnis/composer-normalize markshust/magento2-module-disabletwofactorauth shipperhq/module-shipper taxjar/module-taxjar --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"",
    "stdout": "Installing legacy tool composer v2.3.2\nComposer 2.3.2 2022-03-30 20:45:25\n",
    "stderr": "Loading composer repositories with package information\nWarning from repo.packagist.com: \n======================\nAUTHENTICATION FAILURE\nUsername and authentication token required, see https://packagist.com/profile/auth - this is not your regular password\n======================\n\n\nIn AuthHelper.php line 194:\n                                                                               \n  The 'https://repo.packagist.com/redacted/packages.json' URL require  \n  d authentication.                                                            \n  You must be using the interactive console to authenticate                    \n                                                                               \n\nupdate [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]\n\n",
    "message": "Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/redacted/redacted-com\":\"/mnt/renovate/gh/redacted/redacted-com\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/redacted/redacted-com\" docker.io/renovate/php bash -l -c \"install-tool composer 2.3.2 && composer update ergebnis/composer-normalize markshust/magento2-module-disabletwofactorauth shipperhq/module-shipper taxjar/module-taxjar --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\nLoading composer repositories with package information\nWarning from repo.packagist.com: \n======================\nAUTHENTICATION FAILURE\nUsername and authentication token required, see https://packagist.com/profile/auth - this is not your regular password\n======================\n\n\nIn AuthHelper.php line 194:\n                                                                               \n  The 'https://repo.packagist.com/redacted/packages.json' URL require  \n  d authentication.                                                            \n  You must be using the interactive console to authenticate                    \n                                                                               \n\nupdate [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]\n\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_php --label=renovate_child -v \"/mnt/renovate/gh/redacted/redacted-com\":\"/mnt/renovate/gh/redacted/redacted-com\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e COMPOSER_CACHE_DIR -e COMPOSER_AUTH -w \"/mnt/renovate/gh/redacted/redacted-com\" docker.io/renovate/php bash -l -c \"install-tool composer 2.3.2 && composer update ergebnis/composer-normalize markshust/magento2-module-disabletwofactorauth shipperhq/module-shipper taxjar/module-taxjar --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader --no-plugins\"\nLoading composer repositories with package information\nWarning from repo.packagist.com: \n======================\nAUTHENTICATION FAILURE\nUsername and authentication token required, see https://packagist.com/profile/auth - this is not your regular password\n======================\n\n\nIn AuthHelper.php line 194:\n                                                                               \n  The 'https://repo.packagist.com/redacted/packages.json' URL require  \n  d authentication.                                                            \n  You must be using the interactive console to authenticate                    \n                                                                               \n\nupdate [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]\n\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)"
  }
}
```

</details>

```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
you probably need to set `hostType=packagist`

**Comment by xaecors** [comment]
We've attempted at as well, same exact result.

**Comment by xaecors** [comment]
We have opted to utilize renovate via a GitHub action instead where the issue with COMPOSER_AUTH does not exist. We'll keep an eye out and hope that the GitHub App eventually resolves the impediment.
