### ISSUE TITLE
Upgrade indirect dependencies with yarn

### ISSUE THREAD

**Issue by Tofandel** [renovatebot/renovate#14908]
### What would you like Renovate to be able to do?

When using pinned versions with lock file maintenance, dependencies of dependencies don't get automatically upgraded, resulting in old dependencies with security issues not upgrading forever until we upgrade them manually, get an update of the root dependency or delete the lock file, this is because of https://github.com/yarnpkg/yarn/issues/4986

It would be nice if there could be a separate PR created by renovate bot to upgrade only the lock file with the peer deps 

### If you have any ideas on how this should be implemented, please tell us here.

`yarn upgrade --latest` upgrades peer deps correctly locally

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by Tofandel** [comment]
Reproduction: https://github.com/Tofandel/renovate-bug

Look in https://github.com/Tofandel/renovate-bug/blob/main/yarn.lock#L4598, you'll see webpack is still at version 5.68.0 but the new version is 5.71.0 I'd expect a PR which only updates the lockfile with this new version

**Comment by viceice** [comment]
isn't this an option for you?
- https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
- https://docs.renovatebot.com/faq/#keep-lock-files-including-sub-dependencies-up-to-date-even-when-packagejson-hasnt-changed

**Comment by Tofandel** [comment]
Mmm seems it works with github with the schedule, if schedule is not set will this still run once per week? It doesn't seem to happen ever on my gitlab

**Comment by rarkins** [comment]
If you have 500 transitive dependencies and all are out of date then you want 500 PRs?

**Comment by Tofandel** [comment]
No definitely not I want just one and in fact it seems it works with schedule on github https://github.com/Tofandel/renovate-bug/pull/4 but I'm trying to find out why it doesn't on gitlab now

**Comment by Tofandel** [comment]
Ok seems it does, sorry for the noise
