### ISSUE TITLE
Cargo (Rust) with private git (GitHub) dependencies results in `Artifact update problem`

### ISSUE THREAD

**Issue by mettke** [renovatebot/renovate#14939]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate pushes the following comment to our PR. The problem is that the dynaql repo is private and its defined in the `Cargo.toml` using `async-graphql = { git = "ssh://git@github.com/grafbase/dynaql.git", branch = "main" }`. The renovate user has read permissions to both repositories. Potentially related: https://github.com/renovatebot/renovate/discussions/14571:

### ⚠ Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻ Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you click the rebase/retry checkbox if found above, or
 - you rename this PR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: Cargo.lock

```
Command failed: docker run --rm --name=renovate_rust --label=renovate_child -v "/mnt/renovate/gh/grafbase/api":"/mnt/renovate/gh/grafbase/api" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -w "/mnt/renovate/gh/grafbase/api" docker.io/renovate/rust bash -l -c "cargo update --manifest-path lambda/send-registration-invite/Cargo.toml --workspace"
    Updating git repository `https://github.com/Miaxos/aws-lambda-events`
    Updating git repository `https://github.com/grafbase/rust-coarsetime`
    Updating git repository `https://github.com/grafbase/rusoto`
    Updating git submodule `https://github.com/boto/botocore.git`
    Updating crates.io index
    Updating git repository `https://github.com/softprops/dynomite.git`
    Updating git repository `https://github.com/grafbase/rust-jwt-simple.git`
    Updating git repository `ssh://git@github.com/grafbase/dynaql.git`
error: failed to get `async-graphql` as a dependency of package `gateway v0.1.0 (/mnt/renovate/gh/grafbase/api/workers/gateway)`

Caused by:
  failed to load source for dependency `async-graphql`

Caused by:
  Unable to update ssh://git@github.com/grafbase/dynaql.git?branch=main#1ec8751d

Caused by:
  failed to clone into: /home/ubuntu/.cargo/git/db/dynaql-282a33edd18efb28

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'ssh://git@github.com/grafbase/dynaql.git' '+refs/heads/main:refs/remotes/origin/main'` (exit status: 128)
  --- stderr
  Host key verification failed.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

```

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: artifactErrors(branch="renovate-dependencies-non-major")
{
  "artifactErrors": [
    {
      "lockFile": "Cargo.lock",
      "stderr": "Command failed: docker run --rm --name=renovate_rust --label=renovate_child -v \"/mnt/renovate/gh/grafbase/api\":\"/mnt/renovate/gh/grafbase/api\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gh/grafbase/api\" docker.io/renovate/rust bash -l -c \"cargo update --manifest-path lambda/send-registration-invite/Cargo.toml --workspace\"\n    Updating git repository `https://github.com/Miaxos/aws-lambda-events`\n    Updating git repository `https://github.com/grafbase/rust-coarsetime`\n    Updating git repository `https://github.com/grafbase/rusoto`\n    Updating git submodule `https://github.com/boto/botocore.git`\n    Updating crates.io index\n    Updating git repository `https://github.com/softprops/dynomite.git`\n    Updating git repository `https://github.com/grafbase/rust-jwt-simple.git`\n    Updating git repository `ssh://git@github.com/grafbase/dynaql.git`\nerror: failed to get `async-graphql` as a dependency of package `gateway v0.1.0 (/mnt/renovate/gh/grafbase/api/workers/gateway)`\n\nCaused by:\n  failed to load source for dependency `async-graphql`\n\nCaused by:\n  Unable to update ssh://git@github.com/grafbase/dynaql.git?branch=main#1ec8751d\n\nCaused by:\n  failed to clone into: /home/ubuntu/.cargo/git/db/dynaql-282a33edd18efb28\n\nCaused by:\n  process didn't exit successfully: `git fetch --force --update-head-ok 'ssh://git@github.com/grafbase/dynaql.git' '+refs/heads/main:refs/remotes/origin/main'` (exit status: 128)\n  --- stderr\n  Host key verification failed.\n  fatal: Could not read from remote repository.\n\n  Please make sure you have the correct access rights\n  and the repository exists.\n"
    }
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
GitHub apps have no SSH access/permissions, so with your current approach in `Cargo.toml` this is likely not possible. You would need to refactor your references to be accessible over https, which we can use authentication for, and then hopefully our existing git auth approaches can be used: https://github.com/renovatebot/renovate/blob/5723be1ac5c776cff5c549457bd3cc238c54b5cf/lib/util/git/auth.ts

This is a Cargo-specific problem and not directly related to similar sounding issues you may have found for other managers.

**Comment by mettke** [comment]
Thanks for the quick response. Unfortunately using https in `Cargo.toml` is rather inconvenient as every developer needs to store github credentials on their machines. 

I'm wondering whether it would be possible to either improve `hostRules` or create another config option which allows specifying a private key. It could be encrypted by the renovate public key similar to all the other credentials and would allow users to add the public key to repositories that renovate need to access. On renovate side, all we need to do is store the ssh key under ~/.ssh/id_rsa and it would work. 

In addition other managers should be able to work with ssh out of the box too.

**Comment by rarkins** [comment]
OK, can you file a new feature request for supporting ssh keys for artifacts updating? Unless you find one which already exists. I think it would be manager agnostic.

**Comment by mettke** [comment]
Thanks. Closing in favor of https://github.com/renovatebot/renovate/issues/14955
