### ISSUE TITLE
Add support for cross-repository dependency dashboard issues

### ISSUE THREAD

**Issue by tdeekens** [renovatebot/renovate#14942]
### What would you like Renovate to be able to do?

Renovate opens very helpful "Dependency Dashboard" issues. These help to track and inform yourself about the status of blocked, pending and scheduled updates.

As an addition to repo-bound "Dependency Dashboard" issues it would be very helpful to have cross-repository "Dependency Dashboards". These could allow helping to track a subset of specified dependencies and their update status across repositories. This would be particularly useful if for instance a library used across projects needs updating or internal tools and their update status needs monitoring.

### If you have any ideas on how this should be implemented, please tell us here.

Generally, I think the list of dependency versions to track across repositories should be specified by e.g. NPM scope and or library name. The "Dependency Dashboard" issue should then be opened at a single repository which holds that Renovate config. The listing is then split and grouped by specified repository across the organisation using the library.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by HonkingGoose** [comment]
This sounds similar to a recent issue we closed:

- https://github.com/renovatebot/renovate/issues/19324

It sounds like we don't want to work on a "cross-repository dashboard" or "meta-dashboard for all repositories" feature. We already closed two similar issues.

I'll let @rarkins decide what do to with this issue.
