### ISSUE TITLE
gitLabIgnoreApprovals not working in some cases

### ISSUE THREAD

**Issue by Ristop** [renovatebot/renovate#15009]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I have the following configuration in my renovate.json:
```
"packageRules": [
    {
      "matchUpdateTypes": [
        "minor",
        "patch"
      ],
      "automergeType": "pr",
      "automerge": true,
      "gitLabAutomerge": true,
      "gitLabIgnoreApprovals": true
    }
  ]
```
So renovate should automerge passing PR-s. It does merge, when PR is pre-approved. However when it's not pre-approved, it is not getting merged and I'm seeing following error in the logs:
```
DEBUG:  Automerging #... with strategy auto (repository=..., branch=...)
DEBUG:  Gitlab API error (repository=..., branch=...)
...
"Response code 405 (Method Not Allowed)"
...
DEBUG: merge PR error (repository=..., branch=...)
...
"message": "Response code 405 (Method Not Allowed)"
...
```
So it seems that it is still requiring approval.

Looking through the code I can see that [checkAutoMerge](https://github.com/renovatebot/renovate/blob/8bd77f747b3da59cc955b2fc4ba3301bcb680ea2/lib/workers/repository/update/pr/automerge.ts#L33) just calls [platform.mergePr](https://github.com/renovatebot/renovate/blob/8bd77f747b3da59cc955b2fc4ba3301bcb680ea2/lib/modules/platform/gitlab/index.ts#L652) which doesn't call [ignoreApprovals](https://github.com/renovatebot/renovate/blob/8bd77f747b3da59cc955b2fc4ba3301bcb680ea2/lib/modules/platform/gitlab/index.ts#L498). Am I missing something here or should it also check the ignore approvals flag like [tryPrAutomerge](https://github.com/renovatebot/renovate/blob/8bd77f747b3da59cc955b2fc4ba3301bcb680ea2/lib/modules/platform/gitlab/index.ts#L517) is?

Edit: I also got it working when there is no pre-existing PR.

**Comment by hasanwhitesource** [comment]
@Ristop Can you please provide full logs and possibility a reproduction?

**Comment by mdeknowis** [comment]
Same for me, it's only working, if I set the required approvals in general to zero :-(


If I use

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "automerge": true,
  "gitLabIgnoreApprovals": true
}
```

And have approvals required

![image](https://user-images.githubusercontent.com/23213544/165235802-f47938f4-1b86-4056-8bcd-907da115c5c6.png)

the approvals are not adjusted in the fresh created MR

![image](https://user-images.githubusercontent.com/23213544/165236055-3cc7035e-9d6c-470a-b814-f0468dd3ad55.png)

and I've these logs:

```
DEBUG: Automerging #301 with strategy auto (repository=project, branch=renovate/internal)
DEBUG: Gitlab API error (repository=project, branch=renovate/internal)
       "err": {
         "name": "HTTPError",
         "code": "ERR_NON_2XX_3XX_RESPONSE",
         "timings": {
           "start": 1650954295117,
           "socket": 1650954295118,
           "lookup": 1650954295118,
           "connect": 1650954295119,
           "secureConnect": 1650954295120,
           "upload": 1650954295120,
           "response": 1650954295221,
           "end": 1650954295221,
           "phases": {
             "wait": 1,
             "dns": 0,
             "tcp": 1,
             "tls": 1,
             "request": 0,
             "firstByte": 101,
             "download": 0,
             "total": 104
           }
         },
         "message": "Response code 406 (Not Acceptable)",
         "stack": "HTTPError: Response code 406 (Not Acceptable)\n    at Request.<anonymous> (/builds/foo/renovate-bot/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/32.14.1 (https://github.com/renovatebot/renovate)",
             "authorization": "***********",
             "accept": "application/json",
             "content-type": "application/json",
             "content-length": "36",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://bar/api/v4/projects/foo%2Fdesign%2Fbar/merge_requests/301/merge",
           "hostType": "gitlab",
           "username": "",
           "password": "",
           "method": "PUT",
           "http2": false
         },
         "response": {
           "statusCode": 406,
           "statusMessage": "Not Acceptable",
           "body": {"message": "Branch cannot be merged"},
           "headers": {
             "server": "nginx",
             "date": "Tue, 26 Apr 2022 06:24:55 GMT",
             "content-type": "application/json",
             "content-length": "37",
             "connection": "close",
             "cache-control": "no-cache",
             "vary": "Origin",
             "x-content-type-options": "nosniff",
             "x-frame-options": "SAMEORIGIN",
             "x-request-id": "01G1J8PNTH0RV066YVV978YTGR",
             "x-runtime": "0.098566"
           },
           "httpVersion": "1.1"
         }
       }
```
[failing-logs.txt](https://github.com/renovatebot/renovate/files/8560497/failing-logs.txt)

**Comment by mdeknowis** [comment]
Found my solution

Had also to enable `platformAutomerge`:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "automerge": true,
  "gitLabIgnoreApprovals": true,
  "platformAutomerge": true
}
```
