### ISSUE TITLE
Go mod for private authentication doesn't work

### ISSUE THREAD

**Issue by dirk39** [renovatebot/renovate#15033]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.14

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitlab

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When I tried to run the `gomodTidy1.17` post update option, I got an error on updating dependencies from the private repository:
```
fatal: repository 'https://gitlab.com/private-group/libraries.git/' not found
```
this is my configuration on the `config.js` file:
```
module.exports = {
    autodiscover: true,
    autodiscoverFilter: "private-group/**",
    endpoint: process.env.CI_API_V4_URL,
    gitAuthor: 'Renovate Bot <bot@acme.com>',
    onboarding: true,
    prhourlylimit: 10,
    helmfile: {
        fileMatch: ["(^|/)*helmfile.yaml$"]
    },
    hostRules: [
        {
            matchHost: "github.com",
            token: process.env.GITHUB_TOKEN,
        },
        {
            matchHost: 'gitlab.com/private-group',
            hostType: 'gitlab',
            token: process.env.CI_JOB_TOKEN,
        }],
    platform: 'gitlab',
    username: 'renovate-bot',
};
```
I've followed the issues #12912 and #13214, but the problem persists.
Looking into the debug logs, I've noticed this: 
```
DEBUG: Adding token authentication for github.com to hostRules
DEBUG: Adding token authentication for gitlab.com/private-group to hostRules
DEBUG: Adding token authentication for gitlab.com to hostRules
```
I don't know who set the third hostRules and if it may impact the `go mod tidy`.

Thanks.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: rawExec err (repository=private-group/services/private-repo, branch=renovate/github.com-streadway-amqp-1.x)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "docker run --rm --name=renovate_go --label=renovate_child -v \"/builds/private-group/renovate-gitlab-bot/renovate/repos/gitlab/private-group/services/private-repo\":\"/builds/private-group/renovate-gitlab-bot/renovate/repos/gitlab/private-group/services/private-repo\" -v \"/builds/private-group/renovate-gitlab-bot/renovate/cache\":\"/builds/private-group/renovate-gitlab-bot/renovate/cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e GIT_CONFIG_KEY_3 -e GIT_CONFIG_VALUE_3 -e GIT_CONFIG_KEY_4 -e GIT_CONFIG_VALUE_4 -e GIT_CONFIG_KEY_5 -e GIT_CONFIG_VALUE_5 -e GIT_CONFIG_KEY_6 -e GIT_CONFIG_VALUE_6 -e GIT_CONFIG_KEY_7 -e GIT_CONFIG_VALUE_7 -e GIT_CONFIG_KEY_8 -e GIT_CONFIG_VALUE_8 -e GIT_CONFIG_KEY_9 -e GIT_CONFIG_VALUE_9 -e GIT_CONFIG_KEY_10 -e GIT_CONFIG_VALUE_10 -e GIT_CONFIG_KEY_11 -e GIT_CONFIG_VALUE_11 -w \"/builds/private-group/renovate-gitlab-bot/renovate/repos/gitlab/private-group/services/private-repo\" docker.io/renovate/go:1.18.0 bash -l -c \"go get -d -t ./...\"",
         "stdout": "",
         "stderr": "go: gitlab.com/private-group/libraries/go-private-group@v0.0.0-20220221125806-683b37220146: invalid version: git ls-remote -q origin in /builds/private-group/renovate-gitlab-bot/renovate/cache/others/go/pkg/mod/cache/vcs/e9048582372bf173bc94c080849d87713a0b20bdd3e2e3a3def6aa2aeb478f26: exit status 128:\n\tremote: The project you were looking for could not be found or you don't have permission to view it.\n\tfatal: repository 'https://gitlab.com/private-group/libraries.git/' not found\n",
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment]
This issue looks really similar to yours:

- https://github.com/renovatebot/renovate/issues/3496

I'll let the maintainer check if this is a duplicate of the older issue. 😉

**Comment by rarkins** [comment]
I'm not sure it gets this working, but your matchHost should start with https:// of you include any path with it. As of now, it's not a valid value.

Next question, are you familiar enough with Go to describe how you think Renovate should be able to pass these credentials to the go command?

**Comment by dirk39** [comment]
Hello @rarkins @HonkingGoose thank you for the quick answer. Looking into https://github.com/renovatebot/renovate/blob/5723be1ac5c776cff5c549457bd3cc238c54b5cf/lib/util/git/auth.ts#L82-L103 seems possible to pass the `matchHost` without `https://`. Currently, I was able to work around using the non-dind version and the `.netrc` file.

**Comment by viceice** [comment]
matchHost needs to be a domain name only or a full qualified URL

**Comment by rarkins** [comment]
@dirk39 you misunderstood the code. For anyone in future reading this, please ignore this example because it is wrong

**Comment by dirk39** [comment]
@rarkins Sorry for the mistake. I am trying with the domain name and the full qualified URL, but it is still not working.

**Comment by Shegox** [comment]
Looking at that renovate should normally use each matching host Rule as well as already existing git configuration to set `GIT_CONFIG_KEY`. Looking at the logs and that there is 11 values (`-e GIT_CONFIG_KEY_11 -e GIT_CONFIG_VALUE_11`) passed through to the go-container, I assume that maybe there are multiple git configs for gitlab.com included which then overlap each other. Maybe a GIT_CONFIG is used, which doesn't have a valid/the right token to access the repository.

**Comment by phumberdroz** [comment]
[This is ](https://gist.github.com/MicahParks/1ba2b19c39d1e5fccc3e892837b10e21)what I use for go modules authentication. This also works with nested repos. 

The current issue happens when you repo is not under the initial path:
gitlab.com/some-company/libraries/common
Go modules looks up gitlab.com/some-company/libraries.git which does not exist it then does not try further to figure out if it could be gitlab.com/some-company/libraries/common.git 

this can be solved by using a .netrc file in the container that is executing `go mod tidy` 


There is two things that could help me in particular here let me mount any file into a docker image that runs via self hosted configuration or write / create the .netrc file for me via the configuration file.

**Comment by uhthomas** [comment]
Dupe of #17923?

**Comment by phumberdroz** [comment]
@uhthomas no the linked issue seems unrelated. Or at least I am not seeing the relation.

**Comment by icedream** [comment]
I want to push this issue as I would like to clarify a few things.

Go has its own import path resolving process for import paths without a VCS qualifier (that is paths that don't end in `.bzr`, `.fossil`, `.git`, `.hg`, `.svn`): It asks via `https://<importpath>?go-get=1` for the actual repository URL to later clone from (e. g. `gitlab.com/group/subgroup/project` would mean Go asks `https://gitlab.com/group/subgroup/project?go-get=1` for the actual import path). Up until this point neither Git (or `.gitconfig`) nor SSH (or `.ssh/config`) are even remotely involved. See [this documentation section](https://go.dev/ref/mod#vcs-find) for more information on that.

For this part of the resolving process Go will solely consider a `.netrc` file to fetch the username and password needed to authenticate against a private repository with HTTP Basic Auth. see [this documentation section](https://go.dev/ref/mod#private-module-repo-auth) for more information on that.

My suggestion would be for Renovate to either prepare or forward a `.netrc` file based on credentials known to Renovate and expose it to Go via the `NETRC` environment variable, ideally just for dependencies without explicit VCS qualifiers. Also note that `.netrc` files are limited to syntax like this:

```
machine example.com
login username_here
password password_here

machine ...
login ...
password ...
```

No paths or schemes are supported in place of the hostname for the `machine` keyword.

**Comment by icedream** [comment]
I am also currently figuring out how a reproduction would need to be set up for this as it requires a private repository, on GitLab specifically to be set up with an access token that can be used for private access.
