### ISSUE TITLE
Rewrite `regex` manager docs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15075]
### Describe the proposed change(s).

While reviewing PR #15067 I found the [`regex` manager](https://docs.renovatebot.com/modules/manager/regex/) docs hard to understand. The document needs a rewrite.

To do:

- [x] Rewrite to follow plain language guidelines
- [x] Shorten sentences
- [x] Use readable link names #18841 
- [ ] Split the massive list into sections that are logically grouped together
- [ ] Explain possible values for each field, try out table for `field`/`template`/`required|default`/`description`/`values`

**Comment by TWiStErRob** [comment]
Can you please add the issue as task about original context behind https://github.com/renovatebot/renovate/pull/15067? i.e. make it clear what are the possible values for each field. I have a feeling a table of `field`/`template`/`required|default`/`description`/`values` might be a way.
