### ISSUE TITLE
Extend repository result to differentiate between onboarded and active

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#15112]
### What would you like Renovate to be able to do?

Distinguish in its repo stats whether a repo is onboarded versus it has merged at least one Renovate PR.

### If you have any ideas on how this should be implemented, please tell us here.

Augment this: https://github.com/renovatebot/renovate/blob/ee582fe0e7c06e8c2a1d056cb280e8558dab30d8/lib/workers/repository/result.ts#L22

Propose splitting 'enabled' into 'onboarded' and 'active'.

We should determine whether a repo is 'active' based on whether there exists at least one merged PR by Renovate. I think there's an edge case if someone only uses branch automerge but I'm willing to live with that.

Hopefully this can be achieved using `platform.getPrList().some(pr => pr.state === PrState.Merged)`

### Is this a feature you are interested in implementing yourself?

No

**Comment by MaronHatoum** [comment]
Hi @rarkins 
Maybe we can add this log msg to the log if we have this data (created, merged):
```
{
	"level": 20,
	"msg": "fist update pr merged",
	"pr_details": {
		"created": "",
		"merged": "",
		"link": ""
	},
	"time": "2022-04-13T10:41:44.564Z"
}
```
and then we can parse the log and check if it is relevant.
