### ISSUE TITLE
renovate hammers after failed build

### ISSUE THREAD

**Issue by Morriz** [renovatebot/renovate#15127]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

We suddenly started to see a lot of failed renovate build errors. I have email notifications for failed runs and never saw anything from renovate, but now it clogged up our whole pipeline with too many failed runs, one every hour. Does your service not protect us from hammering?? Please maintain sanity for our sakes and have a backoff strategy.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment]
I think you're angry at us for getting something wrong, but that's no good reason to post passive-aggressive messages like this:

> Does your service not protect us from hammering?? Please maintain sanity for our sakes and have a backoff strategy.

Please stop posting messages like these. Read [our behavior guidelines](https://github.com/renovatebot/renovate/blob/main/docs/development/behavior.md) before you reply.

We need more information from you before we can triage this possible bug. Can you copy/paste the log output from a recent Renovate run where it "hammers" your repository? [Docs on getting the logs](https://docs.renovatebot.com/troubleshooting/#getting-the-logs). Remember to remove any private information.

If you can create a [minimal reproduction](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) that would be even better!

**Comment by rarkins** [comment]
There's not enough info provided here to answer you. We can help you if you're polite, otherwise please uninstall and we all move on.

**Comment by Morriz** [comment]
I'm sorry about that, I just saw pages of actions in red by renovate. It was an action running every hour as a cronjob. So no state was kept anywhere. Not an error on the renovate end. Sorry about my assumption. It was probably a remnant of trying to get the service to work with all the github security limitations.
