### ISSUE TITLE
edge & chrome display  '<br />'  within pull request (at least onboarding PR)

### ISSUE THREAD

**Issue by tbugfinder** [renovatebot/renovate#15158]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest/main

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

7.6.x

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The onboarding pull request displays the tag  '<br />'  in edge and chrome.

I'd assume it should be properly processed by the browser.

https://github.com/renovatebot/renovate/blob/main/lib/workers/repository/onboarding/pr/pr-list.ts#L68

```html
Branch name: `renovate/lock-file-maintenance`\n  - Merge into: `master`\n  - Regenerate lock files to use latest dependency versions\n\n\n\n<br />\n\n🚸 Branch creation will 
```

### Relevant debug logs

Browser Source Code:

```html
Branch name: `renovate/lock-file-maintenance`\n  - Merge into: `master`\n  - Regenerate lock files to use latest dependency versions\n\n\n\n<br />\n\n🚸 Branch creation will 
```

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by tbugfinder** [comment]
Removing '<br />' seems to be a valid approach for me :.-)

**Comment by tbugfinder** [comment]
Not sure why/if a reproduction repo really makes sense, you can use any repo you like.

**Comment by tbugfinder** [comment]
Unfortunately I cannot share my bitbucket server. Would the html file be sufficient?
I’m going to upload that.

**Comment by rarkins** [comment]
Possible but unlikely
