### ISSUE TITLE
Log Measurement of Available API Calls Remaining

### ISSUE THREAD

**Issue by ghost** [renovatebot/renovate#1516]
This is a follow-up to #1500 in which I would like to be able to record the number of API calls remaining per SCM platform as custom measurement for collection by a system/add-on like [Librato](https://devcenter.heroku.com/articles/librato#custom-log-based-metrics).

My objective is to capture at given intervals, how many API calls remain per platform, configure threshold alerts, and receive a notification when our Renovate instance comes close to exhausting the the available API calls for a given access token.

**Comment by rarkins** [comment]
Let's log an info message at the end of each renovateRepository() that says how many calls remaining. May require a new API call in the GitHub platform and matching functions in GitLab and VSTS

**Comment by destroyerofbuilds** [comment]
> Let's log an info message

Please keep in mind that _Librato_, and likely other metric capturing platforms, are specific about the console message format, so I'm not sure if Renovate's log message format, where `INFO:` is prepended to the message, would be correctly ingested by _Librato_.

> at the end of each renovateRepository()

That seems fine.

> May require a new API call in the GitHub platform and matching functions in GitLab and VSTS

GitHub, and likely others, return back the API call count remaining as part of every response, but if a request is made specifically to get the count, then we'll probably need a dedicated method per platform to call.

**Comment by destroyerofbuilds** [comment]
This kind of feature can probably be considered an _enterprise_ feature since it's of great value to SaaS providers, and on-premise users, that want to monitor the health of their deployment.

**Comment by rarkins** [comment]
@destroyerofbuilds you can set process.env.LOG_FORMAT=json if you want something more machine-readable.

**Comment by destroyerofbuilds** [comment]
@rarkins _Librato_ adheres to the [L2met](https://r.32k.io/l2met-introduction) log spec, which expects newline deliminated console log statements like:

```bash
measure#db.latency=123
```

It doesn't ingest JSON or other formats.

**Comment by destroyerofbuilds** [comment]
> space deliminated console log statements

Maybe a simple string output from Renovate _would_ be sufficient. Something like:

```bash
INFO: measure#db.latency=123
```

**Comment by rarkins** [comment]
let's print something like `INFO: remainingApiCalls=123`. It is still human readable but also machine readable.
