### ISSUE TITLE
PR list/cache: store PR body hash, not content

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#15276]
### Describe the proposed change(s).

Today we store the full PR body in memory (`prList`) and then subsequently in our PR cache. Perhaps we can calculate a md5 or sha256 of the content and store that instead? We may need to do some basic parsing of rebase/retry checkboxes, but I can't think of anything else. Such code can be shared between platforms instead of reimplementing in each.

Perhaps this change?

```diff
diff --git a/lib/modules/platform/types.ts b/lib/modules/platform/types.ts
index b592e81c4..c050932d5 100644
--- a/lib/modules/platform/types.ts
+++ b/lib/modules/platform/types.ts
@@ -47,7 +47,8 @@ export interface RepoParams {
  *
  */
 export interface Pr {
-  body?: string;
+  bodySha?: string;
+  rebaseChecked?: boolean;
   sourceBranch: string;
   cannotMergeReason?: string; // for reflecting platform policies which may prevent merging
   createdAt?: string;
```

**Comment by viceice** [comment]
good idea

**Comment by zharinov** [comment]
Can this be closed now, isn't it?
