### ISSUE TITLE
Store PR cache in minimal/transformed form

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#15275]
### Describe the proposed change(s).

After seeing Renovate's PR cache take up 5MB+, I think I need to change my mind about storing raw vs transformed PRs in our repo PR cache.

The downside of transformed is that we potentially "lose" fields, and need them later, and then need to invalidate the entire PR cache. But maybe that's worth the trade-off of storing less.

Then it means what we need is a way to detect sometime in future when an existing cache needs refetching or transforming, without invalidating the entire repo cache by bumping `CACHE_REVISION`. I think that's possible even in this case, e.g. when we load any existing PR cache we detect if it's in raw format and if so then convert to transformed and re-save at the end of the repo run. Possibly though we now add a PR cache revision number so that we can detect such things more simply in future without invalidating the whole cache?

**Comment by viceice** [comment]
sounds good to me

**Comment by zharinov** [comment]
This part is done I guess

**Comment by rarkins** [comment]
Well, it's zipped but still "raw" form, isn't it? So I think it's more like a "won't do" rather than "done" result
