### ISSUE TITLE
Use intelligent pagination caching for datasources

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#15349]
### What would you like Renovate to be able to do?

Use intelligent pagination caching for popular datasources, especially github tags/releases and Docker tags. Then we can maybe remove pagination limits.

### If you have any ideas on how this should be implemented, please tell us here.

It should be implemented in a similar manner to how we did caching for GitHub PRs. e.g. if it's possible to sort by a last modified field then reuse the existing cache (even if "expired") and only retrieve as much as necessary on subsequent requests.

Notes:
- We may need to first adjust our cache logic so that we don't fully expire cached values and instead do a soft expiry. e.g. hard expiry can be 2x the soft expiry so there's usually enough time for us to fetch an update using cached results
- Should use our datasource cache, not repo cache

### Is this a feature you are interested in implementing yourself?

No

### Sub-issues

- [x] #15645

**Comment by zharinov** [comment]
Seems like releases/tags result can not be ordered by `updated_at` field, though default sorting looks good enough to me and smart pagination is still relevant.

**Comment by zharinov** [comment]
The approach I'm about to try:

- `github-tags`
    - Initial fetching:
        - use `ls-remote`
            - similar to `git-refs`
        - single "page"
    - Novelty fetching:
        - use GraphQL API
        - paginate
        - sort by `TAG_COMMIT_DATE`
            - approximately equivalent to `updated_at` field
- `github-releases`
    - Initial fetching:
        - Current implementation
    - Novelty:
        - Treat fresh releases as subject to change (for the first 7 days or so)
        - Fetch page by page until the first *non-fresh* has been encountered

Both caches are meant to reset after some prolonged period, maybe 24 hours or so.

**Comment by rarkins** [comment]
I'd like to see the github-tags approach with ls-remote initially. Let's test and deploy that (need to make sure it works with private repos and custom GHE endpoints too)

**Comment by zharinov** [comment]
Do we actually use `isStable` flag for `github-tags` datasource? Seems like we have an option to fetch `releaseTimestamp` via GraphQL, though still can't access `prerelease` flag on which `githubRelease.isStable` is based on.

My point is that if we only need `releaseTimestamp`s for tags, then hopefully we can obtain it from the commit info via GraphQL together with tag name and commit hash.

**Comment by zharinov** [comment]
Another 3-level design:
- fetch all tags+hashes via `ls-remote`
- query 10–100 items for timestamp via GraphQL (concurrently with the previous step using `Promise.all`)
- after this fetch novelty page-by-page of 10 items via GraphQL (tags+hashes+timestamps)

This is based on possibly wrong premise that we actually don't need timestamps for older items.

**Comment by rarkins** [comment]
We want timestamps for all. And I think isStable is important for GitHub Actions, where some actions have sometimes had pre-releases published with stable semver versions

**Comment by zharinov** [comment]
All releases have corresponding tag, but not all tags have corresponding release.
This means our current implementation doesn't guarantee `releaseTimestamp` field for every tag.
We can achieve this using GraphQL:
```graphql
refs(
  refPrefix: "refs/tags/"
  first: 10
  orderBy: {field: TAG_COMMIT_DATE, direction: DESC}
) {
  nodes {
    version:name
    target {
      ... on Commit {
        hash: oid
        releaseTimestamp: committedDate
      }
    }
  }
}
```

Still need to obtain `isStable` flag values from the `github-releases` datasource

**Comment by zharinov** [comment]
Initial fetching would have penalty on initial fetch for repos with long list of refs, but should be okay with populated cache

**Comment by rarkins** [comment]
So we couldn't detect tag deletions this way, right? Would need a periodic full fetch with cold cache?

**Comment by zharinov** [comment]
Yes, it's the problem for both releases and tags, so I think the remedy will be similar

**Comment by zharinov** [comment]
Though it can be implemented as some gradual process, i.e. check and reconcile just one page of previously stored results per run. Not sure about this for now.

**Comment by rarkins** [comment]
Does GraphQL have any "maximum 10 pages" limitation or can we use it to fetch 100 per page until we have all?

**Comment by zharinov** [comment]
I don't think it would limit us. However, unlike REST, we have to fetch pages sequentially because of cursor-based pagination mechanics.

**Comment by rarkins** [comment]
So using GraphQL the idea would be the following?

If no cache: fetch 100 per page sequentially until done.

If cache, and less than short term cache expiry time (e.g. 30 minutes), then use cache.

If cache, and short term cache expiry has been hit, then fetch 100 per page until some date limit is hit (e.g. one month). Merge any new data with old (including missing tags) and overwrite existing cache.

If long term cache expiry is hit (e.g. one week), then treat like "no cache" scenario?

Result being that we'd perform on average ~one page of fetching every 30 minutes compared to today when we do up to 10 pages every time the cache expires?

**Comment by zharinov** [comment]
Sounds good to me

**Comment by rarkins** [comment]
Does the same work for releases?

**Comment by zharinov** [comment]
Yes, hopefully it'll share common logic
