### ISSUE TITLE
Resolve dynamic deps versions in gradle

### ISSUE THREAD

**Issue by simPod** [renovatebot/renovate#15359]
### What would you like Renovate to be able to do?

In build.gradle I do this:

```groovy
apply from: rootProject.file('gradle/dependencies.gradle')

dependencies {
    annotationProcessor dep.log4jCore
}
```

gradle/dependencies.gradle:

```groovy
def versions = [
    log4j                  : '2.17.+',
]

ext.dep = [
    log4jCore              : "org.apache.logging.log4j:log4j-core:$versions.log4j",
]
```

I'd like Renovate bot to be able to pick log4j version and update it automatically.

Or is there another way to declare deps version in similar manner that Renovate supports?

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
I think you should prefer gadle versions catalog, which is already supported by renovate

https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

**Comment by rarkins** [comment]
Is there a long term reason to use gradle this way instead of v7's central dependencies file?

**Comment by simPod** [comment]
I'll certainly try to use https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

**Comment by simPod** [comment]
@viceice Does it have to be in toml? I have implemented it in groovy and Renovate onboarding says:

```
* `Failed to look up dependency log4j-core:org.apache.logging.log4j`
```

for

```groovy
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }

    versionCatalogs {
        libs {
            def log4j = '2.17.+'

            library('log4j-core', 'org.apache.logging.log4j', 'log4j-core').version(log4j)
        }
    }
}
```

**Comment by viceice** [comment]
i think we only support the toml file.

**Comment by simPod** [comment]
Are there any plans to support Groovy or Kotlin since they're the main languages people use for Gradle definitions?

**Comment by rarkins** [comment]
In short: maybe not. We certainly don't want to have to execute kotlin or groovy code just to work out what dependencies you're using when there's a simpler alternative having toml

**Comment by simPod** [comment]
Understand, will try to move to toml then. Having Renovate working is more worth than using common language/format.
BTW not sure if I overlooked it but there's not much about it in docs. E.g. Having "supports only TOML" mention might help new users.
