### ISSUE TITLE
Github security dependency PR doesn't actually upgrade the relevant package

### ISSUE THREAD

**Issue by DawidJanczak** [renovatebot/renovate#15365]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Hello!

Renovate opened a PR in our repo to upgrade `actionpack` from 6.1.5 to 6.1.5.1, however that PR doesn't actually change that lib in the Gemfile.lock. The only library that changes is unrelated `loofah`. This https://github.com/advisories/GHSA-mm33-5vfq-3mm3 is the vulnerability. I'm not sure exactly why this happens, but I do see something odd in the logs. I'm posting them below.

### Relevant debug logs

<details><summary>Logs</summary>

Notice that `fixedVersion` below points to 6.1.5, shouldn't it be 6.1.5.1? I'm not sure this is the cause, but this is the only suspicious thing I could find in the logs.

```
DEBUG: processRepo()
DEBUG: Processing 3 branches: renovate_all, renovate_lock-file-maintenance, renovate_rubygems-actionpack-vulnerability
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 99
}
DEBUG: PullRequests limit = 99
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 99
}
DEBUG: Branches limit = 99
DEBUG: Setting current branch to master(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: latest commit(branch="renovate_rubygems-actionpack-vulnerability")
{
  "branchName": "master",
  "latestCommitDate": "2022-04-29T09:34:29+02:00"
}
DEBUG: getBranchPr(renovate_rubygems-actionpack-vulnerability)(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: findPr(renovate_rubygems-actionpack-vulnerability, undefined, open)(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: getPrList success(branch="renovate_rubygems-actionpack-vulnerability")
{
  "pullsTotal": 66,
  "requestsTotal": 1,
  "apiQuotaAffected": true
}
DEBUG: Found PR #6694(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: branchExists=true(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: PR rebase requested=true(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Checking if PR has been edited(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Branch has not been modified(branch="renovate_rubygems-actionpack-vulnerability")
{
  "branchName": "renovate_rubygems-actionpack-vulnerability"
}
DEBUG: Found existing branch PR(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Checking schedule(, null)(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: No schedule defined(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Manual rebase requested via Dependency Dashboard(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Using reuseExistingBranch: false(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: bundler.updateLockedDependency: actionpack@6.1.5 -> 6.1.5.1 [Gemfile.lock](branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: bundler.updateArtifacts(Gemfile)(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Using bundler version specified in lockfile(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Using ruby version specified in .ruby-version(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Using docker to execute(branch="renovate_rubygems-actionpack-vulnerability")
{
  "image": "ruby"
}
DEBUG: Found version constraint - checking for a compatible image to use(branch="renovate_rubygems-actionpack-vulnerability")
{
  "depName": "docker.io/renovate/ruby",
  "scheme": "ruby",
  "constraint": "2.6.2"
}
DEBUG: Found compatible image version(branch="renovate_rubygems-actionpack-vulnerability")
{
  "depName": "docker.io/renovate/ruby",
  "scheme": "ruby",
  "constraint": "2.6.2",
  "version": "2.6.2"
}
DEBUG: Resolved tag constraint(branch="renovate_rubygems-actionpack-vulnerability")
{
  "image": "docker.io/renovate/ruby",
  "tagConstraint": "2.6.2",
  "tagVersioning": "ruby",
  "tag": "2.6.2"
}
DEBUG: Fetching Docker image: docker.io/renovate/ruby:2.6.2(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Finished fetching Docker image(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Executing command(branch="renovate_rubygems-actionpack-vulnerability")
{
  "command": "docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/ygt/spabreaks\":\"/mnt/renovate/gh/ygt/spabreaks\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/ygt/spabreaks\" docker.io/renovate/ruby:2.6.2 bash -l -c \"install-tool bundler 1.17.3 && ruby --version && bundler lock --update actionpack\""
}
DEBUG: exec completed(branch="renovate_rubygems-actionpack-vulnerability")
{
  "cmd": "docker run --rm --name=renovate_ruby --label=renovate_child -v \"/mnt/renovate/gh/ygt/spabreaks\":\"/mnt/renovate/gh/ygt/spabreaks\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GEM_HOME -w \"/mnt/renovate/gh/ygt/spabreaks\" docker.io/renovate/ruby:2.6.2 bash -l -c \"install-tool bundler 1.17.3 && ruby --version && bundler lock --update actionpack\"",
  "durationMs": 16666,
  "stdout": "Installing legacy tool bundler v1.17.3\nSuccessfully installed bundler-1.17.3\n1 gem installed\nBundler version 1.17.3\nruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]\nFetching gem metadata from https://rubygems.org/.........\nFetching gem metadata from https://rubygems.org/.\nResolving dependencies........\nWriting lockfile to /mnt/renovate/gh/ygt/spabreaks/Gemfile.lock\n",
  "stderr": ""
}
DEBUG: Returning updated Gemfile.lock(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Updated 1 package files(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Getting updated lock files(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Writing package.json files(branch="renovate_rubygems-actionpack-vulnerability")
{
  "packageFiles": [
    "cypress/package.json",
    "webpack/package.json"
  ]
}
DEBUG: Writing any updated package files(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Updated 1 lock files(branch="renovate_rubygems-actionpack-vulnerability")
{
  "updatedArtifacts": [
    "Gemfile.lock"
  ]
}
DEBUG: Getting comments for #6694(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Found 0 comments(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: isBranchConflicted(master, renovate_rubygems-actionpack-vulnerability)(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Setting git author name(branch="renovate_rubygems-actionpack-vulnerability")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate_rubygems-actionpack-vulnerability")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: 2 file(s) to commit(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Preparing files for committing to branch renovate_rubygems-actionpack-vulnerability(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: git commit(branch="renovate_rubygems-actionpack-vulnerability")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate_rubygems-actionpack-vulnerability",
    "commit": "7a7f41f134dbf2081b64a70f726a3bc6b5167dcd",
    "root": false,
    "summary": {
      "changes": 1,
      "insertions": 1,
      "deletions": 1
    }
  }
}
DEBUG: Pushing branch renovate_rubygems-actionpack-vulnerability(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: git push(branch="renovate_rubygems-actionpack-vulnerability")
{
  "result": {
    "pushed": [],
    "branch": {
      "local": "renovate_rubygems-actionpack-vulnerability",
      "remote": "renovate_rubygems-actionpack-vulnerability",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate_rubygems-actionpack-vulnerability"
    },
    "remoteMessages": {
      "all": []
    }
  }
}
INFO: Branch updated(branch="renovate_rubygems-actionpack-vulnerability")
{
  "commitSha": "7a7f41f134dbf2081b64a70f726a3bc6b5167dcd"
}
DEBUG: Checking if we can automerge branch(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: mergeStatus=no automerge(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Ensuring PR(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: There are 0 errors and 0 warnings(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: getBranchPr(renovate_rubygems-actionpack-vulnerability)(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: findPr(renovate_rubygems-actionpack-vulnerability, undefined, open)(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Found PR #6694(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Found existing PR(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: Processing existing PR(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: updatePr(6694, Update dependency actionpack to v6.1.5.1 [SECURITY], body)(branch="renovate_rubygems-actionpack-vulnerability")
DEBUG: PR updated(branch="renovate_rubygems-actionpack-vulnerability")
{
  "pr": 6694
}
INFO: PR updated(branch="renovate_rubygems-actionpack-vulnerability")
{
  "pr": 6694,
  "prTitle": "Update dependency actionpack to v6.1.5.1 [SECURITY]"
}
DEBUG: PR is not configured for automerge(branch="renovate_rubygems-actionpack-vulnerability")

.
.
.

DEBUG: getBranchPr(renovate_rubygems-actionpack-vulnerability)
DEBUG: findPr(renovate_rubygems-actionpack-vulnerability, undefined, open)
DEBUG: Found PR #6694
DEBUG: Closing Dependency Dashboard
DEBUG: Retrieving issueList
DEBUG: Retrieved 1 issues
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate_all",
    "renovate_lock-file-maintenance",
    "renovate_rubygems-actionpack-vulnerability"
  ],
  "renovateBranches": [
    "renovate_rubygems-actionpack-vulnerability"
  ]
}
DEBUG: remainingBranches=
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by DawidJanczak** [comment]
> Hi there,
> 
> We have found that there's a problem with the logs. Depending on which situation applies follow one, some or all of these instructions.
> 
> ### No logs at all
> If there's no log posted yet, we need you to find and copy/paste the log into the issue template.
> 
> #### Finding logs on hosted app
> Click me to read instructions
> If you use the Renovate app (GitHub):
> 
> 1. Go to the affected PR, and search for "View repository job log here"
> 2. Click on the link to go to the "WhiteSource Renovate Dashboard" and log in
> 3. You are now in the correct repository log overview screen
> 4. Copy/paste the correct log
> 5. Follow the steps in the **formatting your logs** section
> 
> #### Finding logs when self-hosting
> Click me to read instructions
> ### Insufficient logs
> Click me to read instructions
> ### Formatting your logs
> Click me to read instructions
> Please put your logs in a `<details>` and `<summary>` element like this:
> 
> ```
> <details><summary>Click me to see logs</summary>
> 
> ```
> Copy/paste any log here, between the starting and ending backticks
> ```
> 
> </details>
> ```

Logs should be visible, I cut them not to include irrelevant packages and I guess that's what's tripping the bot.

**Comment by rarkins** [comment]
Logs remain incomplete/inadequate

**Comment by DawidJanczak** [comment]
@rarkins I wouldn't want you or anyone else to take this the wrong way, but I have to admit I always find it difficult to guess which parts of the log are necessary and which are not. In this particular case I specifically posted the bit that I find likely to be the culprit. The easiest thing for me to do (and that would give you the full picture) would be to post everything, but that's exactly what the instructions on a new issue say **not** to do. I would appreciate any pointers as to which sections would be helpful to debug this.

**Comment by rarkins** [comment]
I think this hopefully is reasonable:
- Always feel free to post the full log to a gist and link to it
- Try to highlight the important logs into the issue itself

In this case you've raised an issue saying that "Renovate is not creating a branch properly" but then included zero of the logs where Renovate actually creates or updates the branch in question. Do this:

1. Use the rebase/retry checkbox to get Renovate to call `bundler` again (likely it has the same problem as before)
2. Check the new log for instances of `renovate_rubygems-actionpack-vulnerability` and you'll find maybe 20-30 log messages when the branch is being updated

In addition, I hope that the concept of a reproduction repo is explained adequately in the doc linked to above.

**Comment by DawidJanczak** [comment]
Thank you @rarkins, I have updated the logs above with lines mentioning the branch. I'll also try to find some time this weekend of beginning of next week to create a reproduction repo.

Have a nice weekend!

**Comment by rarkins** [comment]
Based on the log, we can see Renovate ran `bundler lock --update actionpack`. The stdout does not give any indication as to why that failed:

```
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies........
Writing lockfile to /mnt/renovate/gh/ygt/spabreaks/Gemfile.lock
```

Therefore a reproduction repository would be needed to try to debug further.

**Comment by DawidJanczak** [comment]
I think that's actually enough to figure out what's wrong, I should have realised this sooner. It looks like whenever a Rails gem is to be updated they all have to be updated in batch. We have the following defined in Gemfile:
```
gem 'actionmailer'
gem 'actionpack'
gem 'activemodel'
gem 'activerecord'
gem 'activesupport'
```
Updating any of these _alone_ doesn't work, they all have to be updated at the same time. So running `bundler lock --update actionpack` won't do anything (apart from updating its dependency, like it did with `loofah` for us). We'd have to run `bundler lock --update actionmailer actionpack activemodel activerecord activesupport railties`.

This is something that's very specific to Rails and as such I'm not sure if you want to handle it. If you do you'd essentially have to scan the `Gemfile` for all Rails gems (that's the ones mentioned here https://github.com/rails/rails#frameworks-and-libraries + `rails` + `railties`) and update all of them whenever a single one needs updating.

If you don't want to handle it it might be worth adding a note somewhere in the docs about this Rails-specific behaviour.

Thanks for looking into this!

**Comment by rarkins** [comment]
Thanks for helping clarify! We should ideally find a place for this explanation/disclaimer to live.

**Comment by HonkingGoose** [comment]
I created a new `group:rubyOnRails` preset, which is also in the `config:recommended` preset.

Does having the new group preset make the security update PR work properly?

**Comment by rarkins** [comment]
Renovate ran `bundler lock --update actionpack`.

Was actionpack in your Gemfile too or just Gemfile.lock?

**Comment by DawidJanczak** [comment]
It's present in both Gemfile and Gemfile.lock, assuming this was a question for me :)

**Comment by rarkins** [comment]
I think to get any further we'll need a reproduction repo we can debug.

**Comment by DawidJanczak** [comment]
I think that preset works! A PR from reproduction repository https://github.com/DawidJanczak/rails-renovate/pull/2/files

**Comment by HonkingGoose** [comment]
@rarkins Do you still want a reproduction to confirm that the "new" Ruby on Rails group preset fixed the problem?

Copy/paste of the current contents of the `group:rubyOnRails` preset:

```json
{
  "packageRules": [
    {
      "groupName": "Ruby on Rails packages",
      "matchDatasources": [
        "rubygems"
      ],
      "matchPackageNames": [
        "actioncable",
        "actionmailbox",
        "actionmailer",
        "actionpack",
        "actiontext",
        "actionview",
        "activejob",
        "activemodel",
        "activerecord",
        "activestorage",
        "activesupport",
        "railties",
        "rails"
      ]
    }
  ]
}
```
