### ISSUE TITLE
Line-endings

### ISSUE THREAD

**Issue by ghost** [renovatebot/renovate#1541]
During some debugging I came across an instance where Renovate submitted a lockfile maintenance PR in which the new content for `yarn.lock` looked identical to the original content.

![line-endings](https://user-images.githubusercontent.com/10657293/36452146-f564c4ba-1658-11e8-91d1-8cb7da1e0cc0.png)

What is happening is the original `yarn.lock` file is getting written to the repository using the line-ending settings in the user's global `.gitconfig` file, or the project's local `.gitattributes` file, but Renovate is using the line-endings of the operating system on which is was executed.

If the settings in `.gitconfig`, or `.gitattributes`, or the operating system on which the original `yarn.lock` was created, do not agree with the same settings of the operating system on which Renovate was run, then you get these weird cases where a PR is opened just to adjust the line-endings.

**Comment by rarkins** [comment]
This will be a problem unless all users have consistent line endings, or all users including Renovate run on the same OS. 

e.g. you presumably don't want users flapping the entire contents of `yarn.lock` due to line endings even when there is some change to be made. 

In that case, isn't `.gitattributes` the best approach if you want Renovate to participate correctly? I guess we could try to autodetect the line endings in each file we edit, assuming it's not possible that there would be mixed line endings?

**Comment by rarkins** [comment]
I guess this could be used: https://www.npmjs.com/package/detect-newline as part of any solution.

**Comment by destroyerofbuilds** [comment]
> This will be a problem unless all users have consistent line endings, or all users including Renovate run on the same OS.

Renovate was executed on Windows, which caused a `yarn.lock` file to be generated containing `CRLF` line-endings, while the file on GitHub had `LF` line-endings. 

Though the _solution_ in this situation was to not run Renovate on Windows, long-term it had me wondering about developers writing files to git containing `CRLF` line-endings, while Renovate was upgrading those files using `LF` line-endings from a Linux box.

_I have not technically tried that, but I assume it would cause the same issue reported here_

> you presumably don't want users flapping the entire contents of yarn.lock due to line endings even when there is some change to be made.

In general I would not want that.

Short-term, comparing contents after stripping newlines would avoid this edge case.

> In that case, isn't .gitattributes the best approach if you want Renovate to participate correctly?

Yes, I believe so, though I don't know how to ask `git` what the line-endings _should_ be for a given file.

> I guess this could be used: https://www.npmjs.com/package/detect-newline as part of any solution.

It would at least prevent the back-and-forth line-ending swap.

**Comment by destroyerofbuilds** [comment]
> In that case, isn't .gitattributes the best approach if you want Renovate to participate correctly?

Except when you need to interact with projects managed by other source control tools (such as Subversion from GitHub, or Mercurial from Bitbucket).

**Comment by rarkins** [comment]
I'm going to rely on gitFs to manage this going forward
