### ISSUE TITLE
Terraform-module provider unable to parse some git url

### ISSUE THREAD

**Issue by jrevillard** [renovatebot/renovate#15467]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.41.2

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.9.4

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Hello,

I'm trying to make terraform module updates using renovate on our self hosted gitlab instance. Actually, renovate reports 'invalid-version' for this kind of git url: 

    module "test" {
      source   = "git@my-gitlab-instance.local:devops/terraform/instance.git?ref=v5.0.0"
    ...
    }

If I switch to `https://my-gitlab-instance.local/devops/terraform/instance.git?ref=v5.0.0` it works but renovate cannot authenticate properly.

This is already working for instance for the ansible-galaxy so I think that this should also be supported here.

The problem is the regex [here](https://github.com/renovatebot/renovate/blob/04333d44ab2be145db46026f29df8014a8fce7c5/lib/modules/manager/terraform/modules.ts#L19).

Best,
Jerome

### Relevant debug logs

<details><summary>Logs</summary>

```
{"packageFile":"main.tf","deps":[{"depType":"module","depName":"git@my-gitlab-instance.local:devops/terraform/instance.git?ref=v5.0.0","datasource":"terraform-module","depIndex":0,"updates":[],"warnings":[],"versioning":"hashicorp","skipReason":"invalid-value"},{"depType":"module","depName":"git@my-gitlab-instance.local:devops/terraform/instance.git?ref=v5.0.0","datasource":"terraform-module","depIndex":1,"updates":[],"warnings":[],"versioning":"hashicorp","skipReason":"invalid-value"}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by jrevillard** [comment]
If I specify the url using this format it works: `ssh://git@my-gitlab-instance.local/devops/terraform/instance.git?ref=v5.0.0`

**Comment by MaronHatoum** [comment]
Hi 
I changed this regex: 
`  /(?:git::)?(?<url>(?:http|https|ssh):\/\/(?:.*@)?(?<path>.*.*\/(?<project>.*\/.*)))\?ref=(?<tag>.*)$/
`
**To:**
`(?:git::)?((?<url>(?:http|https|ssh)(:\/\/))?(?:.*@)?(?<path>.*.*\/(?<project>.*\/.*)))\?ref=(?<tag>.*)$`

after this change, the regex matched the problematic URL successfully.
`git@my-gitlab-instance.local:devops/terraform/instance.git?ref=v5.0.0`

![image](https://user-images.githubusercontent.com/98313426/167836067-4215e06c-68c1-4eb8-8694-f06a519b65dc.png)

**Comment by mcfedr** [comment]
For authentication to gitlab terraform modules, using https, I use host rules.

I'm using renovate runner on gitlab, so it has the variables used, but you can replace these with the hard coded url and a private token that have access to the repo with modules

```json
      "hostRules": [
        {
          "hostType": "terraform-module",
          "matchHost": "$CI_SERVER_HOST",
          "token": "$CI_JOB_TOKEN"
        }
      ],
```

**Comment by MaronHatoum** [comment]
[minimal reproduction](https://github.com/MaronHatoum/terraform-reproduce-url)

**Comment by MaronHatoum** [comment]
Hi @rarkins @viceice 
please advise regarding the new regex I fixed, but it also captures azure devops URLs, please see [this](https://regex101.com/r/vamvyA/1).

**Comment by rarkins** [comment]
I think when it's a git URL we can't be sure of what type of host it is, even though "if the host name contains gitlab then it's probably gitlab" is a sound guess.

Do you plan to treat these as `git-tags` deps? In which case the platform type is not important.

**Comment by MaronHatoum** [comment]
Yes, Azure URLs are treated as `git-tags`, i will open a PR.
