### ISSUE TITLE
Conda Datasource fails for source_url / dev_url beeing {}

### ISSUE THREAD

**Issue by martinei** [renovatebot/renovate#15468]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We use the conda Datasource. It fails to parse the following package: https://api.anaconda.org/package/conda-forge/pytest-dependency
The metadata contain

```
dev_url : {}
```

the conda datasource stores this in "dep.sourceUrl" as Object:
```
result.sourceUrl = response.body.dev_url;
```
(https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/conda/index.ts#L46)

Later metadata tries to parse it as a string: 
```
   const parsedUrl = URL.parse(dep.sourceUrl);
 ```
 (https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/metadata.ts#L131)
which fails:

```
  "err": {
             "code": "ERR_INVALID_ARG_TYPE",
             "message": "The \"url\" argument must be of type string. Received an instance of Object",
             "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"url\" argument must be of type string. Received an instance of Object\n    at new NodeError (internal/errors.js:322:7)\n    at validateString (internal/validators.js:124:11)\n    at Url.parse (url.js:171:3)\n    at Object.urlParse [as parse] (url.js:158:13)\n    at addMetaData (/usr/src/app/node_modules/renovate/lib/modules/datasource/metadata.ts:131:27)\n    at fetchReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:294:14)\n    at getPkgReleases (/usr/src/app/node_modules/renovate/lib/modules/datasource/index.ts:332:7)\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:76:32)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:47:13)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
           },
```           

I propse to check all urls while receiving and convert to strings if they are empty objects.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
We can probably fix this using code inspection alone, but a reproduction is always helpful to verify with
