### ISSUE TITLE
Error "RangeError: Invalid array length" during update of a nuget dependency

### ISSUE THREAD

**Issue by wizgob** [renovatebot/renovate#15489]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.45.2

### Please select which platform you are using if self-hosting.

Azure DevOps (dev.azure.com)

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

The pull request for an update of a nuget package is not created as expected.
An error "RangeError: Invalid array length" appears in log.

RangeError: Invalid array length\n    at Array.flat (<anonymous>)\n    at recursivelyGetDependentPackageFiles (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/modules/manager/nuget/package-tree.js:49:99)\n    at getDependentPackageFiles (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/modules/manager/nuget/package-tree.js:38:12)\n    at async updateArtifacts (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/modules/manager/nuget/artifacts.js:74:13)\n    at async getUpdatedPackageFiles (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/update/branch/get-updated.js:193:29)\n    at async processBranch (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/update/branch/index.js:275:21)\n    at async writeUpdates (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/process/write.js:25:21)\n    at async update (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/process/extract-update.js:108:15)\n    at async Object.renovateRepository (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/index.js:43:25)\n    at async Object.start (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/global/index.js:116:13)\n    at async /home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/renovate.js:15:24

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Setting current branch to develop (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: latest commit (repository=MyProject, branch=renovate/ninject-3.x)
       "branchName": "develop",
       "latestCommitDate": "2022-05-06T12:42:04+00:00"
DEBUG: getBranchPr(renovate/ninject-3.x) (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: getPrList() (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: branchExists=false (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: dependencyDashboardCheck=undefined (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: recreateClosed is true (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: Checking schedule(at any time, null) (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: No schedule defined (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: Branch needs creating (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: Using reuseExistingBranch: false (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: Starting search at index 1079 (repository=MyProject, packageFile=Kernel.Interface/Kernel.Interface.csproj, branch=renovate/ninject-3.x)
       "depName": "Ninject"
DEBUG: Found match at index 1079 (repository=MyProject, packageFile=Kernel.Interface/Kernel.Interface.csproj, branch=renovate/ninject-3.x)
       "depName": "Ninject"
DEBUG: found NuGet.config (repository=MyProject, branch=renovate/ninject-3.x)
       "nuGetConfigPath": "nuget.config"
DEBUG: clearing registry URLs (repository=MyProject, branch=renovate/ninject-3.x)
DEBUG: adding registry URL (repository=MyProject, branch=renovate/ninject-3.x)
       "registryUrl": "https://api.nuget.org/v3/index.json"
DEBUG: Contents updated (repository=MyProject, packageFile=Kernel.Interface/Kernel.Interface.csproj, branch=renovate/ninject-3.x)
       "depName": "Ninject"
DEBUG: nuget.updateArtifacts(Kernel.Interface/Kernel.Interface.csproj) (repository=MyProject, branch=renovate/ninject-3.x)
 WARN: Error updating branch (repository=MyProject, branch=renovate/ninject-3.x)
       "err": {
         "message": "Invalid array length",
         "stack": "RangeError: Invalid array length\n    at Array.flat (<anonymous>)\n    at recursivelyGetDependentPackageFiles (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/modules/manager/nuget/package-tree.js:49:99)\n    at getDependentPackageFiles (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/modules/manager/nuget/package-tree.js:38:12)\n    at async updateArtifacts (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/modules/manager/nuget/artifacts.js:74:13)\n    at async getUpdatedPackageFiles (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/update/branch/get-updated.js:193:29)\n    at async processBranch (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/update/branch/index.js:275:21)\n    at async writeUpdates (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/process/write.js:25:21)\n    at async update (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/process/extract-update.js:108:15)\n    at async Object.renovateRepository (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/repository/index.js:43:25)\n    at async Object.start (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/workers/global/index.js:116:13)\n    at async /home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/dist/renovate.js:15:24"
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
@mattvaughan happening here, any idea?

https://github.com/renovatebot/renovate/blob/6fd86edb32a90922d86a42f9c15b3672a64bdf6b/lib/modules/manager/nuget/package-tree.ts#L53-L69

**Comment by wizgob** [comment]
Unfortunately, I was not able to prepare a reproduction.

**Comment by mattvaughan** [comment]
I'll take a look at this today. Been sick for a bit :mask:

**Comment by mattvaughan** [comment]
@wizgob I'm having trouble reproducing this error. Could you describe your project structure?

**Comment by wizgob** [comment]
@mattvaughan It's a big solution with more than 200 C# projects and lots of dependencies.
The projects use .net 4.7 and most are converted to the new csproj format ( <Project Sdk="Microsoft.NET.Sdk"> ) and some remaining on the old format.
Most of the projects use <PackageReferences> with some still with the old nuget format.
I tried to build a script to build an anoymized stripped down version, but it works as normal.

I you have pointers on how to build an anonymous solution, I can try again.

I can also try using the real solution and removing parts but that will be time consuming.

Thank you for taking a look, I know its not easy without a repoduction.

**Comment by MaronHatoum** [comment]
Hi @wizgob 
can you please provide us with the `csproj` file so we can try to reproduce the issue by unit test?

**Comment by wizgob** [comment]
Hi @MaronHatoum ,

Unfortunately the issue occur only with our full solution with 190 csproj.
Taking only the csproj with the package that show the error does not trigger it.

I also tried removing csproj to try to reduce the set but I ran in another issue where renovate execution is taking more than one hour or not completing at all.

In short, I was not able to prepare a reproduction.
