### ISSUE TITLE
Renovate fails to update yarn.lock with: sed: can't read /home/user/yarn-slim/2.4.3/lib/node_modules/yarn/lib/cli.js: No such file or directory

### ISSUE THREAD

**Issue by coderbyheart** [renovatebot/renovate#15493]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

During execution the job fails at

    Installing legacy tool yarn-slim v2.4.3

with

    sed: can't read /home/user/yarn-slim/2.4.3/lib/node_modules/yarn/lib/cli.js: No such file or directory

Issue where it happens: https://github.com/distributeaid/shipment-tracker/pull/758 (there are more closed issues in this repo with the same problem)

### Relevant debug logs

Renovate job id: 657573079

<details><summary>Logs</summary>

```
DEBUG: rawExec err(branch="renovate/major-jest-monorepo")
{
  "err": {
    "killed": false,
    "code": 2,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/distributeaid/shipment-tracker\":\"/mnt/renovate/gh/distributeaid/shipment-tracker\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_CACHE_FOLDER -w \"/mnt/renovate/gh/distributeaid/shipment-tracker/frontend\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool yarn-slim 2.4.3 && yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts && npx yarn-deduplicate --strategy fewer && yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\"",
    "stdout": "Installing legacy tool yarn-slim v2.4.3\n\nadded 1 package in 1s\n",
    "stderr": "sed: can't read /home/user/yarn-slim/2.4.3/lib/node_modules/yarn/lib/cli.js: No such file or directory\n",
    "message": "Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/distributeaid/shipment-tracker\":\"/mnt/renovate/gh/distributeaid/shipment-tracker\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_CACHE_FOLDER -w \"/mnt/renovate/gh/distributeaid/shipment-tracker/frontend\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool yarn-slim 2.4.3 && yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts && npx yarn-deduplicate --strategy fewer && yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\"\nsed: can't read /home/user/yarn-slim/2.4.3/lib/node_modules/yarn/lib/cli.js: No such file or directory\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/distributeaid/shipment-tracker\":\"/mnt/renovate/gh/distributeaid/shipment-tracker\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e CI -e YARN_CACHE_FOLDER -w \"/mnt/renovate/gh/distributeaid/shipment-tracker/frontend\" docker.io/renovate/node:16.15.0 bash -l -c \"install-tool yarn-slim 2.4.3 && yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts && npx yarn-deduplicate --strategy fewer && yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\"\nsed: can't read /home/user/yarn-slim/2.4.3/lib/node_modules/yarn/lib/cli.js: No such file or directory\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)"
  }
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by viceice** [comment]
already fixed, please force a retry

**Comment by viceice** [comment]
- #15484-

**Comment by coderbyheart** [comment]
Ah, nice. Will try!

**Comment by coderbyheart** [comment]
Retry did not update the lockfile.

**Comment by viceice** [comment]
> Retry did not update the lockfile.

it did at linked PR. the failure is a different issue, check your manual PR changes

**Comment by cailloumajor** [comment]
@viceice 
I encounter the same problem on all of renovate PRs in my repository https://github.com/cailloumajor/factory-frontend, with no way to fix.
Even after retrying PRs, even after closing PRs, deleting branches and requesting recreation in the dependencies dashboard.

**Comment by viceice** [comment]
> @viceice 
> I encounter the same problem on all of renovate PRs in my repository https://github.com/cailloumajor/factory-frontend, with no way to fix.
> Even after retrying PRs, even after closing PRs, deleting branches and requesting recreation in the dependencies dashboard.

maybe the app isn't updated to latest, workaround is to update engines to `yarn=^1.21.0` so a V1 version is forced

**Comment by rarkins** [comment]
The app is running 32.45.2

**Comment by rarkins** [comment]
What's the job ID of a recent run where you got this yarn error?

**Comment by cailloumajor** [comment]
@viceice thanks for the workaround.

@rarkins #658194724

**Comment by rarkins** [comment]
I'm adding some code so that we can log the sha256 of fetched images so that we know for sure which sidecar image we're running.

**Comment by h-saitooo** [comment]
@viceice @cailloumajor
I was experiencing the same problem.
I was able to solve the problem with your reference.
> https://github.com/renovatebot/renovate/issues/15493#issuecomment-1120180152

**Comment by rarkins** [comment]
It does seem like that's the problem:

```
{"level":20,"branch":"renovate/eslint-8.x","toolName":"yarn-slim","constraint":">= 1.21.1","resolvedVersion":"2.4.3","msg":"Resolved stable matching version","time":"2022-05-07T09:35:22.693Z"}
```

Strange because the newest release of Renovate should have fixed that to resolve a 1.x.

**Comment by rarkins** [comment]
If anyone has a reproduction repo, let me know

**Comment by macchiitaka** [comment]
@rarkins The same problem is reproduced in the following repository.
https://github.com/macchiitaka/tasks-app-nextjs
