### ISSUE TITLE
Terraform modules with SSH not supported for Azure DevOps repositories

### ISSUE THREAD

**Issue by patst** [renovatebot/renovate#15491]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.45.2

### Please select which platform you are using if self-hosting.

Azure DevOps (dev.azure.com)

### If you're self-hosting Renovate, tell us what version of the platform you run.

Azure DevOps

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We want to update Terraform module versions using the [terraform manager](https://docs.renovatebot.com/modules/manager/terraform/). 

The modules are hosted in Azure DevOps Repositories and are referenced using the [scp ssh pattern](https://www.terraform.io/language/modules/sources#scp-like-address-syntax). 
Clone URLs in Azure DevOps have a syntax like this:
`git@ssh.dev.azure.com:v3/<OrganizationName>/<ProjectName>/<RepositoryName>`

In terraform a reference looks like this:
```
module "some-module" {
  source = "git::git@ssh.dev.azure.com:v3/<OrganizationName>/<ProjectName>/<RepositoryName>//modules/some-module?ref=v0.0.38"
}
```

The current regex pattern in https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/terraform/modules.ts#L18 do not match this clone urls.

The current logs for the module are appended below.

Expected behaviour:
New tags are discovered and can be updated.

### Relevant debug logs

<details><summary>Logs</summary>

```
{
                 "depType": "module",
                 "depName": "git::git@ssh.dev.azure.com:v3/<OrganizationName>/<ProjectName>/<RepositoryName>",
                 "datasource": "terraform-module",
                 "depIndex": 4,
                 "updates": [],
                 "warnings": [],
                 "versioning": "loose",
                 "skipReason": "invalid-value"
               }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
looks more like a feature request to me, as it's simply not yet supported by renovate 🤔

**Comment by patst** [comment]
> looks more like a feature request to me, as it's simply not yet supported by renovate 🤔

I was not sure, but I agree.
I would be willing to try to implement the feature which would involve (from my understanding):

- a new regex for the Azure DevOps repos in https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/terraform/modules.ts#L18
- usage of the regex at https://github.com/renovatebot/renovate/blob/533024843ccbe52d22c2632baed2ebb8e66a3725/lib/modules/manager/terraform/modules.ts#L36
- testcases in [modules.spec.ts](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/terraform/modules.spec.ts)
