### ISSUE TITLE
Elixir / erlang compatibility

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#15503]
### What would you like Renovate to be able to do?

For `binarySource=install|docker` we need to handle elixir / erlang compatibility.

https://hexdocs.pm/elixir/1.12.3/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

- ref https://github.com/containerbase/buildpack/issues/379

Elixir 1.7+ is still supported and needs erlang 19-22

### If you have any ideas on how this should be implemented, please tell us here.

add manual contraints, if non are set by user or can't extracted.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by Chumper** [comment]
Do we want to install it silently if the version does not match or do we want to abort explicitly?

**Comment by rarkins** [comment]
With other languages we usually have this logic:
- Can we install what the constraints ask? Good, let's do that
- If not, log a message and install the latest version

**Comment by viceice** [comment]
We currently don't use any contraint, when we convert mix to use new buildpack tools, we need to ensure compability somehow.

https://github.com/renovatebot/renovate/blob/6c7e79fbe3fe7f78987c168ee01de209d5f7a233/lib/modules/manager/mix/artifacts.ts#L76-L82

it seems we can also extract the elixir constraint:
https://github.com/renovatebot/renovate/blob/dca3418bbdbf1024ac6807e591562b4042bc846d/lib/modules/manager/mix/__fixtures__/mix.exs#L8

not sure if the lockfile includes the erlang version

**Comment by viceice** [comment]
We can propably parse this [file](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/pages/compatibility-and-deprecations.md#compatibility-between-elixir-and-erlangotp) from time to time like we do with node / debian schedules

**Comment by viceice** [comment]
Oldest erlang we build is v22, so we can only support elixir v1.7+
