### ISSUE TITLE
Use `structureClone()` function for deep clone if available

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#15534]
### Describe the proposed change(s).

It seems to be available starting from Node v17. See also:
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

**Comment by viceice** [comment]
what's the benefit for renovate?

**Comment by zharinov** [comment]
Hopefully it's more performant

**Comment by rarkins** [comment]
https://simonplend.com/deep-clone-values-with-structuredclone/

**Comment by viceice** [comment]
feature request for node v16 Backport was closed. so would only usable when our min version is node v18.

**Comment by viceice** [comment]
blocked by
- https://github.com/renovatebot/renovate/issues/20082

**Comment by JamieMagee** [comment]
Closed by #20885
