### ISSUE TITLE
Support maven optional 

### ISSUE THREAD

**Issue by piotrwielgolaski-tomtom** [renovatebot/renovate#15544]
### What would you like Renovate to be able to do?

I would like to disable update of optional dependency 
https://www.baeldung.com/maven-optional-dependency
I dont see any way to filter by this

### If you have any ideas on how this should be implemented, please tell us here.

Ad support for reading also `optional` similarly as for `scope` in 
https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/maven/extract.ts#L81
When optional is set and has value true, depType can be set as optional

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
Hi, reproduction isn't optional if you're implementing it yourself

**Comment by piotrwielgolaski-tomtom** [comment]
Here is reproducer for this issue https://github.com/piotrwielgolaski-tomtom/renovate-issue-15544
