### ISSUE TITLE
No reviewers are assigned to PR when one of them is wrong in Bitbucket

### ISSUE THREAD

**Issue by rubasace** [renovatebot/renovate#15560]
### How are you running Renovate?

Self-hosted

### Please select which platform you are using if self-hosting.

Bitbucket Cloud (bitbucket.org)

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When the list of reviewers contains an invalid username, no reviewers are assigned.

My understanding is that Renovate is retrieving the users from BitBucket API and it fails as a whole when cannot retrieve one of them. I think it should be able to create the PR with all valid users and just ignore the invalid ones, showing the issue in the logs.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rubasace** [comment]
I saw this PR: https://github.com/renovatebot/renovate/pull/14331

Is that supposed to have fixed the issue? We are running Renovate always on latest version (it updates itself) and we've been experimenting this issue since we started (late 2021)

**Comment by PhilipAbed** [comment]
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-pull-request-id-put

we provide the body of this API with the reviewers that the user inserts,
apparently if the API doesn't find the reviewer, it will probably fail, which is causing the issue,

I'm wondering, is there a way to check if the given reviewers via bitbucket api?
and if yes, does that mean we have to call a new API every time we create a bitbucket request?

https://github.com/renovatebot/renovate/blob/1b28501d30fefa502235b886518133f998db4ea0/lib/modules/platform/bitbucket/index.ts#L592-L612

Note: This will not block the code as there's an exception handler right after the `platform.addReviewers`.

**Comment by setchy** [comment]
@rubasace - in both the createPR and updatePR scenarios, sanitizeReviewers.  

There were some [recent updates](https://github.com/renovatebot/renovate/pull/20445) to sanitizeReviewers to check that each reviewer account is active AND also a member of the workspace.

**Comment by setchy** [comment]
@rarkins - I believe this issue should now be resolved
