### ISSUE TITLE
terraform-module datasource source attribute not parsed correctly when with hyphens

### ISSUE THREAD

**Issue by mintmac** [renovatebot/renovate#15603]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.27.0

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

N/A

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When using `terraform-module` datasource with private Terraform Enterprise registry it seems that the `source` attribute is not parsed correctly for dns names that have hyphens i.e. `tfe.abc.company-name.com`. The name is truncated to `tfe.abc.company` and therefore when TFE service discovery is being called the datasource errors out with `ENOTFOUND`.

It works when packageRules points to the correct url:

```
packageRules: [
        {
            matchDatasources: ['terraform-module'],
            registryUrls: [
                "https://tfe.abc.company-name.com"
            ],
        }
    ],
```

Module import snippet:
```
module "mymodule" {
  source  = "tfe.abc.company-name.com/myregistry/mymodule/google"
  version = "0.7.0"
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
...
{
    "name": "renovate",
    "hostname": "<redacted>",
    "pid": 9,
    "level": 10,
    "logContext": "<redacted>",
    "repository": "myproject/myrepo",
    "namespace": "datasource-terraform",
    "key": "https://tfe.abc.company/.well-known/terraform.json",
    "msg": "Cache miss",
    "time": "2022-05-16T13:00:10.373Z",
    "v": 0
}
...
{
    "name": "renovate",
    "hostname": "<redacted>",
    "pid": 9,
    "level": 20,
    "logContext": "<redacted>",
    "repository": "myproject/myrepo",
    "datasource": "terraform-module",
    "packageName": "tfe.abc.company-name.com/myregistry/mymodule/google",
    "errCode": "ENOTFOUND",
    "msg": "Datasource connection error",
    "time": "2022-05-16T13:00:13.482Z",
    "v": 0
}
...
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by nabeelsaabna** [comment]
@mintmac this issue looks similar to https://github.com/renovatebot/renovate/issues/15467

**Comment by mintmac** [comment]
@nabeelsaabna I may be wrong but [#15467](https://github.com/renovatebot/renovate/issues/15467) looks like related to terraform manager and tags.

**Comment by mintmac** [comment]
@viceice I'm trying to understand how this is a duplicate and what is the fix. Could you help me understand how those two issues are related?

https://github.com/renovatebot/renovate/issues/15467 refers incorrect regex for git repos.
My issue is about the fact that host is not being correctly parsed from the source attribute of the terraform module. Please see the log I attached.

Thanks!

**Comment by viceice** [comment]
in both cases the dash in the url seems to be the root cause.

**Comment by mintmac** [comment]
Ok, thanks.
FYI I just confirmed. Host from url without dashes was parsed correctly.
