### ISSUE TITLE
Use automerge feature of GitLab

### ISSUE THREAD

**Issue by mcfedr** [renovatebot/renovate#15611]
### What would you like Renovate to be able to do?

When making MRs for changes that are configured for auto merge by renovate it would be great if it set the 'merge when pipeline succeeds' flag.

This would mean the changes are merged quicker without another run of renovate required to merge them.

### If you have any ideas on how this should be implemented, please tell us here.

I have not looked at what would be required to implement it. 

I know that GitLab API allows setting this flag once a MR has been created.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
Do you mean https://docs.renovatebot.com/configuration-options/#platformautomerge ?

**Comment by mcfedr** [comment]
Ha, I guess you are right, who knew...

would it be worth enabling this by default in say the gitlab renovate runner?
