### ISSUE TITLE
semanticCommitType is ignored

### ISSUE THREAD

**Issue by eng-dibo** [renovatebot/renovate#15615]
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I set the option `semanticCommitType` to `build`  but I see other strings such as

[fix(): pin dependencies](https://github.com/eng-dibo/dibo/pull/76/commits/ee80aa53aede7c67e48a6fa1870493e3f91433e9)

[chore(): update jest monorepo](https://github.com/eng-dibo/dibo/pull/77/commits/1d268df6d641bcf24d79480f360c9ff78dae7561)

**full config**
{
  "extends": ["config:base"],
  "packageRules": [
    {
      "matchUpdateTypes": ["minor", "patch"],
      "automerge": true,
      "automergeStrategy": "rebase",
      "groupName": "all non-major dependencies"
    },
    {
      "matchPackagePatterns": ["@angular/.+"],
      "dependencyDashboardApproval": true
    }
  ],
  "automergeType": "branch",
  "dependencyDashboardAutoclose": true,
  "dependencyDashboardTitle": "Dependency Dashboard by reovate",
  "labels": ["dependencies"],
  "prBodyColumns": [
    "Package",
    "Update",
    "Type",
    "New value",
    "Package file",
    "References"
  ],
  "prCreation": "not-pending",
  "semanticCommits": true,
  "semanticCommitType": "build",
  "semanticCommitScope": "{{ baseDir }}",
  "commitBody": "by https://www.whitesourcesoftware.com/free-developer-tools",
  "commitBodyTable": true,
  "commitMessageSuffix": "[renovate]",
  "separateMultipleMajor": true,
  "updateInternalDeps": true,
  "ignoreDeps": ["@semantic-release/npm", "strip-json-comments"]
}
```

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by eng-dibo** [comment]
also I want to set the same scope to PR title

**Comment by rarkins** [comment]
Alternatively use https://docs.renovatebot.com/presets-default/#semanticcommittypeallarg0
