### ISSUE TITLE
Improve test code for `lib/config/presets/index.spec.ts`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15614]
### Describe the proposed change(s).

Creating an issue to track this comment from @viceice: https://github.com/renovatebot/renovate/pull/15537#discussion_r874390204

This issue should probably be assigned to @hojerst, as they said:

> To be honest, I don't see if this actually increases readability. I don't want to be rude, but I'd rather see that merged fast instead of reiterating over minor improvements to test code for a problem that blocks a documented use case in production.
> 
> That being said, I will implement the changes next week after I'm back from vacation if the PR is still open. Also feel free to change the PR as desired - I'd enabled changes for maintainers.

**Comment by hojerst** [comment]
I think that can be closed, as the required refactoring was done in the mentioned PR by viceice during my vacation.
