### ISSUE TITLE
Raise issue for "Dependency Lookup Warnings"

### ISSUE THREAD

**Issue by Shegox** [renovatebot/renovate#15651]
### What would you like Renovate to be able to do?

Renovate could raise an optional dedicated issue if any dependency could not be looked up (e.g. because authorization was missing). 

The onboarding PR already includes this section and this is very helpful to identify if all dependencies could be looked up (and potentially updated). For an already onboarded project when it later adds additional dependencies these warnings are not raised and only logged in the log file and easily missed. 

I would like to see that Renovate raises a dedicated issue for these lookup warnings to ensure that one could be aware of them.   

### If you have any ideas on how this should be implemented, please tell us here.

This could be implemented similiar to [`raiseConfigWarningIssue`](https://github.com/renovatebot/renovate/blob/50d23e6576ee1c068de5fb41a4e58cbc3059a685/lib/workers/repository/error-config.ts#L8) and per default included in `suppressNotifications` to not bug people about if they don't want to receive alerts.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by princefisher** [comment]
It could also be a separate section at the bottom or the top on the existing dependency dashboard as well. Like all of the sections in the dependency dashboard the section itself only shows if there is a problem detected (the same way as in the onboarding PR)

Today the dependency board already shows an error if decryption of a protected field fails...

**Comment by rarkins** [comment]
That might be preferable for most because of the dashboard is already open then updates to it won't create notifications noise

**Comment by PhilipAbed** [comment]
@princefisher 
hi, can you change description to dashboard instead of PR ? + title too. 
then we can make this ready i guess

**Comment by PhilipAbed** [comment]
@rarkins the dashboard includes many sections, should we add a warning under a specific section ? or create a new section? how should it look like

**Comment by rarkins** [comment]
Dependency dashboard would be better

**Comment by MaronHatoum** [comment]
minimal reproduction: https://github.com/MaronHatoum/dashboard-dependency-lookup-warnings-reproduction

**Comment by MaronHatoum** [comment]
Hi @Shegox 
is this the expected result (https://github.com/MaronHatoum/dashboard-dependency-lookup-warnings-reproduction/issues/2)? 
![image](https://user-images.githubusercontent.com/98313426/172840300-3ae292bc-ffc7-42ee-9733-73948bd8aa30.png)
