### ISSUE TITLE
Renovate should cache the base perset which is referenced in the same preset

### ISSUE THREAD

**Issue by MurphyZh0** [renovatebot/renovate#15712]
### What would you like Renovate to be able to do?

When using preset https://github.com/whitesource/log4j-remediations, it takes quite long time to finish validatePresets(). After enable trace log and found that there are so many request to https://api.github.com/repos/whitesource/log4j-remediations/contents/base.json because there are many items refer to the same base.json in the same repository, e.g. https://github.com/whitesource/log4j-remediations/blob/main/default.json#L5
If the result of such reference can be cached, then the preset load will be quite faster.

### If you have any ideas on how this should be implemented, please tell us here.

In validatePresets(), when loading the presets, keep the base preset referred cached so that further request can skip and use the cache to save time.

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
The http requests should already be cached

**Comment by rarkins** [comment]
Is this about caching the http requests or caching the validation result? And I assume it relates to the CLI validation and not Renovate itself? Or is this about Renovate's runtime?

**Comment by MurphyZh0** [comment]
Either is ok, the main purpose is to accelerate the validation of the perset github>whitesource/log4j-remediations which will try to resolve preset github>whitesource/log4j-remediations//base thousands of times.

**Comment by MurphyZh0** [comment]
Reproduction provided in https://github.com/MurphyZh0/dummyRenovate

**Comment by rarkins** [comment]
Logs for current Renovate confirm that the HTTP request is cached:

```
DEBUG: http statistics (repository=MurphyZh0/dummyRenovate)
       "urls": {
         "https://api.github.com/graphql (POST,200)": 2,
         "https://api.github.com/repos/MurphyZh0/dummyRenovate/pulls (GET,200)": 1,
         "https://api.github.com/repos/whitesource/log4j-remediations/contents/base.json (GET,200)": 1,
         "https://api.github.com/repos/whitesource/log4j-remediations/contents/default.json (GET,200)": 1
       },
       "hostStats": {"api.github.com": {"requestCount": 5, "requestAvgMs": 305, "queueAvgMs": 0}},
       "totalRequests": 5
```
