### ISSUE TITLE
[Self-Hosted] Ability to generate a non-org-binded secret

### ISSUE THREAD

**Issue by vegaaz** [renovatebot/renovate#15714]
### What would you like Renovate to be able to do?

Hi,

in my case I have a HostRule which provides nexus3 authentication credentials.
To provide these credentials to every repository I create the Onboarding_Config with a extend to a preset (which contains the credentials).

I wanted to improve security and encrypt the password of the preset.
Unfortunately the gpg-key needs to be created with a ORG-Attribute.
In Line 116 of the decrypt-function (https://github.com/renovatebot/renovate/blob/main/lib/config/decrypt.ts) is a check which checks if the current repository starts with the given ORG-Attribute.
In my case I have different ORGs and Userspaces, therefor I can't use the 'general' generated gpg-key because of 'Secret is scoped to a different org'-Issues.

Therefor I would like to have a option to NOT bind the secret to a ORG.
Alternatively something like regex-interpretation of [a-zA-Z]* could fullfill my needs.

Kind regards,
Vegaaz

### If you have any ideas on how this should be implemented, please tell us here.

https://github.com/renovatebot/renovate/blob/main/lib/config/decrypt.ts
Change Line 116:
```
repository.toLowerCase().startsWith(scopedOrg.toLowerCase())
```
To use a regex-allowing-function (test/match) instead of 'startsWith'.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Why do you need to encrypt it in the first place if you are self-hosted? You can provide hostRules in your global (bot) config.

**Comment by vegaaz** [comment]
Hi @rarkins ,
thanks for the fast reply!

I want to encrypt to improve security. The gitlab instance is available from external and used by 1000+ members.
In my mind it's always a bad idea to store plain-text passphrases in git(lab)...

> You can provide hostRules in your global (bot) config.

I coulnd't find the correct way from the documentary. Could you please provide a code-example?
In my current setup I have a dedicated User with a 'renovate-runner' repository.
The renovate runs as gitlab-ci job.
