### ISSUE TITLE
[regression] 32.66.6 cause renovate to fail

### ISSUE THREAD

**Issue by AKorezin** [renovatebot/renovate#15759]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.66.7

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

gitlab.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Since 32.66.6 renovate throws the error.
I tested it with
- docker container at localhost
- gitlab runner template at gitlab.com

I will provide additional information with minimal repo shortly.

### Relevant debug logs

<details><summary>Logs</summary>

```
ERROR: Repository has unknown error (repository=)
       "err": {
         "message": "packageFiles is not iterable",
         "stack": "TypeError: packageFiles is not iterable\n    at /usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:50:23\n    at async Promise.all (index 2)\n    at extractAllDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:47:26)\n    at extract (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:82:20)\n    at extractDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/process/index.ts:105:26)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:42:52)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:150:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
       }

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment]
already fixed in v32.66.7

https://github.com/renovatebot/renovate/releases/tag/32.66.7

**Comment by viceice** [comment]
btw: your report is inconsistent. your referring to v32.66.6 and v32.66.7.

**Comment by AKorezin** [comment]
Yeah, my bad, not yet fixed at gitlab. 
Check [this](https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/renovate-dind.gitlab-ci.yml).

**Comment by viceice** [comment]
should be fixed in a couple of minutes

**Comment by AKorezin** [comment]
Is it necessary to fix the issue with new info?

**Comment by viceice** [comment]
yes, please fix the wrong version

**Comment by viceice** [comment]
fixed in https://gitlab.com/renovate-bot/renovate-runner/-/releases
