### ISSUE TITLE
Renovate doesn't update Docker Images from Red Hat Registry

### ISSUE THREAD

**Issue by lclc** [renovatebot/renovate#15781]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest (04ebc262eb6d0f329c07ace1027061eef9a41a1b)

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

In our Dockerfile we use

> FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5-218

But the current latest is  8.6-751 (see https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.6-751&push_date=1652217593000).

Other Docker Images we use from docker.io get updated properly (e.g. FROM docker.io/library/rust:1.60-alpine to 1.61) by Renovate.

Minimal reproduction repository:  https://github.com/lclc/renovate-rhel

PR updating the Rust-Alpine image: https://github.com/lclc/renovate-rhel/pull/2

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by HonkingGoose** [comment]
Did you try setting your own `regex` `versioning` for the `ubi-minimal:8.5-218` docker image? I suspect Renovate doesn't "understand" the versioning scheme of `ubi-minimal`.

Quote from [our Docker docs, version compatibility](https://docs.renovatebot.com/docker/#version-compatibility):

> 
> ## Version compatibility
> 
> Although suffixes in SemVer indicate pre-releases (e.g. `v1.2.0-alpha.2`), in Docker they typically indicate compatibility, e.g. `1.2.0-alpine`.
> By default Renovate assumes suffixes indicate compatibility, for this reason Renovate will not _change_ any suffixes.
> Renovate will update `1.2.0-alpine` to `1.2.1-alpine` but never updates to `1.2.1` or `1.2.1-stretch` as that would change the suffix.
> 
> If this behavior does not suit a particular package you have, Renovate allows you to customize the `versioning` scheme it uses.
> For example, you have a Docker image `foo/bar` that sticks to SemVer versioning.
> This means that you need to tell Renovate that suffixes indicate pre-release versions, and not compatibility.
> 
> You could then use this `packageRules` array, to tell Renovate to use `semver` versioning for the `foo/bar` package:
> 
> ```json
> {
>   "packageRules": [
>     {
>       "matchDatasources": ["docker"],
>       "matchPackageNames": ["foo/bar"],
>       "versioning": "semver"
>     }
>   ]
> }
> ```
> 
> Another example is the official `python` image, which follows `pep440` versioning.
> You can tell Renovate to use the `pep440` versioning scheme with this set of `packageRules`:
> 
> ```json
> {
>   "packageRules": [
>     {
>       "matchDatasources": ["docker"],
>       "matchPackageNames": ["python"],
>       "versioning": "pep440"
>     }
>   ]
> }
> ```
> 
> If traditional versioning doesn't work, try Renovate's built-in `loose` `versioning`.
> Renovate will perform a best-effort sort of the versions, regardless of whether they have letters or digits.
> 
> If both the traditional versioning, and the `loose` versioning do not give the results you want, try the `regex` `versioning`.
> This approach uses regex capture group syntax to specify which part of the version string is major, minor, patch, pre-release, or compatibility.
> See the docs for `versioning` for documentation and examples of `regex` versioning in action.
> 

Quote from [our `versioning` docs](https://docs.renovatebot.com/configuration-options/#versioning):

> 
By exposing `versioning` to config, you can override the default versioning for a package manager if needed. We do not recommend overriding the default versioning, but there are some cases such as Docker or Gradle where versioning is not strictly defined and you may need to specify the versioning type per-package.

**Comment by rarkins** [comment]
Setting "loose" versioning might be quicker. Renovate defaults to treating -suffix strings in Docker images as compatibility strings (eg -alpine) and only proposing updates with same compatibility.

**Comment by lclc** [comment]
> Setting "loose" versioning might be quicker. Renovate defaults to treating -suffix strings in Docker images as compatibility strings (eg -alpine) and only proposing updates with same compatibility.

Thanks, I've tried with 'loose' (current option here: https://github.com/lclc/renovate-rhel/blob/master/renovate.json) but it didn't work.


Trying with regex next.

**Comment by viceice** [comment]
i don't think this is a renovate bug, so should be converted to a discussion.

**Comment by lclc** [comment]
> i don't think this is a renovate bug, so should be converted to a discussion.

I expected it to update because it does that for the other Docker images too. So I didn't see the lack of updates for a while.

I imagine three options:

1. Adjust it to also cover this kind of image naming (I'd expect RHEL images to be common or become more coming now that UBI are freely available to anyone without the need of a RHEL license)
2. Add a warning text somewhere in the docs
3. Renovate to put out a warning if a specific image hasn't been updated for a longer time and suggest to check on it (to not run into this)

**Comment by viceice** [comment]
it's not a bug, because it's not a usual docker hub image version scheme.

also you can easily workaround by using a matching versioning.

i don't think the default docker versioning can support this without breaking other currently supported schemes.

**Comment by lclc** [comment]
Ok. 

My solution, for now, is to define the versioning as follows:


```
  "packageRules": [
    {
      "matchDatasources": ["docker"],
      "matchPackageNames": ["registry.access.redhat.com/ubi8/ubi-minimal"],
      "versioning": "regex:^(?<major>\\d+)\\.(?<minor>\\d+)\\.*(?<patch>\\d*)-(?<build>\\d+)?$"
    }
  ]
```

**Comment by rarkins** [comment]
The original examples had no patch digits. Can you clarify?

**Comment by lclc** [comment]
Patch digits were introduced with UBI9 (RHEL 9), they weren't part of UBI8 (RHEL 8).

E.g. current UBI9 is:
> registry.access.redhat.com/ubi9/ubi-minimal:9.0.0-1471
(see https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?container-tabs=gti)

Current UBI8 is:
> registry.access.redhat.com/ubi8/ubi-minimal:8.6-751
(see https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?container-tabs=gti)

**Comment by viceice** [comment]
i think we can add the regex versioning to our workarounds presets and add all images which are public and known to use that versioning scheme
