### ISSUE TITLE
Prettify JSON output for default objects in docs

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15787]
### What would you like Renovate to be able to do?

PR #15637 added a new feature, that shows the default objects and array in our configuration docs. But the output is hard to understand sometimes.

For example, check out [Renovate docs, `lockfileMaintenance`](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance):

![json-output-lockfile-maintenance](https://user-images.githubusercontent.com/34918129/170968211-1abf4c29-8b49-48ad-a507-3da11e38cc72.png)

### If you have any ideas on how this should be implemented, please tell us here.

Run Prettier to transform the JSON:

**Input:**

```json
{"enabled":false,"recreateClosed":true,"rebaseStalePrs":true,"branchTopic":"lock-file-maintenance","commitMessageAction":"Lock  file  maintenance","commitMessageTopic":null,"commitMessageExtra":null,"schedule":["before  5am on monday"],"groupName":null,"prBodyDefinitions":{"Change":"All  locks refreshed"}}
```

**Output:**

```json
{
  "enabled": false,
  "recreateClosed": true,
  "rebaseStalePrs": true,
  "branchTopic": "lock-file-maintenance",
  "commitMessageAction": "Lock  file  maintenance",
  "commitMessageTopic": null,
  "commitMessageExtra": null,
  "schedule": ["before  5am on monday"],
  "groupName": null,
  "prBodyDefinitions": { "Change": "All  locks refreshed" }
}
```

### Is this a feature you are interested in implementing yourself?

No

**Comment by Gabriel-Ladzaretti** [comment]
can we use basic html for this? seems that this is the simplest way of doing this

example:
| Name      | Value                                                                                                                                                                                                                                                                                                                                                                                                                             |
| --------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| type      | object                                                                                                                                                                                                                                                                                                                                                                                                                            |
| default   | <pre>{<br>  "enabled": false,<br>  "recreateClosed": true,<br>  "rebaseStalePrs": true,<br>  "branchTopic": "lock-file-maintenance",<br>  "commitMessageAction": "Lock file maintenance",<br>  "commitMessageTopic": null,<br>  "commitMessageExtra": null,<br>  "schedule": [<br>    "before 5am on monday"<br>  ],<br>  "groupName": null,<br>  "prBodyDefinitions": {<br>    "Change": "All locks refreshed"<br>  }<br>}</pre> |
| mergeable | true                                                                                                                                                                                                                                                                                                                                                                                                                              |
| env       | `RENOVATE_LOCK_FILE_MAINTENANCE`                                                                                                                                                                                                                                                                                                                                                                                                  |

**Comment by viceice** [comment]
The default value shoiuld probably below the table and use a proper json code block instead

**Comment by Gabriel-Ladzaretti** [comment]
> The default value shoiuld probably below the table and use a proper json code block instead

is this what you mean?

## lockFileMaintenance
Configuration for lock file maintenance.
| Name      | Value                                                                                                                                                                                                                                                                                                                                                                                                                             |
| --------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| type      | object                                                                                                                                                                                                                                                                                                                                                                                                                            
| mergeable | true                                                                                                                                                                                                                                                                                                                                                                                                                              |
| env       | `RENOVATE_LOCK_FILE_MAINTENANCE`                                                                                                                                                                                                                                                                                                                                                                                                  |

default value:

```json
{
  "enabled": false,
  "recreateClosed": true,
  "rebaseStalePrs": true,
  "branchTopic": "lock-file-maintenance",
  "commitMessageAction": "Lock  file  maintenance",
  "commitMessageTopic": null,
  "commitMessageExtra": null,
  "schedule": ["before  5am on monday"],
  "groupName": null,
  "prBodyDefinitions": { "Change": "All  locks refreshed" }
}
```

**Comment by Gabriel-Ladzaretti** [comment]
both mocks are ready, would love to know which to PR 😀.

**Comment by astellingwerf** [comment]
[This blog post](https://blog.eidinger.info/master-github-markdown-tables-with-multi-line-code-blocks) might be of interest.

> The default value shoiuld probably below the table and use a proper json code block instead

To me, the metadata for the property reads easier/makes more sense when the code is in the table.

**Comment by viceice** [comment]
i don't like the blown table layout. 🤔

**Comment by Gabriel-Ladzaretti** [comment]
Table using html below. 

This will require us to ditch and stop using `import table from 'markdown-table';` and generate the html ourselves, which shouldnt be a problem for GH markdown (what about mkdocs?), but the output looks a bit weird tbh as we cant use backticks but use `<pre>` tags instead  (`default`&`env`). 


HTML source:
```html
<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
  </tr>
  <tr>
    <td>type</td>
    <td>object</td>
  </tr>
  <tr>
    <td>default</td>
    <td><pre lang="json">{
  "enabled": false,
  "recreateClosed": true,
  "rebaseStalePrs": true,
  "branchTopic": "lock-file-maintenance",
  "commitMessageAction": "Lock file maintenance",
  "commitMessageTopic": null,
  "commitMessageExtra": null,
  "schedule": [
    "before 5am on monday"
  ],
  "groupName": null,
  "prBodyDefinitions": {
    "Change": "All locks refreshed"
  }
}</pre></td>
  </tr>
   <tr>
    <td>mergeable</td>
    <td>true</td>
  </tr>
   <tr>
    <td>env</td>
    <td><pre>RENOVATE_LOCK_FILE_MAINTENANCE</pre></td>
  </tr>
</table>
```

## lockFileMaintenance
Configuration for lock file maintenance.

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
  </tr>
  <tr>
    <td>type</td>
    <td>object</td>
  </tr>
  <tr>
    <td>default</td>
    <td><pre lang="json">{
  "enabled": false,
  "recreateClosed": true,
  "rebaseStalePrs": true,
  "branchTopic": "lock-file-maintenance",
  "commitMessageAction": "Lock file maintenance",
  "commitMessageTopic": null,
  "commitMessageExtra": null,
  "schedule": [
    "before 5am on monday"
  ],
  "groupName": null,
  "prBodyDefinitions": {
    "Change": "All locks refreshed"
  }
}</pre></td>
  </tr>
   <tr>
    <td>mergeable</td>
    <td>true</td>
  </tr>
   <tr>
    <td>env</td>
    <td><pre>RENOVATE_LOCK_FILE_MAINTENANCE</pre></td>
  </tr>
</table>


This feature can be used to refresh lock files and keep them up-to-date.
"Maintaining" a lock file means recreating it so that every dependency version within it is updated to the latest.
Supported lock files are:

- `package-lock.json`
- `yarn.lock`
- `composer.lock`
- `Gemfile.lock`
- `poetry.lock`
- `Cargo.lock`
- `jsonnetfile.lock.json`

**Comment by Gabriel-Ladzaretti** [comment]
> the output looks a bit weird tbh as we cant use backticks but use tags instead (default&env).


this actually stands for markdown tables as well, that is when the code blocks are display on odd row numbers:

the only difference is that with html we can have syntax highlight 
<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
  </tr>
  <tr>
    <td>env</td>
    <td><pre>looks a bit better</pre></td>
  </tr>
  <tr>
    <td>default</td>
    <td><pre lang="json">{
  "this looks": "weird"
}
</pre></td>
  </tr>
  <tr>
    <td>default</td>
    <td><pre lang="json">{
  "this looks": "better"
}
</pre></td>
  </tr>
   <tr>
    <td>env</td>
    <td><pre>Weird as well</pre></td>
  </tr>
</table>

**Comment by rarkins** [comment]
I don't think this one is too bad though:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/6311784/173172732-f01b6b4f-f235-447c-aabc-026e2a26e090.png">

But @viceice mentioned her prefers not to "blow out" the table with large definitions, which is separate from how it looks or not.

**Comment by HonkingGoose** [comment]
I like having the JSON default setting _inside_ the table layout. I'd be even better if you can get syntax highlighting working as well. :wink: 

Putting the JSON output for `default` objects outside of the table makes it hard to see what's "default settings from the object" and what's configuration examples from the docs.

I'd like to avoid this:

| Name | Value |
| --- | --- |
| item | item |

```json
{
  "enabled": false,
  "recreateClosed": true,
  "rebaseStalePrs": true,
  "branchTopic": "lock-file-maintenance",
  "commitMessageAction": "Lock file maintenance",
  "commitMessageTopic": null,
  "commitMessageExtra": null,
  "schedule": [
    "before 5am on monday"
  ],
  "groupName": null,
  "prBodyDefinitions": {
    "Change": "All locks refreshed"
  }
}
```

---

We can probably try this one:

> <img alt="image" width="303" src="https://user-images.githubusercontent.com/6311784/173172732-f01b6b4f-f235-447c-aabc-026e2a26e090.png">
