### ISSUE TITLE
Dependency Dashboard not updated when upgrading from 32.50.2 -> 32.66.1

### ISSUE THREAD

**Issue by robertkowalski** [renovatebot/renovate#15808]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.50.2, 32.66.1, 32.70.0

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When updating from 32.50.2 to 32.66.1 the dependency dashboard for our monorepo is not updated any more. Using 32.70.0 also did not fix the issue

our repo is quite large:

```
       "stats": {
         "managers": {
           "dockerfile": {"fileCount": 2, "depCount": 3},
           "github-actions": {"fileCount": 2, "depCount": 4},
           "html": {"fileCount": 1, "depCount": 1},
           "npm": {"fileCount": 353, "depCount": 7151},
           "regex": {"fileCount": 1, "depCount": 109}
         },
         "total": {"fileCount": 359, "depCount": 7268}
```

The debug log in `32.66.1` says it does update the Dependency dashboard (see log section). Checked PRs from the rate limited section are created / updated, but the Dashboard is not updated (checkmarks are staying and merged PRs are not removed)

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Ensuring Dependency Dashboard (repository=[REDACTED]/[REDACTED])
DEBUG: ensureIssue(Dependency Dashboard) (repository=[REDACTED]/[REDACTED])
DEBUG: Patching issue (repository=[REDACTED]/[REDACTED])
DEBUG: Issue updated (repository=[REDACTED]/[REDACTED])
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
This requires further troubleshooting by the user
