### ISSUE TITLE
Dynamic defaultRegistryUrls for gitlab-* datasources

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#15800]
### Describe the proposed change(s).

It would make our managers simpler if the gitlab-* (e.g. `gitlab-tags`) datasources can have a dynamic default registryUrl. i.e.
- If global.platform === 'gitlab' then use global.endpoint
- Else use gitlab.com

However defaultRegistryUrls are today a simple export, while the platform end endpoint aren't known until after config is read from disk/env/CLI. Example https://github.com/renovatebot/renovate/blob/c92f05223967b52738cd78f7f2202fe4b72781b8/lib/modules/datasource/gitlab-tags/index.ts#L20

Is there a way we could modify our `defaultRegistryUrls` definition so that it can be an array of strings or a function returning an array of strings? That way it can be returned dynamically and be "lazily" loaded.

**Comment by rarkins** [comment]
yes, when docs are generated it should "fail" gracefully to find an endpoint in global config and therefore default to gitlab.com

**Comment by rarkins** [comment]
First step: refactor defaultRegistryUrls to be a string or a function returning a string. Existing manages should not change.

Second step: update the gitlab-* datasources to export a function which then looks up the global config and returns `config.endpoint` if `config.platform === 'gitlab'`

**Comment by RahulGautamSingh** [comment]
> First step: refactor defaultRegistryUrls to be a string or a function returning a string. Existing manages should not change.
> 
> Second step: update the gitlab-* datasources to export a function which then looks up the global config and returns `config.endpoint` if `config.platform === 'gitlab'`

Is it necessary to change the type of `defaultRegistryUrls` ? We use it as an array in all datasources and some managers too (nuget, sbt, maven, terraform).

**Comment by viceice** [comment]
yes, should be `string[] | () => string[]`, so no need to change existing datasources.
should also be done in a first refactor PR.

**Comment by RahulGautamSingh** [comment]
> First step: refactor defaultRegistryUrls to be a string or a function returning a string. Existing manages should not change.
> 
> Second step: update the gitlab-* datasources to export a function which then looks up the global config and returns `config.endpoint` if `config.platform === 'gitlab'`
> 
> EDIT: should continue to return an array of strings, not a string

`platform` isn't a property of `GlobalConfig` or `RepoGlobalConfig` either...

**Comment by RahulGautamSingh** [comment]
> First step: refactor defaultRegistryUrls to be a string or a function returning a string. Existing manages should not change.
> 
> Second step: update the gitlab-* datasources to export a function which then looks up the global config and returns `config.endpoint` if `config.platform === 'gitlab'`
> 
> EDIT: should continue to return an array of strings, not a string

Correct me if I am wrong, the function will be used like this:
 
 ```override readonly defaultRegistryUrls = newFunc;```
 
 `gitlabci-include` 
 ```
  dep.registryUrls = [
           ...defaultRegistryUrls()
          ];
 ```

**Comment by rarkins** [comment]
I think you need to add `platform` to global config next.

Then redefine `defaultRegistryUrls` like so:

```diff
diff --git a/lib/modules/datasource/index.ts b/lib/modules/datasource/index.ts
index 803d70b0c..e32cdf0b8 100644
--- a/lib/modules/datasource/index.ts
+++ b/lib/modules/datasource/index.ts
@@ -202,7 +202,9 @@ function resolveRegistryUrls(
         'Custom registries are not allowed for this datasource and will be ignored'
       );
     }
-    return datasource.defaultRegistryUrls ?? [];
+    return is.function_(datasource.defaultRegistryUrls)
+      ? datasource.defaultRegistryUrls()
+      : datasource.defaultRegistryUrls ?? [];
   }
   const customUrls = registryUrls?.filter(Boolean);
   let resolvedUrls: string[] = [];
diff --git a/lib/modules/datasource/types.ts b/lib/modules/datasource/types.ts
index c01732430..0c3b48c9e 100644
--- a/lib/modules/datasource/types.ts
+++ b/lib/modules/datasource/types.ts
@@ -74,7 +74,7 @@ export interface DatasourceApi extends ModuleApi {
   id: string;
   getDigest?(config: DigestConfig, newValue?: string): Promise<string | null>;
   getReleases(config: GetReleasesConfig): Promise<ReleaseResult | null>;
-  defaultRegistryUrls?: string[];
+  defaultRegistryUrls?: string[] | (() => string[]);
   defaultVersioning?: string;
   defaultConfig?: Record<string, unknown>;

```
