### ISSUE TITLE
platformAutomerge doesn't work on GitHub Enterprise Server (GHE)

### ISSUE THREAD

**Issue by DavidSimner** [renovatebot/renovate#15847]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.71.0

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

3.3.4

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

[In GitHub Enterprise Server (GHE) version `3.1.0` released `June 03, 2021` support was added for Pull Request Auto-Merge.](https://docs.github.com/enterprise-server@3.1/admin/release-notes#pull-request-auto-merge)

Later that year, on `2 Nov 2021` I can see https://github.com/renovatebot/renovate/issues/12464 was opened to Disable platform automerge for **unsupported** GHE versions.

However, when that issue was closed by https://github.com/renovatebot/renovate/pull/12483 it Disabled platform-native automerge for **all** GHE versions.

This means that I cannot use `platformAutomerge` with the version of GHE that we use.

Please can you change the logic introduced by https://github.com/renovatebot/renovate/pull/12483/files so that `platformAutomerge` works on GHE versions `>= 3.1.0`

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
It also requires that the graphql mutation is available in GHE. Previously it was not (and also undocumented that it was missing)

**Comment by rarkins** [comment]
Actually, I am closing/deleting as this is an invalid bug report. Recreate as a feature request
