### ISSUE TITLE
Port branchList to GitLab

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#1588]
Porting `branchList` caching from GitHub to GitLab would reduce the number of requests sent

**Comment by rarkins** [comment]
@adam-moss you may be interested in this to help reduce queries.

**Comment by adam-moss** [comment]
Thanks, may take a look, at the moment I'm looking at whether it is possible to get rebasing working to allow automerge to be truly effective with fast_forward.

**Comment by rarkins** [comment]
Do you want to create an issue to discuss what you’re trying to do?

**Comment by adam-moss** [comment]
Haven't done anything over than initial looksee currently, it is basically porting https://github.com/renovateapp/renovate/blob/master/lib/platform/gitlab/index.js#L105 from https://github.com/renovateapp/renovate/blob/master/lib/platform/gitlab/index.js#L184 and https://github.com/renovateapp/renovate/blob/master/lib/platform/github/index.js#L203 from https://github.com/renovateapp/renovate/blob/master/lib/platform/github/index.js#L348 in concept

**Comment by rarkins** [comment]
@adam-moss I think the repo may have changed since you copied those line numbers. Could you paste again with the "permalink" option?

![image](https://user-images.githubusercontent.com/6311784/37207979-d6d56f82-239f-11e8-8e61-e10a34ea8d41.png)

**Comment by rarkins** [comment]
I'm guessing though that you're referring to stale/rebase detection.

Yes, `isBranchStale()` is a good one to implement!

You don't really *need* to implement the `getRepoForceRebase()` for self-hosted though. You could just enable the setting `rebaseStalePrs` on your bot or per-repository to manually enable stale rebasing. That `getRepoForceRebase()` option is only used on GitHub to autodetect that setting or not.

**Comment by adam-moss** [comment]
Yes, I have `rebaseStalePrs` set but since `isBranchStale` is unimplemented in GitLab it doesn't actually take affect as far as I can tell through the, admittedly limited, testing I've done.

**Comment by rarkins** [comment]
Yep that's what I'd expect. Once you can implement `isBranchStale()` then it should work as you expect. I created #1626 to it so you can add any future discussion there

**Comment by rarkins** [comment]
Not necessary now that we have gitFs for GitLab
