### ISSUE TITLE
Dependency dashboard  undefined currentValue

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#15906]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Repository list on dependency dashboard shows `undefined` when no `currentValue` is used:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/6311784/172125557-29af3fd5-907a-4ff9-9d8a-650d2b2ece79.png">

### Relevant debug logs

Not relevant

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
should probably show the current digest if available then or a place-holder

**Comment by rarkins** [comment]
Yep, currentDigest would be preferred
