### ISSUE TITLE
Failed to look up dependency express

### ISSUE THREAD

**Issue by Giancarlo1974** [renovatebot/renovate#15913]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### Please select which platform you are using if self-hosting.

Bitbucket Server

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

I use renovate via helm chart on kubernetes
I have problems only on one repository
And I don't understand why

In the first PR i got:

Detected Package Files
docker-compose.yml (docker-compose)
package.json (npm)
What to Expect
It looks like your repository dependencies are already up-to-date and no Pull Requests will be necessary right away.
⚠ **Dependency Lookup Warnings** ⚠
Please correct - or verify that you can safely ignore - these lookup failures before you merge this PR.
Failed to look up dependency @chilkat/ck-node16-linux64
Failed to look up dependency async
Failed to look up dependency body-parser
Failed to look up dependency compression
Failed to look up dependency cors
Failed to look up dependency dotenv
Failed to look up dependency errorhandler
Failed to look up dependency express
Failed to look up dependency express-flash
Failed to look up dependency express-session
Failed to look up dependency express-validator
Failed to look up dependency helmet

### Can you explain how to fix Dependency Lookup Warnings ?

Why can't it work on dependencies like express?
What did I do wrong?

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
This is unsufficient information for a bug report and is being deleted. Please raise a discussion instead of bug report for any future questions you have.
