### ISSUE TITLE
Dependency dashboard - add option to open all "Pending Approval" PRs and "Rate limited" PRs

### ISSUE THREAD

**Issue by betterPeleg** [renovatebot/renovate#15912]
### What would you like Renovate to be able to do?

In 2 of the dependency dashboard sectors - "Pending Approval" and "Rate limited", add an option to manually open all pending PRs. a small feature to add to save some manual work to the user

1. add checkbox - "Approve all pending PRs"
note - will be top checkbox - differentiate then rest of PR checkboxes
![image](https://user-images.githubusercontent.com/102745725/172185481-21657c69-0c5f-4856-a744-e99fb9fc98c6.png)

2. add checkbox - "Approve opening all rate-limited PRs"
note - will be top checkbox - differentiate then rest of PR checkboxes
![image](https://user-images.githubusercontent.com/102745725/172185904-f3d690df-28a0-4f5f-b589-e0036de38208.png)

### If you have any ideas on how this should be implemented, please tell us here.

no

### Is this a feature you are interested in implementing yourself?

No

**Comment by betterPeleg** [comment]
Hi @rarkins,
a few questions on current Renovate behavior to help implementation:
1. say we have a pending approval PR. Once i check one of the suggestions (and approve it), a PR will be opened. now the current behavior of Renovate is to move the checked line of the "pending approval" to the "Open" section in the dependency dashboard? or simply leave it in the pending approval section?
2. Once we check a PR in the dashboard (and manually ask for its creation), does renovate riggers its run automatically? or do we wait for next scheduled Renovate run?

**Comment by rarkins** [comment]
1. This will be taken care of by Renovate automatically and it will be moved to the Open list
2. If it's the app, which supports webhooks, then yes.

**Comment by betterPeleg** [comment]
thanks.
also, do you think we need to create an option to revert the "open all" decision?
or simply once opening all PRs we will treat them as regular open PRs?

**Comment by rarkins** [comment]
You can't revert it, but the checkbox should be reset to unchecked after the opening is done (so that future ones aren't opened automatically)
