### ISSUE TITLE
Notify Project of Deprecation Notifications

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovatebot/renovate#1592]
While running an on-premise instance of Renovate, I came across the following output:

```bash
"stderr": "warning vue-test-utils@1.0.0-beta.11: VUE-TEST-UILS WARN: vue-test-utils has moved to a scoped package. The new repository is available @vue/test-utils. To install the new package, run npm install --save-dev @vue/test-utils\n..."
```

The output was part of a lockfile maintenance task.

Turns out there's a project that has the following in their `package.json` file:

```json
"vue-test-utils": "1.0.0-beta.11"
```

As noted by the output above, `vue-test-utils` has [moved to a scope on the npm registry](https://www.npmjs.com/package/@vue/test-utils).

The original `vue-test-utils` package has been fully deprecated:

```bash
> yarn info vue-test-utils | grep deprecated
deprecated: 'VUE-TEST-UILS WARN: vue-test-utils has moved to a scoped package. The new repository is available @vue/test-utils. To install the new package, run npm install --save-dev @vue/test-utils',
```

There's no notification mechanism to make that team aware (except if they run `yarn install`).

**Proposal**

Check for the `deprecated` property at the top-level of a package's metadata, and if `deprecated` is set, file issue against the repository indicating that their dependency has been deprecated, along with the deprecation notice.

**Comment by rarkins** [comment]
So this relates to direct dependencies of a package only, when that package is using Renovate?

**Comment by destroyerofbuilds** [comment]
This particular instance is a project with Renovate installed and a direct `devDependency` on `vue-test-utils`.

**Comment by rarkins** [comment]
OK. We already query the registry for every package in a `package.json`, so it's not even any extra network requests to also check the `deprecated` field.

I think the easiest logically would be for us to have a single issue named something like "Dependency deprecation warning" that would contain a list of all direct dependencies that are flagged as deprecated. Of course in most cases it should be just one package at a time.

Having a single issue has the benefit of (a) less noise, (b) less impact if we have false positives, and (c) gives us the ability to automatically close such an issue once it is no longer applicable.

**Comment by destroyerofbuilds** [comment]
> have a single issue

A few questions regarding that approach:
* I assume Renovate would update the initial comment in the issue, and as a result, when a new deprecated dependency is added to the list, there is no additional notification sent to that project (I would assume a one-time notice would be nice, but then the whole point of using a single issue is to avoid one notice per deprecation).
* Discussions may occur on that issue related to a deprecated dependency (A team might discuss their best option for replacing the deprecated dependency), but because all deprecations share the same issue, the issue will grow indefinitely over time, and each subsequent deprecation will force that project team to wade through all previous discussions.
* Assuming an issue that is currently tracking two or more deprecations, how will the issue be updated to notify participants that one of the deprecated dependencies has been resolved?
* Would re-opening a previously closed issue cause previous participants, which may no longer be associated with the project, to receive notifications?

**Comment by rarkins** [comment]
@destroyerofbuilds good points, thanks for adding them. I think you may be right that those are desirable goals and would be next to impossible to meet with a single issue.

On the flip side, having one issue per dependency warning would probably mean that a MVP of this feature would not include the capability to automatically *close* resolved issues - humans would need to do that.

**Comment by destroyerofbuilds** [comment]
> (a) less noise

Can we still leverage the grouping feature available in Renovate for grouping related libraries?

For example, when AngularJS (1.x) is finally `deprecated`, it's likely all support libraries, such as `angular-animate`, will be deprecated as well. I don't believe it would be meaningful to have separate issues per Angular dependency since they are all tightly coupled. To remove one you would basically need to switch your entire framework, leading to the removal of all Angular 1.x components.

> a MVP of this feature would not include the capability to automatically close resolved issues - humans would need to do that.

It might not actually be that unnatural. It's likely that once a deprecation notice is filed as an issue, the team would simply push a new commit to their `master` branch with `fixes #ISSUE` as a footer. So it's quite likely that deprecation notification issues will simply get resolved naturally.

Now, it's also possible someone will not use the `fixes` feature, and the issue will remain around. So eventually they will need to be cleaned up.

**Comment by rarkins** [comment]
I like automatically closing things for cases where Renovate screws up or needs cleaning up :)

**Comment by rarkins** [comment]
To recap, let's do one issue per-dependency, e.g. "Fix Deprecated dependency: abc", that way we can check if the issue used to exist and was closed to prevent ourselves from recreating it endlessly if the users in the project prefer to ignore it and close the issue. Also, make sure to handle the case where the deprecated package is depended on in more than one location in the repository - we don't want errors and ideally would like to include all package files that contain it.

**Comment by rarkins** [comment]
I had a brief look at deprecated dependencies today thanks to @edmorley. Unfortunately the npmjs approach to this is not very semantic. Here are 3 examples:

**verdaccio**
They published a version `3.0.0-test.1` prior to alpha/beta. Unfortunately it shows up as newer than `3.0.0-beta.10` using `semver`. The maintainers deprecated it with a message `this`.

**validate-commit-msg**
Every version is deprecated here with the message `Check out CommitLint for a more focused experience..`

**eslint-config-xo**
Only the very last version (v1.0.0) has a deprecation notice: `"Renamed to eslint-plugin-unicorn"`

So I started off by updating Renovate code to ignore any deprecated version. This solved `verdaccio` but badly impact the other two. For `eslint-config-xo` it means that we raised rollback PRs, which were highly undesirable.

Ideal behaviour is that we could - somehow - ignore the `3.0.0-test.1` version from `verdaccio` and raise warning issues for `eslint-config-xo` and `validate-commit-msg`. In an ideal world we'd even have a registry or renamed packages and raise a PR for `eslint-config-xo` -> `eslint-config-unicorn` instead

**Comment by edmorley** [comment]
> In an ideal world we'd even have a registry or renamed packages and raise a PR for eslint-config-xo -> eslint-config-unicorn instead

I think this would be ideal, and for me probably avoid the need for notifications entirely.

In one of our main project we've already had two different packages have renames, causing us to think we were up to date, but in fact were not. (`angular-ui-router` -> `@uirouter/angularjs`, `font-awesome` -> `@fortawesome/...`.)

Plus there's the upcoming babel renames too.

**Comment by rarkins** [comment]
After renames, did the new repositories mark the old package versions as deprecated, and did they "reset" versioning (e.g. back to v1.0.0) or did they continue incrementally from the latest commit from the old package name?

I think the info in the npmjs registry is unfortunately not semantic enough to act on automatically but maybe we just have a community-contributed JSON object with known mappings. Also, once I add the deprecation notification feature I will probably grep logs for those regularly and be able to catch most of them myself (assuming the old project was marked as deprecated).

**Comment by edmorley** [comment]
For Babel/Neutrino/Font Awesome they continued the same versioning scheme. For @uirouter/angularjs the version was reset.

**Comment by rarkins** [comment]
Sounds like we'd probably just need to pick `latest` of the new package (regardless of whether its version is earlier, same or even a major bump) and put the appropriate warning in the PR that the user needs to verify it themselves carefully.

**Comment by destroyerofbuilds** [comment]
> I think the info in the npmjs registry is unfortunately not semantic enough to act on automatically

I agree. Are there any know upstream issues filed for adding additional semantic information to package metadata to provide a hint as to the successor package?

> maybe we just have a community-contributed JSON object with known mappings

Personally, this sounds like a really bad idea. We would need to confirm that the contributor to this JSON file was the owner of at least the original package, though I would also prefer we had some way to confirm that they have permissions from its replacement package owner.

**Comment by destroyerofbuilds** [comment]
> Ideal behaviour is that we could - somehow - ignore the 3.0.0-test.1 version from verdaccio

This seems like it would be quite difficult since `verdaccio` has basically chosen to use a versioning scheme that does not comply with Semantic Versioning. Supporting `verdaccio` would open the gates to supporting anyone else that wants a custom, non-compliant Semantic Version, versioning scheme.

**Comment by edmorley** [comment]
> We would need to confirm that the contributor to this JSON file was the owner of at least the original package

This wouldn't be necessary I don't think? The reviewer of the PR would simply visit the old package repo/docs, see that it says "we've renamed our package to X", and then approve/merge the PR. (ie: the same as someone reviewing a PR against `renovate-config` that adds a new monorepo package group.)

**Comment by edmorley** [comment]
(But I agree at least getting issues on file against npmjs.com having more useful metadata for this case would be useful)

**Comment by destroyerofbuilds** [comment]
> The reviewer of the PR would simply visit the old package repo/docs, see that it says "we've renamed our package to X", and then approve/merge the PR.

@edmorley, thank you. I can see that as a way to validate a package mapping.

The downsides I see are:
* Can't be automatically updated (What if the replacement package is, itself, deprecated, and the originally deprecated package is re-pointed to something else?)
* Only works for those packages that indicate the replacement package in a verifiable way.
* A resource intensive process in an ecosystem that's growing quickly (begs the question, how many npm packages are there today?)

None of them blockers.

**Comment by destroyerofbuilds** [comment]
I did not find any existing issues so I filed - https://github.com/npm/registry/issues/323
