### ISSUE TITLE
Missing changelog/release notes for python packages with Pipenv

### ISSUE THREAD

**Issue by KOliver94** [renovatebot/renovate#15938]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Hi,

I started a discussion (#15892) but as I didn't get any solution, I will consider it as a bug.

The problem is that python packages (most of them) does not have any release notes or changelogs when using Pipenv as package manager even though all of the packages are from pypi and publicly accessible.

It seems like Renovate does not manage to extract the necessary URLs. All of the packages lack release notes or even link to the repo, except those which are defined here I guess:
https://github.com/renovatebot/renovate/blob/9f50a7d668fa0e6d56af02005bdb0531691ac025/lib/modules/datasource/metadata-manual.ts#L19-L47

See for example KOliver94/bss-request-manager#785 or KOliver94/bss-request-manager#779.

Minimal reproduction: [KOliver94/renovate-changelog-issue](https://github.com/KOliver94/renovate-changelog-issue)

### Relevant debug logs

<details><summary>Logs</summary>

```
{
  "config": {
    "pipenv": [
      {
        "packageFile": "Pipfile",
        "deps": [
          {
            "depType": "packages",
            "depName": "jsonschema",
            "managerData": {},
            "currentValue": "==4.5.0",
            "datasource": "pypi",
            "depIndex": 0,
            "warnings": [],
            "versioning": "pep440",
            "currentVersion": "4.5.0",
            "isSingleVersion": true,
            "fixedVersion": "4.5.0",
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "4.6.0",
                "newValue": "==4.6.0",
                "newMajor": 4,
                "newMinor": 6,
                "updateType": "minor",
                "isRange": true,
                "branchName": "renovate/jsonschema-4.x"
              }
            ]
          },
          {
            "depType": "packages",
            "depName": "sentry-sdk",
            "managerData": {},
            "currentValue": "==1.5.10",
            "datasource": "pypi",
            "depIndex": 1,
            "warnings": [],
            "versioning": "pep440",
            "currentVersion": "1.5.10",
            "isSingleVersion": true,
            "fixedVersion": "1.5.10",
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "1.5.12",
                "newValue": "==1.5.12",
                "newMajor": 1,
                "newMinor": 5,
                "updateType": "patch",
                "isRange": true,
                "branchName": "renovate/sentry-sdk-1.x"
              }
            ]
          }
        ],
        "registryUrls": [
          "https://pypi.org/simple"
        ],
        "lockFiles": [
          "Pipfile.lock"
        ],
        "constraints": {
          "python": "== 3.10.*"
        }
      }
    ]
  }
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
First step is to see if this reproduces locally. If changelogs are present locally, but missing for the app, then we need to work out why.

**Comment by Gabriel-Ladzaretti** [comment]
This reproduces when self hosted as well.

briefly debugging this show that `getSimpleDependency` from `lib/modules/datasource/pypi/index.ts` which is invoked, does not set the `sourceUrl` prop which seems to be used to fetch the changelogs.

while `getDependency` which uses the pypi api does handle this prop. 
not sure if `https://pypi.org/simple/` api provide this info.

**Comment by viceice** [comment]
simple api don't provide `sourceUrl`. I discussed with @rarkins some time ago, that we should automatically replace `https://pypi.org/simple/` with `https://pypi.org/pypi/` in pypi datasource.

**Comment by viceice** [comment]
So add something like `if (registryUrl === 'https://pypi.org/simple') registryUrl = 'https://pypi.org/pypi'` here

https://github.com/renovatebot/renovate/blob/10302eba68fba11b8e6aa667529d64d708a54d97/lib/modules/datasource/pypi/index.ts#L37-L42

Tryling slash is removed by upper layer, so we don't check that here
