### ISSUE TITLE
Proget npm packaged returns 404 because of url encoding

### ISSUE THREAD

**Issue by mieliespoor** [renovatebot/renovate#15942]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

7.21

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When trying to resolve npm packages from Proget, some packages fails to resolve because the url encoding make using of a capital `F` when replacing the `/` instead of lowercase. 

### Relevant debug logs

<details><summary>Logs</summary>

```
"https://private.npm.host/npm/npm/@angular%2Fanimations (GET,404)": 1,
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Please update the title, description and PR to make clear this is only known as a proget problem and NOT all of npm as keeps getting implied
