### ISSUE TITLE
Clear repo cache after repo recreation

### ISSUE THREAD

**Issue by bmarwell** [renovatebot/renovate#15955]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

In the dependency dashboard, I have 5 update "tasks" (checkboxes).
But they are referring to PRs I created, not to PRs renovate created.

Ticking the checkbox does not do anything.

See for yourself: https://github.com/bmarwell/cowsay-liberty-feature/issues/1

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
I think it's linking to *issues* you created, not PRs?

It seems like none of these were created, either? Why do you say you want to "recreate" them?

**Comment by rarkins** [comment]
Fork is working fine: https://github.com/renovate-reproductions/15955/issues/3

**Comment by rarkins** [comment]
```
{"level":20,"msg":"getBranchPr(renovate/com.ibm.websphere.appserver.spi-com.ibm.websphere.appserver.spi.logging-1.x)","time":"2022-06-09T06:31:26.939Z"}
{"level":20,"msg":"findPr(renovate/com.ibm.websphere.appserver.spi-com.ibm.websphere.appserver.spi.logging-1.x, undefined, open)","time":"2022-06-09T06:31:26.940Z"}
{"level":20,"msg":"Found PR #2","time":"2022-06-09T06:31:26.940Z"}
{"level":20,"msg":"getBranchPr(renovate/org.apache.maven.plugins-maven-failsafe-plugin-3.x)","time":"2022-06-09T06:31:26.940Z"}
{"level":20,"msg":"findPr(renovate/org.apache.maven.plugins-maven-failsafe-plugin-3.x, undefined, open)","time":"2022-06-09T06:31:26.940Z"}
{"level":20,"msg":"Found PR #6","time":"2022-06-09T06:31:26.940Z"}
{"level":20,"msg":"getBranchPr(renovate/org.apache.maven.plugins-maven-surefire-plugin-3.x)","time":"2022-06-09T06:31:26.940Z"}
{"level":20,"msg":"findPr(renovate/org.apache.maven.plugins-maven-surefire-plugin-3.x, undefined, open)","time":"2022-06-09T06:31:26.940Z"}
{"level":20,"msg":"Found PR #7","time":"2022-06-09T06:31:26.940Z"}
{"level":20,"msg":"getBranchPr(renovate/org.apache.maven.plugins-maven-javadoc-plugin-3.x)","time":"2022-06-09T06:31:26.941Z"}
{"level":20,"msg":"findPr(renovate/org.apache.maven.plugins-maven-javadoc-plugin-3.x, undefined, open)","time":"2022-06-09T06:31:26.941Z"}
{"level":20,"msg":"Found PR #3","time":"2022-06-09T06:31:26.941Z"}
{"level":20,"msg":"getBranchPr(renovate/org.osgi-osgi.core-8.x)","time":"2022-06-09T06:31:26.941Z"}
{"level":20,"msg":"findPr(renovate/org.osgi-osgi.core-8.x, undefined, open)","time":"2022-06-09T06:31:26.941Z"}
{"level":20,"msg":"Found PR #5","time":"2022-06-09T06:31:26.941Z"}
{"level":20,"msg":"5 PRs are currently open","time":"2022-06-09T06:31:26.941Z"}
```

**Comment by zharinov** [comment]
Hi [bmarwell](https://github.com/bmarwell), have Renovate been used against the repository with the same name previously? Because my guess is that we're applying older repository cache against the newer repo that uses same cache key.

**Comment by bmarwell** [comment]
Yes, I was renaming the previous repo to -showcase and created a new repo which you see now.
Then I pushed to this new origin.

**Comment by rarkins** [comment]
OK, in this case it's a very rare edge case. I'll try to resolve it manually on the backend by deleting your cache later today.

**Comment by bmarwell** [comment]
Thanks, @rarkins!

Hint: What exactly would I need to do differently?

In other words (what I did):

* Create repo "a"
* Renamed "a" to "b"
* Created empty repo "a"
* Pushed local copy of "b"  to "a"

I see this is probably rare, but not unheard of.

**Comment by rarkins** [comment]
We're going to add code so that this edge case is detected/avoided automatically in future, so you won't have to do anything

**Comment by bmarwell** [comment]
Thanks! I also see the PRs popping up again. Do you want to leave this issue open to commit your edge case handling against it? Otherwise this can be closed.

**Comment by rarkins** [comment]
Yes, I manually cleared your cache on the server side so that's why it's working again. But let's leave this issue open as @zharinov is going to work out a way to detect such edge cases and correct them automatically in future.

**Comment by viceice** [comment]
aren't we doing that already? i remember @zharinov did something like that. 🤔

**Comment by zharinov** [comment]
- #17288

**Comment by rarkins** [comment]
So can be closed?
