### ISSUE TITLE
pnpmv7: config global --global, --local are deprecated. Use --location=global instead.

### ISSUE THREAD

**Issue by psteinroe** [renovatebot/renovate#15959]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

After an update to pnpm v7, we are receiving the following artifact update error:

File name: **pnpm-lock.yaml**
```npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.```

### Relevant debug logs

<details><summary>Logs</summary>

```
Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/getmateo/monorepo\":\"/mnt/renovate/gh/getmateo/monorepo\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/getmateo/monorepo\" docker.io/renovate/node bash -l -c \"install-tool pnpm 7.1.9 && pnpm install --recursive --lockfile-only --ignore-scripts --ignore-pnpmfile\"\nnpm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/getmateo/monorepo\":\"/mnt/renovate/gh/getmateo/monorepo\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/getmateo/monorepo\" docker.io/renovate/node bash -l -c \"install-tool pnpm 7.1.9 && pnpm install --recursive --lockfile-only --ignore-scripts --ignore-pnpmfile\"\nnpm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.\n\n    at ChildProcess.exithandler (child_process.js:383:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:475:12)\n    at maybeClose (internal/child_process.js:1058:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
looks like the npm warning is hiding again the real error 😕

**Comment by psteinroe** [comment]
> looks like the npm warning is hiding again the real error 😕

You are completely right, thanks for the hint. I went through the breaking changes in v7 and played around with the settings. It seems like there was a peer deps error, and setting `strict-peer-dependencies=false` fixed the issue.

**Comment by viceice** [comment]
- containerbase/buildpack#399

That PR should help to see the real error

**Comment by Abdullatif-Erfan** [comment]
For windows, I recommend testing another version of nodejs.
1. unistall node.js from control panel
2. Remove two folders manually from
![2](https://user-images.githubusercontent.com/60866963/173174857-101d6cef-9d16-4cc1-ab8e-bbead2b505b2.JPG)

4. download the older or recent version from this link:  (https://nodejs.org/en/download/releases)
5. install it and add to ENV variable
![env](https://user-images.githubusercontent.com/60866963/173175105-4a1ad7ad-5382-44db-abbb-11d1dc355bde.JPG)
