### ISSUE TITLE
Renovating .gitlab-ci.yml file

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/renovate#1598]
Hello,

I need to do some more thinking around this one but in principle would you have any concerns with adding support for renovating `.gitlab-ci.yml` files?

I'm thinking similar to Dockerfile where they contain an `image:` tag, and possibly something smart to ensure when an image like `node:alpine` is used this is aligned with an `.nvmrc` (if present).

Cheers

**Comment by rarkins** [comment]
Sounds fine. `.travis.yml` and `.nvmrc` are fairly recent additions.

I think the best way to align multiple node locations is to pin them to exact versions and let Renovate do the rest :). It can be a little tricky to get them all in to the same branch/PR though, although that works with `.travis.yml` and `.nvmrc` already and could be tweaked to include Docker and this gitlab ci file.
