### ISSUE TITLE
Check only for updates to the Gradle version catalogs used

### ISSUE THREAD

**Issue by chachako** [renovatebot/renovate#15996]
### What would you like Renovate to be able to do?

Add an option to troubleshoot all Gradle unused dependencies and ignore them so that they are not checked for updates

> There doesn't seem to be such a feature at the moment, so maybe I'm missing something?

#### Motivation

In our team, we have pre-written version catalogs that contain dependencies that we may use between multiple projects, but not every project actually uses all of them, so it would be nice if renovatebot could automatically detect and ignore those that are not used :)

> Some similar examples:
https://github.com/Omico/gradle-common-version-catalogs
https://github.com/RedMadRobot/gradle-version-catalogs

### If you have any ideas on how this should be implemented, please tell us here.

The [Gradle's version catalogs](https://docs.gradle.org/current/userguide/platforms.html) seems to convert the dependencies defined in the `*.versions.toml` file into code accessors starting with the filename prefix, e.g. `apache.versions.toml` will generate a field named `apache`. So if we follow this rule, it should be easy to find all the dependencies that have been used?

For example, here is the definition of a version catalog file (`libs.versions.toml`):
```toml
[libraries]
groovy-core = "org.codehaus.groovy:groovy:3.0.5"
commons-lang3 = "org.apache.commons:commons-lang3:3.8"
```

Here is a `build.gradle.kts` file:
```kotlin
dependencies {
    implementation(libs.groovy.core)
}
```

According to the rules of file names and [aliases](https://docs.gradle.org/current/userguide/platforms.html#sub:mapping-aliases-to-accessors), we can search whether any `.gradle(.kts)` files refer to them according to `libs.groovy.core` and `libs.commons.lang3`, and then skip all unreferenced dependencies.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Sorry, not something we want to do.
