### ISSUE TITLE
Ability to have comments in renovate.json

### ISSUE THREAD

**Issue by agilenut** [renovatebot/renovate#16001]
### What would you like Renovate to be able to do?

I would like to be able to add comments to my renovate.json file. An example of why I'd like to have this is when I need to pin a specific dependency because of a known issue in later versions. I'd like to explain the current issue with the later versions and point to a GitHub issue so that others knew they could remove the rule once that issue was resolved.

### If you have any ideas on how this should be implemented, please tell us here.

Not sure

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Use renovate.json5

In future please create idea discussions instead of issues

**Comment by agilenut** [comment]
> Use renovate.json5

Ah. Didn't know that handled comments. Good tip. Thanks.

> In future please create idea discussions instead of issues

Will do. Thanks again.
