### ISSUE TITLE
Detect branch protection bypasses to avoid creating unnecessary automerging PRs

### ISSUE THREAD

**Issue by manuelmeister** [renovatebot/renovate#16037]
### What would you like Renovate to be able to do?

Github has a relatively new feature to bypass branch protection rules for certain actors. I would love for renovate to detect its own bypass capabilities or stop doing proactive checks.

We have branch protection rules to require 2 approves. Currently renovate creates a PR even if the commit passes CI and approves them with two bot accounts. This generates a lot of unnecessary noise and makes it harder for maintainer to focus on what's important.

Problem repo: https://github.com/ecamp/ecamp3/pulls/app%2Frenovate
More on the issue in discuss: https://github.com/renovatebot/renovate/discussions/15123

### If you have any ideas on how this should be implemented, please tell us here.

It could detect its own bypass capabilities _or_ stop doing proactive checks for branch protection rules.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Have you configured branch automerge or is that your goal?

**Comment by manuelmeister** [comment]
Yes, I think we want the automerge of "unproblematic" version updates. If the CI passes then it should not create a PR but merge it directly onto the main branch.
@BacLuc correct me if I'm wrong.
