### ISSUE TITLE
Docker tags list for library images not working (404) if Registry proxy is in use

### ISSUE THREAD

**Issue by BernhardGruen** [renovatebot/renovate#16040]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.64.0 (Problem first occurrred in that version. Problem still exists in 32.85.0) 

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

14.10.4

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Hello,

We are using Renovate Bot with our own Docker registry proxy (using the image registry:2.8.1).
Starting with 32.64.0 Renovate Bot was no longer able to get the _tags list_ of library images (like alpine, ubuntu, node, etc.). Listing of tags for non-library images (like renovate/renovate) still works fine.
The error was not present in version 32.63.1. The error is also not present if we don't use our proxy. But we have to use our proxy because of the rate limiting of the docker registry and also as part of our business continuity plan.

Renovate Bot / the registry shows a 404 since then (see debug logs).

We currently assume that the following PR could be the reason for the change in behavior: https://github.com/renovatebot/renovate/pull/15312/files

As we are using the official Docker Hub registry image we currently assume that the registry image (v2.8.1) is fully compatible with the HTTP v2 API from Docker itself.

Just for completeness this is our `renovate.json`:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":label(renovate)"
  ],
  "branchPrefix": "renovate-",
  "packageRules": [{
    "datasources": ["docker"],
    "registryUrls": ["https://our-private-proxy.companyname.com"]
  }]
}
```

If you need access to our Registry proxy (for tests) we can provide the full URL (privately).
If you are sure that Renovate Bot is working correctly and our Registry proxy is misbehaving please also let me now.

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Invalid registry response (repository=bgruen/renovate-test)
       "apiCheckUrl": "https://our-private-proxy.companyname.com/v2/alpine/tags/list?n=10000",
       "res": {
         "statusCode": 404,
         "body": "{\"errors\":[{\"code\":\"NAME_UNKNOWN\",\"message\":\"repository name not known to registry\",\"detail\":{\"name\":\"alpine\"}}]}\n",
         "headers": {
           "date": "Mon, 13 Jun 2022 07:50:09 GMT",
           "content-type": "application/json; charset=utf-8",
           "transfer-encoding": "chunked",
           "connection": "close",
           "vary": "Accept-Encoding",
           "docker-distribution-api-version": "registry/2.0",
           "x-content-type-options": "nosniff",
           "strict-transport-security": "max-age=15724[80](https://gitlab.companyname.com/bgruen/renovate-test/-/jobs/1289008#L80)0; includeSubDomains",
           "content-encoding": "br"
         },
         "authorization": false
       }
```
Please note that the path `https://our-private-proxy.companyname.com/v2/library/alpine/tags/list?n=10000` works fine.

</details>

### Have you created a minimal reproduction repository?

[reproduction repository](https://github.com/jmueller42/renovate-docker-404)

**Comment by BernhardGruen** [comment]
Hello,

Thank you for your fast response.
We just tested this morning with 32.83.3 and the error still exists.
Please note that I specified 32.64.0 as it is the first version that did not work and 32.63.1 was the last version that worked for us.

**Comment by viceice** [comment]
I think we need something like this as fallback:

https://github.com/renovatebot/renovate/blob/fcc1a8f6198bd03a9f1369c67f951fb20743a6c9/lib/modules/datasource/docker/index.ts#L767-L772

**Comment by BernhardGruen** [comment]
Thank you for your insight into the Renovate code. @viceice 
I am not a Type Script developer but my rudimentary understanding of that code is that it should already handle that case - at least if `getDockerApiTags` does not error with `ExternalHostError` (https://github.com/renovatebot/renovate/blob/fcc1a8f6198bd03a9f1369c67f951fb20743a6c9/lib/modules/datasource/docker/index.ts#L764).

If I understand correctly we'll have to provide a minimal reproduction example, right? And this example should be placed on github.com.

**Comment by jmueller42** [comment]
Hi, 

i created a very small example.
You can find it here: https://github.com/jmueller42/renovate-docker-404

**Comment by rarkins** [comment]
Reproduction forked to https://github.com/renovate-reproductions/16040

**Comment by PhilipAbed** [comment]
i was able to reproduce using the following commands:
```
docker run -d -p 5000:5000 -e REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io" registry:latest
docker run -it -v "C:\github\renovate\config.js:/usr/src/app/config.js" --network host renovate/renovate
```

**Comment by TilmannBach** [comment]
i'm experiencing the same problem with Artifactory as docker hub proxy. it worked before (i dont know which versions). but it dont work with current version 32.89.0

"official images" are affected, like: `mysql` or `traefik`

```log
 WARN: Invalid registry response (repository=faro/faro-helm-chart)
       "apiCheckUrl": "https://dockerhub.devops.mycompany.de/v2/mysql/tags/list?n=10000",
       "res": {
         "statusCode": 404,
         "body": {
           "errors": [
             {
               "code": "NAME_UNKNOWN",
               "message": "Repository name not known to registry.",
               "detail": {"name": "mysql"}
             }
           ]
         },
         "headers": {
           "date": "Fri, 17 Jun 2022 06:39:13 GMT",
           "content-type": "application/json",
           "transfer-encoding": "chunked",
           "docker-distribution-api-version": "registry/2.0",
           "x-artifactory-id": "***********",
           "x-artifactory-node-id": "prod-artifactory-ha-artifactory-ha-primary-0",
           "x-jfrog-version": "Artifactory/7.19.10 71910900",
           "connection": "close"
         },
         "authorization": false
       }
DEBUG: Failed to get authHeaders for getTags lookup (repository=faro/faro-helm-chart)
DEBUG: Failed to look up dependency dockerhub.devops.mycompany.de/mysql (repository=faro/faro-helm-chart, packageFile=values.yaml, dependency=dockerhub.devops.mycompany.de/mysql)
```

**Comment by rarkins** [comment]
@TilmannBach if you query `https://dockerhub.devops.mycompany.de/v2/mysql/tags/list?n=10000` do you get the same error, and can you confirm if `https://dockerhub.devops.mycompany.de/v2/library/mysql/tags/list?n=10000` works instead?

**Comment by TilmannBach** [comment]
@rarkins i can confirm that using postman against our artifactory we see the exact behavior you expected:
* https://dockerhub.devops.mycompany.de/v2/mysql/tags/list?n=10000 -> 404
* https://dockerhub.devops.mycompany.de/v2/library/mysql/tags/list?n=10000 -> 200 OK with json response containing container version tags like this:
```json
{
    "name": "library/mysql",
    "tags": [
        "5",
        "5-debian",
        "5-oracle",
         ...
        ]
}
```

**Comment by rarkins** [comment]
OK, that confirms we should the `library/` fallback even when it's a custom registry

**Comment by PhilipAbed** [comment]
@MaronHatoum is investigating the issue and will try to resolve it, he will let you know, no worries it's in good hands

**Comment by MaronHatoum** [comment]
After investigating the issue I found that we are trying to get the tags using this local URL: http://localhost:5000/v2/alpine/tags/list?n=10000
https://github.com/renovatebot/renovate/blob/93c2d053a33fc283ec14534323d976ee0810ffc7/lib/modules/datasource/docker/index.ts#L62-L65
when trying to call the API above we are getting response code 404 (not found) and as I saw in the code we are not handling this case.
**The suggested solution** is to throw a fallback exception when getting response code 404 from `http.getJson()` and catch this exception in:

https://github.com/renovatebot/renovate/blob/93c2d053a33fc283ec14534323d976ee0810ffc7/lib/modules/datasource/docker/index.ts#L767-L772

**Comment by BernhardGruen** [comment]
Hey,

in case someone else needs a quick and dirty workaround for this (assuming using a Kubernetes Ingress):
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /v2/library/$1/$2$3
  name: registry-proxy-http-test-rewrite
spec:
  ingressClassName: nginx
  rules:
  - host: registry-proxy-test.domain.loc
    http:
      paths:
      - backend:
          service:
            name: registry-proxy
            port:
              name: http
        path: /v2/([a-z0-9-]+)/(blob|manifests|tags)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - registry-proxy-test.domain.loc
    secretName: registry-proxy-test-tls-sec
```
This translates roughly into the following nginx configuration snippet:

```nginx
location ~* "^/v2/([a-z0-9-]+)/(blob|manifests|tags)(.*)" {
    rewrite "(?i)/v2/([a-z0-9-]+)/(blob|manifests|tags)(.*)" /v2/library/$1/$2$3 
break;
    proxy_pass http://registry-proxy-service
}
```

I really hope this helps someone.

**Comment by TilmannBach** [comment]
thank you guys for the fix. it is working now :)
