### ISSUE TITLE
Add support for Hermit

### ISSUE THREAD

**Issue by lyonlai** [renovatebot/renovate#16119]
### What would you like Renovate to be able to do?

Hello from Square Cash. We would like Renovate to be able to support Hermit, our open sourced self-bootstrapping software project tool manager. For more details, please see https://cashapp.github.io/hermit/

### If you have any ideas on how this should be implemented, please tell us here.

Yes. We have successfully make this feature happen in our fork. It has the following features

1. Hermit manager that manages the hermit dependencies, which includes its datasource & versioning
2. Hermit as a binary source. This enables renovate to use the tooling version defined with the software project. e.g. different projects might have defined different version of `go`, and the `hermit` binarySource makes renovate use the version respectively.

This feature has been well tested with quite a few projects internally for some time. We now would like to make the upstream contribution. PR is coming soon

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
Hi @lyonlai, thanks for your proposal. It sounds good, and although you already have a working version you may still find it useful to fill out the new package manager questionnaire to make sure there's nothing you've overlooked

**Comment by lyonlai** [comment]
sure thing, I'll fill out the questionnaire soon.

**Comment by lyonlai** [comment]
# New package manager questionnaire

**Did you read our documentation on adding a package manager?**

- [X] I've read the [adding a package manager](adding-a-package-manager.md) documentation.

## Basics

### Name of package manager
Hermit

### What language does this support?
It's a tool manager not specifically tied to any programming language.

### How popular is this package manager?
Hermit is quite popular in Square. And we are the main user of Hermit. Since it's been open sourced, we also have users from outside of Square.

We have some user number stats indicating around 700 users/day

### Does this language have other (competing?) package managers?

- [ ] Yes 
- [X] No

---

## Package File Detection

### What type of package files and names does it use?
Hermit doesn't really have a centralised package file like `package.json` from `npm` nor `go.mod` from `golang`. It record its tool version in the name of the symlink.

### What [fileMatch](../usage/configuration-options.md/#filematch) pattern(s) should be used?
`bin/hermit` is the file pattern we are looking for. And `bin/hermit` in nested directories are supported

### Is it likely that many users would need to extend this pattern for custom file names?

- [ ] Yes
- [X] No

### Is the fileMatch pattern likely to get many "false hits" for files that have nothing to do with package management?

Not really


---

## Parsing and Extraction

### Can package files have "local" links to each other that need to be resolved?

Nope, even in a nested directory setup of hermit. Package files don't link to each other.

### Is there a reason why package files need to be parsed together (in serial) instead of independently?

### What format/syntax is the package file in?

- [ ] JSON
- [ ] TOML
- [ ] YAML
- [X] Custom (explain below)

Hermit doens't really have a package file like others (e.g. npm & golang)

Hermit uses `hermit list --json` command to extract the installed packages. 

### How do you suggest parsing the file?

- [X] Off the shelf parser (JSON)
- [ ] Using regex
- [ ] Custom-parsed line by line
- [ ] Other

### Does the package file structure distinguish between different "types" of dependencies? e.g. production dependencies, development dependencies, etc?

- [ ] Yes, production and development dependencies
- [X] No, all dependencies are treated the same

### List all the sources/syntaxes of dependencies that can be extracted
It's a structured JSON output.

Example: 
```
[
{
    "Description": "Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.",
    "Homepage": "",
    "Repository": "https://github.com/golang/go",
    "Reference": {
      "Name": "go",
      "Version": "1.17",
      "Channel": ""
    },
}
...
]
```

### Describe which types of dependencies above are supported and which will be implemented in future

N/A

---

## Versioning

### What versioning scheme does the package file(s) use?
Hermit uses a mix of Semver & Channel

For semver we support major.minor.patch_update-prerelease+compatibilities

Hermit has a concept called [Channel](https://cashapp.github.io/hermit/packaging/reference/#channels), it's either custom defined or generated. 

Channels are marked as unstable versions as they will auto update to the latest if new versions are available.

### Does this versioning scheme support range constraints, e.g. `^1.0.0` or `1.x`?

- [ ] Supports range constraints (e.g `^1.0.0` or `1.x`)
- [X] No

### Is this package manager used for applications, libraries, or both? If both, is there a way to tell which is which?

- [ ] Applications
- [ ] Libraries
- [X] Both (explain how to tell which is which)

Hermit doesn't distinguish whether a project is an application or a library.

### If ranges are supported, are there any cases when Renovate should pin ranges to exact versions if rangeStrategy=auto?

N/A

---

## Lookup

### Is a new datasource required? Provide details

- [X] Yes, provide details.
- [ ] No.

The implementation has the hermit datasource. Mainly it uses `hermit search --json` to fetch the versions for a given package. 

### Will users need the capability to specify a custom host/registry to look up? Can it be found within the package files, or within other files inside the repository, or would it require Renovate configuration?

No custom host/registry is needed. Hermit use git clone to fetch the packages information from git repositories. e.g. (https://github.com/cashapp/hermit-packages/)

### Do the package files have any "constraints" on the parent language (e.g. supports only v3.x of Python) or platform (Linux, Windows, etc) that should be used in the lookup procedure?

Nope.

### Will users need the ability to configure language or other constraints using Renovate config?

Nope

---

## Artifacts

### Are lock files or checksum files used? Are they mandatory?

Yes, hermit has lock file for a tool with name & version in the filename of the symlink. They are manadtory.

### If so, what tool and exact commands should be used if updating one or more package versions in a dependency file?

`hermit install` command will update those packages

### If applicable, describe how the tool maintains a cache and if it can be controlled via CLI or environment variables? Do you recommend the cache be kept or disabled/ignored?

Hermit maintain its cache in `XDG_CACHE_HOME`. Keeping the cache across multiple repositories for a renovate run will definitely speed things up.

### If applicable, what command should be used to generate a lock file from scratch if you already have a package file? This will be used for "lock file maintenance"

This is not applicable.

## Other

### Is there anything else to know about this package manager?

Nope

**Comment by lyonlai** [comment]
@rarkins Please take a look at the filled out questionnaire above. 

In terms of the PR, I'll need to write some documents for the Hermit manager early next week. Will submit the PR afterward.

**Comment by rarkins** [comment]
If you need us to run "hermit" as part of the extract process then that's unfortunately a no-go. We only support use cases where there's a file or files in the repo which we can parse, and we do not use third party tools as part of the extract phase

**Comment by rarkins** [comment]
Same for datasources

**Comment by alecthomas** [comment]
For the extract phase, it should be (relatively) straightforward to not run `./bin/hermit`, but for the datasource it will be quite a bit more difficult. Hermit's package definitions are parsed and interpolated by Hermit. Here's [python3](https://github.com/cashapp/hermit-packages/blob/master/python3.hcl#L12-L18) as an example.

**Comment by alecthomas** [comment]
But still possible, so let us know :)

**Comment by rarkins** [comment]
At the moment it's our firm restriction that extract and lookup phases do not run any third party tools (including `gradlew`).

For extraction, I would suggest that having a simple to read declarative definition for dependencies is a good practice regardless of Renovate, i.e. a "manifest file".

For lookups, you are more constrained by third party APIs but potentially you can reuse our existing github tags or releases, docker images, or repology datasources.

**Comment by alecthomas** [comment]
> At the moment it's our firm restriction that extract and lookup phases do not run any third party tools (including gradlew).

Understood, we can make it work.

> For extraction, I would suggest that having a simple to read declarative definition for dependencies is a good practice regardless of Renovate, i.e. a "manifest file".

We have a machine readable manifest, it was just simpler to use `./bin/hermit`, but we can make it work.

> For lookups, you are more constrained by third party APIs but potentially you can reuse our existing github tags or releases, docker images, or repology datasources.

For the datasource, I think what we'll do is run `hermit search --json` in CI and write the output to an `index.json`. This can then be read by the Hermit datasource.

Thanks for the feedback, we'll get back to you once we've made these changes.

**Comment by alecthomas** [comment]
PS. Loving Renovate, it's awesome :)

**Comment by lyonlai** [comment]
Hey @rarkins 

I'm back. I've address the issues in our hermit manager implementation we discussed\ last week so now the hermit manager does the following

1. extract packages from the repository references rather than relying on `hermit list --json` 
2. look up packages from hermit-package repository release asset straight away rather than relying on `hermit search --json packageaName`

 Would you like me to fill out a new questionnaire or this comment is good enough. 

Let me know if there's anything else. If all good then I will submit the PR.

**Comment by rarkins** [comment]
Hi @lyonlai I think we're ok to go ahead now, thanks

**Comment by lyonlai** [comment]
Awesome! Thanks.

**Comment by rarkins** [comment]
@lyonlai can this now be closed?

**Comment by lyonlai** [comment]
yes, thanks for the help all along.

**Comment by alecthomas** [comment]
@rarkins thank you so much to you and the team for guiding this, much appreciated 🙇‍♂️
