### ISSUE TITLE
Speed up CI test runs with `actions/cache`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#16203]
### Describe the proposed change(s).

Over on the Octoclairvoyant repository, I stumbled into a possible speed up for the Prettier run in the CI. [^octoclairvoyant-repo] Pasting the conversation:

> We can take advantage of the cache in CI too if we save it between runs, but I don't think we would get faster runs since the codebase is quite small.
> 
> Do you know how you can use the Prettier cache in the CI? That would speed up the runs on the Renovate repository a lot, I think.
> 
> I think so! You need the [`actions/cache` GitHub Action](https://github.com/actions/cache). With this plugin, you can cache builds or dependencies (pretty much everything), so you can specify the folder where Prettier saves its internal cache.
> 
> From what I see in Prettier docs, by default it's located in `./node_modules/.cache/prettier/.prettier-cache`, and there is no option to customize the path (for now at least), so you would have to set that specific folder in the `actions/cache` after installing the project dependencies (so the `node_modules` don't override your Prettier cache).

[^octoclairvoyant-repo]: https://github.com/octoclairvoyant/octoclairvoyant-webapp/issues/974

**Comment by viceice** [comment]
I'm not sure it's worse the work. currently our lint runs ~1:45 min. jest jests are far mor expensive.

**Comment by HonkingGoose** [comment]
> I'm not sure it's worse the work. currently our lint runs ~1:45 min

If we can save 30 seconds on each Prettier run, we're "wasting" fewer CPU cycles on our test. Wasting fewer CPU cycles means less energy used, which seems a good thing to me.

From running Prettier locally, you take a hit on the first run (because it needs to build the cache), but afterwards it sped up the Prettier run drastically. From about 40 seconds to 4 seconds.

Maybe we could even speed up the ESLint runs by doing something similar as well?

@rarkins what do you think of all this?

**Comment by rarkins** [comment]
I guess it can be quicker to "fail fast", which is also a good thing.

**Comment by JamieMagee** [comment]
> I'm not sure it's worse the work. currently our lint runs ~1:45 min. jest jests are far mor expensive.

What about caching `.cache/jest` in between runs?

**Comment by viceice** [comment]
we should probably configure all those caches to `.cache` and safe that on CI based on yarn lock, otherwise i think it will grow indefinitely?

**Comment by HonkingGoose** [comment]
Sounds like we want to:

- [ ] Use `actions/cache` to:
  - [ ] Speed up Prettier runs
  - [ ] Speed up Jest runs
  - [ ] Speed up ESLint runs
- [ ] Cache location should be `.cache`
- [ ] Probably: add `.cache` to `.gitignore` and `.prettierignore` if needed

**Comment by viceice** [comment]
`.cache` should already be ignored

**Comment by HonkingGoose** [comment]
@zharinov is this issue still relevant? Your work sped up the tests a lot. I don't know if we need this work anymore. 😄

**Comment by zharinov** [comment]
No, I don't think so
