### ISSUE TITLE
Don't show [template] for long strings in docs

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#16216]
### What would you like Renovate to be able to do?

Show the full default values for fields like `commitMessageExtra`

### If you have any ideas on how this should be implemented, please tell us here.

Remove the existing rule for `[template]` and check the result displays ok

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/29a272c78fb2b9a31be24a44be63691b27ab654b/lib/logger/utils.ts#L151-L152

needs to be removed

**Comment by Gabriel-Ladzaretti** [comment]
Thats the only diff in both `self-hosted-configuration.md` & `configuration-options.md`
![image](https://user-images.githubusercontent.com/97394622/175535983-467d2d3a-2775-45b2-a988-5c9092fec6ea.png)

**Comment by rarkins** [comment]
@Gabriel-Ladzaretti I think there's two cases where we substitute [template]. Did you remove both and only get that one diff?

**Comment by Gabriel-Ladzaretti** [comment]
> @Gabriel-Ladzaretti I think there's two cases where we substitute [template]. Did you remove both and only get that one diff?

I double check using `beyond compare` and ran some queries using `everything`. On both before and after the change, this is the only place `[template]` appears.

This is where we do the substation, only `commitMessageExtra` has lenght > 200 (237):
https://github.com/renovatebot/renovate/blob/a1b157428652a2d0301d84821de1f41078601e70/tools/docs/config.ts#L114-L116

apart from the above and what @viceice mentioned, `[template]` also appears here, although both are not related to docs gen.
https://github.com/renovatebot/renovate/blob/e7a969016d4a00f77f677713c547c33f199936ba/lib/logger/config-serializer.ts#L16-L20
