### ISSUE TITLE
Duplicate subject line

### ISSUE THREAD

**Issue by jlarmstrongiv** [renovatebot/renovate#16300]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Subject lines are duplicated by renovate:
- `renovate: 🖌️: renovate: 🖌️ Update all non-major dependencies`
- `renovate: 🖌️: renovate: 🖌️ Update dependency @types/tailwindcss to v3…`

It used to work on 26 June 2022.

My config:

```
{
  "extends": [
    "config:base",
    "group:allNonMajor",
    ":semanticCommitScopeDisabled",
    ":semanticCommitTypeAll(renovate)",
    ":disableRateLimiting",
    ":prConcurrentLimitNone",
    ":automergePatch",
    ":automergeMinor",
    ":automergeBranch"
  ],
  "ignorePresets": ["workarounds:typesNodeVersioning"],
  "commitMessagePrefix": "renovate: 🖌️",
  "timezone": "America/New_York",
  "schedule": ["after 8am", "before 10am"],
  "prConcurrentLimit": 0,
  "prHourlyLimit": 0,
  "packageRules": [
    {
      "matchManagers": ["npm"],
      "matchPackageNames": ["prettier-plugin-sh"],
      "enabled": false
    }
  ]
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment]
It looks similar to this issue:

- https://github.com/renovatebot/renovate/issues/16269

The fix for that problem is in Renovate version `32.99.6`.

**Comment by rarkins** [comment]
The app is now running 32.99.6, please request a run on your repo using the dashboard and see if the PR titles are updated

**Comment by jlarmstrongiv** [comment]
Awesome!  I also deleted renovate branches and reinstalled the app earlier this morning.  After enabling renovate again, everything is named properly 👍
