### ISSUE TITLE
Gradle manager failes to detect/extract dependencies if version schema is not SemVer compliant.

### ISSUE THREAD

**Issue by mhubig** [renovatebot/renovate#16342]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.76.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We have a in-house java gradle library with a custom version schema like this: `2022-06-12_1234` Unfortunately we are not able to tell renovate to accept this kind of version. The package is simply ignored and does not even appear with in the debug logs. If I change the version number to something semver compatible like `1.1.1` everything works like a charm ...

The package with version from the `build.gradle.kt` file:

```gradle
compileOnly("com.example.foo:tool-types:2022-05-10_55")
```

The `renovate.json`file

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "packageRules": [
    {
      "matchPackageNames": ["com.example.foo:tool-types"],
      "versioning": "regex:^\\d+-\\d+-\\d+_(?<patch>\\d+)$"
    }
  ]
}
```

### Relevant debug logs

<details><summary>Logs</summary>

The `com.example.foo:tool-types` is nowhere to find within the logs. The only dependency renovate detects from the `build.gradle.kts` file is `de.data.services:product-data-model`

```json
{
             "packageFile": "build.gradle.kts",
             "datasource": "maven",
             "deps": [
               {
                 "depName": "de.data.services:product-data-model",
                 "currentValue": "5.15.1",
                 "managerData": {
                   "fileReplacePosition": 2651,
                   "packageFile": "build.gradle.kts"
                 },
                 "fileReplacePosition": 2651,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://rtf.artifactory.com/artifactory/maven-central-remote",
                   "https://rtf.artifactory.com/artifactory/maven-releases-productcatalog/",
                   "https://rtf.artifactory.com/artifactory/maven-snapshots-productcatalog/",
                   "https://rtf.artifactory.com/artifactory/maven-externals-productcatalog/",
                   "https://rtf.artifactory.com/artifactory/maven-central-remote/"
                 ],
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "topic": "de.data.services:product-data-model",
                     "message": "Failed to look up dependency de.data.services:product-data-model"
                   }
                 ],
                 "versioning": "gradle"
               }
             ]
           }
```

</details>

### Have you created a minimal reproduction repository?

https://github.com/mhubig/renovate-bug-reproduction-16342

**Comment by rarkins** [comment]
If the dependency does not appear anywhere then it implies it's never even extracted. A package which is never extracted cannot be matched to a package rule.

If the problem is during extraction then you should be able to reproduce it publicly even if the package is private. You can for example use a dummy name to reproduce. Only once it's extracted could you possibly change versioning.

**Comment by RahulGautamSingh** [comment]
I tried reproducing it here https://github.com/RahulGautamSingh-testing/reproduction-16342/pulls
I think the extraction doesn't happened because the version type is not a valid one for our gradle parser.

**Comment by mhubig** [comment]
@RahulGautamSingh Yes I think so too,  but I assumed (https://docs.renovatebot.com/modules/versioning/#why-you-might-need-to-manually-configure-versioning) I can somehow overwrite the Version Type with a package rule like this:

```json
{
      "matchPackageNames": ["com.example.foo:tool-types"],
      "versioning": "regex:^\\d+-\\d+-\\d+_(?<patch>\\d+)$"
},
```

**Comment by mhubig** [comment]
I have changed the description and provided a demo repo (https://github.com/mhubig/renovate-bug-reproduction-16342) where you can clearly see that renovate is only extracting deps with a maven compliant version string, even if this is overwritten with a versioning statement within a matching package rule.

**Comment by rarkins** [comment]
Forked to https://github.com/renovate-reproductions/16342

**Comment by rarkins** [comment]
I don't see any hardcoded semver use in our gradle extract logic, but maybe one of our parsing patterns assumes there's some full stops

**Comment by RahulGautamSingh** [comment]
It fails here https://github.com/renovatebot/renovate/blob/322deea7a30c1622cd9fb14a503282d1b4da4119/lib/modules/manager/gradle/utils.ts#L66
