### ISSUE TITLE
Parse registryUrls from .yarnrc.yml

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#16353]
### What would you like Renovate to be able to do?

Parse `registryURls` from `.yarnrc.yml` (for Yarn 2/3)

### If you have any ideas on how this should be implemented, please tell us here.

Reproduction: https://github.com/renovate-reproductions/renovate-private-registry-yarn-v3-bug

Specifically the `npmRegistryServer` lines should be noted: https://github.com/renovate-reproductions/renovate-private-registry-yarn-v3-bug/blob/6ca4b4e59640ace4df1d95ae2760a4e8d95ac357/.yarnrc.yml#L7

### Is this a feature you are interested in implementing yourself?

No

**Comment by vanstinator** [comment]
👋🏻 coming over from https://github.com/renovatebot/renovate/issues/16339

To answer the specific question, yes we include our npm registry token in our `yarnrc.yml` file.

More broadly renovate will likely need to parse the module scoped credential variants as well to properly handle registry configuration details.
