### ISSUE TITLE
Config migration PR title doesn't follow Conventional Commits spec

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#16364]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Quote from https://github.com/renovatebot/renovate/pull/16355#issuecomment-1172071346:

> ![image](https://user-images.githubusercontent.com/6311784/176854062-0cd24aaf-26b7-4d25-a837-83d29f719594.png)
> 
> Example PR. Note that the PR title does not follow conventional commits although the commit message does - this needs to be fixed later.

We should probably fix this bug before we do:

- #16359

### Relevant debug logs

I don't have access to the logs.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by RahulGautamSingh** [comment]
Should it be hardcoded? 
Somehting like this:

```js
const prTitle = `chore(config): migrate config ${filename}`;
```

**Comment by rarkins** [comment]
No, only if the repo is using conventional commits

**Comment by RahulGautamSingh** [comment]
```js
  const commitMessageFactory = new ConfigMigrationCommitMessageFactory(
    config,
    migratedConfigData.filename
  );

  const prTitle = commitMessageFactory.create().toString();
```

**Comment by Gabriel-Ladzaretti** [comment]
Closed by 
 - https://github.com/renovatebot/renovate/pull/16490
