### ISSUE TITLE
Config migration: run prettier

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#16402]
### What would you like Renovate to be able to do?

Apply `prettier` formatting to config migrations

### If you have any ideas on how this should be implemented, please tell us here.

This could be challenging to do, because prettier config can be made using JS.

But somehow we should detect if prettier is in use and format the migrated config file if so.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Example today without this:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/6311784/177047488-917989df-cd35-46a5-a7f9-e3c6d44bd048.png">

**Comment by viceice** [comment]
we should maybe try to block js config for security reasons

**Comment by rarkins** [comment]
I was looking at our prettier configs and realized there aren't too many settings to apply to JSON, e.g. quotation type and trailing commas don't apply. So the following logic would maybe be right 80-90% of the time:
- Is there signs of prettier? e.g. .prettierrc
- If so, run prettier programmatically against the migrated JSON content using default settings

**Comment by viceice** [comment]
sounds good

**Comment by RahulGautamSingh** [comment]
This ought to do it:
```js
const prettierrcExists = await fs.pathExists('.prettierrc');
            
            if (prettierrcExists && /migrate-config/g.exec(branchName)) {
              file.contents = prettier.format(file.contents, {
                filepath: fileName,
              });
            }
```

**Comment by viceice** [comment]
there are some more file extensions to check 😉

**Comment by RahulGautamSingh** [comment]
> there are some more file extensions to check 😉

For renovate-config files or prettier-config?

**Comment by HonkingGoose** [comment]
Does PR #16471 close this issue? Or do we need something else before we can close it?
