### ISSUE TITLE
Support multiple values.yaml files for helm-manager

### ISSUE THREAD

**Issue by dschunack** [renovatebot/renovate#16442]
### What would you like Renovate to be able to do?

Hi,

at the moment renovate supports only "values.yaml" file but not a second or third file.
We use multiple helm charts and values files with the terraform helm provider and resoruces in a single repository like this:

```
values.yaml
kyverno-values.yaml
kyverno-policies-values.yaml
kyverno-policy-reporter-values.yaml
```

At the moment only the values.yaml is supported by the file match for manager helm-values.

### If you have any ideas on how this should be implemented, please tell us here.

Change the file match in [index.ts](https://github.com/renovatebot/renovate/blob/f1b66c42499977461cc86cac40c495c070aa989e/lib/modules/manager/helm-values/index.ts#L6) for the helm manager maybe like this:

```
fileMatch: ['(^|/).*values.yaml$']
```

At the moment we added an additional file match in the renovate.json like this:

```
  "helm-values": {
    "fileMatch": ["(^|/).*values.yaml$"]
  }
```

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
you can override that within a package rule as required. i don't think we should change the default value.

**Comment by rarkins** [comment]
This is an example of why fileMatch is configurable. Unless a lot of people name files this way, I don't think we want to change defaults.

**Comment by dschunack** [comment]
Hey,

It was only an idea and if you think it's not needed, I will close it. 
As i said we already use custom filters.
