### ISSUE TITLE
Gemfile not updating when rangeStrategy=update-lockfile

### ISSUE THREAD

**Issue by narwold** [renovatebot/renovate#16547]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The docs for rangeStrategy=update-lockfile say that it will fallback to rangeStrategy=replace when the new version is not supported by the existing range. Given flipper@<~ 0.22.2, which wouldn't support 0.25.0, Renovate tries to update the lockfile but then fails to run the lockfile update command since the Gemfile doesn't support the new version. Why isn't it updating the Gemfile?

For reproduction, see https://github.com/narwold/renovate-test/blob/main/renovate.json
Note that it does update the Gemfile when using the `replace` strategy (see previous attempt at https://github.com/narwold/renovate-test/pull/6)

See previous discussion at https://github.com/renovatebot/renovate/discussions/16369

### Relevant debug logs

The log specifically mentions this error:
```
Bundler could not find compatible versions for gem \"flipper\":\n  In snapshot (Gemfile.lock):\n    flipper (>= 0.25.0)\n\n  In Gemfile:\n    flipper\n\n    flipper-redis (~> 0.22.2) was resolved to 0.22.2, which depends on\n      flipper (~> 0.22.2)\n\nRunning `bundle update` will rebuild your snapshot from scratch, using only\nthe gems in your Gemfile, which may resolve the conflict.\n
```
...and if you run `bundle install` locally, it's the same result. If you manually update the Gemfile, then it works.

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Does it only happen if you group the flipper dependencies? And can you duplicate it to a second repo with rangeStrategy=replace to show the working example?

**Comment by narwold** [comment]
I believe it was happening before I grouped them, but I'll double-check.

**Comment by rarkins** [comment]
Always, the more minimal the better

**Comment by narwold** [comment]
OK, so it does appear to work without the grouping, so it's an issue w/ grouping. The additional annoyance, of course, is that flipper can't bump without flipper-redis, so flipper-redis has to go first, but that doesn't stop Renovate from opening a "nothing PR" for flipper at https://github.com/narwold/renovate-test/pull/8. Of course, presumably this would only happen once and wouldn't happen again after the x86_64-linux platform is added to the lockfile.
