### ISSUE TITLE
Use `url` in datasources, or will fail for private repositories

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#16575]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Creating an issue as requested by @viceice. Quote from https://github.com/renovatebot/renovate/pull/16257#discussion_r919686631:

> We probably need to use `url` in other datasources too? otherwise it will fail for private repos as @lyonlai suggested?

### Relevant debug logs

No logs.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
it seems `browser_download_url` doesn't work on private repositories.

https://github.com/renovatebot/renovate/blob/2d5c8230d0c8b6faf19bf947ddc46336d50e5618/lib/modules/datasource/github-releases/types.ts#L16

**Comment by viceice** [comment]
Closing, as nobody has complained yet 🤷‍♂️
