### ISSUE TITLE
Node.js container images from docker mirror not grouped with other Node.js updates

### ISSUE THREAD

**Issue by fabb** [renovatebot/renovate#16634]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:32-slim

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitlab 14.10.5-ee

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

In a frontend project that uses gitlab-ci.yml, .nvmrc and Dockerfile-*, we get one PR for minor node updates, but it the node updates for the Dockerfiles which use a docker mirror are missing.

Apart from extending `config:base`, I have no relevant `packageRules` configured.

### Have you created a minimal reproduction repository?

https://github.com/fabb/renovate-node-grouping

**Comment by rarkins** [comment]
Is the problem that updates are not grouped (as your title indicates) or that updates are *not found* (which your later description indicates)? Do you mean that you are expecting updates to a certain file which are not happening?

**Comment by rarkins** [comment]
I think you'll find that the docker mirror only lists tags it has already downloaded and knows about, unlike Docker Hub itself which lists all tags available. This is not a Renovate bug.

**Comment by rarkins** [comment]
You can use the regex manager to overcome these problems. Extract just the image name and then let Renovate look up tags from Docker Hub instead.

**Comment by rarkins** [comment]
Look at the branch names for a hint as to why they're not grouped. In your reproduction it was because there were minor and major updates, which should not be grouped together. Please start a new GitHub discussion per topic from now on and don't keep continuing in this closed/invalid bug report
