### ISSUE TITLE
renovate-config manager

### ISSUE THREAD

**Issue by foolioo** [renovatebot/renovate#16679]
### What would you like Renovate to be able to do?

Renovate should be able to detect updates to [Sharable Config Preset](https://docs.renovatebot.com/config-presets/#preset-hosting). For instance, look at a Renovate configuration that looks like

```json
{
  "extends": ["gitlab>abc/foo//path/xyz#1.5.4"]
}
```

Renovate should detect that `abc/foo` has a new tag.
There is no builtin [manager](https://docs.renovatebot.com/modules/manager/) for renovate-config where it should be a fundamental manager.

### If you have any ideas on how this should be implemented, please tell us here.

renovate-config manager should use its builtin config library to:
- Parse renovate config (`(^|/).?renovate(?:rc)?(?:\.json5?)?$`)
- Extract the
   - manager (e.g., `github`)
   - repository (e.g., `abc/foo`)
   - version (e.g., `1.5.4`)
- Use the extracted information (manager, repository, and version) from previous step to detect any changes

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
Sure, PRs welcome

**Comment by mkniewallner** [comment]
This looks like a duplicate of #13308.

**Comment by viceice** [comment]
Duplicate of #13308
