### ISSUE TITLE
Add setting flags to choose between Node.js LTS or non-LTS versions

### ISSUE THREAD

**Issue by alexanderniebuhr** [renovatebot/renovate#16690]
### What would you like Renovate to be able to do?

In an earlier [discussion](https://github.com/renovatebot/renovate/discussions/16687), I saw someone promoting v18 as **unstable**.
I can't fully agree. It is, by definition, a stable release. It is not an LTS (long-term-support) one but a stable release.

I prefer the default managers to ship with a config flag to allow the user to specify `lts` or `latest.`
Therefore `ignoreUnstable` flag should be reserved for the actual pre-release version.

### If you have any ideas on how this should be implemented, please tell us here.

Just add a config option, to allow the user specify the release branch. Maybe something like

```
nodeBranch: 'lts' | 'latest'
```

### Is this a feature you are interested in implementing yourself?

No

### references

https://github.com/renovatebot/renovate/discussions/16687

**Comment by viceice** [comment]
no, as node don't publish prereleases and the latest version can always contain breaking changes even in minor versions

**Comment by rarkins** [comment]
Also disagree. Node releases prior to LTS can contain breaking changes and are not stable according to our definition.

**Comment by alexanderniebuhr** [comment]
Healthy open source development should always favor freedom of usage for the consuming users. Therefore, I requested a setting flag to allow for a more straightforward configuration of the node version as an opt-in possibility (optional).

This feature would not include breaking changes to you / the existing user-base of **renovate** as the default value can (and should) stay `LTS`.

But it wouldn't hurt to allow users an **easy** way to choose what they prefer by providing this feature.

I have no idea why the team is hardly against using non-LTS versions and any **easy** way to set this in the configuration. Still, seeing that you are very open to user-led configuration decisions, you should be in favor of the idea.

Nevertheless, if you still want to increase the barriers for users to choose the node version policy they want, I genuinely respect your _own_ definition of stability and hope other people are as understanding as I am with using a lengthy way to configure `non-LTS`.

**Comment by viceice** [comment]
> Healthy open source development should always favor freedom of usage for the consuming users. Therefore, I requested a setting flag to allow for a more straightforward configuration of the node version as an opt-in possibility (optional).
> 
> This feature would not include breaking changes to you / the existing user-base of **renovate** as the default value can (and should) stay `LTS`.
> 
> But it wouldn't hurt to allow users an **easy** way to choose what they prefer by providing this feature.
> 
> I have no idea why the team is hardly against using non-LTS versions and any **easy** way to set this in the configuration. Still, seeing that you are very open to user-led configuration decisions, you should be in favor of the idea.
> 
> Nevertheless, if you still want to increase the barriers for users to choose the node version policy they want, I genuinely respect your _own_ definition of stability and hope other people are as understanding as I am with using a lengthy way to configure `non-LTS`.

there is already a easy config option to use as we told you in your discussion.

**Comment by rarkins** [comment]
What you're missing is that it *does* hurt to keep adding language and manager-specific options into the code base. There are times when we pick a single concept to apply across multiple ecosystems and this is one of those. Either way it's still a single option to opt into non-LTS node releases, so you're just arguing on naming. You would be better off contributing a documentation PR for future users than writing another mini essay on how dissapointed you are

**Comment by alexanderniebuhr** [comment]
> Either way, it's still a single option to opt into non-LTS node releases, so you're just arguing on naming.

Maybe I do miss something, but as far as I understood it, `ignoreUnstable` would also include `v19-nightly` builds, which are released. Correct?

If yes, this is an entirely different opt-in.

**Comment by viceice** [comment]
Our node datasource doesn't include nighly. There are also no nigthly releases on nodejs github repo

https://docs.renovatebot.com/modules/datasource/#node-datasource
