### ISSUE TITLE
Add support for setting bumpVersion in Poetry projects (Python)

### ISSUE THREAD

**Issue by chopeen** [renovatebot/renovate#16704]
### What would you like Renovate to be able to do?

I would like Renovate to update the version field within `pyproject.toml` file any time it updates dependencies within (setting [bumpVersion](https://docs.renovatebot.com/configuration-options/#bumpversion)).

### If you have any ideas on how this should be implemented, please tell us here.

It should be similar to `lib/modules/manager/sbt/update.ts` with slightly adjusted regex to find `version` field in `pyproject.toml` file.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by chopeen** [comment]
I was able to achieve this effect by adding a post-upgrade task to `renovate.json`:

```
  "postUpgradeTasks": {
    "commands": [
      "poetry version patch"
    ],
    "fileFilters": [
      "pyproject.toml"
    ],
    "executionMode": "branch"
  },
```

The following configuration change was required in `config.js`:

```
  allowedPostUpgradeCommands: [
    // allow command https://python-poetry.org/docs/cli/#version, with any arguments
    "^poetry version [a-z0-9-]+$",
  ],

```

**Comment by rarkins** [comment]
Lots of people have +1'd this but FYI without a reproduction this remains as `status:requirements`. Please help out if you'd like to see it moved forward!

**Comment by antoni-szych-rtbhouse** [comment]
> The following configuration change was required in `config.js`:
> 
> ```
>   allowedPostUpgradeCommands: [
> ```

Too bad that:

>[Post-upgrade tasks can only be used on self-hosted Renovate instances.](https://docs.renovatebot.com/configuration-options/#postupgradetasks)

Which means that's a no-go for [github renovate app](https://github.com/marketplace/renovate) :( (but is probably a great workaround when self-hosting)

@rarkins I'm not sure what there is to be reproduced. The feature is absent. The config doesn't really matter. We have `pyproject.toml` with poetry-defined requirements like:
```
[tool.poetry]
name = "my-package-name"
version = "9.2.5"

[tool.poetry.dependencies]
python = "~3.11"
requests = "^2.25.1"
```
and we want renovate to bump version from 9.2.5 to 9.2.6 when it will update requests to `^2.26.0`. That is, we would like for [bumpversion](https://docs.renovatebot.com/configuration-options/#bumpversion) switch to support manager `poetry`, which it currently does not.

**Comment by rarkins** [comment]
See https://github.com/renovatebot/renovate/issues/16704#issuecomment-1192521053 for directions

**Comment by djmattyg007** [comment]
@rarkins Would you be able to provide some guidance on what someone should do in terms of a reproduction for a request for a feature that does not currently exist? How can we reproduce something that doesn’t currently exist?

**Comment by rarkins** [comment]
Create an example repo which has the type of Renovate PR you'd want to bump version with. Configure the repo as if the feature existed. Then when the PR is created (without bumping version) add an additional commit on top demonstrating how you'd expect it to be. Finish with a readme describing the above

**Comment by chopeen** [comment]
I created the reproduction repository [chopeen/renovate-issue-16704](https://github.com/chopeen/renovate-issue-16704):

 - the additional commit is https://github.com/chopeen/renovate-issue-16704/pull/2/commits/cd77b173c7299f6c92363ca794f983ac73971a4f
- the expectations are documented in [README.md](https://github.com/chopeen/renovate-issue-16704/blob/renovate/requests-2.x/README.md)
