### ISSUE TITLE
Failed to detect resilience4j release

### ISSUE THREAD

**Issue by anuragagarwal561994** [renovatebot/renovate#16716]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.125.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab (.com and CE/EE)

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Latest release for resilience4j-bom last year https://github.com/resilience4j/resilience4j/releases/tag/v1.7.1

I am using 1.7.0 and renovate is not able to detect the release.

I am using renovate-bom as the library

```xml
<dependency>
                <groupId>io.github.resilience4j</groupId>
                <artifactId>resilience4j-bom</artifactId>
                <version>${resilience4j.version}</version>
                <scope>import</scope>
                <type>pom</type>
</dependency>
```

Above is the configuration in pom.xml file.

### Relevant debug logs

```json
{
                 "datasource": "maven",
                 "depName": "io.github.resilience4j:resilience4j-bom",
                 "currentValue": "1.7.0",
                 "fileReplacePosition": 5038,
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2"
                 ],
                 "depType": "import",
                 "groupName": "resilience4j.version",
                 "depIndex": 18,
                 "updates": [],
                 "warnings": [],
                 "versioning": "maven",
                 "sourceUrl": "https://github.com/resilience4j/resilience4j",
                 "homepage": "https://resilience4j.readme.io",
                 "currentVersion": "1.7.0",
                 "fixedVersion": "1.7.0"
}
```

Above is the output of the renovate run.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by astellingwerf** [comment]
There is no sign of 1.7.1 on https://repo.maven.apache.org/maven2/io/github/resilience4j/resilience4j-bom/. There's nothing Renovate can do about that. I suggest you take a look at https://github.com/resilience4j/resilience4j/issues/1558.

**Comment by anuragagarwal561994** [comment]
Thanks a lot for your reply, didn’t saw the library was missing on maven.
