### ISSUE TITLE
Warning: Max recursion depth reached

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#16732]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I'm seeing thousands of these errors reported in the hosted app.

Example repo: https://github.com/codecentric/habitcentric (See logs below)

I'd like clarity on who this is a warning for:

1. Do these repos have *wrong* Gradle config, and they should fix it, or
2. Do we have a bug in our code which should be fixed, or
3. If neither of the above are wrong, this should not be a WARN

### Relevant debug logs

<details><summary>Logs</summary>

```
{"level":40,"scriptFile":"../gradle/jacoco.gradle","msg":"Max recursion depth reached","time":"2022-07-24T09:39:34.626Z"}
{"level":20,"fileName":"services/ui/helm/ui/Chart.yaml","msg":"Chart has no dependencies","time":"2022-07-24T09:39:34.642Z"}
{"level":40,"scriptFile":"../gradle/jacoco.gradle","msg":"Max recursion depth reached","time":"2022-07-24T09:39:34.659Z"}
{"level":20,"msg":"Detecting pnpm Workspaces","time":"2022-07-24T09:39:34.664Z"}
{"level":20,"msg":"Detecting Lerna and Yarn Workspaces","time":"2022-07-24T09:39:34.666Z"}
{"level":20,"msg":"Finding locked versions","time":"2022-07-24T09:39:34.666Z"}
{"level":20,"msg":"Found package-lock.json for package.json","time":"2022-07-24T09:39:34.666Z"}
{"level":20,"msg":"Found services/ui/package-lock.json for services/ui/package.json","time":"2022-07-24T09:39:34.776Z"}
{"level":40,"scriptFile":"../gradle/jacoco.gradle","msg":"Max recursion depth reached","time":"2022-07-24T09:39:35.397Z"}
{"level":40,"scriptFile":"../gradle/jacoco.gradle","msg":"Max recursion depth reached","time":"2022-07-24T09:39:35.512Z"}
{"level":40,"scriptFile":"../gradle/jacoco.gradle","msg":"Max recursion depth reached","time":"2022-07-24T09:39:35.801Z"}
{"level":40,"scriptFile":"../gradle/jacoco.gradle","msg":"Max recursion depth reached","time":"2022-07-24T09:39:35.807Z"}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by zharinov** [comment]
Seems like actually it's not so scary, just trying to use `apply from` from inside another `apply from`. Our current limit is maximum 1-level depth.

**Comment by rarkins** [comment]
So downgrade it from warning to debug?

**Comment by Churro** [comment]
Agreed, @zharinov. This was meant as a safe-guard to prevent cyclic `apply from` calls.

The gradle configs are correct. In the example, [build.gradle](https://github.com/codecentric/habitcentric/blob/main/services/habit/build.gradle#L13) includes [gradle/jacoco.gradle](https://github.com/codecentric/habitcentric/blob/main/services/habit/gradle/jacoco.gradle) which in turn includes [../gradle/jacoco.gradle](https://github.com/codecentric/habitcentric/blob/main/services/gradle/jacoco.gradle). 1-level depth is a "conservative" approach but as also stated in the PR https://github.com/renovatebot/renovate/pull/16030 this [could be increased](https://github.com/renovatebot/renovate/blob/a7202c4f4662fcb984e50b8a1a3a1eddc94ac1fc/lib/modules/manager/gradle/parser.ts#L1134)

Personally, I'd opt for the depth increase, as the example you provided is a legit use-case. Making the warning a debug stmt would just hide it.
