### ISSUE TITLE
Move config migration PR creation to the main repository worker flow

### ISSUE THREAD

**Issue by Gabriel-Ladzaretti** [renovatebot/renovate#16736]
### Describe the proposed change(s).

In the current state, we cant use repository cache in the migration flow.
This is because the cache is set before the finalize flow which contains the migration, therefore we cant cache the migration branch.

related discussion in:
 - https://github.com/renovatebot/renovate/pull/16664

**Comment by rarkins** [comment]
@Gabriel-Ladzaretti is this still an issue? Can you expand on the description if so - I'm not sure I understand it

**Comment by Gabriel-Ladzaretti** [comment]
This one is obsolete. 

It was related to an issue we had when running config migration when the repo wasnt being cloned during a run.
Related discussion https://github.com/renovatebot/renovate/pull/16664.

superseded and fixed by - 
 - https://github.com/renovatebot/renovate/pull/17021
- https://github.com/renovatebot/renovate/pull/17311
