### ISSUE TITLE
Handle unicode in URLs

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#1680]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

A repository was added to the app that essentially "doesn't work" because it uses Chinese characters in folder names: https://github.com/RoJoHub/Redux-Tutorial

I am concerned that doing a "blind" `encodeURI()` on every URL we send might end up breaking something else. Does anyone have experience with this?

**Comment by kayoub5** [comment]
my experience is don't use `encodeURI`, use `encodeURIComponent` or `require('querystring')`

**Comment by rarkins** [comment]
I wonder if this works or is easier or harder with gitFs
