### ISSUE TITLE
semantic commit scope and type should not be lowercased

### ISSUE THREAD

**Issue by Roshick** [renovatebot/renovate#16839]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.132.0

### Please select which platform you are using if self-hosting.

Bitbucket Server

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Currently the semantic commit scope (and probably the type too) are lowercased although the [angular conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) does not enforce this.

In our case, we use the scope to define the (jira) issue the change relates to, e.g. "fix(ISSUE-123): Some message".

As renovate appears to lowercase the scope, this message will turn into "fix(issue-123): Some message" and no longer be valid per our commit message regex.

Since there is no apparent reason to lowercase these parts, I would suggest to stop doing so.

### Have you created a minimal reproduction repository?

[Here](https://github.com/Roshick/semantic-commit-scope-should-not-be-lowercased) is the minimal reproduction. I created a single initial commit [fix(SOME-THING): Initialise](https://github.com/Roshick/semantic-commit-scope-should-not-be-lowercased/commit/acebf4a3ba59ca22ac4eb227a11f8af36035b6ff) which was correctly detected as an angular style semantic commit. The semanticCommitScope is set to "SOMETHING" and [this](https://github.com/Roshick/semantic-commit-scope-should-not-be-lowercased/pull/1/commits) is the commit created by renovate.

**Comment by Roshick** [comment]
@rarkins I've added a minimal reproduction repository, I hope it helps.

**Comment by Roshick** [comment]
I took a look at the code and think I might be able to solve this issue.

I still need to understand quite a lot about the code, but I think [this part](https://github.com/renovatebot/renovate/blob/bba3c782e257682feeb42ccb4d35f6db37c9e611/lib/workers/repository/updates/generate.ts#L181-L184) is the issue, but simply removing it could be a breaking change for others since all semantic commit messages would suddenly start with an uppercase letter in the subject.

If it's okay I would like to give it a try.

As I understood when I have questions on how it should be solved or general questions about the code I should create a separate discussion or join the slack?!

**Comment by rarkins** [comment]
Either is welcome. Although best to keep relevant decisions in the issue itself.

I think it's ok to stop lower casing the scope
