### ISSUE TITLE
"Dependency <namespace>.<collection> has unsupported value" when using version ranges

### ISSUE THREAD

**Issue by SirUli** [renovatebot/renovate#16852]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.133.0

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

7.20

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When using a valid range version specifier for the ansible-galaxy manager, renovate complains with:

> `Dependency <namespace>.<collection> has unsupported value`

While the ansible documentation doesn't state it explicitly for requirements.yml files, it is at least shown in the examples of [here]( https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#examples) that it is possible.

Reproduction:

Save the following file as requirements.yml into your repository:

```yaml
---
collections:
  - name: community.crypto
    version: ">=2.0.0,<3.0.0"
  - name: community.general
    version: ">=4.0.0,<5.0.0"
```

Then try to run it through a recent version of ansible galaxy:

```bash
ansible-galaxy collection install -r requirements.yml
```

This should install the following versions:

- community.crypto:2.3.4
- community.general:4.8.4

Which is perfectly in line with the version specifier. Now run renovate with an activated ansible-galaxy manager. This one will show the log from below.

### Relevant debug logs

<details><summary>Logs</summary>

```
{"name":"renovate","hostname":"778c49f13c9d","pid":48,"level":20,"logContext":"6zJKTXkB12j1xoxvQTAh9","repository":"me/myawesomerepo","msg":"Dependency community.general has unsupported value >=4.0.0,<5.0.0","time":"2022-07-29T10:41:43.637Z","v":0}
{"name":"renovate","hostname":"778c49f13c9d","pid":48,"level":20,"logContext":"6zJKTXkB12j1xoxvQTAh9","repository":"me/myawesomerepo","msg":"Dependency community.crypto has unsupported value >=2.0.0,<3.0.0","time":"2022-07-29T10:41:43.645Z","v":0}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
We prefer a spec and not just examples.

Also looks like there is nothing to upgrade here anyway.

**Comment by SirUli** [comment]
Currently community.general is in 5.3.0 - which would mean that renovate wouldn't perform the version range update, correct? Sorry then this was a misunderstanding on my side, i had in mind that it would do that. If it should i'm happy to provide a sample repository.

**Comment by rarkins** [comment]
By default it won't change a range unless there's a newer version "above" that range. However one day there may be, I just meant that right now you shouldn't expect any updates for these examples even if the feature was added
