### ISSUE TITLE
AzureDevops: Allow specify custom approvers

### ISSUE THREAD

**Issue by vitskr** [renovatebot/renovate#16892]
### What would you like Renovate to be able to do?

Renovate has very useful azureAutoApprove feature, but it approves PR as same user that created PR. If branch policy does not allow users approve their own PRs AutoComplete does not work. Also if branch policy requires more than 1 approver autoComplete does not work either.
It would be great if we could pass array of additional User IDs and their PATs that would be used to approve PRs created by Renovate.

### If you have any ideas on how this should be implemented, please tell us here.

Instead of using PR creator id get one from configuration.
https://github.com/renovatebot/renovate/blob/f8c789efb44311d74320865c8cb85abc015b73c4/lib/modules/platform/azure/index.ts#L456

This would probably require separate azureApiGit client with PAT coming from config for each approver

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
you should use a separate bot for that, it's out of scope for renovate

**Comment by vitskr** [comment]
But renovate does approve PRs already. Why not make approver configurable?

**Comment by rarkins** [comment]
If it's not a feature you're interested in implementing yourself then there's nothing more to justify or discuss
