### ISSUE TITLE
Qrganization level presets with repos named {{platform}} without the "."

### ISSUE THREAD

**Issue by schmetzyannick** [renovatebot/renovate#16909]
### What would you like Renovate to be able to do?

# What?
Renovate should be able to finde repos named like {{platform}}  without the "." during the onboarding as described here: https://docs.renovatebot.com/config-presets/#organization-level-presets

# Why?
Gitlab has new "feature": [Do not allow special characters in new project names](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/80055)

### If you have any ideas on how this should be implemented, please tell us here.

I think it will be just the lookup in the onboarding process (did not read your code)

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Use org/renovate-config instead
