### ISSUE TITLE
Support for docker tags with prefixes

### ISSUE THREAD

**Issue by qvalentin** [renovatebot/renovate#16974]
### What would you like Renovate to be able to do?

Currently renovate can not update docker images where the tag contains a prefix followed by the version number.
An example are most images of [snyk](https://hub.docker.com/r/snyk/snyk).

Example:
snyk/snyk:python-3.8 can not be updated to snyk/snyk:python-3.9 because the version can not be parsed.

### If you have any ideas on how this should be implemented, please tell us here.

The versioning implementation for Docker can already seperate a suffix from the tag name.
Prefixes could be handled the same way.

"-" is already being used to seperate the suffix, as shown in:
https://github.com/renovatebot/renovate/blob/main/lib/modules/versioning/docker/index.ts#L24
After seperating you could check for each part if it is the version number and handle the rest as prefixes/suffixes.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
This can be achieved with regex versioning

**Comment by qvalentin** [comment]
> regex versioning

Ups, totally forgot that feature.

Issue can be closed.

Thank you
