### ISSUE TITLE
gomod: hostRules support for subpath under same host  

### ISSUE THREAD

**Issue by nabeelsaabna** [renovatebot/renovate#17045]
### What would you like Renovate to be able to do?

started at: https://github.com/renovatebot/renovate/discussions/16906

To support multiple host rules with different sub-paths for the same host
this includes lookups and commands environment variables (`GIT_CONFIG` and anything else..)

```
{
	"hostRules": [
		{
			"matchHost": "https://github.com/first-org",
			"token": "ghp token first-org"
		},
		{
			"matchHost": "https://github.com/second-org",
			"token": "ghp token second-org"
		},
		{
			"matchHost": "https://github.com",
			"token": "ghp token default"
		},
	]
}
```

### If you have any ideas on how this should be implemented, please tell us here.

**lookups** can be done in multiple ways:

1. try "all" host rules for a specific host one by one (easy but expensive)
2. select host according to prefix match, will require sorting of URLs according to length before selecting the first matched host

**git-config** environment variable should be updated from:

```
export GIT_CONFIG_KEY_2="url.https://ghp_token@github.com/.insteadOf"
export GIT_CONFIG_VALUE_2="https://github.com/"
```

to:

```
export GIT_CONFIG_KEY_2="url.https://<ghp token first-org>@github.com/first-org/.insteadOf"
export GIT_CONFIG_VALUE_2="https://github.com/first-org/"
export GIT_CONFIG_KEY_2="url.https://<ghp token second-org>@github.com/second-org/.insteadOf"
export GIT_CONFIG_VALUE_2="https://github.com/second-org/"
```

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by nabeelsaabna** [comment]
I can assist with creating a "minimal" test data if needed (requires a minimum of 3 private repositories in 2 different organizations)

**Comment by rarkins** [comment]
@nabeelsaabna I believe we do support subpaths for hostRules and if all else is equal then longest matchHost wins: https://github.com/renovatebot/renovate/blob/99de3b72f0a67304903dd2f5061f9e79b41bf15a/lib/util/host-rules.ts#L114-L120

Based on our discussions on Slack, I think in particular you have a problem to be solved with Go artifacts updating?

In this case it might mean we need to switch to a "find all hostRules" approach instead of "apply hostRules" when it comes to github.com?

BTW @Chumper had a PR to greatly enhance our Go artifact config previously, and I think he discovered some gremlins when it came to host matching.

**Comment by nabeelsaabna** [comment]
this part is a bit annoying to understand without debugging it! 😢 
https://github.com/renovatebot/renovate/blob/99de3b72f0a67304903dd2f5061f9e79b41bf15a/lib/util/host-rules.ts#L146-L157

renovate adds 2 default rules and when adding one custom rule like below, the fact that `"hostType": "github"` is defined on `rule #2` makes it take precedence over the longest rule with `/graphql` extension 
```
{
	"hostRules": [
		{
			// rule #1 default
			"timeout": 60000
		},
		{
			// rule #2 default
			"matchHost": "api.github.com",
			"token": "ghp_default_renovate_token",
			"hostType": "github",
			"resolvedHost": "api.github.com"
		},
		{
			// rule #3 custom 
			"matchHost": "https://api.github.com/graphql",
			"token": "ghp_aaaa",
		}
	]
}

```

**Comment by nabeelsaabna** [comment]
we probably need to explain about the default `hostType` and stuff like the difference between `github.com` and `api.github.com`

**Comment by nabeelsaabna** [comment]
so in this issue we only need to support the environment variables for `GIT_CONFIG_KEY` and `GIT_CONFIG_VALUE`

**Comment by rarkins** [comment]
We need to sort the matching somehow, and we chose to sort it by most specific match (e.g. hostType included).

Now that the ordering part is clear, does the problem description change?

**Comment by nabeelsaabna** [comment]
yes 👍 

**Updated description**

- lookups: no need for any changes
- git-config: environment variable should be updated to support multiple value

**Comment by nabeelsaabna** [comment]
Other than host-types (e.g. `github`) that are not datasources..   
Is it safe to say that each [datasource](https://docs.renovatebot.com/modules/datasource/#supported-datasources) have a matching `hostType` ?

**Comment by viceice** [comment]
yes

**Comment by viceice** [comment]
also most manager are using `hostType` to find hostrules

**Comment by nabeelsaabna** [comment]
I believe this hard-coded logic is part of the problem with environment variables: 
https://github.com/renovatebot/renovate/blob/321afb5edeeff480b8bd8af03b61b976ec3f174b/lib/modules/manager/gomod/artifacts.ts#L38-L49

running with this `config.js`
```
module.exports = {
	token: 'ghp_AAA', // test go-private 
	platform: 'github',
	gitAuthor: "Renovate Bot <***@github.com>",
	repositories: [
		'nabeelys/tmp-go-private'
	],	
	hostRules: [
		{
			matchHost: "https://gitlab.com",
			token: "ghp_BBB",
			hostType: "gitlab"
		},
		{
			matchHost: "github.com/nabeelsaabna",
			token: "ghp_CCC",
			hostType: "github"
		},
		{
			matchHost: "https://github.com/nabeelys",
			token: "ghp_AAA",
			hostType: "github"
		}		
	]
};
```

will result in these environment variables for git:
```
{
  "GOPATH": "C:/Users/NABEEL~1/AppData/Local/Temp/renovate/cache/others/go",
  "GOFLAGS": "-modcacherw",
  "CGO_ENABLED": null,
  "GIT_CONFIG_KEY_0": "url.https://ssh:ghp_AAA@github.com/.insteadOf",
  "GIT_CONFIG_VALUE_0": "ssh://git@github.com/",
  "GIT_CONFIG_KEY_1": "url.https://git:ghp_AAA@github.com/.insteadOf",
  "GIT_CONFIG_VALUE_1": "git@github.com:",
  "GIT_CONFIG_KEY_2": "url.https://ghp_AAA@github.com/.insteadOf",
  "GIT_CONFIG_VALUE_2": "https://github.com/",
  "GIT_CONFIG_COUNT": "12",
  "GIT_CONFIG_KEY_3": "url.https://gitlab-ci-token:ghp_BBB@gitlab.com/.insteadOf",
  "GIT_CONFIG_VALUE_3": "ssh://git@gitlab.com/",
  "GIT_CONFIG_KEY_4": "url.https://gitlab-ci-token:ghp_BBB@gitlab.com/.insteadOf",
  "GIT_CONFIG_VALUE_4": "git@gitlab.com:",
  "GIT_CONFIG_KEY_5": "url.https://gitlab-ci-token:ghp_BBB@gitlab.com/.insteadOf",
  "GIT_CONFIG_VALUE_5": "https://gitlab.com/",
  "GIT_CONFIG_KEY_6": "url.https://ssh:ghp_CCC@github.com/nabeelsaabna.insteadOf",
  "GIT_CONFIG_VALUE_6": "ssh://git@github.com/nabeelsaabna",
  "GIT_CONFIG_KEY_7": "url.https://git:ghp_CCC@github.com/nabeelsaabna.insteadOf",
  "GIT_CONFIG_VALUE_7": "git@github.com:nabeelsaabna",
  "GIT_CONFIG_KEY_8": "url.https://ghp_CCC@github.com/nabeelsaabna.insteadOf",
  "GIT_CONFIG_VALUE_8": "https://github.com/nabeelsaabna",
  "GIT_CONFIG_KEY_9": "url.https://ssh:ghp_AAA@github.com/nabeelys.insteadOf",
  "GIT_CONFIG_VALUE_9": "ssh://git@github.com/nabeelys",
  "GIT_CONFIG_KEY_10": "url.https://git:ghp_AAA@github.com/nabeelys.insteadOf",
  "GIT_CONFIG_VALUE_10": "git@github.com:nabeelys",
  "GIT_CONFIG_KEY_11": "url.https://ghp_AAA@github.com/nabeelys.insteadOf",
  "GIT_CONFIG_VALUE_11": "https://github.com/nabeelys"
}
```

since `GIT_CONFIG_KEY_0` will always be matched before `GIT_CONFIG_KEY_6` and `GIT_CONFIG_KEY_9`, this will make them useless keys!
the hard-coded logic should be moved to be at the end rather than the fist one
WDYT ?

**Comment by rarkins** [comment]
Git uses first match only?

**Comment by viceice** [comment]
in that case we need to sort matchHost too, so longest url comes first

**Comment by nabeelsaabna** [comment]
for `go` we want the flat URL `https://github.com/` to always be available, but lower the priority to be lower than any custom hostRules by the user.

currently the code looks for `https://api.github.com/` and automatically apply it to `https://github.com/`, instead we should

1. apply custom rules
2. look for `https://github.com/` exact match if provide in a custom rule (maybe so the default token only used for the repository updates)
3. apply hard-coded solution only if `#2` didn't find the flat `github.com` URL

**Comment by rarkins** [comment]
Can we distinguish between "a custom rule" for github.com vs the rules we automatically add?

**Comment by nabeelsaabna** [comment]
according what I saw the rule we add is for `api.github.com` (not `github.com`)
comment above: https://github.com/renovatebot/renovate/issues/17045#issuecomment-1210362453

**Comment by nabeelsaabna** [comment]
we are making good progress 🎉 

the order of `GIT_CONFIG_KEY_`  is not important for `git`

managed to make the `go get` command to work when all 4 repos are private:

- running on: `github.com/nabeelys/wrn251-private-a`               token-1-GH (renovate default token)
- dependency 1: `github.com/nabeelys/wrn251-private-c`          token-1-GH (renovate default token)
- dependency 2: `github.com/nabeelsaabna/wrn251-private-b`  token-2-GH (hostRule)  
- dependency 3: `gitlab.com/nabeelsaabna/go-private-test`       token-3-GL (hostRule)

```
{
	"$schema": "https://docs.renovatebot.com/renovate-schema.json",
	"dependencyDashboard": true,
	"hostRules": [
		{
			"matchHost": "https://gitlab.com",
			"token": "glpat-aaa",
			"hostType": "gitlab"
		},
		{
			"matchHost": "https://github.com/nabeelsaabna",
			"token": "ghp_bbb",
			"hostType": "go"
		},
		{
			"matchHost": "https://api.github.com/repos/nabeelsaabna",
			"token": "ghp_bbb",
			"hostType": "go"
		}	
	],
	"customEnvVariables": {
		"GOPRIVATE": "github.com/nabeelsaabna,github.com/nabeelys,gitlab.com/nabeelsaabna",
		"GONOSUMDB": "github.com/nabeelsaabna,github.com/nabeelys,gitlab.com/nabeelsaabna",
		"GONOPROXY": "github.com/nabeelsaabna,github.com/nabeelys,gitlab.com/nabeelsaabna"
	},
	"postUpdateOptions": ["gomodTidy"]
}
```

**but!** 
(there is always a but 😞)
lookup is failing for `github.com/nabeelsaabna/wrn251-private-b`

**Comment by nabeelsaabna** [comment]
https://github.com/renovatebot/renovate/blob/9f837f226d5718a5fd7445d0367c1d3e30488c03/lib/util/http/index.ts#L129

since the call to: `https://api.github.com/graphql` always using a single token (most likely the default token) and it's can't be overridden per repository-name since the repository-name is part of the request body (not the URL)

```
{
	"httpOptions": {
		"baseUrl": "https://api.github.com/",
		"method": "post",
		"json": {
			"query": "...query ($owner: String!, $name: String!, $cursor: String, $count: Int!)...",
			"variables": {
				"owner": "nabeelsaabna",
				"name": "wrn251-private-b",
				"cursor": null,
				"count": 100
			}
		},
		"responseType": "json",
		"throwHttpErrors": true,
		"headers": {
			"accept": "application/vnd.github.v3+json"
		}
	}
}
```

**Comment by rarkins** [comment]
Sounds like it could be solved using #15997 too

It could work fairly easily if the go package name includes github.com already (e.g. `matchPackagePrefixes=["github.com/wrn251-"]`) but more challenging for the user if it's e.g. a redirect from `gopkg.in`

In your case though github.com is in the package name so the packageRules approach could work?

**Comment by nabeelsaabna** [comment]
Summary:
the git config was solved in https://github.com/renovatebot/renovate/issues/17137
the remaining part will be fixed in https://github.com/renovatebot/renovate/issues/15997 

should we close this one ?

**Comment by rarkins** [comment]
@nabeelsaabna are you sure it will be solved by #15997?

I thought ultimately this is going to require git config env vars with a path to be passed to `go`. I'm not sure #15997 solves that?

i.e. #15997 might be a solution to Renovate's own datasource lookups, but not sure it solves the `go.sum` artifacts update?

Also relevant: #15274

**Comment by nabeelsaabna** [comment]
if you check the comment above: https://github.com/renovatebot/renovate/issues/17045#issuecomment-1212758366 the artifact update (git config env vars) was solved in https://github.com/renovatebot/renovate/issues/17137

sub path included:
```
  "GIT_CONFIG_KEY_7": "url.https://git:ghp_CCC@github.com/nabeelsaabna.insteadOf",
  "GIT_CONFIG_VALUE_7": "git@github.com:nabeelsaabna",
```

the lookup on the other hand is still pending https://github.com/renovatebot/renovate/issues/15997 and maybe https://github.com/renovatebot/renovate/issues/15274 as well

**Comment by viceice** [comment]
I've created a PR to solve the datasource part, please try

- https://github.com/renovatebot/renovate/pull/17179

**Comment by nabeelsaabna** [comment]
I believe this issue is closed
did we missing something here ?

**Comment by nabeelsaabna** [comment]
we now support multiple go private repositories from different orgs with below example config:
```
{
	"hostRules": [
		{
			"matchHost": "https://github.com/second-org",
			"token": "ghp_123",
			"hostType": "go"
		},
		{
			"matchHost": "https://api.github.com/repos/second-org",
			"token": "ghp_123",
			"hostType": "github"
		},
		{
			"matchHost": "https://github.com/third-org",
			"token": "ghp_345",
			"hostType": "go"
		},
		{
			"matchHost": "https://api.github.com/repos/third-org",
			"token": "ghp_345",
			"hostType": "github"
		}
	]
	"customEnvVariables": {
		"GOPRIVATE": "github.com/second-org,github.com/third-org",
		"GONOSUMDB": "github.com/second-org,github.com/third-org",
		"GONOPROXY": "github.com/second-org,github.com/third-org"
	},
}
```
