### ISSUE TITLE
Gradle wrapper distributionSha256Sum still not updating

### ISSUE THREAD

**Issue by growse** [renovatebot/renovate#17057]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Updates to gradle wrapper versions in `gradle-wrapper.properties` which contain a `distributionSha256Sum` still appear to not be updating the checksum, and only bumping the version.

Previous issues #6148 and #13081 seem to indicate that this has been a problem before and was fixed, so not sure if I'm running into a regression or a new bug manifest in a similar way.

See the PR at https://github.com/owntracks/android/pull/1264/files for an example of where renovate is bumping `distributionUrl` but not changing `distributionSha256Sum`.

### Relevant debug logs

<details><summary>Logs</summary>

```
 "gradle-wrapper": [
      {
        "packageFile": "project/gradle/wrapper/gradle-wrapper.properties",
        "deps": [
          {
            "depName": "gradle",
            "currentValue": "7.5",
            "replaceString": "https\\://services.gradle.org/distributions/gradle-7.5-all.zip",
            "datasource": "gradle-version",
            "versioning": "gradle",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "7.5.1",
                "newValue": "7.5.1",
                "releaseTimestamp": "2022-08-05T21:17:56.000Z",
                "newMajor": 7,
                "newMinor": 5,
                "updateType": "patch",
                "branchName": "renovate/gradle-7.x"
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/gradle/gradle",
            "homepage": "https://gradle.org",
            "currentVersion": "7.5",
            "isSingleVersion": true,
            "fixedVersion": "7.5"
          }
        ]
      }
    ]
  }
}
```

</details>

Logs from https://app.renovatebot.com/dashboard#github/owntracks/android/767100327

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Please find the branch logs from when the incorrect git commit was made

**Comment by growse** [comment]
The PR was opened 3 days ago, and seems to have just dropped off the bottom of the log run list on app.renovatebot.com. Any easy way to re-create it?

**Comment by rarkins** [comment]
Tick the rebase/retry button in the PR

**Comment by PhilipAbed** [comment]
i took the the `gradle-wrapper.properties` file, put it in an empty repo(with the same path as given in https://github.com/owntracks/android/pull/1264/files ) , and it was reproduced

**Comment by rarkins** [comment]
Can you add the reproduction repo to https://github.com/renovate-reproductions ? I just sent you an invite, those permissions are meant to let you create repos. e.g. you can fork yours into that org hopefully. If not I can make you an owner

**Comment by PhilipAbed** [comment]
reproduction repo: https://github.com/renovate-reproductions/17057

**Comment by growse** [comment]
@PhilipAbed many thanks. I had hit the rebase/retry, but the log it produced seemed to be the same as previous runs.

**Comment by MaronHatoum** [comment]
I tried to run Renovate CLI after merging https://github.com/renovatebot/renovate/pull/17164 on the reproduction repository and also I ran docker image Renovate:32.163.1 on the same repository, as I see in the PR the `distributionSha256Sum` has not been updated.
I think this issue still exists.

**Results:**
https://github.com/MaronHatoum/17057/pull/14/files

**Comment by viceice** [comment]
@Churro Did you tested the latest changes from the PR ?

**Comment by Churro** [comment]
Yes, but https://github.com/renovate-reproductions/17057 is too minimal to work with gradle-wrapper, as it lacks the `gradlew` binary. This is also shown in the log output:
> INFO: No gradlew found - skipping Artifacts update

**Comment by viceice** [comment]
@rarkins i don't think there is an issue here, as the minimal reproduction is incomplete, so renovate has no way to update the checksum.

a complete minimal reproduction works as expected. so this should be closed again.

if there is somebody how can create a nonworking complete reproduction should open a new issue.
