### ISSUE TITLE
Create a scheduled GitHub Action to update `data`

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#17050]
### Describe the proposed change(s).

Currently we have some static data, with update scripts, that are manually run. There is:

- `debian-distro-info.json`[^1] and `ubuntu-distro-info.json`[^2] updated by `distro-json-generate.mjs`[^3]
- (Soon) `azure-pipelines-tasks` updated by `azure-pipelines-tasks-json-generate.mjs`
	- #16949

We should add a GitHub Actions pipeline that runs these tasks on a weekly basis, and opens a pull request with any changes.

[^1]: https://github.com/renovatebot/renovate/blob/main/data/debian-distro-info.json
[^2]: https://github.com/renovatebot/renovate/blob/main/data/ubuntu-distro-info.json
[^3]: https://github.com/renovatebot/renovate/blob/main/tools/distro-json-generate.mjs

**Comment by JamieMagee** [comment]
We should also look into automating the sync of Node.js release schedule data[^1] as part of this. No update script is required, but the file is synced from upstream[^2]

[^1]: https://github.com/renovatebot/renovate/blob/main/data/node-js-schedule.json
[^2]: https://github.com/nodejs/Release/blob/main/schedule.json

**Comment by HonkingGoose** [comment]
Yeah I keep manually syncing that `node-js-schedule.json` file with upstream. 😄 

We also have a repository that we intended to use as source for the node.js schedule, with some extra tools to use in Renovate: https://github.com/renovatebot/node-schedule. 

I think the big idea was that we "package up" the `node-schedule` repository and use it as a dependency in our `renovate` repository. I don't know if that is still something we want to do. So before you decide what to do, check the `node-schedule` repository first.

I remember we did a lot of work to `node-schedule` repository somewhat ready for use, but we still have some issues. But this is all a sunk cost anyway, and maybe we're better off using a GitHub Action to update our `data` things.

**Comment by HonkingGoose** [comment]
@JamieMagee does your PR #17080 close this issue? Or do you need/want to do more stuff before closing this issue?

**Comment by JamieMagee** [comment]
Yeah, I think so. I wasn't sure if you wanted to keep this issue open to discuss `node-schedule` work.

**Comment by HonkingGoose** [comment]
I'm closing this issue as done via PR #17080.

We should discuss the future of the `node-schedule` project in this issue:

- https://github.com/renovatebot/node-schedule/issues/43
