### ISSUE TITLE
(feat req) Add <from version> to upgrade pr titles

### ISSUE THREAD

**Issue by hulkish** [renovatebot/renovate#1708]
#### This is a:

* [ ] Bug report (non-security related)
* [X] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [X] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
I think it would be helpful to visualize which pr's are major minor/patch by looking at a list pr's - without having to dive into each pr to see it:s "from" version.

Ex of what this looks like now:
![screenshot_20180323-103959](https://user-images.githubusercontent.com/139332/37835464-99e863f8-2e86-11e8-9bb5-a4070e06d280.png)

**Comment by rarkins** [comment]
I will be refactoring the way prTitle and commitMessage works soon, to make it easier to customise this type of thing without needing to copy/paste/edit the entire template

**Comment by rarkins** [comment]
Waiting on #1747

**Comment by rarkins** [comment]
This should now be achievable via configuration by modifying the `commitMessageExtra` field for npm dependencies.

Default value: https://github.com/renovateapp/renovate/blob/b128870587097cfc1a863bf561fbc01585aba43b/lib/config/definitions.js#L729-L737

I think this config might work:

```
  "npm": {
    "commitMessageExtra": "from {{{currentVersion}}} to {{#if isMajor}}v{{{newVersionMajor}}}{{else}}{{#unless isRange}}v{{/unless}}{{{newVersion}}}{{/if}}"
  }
```

i.e. adding `from {{{currentVersion}}} ` to the beginning
