### ISSUE TITLE
Submodule broken if name contains a dot `.` 

### ISSUE THREAD

**Issue by agaudreault-jive** [renovatebot/renovate#17123]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.154.7

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

Github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Was working with version `32.63.1`.

When trying to run Renovate for a repo that has submodules, the operation fails to fetch the dependency if the submodule name contains a `.`. I assume there is a split somewhere that tries to remove the extension. It is splitting from the first `.`.

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Error mapping git submodules during extraction (repository=org/repo)
      "err": {
        "task": {
          "commands": [
            "ls-remote",
            "--symref",
            "https://github.com/org/com",
            "HEAD"
          ],
          "format": "utf-8",
          "parser": "[function]"
        },
        "message": "remote: Repository not found.\nfatal: repository 'https://github.com/org/com/' not found\n",
        "stack": "Error: remote: Repository not found.\nfatal: repository 'https://github.com/org/com/' not found\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
      }
```

The .gitmodules would look like this
```
[submodule "data/com.org.example"]
	path = data/com.org.example
	url = git@github.com:org/com.org.example.git
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by PhilipAbed** [comment]
by mistake dont mind the retry latest version, please create a reproduction repo example, give us the submodules packages file or something that we can work with, thx
