### ISSUE TITLE
iOS dependencies (CocoaPods/Carthage)

### ISSUE THREAD

**Issue by hisaac** [renovatebot/renovate#1718]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is
* [x] Question

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Hi! I just learned of Renovate from the [most recent episode of The Changelog](https://changelog.com/podcast/289). I'm an iOS developer, and I'd love to have something like this for my iOS projects. Do you think it would be possible to use Renovate to update an iOS project's dependencies via [CocoaPods](https://cocoapods.org) and/or [Carthage](https://github.com/Carthage/Carthage)?

(Note: I'm not asking this as a feature request, just a question on feasibility. If it's theoretically possible, I'd like to start looking into implementing it in my free time.)

**Comment by rarkins** [comment]
Hi @hisaac, welcome!

There's no limit to the scope of languages/package managers that can be supported, so the answer is "yes".

I'll describe here how it is/would be done, and probably put something like this into repository docs soon too.

I am using the term "manager" to refer to a "package manager", e.g. like npm, Docker, Meteor, nvm, etc. The list of current ones are here: https://github.com/renovateapp/renovate/tree/master/lib/manager

Renovate started with `npm`/`yarn` and those are the most complex and not quite "abstracted" from the core of the app yet. The others were added later and right now are pretty much self-contained within the `lib/manager/x` directories with some help from `lib/datasource` too.

To add new languages, you would be best to look at ones like `docker` or `bazel`.

The main parts are:

1. (resolve) Detecting relevant files within the repository
2. (extract) Extracting the full list of dependencies from them
3. (package) Determining what upgrades are available and according to the user's configuration/policy
4. (update) Patching the file(s) ready for Pull Request

Some future manager logic may not be possible to write entirely in JavaScript - or perhaps not a good idea to even if it's possible. So one difference might be that future managers will likely need to call out to a node.js child process to call the package manager from CLI and then parse back the results (either from stdout or a file output). I would be happy to help you bootstrap any you're interested in (by providing the base PR to then be extended, so you can just focus on the logic and not the JS) so let me know if so.

**Comment by hisaac** [comment]
Thanks @rarkins! Good to know that there is a possibility this could work. My next question was going to be how I could get started, but you already answered that 👍

I don't have the bandwidth to work on this at the moment, but I hope to soon. I can ping you here when the time comes.

**Comment by rarkins** [comment]
Renaming this to use as a feature request placeholder
