### ISSUE TITLE
Package-diff link in PR Description is clickable but not working for private NPM packages

### ISSUE THREAD

**Issue by lukaskolafa** [renovatebot/renovate#17240]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.68.0

### Please select which platform you are using if self-hosting.

Azure DevOps (dev.azure.com)

### If you're self-hosting Renovate, tell us what version of the platform you run.

Azure DevOps

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

PR description contains clickable links to the package-diff feature of NPM packages. For private packages, the link is not working. This is confusing for the users. 

From the discussion here: https://github.com/renovatebot/renovate/discussions/17188#discussioncomment-3398637, I understood that private packages-diffs are not supported, which is fine.

expected behavior: the private NPM package update row in the PR Description is not clickable.

### Relevant debug logs

N/A

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
this isn't a bug. i told you not to open an issue until we have a solution idea

**Comment by lukaskolafa** [comment]
sorry, I did that in parallel..
