### ISSUE TITLE
`isVersioningApiConstructor` returns false for all class based versionings

### ISSUE THREAD

**Issue by Gabriel-Ladzaretti** [renovatebot/renovate#17257]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The app is getting versioning on the fly with `getVersionings`
which should instantiate class based versioning but does not due to `isVersioningApiConstructor`

![image](https://user-images.githubusercontent.com/97394622/185407592-1d269e75-e9f4-47ef-90a3-0362b52bfd3e.png)

while we have more than 2 classed based versionings
![image](https://user-images.githubusercontent.com/97394622/185407686-49de8412-1ded-4502-b4be-3161fb843bd6.png)

This causes the below exception in the app as `this` is undefined therefore `this.isValid` throws

```
 INFO: Error comparing updates (repository=nabeelys/docker-test)
       "err": {
         "message": "Cannot read property 'isValid' of undefined",
         "stack": "TypeError: Cannot read property 'isValid' of undefined
		 at isVersion (/worker/node_modules/renovate/dist/modules/versioning/generic.js:65:21)
		 at getUpdatesFromCache (/worker/app/worker/merge-confidence.js:85:17)
		 at renovateRepository (/worker/app/worker/index.js:458:26)
		 at processTicksAndRejections (internal/process/task_queues.js:95:5)
		 at async /worker/app/worker/index.js:539:5"
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by Gabriel-Ladzaretti** [comment]
related code sections
https://github.com/renovatebot/renovate/blob/1c0073d9a978c18b4a81ae89e1f4995897fdd434/lib/modules/versioning/index.ts#L17-L36

https://github.com/renovatebot/renovate/blob/8bd77f747b3da59cc955b2fc4ba3301bcb680ea2/lib/modules/versioning/common.ts#L3-L7

**Comment by rarkins** [comment]
Should it be addressed here or in the app?

**Comment by viceice** [comment]
this seems to me like an app issue, not a renovate issue

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/185424176-6f1a4b10-53eb-4002-8bcc-4b88f04e7c9d.png)
`isVersioningApiConstructor` seems right to me, must be an issue with the app

**Comment by Gabriel-Ladzaretti** [comment]
This is a class which extends `GenericVersioningApi`

![image](https://user-images.githubusercontent.com/97394622/185433152-c995dedd-a394-4d9d-8e68-989b93954e6e.png)

![image](https://user-images.githubusercontent.com/97394622/185433323-b112e950-2340-4324-91a5-b5c7b98e25da.png)

**Comment by Gabriel-Ladzaretti** [comment]
@viceice 
this is a live run on some test repo, check this exit point
i havn't tested it further but it may work only because it was instantiated some place else (?)

![image](https://user-images.githubusercontent.com/97394622/185459075-6012c017-2050-4189-88c4-fdf1b7cf94f2.png)

see the stack trace bottom left side

**Comment by Gabriel-Ladzaretti** [comment]
first place it get instantiated is `lib/modules/manager/api.ts` as part of the first ansible import

**Comment by Gabriel-Ladzaretti** [comment]
and to back this up, it is instantiated when returned from `get` -
![image](https://user-images.githubusercontent.com/97394622/185460662-30b4f48a-f258-4aa8-9e73-90911b5916f5.png)

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/185463175-f19a0dc6-c2f7-419b-966b-e957eef566cb.png)
https://github.com/renovatebot/renovate/blob/189e39bcfc806f8af4a364bb121e0cfbee37b624/lib/modules/versioning/docker/index.ts#L95-L97

**Comment by viceice** [comment]
only the regex manager exports a constructor
https://github.com/renovatebot/renovate/blob/189e39bcfc806f8af4a364bb121e0cfbee37b624/lib/modules/versioning/regex/index.ts#L155-L157
![image](https://user-images.githubusercontent.com/1798109/185463509-2b6d280e-6747-4a03-8a1b-9f55c09e7f8c.png)

**Comment by Gabriel-Ladzaretti** [comment]
ok so it turns out that indeed this is a issue with the app, i probably miss understood the purpose of the `isVersioningApiConstructor` function in this context.

anyway, it turns out that destructuring methods of a given subclass effects the binding of `this` and its super class methods. 

say we have 

```
class A {
   method f
}
```
```
class B extends A {
   method g {this.f()}
}
```

doing 
```
const {g} = B
g()
```
will throw as `f` is no longer a prop of `this`
did a brief search about it but couldnt find an documentation regarding this, but I'm sure there is some where.

solution is basically not to destruct.

**Comment by Gabriel-Ladzaretti** [comment]
![image](https://user-images.githubusercontent.com/97394622/185496743-df8678a3-6735-4cb6-9296-051a56474b53.png)

**Comment by viceice** [comment]
yes, that's why removed all versioning destructioning from oss renovate 😅

**Comment by viceice** [comment]
sa,me restritions are in place for datasourcesand probably more modules in future

**Comment by Gabriel-Ladzaretti** [comment]
Thanks for the help here 😄, this can be closed.
