### ISSUE TITLE
Replace GraphQL API with REST API for container registry and npm packages on GitHub Packages

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#17252]
## Context

GitHub is deprecating the GraphQL API in favor of the REST API for some things. I just wanted to give you a heads-up, so you can look into this.

## Deprecation Notice: GraphQL for Packages

> GitHub Packages is being re-platformed, unlocking great capabilities such as fine-grained permissions, org-level publishing and increased performance.
> 
> Package registries on the new GitHub Packages architecture, including container registry and npm packages, no longer expose data through the [GraphQL API](https://docs.github.com/en/graphql). We recommend using the [REST API](https://docs.github.com/en/rest/packages) instead.
> 
> In the coming months we will be migrating our other GitHub Package registries to this new architecture deprecating the GraphQL API for those registries as well.
> 
> If you have any questions, please [contact GitHub Support](https://support.github.com/contact).

https://github.blog/changelog/2022-08-18-deprecation-notice-graphql-for-packages/

**Comment by viceice** [comment]
i don't think we use those API's at all.

**Comment by rarkins** [comment]
We've seen GitHub pause their GraphQL push for some time, interesting to see the first case of them *reversing* it.

**Comment by HonkingGoose** [comment]
> i don't think we use those API's at all.

I'll close this issue then.
