### ISSUE TITLE
Renovate handles `config.platform.php` different from composer

### ISSUE THREAD

**Issue by internalsystemerror** [renovatebot/renovate#17308]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

There is a setting for composer as documented here https://getcomposer.org/doc/06-config.md#platform, that allows the user to override the detected PHP version when installing packages. Say for example you are locally running PHP 7.4, but in production you are running PHP 8.1. In order to obtain the correct packages for production, this would be set to e.g. `"config": {"platform": {"php": "8.1.3"}}`.

A feature was added to renovate to read the value from this setting in order to override the detected PHP version.

There are 2 large differences however, with how composer and renovate treat these values.

- A setting of `7.4`, would be treated by composer as `7.4.0` and by renovate as `7.4.30` (the latest patch version for this minor) due to the use of docker tags.
- A setting of `7.4.99`, would be treated by composer as a real version, obtaining packages that satisfy this PHP version requirement (the end result being the same as specifying `7.4.30` (the latest patch version for this minor). Renovate on the other hand will fall back to using the `latest` docker tag (which could be a completely different major, e.g. `8.1` when a docker tag with that version number is not found.

The ideal scenario to this would be that if the docker tag for a specific patch is not found, it would fallback to the latest for that minor, and if a docker tag for a specific minor is not found, it would fallback to the latest for that major.

As a compromise, and to mimic how this setting is used in the wild, either specifying a specific PHP version to run against, or by specifying a non-existent version to mean the latest, the following PR will treat a composer override of `7.4` as `7.4.0` in renovate (matching composer) and and override of `7.4.99` as `7.4` in renovate (matching composer).

- PR: https://github.com/renovatebot/renovate/pull/17299
- Example where the wrong PHP version is used: https://github.com/laminas/laminas-skeleton-installer/pull/39

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by internalsystemerror** [comment]
From the example repository linked, this is the lock file maintenance branch. The `composer.json` for this repository [specifies a `config.platform.php` setting of `7.3.99`](https://github.com/laminas/laminas-skeleton-installer/blob/eed49c9720b08930a56a377b42dadbe0511fe3a0/composer.json#L22).

There are 2 versions of the package `laminas/laminas-component-installer`:

[`2.5.1` contains the following `composer.json`](https://github.com/laminas/laminas-component-installer/blob/6f1e11473861e4e2208178b1dfa395a992039674/composer.json#L28)
```json
"require": {
  "php": "^7.3 || ~8.0.0"
}
```

[whilst `2.8.0` of the same package contains:](https://github.com/laminas/laminas-component-installer/blob/3c998d2b2755985c71cd4d5d9b294228f63d3a65/composer.json#L34)
```json
"require": {
  "php": "^7.4 || ~8.0.0 || ~8.1.0"
}
```

Because composer is passing the PHP version to get packages for as `7.3.99`, it fetches version `2.5.1` of the above as this matches the required php constraint, whilst `2.8.0` does not.

When renovate uses this version number to fetch a docker tag, `7.3.99` does not exist, resulting in the warning
> WARN: Failed to find a tag satisfying constraint, using "latest" tag instead(branch="renovate/packagist-composer/composer-vulnerability")
{
  "depName": "[docker.io/renovate/php](http://docker.io/renovate/php)",
  "constraint": "7.3.99",
  "scheme": "composer"
}

And thus the docker image `php:latest` is used, which is actually PHP `8.0.22`.

**Comment by internalsystemerror** [comment]
As an aside, I thought I would check how node handles this. All is fine, but I wanted to document my findings anyway.

Node `16.15.0` & `"engines": {"node": "16.15"}"` PASSES
Node `16.15.0` & `"engines": {"node": "16.15.0"}"` PASSES
Node `16.15.0` & `"engines": {"node": "16.15.1"}"` FAILS
Node `16.15.1` & `"engines": {"node": "16.15"}"` PASSES
Node `16.15.1` & `"engines": {"node": "16.15.0"}"` FAILS
Node `16.15.1` & `"engines": {"node": "16.15.1"}"` PASSES

So it appears that node considers the value `16.15` as `16.15.*` which complies with the docker tag of `16.15` being used (which is the same version as docker tag `16.15.1`). This again differing from composer which will treat a platform value of `7.4` as `7.4.0`, explaining why this problem doesn't occur with node.

**Comment by viceice** [comment]
please provide some kind of documentation/ source code for composer behavior

**Comment by internalsystemerror** [comment]
> please provide some kind of documentation/ source code for composer behavior

The documentation is linked at the top of "Describe the bug" in the original post: https://getcomposer.org/doc/06-config.md#platform. And from that:
> This also means if {"php":"7.4"} is specified; no packages will be used that define 7.4.1 as minimum.

**Comment by rarkins** [comment]
In the case of x.y.z being specified, it seems to mean `>=x.y.0, <=x.y.z`. i.e. doesn't matter if `z` is `99` but the highest `x.y.<anything>` is `x.y.20`. Is there a reason why not to use `>=x.y.0, <=x.y.z`?

**Comment by internalsystemerror** [comment]
Composer requires a specific (pinned) version as this is used instead of detecting the PHP version that composer is being run on. This allows you to fetch dependencies for a different PHP version (e.g. production) than you may be running locally. It is for this reason that specifying a range is not allowed.

It is only the handling of this `config.platform.php` key that this targets. The standard `require.php` key would be unaffected (which allows ranges).

It's important to note that Composer's `config.platform.php` works different from NPM's `engines.node`. Composer uses it to simulate the running PHP version when resolving dependencies, whereas NPM uses it to prevent installation, or to show a warning during installation.

**Comment by rarkins** [comment]
The field may allow a specific version, but composer does not seem to honour that version literally based on your description. We should care about the subsequent behaviour of composer and not the syntax of the field itself.

For example in go.mod the version there represents the minimum go version which works. It would be incorrect to argue that the field doesn't allow a range because that's not the point. Similarly of the php version is not treated strictly then we shouldn't argue to treat it as a version either.

**Comment by internalsystemerror** [comment]
Composer does treat that literally, but what it views as literal differs from how the docker tags are set up.

`7.4` is treated by composer as `7.4.0` but via renovate (docker tags) `php:7.4`.
`7.4.99` is treated by composer as `7.4.99` but via renovate (docker tags) `php:latest`.

**Comment by rarkins** [comment]
I think there's no disagreement on the 7.4 -> 7.4.0 part, and that's easily handled.

The second one remains to be decided.

One key thing is that Composer seems to use this as a compatibility during *lookup* to decide which versions of dependencies are OK. However the topic of this discussion is how Renovate decides which version of PHP to install when running `composer` commands, so it's not the same thing. I'm still not sure why you disagree with my proposal to treat `x.y.z` as `>=x.y.0, <=x.y.z`. This would mean that if composer.compatibility.php doesn't exist then it will fall back to running the highest version which does exist within the same minor range.

**Comment by internalsystemerror** [comment]
>I think there's no disagreement on the 7.4 -> 7.4.0 part, and that's easily handled.

Agreed.

> One key thing is that Composer seems to use this as a compatibility during lookup to decide which versions of dependencies are OK.

Correct.

> I'm still not sure why you disagree with my proposal to treat x.y.z as >=x.y.0, <=x.y.z

I didn't realise this was a proposal, I thought you were thinking that's how composer treated it. The idea here would be to translate the fixed version from composer to a range for renovate? Assuming this is only used to decide which docker tag to use then I would agree with you again.

**Comment by internalsystemerror** [comment]
If we want to go down the route of treating it as a range, I think the more compatible one would be:

`7.4.99` => `<=7.4.99` instead as this would handle missing minors and majors also. I'm sure there are a lot of edge cases not being considered here but I'm not able to think of any that wouldn't be handled by this.

I will update the PR accordingly.

**Comment by rarkins** [comment]
OK, I'm ok to simply use `<=` as you suggest, if you think it's also common that people might define a version with a major which doesn't exist (e.g. `99.0.0`). Ultimately Renovate will pick the highest matching docker image or install version.

BTW Renovate doesn't today use this compatibility as part of its own lookup logic, but one day it should.

**Comment by internalsystemerror** [comment]
I'm not sure any of this is common really, but people definitely do use the platform override for composer, and hopefully they may try renovate. I'm just trying to consider how they may use the field rather than how we (laminas) want to use the field.

One thing I'm still unsure of is how stability flags would be handled. e.g. let's say PHP 9.0.0-beta1 comes out, and in order to test that, someone enters that value into the platform field, this wouldn't be handled how I've planned it:

```ts
if (composerJson.config?.platform?.php) {
    const major = api.getMajor(composerJson.config.platform.php);
    const minor = api.getMinor(composerJson.config.platform.php);
    const patch = api.getPatch(composerJson.config.platform.php);

    // handle where x is taken by composer to mean lowest patch of the lowest minor (x.0.0)
    if (minor === null || minor === 0) {
      res.php = `${major}.0.0`;
    }
    // handle where x.x is taken by composer to mean lowest patch (x.x.0)
    else if (patch === null || patch === 0) {
      res.php = `${major}.${minor}.0`;
    }
    // handle non-existent patch numbers
    else {
      res.php = `<=${major}.${minor}.${patch}`;
    }
  }
```

Is there another method I could use to extract that? Or do you have any other suggestions how that should be handled? This assumes there would be a docker image available for the beta, which I suppose doesn't happen? (at least, not that I've seen)

**Comment by rarkins** [comment]
Support for unstable versions would depend on some changes to e.g. https://github.com/containerbase/php-prebuild

**Comment by internalsystemerror** [comment]
If that's not handled currently, then I'm all for not extending the scope of this 😆

**Comment by internalsystemerror** [comment]
Thank you all.

**Comment by internalsystemerror** [comment]
I can confirm we are seeing now fixed. Thanks again.
