### ISSUE TITLE
Use git-command to compute conflict status

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#17499]
### Describe the proposed change(s).

Use the git-command: [ git merge-tree](https://git-scm.com/docs/git-merge-tree) to check of 2 branches have conflict.

This can a potential replacement for computing conflict status.
I still need to check if this for any performance improvements, or any potential drawbacks, will update soon.

Current logic:
1. Start git merge
2. if conflict found return false
3. else abort merge and return true

With the merge-tree command we will get full output, like below which we can use to get  conflict info:

1. No Conflict
```diff
merged
  result 100644 a8c88e9e2ff6845c5930144e58a0b01ce4e3dc8d lib/util/cache/repository/types.ts
  our    100644 3a24bab188ee298ec73d76d2efe180f26088d409 lib/util/cache/repository/types.ts
@@ -1,6 +1,5 @@
 import type { PackageFile } from '../../../modules/manager/types';
 import type { RepoInitConfig } from '../../../workers/repository/init/types';
-import type { GitConflictsCache } from '../../git/types';

 export interface BaseBranchCache {
...
```

2. Conflicted
```diff
changed in both
  base   100644 3a24bab188ee298ec73d76d2efe180f26088d409 lib/util/cache/repository/types.ts
  our    100644 91b63c61649ced9ad728ac990f97a853a460ab2a lib/util/cache/repository/types.ts
  their  100644 a8c88e9e2ff6845c5930144e58a0b01ce4e3dc8d lib/util/cache/repository/types.ts
@@ -1,6 +1,5 @@
 import type { PackageFile } from '../../../modules/manager/types';
 import type { RepoInitConfig } from '../../../workers/repository/init/types';
-import type { GitConflictsCache } from '../../git/types';

 export interface BaseBranchCache {
 ```
Along with a list of confliced files we also get a exit statis which is 0 (clean merge), 1 (conflict) or others if there is some other.
It is recommended to use exit status so we can do so.

**Comment by rarkins** [comment]
This should be "researched" to be sure it's the best approach, before too much code is written or merged

**Comment by RahulGautamSingh** [comment]
https://schacon.github.io/git/git-merge-tree.html
Haven't been able to find anything bad about it, chatGPT suggests to not use it though.🙃

I checked the official docs recently after there were some updates to it and a mistakes to avoid section has been added to it. Even [there](https://git-scm.com/docs/git-merge-tree#_mistakes_to_avoid) there seems no mention of anything could be troublesome for us.

**Comment by rarkins** [comment]
@RahulGautamSingh what was the motivation for this issue? e.g. do we have a problem with the current approach?
