### ISSUE TITLE
Support new Github Default Release/Tag URL Schema (bazel)

### ISSUE THREAD

**Issue by cpsauer** [renovatebot/renovate#17498]
### What would you like Renovate to be able to do?

Hello again, wonderful Renovate folks.

GitHub seems to have changed the default URL it exposes for releases/tags. At least for Bazel, Renovate quietly skips those new URLs. It's possible the issue is more general. It'd be great if Renovate could handle this new default GitHub URL schema.

Links from GitHub release pages [(example)](https://github.com/libcpr/cpr/releases) are by default of the following form: Example: https://github.com/libcpr/cpr/archive/**refs/tags/**1.9.0.tar.gz
Instead of https://github.com/libcpr/cpr/archive/1.9.0.tar.gz 
(Stars added above to emphasize inserted region. Actual URL does not contain stars.)

Minimal reproduction: https://github.com/renovate-reproductions/17498-renovate-reproduction-new-archive-url
Note the PR to update the entry with the old form URL but not the new form.

Cheers, and thanks for all you do.
Chris

### If you have any ideas on how this should be implemented, please tell us here.

Some notes:

The log listed "skipReason": "invalid-value" and "currentValue": "refs", so it looks like it's mis-parsing based on the old url.

I think I see a reference to this new URL format here https://github.com/renovatebot/renovate/blob/d5a167c5177cbb632308fa0ddb6632e0b4c20614/lib/modules/datasource/github-tags/cache.ts#L15

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by cpsauer** [comment]
@rarkins noted that this is blocked by https://github.com/renovatebot/renovate/issues/9667

**Comment by cpsauer** [comment]
[@rarkins, sorry to bother you, but any chance you could have Renovate take ownership of the [minimal reproduction repo](https://github.com/cpsauer/renovate-reproduction-new-archive-url) if it's going to be blocked for a while? I think I recall that you had a good place for these repos and I'm a little too into keeping my profile clean.]

**Comment by viceice** [comment]
> [@rarkins, sorry to bother you, but any chance you could have Renovate take ownership of the [minimal reproduction repo](https://github.com/cpsauer/renovate-reproduction-new-archive-url) if it's going to be blocked for a while? I think I recall that you had a good place for these repos and I'm a little too into keeping my profile clean.]

forked to https://github.com/renovate-reproductions/17498-renovate-reproduction-new-archive-url

**Comment by zharinov** [comment]
Seems to work correctly, isn't it?
https://github.com/renovate-testing/test-17498-strip-prefix/pulls

**Comment by zharinov** [comment]
Feel free to reopen, if it's not

**Comment by cpsauer** [comment]
Sure looks like it does now! Thanks for crushing that test case. 

We really appreciate all the work you all have been doing around Bazel recently--I think this one in particular will save users lots of time and confusion. Thank you! 🚀
