### ISSUE TITLE
docker pin digest PRs missing digest value in name 

### ISSUE THREAD

**Issue by setchy** [renovatebot/renovate#17549]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

`pinDigest` PRs are missing the digest value as a suffix in the PR

Reproduction repository - https://github.com/setchy/renovate-docker-test/pull/1 

Current PR name: `Pin Node.js to `
Expected PR name: `Pin Node.js to d5d7d8e`

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
Forked to https://github.com/renovate-reproductions/17549
