### ISSUE TITLE
`matchPaths` doesn't support +() anymore?

### ISSUE THREAD

**Issue by TWiStErRob** [renovatebot/renovate#17642]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I tried setting up `matchPaths` as documented here:
https://docs.renovatebot.com/configuration-options/#matchpaths
> If you want to avoid the partial string matching so that only glob matching is performed, wrap your string in +(...)

and as seen here: https://github.com/renovatebot/renovate/discussions/17406
```json
"matchPaths": [
	"+(build.gradle.kts)",
	"+(*/build.gradle.kts)",
	"+(*/*/build.gradle.kts)",
	"+(gradle/libs.versions.toml)"
],
```
this didn't work, I was still getting PRs.

Then following @rarkins advice, I looked at the logs and split up my rules, because it was incorrectly set up.
Then I was still getting PRs...
Then I investigated deeper and **proved that minimatch doesn't work with the documented `+()` syntax**.

### Relevant debug logs

<details><summary>Investigation details</summary>

Then I set up renovate locally (self-hosted) and modified `paths.js` under `node_modules` like this:
```diff
        if (is_1.default.undefined(matchPaths)) {
            return null;
        }
        if (is_1.default.undefined(packageFile)) {
            return false;
        }
+        console.log(`${packageFile} against ${matchPaths}`);
        return matchPaths.some((rulePath) => packageFile.includes(rulePath) ||
            (0, minimatch_1.default)(packageFile, rulePath, { dot: true }));
```
this somehow gave me an idea to remove the `+()` part.
Then magic happened, everything suddenly worked.

I investigated further:
1. `package.json`:
```json
{
	"dependencies": {
		"minimatch": "5.1.0"
	}
}
```
2. `npm install`
3. `index.js`:
```javascript
const minimatch = require("minimatch");

function test(rulePath, packageFile) {
	let includes = packageFile.includes(rulePath);
	let match = minimatch(packageFile, rulePath, { dot: true });
	const result = includes || match;
	console.log(`${packageFile}.includes(${rulePath}) = ${includes} || minimatch(${rulePath}, ${packageFile}) = ${match} => ${result}`);
}

console.log("raw");
test("gradle/agp.versions.toml", "gradle/agp.versions.toml");
test("docs/examples/release/**", "docs/examples/release/gradle/wrapper/gradle-wrapper.properties");
test("docs/debug/agp*-gradle*/gradle/wrapper/gradle-wrapper.properties", "docs/debug/agp333-gradle4103/gradle/wrapper/gradle-wrapper.properties");
console.log("+()");
test("+(gradle/agp.versions.toml)", "gradle/agp.versions.toml");
test("+(docs/examples/release/**)", "docs/examples/release/gradle/wrapper/gradle-wrapper.properties");
test("+(docs/debug/agp*-gradle*/gradle/wrapper/gradle-wrapper.properties)", "docs/debug/agp333-gradle4103/gradle/wrapper/gradle-wrapper.properties");
```
4. `node index.js`
```
raw
gradle/agp.versions.toml.includes(gradle/agp.versions.toml) = true || minimatch(gradle/agp.versions.toml, gradle/agp.versions.toml) = true => true
docs/examples/release/gradle/wrapper/gradle-wrapper.properties.includes(docs/examples/release/**) = false || minimatch(docs/examples/release/**, docs/examples/release/gradle/wrapper/gradle-wrapper.properties) = true => true
docs/debug/agp333-gradle4103/gradle/wrapper/gradle-wrapper.properties.includes(docs/debug/agp*-gradle*/gradle/wrapper/gradle-wrapper.properties) = false || minimatch(docs/debug/agp*-gradle*/gradle/wrapper/gradle-wrapper.properties, docs/debug/agp333-gradle4103/gradle/wrapper/gradle-wrapper.properties) = true => true
+()
gradle/agp.versions.toml.includes(+(gradle/agp.versions.toml)) = false || minimatch(+(gradle/agp.versions.toml), gradle/agp.versions.toml) = false => false
docs/examples/release/gradle/wrapper/gradle-wrapper.properties.includes(+(docs/examples/release/**)) = false || minimatch(+(docs/examples/release/**), docs/examples/release/gradle/wrapper/gradle-wrapper.properties) = false => false
docs/debug/agp333-gradle4103/gradle/wrapper/gradle-wrapper.properties.includes(+(docs/debug/agp*-gradle*/gradle/wrapper/gradle-wrapper.properties)) = false || minimatch(+(docs/debug/agp*-gradle*/gradle/wrapper/gradle-wrapper.properties), docs/debug/agp333-gradle4103/gradle/wrapper/gradle-wrapper.properties) = false => false
```
The second bit was really surprising, and it suggests that either the documentation is wrong (outdated/removed feature), or there's a bug in the way Renovate calls `minimatch`, or I just misunderstood that sentence.

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
https://runkit.com/embed/0i5z2ofv1kk0

Seems like we misunderstood how +() works

**Comment by fgreinacher** [comment]
> https://runkit.com/embed/0i5z2ofv1kk0
> 
> Seems like we misunderstood how +() works

Should we maybe adapt [the documentation](https://docs.renovatebot.com/configuration-options/#matchpaths) then?

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/1540469/205019029-3f23fdba-2336-4b49-afd7-0403517085b2.png">

**Comment by rarkins** [comment]
Yes, let's recommend `matchFiles` instead

**Comment by fgreinacher** [comment]
> Yes, let's recommend `matchFiles` instead

But how does `matchFiles` help to "avoid the partial string matching"?

**Comment by rarkins** [comment]
@fgreinacher what's the `matchPaths` pattern you want?

**Comment by fgreinacher** [comment]
@rarkins Nothing fancy, I just want to be sure that it’s not interpreted as a partial string match, but as a glob pattern.

**Comment by rarkins** [comment]
Yes, I think we should remove it, maybe also log a deprecation warning if there's a match which is partial file match. I think we can close this issue with such docs/logging changes

**Comment by fgreinacher** [comment]
Should we close this now that the relevant chapter has been removed from the docs?

**Comment by TWiStErRob** [comment]
Nice fixes, thank you! I really like the realistic examples in the new docs 🙏.
