### ISSUE TITLE
Refactor token handling

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#1768]
I would like to refactor how we handle tokens as a first step towards #1500 perhaps, or a partial implementation.

i.e. keep the same level of configurability for now, but improve how we handle it so that extensive configurability can be added later.

The problem we have is messy use of `GITHUB_TOKEN` and `GITHUB_ENDPOINT`. It started as a convenient way to work with `gh-got` but now it's too messy for its own good. The way it works is this:

- Bot owners can configure either `GITHUB_TOKEN` or `token` via CLI or config.js
- If there's no token, then we error
- We then set (or reset) `env.GITHUB_TOKEN` during `initRepo()`

The GitLab and VSTS platforms may have taken similar approaches (copied what we have with GitHub).

We do something similar for `GITHUB_ENDPOINT`, e.g. for GitHub Enterprise use.

This worked fairly nicely and conveniently because we would expose the env during `initRepo()` and then `gh-got` automatically detects those env variables and mutates requests before passing to `got`.

It came a bit unstuck when GHE users need to hit github.com for commit histories and release notes (changelog). GitHub.com is a totally different host from their on-prem GHE instance so needs a different token. I added a bit of a hacky workaround in the changelog code where it detects if `GITHUB_ENDPOINT` is set and if so then it deletes it and swaps `GITHUB_COM_TOKEN` -> `GITHUB_TOKEN` and then swaps it back again afterwards. It works, but it's a hack.

Also note that we export the platform to `global.platform` which is also a bit hacky but I think that's probably a hack we want to keep because it makes so many other files much simpler.

The goal of this issue would be to remove the messy use of `GITHUB_TOKEN` except for in the very first step where we read it in config. i.e. `GITHUB_TOKEN` should be read into `config.token` and `GITHUB_ENDPOINT` into `config.endpoint` but after that there should be no reference to them in our files and we might also want to *delete* them from env to ensure no conflicts with `gh-got`. For backwards compatibility we might also want to store `GITHUB_COM_TOKEN` into config too, or let initRepo handle it.

We should then pass the endpoint and token as part of `initRepo()` and store them as state within the "platform".

In future, requests destined for `github.com` should use (logically) `GITHUB_COM_TOKEN || GITHUB_TOKEN` while ones to GHE use `GITHUB_TOKEN`.

If there's no way to clean up the mess without implementing #1500 then perhaps we do it. If we want to rip the bandaid off in one go with a new major release and deprecate GITHUB_TOKEN and GITHUB_ENDPOINT (providing official renovate config equivalents) then that might also be worth it.

Let's discuss in this issue until we have an agreed solution, before implementing.

**Comment by rarkins** [comment]
Here's how a new `authentication` array for #1500 might look:

```
    "authentication": [
	  {
        "host": "github.com",
        "token": "abcdefghkasdfajsdfasdfasfd"
	  },
      {
        "host": "internal.company.com",
        "token": "zzzzzyyyyyyyyyyxxxxxxxxxxx"
	  }
    ]
```

The above would be the equivalent of:
```
GITHUB_ENDPOINT=internal.company.com
GITHUB_TOKEN=zzzzzyyyyyyyyyyxxxxxxxxxxx
GITHUB_COM_TOKEN=abcdefghkasdfajsdfasdfasfd
```

**Comment by kayoub5** [comment]
@rarkins is there still any in progress refactoring that delays this?

**Comment by rarkins** [comment]
@kayoub5 none affecting this code, so please take a look and propose your idea. Eg perhaps we standardise on `got` for the transport later and wrote our own wrapper to handle auth?

**Comment by dylang** [comment]
>  I added a bit of a hacky workaround in the changelog code where it detects if GITHUB_ENDPOINT is set and if so then it deletes it and swaps GITHUB_COM_TOKEN -> GITHUB_TOKEN and then swaps it back again afterwards. It works, but it's a hack.

`gh-got` doesn't *require* using `process.env.GITHUB_TOKEN`, that's just available as a global default. If we *always* pass the value as an option then it is used instead.

From the [gh-got readme](https://github.com/sindresorhus/gh-got):

```js
const ghGot = require('gh-got');

(async () => {
	const {body} = await ghGot('https://api.github.com/users/sindresorhus', {token: 'foo'});

	console.log(body.login);
	//=> 'sindresorhus'
})();
```
