### ISSUE TITLE
Re-created PRs w/ automerge disabled have wrong automerge-message

### ISSUE THREAD

**Issue by snazy** [renovatebot/renovate#17704]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate opened [this PR](https://github.com/snazy/nessie/pull/1232) as a "replacement" for [this PR](https://github.com/snazy/nessie/pull/1197). I suspect, that the merge of 1197 got lost during a rebase against the original repo and a force push.

The `Configuration` section on 1232 says: `Automerge: Disabled by config. Please merge this manually once you are satisfied.`
But that's not exactly true, automerge has been disabled, because of `Disable automerge to prevent re-created PRs from being merged automatically` (from the DEBUG log).

Is it possible to mention that in the `Configuration` section, because the `Disabled by config` is misleading.
Or maybe also mention the old PR (1197 in this case) in the new PR (1232)?

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: findPr(renovate/versionjersey, fix(deps): update dependency org.glassfish.jersey:jersey-bom to v2.37, !open)(branch="renovate/versionjersey")
DEBUG: Found PR #1197(branch="renovate/versionjersey")
DEBUG: Found closed PR with current title(branch="renovate/versionjersey")
DEBUG: Returning PR from cache(branch="renovate/versionjersey")
DEBUG: Disable automerge to prevent re-created PRs from being merged automatically.(branch="renovate/versionjersey")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
I've rolled back this feature in production, due to an abnormally high number of PR comments occurring on github. This feature shouldn't trigger an increase in them, so I have reverted it out of caution because there's no ill effects. We'll consider your suggestion if we reimplement it
