### ISSUE TITLE
Can't access private GitHub repos in another org

### ISSUE THREAD

**Issue by jmreicha** [renovatebot/renovate#17731]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I am attempting to read and update a private package from another org in my repo but seem to be hitting a wall. Logs say that renovate failed to look up the dependency - I do know the token works as I have tested it locally with curl, not sure what I am missing.

Following the instructions from [here](https://docs.renovatebot.com/getting-started/private-packages/#example-for-gomod):

And here's my test case for updating a single module:

https://github.com/klamathbytes/renovate-test-cross-org

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: GitHub 404
{
  "url": "https://api.github.com/repos/gruntwork-io/terraform-aws-load-balancer/tags?per_page=100"
}
DEBUG: Datasource 404
{
  "datasource": "github-tags",
  "packageName": "gruntwork-io/terraform-aws-load-balancer",
  "url": "https://api.github.com/repos/gruntwork-io/terraform-aws-load-balancer/tags?per_page=100"
}
DEBUG: Failed to look up dependency github.com/gruntwork-io/terraform-aws-load-balancer (github.com/gruntwork-io/terraform-aws-load-balancer)(packageFile="module-2/main.tf", dependency="github.com/gruntwork-io/terraform-aws-load-balancer")
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
This unfortunately isn't a usable reproduction because the token can only be decrypted when inside the production app runtime.

I have forked this repo and tested it locally with the exact same setup but a dummy token. What I could confirm was:
- The dummy token from the hostRules was used to query the terragrunt repo
- When the token wasn't valid, GitHub returned "bad credentials"
- When the token was valid, but didn't have rights to access the repo, GitHub returned 404

**Comment by jmreicha** [comment]
Hrmm I wonder how to create a valid reproduction here then 🤔 

> When the token was valid, but didn't have rights to access the repo, GitHub returned 404

This was the result I saw but the same token used locally does work so I’m not sure what I’m missing other than encrypting incorrectly.

**Comment by rarkins** [comment]
I suggested to use two new github orgs here: https://github.com/renovatebot/renovate/discussions/17595#discussioncomment-3606040

Then run using Renovate locally, not the app.

**Comment by jmreicha** [comment]
Okay I will give that a shot, thanks.

**Comment by jmreicha** [comment]
So I ran it locally in Docker container with `GTIHUB_COM_TOKEN` and removed the `hostRules` config from renovate.json and everything worked as expected, I am going to try setting the token directly next.

My guess at this point is that setting the organization from the [encrypt page](https://app.renovatebot.com/encrypt) is causing the issue. Out of curiosity, why is the organization required when using something like a PAT that doesn't need to be scoped to an org?

**Comment by rarkins** [comment]
It's needed to avoid "replay" attacks. If the org you encrypted wasn't scoped to your org then anyone who gets a copy of the encrypted value could reuse it in their own org and potentially exfiltrate your private repos/packages/whatever

**Comment by jmreicha** [comment]
Ahhhh that makes sense, thank you. So it looks like running this internally is basically the way around this then.
