### ISSUE TITLE
Include `nx` core library in `nrwl-monorepo` group

### ISSUE THREAD

**Issue by AndrewLeedham** [renovatebot/renovate#17886]
### What would you like Renovate to be able to do?

When grouping `@nrwl` packages the main package `nx` is not included (I guess because it is now in the `@nrwl` scope), this recently caused some hard to debug issues due to the mismatch.

This PR shows the issue: https://github.com/xeroxinteractive/browserslist-tools/pull/713 it was failing until I manually updated the `nx` package.

### If you have any ideas on how this should be implemented, please tell us here.

Add `nx` to the `nrwl-monorepo` group.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by AndrewLeedham** [comment]
I was looking at fixing this, but it looks to me like it should already do this. Since, it should be matching against `https://github.com/nrwl` and `nx` is in the org, I was assuming it matched based on the `@nrwl` scope.

**Comment by viceice** [comment]
all nx packages should be automatically grouped by sourceUrl not package prefix. so it seems you use a npm proxy which doesn't return required metadata.

on my own nx workspaces renovate always group all nx packages.

**Comment by AndrewLeedham** [comment]
@viceice What do you mean by "npm proxy" I am using the renovate GitHub app, not self hosting. The project uses `yarn` which has a proxy, but that just forwards to npm.

**Comment by viceice** [comment]
renovate should already group all nx packages, so if not it's probably a config issue, as it works for me as expected

**Comment by viceice** [comment]
npm proxy = custom npm registry.

yarn only uses a custom DNS entry, the target is the same as the normal npm registry

**Comment by AndrewLeedham** [comment]
>npm proxy = custom npm registry.
>
> yarn only uses a custom DNS entry, the target is the same as the normal npm registry

Right, it is not that then.

My config is:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "dependencyDashboard": true,
  "labels": [
    "change: dependencies"
  ],
  "reviewers": [
    "AndrewLeedham"
  ],
  "schedule": [
    "before 9am on the 15th day of the month"
  ],
  "timezone": "Europe/London",
  "automerge": true,
  "automergeType": "pr",
  "platformAutomerge": true,
  "assignAutomerge": true,
  "automergeStrategy": "merge-commit",
  "extends": [
    ":ignoreModulesAndTests",
    ":autodetectPinVersions",
    "group:allNonMajor",
    "group:monorepos",
    "group:recommended",
    "group:definitelyTyped",
    ":prHourlyLimit2",
    ":prConcurrentLimit20",
    ":semanticCommitsDisabled",
    "workarounds:all"
  ]
}
```
The generated PR: https://github.com/xeroxinteractive/browserslist-tools/pull/713 does not include `nx`.

**Comment by AndrewLeedham** [comment]
I created a minimal repo with the default config and the same happens: https://github.com/AndrewLeedham/renovate-nx-repro/pull/2

I wonder if it is because `nx` is set to `latest` 🤔

**Comment by AndrewLeedham** [comment]
Closing as duplicate of https://github.com/renovatebot/renovate/issues/3945
