### ISSUE TITLE
Only dependency dashboard, no commits

### ISSUE THREAD

**Issue by orenmazor** [renovatebot/renovate#17944]
### What would you like Renovate to be able to do?

we have fairly strict commit requirements, so I can't quite sell letting renovatebot open MRs for me (yet, but working on it).

what I'd love to have it do is just open gitlab issues (dependency dashboard or otherwise) so we know that we need to update something.

is this possible, or does the flow absolutely require a new branch + commit to be created?

### If you have any ideas on how this should be implemented, please tell us here.

I'm not sure. I could come up with a few things but I yield to the experts that have more context than me :) 

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
Set dependencyDashboard=true and no update MRs will be created. 

Then you just need to decide what to do about onboarding (initial config) or not

**Comment by orenmazor** [comment]
weird. I have that set and it's still trying to create commits..

note that I used dependencyDashboardApproval and dependencyDashboard interchangeably. I saw that the former implies the latter.

```
{
  "token": "SNIP",
  "platform": 'gitlab',
  "enabledManagers": ["terraform", "terraform-version"],
  "endpoint": "https://gitlab/api/v4",
  "autodiscover": true,
  "dependencyDashboardApproval": true,
  "automerge": false,
  "assigneesFromCodeOwners": true
}

```

**Comment by rarkins** [comment]
It may be the onboarding pull request commit

**Comment by rarkins** [comment]
You can set requireConfig=optional and onboarding=false to skip onboarding

**Comment by orenmazor** [comment]
fantastic. exactly what I was trying to work out. thanks!
