### ISSUE TITLE
Error when prHourlyLimit config is set

### ISSUE THREAD

**Issue by jhaumont** [renovatebot/renovate#18006]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.204.5

### If you're self-hosting Renovate, select which platform you are using.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitHub

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

If you set `prHourlyLimit` param in renovate config of a GitHub repo, you will have an error during scan. (See logs)

### Relevant debug logs

<details><summary>Logs</summary>

{
    "name": "renovate",
    "hostname": "renovate-manager-6bb5895648-mmzvh",
    "pid": 10625,
    "level": 50,
    "logContext": "2rz9_uu_6vWhmgDm0kuEC",
    "repository": "org/test-repo",
    "err": {
        "message": "Cannot read properties of undefined (reading 'startsWith')",
        "stack": "TypeError: Cannot read properties of undefined (reading 'startsWith')\n    at /usr/src/app/node_modules/renovate/lib/workers/repository/process/limits.ts:23:27\n    at Array.filter (<anonymous>)\n    at getPrHourlyRemaining (/usr/src/app/node_modules/renovate/lib/workers/repository/process/limits.ts:20:36)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at getPrsRemaining (/usr/src/app/node_modules/renovate/lib/workers/repository/process/limits.ts:90:27)\n    at writeUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/write.ts:50:24)\n    at update (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:147:11)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:52:19)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:160:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
    },
    "msg": "Error checking PRs created per hour",
    "time": "2022-09-27T15:21:29.932Z",
    "v": 0
}

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Can you update your Renovate and retry? There was a similiar problem fixed today. And do you have repositoryCache enabled?
