### ISSUE TITLE
v33

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#18020]
### Describe the proposed change(s).

- [x] #14531
- [ ] #14525
- [ ] #16969
- [ ] #16525
- [ ] #15731
- [ ] #13171
- [x] #17306
- [x] #18019

**Comment by rarkins** [comment]
Cc @maxbrunet

**Comment by HonkingGoose** [comment]
We've released `v33` now, so I think we can close this issue. 😉

**Comment by viceice** [comment]
> Thanks for the new version! I wanted to note that [c9161ef](https://github.com/renovatebot/renovate/commit/c9161ef6fd4ab31ff43e361dc6373cacb520d26d) caused previously closed PRs to be re-created because the branch names would differ (e.g. 7.x is now 7-x). Obviously it could be avoided if the value is explicitly set to false (but I believe the consequence may not be clear to everyone)

That's why it's a breaking change 😉

**Comment by rarkins** [comment]
Under consideration: https://github.com/renovatebot/renovate/pull/18536

**Comment by devversion** [comment]
@viceice That is very clear (your response is not useful at all). That is why my comment was a **note**, trying to help other users figuring out about this potentially non-obvious consequence too.
