### ISSUE TITLE
Support customizable subset of `prBody`

### ISSUE THREAD

**Issue by jfairley** [renovatebot/renovate#1802]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Teams at my company commonly leverage Github Teams for notifications. Specifically, when submitting a PR, we will include the team name in the PR body rather than individuals. This can look like `@organization/a-team`. This is equivalent to tagging each member of the team individually.

I would like to add these team tags to the renovate PR template, but I won't be going to far as to override the entire `prBody`. (Your standard PR templates are very nice and informative.)

I would love to see something akin to the `reviewers` configuration, where the values are prepended or appended to the standard `prBody` template.

**Comment by rarkins** [comment]
@jfairley thanks for the request. I've also concluded that there needs to be an easier way to add to the prBody without having to copy/paste the whole thing, so plan to implement this hopefully this month or next.

**Comment by jfairley** [comment]
I had noticed https://github.com/renovateapp/renovate/issues/442, but thought it'd be good to have a separate issue for tracking purposes. Thanks!

**Comment by rarkins** [comment]
@jfairley please try it out! https://renovatebot.com/docs/configuration-options/#prbodynotes
