### ISSUE TITLE
Platform native automerge not re-enabled after autoclose due to new version

### ISSUE THREAD

**Issue by kristof-mattei** [renovatebot/renovate#18049]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I use `platformAutomerge: true`, as shown here: https://github.com/kristof-mattei/renovate-config/blob/main/default.json#L5

However as shown in this PR: https://github.com/kristof-mattei/leetcode/pull/235

We can see that a PR gets craeted for 2.1.25. Something ELSE caused the update to 2.1.25 (in my case, I pulled in upstream, which is a base repo that acts like a foundation for my repos). 

Renovate deleted the branch which closed the PR, as the 2.1.25 was merged in. 

But then 2.1.26 came in which made Renovate re-open the same PR but not re-enable `platformAutomerge`. 

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
This would need local debugging, which in turn means we need some foolproof steps for reproducing.

**Comment by viceice** [comment]
@rarkins i think this is by design. we only enable platform automerge on PR creation.

**Comment by rarkins** [comment]
It is essentially by design, and not a bug, but I think when reopening/reusing an existing branch it might be an edge case where we could support enabling it.
