### ISSUE TITLE
Allow automerge when "Require a pull request before merging" option is enabled

### ISSUE THREAD

**Issue by gorohash** [renovatebot/renovate#18087]
### What would you like Renovate to be able to do?

The documentation states that if pull requests are required before merging in a project, automerge is not possible.

https://docs.renovatebot.com/key-concepts/automerge/#pull-requests-required
> ### Pull Requests Required
> If you have configured your project to require Pull Requests before merging, it means that branch automerging is not possible, even if Renovate has rights to commit to the base branch.

However, I think that Renovate should allow automerge even when "Require a pull request before merging" option is enabled in Branch protection rules.

### If you have any ideas on how this should be implemented, please tell us here.

Currently Renovate only checks the `required_pull_request_reviews` parameter of the Get branch protection API.

https://github.com/renovatebot/renovate/blob/ffc63c35c230d8280a00971ef95165bd3e17303a/lib/modules/platform/github/index.ts#L527-L532

It should be modified to check `require_code_owner_reviews` and `required_approving_review_count`. See the following document for the schema of the Get branch protection API.

https://docs.github.com/en/rest/branches/branch-protection#get-branch-protection

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
Instead of proactively checking multiple APIs, should we instead "try and gracefully fail"? i.e. always try, if we can recognize the error messages for why. GitHub's protections keep coming more sophisticated (including allowing exceptions) so maybe we shouldn't try to reverse engineer them all and instead should just try automerge if we're allowed, and report why if we're not.

**Comment by rarkins** [comment]
I think this is now completed
