### ISSUE TITLE
Modified PRs can have incorrect versions in PR body

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#18103]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When a PR's branch has been modified, Renovate will stop committing to it - this is good.

Renovate will also update the PR body to indicate that it will stop automatically updating/rebasing due to the PR being modified - this is also good.

However, while updating the PR, Renovate will also update anything else in the PR body at the same time.. such as newer versions.

An example scenario is:
- Current version in repo base branch is 1.0.0
- Renovate creates PR updating to 1.0.1
- User modifies branch
- Renovate stops committing to the branch
- Version 1.0.2 is released
- Renovate updates the PR body, both the dependency version (1.0.2) and the branch modification status but the branch only has 1.0.1

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Updating existing PR to indicate that rebasing is not possible (repository=***/***, branch=renovate/external-dependencies)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Possible solutions:
1. Use a PR comment instead of PR body to indicate that the PR has been modified and won't be updated, or
2. Don't update the full PR body, instead download the existing PR body and do a search/replace (note: not sure if we store the full PR body any longer and instead have a hash)

**Comment by rarkins** [comment]
I think we also have a text change in the configuration section?

**Comment by zharinov** [comment]
What do you mean exactly?

**Comment by rarkins** [comment]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/6311784/194218462-42fd3f47-fe57-4129-b27c-a654b705e4e5.png">

Look at the rebasing line above

**Comment by zharinov** [comment]
Then seems like we have to step back from our current approach to PR body generation with storing only hashes of it

**Comment by zharinov** [comment]
`findPr` should have option to bypass caching layer and retrieve PR directly from platform. Then we can `updatePr` with updated body.
