### ISSUE TITLE
Add link(s) to new pull requests docs in default PR body text

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#18178]
### What would you like Renovate to be able to do?

Me and @rarkins created a new page that explains Renovate's pull requests. We should add a link to this new page in the Renovate PRs body text.

Related issues/PRs:

- #15797
- #15822

### Add text to top of PR body

I think we should have a text like this near the top of each Renovate PR:

```markdown
To learn more about Renovate's pull request, read our [docs](https://docs.renovatebot.com/key-concepts/pull-requests/).
```

### Add link to immortal PR docs

We should also add a link in the `immortal` section of the PR:

```typescript
      `:ghost: **Immortal**: This PR will be recreated if closed unmerged. Get [config help](${config.productLinks?.help}) if that's undesired. Read our [docs](https://docs.renovatebot.com/key-concepts/pull-requests/#immortal-prs) to learn more about immortal PRs.\n\n`
 ```

https://github.com/renovatebot/renovate/blob/734abb68041a8d5007e268466fbfa2879004834e/lib/workers/repository/update/pr/body/config-description.ts#L48

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
I would not put this near the top of each PR - that's too prominent. I think it better suits as a type of generic and perhaps collapsible "help" section towards the bottom of PRs

**Comment by HonkingGoose** [comment]
Duplicate of #16611
