### ISSUE TITLE
Dependency dashboard rendering breaks with too long warnings

### ISSUE THREAD

**Issue by gberche-orange** [renovatebot/renovate#18244]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Too long content breaks rendering of the Dependency Dashboard gh issue, preventing access to the "rebase" or "rebase all" buttons.

See screenshots at https://github.com/renovatebot/renovate/discussions/18222#discussioncomment-3837439 and analysis of  analysis of body truncated at 59,999 chars at https://github.com/renovatebot/renovate/discussions/18222#discussioncomment-3837779

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment]
I found these related issues and pull requests:

- #16373
- #16527
- #15850
- https://github.com/renovatebot/renovate/pull/16959#discussion_r940059501

I'll let the maintainers decide what to do about your issue. 😉

**Comment by rarkins** [comment]
The dashboard *must* be truncated in some circumstances, but it ideally should be done so intelligently. The question is then which order/priority we should retain. I believe that the warnings are considered most important for now?

**Comment by gberche-orange** [comment]
>  I believe that the warnings are considered most important for now?

With the checkbox ` Check this box to trigger a request for Renovate to run again on this repository` being truncated, is there another available way to notify renovatebot about the need to check the repo sooner ? 

If not, I'd think that preserving this checkbox would be higher priority than displaying the full untruncated list of warnings, because it is a prereq to be able to quickly fix the long warning lists.

**Comment by rarkins** [comment]
Ideas:
- limit warnings, display "+15" or something similar 
- always preserve the checkbox part at the bottom
