### ISSUE TITLE
Failed to parse "never"

### ISSUE THREAD

**Issue by mbrevda** [renovatebot/renovate#18261]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When setting the schedule to "never", the logs show `Failed to parse "never"`. Use case: shared config, want to temporarily stop renovate from opening new PRs.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: prAlreadyExisted=false(branch="renovate/octokit-request-action-2.x")
DEBUG: Checking schedule(never, xxx/xxx)(branch="renovate/octokit-request-action-2.x")
WARN: Invalid schedule: Failed to parse "never"(branch="renovate/octokit-request-action-2.x")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### Later test

When testing this in Later, it seems to parse just fine. Can be run [here](https://npm.runkit.com/%40breejs%2Flater)

```js
var later = require("@breejs/later")
var s = later.parse.text('never');

later.schedule(s).next(1);
```

**Comment by mbrevda** [comment]
Closing for now, will try `on never`

**Comment by rarkins** [comment]
Schedule field isn't intended for disabling updates. Instead set enabled=false
