### ISSUE TITLE
Found no results from datasource that look like a version (repository=enskyl/renovate-go-issue-otel, dependency=go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc)

### ISSUE THREAD

**Issue by ekyl** [renovatebot/renovate#18267]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.229.0-slim

### If you're self-hosting Renovate, select which platform you are using.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

github

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovates fails to lookup versions for multiple go dependencies

from go.mod
```
module test/test

go 1.19

require (
	go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws v0.30.0
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.30.0
	go.opentelemetry.io/otel v1.9.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.5.0
)
...
```

Reproduction repository: https://github.com/enskyl/renovate-go-issue-otel
Renovate logs: https://github.com/enskyl/renovate-go-issue-otel/actions/runs/3227900628/jobs/5283297677

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found no results from datasource that look like a version (repository=enskyl/renovate-go-issue-otel, dependency=go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc)
       "result": {
         "sourceUrl": "https://github.com/open-telemetry/opentelemetry-go",
         "releases": []
       }
DEBUG: Found no results from datasource that look like a version (repository=enskyl/renovate-go-issue-otel, dependency=go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp)
       "result": {
         "sourceUrl": "https://github.com/open-telemetry/opentelemetry-go-contrib",
         "releases": []
       }
DEBUG: Found no results from datasource that look like a version (repository=enskyl/renovate-go-issue-otel, dependency=go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws)
       "result": {
         "sourceUrl": "https://github.com/open-telemetry/opentelemetry-go-contrib",
         "releases": []
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by ekyl** [comment]
Thank you very much for the answer. Not sure if I interpret the following results correctly, but it seems like this design decision has already been made:

The non working example:
```
dependency: go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws v0.30.0
repository: https://github.com/open-telemetry/opentelemetry-go-contrib
path: /instrumentation/github.com/aws/aws-sdk-go-v2/otelaws
tag: instrumentation/github.com/aws/aws-sdk-go-v2/otelaws/v0.36.1
```

A working example:
```
dependency: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/monitor/armmonitor
repository: https://github.com/Azure/azure-sdk-for-go
path: /sdk/resourcemanager/monitor/armmonitor
tag: sdk/resourcemanager/monitor/armmonitor/v0.7.0
```

If you are interested I can extend the reproduction repo with this dependency. It looks like we only would need to respect the mapping `go.opentelemetry.io/contrib`-> `https://github.com/open-telemetry/opentelemetry-go-contrib` but not sure.

**Comment by rarkins** [comment]
How would we know that it's `go.opentelemetry.io/contrib` which maps to the repo and not `go.opentelemetry.io` or `go.opentelemetry.io/contrib/instrumentation`, for example?

**Comment by JVecsei1** [comment]
The path shouldn't be an issue here. The custom domain is correctly resolved using the meta tags from https://go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws.

`<meta name="go-import" content="go.opentelemetry.io/contrib git https://github.com/open-telemetry/opentelemetry-go-contrib">`

These are also resolved correctly which can be seen in the renovatebot logs:

```json
"goModule": "go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws",
"goSourceUrl": "https://github.com/open-telemetry/opentelemetry-go-contrib"
```

Getting the path would be possible by trimming the prefix of the original URL, using the meta tag which leaves you with `/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws`.

**Comment by JVecsei1** [comment]
The custom domain is correctly resolved using the meta tags from https://go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws.

`<meta name="go-import" content="go.opentelemetry.io/contrib git https://github.com/open-telemetry/opentelemetry-go-contrib">`

These are also resolved correctly which can be seen in the renovatebot logs:

```json
"goModule": "go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws",
"goSourceUrl": "https://github.com/open-telemetry/opentelemetry-go-contrib"
```

The meta tag contains the important the part that is reolved to the github repoistory `go.opentelemetry.io/contrib`.
