### ISSUE TITLE
Module updates from Terraform Cloud Registry

### ISSUE THREAD

**Issue by joonvena** [renovatebot/renovate#18294]
### What would you like Renovate to be able to do?

It would be nice if Renovate could support updating Terraform modules from Terraform Cloud Registry.

### If you have any ideas on how this should be implemented, please tell us here.

Terrafrom Cloud provides Registry Module API to interact with the registry so it should be pretty straight forward to implement this using it.

https://www.terraform.io/cloud-docs/api-docs/private-registry/modules

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
did you tried to override registry url? i though it should work. 🤔

**Comment by joonvena** [comment]
It did actually work! Thank for the tip 👍
