### ISSUE TITLE
renovate doesn't read symlinked config file

### ISSUE THREAD

**Issue by bitte-ein-bit** [renovatebot/renovate#18337]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.227.0-slim

### If you're self-hosting Renovate, select which platform you are using.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

Github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate is ignoring a symlinked config file as described in https://github.com/renovatebot/renovate/issues/2641. The use case here is the following:

We have a lot of IaC repositories forked of a central blueprint. Customizations are done in the fork, other development is done on the fork directly. Most of the maintenance work should only be executed on the blueprint directly (e.g. update Terraform providers) and not on the forks. Only the customizations should be updated by Renovate when run against the fork.

We tried realizing it this way:
* Have a `renovate.json5` in the blueprint and (because of the update process) in the forks. It should hold the config for the blueprint only
* Have a `renovate-fork.json` in the blueprint. This should hold the config to be applied for the forks. The name isn't detected by Renovate obviously, but this way, we can still roll central updates purely by git operations.
* In the forks we create a customization in the form of a symlink (`ln -s renovate-fork.json renovate.json`). Since the `renovate.json` file has a higher priority, the expectation is that renovate would pick up this symlink.

Without the symlink approach, there is no way to centrally manage both configs without either Git conflicts or manual copy & pasting.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
use shared preset's
