### ISSUE TITLE
Reduce BranchConfig used to compute skipBranchUpdate

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#18353]
### Describe the proposed change(s).

We use `branchFingerprint` to determine whether an existing branch should be updated (i.e. clone + write updates + compare + commit).
We use the `branchConfig` in the calculation of the `branchFingerprint` so that if any field of the config differs, the fingerprint will be different and we will perform an update.

The issue is that we set the entire `branchConfig`, which contains many fields that are irrelevant to the branch-update process and are used for validation, scheduling, and managing PRs. When such a "config-field" changes, the fingerprint changes, and we end up running through the while update process and cloning the repo, increasing repo processing time.

We can avoid the problem by creating a new config and using it to compute `branchFingerprint` after filtering out all unnecessary fields from `branchConfig`.

It's worth noting that the current `branchConfig` contains all of the fields present in the `RenovateConfig` because we never narrow down the config when passing it to processBranch(), which increases the chances of unwanted fingerprint changes.

The solution is straightforward. Make a list of all the fields that have an impact on the branch-update process and use it when fingerprinting.
Let us call the new configuration -> `fingerprintConfig`, and then we must:
1. Narrow `BranchConfig` down to `fingerprintConfig`. We filter out all `BranchConfig` fields that aren't used in branch processing.
2. Further restrict `fingerprintConfig` to only include fields used in the branch-update process, i.e. remove config related to scheduling, validation, etc.

**Comment by rarkins** [comment]
I'm not sure you need a two-step narrowing, unless you use the two steps for other things.

The fingerprinting should be based on which config can impact whether a *commit* needs to be made (branch updating). It should not include fields which are required only for deciding if the *PR body* needs updating, or the PR needs creating.

**Comment by RahulGautamSingh** [comment]
I want the two-step narrowing so that I can see the improvements in both steps. I'm just curious :)

**Comment by RahulGautamSingh** [comment]
We can just focus on branch fingerprint config ie. create `BranchFingerprintConfig` and the add fields whether they can cause a new commit to a exising branch.

Regarding that I think answering the below question is a important step.

Q. When will renovate-bot make a new commit on an open PR ?

1. rebase due to conflicted, behind-base, user-requested
2. When using same branch to create a new PR ie. new version available while PR which updates same dep but old version is not merged.

These are the 2 scenarios I could think of.

**Comment by rarkins** [comment]
Point (1) should already be covered in existing functionality and is not benefited by the fingerprint.

(2) is true (versions changed)

(3) maybe there's a change in grouping, or a package added, etc
