### ISSUE TITLE
Add support for jetpack compiler `kotlinCompilerExtensionVersion `

### ISSUE THREAD

**Issue by igorwojda** [renovatebot/renovate#18354]
### What would you like Renovate to be able to do?

Unlike any other dependency, the Android Jetpack compose compiler dependency is upgraded by setting `kotlinCompilerExtensionVersion` property in the Gradle file:

`module\build.gradle` file :
```
android {
   ...

    composeOptions {
        kotlinCompilerExtensionVersion = "1.3.2"
    }
}
```

More: https://developer.android.com/jetpack/androidx/releases/compose-kotlin

### If you have any ideas on how this should be implemented, please tell us here.

Upgrade the value of the `kotlinCompilerExtensionVersion` property in all `module\build.gradle` files.

Keep in mind that `kotlinCompilerExtensionVersion` propertyty value can be retrieved directly from Gradle `libs.versions.toml` file:
```
android {
   ...

    composeOptions {
        kotlinCompilerExtensionVersion = libs.versions.kotlinCompilerExtensionVersion.get()
    }
}
```

BTW
Android Jetpack compiler version is tightly coupled with the Kotlin version, so they have to be upgraded together. See kotlin compatibility https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility

### Is this a feature you are interested in implementing yourself?

No

**Comment by Churro** [comment]
It's possible to integrate updates for `kotlinCompilerExtensionVersion`, as it can be mapped to https://maven.google.com/web/index.html#androidx.compose.compiler:compiler
In fact, it will be very similar to `checkstyle`, `pmd`, `lombok`, so that will work once done.

What won't work is to make renovate aware what `kotlinCompilerExtensionVersion` is compatible with which kotlin version. You could still define yourself one or multiple `packageRules` for that.

**Comment by ede-wolf-gls** [comment]
How would a package rule look like to combine kotlin and compose compiler PRs? I tried something like:
```json
{
# ...
  "packageRules": [
    {
      "matchSourceUrlPrefixes": ["https://github.com/JetBrains/kotlin"],
      "matchPackageNames": ["androidx.compose.compiler:compiler"],
      "groupName": "kotlin monorepo"
    }
  ]
}
```
but it looks like, this isn't working.

**Comment by viceice** [comment]
@ede-wolf-gls Please ask at a new discussion

**Comment by mustafaozhan** [comment]
Really interested in this

**Comment by mustafaozhan** [comment]
Is renovate updates the unused dependencies too ? What about if we define below in TOML file

```
[versions]

composeCompiler = "1.4.0"

[libraries]

android-composeCompiler = {module="androidx.compose.compiler:compiler", version.ref ="composeCompiler"}
```
Will Renovate update `composeCompiler = "1.4.0"` to `1.4.1` when the new version available, even if we do not use `android-composeCompiler` anywhere in dependencies ?

**Comment by mustafaozhan** [comment]
Luckily, new version of composeCompiler is released yesterday and I had chance to test the workaround above, and it is working 🎉 

@igorwojda you can use as workaound, you do not need to `implement` the dependency anywhere it is enough it to be existed in the toml file

**Comment by igorwojda** [comment]
Yes, `composeCompiler` can be updated, but at some point, it will be misaligned with the `Kotlin` version.

@Churro can you elaborate on these packageRules? Perhaps drop rules that would work for this scenario?

**Comment by mustafaozhan** [comment]
I currently have this in my package rules in order to update kotlin related libraries together:
```json
  "packageRules": [
    {
      "matchPackagePatterns": [
        "^org.jetbrains.kotlin",
        "^com.google.devtools.ksp",
        "^androidx.compose.compiler"
      ],
      "groupName": "kotlin"
    }
  ]
```

**Comment by mustafaozhan** [comment]
@Churro @rarkins is that mean I can get rid of the workaround now ? 

The unused dependency in TOML file ?
```
[libraries]

android-composeCompiler = {module="androidx.compose.compiler:compiler", version.ref ="composeCompiler"}
```
