### ISSUE TITLE
BaseRecyclerViewAdapterHelper info link incorrect

### ISSUE THREAD

**Issue by Goooler** [renovatebot/renovate#18384]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

[BaseRecyclerViewAdapterHelper](https://github.com/CymChad/BaseRecyclerViewAdapterHelper) was bumped from `3.0.9` to `3.0.10`, but the repo link doesn't right, it should be:

https://github.com/CymChad/BaseRecyclerViewAdapterHelper

instead of:

https://github.com/liyuhaolol/PtrNew

you can repro this issue on https://github.com/zhaobozhen/LibChecker/pull/462.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
This may be related to bad data from the Maven repository.

For example if you view https://mvnrepository.com/artifact/com.github.CymChad/BaseRecyclerViewAdapterHelper/2.9.34 you can see the repository in question

**Comment by rarkins** [comment]
It appears that versions are spread across different repositories. Here's the 3.0.10 one, with a different SCM link: https://jitpack.io/com/github/CymChad/BaseRecyclerViewAdapterHelper/3.0.10/BaseRecyclerViewAdapterHelper-3.0.10.pom

**Comment by Goooler** [comment]
Ok, filed a bug to https://github.com/CymChad/BaseRecyclerViewAdapterHelper/issues/3704, and I'll investigate the pom files later.

**Comment by Goooler** [comment]
I've rechecked the [pom file](https://jitpack.io/com/github/CymChad/BaseRecyclerViewAdapterHelper/3.0.10/BaseRecyclerViewAdapterHelper-3.0.10.pom), the project's website is `www.recyclerview.org` instead of `github.com/liyuhaolol/PtrNew`, I can't find any word of `liyuhaolol/PtrNew` in pom, in this case, you should pick up `www.recyclerview.org` as the project's website, right?

**Comment by rarkins** [comment]
Ideally we'd treat that as website, yes (not sourceUrl)

**Comment by rarkins** [comment]
It merges results from all repositories (including Maven Central)

**Comment by Goooler** [comment]
There was only one link pasted in that PR, in this case, can we just paste the latest result?

**Comment by rarkins** [comment]
Minimal reproduction needed first (see instructions above)

**Comment by Goooler** [comment]
Alright, I believe https://github.com/Goooler/BaseRecyclerViewAdapterHelper can repro this issue.

**Comment by rarkins** [comment]
Please read https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md
