### ISSUE TITLE
Flag config options in code to show "for advanced users only" admonition

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#18408]
### What would you like Renovate to be able to do?

Right now, we have to put an admonition in the docs to tell users that a config option is "for advanced users only".

@rarkins had the idea of automating this, like we do already for experimental config options.

### If you have any ideas on how this should be implemented, please tell us here.

- [x] Create new config option Boolean called `advancedUse` that we can attach to config options in the code
- [x] Write code that can create the `warning` admonition for us.
- [x] _After_ the PR lands that makes the code and admonition work: remove the old manual "for advanced users" admonitions from the docs

How it should work:

- If `advancedUse=true` then our docs build process adds the admonition to the docs
- If `advancedUse=false` then nothing happens.

Related comment:

- https://github.com/renovatebot/renovate/issues/18404#issuecomment-1283604679

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
I think we can shorten it to an `advancedUse` boolean

**Comment by betterPeleg** [comment]
@HonkingGoose 
can you please share the current admonition added to the docs manually?

**Comment by HonkingGoose** [comment]
> can you please share the current admonition added to the docs manually?

@betterPeleg Here's your Markdown: 😉 

```markdown
<!-- prettier-ignore -->
!!! warning
    Warning, for advanced use only! Use at your own risk!
```

---

> How is it planned to notify the users?
> A log message is pretty obvious, but what is about users without access to the logs?

@secustor I'm sorry for confusing you. We plan to notify the users via the docs. I don't know if adding a log `WARN` message is something we want. I'll let @rarkins decide. 😉 

> I propose following:
> 
>     * Add a warning to the dashboard
> 
>     * create repository config option to acknowledge these warnings, which will then remove them again.

I don't like this idea for "advanced users only warnings" in the Dependency Dashboard. It _may_ work somewhat OK for "deprecated" config options. But we're planning to migrate a users' outdated config with a Renovate PR automatically. Once that feature lands we don't need a Dependency Dashboard notification:

- https://github.com/renovatebot/renovate/issues/16359

**Comment by secustor** [comment]
@HonkingGoose  Oh, gotcha!

**Comment by rarkins** [comment]
I think a docs-only warning message is ok. We don't to want to warn advanced users non-stop e.g. in Dashboard
