### ISSUE TITLE
Remove direct commitMessage editing

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#18404]
### Describe the proposed change(s).

Remove `commitMessage` from config options, so that users can't change it directly.

We should advise against changing `commitMessage*` values unless the user is really sure of it.

We should document how the commit message (and therefore PR title) is constructed, as otherwise that information would be lost if we simply delete it.

To be released in a major release.

**Comment by HonkingGoose** [comment]
## Deprecation warning for `commitMessage` is already in the docs

We have this warning in the docs for the root `commitMessage` config option: [^commitMessage]

> Editing of `commitMessage` directly is now deprecated and not recommended. Please instead edit the fields such as `commitMessageAction`, `commitMessageExtra`, etc.

@rarkins Do you want me to add a link to this issue?

## Missing admonitions

These options are missing the recommendation to avoid the options unless the user is sure about what they're doing:

- `commitMessageAction`
- `commitMessageExtra`
- `commitMessagePrefix`
- `commitMessageSuffix`
- `commitMessageTopic`

@rarkins Do you want me to add a suitable warning message for these config options in the docs?

## Document how Renovate creates commit messages

> We should document how the commit message (and therefore PR title) is constructed, as otherwise that information would be lost if we simply delete it.

Sounds like a good plan to me. Where do you want to put the rescued information?

I'm thinking it may fit in a new **Deep Dive -> How Renovate creates commit messages** page in the docs. Learning "how Renovate creates commit messages" sounds like an advanced topic to me. I don't think we should put it in **Key concepts**, unless many people need to know about it. 😉 

[^commitMessage]: https://docs.renovatebot.com/configuration-options/#commitmessage

**Comment by rarkins** [comment]
> We have this warning in the docs for the root `commitMessage` config option: [1](#user-content-fn-commitMessage-c609e118dbd103a55488b4be0dfedf63)
> 
> > Editing of `commitMessage` directly is now deprecated and not recommended. Please instead edit the fields such as `commitMessageAction`, `commitMessageExtra`, etc.
> 
> @rarkins Do you want me to add a link to this issue?

I don't think we need it. FYI I also found out that we have a config validation *warning* (not error) already too.

> @rarkins Do you want me to add a suitable warning message for these config options in the docs?

Yes, I think a Warning for these would be useful. Makes me wonder if we should have a new metadata about options so we can flag them in bulk as "Warning, for advanced use only - use at own risk" or something similar, like we do with experimental.



> I'm thinking it may fit in a new **Deep Dive -> How Renovate creates commit messages** page in the docs

Yes, but it can also include PR titles too - because they are derived from commitMessage by default

**Comment by HonkingGoose** [comment]
> > I'm thinking it may fit in a new **Deep Dive -> How Renovate creates commit messages** page in the docs
> 
> Yes, but it can also include PR titles too - because they are derived from commitMessage by default

Thinking some more about the best place to put the rescued information. We have a **Key concepts -> Pull Request** page. [^docs] So maybe the "PR title creation" information should go there?

But the PR title is _coupled_ to the commit message, so maybe the PR title information should  go in the new "How Renovate creates commit messages" page instead?

Summarizing the choices:

## Option 1

- Create new **Deep Dive -> How Renovate creates commit messages** page
- **Key concepts -> Pull Requests**
  - Insert section: How Renovate creates PR titles based on commit message

## Option 2:

- Create new **Deep Dive -> How Renovate create commit messages** page
  - How Renovate creates commit messages
  - How Renovate creates PR titles
  
[^docs]: https://docs.renovatebot.com/key-concepts/pull-requests/

**Comment by rarkins** [comment]
I think that "Commit Message construction" could be a subsection of Pull Requests maybe? Especially because prTitle is based on commitMessage

**Comment by williamboman** [comment]
Personally I find constructing a commit message using the pre-defined, hard-coded, components to be a bit unwieldy. Constructing a custom commit message through a single template string (`commitMessage`) made it very easy for me to create the commit message style I wanted. Isn't it unnecessarily strict to enforce a certain template?

**Comment by rarkins** [comment]
I guess it's mostly the prTitle we care about, because of it's role in matching existing PRs today.

Commit message *could* be left over writable although still makes it harder for us to get things done that touch this code

**Comment by rarkins** [comment]
Setting this back to status:requirements because where possible I'd like to avoid imposing on user conventions/desires. We should think of alternatives, even if it just means restricting PR title customization instead of commit message
