### ISSUE TITLE
Support github fine-grained token

### ISSUE THREAD

**Issue by rlex** [renovatebot/renovate#18459]
### What would you like Renovate to be able to do?

Github recently introduced fine-grained tokens - https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/

Will be nice if renovate can support them.

Here is official github discussion related to that feature https://github.com/community/community/discussions/36441

### If you have any ideas on how this should be implemented, please tell us here.

Looks like new method needs to be added. Currently, if used with fine-grained token, github will return following error:

```
 "response": {
      "statusCode": 401,
      "statusMessage": "Unauthorized",
      "body": {
        "message": "Personal access tokens with fine grained access do not support the GraphQL API",
        "documentation_url": "https://docs.github.com/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql"
      },
...
```

### Is this a feature you are interested in implementing yourself?

No

**Comment by rlex** [comment]
Github states they will implement GraphQL support "in coming months" so maybe no action will be needed at all.

**Comment by JamieMagee** [comment]
Marked as high priority as the GitHub UI is defaulting to fine-grained tokens. If any work is necessary in Renovate we should support them as soon as they are supported in GraphQL calls.

**Comment by rarkins** [comment]
Can we catch and reject them early for now?

**Comment by JamieMagee** [comment]
Yes. Classic tokens start with `ghp_`. New, fine-grained, tokens start with `github_pat_`. 

Throwing an error with a link to a documentation page explaining the difference is probably the best thing to do right now.

**Comment by Shashwat-SRE** [comment]
Hey All,
My team is moving away from Classic PAT and will use only FG PAT now.
And because of this we wont be able to use Renovate anymore.

I see the feature request is still in open state... does anyone has any work-around to make it work with FG PAT for the time being this is implemented ?

**Comment by viceice** [comment]
nope, because the new token can't be used with graphql API.

workaround: use an app or classic token

**Comment by JamieMagee** [comment]
I wanted to check in and see what the current state of fine-grained PAT support for GraphQL is. This is the tracking issue: https://github.com/github/roadmap/issues/622

But it looks like [the docs][1] have been updated to mention fine-grained tokens:

>  If you receive a 403 error with Resource not accessible by personal access token, ensure that your fine-grained personal access token is targeted to the correct resource owner.

I think support for fine-grained tokens can be added.

[1]: https://docs.github.com/en/graphql/guides/introduction-to-graphql

**Comment by o-grigorev** [comment]
Hi there,

I also suppose the check for` fine-grained` token can be removed.
Here is the anoncement. 
https://github.blog/changelog/2023-04-27-graphql-improvements-for-fine-grained-pats-and-github-apps/

I tested with old release `34.116.0` without folowing chanes and it works fine with my  fine-grained token
https://github.com/renovatebot/renovate/pull/20097/files

**Comment by frantic1048** [comment]
Hi @rarkins, I have submitted a pull request addressing this issue. Kindly review it at your convenience. 🙏

**Comment by viceice** [comment]
shipped to github.com

https://github.blog/changelog/2023-04-27-graphql-improvements-for-fine-grained-pats-and-github-apps/

needs ghes 3.10

**Comment by frantic1048** [comment]
Today, I have tested it with Renovate 36.49.0, which includes the fix that was [initially introduced in version 36.47.0](https://github.com/renovatebot/renovate/pull/23810#issuecomment-1680021582).

Testing has shown that the GitHub fine-grained token is working well without any issues. Therefore, I believe this problem has been resolved. 👀
