### ISSUE TITLE
Support PHP as a package via github-tags

### ISSUE THREAD

**Issue by internalsystemerror** [renovatebot/renovate#18468]
### What would you like Renovate to be able to do?

Similar to how renovate is able to suggest updates to node, I would like the `php` package when specified in `composer.json` to also be updated. At present this package is skipped as "unsupported".

### If you have any ideas on how this should be implemented, please tell us here.

I've not delved into this part of the codebase yet, but I see that `node` updates are handled via `github-tags`. We could do the same with `php` via https://github.com/php/php-src.

I would like to implement this myself, but I am in need of some pointers. Mainly due to the fact that the git tags would need parsing removing the `php-` prefix.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment]
we should use our own php build from containerbase org as datasource. those are also used by renovate for running composer.

should be github-releases then.

**Comment by internalsystemerror** [comment]
That would work, but it doesn't include the RC/beta/alpha versions that the git tags do.

**Comment by viceice** [comment]
Renovate doesn't support them anyways

**Comment by internalsystemerror** [comment]
The overall goal is to allow us to test new PHP releases before they are actually released. Currently every year we have to manually open PRs to essentially wident the `php` version in `composer.json` which are tooling will run checks against (so if we have for example: `"php": "^7.4 || ~8.0.0 || ~8.1.0 || ~8.2.0-rc1"`, then checks are ran against PHP 7.4.x, 8.0.x, 8.1.x and 8.2.0-rc1).

Ideally we'd like to have renovate open these PRs, not only when a new PHP version is released, but when a new RC is released. There would still be some work to do our end to ensure that that we're failing the job if the binary is not available from `ppa:ondrej/php`, and I don't suggest this as a source because not everyone uses ubuntu.

**Comment by viceice** [comment]
so let's use our stable version as default datasource, which can be easily overriden by user package rules.

**Comment by internalsystemerror** [comment]
How would a user specify the git tags from `php/php-src` which has it's own versioning scheme though? We would need to specify composer versioning for reading the `php` field from `composer.json` but a custom versioning scheme for the git tags retrieved from the source repository.

I spent a while trying to solve this already using a custom regex manager, but I'm not able to say, the git tags need parsing before being used as release version numbers. Unless I'm mistaken?

**Comment by viceice** [comment]
did you tested extractVersion option?

**Comment by internalsystemerror** [comment]
🤦 I did not... I only looked at `extractVersionTemplate` verison which talks about `matchString` and I misread what it was telling me.

**Comment by internalsystemerror** [comment]
I'll still submit a PR to do as you suggested using containerbase.

**Comment by viceice** [comment]
sure

**Comment by rarkins** [comment]
@viceice I'm leaning towards using the php source for this so that users like @internalsystemerror are free to use this for unstable versions too.

In the example given, `"php": "^7.4 || ~8.0.0 || ~8.1.0 || ~8.2.0-rc1"`, our binarySource would still succeed - it just wouldn't find any of the RC ones.

Even if it failed to find any, it would fall back to latest stable.

Whether we support unstable versions in containerbase is a separate issue. Any major downsides I'm missing?

**Comment by viceice** [comment]
ok
