### ISSUE TITLE
Renovate adds bundledDependencies to lockfile unlike yarn CLI

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#1851]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Renovate updated the Neutrino monorepo's `yarn.lock` in this lockfile maintenance PR:
https://github.com/mozilla-neutrino/neutrino-dev/pull/794

However after that PR landed, if I run `yarn install`, yarn 1.6.0 makes changes to `yarn.lock` - meaning the committed file isn't up to date / correct as far as yarn sees it.

Specifically, Renovate added many wildcard dependencies (eg `debuglog "*"`) that are then removed when I run yarn. These are not actual `dependencies`, but instead `bundleDependencies` (also known by the alternative alias `bundledDependencies`). For example `debuglog` here:
https://github.com/npm/npm/blob/v5.1.0/package.json#L134

Presuming the yarn CLI's behaviour here is correct (ie having `bundleDependencies` not be listed in `yarn.lock`) - then it seems like whatever library/workflow Renovate is using to update the lockfile doesn't handle `bundleDependencies` correctly? (Fwiw I tried yarn v1.3.2, v1.6.0 and `master`, and all had the same behaviour.)

Many thanks :-)

CC @eliperelman

**Comment by rarkins** [comment]
Can you tell if this is a new problem or not? i.e. were you seeing bundled dependencies being added to yarn.lock in previous lock file maintenance PRs? I'm wondering if it's related to the v1.6.0 yarn upgrade within Renovate, or independent of it.

**Comment by rarkins** [comment]
Relevant: https://github.com/yarnpkg/yarn/issues/3751#issuecomment-349938952

**Comment by edmorley** [comment]
> Can you tell if this is a new problem or not? i.e. were you seeing bundled dependencies being added to yarn.lock in previous lock file maintenance PRs?

It's hard to say - this repository only recently enabled Renovate lockfile maintenaince, and then this is the first PR that's been merged due to #1809 and others. However I did find mozilla-neutrino/neutrino-dev#745 (which was prior to, and the reason for #1655), which wasn't merged, but didn't try and remove the `debuglog "*"` line.

**Comment by edmorley** [comment]
One other thing I noticed -- if I run `yarn install --frozen-lockfile` (which we actually do on our Travis run), then it doesn't error saying changes needed, even though that running `yarn install` will make changes. 

I know there are cases when this difference in behaviour is expected (eg `yarn.lock` is technically up to date, but could be further optimised) - but the question is whether this is expected for this issue in particular (otherwise there's a 2nd bug here, in `--frozen-lockfile`).

**Comment by rarkins** [comment]
Yeah, my instinct is to say "you should install with `--frozen-lockfile` anyway, it will error if the lock file is incorrect" but wanted to fully investigate it first before dismissing it as a problem.

**Comment by rarkins** [comment]
@edmorley I'll hopefully have time to look into it next week, sorry for the inconvenience

**Comment by edmorley** [comment]
No worries! Thank you for all your time on the various lockfile issues :-)

**Comment by rarkins** [comment]
BTW, I've made log files available via https://renovatebot.com/dashboard - you should be able to view the debug logs for all runs in the past week. It's rough.. but a start

**Comment by rarkins** [comment]
@edmorley while attempting to replicate this locally, I noticed that your recent change to remove `gitbook` meant that the `npm` subdependency was also removed, which was where the problem was occurring. Hence I am lowering the priority of this from important to normal, as I'm not aware of anyone else impacted.

**Comment by edmorley** [comment]
Ah sorry I meant to comment here saying we'd just removed gitbook and so shouldn't hit this issue any more - so this is definitely lower priority (or can be closed out if you'd prefer). It may end up being some yarn bug that isn't anything to do with Renovate.

**Comment by rarkins** [comment]
I'll just keep it open and lower to pri4-low then

**Comment by edmorley** [comment]
This issue no longer affects us, and I think it may even be an upstream problem with yarn (my not being able to reproduce locally above is since the yarn behaviour differs based on whether the lockfile was deleted prior or not).

As such, happy to close this out if you are?

**Comment by rarkins** [comment]
OK, let's close it for now and reopen if someone else is affected
