### ISSUE TITLE
Config validation: registryUrls + matchUpdateTypes

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#18522]
### What would you like Renovate to be able to do?

These cannot be used together, and we should raise a config warning if they're found in the same package rule.

### If you have any ideas on how this should be implemented, please tell us here.

Raise error as part of config validation

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
it seems not all renovate configs are fully validated 🤔 

https://github.com/renovatebot/renovate/blob/58c9b151625ca4e44ebb4d1c26f13cf183b3ebc8/lib/config/validation.ts#L383-L395

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/discussions/18510#discussioncomment-3951564

**Comment by viceice** [comment]
It seems the global config isn't fully validated / massaged, which also recently caused this error:
- #18529
