### ISSUE TITLE
lockfile maintenance no longer works

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#18543]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Even if i force it from dashboard, no yarn is run to update the lockfile.

https://github.com/renovatebot/docker-renovate

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: syncBranchState()(branch="renovate/lock-file-maintenance")
DEBUG: branch.isUpToDate(): needs recalculation(branch="renovate/lock-file-maintenance")
DEBUG: getBranchPr(renovate/lock-file-maintenance)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, open)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, closed)(branch="renovate/lock-file-maintenance")
DEBUG: Found PR #281(branch="renovate/lock-file-maintenance")
DEBUG: branchExists=false(branch="renovate/lock-file-maintenance")
DEBUG: dependencyDashboardCheck=unschedule(branch="renovate/lock-file-maintenance")
DEBUG: recreateClosed is true(branch="renovate/lock-file-maintenance")
DEBUG: Checking schedule(before 3am on Monday, null)(branch="renovate/lock-file-maintenance")
DEBUG: Checking 1 schedule(s)(branch="renovate/lock-file-maintenance")
DEBUG: Checking schedule "before 3am on Monday"(branch="renovate/lock-file-maintenance")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          10800
        ],
        "d": [
          2
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: Package not scheduled(branch="renovate/lock-file-maintenance")
DEBUG: Branch needs creating(branch="renovate/lock-file-maintenance")
DEBUG: Using reuseExistingBranch: false(branch="renovate/lock-file-maintenance")
DEBUG: Setting current branch to main(branch="renovate/lock-file-maintenance")
DEBUG: latest commit(branch="renovate/lock-file-maintenance")
{
  "branchName": "main",
  "latestCommitDate": "2022-10-25T12:14:02+00:00"
}
DEBUG: manager.getUpdatedPackageFiles() reuseExistingBranch=false(branch="renovate/lock-file-maintenance")
DEBUG: No package files need updating(branch="renovate/lock-file-maintenance")
DEBUG: Getting updated lock files(branch="renovate/lock-file-maintenance")
DEBUG: Writing package.json files(branch="renovate/lock-file-maintenance")
{
  "packageFiles": [
    "package.json"
  ]
}
DEBUG: Writing any updated package files(branch="renovate/lock-file-maintenance")
DEBUG: No updated lock files in branch(branch="renovate/lock-file-maintenance")
DEBUG: No files to commit(branch="renovate/lock-file-maintenance")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by viceice** [comment]
I see these messages:
https://github.com/renovatebot/renovate/blob/9654516f5484b0c89f09f199f9a40d7949c152df/lib/workers/repository/update/branch/index.ts#L425
https://github.com/renovatebot/renovate/blob/9654516f5484b0c89f09f199f9a40d7949c152df/lib/workers/repository/update/branch/index.ts#L447

**Comment by viceice** [comment]
it seems renovate no longer enters this loop

https://github.com/renovatebot/renovate/blob/9654516f5484b0c89f09f199f9a40d7949c152df/lib/modules/manager/npm/post-update/index.ts#L597

**Comment by RahulGautamSingh** [comment]
I think not since `skipBranchUpdate` is false here so the update should have gone as normal.

**Comment by viceice** [comment]
OK, but it seems some metadata is missing on lockfile upgrade, so it doesn't find the lockfile here
https://github.com/renovatebot/renovate/blob/9654516f5484b0c89f09f199f9a40d7949c152df/lib/modules/manager/npm/post-update/index.ts#L47

**Comment by five-iron** [comment]
We are seeing an issue which may be related / the same. On a self-hosted gitlab config, renovate MRs do not include updates to package-lock.json. The bot's comment shows no error message other than 'undefined':

![image](https://user-images.githubusercontent.com/33008162/197889397-5bcac1cd-25ca-4e45-9606-fb218ab90d7f.png)

The logs show nothing apparently blowing up:
> Writing package.json files
Writing package-lock.json
writeUpdatedPackageFiles
Writing any updated package files
No updated lock files in branch
No files to commit

**Comment by rarkins** [comment]
@five-iron this is not related

**Comment by RahulGautamSingh** [comment]
Is this not because of schedule? as seen in the logs.
I tried a small [repro ](https://github.com/RahulGautamSingh-testing/lockfile)and got the schedule issue (expected) at first then I changed the schedule to at any time and it worked fine.

**Comment by viceice** [comment]
🤦‍♂️ that repo has no lockfile, was deleted long ago. but forgot to disable lockfile maintenance.
