### ISSUE TITLE
 Host Rules - custom Docker Registry trailing slash required

### ISSUE THREAD

**Issue by paulexyz** [renovatebot/renovate#18585]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.1.4

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab EE

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I want to add my own GitLab instance as custom registry. To authenticate I use a group Deploy token.
The docker image renovate should manage has the following path `registry.company.com/group/subgroup/project/image-name` To get renovate to respect the configured registry a **trailing slash is required** in the `matchHost` parameter.

This seems contra intuitive and makes no sense to me. Additionally the [documentation](https://docs.renovatebot.com/docker/#registry-authentication) features no example for configuring a self hosted registry. So if this is intended behavior it is also not really documented.

I hope somebody can help me out if that's intended behavior, and fix the docs or fix the code which parses the matchHost url. 

```js
# works
"hostRules": [
    {
      "hostType": "docker",
      "matchHost": "https://registry.company.com/",
      "username": "renovate-registry-read",
      "password": "glpat-xxxxxxxxxxxxxx"
    }
]

# does not work
"hostRules": [
    {
      "hostType": "docker",
      "matchHost": "https://registry.company.com",
      "username": "renovate-registry-read",
      "password": "glpat-xxxxxxxxxxxxxx"
    }
]

  ```

### Relevant debug logs
This is the error i get in the debug log which does not indicate what actually went wrong
<details><summary>Logs</summary>

```
DEBUG: Failed to look up docker dependency registry.company.com/group/subgroup/project/image-name (repository=group/subgroup/project, packageFile=templ.yml, dependency=registry.company.com/group/subgroup/project/image-name)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
We're going to need a way to reproduce this, e.g. using a public host.

Here's the code logic which is used to match hostRules in this case, I don't see any problem here: https://github.com/renovatebot/renovate/blob/fbaac110c9fd95f064b6ab90e49722a468661600/lib/util/host-rules.ts#L95-L112

**Comment by rarkins** [comment]
I believe line 101 should be the one executed

**Comment by paulexyz** [comment]
Found out something more - it seems to depend on the config file format or location (js vs json) if you need the trailing slash or not. I'll try to setup a example on gitlab.com to reproduce this issue isolated tomorrow.
