### ISSUE TITLE
Support Terraform

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/renovate#1860]
#### This is a:

* [ ] Bug report (non-security related)
* [X] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [X] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
Support renovation of terraform files - module imports etc.

**Comment by johncuthbertuk** [comment]
There are a couple of examples, one of those would be the Terraform Provider for AWS which has various releases:
https://github.com/terraform-providers/terraform-provider-aws/releases

For modules - you can specify which version to use within the Terraform as per:
https://www.terraform.io/docs/modules/usage.html#module-versions

I guess one of the issues will be verifying the changes as you'd only be able to do validate and plan. As an `apply` could potentially be destructive and will change an environment. Unless careful use of Terraform `workspaces` are used to separate the environments.

**Comment by rarkins** [comment]
https://www.terraform.io/docs/modules/sources.html

**Comment by rarkins** [comment]
@adam-moss @johncuthbertuk are you using a Hashicorp registry with versioning, or github.com sources? I can see that semver ranges with modules is only supported with the registry, but trying to work out for sure the ways that pinned/exact versions work with github.com sources.

**Comment by adam-moss** [comment]
Hi @rarkins. In order, GitLab, Hashicorp's registry, and GitHub. SonaType's Nexus also in preference to Hashicorp's when the add support for it. Thanks

**Comment by rarkins** [comment]
@adam-moss can you paste in 1 or 2 example files using modules and versions? I'm particularly interested to see how the gitlab and github references look like.
