### ISSUE TITLE
Update comments in GitHub Actions workflows referencing action versions

### ISSUE THREAD

**Issue by foolioo** [renovatebot/renovate#18697]
### What would you like Renovate to be able to do?

GitHub Actions workflows often specify the version of an action using the commit SHA. Since commit SHAs are immutable, this ensures that Actions always picks the same version. Commit SHAs, however, are not very human friendly, so best practice is to include the semver version in a comment next to the SHA.
I would love to see Renovate will update the semver version in comments when updating Actions workflows with a commit SHA version.

In the spirit of [Dependabot latest change](https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/).

### If you have any ideas on how this should be implemented, please tell us here.

Have [GitHub action manager](https://github.com/renovatebot/renovate/tree/main/lib/modules/manager/github-actions) add the a comment with the semver in comment when updating Actions workflows with a commit SHA version.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
already implemented. but renovate can't pin from Sha to a version.

checkout this repo workflows for sample

**Comment by viceice** [comment]
- https://github.com/renovatebot/renovate/issues/18640

**Comment by rarkins** [comment]
This has been supported for a long time using the ` # tag=v2.0.1` syntax
