### ISSUE TITLE
Losing multi-arch suggests wrong arch upgrades

### ISSUE THREAD

**Issue by moenzuel** [renovatebot/renovate#18708]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When renovatebot is suggesting upgrades to a container that previously publishes multi-arch containers and then switches to single arch it will continue to suggest upgrades even if the only option is the wrong arch.

In my specific case a repository was publishing amd64 and arm64. I was using arm64. The repository started publishing only amd64 and renovatebot opened PRs for the continued amd64 updates which would not be compatible.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by moenzuel** [comment]
I has sense been fixed in the repo but you can see an example of the image tagging with the following two images.

https://github.com/onedr0p/containers/pkgs/container/sonarr-develop/47346242?tag=4.0.0.141 (single arch)
https://github.com/onedr0p/containers/pkgs/container/sonarr-develop/45945122?tag=4.0.0.140 (multi arch)

**Comment by viceice** [comment]
@moenzuel We need a minimal reproduction to get further. please see our guide above
