### ISSUE TITLE
`pre-commit autoupdate --freeze` equivalent flag

### ISSUE THREAD

**Issue by l0b0** [renovatebot/renovate#18752]
### What would you like Renovate to be able to do?

`pre-commit autoupdate --freeze` creates `rev: e0f74cfd5f9497d3279995efeb13d11bd6434b5e # frozen: 0.18.4` type entries in `.pre-commit-config.yaml`. This guarantees reproducibility in case the tag in the upstream repository is moved for any reason.

Should only require a `pinDigests` flag in the `defaultConfig`.

### If you have any ideas on how this should be implemented, please tell us here.

I'm not very familiar with TypeScript, but I might give this a try.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
This sounds similar conceptually to similar functionality in the `github-actions` manager

**Comment by l0b0** [comment]
@rarkins I don't get the reproduction:needed label on this - it's a feature request, not a bug. Is it just a way to close it in two weeks automatically?

**Comment by rarkins** [comment]
Feature requests are not closed automatically due to lack of reproduction.

But reproductions typically are still required for feature requests, because it's a bad idea to add features without testing them on a real repo first. Sometimes features can be added with just unit tests, but this is not that type of feature.

**Comment by rarkins** [comment]
I think you misunderstand the meaning of "reproduction". It doesn't mean implementation

**Comment by l0b0** [comment]
What does it mean, then? I don't think I've ever heard of anyone using "reproduction" is the context of a feature request.

**Comment by l0b0** [comment]
This seems to be the only relevant line from the documentation:

> A minimal reproduction helps the developers see where the bug or missing feature is, and allows us to verify that the new code meets the requirements.

So I guess a reproduction here means pointing out that the relevant code is in `lib/modules/manager/pre-commit`. Do you need me to be more specific? Is there anything else needed for a "reproduction" of a missing feature? A test?

**Comment by rarkins** [comment]
It means you create a repository with the minimum content necessary to demonstrate the problem

**Comment by l0b0** [comment]
I guess we can't get past this communications barrier, so I'd rather just leave it here.
