### ISSUE TITLE
When a PR's title is edited manually, Renovate shouldn't overwrite it when it gets rebased

### ISSUE THREAD

**Issue by nachtien** [renovatebot/renovate#18829]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We have to have a Jira ticket associated with every PR (this makes us SOC compliant I think?).  After Renovate creates a PR, we manually prefix a Jira ticket to the title. 

When the PR gets rebased, Renovate resets the PR title back to what it used to be.

I'd like to keep the Jira ticket in the title when the PR gets rebased.

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
The PR title is essential to Renovate to find existing merged or closed PRs. Is the Jira issue number static and therefore could be configured?

**Comment by nachtien** [comment]
Thanks for responding so quickly and reading my issue :) 

I asked if we could have a static Jira issue number and they said "that goes against our SDLC and puts us out of SOC2".

Do you happen to have any other thoughts or suggestions?  

If I understand you correctly, you're saying that modifying the PR title in any way, whether it's rebased or not, could really mess things up?

**Comment by nachtien** [comment]
If we change the name + delete/rename, then won't renovate create another PR? 

I'm an Android developer and I really don't know why the design decisions were done, so forgive me for asking :) . Why isn't the PR# referenced instead of the title?

**Comment by nachtien** [comment]
ohhhhh gotcha, that makes sense!

**Comment by PhilipAbed** [comment]
> If we change the name + delete/rename, then won't renovate create another PR?

yes it will create a new PR 

changing PR title completely is not possible, but u can always play with the title configurations or add extra comments to it

**Comment by PhilipAbed** [comment]
@nachtien you dont need to put the jiraticket in the PR title, 

there's an automatic way to integrate between github and jira, google it and
if you want it manually edit it u can add it as a comment

**Comment by nachtien** [comment]
Would it be really difficult to add a configuration that would ignore a prefix? Maybe like some sort of regex string? 

Am I the only one with this problem?

**Comment by nachtien** [comment]
I modified Renovate a bit, but here's a PR thats up:

Update dependency androidx.navigation:navigation-compose from v2.5.1 to v2.5.3

In order for us to merge it in, it would have to look like similar to this (as long as it contains the ticket number):

[MXP-1234] Update dependency androidx.navigation:navigation-compose from v2.5.1 to v2.5.3

**Comment by rarkins** [comment]
In this case we'd need to see if the actual PR title _ends with_ the expected title.

**Comment by PhilipAbed** [comment]
> In this case we'd need to see if the actual PR title _ends with_ the expected title.
is there a chance 2 PRS end with the same text?  we should add a flag to support a certain regex template where you can add [MXP-numbers] + pr title... and then we can replace/remove it temporarily when we try to find prs.

we can support this in github only in this case, because we might need to change the `findPr` platform function.
maybe we should add a flag for this functionality that works only on github for now?

i thought also we could use the `commitMessagePrefix` but it's not dynamic so not sure
