### ISSUE TITLE
Add a preUpgradeTasks option?

### ISSUE THREAD

**Issue by r65535** [renovatebot/renovate#18845]
### What would you like Renovate to be able to do?

My team is running renovate against some golang repositories.

We have also set `postUpdateOptions` in `renovate.json` to run `gomodtidy`.

Before this can be run successfully, we need to run some initialization commands to the code base.

Example:
We use [swaggo/swag](https://github.com/swaggo/swag) to generate a `docs/` module which we don't commit to git. Renovate needs to run `swag init ./...` before updating dependencies

### If you have any ideas on how this should be implemented, please tell us here.

Add a preUpgradeTasks option similar to [postUpgradeTasks](https://docs.renovatebot.com/configuration-options/#postupgradetasks)?

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by viceice** [comment]
i think we already have an issue for this, please search again
