### ISSUE TITLE
Add job link in the Renovate comment with corresponding log

### ISSUE THREAD

**Issue by Hongbo-Miao** [renovatebot/renovate#18888]
### What would you like Renovate to be able to do?

Take https://github.com/Hongbo-Miao/hongbomiao.com/pull/5997 for example,

<img width="925" alt="image" src="https://user-images.githubusercontent.com/3375461/201510059-56597a89-27b9-4914-9a44-90f1a3ac49c4.png">

Currently, this is the link in above screenshot: https://app.renovatebot.com/dashboard#github/Hongbo-Miao/hongbomiao.com

It would be great to specify exact log link such as https://app.renovatebot.com/dashboard#github/Hongbo-Miao/hongbomiao.com/886333983

Thanks! 😃

### If you have any ideas on how this should be implemented, please tell us here.

Not sure..

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Please post to the ideas discussion forum next time.

Closing this for two reasons:
- this text is inserted by the app, and is not implemented in this open source repo
- jobs run all the time. We don't want to update the log link all the time, and not would that be helpful
