### ISSUE TITLE
Missing release notes for java package

### ISSUE THREAD

**Issue by simPod** [renovatebot/renovate#18897]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.24.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.5

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

There was a new release which is filled on github https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.44.0

However, I'm not seeing release notes in Renovate's PR

<img width="969" alt="image" src="https://user-images.githubusercontent.com/327717/201539947-1efbf3f8-da54-4d3b-aa54-a3fd27a478d1.png">

### Relevant debug logs

<details><summary>Logs</summary>

```
               {
                 "commitMessageTopic": "plugin gradleVersions",
                 "currentValue": "0.43.0",
                 "currentVersion": "0.43.0",
                 "depIndex": 43,
                 "depName": "com.github.ben-manes.versions",
                 "depType": "plugin",
                 "fileReplacePosition": 342,
                 "fixedVersion": "0.43.0",
                 "isSingleVersion": true,
                 "managerData": {
                   "fileReplacePosition": 342,
                   "packageFile": "gradle/libs.versions.toml"
                 },
                 "packageName": "com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin",
                 "registryUrls": [
                   "https://plugins.gradle.org/m2/",
                   "https://jitpack.io",
                   "https://repo.maven.apache.org/maven2"
                 ],
                 "versioning": "gradle",
                 "warnings": [],
                 "updates": [
                   {
                     "bucket": "non-major",
                     "newVersion": "0.44.0",
                     "newValue": "0.44.0",
                     "releaseTimestamp": "2022-11-13T18:10:19.000Z",
                     "newMajor": 0,
                     "newMinor": 44,
                     "updateType": "minor",
                     "branchName": "renovate/com.github.ben-manes.versions-0.x"
                   }
                 ]
               },
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
do they publish scm url inside their pom files? renovate needs them to find the source repo.

**Comment by rarkins** [comment]
If Renovate detected the source URL from the Pom.xml then you'd see a hyperlink in the screenshot

**Comment by rarkins** [comment]
@simPod please locate the Pom file for this release and check whether the SCM URL is set. If not, Renovate can't/won't find the source repo

**Comment by simPod** [comment]
Ok it is not there. Thanks for specifying where Renovate reads from.

**Comment by ben-manes** [comment]
@rarkins this is [present](https://github.com/ben-manes/gradle-versions-plugin/issues/709), but you are likely confused by the intermediate pom from Gradle's [plugin marker artifact](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers). Either Rennovate should detect this Gradle quirk and traverse the transient to the developer's pom or the Gradle should copy the metadata onto these automatically generated metadata files. This would not be a plugin author's responsibility as that was provided and is instead the tooling's to deal with.

**Comment by rarkins** [comment]
It is not a bug though, so needs resubmitting with the appropriate templates and a reproduction repo
