### ISSUE TITLE
Contribute Renovate as a TypeScript regression test project

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#18956]
### Describe the proposed change(s).

For every commit made to the TypeScript project, the TypeScript team runs regression tests against existing TypeScript projects. Packages are included in the test suite for one of two reasons:

- They are in the top 100 starred TypeScript packages on GitHub
- They are 'interesting', where interesting means:
  - They are important to the TypeScript ecosystem
  - They have particularly complex types
  - They have been badly broken by TypeScript upgrades in the past

Even though we hit 10k stars recently, we'd need to be at 16k stars to make the top 100 TypeScript projects on GitHub. However, I think there is a case to be made that Renovate falls into the 'interesting' category.

Check out [the test contribution guide][1] for more information

[1]: https://github.com/microsoft/typescript-error-deltas#user-tests

**Comment by viceice** [comment]
i like that idea ❤️

**Comment by HonkingGoose** [comment]
I like this idea as well! Who wants to be assigned to the issue? 😉

**Comment by JamieMagee** [comment]
PR opened in [microsoft/typescript-error-deltas#97](https://github.com/microsoft/typescript-error-deltas/pull/97)

**Comment by JamieMagee** [comment]
The PR has been merged upstream. Renovate will appear in new runs of [this build][1]. We may get tagged in issues in the TypeScript repository, or have issues or pull requests created by the TypeScript team in our repository.

[1]: https://typescript.visualstudio.com/TypeScript/_build?definitionId=47&_a=summary

**Comment by viceice** [comment]
🫣

**Comment by JamieMagee** [comment]
I'm reopening this as there appears to be an error setting up Renovate. [See here](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=148677&view=logs&j=61431db2-83b0-564b-4dc6-e3befd9254ba&t=c97e3e88-b767-522f-5d47-8801213b3478&l=334)

```
Cloning if absent
Cloning https://github.com/renovatebot/renovate.git into renovate
Installing packages if absent
Ignoring package install error from non-product folder test/e2e:
> Exited with code 1
> No stdout
> error "../../renovate-v0.0.0-semantic-release.tgz": Tarball is not in network and can not be located in cache (["/mnt/ts_downloads/renovate/renovate-v0.0.0-semantic-release.tgz","/home/vsts/.cache/yarn/v6/.tmp/c8dfa9055a0cda93989d5be6b4d41ff9/.yarn-tarball.tgz"])
/mnt/ts_downloads/renovate> yarn cache clean --all
yarn cache v1.22.19
success Cleared cache.
Done in 3.61s.

Testing with /home/vsts/work/1/s/typescript-53146/built/local/tsserver.js (new)
Killing process 3748 and its descendents: 3759
New server timed out after 600000 ms
Done https://github.com/renovatebot/renovate.git
Repo https://github.com/renovatebot/renovate.git had status "Unknown failure"
Cleaning up repo
```

**Comment by viceice** [comment]
> I'm reopening this as there appears to be an error setting up Renovate. [See here](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=148677&view=logs&j=61431db2-83b0-564b-4dc6-e3befd9254ba&t=c97e3e88-b767-522f-5d47-8801213b3478&l=334)
> 
> ```
> Cloning if absent
> Cloning https://github.com/renovatebot/renovate.git into renovate
> Installing packages if absent
> Ignoring package install error from non-product folder test/e2e:
> > Exited with code 1
> > No stdout
> > error "../../renovate-v0.0.0-semantic-release.tgz": Tarball is not in network and can not be located in cache (["/mnt/ts_downloads/renovate/renovate-v0.0.0-semantic-release.tgz","/home/vsts/.cache/yarn/v6/.tmp/c8dfa9055a0cda93989d5be6b4d41ff9/.yarn-tarball.tgz"])
> /mnt/ts_downloads/renovate> yarn cache clean --all
> yarn cache v1.22.19
> success Cleared cache.
> Done in 3.61s.
> 
> Testing with /home/vsts/work/1/s/typescript-53146/built/local/tsserver.js (new)
> Killing process 3748 and its descendents: 3759
> New server timed out after 600000 ms
> Done https://github.com/renovatebot/renovate.git
> Repo https://github.com/renovatebot/renovate.git had status "Unknown failure"
> Cleaning up repo
> ```

😕 it's our e2e test, which needs a package create before. can we ignore that somehow?

**Comment by JamieMagee** [comment]
It's hard to track, but the install command used appears to be `yarn install --no-immutable --ignore-scripts --silent`[^1].

If I can't get the simple setup to work, we can also define a custom build script[^2].

[^1]: https://github.com/microsoft/typescript-error-deltas/blob/main/src/utils/installPackages.ts
[^2]: https://github.com/microsoft/typescript-error-deltas#clone-repos-script-build

**Comment by viceice** [comment]
sounds like we should go with a custom build script

**Comment by JamieMagee** [comment]
I created a custom build script: https://github.com/JamieMagee/typescript-error-deltas/commit/7bc1415f344211097fc151a04bc6a1112a1c0ffe

Will create a PR tomorrow, as I can't interact with Microsoft GitHub repos from a non-work computer.

**Comment by JamieMagee** [comment]
Created https://github.com/microsoft/typescript-error-deltas/pull/121

**Comment by JamieMagee** [comment]
The PR has been merged upstream. Renovate will appear in new runs of [this build][1]. We may get tagged in issues in the TypeScript repository, or have issues or pull requests created by the TypeScript team in our repository.

[1]: https://typescript.visualstudio.com/TypeScript/_build?definitionId=47&_a=summary
