### ISSUE TITLE
Invalid lockfile since v34.26.3

### ISSUE THREAD

**Issue by twittwer** [renovatebot/renovate#18964]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.26.2

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Since version 34.26.3 renovate cannot install itself anymore.
```
Invalid: lock file's @opentelemetry/api@1.2.0 does not satisfy @opentelemetry/api@1.3.0
```
It seems to be related to the following update in version 34.26.3:
[build(deps): update opentelemetry-js monorepo](https://github.com/renovatebot/renovate/issues/18948)

### Relevant debug logs

<details><summary>Logs</summary>

```
#12 1.666 npm ERR! 
#12 1.666 npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
#12 1.666 npm ERR! 
#12 1.666 npm ERR! Invalid: lock file's @opentelemetry/api@1.2.0 does not satisfy @opentelemetry/api@1.3.0
#12 1.666 npm ERR! 
#12 1.666 npm ERR! Clean install a project
#12 1.666 npm ERR! 
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
When and where does Renovate install itself? `npm i -g renovate` still works fine, doesn't it?

**Comment by twittwer** [comment]
Like the log says it happened during an `npm ci`
The use case is a self hosted renovate that updates itself.

**Comment by twittwer** [comment]
While trying to create a reproduction I found out that it works if you update renovate via `npm i renovate@34.26.3`. Then it is possible to run `npm ci` as well.  
So it seems update of renovate by renovate seems not to update the lock file and a lock file recreation fixes the problem.

Missing lock file changes:
![image](https://user-images.githubusercontent.com/8677948/202662468-c0e90ebc-bffc-4e41-8181-123e732a266a.png)
