### ISSUE TITLE
Terraform lock file: make list of platforms configurable

### ISSUE THREAD

**Issue by malt3** [renovatebot/renovate#18960]
### What would you like Renovate to be able to do?

Renovate can already update terraform lock files (`.terraform.lock.hcl`). However, this does not work correctly if I create a lock file for multiple platforms:

```
terraform providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_arm64 -platform=darwin_amd64 -platform=windows_amd64
```

If renovate tries to upgrade a lock file containing hashes for multiple platforms, the new lock file does not include hashes for all platforms and there is no configuration option to specify the desired platforms.

### If you have any ideas on how this should be implemented, please tell us here.

Add configuration option to specify desired platforms for terraform lock file and include hashes for each specified platform.

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
🤔 renovate should add hashes for all supported platform of a package. you need to create a minimal reproduction. instructions follow.

**Comment by malt3** [comment]
> thinking renovate should add hashes for all supported platform of a package. you need to create a minimal reproduction. instructions follow.

I think I may have misunderstood the inner workings of the terraform lock file.

Renovate removed `zh` entries from the lock file which I understood as the lock file being incomplete. Here is the PR where I added back the removed lines on a project:

**Comment by secustor** [comment]
`zh` are legacy hashes which represent the whole downloaded archives.    
`h1` are used to check the actual provider blobs. 

There is a discussion regarding this on this issue https://github.com/renovatebot/renovate/issues/13692

**Comment by malt3** [comment]
Thank you so much for this info. I think this can be closed.
