### ISSUE TITLE
Prebuild Codespaces workspace

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19023]
### Describe the proposed change(s).

https://docs.github.com/en/codespaces/prebuilding-your-codespaces/about-github-codespaces-prebuilds

**Comment by HonkingGoose** [comment]
Remember to set up spending limits first, to prevent excessive bills for the Renovate organization. 😉 Here's how:

- [GitHub docs, managing the spending limit for GitHub Codespaces](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/managing-the-spending-limit-for-github-codespaces)
- [GitHub docs, managing the cost of GitHub Codespaces in your organization](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-the-cost-of-github-codespaces-in-your-organization)
