### ISSUE TITLE
Support version pinning for pnpm

### ISSUE THREAD

**Issue by pdcmoreira** [renovatebot/renovate#19038]
### What would you like Renovate to be able to do?

Basically https://github.com/renovatebot/renovate/issues/1362 should also work for `pnpm-lock.yaml` the same way it does for `package-lock.json`, otherwise the "Pin dependencies" PR that is created is trying to update all packages to the latest versions while pinning.

Repro repo / pinning PR:
https://github.com/pdcmoreira/renovate-pnpm-pin-dependencies/pull/1

`package.json` with `"axios": "^1.0.0"` range:
https://github.com/pdcmoreira/renovate-pnpm-pin-dependencies/blob/main/package.json

`pnpm-lock.yaml` with `axios v1.0.0` currently installed:
https://github.com/pdcmoreira/renovate-pnpm-pin-dependencies/blob/main/pnpm-lock.yaml

Output of "Configure Renovate" PR with `"rangeStrategy": "pin"`:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/4430606/203378465-ef9e6da7-a1c2-4959-9350-600f519a399f.png">

(Should be "Pin axios to `1.0.0`")

### If you have any ideas on how this should be implemented, please tell us here.

I would guess, try to find and parse the `pnpm-lock.yaml` file like it was done in https://github.com/renovatebot/renovate/pull/1447 for `package-lock.json`.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Reproduction forked to https://github.com/renovate-reproductions/19038

Solving this will require filling in this: https://github.com/renovatebot/renovate/blob/182496ca6a05b5695f756d26ec7ecfd4220d1e87/lib/modules/manager/npm/extract/locked-versions.ts#L76-L79
