### ISSUE TITLE
Log commands before running them

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19030]
### What would you like Renovate to be able to do?

Instead of logging the artifacts updating command and its result after the commands finishes, instead log the command _prior_ so that if it times out, we know what command is being run.

Example where this would have helped: https://github.com/renovatebot/renovate/discussions/19029#discussion-4589471

### If you have any ideas on how this should be implemented, please tell us here.

There's possibly an existing debug log which could be shifted in location.

### Is this a feature you are interested in implementing yourself?

No

**Comment by RahulGautamSingh** [comment]
https://github.com/renovatebot/renovate/blob/11a96b72a6b2564576edbc50086dd3cb28b4a390/lib/util/exec/index.ts#L181-L185

Should I convert the `trace` to debug? Or just add a new one.
```ts
 logger.debug({ command: rawCmd }, 'Executing command'); 
```

**Comment by rarkins** [comment]
Convert to debug!
