### ISSUE TITLE
Update dependency error in `modules/manager/npm/update/dependency/index.ts/replaceAsString()`

### ISSUE THREAD

**Issue by herndlm** [renovatebot/renovate#19072]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.32.2

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

7.12.0

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

We basically have the following package.json and use yarn with it:
```json
{
  "devDependencies": {
    "our-internal-dep": "0.45.1-2615"
  },
  "peerDependencies": {
    "our-internal-dep": "*"
  }
}
```

`our-internal-dep` is on an internal package repository and the latest version is `0.45.1-2825`. Renovate was able to update this successfully until around October 20th I was told. But now it fails with an internal error (see logs below).

To me it looks like the problem could be related to the `peerDependency` with the `*` version selector (see also relevant logs below) where Renovate does not find a `lockedVersion` and additionally `currentVersion` is set to `null`. Some of those seem to be also triggering a rollback I suppose. It can be seen that the previous block (the `devDependency`) was resolved properly.

The line that triggers the error is https://github.com/renovatebot/renovate/blob/34.32.2/lib/modules/manager/npm/update/dependency/index.ts#L105

I was wondering if this could also be related to https://github.com/renovatebot/renovate/pull/18251 somehow? or similar later changes? because the last-working timing doesn't quite match.. CC @Gabriel-Ladzaretti 

I tried, but couldn't create a reproducer so far :/

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Current version not found - rolling back (repository=<internal-repo>, packageFile=packages/af-pilets/package.json)
    "depName": "<internal-dependency>",         "depName": "<internal-dependency>",
    "currentValue": "*"

...

{
    "depType": "devDependencies",
    "depName": "<internal-dependency>",                   "depName": "<internal-dependency>",
    "currentValue": "0.42.0-2615",
    "datasource": "npm",
    "prettyDepType": "devDependency",
    "lockedVersion": "0.42.0-2615",
    "depIndex": 11,
    "updates": [
        {
        "bucket": "non-major",
        "newVersion": "0.45.1-2825",
        "newValue": "0.45.1-2825",
        "releaseTimestamp": "2022-11-24T03:12:46.098Z",
        "newMajor": 0,
        "newMinor": 45,
        "updateType": "minor",
        "branchName": "<renovate-update-branch>"
        }
    ],
    "warnings": [],
    "versioning": "npm",
    "currentVersion": "0.42.0-2615",
    "isSingleVersion": true,
    "fixedVersion": "0.42.0-2615"
},

...

{
    "depType": "peerDependencies",
    "depName": "<internal-dependency>",                   "depName": "<internal-dependency>",
    "currentValue": "*",
    "datasource": "npm",
    "prettyDepType": "peerDependency",
    "depIndex": 76,
    "updates": [
        {
        "bucket": "rollback",
        "newMajor": 0,
        "newValue": null,
        "newVersion": "0.45.1-2825",
        "updateType": "rollback",
        "branchName": "<renovate-update-branch>"
        }
    ],
    "warnings": [],
    "versioning": "npm",
    "currentVersion": null,
    "skipReason": "invalid-version"
},

...

DEBUG: manager.getUpdatedPackageFiles() reuseExistingBranch=false (repository=<internal-repo>, branch=<renovate-update-branch>)
DEBUG: npm.updateDependency(): peerDependencies.<internal-dependency> = null (repository=<internal-repo>, branch=<renovate-update-branch>)
DEBUG: updateDependency error (repository=<internal-repo>, branch=<renovate-update-branch>)
    "err": {
    "stack": "Error: \n    at replaceAsString (/usr/src/app/node_modules/renovate/lib/modules/manager/npm/update/dependency/index.ts:105:9)\n    at updateDependency (/usr/src/app/node_modules/renovate/lib/modules/manager/npm/update/dependency/index.ts:173:26)\n    at getUpdatedPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/update/branch/get-updated.ts:187:30)\n    at processBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/update/branch/index.ts:418:19)\n    at writeUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/write.ts:159:17)\n    at update (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:151:11)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:61:19)\n    at attributes.repository (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:173:11)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:158:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:17:22"           "stack": "Error: \n    at replaceAsString (/usr/src/app/node_modules/renovate/lib/modules/manager/npm/update/dependency/index.ts:105:9)\n    at updateDependency (/usr/src/app/node_modules/renovate/lib/modules/manager/npm/update/dependency/index.ts:173:26)\n    at getUpdatedPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/update/branch/get-updated.ts:187:30)\n    at processBranch (/usr/src/app/node_modules/renovate/lib/workers/repository/update/branch/index.ts:418:19)\n    at writeUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/write.ts:159:17)\n    at update (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:151:11)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:61:19)\n    at attributes.repository (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:173:11)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:158:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:17:22"
    }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by herndlm** [comment]
I tried :/

In my reproducer the peerDependency always has a currentVersion and lockedVersion like
```json
{
    "currentValue": "*",
    "currentVersion": "17.0.0",
    "datasource": "npm",
    "depIndex": 2,
    "depName": "react",
    "depType": "peerDependencies",
    "fixedVersion": "17.0.0",
    "homepage": "https://reactjs.org/",
    "lockedVersion": "17.0.0",
    "prettyDepType": "peerDependency",
    "sourceDirectory": "packages/react",
    "sourceUrl": "https://github.com/facebook/react",
    "versioning": "npm",
    "warnings": [],
    "updates": []
}
```

I think I might just have to start step-debuging Renovate 😊

**Comment by herndlm** [comment]
well, that was easier than I thought :) I'll continue later, but what I saw so far

`allSatisfyingVersions` is empty in https://github.com/renovatebot/renovate/blob/34.34.0/lib/workers/repository/process/lookup/index.ts#L138
`unconstrainedValue` is `false`, `currentValue` is `*` as expected BUT `allVersions` is properly populated as well!
![image](https://user-images.githubusercontent.com/5738896/203839319-2e17fe73-9fe7-4d29-811d-5a8b22ede630.png)

I guess `unconstrainedValue` should be `true` here?

**Comment by herndlm** [comment]
right, so the problem is the version number with the hyphen..

```js
allVersioning.get('npm').matches('1.2.3+123', '*') 
true
allVersioning.get('npm').matches('1.2.3-123', '*') 
false
allVersioning.get('npm').matches('1.2.3', '*') 
true
```

according to https://semver.org/#spec-item-9 the hyphen marks a pre-release. I'm not sure how this should be handled, other versioning implementations (e.g. semver) also behave like that. is a special condition for `*` needed? I could also try a git bisect to figure out why it worked before and broke..

**Comment by rarkins** [comment]
In npm versioning, * does not match pre-releases

**Comment by rarkins** [comment]
Renovate has the concept of ignoreUnstable=false but I'm not sure if that will help you here if the problem is npm's own versioning

**Comment by herndlm** [comment]
I'll continue tomorrow. But this is the check that deals with making a rollback or not if the current version can't be found in the repo. Not sure if it has to be in range. Something feels off

**Comment by rarkins** [comment]
If you disable rollback PRs, is the error removed?

**Comment by rarkins** [comment]
Current:

```
      // Check that existing constraint can be satisfied
      const allSatisfyingVersions = allVersions.filter(
        (v) =>
          // TODO #7154
          unconstrainedValue || versioning.matches(v.version, currentValue!)
      );
```

Maybe:

```
      // Check that existing constraint can be satisfied
      const allSatisfyingVersions = allVersions.filter(
        (v) =>
          // TODO #7154
          unconstrainedValue || versioning.matches(v.version, currentValue!) || v.version === lockedVersion
      );
```

**Comment by herndlm** [comment]
yes, that makes sense and should do the trick I think! I'll check it out and get a PR ready if it does indeed fix it.

**Comment by herndlm** [comment]
argh, I think that would work, but in my constellation (having the same dependency both as peer and dev dependency) the `peerDependency` entry with `currentValue:  "*"` has `lockedVersion: null`. I'll try to find out why that is. If all things fail I should be able to create a reproducer now at least I think

**Comment by herndlm** [comment]
and to answer your previous question: yes, disabling rollback PRs fixes this too, so that's definitely a viable solution for me! I think this is some edge case wit a `*` selector and our weird pre-releases that we're triggering, not sure if there's a general way of dealing with this. but if you have any more ideas let me know, I can try them out.

**Comment by rarkins** [comment]
Possibly a bug or shortcoming in our get locked versions logic during extract phase?

**Comment by herndlm** [comment]
Yep, so https://github.com/renovatebot/renovate/blob/34.34.0/lib/modules/manager/npm/extract/locked-versions.ts#L40 doesn't work properly because `${dep.depName}@${dep.currentValue}` evaluates to `our-internal-dep@*` but the lockfile only has the following
```json
our-internal-dep@0.42.0-2615: "0.42.0-2615"
our-internal-dep@^0.42.0-2615: "0.42.0-2615"
```
