### ISSUE TITLE
Reviewers feature not working for team reviews

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#1908]
#### This is a:

Bug report (non-security related)

#### I'm using:

The Renovate GitHub App

#### Please describe the issue:
Split out of https://github.com/renovateapp/renovate/issues/782#issuecomment-385990779.

The [reviewers]() feature doesn't appear to be working for teams - since Renovate just opened mozilla-neutrino/neutrino-dev#841, however no reviewer was set.

Our config is:
https://github.com/mozilla-neutrino/neutrino-dev/blob/a75b56daad90415dab927569133b0131cacdf3fa/renovate.json#L9-L11

Which should map to:
https://github.com/orgs/mozilla-neutrino/teams/core-contributors

Also:
* Should the usernames in the config start with a `@` or not?
* Once this is fixed the docs can now be updated to remove mention of the "outstanding GitHub API bug", [here](https://renovatebot.com/docs/configuration-reference/configuration-options#reviewers)

Many thanks :-)

**Comment by rarkins** [comment]
@edmorley I think it might be another limitation of GitHub, e.g. need to request team list read permissions for the app in order to assign a team to a PR or issue.. even though we don't care who's in the team and never want to hit that API.

**Comment by edmorley** [comment]
Ah right, thank you

**Comment by rarkins** [comment]
It seems that this "members" permissions is needed to be added to the app: https://developer.github.com/v3/apps/permissions/#permission-on-members

Unfortunately GitHub's permissions are not so granular, so doing so means:
- Every existing Renovate admin would get an email from GitHub asking for these "members" permissions to be confirmed
- All new installations have no choice but to accept it (it's "all or none" when it comes to GitHub permissions)

Requesting this permissions means that Renovate can (theoretically) find out all teams and members in an Org. Do you think anyone would reject that?

**Comment by edmorley** [comment]
Ah that's unfortunate. I can't really say whether people would mind or not; Mozilla is pretty open compared to many orgs and most of our repositories are open source -- so we're not exactly a typical case.

It does seem a bug that you can't set a reviewer without this permission though? Perhaps this avenue is worth following first?

**Comment by edmorley** [comment]
I should have asked this before, but does the reviewers feature work if individual users are specified rather than teams?

**Comment by rarkins** [comment]
I don’t use the feature myself but as far as I’m aware, yes. Ie if you define one or more reviewers individually then it should work

**Comment by glavoie** [comment]
Hi! Is this limitation still "valid"? We also have the need to add team reviewers to PRs created by Renovate Bot. We use a self-hosted instance connecting to GitHub using an API key of a dedicated user.  The API key only has the scope `repo` (Full control of private repositories).

With this scope, I can call manually `curl -X POST -u github-renovate-user -d '{"team_reviewers":["team-slug-name"]}' -H "Content-Type: application/json" https://api.github.com/repos/my_org/my_repo/pulls/123/requested_reviewers` to add a team to a PR.

**Comment by rarkins** [comment]
For self-hosted GitHub Enterprise, if the token belongs to an account with sufficient privilege to add team reviewers then we should ideally support that in Renovate. If some code changes are needed to support both scenarios gracefully then I’d be welcoming to a PR.

**Comment by glavoie** [comment]
To make it clear, this is on regular GitHub with a private Org.

**Comment by rarkins** [comment]
We may support `@user` syntax already (or massage it) so I think it would be clearer if we do something obvious like `team:team-1`

**Comment by glavoie** [comment]
https://github.com/renovatebot/renovate/pull/3973

**Comment by rarkins** [comment]
Closed by #3973

**Comment by felixfbecker** [comment]
I cannot get the team reviewers feature to work. We have a `web` team in our org on github.com (https://github.com/sourcegraph). What do I need to put into the `reviewers` config to make it work? `team:web`, `team:sourcegraph/web` or maybe `team:@sourcegraph/web`?

**Comment by glavoie** [comment]
When I tested it, I used the team ID without the organization name: 
<img width="223" alt="image" src="https://user-images.githubusercontent.com/13800915/65975296-65e22180-e43c-11e9-8f83-160e5146423a.png">

In the config:
``` "reviewers": ["team:dev-devops-tools"]```

**Comment by felixfbecker** [comment]
And that worked on github.com with the GitHub marketplace app?

**Comment by glavoie** [comment]
Allright, if you go through the comments above, it is mentioned that in the GitHub marketplace, the granted permissions may not be enough to support that feature. 

We use it in a self-hosted environment where we can grant enough permissions to our GitHub org to the user account used by Renovate.

**Comment by felixfbecker** [comment]
@rarkins would it be possible to make this work for GitHub marketplace? We don't have a problem with giving Renovate access to our team members, that seems like a reasonable permission for Renovate to have given it can assign people.

**Comment by rarkins** [comment]
@felixfbecker Renovate recently did request organization owners permission for teams permission, although it was not with this team reviewers permission in mind. I'm not sure if there's an easy way for me to check if your org owner granted it or not, but if they visit https://github.com/apps/github then they can hopefully see if there's any request outstanding.
