### ISSUE TITLE
CodeCommit: Remove ARN identification

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19093]
### What would you like Renovate to be able to do?

Currently, we have: https://github.com/renovatebot/renovate/blob/325a11257de46e68f2eb4400041763554f05cbd5/lib/modules/platform/codecommit/index.md?plain=1#L44

Ideally we would like to avoid this recommendation to have `IAMReadOnlyAccess`

### If you have any ideas on how this should be implemented, please tell us here.

Currently in https://github.com/renovatebot/renovate/blob/main/lib/modules/platform/codecommit/iam-client.ts we:
- Call GetUser() to get user.arn
- If it fails, parse the error message to learn the user arn that way

Instead, we should skip fetching the ARN

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
I think let's have #19091 implemented first, and then see if there's any way to avoid this permission here.

**Comment by PhilipAbed** [comment]
i ran on an EC2 instance 
![image](https://user-images.githubusercontent.com/42116482/205608732-fc13db14-04aa-4183-9297-70bb78f718de.png)

and here's the PR author:
![image](https://user-images.githubusercontent.com/42116482/205609252-8ea5cf0d-d966-4b74-8977-9377641d8ffd.png)

it's possible to extract the id using a simple command see:
```
ubuntu@ip-172-31-7-182:~/renovate$ ec2metadata --instance-id
i-0a2de13b2c0ba55a7
```

Conclusion:

For user access key Id/secret access key, the ARN will be the User which we can get from `IAM.GetUser()` permission
For Code-build yaml, the ARN will be the build number prefixed by CodeBuild like: `CodeBuild-1234566xyz`
For EC2 instance, the author ARN is the EC2 Instance number as you can see in the above screenshots,

**Comment by rarkins** [comment]
What is ARN used for today? Only for filtering _open_ PRs by author?

**Comment by PhilipAbed** [comment]
correct

**Comment by rarkins** [comment]
In that case let's remove it altogether and instead we can use branch name + PR title to search. Any major downsides?

**Comment by PhilipAbed** [comment]
yes the `findPr` does that already,

the ARN is too dynamic, i agree that we should remove the filtering.

the only downside having no filter for PRs.

**Comment by rarkins** [comment]
In that case let's remove the ARN discovery + filtering and we can close this issue that way

**Comment by PhilipAbed** [comment]
@rarkins removing all author discovery altogether.

That means author discovery for user credential based access (access key and secret access key) will also be removed
