### ISSUE TITLE
Stale bot ignores older issues?

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19100]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I see old issues with reproduction needed but no stale warning. Example: https://github.com/renovatebot/renovate/issues/13470

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by HonkingGoose** [comment]
> I see old issues with reproduction needed but no stale warning. Example: https://github.com/renovatebot/renovate/issues/13470

Your example issue is labeled `type:feature`. We only stale `type:bug` issues with `reproduction:needed`:

https://github.com/renovatebot/renovate/blob/ee76b623e2a3b2f69e886694064e32f5e578e63b/.github/workflows/stale-action.yml#L21-L22

Do you want to start labeling old feature requests that need a reproduction as stale?

**Comment by rarkins** [comment]
No, let's keep that as is. I was sure I'd seen an old bug with no reproduction too, but maybe I imagined it

**Comment by HonkingGoose** [comment]
I think we can close this issue then. 😉
