### ISSUE TITLE
recreateClosed is false for groups

### ISSUE THREAD

**Issue by omercnet** [renovatebot/renovate#19126]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

whitesource/renovate:2.6.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Using groupName, Renovate does not open new PRs automatically
Had to change recreateClosed to True for it to work, contrary to documentation
https://docs.renovatebot.com/configuration-options/#recreateclosed

>For example we override it to true in the following cases where branch names and PR titles need to be reused:
>* Package groups

### Relevant debug logs

<details><summary>Logs</summary>

```
"prTitle": "chore(deps): update internal packages"
DEBUG: Closed PR already exists. Skipping branch. (repository=org/repo, branch=renovate/internal-packages)
DEBUG: Returning PR from cache (repository=org/repo, branch=renovate/internal-packages)
DEBUG: Found closed PR with current title (repository=org/repo, branch=renovate/internal-packages)
DEBUG: Found PR #2411 (repository=org/repo, branch=renovate/internal-packages)
DEBUG: findPr(renovate/internal-packages, chore(deps): update descope packages, !open) (repository=org/repo, branch=renovate/internal-packages)
DEBUG: recreateClosed is false (repository=org/repo, branch=renovate/internal-packages)
DEBUG: dependencyDashboardCheck=undefined (repository=org/repo, branch=renovate/internal-packages)
DEBUG: branchExists=false (repository=org/repo, branch=renovate/internal-packages)
DEBUG: Found PR #2240 (repository=org/repo, branch=renovate/internal-packages)
DEBUG: findPr(renovate/internal-packages, undefined, closed) (repository=org/repo, branch=renovate/internal-packages)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Here's the logic where `recreateClosed` is set to `true` automatically: https://github.com/renovatebot/renovate/blob/e82f6cd480ae1f40265334b070824700f25a6b7e/lib/workers/repository/updates/generate.ts#L172-L185

What's the contents of that group?

**Comment by omercnet** [comment]
```json
"packageRules": [
    {
      "matchPackagePatterns": ["ghcr.io/org/.*"],
      "matchDatasources": ["docker"],
      "groupName": "internal services images",
      "recreateClosed": true
    }
  ]
```

**Comment by rarkins** [comment]
I mean, which dependency updates are found within that group?

**Comment by omercnet** [comment]
sorry, I don't understand the question..
it's for docker images for our internal services, hosted on GHCR
the file matched is a `docker-compose.yaml` file

**Comment by rarkins** [comment]
Are they all the same dependency? All the same version? 2 of them or 20? etc. Something in particular about these dependencies leads Renovate to skip those `if` conditions above

**Comment by omercnet** [comment]
It's 1-10 different docker images

**Comment by rarkins** [comment]
That might be it. Perhaps we need a rule saying that if all updates are digest updates then recreateClosed should be true

**Comment by HonkingGoose** [comment]
> Perhaps we need a rule saying that if all updates are digest updates then `recreateClosed` should be `true`

Is this `status:ready` then? Or do you maintainers need to think some more about this?

**Comment by rarkins** [comment]
Not until there's a reproduction
