### ISSUE TITLE
Sign our own npm package

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#19170]
### What would you like Renovate to be able to do?

We should look into signing our packages. It's probably a good idea to figure out signing our npm package first to learn how it all works. We can expand signing to our other projects/build artifacts later.

### If you have any ideas on how this should be implemented, please tell us here.

GitHub has a blog [^blog] about using Sigstore on GitHub Actions to sign a build. The key benefit seems to be that with Sigstore you don't have to manage a private key, they call this "keyless signing". It sounds like this all makes signing easier to setup and maintain. 😄 

The Sigstore project is now released under General Availability, and GitHub says it's stable to start using now.

I've copy/pasted the most relevant part of the blog below for reference:

> **Sigstore and GitHub Actions, today**
> 
> The first thing people do to secure their builds is to sign them, so you can detect if it’s been tampered with between when the build finished and when you’re about to run it. This often requires managing a private key, including generating it correctly, keeping it a secret, and rotating it over time. At best this is a hassle, and at worst it’s a roadblock for folks who don’t have experience in this area. As a result, builds aren’t signed nearly as often as they should be.
> 
> When you’re building in a cloud CI/CD provider that [supports OIDC tokens, like GitHub Actions](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect), Sigstore can generate a signing certificate for your build _without_ having to maintain a private key. Sigstore calls this [keyless signing](https://github.com/sigstore/cosign/blob/main/KEYLESS.md), and it’s a fantastic example of lowering the barrier to entry so more projects can sign their builds. In fact, this keyless signing is already in use for [Kubernetes](https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/#signing-release-artifacts) as well as [CPython](https://www.python.org/download/sigstore/) releases.
> 
> To illustrate how to do this, last year we wrote about [how to use Sigstore’s cosign to sign container images built in GitHub Actions](https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/). While cosign sign assumes your build is a container image, you can also use cosign sign-blob on any type of build output.
> 
> These are all things you could already do with Sigstore on GitHub Actions, but general availability is an exciting milestone in terms of maturity: the components have all reached a 1.0+ release, the APIs are stable, and the public servers now have a SLO and a 24/7 on-call rotation. This release is a collaboration across several organizations, and GitHub has directly supported it by contributing to both the development of the Sigstore code as well as the on-call rotation for the servers.

I'll let you maintainers figure out how this all works, and let you set up signing. 😉 

[^blog]: https://github.blog/2022-10-25-why-were-excited-about-the-sigstore-general-availability/

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment]
Thanks for the links!

Are you sure about using `sigstore-js`? Here's a quote from their readme:

> # sigstore-js
> 
> ⚠️ This project is not ready for general-purpose use! ⚠️

I'll let you decide what to do with this information. 🙂

**Comment by JamieMagee** [comment]
I have the solution in a branch, [`feat/sign-npm`][1]. This enables provenance generation by default when running `npm publish`.

I created [an example package][2] with [provenance enabled in `.npmrc`][3] to test the functionality. Unfortunately, I currently get [an error when trying to publish the package][4]:

> npm ERR! 422 Unprocessable Entity - PUT https://registry.npmjs.org/@jamiemagee%2fprovenance - Publishing with sigstore provenance is not enabled for your account. Contact support if you would like to beta test this feature when it becomes available.

[1]: https://github.com/renovatebot/renovate/commit/e17ca05988f538fef0a23f488ba1396c217bd1be
[2]: https://github.com/JamieMagee/jamie-provenance
[3]: https://github.com/JamieMagee/jamie-provenance/blob/main/.npmrc
[4]: https://github.com/JamieMagee/jamie-provenance/actions/runs/3580599928/jobs/6022862363#step:7:29

**Comment by rarkins** [comment]
I submitted a request for the `publish-bot` npm user to be able to sign `renovate`

**Comment by JamieMagee** [comment]
@rarkins did you hear back? It looks like GA of the feature is coming soon https://github.com/github/roadmap/issues/657

**Comment by rarkins** [comment]
I don't think I've been notified of anything, can't find any sign of it when I log in either

**Comment by JamieMagee** [comment]
The feature is now generally available https://github.blog/2023-04-19-introducing-npm-package-provenance/

**Comment by JamieMagee** [comment]
I was just opening a PR 😓 

https://github.com/renovatebot/renovate/pull/21612

**Comment by viceice** [comment]
can we close this now?

**Comment by HonkingGoose** [comment]
This likely fix is now in `main`

- #21612

but we don't know if it works. We'll have to wait for a release-worthy commit to land in `main`, to see if the `release-npm` step finishes properly.

Then we need to check that we can see the new provenance label on the npm registry for our package. Once all that is done, we can close this issue. 😄

**Comment by JamieMagee** [comment]
Renovate version `35.55.1` is the first version of Renovate to be signed:
- https://www.npmjs.com/package/renovate/v/35.55.1#provenance-details-header
- https://search.sigstore.dev/?logIndex=18502134

![image](https://user-images.githubusercontent.com/1358764/233467026-013ba734-6e39-41c4-8094-f2c82d3474d0.png)
