### ISSUE TITLE
Improve regexManager documentation

### ISSUE THREAD

**Issue by TimKnight-DWP** [renovatebot/renovate#19265]
### What would you like Renovate to be able to do?

We are looking to use renovate to migrate gitlab-ci includes definitions from one internal repo to another using a regexManager and autoReplaceStringTemplate

### If you have any ideas on how this should be implemented, please tell us here.

We are close to finishing completion on a working config to do this, so would be looking to feed the learnings back into the renovate documentation.

I have a feeling some of the discoveries may prompt from the PR to raise some issues to fix bugs if some of our work is working around unintended logic.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by PhilipAbed** [comment]
see https://github.com/renovatebot/renovate/issues/15384
if you have a really good documentations for regex.
maybe we can create a tutorial for regex manager too from it.

**Comment by TimKnight-DWP** [comment]
I can probably contribute a partial example to that tutorial repo too yeah
