### ISSUE TITLE
Inconsistent escaping in fileMatch

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19312]
### Describe the proposed change(s).

`fileMatch: ['(^|\\/)`:

![image](https://user-images.githubusercontent.com/6311784/206426145-755e4bc5-5040-40ce-8a9b-54053d223aef.png)

There are then 49 instances of `fileMatch: ['(^|/)`.

Do both work?

**Comment by viceice** [comment]
yes, because of the relaxed javascript regex engine. the correct one is the escaped.

**Comment by rarkins** [comment]
Seems that:
- forward slash is not a special character which needs escaping
- It's only necessary to escape if using `/` to denote start/end of a regex

Source (but one of many): https://javascript.info/regexp-escaping
