### ISSUE TITLE
Generic version detection/replacement

### ISSUE THREAD

**Issue by mxey** [renovatebot/renovate#1938]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [x] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Similar idea to https://github.com/renovateapp/renovate/issues/839, having the ability to let Renovate look at a version number in an arbitrary file, with a marker where to find the most recent version.

One use case for me would with Puppet, where I have a version in my Hiera data like this:

```yaml
profile::kubernetes::common::version: 1.10.2 #github: kubernetes/kubernetes
```

That is just an arbitrary string value to Puppet, it only has meaning in context. It would be useful if I Renovate could recognize the version and compare it against the latest releases of Kubernetes on GitHub, for example.

**Comment by rarkins** [comment]
Thanks for the additional use case. It's definitely something I want Renovate to do one day. The challenge with generic files will be that the way you structure them and comment within them varies, so we can't be completely "agnostic" and support all files without configuration. 

I think one easy addition to this is idea is to use Renovate in that comment so we can find them, e.g. something like `#renovate:github kubernetes/kubernetes`, otherwise there's a risk of false positives.

**Comment by rarkins** [comment]
@mxey is the above format of `a::b::c::version:` a strict Puppet convention, or are those names/fields arbitrary? From my quick look at puppet docs, it looks like "version" is arbitrary, although perhaps if we added official puppet support to Renovate (instead of a solve-all generic yet) then we could insist that it must end with "version".

**Comment by mxey** [comment]
The structure of the key is a strict convention, where `a::b::c` is the name of the class and  `version` is the name of the field. The names themselves are all arbitrary. I would recommend against making a requirement on the name.

**Comment by rarkins** [comment]
But we can assume it always ends in :version ?

**Comment by felixfbecker** [comment]
It would be nice if we could update software downloaded and built from source in Dockerfiles or through package managers that allow version pinning. I think you could get by without magic comments and instead with some config in renovate.json that specifies `fileMatch` (already exists) and a regex with a capture group to match and extract the current version. Then a config on where to get the latest release from - in most cases there will probably be a git/GitHub repository somewhere that exposes tags/releases. Other sources could be e.g. `apt-get`/`apk` repositories.

**Comment by rarkins** [comment]
@felixfbecker could you provide some example files you’d like to be able to update? Ie some references for me to aim for

**Comment by felixfbecker** [comment]
Here you go: https://github.com/sourcegraph/lsp-adapter/tree/master/dockerfiles

**Comment by hbetts** [comment]
> with some config in renovate.json that specifies fileMatch (already exists) and a regex with a capture group to match and extract the current version

Could these version matchers be shared as well? Would it make sense? (If I were following a community convention for a product or technology, could I just on-board my project by extending a community collection of pattern matchers?

**Comment by hbetts** [comment]
Recently came across another use case. The need to revision the `include` URL in a `.gitlab-ci.yml` file - https://gitlab.com/gitlab-com/support-forum/issues/3725

**Comment by rarkins** [comment]
I’m confused by the issue you point to, it sounds as if the approach *doesn’t* support revisioning ?

**Comment by hbetts** [comment]
@rarkins it can be revisioned by using a permalilnk (commit hash or version tag).

Doing so, though, would require that I update all projects manually any time the CI configuration file changes.

**Comment by felixfbecker** [comment]
How about a config schema like this?
```json
"regex": [
  {
    "fileMatch": "**/script.sh",
    "pattern": "git clone (?<repo>https://.+) && git checkout (?<revision>[0-9a-f]{40})"
  }
]
```
It uses named capture groups to tell Renovate what parts of the regex have semantic meaning. Renovate would be able to handle a known set of properties, e.g. if `repo` matches a git clone URL, it will compare `revision` with the latest commit from the default branch of that repo and create PRs to replace it.

**Comment by rarkins** [comment]
@felixfbecker I like the idea of using named capture groups to make generic rules simpler.

**Comment by adam-moss** [comment]
Definitely like the idea of this one.  A generic regex file match as per the above example would be exceedingly useful for dealing with some non-dependency related technical debt that can (and should) be fully automated.

**Comment by monochromata** [comment]
I'd also like to contribute use cases:

**p2-maven-plugin configuration**

I use the [p2-maven-plugin](https://github.com/reficio/p2-maven-plugin) and refer to versions of artifacts available from the Central Repository in a configuration of the p2-maven-plugin that is part of the pom.xml but not currently updated by renovate: https://gitlab.com/monochromata-de/third-party-p2/blob/master/pom.xml#L109

The source of the current version would be the Central repository, the format is `groupId:artifactId:version`.

**References to Maven plugins in bash scripts**

I use shell scripts in which I invoke maven with an explicit version of a plug-in so it does not need to be specified: https://gitlab.com/monochromata-de/build-tools/blob/master/src/main/bash/includes/steps/setNewVersion/inMavenTychoPom.inc#L35

The source of the current version of the plug-in would be the Central repository, the format is `groupId:artifactId:version:goal` - `goal` could likely be excluded from the regex

**Comment by mykter** [comment]
Love the regexp matching idea. For our usecase, it would benefit from an additional configuration option of being able to specify the datasource.

Here's the start of a Dockerfile we have that installs a bunch of tools:
```Dockerfile
ENV NODEV="12.14.1" \
    GOSWAGGERV="0.21.0" \
    GOLANGCILINTV="1.23.1" \
    GCPSDKV="276.0.0" \
    TERRAFORMV="0.12.19"
```
These variables are all referenced in curl commands later on. The datasources vary - gitlab releases; a specific URL; etc. There's no way to automatically work out what datasource to use, or what the package name is within that datasource. 

To expand on the example above then, something like this would be great:
```
"regex": [
 {
    "fileMatch": "my.Dockerfile",
    "pattern": "GOLANGCILINTV=\"(?<revision>.+)\""
    "source": "github-releases"
    "package": "golangci/golangci-lint"
  },
  {
    "fileMatch": "my.Dockerfile",
    "pattern": "NODEV=\"(?<revision>.+)\""
    "source": "npm"
    "package": "node"
  },
...
]
```

**Comment by rarkins** [comment]
Example: https://github.com/renovate-tests/regexmanager1/pull/1

**Comment by rarkins** [comment]
Docs: https://docs.renovatebot.com/modules/manager/regex/

Feedback welcome! I also hope to build up a small army of presets around this functionality and do better at documenting *those* too.

**Comment by mykter** [comment]
Looks terrific. Like the improvement on my example of embedding source info inline as comments.
