### ISSUE TITLE
Fall back to expired cached results when datasources error

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19414]
### What would you like Renovate to be able to do?

Reuse cached results instead of aborting runs when external datasource hosts fail

### If you have any ideas on how this should be implemented, please tell us here.

- Do not immediately expire cached datasource results. e.g. expire them in Redis at 10x the TTL we set
- If the fresh lookup (e.g. to npmjs) succeeds, use it and update Redis
- If results have passed their TTL, but then the "fresh" lookup fails, reuse the cached results. e.g. instead of an ExternalHostError for npm or Docker Hub, return the old results

If this needs to be implemented manager-by-manager then focusing on Docker Hub and npmjs would be best.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by zharinov** [comment]
Can be implemented in the decorator level, but shouldn't be a default behavior since we're also using it for caching intermediate results.

**Comment by rarkins** [comment]
A related performance improvement: some datasources could be made more efficient if they were allowed to return metadata _about_ the result, which is then passed back to it after soft expiry.

For example with npm, it could be as simple as returning the etag and/or last-modified headers. Then, these could be used for the requery to (hopefully) get back a 304 response instead of needing the full one.

```
❯ curl -I -H 'If-None-Match: "e7edea410bbe0a818a4c0dbf7b96484d"' https://registry.npmjs.org/@renovate/pep440
HTTP/2 304
date: Tue, 20 Dec 2022 08:37:49 GMT
cf-ray: 77c70ee96888991a-ARN
age: 287
cache-control: public, max-age=300
etag: "e7edea410bbe0a818a4c0dbf7b96484d"
last-modified: Wed, 06 Apr 2022 19:21:55 GMT
vary: Accept-Encoding
cf-cache-status: HIT
x-amz-replication-status: COMPLETED
server: cloudflare
```

**Comment by rarkins** [comment]
In theory these datasources could cache these values themselves though

**Comment by rarkins** [comment]
In theory each datasource could cache the metadata separately/independently however it's better to combine it so that:
- one cache return trip instead of two
- you need the cached results to return anyway, if you get a 304

Also, there may be some paginated datasources where having the existing results can mean reduced data fetching even when something has changed (e.g. filtering by last updated more recently than the last fetch)

**Comment by rarkins** [comment]
I've implemented this for npm, and would now like to add this partially for the cache decorator. To close this issue:

- The current TTL used should be considered a "soft" expire time, and the actual cache expire should be set to 24h
- If the decorator gets back a soft expired result, it should still call the datasource
- If the datasource returns an error, but a soft expired result exists, then the decorator should log a warning and return the soft expired result

There might be some cases where we should also replace a result of `null` but for now let's just stick with when the datasource throws.

**Comment by viceice** [comment]
no, updated idea.

@zharinov @JamieMagee Any idea how to pass the `etag` to the `callback` inside the `cache` decorator?

**Comment by JamieMagee** [comment]
You'd have to refactor out the `etag` and make it available from a parameter or static function call. Those are the only things accessible to a decorator.

**Comment by rarkins** [comment]
Let's set aside the performance improvement related to etag and just get the error fallback working with the decorator if possible
