### ISSUE TITLE
CodeCommit: filter PRs using ARN

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19426]
### Describe the proposed change(s).

If Renovate's ARN is obtainable, then filter PRs by that ARN to save requests and bandwidth.

**Comment by HonkingGoose** [comment]
AWS has deprecated the Codecommit platform. I added a notification to our Codecommit platform docs in this PR:

- #30479

We don't plan to work on new Codecommit features, so I'm closing this issue.
