### ISSUE TITLE
CodeCommit: support "close to ignore" for Pull Requests

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19427]
### What would you like Renovate to be able to do?

Support Renovate's (standard) "close to ignore" functionality for PRs

### If you have any ideas on how this should be implemented, please tell us here.

The only reason this is not supported today was for optimization reasons, because we didn't want one API GET per PR. However unfortunately AWS's API does not support any more efficient way to do it.

Therefore, for each closed pull request, fetch its details individually using CodeCommit's API.

Let's do this fetching by default, but also add a `RENOVATE_X_CODECOMMIT_SKIP_CLOSED_PRS` experimental flag in case any individual user needs to disable it if their repo gets too big.

BTW if we do this then it makes it even more important that we can filter PRs by ARN: #19426

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment]
AWS has deprecated the Codecommit platform. I added a notification to our Codecommit platform docs in this PR:

- #30479

We don't plan to work on new Codecommit features, so I'm closing this issue.
