### ISSUE TITLE
Clearing the Dependency Dashboard issue leaves Renovate in a broken state

### ISSUE THREAD

**Issue by aisamu** [renovatebot/renovate#19563]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

After erasing the whole contents of the Dependency Dashboard Github issue, Renovate was stuck in a non-working state.

<img width="667" alt="Screen Shot 2022-12-24 at 10 42 45" src="https://user-images.githubusercontent.com/431708/209438602-c5066e6a-add6-4b35-9513-6bd4d030b44a.png">

It kept trying to run unsuccessfully.

<img width="660" alt="Screen Shot 2022-12-24 at 10 39 32" src="https://user-images.githubusercontent.com/431708/209438551-6c9170e7-4f1e-4a2b-8b79-ed6dfcf87f3b.png">

This was not an attempt at opting out of Renovate, but the outcome of a faulty automated process.

I was able to trigger a re-run by copying the contents of a checked "Check this box to trigger a request for Renovate to run again on this repository" from a working repository.

Thanks for Renovate, and happy holidays! 🥳 

### Relevant debug logs

<details><summary>Logs</summary>

```
ERROR: Repository has unknown error
{
  "err": {
    "message": "Cannot read properties of null (reading 'matchAll')",
    "stack": "TypeError: Cannot read properties of null (reading 'matchAll')\n    at getCheckedBranches (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/dependency-dashboard.js:52:50)\n    at parseDashboardIssue (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/dependency-dashboard.js:59:39)\n    at readDashboardBody (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/dependency-dashboard.js:81:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async extractDependencies (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/index.js:54:5)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:46:56)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:260:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:454:5"
  }
}
```

</details>
<details><summary>Logs (another repo)</summary>
(Confirmed to be identical)

```
ERROR: Repository has unknown error
{
  "err": {
    "message": "Cannot read properties of null (reading 'matchAll')",
    "stack": "TypeError: Cannot read properties of null (reading 'matchAll')\n    at getCheckedBranches (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/dependency-dashboard.js:52:50)\n    at parseDashboardIssue (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/dependency-dashboard.js:59:39)\n    at readDashboardBody (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/dependency-dashboard.js:81:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async extractDependencies (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/index.js:54:5)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:46:56)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:260:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:454:5"
  }
}
```
</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by RahulGautamSingh** [comment]
@rarkins what should our response be, when user edits the dependency dashboard. 

Rewrite or leave it as-is.

**Comment by rarkins** [comment]
We should do our best to parse it, and then rewrite it no matter what
