### ISSUE TITLE
Preserve platform automerge when rebasing the PR

### ISSUE THREAD

**Issue by ryancausey** [renovatebot/renovate#19566]
### What would you like Renovate to be able to do?

I am using the GitLab platform and noticed that the `platformAutomerge` feature is not preserving the automerge setting when Renovate decides it has to rebase the branch. A manual retry of the PR by checking the retry box in the dependency dashboard or the PR description does re-enable automerge as expected.

I would like to see the automatic rebasing Renovate does preserve the automerge setting as per the `packageRules`. However, in the discussion this was cloned from, a good point was raised about preventing Renovate from fighting a human that may have manually cancelled the automerge.

### If you have any ideas on how this should be implemented, please tell us here.

I have this idea for the GitLab platform. I do not know much about the GitHub API.

In the GraphQL API reference is it possible to query for the status of the merge request:

https://docs.gitlab.com/ee/api/graphql/reference/#querymergerequest

In order to preserve the automerge status but not fight a human who manually cancelled, Renovate bot could:

1. after rebasing, check if any of the `packageRules` allow for the PR to be automerged.
2. If they do, check the user that cancelled the automerge by following the Notes edges to find the most recent Note that indicates which user last aborted the automerge:
    * ![image](https://user-images.githubusercontent.com/2704075/209450915-30a3eaaa-f4f8-4f28-8e93-4cdeeb9e2375.png)
    * https://docs.gitlab.com/ee/api/graphql/reference/#note
3. If the user was not the bot user, then don't re-enable automerge. Otherwise, re-enable automerge.

Another potential implementation:

1. before rebasing and doing any operations to the PR, check if automerge is still enabled on the PR.
2. if it is, re-enable automerge after completing rebasing and git operations.
    * NOTE: if using git instead of the API to update the commit on GitLab, I have found from experience that it takes a few seconds before the PR processes the git update and re-enabling automerge will work as expected. To be safe I would wait 10 seconds or poll for the PR's HEAD SHA to change. Otherwise, the automerge may be re-enabled before the commit is processed, causing it to be disabled once the commit is processed.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by ryancausey** [comment]
This was created from #19504.

**Comment by rarkins** [comment]
Rebasing is done using git. We do check for an existing PR prior to that step (Eg to see if it's been closed) so we augment that functionality if automerge=true and platformAutomerge=true

**Comment by ryancausey** [comment]
> Rebasing is done using git. We do check for an existing PR prior to that step (Eg to see if it's been closed) so we augment that functionality if automerge=true and platformAutomerge=true

@rarkins I believe there was some concern about not wanting to fight a human if they've gone in and manually cancelled the automerge in the discussion that spawned this issue. Is that correct or did I misunderstand?

I ask because I think I'm looking for something more aggressive than this proposal, though the functionality in your comment could be a good first start. I've noticed that if a human pushes another change to the main branch, that can cause renovate MRs with automerge set to get automerge removed if a fast forward merge is configured to be required. I would personally like renovate bot to re-enable automerge when rebasing in this case _unless I had specifically removed it within the MR itself_. I do not know if this granularity about how the automerge was disabled is possible to retrieve from the GitLab API or the GitHub API. Maybe the alternative here would be for your proposal to be the default and then have an extra "be aggressive about automerging" flag or something along those lines. What do you think?

**Comment by rarkins** [comment]
I think we should re-enable platform automerge on each rebase unless a user had disabled it

**Comment by ryancausey** [comment]
What I was trying to say was that answering the "unless a user has disabled it" question may be complicated. GitLab at least has certain scenarios where it will disable automerge when someone pushes a change to the target branch. I want to be able to configure renovate to re-enable automerge in this scenario after it rebases the dependency update branch.

I'm not entirely certain how to distinguish that kind of automatic disabling of automerge from someone clicking the button in the merge request UI to turn automerge off.

**Comment by rarkins** [comment]
Can't we just check "is automerge still enabled?"

**Comment by ryancausey** [comment]
It wouldn't work for the use case I'm trying to use it for. Since the projects I have are set to require a fast forward merge, any time a change is pushed to the main branch the automerge is disabled on the MR automatically by the platform logic. I am hoping in these cases for renovate bot to rebase the MR (which it does today) and re-enable the automatic merge (which it does not today).

Maybe it is worth to solve for the "is automerge still enabled?" case while including a "no really, force re-enable automerge please" option.

**Comment by rarkins** [comment]
What if we check for "is automerge still enabled?" before we do any push?

**Comment by ryancausey** [comment]
I don't think that will work for my use case as if another human or even another renovate dependency MR merges to the main branch, all the other MRs targeting that branch will have their automatic merges disabled due to requiring to be rebased.

**Comment by rarkins** [comment]
So then a new config option called something like platformAutomergeReenable which defaults to "never" and also supports "unless-disabled" and "always" options?

Alternatively we could refactor platformAutomerge itself to be an enum like this (none, conservative, aggressive, pragmatic)

**Comment by ryancausey** [comment]
Yes I think that either would be the right approach and would solve for what I want without having to write a bunch of platform specific code to try and decode who actually removed the automerge in every scenario.

**Comment by ryancausey** [comment]
@rarkins it looks like this has been fixed, as I'm seeing my MRs merge automatically after rebasing by Renovate. I'm going to close this issue. Feel free to reopen if you believe it is not resolved.
