### ISSUE TITLE
Rename `crate` datasource to `crates-io`

### ISSUE THREAD

**Issue by Turbo87** [renovatebot/renovate#19621]
### What would you like Renovate to be able to do?

The official name of the Rust package registry is "crates.io", however the renovatebot datasource is currently just called `crate`. While that name is close, it would probably be best to use e.g. `crates-io` instead and have `crate` as an alias for backward compatibility.

### If you have any ideas on how this should be implemented, please tell us here.

I've found https://github.com/renovatebot/renovate/issues/14755, which also talks about renaming another datasource, but I didn't see any hints there on how this could be implemented or if a renaming like that had already happened in the past that could be looked at.

I'm open to implementing it myself though, but I would need a few pointers on how this could be done.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
This datasource is meant to include not only crates.io but also self hosted. So I still think "crate" works best

**Comment by Turbo87** [comment]
hmm, seems a bit confusing to me but okay 😅
