### ISSUE TITLE
Add support for the Azure DevOps Marketplace tasks

### ISSUE THREAD

**Issue by jessehouwing** [renovatebot/renovate#19694]
### What would you like Renovate to be able to do?

Currently Renovate only updates the built-in tasks supplied by Microsoft and ignores any task that's installed through the Azure DevOps Marketplace.

Renovate should also suggest updates for any public marketplace installed tasks.

### If you have any ideas on how this should be implemented, please tell us here.

* https://github.com/renovatebot/renovate/pull/19692

### Is this a feature you are interested in implementing yourself?

Yes

@JamieMagee To transfer the repo to generate the static file I can initiate a repository transfer:

 * [x] Transfer `https://github.com/jessehouwing/renovate-azure-devops-marketplace/` to `github.com/renovatebot/azure-devops-marketplace/`
 * [x] https://github.com/renovatebot/renovate/pull/19764
 * [x] Set a PAT in the Actions Secret
 * [x] Change the commit details in the repository scripts
 * [x] Add me as contributor

**Comment by jessehouwing** [comment]
Technically, Renovate should also be able to hit the 

```
/_apis/distributedtask/tasks
```

of every `dev.azure.com` instance using an authenticated token to fetch all latest versions of installed tasks in the instance. 

I've used that in one of my other projects:
https://github.com/jessehouwing/azure-pipelines-tasks-zips/blob/main/download.ps1

But the pull request follows the same principle currently used for built-in tasks and was the simplest solution for now that doesn't require any configuration changes or instance access (with the required additional permissions).

**Comment by jessehouwing** [comment]
@JamieMagee 

Want to continue here or in a new issue?

**Comment by jessehouwing** [comment]
@geekzter FYI

**Comment by JamieMagee** [comment]
We can use this issue to track migrating the repo. This is fine.

**Comment by JamieMagee** [comment]
@jessehouwing it looks like the order might not be consistent. See #19720

**Comment by jessehouwing** [comment]
@JamieMagee I had already updated the script to keep order. But the json file in the initial pull-request is from before that update, so we'll have to do at least one big diff commit to fix that in the renovate repo.

I'm seeing one more interesting thing happen in the update from today, and that's from 2 extension that have the same display name (current sort order) (and one should never have been a public extension to begin with it seems) which seem to flip-flop in the data file *sigh*.

I can see if I can simply order the file alphabetically upon save.

**Comment by jessehouwing** [comment]
Updated the scripts to sort the json properties alphabetically before save. So it should now be in consistent order.

**Comment by jessehouwing** [comment]
Some things I'd love to (see) add(ed), but would be more work:

 * [ ] Add support for the `preview` flag (task.json)
 * [ ] Add support for the `deprecated` flag (task.json)
 * [ ] Add support for the `repository` attribute in the extension.json (task.json)
 * [ ] Add support for marking a whole extension deprecated (no longer returned by the marketplace API)

These require a change in the datasource structure and I'd need to better understand how renovatebot does that.

Potentially add support for querying the Azure DevOps Organization directly to also support private tasks:

 * [ ] Query all tasks installed in an organization to get the task `name's and `id`s (`https://dev.azure.com/jessehouwing/_apis/distributedtask/tasks/`)
 * [ ] Query each task by `id` to get a list of versions (`https://dev.azure.com/jessehouwing/_apis/distributedtask/tasks/{{task.Id}}?allversions=true`
 * [ ] Support the full-name syntax (`contributionIdentifier` prefix)
 * [ ] Fetch the extention manifest from the marketplace API (`https://extmgmt.dev.azure.com/jessehouwing/_apis/extensionmanagement/installedextensionsbyname/jessehouwing/jessehouwing-vsts-variable-tasks?api-version=7.1-preview.1&assetTypes=Microsoft.VisualStudio.Services.Manifest`)
 * [ ] Grab the repository data (`repository.uri`) from the fetched manifest file (`https://jessehouwing.gallerycdn.vsassets.io/extensions/jessehouwing/jessehouwing-vsts-variable-tasks/3.0.10/1670319234705/Microsoft.VisualStudio.Services.Manifest`)

**Comment by jessehouwing** [comment]
To transfer the repo to generate the static file I can initiate a repository transfer:

 * [ ] Transfer `https://github.com/jessehouwing/renovate-azure-devops-marketplace/` to `github.com/renovatebot/renovate-azure-devops-marketplace/`
 * [ ] Update the update task in the `renovatebot` repo to point to the new location
 * [ ] Set a PAT in the Actions Secret
 * [ ] Change the commit details in the repository scripts
 * [ ] Potentially keep me around as contributor?

**Comment by jessehouwing** [comment]
Related: #19725

**Comment by jessehouwing** [comment]
Related: https://github.com/renovatebot/renovate/pulls

**Comment by jessehouwing** [comment]
* Related: https://github.com/renovatebot/renovate/issues/15818

**Comment by JamieMagee** [comment]
> @JamieMagee To transfer the repo to generate the static file I can initiate a repository transfer:

I received your invitation, but I don't have the necessary permissions in the renovatebot org. You'll need to invite @rarkins to do the repo transfer.

**Comment by rarkins** [comment]
Because it's a personal repo, I think you'll actually need to transfer it to me (`@rarkins`) before I can then transfer it into the `renovatebot` org

**Comment by jessehouwing** [comment]
Request made @rarkins

**Comment by jessehouwing** [comment]
@JamieMagee @rarkins can you overwrite the AZURE DEVOPS PAT secret with a fresh PAT (expires yearly) with 'Marketplace (read)' permissions on the 'all accessible organisations' scope?

**Comment by JamieMagee** [comment]
@rarkins I don't have permissions. You'll need to do it.

**Comment by rarkins** [comment]
I've updated it with my own PAT now. What's the best way to make sure it's working?

**Comment by jessehouwing** [comment]
Running the workflow manually. I just triggered a run.

**Comment by jessehouwing** [comment]
PAT is working. I increased the logging a little bit to be sure :).

A new run is both fetching new extensions and downloading the vsix files.

@rarkins To what should I change the committer? Right now it's still making all commits (including bot) under my name. Should it be `Renovate(bot)`? Or is it ok to leave it under my creds for now?

**Comment by rarkins** [comment]
I'm not sure it makes any difference? If not then fine to leave as is until it's necessary to change
