### ISSUE TITLE
Resolution of non-existing groups in GitLab is too slow

### ISSUE THREAD

**Issue by z0rc** [renovatebot/renovate#19743]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest from https://gitlab.com/renovate-bot/renovate-runner

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.6.2-ee

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

In my self-hosted gitlab instance, there is a number of repos that has errors in CODEOWNERS, mainly referencing non-existing groups (reorg happened recently, it takes time to update the repos).

Before https://github.com/renovatebot/renovate/pull/19469, processing of this kind of repos took the same amount of time like others. But with release of renovate `34.82.1` it started too take way more time.

Before:
```
 INFO: Repository finished (repository=backend/call-service)
       "cloned": false,
       "durationMs": 13476
```

After:
```
 INFO: Repository finished (repository=backend/call-service)
       "cloned": false,
       "durationMs": 1108188
```

I noticed this after renovate job started timing out. Before change it took 20 minutes to process all repos in gitlab instance, but now 2 hours (job timeout) aren't enough to complete renovate run.

CC @justinas-b 

I don't know how to provide a minimum reproduction. This is self-hosted gitlab with private groups.

### Relevant debug logs

<details><summary>Logs</summary>

Before:
```
 INFO: Repository started (repository=backend/call-service)
       "renovateVersion": "34.82.0"
 INFO: Dependency extraction complete (repository=backend/call-service, baseBranch=master)
       "stats": {
         "managers": {
           "docker-compose": {"fileCount": 1, "depCount": 1},
           "dockerfile": {"fileCount": 2, "depCount": 2},
           "gitlabci": {"fileCount": 1, "depCount": 8},
           "gitlabci-include": {"fileCount": 1, "depCount": 1},
           "helm-values": {"fileCount": 1, "depCount": 1},
           "helmfile": {"fileCount": 1, "depCount": 1},
           "poetry": {"fileCount": 1, "depCount": 27}
         },
         "total": {"fileCount": 8, "depCount": 41}
       }
 INFO: Repository finished (repository=backend/call-service)
       "cloned": false,
       "durationMs": 13476
```

After:
```
 INFO: Repository started (repository=backend/call-service)
       "renovateVersion": "34.82.1"
 INFO: Dependency extraction complete (repository=backend/call-service, baseBranch=master)
       "stats": {
         "managers": {
           "docker-compose": {"fileCount": 1, "depCount": 1},
           "dockerfile": {"fileCount": 2, "depCount": 2},
           "gitlabci": {"fileCount": 1, "depCount": 8},
           "gitlabci-include": {"fileCount": 1, "depCount": 1},
           "helm-values": {"fileCount": 1, "depCount": 1},
           "helmfile": {"fileCount": 1, "depCount": 1},
           "poetry": {"fileCount": 1, "depCount": 27}
         },
         "total": {"fileCount": 8, "depCount": 41}
       }
 INFO: Repository finished (repository=backend/call-service)
       "cloned": false,
       "durationMs": 1108188
```
</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Please enable debug logs so we can see how many timeouts you have and how long they take

**Comment by z0rc** [comment]
Thanks, using debug log I noticed additional problem with my old projects using unavailable local registry, which was suchdown around there same time as renovate 34.82.1 release. Default hostRules use timeout of 60 seconds, which is what actually takes most of time from repo processing.

Not posting full logs as there is too many sensitive metadata. Edited extract from logs:
```
       "hostStats": {
         "api.github.com": {"requestCount": 8, "requestAvgMs": 228, "queueAvgMs": 0},
         "gitlab.example.com": {"requestCount": 14, "requestAvgMs": 629, "queueAvgMs": 0},
         "unavailable.registry.example.com": {
           "requestCount": 27,
           "requestAvgMs": 60042,
           "queueAvgMs": 0
         },
         "pypi.org": {"requestCount": 8, "requestAvgMs": 103, "queueAvgMs": 0}
       },
```

I'm thinking of adding hostRules for this registry, to lower timeout value for it. Ideally I'd like to configure renovate to completely ignore/skip this registry, but I cannot find such option.

**Comment by viceice** [comment]
use hostrules and set that host to disable

**Comment by z0rc** [comment]
I added to `config.js`:
```js
hostRules: [
  {
    matchHost: 'unavailable.registry.example.com',
    enabled: false,
  },
]
```

That fixed log renovate runs for me. It skips unavailable host now and completes within expected margins. Thanks for the hints.
