### ISSUE TITLE
Set non-zero defaults for prHourlyLimit and prConcurrentLimit

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19781]
### What would you like Renovate to be able to do?

Have low default values for these limit fields to reduce the chances of people blowing their foot off with new Renovate installations where they're not using `config:base`

### If you have any ideas on how this should be implemented, please tell us here.

prHourlyLimit=2
prConcurrentLimit=10

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment]
what about branch concurrent limit?

**Comment by rarkins** [comment]
IIRC it defaults to prConcurrentLimit if non-configured so therefore doesn't need a default

**Comment by HonkingGoose** [comment]
## Hard-coding default settings from `config:base` preset

> prHourlyLimit=2
> prConcurrentLimit=10

So you're hard-coding the default settings from our `config:base` preset:

```json5
{
  "extends": [
    ":dependencyDashboard",
    ":semanticPrefixFixDepsChoreOthers",
    ":ignoreModulesAndTests",
    ":autodetectPinVersions",
    ":prHourlyLimit2", <-- This one
    ":prConcurrentLimit10", <--- And this one
    "group:monorepos",
    "group:recommended",
    "workarounds:all"
  ]
}
```

Sounds good to me! 😄

## Related issue

- #18939

**Comment by viceice** [comment]
ok, sounds good

**Comment by rarkins** [comment]
Closed by https://github.com/renovatebot/renovate/commit/a75f9d71c11bc4105cc71266554998894ef12519
