### ISSUE TITLE
feature request: rewrite URLs in Link response headers

### ISSUE THREAD

**Issue by dsilvasc** [renovatebot/renovate#19817]
### What would you like Renovate to be able to do?

When Renovate calls GitHub Enterprise behind a proxy and it calls a paginated API, the response includes a Link header (for the following page) with a URL starting with a prefix different than the config value from RENOVATE_ENDPOINT.

For example, suppose GHE is hosted on ghe.your-company.com but Renovate calls it via a proxy at an internal domain like ghe-proxy.company-internal.  This is usually done so that employees access GHE with an SSO mechanism and scripts/bots/services access GHE with internal service-to-service auth.  The call to the proxy might also be over HTTP instead of HTTPS if the company is letting a service mesh sidecar (like Envoy or Linkerd) intercept service-to-service traffic and inject auth headers.

In this case, Renovate calls `http://ghe-proxy.company-internal/api/v3/repos/SomeOrg/some-repo/pulls` and gets back a Link header with `https://ghe.your-company.com/api/v3/repositories/12345/pulls?page=2`.

Here's where Renovate follows the Link header:
https://github.com/renovatebot/renovate/blob/d869c946d164965393f1259db5171e2a0303fb27/lib/util/http/github.ts#L308-L326

Would it be possible to provide a config option to rewrite a prefix on these links (in the example above, `https://ghe.your-company.com/api/v3/`) to the value of RENOVATE_ENDPOINT?

### If you have any ideas on how this should be implemented, please tell us here.

Maybe a string config option like `rewriteLinkPrefix`, which in the example above would be `"https://ghe.your-company.com/api/v3/"`.

### Is this a feature you are interested in implementing yourself?

Possibly.

**Comment by viceice** [comment]
you should better correctly configure the for load balancer usage[^1]

[^1]: https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-network-settings/using-github-enterprise-server-with-a-load-balancer

**Comment by dsilvasc** [comment]
Thanks for the link.  While the GHE load balancer config helps GHE determine the original client's IP address (passed by the load balancer either through the proxy protocol or the x-forwarded-for header), it doesn't help a client reach GHE through an alternative hostname.

GHE has a single configured hostname, and that's what it seems to use in the absolute URLs it includes in Link response headers:
https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-network-settings/configuring-a-hostname
https://docs.github.com/en/enterprise-server@3.4/rest/guides/using-pagination-in-the-rest-api

**Comment by dsilvasc** [comment]
Renovate already uses the base URL when parsing values in the Link header:

https://github.com/renovatebot/renovate/blob/d869c946d164965393f1259db5171e2a0303fb27/lib/util/http/github.ts#L320

If renovate's github.ts first turned `linkHeader.next.url` into a root-relative url then that would effectively allow renovate to talk to GHE from a domain different than the default one configured in https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-network-settings/configuring-a-hostname

**Comment by rarkins** [comment]
If you're interested in contributing this feature, and could start by gating it behind a `RENOVATE_X_` experimental flag, we'd probably accept it.
