### ISSUE TITLE
Support go mod tidy -e Option

### ISSUE THREAD

**Issue by jcburley** [renovatebot/renovate#19816]
### What would you like Renovate to be able to do?

We are considering enabling the **postConfiguration** option **gomodTidy**, so we don't have to keep fixing broken PRs due to bad **go.sum** files.

But many of our repos are incomplete in source-repo form, so in fact we run `go mod tidy -e` so the **go.mod** and **go.sum** files are updated even in the presence of errors (of the sort that don't prevent some degree of tidying, which is what we care about).

Would it be possible to support an option to enable that?

### If you have any ideas on how this should be implemented, please tell us here.

I'm not sure what the new option should be called; maybe **goModTidyProceed**, based on the help text?

> The -e flag causes tidy to attempt to proceed despite errors encountered while loading packages.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by jcburley** [comment]
Another possibility is to add a checkbox for `-e`, to be applied to any of the `go mod tidy` options.

Along those lines, another checkbox for `-compat=whatever` might be worthwhile.

**Comment by rarkins** [comment]
What do you mean by checkbox? Checkboxes in a PR which you then expect Renovate to read and apply on a subsequent run?

**Comment by jcburley** [comment]
No, I'm referring to the configuration page. And the config file would support the corresponding settings. If that makes sense (as I'm only a user of Renovate, with no Admin access to configure it, at work).

On January 18, 2023 1:45:01 PM EST, Rhys Arkins ***@***.***> wrote:
>What do you mean by checkbox? Checkboxes in a PR which you then expect Renovate to read and apply on a subsequent run?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/renovatebot/renovate/issues/19816#issuecomment-1387563244
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
James Craig Burley, Software Architect

**Comment by rarkins** [comment]
I think we could call the new option `goModTidyE`

**Comment by jcburley** [comment]
> I think we could call the new option `goModTidyE`

Sounds good to me!

**Comment by jcburley** [comment]
@rarkins – in the meantime, is it feasible for us (as a non-self-hosted Renovate user) to create a preset that adds the `-e` option and switch over to that? I don't know Renovate configs (nor JSON, really) all that well, so while it seems flexible enough to accommodate such a thing, I hesitate to dive in and try it without some expectation of success.

**Comment by rarkins** [comment]
No it's not possible

**Comment by BirknerAlex** [comment]
Hey 👋🏻 

I would love to see this feature too as well. We are also having auto-generated code in our go projects which isn't included in the git repository at all (proto files). The golang proto files are being build from our Gitlab pipeline and added as "job artifacts" before building the binaries. 

So there would be 2 different ways of adressing that:

- adding a way for renovate to download/inject additional files after git clone
- execute `go mod tidy -e` and ignoring the "cannot find module providing package" errors

**Comment by rarkins** [comment]
The solution has already been decided, so there's no need for any essays or pleas. Someone needs to contribute a PR adding a new `postUpdateOptions` value `goModTidyE`, and you could model it directly on `goModTidy1.17`: https://github.com/renovatebot/renovate/blob/44469afc0edf3e94eeced521691f2aae9bee50c2/lib/config/options/index.ts#L1981

**Comment by jcburley** [comment]
@rarkins @viceice @BirknerAlex – thanks for implementing this so quickly!

I'm trying it out on one of our private repos (we are not self-hosted, btw), and while I can see, in the Renovate logs, that the `-e` option is now always provided to `go mod tidy`, the end result is the same: the PR, to update a package version, still has only the `go.mod` change, without a `go.sum` change.

I expected `go.sum` changes to be added to the PR, which was created (by Renovate) two weeks ago.

Are my expectations correct? The config (for just this one repo) appears to be working, per the Renovate logs, but here it is in case something is wrong with it:

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>namely/renovate-config"
  ],
  "postUpdateOptions": [
    "gomodTidyE"
  ]
}
```

Note that our org's `default.json` makes no reference to any `gomodTidy*` configs, but does specify `gomod` as one of the `enabledManagers`.

It might be the case that this PR needs to be recreated from scratch, though.

Please advise.

Again, thanks!

**Comment by rarkins** [comment]
@jcburley please raise a discussion instead, and include debug logs

**Comment by jcburley** [comment]
> @jcburley please raise a discussion instead, and include debug logs

https://github.com/renovatebot/renovate/discussions/20457
