### ISSUE TITLE
Update GitHub actions runner automatically

### ISSUE THREAD

**Issue by TWiStErRob** [renovatebot/renovate#19827]
### What would you like Renovate to be able to do?

GitHub has been bumping [Ubuntu](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) and [Mac](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/) runners recently. It would be nice if in these cases we get Renovate PRs, manually looking for these in every single repo is time consuming and error prone.

I can't think of a better way of explaining it than with a visual diff:
```diff
jobs:
  job-name:
    name: My Job
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
```

### If you have any ideas on how this should be implemented, please tell us here.

The [documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) is one source data. and [this section](https://github.com/actions/runner-images#available-images) is the source of truth, I think, sadly, this is still just a `README.md`.

They communicate changes in [Announcements](https://github.com/actions/runner-images/issues?q=is%3Aissue+is%3Aopen+label%3AAnnouncement), and [blog posts](https://github.blog/changelog/label/actions/).

This doesn't bode well for a data source, as I personally couldn't find a public resource where the versions are cleanly available, but I noticed you have [static data](https://github.com/renovatebot/renovate/blob/main/data/ubuntu-distro-info.json) (for these cases?) which is pretty close to what would be necessary. I'm sure that the community will be happy to provide updates whenever runners move ahead a version (i.e. e.g. `ubuntu-latest` changes meaning), which should be once every 1-4 years as far as I can see.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
I think this could possibly be a static and community-driven (through PRs) datasource if it doesn't change often.

**Comment by TWiStErRob** [comment]
I don't think it does, it's a lot of work from GitHub to deprecate and bump a major OS version, and it usually involves a lot of implicit installed software bumps too.

**Comment by rarkins** [comment]
Let's try!

**Comment by TWiStErRob** [comment]
Is there a similar PR/feature that can be copied to do this?

**Comment by rarkins** [comment]
I don't think we have any statically defined datasources today so pick the simplest one you find and then add in static results

**Comment by TWiStErRob** [comment]
Huh I thought those in the [data directory](https://github.com/renovatebot/renovate/blob/main/data) are. [gradle-version](https://github.com/renovatebot/renovate/tree/main/lib/modules/datasource/gradle-version) looks like a simple one, remote JSON could be replaced with local JSON, but I don't have time right now.

Up for grabs if anyone is interested.

**Comment by jessehouwing** [comment]
All images are defined in this repo:
https://github.com/actions/runner-images/tree/main/images

Each image has a json or pck.hcl file describing it.

The versions could be extracted similarly as the azure-devops built-in tasks by walking through the history of that repo.

**Comment by TWiStErRob** [comment]
@jessehouwing I can see the images, but there's no indication of version / runner name. There must be an additional mapping somewhere that maps from `ubuntu-20.04` to `images/linux/ubuntu2004`.

**Comment by jessehouwing** [comment]
I've pinged someone on the actions and the Azure pipelines team.

I found an internal API in Azure Pipelines, not yet for GitHub Actions.
Both platforms use the same infrastructure.

But having a static list could also cause issues, since the new images
don't roll out to all users at the same time.

**Comment by TWiStErRob** [comment]
Why would a static list cause issues? These are all major versions we're talking about. It could be updated as soon as the last rollout finishes for latest they're on 100%), or as soon as a new runner is introduced. The "newest" version doesn't have to follow "latest", for that people can define "latest" in their yaml. If they use a specific version e.g. ubuntu-22.04, then if GitHub releases ubuntu-24.04 (and static data is updated to reflect that), a PR would be raised. From there it's the maintainer's decision to merge or close it. This would actually help GitHub with adoption and latest could jump faster because of it.

**Comment by jessehouwing** [comment]
It's just that I've read the comments on the existing Azure DevOps functionality, how people feel the suggested versions should be accurate and available to them. The ring-based deployments can easily mean 6 to 12 weeks between first availability in Brazil and final availability in New Zealand.

Given that both Azure Pipelines and GitHub actions use the same incremental rollout (and the same runner infrastructure in general), versions may not be available to all accounts and organizations at the same time.

Plus there's the difference between GitHub Enterprise Server, Cloud and Public and GitHub AE which are all on slightly delayed cadences.

Plus, if the GitHub org itself has an API that provides an exact list available to the account, that would provide exact options, even if, say entreprise policy, disabled certain runners. Why not use that?

**Comment by TWiStErRob** [comment]
So what is a solution to all this? Because I don't think not implementing is an option, just because it doesn't apply to everyone. I would guess the majority of the intersection of Renovate and GitHub Actions is a user on Public GH with GH hosted runners. When GH says in their docs that a runner is available, it better well be :) and that would easily cover "versions should be accurate and available to them".

> easily mean 6 to 12 weeks between first availability in Brazil and final availability in New Zealand.

If GH says the runner is available, won't it be falling back to regions that are already ready?

> if the GitHub org itself has an API that provides an exact list available to the account Why not use that?

I'm all for it, but as far as I understand this is not yet available (maybe not even planned?), so it's a future problem and an implementation detail of the data source.

> there's the difference between GitHub Enterprise Server, Cloud and Public and GitHub AE which are all on slightly delayed cadences.

That can be solved with more configuration, right? For example allowing to override the current latest version from renovate.json so that they can release in their internal company GHs whenever it's available to them?

**Comment by rarkins** [comment]
If we know release timestamps, and release delay is somewhat predictable, we could perhaps use stabilityDays for users to control how long they wait (e.g. could be 30, 60, 90 days)

**Comment by jessehouwing** [comment]
I'm all for adding this feature. From my azure DevOps experience with Renovate, just make sure the docs explain these possible issues and how to configure for them, maybe it's clear to existing Renovate users, but I had a rough time getting the config right in the way most people use the platform.

**Comment by HonkingGoose** [comment]
### Let's start the static way

I like the idea to update the GitHub Actions runner automatically. I'd say let's get started the "dumb way":

1. Create a file that has the schedule(s)
1. Update the schedule file manually when a new major version of the GitHub Action runners releases
1. Use `stabilityDays` to delay the change to Renovate bot users
1. Once we find an official API -> use the API

Having the dumb way feature helps us learn in practice if the feature works as expected, and find possible bugs in our thinking. 😄 

### Docs

> From my azure DevOps experience with Renovate, just make sure the docs explain these possible issues and how to configure for them, maybe it's clear to existing Renovate users, but I had a rough time getting the config right in the way most people use the platform.

@jessehouwing I'd like to know more about your problems with getting started with Renovate bot. Your experiences can help me to see what things we should fix in the docs. Can you create a new discussion and ping me in it, and tell me about your problems? 😉

**Comment by dudicoco** [comment]
Hi guys, is this feature going to be implemented?

**Comment by viceice** [comment]
> Hi guys, is this feature going to be implemented?

see labels, needs community contribution

**Comment by PeterNitsche** [comment]
Hey, I am working on a PR for this issue. Can you assign it to me? 

Unlike the currently proposed solution, I suggest to only add runner versions to the static datasource, if they are announced as stable for everyone and leaving beta state.

**Comment by PeterNitsche** [comment]
@HonkingGoose I have created a draft PR. Are you fine with not using schedule information and `stabilityDays` as you originally proposed in this comment? https://github.com/renovatebot/renovate/issues/19827#issuecomment-1386728505

**Comment by HonkingGoose** [comment]
@PeterNitsche I'm fine with starting with "if runner is announced available through official GitHub channels, then add it to the list, and let Renovate propose the update", to start us with this feature.
