### ISSUE TITLE
Renovate Closes Other Merge Requests with same branchPrefix

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/renovate#1982]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate closing MR's it did not open

**To Reproduce**
Create MR with prefix the renovatebot looks for

**Expected behavior**
Renovate doesn't touch a MR it hasn't created / committed too.

**Comment by rarkins** [comment]
This is deliberate behaviour for now - we look for every branch with our branch prefix and delete any that shouldn't be there. In general it's a bad idea to create MRs in the same namespace as Renovate uses as it assumes it can use the entire `branchPrefix` namespace and you could get conflicts if not careful.

There's also one special case that can't be avoided - if your `branchPrefix` is `renovate/` then if you create a branch called `renovate` then it will block us from creating any branch `renovate/*`.

We can probably loosen this though - e.g. raise a config error if the exact `branchPrefix` branch exists, and search only for PRs created by the same user account when deciding what to autoclose. I would not reject a PR to this repo if you wanted to. But as a general rule - do not create branches/MRs in Renovate's namespace.

**Comment by adam-moss** [comment]
Thanks, will work up an MR.

**Comment by rarkins** [comment]
There have been some changes to our pruning - for example to skip autoclosing the PR if it's modified. But it's possible that a `renovate/*` branch by another user which has *no* PR might still get deleted by Renovate. We could check for the author of the branch before deleting, if we don't already.
