### ISSUE TITLE
Replace `as` with `satisfies` keyword

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#19856]
### Describe the proposed change(s).

Typescript recently got a new keyword [satisfies](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator). In a recent discussion on the Slack channel it was agreed upon to replace `as` with `satisfies` 

There some detailed info this [issue](https://github.com/microsoft/TypeScript/issues/47920).

**I am not sure if all instances of `as` need to be repalced. If they can be good, else I will list the reasons as I find them and 
this issue will be used to track all related updates/changes on that topic.**

**Comment by RahulGautamSingh** [comment]
Do you think this is correct?

https://github.com/renovatebot/renovate/blob/b309f2cbc4e5d50804311b7a9ad6e832f42772a4/lib/config-validator.ts#L97-L99

Or should it be like this since `satisfies` is not an option here as we want to assert the type.
```ts
 try {
      const pkgJson: PackageJson = JSON.parse(
        await readFile('package.json', 'utf8')
      );
```

**Comment by RahulGautamSingh** [comment]
https://github.com/renovatebot/renovate/blob/3a58d239ec7467b8b720798a6b2f5d5a74f8fb3c/lib/modules/manager/cocoapods/artifacts.spec.ts#L115-L117

There are many tests where such assertions are used. Will it be desirable to instead initialize a minimal mockObject that has all non-optional properties and use that instead:
```ts
const statusResult:StatusResult = { ...haveAllStrictFields }

..

git.getRepoStatus.mockResolvedValueOnce(statusResult);
git.getRepoStatus.mockResolvedValueOnce({ ...statusResult, modified:['somefile']});
```

**Comment by viceice** [comment]
we should probably use our partial helper function there.

**Comment by HonkingGoose** [comment]
Do we need to update our developer best practice documentation [^docs] to tell contributors/maintainers to use `satisfies` instead of `as` keyword? 

[^docs]: https://github.com/renovatebot/renovate/blob/main/docs/development/best-practices.md

**Comment by viceice** [comment]
yes please

**Comment by rarkins** [comment]
@RahulGautamSingh much work left here?
