### ISSUE TITLE
Fallback range strategies

### ISSUE THREAD

**Issue by WyriHaximus** [renovatebot/renovate#19866]
### What would you like Renovate to be able to do?

Coming from Dependabot Renovate gives an impressive amount of additional features. My initial experience with Renovate was a bit spotty but that is being resolved through #18715. The thing I would love Renovate to be able to do is allow to pass in an array of range strategies into `rangeStrategy` rather than having to pick one. 

To paint a situation and how Renovate would deal with that:
rangeStrategy is set to the default `replace`
Language: PHP
PHP version targeting: `^8 || ^7.4`
Package `vendor/a` is currently installed at version `v1` targetted with `^1` with has the following PHP versioning constraints: `^8 || ^7.4`

Then a `vendor/a` v2 is released with the following PHP versioning constraints: `^8.1`.
Currently Renovate will replace the targeting from `^1` to `^2`.

However, what I really want Renovate to do is to update the lockfile and widen if a new major version comes out that supports my targeting ranges. So I can currently either change it to either `widen` or `update-lockfile`. However `update-lockfile` fallback to `replace`, which is the one I'm avoiding.

### If you have any ideas on how this should be implemented, please tell us here.

While reading through the code I realized that having an array of possible strategies to try is a massively complex thing to implement in one manager, not even to mention all of them. So I came to the conclusion that the simplest way to get some of it is to provide a `rangeStrategyFallback` option or to turn `rangeStrategy` into an update with two arguments or whatever the maintainers deem best. Where you can specify the fallback which is then injected in calls like this: https://github.com/renovatebot/renovate/blob/8bd77f747b3da59cc955b2fc4ba3301bcb680ea2/lib/modules/versioning/composer/index.ts#L176

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
Hi, I understand better what you're after now, and it deserves a separate issue to #18715. However, I would like to combine it together with #19802 because it's essentially the same thing.

**Comment by WyriHaximus** [comment]
Amazing thank you, and to be fair I needed that stroll to the code to understand how it exactly works. Subscribed to https://github.com/renovatebot/renovate/issues/19802's progress :+1:
