### ISSUE TITLE
PR opened for pre-release version that's older than currently installed

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#1988]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Renovate opened a PR to update [verdaccio](https://github.com/verdaccio/verdaccio) from `v3.0.0-beta.10` to `v3.0.0-test.1` - however the existing version we're using is actually the newest available, not `v3.0.0-test.1`. See:
https://github.com/mozilla-neutrino/neutrino-dev/pull/879

**To Reproduce**

1. `yarn add verdaccio@3.0.0-beta.10`
2. Push `package.json` and `yarn.lock` change to repo
3. Wait to see if Renovate opens a PR

**Expected behavior**
No PR from Renovate for `verdaccio`, since it's up to date on the latest pre-release version.

Neither `yarn outdated` nor https://david-dm.org/mozilla-neutrino/neutrino-dev?type=dev report the `v3.0.0-test.1` as newer.

**Additional context**

```
$ yarn info verdaccio
{ name: 'verdaccio',
  ...
  'dist-tags':
   { latest: '2.7.4',
     beta: '3.0.0-beta.10' },
  versions:
   [ ...
     '2.7.4',
     '3.0.0-alpha.1',
     ...
     '3.0.0-beta.10',
     '3.0.0-test.1' ],
  ...
  time:
   { modified: '2018-05-14T19:51:21.156Z',
     created: '2016-07-28T12:48:43.536Z',
     ...
     '3.0.0-alpha.13': '2018-02-16T17:15:29.618Z',
     '3.0.0-test.1': '2018-02-17T08:12:52.899Z',
     '3.0.0-beta.0': '2018-02-24T21:22:56.077Z',
     ...
     '3.0.0-beta.10': '2018-05-14T19:51:16.559Z' },
```

**Comment by edmorley** [comment]
(Edited to actually link to the PR 😆)

**Comment by rarkins** [comment]
Unfortunately this prints "true":
```
const semver = require('semver');
console.log(semver.gt('3.0.0-test.1', '3.0.0-beta.10'));
```

**Comment by rarkins** [comment]
`npm` follows this logic too:

![image](https://user-images.githubusercontent.com/6311784/40201145-85c49ed2-5a1e-11e8-851c-e5c4821c4b81.png)

**Comment by edmorley** [comment]
Yeah it's probably one of those annoying cases where yarn/npm have legacy hardcoded workarounds for bad package versions.

Perhaps we can ask the package maintainer to mark that version as deprecated, and then just skip deprecated versions?

**Comment by rarkins** [comment]
`yarn` doesn't even recommend `beta.10` when I try this:
```
yarn upgrade-interactive v1.6.0
success All of your dependencies are up to date.
```

**Comment by edmorley** [comment]
Ah ok. If you install `3.0.0-beta.10` rather than beta 9, does npm still show outdated?

**Comment by rarkins** [comment]
Previously my beta-9 wasn't pinned. Surprised to see this result when it's now pinned:

![image](https://user-images.githubusercontent.com/6311784/40201474-75b7fdf8-5a1f-11e8-9f51-9899a5aa9794.png)

I had expected it to recommend beta.10

**Comment by edmorley** [comment]
I've filed an issue asking for them to mark that version as deprecated:
verdaccio/verdaccio#699

**Comment by edmorley** [comment]
That version has now been marked as deprecated. Does Renovate already ignore deprecated packages (and so I can rename the closed Renovate PR title to test another isn't opened) or should I hold off? :-)

**Comment by rarkins** [comment]
I don’t think we have that logic unfortunately

**Comment by rarkins** [comment]
I've added the deprecated check to npm lookups now and it should be live in the app soon.

**Comment by rarkins** [comment]
Actually I'm rolling back all the new logic. The `deprecated` field can be really challenging. For example, `validate-commit-msg` has deprecated every version. `eslint-plugin-xo` deprecated just their (last ever) `v1.0.0` version and left all previous versions, which resulted in Renovate attempting to roll back v1.0.0 -> v0.5.1. Any logic using this field has to be quite advanced. There's an open issue about warning about deprecated versions in use, which I'll probably address first.

**Comment by rarkins** [comment]
See #1592 for a discussion on why the deprecation idea is not working.

So one question is - could the verdaccio problem be prevented some other way? 

One of the root problems is that Semver doesn't specify the test/alpha/beta part semantically like PEP440 does, e.g. there is no *semantic* definition of `pre`, `alpha`, `beta`, etc.

In theory we could use the timestamp of the versions to take an educated guess, but that's essentially using `timestamp` to override semver's "greater than" function.

**Comment by rarkins** [comment]
I want to dig around a little more before deciding whether to re-close. I think your point about `latest` is a good one for this particular case. By default we have the setting `respectLatest=true` which means don't upgrade past `latest` unless the current version is already past `latest`. This *should* stop any verdaccio upgrade to `3.0.0-test.1` because even though it's considered "greater than" `3.0.0-beta.10`, it's also therefore greater than `latest`.

**Comment by edmorley** [comment]
I meant to say earlier, thank you for looking at this / trying to fix it in 7fcbb47, your time/effort is much appreciated :-)

**Comment by rarkins** [comment]
Another approach: do not update from a non-deprecated to deprecated

**Comment by rarkins** [comment]
I think that avoiding upgrading from non deprecated to deprecated is a good idea here. I can implement it after refactoring get package updates

**Comment by edmorley** [comment]
Many thanks for this and #1592 :-)
