### ISSUE TITLE
Slim Docker image for `binarySource=install`

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#19890]
### What would you like Renovate to be able to do?

I like to have a renovate docker image, which is fully prepared for `binarySource=install`, so users can use that instead the full big fat docker image.

### If you have any ideas on how this should be implemented, please tell us here.

Create a new Repo to publish a new image.

We need to decide the suffix for it. Maybe `install` ? 🤔 

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by Shegox** [comment]
If we do this, I think we should take the effort into account and as well (then with slim/full/install image) add a page to the docs which outlines what image does what, when to use what and what are the advantages and disadvantages of the different container images. 

While I generally agree, the full image with `binarySource=install` has the advantage that there exists pre-installed "defaults" if the project doesn't define own e.g. `npm`/`node` versions. I think this trade-off might be for most self-hosted setups acceptable and preferred over using a "install-only" image.

**Comment by viceice** [comment]
> If we do this, I think we should take the effort into account and as well (then with slim/full/install image) add a page to the docs which outlines what image does what, when to use what and what are the advantages and disadvantages of the different container images. 

agreed


> While I generally agree, the full image with `binarySource=install` has the advantage that there exists pre-installed "defaults" if the project doesn't define own e.g. `npm`/`node` versions. I think this trade-off might be for most self-hosted setups acceptable and preferred over using a "install-only" image.  

for me the full image is too heavy, i only need a couple of tools. currently I've my own renovate image with just a few basic tools preinstalled and let renovate do others as required. dynamically tools are cached, so preinstalled full image doesn't have benefits for me.

**Comment by secustor** [comment]
+1 to the fact that we need to document the use cases.   

I guess `minimal` would be a fitting name too.

**Comment by Shegox** [comment]
> for me the full image is too heavy, i only need a couple of tools. currently I've my own renovate image with just a few basic tools preinstalled and let renovate do others as required. dynamically tools are cached, so preinstalled full image doesn't have benefits for me.

Makes sense, I hadn't that use-case in mind. Agree with `minimal`, that we communicate use this if you either:
- need not much (e.g. only docker images, which require no external tooling)
- build your own image based on this with adding your own tools
- use `binarySource=install` to install dynamically needed tools

**Comment by viceice** [comment]
closing this, as the slim image is now prepared and can be used with `binarySource=install` (needs to be set via env or cli)
