### ISSUE TITLE
Renovate doesn't look up dependencies on secondary index

### ISSUE THREAD

**Issue by ns-gchalapaka** [renovatebot/renovate#19908]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.70.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We have our python apps using one index-url proxying pypi.org and other extra-index-url point to internally hosted pypi.
Renovate looks for dependencies only from index-url although it parses the index and extra-index from the requirements.in file, and complains

⚠ Dependency Lookup Warnings ⚠
Renovate failed to look up the following dependencies: internal_x_pkg.

More details here from the discussion https://github.com/renovatebot/renovate/discussions/19524 

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Logic exists for detecting extra index URLs: https://github.com/renovatebot/renovate/blob/1127c5e4018f2fdd7883af5e5f59469c187e2a47/lib/modules/manager/pip_requirements/extract.ts#L58-L62

So we need a reproduction. The internal index can be a dummy one - the test would be whether Renovate attempts to reach it or not. Renovate should try all registry URLs for pypi and then merge them: https://github.com/renovatebot/renovate/blob/1127c5e4018f2fdd7883af5e5f59469c187e2a47/lib/modules/datasource/pypi/index.ts#L30
