### ISSUE TITLE
update pr upon changing baseBranch

### ISSUE THREAD

**Issue by gberche-orange** [renovatebot/renovate#19900]
### What would you like Renovate to be able to do?

as a renovate user
in order to change the baseBranch without having to update myself the existing PRs targetting an old base branch
I need renovate to update existing PRs baseBranch when renovate baseBranch is changed

Workaround: update the PRs using the script below using [github cli](https://cli.github.com/)

```bash
#!/bin/bash

set -x
set -f # disable file name expansion, especially in for loops

FROM="feature-bumps-for-v55"
TARGET="feature-bumps"
LIMIT="300"

echo "Editing renovate PRs to change base branch from ${FROM} to ${TARGET}"

PRS=$(gh pr list \
  --limit ${LIMIT} \
  --app "renovate" \
  --base "${FROM}" \
  --json number \
  | jq -r '.[].number' )

echo "first PRs (maxed at ${LIMIT}} to edit are: ${PRS}"

for p in $PRS; do
  gh pr edit $p --base ${TARGET}
done;


echo "rereun this command to check not more PR beyond $LIMIT is left to process"
```

### If you have any ideas on how this should be implemented, please tell us here.

similar as current PR submissions

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
Please include:
1. Current behavior (logs could be useful)
2. Exact instructions to reproduce minimally

**Comment by gberche-orange** [comment]
> Please include:
> 

>     2. Exact instructions to reproduce minimally

* configure renovate with baseBranch=branch1
* get some PRs opened with baseBranch=branch1
* change renovate config with baseBranch=branch2
* `[x] Click on this checkbox to rebase all open PRs at once` in the dashboard issue

> Expected behavior

The existing PRs are edited to set the base branch to branch 2

>     1. Current behavior (logs could be useful)


The existing PRs are NOT edited to set the base branch to branch 2, only a force push is performed

Logs from renovate dashboard UI
```
DEBUG: migrated config
{
  "config": {
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "github>whitesource/merge-confidence:beta",
      "config:base",
      ":disableRateLimiting",
      ":rebaseStalePrs"
    ],
    "baseBranches": [
      "feature-bumps-for-v56"
    ],
[...]

DEBUG: Found PR #1512(branch="renovate/cloudfoundry-community-ntp-release-4.x")
{
  "baseBranch": "feature-bumps-for-v56"
}

DEBUG: Branch summary
{
  "baseBranches": [
    {
      "branchName": "feature-bumps-for-v56",
      "sha": "098701b34f161503effe6b6c143af201509cea0b"
    }
  ],
  "branches": [
    {
      "automerge": false,
      "baseBranch": "feature-bumps-for-v56",
      "baseBranchSha": "098701b34f161503effe6b6c143af201509cea0b",
      "branchName": "renovate/cloudfoundry-community-ntp-release-4.x",
      "branchSha": "3660bc7d1291dea8f4de2891aa41f6e323f24433",
      "isModified": false,
      "isPristine": false
    },

DEBUG: Renovate repository PR statistics
{
  "stats": {
    "total": 428,
    "open": 101,
    "closed": 185,
    "merged": 142
  }
}
``` 
See the PR associated history not showing the PR edition, and instead the actions from the automated workaround script above "changing base branch from ..."
![image](https://user-images.githubusercontent.com/4748380/213246229-7934b672-c656-43dd-bbec-fb403b663826.png)

**Comment by rarkins** [comment]
Can you reproduce this on github.com using the hosted app?

I had expected that Renovate would detect it as modified and stop updating it, but it seems it force pushed after you made that modification. Is the git history itself correct, e.g. it's committed on top of the correct base branch commit?

**Comment by rarkins** [comment]
Please reproduce it on a public repo and share the URL

**Comment by gberche-orange** [comment]
thanks @RahulGautamSingh  @rarkins  !
