### ISSUE TITLE
Istio packages failed 

### ISSUE THREAD

**Issue by Meshmov** [renovatebot/renovate#19989]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

GitHub Enterprise Server

### Was this something which used to work for you, and then stopped?

Never worked

### Describe the bug

Istio in my go modules returns ` Failed to look up go dependency` after installing renovate

### Relevant debug logs

<details><summary>Logs</summary>

```
`DEBUG: Datasource connection error (repository=secret)
        "datasource": "go",
        "packageName": "istio.io/istio",
        "url": undefined,
        "errCode": "EPROTO"
 DEBUG: Failed to look up go dependency istio.io/istio (repository=secret, packageFile=istio-init/go.mod, dependency=istio.io/istio)`
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by Meshmov** [comment]
in my `go.mod`:

`require istio.io/istio v0.0.0-20221208194603-fc52de67ee0e`
```
require (
	istio.io/pkg v0.0.0-20230119194614-e877df450e1b // indirect
)
```

in my `go.sum`:
```
istio.io/istio v0.0.0-20221208194603-fc52de67ee0e 
istio.io/istio v0.0.0-20221208194603-fc52de67ee0e/go.mod 
istio.io/pkg v0.0.0-20230119194614-e877df450e1b 
istio.io/pkg v0.0.0-20230119194614-e877df450e1b/go.mod 
```

**Comment by Meshmov** [comment]
The dependancy gets recognised but as the url is not valid to find versions I get the error

**Comment by Meshmov** [comment]
[Minimal reproduction repo](https://github.com/Meshmov/Istio_renobot_issue/tree/main)

**Comment by Meshmov** [comment]
For some reason it works here and with `GitHub Enterprise Server`does not . 
This was the [PR](https://github.com/Meshmov/Istio_renobot_issue/pull/2) generated with it but it doesn't get the rest `v0.0.0-20230126010610-cced4dfa0f86`only the `digest`-> `cced4dfa0f86 `

**Comment by Meshmov** [comment]
For reference [pkg.go.dev/istio.io](https://pkg.go.dev/istio.io/istio?tab=versions)

**Comment by rarkins** [comment]
Have you configured GOPROXY?

**Comment by rarkins** [comment]
Related: https://github.com/renovatebot/renovate/issues/20040
