### ISSUE TITLE
Don't automerge if automerge option is false for any package in the PR

### ISSUE THREAD

**Issue by tsido** [renovatebot/renovate#1999]
Currently Renovate doesn't seem to check that the `automerge` is `false` for every package that is part of the pull request but uses the `automerge` setting of the first package present in PR instead. 

This can lead to packages that have the `automerge` option set to `false` to be merged when using `packageRule` to group multiple packages to single PRs, which is not intuitive or desired.

**Comment by rarkins** [comment]
I think this can become the new default behaviour as it’s more obvious than picking a non-deterministic first package’s settings. 

Could even be a “one liner”:

`config.automerge = config.upgrades.every(upgrade => upgrade.automerge);`

**Comment by teppeis** [comment]
+1 👍 

If `automergePatch` is enabled and a package in a group has minor or major update, I don't want the group to automerge.

**Comment by teppeis** [comment]
@rarkins Thank you for your awesome work!

**Comment by anantakrishna** [comment]
I'm wondering why this pull request in my repo still was marked for automatic merging?

https://github.com/PureBhaktiArchive/audioseva/pull/248

Both minor and major updates are grouped together, and I have the following config:

```
  "automerge": true,
  "major": {
    "automerge": false
  },
```
