### ISSUE TITLE
[SPM] Renovate does not understand Swift 5.7 `package(... exact:)` syntax

### ISSUE THREAD

**Issue by manicmaniac** [renovatebot/renovate#20031]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

## Problem

Prior to Swift 5.7, specifying the exact version looks like the following (see how to use `exact`).

```swift
  dependencies: [
    .package(url: "https://github.com/manicmaniac/SomePackage", .exact("1.0.0"))
  ]
```

Renovate works well for this syntax.

However, this syntax is deprecated in Swift 5.6 and removed in 5.7.
The new syntax is like the following:

```swift
  dependencies: [
    .package(url: "https://github.com/manicmaniac/SomePackage", exact: "1.0.0")
  ]
```

Renovate does not recognize this kind of syntax and complains like I attached below.

Apparently [34.114.0](https://github.com/renovatebot/renovate/releases/tag/34.114.0) does not test the new syntax.

https://github.com/renovatebot/renovate/blob/34.114.0/lib/modules/manager/swift/index.spec.ts#L66

## Workaround

A possible workaround I find is downgrading Swift tools version to 5.5 in magic comment and use the older syntax.

```swift
// swift-tools-version: 5.5

...
  dependencies: [
    .package(url: "https://github.com/manicmaniac/SomePackage", .exact("1.0.0"))
  ]
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Dependency SomePackage has unsupported value "1.0.0"
...
DEBUG: packageFiles with updates
...
        "packageFile": "Package.swift",
        "deps": [
          {
            "datasource": "git-tags",
            "depName": "SomePackage",
            "packageName": "https://github.com/manicmaniac/SomePackage",
            "currentValue": "\"1.0.0\"\n    ",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "versioning": "swift",
            "skipReason": "invalid-value"
          },
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by viceice** [comment]
not a bug, but a feature request.

feel free to send a PR to support the new syntax
