### ISSUE TITLE
Single-repo Dry-run succeeds even though config is invalid

### ISSUE THREAD

**Issue by reitzig** [renovatebot/renovate#20177]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.48.3

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

I have the exact same issue as described in #7424, though there may be other cases.

Point is, I have a broken config but _both_ validator and dry-run on that single repo (mode lookup) terminate successfully. Therefore, my PR pipeline is green.
I expect at least one of the two to fail. To me, this is essential for maintaining configs over time.

I also note that information about the error is logged on DEBUG resp. INFO level, so it's not even that easy to reliably check the logs as a workaround.

Since I can't conceive of a use case for single-repo dry-runs that is tolerant of broken configs, I'm labelling this as bug.
If the current behaviour is as intended -- and I can see how you wouldn't want to fail a company-wide cronjob because of a single bad config! -- I'd like to propose an optional config/CLI flag that enables a stricter mode, failing on any config errors.

### Relevant debug logs

<details><summary>Logs</summary>

```
+ renovate --autodiscover=false --dry-run=lookup --print-config=true --use-base-branch-config=merge my-project/my-repo
DEBUG: Using RE2 as regex engine
<snip>
DEBUG: Aggregate error is thrown (repository=my-project/my-repo, baseBranch=fix/renovate-config)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: config-validation\n        at filterVersions (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:97:21)\n        at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:235:44)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)\n        at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:59:15)\n        at /usr/src/app/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: config-validation\n        at filterVersions (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:97:21)\n        at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:235:44)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)\n        at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:59:15)\n        at /usr/src/app/node_modules/p-map/index.js:57:22\n    at next (/usr/src/app/node_modules/p-map/index.js:43:14)\n    at /usr/src/app/node_modules/p-map/index.js:59:6\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
DEBUG: Aggregate error is thrown (repository=my-project/my-repo, baseBranch=fix/renovate-config)
       "err": {
         "name": "AggregateError",
         "message": "\n    Error: config-validation\n        at filterVersions (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:97:21)\n        at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:235:44)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)\n        at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:59:15)\n        at /usr/src/app/node_modules/p-map/index.js:57:22",
         "stack": "AggregateError: \n    Error: config-validation\n        at filterVersions (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:97:21)\n        at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:235:44)\n        at runMicrotasks (<anonymous>)\n        at processTicksAndRejections (node:internal/process/task_queues:96:5)\n        at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:59:15)\n        at /usr/src/app/node_modules/p-map/index.js:57:22\n    at next (/usr/src/app/node_modules/p-map/index.js:43:14)\n    at /usr/src/app/node_modules/p-map/index.js:67:7\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
 INFO: Repository has invalid config (repository=my-project/my-repo)
       "error": {
         "validationSource": "config",
         "validationError": "Invalid `allowedVersions`",
         "validationMessage": "The following allowedVersions does not parse as a valid version or range: \"^\\\\d{1-2}\\\\.\"",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at filterVersions (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:97:21)\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:235:44)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:59:15)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Unless you plan to submit the fix, you'll need to reproduce it. Assuming it's not Bitbucket specific, please come up with a repo and config on GitHub.com which shows the same behaviour

**Comment by reitzig** [comment]
Fair. Do you have a template I can get started with?

**Comment by viceice** [comment]
@rarkins i think we can at least warn when we catch a config error?

@reitzig some errors are only catchable doing a full dry run. they aren't easily findable by config validation.

**Comment by rarkins** [comment]
I think when it's a non dry-run we do a WARN, we could do the same for dry-run too. We today do not error for invalid *user* config. Errors are reserved for when Renovate has an error, not for when the user makes a mistake

**Comment by reitzig** [comment]
FWIW, log levels are a secondary concern to me; might open a separate issue. The main thing I need is to fail a dry-run in case of config errors (since the validator doesn't catch them all). 
I'm of two minds about lookup errors; I'd like to catch missing registries, for instance, but I don't want a brittle pipeline either. :thinking: 

That said, if errors would log on WARN and we had a flag like `--fail-on-warning`, _this_ direction would work out. Not sure how many false negatives that would create.

**Comment by rarkins** [comment]
Like @viceice said, you hit a config error which can't be caught statically, because `allowedVersions` being valid or not depends on which type of `versioning` is fed to it at runtime.

**Comment by reitzig** [comment]
Yes, I'm talking about the (dry-)runtime. `dry-run=lookup` clearly catches that error (if maybe not all possible ones, I don't know) but the UI (as in, CLI params) does not allow me to act on that.
