### ISSUE TITLE
Renovate is timing out as of February 3rd, 9AM EST

### ISSUE THREAD

**Issue by esetnik** [renovatebot/renovate#20205]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/664434/216662064-3cfd3150-6e93-437c-aaae-f446e307604b.png">

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Using cached etag
DEBUG: Using cached etag
DEBUG: Cached npm result is revalidated
{
  "packageName": "saml"
}
DEBUG: Cached npm result is revalidated
{
  "packageName": "yarnhook"
}
WARN: Job timeout
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
App support is in Discussions
