### ISSUE TITLE
Modify the `registryStrategy` for `composer`

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#20219]
### What would you like Renovate to be able to do?

I would like renovate to be able to switch `registryStrategy` for composer based on canonical value.
Related: https://github.com/renovatebot/renovate/discussions/20181 (discussion)

### If you have any ideas on how this should be implemented, please tell us here.

The concept of lower/higher priority repositories in Composer is defined using the [canonical][1] option within the `repositories` field in `composer.json`. This option takes a boolean value and determines the source of dependencies when looking up packages.

Example:
```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://example.org",
            "canonical": false // default value is true
        }
    ]
}
```
`canonical:false`
> make sure Composer keeps looking in other repositories, even if that repository contains a given package.

`canonical:true`
> When Composer resolves dependencies, it will look up a given package in the topmost repository. If that repository does not contain the package, it goes on to the next one, until one repository contains it and the process ends

The `registryStrategy` for composer is `hunt`.
I think we will need to change th extraction logic to check for `canonical` option, if not found or true  use the hunt strategy and if false then switch to merge.

I am not sure if this is desired cause we currently don't have any datasource that changes `registryStrategy` based on manager.

Extra: There is also an option [only][2] which is used to filter packages which we might need to take care of as well.

[1]: <https://getcomposer.org/doc/articles/repository-priorities.md#making-repositories-non-canonical>
[2]: <https://getcomposer.org/doc/articles/repository-priorities.md#filtering-packages>

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by RahulGautamSingh** [comment]
Duplicate

**Comment by viceice** [comment]
@RahulGautamSingh please link the duplicate. 😉
