### ISSUE TITLE
Renovate shows wrong package version

### ISSUE THREAD

**Issue by achterin** [renovatebot/renovate#20257]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.241.11

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

7.17.1

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Renovate opened a pull-request on our project for updating [php-cs-fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) to v3.14.3 but the changes showed that it actually updated only to v3.14.2.
This is because another library requires doctrine/annotations in v1, but support for that got removed in php-cs-fixer v3.14.3.
What i would expect, is one of two things:
- renovate tries to update to the correct version and it fails because of the dependency conflict.
- renovate updates to the last installable version and shows the installed version in the pr/commit/... instead of the latest version

### Relevant debug logs

<details><summary>Logs</summary>

```
{"name":"renovate","hostname":"redacted","pid":52,"level":20,"logContext":"QnPmGGXtVM-loZmOxOYrB","repository":"redacted","branch":"renovate/friendsofphp-php-cs-fixer-3.x-lockfile","cmd":"composer","args":"update friendsofphp/php-cs-fixer --with-dependencies --ignore-platform-req='ext-*' --ignore-platform-req='lib-*' --no-ansi --no-interaction --no-scripts --no-autoloader","msg":"composer command","time":"2023-02-03T23:16:37.693Z","v":0}
```

</details>

### Have you created a minimal reproduction repository?

[Reproduction repository](https://github.com/achterin/renovate_issue_20257)

**Comment by achterin** [comment]
I've added a small symfony app which should enable you to reproduce the issue.
Renovate will try to update friendsofphp/php-cs-fixer to v3.14.3 but composer will prevent this and update to v3.14.2 instead. This is because the dependecy doctrine/annotations is required to be v1 because damienharper/auditor-bundle is not compatible with v2 which php-cs-fixer v3.14.3 requires.
Hope this helps.

**Comment by rarkins** [comment]
Please see our guide about _minimal_ reproductions. The repository is not minimal (contains excess package managers and dependencies)
