### ISSUE TITLE
Track multiple `followTag` for specific libraries?

### ISSUE THREAD

**Issue by dotansimha** [renovatebot/renovate#20265]
### What would you like Renovate to be able to do?

Track multiple `followTag` configurations (pass an array). The goal is to implement the following flow:
1. We want to track `rc` tag releases of specific packages, and have the PR getting updated with the RC, triggering CI and so on. We do not intend to merge Renvoate RC PRs, just to have it tracked with CI and for visibility.  
2. When a stable release is published, Renovate updates the PR to use the latest stable, because it's "preferred" (see below). 

Also related: https://github.com/renovatebot/renovate/issues/5872 

### If you have any ideas on how this should be implemented, please tell us here.

2 options: 

1 - treat `stable` as special keyword and always prefer stable if it's specific, for example: `followTag: [rc, stable]` will lead to Renovate always picking `stable` and when there isn't one -> pick `rc`. 
2 - use the order of the tags to decide which is more important to pick: `followTag: [stable, rc]` -> prefers `stable` because it's first in the array. 

Both options still allow users to override and use `followTag: rc` or `followTag: [rc]` in order to override the default config, and bypass `stable` if needed. 

### Is this a feature you are interested in implementing yourself?

Maybe, depends on feedback :)

**Comment by rarkins** [comment]
Assume there's always going to be both a stable and rc tag published. Sometimes one will be higher than the other. How to choose every time?

Or is your scenario assuming that the rc tag gets *deleted* periodically once there's stable available?

**Comment by dotansimha** [comment]
> Assume there's always going to be both a stable and rc tag published. Sometimes one will be higher than the other. How to choose every time?
> 
> Or is your scenario assuming that the rc tag gets _deleted_ periodically once there's stable available?

Yeah, we always aim to use the latest stable when it's available, and when not, we want to use the latest RC.

**Comment by rarkins** [comment]
So you always want to be on the latest tagged version, whether it's latest or rc?

**Comment by dotansimha** [comment]
> So you always want to be on the latest tagged version, whether it's latest or rc?

Yes, but for specific tags. And with priority. I will always prefer to have Renovate creating a PR for the latest stable release, and there is no such release, it will try to look for a newer release (using `semver`) with the specific tag (in this case `rc`).

So if I'm currently on `foo@1.0.0`, Renovate will try to update it to stable release `>1.0.0` if available, and if not, it will update to `>1.0.0@rc` if it's available

I can explain a bit more about our use case: we are a group of developers (https://www.the-guild.dev/) that maintains multiple NPM packages. Each one is on its own repo with its own release lifecycle. We do alpha releases for PRs, and RC releases for groups of changes before releasing stable. 
Some of our packages have dependencies and we wish to know about possible breaking changes / problematic releases ahead of time. 
We wanted to leverage the automated RC release flow, and have a PR in the dependent packages for using the RC, while waiting for the stable release. This way we can tell ahead of time if an RC release broke a package, while "waiting" for the stable release to come. 

For example:
1. `graphql-codegen` depends on `graphql-tools`.
2. `graphql-tools` is getting ready to have a release, and release RC version.
3. Renovate catches the `graphql-tools@rc` release, and opens a PR in `graphql-codegen` 
4. `graphql-codegen` CI runs for the Renovate PR and reports a status. 
5. We are now able to tell of `graphql-tools` broke `graphql-codegen` before making the actual release of `graphql-tools`, thanks to RC release + Renovate.

**Comment by rarkins** [comment]
> So if I'm currently on `foo@1.0.0`, Renovate will try to update it to stable release `>1.0.0` if available, and if not, it will update to `>1.0.0@rc` if it's available

Then what to do if you're on 1.0.0 and `1.1.0rc0` is released?

**Comment by dotansimha** [comment]
> Then what to do if you're on 1.0.0 and `1.1.0rc0` is released?

Then a PR for `1.1.0-rc0` is created. Our goal is not to merge this PR, get the CI results. When `1.1.0` is released, then the PR will be updated and we'll get it merged.

**Comment by rarkins** [comment]
So follow multiple tags, always tag whichever is highest?

**Comment by dotansimha** [comment]
> So follow multiple tags, always take whichever is highest?

Yeah, exactly. The highest available from each tag, and then a user can pick what tag is more preferred (if it has a new available version)

**Comment by viceice** [comment]
checkout the ignore unstable setting

**Comment by dotansimha** [comment]
> checkout the ignore unstable setting

Thank you! that's almost what we need, but we want to specify tags for that configuration. Because our packages have an `alpha` release per each commit/PR, and `rc` tag for upcoming releases. Using this configuration will make Renovate go crazy because of all the alpha releases, no? 
Also, how does it prioritize how to pick alpha vs beta vs rc in that case?

**Comment by viceice** [comment]
use allowed versions setting 😉

**Comment by dotansimha** [comment]
> use allowed versions setting 😉

🤯 🤯 🤯 

Thanks, I will try to use a regex matcher for `allowedVersions` along with `ignoreUnstable: false` and will update soon ;) Thank you!

**Comment by rarkins** [comment]
> Yeah, exactly. The highest available from each tag, and then a user can pick what tag is more preferred (if it has a new available version) 

How would that be different to following only one tag? Ie if it's preferred and never removed, it will be selected every time anyway?

**Comment by dotansimha** [comment]
@viceice I was using the following:

```json
  "packageRules": [
    {
      "groupName": "@theguild/prettier-config",
      "matchPackageNames": ["@theguild/prettier-config"],
      "ignoreUnstable": false,
      "allowedVersions": "/^(d+).(d+)(?:.(d+))?(-rc-.+)?$/"
    }
]
```

The package mentioned there has a stable and a newer `rc` release:

```
~ npm show @theguild/prettier-config

dist-tags:
alpha: 1.1.1-alpha-20230130173931-3cdb8b2
latest: 1.1.1
rc: 1.1.2-rc-20230209111424-9d57ee2
```

My project is currently set to use it as: `"@theguild/prettier-config": "^1.1.0",`. 

Renovate ran and didn't create a PR to update it to `rc`, any idea why? I found this piece of log in Renovate dashboard:

```json
{
            "currentValue": "^1.1.0",
            "currentVersion": "1.1.1",
            "datasource": "npm",
            "depIndex": 16,
            "depName": "@theguild/prettier-config",
            "depType": "devDependencies",
            "prettyDepType": "devDependency",
            "registryUrl": "https://registry.npmjs.org",
            "sourceDirectory": "packages/prettier-config",
            "sourceUrl": "https://github.com/the-guild-org/shared-config",
            "versioning": "npm",
            "warnings": [],
            "updates": []
          },
```

Thanks!

**Comment by rarkins** [comment]
Try `respectLatest=false` too in case that's holding it back

**Comment by dotansimha** [comment]
> Try `respectLatest=false` too in case that's holding it back

Thanks @rarkins , I tried that but it seems like it still does not work.

```json
{
            "currentValue": "1.1.1",
            "currentVersion": "1.1.1",
            "datasource": "npm",
            "depIndex": 0,
            "depName": "@theguild/prettier-config",
            "depType": "dependencies",
            "fixedVersion": "1.1.1",
            "prettyDepType": "dependency",
            "registryUrl": "https://registry.npmjs.org",
            "sourceDirectory": "packages/prettier-config",
            "sourceUrl": "https://github.com/the-guild-org/shared-config",
            "versioning": "npm",
            "warnings": [],
            "updates": []
          }
```

Here's a simple reproduction, in case it that helps https://github.com/dotansimha/renovate-experiments

**Comment by rarkins** [comment]
A brief debug shows that it doesn't match allowedVersions

**Comment by dotansimha** [comment]
> A brief debug shows that it doesn't match allowedVersions

Oh, that's 100% correct. I changed it to be `/^([0-9]+).([0-9]+)(?:.([0-9]+))?(-rc-.+)?$/` and it does seem to work (https://github.com/dotansimha/renovate-experiments/pull/3). 

Thank you, this works great now! Closing ✅

**Comment by dotansimha** [comment]
@rarkins @viceice one more question about that: is it possible to create a draft PR based on some rules? I wanted to create the `rc` PRs as draft, and then mark it as ready PR when it's a stable release.

**Comment by rarkins** [comment]
No
