### ISSUE TITLE
Dependency XXXX has unsupported value main

### ISSUE THREAD

**Issue by faradaytrs** [renovatebot/renovate#20266]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34

### If you're self-hosting Renovate, select which platform you are using.

None

### If you're self-hosting Renovate, tell us what version of the platform you run.

github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

I am trying to use self-hosted renovate for private repo with private submodules. I know it's not officially supported, but i believe I found some advices here and got custom ssh layer with auth.

Cloning submodules is successful, but later I see the following message in the logs:
````
Dependency XXXXX has unsupported value main
````
main is the branch of submodule. I have several submodules, all of them have this problem.
As result, nothing inside of submodule is updated by renovate.

### Relevant debug logs

Logs are in the file
[output.log](https://github.com/renovatebot/renovate/files/10672281/output.log)

Here is my renovate config for monorepo:
````json
{
  "extends": ["config:base"],
  "rebaseStalePrs": true,
  "ignoreTests": false,
  "automerge": true,
  "automergeType": "branch",
  "packageRules": [
    {
      "depTypeList": ["dependencies"],
      "updateTypes": ["major"],
      "automerge": false
    }
  ],
  "git-submodules": {
    "enabled": true
  },
  "hostRules": [
    {
      "matchHost": "github.com",
      "token": "XXX_TOKEN___XXXX"
    }
  ]
}
````

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
This is inappropriate for a bug report. Please resubmit as a discussion
