### ISSUE TITLE
Renovate was incorrectly added to multiple repositories in the /android org

### ISSUE THREAD

**Issue by JoseAlcerreca** [renovatebot/renovate#20268]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

N/A

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

This might be a bug in Github and not Renovate, but I'll start here.

Last week I configured Renovate in two repositories:
https://github.com/android/architecture-samples/pull/898
https://github.com/android/architecture-components-samples/pull/1080

But it was also added to a bunch of repositories in the android org that I did not select:
https://github.com/android/uamp/pull/515
https://github.com/android/ndk/pull/1838

But not in others like 
https://github.com/android/sunflower/pulls?q=is%3Apr+renovate

The screen to configure new repositories is acting strangely, as it lists zero configured repos.
![image](https://user-images.githubusercontent.com/609125/217198006-bc0342ac-623a-45d6-951e-0bcd7fedb2d8.png)

### Relevant debug logs

N/A

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Anything we can help with? I'd be curious to know if it was a GitHub bug or someone else added them?

**Comment by JoseAlcerreca** [comment]
I closed the issue for now because we're investigating. It looked like someone might have selected "All repositories" so we thought it was human error, but Github sent an email to all the repo owners with:

> You’re receiving this email because @JoseAlcerreca has requested the installation of Renovate at your organization android.

And I definitely chose only 2 repositories. I'll contact Github support to see if they can inspect logs.
