### ISSUE TITLE
allowedVersions

### ISSUE THREAD

**Issue by swiss-chris** [renovatebot/renovate#20274]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

In my preset I have the following config:

  "packageRules": [
    {
      "groupName": "Apache Commons",
      "matchPackagePatterns": [
        "^org.apache.commons:",
        "^commons-beanutils:",
        "^commons-cli:",
        "^commons-collections:",
        "^commons-io:"
      ],
      "allowedVersions": "/^(\\d{1,3}\\.)(\\d*\\.)*\\d*(?!.*\\.redhat-.*)$/"
    },

Since I created this preset almost 2 months ago, I haven't been getting any more renovate updates on my maven projects.

Today I saw this log message in the Pod running Renovate:

INFO: Repository has invalid config (repository=...)
"error": {
"validationSource": "config",
"validationError": "Invalid `allowedVersions`",
"validationMessage": "The following allowedVersions does not parse as a valid version or range: \"/^(\\\\d{1,3}\\\\.)(\\\\d*\\\\.)*\\\\d*(?!.*\\\\.redhat-.*)$/\"",
"message": "config-validation",
"stack": "Error: config-validation\n at filterVersions (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:97:21)\n at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:234:44)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)\n at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:58:15)\n at /usr/src/app/node_modules/p-map/index.js:57:22"
}
WARN: Cannot ensure issue (repository=...)
"title": "Action Required: Fix Renovate Configuration"
INFO: Repository finished (repository=...)
"cloned": true,

1. Am I correct in assuming that my preset is breaking renovate and preventing it from making updates to my maven projects ?
2. How can I fix this ? I don't want 'a.b.c.redhat-d' updates.

### Relevant debug logs

<details><summary>Logs</summary>

```
INFO: Repository has invalid config (repository=...)
"error": {
"validationSource": "config",
"validationError": "Invalid `allowedVersions`",
"validationMessage": "The following allowedVersions does not parse as a valid version or range: \"/^(\\\\d{1,3}\\\\.)(\\\\d*\\\\.)*\\\\d*(?!.*\\\\.redhat-.*)$/\"",
"message": "config-validation",
"stack": "Error: config-validation\n at filterVersions (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/filter.ts:97:21)\n at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:234:44)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)\n at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:58:15)\n at /usr/src/app/node_modules/p-map/index.js:57:22"
}
WARN: Cannot ensure issue (repository=...)
"title": "Action Required: Fix Renovate Configuration"
INFO: Repository finished (repository=...)
"cloned": true,
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Should be a discussion, not bug report
