### ISSUE TITLE
[Manager] Support Vendir

### ISSUE THREAD

**Issue by KnechtionsCoding** [renovatebot/renovate#20310]
### What would you like Renovate to be able to do?

[Vendir](https://carvel.dev/vendir/) is a tool for bringing in external code (like helm charts) in a declarative fashion. It's very useful for highly regulared environments where airgaps/airlocks are required. 

Having Renovate support the vendir spec to submit and look for updates would be awesome

### If you have any ideas on how this should be implemented, please tell us here.

Add a new manager that supports vendir

### Is this a feature you are interested in implementing yourself?

No

**Comment by viceice** [comment]
Duplicate of #17711
