### ISSUE TITLE
[Gradle][Plugin][JMH] jmhVersion not detected

### ISSUE THREAD

**Issue by dtrunk90** [renovatebot/renovate#20464]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate doesn't detect the `jmhVersion` from the following gradle plugin: https://github.com/melix/jmh-gradle-plugin

I've configured the following in my `build.gradle` file:
```groovy
jmh {
    jmhVersion = '1.35'
    resultFormat = 'JSON'
}
```

Latest jmh version is 1.36.

Reproduction repository: https://github.com/slugify/slugify

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
@Churro this doesn't feel right to be a bug. I assume there are many plugins we can progressively add, treating each missing one as a bug seems wrong. WDYT?

**Comment by Churro** [comment]
> @Churro this doesn't feel right to be a bug. I assume there are many plugins we can progressively add, treating each missing one as a bug seems wrong. WDYT?

Absolutely. I don't see this as a bug either, as there is an infinite number of community plugins their individual attributes.
