### ISSUE TITLE
Speed up Jest tests by using `@swc/jest`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#20477]
### Describe the proposed change(s).

@viceice offered to try `@swc/jest` again. So here's their todo issue. 😉 

Related issues/PRs:

- #15053
- #14572

**Comment by kdy1** [comment]
Is there anything I can help with?

**Comment by viceice** [comment]
> Is there anything I can help with?
> 

sure, you can take this issue if you want.
you can check my PR for what was done and start playing with swc

**Comment by HonkingGoose** [comment]
@viceice do you want to try the `@swc/jest` package again?

**Comment by viceice** [comment]
yes, when I've some time 😅
