### ISSUE TITLE
Suggest new sbt versions

### ISSUE THREAD

**Issue by gaeljw** [renovatebot/renovate#20481]
### What would you like Renovate to be able to do?

In sbt projects, I would like Renovate to suggest new sbt versions.

In a sbt project, there's a file called `project/build.properties` with following content:
```
sbt.version=1.7.1
```

The goal would be to generate MR when a new sbt version is available.

A similar discussion started in https://github.com/renovatebot/renovate/issues/11212 but was somehow messy and issue was closed for comments, thus I prefer to open a new one with a clear goal.

### If you have any ideas on how this should be implemented, please tell us here.

I think this could be implemented with a very basic regex manager and using GitHub tags as reference for available versions (https://github.com/sbt/sbt/tags).

Something similar to:
```json
{
            "fileMatch": ["(^|/)build\\.properties$"],
            "matchStrings": ["sbt\\.version=(?<currentValue>\\S*)"],
            "lookupNameTemplate": "sbt/sbt",
            "extractVersionTemplate": "^(?<version>.*)$",
            "versioningTemplate": "semver",
            "datasourceTemplate": "github-tags",
            "registryUrlTemplate": ["https://github.com"]
        }
```
_(I just copy pasted a regex manager I use for another purpose to give an idea, I have not tested this manager at all)._

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by gaeljw** [comment]
I'll be happy to help if someone can give me some minimal guidance at where to make some changes :)

**Comment by rarkins** [comment]
Best to start with a reproduction repo with the characteristics you described. The change would be in https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/sbt/extract.ts, @zharinov can maybe help you out if it's not obvious where to add it

**Comment by gaeljw** [comment]
Here's the reproduction repo: https://github.com/gaeljw/feat_renovate_20481

Expected behaviour once this feature is implemented is to get a PR for the file `project/build.properties` with following content:
```diff
- sbt.version=1.6.0
+ sbt.version=1.8.2
```

Will see if I'm able to provide a PR for this.

**Comment by rarkins** [comment]
Reproduction forked to https://github.com/renovate-reproductions/20481

**Comment by gaeljw** [comment]
@zharinov I'm blocked at trying to define the parser for `sbt.version=x.y.z` for two reasons:
- `sym('sbt.version')` seems to not work, look's like the dot is problematic
- then I'm able to match `sbtVersion="1.2.3"` with `sym('sbtVersion').op('=').str()` but I can't find a way to match without double quotes, i.e. `sbtVersion=1.2.3` (I tried `sym('sbtVersion').op('=').num().op('.').num().op('.').num()` without success)

If you can give me some pointers to where to look for example of similar parsing or documentation, I think I'll be able to provide a PR for this.

**Comment by gaeljw** [comment]
Nevermind, I found where to put my breakpoint. It happens that the value is parsed as `num().num().num()` which is a bit strange but I'll work with that for now.

**Comment by gaeljw** [comment]
Note that for this to work properly in environments where private registry is configured for sbt, the GitHub registry url must be added in the list of registries and be the first one in the list:

```json
{
            "matchManagers": [
                "sbt"
            ],
            "registryUrls": [
                "https://github.com",
                "https://artifactory.mycompany.net/artifactory/xxx"
            ]
        }
```

If it's not added, then only the Artifactory url is used to look for sbt releases and it doesn't work.

If it's added last, then we get the warning:
```
WARN: Excess registryUrls found for datasource lookup - using first configured only
datasource": "github-releases",
       "depName": "sbt/sbt",
       "registryUrls": [
         "https://artifactory.mycompany.net/artifactory/...",
         "https://github.com"
       ]
```

This feels a bit weird to have to do that. I guess that's because we put sbt version management with Github datasource as part of the manager "sbt" but the datasources for sbt dependencies and sbt itself are completely different.

Shouldn't we move this to a dedicated manager in the end?

@rarkins @viceice any opinion?

**Comment by rarkins** [comment]
Can't the packageRule also use matchPackageNames so that it applies only to the sbt version and not all sbt dependencies?

**Comment by gaeljw** [comment]
> Can't the packageRule also use matchPackageNames so that it applies only to the sbt version and not all sbt dependencies?

I feel this forces users to have "deep knowledge" of how the sbt manager works. IMHO users shouldn't have to know the sbt manager handles different kind of dependencies with different kind of settings.

If user are defining private registries for sbt, thinking about traditional sbt dependencies, they very likely won't assume they need to add other settings to get sbt upgrades PR and they will just never notice there's an issue.

**Comment by rarkins** [comment]
The sbt manager can include `registryUrls` per-package too, so the user doesn't need to understand. Honestly though I may be misunderstanding what you mean. Can you create a new discussion and new reproduction repo to demonstrate?

**Comment by gaeljw** [comment]
Opened a discussion to not pollute this original issue: https://github.com/renovatebot/renovate/discussions/20676
