### ISSUE TITLE
github-tags digest lookup fails in app only

### ISSUE THREAD

**Issue by DuncanCasteleyn** [renovatebot/renovate#20507]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

The github hosted renovate app can't determine the v1 tag digest for [unfor19/install-aws-cli-action](https://github.com/unfor19/install-aws-cli-action). 

A reproduction repo has been forked and confirmed the bug: https://github.com/renovate-reproductions/20475

It appears the bug only happens with the renovate app.

Extra logging has been added to investigate the bug further: https://github.com/renovatebot/renovate/pull/20506

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Could not determine new digest for update.
{
  "depName": "unfor19/install-aws-cli-action",
  "currentValue": "v1",
  "datasource": "github-tags",
  "newValue": "v1"
}

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by DuncanCasteleyn** [comment]
See the discussion for more context: https://github.com/renovatebot/renovate/discussions/20475#discussioncomment-5022383

**Comment by rarkins** [comment]
Fixed by #20630

https://github.com/renovate-reproductions/20475/pull/3

**Comment by viceice** [comment]
interesting, that fix send me two PR's which where autoclosed before. hadn't time to look into yet. can't share more info, as it's a private repo.

**Comment by DuncanCasteleyn** [comment]
Can confirm on multiple repo's that the issue has been resolved.

Thanks for the effort.
