### ISSUE TITLE
Renovate sidecar for yarn does not pass npm config to child process 

### ISSUE THREAD

**Issue by Breee** [renovatebot/renovate#20513]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.48.4-slim

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.8.3

### Was this something which used to work for you, and then stopped?

I never saw this working

## General config 
The most important setting is that our renovateconfig allows us to authenticate against an artifactory instance.  If you want something detailed i can provide it

## Given the following files in our repo 

.npmrc: 
```
@myscopedpackage:registry=https://artifactory.example.com/artifactory/api/npm/myrepo/
```

renovate.json
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "dependencyDashboard": true,
  "lockFileMaintenance": {
    "enabled": true,
    "schedule": [
      "at any time"
    ]
  }
}
```

In the errors below we can see that the npm-configs are not passed to the sidecar processes it seems.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: lock file error (repository=myrepo/renovate-test, branch=renovate/test)
       "err": {
         "name": "ExecError",
         "cmd": "/bin/sh -c yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts",
         "stderr": "error Couldn't find package \"@myscopedpackage/mysdk\" on the \"npm\" registry.\n",
         "stdout": "yarn install v1.22.19\n[1/4] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n",
         "options": {
           "cwd": "/tmp/renovate/repos/gitlab/myrepo/renovate-test",
           "encoding": "utf-8",
           "env": {
             "NPM_CONFIG_CACHE": "/tmp/renovate/cache/others/npm",
             "npm_config_store": "/tmp/renovate/cache/others/pnpm",
             "CI": "true",
             "YARN_CACHE_FOLDER": "/tmp/renovate/cache/others/yarn",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/home/ubuntu/bin:/opt/buildpack/tools/python/3.11.1/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "BUILDPACK_CACHE_DIR": "/tmp/renovate/cache/containerbase",
             "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/cache/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "message": "Command failed: yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\nerror Couldn't find package \"@myscopedpackage/mysdk\" on the \"npm\" registry.\n",
         "stack": "ExecError: Command failed: yarn install --ignore-engines --ignore-platform --network-timeout 100000 --ignore-scripts\nerror Couldn't find package \"@myscopedpackage/mysdk\" on the \"npm\" registry.\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/lib/util/exec/common.ts:99:11)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)"
       },
       "type": "yarn"
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by Breee** [comment]
@rarkins before i create a minimal example:  do you have an artifactory instance (or any other private registry)  available for testing yarn?

**Comment by rarkins** [comment]
No, but I think you can spin up free Artifactory Cloud instances

**Comment by viceice** [comment]
you should better switch to install binary source, that mod can now be used with the slim image too.

**Comment by rarkins** [comment]
BTW if the `.npmrc` is in the repo, then Renovate doesn't need to "pass" it because the whole repo is mapped to the sidecar

**Comment by Breee** [comment]
It should not query against `https://yarnpkg.com`, the `.npmrc` clearly states the scoped package.
Is there any configuration that is influencing the yarn registry used?

**Comment by Breee** [comment]
> you should better switch to install binary source, that mod can now be used with the slim image too.

Is `--binary-source=install`  as flexible as `--binary-source=docker` ?

**Comment by viceice** [comment]
> > you should better switch to install binary source, that mod can now be used with the slim image too.
> 
> Is `--binary-source=install`  as flexible as `--binary-source=docker` ? 
> 

yes, it's doing same but without docker sidecar container
