### ISSUE TITLE
Host rules migration not working as expected

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#20539]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.148.0

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Host rules are migrated twice and the first migration effects the next one such that it can't serve its purpose.
https://github.com/renovatebot/renovate/blob/35baf4aaa0d327ec83755988ce7074831e0f1dfc/lib/config/migrations/custom/host-rules-migration.ts#L28-L37
https://github.com/renovatebot/renovate/blob/35baf4aaa0d327ec83755988ce7074831e0f1dfc/lib/util/host-rules.ts#L18-L38
The custom migration migrates `LegacyHostRule` options to `matchHost` (first come precedence if more than one legacy option is present)
And later `migrateRule` function does the same but instead it throws an error if more than 1 legacy option is present.
But `migrateRule` will never be called with legacy options as the previous config-migration already takes care of it. 

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Checking for config file in C:\Users\LENOVO\Desktop\Whitesource\renovate/config.js
 WARN: Config needs migrating
       "originalConfig": {
         "token": "***********",
         "repositories": ["RahulGautamSingh-testing/merge3"],
         "hostRules": [
           {
             "baseUrl": "https://some.domain.com/",
             "domainName": "domain.com",
             "matchHost": "domain.com/",
             "hostName": "some.domain.com",
             "token": "***********"
           }
         ]
       },
       "migratedConfig": {
         "token": "***********",
         "repositories": ["RahulGautamSingh-testing/merge3"],
         "hostRules": [
           {"matchHost": "https://some.domain.com/", "token": "***********"}
         ]
       }
```

</details>

### Have you created a minimal reproduction repository?

https://github.com/RahulGautamSingh-testing/repro-20539

**Comment by RahulGautamSingh** [comment]
Fix:
We should move the "throw error" to the custom migration and remove the migrateRule function.
This will also reduce the type issues caused due to LegacyHostRule options.

**Comment by rarkins** [comment]
If I had to choose between this type of config warning: https://github.com/RahulGautamSingh-testing/merge3/issues/16 versus the risk of breaking apps and users with #20540, then I think I go for letting them have a config warning.

@viceice wdyt?

**Comment by viceice** [comment]
yes, a config warning issue should the way to go

**Comment by RahulGautamSingh** [comment]
We can just remove this extra migration from the code and add a config-warning-issue to the later part. ie. the `migrateRule`.
This way we do the migration, no breaking changes and we report the config warning to the user as well.
Just need to be sure that matchHost isn't used elsewhere without `migrateRule` being called first.

https://github.com/renovatebot/renovate/blob/35baf4aaa0d327ec83755988ce7074831e0f1dfc/lib/config/migrations/custom/host-rules-migration.ts#L28-L37

**Comment by RahulGautamSingh** [comment]
Currently if we wish to warn user using a message we throw an error and abort the run?
Do you want that to change that ie. warn user but silently migrate the config and process the repo?

**Comment by RahulGautamSingh** [comment]
Checking my understanding..

1. Do not modifiy the `add` function.
2. Detect multiple hosts in the custom migration and throw a config_validation error there, this will stop the processing and that is okay.

This way normal users are warned of the issue and the app also doesn't break.
