### ISSUE TITLE
Dependency Dashboard has list multi packages need to updated, but only create two MRs

### ISSUE THREAD

**Issue by radicalviva** [renovatebot/renovate#20596]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.0.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

<img width="829" alt="image" src="https://user-images.githubusercontent.com/15885774/220969982-1eaad6ac-0f9d-4462-8a61-54cff2650772.png">
We can see only two mr be created, I don't know why.
It's my renovate.json config
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base"]
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
Please create a discussion instead
