### ISSUE TITLE
Dependency Dashboard list multi packages should be updated but only create tow MRs

### ISSUE THREAD

**Issue by radicalviva** [renovatebot/renovate#20597]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.0.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

gitlab

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

<img width="818" alt="image" src="https://user-images.githubusercontent.com/15885774/220979291-95c77ac1-55a2-48f7-a215-338a544a2f93.png">
Here is my renovate.json config
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:base"]
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
This is insufficient information for a bug report. Please create a discussion instead. This issue will be deleted
