### ISSUE TITLE
docker digestPin is no longer working for multiple images in same file

### ISSUE THREAD

**Issue by setchy** [renovatebot/renovate#20625]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

I noticed today that when using docker:digestPin, renovate is no longer updating all image/from statements within the dockerfile.  It would appear that it is only updating the last dependency, although the PR body table contains all of the dependencies and updates

Minimal reproduction
- repository - https://github.com/setchy/renovate-docker-pinning-issue
- pin PR with the two dependencies correctly identified in issue body - https://github.com/setchy/renovate-docker-pinning-issue/pull/5
- only the last dependency was pinned - https://github.com/setchy/renovate-docker-pinning-issue/pull/5/files

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by viceice** [comment]
looks like digest pinning is somehow broken 🤔 

probably caused by latest auto-replace changes.

**Comment by viceice** [comment]
we need debug logs

**Comment by setchy** [comment]
#20627 raised as a fix.
