### ISSUE TITLE
Version pinning doesn't seem to work properly with Gradle Version Catalogs

### ISSUE THREAD

**Issue by eirnym** [renovatebot/renovate#20632]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

I have a specific rule to pin major versions in one of my gradle version catalogs as shown below. After the upgrade I've got [a PR to upgrade version 4.x to 7.x](https://github.com/jsonschema2dataclass/js2d-gradle/pull/697). Problem has been introduced by changing dependencies to Gradle Version Catalog instead of direct versioning.

FYI: `matchFiles` and `matchPaths` nodes doesn't make any difference.

public repo: https://github.com/jsonschema2dataclass/js2d-gradle

<details><summary>Renovate configuration</summary>
```json
      {
        "description": [
          "Disable updating AGP compatibility dependencies. Allow changes in minor and patches."
        ],
        "matchPackageNames": [
          "com.android.tools.build:gradle"
        ],
        "matchPaths": [
          "gradle/agp.versions.toml"
        ],
        "matchUpdateTypes": [
          "major"
        ],
        "enabled": false
      }
```
</details>

this file contents are:

<details><summary>Gradle version catalog contents</summary>
[libraries]
android-gradle-v4x = { module = "com.android.tools.build:gradle", version = "4.2.2" }
android-gradle-v7x = { module = "com.android.tools.build:gradle", version = "7.4.1" }
</details>

### Relevant debug logs

<details><summary>Logs</summary>

```
https://gist.github.com/eirnym/ca065a0b42cf2ec13c12b337f5ab3047
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Please isolate this into a _minimal_ reproduction repo (see instructions above)
