### ISSUE TITLE
Get GitHub App Installation token directly

### ISSUE THREAD

**Issue by norman-zon** [renovatebot/renovate#20689]
### What would you like Renovate to be able to do?

As far as I can tell from the [current docs](https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app) Renovate needs a [GitHub App Installation token](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-an-installation), which the user has to supply via CLI or ENV.

Regarding that App Installation tokens have a lifetime of 1h, one would need to implement a sidecar (if running on Kubernetes) or some other reoccurring job to regularly update the token.

I would very much prefer, if Renovate would be able to [create a JWT](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-with-github-apps#generating-a-json-web-token-jwt) from the **AppId** and the **App private key**(PEM) and use the JWT to create a fresh App Installation token on each run.

### If you have any ideas on how this should be implemented, please tell us here.

Renovate would have to construct a JWT [as documented by Github](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-with-github-apps#generating-a-json-web-token-jwt) to pull a fresh App Installation token when the old one is running out of TTL, or even on every run.

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
This has been discussed before and would require too many changes to our current platform/token architecture
