### ISSUE TITLE
Workflow to comment on converted discussions

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#20696]
### Describe the proposed change(s).

I'd like a workflow which runs on discussion creation and detects if it's been converted from an issue and if so adds a comment asking the user to consider creating discussions in future, so we don't have to type it manually.

I think we could look at discussion labels because at time of creation they'll still say e.g. `type:bug` or `type:feature`.

Would be great if the action could then remove any labels if so.

**Comment by HonkingGoose** [comment]
We now use this configuration for our `label-actions` bot, the bot comments on the _issue_ though: https://github.com/renovatebot/renovate/blob/80ccbb084fe7704fa88c64656f63b481d027a368/.github/label-actions.yml#L169-L185

I don't know if you still want to keep this issue open and search for an action/bot that can comment on discussion creation?

**Comment by rarkins** [comment]
Will close this one
