### ISSUE TITLE
Renovate opens security PRs for issues which are already fixed

### ISSUE THREAD

**Issue by uhthomas** [renovatebot/renovate#20706]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.153.3

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

N/A

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate will continuously create security PRs for some dependencies, even though the security fix has already been applied. In our case, we're finding that this security advisory is the culprit:

https://github.com/cloudflare/cloudflared/security/advisories/GHSA-hgwp-4vp4-qmm2

The project uses a non-standard form of versioning (<year>.<month>.<minor>) which could be causing problems.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by uhthomas** [comment]
Sorry @rarkins just going to link that now.

**Comment by uhthomas** [comment]
This might actually be a bigger issue than just Renovate. GitHub's dependabot also things this is a problem.

<img width="1512" alt="Screenshot 2023-03-02 at 10 46 05" src="https://user-images.githubusercontent.com/9749173/222406814-291c01e0-8382-49b8-b57b-23e305737423.png">

@rarkins Here's the reproduction repo and corresponding bad PR.

https://github.com/uhthomas/renovate20706/pull/4

This is also a problem when using [osv](https://osv.dev/).

**Comment by rarkins** [comment]
If the problem is OSV data, then this is not a Renovate bug and can be deleted. Renovate will follow what OSV and/or Dependabot alerts say to, and is not doing anything "bad" when it does

**Comment by uhthomas** [comment]
I see, thanks @rarkins. I thought it could be to do with how Renovate was matching versions, but presumably this isn't the case? Do you have any guidance on how to open an upstream issue with the vulnerability databases?

**Comment by uhthomas** [comment]
Following up on "and is not doing anything "bad" when it does". I agree it's not _bad_, but it is incorrect and likely to contribute to alert fatigue. Security PRs should be taken seriously, and it's not good for anyone if some security PRs are actually ignorable. Especially if the dependency were to have a new vulnerability at some point in the future, it may go unnoticed due to the existing noise.

**Comment by rarkins** [comment]
That's faulty logic, sorry. With the same logic, you could raise bugs here for any package manager bug you find too (e.g. a new version of npm creates invalid PRs) and justify the Renovate bug report by saying "it will add to PR fatigue". 

I will convert this into a discussion now. Please note this new guidance we added to this repo yesterday:

![image](https://user-images.githubusercontent.com/6311784/222421770-fea36e60-7b95-433b-a4eb-8416bf4adf56.png)
