### ISSUE TITLE
Renovate don't like Pre-commit.io

### ISSUE THREAD

**Issue by sbrunner** [renovatebot/renovate#20723]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate don't like the commit done by precommit.io and want re revert it:
See result: 
https://github.com/sbrunner/docker-compose/pull/5 (362 hidden item during the conflict)

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
Please create a discussion instead. This issue will be deleted
