### ISSUE TITLE
Bitbucket Cloud: initialize repos with development branch

### ISSUE THREAD

**Issue by setchy** [renovatebot/renovate#20802]
### What would you like Renovate to be able to do?

Use development branch to initialize Bitbucket Cloud repositories.

Bitbucket Cloud supports a [variety of branching models](https://support.atlassian.com/bitbucket-cloud/docs/branch-a-repository/#The-branching-model), which are configured at the repository level.

Two of importance to this feature request are

- **Development branch** - this is where new feature branches are targeted, commonly `main` or `master` for trunk-based development and `develop` for git-flow.  This is configured under _Repository Details >> Worklow >> Branching Model_
- **Main branch** - this is configured under _Repository Details >> Advanced >> Main branch_.  Commonly this is left set to `main` or `master` regardless of trunk-based, git-flow or other workflow

At present, when Bitbucket Cloud repositories are initialized, it sets the defaultBranch to be the repositories **main branch** instead of the preferred **development branch**.  This means that for repositories using non trunk-based workflows, Renovate PRs will be targeting the wrong branch for their workflow.

This same situation was discussed on https://github.com/renovatebot/renovate/discussions/11739 a few years back with a suggested workaround of using the [baseBranches](https://docs.renovatebot.com/configuration-options/#basebranches).  

This feature request would remove the need for such a workaround.

### If you have any ideas on how this should be implemented, please tell us here.

Update the Bitbucket repositories initialization to fetch the **development branch** from the [REST API: Branching Model for the Repository](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-branching-model/#api-repositories-workspace-repo-slug-branching-model-get) and set this as the Renovate repository default branch.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by viceice** [comment]
the new behavior should be configurable and disabled by default, so it's not breaking.

then a user can configure it on global or repo level.

**Comment by viceice** [comment]
i think this can be configurable via repo config. do we initialize the repo before fetching the config? 🤔

**Comment by rarkins** [comment]
Yes, to find the default branch for instance (so we know where to look for config)
