### ISSUE TITLE
VSTS - PR not abandoned

### ISSUE THREAD

**Issue by jycouet** [renovatebot/renovate#2082]
#### This is a:

- [x] Bug report (non-security related)
- [ ] Feature request
- [ ] I'm not sure which of those it is

#### I'm using:

- [ ] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [ ] Self-hosted GitLab
- [x] Self-hosted VSTS

#### Please describe the issue:

When renovate delete a renovate branch (because the dep was resolved somewhere else) it should also abandon the PR.

I will have a look later

**Comment by rarkins** [comment]
Yes, if we delete a branch what we should do is this:
1. Rename the PR to add (" - autoclosed")
2. Delete the branch
3. Close the PR (if VSTS doesn't do that automatically)
