### ISSUE TITLE
Renovate only patches package-lock.json, not package.json

### ISSUE THREAD

**Issue by jessehouwing** [renovatebot/renovate#20846]
### How are you running Renovate?

Self-hosted on GitHub Actions on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

35.0.0

### If you're self-hosting Renovate, select which platform you are using.

Windows

### If you're self-hosting Renovate, tell us what version of the platform you run.

Github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

see:
https://github.com/microsoft/azure-devops-extension-tasks/pull/381
https://github.com/microsoft/azure-devops-extension-tasks/actions/runs/4384446516/jobs/7675931768

As of 35.0.0 renovate only patches the `package-lock.json`, but not the `package.json`.

Last successful run that created pull requests did patch both the package and lock files:
https://github.com/microsoft/azure-devops-extension-tasks/actions/runs/4256868933/jobs/7406283477

### Relevant debug logs

<details><summary>Logs</summary>

```

```

</details>

[log.txt](https://github.com/renovatebot/renovate/files/10942198/log.txt)

### Have you created a minimal reproduction repository?

I have read the minimal reproductions documentation and linked to such a repository in the bug description

**Comment by rarkins** [comment]
Which repo is the minimal reproduction?

**Comment by jessehouwing** [comment]
it's not minimal-minimal yet. Haven't been able to create one, but it happens here:
https://github.com/microsoft/azure-devops-extension-tasks

Specifically, when trying to patch this project (which is pretty minimal by itself):
https://github.com/microsoft/azure-devops-extension-tasks/tree/main/BuildTasks/TfxInstaller/v4

And used to work prior to 35.0.0.

The call is:

```
npm install renovate@^35
npm exec -- renovate --platform=github --include-forks=true --enabled-managers="npm,azure-pipelines,github-actions" Microsoft/azure-devops-extension-tasks
```

Revering to 34 fixes things:
```
npm install renovate@^34
npm exec -- renovate --platform=github --include-forks=true --enabled-managers="npm,azure-pipelines,github-actions" Microsoft/azure-devops-extension-tasks
```

**Comment by jessehouwing** [comment]
I'm proceeding in manually patching the repo, as I currently don't have the time to undress this repo to seek a more minimal reproduction.

**Comment by jessehouwing** [comment]
Here is a fork that's at the impacted version:
https://github.com/jessehouwing/azure-devops-extension-tasks-backup

**Comment by rarkins** [comment]
It's a pretty heavy repro (20+ lockfiles needing separate update in the same PR) so hard to debug

**Comment by rarkins** [comment]
Is this the _wrong_ PR reproduced? https://github.com/renovate-reproductions/20846/pull/1/files

The one you linked to above now has zero files and was autoclosed

**Comment by rarkins** [comment]
I think I know the answer to this.

- You're running with v35
- v35 included a change where it now defaults to rangeStrategy=update-lockfile when rangeStrategy=auto, and you are using `config:base` so that's what you got
- As a result, for the first time ever, you are getting "lock file only" PRs when you have ranged dependencies in `package.json`

It's not a mistake or a bug. If you want to avoid lockfile-only updates, configure `rangeStrategy=replace` to revert back to old behavior.
