### ISSUE TITLE
platform(github): unable to detect edited pr target branch

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#20915]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate is unable to detect that a pr is edited, when user manually changes the `targetBranch` of the update PR

This happens because the `targetBranch` isn't part of `getBranchPr` result for `github`due to the [coerce ](https://github.com/renovatebot/renovate/blob/39caa803157de4d1ec245d7c1aa5663bcf073639/lib/modules/platform/github/common.ts#L10)function not including it.(Not sure why?)
Thus `targetBranch=undefined` and the following code can't detect if user edited the target branch
https://github.com/renovatebot/renovate/blob/39caa803157de4d1ec245d7c1aa5663bcf073639/lib/workers/repository/update/branch/index.ts#L201-L205

I think this bug was introduced after this [merge](https://github.com/renovatebot/renovate/pull/14907/files#diff-02818e53b112f2984e86a70880277589bd4f84b1b6ac5f0af2343cf97dd30b7d)

Reproduction: https://github.com/RahulGautamSingh-testing/nvmrc-matching/pull/2

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have read the minimal reproductions documentation and linked to such a repository in the bug description

**Comment by rarkins** [comment]
Sounds like an easy fix? The main challenge may be the cache

**Comment by RahulGautamSingh** [comment]
If we add targetBranch the existing cache will be invalidated right and reset. Or are their more layers to it?

**Comment by rarkins** [comment]
I'm not sure we can detect why the target branch changed without a cache. Otherwise, these two scenarios seem the same:
- Renovate config changed, or
- Renovate config unchanged, but user manually changed the target

**Comment by RahulGautamSingh** [comment]
Got it.
Adding the fix which uses cache to detect if config changed or user chaged the target branch in the same PR.

**Comment by viceice** [comment]
can we add the original target branch to the renovate html comment? that way we can detect it without cache, as long as the platform supports HTML comment

**Comment by RahulGautamSingh** [comment]
Sounds good to me I will try it out. We already add hash to the PR-body so it should be doable.
