### ISSUE TITLE
RegExp in commitMessage template isn't applied

### ISSUE THREAD

**Issue by auke-** [renovatebot/renovate#20957]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

v34.160.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When using the `replace` directive in the `commitMessage` template the regular expression isn't applied.

The background of this issue is https://github.com/renovatebot/renovate/issues/2893, where in our case long nested paths cause long commit subject lines which is rejected by our commitlinter.

The following pattern should remove all path components but two, which works if executed in a JavaScript environment:
```javascript
const find = '[^ ]+(\/[^\/ ]+\/[^\/ ]+)'
const replace = '...$1'

const context = 'our-docker-registry/some/nested/path/to/a/docker/image docker tag'

console.log(context.replace(new RegExp(find, 'g'), replace))

> ".../docker/image docker tag"
```

Unfortunately it doesn't work when applied to the `commitMessage` template:
```json
"commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}} {{{replace '[^ ]+(\/[^\/ ]+\/[^\/ ]+)' '...$1' commitMessageTopic}}} {{{commitMessageExtra}}} {{{commitMessageSuffix}}}"
```

I have confirmed that the `commitMessage` template is used and that `commitMessageTopic` contains the value which we want to truncate, but the original value is used and the pattern isn't applied.

I can't link to a eproduction repository since we use a selfhosted environment. 

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by rarkins** [comment]
You may be experiencing the problem in a private repo, but that itself does not prevent you from reproducing it in a public repo

**Comment by auke-** [comment]
Reproducer available at https://github.com/auke-/renovate-20957

The commit in the pull request does contain the debug markers (`--`) but still contains the full docker url:
https://github.com/auke-/renovate-20957/pull/1/commits

**Comment by rarkins** [comment]
Can you reproduce this with a simpler regex? i.e. narrow down to whether:
- no regex at all works, or
- a moderately complex regex you're trying doesn't work

**Comment by auke-** [comment]
Non regexp doesn't work either (see reproducer)

**Comment by rarkins** [comment]
I suspect this is because `commitMessageTopic` is itself a template and they are being evaluated from outside in not inside out

**Comment by auke-** [comment]
This is really inconvenient. Moving the logic to `commitMessageTopic` doesn't work either:
- it is used in both the commit message and the pr title
- when a specific package rule defines commitMessageTopic our config isn't used
- the Docker datasource defines [all kinds of logic](https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/index.ts#L349-L371) to define  commitMessageTopic which we can't duplicate in or config

Do you have any ideas for another approach? Is it somehow possible to enforce the evaluation of the inner template before evaluating the replace directive?

**Comment by rarkins** [comment]
No ideas. We are deferring this logic to handlebars

**Comment by rarkins** [comment]
This does not seem to be a bug in Renovate so I will close, please start a discussion if you wish to continue
