### ISSUE TITLE
Add support for `plugin(...)` definitions in inlined Gradle version catalog

### ISSUE THREAD

**Issue by igorwojda** [renovatebot/renovate#20981]
### What would you like Renovate to be able to do?

Allow renovate to discover and update dependencies defined by `plugin` element:

```kotlin
// settings.gradle.kts

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            version("kotlinVersion", "1.8.10")

            plugin("springframework-boot", "org.springframework.boot").version("3.0.2") // not supported

            library("junitJupiterEngine", "org.junit.jupiter", "junit-jupiter-engine").version("5.9.2")
        }
    }
}
```

### If you have any ideas on how this should be implemented, please tell us here.

This is similar to the Gradle verison catalog defined in the `libs.versions.toml` file.

[As mentioned](https://github.com/renovatebot/renovate/discussions/20936#discussioncomment-5321778) by @Churro adding support for `plugins` should be simple.

### Is this a feature you are interested in implementing yourself?

No

**Comment by Churro** [comment]
This has already been solved by https://github.com/renovatebot/renovate/pull/20969

**Comment by igorwojda** [comment]
Wow, that was fast! Amazing work @Churro
