### ISSUE TITLE
Issue/Discussion template defaults can lead to incorrect submissions

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#21034]
### Describe the proposed change(s).

I notice sometimes people submitting invalid information, I think this is often caused by them simply leaving the default value, such as:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/6311784/226161755-0636d4eb-4a4c-406f-a5b3-f3891c74b62a.png">

Sometimes we could fix this by switching defaults, but at other times we really want to make sure that users have *selected* something and not just left it as default. Do we need a "dummy" default such as "--Please select a value--" in such cases?

**Comment by HonkingGoose** [comment]
Found a "feature request" for GitHub to edit the Forms feature so it validates users picked something other than the "default/dummy" value:

- https://github.com/community/community/discussions/42187
