### ISSUE TITLE
Refactor got use

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2105]
Ideas:
- [ ] Stop using `gh-got` and `gl-got` and instead use our own `got` wrapper common for all APIs
- [ ] Perform pagination in this wrapper (controlled via options)
- [ ] Perform authentication in this wrapper
- [ ] Maybe configure/perform retries in this wrapper, if `got`'s own behaviour doesn't suit
- [ ] Perform caching in this layer (e.g. cache all GET requests for duration of repository renovation)

- [ ] First step would be to remove gh-got/gl-got dependencies. To do that, we need to (a) convert `GITXXX_TOKEN` to `Authorization` header, and (b) pass `json: true` through. Basically a subset of `gh-got`

**Comment by rarkins** [comment]
We can also handle credentials here and avoid the messiness of env variable swapping

**Comment by rarkins** [comment]
Username/password support: http://stackabuse.com/the-node-js-request-module/

**Comment by rarkins** [comment]
got has now updated to v9, although I plan to wait 1-2 weeks to see if any important bugs are raised. It now supports more configurable retries, which may be able to reduce the amount of retry logic we need in our own code.

**Comment by dylang** [comment]
`gh-got` supports passing in the token, it doesn't have to be an env variable. 

https://github.com/sindresorhus/gh-got#usage

**Comment by rarkins** [comment]
Waiting on #2423
