### ISSUE TITLE
save metadata embedded in the Branch or PR Name

### ISSUE THREAD

**Issue by zisuu** [renovatebot/renovate#21105]
### Describe the problem
We have the followig renovate.json config in our Bitbucket Repository:
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    ":disableDependencyDashboard",
    ":semanticCommits",
    ":semanticCommitTypeAll(chore)",
    ":autodetectRangeStrategy",
    ":prHourlyLimit2",
    ":prConcurrentLimit20",
    ":preserveSemverRanges",
    "workarounds:all",
    "schedule:earlyMondays"
  ],
  "packageRules": [
    {
      "matchUpdateTypes": [
        "major"
      ],
      "excludePackagePatterns": [
        "^Com\.Example\..*$"
      ],
      "groupName": "all major dependencies (except com.example)",
      "groupSlug": "all-major-except-com-example"
    },
    {
      "matchUpdateTypes": [
        "minor",
        "patch"
      ],
      "excludePackagePatterns": [
        "^Com\.Example\..*$"
      ],
      "groupName": "all major dependencies (except com.example)",
      "groupSlug": "all-major-except-com-example"
    },
    {
      "matchDatasources": ["nuget"],
      "stabilityDays": 5
    }
  ]
}

We face the following Problem: Renovate uses the branch name and PR title like a cache key. If the same key exists and the PR was declined, then we ignore the PR. Cache keys can cause problems: Let's say you have an "All non-major updates" PR. If you decline the PR, and Renovate ignores it based on the PR title, then you would never get a non-major update again.

We have exactly this Problem. We cannot change the way we work/group the packages, so there is currently no way for us to use Renovate because we would either get to many PRs, or at some point none at all.

### Additional context (if not clear)
Dont get any new PRs from Renovate? This can have various reasons. First you need to know that Renovate does not keep any kind of database/state of its own about open or declined Pull Requests. Instead, it uses the code platform's APIs to search and find such PRs. Locating of existing PRs - whether open or declined - is done by matching both the branch name (e.g. renovate/lodash-4.x) and Pull Request title (e.g. Update lodash to v4.17.21). In cases like the above, there is typically at most one existing PR with the desired branch + title combination. When grouping is enabled by users, and PRs have titles like "All non-major updates", then there may be multiple past PRs which match.

As described above, Renovate PRs normally have some uniqueness in their title relating to the version in the upgrade. In such cases, if a user declines such a PR, it can be inferred that they don't want to see it again in future. For example, they wish to ignore lodash@4.17.21. In such cases, new PRs won't be created until the branch+title uniqueness exists again, such as if there is a lodash@4.17.22. Similarly in the case of major updates (such as "Update lodash to v4") then it can be inferred that the user wishes to ignore all of v4 of lodash, even when newer v4 versions are available.

### If you have any ideas on how this should be implemented, please tell us here.

I know there are already a few other Discussions and Issues about this, but I don't think this idea has been discussed yet:

### Describe the solution you'd like
Other tools use a hash for all updated dependencies (NuKeeper). That leads to the situation in which Renovate would create a new PR if just one dependency changes. Then the old PR has to be declined manually, which is fine. But it doesn't create a new PR if it is exactly the same as the old one.

We would need to have the Option to keep/save metadata about the artifacts and versions the PR/Branch contains, with the goal that Renovate is capable of identifying the exact files and packages + versions that PR contains and not just use the branch name and PR title as cache key, which is not sufficient in our case. Is it possible to empower Renovate to put a hashcode with the metadata (identifying the exact files and packages + versions) in the name of the PR or Branch?

### Describe alternatives you've considered

- We tried the default behaviour, which ended up in getting no more PRs at all, since they "key" which Renovate Checks was declined.
- As workaround we tried the Branch Prefix Config Option "additionalBranchPrefix" and injected the current date which allows us to have individual Branchnames (e.g. renovate/20230322-com.example.location.organization.streamapi-2.x and renovate/20230322-all-non-major-except-com-example). But as you can imagine this is not a real solution for us since it's flooding us with Renovate PRs.
- currently most obvious: continue using NuKeeper and not switching to Renovate

### Is this a feature you are interested in implementing yourself?

No

**Comment by rarkins** [comment]
See #21089

Please create a discussion if you wish to discuss additional requirements like the above
