### ISSUE TITLE
Test lockFileMaintenance with npm 8 vs 9

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#21125]
### Describe the proposed change(s).

Someone things that Renovate converted their v2 lockfile project to v3 lockfile as part of lockFileMaintenance. I would like to try to reproduce this and see if it happens when binarySource=install or binarySource=docker.

Ideally if the existing lock file uses lockfileVersion=2 then we'd make sure we use npm <9

**Comment by RahulGautamSingh** [comment]
We choose the `npm` version constraints based on the config user adds and the version of lock-file.
Also the code below ensures that we chose `npm<9` when `lockFileVersion=2` 
https://github.com/renovatebot/renovate/blob/325e713d83bf107ca48f300b664b6c93090e4563/lib/modules/manager/npm/extract/locked-versions.ts#L54-L82

Further here is a [reproduction](https://github.com/RahulGautamSingh-testing/reno-npm/pull/3/files)

**Comment by RahulGautamSingh** [comment]
We should update `8.19.3` -> `8.19.4` as this was the last release of `8.x` version. Is it necesssary or we will be fine without it?

**Comment by rarkins** [comment]
It doesn't really matter too much but it can be updated
