### ISSUE TITLE
Preset `group:pixijsMonorepo` does not work

### ISSUE THREAD

**Issue by latin-1** [renovatebot/renovate#21393]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

PixiJS now has a different repo url than the one in the preset.

Repo: https://github.com/pixijs/pixijs

Preset `monorepo:pixijs`:
```json
{
  "matchSourceUrls": [
    "https://github.com/pixijs/pixi.js"
  ]
}
```

### Have you created a minimal reproduction repository?

Placeholder value, please select the correct response from the dropdown

**Comment by rarkins** [comment]
It's not a Renovate bug if another repo renames itself
