### ISSUE TITLE
Review GitHub Action cache eviction behavior

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#21447]
### Describe the proposed change(s).

GitHub now shows the number of caches, and the total filesize, see [`renovatebot/renovate` cache overview](https://github.com/renovatebot/renovate/actions/caches). GitHub tells us we're using **147 caches** and that we're over the 10 GB storage limit:

> **Approaching total cache storage limit** (9.82 GB of 10 GB Used)
> Least recently used caches will be automatically evicted to limit the total cache storage to 10 GB. [Learn more about cache usage.](https://docs.github.com/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy)

This _may_ cause problems: [^quote]

> **Usage limits and eviction policy**
>
> GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 10 GB.
> 
> If you exceed the limit, GitHub will save the new cache but will begin evicting caches until the total size is less than the repository limit. The cache eviction process may cause cache thrashing, where caches are created and deleted at a high frequency. To reduce this, you can review the caches for a repository and take corrective steps, such as removing caching from specific workflows. For more information, see "[Managing caches](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches)."

The [GitHub Docs, force deleting cache entries](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries) explains how we can configure our workflows so they automatically delete the PR's cache once the PR is merged. This may reduce "cache trashing", but I don't know if that causes problems in some other way.

I'll let @JamieMagee or @viceice review the docs, check the cache dashboard and decide if we have a problem, and how to fix the problem. 😉 

[^quote]: [GitHub Docs, usage limits and eviction policy](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy)

**Comment by viceice** [comment]
i think we should check if we can skip cache creation on merge queue branches

**Comment by zharinov** [comment]
Is my understanding correct that in theory merge queue branches could use previously saved branch cache, but never do this because of caching policy? I.e. we can reuse the cache created in `main` branch, but this is pretty much all cross-branch sharing we have?

**Comment by zharinov** [comment]
If GitHub evicts oldest caches first, maybe it's actually not a big problem for us

**Comment by HonkingGoose** [comment]
### GitHub evicts oldest caches first

Here's GitHub's warning message on our action cache overview page: [^quote]

> Least recently used caches will be automatically evicted to limit the total cache storage to 10 GB.

[^quote]: https://github.com/renovatebot/renovate/actions/caches

### Merge queue re-using caches?

> Is my understanding correct that while merge queue branches could reuse PR branch cache theoretically, but never do this because of caching policy? I.e. we can reuse the cache created in `main` branch, but this is pretty much all cross-branch sharing we have?

I don't know. 😄 The GitHub docs say this is how Merge Queues work: [^docs]

> The merge queue creates temporary branches with a special prefix to validate pull request changes. The changes in the pull request are then grouped into a `merge_group` with the latest version of the `base_branch` as well as changes ahead of it in the queue. GitHub will merge all these changes into `base_branch` once the checks required by the branch protections of `base_branch` pass.

[^docs]: [GitHub Docs, about merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues)

**Comment by zharinov** [comment]
I think we're okay with our current caching approach, what I see in recent workflows is mostly cache hits

**Comment by HonkingGoose** [comment]
Let's close this issue then.
