### ISSUE TITLE
Switch `cron` library

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#21523]
### What would you like Renovate to be able to do?

When you enter this config:

```json
  "lockFileMaintenance": {
    "enabled": true,
    "schedule": ["every 2 months on the first saturday of the month"]
  },
```

The `later` library returns an error code:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/6311784/231457103-d69d7547-be11-42cd-a466-d5d37982f50f.png">

We could support such schedules by switching to a different `cron` libary, that supports `#` and `L`.

For the full context see discussion https://github.com/renovatebot/renovate/discussions/21427.

### If you have any ideas on how this should be implemented, please tell us here.

A user suggested the [`cron-parser` npm package](https://www.npmjs.com/package/cron-parser).

I'll let the maintainers decide what `cron` libary is best for us.

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment]
@rarkins @secustor @JamieMagee do you have any suggestions for a replacement `cron` library?

**Comment by RahulGautamSingh** [comment]
Assigned myself but will be working on this only at the end of this week, so feel free to implement during that time💪
