### ISSUE TITLE
Support changelog files without markdown headings

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2152]
Example Changelog: https://github.com/algolia/algoliasearch-client-javascript/blob/develop/CHANGELOG.md

Example PR: https://github.com/algolia/react-instantsearch/pull/1355

**Comment by Haroenv** [comment]
It's a legacy format, if necessary we can move it to a more machine readable one. Which format reads well?

**Comment by rarkins** [comment]
Pretty much any format where the files use # or ## or ### for each header should be detected already.

**Comment by Haroenv** [comment]
okay, will change the versions to have headers then!

**Comment by Haroenv** [comment]
Now it looks like [this](https://github.com/algolia/algoliasearch-client-javascript/blob/develop/CHANGELOG.md), I guess we'll only see the change on next version, or do you check from GitHub?

**Comment by rarkins** [comment]
We check from GitHub so it should be picked up soon if all is well. We cache changelogs for 1 hour though as they usually don’t change often
