### ISSUE TITLE
Support golang

### ISSUE THREAD

**Issue by petemounce** [renovatebot/renovate#2155]
**What would you like Renovate to be able to do?**

I would love it if renovate had support for upgrading golang dependencies. In my specific case, vendored via https://github.com/golang/dep.

**Describe the solution you'd like**

I would like to be able to 
* enlist a monorepo containing golang code into renovate
* have renovate discover where my golang gopkg.toml is
* integrate into my own internal tooling for managing dependencies (this runs `dep ensure` then updates a `vendor.lock` file containing a digest of the `vendor` tree, to force that tree to contain only the dependencies that are actually in use, and thereby forcing the tooling to be used correctly) when it tries to update my dependencies.

**Describe alternatives you've considered**

Building this myself. But that would force me to also create a project website for such a tool, and yours is better (so's your tool ;) ).

**Comment by rarkins** [comment]
@petemounce does it mean that we need a full local copy of the source code when running `dep ensure` if it’s checking which dependencies are in use?

**Comment by petemounce** [comment]
I _think_ so. We vendor our dependencies, so have that.

**Comment by joseSantacruz** [comment]
Would be great have this feature on my case also with golang/dep

**Comment by mxey** [comment]
Go 1.11 makes Go modules the official dependency management (as a preview). There are no vendored files, just the versions in the go.mod. https://github.com/golang/go/wiki/Modules

**Comment by rarkins** [comment]
Closing in favour of #933 so we don't end up with split discussions
