### ISSUE TITLE
Add dedicated docs for nuget

### ISSUE THREAD

**Issue by samneirinck** [renovatebot/renovate#2156]
**What would you like Renovate to be able to do?**
Have a dedicated language page for .NET on the renovate website. It should describe what are the limitations, and how it works. 

**Describe the solution you'd like**
Add a page under `Language Support`, similar to [Bazel](https://renovatebot.com/docs/bazel/).

PS: I'm willing to take this up

**Comment by rarkins** [comment]
Sounds great to me, thanks

**Comment by tomkerkhove** [comment]
Thanks @samneirinck, was just going to create the same bug.
Feel free to ping me if you need help/proof reading
