### ISSUE TITLE
Make sure dependencies can link to the correct page

### ISSUE THREAD

**Issue by samneirinck** [renovatebot/renovate#2157]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
This is mainly for .NET/nuget, I'm not sure if it's relevant for other package managers. For some packages, the pullrequest to update does not contain a link to the project page. This results in PR's such as [this](https://github.com/tomkerkhove/promitor/pull/76), with just a package name. Ideally, we link to the actual projectUrl if it's available, so we don't have to look up the homepage.

**To Reproduce**
1. Create repository with outdated dependency such as `Swashbuckle.AspNetCore`
2. Let renovate run
3. Check out the PR, there is no link.

**Expected behavior**
The package name should always link to the homepage, whether it's GitHub, a custom page, or anything else specified in the nuspec.

**Comment by tomkerkhove** [comment]
It looks like this is working now - https://github.com/tomkerkhove/promitor/pull/104

**Comment by rarkins** [comment]
Yes it links to the URL if found
