### ISSUE TITLE
Support Clojure package manager

### ISSUE THREAD

**Issue by hden** [renovatebot/renovate#2158]
**What would you like Renovate to be able to do?**
I'd love Renovate to be able to update Clojure dependencies.

**Describe the solution you'd like**
I would like to be able to

* Read dependencies from either `deps.edn` or `project.clj`.
* Propose updates via pull-requests.

**Describe alternatives you've considered**
Building this myself. But obviously Renovate is better.

**Additional context**
- Dependencies specifications
  - [Clojure CLI (deps.edn)](https://clojure.org/guides/deps_and_cli)
  - [Leiningen (project.clj)](https://leiningen.org/)
- Major Repositories
  - Maven Central [API](http://search.maven.org/#api)
  - Clojars [API](https://github.com/clojars/clojars-web/wiki/Data)
- Javascript [edn parser](https://github.com/edn-format/edn/wiki/Implementations)

**Comment by rarkins** [comment]
Hi @hden, thanks for the suggestion and details. I would be happy to include Clojure in Renovate's supported languages/package managers.

Can you confirm that the Clojure CLI and Leiningen approaches are independent and could be implemented separately?

Here is the general approach we take:

1. Locate all dependency files and parse them to extract a list of current dependencies
2. For each dependency, look up the list of available versions to see if any newer are available
3. Patch the dependency file(s) with newer versions
4. Update accompanying lock file, if any

**Comment by hden** [comment]
@rarkins  Yes, AFAIK these tools are independent. The approach looks good. Although like every other build tool we might need to support private repositories.

ref #817

**Comment by rarkins** [comment]
@hden do you mean the package file points to another repository that is private and hosts the dependency? I assume typical use case is that both repositories are owned by same user or org?

**Comment by hden** [comment]
@rarkins Yes that's the typical use case. An edge case is that third-party private repositories can be use by proprietary software e.g. [Datomic](https://gist.github.com/jamesnyika/77c3e281cdfcb3c2452f6eff751bbb17#part-v--configure-your-peers-to-connect-appropriately).

**Comment by rarkins** [comment]
We should be fine to support both public and private same-owner repositories from day 1, just as long as Renovate is installed into both. i.e. the upstream package should also have Renovate installed, even if you choose to deactivate it, or it has no dependencies of its own. Otherwise GitHub would deny us from accessing it.

**Comment by rarkins** [comment]
Actually I should clarify - would you be using it via the hosted app, or self-hosted CLI?

**Comment by hden** [comment]
@rarkins I'll be using the hosted app.
