### ISSUE TITLE
Support nested changelog.md files

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2162]
Currently Renovate does not find/embed `CHANGELOG.md` files for an updated package if that file is not located in the root of the source repository.

Example from `eslint-config-airbnb-base`: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md

The challenge in this particular case is, I don't see anything in the published `package.json` that gives a hint as to the sub-url, e.g. `repository` points to the root:
![image](https://user-images.githubusercontent.com/6311784/41806105-745d38f6-76b7-11e8-9252-9724f14fa440.png)

Cc @ljharb

**Comment by ljharb** [comment]
The convention for monorepos is to publish a link to the root - but since the package name is `eslint-config-airbnb-base`, there'd only be one package.json file in that repo with a "name" field that matches.

**Comment by rarkins** [comment]
Thanks @ljharb. Ideally there’d be a more programmatic way to indicate the changelog location from the `package.json`. Pulling potentially dozens or even hundreds of `package.json` contents in a source repo to work out which one has `name` set to what we want is really inefficient. Maybe in the meantime we can leverage the convention that most would put the package name in the subdirectory name as a shortcut for looking for the right changelog.

**Comment by ljharb** [comment]
id think you can use `find` and `grep` to narrow down the list of package.json files to 1 or 2 relatively trivially.

**Comment by rarkins** [comment]
Unfortunately find and grep would mean we need to clone the full source repo of every dependency we update - also undesirable.

**Comment by rarkins** [comment]
We otherwise don’t have a need to *install* dependencies. And I didn’t think it’s possible to selectively download one file from npmjs without taking the whole archive. Hence why it would be nice to be able to view a changelog for a new release *before* installing but maybe it’s unavoidable.

**Comment by ljharb** [comment]
You could use unpkg.com?

**Comment by ljharb** [comment]
There’s just not a convention for monorepo project package.jsons to link anywhere but the monorepo, so I’m not sure how else to solve it :-/

**Comment by rarkins** [comment]
I think publishing a changelog with the package like you do is a perfectly acceptable approach. If npmjs supported cherry picking files, or a standardised field for changelog info then we’d be fine. They have RFCs open related to the latter too.

In the meantime, unpkg looks like a viable fallback!

**Comment by rarkins** [comment]
Renovate now does attempt to find changelogs in subdirectories, so I'm going to close this. If there's a use case for finding changelogs which are not committed to the repo but are bundled in the npm release, we can have a new issue if a reproduction can be made
