### ISSUE TITLE
Github Actions versioning

### ISSUE THREAD

**Issue by twang817** [renovatebot/renovate#21727]
### What would you like Renovate to be able to do?

It is current practice for Github Actions to move "v1" and "v1.0" tags each time you release a new version.  For example, when releasing v2.1.2, you would update the v2 and v2.1 tags to reflect the latest release.

This is described [here](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management) in their docs.

Currently, you can set versioning to semver-coerced and renovate will coerce these incomplete (or short) version tags.  For example, v2 will become v2.0.0 and v3.4 would become v3.4.0.  Upon running, depending on how you have `separateMajorMinor` set, you will get PRs updating the action to the appropriate full tags.

I would prefer (and I think most users who want to stick with the Github versioning scheme) that renovate treats each short semver tag always as the latest in their respective range, and only provide PRs that preserve the same precision as your current tag.

For example, v2.1 would update to v2.2, but ignore v2.1.x.  Similarly, v2 would update to v3, but ignore v2.3.0.

### If you have any ideas on how this should be implemented, please tell us here.

I have messed around with the versioning api and I believe I have come up with a viable solution.  The idea is to:

a) Always treat a "short" semver as the latest.  For example, this would be the correctly sorted order of these tags: `[v1.1.1, v1.1.2, v1.1.3, v1.1, v1]`
b) Filter release tags to the same precision as the currentVersion tag.  So, for a currentVersion of v1, the only valid tags would have a precision of 1, e.g.: v2, v3, etc.  Similarly, for currentVersion of v1.1, the only valid tags would have a precision of 2, e.g.: v1.1, v1.2, v2.1, etc.

The following implements this:

```typescript
// vim: sts=2 sw=2 ts=2 et ai
import semver, { SemVer } from 'semver';
import { regEx } from '../../../util/regex';
import type { GenericVersion } from '../generic';
import type { VersioningApi } from '../types';
import { api as semverCoerced } from '../semver-coerced'

export const id = 'github-actions';
export const displayName = 'Github Actions';
export const urls = [];
export const supportsRanges = false;

interface GithubActionVersion extends GenericVersion {
  raw: (number | undefined)[]
  coerced: SemVer | null;
  precision: number;
}

function _parse(version: string): GithubActionVersion | null {
  const regx = regEx(
    /^v?(?<major>\d+)(?:\.(?<minor>\d+))?(?:\.(?<patch>\d+))?(?<rest>.+)?/
  );
  const m = regx.exec(version);

  if (!m?.groups) {
    return null;
  }

  const { major, minor, patch, rest: prerelease } = m.groups
  const parts = [major, minor, patch]
  const precision = parts.filter((x) => typeof x !== 'undefined').length
  const release = parts.map((x) => typeof x === 'undefined' ? 0 : Number.parseInt(x, 10));
  const raw = parts.map((x) => typeof x === 'undefined' ? undefined : Number.parseInt(x, 10));
  const coerced = semver.coerce(version)

  return {
    release,
    prerelease,
    raw,
    coerced,
    precision,
  };
}

function isStable(version: string): boolean {
  const parsed = _parse(version);
  return !!(parsed && !parsed.prerelease);
}

function sortVersions(a: string, b: string): number {
  const v1 = _parse(a);
  const v2 = _parse(b);

  if (v1 && v2) {
    if (v1.precision == 3 && v2.precision == 3) {
      return v1.coerced && v2.coerced ? semver.compare(v1.coerced, v2.coerced) : 0;
    }

    for (let n = 0; n < 3; n++) {
      let x = v1.raw[n];
      let y = v2.raw[n];
      if (x !== undefined && y !== undefined) {
        if (x == y) {
          continue;
        }
        return x > y ? 1 : -1;
      }
      else if (x === undefined && y == undefined) {
        return 0;
      }
      else if (x === undefined) {
        return 1;
      }
      else if (y === undefined) {
        return -1;
      }
    }
  }
  throw new Error('error in sortVersions');
}

function isLessThanRange(version: string, range: string): boolean {
  return sortVersions(version, range) < 0
}

function isGreaterThan(version: string, other: string): boolean {
  return sortVersions(version, other) > 0
}

function isCompatible(version: string, current?: string): boolean {
  if (current) {
    let currentVersion = _parse(current);
    let other = _parse(version);
    if (currentVersion && other) {
      return semverCoerced.isVersion(version) && other.precision == currentVersion.precision
    }
  }
  return semverCoerced.isVersion(version);
}

export const api: VersioningApi = {
  equals: semverCoerced.equals,
  getMajor: semverCoerced.getMajor,
  getMinor: semverCoerced.getMinor,
  getPatch: semverCoerced.getPatch,
  isCompatible,
  isGreaterThan,
  isLessThanRange,
  isSingleVersion: semverCoerced.isSingleVersion,
  isStable,
  isValid: semverCoerced.isValid,
  isVersion: semverCoerced.isVersion,
  matches: semverCoerced.matches,
  getSatisfyingVersion: semverCoerced.getSatisfyingVersion,
  minSatisfyingVersion: semverCoerced.minSatisfyingVersion,
  getNewValue: semverCoerced.getNewValue,
  sortVersions,
};
export default api;
```

I could flesh out tests and docs, if there is interest in such a feature.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by twang817** [comment]
Sorry, I'm not sure what to reproduce.  I'm trying to understand if there's interest in a PR that adds github actions versioning.

**Comment by rarkins** [comment]
I'm trying to understand is your use case is already satisfied by Docker versioning

**Comment by viceice** [comment]
yes, try docker versioning, it should do what you want

**Comment by twang817** [comment]
> yes, try docker versioning, it should do what you want

Perfect.  Thank you, I believe this works.
