### ISSUE TITLE
Consistency of glob vs regex across different configuration options

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#21737]
### Describe the proposed change(s).

When it comes to file matching today we have a mix of regex and glob matching, even some legacy string matching.

We should at the minimum ensure that our documentation is clear, and decide if we should do any deprecating or enhancing to provide better consistency.

**Comment by rarkins** [comment]
- [ ] `fileMatch`
- [ ] `ignorePaths`
- [ ] `matchFiles`
- [ ] `matchPaths`
- [ ] `includePaths`
- [ ] `fileFilters`
- [ ] `excludeCommitPaths`

**Comment by viceice** [comment]
`blob` => `glob`?

**Comment by rarkins** [comment]
Yes not sure how I kept typo'ing or autocorrecting that

**Comment by rarkins** [comment]
We could support glob or regex for all fields as long as we have an intuitive way to distinguish between then. e.g. if it starts and ends with `/` (e.g. `/^abc/`) then we know it's regex, otherwise treat it as a glob.

We could also support negative regex matching via a `!/` prefix, e.g. `!/^abc/`.

A challenge is how to handle OR and AND logic when we use a single array. For example if everything in the array is OR then `["/^abc", "!/^abc/"]` matches everything. We could:
- Stick to OR logic, and users need to embed negation into their patterns if needed
- Invent syntax for AND, such as nested arrays (complex..) or something like an `&` prefix, such as `["/^abc", "&!/beta/"]`, which would mean "starts with `abc` and does not contain the string `beta`

**Comment by rarkins** [comment]
Duplicate of #10582
