### ISSUE TITLE
How do I add support for different pypi providers?

### ISSUE THREAD

**Issue by khornberg** [renovatebot/renovate#2181]
#### This is a:

- [ ] Bug report (non-security related)
- [ ] Feature request
- [x] I'm not sure which of those it is

#### I'm using:

- [x] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [ ] Self-hosted GitLab
- [ ] Self-hosted VSTS

#### Please describe the issue:

I see that [public pypi](https://github.com/renovatebot/renovate/blob/master/lib/datasource/pypi.js#L12) is the sensible default. I'd like to make it so that either `PIP_INDEX_URL` from the environment or `--pip-index-url` from the command line would override the host, allowing for private/other hosts.

Where should I get started in writing the test for that?

**Comment by rarkins** [comment]
In this scenario, are you fetching *all* packages from the alternate host, and never querying the public pypi index?

**Comment by destroyerofbuilds** [comment]
I would like to second the request. In my own organization we would like to fetch package metadata from an Artifactory instance (https://www.jfrog.com/confluence/display/RTF/PyPI+Repositories), which mirrors the public PyPI index.

Our Renovate environment is setup with a [`pip.conf`](https://www.jfrog.com/confluence/display/RTF/PyPI+Repositories#PyPIRepositories-UsingaConfigurationFile) file.

Though the same information [could be specified in a project's `requirements.txt`](https://www.jfrog.com/confluence/display/RTF/PyPI+Repositories#PyPIRepositories-UsingaRequirementsFile) files.

**Comment by rarkins** [comment]
@destroyerofbuilds is the `pip.conf` file checked into the repository in the same directory as the `requirements.txt`, or is it in `~/.pip/pip.conf` as in the artifactory example?

**Comment by rarkins** [comment]
Example `pip.conf`:
![image](https://user-images.githubusercontent.com/6311784/42014551-2901312e-7aa3-11e8-9fc7-8ed27b7b1f94.png)

Example from `requirements.txt`:
![image](https://user-images.githubusercontent.com/6311784/42014534-11e762a6-7aa3-11e8-9d8f-813efe2cbfe7.png)

**Comment by rarkins** [comment]
@khornberg you mentioned that you're using the hosted GitHub App, in which case environment variables are not possible

> Instead of the public pypi url would it be appropriate to call a function from another file to resolve which host to use? That way, if the more complex use cases are implemented, the logic is removed from the datasource file.

No, it's best keep the logic within datasource. And initially I think we support just a single index URL.

**Comment by khornberg** [comment]
Ok thanks.

I understand, but did not think about, that for the GitHub App environmental variables are not possible. If only GitHub apps would have a built in config page with which that data would be communicated for the specific installation of the app. I've run into this on my own GH apps :\ 

I assume that if I am running it myself, the env vars would be available.

**Comment by rarkins** [comment]
I don’t think that configuration files are an undue burden and prefer them due to my preference for version controlling everything. I’m not a pip user but putting the URL in requirements.txt sounds better for coordinating between teams too, rather than relying on everyone setting the same environment variable. 

Self hosted version would indeed be able to “see” environment variables but we’d still need code added to extract or datasource to know to look ok for it and interpret it.

**Comment by khornberg** [comment]
I'll go down the route of trying to add something to the datasource file.

I generally agree that config files are not a burden until one has 20 or 300 or any number of repositories that all need the same config. Inheritance of configuration or a centralized configuration for GH apps is lacking but think is probably a more complicated problem that I am aware of GH.

**Comment by destroyerofbuilds** [comment]
> is the pip.conf file checked into the repository in the same directory as the requirements.txt

Our projects do not commit a `pip.conf` file into their repositories.

> or is it in ~/.pip/pip.conf as in the artifactory example

It's in that directory on both our developer's laptops and for our Renovate deployment.
