### ISSUE TITLE
Check Rubygems API

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#21821]
### Describe the proposed change(s).

https://blog.rubygems.org/2023/04/07/dependency-api-deprecation-delayed.html

I _thought_ we should always try `/versions` for Rubygems.org, although we should double check this.

**Comment by zharinov** [comment]
It was weird API, I'll remove it

**Comment by zharinov** [comment]
I think we should add online logging of any hosts falling back to this API. It seems to be a last resort, and we don't want to break support for hosts that don't support anything else.

**Comment by rarkins** [comment]
I think it's ok as long as we don't use it for rubygems.org specifically

**Comment by zharinov** [comment]
Okay, I think we don't do that
