### ISSUE TITLE
Handle rate limit exceeded response for github.initRepo

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#21861]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

The initRepo GraphQL query can return this result:

```json
{
  "level": 20,
  "res": {
    "errors": [
      {
        "type": "RATE_LIMITED",
        "message": "API rate limit exceeded for installation ID 9306189."
      }
    ]
  },
  "msg": "No repository returned",
  "time": "2023-04-27T19:58:46.771Z"
}
```

It should throw a more appropriate error than "repo not found"

### Relevant debug logs

See above

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by RahulGautamSingh-testing** [comment]
**This occurs here:**

https://github.com/renovatebot/renovate/blob/0a4be4a989788fa7f920b1ff8bff3326970aea53/lib/modules/platform/github/index.ts#L389-L402

**Reason:**

We expect `requestGraphQl` to return `GhRepo` type result but actually the returned object is of the type:
`GithubGraphqlResponse` which can also `errors` which we haven't handled.
https://github.com/renovatebot/renovate/blob/0a4be4a989788fa7f920b1ff8bff3326970aea53/lib/util/http/github.ts#L375-L378

https://github.com/renovatebot/renovate/blob/0a4be4a989788fa7f920b1ff8bff3326970aea53/lib/util/http/github.ts#L45-L56

I think we didn't handle it assuming that errors will not have a 200 status code and the catch block will handle them, but that is not the case. `Rate-limited`, error occurs with a 200 status code 🙂. [ref](https://github.com/github/docs/issues/22607#issuecomment-1350193971)

**Comment by RahulGautamSingh** [comment]
**This occurs here:**

https://github.com/renovatebot/renovate/blob/0a4be4a989788fa7f920b1ff8bff3326970aea53/lib/modules/platform/github/index.ts#L389-L402

**Reason:**

We expect `requestGraphQl` to return `GhRepo` type result but actually the returned object is of the type:
`GithubGraphqlResponse` which can also `errors` which we haven't handled.
https://github.com/renovatebot/renovate/blob/0a4be4a989788fa7f920b1ff8bff3326970aea53/lib/util/http/github.ts#L375-L378

https://github.com/renovatebot/renovate/blob/0a4be4a989788fa7f920b1ff8bff3326970aea53/lib/util/http/github.ts#L45-L56

I think we didn't handle it assuming that errors will not have a 200 status code and the catch block will handle them, but that is not the case. `Rate-limited`, error occurs with a 200 status code 🙂. [ref](https://github.com/github/docs/issues/22607#issuecomment-1350193971)
