### ISSUE TITLE
Test logging performance impact

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#21862]
### Describe the proposed change(s).

Proposed approach:

1. Get a repeatable "real" test, like `time yarn start --dry-run=lookup renovatebot/renovate`
2. Remove `bunyan` and any logging, make all `logger.x` calls stubs
3. Time again without logging

In theory this should be the "best case" performance without any logging. If we then decide that our logging is a big performance hit, we need to decide whether:
- we can improve it as-is, or
- try replacing bunyan with pino

**Comment by viceice** [comment]
repo cache should be disabled

**Comment by rarkins** [comment]
I don't mind really - as long as the time taken is stable. In some ways repo cache is better because that represents the "real world" of the hosted app

**Comment by viceice** [comment]
then there should be a first run to update the cache and hopefully no commit between runs, as that would affect extraction time

**Comment by zharinov** [comment]
I think, statistical error is too high for Renovate repository. Instead, I took very simple repository and set `LOG_LEVEL=trace`. The observed logging overhead is 10 seconds, which I guess is something dependency-heavy repositories only can achieve. For `LOG_LEVEL=debug`, I don't see any sufficient difference.

**Comment by rarkins** [comment]
Did you stub out the logging completely? Can you push a branch showing how it was done?

Because it's not the same test to simply lower logging level - much of the overhead can still remain.

**Comment by zharinov** [comment]
https://github.com/renovatebot/renovate/pull/23086

**Comment by rarkins** [comment]
Thanks, that looks valid to me. In this case our conclusion is that our logging _doesn't_ impact performance much at all for debug and lower?

**Comment by zharinov** [comment]
Yes, I think we need to search for bottlenecks somewhere else

**Comment by zharinov** [comment]
Closing it, if you don't mind
