### ISSUE TITLE
Configuration FAQ link on website is a 404

### ISSUE THREAD

**Issue by Arcanemagus** [renovatebot/renovate#2188]
**What Renovate type are you using?**
N/A

**Describe the bug**
The "Configuration FAQ" link from the [Docs](https://renovatebot.com/docs/) page is a 404.

**To Reproduce**

1.  Open the [Docs](https://renovatebot.com/docs/) page
2.  Attempt to click "Configuration FAQ"

**Expected behavior**
A page to load.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rarkins** [comment]
Thanks, it's now fixed
