### ISSUE TITLE
Update image on docker hub

### ISSUE THREAD

**Issue by iMarv** [renovatebot/renovate#2193]
#### This is a:

- [ ] Bug report (non-security related)
- [ ] Feature request
- [x] I'm not sure which of those it is

#### I'm using:

- [ ] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [x] Self-hosted GitLab
- [ ] Self-hosted VSTS

#### Please describe the issue:

The image on DockerHub is one major version behind the repository.
Please update regularly/automate the process

**Comment by rarkins** [comment]
Automated builds are now restored:
![image](https://user-images.githubusercontent.com/6311784/42089525-ca92b666-7b9d-11e8-93ef-c59ba1d48fe3.png)
