### ISSUE TITLE
Bad heading in Renovate's manager docs: `References ## Default config`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#21980]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

The published manager docs have a bad heading:

```
References## Default config
```

Some examples of pages with the bad heading:

- https://docs.renovatebot.com/modules/manager/ansible/
- https://docs.renovatebot.com/modules/manager/cargo/

I suspect any of this code may cause the problem:

https://github.com/renovatebot/renovate/blob/2f3b636f250fa7c9eefaad0f535bdd3fa14a628b/tools/docs/manager.ts#L76-L86

https://github.com/renovatebot/renovate/blob/2f3b636f250fa7c9eefaad0f535bdd3fa14a628b/tools/docs/utils.ts#L51-L59

### Relevant debug logs

No relevant logs. Also no reproduction, because the problem is with our own code.

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by rarkins** [comment]
Is it happening for managers which don't have URLs?
