### ISSUE TITLE
Renovate skip GitLab branches

### ISSUE THREAD

**Issue by sarunint** [renovatebot/renovate#2200]
**What Renovate type are you using?**
Self-hosted Renovate

**Describe the bug**
In GitLab API, the state for open MR is `opened`, this cause this line:

https://github.com/renovatebot/renovate/blob/458cf5742907ae378f05b71482f0422f5eb5c2a2/lib/workers/branch/index.js#L89

to fail.

**To Reproduce**

1.  Use Renovate with GitLab

**Expected behavior**
Renovate should renovate the branch as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/3850197/42128627-ffb82078-7cd9-11e8-89c3-634d56bf9c2c.png)

**Additional context**
Caused by https://github.com/renovatebot/renovate/commit/46fae9473a63dbf21cb89a995f5a24a0a31eabdd

**Comment by rarkins** [comment]
Thanks @sarunint for the detailed bug report, and sorry for the inconvenience. I have added a line to the gitlab platform library to massage `opened` to `open`, which I think should fix this problem. New release should be in a few minutes time.

**Comment by sarunint** [comment]
Thanks!
