### ISSUE TITLE
PR is automerged before CI job starts

### ISSUE THREAD

**Issue by teppeis** [renovatebot/renovate#2201]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
PR was automerged before the CI test job started.

**To Reproduce**
- PR: https://github.com/kintone/plugin-packer/pull/173
- Log: https://renovatebot.com/dashboard#/repos/kintone/plugin-packer/jobs/11570061
- Log(copy): https://gist.github.com/teppeis/eccf051c0c185dde164168e5c416398c

1. Updated branch: 
```
DEBUG: Updating branch renovate/eslint-and-prettier with commit 2892bcd11525e608470ec861cb271fd9eb0e29a5
```
2. Set unpublishSafe status:
```
INFO: Setting branch status (dependencies=prettier,eslint-config-teppeis,eslint, branch=renovate/eslint-and-prettier)
{
  "branchName": "renovate/eslint-and-prettier",
  "context": "renovate/unpublish-safe",
  "state": "success"
}
```
3. Checked branch status
```
DEBUG: branch status check result (dependencies=prettier,eslint-config-teppeis,eslint, branch=renovate/eslint-and-prettier)
{
  "state": "success",
  "statuses": [
    {
      "url": "https://api.github.com/repos/kintone/plugin-packer/statuses/2892bcd11525e608470ec861cb271fd9eb0e29a5",
      "id": 5152688197,
      "node_id": "MDEzOlN0YXR1c0NvbnRleHQ1MTUyNjg4MTk3",
      "state": "success",
      "description": "Packages cannot be unpublished",
      "target_url": "https://renovatebot.com/docs/configuration-reference/configuration-options#unpublishsafe",
      "context": "renovate/unpublish-safe",
      "created_at": "2018-06-29T20:17:19Z",
      "updated_at": "2018-06-29T20:17:19Z"
    }
  ]
}
DEBUG: branchStatus=success
```
4. The response included only unpublishSafe status (other CI jobs have not started yet) and it was success, so the PR was automerged.

**Expected behavior**

A few seconds after the branch was updated, the other CI jobs was executed.
Status check should wait for them or try to automerge in the next renovate job.

New feature `requiredStatusChecks` #1853 may help me.

**Comment by rarkins** [comment]
You can configure your CI as a required status check in *github* config to ensure GitHub never reports it as “green” without first passing CI

**Comment by rarkins** [comment]
Possibly though we should deliberately skip automerge on the same run as we create the branch, unless `requiredStatusChecks` is `null`

**Comment by teppeis** [comment]
@rarkins The github option to protect branch is better for me. Thanks!

**Comment by teppeis** [comment]
@rarkins Thank!

**Comment by destroyerofbuilds** [comment]
> Possibly though we should deliberately skip automerge on the same run as we create the branch, unless requiredStatusChecks is null

I kind of like the option of not needing to hard-code required status into a project's Renovate configuration. My ideal world would not require project maintainers to keep their installed GitHub apps (Or whatever platform they are using) in sync with their Renovate configuration file.

So, yeah, I really like skipping one loop of Renovate.

**Comment by rarkins** [comment]
@destroyerofbuilds FYI I did in fact implement that already:
![image](https://user-images.githubusercontent.com/6311784/42257025-dc27c352-7f54-11e8-9d7d-6f026ea5de35.png)

However I do think that it makes sense that it's your *GitHub* configuration that should include CI as a required status check, not your *Renovate* configuration. With the current setup, if Travis CI is temporarily "down" for instance - e.g. fails to add a "pending" status check immediately as it usually does - then you might still get an untested automerge on the *second* run, if it happens before the CI is able to mark a status check.
