### ISSUE TITLE
Combine Lock file maintenance and other updates in one pull request

### ISSUE THREAD

**Issue by Siilwyn** [renovatebot/renovate#2204]
**What would you like Renovate to be able to do?**
Would like Renovate to update the `package.json` and `package-lock.json` files in one pull request. On a simple repository having two pull requests is pretty annoying since sometimes there is a merge conflict but on monorepos this problem gets frustrating. For example with the 'plek' monorepo with two pull requests: one for [updating dependencies](https://github.com/voorhoede/plek/pull/21/files) and one for [lock file maintenance](https://github.com/voorhoede/plek/pull/22/files). The updating PR touches one lockfile which is also updated by the maintenance, resulting in a merge conflict.

**Describe the solution you'd like**
Instead of having two pull requests I would like one pull request with all changes so no merge conflicts happen.

**Additional context**
Slightly related to: https://github.com/renovatebot/renovate/issues/1342

**Comment by rarkins** [comment]
This feature request makes sense.

Config:
```json
{
  "extends": ["config:semverAllMonthly"]
}
```

I will look into whether this is solvable via config-only or needs a code tweak as well.

**Comment by Siilwyn** [comment]
Great to hear, thank you for taking this up! Love using Renovate. :1st_place_medal:

**Comment by rarkins** [comment]
This should be resolved the next time it runs
