### ISSUE TITLE
Large lists of deps should be split into sections in PR body

### ISSUE THREAD

**Issue by OmgImAlexis** [renovatebot/renovate#2211]
**What would you like Renovate to be able to do?**
It'd be nice to see large lists of deps split into sections for when there are multiple package files as they're currently all shown without any context to which file they belong.

**Additional context**
Please see https://github.com/pymedusa/Medusa/pull/4532#issuecomment-402117488

**Comment by rarkins** [comment]
This example applies to the onboarding PR, where we are not "de-duping". The same principle may apply to the "actual" PRs too, e.g. the Pin one. In those we have some de-duping already however, and you can drill down to see the file diffs.
