### ISSUE TITLE
Print human-readable summaries of cron schedules

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#22267]
### What would you like Renovate to be able to do?

Print human-readable summaries of any cron schedules in config

### If you have any ideas on how this should be implemented, please tell us here.

Use this library: https://github.com/bradymholt/cronstrue

### Is this a feature you are interested in implementing yourself?

No

**Comment by RahulGautamSingh** [comment]
https://github.com/renovatebot/renovate/pull/30472 Fixed
