### ISSUE TITLE
Broken link to "Configure Renovate" on renovatebot.com

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/renovate#2236]
**Describe the bug**
Broken link to "Configure Renovate" on renovatebot.com

**To Reproduce**
1. Click "Onboarding Guide"
2. Navigates to `https://renovatebot.com/docs/getting-started/configure-renovate`

![image](https://user-images.githubusercontent.com/4345663/42418380-c2bbd856-829f-11e8-9bea-61dbb9356871.png)

**Expected behavior**
Navigate to `https://renovatebot.com/docs/configure-renovate/`

Willing to PR but couldn't find renovatebot.com in this repo except for docs.

**Comment by rarkins** [comment]
Thanks, now fixed
