### ISSUE TITLE
pnpm lockedVersion should come from importers, not packages

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#22382]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

Renovate gets `lockedVersion` wrong for some pnpm packages, which results in confused PRs as described in https://github.com/renovatebot/renovate/discussions/22375

Instead of iterating through the `packages` section of the pnpm lock file, Renovate needs to iterate through the `importers` section instead

### Relevant debug logs

<details><summary>Logs</summary>

```
            "currentValue": "^5.1.1",
            "currentVersion": "7.1.1",
            "datasource": "npm",
            "depName": "execa",
            "depType": "devDependencies",
            "fixedVersion": "7.1.1",
            "isSingleVersion": false,
            "lockedVersion": "7.1.1",
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above

**Comment by viceice** [comment]
you forgot the link to the reproduction 🙃

**Comment by rarkins** [comment]
`yarn start --dry-run=lookup renovate-reproductions/22375`

**Comment by RahulGautamSingh** [comment]
Yes on it.

**Comment by rarkins** [comment]
I think it's working but please test it and then tests need updating

**Comment by RahulGautamSingh** [comment]
Is it necessary that there always be `importers`? I tried on [replit ](https://replit.com/@rahtes/pnpm-lock-importersvspackages)and got no importers for simple repos.

**Comment by rarkins** [comment]
Please check the pnpm definitions. The current approach seems wrong

**Comment by viceice** [comment]
We need to check the different lockfile versions. maybe that importers are only available since a specific version.

**Comment by RahulGautamSingh** [comment]
https://github.com/pnpm/spec/blob/master/lockfile/5.2.md#fields-that-are-present-in-dedicated-shrinkwrap
We need to care for lockfile-version>=5 since we only update `pnpm-lock.yaml`. And according to this [comment ](https://github.com/pnpm/spec/issues/4#issuecomment-1419975641)by the maintainer the formatting of the v5 and v6 should be almost same. 

Which means for monorepos we need to look in `importers` section and for normal repos we need to look either in `packages` or `dependencies` section. I would prefer `dependencies` since it willl be smaller in size than `packages`.

**Comment by RahulGautamSingh** [comment]
Lockfile Version <=5 / 5.3 and 6 have different formatting which is still not updated in the official docs. I have commented upstream. When they add a doc we can be 100% sure but tilll then I will have to rely on the lock-file formatting  generated locally 

The difference seems to be in the way the dep-types and version are listed in these lockfiles.
<details>   
<summary>6.0</summary>

```
lockfileVersion: '6.0'

importers:

  .:
    dependencies:
      chalk:
        specifier: 1.1.0
        version: 1.1.0
      pnpm:
        specifier: ^8.5.1
        version: 8.5.1

  package-a:
    dependencies:
      dotenv:
        specifier: ^9.0.2
        version: 9.0.2
```

</details>




<details>

<summary>5.3</summary>

```

lockfileVersion: 5.3

importers:

  .:
    specifiers:
      chalk: 1.1.0
      pnpm: ^6.2.0
    dependencies:
      chalk: 1.1.0
      pnpm: 6.35.1

  package-a:
    specifiers:
      dotenv: ^9.0.2
    dependencies:
      dotenv: 9.0.2
  ```

  </details>
