### ISSUE TITLE
Branch automerge skipped if out of schedule

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#22436]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

If a branch exists, and is configured for automerge, but is not in schedule, then the branch automerge will always be skipped.

The branch is skipped here: https://github.com/renovatebot/renovate/blob/e066924971bb0dc4ebfa0c95c919969c9eba7064/lib/workers/repository/update/branch/index.ts#L314-L320

Whereas branch automerge is not tried until hundreds of lines later: https://github.com/renovatebot/renovate/blob/e066924971bb0dc4ebfa0c95c919969c9eba7064/lib/workers/repository/update/branch/index.ts#L610-L614

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: branch.isModified() = false (repository=my-project/some-repo, branch=renovate/agent-images-automatically)
DEBUG: Checking schedule(before 8am, null) (repository=my-project/some-repo, branch=renovate/agent-images-automatically)
DEBUG: Checking 1 schedule(s) (repository=my-project/some-repo, branch=renovate/agent-images-automatically)
DEBUG: Checking schedule "before 8am" (repository=my-project/some-repo, branch=renovate/agent-images-automatically)
DEBUG: Package not scheduled (repository=my-project/some-repo, branch=renovate/agent-images-automatically)
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by RahulGautamSingh** [comment]
We should check branch.automergeSchedule right and only if both schedules do not match.

**Comment by viceice** [comment]
branch automerge should ignore normal schedule and only respect automerge schedule.
