### ISSUE TITLE
Onboarding branch should update config if onboardingConfig changes and branch is unmodified

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#22448]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

If an onboarding PR exists, and is unmodified, and its config does not match what is currently in `onboardingConfig`, then Renovate should rebase/repush the onboarding branch.

See #22444 for further details.

To reproduce:
- Run on a repo to create an onboarding PR
- Modify `onboardingConfig` locally
- Run again on the repo

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

**Comment by RahulGautamSingh** [comment]
Will need to bring back previous rebasing logic from the ruins and then use an if-check which will decide if the `onboardingConfig` is same or different and rebase if it's different.

 In a foolow-up pr the same logic can be extended to also allow rebasing when user checks a chekcbox. ([context](https://github.com/renovatebot/renovate/issues/20537))

**Comment by RahulGautamSingh** [comment]
Slightly related question: 
We use `getFile()` to fetch the contents of the onboarding config file and then hash it. Won't it be simpler to use `getOnboardingConfig()` and hash the object instead? 

https://github.com/renovatebot/renovate/blob/16f7b4919afc9efd527709a80cdea134ed8f9ddb/lib/workers/repository/onboarding/pr/index.ts#L222-L227
The only difference in the current way and directly hashing onboarding config object seems to be the formatting of the config file. I don't think formatting will matter much when we are just comparing config details.
