### ISSUE TITLE
Rename branch/pr fingerprints

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#22449]
### Describe the proposed change(s).

Rename the "branch fingerprint" to be "commit fingerprint" and rename the "PR fingerprint" to be "PR body fingerprint". This should be done automatically when caches are loaded the next time, and then saved.

This is to reduce confusion with the new fingerprint I'll add in #22251

**Comment by rarkins** [comment]
@zharinov closed?

**Comment by zharinov** [comment]
I think so
