### ISSUE TITLE
GITHUB_ENDPOINT environment variable is ignored

### ISSUE THREAD

**Issue by lo1tuma** [renovatebot/renovate#2249]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Since the credentials handling has been refactored there seem to be a lot of issues with github enterprise.
I’m using the `GITHUB_ENDPOINT` environment variable to configure the endpoint of the github enterprise instance.

```
GITHUB_ENDPOINT=https://my-gh-enterprise.com/api/v3 GITHUB_TOKEN=abc GITHUB_COM_TOKEN=def npx renovate.
```

For every repository configured I get an error response that says the credentials are invalid.

I‘ve added a few `console.log` statements to some places in the renovate codebase to see the actual credentials that are being used. It turned out the credentials were correct but the the github endpoint was overwritten to `https://api.github.com`.
I think [this line](
https://github.com/renovatebot/renovate/blob/ef92d69a8833743e40ad19d48d629b1e25a251bf/lib/config/index.js#L96) is causing the issue, because `endpoint` is `null` in my case (because it is not defined in `config.js`, only per env variable) and the credential overrides fall back to using the endpoint of the default platforms which is `https://api.github.com`.

A workaround is to define `endpoint` in `config.js` as well.

I’ve also noticed that now it is important that `endpoint` has a traling slash, so you have to use `https://my-gh-enterprise.com/api/v3/` instead of `https://my-gh-enterprise.com/api/v3` otherwise you will get `Repository is not found` errors. The trailing slash wasn’t required in renovate version `13.17.3`.

**Comment by rarkins** [comment]
@lo1tuma thanks for the feedback and sorry for the trouble. I'll look at this today.

- [ ] `GITHUB_ENDPOINT` should be accepted
- [ ] We should massage/join without requiring a trailing slash

Cc @kayoub5

**Comment by rarkins** [comment]
@lo1tuma could you test (without the workaround) using v13.18.11? https://github.com/renovatebot/renovate/releases/tag/13.18.11

**Comment by lo1tuma** [comment]
@rarkins with 13.18.11 it works using only the `GITHUB_ENDPOINT` environment variable.
Thank you for fixing this so quickly.
