### ISSUE TITLE
Bug: unnecessarily escaped @'s in changelogs

### ISSUE THREAD

**Issue by OmgImAlexis** [renovatebot/renovate#2252]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

```Added: stylelint-config-recommended@&#8203;2.1.0 as dependency```

Notice the `&#8203;`

**Additional context**
Please see https://github.com/pymedusa/Medusa/pull/4619

**Comment by rarkins** [comment]
@OmgImAlexis I looked at the PR and don't understand what I'm meant to be looking for. Can you give more details?

**Comment by OmgImAlexis** [comment]
Look at the changelog under `v18.2.0`.

[The original changelog](https://raw.githubusercontent.com/stylelint/stylelint-config-standard/master/CHANGELOG.md)
![screen shot 2018-07-13 at 2 14 45 pm](https://user-images.githubusercontent.com/6525926/42672789-2b664516-86a7-11e8-9a25-ff4325e21c8c.png)

---

What renovate added to the PR.
![screen shot 2018-07-13 at 2 14 41 pm](https://user-images.githubusercontent.com/6525926/42672793-36aafe4e-86a7-11e8-9941-6a86db28334e.png)

**Comment by rarkins** [comment]
We need to aggressively escape @‘s to make sure we don’t accidentally trigger GitHub’s auto linking. In this case it’s not necessary however to know that we’d probably need to be fully markdown-aware, which would be very complex.

**Comment by rarkins** [comment]
This particular case/example is now fixed, but it's a neverending whack-a-mole.

![image](https://user-images.githubusercontent.com/6311784/45920593-c5f7cc80-bea6-11e8-9b01-0b5049c72b0e.png)
