### ISSUE TITLE
Lock updates to particular npm distribution

### ISSUE THREAD

**Issue by ajafff** [renovatebot/renovate#2258]
**What would you like Renovate to be able to do?**
I'm using nightly releases of TypeScript in my repo, e.g. `typescript@3.0.0-dev.20180712`.
Occasionally TypeScript releases an "Insiders" build, e.g. `typescript@3.0.0-insiders.20180706`

Renovate always considers `-insiders` to be greater then `-dev`. This might work for prereleases like `-alpha`, `-beta`, `-rc` and so on. But in my case it actually downgrades the dependency: https://github.com/fimbullinter/wotan/pull/330

**Describe the solution you'd like**
I don't want/need `-insiders` at all.
I'd like a configuration per package where I can specify a regular expression of versions to ignore.

**Comment by rarkins** [comment]
According to semver, it simply sorts suffixes alphabetically so “insiders” is actually newer than ”dev”. The date that comes after it is irrelevant. Ie it’s unfortunate tagging from the maintainers. 

You can probably solve this in Renovate using a package rule and `allowedVersions`. Play around with the version string on semver.npmjs.com until you get the right one that ignores insiders like you wish.  Any questions please raise them in the renovatebot/config-help repo.

**Comment by ajafff** [comment]
Unfortunately `allowedVersions` only uses semver ranges. Semver doesn't support matching prereleases of different major.minor.patch versions.
Therefore I would need to use `allowedVersions: ^3.0.0-dev || ^3.1.0-dev || ^3.2.0-dev` and so on.

What I need is a regular expression to allow / ignore certain versions: `ignoredVersions: ^\d+\.\d+\.\d+-insiders\.`

**Comment by rarkins** [comment]
So you always want unstable versions of typescript (no matter what the major.minor.patch) but never want the “insiders” builds? What is their purpose of “insiders” vs “dev” and do you know if they’re aware that they are not really versioning correctly according to semver?

**Comment by ajafff** [comment]
> can this be supported by specifying which dist-tag to use?

That's a really good idea. That could actually work. If it was configurable I would prefer to only use `next`.

> If we were to support this I’d be tempted to overload allowedVersions to allow regex too.

Is there a way to tell what is a semver range and what's a regex?

> What is their purpose of “insiders” vs “dev” and do you know if they’re aware that they are not really versioning correctly according to semver?

I'll try to get this resolved.

**Comment by rarkins** [comment]
In that case it would be a regular config option called tag or useTag or something like that (ideally generic in name so usable in future for more than just npm if necessary) and of set then it updates you to *only* that version at all times, including rolling backwards if necessary. Right now we use “latest” as our default maximum but don’t fix to only the latest version. Eg if you have 1.7.0 and both 1.7.1 and 2.0.0 exist then you’ll get 2 PRs. If you were to specify useTag=latest then you’d get only 2.0.0. In this case though you would want useTag=next and always update to whatever is specified by that tag

**Comment by rarkins** [comment]
@ajafff have you anything more to add on this topic? Eg locking the version to a certain tag?

**Comment by ajafff** [comment]
I have nothing more to add. I totally agree with your proposed behavior regarding locking to an npm tag.

**Comment by wKovacs64** [comment]
As mentioned on Gitter, it might be worth considering changing the unstable update logic to only accept updates within the exact same major.minor.patch as opposed to adding an option. That's how I assumed it worked already. But what's assumed/intuitive to one is opposite for another, so.  🤷‍♂️

**Comment by rarkins** [comment]
@wKovacs64 I've now implemented that, although it doesn't close the original issue for @ajafff so leaving this open.

**Comment by wKovacs64** [comment]
Good point. Thanks for the update!
