### ISSUE TITLE
Platform refactor: set assignees with createPr

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2269]
Some platforms support assignees at pr creation time, and others don't support adding assignees later. To solve this:

1. `createPr` in each platform should now accept assignees. The platform code will be responsible for whether these can be applied in same API call as creating the PR, or added in a second command
2. `addAssignees` can be optional per platform
3. If the platform doesn't support `addAssignees` then logic should be updated to always add them at time of pr creation instead of only if automerge fails

**Comment by rarkins** [comment]
I thought that Bitbucket didn’t support adding assignee after PR creation. If that is now not the case then we can close this

**Comment by kayoub5** [comment]
Bitbucket does not support "assignee" (not even at creation time), it supports "participants" and "reviewers" and they are changeable according to Bitbucket docs.

**Comment by rarkins** [comment]
OK, closing then, assuming we can add assignees (participants) to BitBucket PRs after creation.
