### ISSUE TITLE
NuGet: Support for multiple package feeds

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/renovate#2270]
**What would you like Renovate to be able to do?**
Provide support for checking new package versions coming from defined package feeds such as NuGet.org, MyGet.org, etc.

**Describe the solution you'd like**
Nothing set in stone yet but one option is to check the feeds defined in NuGet.config

**Additional context**
Initially requested by @jaredcnance in https://github.com/renovatebot/renovate/issues/2266

**Comment by rarkins** [comment]
Supporting NuGet.config plus a Renovate config option sounds like a find start. We do something similar for PyPi.

It also seems like the same config file might support credentials/authentication, but ideally let’s do that in a second phase/issue.

**Comment by rarkins** [comment]
Does a NuGet.config file in the root of a repository apply for only the files also in the root, or for all files within subdirectories too?

**Comment by rarkins** [comment]
And when multiple sources are defined in NuGet.config, are we meant to try them all of the first one fails, or is there a “smarter” way than try/fail/try/fail/try/etc?

**Comment by tomkerkhove** [comment]
I think it would be best to check all package feeds to ensure that we know what the latest version is.

I'm not an expert on NuGet.config but you can have it at a variety of scopes but we can add a disclaimer.
([docs](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior))

**Comment by rarkins** [comment]
Now supported, I believe.
