### ISSUE TITLE
Restrict Docker updates to patch updates

### ISSUE THREAD

**Issue by browniebroke** [renovatebot/renovate#2276]
**What would you like Renovate to be able to do?**

I'm starting to use Renovate to keep our Python images up-to-date. Maybe I misread the doc but it doesn't seem to support what I want so I thought I'd submit a feature request. 

Python versions are a bit weird, the major version is basically 2 vs 3. We use 3.6.5 and a few weeks ago, 3.7.0 & 3.6.6 came out. Jumping to 3.7.x is like jumping a major version, it requires some changes to our code but also to third party libraries. It'll take a bit of time, and in the meantime, I'd like to Renovate to keep sending me updates for 3.6.x. 

The closest config I found was `docker:enableMajor` but it doesn't do what I want.

**Describe the solution you'd like**

Ideally, I'd like an option to tell Renovate I'm not interested in upgrading minor versions for `specific` Dockerfile (not all the files in the repo). I like the way it's done by Pyup, using [filters](https://pyup.io/docs/bot/filter/), but I appreciate it might not fit how Renovate does things. Another possible solution would be to add an option `docker:enableMinor`.

**Describe alternatives you've considered**

I've looked at [this doc](https://renovatebot.com/docs/docker/) page and the opened issues but didn't find a mention of something fitting my need.

**Additional context**

In case it helps, here is the repository where I'm using this:
https://github.com/founders4schools/Dockerfiles

**Comment by rarkins** [comment]
The (generic) config option that would apply here is [separateMinorPatch](https://renovatebot.com/docs/configuration-options/#separateminorpatch) which is disabled by default. Unfortunately, our Docker lookup hasn't been ported over to use the generic lookup yet so the option doesn't apply to Docker yet. When enabled, it means we don't just group all 3.x together, we instead have one PR for 3.6.x and another for minor updates.

Another generic config that would apply is [allowedVersions](https://renovatebot.com/docs/configuration-options/#allowedversions) inside `packageRules`. With this you could manually restrict versions to be `< 3.7` for example.

Both of these will work once I've completed #2081 so you may want to subscribe to that too.
