### ISSUE TITLE
Why does renovate need write access to code?

### ISSUE THREAD

**Issue by JustinBeckwith** [renovatebot/renovate#2278]
We're going through approvals to get renovate enabled for our organization.  One of the sticking points that makes this hard is the requirement for renovate to have write access to our repositories:

![image](https://user-images.githubusercontent.com/534619/42827957-74bff8fe-899c-11e8-8a29-952d5e122763.png)

Since all changes are coming via PR...  why does renovate need write access?  Would it be possible to not ask for this?

cc @juliaferraioli @willnorris

**Comment by rarkins** [comment]
It’s possible to install https://github.com/forking-renovate instead, works for any public repository. With no write access it means Renovate submits PRs from its own fork and also cannot automerge.

**Comment by rarkins** [comment]
Forking Renovate is in use by the ampproject org too fYI
