### ISSUE TITLE
Error: Bad Credentials

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#2286]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I had a few releases today, but the last run from Renovate was 11h ago and errored:
```

INFO: Bad credentials
{
  "err": {
    "name": "GitHubError",
    "host": "api.github.com",
    "hostname": "api.github.com",
    "method": "GET",
    "path": "/repos/sourcegraph/sourcegraph/contents/renovate.json?ref=master",
    "protocol": "https:",
    "url": "https://api.github.com/repos/sourcegraph/sourcegraph/contents/renovate.json?ref=master",
    "statusCode": 401,
    "statusMessage": "Unauthorized",
    "headers": {
      "date": "Wed, 18 Jul 2018 13:30:41 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "83",
      "connection": "close",
      "server": "GitHub.com",
      "status": "401 Unauthorized",
      "x-github-media-type": "github.machine-man-preview; format=json",
      "x-ratelimit-limit": "60",
      "x-ratelimit-remaining": "24",
      "x-ratelimit-reset": "1531922296",
      "access-control-expose-headers": "ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval",
      "access-control-allow-origin": "*",
      "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
      "x-frame-options": "deny",
      "x-content-type-options": "nosniff",
      "x-xss-protection": "1; mode=block",
      "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
      "content-security-policy": "default-src 'none'",
      "x-runtime-rack": "0.023066",
      "x-github-request-id": "CE2E:5BC6:36610D5:3E7A8C1:5B4F4101"
    }
  },
  "message": "Bad credentials (401)",
  "rateLimit": "60",
  "body": {
    "message": "Bad credentials",
    "documentation_url": "https://developer.github.com/v3"
  }
}
ERROR: Repository has unknown error
{
  "err": {},
  "message": "bad-credentials",
  "stack": "Error: bad-credentials\n    at get (/usr/src/node_modules/renovate/lib/platform/github/gh-got-wrapper.js:141:13)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
}
INFO: Unknown error
{
  "err": {},
  "message": "bad-credentials"
}
INFO: Finished repository
```

**Comment by rarkins** [comment]
Unfortunately this is a GitHub bug, and as per their usual policy they are giving zero visibility about their intention or timeline to fix it. 

About 1-2 times per week their system suddenly flags a Renovate IP for a few minutes and returns these stupid 401 errors. A weird giveaway of this is the `"x-ratelimit-limit": "60",` header. All tokens on GitHub are meant to have a minimum of 5000 requests per hour, but whenever this happens they report back only 60.

I'll push them again and also think if there's any reasonable way to mitigate the problem on Renovate side.

**Comment by rarkins** [comment]
FWIW here's the feedback I got last month:

> I checked with the team and see that we have an internal issue open for this. I've included your case there for them to review further. While I can't promise an ETA for when this will be addressed, but we'll write back as soon as there's any news.

and then a week later:

> Thanks for reaching out! I checked with the team internally and there hasn't been any updates that we can share at this time. I reached out to them again to see if anything new changed since you last wrote in. Our team will write to you as soon as we hear more from them.

**Comment by rarkins** [comment]
I just realised though that this type of error on the bot would lead the repository to be demoted to the daily list rather than hourly, so I have applied a fix for that so that it would be retried more quickly.

**Comment by rarkins** [comment]
GitHub has escalated this now and I’m in contact with their partner engineering rep until there’s a resolution. Unfortunately for now they don’t know why it’s happening so all I can do is inform them the 1-2 times per week that it happens. Renovate will now “gracefully” treat this as a platform failure rather than Renovate error, so it will be retried the following hour.

**Comment by rarkins** [comment]
This has been resolved
