### ISSUE TITLE
Feature request: dependency "support policy" for libraries using ranges

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2290]
It's generally accepted that libraries need to use ranges, to help downstream compatibility. And this means not narrowing ranges unnecessarily. But why should projects - particular open source ones - support old versions indefinitely?

The idea of this feature request is to allow a library author to define their default support policy, as well as overrides. e.g. you might support the last 2 major versions for up to one year, otherwise only the latest, you might support the last two minor versions for up to 6 months, and the last two patch versions for up to one month.

**Comment by rarkins** [comment]
As a library author, what would your ideal rules be for deciding when to support "old" dependencies?

**Comment by rarkins** [comment]
Note: I’m most interested in *how* you describe it, not what the exact values will be. I think the structure we need will include concepts of max/min for age and volume of dependencies. 

Cc @teppeis

**Comment by rarkins** [comment]
Cc @hbetts

**Comment by hbetts** [comment]
@rarkins are you suggesting a policy that manages the lower bound of a dependency range specifier in a library's `package.json` file?

**Comment by rarkins** [comment]
@hbetts yes. Eg eslint plug-in developers might decide to support one eslint major release back but only for 6 months. 

The idea is to provide a programmatic way for library developers to keep a “reasonable” range instead of keeping old ones indefinitely or bumping them arbitrarily.

Inspired partly by a post a while ago which wondered out loud why open source developers have more generous “LTS” policies than most commercial companies that are getting *paid* for maintenance. 

Also inspired when I learned that @teppeis is using Removate’s “bump” range strategy as a way to deprecate old version dependencies in his libraries.

**Comment by rarkins** [comment]
In short, a way for library authors to programmatically manage the task of deprecating old dependencies
