### ISSUE TITLE
Lables per language

### ISSUE THREAD

**Issue by OmgImAlexis** [renovatebot/renovate#2292]
**What would you like Renovate to be able to do?**
Add specific label/s to PRs depending on the language.

**Additional context**
We use both js(package.json) and python(requirements.txt) and we'd like to have seperate labels for each.

Something like this maybe?

```js
{
    languageSpecificLabels: {
        js: 'update deps (js)'
	    python: 'update deps (py)'
    }
}
```

**Comment by rarkins** [comment]
This should be possible already if you nest the labels *inside* the language, e.g. like

```
  "python": {
    "labels": ["update deps(py)"]
  }
```

Check renovatebot.com/docs for a list of supported objects you can use, and post a new issue into renovatebot/config-help repo if you're unable to get it to work.
