### ISSUE TITLE
Support shared presets on AWS CodeCommit

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#23099]
### Describe the proposed change(s).

Support `local>` shared presets on AWS CodeCommit

### Describe why we need/want these change(s).

It's currently missing from https://github.com/renovatebot/renovate/blob/3c3f2464481bc2ab0f1cf9c292478ea99a56b695/lib/config/presets/local/index.ts#L19-L28

First requires someone to look into the APIs required to check if CodeCommit can be supported, then this can be moved to label `status:ready`

**Comment by HonkingGoose** [comment]
AWS has deprecated the Codecommit platform. I added a notification to our Codecommit platform docs in this PR:

- #30479

We don't plan to work on new Codecommit features, so I'm closing this issue.
