### ISSUE TITLE
Update docs for `renovate/renovate` Docker image

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#23143]
### Describe the proposed change(s).

Update the Renovate docs:

- [ ] Update [Running Renovate](https://docs.renovatebot.com/getting-started/running/)
- [ ] Update other text surrounding `renovate/renovate` Docker image references

### Describe why we need/want these change(s).

`renovatebot/docker-renovate` released a breaking change to the published image:

- https://github.com/renovatebot/docker-renovate/pull/1518
- https://github.com/renovatebot/docker-renovate/issues/1237

I think this means we need to update our docs, because that image now points to `-slim` by default?

**Comment by HonkingGoose** [comment]
@rarkins can make the changes for this issue in the docs PR you just pinged me to review?

**Comment by rarkins** [comment]
I prefer to keep them separate so they don't get blocked for long

**Comment by rarkins** [comment]
Never mind, I added them to the existing

**Comment by viceice** [comment]
we should remove all references to slim and use normal tags. for full image we now need to use `full` or `<version>-full` tags

**Comment by viceice** [comment]
`slim` tags are deprecated

**Comment by rarkins** [comment]
I removed some more slim references from my PR

**Comment by viceice** [comment]
What's missing here? 🤔

**Comment by HonkingGoose** [comment]
Maybe we've already done this work? I searched for the keyword `slim` and the hits I found seemed to be logical, but make sure to review this!

**Comment by viceice** [comment]
I only find some unrelated test fixtures for slim
