### ISSUE TITLE
Support Docker registries that don't issue `Docker-Content-Digest` headers

### ISSUE THREAD

**Issue by nbyl** [renovatebot/renovate#2315]
**What would you like Renovate to be able to do?**
The docker digest feature is really helpful to update base images, when the contents of a docker tag changes. The implementation of the retrieval of the current digest is based in the `Docker-Content-Digest` header. According to the [offical documentation](https://docs.docker.com/registry/spec/api/#content-digests) this header _may_ be added. One example which does not add this header is RedHats registry at `registry.access.redhat.com`. For these registries renovate should have a fallback.

**Describe the solution you'd like**
If would like to use the blueprint of tools like the mechanism of [skopeo](https://github.com/projectatomic/skopeo) to build a more resilient way of retrieving this digest.

**Describe alternatives you've considered**
An alternative would be to download the image and retrieve it from the local docker daemon. This is a pretty big overhead.

I will be working on this feature at my fork to see if this a possible way to go.

**Comment by rarkins** [comment]
For my hosted app, I don’t want to download entire images just to get the digest. For self hosted I suppose we could enable this behind an admin feature flag, but ideally there’s a better way!
