### ISSUE TITLE
Support helmfile.yaml.gotmpl

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#23176]
### Describe the proposed change(s).

Extend `helmfile` default `fileMatch` to include `helmfile.yaml.gotmpl`. Verify/test against https://github.com/z0rc/renovate-helmfile-yaml-gotmpl

### Describe why we need/want these change(s).

Details in #23166

**Comment by HonkingGoose** [comment]
@rarkins I think you dropped some words in the Issue title. 😉

**Comment by pathob** [comment]
Solved with #26063, so can be closed (no idea why it didn't get closed automatically?)

**Comment by rarkins** [comment]
There needs to be text like "Closed by #26063" in the PR body for GitHub to associate and close automatically

**Comment by rarkins** [comment]
Closed by #26063
