### ISSUE TITLE
Error type: Preset package is missing a renovate-config entry (config:base)

### ISSUE THREAD

**Issue by sarunint** [renovatebot/renovate#2326]
**What Renovate type are you using?**
Self-hosted Renovate

**Describe the bug**
2 hours ago, Renovate opened this issue:
![image](https://user-images.githubusercontent.com/3850197/43386128-e71769da-940c-11e8-935b-f4bd1b22783c.png)

Can I safely ignore this? Because I checked Renovate's code and nothing's wrong. May be it's that my server hosting renovate got internet connection problem? I don't know.

**To Reproduce**
N/A

**Comment by rarkins** [comment]
Can you check which version you were running and try again with the latest and see if the issue clears?

**Comment by sarunint** [comment]
@rarkins Long story short, the bug is in v13.38.4. The bug stops renovate to renovate itself (lol) so I don't get the fix which is in v13.38.5.

Now manually updated to v13.38.6 and it should fix the problem.

**Comment by rarkins** [comment]
Whoops, sorry!
