### ISSUE TITLE
Why do I need packagePatterns if I specify includePaths?

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#2336]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I try to specify a `packageRule` for all packages for package.jsons in certain folders, but I am getting this error:

> There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.
> 
> File: `renovate.json`
> Error type: The renovate configuration file contains some invalid settings
> Message: packageRules: Each packageRule must contain at least one selector (paths, depTypeList, packageNames, packagePatterns, excludePackageNames, excludePackagePatterns, updateTypes). If you wish for configuration to apply to all packages, it is not necessary to place it inside a packageRule at all.

To reproduce:
```json
{
  "packageRules": [
    {
      "includePaths": ["client/"],
      "assignees": ["felixfbecker"]
    }
  ]
}
```

I think Renovate should allow this.

**Comment by rarkins** [comment]
You need `paths` instead of `includePaths` if using inside `packageRules`.
