### ISSUE TITLE
feat(minimatch): add caching support

### ISSUE THREAD

**Issue by setchy** [renovatebot/renovate#23491]
### Describe the proposed change(s).

As discussed through the review of https://github.com/renovatebot/renovate/pull/23085, this issue is to add caching support to the minimatch uses within Renovate.

Idea would be the wrap the minimatch package like is done for regex

### Describe why we need/want these change(s).

Efficiency and speed

**Comment by RahulGautamSingh** [comment]
This is completed right?

**Comment by viceice** [comment]
did you checked all usages? we should disallow direct minimatch import via eslint (exclude our util)

**Comment by RahulGautamSingh** [comment]
> did you checked all usages? we should disallow direct minimatch import via eslint (exclude our util)

Modified the rmaining here: https://github.com/renovatebot/renovate/pull/25842
