### ISSUE TITLE
Remove dependency hasha

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#23520]
### Describe the proposed change(s).

replace it with buildin crypto API, see link for easy replacement 

-https://github.com/containerbase/base/blob/main/src/cli/utils/hash.ts

### Describe why we need/want these change(s).

it's a wrapper for crypto API, but it has issues when trying to compile as app.

**Comment by viceice** [comment]
@setchy do you like to do this?

**Comment by setchy** [comment]
Looks mostly straight forward.

There are a few instances of `hasha.fromStream(http.stream(some-url))`, guessing we'd just need to convert that into a string first?
