### ISSUE TITLE
Customize Renovate's status check strings

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#23530]
### Discussed in https://github.com/renovatebot/renovate/discussions/23141

<div type='discussions-op-text'>

<sup>Originally posted by **HonkingGoose** April 17, 2023</sup>
### What would you like Renovate to be able to do?

I would like to think if it's the right time to let users customize Renovate's status check strings too

_Originally posted by @rarkins in https://github.com/renovatebot/renovate/issues/21376#issuecomment-1504727770_

### If you have any ideas on how this should be implemented, please tell us here.

I'll let the maintainers figure out the requirements and implementation details. 😉 

### Is this a feature you are interested in implementing yourself?

No</div>

**Comment by rarkins** [comment]
Proposal: new option `statusCheckNames` with default values:

```
{
  "minimumReleaseAge": "renovate/stability-days",
  "mergeConfidence": "renovate/merge-confidence"
}
```

**Comment by rarkins** [comment]
- We should validate the object to make sure it's string->string and that the keys can only be the two above.
- Setting to `null` or empty string would mean it's disabled/skipped

**Comment by RahulGautamSingh** [comment]
Should we also add the status check strings for artifacts ie. `renovate/artifacts` and the config validation status check we use for reconfigure branch `renovate/config-validation` to the list?

**Comment by rarkins** [comment]
Yes

**Comment by RahulGautamSingh** [comment]
Do we want the field to be mergeable?
ie. 
// user config
```
statusCheckNames: {
  "minimumReleaseAge": "some-string"
}
```

Then should the other values ie. `nergeConfidence` use the default value or should they be undefined.

**Comment by rarkins** [comment]
Yes, mergeable so that you only need to specify the values you want to override
