### ISSUE TITLE
Incorrect API url in GitLab

### ISSUE THREAD

**Issue by adam-moss** [renovatebot/renovate#2363]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
404 Not Found error being reporting when trying to get repos from the GitLab API as the url being used is incorrect (missing `/` in `path` attribute):

```json
ERROR: GitLab getRepos error
       "err": {
         "name": "GitLabError",
         "host": "host_fqdn",
         "hostname": "host_fqdn",
         "method": "GET",
         "path": "/api/v4projects?membership=true&per_page=100",
         "protocol": "https:",
         "url": "https://host_fqdn/api/v4projects?membership=true&per_page=100",
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "nginx",
           "date": "Tue, 07 Aug 2018 21:19:14 GMT",
           "content-type": "application/json",
           "content-length": "37",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-request-id": "ca4ca047-c277-4405-8447-a2ca5be4b2c9",
           "x-runtime": "0.018581"
         }
       }
FATAL: Renovate fatal error: undefined (404)
```

**To Reproduce**
Run renovate cli (official docker image) with appropriate auth tokens against gitlab.

**Expected behavior**
API is called corrected, list of repos is retrieved for processing.

**Screenshots**
Per output above

**Additional context**
GitLab CE on-prem, major version 11.

**Comment by rarkins** [comment]
Does it still work if you add a `/`to the end of your configured endpoint?

**Comment by adam-moss** [comment]
Hmmm.  Digging a bit more - looks like I've never included a trailing `/` in my `endpoint` attribute in my `config.js`.  Happy to add this in, which will fix it.  Do you want a PR to auto-add it?

**Comment by rarkins** [comment]
Yes, PR would be great if you don’t mind. I’m on mobile for an extended period right now

**Comment by adam-moss** [comment]
Sure, no probs, let me work that one up 😄

**Comment by gmcnaught** [comment]
FYI We had the same issue using RENOVATE_ENDPOINT with a Github Enterprise account and adding the trailing / in the endpoint definition fixed it, though it was a change in behavior!

**Comment by rarkins** [comment]
@kayoub5 this needs a simple `.replace(/[^/]$/, '$&/')` for the configured endpoint however I'm not sure exactly where to put it with the "new" endpoints approach. Can you make the PR?
