### ISSUE TITLE
@SirUli With your yml format `matchStrings` extracts version as `"1.14.0"` and not `1.14.0`. That could be the cause of the issue.

### ISSUE THREAD

**Issue by Giangpro89** [renovatebot/renovate#23654]
@SirUli With your yml format `matchStrings` extracts version as `"1.14.0"` and not `1.14.0`. That could be the cause of the issue. 
I recommend trying regex preview site to check it, for example: https://regex101.com/

Here is my yml definition:

```yaml
# renovate: depName=nomad
nomad_version: 1.6.0
```

`datasource` is not needed as `datasourceTemplate` will set it if not present.

_Originally posted by @Demivan in https://github.com/renovatebot/renovate/discussions/23286#discussioncomment-6537348_

**Comment by SirUli** [comment]
Not sure what to respond here. Did you open this issue intentionally?
