### ISSUE TITLE
Feature: Add support for golang

### ISSUE THREAD

**Issue by publicarray** [renovatebot/renovate#2385]
**What would you like Renovate to be able to do?**
Add support for golang dependencies.

**Describe the solution you'd like**
The [dep](https://github.com/golang/dep) program adds a [Gopkg.toml](https://golang.github.io/dep/docs/.html) file to manage dependencies. It would be nice If renovate could add support 🚀 

**Describe alternatives you've considered**
[dependabot](https://dependabot.com/go.html) has go support in alpha status.

**Comment by rarkins** [comment]
Thanks, but will close this in favour of #933
