### ISSUE TITLE
Warn if config.js or RENOVATE_CONFIG need migrating

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#23868]
### Describe the proposed change(s).

Log a warning if the content of config.js needs migrating or fails validation

### Describe why we need/want these change(s).

This can help to catch errors

**Comment by rarkins** [comment]
The challenge here is that we need to allow the full global + repo config options whereas our validator today throws an error if global options are used in repo config.

**Comment by RahulGautamSingh** [comment]
Can be resolved by passing fileName value to `validateConfig()` fn and if it is not one of ththe allowed configFileNames we can assume it is a fileConfig and allow global options?

**Comment by rarkins** [comment]
Not a migration warning - a validation warning

**Comment by RahulGautamSingh** [comment]
> The challenge here is that we need to allow the full global + repo config options whereas our validator today throws an error if global options are used in repo config.

Currently the validation fn only throws errors if the global option present in renovate.json is an object, it allows other types.

**Comment by rarkins** [comment]
Can you give examples?

**Comment by RahulGautamSingh** [comment]
https://github.com/RahulGautamSingh-testing/config-validation/issues/1

You can see that there are 4 different global options of diff types. But we only get warning for the one options that is an object.

**Comment by RahulGautamSingh** [comment]
When I tried locally,
<img width="456" alt="image" src="https://github.com/renovatebot/renovate/assets/76607510/93b6f220-bd37-4405-8f64-f3a7ad5f0d46">

**Comment by RahulGautamSingh** [comment]
We can fix this by adding an if-check which looks for the option.globalOnly field. in the validateConfig() fn at the very top.
```js
for(const [key, val] of Object.entries(migratedConfig)){
     if(options[key].globalOnly){
          errors.push({...errorObject})
    }
    ...
}
```

**Comment by rarkins** [comment]
> Currently the validation fn only throws errors if the global option present in renovate.json is an object, it allows other types.

@RahulGautamSingh when you write this, does this apply to `renovate-validator` use only, or also to the way Renovate does validation at runtime?

**Comment by RahulGautamSingh** [comment]
Current logic flow for the validation function looks like this:

```js
for( [key, val] ) {
    // 1. do some genreal validation like; security errors, shd be a top-level config but found inside parent
    // 2. key based validation for some keys like fileMatch, enabledManagers
    // 3. type-based validation ... string, boolean, array and object <inorder>
 }
```

We can add the check for globalOption validation after the first type of validation
Updated Logic Flow:

```js
for( [key, val] ) {
   // 1. do some genreal validation like; security errors, shd be a top-level config but found inside parent
    // 2. GlobalOnly option validation
    // 3. key based validation for some keys like fileMatch, enabledManagers
    // 4. type-based validation ... string, boolean, array and object <inorder>
}
```

We can perform the check for a global option is two ways:
 1. We have a `GlobalConfig.OPTIONS` array, in the `lib/config/globals.ts` file, which we use for global options. But it, is private...
     So we can create a public method `isGlobalOption` which checks for the key in that array and use it 
     **OR**
 2. We can check if the key has `globalOptions=true`

 
GlobalOnly option validation will look like this:
```js
if( isGlobalOption(key) ) {
    // check if we are validating renovate.json or config.js
    if( !isFileConfig(filename) ) {
        errors.push( `${key} is a global config option, can't be inside renovate.json` );
    }
    else {
        // this will be a new validation function which we use to validate global options
        errors.push( validateFileConfigKey(key, val) );
    }
}
```

**Comment by rarkins** [comment]
At runtime the bot shouldn't need to guess based on filename - it should already know if it's repo config.

For command-line validation, the filename-based approach is probably ok.

Consider checking the `globalOnly` flag in our config options file as an alternative approach to knowing if it's global

**Comment by RahulGautamSingh** [comment]
We have two tests in `validation.spec.ts` that validate a global option (globalOnly=true). How should we handle these?

https://github.com/renovatebot/renovate/blob/9e6ed574c29842df8143cbe94022b0e59a58fadb/lib/config/validation.spec.ts#L865-L881

**Comment by rarkins** [comment]
Maybe do https://github.com/renovatebot/renovate/issues/24560 first?

**Comment by viceice** [comment]
> We want to allow some global options in the repo config
> https://github.com/renovatebot/renovate/blob/9e6ed574c29842df8143cbe94022b0e59a58fadb/lib/config/validation.ts#L606-L614
> 
> Will store them in a variable and ignore these.


why do we do this that way? we should remove the global only flag if they are allowed in repo config or forbid (warn for now) them if not allowed

**Comment by RahulGautamSingh** [comment]
> why do we do this that way? we should remove the global only flag if they are allowed in repo config or forbid (warn for now) them if not allowed

It seems we wanted to validate them, if founf in `config.js` ... but since there was no different function we decided to validate them as objects. I will handle it as a part of this issue.

**Comment by RahulGautamSingh** [comment]
I had gone wrong path due to confusion and thought we only need to validate config.js manually ie. by calling config-validator.

But we want to validate file config during repo runs as well.
For this we just need to call the `validateConfig` function with `isGlobalConfig:true` in the `getConfig` function after the file config is parsed and migrated
https://github.com/renovatebot/renovate/blob/a1e5f548d148f96904ca505c08a4c11825f98446/lib/workers/global/config/parse/file.ts#L80-L88

It will look like this 

```ts
export async function getConfig(env: NodeJS.ProcessEnv): Promise<AllConfig> {
...
 // validate file config and log the erros and warnings 
  const { errors, warnings } = await validateConfig(
    config,
    false,
    undefined,
    true
  );
  if (errors) {
    // log errors
  }
  if (warnings) {
    // log warnings
  }

  // delete file config errors so they don't get mixed with repo config errors when we validate repo config
  delete config.errors;
  delete config.warnings;

  return config;
```

I will add the changes in this PR https://github.com/renovatebot/renovate/pull/25218

**Comment by rarkins** [comment]
Is it possible that this change only logs _warnings_ for now, and not errors? Logging errors will mean Renovate exits with a non-zero exit code, which I think should be a breaking change in a major release

**Comment by RahulGautamSingh** [comment]
> Is it possible that this change only logs _warnings_ for now, and not errors? Logging errors will mean Renovate exits with a non-zero exit code, which I think should be a breaking change in a major release
Yes

**Comment by RahulGautamSingh** [comment]
Yes.

For global options validation will be added with the new PR so that is in our control ie. only pushing warnings 
For the non-global options, we still use the existing validation. We can log the errors as warnings.

**Comment by RahulGautamSingh** [comment]
@rarkins This issue focuses on the `config-validator` use case right. As we have https://github.com/renovatebot/renovate/issues/25274 for the runtime case.

**Comment by rarkins** [comment]
I think I intended this to be for runtime actually, but ok to split them
