### ISSUE TITLE
Link to Python packages on PyPI in PR description

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#2387]
**What would you like Renovate to be able to do?**
Make the package name in Python dependency PRs a link to more information about the package (rather than a backtick quoted string), like occurs already for JS dependencies PRs.

**Describe the solution you'd like**
Currently:
```
<p>This Pull Request updates dependency <code>mkdocs</code> from ...
```

Desired:
```
<p>This Pull Request updates dependency <a href="...">mkdocs</a> from ...
```

**Describe alternatives you've considered**
The URL could be either:
* the source on GitHub (if found in the package/PyPI metadata)
* the project website/docs page
* the PyPI page for the package (eg https://pypi.org/project/mkdocs/ )

**Additional context**
Examples of where `<code>...</code>` was used instead:
mozilla-neutrino/neutrino-dev#1012
mozilla-neutrino/neutrino-dev#1013

It looks like Renovate currently checks the `home_page` field from the PyPI metadata, here:
https://github.com/renovatebot/renovate/blob/d2885e5d9ee1dd5886d884e05d60c84c2660b87c/lib/datasource/pypi.js#L43-L49

But looking at the PyPI API responses, there's also:
* `project_url` (is the link to the PyPI page
* `project_urls` (appears to be an array of URLs combined from other fields; only has one entry for many packages, though some have several eg https://pypi.org/pypi/Django/json)

**Comment by rarkins** [comment]
Seems `mkdocs` is one that doesn't link to its source repo, so in this case it would only be its home page we can link to.

As mentioned in #2071, there are three URLs of interest to us about packages:

1. Source repo (usually GitHub)
2. Homepage (e.g. https://mkdocs.org)
3. Registry page (e.g. pypi.org/pypi/mkdocs)

Perhaps we could show all 3 if available, if it doesn't complicate the display too much.

**Comment by edmorley** [comment]
Having a link to a few of the different URL types would be useful, however even just having an "if no github URL found, use homepage instead in the PR description" fallback would be great for now :-)

**Comment by edmorley** [comment]
Many thanks!
