### ISSUE TITLE
DCO Sign-off

### ISSUE THREAD

**Issue by hbetts** [renovatebot/renovate#2393]
**What would you like Renovate to be able to do?**

Sign-off commits for projects using a [Developer Certificate of Origin](https://github.com/probot/dco#how-it-works) workflow.

**Describe the solution you'd like**

Add a `Signed-off-by:` line at the end of every Renovate generated commit with a space, and the e-mail of the Renovate bot, appended to the line.

**Describe alternatives you've considered**

The alternative to signing off commits is to either force accept a pull request with a failing DCO status check, or to use an alternative workflow, such as a more traditional CLA.

**Additional context**

An example of a failing DCO status check - https://github.com/factset/deprecator/pull/25

**Comment by rarkins** [comment]
@hbetts can you check if the preset described in https://github.com/renovatebot/renovate/issues/777#issuecomment-353889606 works for you?

@olstenlarck are you still using this approach?

**Comment by olstenlarck** [comment]
Hm. I thought i tried it, but seems like i'm not using it. I think it would work, yea.

That's my config https://github.com/tunnckoCore/renovate-config-tunnckocore/blob/master/package.json and seems that i was trying it with `commitBody` ;d

**Comment by hbetts** [comment]
@rarkins yes, that was definitely what I was looking for! (I'm sorry for not having searched beforehand).

I [extended by preset](https://gitlab.com/hyper-expanse/open-source/configuration-packages/renovate-config/commit/b290de327c218422895ff68692ddda40e3bc4052) about three hours ago, 

Renovate [submitted a PR](https://github.com/factset/deprecator/pull/26) about two hours ago.

The commit still seems to be missing the DCO signoff.

Going [through the logs](https://renovatebot.com/dashboard#factset/deprecator/16524035) I couldn't see the final configuration (to know whether I am using the preset correctly.

**Comment by rarkins** [comment]
@hbetts I'll debug it and fix if necessary. I decided not to dump the entire config into debug logs because in many cases the full config is pretty large due to all the presets including monorepos.

**Comment by rarkins** [comment]
Ahh, there we go. My own debugging caught it:

```json
{
  "level": 20,
  "repository": "factset\/deprecator",
  "package": "@hbetts\/renovate-config",
  "latest": "1.0.6",
  "headers": {
    "date": "Thu, 16 Aug 2018 14:55:42 GMT",
    "content-type": "application\/json; charset=UTF-8",
    "set-cookie": [
      "__cfduid=dabf0350075d5638e14f2fb988df4d4501534431342; expires=Fri, 16-Aug-19 14:55:42 GMT; path=\/; domain=.registry.npmjs.org; HttpOnly"
    ],
    "cache-control": "public, max-age=14400",
    "cf-cache-status": "REVALIDATED",
    "cf-ray": "44b4be54ffc8bc7a-SEA",
    "etag": "W\/\"f482506c5af87a7c279ed06b159efe2a\"",
    "expect-ct": "max-age=604800, report-uri=\"https:\/\/report-uri.cloudflare.com\/cdn-cgi\/beacon\/expect-ct\"",
    "last-modified": "Tue, 07 Aug 2018 14:38:18 GMT",
    "vary": "Accept-Encoding",
    "server": "cloudflare",
    "content-encoding": "gzip",
    "age": "3681"
  },
  "msg": "npmjs res.headers for scoped package",
  "time": "2018-08-16T15:57:03.291Z"
}
```
Note that it returned an old version (v1.0.6). It's a bug I've reported to npmjs already; https://npm.community/t/scoped-packages-have-latest-version-disappear-temporarily-soon-after-publish/633

**Comment by hbetts** [comment]
Thank you @rarkins, again. 👍 

Looks like this is just a caching issue.

**Comment by rarkins** [comment]
I've disabled RFC-compliant caching of scoped npmjs requests for now, because it seems the registry is inappropriately returning 4 hour expiries on all scoped packages vs 5 minute expiries on non-scoped.

**Comment by hbetts** [comment]
@rarkins I am now getting a DCO sign-off on https://github.com/factset/deprecator/pull/27

Should this issue be closed now?
