### ISSUE TITLE
Ignore inline comments in a CODEOWNERS file

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#23964]
### Describe the proposed change(s).

Renovate ignores inline comments in a CODEOWNERS file.

### Describe why we need/want these change(s).

```
# CODEOWNERS

*   @org/team-a # comment
```

When Renovate sees this CODEOWNERS file, and `reviewersFromCodeOwners` is set to `true`, Renovate adds three reviewers to its PRs:

- `@org/team-a` (correct)
- `#` (wrong)
- `comment` (wrong)

Renovate should understand inline comments, so it only adds the `@org/team-a` as reviewer.

Also see #23913 for more background information.

**Comment by ezzatron** [comment]
@HonkingGoose I think I can probably put together a PR if you'd like to assign me.
