### ISSUE TITLE
Detect .NET version from global.json

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#24029]
### Describe the proposed change(s).

Look for `global.json` to determine .NET version

Example:

```json
{
  "sdk": {
    "version": "6.0.413",
    "rollForward": "latestFeature"
  }
}
```

### Describe why we need/want these change(s).

So that users don't need to configure constraints.dotnet

**Comment by omlnaut** [comment]
Is there currently any way of achieving this behaviour? Reading the issue description I thought that I can define constraints.dotnet somewhere, but does not seem to be the case?

**Comment by rarkins** [comment]
Please ask a config question in Discussions instead

**Comment by RahulGautamSingh** [comment]
We already extract the sdk version extract here and just need to put it inside a `extractedConstraints` object and return it. 

https://github.com/renovatebot/renovate/blob/d16e0f23596fc32af4fa88bd5ba66b4a72de890d/lib/modules/manager/nuget/extract/global-manifest.ts#L32-L39
