### ISSUE TITLE
Feature request: support strict-ssl=false for npm

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2412]
Because Renovate does its own npm registry lookups directly, invalid certificates will result in a Node.js `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` error. Before performing requests, we should see if the `.npmrc` contains `strict-ssl=false` and if so then try to set something like `rejectUnauthorized` in Node.js 	request module to `false`.

**Comment by Journerist** [comment]
you described the solution by yourself:

1. adapt npmrc: `strict-ssl=false`
2. add env variable: `NODE_TLS_REJECT_UNAUTHORIZED=0`

now it works ;)
