### ISSUE TITLE
Jobs list fails to load on Renovate dashboard due to CORS error

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#2413]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I get a CORS error when trying to use the Renovate dashboard and the list of jobs on the page doesn't load.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at
https://v1.renovateapi.com/gh/repos/neutrinojs/babel-merge/jobs
(Reason: CORS request did not succeed).
```

**To Reproduce**

1.  Visit https://renovatebot.com/dashboard
2.  Click the authenticate with GitHub button
3.  Click one of the repos on the left (eg in my case https://renovatebot.com/dashboard#neutrinojs/babel-merge)

**Expected behavior**
The jobs list on the page fully loads.

**Screenshots**

![renovate-dashboard-cors-error](https://user-images.githubusercontent.com/501702/44454039-65991500-a5f2-11e8-9149-917aaf73da8b.jpg)

**Additional context**
Firefox Nightly on Windows 10 x64.

**Comment by edmorley** [comment]
Bah sorry NoScript wasn't yet whitelisted for the `renovateapi.com` domain, and for some reason the toolbar NoScript icon hadn't changed colour to indicate there was blocked content (which would have prompted me to check the whitelist).

**Comment by rarkins** [comment]
I noticed this today too. Don’t suppose you would mind using Chrome until we fix? :D

**Comment by rarkins** [comment]
Strange. What I saw earlier were CORS errors:

![image](https://user-images.githubusercontent.com/6311784/44454834-db09e300-a5fc-11e8-855c-01cfc4d35bc0.png)
