### ISSUE TITLE
Digest pinning only in Dockerfiles not in docker-compose.yml

### ISSUE THREAD

**Issue by peterbe** [renovatebot/renovate#2415]
**What would you like Renovate to be able to do?**
I like [digest pinning in Dockerfiles](https://renovatebot.com/docs/docker/). It's an awesome feature. But I don't care for it in the `docker-compose.yml` files. Look at [this one for example](https://github.com/mozilla-services/tecken/commits/master/docker-compose.yml)
They are disruptive and adds noise. More PRs means more load on the CI, especially if PRs needs to be retested when the master branch is updated. 

Also, in production, I use the docker image built from the `Dockerfile` but the `docker-compose.yml` file(s) is only used for local development and for setting up services when running the CI. 

**Describe the solution you'd like**
An option to only enable digest pinning on the `Dockerfile`(s).

**Describe alternatives you've considered**
Ignoring the PRs :)

**Additional context**
There is not option mentioned on this page: https://renovatebot.com/docs/docker/

**Comment by rarkins** [comment]
@peterbe digest pinning is disable by default now, so one way is to simply delete the existing digest if you don't want to use them at all. If instead you want to use them, but never update them once they're set, then you should be able to disable it like this:

```json
{
  "docker-compose": {
    "digest": {
      "enabled": false
    }
  }
}
```

`docker` objects apply to all docker, while `dockerfile` and `docker-compose` apply to those types specifically and override anything in `docker`.

**Comment by rarkins** [comment]
That config change looks fine
