### ISSUE TITLE
Global .pip Configuration File Support

### ISSUE THREAD

**Issue by hbetts** [renovatebot/renovate#2421]
**What would you like Renovate to be able to do?**

I would like to run `renovate` (currently using `renovate` as an internal GitHub App) in an environment where I do no have access to permanent disk space.

Therefore, when I run `renovate`, I can not pre-position a `~/.pip` configuration file containing our organization's Pip configuration:

```
[global]
index-url=http://artifactory.example.com/artifactory/api/pypi/python/simple
trusted-host=artifactory.example.com
```

**Describe the solution you'd like**

May I have the ability to inject our organization's `.pip` file through a `piprc` like environment option, similar to the existing [`npmrc`](https://renovatebot.com/docs/configuration-options/#npmrc) option?

**Describe alternatives you've considered**

One alternative is to register our PYPI registry URLs in a shared Renovate preset. However, not all projects within our organization use our shared preset, nor are they required to. Yet, every project within our organization is required to use our internal package repository mirror. 

Another alternative is to bake our own Docker image containing both the configuration file and Renovate. This approach may not work for the reasons [outline in this comment on the Renovate Pro repository](https://github.com/renovatebot/pro/issues/12#issuecomment-390756710).

**Comment by rarkins** [comment]
Things to consider:

- Is it best to configure a *file* or instead just the relevant values it contains? pip logic is entirely contained within Renovate’s Code so does not call `pip` itself 

- If a file, then do we keep adding custom options for each language or work out a generic file config?

**Comment by rarkins** [comment]
@hbetts wouldn't the existing PyPi code satisfy your requirements?

https://github.com/renovatebot/renovate/blob/af547f070e6a3714cda36f7d84cfa8d99c22fb9b/lib/datasource/pypi.js#L17-L22

**Comment by hbetts** [comment]
> @hbetts wouldn't the existing PyPi code satisfy your requirements?

Yes, it probably would. For some reason I was thinking `config` was only going to load presets, and not the environment variables exposed to Renovate.

Let me try setting `RENOVATE_REGISTRY_URLS=http://artifactory.example.com/artifactory/api/pypi/python/simple` and see what happens.

> Is it best to configure a file or instead just the relevant values it contains? 

Just my two cents, but I am fine with not using the `.pip` file directly. In the end my preference is for something that's easy to use, and my requirement is that it must behave exactly like what would happen if I was using `pip`/`npm`/etc directly.

**Comment by hbetts** [comment]
Also, I just noticed the following change (which I apparently commented on in the PR review) - c59a9fdeb541812a2f0336b597550b4f964117ec

It allows for a `PIP_INDEX_URL` environment variable option.

**Comment by hbetts** [comment]
`RENOVATE_REGISTRY_URLS` did not work since the option [is not setup to be pulled from the environment](https://github.com/renovatebot/renovate/blob/08b44a062a36aa9180084e3993e4bb8a1f871d81/lib/config/definitions.js#L329).

`PIP_INDEX_URL` did work as expected.

Thank you @rarkins
