### ISSUE TITLE
Evolve credentials/endpoints handling

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2423]
1. Match hostnames and not just full URLs
2. What to do if more than one match? Use best match or “last” match in the list?
3. Rename “platform”?

**Comment by rarkins** [comment]
Also need to think how credentials can continue to be defined using env only (ie 12 factor)

**Comment by rarkins** [comment]
For configuration via env, we could support perhaps:

1. Stringified JSON.. pretty hard to maintain
2. Intelligent env parsing, see below

If we support hostnames instead of URLs, then we something like this could be feasible:

```
RENOVATE_CREDENTIALS_REGISTRY_NPMJS_ORG_TOKEN=abcdef-ghijk
RENOVATE_CREDENTIALS_BITBUCKET_COMPANY_COM_USERNAME=abc
RENOVATE_CREDENTIALS_BITBUCKET_COMPANY_COM_PASSWORD=def
```

Becomes:

```json
{
  "credentials": [
    {
       "platform": "registry.npmjs.org",
       "token": "abcdef-ghijk"
    },
    {
      "platform": "bitbucket.company.com",
      "username": "abc",
      "password": "def"
  ]
}
```

The above couldn't work with hosts that have underscores, but that may have to just be a limitation. Potentially you could use a double underscore to mean an underscore in the hostname, thereby only excluding hosts with double underscores!

**Comment by rarkins** [comment]
I'm also considering renaming it from "endpoints" to "hosts" or "hostRules" as it will probably evolve to be more than credentials only.

**Comment by kayoub5** [comment]
another possibility is to give platforms arbitrary names
```shell
RENOVATE_CREDENTIALS_FOO_PLATFORM=bitbucket # this could be auto detected using api calls
RENOVATE_CREDENTIALS_FOO_TOKEN=abcdef-ghijk
RENOVATE_CREDENTIALS_FOO_USERNAME=abc
RENOVATE_CREDENTIALS_FOO_PASSWORD=def
RENOVATE_CREDENTIALS_FOO_HOST=bitbucket.company.com
```
becomes
```json
{
  "credentials": [
    {
      "name": "foo",
      "platform": "bitbucket ",
      "token": "abcdef-ghijk",
      "host": "bitbucket.company.com",
      "username": "abc",
      "password": "def"
    }
  ]
}
```

**Comment by rarkins** [comment]
@kayoub5 would the "name" be purely cosmetic?

**Comment by kayoub5** [comment]
Yes, it's an arbitrary alias
