### ISSUE TITLE
feat(manager/maven): support `.mvn/extensions.xml`

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#24328]
### Discussed in https://github.com/renovatebot/renovate/discussions/24316

<div type='discussions-op-text'>

<sup>Originally posted by **jonesbusy** September  8, 2023</sup>
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

36.82.0

### If you're self-hosting Renovate, select which platform you are using.

Bitbucket Server

### Was this something which used to work for you, and then stopped?

I never saw this working

### Wanted end result.

Hi,

"Recent" version of maven allow the use of '.mvn/extensions.xml' with following format

```
<extensions xmlns="http://maven.apache.org/EXTENSIONS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 http://maven.apache.org/xsd/core-extensions-1.0.0.xsd">
  <extension>
    <groupId>....</groupId>
    <artifactId>...</artifactId>
    <version>1.0.0</version>
  </extension>
</extensions>
```

The maven manager is supposed to renovate maven extension like any other plugin/dependency ?

Dependabot works well for `extensions.xml` but it seems it doesn't work out of the box by Renovate

I didn't find anything on the doc about this.

Should be supported by 'maven' manager ? Or should a 'maven-extensions' manager be implemented ?

Thanks for the help!

### What you tried so far.

I can try to use regexManager with 'git-tags' but it's not very convenient

Also tried to use 

```
  "maven": {
    "fileMatch": [
      "(^|/|\\.)pom\\.xml$",
      "(^|/|\\.)\\.mvn/extensions\\.xml$"
    ]
  },
```

But I don't see any check on my extensions even if

```
DEBUG: Matched 4 file(s) for manager maven: .mvn/extensions.xml, it/pom.xml, library/pom.xml, pom.xml (repository=local)
```

### Relevant debug logs

_No response_</div>

**Comment by rarkins** [comment]
Reproduction: https://github.com/renovate-reproductions/24316

**Comment by jonesbusy** [comment]
Thanks!

**Comment by ahoehma** [comment]
Any news here?

**Comment by RahulGautamSingh** [comment]
Closed by: https://github.com/renovatebot/renovate/pull/28893
