### ISSUE TITLE
Feature: support reviewers for Bitbucket Cloud

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2440]
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D#put

**Comment by rarkins** [comment]
Also useful for bitbucket server

**Comment by ViceIce** [comment]
> Also useful for bitbucket server

Done, see #3230

**Comment by njibhu** [comment]
@ViceIce Sadly this PR only add the feature to Bitbucket server and not Bitbucket cloud.

**Comment by ViceIce** [comment]
@njibhu I know, but they have different api's.

**Comment by ViceIce** [comment]
@njibhu Do you need this? Should be easy to implement.

**Comment by njibhu** [comment]
@ViceIce I actually do, yes
I never worked with bitbucket api directly, but I would assume that for that it's very similar between the server and the cloud product

**Comment by ViceIce** [comment]
@njibhu unfortunately the api if very different at that point. Sorry.

**Comment by rarkins** [comment]
Implemented in https://github.com/renovatebot/renovate/pull/3509
