### ISSUE TITLE
bun: support parsing bun.lockb to detect locked versions

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#24462]
### Describe the proposed change(s).

Parse barn.lockb so that each dependency's `lockedVersion` can be known.

This would enable more accurate detection of currentVersion, and rangeStrategy=pin, but not immediately rangeStrategy=update-lockfile

**Comment by HonkingGoose** [comment]
_What's_ causing the `status:blocked`? Reading the issue does not tell me what's needed before we can start work.

**Comment by rarkins** [comment]
Switched back to `status:requirements`. The challenge here is how to parse the lock file. e.g.
- "reverse engineer" the format and parse it in JS, or
- Break our rule of "no binary tools during extract process"

**Comment by hyrious** [comment]
> "reverse engineer" the format and parse it in JS

Just did that -- https://github.com/hyrious/bun.lockb.

It's still experimental and useless (only translates the bun.lockb to yarn lockfile v1, no reverse), let me know if you find any issues or need some features.

**Comment by rarkins** [comment]
We’ll wait for the non binary bun lock file instead: https://github.com/oven-sh/bun/issues/11863
