### ISSUE TITLE
feat: Auto merge PRs when review required.

### ISSUE THREAD

**Issue by ryansmith94** [renovatebot/renovate#2446]
**What would you like Renovate to be able to do?**
Currently it's quite frustrating when `automerge` is enabled, but Renovate makes pull requests because a review is required.

**Describe the solution you'd like**
Would it be possible to approve the pull request automatically in this scenario and automatically merge the pull request?

**Describe alternatives you've considered**
We considered making a webhook that checked the title of pull requests for non-major dependency updates from Renovate, then approved the PR and merged it automatically using a bot account.

**Comment by rarkins** [comment]
If you install https://github.com/apps/renovate-approve then it will hopefully do what you want. It should approve *all* Renovate PRs, although Renovate itself will of course only automerge those you've configured for it. 

Screenshot:
![image](https://user-images.githubusercontent.com/6311784/44846767-a677d600-ac51-11e8-873e-a7ca90253578.png)

Note: I'm pretty sure it will only pick up on *new* PRs so you won't see any existing ones get auto-approved after you install.

**Comment by rarkins** [comment]
By the way GitHub doesn't allow users/apps to approve their *own* PRs. That's why it needs to be a separate app.

**Comment by ryansmith94** [comment]
Hey Rhys, hope you're well. Totally understand it needing to be a separate app/user. Am I right in assuming that this will approve all PRs (including major changes to dependencies) and not just patch and minor changes to dependencies?

**Comment by rarkins** [comment]
Yes, it will approve all/any Renovate PRs, including major. It has no "awareness" of Renovate concepts and just looks if the author of the PR is `renovate[bot]`. This won't cause Renovate to automerge major though unless you have configured it to do that - Renovate still uses its own logic to decide on automerging.

**Comment by ryansmith94** [comment]
Ahhhhhh yes good point, I forgot the renovate[bot] would actually merge the PR, thanks Rhys! Will close this.

**Comment by ryansmith94** [comment]
Hi @rarkins, seems to work to some extent, any idea how I solve the issue with the `renovate-approve` app not being an acceptable review here https://github.com/xAPI-vle/moodle-logstore_xapi/pull/236?

**Comment by rarkins** [comment]
I forgot that GitHub added the requirement “with write access” after I first wrote that bot. I’ll update its permissions later today to request read/write access although it will still just do nothing but auto approve.

**Comment by rarkins** [comment]
Done

**Comment by ryansmith94** [comment]
Awesome thanks Rhys!

**Comment by itajaja** [comment]
so, if I have automerge, but not `renovate-approve`, will it wait for my approval and then merge? that's probably the worfklow I'd like
