### ISSUE TITLE
Endpoints CLI argument not parsed

### ISSUE THREAD

**Issue by eseliger** [renovatebot/renovate#2455]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
passing `--endpoints` as an argument to the cli is not working at the moment, because this line assumes it's an object. https://github.com/renovatebot/renovate/blob/HEAD/lib/util/endpoints.js#L21
It is a string though, as the cli config parser has no coercion for json, hence platform of string is always undefined and `Failed to configure platform '${platform}': no endpoint defined` is a very confusing error for `'cannot be passed to the cli'`.

**To Reproduce**
add argument `--endpoints='{"platform":"docker","host":"docker.company.io"}'`

**Expected behavior**
I would like a coercion for json inputs for the cli argument so it's possible to pass secret docker credentials internally to the renovate cli tool.

**Comment by rarkins** [comment]
I think if we add `cli: true` to the `endpoints` config object then this might be all that's needed: https://github.com/renovatebot/renovate/blob/a7def6bb85f424fcfe487b32c3ed8b3e515cae21/lib/config/definitions.js#L1159-L1166

**Comment by eseliger** [comment]
would be great :) I can prob do a PR later today if you want me to

**Comment by rarkins** [comment]
Yes if you could do that it would be great. The change is probably one line but should be tested first, which I can’t do right now


________________________________
