### ISSUE TITLE
Consistent, predictable json/json5 handling

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#24554]
### Describe the proposed change(s).

Files with extension `.json` should use `JSON.parse()`, files with extension `.json5` or without extension such as `.renovaterc` should use `JSON5.parse()`.

Where we are allowing JSON5 for `.json` files today, we should change so that we _warn_ if a `.json` file parses with JSON5 but not with JSON.

Then after sufficient time has passed, perhaps 2 major releases, we should remove JSON5 parsing of `.json` files, which will result in a Config Validation error.

We should do the same with presets too.

**Comment by viceice** [comment]
sounds good to me

**Comment by rarkins** [comment]
An alternative: allow VSCode-style JSONC for .json files: https://github.com/microsoft/node-jsonc-parser

**Comment by viceice** [comment]
interesting library. maybe it allows us to migrate config files with less changes

**Comment by rarkins** [comment]
It's all quite a mess - there's also an argument for saying if you want JSONC then use .jsonc. I think these days we can support almost unlimited json/jsonc/json5 extensions for each file name anyway.

**Comment by RahulGautamSingh** [comment]
```js
export function parseJSONWithFallback(content: string): any {
  let parsedJson: any;

  try {
    parsedJson = JSON.parse(content);
  } catch (jsonErr) {
    try {
      parsedJson = JSON5.parse(content);
      console.warn('Warning: JSON5.parse was used to parse the JSON data.');
    } catch (json5Err) {
      console.error('Error: Failed to parse the input as both JSON and JSON5.');
      return null; // or handle the error as needed
    }
  }

  return parsedJson;
}
```

This should work right?

**Comment by rarkins** [comment]
Yes, this looks good, although we maybe want to log if both parsing fails too

**Comment by RahulGautamSingh** [comment]
I think throwing an error makes will be better incase the content isn't parsable as that is current behaviour wherever parsing is performed.

**Comment by jamietanna** [comment]
Sounds reasonable, it's always nicer to have this sort of thing be extra predictable, as well as nudging editors what the correct file format is.

I assume that [`optimizeForDisabled`](https://docs.renovatebot.com/self-hosted-configuration/#optimizefordisabled) and other config will be updated, if needed, to handle the new filename(s)?

**Comment by rarkins** [comment]
We should use the `onboardingConfigFileName` value for `optimizeForDisabled`. This probably should be renamed too, so that it's more generic.
