### ISSUE TITLE
Use GitHub block quotes extension

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#24550]
### Discussed in https://github.com/renovatebot/renovate/discussions/24549

<div type='discussions-op-text'>

<sup>Originally posted by **uhthomas** September 20, 2023</sup>
### Tell us more.

GitHub has extended the blockquote syntax to include more visible messages. It would be nice if Renovate were to use these instead the existing style.

https://github.com/orgs/community/discussions/16925

Example:

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

Current:

<img width="910" alt="Screenshot 2023-09-20 at 13 19 46" src="https://github.com/renovatebot/renovate/assets/9749173/9f1160ea-d8d7-4bb9-870a-35199585a4d7">

With proposed change:

<img width="911" alt="Screenshot 2023-09-20 at 13 20 29" src="https://github.com/renovatebot/renovate/assets/9749173/6c0fe9f5-b82b-42be-9484-a5f2e25b6846">
</div>

**Comment by HonkingGoose** [comment]
## GitHub-only styling harder to maintain?

Are you sure you want to add a new separate syntax just for GitHub? Other platforms will still use the old styling? It may make things harder to maintain?

## Do we want a `---` separator, or not?

The screenshot of the mockup dropped the `---` separators. Here's how it looks with the `---` separators between sections:

_Start of mockup_

This PR contains the following updates:

| **Package** | **Update** | **Change** |
| --- | --- | --- |
| [`grafana/grafana`]() | minor | `10.0.2` -> `10.1.2` |

---

> [!WARNING]
> Warnings were logged while processing this repo. Please check the Dependency Dashboard for more information.

---

## Release Notes 

_End of mockup_

**Comment by HonkingGoose** [comment]
> [!IMPORTANT]
>
> The old `> **Alert**` syntax is _deprecated_, we should use the new `> [!ALERT]` syntax instead.

Read the [GitHub docs for the alert syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) to learn about the new syntax.

**Comment by rarkins** [comment]
New syntax:

```
> [!NOTE]
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]
> Crucial information necessary for users to succeed.

> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.
```

Becomes:

> [!NOTE]
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]
> Crucial information necessary for users to succeed.

> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.
