### ISSUE TITLE
rangeStrategy: widen does not update package-lock.json

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#2480]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
When using `"rangeStrategy": "widen"` for a library, the PR to widen a range does not update package-lock.json. This means the tests in CI don't actually test against the new version, which means I have no way to tell if the new major version actually works or not.

**To Reproduce**
See https://github.com/sourcegraph/codeintellify/pull/50

**Expected behavior**
It should widen the range in package.json and update the package to the new version in package-lock.json.

**Comment by rarkins** [comment]
This seems to be `npm`'s choice, although I agree it's a problem in terms of testing. I did this to confirm:

- clone'd repo
- ran `npm i`
- manually updated the `marked` version to `"^0.4.0 || ^0.5.0"`
- ran `npm i`

The result: no `package-lock.json` change.

For completeness, here is what `package-lock.json` shows for `marked`:

```json
    "marked": {
      "version": "0.4.0",
      "resolved": "https://registry.npmjs.org/marked/-/marked-0.4.0.tgz",
      "integrity": "sha512-tMsdNBgOsrUophCAFQl0XPe6Zqk/uy9gnue+jIIKhykO51hxyu6uNx7zBPy0+y/WKYVZZMspV9YeXLNdKk+iYw=="
    },
```

Interestingly, `semantic-release` depends on 0.5.0

**Comment by felixfbecker** [comment]
I don't think this is npms fault, if the package.json version is still compatible, why would `npm install` update the lockfile? That would basically mean the lockfile doesn't actually lock anything.

I think Renovate should run different commands here, e.g. `npm update`. Maybe widen the range only _after_ the update manually.

**Comment by rarkins** [comment]
> why would npm install update the lockfile? 

If a version string in the `package.json` has changed, I would expect it to recalculate what version should be locked. `yarn` does it that way and "correctly" updates `marked`'s locked version to 0.5.0 in the same situation as above.

I tried running `npm update marked` after updating `package.json` and it didn't "fix" the lock file either. Manually deleting `marked` from `package-lock.json` and then running `npm install` does result in `0.5.0` as expected.

**Comment by felixfbecker** [comment]
> If a version string in the package.json has changed

It has no way to check if a string changed though. package.json is the source of truth for version ranges, they are not in package-lock.json, so there is nothing to diff against.

**Comment by felixfbecker** [comment]
> I tried running npm update marked after updating package.json and it didn't "fix" the lock file either. Manually deleting marked from package-lock.json and then running npm install does result in 0.5.0 as expected.

What I thought of was using `update` or `install` to update the package, _then_ updating the package.json to have a wide range. Would that work?

**Comment by rarkins** [comment]
> It has no way to check if a string changed though. package.json is the source of truth for version ranges, they are not in package-lock.json, so there is nothing to diff against.

`package.json` is the source of truth for `npm install`, `package-lock.json` is the source of truth for `npm ci`. I expect that if the source of truth for `npm install` changes, then the output for `npm install` should be expected to change if necessary too. "they are not in package-lock.json, so there is nothing to diff against" to me is an implementation detail that could change. I expect that the lock file is updated without me needing to hack at it using combinations of commands. 

> What I thought of was using `update` or `install` to update the package, then updating the package.json to have a wide range. Would that work?

This is like an npm bait and switch. Install one thing, but then update the package file to a different version string that's sort of the same but not exactly, and hope that npm's way of aligning `package.json` and `package-lock.json` doesn't change too much in future that it completely breaks our hack. 

How lock files are computed is an implementation detail, and therefore this proposed solution would be relying on an implementation detail not to change. Proof that this is an implementation detail: if you did the same commands as you suggest using Yarn, then you'd be committing an invalid `package.json`/`yarn.lock` combination. It would only be (possibly/probably) valid for `npm` for now because we are using knowledge of their internals to work around their native behaviour.

Anyway, I still don't mind being pragmatic if there's no other workaround. But right now my preferred one is to delete the existing entries from `package-lock.json` for any dependencies we're updating and then run `npm install` like usual.

**Comment by rarkins** [comment]
I just realised that your proposed workaround could be de-risked if we ran a final `npm install` as a safety against implementation changes in future. e.g.

- install the exact latest Version manually
- update `package.json` to the range again
- run `npm install` one more time

**Comment by felixfbecker** [comment]
> package.json is the source of truth for npm install, package-lock.json is the source of truth for npm ci.

It's true that package-lock is the only source of truth for `npm ci`, but for `npm install` _both_ package.json and package-lock.json are the source of truth. `npm install` will just make sure that the two don't contradict and fix the lockfile if needed, but otherwise respect the lockfile.

> This is like an npm bait and switch. Install one thing, but then update the package file to a different version string that's sort of the same but not exactly, and hope that npm's way of aligning package.json and package-lock.json doesn't change too much in future that it completely breaks our hack.

> How lock files are computed is an implementation detail, and therefore this proposed solution would be relying on an implementation detail not to change. Proof that this is an implementation detail: if you did the same commands as you suggest using Yarn, then you'd be committing an invalid package.json/yarn.lock combination. It would only be (possibly/probably) valid for npm for now because we are using knowledge of their internals to work around their native behaviour.

You can run `npm install`/`yarn` again to reconcile the lockfile and make sure it is in a valid state (but nothing should change for npm). The fact that `npm install` reconciles package-lock.json to not contradict package.json, otherwise respects package-lock.json without changing it, is documented behaviour, so I wouldn't say it's an implementation detail.

> But right now my preferred one is to delete the existing entries from package-lock.json for any dependencies we're updating and then run npm install like usual.

This seems to contradict your point above "How lock files are computed is an implementation detail [that we shouldn't rely on]"?

**Comment by rarkins** [comment]
> The fact that npm install reconciles `package-lock.json` to not contradict `package.json`, otherwise respects `package-lock.json` without changing it, is documented behaviour

Serious question: do you know where this is documented? Because I've actually been searching to try to find some definitive descriptions on this today and definitely haven't found it so far. I'd like to read what documentation they have before deciding on the best approach.

**Comment by rarkins** [comment]
I guess this might be the best "documentation" on the topic: https://github.com/npm/npm/issues/17979#issuecomment-332701215

![image](https://user-images.githubusercontent.com/6311784/45089644-1a602580-b10d-11e8-8f88-c7c01ac945be.png)

In other words it's like we've been discussing here: `package-lock.json` is kept as-is unless it contradicts `package.json`.

**Comment by rarkins** [comment]
I've confirmed with one of the npm developers that there is no simple way to achieve this (i.e. bump the version in the lockfile) but they are considering modifying `npm update`'s behaviour to allow it to happen that way. So to solve this, we need to a "workaround" as discussed above.
