### ISSUE TITLE
Support for Bitbucket Server

### ISSUE THREAD

**Issue by ViceIce** [renovatebot/renovate#2482]
**What would you like Renovate to be able to do?**
I would like to use Renovate with our own hosted Bitbucket Server

**Describe the solution you'd like**
Please implement a platform backend for Bitbucket Server. I can help.

**Describe alternatives you've considered**
Currently i can't use Renovate and there is no workaround

**Additional context**
[Bitbucket Server REST API](https://docs.atlassian.com/bitbucket-server/rest/5.13.1/bitbucket-rest.html)

**Comment by ViceIce** [comment]
Fetch repos: [/rest/api/1.0/repos](https://docs.atlassian.com/bitbucket-server/rest/5.13.1/bitbucket-rest.html#idm45902675643680)

Create PR: [/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests](https://docs.atlassian.com/bitbucket-server/rest/5.13.1/bitbucket-rest.html#idm45902674652464)

**Comment by iamstarkov** [comment]
@ViceIce have you seen code for BB cloud adapter?

**Comment by ViceIce** [comment]
Yes, but the 2.0 API is not available in bitbucket server.

**Comment by rarkins** [comment]
Is there any guide to differences between cloud and server APIs?

**Comment by iamstarkov** [comment]
bitbucket server doesnt have the same versioning scheme as bitbucket cloud. it has like 4 versions
