### ISSUE TITLE
Support ISO 8601 Time Interval strings

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2488]
To supplement the existing schedule strings, add support for ISO 8601 Time Interval strings as suggested in https://github.com/renovatebot/config-help/issues/94

Right now we do not support absolute dates, so these two formats would be good to start with:

- Start and end, such as "2007-03-01T13:00:00Z/2008-05-11T15:30:00Z"
- Start and duration, such as "2007-03-01T13:00:00Z/P1Y2M10DT2H30M"

Also there is the possibility of using https://www.npmjs.com/package/iso8601-interval-recurrence as a substitute for "plain english" recurring schedules.

Cc @felixfbecker

**Comment by rarkins** [comment]
Prefer to support cron ranges instead

**Comment by HonkingGoose** [comment]
See issue:

- https://github.com/renovatebot/renovate/issues/7612 

for the discussion on cron support for schedules.
