### ISSUE TITLE
Handle/skip invalid YML in .travis.yml

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2492]
Example: 

```
after_deploy:
  - "curl -H 'Content-Type: application/json' --data '{\'build\': true}' -X POST $DOCKER_HUB_URL;"
```

**Comment by nihal9ns** [comment]
@rarkins  The yml you provided as an example have invalid escape sequence. It should be : 
```after_deploy:
  - "curl -H 'Content-Type: application/json' --data '{\\'build\\': true}' -X POST $DOCKER_HUB_URL;"```

**Comment by nihal9ns** [comment]
Notice the 
```
\\'build\\ '
```

**Comment by rarkins** [comment]
Exactly. Doesn’t it cause us to print an error or warning now?

**Comment by nihal9ns** [comment]
Nah, our code breaks if we don't handle such errors. May be a try/catch block should help and some logging?

**Comment by nihal9ns** [comment]
The yml parser rejects it, we need to handle that

**Comment by rarkins** [comment]
Yes

**Comment by nihal9ns** [comment]
How can I test this live? Not through a test case but by running the app. Just want to know when the does the control come into lib/manager?

**Comment by rarkins** [comment]
Look up our docs on how to debug
