### ISSUE TITLE
Migrate galaxy-collection datasource from v2 to v3

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#24981]
### Describe the proposed change(s).

It appears that the v2 Ansible Galaxy API we've been using has stopped working and that we need to migrate to v3. However I've not been able to find a definitive reference for this year, so there is still some research to be done.

This URL for example includes the word "beta" in the examples: https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/community/api_v3/

**Comment by rarkins** [comment]
Reproduction repo: https://github.com/renovate-reproductions/24981

**Comment by secustor** [comment]
For reference there seems to be a general issue with the API currently 

https://github.com/ansible/galaxy/issues/3253#issuecomment-1744520197

**Comment by fust** [comment]
Looks like ansible/galaxy is being superseded by ansible/galaxy_ng and the latter went live on galaxy.ansible.com on september 30: https://forum.ansible.com/t/new-ansible-galaxy/1155
This is around the same time we were starting to see errors for Galaxy dependencies in our Renovate pipelines.
I can't find anything on the v2 API for ansible/galaxy_ng which leads me to believe that it won't be coming back.

**Comment by secustor** [comment]
Found the migration blog https://www.ansible.com/blog/new-ansible-galaxy

Seems like they moved the old galaxy instance to https://old-galaxy.ansible.com

I'm preparing a patch that will let Renovate default to that host name instead.
