### ISSUE TITLE
graphql: endpoint path not correct for GHE

### ISSUE THREAD

**Issue by dylang** [renovatebot/renovate#2507]
**What Renovate type are you using?**
Renovate CLI, Renovate GitHub App, or Renovate Pro?

`"renovate": "13.64.5"`

**Describe the bug**
The Github enterprise endpoint both needs `v3` and can't have `v3` at the same time.

If we include `v3` then GHE graphql calls fail because they are **including** `v3`

```
Error retrieving vulnerability alerts...
"url": "https://github.company-name.com/api/v3/graphql",
"statusCode": 404,
```

If we remove `v3` then GHE REST calls fail because they are **missing** `v3`

```
Unknown GitHub initRepo error
"url": "https://github.company-name.com/api/repos/Org/repo",
"statusCode": 406,
```

**To Reproduce**

```
'GITHUB_ENDPOINT=https://github.company-name.com/api/v3',
'RENOVATE_ENDPOINT=https://github.company-name.com/api/v3',
```
or 
```
'GITHUB_ENDPOINT=https://github.company-name.com/api',
'RENOVATE_ENDPOINT=https://github.company-name.com/api',
```

**Expected behavior**
We could trim the `v3` for the `graphql` requests, and add, if missing, the `v3` for REST requests.

**Additional context**

We're also seeing it use our GHE token on the public github, that's what lead me to discover this issue.

**Comment by rarkins** [comment]
@dylang thanks for reporting. Can you confirm that failed graphql queries are able to be skipped over though, i.e. it logs errors but otherwise is unaffected?

**Comment by dylang** [comment]
They are skipped.

GraphQL does not use `v4`, it's not versioned using the url.

**Comment by rarkins** [comment]
OK, I understand your idea to strip v3 now and will implement that way for backwards compatibility
