### ISSUE TITLE
npm token not being used

### ISSUE THREAD

**Issue by dylang** [renovatebot/renovate#2511]
**What Renovate type are you using?**

`"renovate": "13.64.5"`

**Describe the bug**

Despite the following in our renovate config, every lock file update has been failing because of 401 hitting our private repository.

```js
    // https://renovatebot.com/docs/private-modules/
    npmrc: fs.readFileSync(path.join(os.homedir(), '.npmrc'), 'utf8'),
    yarnrc: fs.readFileSync(path.join(os.homedir(), '.yarnrc'), 'utf8'),
    // I've tried with and without this:
    npmToken: process.env.NPM_CONFIG__AUTH,
    // Enable this to expose bot process.env to repositories for npmrc substitution and package installation
    // I've tried with and without this:
    exposeEnv: true,
```

**To Reproduce**

I use the above config to try to make sure the upgrade workers have the right token. 

**Expected behavior**

Not this error:

```
"stdout": "/home/jenkins/.npm/lerna@3.3.0/bin/lerna -> /home/jenkins/.npm/lerna@3.3.0/lib/node_modules/lerna/cli.js\n+ lerna@3.3.0\nadded 2 packages from 1 contributor, removed 1 package and updated 21 packages in 31.567s\n",
         "stderr": "\u001b[2K\u001b[1G\u001b[31merror\u001b[39m An unexpected error occurred: \"https://private-npm-server/api/npm/virtual-npm/@commitlint/lint/-/lint-7.0.0.tgz: Request failed \\\"401 Unauthorized\\\"\".\n",
         "message": "Command failed: npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n\u001b[2K\u001b[1G\u001b[31merror\u001b[39m An unexpected error occurred: \"https://private-npm-server/api/npm/virtual-npm/@commitlint/lint/-/lint-7.0.0.tgz: Request failed \\\"401 Unauthorized\\\"\".\n `npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879` (exited with error code 1)",
         "stack": "ChildProcessError: Command failed: npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n\u001b[2K\u001b[1G\u001b[31merror\u001b[39m An unexpected error occurred: \"https://martifactory.io/api/npm/virtual-npm/@commitlint/lint/-/lint-7.0.0.tgz: Request failed \\\"401 Unauthorized\\\"\".\n `npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879` (exited with error code 1)\n    at callback (/home/jenkins/workspace/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:295:5)\n    at ChildProcess.emit (events.js:182:13)\n    at maybeClose (internal/child_process.js:962:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)"
```

**Screenshots**

**Additional context**
We're also seeing it only use our GHE token (`GITHUB_TOKEN`) on github.com (instead of `GITHUB_COM_TOKEN`). Maybe there's a bug in the config code or how workers see the config? Is there something like `renovate --show-config` to see what it thinks the config is at runtime?

**Comment by dylang** [comment]
I may have resolved the npm token issue by commenting out `npmrc`, `yarnrc`, and `npmToken` and **only** using `exposeEnv: true`. This is fine for us.

```
    // https://renovatebot.com/docs/private-modules/
    // npmrc: fs.readFileSync(path.join(os.homedir(), '.npmrc'), 'utf8'),
    // yarnrc: fs.readFileSync(path.join(os.homedir(), '.yarnrc'), 'utf8'),
    // I've tried with and without this:
    // npmToken: process.env.NPM_CONFIG__AUTH,
    // Enable this to expose bot process.env to repositories for npmrc substitution and package installation
    // I've tried with and without this:
    exposeEnv: true,
```

I'm running another build to make sure.

**Comment by rarkins** [comment]
If `npmrc` is added explicitly to config, then any `.npmrc` files in the repo will be ignored. Therefore if you already have `.npmrc` in the repo with environment variable substitutions then what you’re doing now (`exposeEnv`) is probably what I’d recommend anyway as it means the least duplication.

**Comment by rarkins** [comment]
FYI, the auth approaches for npm and GitHub are completely different so this would be unrelated to the earlier changelog problem.

**Comment by dylang** [comment]
Closing, thanks!

**Comment by dylang** [comment]
Re-opening, `exposeEnv: true` didn't fix the problem.

**Comment by dylang** [comment]
Config has `exposeEnv: true`.

I think I thought it was passing because the `package.json` hadn't changed, so it was ignoring lockfile changes.

```
INFO: PR not found in open or closed PRs list - trying to fetch it directly (repository=reporting/reporting, dependencies=snappy, branch=renovate/snappy-6.x)
       "prNo": 4542
 INFO: PR not found in open or closed PRs list - trying to fetch it directly (repository=reporting/reporting, dependencies=styled-components, branch=renovate/styled-components-3.x)
       "prNo": 4845
 INFO: PR not found in open or closed PRs list - trying to fetch it directly (repository=reporting/reporting, dependencies=styled-components, branch=renovate/styled-components-3.x)
       "prNo": 4845
 INFO: Branch is stale and needs rebasing (repository=reporting/reporting, dependencies=styled-components, branch=renovate/styled-components-3.x)
 INFO: lock file error (repository=reporting/reporting, dependencies=styled-components, branch=renovate/styled-components-3.x)
       "cmd": "npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
       "err": {
         "name": "ChildProcessError",
         "code": 1,
         "childProcess": {},
         "stdout": "/home/jenkins/.npm/lerna@3.3.0/bin/lerna -> /home/jenkins/.npm/lerna@3.3.0/lib/node_modules/lerna/cli.js\n+ lerna@3.3.0\nupdated 1 package in 36.543s\n",
         "stderr": "\u001b[2K\u001b[1G\u001b[31merror\u001b[39m An unexpected error occurred: \"https://martifactory.io/api/npm/virtual-npm/webpack/-/webpack-4.17.2.tgz: Request failed \\\"401 Unauthorized\\\"\".\n",
         "message": "Command failed: npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n\u001b[2K\u001b[1G\u001b[31merror\u001b[39m An unexpected error occurred: \"https://martifactory.io/api/npm/virtual-npm/webpack/-/webpack-4.17.2.tgz: Request failed \\\"401 Unauthorized\\\"\".\n `npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879` (exited with error code 1)",
         "stack": "ChildProcessError: Command failed: npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n\u001b[2K\u001b[1G\u001b[31merror\u001b[39m An unexpected error occurred: \"https://martifactory.io/api/npm/virtual-npm/webpack/-/webpack-4.17.2.tgz: Request failed \\\"401 Unauthorized\\\"\".\n `npm i -g -C ~/.npm/lerna@3.3.0 lerna@3.3.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.0/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879` (exited with error code 1)\n    at callback (/home/jenkins/workspace/78f00166/workspace/renovate_master-EPD7JO65Z2D3QYCBQKHZL6Z44R23NJF7UMXKRHMCFIRCJPY7SRJA/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:295:5)\n    at ChildProcess.emit (events.js:182:13)\n    at maybeClose (internal/child_process.js:962:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)"
       },
       "stdout": undefined,
       "stderr": undefined,
       "type": "lerna",
       "lernaClient": "yarn"
 INFO: PR is older than a day, raise PR with lock file errors (repository=reporting/reporting, dependencies=styled-components, branch=renovate/styled-components-3.x)
 INFO: Branch updated (repository=reporting/reporting, dependencies=styled-components, branch=renovate/styled-components-3.x)
       "branchName": "renovate/styled-components-3.x"
 INFO: Branch updated (repository=reporting/reporting, dependencies=styled-components, branch=renovate/styled-components-3.x)
       "branchName": "renovate/styled-components-3.x"
 INFO: PR not found in open or closed PRs list - trying to fetch it directly (repository=reporting/reporting, dependencies=styled-components, branch=renovate/styled-components-3.x)
```

**Comment by dylang** [comment]
`.npmrc`

```
_auth = Z*******************Q==
email = service-fowler@medallia.com
always-auth=true
registry=https://artifactory.company.com/api/npm/virtual-npm

@m:registry=https://artifactory.company.com/api/npm/virtual-npm/
//artifactory.company.com/api/npm/virtual-npm/:_password=Q**********************5
//artifactory.company.com/api/npm/virtual-npm/:username=fowler
//artifactory.company.com/api/npm/virtual-npm/:email=service-fowler@company.com
//artifactory.company.com/api/npm/virtual-npm/:always-auth=true
```

`.yarnrc`
```
registry "https://artifactory.company.com/api/npm/virtual-npm/"
```

`env`
```
NPM_CONFIG_ALWAYS_AUTH=true
NPM_CONFIG_LOGLEVEL=warn
NPM_CONFIG_REGISTRY=https://private-artifactory.io/api/npm/virtual-npm
NPM_CONFIG__AUTH=Zm93bGVyOkFQNzhWVGNBdFRtbXVTWFVkWmJTdEp3ZlQ2OQ==
```

It's strange that our `NPM_CONFIG_REGISTRY` is not the same hostname as the rc files, but they point to the same machine.

**Comment by rarkins** [comment]
Observations:
- No env variable substitution present in `.npmrc`
- Legacy `_auth` line: we already have special code in place to massage it
- Special `registry=` line for `@m` scope but it points to the same URL so seems redundant
- The custom registry host then has *additional* username/password settings. I think those "overwrite" the `_auth` from line 1? The `_auth` value could even be old/wrong in that case. We *don't* have special code for username/password
- Then there is the env variable with same auth value as `auth_`
- `.yarnrc` points to the same registry as `.npmrc` but should be harmless

Questions:

1. Are these two files - including the auth settings - committed to the root of each repo that needs them?
2. It shouldn't matter, but can you confirm that the `.yarnrc` file is unnecessary? I believe `yarn` happily reads registry settings from `.npmrc`
3. Are the `env` variables there just for your testing of Renovate, or do you somehow have every machine using this repo also exposing them?
4. Considering that there seems to be a lot of duplication here, are you able to fix/de-duplicate these files and env in the process of fixing this, or is this something you're not allowed to touch?

Additional info:

There are two ways in which npm auth is used and needed:
- When we do a lookup query to npm's API via our own internal code
- When we run `npm install` or `yarn install` later to update the lock file(s)

We should solve the problem in that order, i.e. make sure that Renovate's own lookups work first before then making sure the lockfile generation works.

**Comment by dylang** [comment]
The `.npmrc` and `.yarnrc` are in the `~` directory on the docker VM provided by our SAAS team for running on Jenkins. 

I've pinged them about the redundant scope settings and that the hostname is not the same as the one we use in our lockfile.

I can try using this data to generate a new `.npmrc` in the config.

**Comment by rarkins** [comment]
Are there any npm or yarn settings in the repositories too?

**Comment by dylang** [comment]
> Are there any npm or yarn settings in the repositories too?

Nope.

Damn, still getting 

```
 "stderr": "\u001b[2K\u001b[1G\u001b[31merror\u001b[39m An unexpected error occurred: \"https://private-registry.io/api/npm/virtual-npm/webpack/-/webpack-4.17.2.tgz: Request failed \\\"401 Unauthorized\\\"\".\n"
```

with this in our renovate config:

```js
const fs = require ('fs');
const path = require('path');
const os = require('os');

// Quick hacky cleanup of the rc files:
const npmrc = fs.readFileSync(path.join(os.homedir(), '.npmrc'), 'utf8')
    .replace(/artifactory.company.com/g, 'private-registry.io')
    .split('@m:')[0];

const yarnrc = fs.readFileSync(path.join(os.homedir(), '.yarnrc'), 'utf8')
    .replace(/artifactory.company.com/g, 'private-registry.io')
    .split('@m:')[0];


module.exports = {
....<cut>....
    exposeEnv: true,
    npmrc,
    yarnrc
};
```

**Comment by dylang** [comment]
We're using the same Jenkins VM's and settings for installing this package, and all the packages for all projects using renovate.

```
         "stack": "ChildProcessError: Command failed: npm i -g -C ~/.npm/lerna@3.3.2 lerna@3.3.2 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.2/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n\u001b[2K\u001b[1G\u001b[31merror\u001b[39m An unexpected error occurred: \"https://private-registry.io/api/npm/virtual-npm/webpack/-/webpack-4.17.2.tgz: Request failed \\\"401 Unauthorized\\\"\".\n `npm i -g -C ~/.npm/lerna@3.3.2 lerna@3.3.2 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@3.3.2/bin/lerna bootstrap -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879` (exited with error code 1)\n    at callback (/home/jenkins/workspace/78f00166/workspace/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:295:5)\n    at ChildProcess.emit (events.js:182:13)\n    at maybeClose (internal/child_process.js:962:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)"
       },
       "stdout": undefined,
       "stderr": undefined,
       "type": "lerna",
       "lernaClient": "yarn"
```

It looks like `npm` is installing `lerna`, but then `yarn` installing installing the dependency.

I'm storing verbose logs from this, but i don't see anything additional that would be helpful.

> Is npm install using the right token? (presumably not, if you verify 1 above)

I know the token is correct, but I don't know if `yarn` in the  `child_process` is using that token. Is there any way to verify what it is using? I don't have access to the tmp dir where the files are written and I don't think we're logging the npm or yarn error log.

**Comment by rarkins** [comment]
First can you confirm for sure steps 2 and 3 above? Is Renovate definitely accessing the private server correctly during its own lookups prior to npm/lerna/yarn?

**Comment by rarkins** [comment]
> `npm i -g -C ~/.npm/lerna@3.3.2 lerna@3.3.2`

This is Renovate installing the exact version of `lerna` as specified in your `package.json`.

> `yarn install ..........`

As a `yarn.lock` was detected, `yarn install` is used to install dependencies in the root directory.

> `~/.npm/lerna@3.3.2/bin/lerna bootstrap -- ..........`

^^ Then calling `lerna bootstrap`.

```
at callback (/home/jenkins/workspace/78f00166/workspace/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:295:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5
```
I don't know if this "inception" of yarn inside lerna inside Renovate inside Jenkins has anything to do with it.

Idea:

- Install `renovate` on your workstation
- Copy the `.npmrc` to your home directory
- Run `renovate` against the repo and see if you get the exact same error or not

**Comment by dylang** [comment]
I will try that next, thanks!

**Comment by dylang** [comment]
I'm using the same `.npmrc` locally using the `npmrc` config. The project does have a `.yarnrc` and I noticed in the temp directory it doesn't try merging the two. For us, that's fine.

It didn't get the permission error.

```
DEBUG: Writing yarn.lock (repository=reporting/reporting, dependencies=aws-sdk, branch=renovate/aws-sdk-2.x)
DEBUG: Writing yarn.lock (repository=reporting/reporting, dependencies=aws-sdk, branch=renovate/aws-sdk-2.x)
>>> ^ this line repeats about ~100 times.
>>> An unrelated bug in the loop code causing it to re-write the file?
DEBUG: Writing any updated package files (repository=reporting/reporting, dependencies=aws-sdk, branch=renovate/aws-sdk-2.x)
DEBUG: No updated lock files in branch (repository=reporting/reporting, dependencies=aws-sdk, branch=renovate/aws-sdk-2.x)
>>> Strange, because it says it wrote one.
DEBUG: No files to commit (repository=reporting/reporting, dependencies=aws-sdk, branch=renovate/aws-sdk-2.x)
```

So this PR still doesn't have the lockfile changes.

Same thing happened to all the other PR's.

**Comment by rarkins** [comment]
Is it a lerna repo with ~100 packages inside? Can you also make sure you are trying with the verrry latest Renovate?

**Comment by rarkins** [comment]
Any chance you’re able to reduce it to be a non lerna repo for testing to reduce the number of possible things that could go wrong? Eg a repo with a single outdated repo and yarn.lock with nothing more than “# foo” with one line return is enough to trigger an update.

**Comment by dylang** [comment]
Some things that were interesting to me:

`npm i -g -C ~/.npm/lerna@${lernaVersion} lerna@${lernaVersion}`

We're installing `lerna` globally. In our CI environment, we probably wouldn't want that done because our global space is shared, and could be made read-only.

```
npm config list
# vs
~/.npm/lerna@3.3.2/bin/lerna exec npm config list
```

The first one only uses the config `.npmrc` written to that project's directory from the `npmrc` config setting.

The second one combines that config with the config in `~/.npmrc`. The project config has precedence, so this shouldn't matter.

```
NPM_CONFIG_REGISTRY=https://private-artifactory.io/api/npm/virtual-npm
vs
registry=https://artifactory.company.com/api/npm/virtual-npm
```

I think this is the problem...

I think is causing the lockfile to include *both* hostnames, however yarn only thinks the `_auth` is for one of them, so the other causes a `401`.

Also, when a dependency is cached, yarn doesn't bother hit the server, so no 401's for cached dependencies, which made this harder to reproduce.

**Comment by rarkins** [comment]
What would you think if I made a config option which means "use globals only". i.e. assume that `lerna`, `npm` and `yarn` are installed globally and not to use any bundled versions OR install any on-demand like `lerna`?

**Comment by rarkins** [comment]
Actually I was planning to do that anyway, as part of a future plan to support `docker` as a new option - i.e. call all external binaries via docker containers. Set `--binary-source=global` or `"binarySource": "global"` or `RENOVATE_BINARY_SOURCE=global` with `renovate@13.67.0` or later and you should see your global `lerna` being called instead.

**Comment by dylang** [comment]
> use globals only

We don't install lerna globally because each team could have a different version of lerna in use, and the whole issue of multiple npm or yarn copies trying to install a package into the same location at the same time and potentially blocking each other.

My preferences:

* If you need to control which version of lerna is used, then include as a dependency of renovate.

* If using the same version that the repo is using is required, then install in a temp directory and clean up on exit.

**Comment by rarkins** [comment]
At this point I don't plan to make the `lerna` install temporary like you suggest, but wouldn't reject a PR if it was backwards-compatible. Renovate has no need to control which version of `lerna` is used, it's only done in order to generate compatible behaviour with what is being used in the repository. You should consider running Renovate inside a Docker container or on a dedicated machine to avoid conflicts with other software.

**Comment by dylang** [comment]
We run in a docker container, but they share a common file system (and home directory). 

I'm not sure why, maybe so cache from one job can help out another, maybe it's a Jenkins thing.

**Comment by dylang** [comment]
We can close this issue, or I can change the title and body, as the real issue seems to be something like <deep breath in>....

Running `~/.../lerna... yarn` combines the project `.npmrc` with the user `~/.npmrc`, which, for some reason, prioritizes the user's registry instead of the project's registry, so the hostnames in the lockfile couldn't be authenticated because they only matched the hostname in the project's `.npmrc`.

**Comment by rarkins** [comment]
Wow, that's a pretty narrow and confusing cause! Good job figuring that out.

How do you normally run `lerna` in this environment if not installing/running it globally? e.g. run it out of `node_modules/.bin/lerna`?

**Comment by dylang** [comment]
Thanks!

Correct, always `yarn lerna ...`. (`yarn <command>` searches both the `scripts` and the `.bin` directory for matching names.)
