### ISSUE TITLE
Renovate not updating all package-lock.json files with lerna repo

### ISSUE THREAD

**Issue by stieg** [renovatebot/renovate#2519]
**What Renovate type are you using?**
Private repo uses Renovate GitHub App,
Was able to reproduce it with Renovate CLI locally on test repo

**Describe the bug**
Renovate is only updating one `package-lock.json` file when it should be updating many.  

Observe the following [repo configured with lerna](https://github.com/stieg/renovate-test) with 3 package dependencies internally:  foo -> bar -> baz.  Foo and Bar depend on lodash in this example and [renovate attempts to update lodash in this PR](https://github.com/stieg/renovate-test/pull/5).  You can see that renovate updates two package.json files, but only updates one lock file.  A subsequent run of `npm install` will update the other lockfile.

Here is the log file of the renovate run when it created the PR mentioned above: [renovate.log](https://github.com/renovatebot/renovate/files/2381526/renovate.log)

**To Reproduce**
1.  Fork https://github.com/stieg/renovate-test
2.  Install renovate locally and get a GH Token to you can run renovate locally.
3.  Run renovate on the fork. It should create the PR with the described issue.

**Expected behavior**
Renovate updates all lockfiles.

If you need anything further please do not hesitate to ask.  Also thanks for your time and effort... it is appreciated.

**Comment by rarkins** [comment]
Thank you for taking the time to prepare the reproduction steps!

Cloning the repo manually and running `lerna bootstrap` resulted in both package lock files showing as modified, as expected:

```
❯ lerna bootstrap -- --package-lock-only --no-audit
info cli using local version of lerna
lerna notice cli v3.3.2
lerna info versioning independent
lerna info Bootstrapping 3 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 3 packages

~/tmp/renovate-test master*
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   packages/bar/package-lock.json
	modified:   packages/bar/package.json
	modified:   packages/foo/package-lock.json
	modified:   packages/foo/package.json

no changes added to commit (use "git add" and/or "git commit -a")
```

So that lead me to check whether our *detection* of changed files was correct, and in this case, it was not.

It should now be fixed, I verified using my fork of your repo: https://github.com/renovate-tests/renovate-test/pull/3/files

Thanks again for the easy reproduction steps which lead to the quick fix.

**Comment by stieg** [comment]
Hell yeah.  Thanks @rarkins !
