### ISSUE TITLE
Allow custom release notes mapping

### ISSUE THREAD

**Issue by Fandekasp** [renovatebot/renovate#2520]
**What would you like Renovate to be able to do?**
Several packages do not get release notes shown on the pull request description. Searching for the release notes online takes too much time (for example the js firebase package release notes are in https://firebase.google.com/support/release-notes/js

**Describe the solution you'd like**
Please let us configure custom mappings, eg firebase => https://firebase.google.com/support/release-notes/js . If it's difficult to parse and populate the PR description with the notes from custom links, just showing the link will be fine.

**Comment by rarkins** [comment]
This has been implemented as part of code, with `firebase` on npmjs being the first and only package with a manual mapping.

**Comment by Fandekasp** [comment]
@rarkins sorry, I must have misunderstood the usage convention. How do you use changelogUrls ?
![](https://i.imgur.com/RjfdDGM.png)

renovate.json
```json
{
  "extends": [
    "config:base"
  ],
  …
  "changelogUrls": {
    "firebase": "https://firebase.google.com/support/release-notes/js",
    "flow-bin": "https://github.com/facebook/flow/blob/master/Changelog.md"
  }
}
```

**Comment by rarkins** [comment]
@Fandekasp right now it's hardcoded in source code as I think any URLs would apply to all users anyway. I've created a PR just now for `flow-bin`: https://github.com/renovatebot/renovate/pull/2534

**Comment by Fandekasp** [comment]
oh ok... there are lots of repos with custom changelogs, so making a PR on
renovate everytime doesn't sound very scalable.
But alright, I'll do that, thanks for the quick reply

**Comment by rarkins** [comment]
Well, as shown in that PR - it's just a one-line PR necessary, so really about the same work as adding it to your config anyway, and this way everyone else will get it as a bonus.
