### ISSUE TITLE
Github label to instruct renovate to rebase a single stale PR 

### ISSUE THREAD

**Issue by danlunde** [renovatebot/renovate#2521]
**What would you like Renovate to be able to do?**
There's been a number of occasions where a renovate branch will fail one or more of our PR checks and tests due to an incompatible dependence on a different package.  Often the problem will be resolved after merging in a separate renovate branch, however that branch doesn't create a merge conflict with the original renovate branch, the original won't get rebased on master and the checks will continue to fail.

**Describe the solution you'd like**
A method to opt-in a renovate PR to rebase itself without having to `rebaseStalePrs` on for every renovate PR.  My suggestion would be to add a custom `rebase` or similar label onto the PR, then the next time renovate runs it will rebase the branch and remove the label.

**Describe alternatives you've considered**
According to https://renovatebot.com/docs/updating-rebasing/, I could set `rebaseStalePrs` to true, but that will generate a lot of unnecessary churn with our CI and this problem doesn't occur often enough to go that route.  That's also the reason we don't have "Require branches to be up to date before merging" turned on.  Maybe there's already a way to perform this function in a one-off manner, but I couldn't find it.

Thanks for your consideration!

**Comment by rarkins** [comment]
Thanks for the suggestion. I will combine it with #1406 and close this.
