### ISSUE TITLE
Validate config.js and _WARN_ for any config errors

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25274]
### Describe the proposed change(s).

Global config (e.g. config.js, but also including `RENOVATE_CONFIG`) should be validated and a log warning issued if they contain invalid values.

This warning should *not* show up in _repos_ (e.g. in dependency dashboard).

We will upgrade this severity to ERROR and then FATAL in future major releases

**Comment by RahulGautamSingh** [comment]
If someone needs to validate their config.js or equivalent file config then they run `config-validator` for it. We do not validate the `config.js` file during repo runs, should we add that as a part of this issue?

**Comment by RahulGautamSingh** [comment]
Is this similar to https://github.com/renovatebot/renovate/issues/23868

**Comment by rarkins** [comment]
We should do this at runtime when the config.js is loaded ("file config")

**Comment by RahulGautamSingh** [comment]
For file config we can validate the already migrated config here:
https://github.com/renovatebot/renovate/blob/3c0792569df6b0dc955895d597b8315f5a855e62/lib/workers/global/config/parse/file.ts#L86-L94

And for the config inside `RENOVATE_CONFIG` we will need to first migrate and the validate the config here:
https://github.com/renovatebot/renovate/blob/3c0792569df6b0dc955895d597b8315f5a855e62/lib/workers/global/config/parse/env.ts#L96-L104

**Comment by rarkins** [comment]
If RENOVATE_CONFIG isn't migrated already, that should be added
