### ISSUE TITLE
Support Docker uses in GitHub Actions

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25276]
### Describe the proposed change(s).

Support `docker://` images as documented here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-docker-hub-action

**Comment by viceice** [comment]
closing, as we do support that

https://github.com/renovatebot/renovate/blob/e13f5a09f5cb6266e7ed7f1856cb4d1fe9eb04f1/lib/modules/manager/github-actions/extract.ts#L55-L62
