### ISSUE TITLE
Support pnpm workspaces

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25335]
### Discussed in https://github.com/renovatebot/renovate/discussions/25330

<div type='discussions-op-text'>

<sup>Originally posted by **kachkaev** October 20, 2023</sup>
### Tell us more.

This feature request is similar to https://github.com/renovatebot/renovate/issues/20324 (fixed in https://github.com/renovatebot/renovate/pull/20420).

Unlike yarn and npm, pnpm [relies on `pnpm-workspace.yaml`](https://pnpm.io/workspaces) as a source of truth for monorepo workspaces. Usage of `package.json` → `workspaces` is not supported (https://github.com/pnpm/pnpm/issues/2255).

I created `packages/@local/eslint-config` and `packages/@local/eslint-config` in a private monoepo. These folders define two private packages named `"@local/eslint-config"` and `"@local/tsconfig"`. Two other workspaces (in `apps/*`) declare `@local/*` packages as `devDependencies`.

The setup is working, but Renovate Dashboard shows this now:

---

> [!WARNING]
> Renovate failed to look up the following dependencies: `Failed to look up npm package @local/eslint-config`, `Failed to look up npm package @local/tsconfig`.
> 
> Files affected: `apps/a/package.json`, `apps/b/package.json`

---

My `pnpm-workspaces.yaml` contains the following:

```yaml
packages:
  - apps/*
  - packages/*
  - packages/@local/*
```

The issue is non-blocking, i.e. it does not break anything. The warning is a bit confusing but folks can live with it.

Hope that getting the list of workspaces from `pnpm-workspace.yaml` is not too hard given that https://github.com/renovatebot/renovate/pull/20420 is already working. Happy to help with testing. Renovate rocks! 💯 

---

**UPD**: Reproduction: 

- Repo: [kachkaev/renovate-pnpm-monorepo-mwe](https://github.com/kachkaev/renovate-pnpm-monorepo-mwe)
- Renovate Dashboard with a warning: https://github.com/kachkaev/renovate-pnpm-monorepo-mwe/issues/1
- Renovate PR with a warning: https://github.com/kachkaev/renovate-pnpm-monorepo-mwe/pull/2
</div>

**Comment by kachkaev** [comment]
:wave: @rarkins! I think that I have found a solution: [replacing](https://github.com/kachkaev/renovate-pnpm-monorepo-mwe/commit/b2b609c905252c73771a8833ace56a9f88eee8c6) `"@local/something": "0.0.0-private",` with `"@local/eslint-config": "workspace:0.0.0-private",` does the job. I can no longer see a warning in https://github.com/kachkaev/renovate-pnpm-monorepo-mwe/issues/1!

I discovered this solution after struggling to upgrade pnpm from v8 to v9: https://github.com/kachkaev/renovate-pnpm-monorepo-mwe/issues/1. Running `pnpm install` failed even without Renovate in the loop. After reading [docs on workspaces](https://pnpm.io/workspaces), I prepended local versions with `workspace:` and it worked. Renovate is happy too: bumping pnpm from v8 to v9 is now possible: https://github.com/kachkaev/renovate-pnpm-monorepo-mwe/issues/6.

I am going to close this issue, assuming that [my trick](https://github.com/kachkaev/renovate-pnpm-monorepo-mwe/commit/b2b609c905252c73771a8833ace56a9f88eee8c6) works for everyone. I believe that it’s needed to upgrade monorepos from pnpm v8 to v9 anyway. If that’s not true, please share your thoughts below.

**Comment by rarkins** [comment]
Even though you _can_ get it to work, does this still deserve a feature request for Renovate to support the syntax which doesn't work? Or do you mean that this syntax change was necessary for pnpm v9 anyway, independently of Renovate?

**Comment by kachkaev** [comment]
> syntax change was necessary for pnpm v9 anyway, independently of Renovate

This. It’s impossible to use pnpm v9 without adding `workspace:` prefixes in `package.json`s inside a monorepo. pnpm v8 is happy with the prefixes too. When prefixes are added, Renovate works without warnings 👍

**Comment by kachkaev** [comment]
Yep, I guess we can close this issue. If folks experience other problems with pnpm in Renovate, they can open new ones.

[Adding `workspace:` to local workspace references](https://github.com/kachkaev/renovate-pnpm-monorepo-mwe/commit/b2b609c905252c73771a8833ace56a9f88eee8c6) is what solves the current issue. No changes are necessary on the Renovate side.
