### ISSUE TITLE
Semantic releases

### ISSUE THREAD

**Issue by Fandekasp** [renovatebot/renovate#2541]
**What would you like Renovate to be able to do?**
Renovate PRs are not semantic, and the github app [semantic pull requests](https://github.com/probot/semantic-pull-requests) fails for them.
Semantic titles would allow us to have release notes auto-prepared for us. Right now, we have to manually add the chore package upgrade notes. 

**Describe the solution you'd like**
Please format renovate PR titles using [conventional commit messages](https://conventionalcommits.org/)

**Comment by rarkins** [comment]
Semantic type and scope are completely configurable. What type of title are you currently seeing and what do you want them to be?

**Comment by rarkins** [comment]
By the way, this is a configuration help question so in future please raise similar types of questions in https://github.com/renovatebot/config-help

**Comment by rarkins** [comment]
If you go to https://renovatebot.com/docs and search for "semantic", you can see many options:

![image](https://user-images.githubusercontent.com/6311784/45798484-57e6b600-bcaa-11e8-82c0-298d40f411ae.png)

The `"config:base"` preset ships with https://renovatebot.com/docs/presets-default/#semanticprefixfixdepschoreothers included, so if using fix/chore doesn't meet your requirements then you should remove `config:base` and replace it with customise settings.

**Comment by Fandekasp** [comment]
@rarkins sorry about that, I should have spent more time looking in the docs. Thank you for the support !

**Comment by rarkins** [comment]
@Fandekasp you're welcome. Feel free to post an issue into config-help if you run into any confusion. In short:

- Renovate tries to detect if you're already using semantic commits and if so then they're enabled. However you can also force them on permanently too
- The "config:base" preset includes an "opinionated" preset with "fix" for dependencies and "chore" for others. 
- You can see an example of overriding this preset in this repo's config: https://github.com/renovatebot/renovate/blob/6c7992f7f327c2b2a26737bffd527005ee3bfbc4/renovate.json#L10-L23
