### ISSUE TITLE
pep440: failed to calculate newValue

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25501]
### Discussed in https://github.com/renovatebot/renovate/discussions/25495

<div type='discussions-op-text'>

<sup>Originally posted by **nijel** October 30, 2023</sup>
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

When the current package version from PyPI is restricted in the dependencies, a warning appears: `pep440: failed to calculate newValue`.

It is also shown as an error in the Rennovate app:

![obrazek](https://github.com/renovatebot/renovate/assets/212189/ed5adc2a-9c35-4daa-9c31-4839949e15b3)

Presently, this can be reproduced with the following `requirements.txt`: 

```requirements-txt
sentry-sdk>=1.25.0,<2,!=1.32.0
```

I understand that there is no update possible, but the warning makes it quite hard to see what is going on.

EDIT: Reproducer repo is at https://github.com/nijel/renovate-25495

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: pep440: failed to calculate newValue
{
  "result": ">=1.25.0,<2,!=1.32.0"
  "newVersion": "1.32.0"
  "currentValue": ">=1.25.0,<2,!=1.32.0"
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above</div>

**Comment by RahulGautamSingh** [comment]
I think the fix here is to add an if-statement to check whether the `newVersion` is excluded from `range`. And, if so log a DEBUG message informing of the same instead of the current warning.
