### ISSUE TITLE
Support configurable versions of npm/yarn/etc

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2565]
**What would you like Renovate to be able to do?**

Adapt which version of npm/yarn/pnpm is run, per-repo

**Describe the solution you'd like**

Renovate looks at version ranges in `package.json`>`engines` to "guess" at the best to use, but ideally also has its own config option to override that if necessary.

**Describe alternatives you've considered**

Right now Renovate tries to stick with the latest stable version of each tool, and apply that to repo.

**Additional context**

Previously `npm` and now `yarn` have introduced changes to lock file format that cause "flapping" between versions. For `yarn` right now, version 1.10.x will *add* `integrity` fields to every package entry, while version 1.9.x will *remove* them again. This means it's important that every device in a project sticks with the same version of `yarn`, including Renovate. Which means Renovate needs to make its versions configurable.

**Comment by tknickman** [comment]
Hey @rarkins, we would love to use this for our renovate enterprise on-prem install. Any updates here / ways we could help out? 

Thanks!

**Comment by rarkins** [comment]
Here's what needs to be done to get dynamic-switching Docker-based binaries in use:
- [ ] Add logic to our `lib/manager/npm` extract logic to detect/store applicable values into the "compatibility" object. We should probably do this for both `node` as well as npm/yarn/pnpm as applicable. For reference, see how it's done for bundler in this file: https://github.com/renovatebot/renovate/blob/edf85d42bf9589c9ca1809fd84e14c28be56294d/lib/manager/bundler/extract.ts#L39
- [ ] Ensure Renovate's [npm](https://github.com/renovatebot/docker-npm), [yarn](https://github.com/renovatebot/docker-yarn) and [pnpm](https://github.com/renovatebot/docker-pnpm) Docker images have been building and pushing to Docker Hub as expected
- [ ] Add logic to Renovate's lib/npm/post-update functions so that they query Docker Hub to determine the best `renovate/<manager>` image to use

**Comment by rarkins** [comment]
This is now complete in v20.23.0
