### ISSUE TITLE
Support bazel "urls" array

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2576]
Example:

```
http_archive(
    name = "bazel_skylib",
    sha256 = "b5f6abe419da897b7901f90cbab08af958b97a8f3575b0d3dd062ac7ce78541f",
    strip_prefix = "bazel-skylib-0.5.0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/archive/0.5.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/archive/0.5.0.tar.gz",
    ],
)
```
([source](https://github.com/renovate-tests/bazel-watcher/blob/master/WORKSPACE))

Transferring from https://github.com/renovatebot/config-help/issues/99, Cc @achew22

1. Check if any of the urls points to a GitHub repo
2. Check if that GitHub repo contains a newer release
3. If so, update X.tar.gz in all URLs to match newer release Y.tar.gz
4. Handle "archive" links instead of "releases"

**Comment by achew22** [comment]
@rarkins, thanks so much for doing this! It looks like you've got all the bots. Do you know how long this takes to roll out to production? Should I expect a PR in the next few weeks/days? Would you like me to update this thread when that happens?

**Comment by rarkins** [comment]
@achew22 check out https://github.com/bazelbuild/bazel-watcher/pull/149#issuecomment-433991351 for next steps
