### ISSUE TITLE
Default RENOVATE_X_DOCKER_HUB_TAG behavior to true

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25804]
### Describe the proposed change(s).

Default to behavior currently controlled by RENOVATE_X_DOCKER_HUB_TAG

**Comment by RahulGautamSingh** [comment]
Should we pass it to v39?

**Comment by rarkins** [comment]
It wasn't already done? I thought we flipped the logic

**Comment by RahulGautamSingh** [comment]
Yes, seems done https://docs.renovatebot.com/self-hosted-experimental/#renovate_x_docker_hub_tags_disable

**Comment by viceice** [comment]
fixed in #28400
