### ISSUE TITLE
Go modules - vendoring support

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2580]
Third step for go modules support - updating `vendor/` directory along with `go.mod` and `go.sum`.

**Comment by rarkins** [comment]
Waiting on #2431

**Comment by rarkins** [comment]
I think we would need to run an additional `go mod vendor` command. 

I'm not sure whether to run it with the source code present or not. It would be easier to just run it in the cloned dir which already had `vendor/` files but takes a lot longer with source code present.

Also, ideally we could update the vendoring for just *one* of the modules, not others which may not be relevant to the PR.

**Comment by rarkins** [comment]
Waiting on #2431

**Comment by paultyng** [comment]
If you have the code it would also be useful to run a `go mod tidy` as some dependencies may no longer be necessary with a version bump I think?

**Comment by rarkins** [comment]
@paultyng yes, we can do that too - although I have some doubts about whether everyone would want that. Unless everyone else in the project has diligently tidied the checksum file then you’ll see Renovate’s tidying removing a confusing number of lines unrelated to the actual PR’s changes to go.mod. Russ Cox’s opinion seems to be that users shouldn’t fixate too much on “old” lines in go.sum.

**Comment by rarkins** [comment]
`go mod tidy` also seems to have at least one bug right now too: https://github.com/golang/go/issues/27868

**Comment by paultyng** [comment]
Good point, vendoring is definitely the priority.

**Comment by rarkins** [comment]
@paultyng do you have any public repo requiring vendoring that I can use to test with when we implement?

**Comment by paultyng** [comment]
Any of our apps in https://github.com/hashicorp or https://github.com/terraform-providers vendor (not our libraries). Specifically you could look at https://github.com/terraform-providers/terraform-provider-newrelic which was the one I was playing with for automatic PR creation.

**Comment by paultyng** [comment]
@rarkins any news on this? I would happily upgrade to Pro (if we aren't already) to use this with all our Go repos.

**Comment by rarkins** [comment]
@paultyng I think this one can be completed pretty soon actually. Thanks for the reminder!

**Comment by rarkins** [comment]
@paultyng FYI here is an example from the work in progress: https://github.com/renovate-tests/terraform-provider-newrelic/pull/14

**Comment by paultyng** [comment]
This is great! Will it be optional whether you want a `tidy`, a `vendor`, or both?

**Comment by bflad** [comment]
@rarkins awesome!! Very excited for this. Great work.

**Comment by rarkins** [comment]
I thought vendor should run every time if there’s a `vendor/modules.txt`, would you agree? Tidying would be optional

**Comment by paultyng** [comment]
@rarkins yeah that sounds reasonable to me!

**Comment by adamdecaf** [comment]
How does this get enabled for a project? I recently had renovatebot update modules, but not `vendor/`. (See: https://github.com/moov-io/ach/pull/490)

I'm not seeing configuration options to force `go mod vendor` either: https://renovatebot.com/docs/configuration-options/#gomod

**Comment by rarkins** [comment]
@adamdecaf right now I am doing the switch manually and check the logs every day or two for repos that need it. I switched all of `moov-io/` over now so the next time you rebase that PR you should see the results. BTW you can always check renovatebot.com/dashboard for logs.

**Comment by adamdecaf** [comment]
Oh cool! I didn't know about renovatebot.com/dashboard, thanks!
