### ISSUE TITLE
yarn integrity hashes being removed when using lerna

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#2589]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The existing integrity hashes in `yarn.lock` are being removed in a Renovate PR, even after #2567.

See:
neutrinojs/neutrino#1151

**Did you see anything helpful in debug logs?**
I don't see the string "Using yarn@1.10 for install" (from #2567) in the log:
https://renovatebot.com/dashboard#neutrinojs/neutrino/22386063

**To Reproduce**

1.  Have yarn integrity hashes preset in `yarn.lock` for https://github.com/neutrinojs/neutrino
2.  Inspect future Renovate PRs to ensure they preserve the hashes

**Expected behavior**
Hashes are not removed

**Comment by edmorley** [comment]
In comparison the hashes were not removed for this equivalent PR in another repo:
neutrinojs/webpack-chain#108

**Comment by rarkins** [comment]
@edmorley 	I've worked out that this is when `yarn` is called via `lerna`. I'm thinking of just calling `yarn` directly instead of via `lerna`.

**Comment by edmorley** [comment]
Many thanks :-)
