### ISSUE TITLE
commitBody is ignored for onboarding branch commit

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25943]
### Discussed in https://github.com/renovatebot/renovate/discussions/25926

<div type='discussions-op-text'>

<sup>Originally posted by **lmilbaum** November 23, 2023</sup>
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, select which platform you are using.

github.com

### What is your question?

How can I make those commits to be signed-off?

Thanks

### Logs (if relevant)

<details><summary>Logs</summary>

```

Copy/paste the relevant log(s) here, between the starting and ending backticks

```

</details>
</div>

**Comment by RahulGautamSingh** [comment]
Do we want other template values except `gitAuthor` inside the onboarding commit message?

**Comment by rarkins** [comment]
No
