### ISSUE TITLE
Master issue for listing/approving PRs

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2595]
**What would you like Renovate to be able to do?**

In discussion with @edmorley in the Yarn repository, @arcanis suggested providing a manual approval step for most PRs with a dedicated issue be created to contain that list for approval. Using this list, maintainers can select which PRs to create, from a pending approval list. The main goal is to reduce "noise" and provide a way to reduce CI cycles consumed by Renovate PRs.

**Describe the solution you'd like**

Now:

- Option to create a "master issue" per-repo that lists each PR and its state, even if an approval step is not required
- Option to configure (selectively or for all updates) whether manual approval is required or not
- Renovate blocks branch creation until PRs are approved

Future:
- Allow the use case where *branches* can be created/updated at any time but PRs require the manual approval

**Describe alternatives you've considered**

Something similar could be done in a dedicated "dashboard" however that's a step removed from repository people already use and hence may not be noticed/used. By having it in an issue in the repo it more rightly integrates with regular workflows.

**Additional context**

Screenshot of prototype:

![image](https://user-images.githubusercontent.com/6311784/46400348-875ddf80-c6fa-11e8-8884-e9db9d5e41cd.png)

**Comment by rarkins** [comment]
This might be ready for release (behind a feature flag of course) tomorrow. Some things I found today:
- You need to play some HTML tricks to get checkboxes to render inside tables (with GitHub Flavored Markdown)
- Once you play those tricks, GitHub's neat "clicking a checkbox implicitly edits the markdown behind it" stops working

So I have reverted back to headings and lists instead of tables.

Something else I thought about was whether to "alert" users by @ mentioning their usernames in the issue, but the problem is:
- this issue is likely to be long-lived,
- once you're mentioned in an issue, you're permanently linked to it

So for now: no @ mentions in the issue body.

I will also add a webhook to detect edits to the issue and trigger a run. In lieu of being about to debounce, each edit will have a one minute delay before triggering a job. That way the user has one minute to get all their checkboxing out of the way before running the risk of competing with the bot over editing the master issue content.

**Comment by edmorley** [comment]
If I understood https://github.com/yarnpkg/yarn/pull/6463#issuecomment-426326928 correctly, one of the bigger concerns was that of CI load.

There are a few features already supported by Renovate that would reduce CI load for a repository:
* using a schedule and having PRs only be opened at weekends/off peak hours
* using the option that stops Renovate from automatically rebasing, so if a backlog of open PRs accumulates, then they don't spam CI each time there are yarn.lock conflicts etc
* grouping dependency updates into one PR (either across the board, or say devDependencies only, or at least making sure the list of known monorepos is kept up to date)
* having auto-merge set for eg eslint devDependencies, so if CI passes they are merged automatically - thereby reducing the chance of a PR backlog from accumulating

I wonder if these need to be emphasised more in the docs? Whilst this new feature looks awesome, and for some people is probably the best fit for their desired workflow - it will presumably mean it's more likely dependency updates are ignored and a project's dependencies become progressively out of date - whereas if people knew about the above features, they might not need this more extreme feature in as many cases.

**Comment by rarkins** [comment]
@edmorley all the above points are valid, including that better documentation would help. In the Yarn case the ones being closed are all major upgrades perhaps deferred until a later Yarn major version, although I think plenty of them should not actually need to wait for a major of Yarn and the project risks missing out of bug fixes that aren't backported to the major version that Yarn is on. Maybe the project will settle on automatically creating patch/minor updates and only holding back major versions.

By the way, this new "master issue" is also supported even if you don't want the approval workflow. i.e. no less PRs than today, just an additional issue to summarise them all. You could think of it then as a kind of dashboard-within-the-repo.

I am planning a second revision of it where the approval step is at PR creation, not branch creation. e.g. you can still use schedules to determine when branches are created and updated, ideally during times that are not disturbing to teams or CI queues. But then prCreation would be set to 'manual-approve' or something like that, which means it can only be done via the master issue. This way you can see a dashboard of updates which have had branches created and tested, but decide if/when to raise them as PRs for reviewing release notes and merging. *Maybe* also even selecting to automerge them in place without PR, but that would come later still.

**Comment by edmorley** [comment]
Oh that sounds pretty handy :-)
