### ISSUE TITLE
Could Renovate apply edits to go.mod to ignore out-of-repo references?

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#2596]
**What would you like Renovate to be able to do?**
We have a `replace` directive in go.mod like this:
```
replace github.com/sourcegraph/sourcegraph => ../sourcegraph
```
It makes an assumption that devs have the repo checked out in `../sourcegraph` to make sure we are always using the latest version locally.
Unfortunately, this breaks all Renovate Go module updates because the path cannot be found.

This is not a problem with npm where `npm link` creates symlinks in `node_modules` that are gitignored, but the only way Go supports this is with a replace directive inside go.mod.

**Describe the solution you'd like**
Maybe we could configure Renovate to remove the replace directive before updating with `go mod edit -replace=github.com/sourcegraph/sourcegraph`, or by having it automatically remove all replace directives that point to relative paths outside of the repo?

**Comment by rarkins** [comment]
I think that removing all relative replace paths sounds like a good idea.
