### ISSUE TITLE
Migration guide for self hosted Docker

### ISSUE THREAD

**Issue by kunagpal** [renovatebot/renovate#2598]
**What would you like Renovate to be able to do?**
Provide details on how to migrate from older Docker images to newer ones.

**Describe the solution you'd like**
A migration guide that outlines the steps that should be taken to upgrade to a newer Docker image version for self-hosted variants of renovate.

**Describe alternatives you've considered**
N.A

**Additional context**
N.A

P.S: Thanks for building this tool 😄

**Comment by rarkins** [comment]
Can you give me an idea of what type of information you were looking for?

**Comment by kunagpal** [comment]
@rarkins Something along the lines of any caveats or quirks to be aware of, or any migration steps involved for databases/caches other such resources (if applicable).

**Comment by rarkins** [comment]
Right now there's not really anything to list along these lines. The structure of the Docker image has never changed, and semantic versioning is always used so you can know if a change is backwards compatible or not. The Renovate OSS Docker image uses no database so nothing to migrate there, and caching is not something we provide guidance on.

**Comment by kunagpal** [comment]
@rarkins Thanks for clearing that up 😄
