### ISSUE TITLE
Renovate Docker image is missing "go" tool

### ISSUE THREAD

**Issue by mxey** [renovatebot/renovate#2602]
**What Renovate type are you using?**
Renovate CLI in official Docker image

**Describe the bug**
Renovate created a Merge Request for updating `go.mod` containing this error message:

```
Command failed: go get
/bin/sh: go: not found
 `go get` (exited with error code 127)
```

**To Reproduce**

1.  Create repository with go.mod
2. Run Renovate from Docker image against that repository

**Expected behavior**

Renovate creates a Merge Request to update dependencies without an error

**Screenshots**
<img width="873" alt="bildschirmfoto 2018-10-05 um 11 58 37" src="https://user-images.githubusercontent.com/128020/46529168-03d8f580-c896-11e8-8c88-c6a8a204b4bd.png">

**Additional context**

You can probably include the Go SDK into your Docker image quite easily using `COPY --from=golang…`

**Comment by rarkins** [comment]
Thanks @mxey
