### ISSUE TITLE
[BUG] Renovate Dashboard: cannot load repos for users with 100+ repos

### ISSUE THREAD

**Issue by amilajack** [renovatebot/renovate#2605]
**What Renovate type are you using?**
Renovate Dashboard

**Describe the bug**
Renovate dashboard only shows first 100 repos

**Did you see anything helpful in debug logs?**
There is a query limit of 100

**To Reproduce**
1. Make sure you have 100+ repos.
2. Scroll down. No more repos will load

**Expected behavior**
More repos should paginate when scrolling down. So users with n projects will not be able to see n - 100 projects

**Screenshots**
<img width="568" alt="screen shot 2018-10-05 at 9 50 32 am" src="https://user-images.githubusercontent.com/6374832/46548791-ecddd780-c884-11e8-9d12-54f8d095931e.png">

This is the end of my repos list. as you can see it only ends at "b"

**Comment by rarkins** [comment]
Thanks for the bug report. Until it's fixed, you can click on one of the ones that is displayed and then just edit the URL to get to the one you want.

**Comment by rarkins** [comment]
This is now resolved

**Comment by ahmadnassri** [comment]
thank you!
