### ISSUE TITLE
Renovate Docker Image: Cannot find module '/usr/src/app/bin/yarn-1.10.1.js'

### ISSUE THREAD

**Issue by busybeaver** [renovatebot/renovate#2609]
**What Renovate type are you using?**
Renovate Docker Image: `renovate/renovate:13.98.0`

**Describe the bug**

When running Renovate via Docker (and GitHub Enterprise), the following exception occurred when Renovate tries to update the `yarn.lock` file (1.10.x format with integrity hashes):

```js
module.js:550
    throw err;
    ^

Error: Cannot find module '/usr/src/app/bin/yarn-1.10.1.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

The `package.json` is still properly updated, however, the `yarn.lock` is not.

Looking within the docker image (via `docker run -it --entrypoint=/bin/sh renovate/renovate:13.98.0`), it seems like the file is missing (actually, there is no _bin_ folder at all):

```bash
/usr/src/app $ ls -la
total 392
drwxr-xr-x    1 root     root          4096 Oct  6 08:06 .
drwxr-xr-x    1 root     root          4096 Sep 17 12:17 ..
drwxr-xr-x   10 root     root          4096 Oct  6 08:06 lib
drwxr-xr-x  648 root     root         20480 Oct  6 08:05 node_modules
-rw-r--r--    1 root     root          5353 Oct  6 08:00 package.json
-rw-r--r--    1 root     root        357265 Oct  6 08:00 yarn.lock
```

**To Reproduce**

1.  Create repository with a `yarn.lock` format that includes integrity hashes
2.  Configure the `package.json` engines options to require yarn >= 1.10.x
3.  Run the docker image

**Expected behavior**

The `package.json` and the `yarn.lock` get properly updated (including the integrity hashes).

**Screenshots**

This comment is posted by Renovate in the GitHub PR:

> ![image](https://user-images.githubusercontent.com/858259/46576126-6c71c080-c9c3-11e8-9b71-3102aea032dc.png)

**Additional context**

* Renovate: `renovate/renovate:13.98.0`, executed via k8s cron job
* GitHub Enterprise: 2.13.2

**Comment by rarkins** [comment]
@busybeaver thanks for raising the issue with great troubleshooting details. I've now made sure that bin/yarn* is added to the published Docker image. Please confirm if renovate/renovate:13.99.5 works fine for you - I've confirmed that the Yarn binary is now where I expect it to be.

**Comment by busybeaver** [comment]
@rarkins thanks for the quick fix! I can confirm that it's working as expected with version _13.99.5_ 👍
