### ISSUE TITLE
Incorrect title "docker digest to vundefined"

### ISSUE THREAD

**Issue by teppeis** [renovatebot/renovate#2613]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

`vundefined` in this title is weird.

> ci(docker): update circleci/node:10 docker digest to vundefined #228
> https://github.com/kintone/webpack-plugin-kintone-plugin/pull/228

**To Reproduce**

Based on this config: https://github.com/teppeis/renovate-config

**Expected behavior**

?

**Additional context**

Previous week, the title was different.

> ci(docker): update node docker digests in circleci #223
> https://github.com/kintone/webpack-plugin-kintone-plugin/pull/223

**Comment by teppeis** [comment]
other samples: https://github.com/search?q=vundefined+renovate&type=Issues

**Comment by rarkins** [comment]
Thanks @teppeis. I am also fixing some cosmetic problems in the PR body that I noticed at the same time.

**Comment by teppeis** [comment]
@rarkins thanks!
