### ISSUE TITLE
loose versioning should sort numeric parts numerically

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#26136]
### Describe the proposed change(s).

This unit test addition should pass:

```
diff --git a/lib/modules/versioning/loose/index.spec.ts b/lib/modules/versioning/loose/index.spec.ts
index 81b94d579..9d19c2f90 100644
--- a/lib/modules/versioning/loose/index.spec.ts
+++ b/lib/modules/versioning/loose/index.spec.ts
@@ -53,6 +53,7 @@ describe('modules/versioning/loose/index', () => {
     a                               | b                               | expected
     ${'2.4.0'}                      | ${'2.4'}                        | ${true}
     ${'2.4.2'}                      | ${'2.4.1'}                      | ${true}
+    ${'2.4.100'}                    | ${'2.4.99'}                     | ${true}
     ${'2.4.beta'}                   | ${'2.4.alpha'}                  | ${true}
     ${'1.9'}                        | ${'2'}                          | ${false}
     ${'1.9'}                        | ${'1.9.1'}                      | ${false}
@@ -63,6 +64,7 @@ describe('modules/versioning/loose/index', () => {
     ${'2024-07-21T11-33-05.abc123'} | ${'2023-06-21T11-33-05.abc123'} | ${true}
     ${'2023-07-21T11-33-05.abc123'} | ${'2023-07-21T11-33-04.abc123'} | ${true}
     ${'2023-07-21-113305-abc123'}   | ${'2023-07-21-113304-abc123'}   | ${true}
+    ${'1.1.5-100'}                  | ${'1.1.5-99'}                   | ${true}
   `('isGreaterThan("$a", "$b") === $expected', ({ a, b, expected }) => {
     expect(loose.isGreaterThan(a, b)).toBe(expected);
   });
```

**Comment by RahulGautamSingh** [comment]
I guess we will need to create a new function that traverses both the strings and compares char by char. Except that when it finds a digit in both the strings then it stops, looks for the entire integer the digits belongs to and comapres them.

Something similar to : https://github.com/sawano/alphanumeric-comparator

**Comment by RahulGautamSingh** [comment]
This implementation passes all the tests inclusing the one you mentioned above:

```ts
function compareAlphaNumericStrings(str1: string, str2: string): number {
  let i = 0,
    j = 0;

  while (i < str1.length && j < str2.length) {
    // eslint-disable-next-line no-negated-condition

    if (isDigit(str1[i]) && isDigit(str2[j])) {
      const num1 = extractNumber(str1, i);
      const num2 = extractNumber(str2, j);
      if (num1 !== num2) {
        return num1 - num2;
      }
      i += String(num1).length;
      j += String(num2).length;
    } else {
      if (str1[i] !== str2[j]) {
        return str1[i].localeCompare(str2[j]);
      }

      i++;
      j++;
    }
  }

  return str1.length - str2.length;
}

function isDigit(ch: string): boolean {
  return /\d/.test(ch);
}

function extractNumber(str: string, startIndex: number): number {
  let endIndex = startIndex;
  while (endIndex < str.length && isDigit(str[endIndex])) {
    endIndex++;
  }
  return parseInt(str.substring(startIndex, endIndex), 10);
}
```

**Comment by rarkins** [comment]
I think this function already exists because it uses this logic for most parts already. Eg 1.10.0 sorts higher than 1.9.0

**Comment by RahulGautamSingh** [comment]
Yes, that is because the version `1.10.0` and `1.9.0` is parsed as 
```{release: [1, 10, 0], suffix: ''}``` and ```{release: [1, 9, 0], suffix: ''}``` prior to comparing them. Hence comparing the releases is enoigh to get correct result.

If we compare these versions `1.10.0.100` and `1.10.0.99`, then  `1.10.0.100` will be sorted lower than `1.10.0.99`.
This is because the versions are parsed as
```1.10.0.100: {release: [1], suffix: '.10.0.100'}``` and ```1.10.0.99: {release: [1], suffix: '.10.0.99'}```. 

Since the release is same we move to comparing the suffixes, and they are compared as strings.

So I think a new comparing method is need to comapre the suffixes.

**Comment by RahulGautamSingh** [comment]
The current parse function which correctly compares the `1.10.0` & `1.9.0`, is custom designed to handle two kinds of versions 
1. numeric 
2. semver-like versions (versions in which digits are separated by a `.`)

As per the parsing logic used for current implementation:
`1.10.0` parses to ``` { release: [1, 10, 0], suffix: ''} ```
`1.10.0-100` parses to ``` { release: [1, 10, 0], suffix: '-100' } ```
`2024-07-21T11-33-05.abc123` parses to ``` { release: [2024], suffix: '-07-21T11-33-05.abc123' } ```
`2.4.beta` parses to ```{ release: [2, 4], suffix: '.beta' }``` 

The compare logic is as follows:
1. compare the elements of the `release` and return a diff if it exists
2. if no diff exists then compare the suffix using `String.localCompare

**Comment by viceice** [comment]
I think we just need to.add the numeric option to the local compare 

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#options
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator#numeric

**Comment by RahulGautamSingh** [comment]
I did look into it, but I think it should be used for numeric strings rather than alphanumeric strings. I will try to find its implementation and confirm.
