### ISSUE TITLE
GitLabError: 404 Branch Not Found

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#2614]
**What Renovate type are you using?**
Renovate Docker run via GitLab CI

**Describe the bug**
If you delete a branch in GitLab, it causes an error in renovate log:

```
WARN: Error getting PR branch (repository=<project>, dependencies=vue-router, branch=renovate/vue-router-3.x)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.com",
         "hostname": "gitlab.com",
         "method": "GET",
         "path": "/api/v4/projects/<project>/repository/branches/renovate%2Fvue-router-3.x",
         "protocol": "https:",
         "url": "https://gitlab.com/api/v4/projects/<project>/repository/branches/renovate%2Fvue-router-3.x",
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "nginx",
           "date": "Mon, 08 Oct 2018 09:19:59 GMT",
           "content-type": "application/json",
           "content-length": "34",
           "connection": "close",
           "cache-control": "no-cache",
           "vary": "Origin",
           "x-content-type-options": "nosniff",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "ba0f7a0a-b8d0-43e7-91ec-4550b58fc765",
           "x-runtime": "0.028301",
           "ratelimit-limit": "600",
           "ratelimit-observed": "3",
           "ratelimit-remaining": "597",
           "ratelimit-reset": "1538990459",
           "ratelimit-resettime": "Tue, 08 Oct 2018 09:20:59 GMT"
         },
         "body": {"message": "404 Branch Not Found"},
         "message": "404 Branch Not Found (404)",
         "stack": "GitLabError: 404 Branch Not Found (404)\n    at stream.catch.then.data (/usr/src/app/node_modules/gl-got/node_modules/got/index.js:182:13)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
       }
```

This causes the script to return a failure (return code 1)

**To Reproduce**

1.  Get Renovate to make an MR
2.  Close the MR and Delete the branch
3.  Re-run renovate

**Expected behavior**
I would expect renovate to close the MR (if it hasn't been closed) and ignore that update.

**Comment by rarkins** [comment]
Doesn’t GitLab automatically close PRs when the associated branch disappears?

**Comment by Jamesking56** [comment]
@rarkins I don't think so no

**Comment by rarkins** [comment]
That's really strange then. A while back they changed behaviour which meant Renovate's own PRs got closed when it needs to delete a branch before pushing again. I don't understand how/why the behaviour would be different in this case. In short though: don't go deleting the branches unless you plan to close the MR too :)

**Comment by Jamesking56** [comment]
@rarkins Yeah I realise that now, the issue I now have is how do I stop it warning me on every run?

**Comment by rarkins** [comment]
@Jamesking56 if the problem is because a MR's branch was deleted and the MR remains open, can you just manually close or delete the MR?

**Comment by Jamesking56** [comment]
@rarkins The MR is closed. I closed the MR and clicked to delete the branch and now this warning always appears.

**Comment by rarkins** [comment]
@Jamesking56 in that case could you update/correct the reproduction steps? What you describe now doesn't match with the steps in the bug report.

**Comment by Jamesking56** [comment]
@rarkins updated

**Comment by Jamesking56** [comment]
Thanks so much @rarkins
