### ISSUE TITLE
Master issue has wrong PR links

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#2615]
**What Renovate type are you using?**
Renovate Docker

**Describe the bug**
When Renovate's master issue links to GitLab MRs, the link is incorrect.

It generates: `https://gitlab.com/<project>/pull/<#>`

When it should be: `https://gitlab.com/<project>/merge_requests/<#>`

**To Reproduce**

1.  Setup a renovate project in GitLab with `:masterIssueApproval` with some outdated dependencies
2.  Run renovate
3.  Open new master issue and tick the dependency to get renovate to open a PR
4.  Run renovate again
5.  See open PR link is now incorrect in GitLab issue.

**Expected behavior**
Link leads to correct PR instead of 404.

**Comment by rarkins** [comment]
Thanks, it's hopefully possible to correct this with a simple search/replace in gitlab's getPrBody() function like we do with Pull Request/Merge Request
