### ISSUE TITLE
Lock file maintenance PR not opened

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#2616]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
We use the `:maintainLockFilesWeekly` preset, however today a lockfile maintenance PR was not opened. I can see the branch has been created, but there was no subsequent PR. 

The branch is here:
https://github.com/neutrinojs/neutrino/compare/renovate/lock-file-maintenance

Our settings here:
https://github.com/neutrinojs/neutrino/blob/573eed247d1fe2e0826c6943b1ff68e7911f9ef7/renovate.json

**Did you see anything helpful in debug logs?**
In this log:
https://renovatebot.com/dashboard#neutrinojs/neutrino/23161322

...I see:

```
DEBUG: createCommit(66fa422cb1daacc2cb7f19c109ffd93cb8500801, 9b871b750f6c2582fdd5a735750db6c8349f57dc, Lock file maintenance)
DEBUG: Found gitPrivateKey
DEBUG: branchExists(renovate/lock-file-maintenance)=true
DEBUG: Updating branch renovate/lock-file-maintenance with commit 851e2c4c4ed9eaa50c4347e0fa20e585263cf108
DEBUG: Branch updated
INFO: Branch updated
DEBUG: Status check is already up-to-date
DEBUG: Checking if we can automerge branch
DEBUG: mergeStatus=no automerge
DEBUG: Ensuring PR
DEBUG: There are 0 errors and 0 warnings
DEBUG: getBranchPr(renovate/lock-file-maintenance)
DEBUG: findPr(renovate/lock-file-maintenance, null, open)
DEBUG: Checking branch combined status
DEBUG: getBranchStatus(renovate/lock-file-maintenance)
DEBUG: branch status check result
{
  "state": "pending",
  "statuses": []
}
DEBUG: Branch status is "pending" - checking timeout
DEBUG: Branch is 0 hours old - skipping PR creation
```

In later logs there is no further reference to that branch. ie: I would have expected an attempt to open the PR once the checks (presumably Travis?) were no longer pending.

**To Reproduce**

This section isn't really relevant for bug reports like these.

**Expected behavior**
For a weekly lockfile PR to be opened.

**Comment by rarkins** [comment]
I think this is probably because Tracis CI deprecated the use of commit status checks and instead now use only the “checks api”. For PRs it doesn’t matter as we get a combined status but for branches we need to now check both status checks and the checks API.

**Comment by Jamesking56** [comment]
It seems like one of your branch status checks was still pending at the time which is why renovate skipped creating the PR.

I'm wondering whether renovate should skip creating the PR, won't the status checks just continue inside the PR if one is created?
