### ISSUE TITLE
Cannot read property match of undefined

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#2619]
**What Renovate type are you using?**
Renovate Docker

**Describe the bug**
Suddenly running renovate again, I'm now getting an obscure javascript error:

```
ERROR: Repository has unknown error (repository=<repo>)
       "err": {
         "message": "Cannot read property 'match' of undefined",
         "stack": "TypeError: Cannot read property 'match' of undefined\n    at processRepo (/usr/src/app/lib/workers/repository/process/index.js:19:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
       }
```

**Did you see anything helpful in debug logs?**
Nope, just this error for every repo.

**To Reproduce**

**NO IDEA** Just randomly started happening.

**Expected behavior**
No errors

**Comment by Jamesking56** [comment]
Line which is failing: https://github.com/renovatebot/renovate/blob/71810d3b5f1fdac1ebb9d0363a4f5e93560962c9/lib/workers/repository/process/index.js#L19

I'm using GitLab CI + GitLab repos, no idea why the issue wouldn't have a body?

**Comment by rarkins** [comment]
There’s probably a problem with the findIssue function in our GitLab lib. I’ll fix this and the MR link tomorrow. From where did you find out about the masterIssue option? It’s actually am unofficial/undocumented feature I’m still testing out before properly releasing.

**Comment by Jamesking56** [comment]
I found it from an issue on here (not sure which one), didn't realise it was unofficial at the moment. For the record, I prefer it to the usual firehose of PRs.

I've submitted what I think is a fix for this issue, ready for you to test + review whenever you are ready (tomorrow is fine).

Loving your work on Renovate so far :+1:
