### ISSUE TITLE
Unable to use GITHUB_COM_TOKEN on Renovate stable

### ISSUE THREAD

**Issue by hbetts** [renovatebot/renovate#2629]
**What Renovate type are you using?**

I am using the `stable` dist-tag of `renovate` internally at  my company.

**Describe the bug**

We configure our environment with `GITHUB_COM_TOKEN`, where we provide the token for a bot account on GitHub.com to enable our Renovate instance to have access to 5000 API calls.

We attempted to upgrade from 13.0.5 to 13.51.11, the latest `stable` version at the time of writing.

During our testing we began receiving 401 authentication errors from GitHub.com requests.

**Did you see anything helpful in debug logs?**

We began debugging `renovate` and saw the following `opts` object passed to `got`:

```javascript
{ json: true,
  token: 'dummy_token',
  endpoint: 'https://api.github.com/',
  name: 'GitHub',
  platform: 'github',
  paginate: true,
  headers:
   { accept: 'application/vnd.github.v3+json',
     'user-agent': 'https://github.com/sindresorhus/gh-got',
     authorization: 'token dummy_token' } }
```

That `opts` object was used for the following URL: `https://api.github.com/repos/nodejs/node/tags?per_page=100`

In the `opts` object the token was set to `dummy_token`. In version 13.0.5 the `token` property is set correctly.

Through additional testing, and looking through Renovate changes since `13.51.11`, I saw, and then applied 805cd837dd4d6085a37824a09e3b4a443e06803b

That commit seems to fix the issue we are encountering.

**To Reproduce**

1. Use the stable version of `renovate`.
2. Set a `GITHUB_COM_TOKEN` environment variable with the token of a bot account on GitHub.com.
3. Console print the contents of the `opts` object passed to `gh-got` package from within the [`gh-got-wrapper` file](https://github.com/renovatebot/renovate/blob/56de9339b52652569dc8e67c22981506138d22ca/lib/platform/github/gh-got-wrapper.js#L11).

**Expected behavior**

Our expectation is that Renovate should be able to make requests to GitHub.com using the token stored in the `GITHUB_COM_TOKEN` environment variable, while using the `stable` version of `renovate`.

**Comment by rarkins** [comment]
@hbetts is this happening when you run Renovate without modification? I searched the stable branch for `dummy_token` and do not receive a hit. IIRC you are using a fork/adaptation of https://github.com/renovatebot/github-app-cli/ ? FYI I have now deprecated and archived that repo as it's not an approach I have the time to maintain. 

Regardless, I cherry picked the commit you mentioned into the stable branch but unfortunately that fails tests on TravisCI so does not publish: https://travis-ci.org/renovatebot/renovate/builds/439460326. Unless this is also happening in the CLI version, I will need to close this as `wontfix`.

FYI I plan to tag the current master as stable sometime within the next 7-10 days.

**Comment by hbetts** [comment]
> is this happening when you run Renovate without modification?

I was/am running Renovate through a wrapper package.

I had quite a difficult time finding where `dummy_token` came from, but it seems to come from our internal copy of `github-app-cli`, which [sets that token when building the configuration object](https://github.com/renovatebot/github-app-cli/blob/509a3da7ef24f496c9659b2cb6714c8ce67f53a0/lib/index.js#L11).

This looks like a bug in the way we're calling Renovate (our code is not aligned with the expectations of the Renovate code). Therefore I'm closing out this issue.
