### ISSUE TITLE
[npm] Support pnpm overrides

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#26320]
### Discussed in https://github.com/renovatebot/renovate/discussions/26249

<div type='discussions-op-text'>

<sup>Originally posted by **viceice** December 12, 2023</sup>
### Tell us more.

`pnpm.overrides`[^1] should be supported.

**`package.json`**
```json
{
  "pnpm": {
    "overrides": {
      "foo": "^1.0.0",
      "quux": "npm:@myorg/quux@^1.0.0",
      "bar@^2.1.0": "3.0.0",
      "qar@1>zoo": "2"
    }
  }
}
```

[^1]: https://pnpm.io/package_json#pnpmoverrides</div>

**Comment by RahulGautamSingh** [comment]
https://github.com/renovatebot/renovate/issues/17298
Duplicate issue?
