### ISSUE TITLE
Flutter and Dart sdks should support ranges

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#26349]
### Discussed in https://github.com/renovatebot/renovate/discussions/26346

<div type='discussions-op-text'>

<sup>Originally posted by **KoheiKanagu** December 18, 2023</sup>
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I have not seen this working

### Describe the problem

I think there is a bug in the implementation that extracts the Flutter and Dart versions from pubspec.lock.

The Flutter and Dart versions are listed as follows.
```lock
sdks:
  dart: ">=3.3.0-174.3.beta <4.0.0"
  flutter: ">=3.18.0-0"
````

but renovate is trying to resolve the version with semver and failing.
So, it fails to update the lock file.

I think the correct versioning is npm.

Repositories that can reproduce the problem: https://github.com/KoheiKanagu/renovate_pub_issue

### Relevant debug logs

<details><summary>Logs</summary>

```

DEBUG: Using containerbase dynamic installs (branch="renovate/dart-3.x")
WARN: Invalid tool constraint (branch="renovate/dart-3.x")
{
  "toolName": "flutter"
  "constraint": ">=3.3.0"
  "versioning": "semver"
}

DEBUG: Resolved stable matching version (branch="renovate/dart-3.x")
{
  "toolName": "flutter"
  "resolvedVersion": "3.16.4"
}

DEBUG: Executing command (branch="renovate/dart-3.x")
{
  "command": "install-tool flutter 3.16.4"
}

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above</div>

**Comment by RahulGautamSingh** [comment]
I think the extraction is fine as confirmed by this test:
https://github.com/renovatebot/renovate/blob/6d8a9fffc3d371e69d21a78e4d298cf817fc1370/lib/modules/manager/pub/utils.spec.ts#L14-L18

I also, tried it with the following string and the tests pass:
```
sdks:
  dart: ">=3.3.0-174.3.beta <4.0.0"
  flutter: ">=3.18.0-0"
```

I tried to reproduce the error using the linked minimal reproduction, after changing the dart version ranges (because I am not familiar with the flutter, dart ecosystem and the runs kept failing due to incorrect dart version errors so I limited the versions):
It seems the range was handled well here: https://github.com/RahulGautamSingh-testing/renovate_pub_issue/pull/16

**Comment by KoheiKanagu** [comment]
The problem seems to be the Dart and Flutter versions of container.
https://github.com/renovatebot/renovate/blob/main/lib/util/exec/containerbase.ts#L189-L198

I don't see a problem with the `parsePubspec` method, as verified by that test.

**Comment by rarkins** [comment]
Change both to npmVersioningId?

**Comment by RahulGautamSingh** [comment]
> Change both to npmVersioningId?

Yes, since we need to handle ranges in both. The decision to use semver was made [here](https://github.com/renovatebot/renovate/pull/19116#issuecomment-1335064883).

> The problem seems to be the Dart and Flutter versions of container.

I tested with `binarySource=global` hence couldn't reproduce the error. 😓

**Comment by RahulGautamSingh** [comment]
The version is resolved when using npm versioning.

Log

```
DEBUG: Setting CONTAINERBASE_CACHE_DIR to .../cache/containerbase (repository=RahulGautamSingh-testing/renovate_pub_issue, branch=renovate/dart-3.x)
DEBUG: Using containerbase dynamic installs (repository=RahulGautamSingh-testing/renovate_pub_issue, branch=renovate/dart-3.x)
DEBUG: Resolved unstable matching version (repository=RahulGautamSingh-testing/renovate_pub_issue, branch=renovate/dart-3.x)
       "toolName": "flutter",
       "constraint": ">=3.18.0-0",
       "resolvedVersion": "3.18.0-0.2.pre"
.........
DEBUG: Setting CONTAINERBASE_CACHE_DIR to .../cache/containerbase (repository=RahulGautamSingh-testing/renovate_pub_issue, branch=renovate/flutter-3.x)
DEBUG: Using containerbase dynamic installs (repository=RahulGautamSingh-testing/renovate_pub_issue, branch=renovate/flutter-3.x)
DEBUG: Resolved unstable matching version (repository=RahulGautamSingh-testing/renovate_pub_issue, branch=renovate/flutter-3.x)
       "toolName": "flutter",
       "constraint": ">=3.18.0-0",
       "resolvedVersion": "3.18.0-0.2.pre"
```

**Comment by RahulGautamSingh** [comment]
While testing I realized that the npm versioning also doesn't work as exepected for some cases.

For eg. 

```
flutter: <2.17.5
```
And the releases are: 
```
           { version: '2.17.0-69.2.beta', isStable: false },
            { version: '2.17.0-7.0.dev', isStable: false },
            { version: '2.17.5', isStable: true },
            { version: '2.17.6', isStable: true },
            { version: '2.17.7', isStable: true },
            { version: '2.18.0', isStable: true },
            { version: '2.18.0-44.1.beta', isStable: false },
```


Then the resloved version is `2.18.0-44.1.beta` (highest version). I was exepcting it to select `2.17.0-7.0.dev`.
Is this expected behaviour @rarkins?

**Comment by RahulGautamSingh** [comment]
Not very likely, since a lower stable version should be available, ie. `2.17.4` most of the time.

**Comment by viceice** [comment]
i think we should use github release as flutter datasource for buildpack
https://github.com/containerbase/flutter-prebuild

so we really get only installable versions

**Comment by viceice** [comment]
`2.17.0-7.0.dev` isn't a valid semver, so npm versioning rejects that

**Comment by RahulGautamSingh** [comment]
> i think we should use github release as flutter datasource for buildpack https://github.com/containerbase/flutter-prebuild
> 
> so we really get only installable versions

I think this should be part of another issue, since this issue focuses on supporting ranges, which concerns the versioning.
