### ISSUE TITLE
rangeStrategy and composer

### ISSUE THREAD

**Issue by evilebottnawi** [renovatebot/renovate#2635]
**What Renovate type are you using?**

Renovate CLI

**Describe the bug**
I am using `rangeStrategy: pin`.
After enable `composer` support renovate don't create PR to pin all deps.

**Did you see anything helpful in debug logs?**

no

**To Reproduce**

1.  Create `composer.json` with `~` (example `"illuminate/config": "~5.7.2"`)
2.  Enable renovate on repo

**Expected behavior**

Renovate should pin deps.

**Screenshots**

don't have

**Additional context**

no

**Comment by rarkins** [comment]
I cannot reproduce this - it worked fine for me using the example: https://github.com/renovate-tests/composerpin1/pull/2

**Comment by evilebottnawi** [comment]
@rarkins strange, doesn't work for me, looks problem on our side, i will investigate into this and create issue if found bug, thanks!

**Comment by evilebottnawi** [comment]
@rarkins seems i found a problem.

Currently behavior of `composer` is different than `npm/yarn` for `require`(`dependencies`) when you use `rangeStrategy: 'auto'`:
- `npm/yarn` pin `dependencies` for `app` type https://github.com/renovatebot/renovate/blob/master/lib/manager/npm/range.js#L31
- `composer` doesn't pin `require` for `app` type https://github.com/renovatebot/renovate/blob/master/lib/manager/composer/range.js

I think this is a mistake. I expect pinning `require` for `app` type as for `npm/yarn`.

**Comment by evilebottnawi** [comment]
I think we can use this field to detect type https://getcomposer.org/doc/04-schema.md#type

**Comment by rarkins** [comment]
Closing in favour of new issue: https://github.com/renovatebot/renovate/issues/2678

**Comment by rarkins** [comment]
That’s fine by me, but we need a way to determine when a project is an app. How can we do that?


________________________________

**Comment by evilebottnawi** [comment]
@rarkins we already create issue about this https://github.com/renovatebot/renovate/issues/2678, i think we can use this field https://getcomposer.org/doc/04-schema.md#type

**Comment by rarkins** [comment]
Thanks. That email response was actually sent hours ago before the other ones.. I agree re: approach
