### ISSUE TITLE
Dashboard project list is limited

### ISSUE THREAD

**Issue by ahmadnassri** [renovatebot/renovate#2644]
**What Renovate type are you using?**
Dashboard

**Describe the bug**
Dashboard is not showing full list of projects if the list is too long.

**Did you see anything helpful in debug logs?**
seems like it's not paginating across all results.

*To Reproduce**

1.  using an GitHub Org with hundreds of repositories
2.  view dashboard
3.  only a subset of repos are shown

**Expected behavior**

should be able to see all projects, or at least paginate the list

**Comment by rarkins** [comment]
Duplicate of #2605

**Comment by ahmadnassri** [comment]
thank you!
