### ISSUE TITLE
Support for “arbitrary” code modifications

### ISSUE THREAD

**Issue by mxey** [renovatebot/renovate#2646]
**What would you like Renovate to be able to do?**

The Renovate workflow with PRs/MRs, automerge, etc. works great for dependency updates. This might be a stretch, but it would be cool to reuse that for other code changes that have to be applied to various repositories.

One example for me would be modifications to Gitlab CI pipelines. So it could be tied to updating the Docker image in the `.gitlab-ci.yml`

**Describe the solution you'd like**

Hard to pin down obviously. I imagine there'd have to be some way to describe what changes to make, maybe what tools to run on which kinds of repositories. 

**Describe alternatives you've considered**

* The closest to my knowledge is [modulesync](https://github.com/voxpupuli/modulesync). It however is a separate tool, it requires a configured list of repositories and AFAICT does not support Gitlab MRs or Renovate's automerge.

**Additional context**

Similar to #1678

**Comment by rarkins** [comment]
I see Renovate progressing to allow increasingly flexible modifications/updates and for self-hosted making it pretty much completely flexible/open if the admin wishes.

For any feature like this though I think it's important we at least have 1-2 specific use cases to aim for.

**Comment by mxey** [comment]
OK, my specific example is that we use a Jsonnet template to generate all parts of a Gitlab pipeline that builds an image and deploys it to Kubernetes. That includes configuration for Gitlab CI, Skaffold and Kustomize. 

Now we'd like to extend that pipeline to support review apps (deployment of feature branches), for example. I'd configure Renovate to run a given command (like evaluating the Jsonnet template again) on all repositories that fulfill a set of conditions (like: all these files exists and have content matching a pattern). 

That command would probably have to be provided in a Docker image. (Since Renovate runs as a container on Kubernetes here as well, starting other Docker images is a security problem, although unprivileged Docker-in-Docker is slowly coming. For such a one-off change, I would be fine with running Renovate manually though, I just don't want to touch all the repositories manually)

**Comment by rarkins** [comment]
The approach to this will definitely be using Docker, but I still haven't decided for sure which way to implement that. 

In general I would prefer that all "spawned" commands are run inside Docker containers although I'll probably always retain the option of letting self-hosted users use global commands if it's not too difficult.

Currently this type of thing (spawning commands inside containers) can be done by mapping the Docker socket into Renovate's container to allow it to start sibling containers.

Docker-in-Docker seemed to be out of favour for a long time but I read https://applatix.com/case-docker-docker-kubernetes-part-2/ recently and was interested by it.

**Comment by mxey** [comment]
> Docker-in-Docker seemed to be out of favour for a long time but I read https://applatix.com/case-docker-docker-kubernetes-part-2/ recently and was interested by it.

Yes, it's possible, but you either have to expose the host Docker daemon, which equals root access, or you have to make the pod privileged, which also equals root access ;)

**Comment by rarkins** [comment]
So if you make the Renovate container privileged then it has the ability to spawn unprivileged containers (either via run or dind) and protect *itself* from malicious code in repositories. But then you cannot protect yourself from the main Renovate code, looking at it from a k8s admin point of view.

If you make Renovate unprivileged then it must run everything inside its own container and therefore could be compromised by malicious repository users running arbitrary code.

**Comment by mxey** [comment]
Ideally, Renovate could create Kubernetes pods or jobs to run those containers, but that would be a lot more involved.

**Comment by mxey** [comment]
> Is it a common use case for a Kubernetes pod to have privileges to create other pods?

It's not that common for “applications”, but there are lots of additional controllers/operators that run as pods and also create pods or other things of their own. Every pod is passed an API token for the Kubernetes API, so it's just a matter of setting permissions to create pods (or jobs).

The closest to Renovate might be the [Kubernetes executor of Gitlab runner.](https://docs.gitlab.com/runner/executors/kubernetes.html)

**Comment by rarkins** [comment]
Thanks for the pointer to the GitLab runner - looks similar.

Marking this as "blocked" as it would require #2431 first at the minimum

**Comment by pcwinters** [comment]
Another tool that I'd like to be able to use with renovate is [Mrm](https://github.com/sapegin/mrm).

> Command line tool to help you keep configuration (package.json, .gitignore, .eslintrc, etc.) of your open source projects in sync.

If we were able to run arbitrary scripts with Renovate, we'd schedule and automate updates to boilerplate and configuration files that would help keep our package's consistent. Mrm overlaps with Renovate a bit here, because it's capable of upgrading packages as a part of its project codemods. For that reason, I don't think it necessarily fits as a ["post upgrade task #838"](https://github.com/renovatebot/renovate/issues/838) nor as ["hooks #2992"](https://github.com/renovatebot/renovate/issues/2992).

I think that Mrm could align more closely with renovate if Mrm kept track of the last run version/release of a Mrm task. In that way, Renovate could compare the latest release of a Mrm task or preset with what has been "applied" in a project. Then, a renovate-mrm engine could treat outdated tasks as outdated dependencies.

Could Renovate support community developed engines/managers to achieve this goal?

**Comment by rarkins** [comment]
@pcwinters I probably don’t “get” Mrm 100% yet but I think what you suggest would align with Renovate. Would you keep your baseline Mrm config in a repo or npm package and “depend” on it in your other projects?

**Comment by rarkins** [comment]
@pcwinters because if you had a repo that contains your shared Mrm config and put that in `devDependencies` of each repo then that would be one way to run it as a post-upgrade task whenever you bump the Mrm config repo's version.

**Comment by pcwinters** [comment]
@rarkins I think that could work. A "post upgrade task" might be a great place to start and would likely be enough for our needs.

In fact, npm packages could make use of npm's `postinstall` script right now (https://docs.npmjs.com/misc/scripts). Of course, this would cause Mrm to run everytime a developer did an `npm install` in a development environment. Thankfully, Mrm tasks are intended to be idempotent!

**Comment by awgeorge** [comment]
Similarly, I would like to copy the `.github/.gitlab` folder from a template repo to all other repos and think that it sounds similar to the above.

**Comment by rarkins** [comment]
@awgeorge are you talking about keeping repositories in sync with the template repo?

If so then this is a good idea, but it will be implemented as a new "manager".

**Comment by awgeorge** [comment]
Indeed. Yes, I was thinking maybe a new `git` or `repo` manager that would be created. The manager would need to pull the template repo, and the target repo, then based on some configuration in the target repo, ie. which files/folders to copy open an MR if its detected these files have changed. What do you think?

**Comment by rarkins** [comment]
This is possible for self-hosted today. See https://docs.renovatebot.com/self-hosted-configuration/#allowedpostupgradecommands and https://docs.renovatebot.com/configuration-options/#postupgradetasks
