### ISSUE TITLE
Getting lock file errors due to machine running out of space? (npm, package-lock)

### ISSUE THREAD

**Issue by vicrep** [renovatebot/renovate#2647]
**What Renovate type are you using?**
Renovate GH App

**Describe the bug**
Basically, our renovate jobs for one of our projects are consistently failing with a `lock file error`, and consequentially, the bot isn't creating / updating PRs anymore. Note that since onboarding, we have had the bot run successfully 4 times, and unsuccessfully (with this error) > 20 times.

**Did you see anything helpful in debug logs?**

Looking at logs, this fails at the `npm install` step which updates the project's lockfile
```
DEBUG: Using npm: node /usr/src/node_modules/npm/bin/npm-cli.js --version && node /usr/src/node_modules/npm/bin/npm-cli.js install --ignore-scripts --no-audit
INFO: lock file error
```
and this seems to be caused by the job VM running out of space:
```json
{
  "cmd": "node /usr/src/node_modules/npm/bin/npm-cli.js --version && node /usr/src/node_modules/npm/bin/npm-cli.js install --ignore-scripts --no-audit",
  "err": {
    "name": "ChildProcessError",
    "childProcess": {},
    "stdout": "6.4.1\n",
    "stderr": "npm WARN tar ENOSPC: no space left on device, open '/mnt/renovate/gh/[org]/[project]/node_modules/.staging/material-design-icons-dc78a50b/action/drawable-xxxhdpi/ic_bookmark_black_24dp.png'\n [...]"
  }
} 
```

Truncated for size, but this goes on for a lot of other deps.

**To Reproduce**

N/A

**Expected behavior**

**Screenshots**
w/ job IDs if useful:
<img width="995" alt="screen shot 2018-10-12 at 11 31 57 am" src="https://user-images.githubusercontent.com/11432241/46878883-7dcb2a80-ce12-11e8-8124-002667bc95df.png">

**Additional context**

**Comment by rarkins** [comment]
Is this a Lerna repo?

**Comment by vicrep** [comment]
@rarkins nope, it's a standard npm project (actually, the repo has two package.json files, but those aren't linked)

**Comment by rarkins** [comment]
How large is the project for you locally once you install all node modules?

**Comment by vicrep** [comment]
@rarkins My node_modules is 1.5GB on darwin.

Thanks for investigating -- there is indeed a linked package, but that's just for bundling purposes, as that project `packages/cp-react` itself doesn't contain any deps in its package.json. This makes me think that we're explicitly hitting the bug you mentioned.

Is there anything I can do on my end to fix this? Would a way for me to explicitly enable skipInstall on renovate jobs?

**Comment by rarkins** [comment]
For future record, job 23846437 shows error `npm WARN tar ENOENT: no such file or directory, lstat '/mnt/renovate/gh/dialoguemd/care-platform/node_modules/.staging/material-design-icons-dc78a50b/action/ios/ic_assignment_turned_in.imageset'` while job  shows error `npm WARN tar ENOSPC: no space left on device, open '/mnt/renovate/gh/dialoguemd/care-platform/node_modules/.staging/material-design-icons-dc78a50b/social/1x_web/ic_whatshot_white_18dp.png'`

**Comment by vicrep** [comment]
@rarkins fwiw, I can't repro locally when running same command as renovate ```npm i --ignore-scripts --no-audit``` on a clean project clone, which leads me to believe that the `ENOENT` error might be a side effect of the buffer running out of space?

**Comment by rarkins** [comment]
It's good to know that the other package has no dependencies, because in that case it hopefully shouldn't hit the transitive local dependencies bug and a full `npm install` is not necessary.

Right now `skipInstalls` defaults to true and is "flipped" to false when file: links are found, and there's no way to flip it back. I'm thinking whether I can default it to `null` instead to enable you to force it to `true` by config, in which case we could detect that and *not* set to false.

**Comment by rarkins** [comment]
@vicrep 	anything is possible, but I have doubts that the buffer problem *causes* the ENOENT problem.  Normally the buffer is not very big when everything goes right, and as soon as we hit one of those .staging errors then the entire install is hosed. I'm surprised that npm continues on so long with errors over and over.

Anyway, it seems like the best thing to try is skipping the full install, so I'll work on that first.

**Comment by vicrep** [comment]
@rarkins that's great to hear, thanks for the quick turnaround! Let me know if/when I can try out the full install skip 👍

**Comment by rarkins** [comment]
@vicrep I will test it out within the next hour and report back. I can add the skipInstalls=true setting manually on the server-side for testing so that you don't need to alter your config in the repo.

**Comment by vicrep** [comment]
@rarkins That'd be even better :) thanks!

**Comment by rarkins** [comment]
@vicrep it ran just now and successfully created two PRs using `--package-lock-only` and I think also rebased a third. The rest are rate limited due to the maximum 2 new PRs per hour but will be raised at a rate of two per hour, hopefully successfully.

The log shows 34 hits for "Reached PR creation limit - skipping branch creation" so you might want to increase the value of `prHourlyLimit` if you don't want to wait 17 hours and your CI can handle more than 2 per hour.

To wrap up, could you add `"skipInstalls": true` to your `renovate.json` so that it's official and close this issue once you're confident the problem is solved?

**Comment by vicrep** [comment]
Yep, I just saw that the PRs started being processed again, can confirm it seems to be fixed! 

re: PR limit, I'm aware of it, but thanks for heads up.

I'll close the issue once I push those renovate.json changes. Thank you again for the quick turnaround on this fix! 👍 👍

**Comment by rarkins** [comment]
You're welcome, and thanks for your help troubleshooting it

**Comment by vicrep** [comment]
Confirmed to have been fixed on our end, closing! 🎉
