### ISSUE TITLE
GitLab authentication token not implicitly passed to Composer

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#2660]
**What Renovate type are you using?**
Renovate Docker + GitLab CI

**Describe the bug**
When a project contains a private composer package under a private GitLab repository, `composer` fails with error message `Could not authenticate against gitlab.com` because Renovate doesn't share the auth token with `composer`

**Did you see anything helpful in debug logs?**
```
Installing my/package (v5.0.3): Downloading    Failed to download my/package from dist: Could not authenticate against gitlab.com
```

**To Reproduce**

1.  Create a satis repository hosting a `composer` package from a private GitLab repository
2.  Configure Renovate with the satis basic auth credentials and a GitLab token.
3.  Create a project for Renovate to work on which asks for the private package from the satis repository
4.  Run renovate to update the package, see the authentication failure

**Expected behavior**
Package to be upgraded successfully.

**Additional context**
The fix for this, is to ensure that the token given in `--token` on CLI is also saved in `composer`. It seems this may only be done for GitHub, it needs to also be done for GitLab.

**Comment by rarkins** [comment]
I don't believe this is caused by or requires satis/auth specifically. It just needs a private source repository on gitlab.com referenced from any packagist source. The solution hopefully just needs a short piece of logic for gitlab.com right after the existing github.com one.

**Comment by Jamesking56** [comment]
Yeah I don't believe Satis is involved, just thought I'd give you the way I discovered the issue.
