### ISSUE TITLE
Refactor: run go get in temporary folder

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2662]
"go get" is very fast if there's must a `go.mod` but can be very slow if the source code is present, because Go seems to crawl through the entire source tree looking for missing modules. It is not Renovate's job to add missing modules in a PR that's updating a module version, and in fact that is probably undesirable. To prevent this, run `go get` in an ephemeral directory when using gitFs.

**Comment by paultyng** [comment]
An alternative to speed up your go executions is to setup a proxy similar to [Athens](https://github.com/gomods/athens) and cache these modules a lot closer to your servers.

**Comment by rarkins** [comment]
Thanks, that sounds like a good option too

**Comment by rarkins** [comment]
- create temporary directory
- copy over all go.mod/go.sum in right subdirectories (maybe via a clever find/grep/xargs/cp shell command)
- run `go get` on the temporary directory rather than the full repo

Also this should be opt-in. In a way this is similar to [skipInstalls](https://github.com/renovatebot/renovate/blob/d78e6a048627910cef4df4fde2f54b7bf142f331/lib/config/definitions.js#L268-L275) in npm
