### ISSUE TITLE
renovate dont create PR for update with specific version format

### ISSUE THREAD

**Issue by aldarund** [renovatebot/renovate#2666]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
https://www.npmjs.com/package/nuxt-edge
When version is set 2.2.0-25662130.e115890 renovate wont create PR to update it to 2.3.0-25663589.d13d0ff
Same goes when it changes from 2.1.0-xxxx to 2.2.0-xxx
Within 2.2.0-xxx update created

**To Reproduce**
create package.json with nux-edge version 2.2.0-25662130.e115890
run renovate

**Expected behavior**
a new pr with 2.3.0-25663589.d13d0ff version

**Comment by rarkins** [comment]
Any semver version with a hyphen after major.minor.patch is considered unstable/prerelease, and Renovate does not jump unstable versions by default. You should configure a package rule matching this dependency and setting ignoreUnstable=false for it.

**Comment by aldarund** [comment]
@rarkins but isnt it on unstable already?  E.g. its on 2.2.0-25662130.e115890 which is unstable. Why wont it jump to 2.3 which is unstable too? From docs
``By default, Renovate won't update any packages to unstable versions (e.g. 4.0.0-rc3) unless the package version was already unstable```

**Comment by rarkins** [comment]
Sorry, I need to update the docs. Renovate only automatically updates to an unstable version with same major.minor.patch. For “permanent” unstable behaviour you need the config option set.
