### ISSUE TITLE
different commit message scope in monorepo

### ISSUE THREAD

**Issue by alan-agius4** [renovatebot/renovate#2669]
I'd like to use renovate in a mono repo, however I want my conventional commits to scoped with the package name.

Example in the folder structure;
```
package.json
-- modules
---- foo
------ package.json
----bar
------ package.json
```

I'd want that commits to be something like: `chore(foo): update mydeps` and `chore(bar): update mydeps`.

Is this something which is supported at the moment?

**Comment by rarkins** [comment]
What if a PR contains updates to both packages? Ie foo and bar

**Comment by rarkins** [comment]
It’s not possible right now because we don’t have a variable exposed for the parent directory. If exposed then your simple use case could be done simply. 

My main concern is the “edge” cases like: 
- updates in the root dir
- updates containing more than one module dir

**Comment by alan-agius4** [comment]
I see, yeah having 2 package.json updated with the same commit would cause a big issue.

**Comment by rarkins** [comment]
I assume you want to have both package json files updated in the same PR though? Ie to avoid having duplicate versions of the same dependency within the monorepo. 

Also I realised that you could actually configure this manually right now with packageRules if the number of modules is not too high.

**Comment by alan-agius4** [comment]
Yes, I'd expected that both package.json files updated are in the same PR.

Is there a doc to illustrates how to do this using `packageRules` as I though that `packageRules` effected dependencies

**Comment by rarkins** [comment]
I’m on mobile right now so a little hard to extract all the links, but go to https://renovatebot.com/configuration-options/ and then the packageRules section. You can use the “paths” option and define one rule per module to then set the commitScope value based on a path match. If there are multiple updates in a single PR then the commitScope will be based on whichever update happens to be first in the list.

**Comment by alan-agius4** [comment]
Thanks

**Comment by Hartorn** [comment]
@rarkins I'm also interested in this feature, especially useful when using https://www.npmjs.com/package/@commitlint/config-lerna-scopes

I'm wondering, maybe it would be possible to create variable from capturing group inside a regex ?
Not sure if I could contribute, but I can try to give a hand if needed (on this, or something else)

**Comment by rarkins** [comment]
@Hartorn can you give an example or two of what you'd like to achieve? e.g. what it looks like today, and what you'd like it to look like tomorrow, and what variables/data you'd need exposed to achieve it?

**Comment by Hartorn** [comment]
@rarkins This is an example : 
https://github.com/thc-tools/webpack-laboratory/pull/63
Pull request is being rejected, because scope is not good.

So I could make the fix as you described (making as many rules as I have packages), but I thought it would be good to be able to do something like this
```
  "packageRules": [{
    "packagePatterns": ["^packages/quarks/\(.*\)$", "^packages/atoms/\(.*\)$", "^\(webpack-chemistry\)$"],
    "semanticCommitScope": "$1"
  }]
```
I meant the parenthesis as matching group, not as literals

**Comment by Hartorn** [comment]
@rarkins I did what you say, using packageRules, and it's working well.
There is one thing I did not manage todo, that is to make the root package.json being with no scope and match it with `paths`

I tried by not matching `packages`, but maybe I did not do it well.
```
        {
            "paths": ["^[packages]"],
            "semanticCommitScope": null
        },
```
How can I match only root package.json ? with `^package.json$` ? (not sure about what glob allows and does not allow)

**Comment by rarkins** [comment]
I think an exact string might match, ie just “package.json” without any special chars

**Comment by Hartorn** [comment]
I managed it by putting in `branchPrefix` and `semanticCommitScope` root config for renovate then again for every package in `packageRules`.
So, `branchPrefix` and `semanticCommitScope` in root config are used only for root package.json

**Comment by rarkins** [comment]
Here's what we need to do to close this issue:

Somewhere in the branch worker, once we have all updates, we should add `parentDir` and `baseDir` fields to each update. Examples:

packageFile: `package.json`:
- parentDir: `""`
- baseDir: `""`

packageFile: `packages/foo/package.json`:
- parentDir: `foo`
- baseDir: `packages/foo`
