### ISSUE TITLE
Support advanced Yarn resolutions syntax

### ISSUE THREAD

**Issue by rmoedt** [renovatebot/renovate#2670]
**What would you like Renovate to be able to do?**

We ran into an issue with Typescript project that uses React. As a dev dependency we have added '"@types/react": "16.4.18"'. To fix issues where sub depedencies are using a different version of '@types/react' we have added a resolutions section to our package.json
```
"resolutions": {
    "**/@types/react": "16.4.18",
  },
```

Where there is a new version of '@types/react'  Renovate creates a PR to update the version in the devDependencies, but it doesn't update the version number in the resolutions section.

**Describe the solution you'd like**
Renovate creates a PR where it updates both the version number in the (dev)Dependency section as wel as in the resolutions.

**Comment by rarkins** [comment]
We already have some functionality for keeping resolutions in sync, but it isn't aware of that `**/@types/react` syntax. What's the difference between that and just `@types/react` ?

Also, is this a Yarn Workspaces project?

**Comment by rarkins** [comment]
I found the original RFC for this feature in Yarn: https://github.com/victornoel/rfcs/blob/bc3e5180211268a92c675c9c7460a714438d999d/accepted/0000-selective-versions-resolutions.md

Here is a example with similar glob syntax:

---

With:
```json
  "dependencies": {
    "package-a": "1.0.0",
    "package-c": "1.0.0"
  },
  "resolutions": {
    "**/package-a": "3.0.0"
  }
```

`package-a` will still be resolved to `1.0.0`, but `package-c` will have
`package-a@3.0.0` in its own `node_modules`.

---

Also this is important:

---

## Retro compatibility for the `resolutions` field

Until now, the`resolutions` field can contain *resolutions* of the following
form (filled by `add --flat` or `install --flat`):
```json
  "resolutions": {
    "package-a": "1.0.0"
  }
```

With the current proposal, the package designation `package-a` is an alias for
`**/package-a`: this means the behaviour of yarn with a project whose
`resolutions` field contains *resolutions* filed by a pre-RFC yarn will be
as expected: the nested dependencies will have the fixed version specified.

---

It seems like Renovate's current support is for the retro/alias so we don't need any change in logic but instead just a change in syntax support.

**Comment by rarkins** [comment]
@rmoedt I *think* this means that if you update your resolutions syntax to use the "retro" syntax then Renovate should work as you expect right away. Otherwise it requires this issue to be resolved first.

I believe this would work the same way for you:

```
"resolutions": {
    "@types/react": "16.4.18"
  },
```

**Comment by rmoedt** [comment]
NIce work!
