### ISSUE TITLE
Recent Renovate runs failing with "platform-failure"

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#2675]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The weekly lockfile maintenance PR was not opened for several repositories, eg:
https://github.com/mozilla/treeherder
https://github.com/neutrinojs/neutrino

**Did you see anything helpful in debug logs?**
The dashboard says "platform-failure", starting about 9-10 hours ago.

Trying to view the logs for any of those entries results in the log viewer getting stuck with the three loading dots animation, and the developer console shows `uncaught exception: Unauthorized`.

**To Reproduce**
Use Renovate on the repos above.

**Expected behavior**
* Recent jobs succeeding in Renovate dashboard
* Able to view logs when "platform-failure"s do occur
* No uncaught exceptions in developer console when viewing dashboard/logs

**Screenshots**

![screenshot_2018-10-22 renovate mozilla treeherder](https://user-images.githubusercontent.com/501702/47284826-ab695e00-d5e0-11e8-8ad0-3d7eca7669fa.png)

**Comment by rarkins** [comment]
https://status.github.com/messages

**Comment by rarkins** [comment]
Also I won’t be bringing Renovate back online until I’m sure GitHub are on top of things and right now they appear to be the opposite of on top of anything.. whatever that term is!

**Comment by edmorley** [comment]
Ah yes makes sense! (I'd been lucky enough to not hit any GitHub issues this morning so had not realised there was an incident - though in the last hour am struggling to load issues/PRs)

**Comment by rarkins** [comment]
Although the web ui seems to be mostly OK by now, the API backend is still a mess and is hitting Renovate with 403s when we just attempt to fetch tokens, not even start processing any repo. I have emailed their partner engineering but who knows how long it could take.

**Comment by edmorley** [comment]
Resolved :-)
