### ISSUE TITLE
Add rangeStrategy=auto setting for pip_requirement manager

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2680]
From @nottrobin in https://github.com/canonical-websites/docs.snapcraft.io/pull/57#issuecomment-431828458:

> Yes I would say you can distinguish libraries and packages from end-of-chain projects because the libraries and packages will be published to PyPI and therefore have a setup.py - see a guide on Python packaging, or an example of one of our packages.
>
> In that case the dependencies will be specified inside the setup.py rather than in requirements.txt. Some people still use requirements.txt for extra dependencies needed for developing on the library itself etc. (e.g. see canonical-ols/talisker).
>
> If a project has a requirements.txt and no setup.py I would suggest you can assume it's not a package or library. This may not always be true, but by and large should be. If a project has a setup.py, you can be sure the dependencies inside the setup.py are the actual library dependencies. If it also has a requirements.txt, I would suggest it would be reasonable to treat those as development dependencies, although maybe that's a little bit more presumptuous.
>
> I think that means the following could be reasonable behaviour:
>
> - Pin dependencies in requirements.txt (replacing unlocked or range-bases dependencies) similar to how you might in package.json for non-libraries
> - File PRs to bump dependency versions in both requirements.txt and setup.py
> - Leave any range modifiers (>, <) in setup.py alone (more info on version syntax)
> I'm not sure what you should do with unbound dependencies in setup.py - but I guess you should do whatever you do for unbound dependencies in package.json for libraries

In short: add `getRangeStrategy()` for pip_requirements that returns "pin" for all.

**Comment by nottrobin** [comment]
@rarkins just a quick q - does Renovate support the [Pipfile](https://github.com/pypa/pipfile) format? This is likely going to slowly replace `requirements.txt`.

**Comment by rarkins** [comment]
@nottrobin yes it’s alrwady supported but classified as beta for now so not automatically enabled - you need to opt in. As I’m not using it myself day to day I’m waiting for someone to let me make me it’s ready for default enablement.

**Comment by nottrobin** [comment]
Thanks for the update. Yeah we don't use it yet, so I'm not pushing for it to be default. It still states "Nothing is set in stone at this point in time" in its README, and there's also the question, it seems, of whether [https://github.com/sdispater/poetry](poetry) might become [a challenger](https://frostming.com/2018/05-15/pipenv-vs-poetry).

**Comment by rarkins** [comment]
Out of all the packet managers I've looked at, `pipenv` would probably be the shakiest in terms of long term adoption. It has some serious inconveniences (some might say flaws) that seem to be getting shut down in discussion (e.g. issues "locked" from commenting) so I'm also wondering if poetry will become ascendant.
