### ISSUE TITLE
Create pattern matching doc page

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#26817]
### Describe the proposed change(s).

Create a page - maybe a subsection of an existing page if applicable - which documents how pattern matching works in Renovate, i.e. regex and glob. Important for us to note which fields use which type of pattern matching - and potentially link back from those fields to this page too.

Ideally we want most fields to migrate to the "glob or regex" approach we have.

**Comment by HonkingGoose** [comment]
Here are some pages from our docs that seem relevant:

- [Custom Manager Support using Regex](https://docs.renovatebot.com/modules/manager/regex/)
- [`fileMatch` config option](https://docs.renovatebot.com/configuration-options/#filematch).
- [`packageRules` mentions patterns](https://docs.renovatebot.com/configuration-options/#packagerules)
- And we have a bunch of `matchX` type config options that may also have relevant information

I suppose a separate page dedicated to Renovate's pattern matching is probably best, and then link to that page from the appropriate config options sections?

**Comment by HonkingGoose** [comment]
This PR seems related, or may even close this issue:

- #27387

I'll let you review if we need to do more. :wink:
