### ISSUE TITLE
Dashboard is loading forever

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#2687]
If I select a repo in the dashboard, it loads forever.

Console errors:
![image](https://user-images.githubusercontent.com/10532611/47464298-a6054280-d79d-11e8-9324-032a64d0b0b7.png)

**Comment by rarkins** [comment]
This is now resolved, sorry for the inconvenience. Cloudfront had a problem reaching the backend API and those error messages were the result.

**Comment by ajafff** [comment]
Seems like this is happening again. Hopefully it will fix itself.

**Comment by rarkins** [comment]
@ajafff sorry, please try again now. I restarted the API server and verified it's working although there's the possibility Cloudfront will cache results but should be for no longer than 5 minutes.
