### ISSUE TITLE
Support PR commands

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2691]
**What would you like Renovate to be able to do?**

Support inline “commands” in PR comments

**Describe the solution you'd like**

An authorised repository collaborator can comment “!renovate rebase” or “!renovate merge” and have Renovate do it. Commands from non authorised users need to be ignored. 

**Describe alternatives you've considered**

Labels and PR title modifications, because both can only be done by collaborators. 

**Additional context**

We don’t want to rebase forever so we need to know when the rebase command has been implemented. Either:

- delete the comment after rebase, or
- add a Renovate comment after, or
- compare comment time to last commit time

Meanwhile merging should be retried forever, including after rebases.

I am proposing “!renovate” instead of @renovate-bot or @renovate[bot] or @renovate because we can’t be sure that user exists on every platform/instance and getting user notifications would be useless anyway.

**Comment by rarkins** [comment]
Check permissions: 
https://developer.github.com/v3/repos/collaborators/

**Comment by donkkc0924** [comment]
It can be repaired directly by maintenance (no need to pay attention to any situation)
Go straight to rest after repairing
R&F

PR to PR to $
No opinion

Unstaged Changes

Collaborators take cake Renovate to Renovate (don't care about anything)
Go home and rest directly after repair
R&F

PR to PR to $

Just work with Renovate

Rebase(null) and then a Renovate annotation find the time that belongs to him, or
Compare comment time and last submission time
At the same time, the merger should be retried forever, including after the reorganization.

Recommend using "!renovate" esay to anywery.

**Comment by rarkins** [comment]
For rebase, I think:
- check the user has write access to the repo
- delete the comment regardless, so we don’t check unauthorised rebases every time. Log if unauthorised

So we need a way for the platform to either tell us every authorised user for the repo, or to tell us per-user.

**Comment by donkkc0924** [comment]
Make a request and take it to repair as soon as possible
Please approve

**Comment by rarkins** [comment]
If the user requests a rebase, and then the bot comments to say it's done or it's rejected, then it adds noise. Question is whether that's good noise or not?

I also just realised that this feature could add a minimum 1 extra API query per-open PR, which actually can be quite significant. We can *maybe* optimise that using GraphQL though.

**Comment by rarkins** [comment]
I wonder though if those can be “extended” by third parties? GitLab doesn’t really have the concept of apps as first party actors so I doubt it. I guess though using `/renovate x` as syntax is consistent. However they appear to then delete the text once done and I’m nit sure yet if that is best for Renovate or keeping history is preferred.

**Comment by hutson** [comment]
@rarkins GitLab does not currently support custom quick actions.

However, you may be interested in the following issue - https://gitlab.com/gitlab-org/gitlab-ce/issues/54363

**Comment by rarkins** [comment]
There are now multiple convenient ways to rebase on demand:
- Rename PR with title prefix "rebase!"
- Add label "rebase" to the PR
- Check the rebase checkbox within the PR's body

So this then leaves just merging by command, which is also being discussed in #1355
