### ISSUE TITLE
[composer] update packages with same vendor in one PR/MR

### ISSUE THREAD

**Issue by evilebottnawi** [renovatebot/renovate#2695]
**What would you like Renovate to be able to do?**

Create one PR/MR with same vendor package.

I have this dependencies:
```
"require": {
    "php": "^7.1",
    "illuminate/config": "5.7.9",
    "illuminate/container": "5.7.9",
    "illuminate/contracts": "5.7.9",
    "illuminate/filesystem": "5.7.9",
    "illuminate/support": "5.7.9",
  }
```

Right now `renovate` create new PR on each `illuminate` package when they updated (when `5.7.10` released) and we have `5` `PR`/`MR`, when i merge first other `PR`/`MR` require rebase (due conflict in `composer.lock`). This greatly increases load on CI servers and it is inconvenient. Not sure it is possible, but implement this will be great.

For `npm/yarn` we use same logic for `scoped` packages.

**Describe the solution you'd like**

Update in one `PR`/`MR` same vendor packages.

**Describe alternatives you've considered**

Nothing.

**Additional context**

No.

**Comment by rarkins** [comment]
I think we shouldn’t always group together packages based on the scope, right? Ie this should only be for *certain* authors?

**Comment by evilebottnawi** [comment]
@rarkins Hm, in theory we have packages what should grouped in `require` (example https://github.com/illuminate/config/blob/master/composer.json#L16). 

Maybe our logic should be:
1. We have updated `illuminate/config` (i.e. `5.7.10`).
2. Looks in `require` and check `illuminate/contracts` and `illuminate/support` has updated (maybe we should implement some delay (5-15 minutes) because not all packages updated at the same time.).
3. If yes repeat `2` step for `illuminate/contracts` and `illuminate/support`, because they also can contain other updated package.
4. If we have update `illuminate/filesystem` (i.e. `5.7.10`) we merge their `require` (intersection, i.e. `illuminate/filesystem` have `illuminate/contracts` and `illuminate/support` in `require`) and if we find intersection we include this package in one `PR`/`MR` too.

Just idea.

**Comment by rarkins** [comment]
In npm, none of this is automatic - it’s done using package rules. And you could therefore achieve the same today for illuminate with a package rule. Is there any difference you recommend for composer vs npm?

I assume we can’t *always* group all packages from the same scope together as sometimes they’d be unrelated, so we need to do it using static rules. 

The next question is: are there any groupings such as this that you think all composer users would benefit from?

**Comment by evilebottnawi** [comment]
@rarkins honestly I do not know. 

Same problem for `symfony` packages (example https://github.com/laravel/framework/blob/5.7/composer.json), they should be updated in group too otherwise it is created a lot of `PR`/`MR`. Maybe you have ideas how we can solve this too?

**Comment by rarkins** [comment]
Yep I will solve it the same way, starting with illuminate and symfony. Any others you can think of?

**Comment by evilebottnawi** [comment]
Looks it is all right now :smile:
