### ISSUE TITLE
PackageRules: add DepNamePrefix matcher

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#27048]
We currently have an [PackageNamePrefix matcher](https://github.com/renovatebot/renovate/blob/a9c37258d3eb34dd842e6b1665115f889ac5ac50/lib/util/package-rules/package-prefixes.ts), but we currently do not have equivalent for `depName`s.

Other matchers for `depName`:
- [dep-names](https://github.com/renovatebot/renovate/blob/main/lib/util/package-rules/dep-names.ts)
- [dep-patterns](https://github.com/renovatebot/renovate/blob/main/lib/util/package-rules/dep-patterns.ts)

**Comment by yinm** [comment]
Can I try it?

**Comment by secustor** [comment]
Sure thing!
