### ISSUE TITLE
Support Maven

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2706]
Placeholder issue for Maven support. Gradle has been implemented already in #2610. Please +1 this issue to show your support or better yet please comment below giving specifics about your use case.

**Comment by drallgood** [comment]
We got a fairly complex set of maven projects with various technologies ranging from OS tools like the spring suite to homegrown frameworks.
Renovate would help us keep those dependencies at bay.

**Comment by ChristianMurphy** [comment]
@rarkins if you're looking for reference maven repos.
[Apereo (formerly Jasig)](https://www.apereo.org) has a number of open source maven repos with varying levels of complexity.

https://github.com/apereo/java-cas-client
https://github.com/Jasig/WeatherPortlet
https://github.com/Jasig/CoursesPortlet
https://github.com/Jasig/MapPortlet
https://github.com/Jasig/EsupTwitter
https://github.com/Jasig/SurveyPortlet
https://github.com/Jasig/SimpleContentPortlet

**Comment by rarkins** [comment]
FYI, Maven support is progressing rapidly and should be completed this month

**Comment by drallgood** [comment]
Yay. Can't wait!

**Comment by rarkins** [comment]
Does everyone agree that the "depName" should be the concatenation of `groupId` and `artifactId`?

e.g. `<dependency> <groupId>org.springframework.integration</groupId> <artifactId>spring-integration-aws</artifactId> <version>1.2.3</version> </dependency>` would be considered depName=`org.springframework.integration:spring-integration-aws`?

**Comment by rarkins** [comment]
Maven support has now been merged to master and released. For now I classify it as "alpha" support until some people give its current functionality the thumbs up. 

It supports parsing `pom.xml` files and updating any dependencies referenced *directly* within.

You can test it out by adding this to your Renovate config:

```
  "maven": { "enabled": true }
```

Still to do:
- [Range syntax support](https://github.com/renovatebot/renovate/issues/2986)
- [Parent support](https://github.com/renovatebot/renovate/issues/3164)
- [Properties support](https://github.com/renovatebot/renovate/issues/3165)

Please raise feature requests for any other functionality you would like to see.
