### ISSUE TITLE
GitLab status check wrong sha after rebase

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2709]
@hbetts repositories such as gitlab.com/hyper-expanse/open-source/github-metadata-sync are failing to set the unpublishSafe status check and raising a warning instead. Can you confirm if this is another "expected" permissions problem? According to https://docs.gitlab.com/ee/user/permissions.html, a Developer should be able to "Create or update commit status".

Either this is a technical bug and I'm missing something (e.g. wrong endpoint) that needs to be fixed, or it is to be expected and I need to lower this from a warn to an info.

**Comment by rarkins** [comment]
I think we're using an old sha value from before a rebase:

```
{"msg":"Branch is stale and needs rebasing","time":"2018-10-29T18:08:43.988Z"}

{"path":"projects/hyper-expanse%2Fopen-source%2Fgithub-metadata-sync/repository/commits","msg":"POST","time":"2018-10-29T18:08:50.786Z"}

{"path":"projects/hyper-expanse%2Fopen-source%2Fgithub-metadata-sync/statuses/641710f1ee9862fcd3fc21f4c063f153095cd574","msg":"POST","time":"2018-10-29T18:08:53.774Z"}
```

The 641710f commit is actually the one before the rebase, not after.

**Comment by hbetts** [comment]
I haven't checked anything else, but I can confirm that `641710f` is the previous commit on that branch.

On the diffs page `641710f` shows up as Version 8, and now there is a newer commit listed as Latest -
https://gitlab.com/hyper-expanse/open-source/github-metadata-sync/merge_requests/1/diffs?diff_id=26132424
