### ISSUE TITLE
Initial PR never created

### ISSUE THREAD

**Issue by porridge** [renovatebot/renovate#2712]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Last week I signed up for the free demo, clicked all the way through to enabling renovatebot for https://github.com/porridge/dcos-commons
In the end I got redirected to a page which said that a PR will be created against the repo, but it never was.

**Did you see anything helpful in debug logs?**
There are no logs.

**To Reproduce**

1.  Fork https://github.com/mesosphere/dcos-commons
2.  Sign up for renovatebot

**Expected behavior**
A PR should be created or an email sent explaining what went wrong.

**Comment by rarkins** [comment]
Hi, forked repositories are ignored by default.

If you add a non-fork then you should see an onboarding PR.

If you definitely want to renovate a fork, you’ll need to add the renovate.json file manually with contents { “renovateFork”: true }

**Comment by rarkins** [comment]
Hi, forked repositories are ignored by Renovate by default. Usually you need to manually provision them by adding a `renovate.json` to `master` branch that includes `{ "renovateFork": true }`.

In this case I've added a rule to the bot to enable renovating for this particular repo, you now have an onboarding PR: https://github.com/porridge/dcos-commons/pull/1

Please ask if you have any more questions and sorry for the inconvenience!

**Comment by ViceIce** [comment]
This should be added to the official docu.

**Comment by rarkins** [comment]
@ViceIce 

![image](https://user-images.githubusercontent.com/6311784/52472916-d62df100-2b94-11e9-94cb-c5c7bf3941b2.png)

I've extended the description just now too, but if people don't search for "fork" then they won't find it regardless

**Comment by ViceIce** [comment]
@rarkins Ok, found it. Anyway, a hint on the onboarding page would be helpful.
