### ISSUE TITLE
gitFs error updating branch (cannot lock ref)

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2713]
This is happening in the hosted app, for multiple branches per-repository and also multiple repositories. Example error:

```
Error: To https://github.com/owner/repo-components.git
 ! [remote rejected] renovate/file-loader-2.x -> renovate/file-loader-2.x (cannot lock ref 'refs/heads/renovate/file-loader-2.x': is at b897544d91efd632d641baedb2961643f36b63aa but expected 70d741ca2803e9339cb8ec45f13e1bcedb07bb12)
error: failed to push some refs to 'https://x-access-token:[**redacted**]@github.com/owner/repo-components.git'

    at /usr/src/node_modules/simple-git/promise.js:21:26
    at Git.<anonymous> (/usr/src/node_modules/simple-git/src/git.js:949:21)
    at Function.Git.fail (/usr/src/node_modules/simple-git/src/git.js:1474:18)
    at fail (/usr/src/node_modules/simple-git/src/git.js:1432:20)
    at /usr/src/node_modules/simple-git/src/git.js:1441:16
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"
```

This comes after a "2 file(s) to commit" message.

**Comment by rarkins** [comment]
It seems to be being thrown from the commitFilesToBranch function:
```
      await git.reset('hard');
      await git.checkout(['-B', branchName, 'origin/' + parentBranch]);
      for (const file of files) {
        await fs.writeFile(join(cwd, file.name), Buffer.from(file.contents));
      }
      await git.add(files.map(f => f.name));
      await git.commit(message);
      await git.push(['origin', branchName, '--force']);
```

**Comment by rarkins** [comment]
For both repos, the affected run was triggered by a "master-commit" event - package.json and package-lock.json updated in master. It *seems* like a `repository-changed` type of error but I'm not sure.

Even weirder is that we received a webhook at the same time seemingly confirming the push.

**Comment by kayoub5** [comment]
@rarkins I think I know where the problem is, `commitFilesToBranch` is hard-coded to use the API and not GitFs (since it's not supported for gitlab). so GitFS and API cache, get out of sync.
the solution is to force GitFS to pull/reset from the server.

**Comment by rarkins** [comment]
@kayoub5 	did this change when you added gitFs for GitLab?

**Comment by rarkins** [comment]
@kayoub5 	this is actually for a github repo though

**Comment by rarkins** [comment]
First instance of this occurring was 2018-10-30 07:22am UTC, which is soon after the GitLab gitFs PR went live. simple-git was last updated 16 days ago so seems unlikely to be the cause instead, but I still don't understand which bit of the gitlab change could have caused this though.

**Comment by rarkins** [comment]
This happened to me on the Renovate repo too just now actually, around the time I was merging multiple PRs at once. I think I'll treat this as a 'repository-changed' error.
