### ISSUE TITLE
Only rebase stale PRs during Renovate scheduled hours

### ISSUE THREAD

**Issue by UberMouse** [renovatebot/renovate#2714]
**What would you like Renovate to be able to do?**
Not sure if this is a bug or intended but if I have the `rebaseStalePrs` option set to true then Renovate will rebase all open PRs whenever we have a merge to master. My preference would be that it only does this during the hours I have Renovate schedule to run.

**Comment by rarkins** [comment]
Set https://renovatebot.com/docs/configuration-options/#updatenotscheduled to `false`

**Comment by UberMouse** [comment]
Awesome, cheers.

**Comment by rarkins** [comment]
BTW, Renovate now supports “manual” rebase requests - you can add the label “rebase” to any PR or rename a PR title to start with “rebase!” and both will trigger a run. I haven’t tested it with the out of schedule no-updates so let me know if you every try it and it doesn’t work.
