### ISSUE TITLE
Malformed ('git+https') URLs for issue/PR links in release notes

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#2715]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The release notes section of neutrinojs/neutrino#1195 contains invalid URLs like:
`http://git+https/github.com/okonet/lint-staged/issues/520`

**Did you see anything helpful in debug logs?**
Didn't look, since doubt relevant.

**To Reproduce**

1.  Look at neutrinojs/neutrino#1195

**Expected behavior**
Renovate redirect URLs (to avoid reference spam of linked issues/PRs), that are valid links.

**Comment by rarkins** [comment]
Isn’t it coming directly from their release notes, eg https://github.com/okonet/lint-staged/releases/v8.0.2 ?

**Comment by edmorley** [comment]
Oh yes sorry!
