### ISSUE TITLE
validate macOS arm64 runner

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#27187]
### Describe the proposed change(s).

Check if the new macOS arm based runner are faster than the x64 based

**Comment by zharinov** [comment]
Looks costly, though

**Comment by viceice** [comment]
> Looks costly in terms of minutes, though

? why? it's free for opensource. I don't mean the `large` or `xlarge` runners. the normal `macos-14`[^1]

[^1]: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

**Comment by zharinov** [comment]
Oh, wow, didn't know about `macos-14z one, I'll check
