### ISSUE TITLE
Mark macOS 14 runners as stable in our `datasource/github-runners` when out of beta

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#27228]
### Describe the proposed change(s).

Currently the macOS 14 runners for the `datasource/github-runners` are in beta. Though GitHub has blogged about the availability, [^2] the macOS 14 runners are still in beta according to the official readme. [^1]

We should add the macOS 14 runners, once they are out of beta. 😉 

[^1]: [`actions/runner-images`, available images section](https://github.com/actions/runner-images?tab=readme-ov-file#available-images)
[^2]: [GitHub blog about macOS 14 runners being avaible](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/)

**Comment by HonkingGoose** [comment]
@rarkins I wanted to tag this `datasource:github-runners` but that label is missing. Do you want to make a new label, or do you want to keep things as-is?

**Comment by viceice** [comment]
Doesn't mean the blog post that they are GA? 🤔

**Comment by HonkingGoose** [comment]
@viceice it's still in beta, I asked:

- https://github.com/actions/runner-images/discussions/9283#discussioncomment-8410181

**Comment by viceice** [comment]
OK, we can add them as unstable, then renovate would not suggest the update until you explicit set `ignoreUnstable=false`

- #27292

**Comment by HonkingGoose** [comment]
I renamed the issue, because we need to track when the macOS 14 runner gets out of beta, and then mark it as stable in our code.

I also opened a discussion, to talk about automating this datasource somehow:

- https://github.com/renovatebot/renovate/discussions/27745

**Comment by HonkingGoose** [comment]
The [`actions/runner-images` repository's `README.md` file](https://github.com/actions/runner-images/blob/main/README.md) says the macOS 14 runners are out of beta. So we can mark them as stable in our code.

Please also check if our code's up-to-date with the rest of the repository's readme as well.

**Comment by HonkingGoose** [comment]
This issue is marked `priority-2-high`. It should probably be assigned to somebody to work on. 

I'm _not_ going to work on this, because I would need to update the Jest snapshot tests. I often mess up when updating the tests. So I'll let a maintainer work on this. :wink:
