### ISSUE TITLE
Automerge of failed branch on Gitlab when setting assignees

### ISSUE THREAD

**Issue by mxey** [renovatebot/renovate#2735]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**

The repository had a Renovate MR open for a few days that was not automerged because its pipeline had failed. Then I changed the renovate.json in the repository to set `assignees`. On the next run, Renovate set an assignee for the MR, which AFAIK it only does if it will not automerge the MR, but then proceeded to automerge the MR in the same run.

**Did you see anything helpful in debug logs?**

```
DEBUG: Setting assignees and reviewers as status checks failed (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
DEBUG: Adding assignees m.gass to #4 (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
DEBUG: GET (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
       "path": "users?username=m.gass"
DEBUG: PUT (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
       "path": "projects/m.gass%2Frenovate-automerge-assignee-reproduction/merge_requests/4?assignee_id=2"
 INFO: Added assignees (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
       "assignees": ["m.gass"]
DEBUG: Merge Request #4 does not need updating (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
DEBUG: Checking #4 for automerge (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
DEBUG: Automerging #4 (repository=m.gass/renovate-automerge-assignee-reproduction, dependencies=k8s-skaffold/skaffold, branch=renovate/docker-k8s-skaffold-skaffold-0.x)
```

**To Reproduce**

* Create repository like https://github.com/mxey/renovate-automerge-assignee-reproduction on a Gitlab
* Run Renovate, it creates a MR
* Wait for the MR pipeline to fail
* Modify `renovate.json` in the repository to set assignees
* Run Renovate

**Expected behavior**

Renovate should not have automerged the failed MR.

**Comment by mxey** [comment]
> Do you know if it works correctly if the assignee is set from the beginning?

I am not a 100% certain, but apparently yes.

**Comment by mxey** [comment]
I just had the same issue again. Apparently I was wrong. Even if the assignee is already configured, the issue occurs.

**Comment by mxey** [comment]
As I understand it, `can_be_merged` indicates that there is no merge conflict, it does not indicate pipeline status.

Doesn't Renovate's `getBranchStatus` for Gitlab look at the pipeline status of the commits?

**Comment by rarkins** [comment]
This setting is relevant:
![image](https://user-images.githubusercontent.com/6311784/48129075-c4346d80-e288-11e8-81f2-760a72f99d01.png)

**Comment by rarkins** [comment]
We don't look at `getBranchStatus` for PRs currently as I assumed the platform should return the relevant can/cannot be merged status within the PR. But I think you're right - GitLab confusing returns no indication that a MR can't be merged even when the UI shows it is blocked. And it literally says "can_be_merged" to make it worse. Seems like we need to add an internal call to getBranchStatus() from within getPr().

**Comment by mxey** [comment]
In your screenshot of the merge request, AFAICT the merge request is not blocked. The button is red because the pipeline failed, but the merge is still possible. If you enable the setting you showed, then the UI will not show the merge button: https://gitlab.rz.babiel.com/help/user/project/merge_requests/merge_when_pipeline_succeeds#only-allow-merge-requests-to-be-merged-if-the-pipeline-succeeds

So yes, you'll have to call `getBranchStatus`.

**Comment by rarkins** [comment]
Thanks for the help, now done.
