### ISSUE TITLE
Support looseVer

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2748]
We need a “loose” versioning scheme for cases where semver isn’t official and versioning might be a little wild. 

It must support varied precision, anywhere from 1 section (“3”) to 6 sections (1.2.3.4.5.6). 2.4.0 should be considered greater than 2.4.

No ranges necessary. 

Ideally supports “prerelease” like 1.2.3-alpha.1, we can just sort everything after the hyphen alphabetically. 

Also needs to support weird suffixes like 1.2.3.release. Ie allow there to be non-numbers and if so then sort alphabetically, otherwise sort numerically. 

Main driver for this was looking at Homebrew taps.

**Comment by kayoub5** [comment]
@rarkins waiting for #2742 to be merged, to reuse some code

**Comment by rarkins** [comment]
No ranges. I meant `isVersion` is the one that's generous. Here's another inspiration: https://github.com/ChristianMurphy/uPortal/blob/example/issue/gradle.properties

The following are all versions there:
```
1.4
3.5.0
4.2.21.Final
0.6.5.1
20100527
2.1.0-M3
4.3.20.RELEASE
1.1-groovy-2.4
0.8a
3.1.0.GA
3.0.0-beta.3
```

I'm not sure if/how to manage "unstable" either. Obviously the one with "beta" in it looks unstable, but the "Final", "RELEASE" and "GA" ones appear stable. Also "1.1-groovy-2.4" is probably stable, as is "2.1.0-M3". I think we ignore stable/unstable initially.
