### ISSUE TITLE
Error in 'azure-bicep-resource' data source due to updates JSON schema

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#27575]
### Discussed in https://github.com/renovatebot/renovate/discussions/27556

<div type='discussions-op-text'>

<sup>Originally posted by **NicolasBissig** February 26, 2024</sup>
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

renovate/renovate:37-slim

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

## Description

Currently, the `azure-bicep-resource` data source on the self-hosted docker version always fails and thus dependencies are not updated.

## Cause

It seems that the bicep `index.json` got a new format between these two commits:

https://github.com/Azure/bicep-types-az/blob/326b3589f201db73cbd08e3060f952eb931b487f/generated/index.json
https://github.com/Azure/bicep-types-az/blob/6b9843ae1ff0c3aa642e24411e50c467d1fbb697/generated/index.json

Here the field `Resources` got renamed to `resources`, and the field `Functions` to `resourceFunctions`
Also, the `$ref` elements got introduced.

## Reproduce

I tried to reproduce the issue [here](https://github.com/NicolasBissig/renovate-bicep-reproduce) but with the GitHub version it seems to work.
I cannot publicly share a repository of our GitLab Instance.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Datasource unknown error (repository=[REDACTED])
       "datasource": "azure-bicep-resource",
       "packageName": "Microsoft.Web/sites",
       "err": {
         "message": "Schema error",
         "stack": "ZodError: Schema error\n    at Object.get error [as error] (/usr/local/renovate/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/types.js:43:31)\n    at ZodEffects.parseAsync (/usr/local/renovate/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/types.js:166:22)\n    at Http.requestJson (/usr/local/renovate/lib/util/http/index.ts:369:18)\n    at AzureBicepResourceDatasource.getResourceVersionIndex (/usr/local/renovate/lib/modules/datasource/azure-bicep-resource/index.ts:63:22)\n    at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n    at AzureBicepResourceDatasource.getReleases (/usr/local/renovate/lib/modules/datasource/azure-bicep-resource/index.ts:42:34)\n    at /usr/local/renovate/lib/util/cache/package/decorator.ts:122:18\n    at fetchReleases (/usr/local/renovate/lib/modules/datasource/index.ts:296:13)\n    at lookupUpdates (/usr/local/renovate/lib/workers/repository/process/lookup/index.ts:116:56)\n    at withLookupStats (/usr/local/renovate/lib/workers/repository/process/fetch.ts:28:18)\n    at fetchDepUpdates (/usr/local/renovate/lib/workers/repository/process/fetch.ts:72:42)\n    at /usr/local/renovate/lib/workers/repository/process/fetch.ts:118:23\n    at /usr/local/renovate/node_modules/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22",
         "issues": {"Resources": "Required", "Functions": "Required"}
       }
DEBUG: Failed to look up azure-bicep-resource package Microsoft.Web/sites (repository=[REDACTED], packageFile=bicep/functionApp.bicep, dependency=Microsoft.Web/sites)
```

</details>

### Have you created a minimal reproduction repository?

https://github.com/renovate-reproductions/27556

**Comment by RahulGautamSingh** [comment]
Hmm, I was able to reproduce the error on Github as well...https://github.com/RahulGautamSingh-testing/renovate-bicep-reproduce/issues/1#issue-2156459046 (will need check the first version from the `edited` dropdown)
