### ISSUE TITLE
Renovate Fails when Encountering SBT build.properties File

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#27653]
### Discussed in https://github.com/renovatebot/renovate/discussions/27650

<div type='discussions-op-text'>

<sup>Originally posted by **gwendolyngoetz** March  1, 2024</sup>
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the problem

I found that Renovate was failing early today for me. The failures began yesterday (Feb 28th).

Using the renovate-cli I managed to track down the issue. Something fails to read the sbt build.properties file.

[Here's a repository with a minimal repro of the issue](https://github.com/gwendolyngoetz/renovate-sbt-error).

For now I'm ignoring the build.properties file by adding `"ignorePaths": ["**/server/project/build.properties"]` to my `renovate.json` file. This unblocked our repository on github, but it would be nice to get this working again.

Error:
```json
[
  {
    "name": "renovate",
    "level": 50,
    "logContext": "YhlByu1xECO48xRTHUABV",
    "repository": "local",
     "err": {
       "message": "Cannot read properties of undefined (reading 'unshift')",
       "stack": "TypeError: Cannot read properties of undefined (reading 'unshift')\n    at Object.extractAllPackageFiles (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/modules/manager/sbt/extract.ts:402:27)\n    at extractAllPackageFiles (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/modules/manager/index.ts:53:17)\n    at getManagerPackageFiles (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:33:29)\n    at /home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/extract/index.ts:57:28\n    at async Promise.all (index 0)\n    at extractAllDependencies (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/extract/index.ts:54:26)\n    at extract (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at extractDependencies (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/process/index.ts:154:26)\n    at Object.renovateRepository (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/index.ts:63:9)\n    at attributes.repository (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/global/index.ts:200:11)\n    at start (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/global/index.ts:185:7)\n    at /home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/renovate.ts:18:22"
      },
     "msg": "Repository has unknown error"
   }
]
```

### Relevant debug logs

<details><summary>Logs</summary>

```
[
  {
    "name": "renovate",
    "level": 50,
    "logContext": "YhlByu1xECO48xRTHUABV",
    "repository": "local",
     "err": {
       "message": "Cannot read properties of undefined (reading 'unshift')",
       "stack": "TypeError: Cannot read properties of undefined (reading 'unshift')\n    at Object.extractAllPackageFiles (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/modules/manager/sbt/extract.ts:402:27)\n    at extractAllPackageFiles (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/modules/manager/index.ts:53:17)\n    at getManagerPackageFiles (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:33:29)\n    at /home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/extract/index.ts:57:28\n    at async Promise.all (index 0)\n    at extractAllDependencies (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/extract/index.ts:54:26)\n    at extract (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at extractDependencies (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/process/index.ts:154:26)\n    at Object.renovateRepository (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/repository/index.ts:63:9)\n    at attributes.repository (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/global/index.ts:200:11)\n    at start (/home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/workers/global/index.ts:185:7)\n    at /home/gwendolyn/.local/share/nvm/versions/node/v20.11.1/lib/node_modules/renovate/lib/renovate.ts:18:22"
      },
     "msg": "Repository has unknown error"
   }
]
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above</div>

**Comment by rarkins** [comment]
This may be fixed by https://github.com/renovatebot/renovate/commit/4bc12952d1ede89d601e9a43a3ea3c86cca2bcd5

But we need a further code review by @lpriyasivakumar in case there's any root cause needing fixing

**Comment by gwendolyngoetz** [comment]
Running the cli version in local mode (`LOG_LEVEL=debug npx renovate --platform=local`) now works again. I used v37.221.0. 

The process on GitHub still fails; https://developer.mend.io logs say it's using v37.220.2. I don't know what cadence that gets updated with, but I'll try again in a day or two.

**Comment by mertant** [comment]
1 business day later, as of 2024-03-04 10:50 UTC, our SaaS Renovate is still using the broken version [37.220.2](https://github.com/renovatebot/renovate/releases/37.220.2). (The fix, per https://github.com/renovatebot/renovate/pull/27667,  would be on versions >= [37.221.3](https://github.com/renovatebot/renovate/releases/tag/37.221.3).)

```
INFO: Repository started
{
  "renovateVersion": "37.220.2"
}
```

When can we expect the next `renovateVersion` bump on the SaaS? It looks like the last one ([37.212.0](https://github.com/renovatebot/renovate/releases/tag/37.212.0) -> [37.220.2](https://github.com/renovatebot/renovate/releases/37.220.2)) happened at around 2024-02-29 10:00 UTC (±15min), only a couple hours after it was released. Can I assume there is some sort of manual process involved?

**Comment by rarkins** [comment]
It's a manual process, so no SLAs/expectations. We'll try to get to this one soon

**Comment by mertant** [comment]
Ok, got it. Thanks!

**Comment by mertant** [comment]
The Mend runner seems to have updated at around 2024-05-03 17:30 UTC.

```
INFO: Repository started
{
  "renovateVersion": "37.227.2"
}
```

**Comment by gwendolyngoetz** [comment]
Hi @rarkins,

Sorry for the delay. I was waiting for the mend.io to update and finally had a chance to get back to this.

I'm still having errors which repro both in our project and my [minimal example repo](https://github.com/gwendolyngoetz/renovate-sbt-error).


Here are log files for the minimal repro and my full project
[sample-repo-logs.txt](https://github.com/renovatebot/renovate/files/14552539/sample-repo-logs.txt)
[civiform-repo-logs.txt](https://github.com/renovatebot/renovate/files/14552547/civiform-logs.txt)

Running the cli `platform=local` succeeds, but when run normally is where the failure occurs.

I get this warning: "Package lookup failures" and this is shown on the dashboard "Failed to look up github-releases package sbt/sbt`". There tend to be a lot of http 405s or http 404s to maven.org, scala-sbt.org, and shibboleth.net.

```json
{
  "warnings": [
    "Failed to look up github-releases package sbt/sbt"
  ]
  "files": [
    "server/project/build.properties"
  ]
}
```

Further back in the log output there is a POST to maven with an http 405 result.


```
DEBUG: hostRules: no authentication for repo1.maven.org
DEBUG: Using throttle 200 intervalMs for host repo1.maven.org
DEBUG: Using queue: host=repo1.maven.org, concurrency=5
DEBUG: POST https://repo1.maven.org/maven2/api/graphql = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=405 retryCount=0, duration=24)
DEBUG: Datasource connection error
{
  "datasource": "github-releases"
  "packageName": "sbt/sbt"
  "url": "https://repo1.maven.org/maven2/api/graphql"
  "errCode": "ERR_NON_2XX_3XX_RESPONSE"
}

DEBUG: Failed to look up github-releases package sbt/sbt
{
  "dependency": "sbt/sbt"
  "packageFile": "server/project/build.properties"
}

DEBUG: PackageFiles.add() - Package file saved for base branch
{
  "baseBranch": "master"
}

DEBUG: Package releases lookups complete
{
  "baseBranch": "master"
}
```

**Comment by viceice** [comment]
it's using the wrong url for sbt, it should not set a registry url for that particular package

**Comment by rarkins** [comment]
Please raise anything else in a new discussion, it's too easy to miss comments in closed issues/PRs
