### ISSUE TITLE
Discard extra dependency information in square brackets for python managers

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#27657]
### Describe the proposed change(s).

As discussed in https://github.com/renovatebot/renovate/discussions/27552

Sometimes the dependency name will have square brackets like `splinter[django]`. This is frequently referred to as "optional" dependencies, although the meaning of the second part can be varied. From Renovate's point of view, we can discard/ignore the second part and just treat the above example as `splinter`.

May apply to all python package managers.

Reproduction for pipenv: https://github.com/renovate-reproductions/27552

**Comment by RahulGautamSingh** [comment]
Pip-requirements can be removed from the list, it already handles such cases.
https://github.com/renovatebot/renovate/blob/4bfd0f304eef6608e566f0af3153864a1279e793/lib/modules/manager/pip_requirements/extract.ts#L13-L26

We can use the same regex for the other managers as well.

**Comment by RahulGautamSingh** [comment]
I think this won't apply to poetry either, it specifies extras differently ([ref](https://python-poetry.org/docs/pyproject/#extras))
And the `pip-setup` manager handles them already as well.
