### ISSUE TITLE
autodiscoverProjects for Bitbucket Cloud

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#27661]
### Describe the proposed change(s).

Discussed in https://github.com/renovatebot/renovate/discussions/27093

I think it's best to make this a new option because, apart from it being a different name (projects vs namespaces), Bitbucket Cloud also has these differences vs GitLab:
- Filtering would be done client-side not server-side
- Ability to use patterns and/or excludes

So we should create a new option autodiscoverProjects, for Bitbucket Cloud only, and use the `matchRegexOrGlobList()` function which allows exclusions.

**Comment by viceice** [comment]
can this be faked with our topic filter?

**Comment by rarkins** [comment]
I think they're potentially too different semantics
