### ISSUE TITLE
Check GitLab MR body settings

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2769]
I suspect that GitLab is changing the MR body, in particular making them \r\n instead of \n. Ideally our own massaging should match GitLab's defaults so that we don't end up with unnecessary MR updating.

I noticed this when I was editing MR titles through the web UI, it seems that the description also gets changed even though I didn't actually change the description.

**Comment by rarkins** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/53715

**Comment by kayoub5** [comment]
@rarkins should we change the code comparing PR bodies to something that ignores white space changes?

**Comment by rarkins** [comment]
Yeah, maybe ignoring all white space is a good idea instead of simply normalising it. Unless we have a white space bug in our template, because then it means we wouldn’t “heal” it. So either we normalise line returns before comparing or we strip out all white space and then compare.

**Comment by rarkins** [comment]
Let's make our PR body compare logic first strip out all whitespace from both bodies and then compare.
