### ISSUE TITLE
Renovate Errors When MR Close and Branch is Deleted

### ISSUE THREAD

**Issue by ekristen** [renovatebot/renovate#2771]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
If you close a Merge Request on GitLab because you want it to be ignored, and subsequently delete the branch for the Merge Request, next time you run Renovate it starts to error out.

It still resolves the closed MR branch as a branch it needs to "review" and when it can't find the branch it gets errors from the API and then exits non-zero.

**To Reproduce**

1. Create a repository with a node.js project on GitLab
2. Enable renovate for that project.
3. Close a Merge Request it opens and delete the backing branch

**Expected behavior**
If a MR is closed, it should ignore the branch, and shouldn't care if it is no longer present. It shouldn't even resolve it as a branch to check on.

**Comment by rarkins** [comment]
Please confirm which version of Renovate you’re running and see if you can reproduce it with the latest version as there’s been some recent GitLab fixes.

**Comment by ekristen** [comment]
Wow, thanks for the quick response!

IIRC I didn't actually delete the branch, I believe that closing the MR did it for me based on what I'm seeing, but nonetheless, Renovate doesn't like that, it still tries to find the branch and errors because of it.

I will test the latest ASAP and get back to you.

**Comment by ekristen** [comment]
Version: 13.123.1

Latest version doesn't work. This is the behavior ...

1. Renovate opens a MR with a branch renovate/some-dep
2. I close the MR because I want to ignore it. Branch is still present.
3. On the next run of Renovate, the branch gets deleted (reaped it looks like)
4. On the next run of Renovate, it errors out because it looks for the branch that is not longer present for the MR that is closed.

**Comment by rarkins** [comment]
Thanks for the extra details. If you can double check the exact steps then it will help me solve it quicker.

**Comment by rarkins** [comment]
Actually never mind, I didn’t see your second message when replying. I’ll take a look.

**Comment by ekristen** [comment]
No problem! Let me know how I can help. I can provide logs and any other details if you'd like. Thanks for the wonderful tool!

**Comment by rarkins** [comment]
I can reproduce it and have a fix on the way

**Comment by ekristen** [comment]
Thanks! I've been using the docker image to run the code, so once that's published I'll update and test.

**Comment by rarkins** [comment]
OK, keep an eye out for when v13.124.1 is available in https://hub.docker.com/r/renovate/renovate/tags/ - I'd estimate around 10-15 minutes time.

**Comment by rarkins** [comment]
Now available

**Comment by ekristen** [comment]
that's a nifty bot feature!

**Comment by ekristen** [comment]
Confirmed Fixed! I must say this is the quickest resolution to a bug I've had in a *very* long time. Much appreciated.

**Comment by rarkins** [comment]
You're welcome, and thanks for the quality bug report. The better they are, the sooner I try to fix!

**Comment by rarkins** [comment]
By the way, if you're running on gitlab.com and not your own GitLab instance, you can now install the app rather than managing your own Renovate instance: https://renovatebot.com/docs/install-gitlab-app/

**Comment by ekristen** [comment]
Oh nice! Thanks for the info.
