### ISSUE TITLE
Add Cargo semver versioning

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2780]
Necessary for #1870 

We need to add lib/versioning/semver-cargo

It will be similar to how [semver-composer](https://github.com/renovatebot/renovate/tree/master/lib/versioning/semver-composer) is implemented - i.e. some syntax is same as npm's semver but some is not.

It looks *mostly* similar. One different is the use of comma for multiples, e.g. `>= 1.2, < 1.5`

We should compare the examples listed on https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html with https://semver.npmjs.com

**Comment by rarkins** [comment]
Actually the only difference I see is the use of commas. So it's more like semver-hashicorp in that it needs a simple massaging of ranges (to remove commas/add them back) and that's it. We could develop the Cargo manager using regular semver for now.

**Comment by kayoub5** [comment]
@rarkins there are more differences in the logic, rather the syntax, for example "1.2.3" is equivalent to "^1.2.3" and not "=1.2.3".

**Comment by rarkins** [comment]
Thanks, I skipped over that section and missed it

**Comment by rarkins** [comment]
So "1.2.3" is a range while "= 1.2.3" is the way to specify a single version

**Comment by kayoub5** [comment]
#### Caret requirements
> This compatibility convention is different from SemVer in the way it treats versions before 1.0.0. While SemVer says there is no compatibility before 1.0.0, Cargo considers 0.x.y to be compatible with 0.x.z, where y ≥ z and x > 0.

**Comment by rarkins** [comment]
@kayoub5 thanks. I saw that but don't think it changes any of our logic unless we implement https://github.com/renovatebot/renovate/issues/1257 to cover all managers
