### ISSUE TITLE
Label check action

### ISSUE THREAD

**Issue by denis-rossati** [renovatebot/renovate#27828]
# Label check action
## Found issues with missing `status:` labels:
- #27802
- #27801
- #27793
- #27775
- #27661
- #27655
- #27633
- #27631
- #27601
- #27600
- #27543
- #27535
- #27491
- #27478
- #27433
- #27391
- #27377
- #27375
- #27349
- #27312
- #27295
- #27293
- #27168
- #27167
- #27105
- #27055
- #27048
- #27035
- #27034
- #27032
## Found issues with missing `priority` labels:
- #27661
- #26744
- #27180

**Comment by denis-rossati** [comment]
Sorry, I forgot to change the URL of the test repo where I was supposed to create this issue to a PR that I'm going to open shortly :sweat_smile:

**Comment by viceice** [comment]
status is not required, because we've removed the ready value

**Comment by rarkins** [comment]
No status is ok - it means an issue is ready. But each issue should have a priority.
