### ISSUE TITLE
"failed to add assignee (Cannot read properties of undefined (reading 'id'))" on Gitlab self-hosted

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#27943]
### Discussed in https://github.com/renovatebot/renovate/discussions/27890

<div type='discussions-op-text'>

<sup>Originally posted by **deronnax** March 12, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Gitlab

### Please tell us more about your question or problem

Hello.
I run renovate on one of our repo, and on this repository, renovate has an assignee problem: it fails to add assignees to an MR (see logs).
I won't be able to do a minimum reproducible use case, but maybe we can work something else.
I am pretty sure it did work when using reviewers instead of assignees.
Thank you very much.

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: Adding assignees 'orga/core/squad-honeytoken' to #11290 (repository=gg-code/prm/ward-runs-app, branch=renovate/python-gitlab-4.x)
DEBUG: addAssignees error (repository=gg-code/prm/ward-runs-app, branch=renovate/python-gitlab-4.x)
       "err": {
         "message": "Cannot read properties of undefined (reading 'id')",
         "stack": "TypeError: Cannot read properties of undefined (reading 'id')\n    at getUserID (/usr/local/renovate/lib/modules/platform/gitlab/http.ts:10:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Proxy.addAssignees (/usr/local/renovate/lib/modules/platform/gitlab/index.ts:1196:24)\n    at addParticipants (/usr/local/renovate/lib/workers/repository/update/pr/participants.ts:61:11)\n    at ensurePr (/usr/local/renovate/lib/workers/repository/update/pr/index.ts:501:9)\n    at processBranch (/usr/local/renovate/lib/workers/repository/update/branch/index.ts:753:28)\n    at writeUpdates (/usr/local/renovate/lib/workers/repository/process/write.ts:166:17)\n    at update (/usr/local/renovate/lib/workers/repository/process/extract-update.ts:214:11)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:77:19)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:200:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:185:7)\n    at /usr/local/renovate/lib/renovate.ts:18:22"
       }
 WARN: Failed to add assignees (repository=gg-code/prm/ward-runs-app, branch=renovate/python-gitlab-4.x)
```

</details>
</div>

**Comment by rarkins** [comment]
This code needs to be refactored to be defensive: https://github.com/renovatebot/renovate/blob/5f4af4060d41498b0aabd07ec77e0fa9dcc7f881/lib/modules/platform/gitlab/http.ts#L7-L10

**Comment by RahulGautamSingh** [comment]
What should be done here? Add optional chaining and a warning incase id could not be found.

**Comment by viceice** [comment]
> What should be done here? Add optional chaining and a warning incase id could not be found.

yes, seems good

**Comment by RahulGautamSingh** [comment]
If one assignee could not be found, then none of the assginees are added in gitlab. Should this be refactred to add the available assignees and log a message for the ones which could not be assigned?

**Comment by deronnax** [comment]
Hello, original bug reporter here. I would love a log message telling which assignees pose a problem, because we have no clue on the Gitlab side, it all looks fine.
