### ISSUE TITLE
Default to JSON5 parsing

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#27969]
### Describe the proposed change(s).

[This is a reversal of a previous change]

Renovate should use JSON5 parsing for its own config files (including presets). Users are "free" to stick with standard JSON syntax too.

**Comment by rarkins** [comment]
A big challenge here is how to handle config migration of JSON5 without stripping comments.

**Comment by viceice** [comment]
should we close this in favor of the jsonc issue?

**Comment by HonkingGoose** [comment]
I assume this is the "jsonc issue"?

- #27972
