### ISSUE TITLE
Wrong commit type used

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#2796]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I have configured Renovate to always update `npm` updates with `chore`:

https://github.com/felixfbecker/vscode-php-intellisense/blob/331f59a6a44f974063d04585616cb1180b3aeece/renovate.json#L7

But it is creating PRs with `fix`: https://github.com/felixfbecker/vscode-php-intellisense/pull/389

I also configured it for a specific package to "mirror" the type of upgrade (i.e. patch -> `fix`, minor -> `feat`):

https://github.com/felixfbecker/vscode-php-intellisense/blob/331f59a6a44f974063d04585616cb1180b3aeece/renovate.json#L35-L37

But it is creating PRs for patch updates with `feat`:

https://github.com/felixfbecker/vscode-php-intellisense/pull/390

`feat(deps): update dependency felixfbecker/language-server to v5.4.4`

```diff
-        "felixfbecker/language-server": "5.4.3"
+        "felixfbecker/language-server": "5.4.4"
```

**Comment by felixfbecker** [comment]
Ah, that explains it. Honestly I prefer using explicit configuration over presets (especially the ones that look like function calls) because I can get autocompletion, validation and hover tooltips for those, while for presets I always need to look at the docs (or even the source on GitHub) to see what is available, what they do and what they are called. I would actually consider getting rid of `config:base` completely and purely rely on Renovate's pure defaults + explicit configuration.

I see that `:semanticCommitType(chore)` just defines `"semanticCommitType": "{{arg0}}"`, so shouldn't it be the same as specifying `semanticCommitType": "chore"` manually?

Is there explicit configuration I could use to make this work?

**Comment by rarkins** [comment]
Sorry, I typed that from my mobile earlier and included the wrong one :-/

I meant to recommend `:semanticCommitTypeAll(chore)` which expands to:

```
{
  "packageRules": [
    {
      "packagePatterns": [
        "*"
      ],
      "semanticCommitType": "chore"
    }
  ]
}
```

FYI, the sub-preset inside `config:base` that you are needing to override expands to this:

```json
{
  "packageRules": [
    {
      "packagePatterns": [
        "*"
      ],
      "semanticCommitType": "chore"
    },
    {
      "depTypeList": [
        "dependencies"
      ],
      "semanticCommitType": "fix"
    }
  ]
}
```

**Comment by felixfbecker** [comment]
So this should do it then for npm, right?
```diff
  "rangeStrategy": "pin",
   "semanticCommits": true,
   "npm": {
-    "semanticCommitType": "chore",
     "packageRules": [
       {
         "packagePatterns": [
           "*"
         ],
+        "semanticCommitType": "chore",
         "minor": {
           "groupName": "all non-major dependencies",
           "groupSlug": "all-minor-patch"
```

But how to fix the rule for the Composer dependency? It is already in a `packageRule`:

```json
  "packageRules": [
    {
      "packageNames": ["felixfbecker/language-server"],
      "schedule": [],
      "minor": {
        "semanticCommitType": "feat"
      },
      "patch": {
        "semanticCommitType": "fix"
      }
    }
  ]
```

**Comment by felixfbecker** [comment]
Thanks, committed that. It's unfortunate that the nested configuration with `minor`/`patch` doesn't work as expected.

**Comment by felixfbecker** [comment]
Thank you for your help!

**Comment by rarkins** [comment]
Reference of issue to refactor (fix) the minor/patch logic: https://github.com/renovatebot/renovate/issues/2799

**Comment by felixfbecker** [comment]
Still happening :(

https://github.com/felixfbecker/vscode-php-intellisense/pull/393

Config: https://github.com/felixfbecker/vscode-php-intellisense/blob/master/renovate.json

**Comment by rarkins** [comment]
This might actually be a separate cause. If you don’t configure separateMinorPatch=true then all updates are classified as one of major or minor, with minor in this case meaning “not major”. This approach comes from the earliest days before rules for patch were even supported. I think I might fix it for good in the next major release as it will be slightly breaking in behaviour.

**Comment by felixfbecker** [comment]
So I need to set `separateMinorPatch: true`?

**Comment by rarkins** [comment]
I believe that will resolve your current problem. The downside is that if there are both a patch *and* a minor update available at the same time, you'll get two PRs and need to choose which to merge first. Merge the minor one and the patch one will get autoclosed.

**Comment by rarkins** [comment]
Looks like it resolved the issue? https://github.com/felixfbecker/vscode-php-intellisense/pull/394
