### ISSUE TITLE
Config logic refactor

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2800]
The internal logic for applying rules can be very confusing at times, example: https://github.com/renovatebot/renovate/issues/2796

This is mainly because Renovate has two different ways of "prioritising" config rules:
1. Order of config (in particular, order of packageRules)
2. Specificity of config, e.g. major/minor/patch rules get applied last - by necessity - but it can be confusing to know why/when.

It can also be particularly confusing how "regular" config in a renovate.json does not always override presets you'd expect. e.g. you could do:

```
{
  "extends": ["config:base"],
  "semanticCommitType": "build"
}
```

and yet still end up with fix/chore in PRs due to a preset inside `config:base`.

Proposal: internally, massage everything to flattened packageRules, starting with #2799. in addition:

- Can we migrate other nested objects inside packageRules such as managers?
- "Regular" config should be applied in the very last packageRule (except if `force` is used)

The goal is:
- Preserve as much of the existing syntax as possible
- Make the typical result more "predictable" to the user
- By massaging everything to packageRules, make it much easier to debug/troubleshoot if the result is *not* predicted

**Comment by rarkins** [comment]
Cc @felixfbecker @hbetts  - your inputs would be appreciated. My desire to make Renovate highly configurable has now resulted in some unanticipated complexities/inconsistencies that I'd like to sort out.

**Comment by 72636c** [comment]
👋 I'm interested in contributing here. I've been iterating on a Renovate preset and have run into a couple of pain points that seem to stem from the aforementioned prioritisation:

- It is harder than expected to override defaults specified in [schema.json](https://github.com/renovatebot/renovate/blob/master/renovate-schema.json)
- Things seem to get super dicey once groups are involved (e.g. how do I ensure a rule is applied to a group if it contains a package matching `"depTypeList": ["dependencies"]`?)

**Comment by rarkins** [comment]
Yes, I was recently thinking of partly implementing this as part of the next major release. In particular, making sure that *order of packageRules* is the most important consideration for how we apply config.

Can you list your ideas here about what to change? examples comparing current behaviour to desired behaviour would especially help.

Here is another example: https://github.com/renovatebot/config-help/issues/346 (it should actually be an easy "fix" to just remove rule, but I need to think if there are any unintended consequences)

**Comment by rarkins** [comment]
By the way, I always thought it desirable to put defaults into `schema.json` as it also functions as a pseudo-documentation of behaviour, however I agree that there are times when it makes it really challenging to override.

Another idea I've had with config is "everything is a package rule". It's nice and convenient to use object shorthand (e.g. `{ python: { foo: 'bar' }}` but if we had a deterministic way to convert all shorthand configs into packageRules before evaluation then it would be much easier to track things down and understand.

**Comment by 72636c** [comment]
> everything is a package rule

I think this would be the easiest to reason about. I'd love to develop and debug configs with a `renovate render` command that evaluates and prints a flat list of corresponding package rules.

I'll expand on grouping behaviour separately because implementing my desired behaviour there may be more effort than it is worth.

For now, if we assume that config is evaluated on a per-package basis, here's a strawman:

- Package rules are always evaluated in order, last rule wins
- A rule matches all packages by default and can be narrowed by specifying `matchers`
- A preset is just a list of `packageRules` that is expanded inline

This has practical issues:

- Compatibility with existing configs, where specificity plays a part
- Presets can't be extended, only overridden

```yaml
schemaVersion: v2.0.0

packageRules:
  # schedule all packages daily
  - preset: schedule:daily

  # schedule non-DefinitelyTyped npm packages on weekends
  - matchers:
      - excludePackagePatterns: ['^@types/']
      - includeManagers: [npm]
    options:
      schedule: every weekend

  # group react packages
  - matchers:
      - includePackagePatterns: [react]
    options:
      groupName: Package has react in its name!
```

**Comment by 72636c** [comment]
Sorry, I just re-read the OP and see that compatibility is a big focus, so you can  disregard the strawman above 🤦‍♂. The problem it was trying to address was that it's hard to reason about both `packageRules` order and specificity at the same time, so it eliminated the latter.

With the current config format, I already try to use `packageRules` as an ordered list. It's workable, though occasionally I need to reach for rather specific rules to "reset" the schema defaults, e.g.

```json
{
  "packageRules": [
    {
      "digest": {
        "commitMessageTopic": "{{{depName}}}"
      },
      "managers": ["gomod"],
      "semanticCommitType": "fix"
    }
  ]
}
```

I'll do more thinking about the desired grouping behaviour and come back to you.

**Comment by rarkins** [comment]
I am ok with breaking changes if it’s better for the long term. Specificity came before package rules and the latter makes more sense. We can also potentially do intelligent massaging of existing config to put specific configs into package rules that come last.

**Comment by 72636c** [comment]
Here's a grouping problem I've run into:

```json
[
  {
    "depTypeList": ["devDependencies"],
    "groupName": "npm dev dependencies",
    "managers": ["npm"]
  },
  {
    "extends": ["group:monorepos"],
    "excludePackageNames": []
  }
]
```

- If there are monorepo packages spread across `dependencies` and `devDependencies`, I want those packages to be part of a separate monorepo PR
- If there are `devDependencies`-only monorepo packages, I'd prefer for them to be grouped up with the rest of the `npm dev dependencies`
- The `packageRules` above will always separate out the monorepo packages

Curious on your thoughts as I'm not really sure how to express this in the current configuration language.
