### ISSUE TITLE
Renovate PR was merged before passing CI

### ISSUE THREAD

**Issue by HiroshiOHSUGA** [renovatebot/renovate#2801]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

Renovate sent PR and merge it but CircleCI was not done.

**Did you see anything helpful in debug logs?**

CircleCI log
```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

remote: Enumerating objects: 430, done.        
remote: Counting objects: 100% (430/430), done.        
remote: Compressing objects: 100% (210/210), done.        
remote: Total 21839 (delta 255), reused 347 (delta 209), pack-reused 21409        
Receiving objects: 100% (21839/21839), 6.08 MiB | 0 bytes/s, done.
Resolving deltas: 100% (13265/13265), done.
fatal: Couldn't find remote ref renovate/react-16.x
Exited with code 128
```

**To Reproduce**
I cant find.

**Expected behavior**
1. Renovate automerging always work after all ci status were green.

**Screenshots**

This is status when Renovate merged its PR
![screencapture-github-pull-577-2018-11-12-09_58_57](https://user-images.githubusercontent.com/40752460/48320965-37abf580-e662-11e8-9d3e-7693c70ca782.png)

**Additional context**
renovate.json
```json
{
  "extends": [
    "config:base"
  ],
  "automerge": true,
  "major": {
    "automerge": false
  }
}
```

This renovate behavior broke our master branch.
If this is renovate collect behavior, we can't use automerge option 😢

**Comment by rarkins** [comment]
It's important that you configure GitHub branch protection before enabling automerge. Your `master` branch protection should include all tests you need to pass before merging. I will show you how:

1. Visit https://github.com/<owner>/<repo>/settings/branches

Add one for `master`.

![image](https://user-images.githubusercontent.com/6311784/48331376-3376dc80-e650-11e8-94cf-fd7090ed59cf.png)

2. Enable "Require status checks to pass before merging" and select CircleCI:

![image](https://user-images.githubusercontent.com/6311784/48331441-66b96b80-e650-11e8-9efa-f6aa3f157be3.png)


If you let me know the repository name then I can look at the debug logs for when this happened to have a look at well. Normally you can access them yourself via https://renovatebot.com/dashboard for the last 3 days.

**Comment by HiroshiOHSUGA** [comment]
it seems work well.
thank you!
