### ISSUE TITLE
Bazel: Support commit-based go_repository

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2806]
_Originally posted by @prestonvanloon in https://github.com/renovatebot/renovate/issues/2733#issuecomment-437835935_

**Comment by rarkins** [comment]
@prestonvanloon I think this might require an additional enhancement so raising this as a new issue for @kayoub5 to comment on

**Comment by kayoub5** [comment]
@rarkins 
From https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository
`commit` and `tag` may not both be set, this means if you have a commit, you don't have a version.

**Comment by rarkins** [comment]
@kayoub5 I think @prestonvanloon has in mind cases with only commits because the source repository doesn't yet support go module versions. In the `gomod`  manager we treat these as "digests" that need updating.

**Comment by prestonvanloon** [comment]
Yes exactly. I'm thinking of the following dependency: 
```python
go_repository(
   name = "com_github_google_uuid",
   importpath = "github.com/google/uuid",
   commit = "dec09d789f3dba190787f8b4454c7d3c936fed9e"
)
```
Thanks!

**Comment by prestonvanloon** [comment]
Thanks!

**Comment by rohansingh** [comment]
It would be nice to have this mentioned in the Bazel docs:
https://renovatebot.com/docs/bazel/
