### ISSUE TITLE
Cache more (all) GitHub repo endpoints

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28098]
### Describe the proposed change(s).

We should add etag/last-modified repository caching of all remaining repo-based `githubApi.getJson()` calls. The ones missing are in:
- findPr()
- getStatus() - statuses and check runs, has the biggest gain
- getComments()

However before we enable this, we need to introduce the concept of cleanup, otherwise we'll have the http cache grow indefinitely and maintain histories of every past PR status check in particular. Knowing exactly which cache items are still used and which are expired after every run might be challenging to get correct? For example I'm not sure if sometimes we skip status checks on a branch during a run if it's not in schedule, but we'll check them again on a later run. In such cases we wouldn't want to expunge the cached lookup just because we didn't use them in a run.

Also we want to avoid using a "last accessed date" field otherwise we'll need to update the cache after every run, which is itself not ideal.

**Comment by viceice** [comment]
status checks are tricky, because they're commit dependent and can change at any time from anywhere

**Comment by rarkins** [comment]
Right, as soon as a new commit is done to a branch, the previous ones won't be relevant to us.

Another possibility - requires more code - is to make the results caching in the platform/github or even application layer, where we be more aware about brandch -> commit
mapping.

However in the short term, I found that simple caching saved a lot of API queries whenever a repo had open branches without a change in commit.

**Comment by viceice** [comment]
sure, but how to collect status changes happening after we cached them? do you plan to use etag or last modified header usage?

**Comment by rarkins** [comment]
I edited the original description to make it clear I mean etag/last-modified caching

**Comment by rarkins** [comment]
The cleanup part is challenging because this is low-level HTTP caching based on URLs.

Well need:
- Ability to iterate through all cached URLs
- Filter based on patterns (e.g. PR comments, or branch status checks)
- Extract from each result the PR number or branch name
- Match the list against the list of open branches
- Delete any which don't belong to open branches

**Comment by zharinov** [comment]
Why not to make 90 days of TTL for records and erase older records based on `timestamp` field?
