### ISSUE TITLE
Renovate bump beta dependency incorrectly

### ISSUE THREAD

**Issue by aldarund** [renovatebot/renovate#2809]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
https://github.com/nuxt/nuxt.js/pull/4310
`    "eslint-plugin-vue": "^5.0.0-beta",
`
instead of
`"eslint-plugin-vue": "^5.0.0-beta.4",`

**Expected behavior**
    "eslint-plugin-vue": "^5.0.0-beta.4",

**Comment by rarkins** [comment]
This is now fixed, thanks.

**Comment by aldarund** [comment]
@rarkins that was fast ;) thanks
