### ISSUE TITLE
Composer: Support github repositories lookup

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2813]
Example: https://github.com/modularsoftware/estate-agent/blob/e3b375b865bb7db6a6a092ff18a6d2c5b2e8eade/composer.json#L38-L41

**Comment by rarkins** [comment]
A “hit” in the repo should stop us from looking up additional registries.

**Comment by evilebottnawi** [comment]
@rarkins can you provide information/place where i should start/examples/etc how i can help to solve this issue?

**Comment by PhilipAbed** [comment]
is this task still relevant?
