### ISSUE TITLE
Squash merge on Gitlab

### ISSUE THREAD

**Issue by mxey** [renovatebot/renovate#2815]
**What would you like Renovate to be able to do?**

Gitlab supports squashing when merging MRs. I would like Renovate to optionally use that feature.

**Describe the solution you'd like**

When creating an MR, enable the squash option

**Describe alternatives you've considered**

* automergeType=branch is only supported on GitHub. Also it would bypass Gitlab's MR logic.

**Additional context**

* https://docs.gitlab.com/ce/user/project/merge_requests/squash_and_merge.html#enabling-squash-for-a-merge-request

**Comment by rarkins** [comment]
> automergeType=branch is only supported on GitHub. Also it would bypass Gitlab's MR logic.

FYI `mergeBranch` is actually supported already

> Gitlab supports squashing when merging MRs. I would like Renovate to optionally use that feature.

Renovate only ever creates one commit per branch. If it needs changes, it "rebases". And if you add any commits of your own, then Renovate won't automerge. So in that case, the only time Renovate ever merges is when there's 1 commit to merge. Is there still any reason for squashing?

**Comment by rarkins** [comment]
So is setting merge type of squash something we can do *without* actually merging? Ie for a human to accept / merge

**Comment by mxey** [comment]
[Yes, you can set the `squash` boolean on an MR](https://docs.gitlab.com/ce/api/merge_requests.html#update-mr)

**Comment by mxey** [comment]
I just was told that GitLab‘s squash works differently from Git‘s squash merge. It will squash all the commits together and then do a merge with an explicit merge commit. So there will always be two commits anyway and I cannot influence the message of one like that :/
