### ISSUE TITLE
Bazel: go_repository remote not used

### ISSUE THREAD

**Issue by prestonvanloon** [renovatebot/renovate#2832]
**What Renovate type are you using?**
Github App

**Describe the bug**
Renovate is fetching the `importpath` repository rather than the explicit `remote` repository in the go_repository rule

**Did you see anything helpful in debug logs?**
Yes, debug logs validate my suspicion https://renovatebot.com/dashboard#github/prysmaticlabs/prysm/28753154

**To Reproduce**
See this PR: https://github.com/prysmaticlabs/prysm/pull/757

See this style of dependency

```
go_repository(
    name = "com_github_ethereum_go_ethereum",
    importpath = "github.com/ethereum/go-ethereum",
    remote = "https://github.com/prysmaticlabs/bazel-go-ethereum",
    vcs = "git",
    commit = "f4b3f83362a4cf2928e57914af040aea76c8a7d6",
)
```

**Expected behavior**

Renovate reads github.com/prysmaticlabs/bazel-go-ethereum to fetch the latest digest.

**Comment by rarkins** [comment]
Looks like we need to modify the current logic to:

1. Check if a go_repository has field "remote"
2. If it's "plain" github one like https://github.com/foo/bar then we use that in the `purl`
3. If it's not plain, we add skipReason='unsupported-remote'
