### ISSUE TITLE
Support setup.py with nested references

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2833]
`setup.py` Renovation is now in beta.

[This setup.py](https://github.com/renovate-tests/quart-openapi/blob/4fb9d6ce726f57ef9b440fefa6da8afc853b4e68/setup.py#L51-L54) contains references to `requirements/*.pip` files in the same repo.

When using non-gitFs, this results in a hard fail of parsing `setup.py`. Using gitFs=https, it's a soft fail: no dependencies detected.

If I instead configure like so:
```
  "pip_requirements": {
    "fileMatch": ["requirements/*"]
},
```

Then these .pip files are detected as `pip_requirements` files and an upgrade is found.

Questions for @hutson:

1. Do you think it's common for `setup.py` to include external requirements like this?
2. Was this only done so that you could treat them as `requirements.txt` files?
3. Do you think it's likely anyone would externalise `setup.py` files and *not* have them in pip requirements format?
4. Do you think Renovate should look for *.pip files by default?

**Comment by hutson** [comment]
I believe the configuration suggestion is good enough for our use case.

1. I have not seen this approach before, but I have heard it's used elsewhere.
2. The approach was taken to keep setup and maintenance of the files simple.
3. I don't know.
4. In our case, no. The suggested configuration should be fine for our use case.

**Comment by rarkins** [comment]
For now, we will support just versions contained within the `setup.py`. If someone has a real use case you think deserves support and you find this issue, please explain more about it below.
