### ISSUE TITLE
gitlabci manager: support multidoc yaml

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28416]
### Discussed in https://github.com/renovatebot/renovate/discussions/28386

<div type='discussions-op-text'>

<sup>Originally posted by **benedikt-bartscher** April 13, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Gitlab - Renovate 37.291.0

### Please tell us more about your question or problem

With gitlabs new CI Components gitlab-ci files can be multidocument yaml ([docs](https://docs.gitlab.com/ee/ci/yaml/inputs.html#define-input-parameters-with-specinputs)). Renovate currently fails parsing multidocument gitlab-ci files.  

Something like https://github.com/renovatebot/renovate/pull/8828/files is needed

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: YAML exception extracting GitLab CI includes (repository=senbax/gitlabci/docker, packageFile=templates/docker.yml)
       "err": {
         "name": "YAMLException",
         "reason": "expected a single document in the stream, but found more",
         "message": "expected a single document in the stream, but found more",
         "stack": "YAMLException: expected a single document in the stream, but found more\n    at load (/usr/local/renovate/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/lib/loader.js:1722:9)\n    at parseSingleYaml (/usr/local/renovate/lib/util/yaml.ts:65:29)\n    at Object.extractPackageFile (/usr/local/renovate/lib/modules/manager/gitlabci-include/extract.ts:75:32)\n    at extractPackageFile (/usr/local/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/usr/local/renovate/lib/workers/repository/extract/manager-files.ts:45:43)\n    at /usr/local/renovate/lib/workers/repository/extract/index.ts:57:28\n    at async Promise.all (index 1)\n    at extractAllDependencies (/usr/local/renovate/lib/workers/repository/extract/index.ts:54:26)\n    at extract (/usr/local/renovate/lib/workers/repository/process/extract-update.ts:140:28)\n    at extractDependencies (/usr/local/renovate/lib/workers/repository/process/index.ts:154:26)\n    at Object.renovateRepository (/usr/local/renovate/lib/workers/repository/index.ts:69:9)\n    at attributes.repository (/usr/local/renovate/lib/workers/global/index.ts:217:11)\n    at start (/usr/local/renovate/lib/workers/global/index.ts:202:7)\n    at /usr/local/renovate/lib/renovate.ts:18:22"
       }

```

</details>
</div>

**Comment by rarkins** [comment]
Reproduction: https://github.com/renovate-reproductions/28416

**Comment by RahulGautamSingh** [comment]
I think this should be a feature since we are expanding to support multidoc?

**Comment by rarkins** [comment]
Good point, if Gitlab add multidoc then it's a feature for us to support it too
