### ISSUE TITLE
incorrect links for python coverage

### ISSUE THREAD

**Issue by Fandekasp** [renovatebot/renovate#2846]
![](https://i.imgur.com/FLE4Nkj.png)

Link provided to homepage is https://bitbucket.org/ned/coveragepy, but in said link, we can read

> Development of coverage.py has moved to GitHub.

Proper link is: https://github.com/nedbat/coveragepy/

And the changelogs are at https://github.com/nedbat/coveragepy/blob/master/CHANGES.rst

**Comment by Fandekasp** [comment]
The changelogs link is confusing. Found a better link with details regarding that v4.5.2 release at https://coverage.readthedocs.io/en/v4.5.x/changes.html

**Comment by rarkins** [comment]
FYI @Fandekasp 	I have centralized all the "manual" changelog/source repo overrides into lib/datasource/index.js.
