### ISSUE TITLE
Support source and changelog links for sbt manager in the same way as for maven manager

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28491]
### Discussed in https://github.com/renovatebot/renovate/discussions/28422

<div type='discussions-op-text'>

<sup>Originally posted by **gaeljw** April 15, 2024</sup>
### Tell us more.

I just noticed a small difference of behaviour between sbt and maven managers when it comes to extracting source code and changelog.

Example for Maven:

| Description | Diff |
|--------|--------|
| ![image](https://github.com/renovatebot/renovate/assets/18280708/b23f6138-3908-4554-bd9e-7d92dbd639c0) | ![image](https://github.com/renovatebot/renovate/assets/18280708/24d283a9-3f6e-4b03-a0dd-a57329f44b09) | 

Example for sbt:

| Description | Diff |
|--------|--------|
| ![image](https://github.com/renovatebot/renovate/assets/18280708/3bfcc884-923b-423b-9907-c6cda12fbe90) | ![image](https://github.com/renovatebot/renovate/assets/18280708/749a0ad0-4d62-4461-9cc1-d6f2a19fbd1d) |

Notice the "source" and "changelog" links are *not* present for sbt.

As sbt and maven share the same datasource (in this case at least, = maven registry), I guess sbt manager could extract the info in the same way as the maven manager does, right?</div>

Reproduction forked to https://github.com/renovate-reproductions/28490

**Comment by gaeljw** [comment]
Any specific reason for closing it @rarkins ? I might give it a look if not too complex.

**Comment by rarkins** [comment]
Duplicate of #28490

**Comment by rarkins** [comment]
Please see #28490 instead
