### ISSUE TITLE
Go: Tag has to be prefixed with v

### ISSUE THREAD

**Issue by mxey** [renovatebot/renovate#2850]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate suggests Go dependency updates that the Go tooling does not understand. Renovate treats all Git tags of a dependency as releases, but Go requires that the tags are prefixed with `v`. 

**Did you see anything helpful in debug logs?**

No.

**To Reproduce**

1.  Create repository like https://github.com/mxey/renovate-gomod-tag-reproduction
2. Run Renovate against it

**Expected behavior**

Renovate does not suggest updates that are not recognized by the Go tool, by limiting the tags to those prefixed with `v` 

**Additional context**
* https://github.com/golang/go/wiki/Modules#modules

**Comment by rarkins** [comment]
Thank you for the reproduction steps. I think I’ll create a new variant of versioning/semver for the Go variant with this particular rule

**Comment by rarkins** [comment]
Very good idea. I forgot that we now put all Go lookups through a dedicated go datasource so it would also be logically correct to filter there too.
