### ISSUE TITLE
Throw config validation error if combining * with other values in a matchRegexOrGlobList field

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28554]
### Describe the proposed change(s).

Using `matchRepositories` as an example, we should throw a config validation error if the user configures `*` or `**` patterns with any other value.

e.g. these are all not ok:

```
  "matchRepositories": ["*", "!abc/def"]
  "matchRepositories": ["*", "x/y", "!abc/def"]
  "matchRepositories": ["*", "x/y"]
  "matchRepositories": ["*", "**"]
```

We should keep a list of config options/fields which support matchRegexOrGlob - it will increase over time. I think so far it's `allowedHeaders`, `allowedEnvVars`, `autodiscoverProjects` and `matchRepositories`.

**Comment by viceice** [comment]
we can add a new property to the options to mark them, that way we can also easily update the docs 🤗

**Comment by RahulGautamSingh** [comment]
> we can add a new property to the options to mark them, that way we can also easily update the docs 🤗

Name suggestion: `regexOrGlobMatchingSupported` and it will be boolean

**Comment by rarkins** [comment]
`regexOrGlob: true` is perhaps enough
