### ISSUE TITLE
Allow wildcards in ignoreDeps

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#2869]
**What would you like Renovate to be able to do?**
Allow the user to add a wildcard in the `ignoreDeps` configuration option, this will then allow excluding packages with similar names.

**Describe the solution you'd like**
An example: `laravel/*` to exclude all dependency updates for any Laravel packages.

**Describe alternatives you've considered**
Adding each and every Laravel package manually, which is a bit annoying.

**Additional context**

**Comment by rarkins** [comment]
As a workaround in the meantime, you can do this:

```json
{
  "packageRules": [{
		"packagePatterns": ["^laravel/"],
		"enabled": false
  }]
}
```

Otherwise I suppose we should be pretty safe to assume no packages (across all managers) will contain `*` in their name. The question is whether it means 0 or more or 1 or more. If converting a string like 'abc*foo' would you match 'abcfoo' yes/no?

**Comment by rarkins** [comment]
Maybe we can do like this: if the string contains an asterisk then we treat it as a glob and use glob matching instead of exact string matching.

**Comment by Jamesking56** [comment]
I would say most `laravel` or `illuminate` vendor packages will not need to be updated by Renovate (except maybe patch updates).

Why I say no to the 0 or more is because there is bound to be someone who wants to update `vendor/package-sub` but not `vendor/package`. At least by writing it as 1 or more they can be explicit.

**Comment by rarkins** [comment]
Package rules is a much lengthier approach for simple ignoring by package name. I worry we’d be making config too complex “by default” rather than complex “if necessary”

**Comment by Jamesking56** [comment]
Maybe instead we make `ignoreDeps` a shorter alias which Renovate expands into `packageRules` when processing?

Then we can use the same wildcarding as seen in the `packagePatterns`.

Like:

```json
{
  "ignoreDeps": ["^laravel/"]
}
```

Expands to:

```json
{
  "packageRules": [{
    "packagePatterns": ["^laravel/"],
    "enabled": false
  }]
}
```

**Comment by rarkins** [comment]
For now I’m going to stick with the current approach. The problem with overloading ignoreDeps to allow regex is that you can never be sure if the user intended a package name as an exact match or as a regex match. We could search for special characters but then it’s hacky to explain.
