### ISSUE TITLE
Gitlab interprets @ in issues

### ISSUE THREAD

**Issue by Morton** [renovatebot/renovate#2870]
**What Renovate type are you using?**
Renovate CLI in Docker (renovate/renovate)

**Describe the bug**
Renovatebot does not escape @ when posting issues to Gitlab. Gitlab will interpret this as mentioning someone and will notifies the person or group of persons. This is an issues as many npm-packages are namespace and therefor prefix with an @.

Example: Let's say I have an application called _Wooble_. My apps shared-lib's name will be _@wooble/shared-lib_ . My Gitlab's group will be _wooble_ with the projects _webapp_ and _shared-lib_. Apart from me 30 more colleagues have access to the group in Gitlab. Assuming Renovatebot will run on _webapp_ and create an issue for _**@wooble**/shared-lib_, Gitlab will interpret **@wooble** as mentioning the Gitlab-group and puts everyone in that group as issue participants. Hence everyone will receive mails for this issue.

**Did you see anything helpful in debug logs?**
No, but I guess that's not important in that case.

**To Reproduce**

1.  Find a repository in Gitlab within a group.
2. Open renovate-config and add custom preset with your group's name (like: @group:name).
3. As this preset does not exist, Renovatebot will create an issue mentioning the package-name (with the @ making Gitlab adding the whole, group to the issue.)

**Expected behavior**
For no-one to get a mail.

I can create a PR later this week but maybe someone can agree for this to be a bug and point me into the best direction to fix. Thanks!

**Comment by rarkins** [comment]
Thanks for raising this issue. We already have code for escaping @'s in Pull Request bodies, so probably all we need to do is reuse the same code/escaping for any issues we create too. GitHub is probably impacted by the same problem - i.e. not just GitLab.

The code for PRs is here: https://github.com/renovatebot/renovate/blob/c80f1475332cea40040f8bdd3d38995aeb5d3a37/lib/workers/pr/pr-body.js#L163-L176

It could probably be put into a new file/function inside `lib/util/` and then referenced both from the PR worker as well as when creating an Issue for configuration errors, which I think is here: https://github.com/renovatebot/renovate/blob/1b935db8adc2d7842dfaae01c21c4ae0744c798d/lib/workers/repository/error-config.js#L24

There may be other cases where `ensureIssue()` is called.

One other option might be just to wrap the text on this line with backticks: https://github.com/renovatebot/renovate/blob/1b935db8adc2d7842dfaae01c21c4ae0744c798d/lib/workers/repository/error-config.js#L13
