### ISSUE TITLE
Add "ignore: true" option?

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2871]
Reading this article from @zephraph: http://artsy.github.io/blog/2018/11/26/keeping-dependencies-updated/

It got me thinking that we lean on `"enabled": false` quite a bit, especially in package rules. Would it be a *good* idea to introduce a little syntactic "sugar" of an `"ignore": true` option that means exactly the same as '"enabled": false`?

On one hand it can be "cluttering" to duplicate a config but on the other hand it's an important concept and can be better if the rules "read" more simply to users.

Thoughts, @hutson?

**Comment by zephraph** [comment]
I think only having the single flag would be better for simplicity. Renovate already has a lot of features and that'd just be one more thing to document and one more difference between people's configs. 

I think something that would be more helpful is just having a set of small, concrete examples of how to do certain things. My blog post kind of shows how to only update packages in a certain namespace (while disabling everything else). Another example grouping things like all of react's dependencies into a single PR would be good. Just things like that so it's a little clearer to people how to acheive certain things. The docs are pretty good, but it'd just add another angle that people could look at it to understand things a little easier.

**Comment by rarkins** [comment]
Ok so maybe a little “cookbook” containing examples and also explaining why the example works, if it’s not obvious

**Comment by zephraph** [comment]
Yep! Once I understood that I had to create a package rule that ignored everything except the files that I wanted to update it was pretty straight forward. It just took a bit to fully see how everything pieced together.
