### ISSUE TITLE
Show preview of changes on PR of config change

### ISSUE THREAD

**Issue by zephraph** [renovatebot/renovate#2879]
**What would you like Renovate to be able to do?**
I'd like to know what actions Renovate will make when I alter a config in a PR _before_ merging the PR. 

**Describe the solution you'd like**
Think of this as kind of a version of the on-boarding issue, but when migrating. You make a change to the `renovate.json` and renovate adds a comment to the PR detailing what new things will be changed/updated. 

This'll give us the ability to preview changes without actually merging them and potentially causing a number of PRs to be created that we didn't actually want.

**Comment by rarkins** [comment]
Can you confirm if #547 would satisfy your requirements?

**Comment by zephraph** [comment]
Yep. I'll close this in favor of #547.
