### ISSUE TITLE
migration.js running forever with schedule migration

### ISSUE THREAD

**Issue by dylang** [renovatebot/renovate#2880]
**What Renovate type are you using?**

```
"renovate": "13.136.4"
```

**Describe the bug**

Looks like it locks up forever, but by debugging app found that `migration.js` is running forever, growing the `schedule` by one line each time.

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

No debug logs, I think because this is in config stage before logging has been enabled.

**To Reproduce**

```
    schedule: [
        'every weekday after 10pm and before 8am',
    ],
```

```
RENOVATE_CONFIG_FILE=renovate.js GITHUB_API_TOKEN=test yarn run renovate --log-level=debug
```

(note: `--log-level=debug` does nothing to help understand the problem)

**Expected behavior**

Migrate or return an error that the format is incorrect.

**Screenshots**

**Additional context**

As always, thanks for your great work on this!

**Comment by dylang** [comment]
Workaround: changing the config to this seems to work.

```
schedule: [
        'every weekday after 10pm',
		'every weekday before 8am'
    ],
```

**Comment by rarkins** [comment]
@dylang thanks for debugging this! Do you know if this is a regression error that got introduced at some time, i.e. after an upgrade? Or did you add the schedule recently and then experienced the problem?

**Comment by dylang** [comment]
This is the PR where it failed, and I probably waited a few weeks to see if it would "fix itself" :)

| Package | Type | Update | Change | References |
|---|---|---|---|---|
| renovate | dependencies | minor | `13.127.2` -> `13.136.4` | [homepage](https://renovatebot.com), [source](https://github.com/renovatebot/renovate) |

**Comment by rarkins** [comment]
Thanks, I'll try to reproduce, fix and hopefully figure out the root cause based on git blame (which is 100% sure to be me if it's in the migration code).
