### ISSUE TITLE
No initial PR 

### ISSUE THREAD

**Issue by chrisforrette** [renovatebot/renovate#2882]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
My work has a private GitHub organization and we just added Renovate to a couple repos (only one is currently configured) this morning and no initial PR was ever created. I can see the repos listed in https://renovatebot.com/dashboard, but there are no logs for them at all.

**Did you see anything helpful in debug logs?**
Logs are not coming through for the repo(s).

**To Reproduce**
Not sure, it might happen when adding Renovate to a repo belonging to a private org that you belong to when you've already added Renovate to other of your own repos..?

**Expected behavior**
An initial configuration PR to be opened for each repo I have configured, and also logs displaying in my dashboard about them.

**Screenshots**
N/A

**Additional context**
I suspect this might be a permissions issue—yesterday I set up Renovate on a personal project in my own account, and today another user on my team added it to the GitHub org. I had been actively receiving PRs updating dependencies on my personal project and they seem to have stopped after we added this private GitHub organization.

Additionally, we have a few JS packages installed from other GitHub repos that we did not yet add to Renovate, and we also have some private NPM packages but we did grant read access to `renovate` on our private NPM org.

**Comment by rarkins** [comment]
Hi Chris, I’ll take a look soon and give it a kick if possible.

**Comment by chrisforrette** [comment]
@rarkins Thanks!

**Comment by rarkins** [comment]
@chrisforrette I manually enqueued your personal private repo just now and I think it should happily run approximately hourly after that, or any time a relevant webhook is detected. It seems it just fell off the queue somehow but would have been picked up a little later in a daily sweep.

For the githug org, I am not 100% certain which one is yours but the one I suspect it to be looks like it got renamed after it was installed. You could try uninstalling then reinstalling the app, or email support@renovatebot.com to confirm the org name confidentially.

**Comment by chrisforrette** [comment]
@rarkins Great! So my personal account is working again, but I just tried uninstalling and re-installing Renovate in my GitHub org and nothing seems to have happened. I'll send you an email now with the org name.

**Comment by rarkins** [comment]
Now resolved via email, the org is activated and the private repos seem to be looked up fine.
