### ISSUE TITLE
Document sourceUrl and releaseTimestamp support in datasources

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28947]
### Describe the proposed change(s).

Extend https://github.com/renovatebot/renovate/blob/5de7eee2b3f7011397ea273d1289933c343da9cb/lib/modules/datasource/types.ts#L111-L114

To be like:

```
  /**
   * Whether custom registryUrls are allowed.
   */
  customRegistrySupport: boolean;

  /**
   * Whether release timestamps can be returned.
   */
   releaseTimestampSupport: boolean;
   releaseTimeStampNote?: string;

  /**
   * Whether sourceURLs can be returned.
   */
   sourceUrlSupport: 'package' | 'release' | 'none';
   sourceUrlNote?: string;
```

`releaseTimestampSupport` should be `true` if the datasources looks for release.releaseTimestamp

`sourceUrlSupport` should be `release` if the datasource supports returning them per-release (e.g. npm), `package` if they can be returned but only per-package (e.g. cdnjs), or `none` if no `sourceUrl` logic exists.

The optional note fields should ideally be filled into clarify how the field is determined. e.g in both npm and cdnjs, it's from the `repository` value in the results. Can we possibly use types to make these note fields _mandatory_ if their sibling field is set?

**Comment by rarkins** [comment]
In addition to the work above, please create any necessary GitHub issues to _add_ releaseTimestamp or sourceUrl support for any particular datasources which are missing them but for which we think it should be possible.

**Comment by HonkingGoose** [comment]
> The optional note fields should ideally be filled into clarify how the field is determined. e.g in both npm and cdnjs, it's from the `repository` value in the results. Can we possibly use types to make these note fields _mandatory_ if their sibling field is set?

This sounds like the `description` field in the Renovate presets. 🙂

I don't know if you can make the `note` field mandatory with TypeScript. You can probably write a test to check if the `note` is filled in when the sibling field is set.

**Comment by RahulGautamSingh** [comment]
In some cases, for eg. `bitbucket-tags` we determine the `sourceUrl` by combining `registryUrl` and `packageName`. Both of these values are already available to us, and aren't extracted from the response. 
Which kind of `sourceUrlSupport` does it come under then?

**Comment by rarkins** [comment]
In that case, true

**Comment by RahulGautamSingh** [comment]
> sourceUrlSupport: 'package' | 'release' | 'none';

sourceUrlSupport: 'package' | 'release' | 'none' | 'true' ??

**Comment by rarkins** [comment]
Corrected to "package". i.e the sourceUrl is returned per package and we don't the concept of sourceUrl per-release

**Comment by RahulGautamSingh** [comment]
What should be done when `getDigest` supportes `releaseTimestamp` but `getRelease` does not?
For eg. 
`conan` results have the `time` field in its results for the `getDigest` api call but not in the results of the api call performed in `getReleases`.

**Comment by rarkins** [comment]
I'm not sure we use the timestamp for digests. I'd consider that support false if it's not per-release
