### ISSUE TITLE
 Retry GitLab API requests on HTTP 409 Resource lock errors

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#29006]
### Describe the proposed change(s).

I'm creating this issue based on a comment from @fgreinacher in discussion #28972. I edited the comment for readability.

The GitLab API may return `HTTP 409 Resource lock` in cases where an internal DB lock fails to be acquired in time, see:

- https://gitlab.com/gitlab-org/gitlab/-/blob/443c12cf3b238385db728f03b2cdbb4f17c70292/lib/api/api.rb#L111

Those errors are usually transient and a retry is therefore worthwhile.

For example, the `python-gitlab` library added special handling for this in [python-gitlab/python-gitlab#2326](https://github.com/python-gitlab/python-gitlab/pull/2326).

We should add similar logic to Renovate's GitLab layer.

**Comment by HonkingGoose** [comment]
@fgreinacher, if you want you can assign yourself to this issue. Or ask me to assign you, if you can not assign yourself due to permissions.

If you do _not_ want to work on this, let me know too. :wink:

**Comment by fgreinacher** [comment]
> @fgreinacher, if you want you can assign yourself to this issue. Or ask me to assign you, if you can not assign yourself due to permissions.

Sure, thanks for creating the issue @HonkingGoose 👍 Please assign it to me.
