### ISSUE TITLE
Use package's org config if present

### ISSUE THREAD

**Issue by manniL** [renovatebot/renovate#2901]
**What would you like Renovate to be able to do?**

When initializing renovate via PR, Renovate could check (through the package.json) which scope/org will be used to publish that package. If there is a renovate config preset from that org, it could be used directly in the PR.

Example: 
* https://github.com/nuxt-community/moment-module/pull/7

* Package.json shows it'll be published under `@nuxtjs` (https://github.com/nuxt-community/moment-module/blob/master/package.json#L2)

* Is there a package called `@nuxtjs/renovate-config`? Yes! https://www.npmjs.com/package/@nuxtjs/renovate-config

* Use that preset in the PR

**Comment by rarkins** [comment]
I think this could maybe be used to determine the default onboarding config in the "Configure Renovate" PRs - is that what you mean?

**Comment by manniL** [comment]
Yup, that's exactly what I mean! ☺️

**Comment by rarkins** [comment]
So:

- Whenever onboarding a repository, check for a `package.json` in the root of the repo
- Check for the `name` value if exists
- If the name has a scope, e.g. `@nuxtjs`, then check if `@nuxtjs/renovate-config` exists
- If it does, then set the default `renovate.json` to be `{"extends": ["@nuxtjs"]}`

**Comment by rarkins** [comment]
By the way, we support github-hosted preset, e.g. `github>nuxtjs/renovate-config`. So that might be a more flexible approach that also supports non-npm repositories too.

**Comment by rarkins** [comment]
This is supported today for repository-based presets
