### ISSUE TITLE
Bazel: support commit-based http_archive

### ISSUE THREAD

**Issue by dicarlo2** [renovatebot/renovate#2904]
**What would you like Renovate to be able to do?**

I'd like Renovate to automatically update my bazel dependencies (`http_archive`, specifically) when they are based on commits (i.e. renovate would keep it pinned to head).

**Describe the solution you'd like**

Given

```
http_archive(
    name="<repository>",
    sha256="<sha256>",
    strip_prefix="<repo>-<commit>",
    urls=["https://github.com/<org>/<repo>/archive/<commit>.tar.gz"],
)
```

Keep `<commit>` and `<sha256>` up to date for the given `<org>/<repo>`.

**Describe alternatives you've considered**

Sticking with the tagged releases. Some of the bazel repos move at fairly quick pace and are under active development where the release cadence doesn't necessarily keep up. As a result, frequently features that are blocking our workflow have not been officially tagged and released, but we want to go ahead and use them anyways.

**Additional context**

n/a

**Comment by rarkins** [comment]
Thanks for the suggestion @dicarlo2. Is it possible for you to also add a real-life example you're using, that I can use in testing?

**Comment by dicarlo2** [comment]
Here's two that we're using now:
```
http_archive(
    name="io_bazel_rules_docker",
    sha256="c00ae13bf3132bf532db49faee61ebc4b5c2e30af7b255bcf802e6e962941573",
    strip_prefix="rules_docker-9527234ef0b5a57bce93be524cb56d7ab1a85ea3",
    urls=["https://github.com/bazelbuild/rules_docker/archive/9527234ef0b5a57bce93be524cb56d7ab1a85ea3.zip"],
)

http_archive(
    name="distroless",
    sha256="ab4369d727965ccc6e685c29669922b7d6cba92d8314ea39e99610eeb67b0042",
    strip_prefix="distroless-446923c3756ceeaa75888f52fcbdd48bb314fbf8",
    urls=["https://github.com/GoogleContainerTools/distroless/archive/446923c3756ceeaa75888f52fcbdd48bb314fbf8.zip"]
)
```

**Comment by rarkins** [comment]
We can start by supporting the case where `urls` is of length 1 and has the format described - `https://github.com/<org>/<repo>/archive/<commit>.tar.gz` with a matching `strip-prefix`. If so then we look for the latest commit from the repo and update the strip_prefix, urls, and sha256 fields.

**Comment by alex1545** [comment]
Hi @rarkins,
I'm also very interested in this and thank you for approving this feature request.
Do you have a time estimate of when this could be completed? Is this work in progress or the implementation work for this wasn't started yet?

**Comment by rarkins** [comment]
@alex1545 hasn’t started yet. If you subscribe to the issue then you’ll hopefully see once the “ready” label shifts to “in progress”.

**Comment by rarkins** [comment]
First step is to get the extract function detecting and extracting this commit-based http_archive dep.

Second step is to check if the lookup function successfully returns a new commit hash as we expect.

Final step is to enhance the update function to support the commit-based http_archive update and to retrieve/insert the sha256 too.

**Comment by alex1545** [comment]
Hi @rarkins,
I just wanted to check back on the status of this as I noticed that @Dmitry9 was assigned to this issue. Does this mean that it's a WIP now? And do you have any rough estimates as of when this feature could land?

**Comment by rarkins** [comment]
I'm not sure if @Dmitry9 has started implementation yet but I know he took a look at it so I'll update it to in progress

**Comment by Dmitry9** [comment]
@rarkins `For now, please just upload the extract part for review and we can discuss on GitHub from there.`
The `extract` part can be viewed [here](https://github.com/Dmitry9/renovate/pull/1/files). I am unable to push to upstream.

**Comment by rarkins** [comment]
@Dmitry9 I prefer you don’t do a large refactor as part of a feature addition though. Best is to separate the refactor into a separate PR so that it can be tested and checked manually before the feature addition is added as a separate commit. 

Although the existing code is messy, is it really necessary to refactor for this feature? I hasn’t expected the extract function to take much work.

**Comment by Dmitry9** [comment]
@rarkins You are correct. It is never really necessary to refactor the code. I will keep it as it is in the future. But if -> else if -> else if beauty will grow. So should I replace it into a single file as it was?

**Comment by rarkins** [comment]
I’m happy if you would like to refactor it into more functions or files first and maintain backwards compatibility. Then let’s add the new feature after.

**Comment by Dmitry9** [comment]
Sure. I meant this object to hold all known depTypes specific logic. Of course backwards compatibility will not suffer.
![update](https://user-images.githubusercontent.com/22542906/53435204-f7019d80-3a00-11e9-9830-52bf0b46b984.png)

**Comment by Dmitry9** [comment]
@rarkins can you please take a look?
[Here](https://github.com/renovatebot/renovate/compare/master...Dmitry9:Feat%232904/bazel-commit-based-http-archive-no-refactor) I extracted dependency definition
In lib/workers/branch/index.js:204 now it cannot create branch for the commit.
![newdigest](https://user-images.githubusercontent.com/22542906/53651264-efcfcf00-3c4e-11e9-8ede-aca8ca6f8432.png)
![lastcommit](https://user-images.githubusercontent.com/22542906/53651300-06762600-3c4f-11e9-9692-bac76069f62c.png)

**Comment by rarkins** [comment]
@Dmitry9 can you raise this as a Draft Pull Request please? That way I can properly review it

We shouldn't have manager-specific code in the generic lookup function so need a better way to achieve whatever it is you need

**Comment by Dmitry9** [comment]
@rarkins  here is [Draft PR](https://github.com/renovatebot/renovate/pull/3295).

**Comment by dicarlo2** [comment]
@rarkins @Dmitry9 just saw this in my notifications - great work, thanks for adding this!
