### ISSUE TITLE
refactor raiseDeprecationWarnings into suppressNotifications

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2909]
Remove this option: https://github.com/renovatebot/renovate/blob/32554a9db6e3f402ded7e9b0f23644805cb70f0d/lib/config/definitions.js#L1305-L1311

Instead, replace it with a new value "deprecationWarningIssues" inside "suppressNotifications".

There will also need to be a rule added to https://github.com/renovatebot/renovate/blob/master/lib/config/migration.js that:

- deletes `raiseDeprecationWarnings` if found
- adds "deprecationWarningIssues" to the `suppressNotifications` array if the user set raiseDeprecationWarnings=false

**Comment by tuckbick** [comment]
How does one remove `deprecationWarningIssues` from `suppressNotifications[]` if it's always being set?

**Comment by rarkins** [comment]
It's maybe not possible right now - I need to check. Can you create a new issue like "re-enable deprecated dependency warnings" so that I can track it? The problem was our `ensureIssueOnce` function misfired in some circumstances (GitHub's API behaved differently if there's a personal access token in use vs an app token) so it was disabled out of caution.

**Comment by tuckbick** [comment]
Thanks for your feedback. Here is the issue I've filed: https://github.com/renovatebot/renovate/issues/5098
