### ISSUE TITLE
Support MSBuild SDK via `Sdk` attribute on `Project`

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#29101]
### Discussed in https://github.com/renovatebot/renovate/discussions/29048

<div type='discussions-op-text'>

<sup>Originally posted by **ForNeVeR** May 14, 2024</sup>
### Tell us more.

In MSBuild, it's possible to specify the SDK like this:
```xml
<Project Sdk="Microsoft.Build.NoTargets/3.4.0">
</Project>
```

Currently, Renovate supports specifying of these versions via `global.json`, but not via the project files themselves.

See [the documentation](https://learn.microsoft.com/en-us/visualstudio/msbuild/project-element-msbuild?view=vs-2022) (look for the `Sdk` attribute description).</div>

**Comment by ForNeVeR** [comment]
I think it would be ok to have both in same PR. These are very related features.

**Comment by RahulGautamSingh** [comment]
There is also a third way to add project sdks using the [Import element](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022#use-the-import-element-anywhere-in-your-project)
