### ISSUE TITLE
[GitHub] enable `platformCommit` when we detect an app token

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#29115]
### Describe the proposed change(s).

Change `platformCommit` to enum like with values `enabled`, `auto` and `disabled`.
Default to `auto`.
Set to `enabled` when it's auto and we detect an github app token.
i think they start with `ghs_`.

https://github.com/renovatebot/renovate/blob/66de0465e944f55669d5822cea6a2d459a6e5ed6/lib/util/check-token.ts#L67-L69

**Comment by rarkins** [comment]
Added breaking tag, let's do it for v38

**Comment by RahulGautamSingh** [comment]
Is it necessary to do it via `token` or can we just enabled it when platform is GIthubApp?

**Comment by rarkins** [comment]
So will the worker keep platformCommit=auto for the whole run? Where would the logic lie?

**Comment by RahulGautamSingh** [comment]
We only use this option for Github so we can keep the logic in `platform/github/scm`.

From
https://github.com/renovatebot/renovate/blob/f8f518493dad03c26facac4f110b4e553b09b99e/lib/modules/platform/github/scm.ts#L10-L13

To
```typescript
export class GithubScm extends DefaultGitScm {
  override commitAndPush(
    commitConfig: CommitFilesConfig,
  ): Promise<LongCommitSha | null> {
    let platformCommit = commitConfig.platformCommit;
    if (platformCommit === 'auto' && isGHApp()) {
      platformCommit = 'enabled';
    }

    return commitConfig.platformCommit === 'enabled'
      ? commitFiles(commitConfig)
      : git.commitFiles(commitConfig);
  }
}
```

The `isGhApp` fn will reside in `platform/github/index`
```typescript
export function isGHApp(): boolean {
  return !!platformConfig.isGHApp;
}
```

**Comment by RahulGautamSingh** [comment]
We don't need to keep it there though we can also move this logic to `start` fn. 
Around here:
https://github.com/renovatebot/renovate/blob/f8f518493dad03c26facac4f110b4e553b09b99e/lib/workers/repository/index.ts#L75-L78

This way `platformCommit` stays changed.

**Comment by rarkins** [comment]
Keeping the logic in platform sounds better
