### ISSUE TITLE
Bump semantic-release to `23.1.0`, and update our configuration file(s)

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#29118]
### Describe the proposed change(s).

Semantic Release `v23.1.0` has this change:

> add main branch to default release branch config

I think this means we do no longer need to explicitly define the `main` branch, in this file?

https://github.com/renovatebot/renovate/blob/8bbde23579b4bf86a121ed6951681ef9d258a701/.releaserc.json#L93-L96

Maybe there are other Semantic Release config files that we should update, that I'm forgetting to list. :wink: 

### Context:

- https://github.com/semantic-release/semantic-release/issues/1581
- [Semantic Release docs, configuration file](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration-file)
- [Semantic Release `v23.1.0` changelog](https://github.com/semantic-release/semantic-release/releases/tag/v23.1.0)

**Comment by HonkingGoose** [comment]
[Our `build.yml` workflow file](https://github.com/renovatebot/renovate/blob/main/.github/workflows/build.yml) now sets node to 20 in its environment.

Are we ready to upgrade `semantic-release`?

**Comment by viceice** [comment]
yes, already done
