### ISSUE TITLE
sbt metabuild support

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#29127]
### Discussed in https://github.com/renovatebot/renovate/discussions/29083

<div type='discussions-op-text'>

<sup>Originally posted by **ArtyomGabeev** May 15, 2024</sup>
### What would you like help with?

I think I found a bug

### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

Bitbucket

### Please tell us more about your question or problem

sbt has an idea of meta-builds. One of primary usage is to organize dependency management in one place, as documented here:
https://www.scala-sbt.org/1.x/docs/Organizing-Build.html#Tracking+dependencies+in+one+place

The issue comes with scalaVersion resolution.
scalaVersion can be defined only in build.sbt file, e.g.:
```
ThisBuild / scalaVersion := "3.4.1"
```
But when there are scala dependencies in Dependencies.scala file from meta-build project directory, there is no information about scala version. We need somehow to propagate this information.

Options considered:
1. Create some anchor (e.g. via renovate comment) which can be used to specify scala version at top of Dependencies.scala file - the issue is that we will have several places with scalaVersion defined
2. Pass scala version as sbt manager parameter - same problem, several places with scalaVersion needs to be synced by developers
3. Parse build.sbt and extract scalaVersion from root file, pass scalaVersion when parsing other files - this is ideal solution, but I'm not sure about implementation feasibility.

Notes:
I'm looking for advice how to proceed and can contribute the fix.

### Logs (if relevant)

<details><summary>Logs</summary>

```

Replace this text with your logs, between the starting and ending triple backticks

```

</details>
</div>

**Comment by rarkins** [comment]
The `sbt` manager already uses `extractAllPackageFiles()`, which means it processes every file at the same time and can apply "shared" values before returning them. For example there's already a loop where Renovate iterates over each detected file and applies registryUrls settings: https://github.com/renovatebot/renovate/blob/f9511394096516ef21f01ebd50f6f57d1dd875fe/lib/modules/manager/sbt/extract.ts#L396

We could perhaps reuse that loop to apply scala version settings for meta builds

**Comment by ArtyomGabeev** [comment]
Hi, @rarkins

I've opened PR some time ago, but no reviewers are assigned.
May I ask for a review?

Thanks.
