### ISSUE TITLE
Add documentation for `sourceUrl` and `releaseTimestamp` fields

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#29186]
### Describe the proposed change(s).

Related PR:

- #29122

> ## Changes
> 
> - Added `sourceUrlSupport/Note` and `releaseTimestampSupport/Note` fields based on the return object of each datasource

We need to add documentation for this new feature/behavior, so probably:

- explain what it is
- explain what it does
- explain when to use it
- explain when not to use it
- if needed, warn users about possible logic/bugged behavior
- give examples of correct configuration/behavior

I don't know what's the best/correct place to put this information.

I'll let @RahulGautamSingh (PR creator), or another maintainer work on this issue. :wink:

**Comment by RahulGautamSingh** [comment]
Duplicate: https://github.com/renovatebot/renovate/issues/28948#issue-2286911642

**Comment by rarkins** [comment]
Yes, I forgot that one existed

**Comment by HonkingGoose** [comment]
Duplicate of #28948
