### ISSUE TITLE
Increase unpublishSafe to 72 hours

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2938]
This change to npm policy was done in June: https://github.com/npm/policies/commit/04acfa2c258e5cc7572686a59cfcdcab5eb72505#diff-9a807f6434cbf21bf26c380f1efc5366

We previously had some race conditions with unpublishSafe and pending timeouts, so need to code review those first before making the change.

Cc @edmorley

**Comment by rarkins** [comment]
@jefflembeck was there any public discussion/explanation or problem this was alleviating? I wasn't able to locate any.

**Comment by hutson** [comment]
cc @neverett who approved the PR - https://github.com/npm/policies/pull/92

**Comment by rarkins** [comment]
Will use #5265 instead
