### ISSUE TITLE
hostRules: improve matchHost validation and parsing

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#29425]
### Describe the proposed change(s).

Goal: massage "incorrect" matchHost values with ports or paths, for example `gitlab.company.com:8080` or `registry.company.com/some/path`.

Improve validation: if a matchHost value contains `"` or `/` then we should add `https://` as the prefix and check if it's a valid URL. If it's not then I think it's safe for us to raise a config validation error. If it's valid, then we don't need to migrate it, because some config.js configurations may not be possible to migrate (the value comes from env).

Also improve validation of empty matchHost. If the `matchHost` key is defined, but the _value_ is `undefined`, then we should warn. This is commonly caused by empty process.env.SOMETHING being used. We should similar do for empty string `""`.

Finally, we should enhance the addRule function to do similar logic and prefix the matchHost with `https://` if it contains `:` or `/`.

**Comment by RahulGautamSingh** [comment]
>  Improve validation: if a matchHost value contains " or / then we should add https:// as the prefix and check if it's a valid URL.
 
you mean : or / ?

**Comment by rarkins** [comment]
Yes I did

**Comment by RahulGautamSingh** [comment]
Can you confirm these are correct?

gitlab.company.com:8080 -> https://gitlab.company.com
registry.company.com/some/path -> https://registry.company.com
github.com -> github.com
api.github.com -> api.github.com
https://someurl.com -> https://someurl.com

**Comment by rarkins** [comment]
Yes, correct

**Comment by RahulGautamSingh** [comment]
> Improve validation: if a matchHost value contains " or / then we should add https:// as the prefix and check if it's a valid URL. If it's not then I think it's safe for us to raise a config validation error. If it's valid, then we don't need to migrate it, because some config.js configurations may not be possible to migrate (the value comes from env)

We only create a migration PR for the repo config, so it should not be an issue if the config.js takes values from the env.

**Comment by rarkins** [comment]
Yes something like that

**Comment by RahulGautamSingh** [comment]
> Also improve validation of empty matchHost. If the matchHost key is defined, but the value is undefined, then we should warn.

We already error on this as the `matchHost`.
