### ISSUE TITLE
Block automerging if negative reviews exist (github)

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2949]
If an automerging PR has negative/disapproving reviews, then do not automerge it until they are approved or dismissed.

Note: this is entirely different to GitHub's capability to branch restrict merges for only approved PRs. In this case we are talking about Renovate being allowed to automerge without reviews, *but* a user has caught a problem and added a disapproving review.

_Originally requested by @abernix in https://github.com/apollographql/apollo-server/pull/1992#issuecomment-446993015_

**Comment by abernix** [comment]
Thank you for logging this, @rarkins!

**Comment by rarkins** [comment]
There's two possible places we could detect this:
- When fetching the PR (i.e. set canMerge=false if changes are requested)
- When automerging (i.e. abort then if requested changes found)

If we were to do it when fetching PR it would be part of this query: https://github.com/renovatebot/renovate/blob/0a8264612de6d50e8c65d138b9f22d42bdd2f4ec/lib/platform/github/index.js#L1019-L1057
