### ISSUE TITLE
Configuration to bypass default reviewers in auto merged PRs

### ISSUE THREAD

**Issue by nicksnyder** [renovatebot/renovate#2954]
**What would you like Renovate to be able to do?**
It would be nice if Renovate could be configured to create PRs without notifying configured code owner.

For example, I want to be a code owner for a bunch of Kubernetes yaml files so I get notified for "real" changes, but we have Renovate configured to auto merge image bumps and I don't want to be notified for that.

**Describe the solution you'd like**

A config option to enable this behavior.

**Describe alternatives you've considered**
I could (and probably will) create an email filter to ignore these notifications that I don't care about.

**Comment by rarkins** [comment]
Can you point me to an example PR?

I haven't touched this code in probably a year, but Renovate was designed from nearly the start to not assign automerged PRs. I'm wondering if it's GitHub's code owner settings that's doing the assigning.

**Comment by nicksnyder** [comment]
Yeah, the reviewers are getting added by GitHub because of .github/CODEOWNERS so I wouldn't be surprised if there is nothing you can do, so I might be stuck with an email filter.

**Comment by rarkins** [comment]
Closing as I think there's no way to bypass this GitHub automatic feature except doing branch automerges without PR at all.
