### ISSUE TITLE
Incorrect changelog entry

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2960]
Example:  https://github.com/gluons/vue-pack/pull/26

**Comment by rarkins** [comment]
@IlyaSavchuk I have assigned this one to myself already because of the difficulty in solving it, it will probably take me as long to explain it as to fix it

**Comment by IlyaSavchuk** [comment]
@IlyaSavchuk sorry, I missed, okay no problem :)

**Comment by viceice** [comment]
Is this still an issue? We recently fixed some deduplication issue.
