### ISSUE TITLE
Can't install on the Angular github org

### ISSUE THREAD

**Issue by alexeagle** [renovatebot/renovate#2965]
Trying to install Renovate on the Angular org I get an error

![slqxud57q9x](https://user-images.githubusercontent.com/47395/50122812-1915bd00-0213-11e9-9d89-176e13984258.png)

It seems like this is because we paying GitHub (via the Google org's open source program office) and that's not compatible with the new GitHub apps model. I guess it used to work fine when we had renovate setup for angular/tsickle repo because that used the old GitHub services?

Not sure if this is something you can address or if I need to ask GitHub support for help. Have you seen this before?
Thanks!

**Comment by rarkins** [comment]
Hi @alexeagle - you can get around this by installing via https://github.com/apps/renovate instead of the marketplace link. You don't actually *need* the Open Source plan - it's quite a frustrating UX from GitHub!

**Comment by alexeagle** [comment]
Thank you! Could you remind me how to get a link to install the forked version of renovate? I can't grant your app write permission to the angular-cli repo due to Google legal.

**Comment by alexeagle** [comment]
Ah, found it https://github.com/apps/forking-renovate
