### ISSUE TITLE
Use GitHub Alerts for Deprecated Dependency warnings (blocked by 5098)

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#29689]
### Describe the proposed change(s).

Blocked by:

- #5098

Use GitHub's Alert styling to make the warning stand out more. Of course this will only work on GitHub. :wink: So something like this:

> [!WARNING]
> Renovate found the following deprecated dependencies:
> 
> - Deprecated-stuff-1
> - Deprecated-stuff-2
>
> You should review the listed dependencies, and either request a update from Renovate via this dashboard, or upgrade manually.

Here's the Markdown for the mock-up above:

```markdown

> [!WARNING]
> Renovate found the following deprecated dependencies:
> 
> - Deprecated-stuff-1
> - Deprecated-stuff-2
>
> You should review the listed dependencies, and either request a update from Renovate via this dashboard, or upgrade manually.
```

Read the [GitHub Docs, Basic writing and formatting syntax, Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) for more information.

If `[!WARNING]` is too eye-catching, we can select a different alert level.

**Comment by rarkins** [comment]
I'm already doing this as part of my PR https://github.com/renovatebot/renovate/pull/29694

FYI we can put this in source code:

```
> ⚠ **Warning**\n> \n
```

And then our github platform massageMarkdown code massages it to this:

```
> [!WARNING]
```
