### ISSUE TITLE
Support pypi /simple endpoint

### ISSUE THREAD

**Issue by Nebukadneza** [renovatebot/renovate#2970]
Renovate supports the more modern `/pypi/*/json` endpoints that many pypi servers, most notably the official one, use. Many 3rd-party tools however, for example Artifactory, however, provide the easier-to-implement `/simple/*` endpoint, in which a well-formed HTML directory listing is returned, and the client has to parse this.

While that is certainly a lot less elegant than parsing the json data in the current implementation, it would certainly help to adopt `renovate` in more deployment scenarios.

As far as i see, the support would completely happen in `lib/datasource/pypi.js`, and the only other change I could spot is that `lib/manager/pipenv/extract.js` must not replace `simple` by `pypi` anymore.

In any case, thanks a lot for this already great project!
Thanks & Best Regards,
-Dario

**Comment by rarkins** [comment]
Thanks for raising this feature request. Can you provide an example Pipfile/Pipfile.lock with entries as you describe, as well as if you are aware of any public servers we could test against as part of implementation?

**Comment by Nebukadneza** [comment]
Thanks for the quick reply!

the official pypi.org-server still supports `/simple`, so i guess it’d be easiest to test against that. An random example looks like this:
https://pypi.org/simple/opcua/

An example `Pipfile/.lock` with a random project, and a few dependecy-dependencies would probably be:
`Pipfile`:
```
[[source]]
url = "https://pypi.org/simple/"
verify_ssl = true
name = "pypi-official-local"

[packages]
opcua = ">0.98"
```
`Pipfile.lock`:
```
{
    "_meta": {
        "hash": {
            "sha256": "043c6204e6ef611ed89cf21cb8e1c4f54dce47460f01752b28ec8d759b1f59c8"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi-official-local",
                "url": "https://pypi.org/simple/",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "lxml": {
            "hashes": [
                "sha256:02bc220d61f46e9b9d5a53c361ef95e9f5e1d27171cd461dddb17677ae2289a5",
                "sha256:22f253b542a342755f6cfc047fe4d3a296515cf9b542bc6e261af45a80b8caf6",
                "sha256:2f31145c7ff665b330919bfa44aacd3a0211a76ca7e7b441039d2a0b0451e415",
                "sha256:36720698c29e7a9626a0dc802ef8885f8f0239bfd1689628ecd459a061f2807f",
                "sha256:438a1b0203545521f6616132bfe0f4bca86f8a401364008b30e2b26ec408ce85",
                "sha256:4815892904c336bbaf73dafd54f45f69f4021c22b5bad7332176bbf4fb830568",
                "sha256:5be031b0f15ad63910d8e5038b489d95a79929513b3634ad4babf77100602588",
                "sha256:5c93ae37c3c588e829b037fdfbd64a6e40c901d3f93f7beed6d724c44829a3ad",
                "sha256:60842230678674cdac4a1cf0f707ef12d75b9a4fc4a565add4f710b5fcf185d5",
                "sha256:62939a8bb6758d1bf923aa1c13f0bcfa9bf5b2fc0f5fa917a6e25db5fe0cfa4e",
                "sha256:75830c06a62fe7b8fe3bbb5f269f0b308f19f3949ac81cfd40062f47c1455faf",
                "sha256:81992565b74332c7c1aff6a913a3e906771aa81c9d0c68c68113cffcae45bc53",
                "sha256:8c892fb0ee52c594d9a7751c7d7356056a9682674b92cc1c4dc968ff0f30c52f",
                "sha256:9d862e3cf4fc1f2837dedce9c42269c8c76d027e49820a548ac89fdcee1e361f",
                "sha256:a623965c086a6e91bb703d4da62dabe59fe88888e82c4117d544e11fd74835d6",
                "sha256:a7783ab7f6a508b0510490cef9f857b763d796ba7476d9703f89722928d1e113",
                "sha256:aab09fbe8abfa3b9ce62aaf45aca2d28726b1b9ee44871dbe644050a2fff4940",
                "sha256:abf181934ac3ef193832fb973fd7f6149b5c531903c2ec0f1220941d73eee601",
                "sha256:ae07fa0c115733fce1e9da96a3ac3fa24801742ca17e917e0c79d63a01eeb843",
                "sha256:b9c78242219f674ab645ec571c9a95d70f381319a23911941cd2358a8e0521cf",
                "sha256:bccb267678b870d9782c3b44d0cefe3ba0e329f9af8c946d32bf3778e7a4f271",
                "sha256:c4df4d27f4c93b2cef74579f00b1d3a31a929c7d8023f870c4b476f03a274db4",
                "sha256:caf0e50b546bb60dfa99bb18dfa6748458a83131ecdceaf5c071d74907e7e78a",
                "sha256:d3266bd3ac59ac4edcd5fa75165dee80b94a3e5c91049df5f7c057ccf097551c",
                "sha256:db0d213987bcd4e6d41710fb4532b22315b0d8fb439ff901782234456556aed1",
                "sha256:dbbd5cf7690a40a9f0a9325ab480d0fccf46d16b378eefc08e195d84299bfae1",
                "sha256:e16e07a0ec3a75b5ee61f2b1003c35696738f937dc8148fbda9fe2147ccb6e61",
                "sha256:e175a006725c7faadbe69e791877d09936c0ef2cf49d01b60a6c1efcb0e8be6f",
                "sha256:edd9c13a97f6550f9da2236126bb51c092b3b1ce6187f2bd966533ad794bbb5e",
                "sha256:fa39ea60d527fbdd94215b5e5552f1c6a912624521093f1384a491a8ad89ad8b"
            ],
            "version": "==4.2.5"
        },
        "opcua": {
            "hashes": [
                "sha256:44ef09506d284c31f9455a48a37074fce87c53363f5e6ec4b6eb9965525c3f24"
            ],
            "index": "pypi-official-local",
            "version": "==0.98.5"
        },
        "python-dateutil": {
            "hashes": [
                "sha256:063df5763652e21de43de7d9e00ccf239f953a832941e37be541614732cdfc93",
                "sha256:88f9287c0174266bb0d8cedd395cfba9c58e87e5ad86b2ce58859bc11be3cf02"
            ],
            "markers": "python_version >= '2.6' and python_version != '3.1.*' and python_version != '3.0.*'",
            "version": "==2.7.5"
        },
        "pytz": {
            "hashes": [
                "sha256:31cb35c89bd7d333cd32c5f278fca91b523b0834369e757f4c5641ea252236ca",
                "sha256:8e0f8568c118d3077b46be7d654cc8167fa916092e28320cde048e54bfc9f1e6"
            ],
            "version": "==2018.7"
        },
        "six": {
            "hashes": [
                "sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c",
                "sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73"
            ],
            "markers": "python_version >= '2.6' and python_version != '3.1.*' and python_version != '3.0.*'",
            "version": "==1.12.0"
        }
    },
    "develop": {}
}
```

I hope that already helps a bit ….

**Comment by Nebukadneza** [comment]
Hi,

I just saw that the `needs-requirements` label is still set. Is there anything else I could add to help?

Thanks! … And best regards,
-Dario

**Comment by rarkins** [comment]
Sorry, I missed one part from the original request. Could we base our behaviour entirely on the presence of simple vs pypi when we’re extracting?

**Comment by Nebukadneza** [comment]
Hi,

while it’s not really specified in https://www.python.org/dev/peps/pep-0503/ I guess it’s reasonable to assume that if the given URL ends with `/simple`, then the simple endpoint parser shall be used. This is, to my knowledge, true for most pypi services offering only the simple endpoint.

Hope that helps, thanks
-Dario

**Comment by rarkins** [comment]
OK, making notes to self here:

The test case above is Pipefile/Pipfile.lock but I think this concept can extend to `requirements.txt` too whenever custom hosts are used.

Remove this massaging from pipenv extract: https://github.com/renovatebot/renovate/blob/b8df0f85713d7f6fe9f3b471764aa21512f8b3c3/lib/manager/pipenv/extract.js#L29

On this line: https://github.com/renovatebot/renovate/blob/b8df0f85713d7f6fe9f3b471764aa21512f8b3c3/lib/datasource/pypi/index.js#L39-L42

We should add logic there that says `if (hostUrl.endsWith('/simple')) { return getSimpleDependency(...); }` and then a new function `getSimpleDependency` that attempts to retrieve and parse the simple HTML format.

**Comment by Nebukadneza** [comment]
Agree, release date isn’t provided by the simple endpoint, but as a user, I feel a strict version-sorting is what matters anyways.

Thanks for staying on this ^_^.
