### ISSUE TITLE
New self-hosted config option `platformOptions`

### ISSUE THREAD

**Issue by RahulGautamSingh** [renovatebot/renovate#29716]
### Describe the proposed change(s).

To improve the organization and accessibility of platform-specific configuration options, combine them under a single config option named `platformOptions`.

Example:
```json
{
  "platformOptions": {
  
  // global-only config 
  "bbUseDevelopmentBranch": true,
   "gitlabAutoMergeableCheckAttempts": 3, // prev. RENOVATE_X_GITLAB_AUTO_MERGEABLE_CHECKS_ATTEMPTS
   "gitlabBranchStatusDelay": 4, // prev. RENOVATE_X_BRANCH_STATUS_DELAY
   "gitlabMergeRequestDelay": 100, // prev. RENOVATE_X_MERGE_REQUEST_DELAY
    
  // repo config
    "gitLabIgnoreApprovals": true,
    "bbUseDefaultReviewers": true
    "azureWorkItemId": 123213
  }
}
```

_Originally posted by @viceice in https://github.com/renovatebot/renovate/pull/29137#discussion_r1617788554_

**Comment by RahulGautamSingh** [comment]
Should `azureWorkItemId` be included in this list too? It is a repo config option currently whereas all the others are already global only options.

**Comment by viceice** [comment]
> Should `azureWorkItemId` be included in this list too? It is a repo config option currently whereas all the others are already global only options.

I'm not sure about that 🤔

**Comment by RahulGautamSingh** [comment]
Blocked by: https://github.com/renovatebot/renovate/pull/29137

**Comment by RahulGautamSingh** [comment]
> Should `azureWorkItemId`, `bbUseDefaultReviewers`, `gitLabIngoreApprovals` be included in this list too? These 3 are a repo config options, whereas all the others options that I included in the pr description are global only options.

@secustor @rarkins

**Comment by secustor** [comment]
I'm in favor of including these options there too, as else it is confusing why similar options have to be set at different places.

**Comment by RahulGautamSingh** [comment]
If we include the repo config options, then `platformOptions` will need to be a repo config option ie. it will be available in both repo config and global config. But we cannot include the global config fields (ie. `githubTokenWarn`) when we add `platformOptions` to the repo config.

What should we do in this case? I think maybe we can make this option context-aware:

If found in the repo config:

- Allow only repo-specific options (e.g., `azureWorkitemId`)
- Remove & warn about global options (e.g., `githubTokenWarn`) if present


If found in repo config:

- Allow all options, both global and repo-specific

**Comment by viceice** [comment]
we can mark the specific child options as global only, so only they fail validation on repo config. `platformOptions` should be mergable.

**Comment by RahulGautamSingh** [comment]
There is an internal variable with the same name [platformOptions](https://github.com/search?q=repo%3Arenovatebot%2Frenovate%20platformOptions&type=code) which we use for passing options to the `createPr`/`updatePr` functions. I think renaming it to `platformPrOptions` before hand will be good.

**Comment by RahulGautamSingh** [comment]
Rhys [suggested ]([comment](https://github.com/renovatebot/renovate/pull/30173#issuecomment-2227460472) )this option needs a new name. So, I'm adding this to get some recommendations. MAybe `platformSettings` ?

**Comment by RahulGautamSingh** [comment]
I don't think `githubTokenWarn` should be included in this. Even, though it has a platform in its name, it is used to supress github token warning which can be used by users of any platform while self-hosting.

**Comment by rarkins** [comment]
Can't it be replaced with a log level remap now anyway?

**Comment by RahulGautamSingh** [comment]
Yes.

**Comment by RahulGautamSingh** [comment]
Yes

**Comment by RahulGautamSingh** [comment]
Closing as this not necessary right now. [^1]

[^1]: https://github.com/renovatebot/renovate/pull/31381#pullrequestreview-2305795711
