### ISSUE TITLE
Remove deprecationWarningIssues functionality completely

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#29739]
### Describe the proposed change(s).

This functionality (create one issue per deprecated dependency) has been disabled for years and should be removed.

- Remove the `deprecationWarningIssues` value but do not create config warnings if it's included in a user's config (massage it away)
- Remove any code for creating deprecation issues

Do not make any changes which break the dependency dashboard deprecated warnings feature

**Comment by RahulGautamSingh** [comment]
We will need to redo the default value of [`suppressNotifications`](https://docs.renovatebot.com/configuration-options/#suppressnotifications) config option as well. Should I set it to `null`?

**Comment by rarkins** [comment]
Yes, maybe `null` or `[]`
