### ISSUE TITLE
Kubernetes: Renovate hasn't opened a PR in 2 days 

### ISSUE THREAD

**Issue by ggilmore** [renovatebot/renovate#2974]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
In https://github.com/sourcegraph/deploy-sourcegraph-dot-com, we configured Renovate to update our docker image tags in our Kubernetes manifests. We've just noticed that Renovate hasn't opened a PR in over 2 days.

**Did you see anything helpful in debug logs?**
[(Click here for our Renovate job dashboard)](https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph-dot-com/34416619)

In our renovate.json, we set a up a group for all of our sourcegraph-related docker images:

```js
"packageRules": [
  {
    "packagePatterns": [
      "^sourcegraph/"
    ],
    "groupName": "Sourcegraph Docker images",
    // ...
  }
]
```

Renovate has previously been able to create PRs and automerge them when only a single docker image's tag needs to be updated. (See https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph-dot-com/33998519 , https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph-dot-com/34056264). 

However, when multiple tags need to be updated - Renovate was able to create a PR and automerge it only once ( I can't link to the job since it is old and doesn't show up on the dashboard anymore). However, it seems like Renovate is getting stuck and isn't able to open a PR that updates multiple images since then.

Example:

In https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph-dot-com/34416619, the following log line shows up:

```log
INFO: Merged PR is blocking this branch(dependencies=["sourcegraph/frontend","sourcegraph/xlang-javascript-typescript"], branch="renovate/docker-sourcegraph-docker-images")
{
  "pr": 32
}
```

https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/32 was the PR that Renovated created earlier that successfully updated multiple images. As far as I can tell, Renovate was able to merge and delete the branch as it normally does:

![screen shot 2018-12-18 at 8 46 02 am](https://user-images.githubusercontent.com/9022011/50168938-65a7d980-02a1-11e9-9be7-f55f4fdb9bf1.png)

Is there any more information that I could provide? I'm not sure how to debug this.

**Comment by rarkins** [comment]
@ggilmore that appears to be a bug in our logic. Any PR without a unique version in the PR to  identify it shouldn't block future ones. I'll try to think of a way to reproduce it to produce a fix. Sorry for the inconvenience and thanks for the great details!

**Comment by rarkins** [comment]
@ggilmore thanks again for reporting the bug. It impacted groups of Docker digest updates, by not detecting that reuse of same branch name/ PR title should be enabled. You should now see PR #36 raised.
