### ISSUE TITLE
Duplicate dependency deprecation warning issues

### ISSUE THREAD

**Issue by alan-agius4** [renovatebot/renovate#2979]
**What Renovate type are you using?**
GitHub App (Forking Renovate)

**Describe the bug**
It looks like duplicate issues for `Dependency deprecation warning` are being created.

**Expected behavior**
One issue per deprecated package is logged.

**Screenshots**
https://github.com/angular/angular-cli/issues/13228
https://github.com/angular/angular-cli/issues/13230

**Comment by rarkins** [comment]
@alan-agius4 apologies for the noise. It should already be fixed, but I have disabled the notifications temporarily until I'm as sure as I can be that it won't happen again.

**Comment by alan-agius4** [comment]
Thank you, for your swift action.
