### ISSUE TITLE
Add java (Maven) range versioning

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2986]
Based on the existing lib/versioning/loose implementation, we want a java-specific one for Gradle and Maven. Particularly, it needs to answer correctly for stable vs unstable, so that versions like 1.2.3.Release are not classified as unstable.

Let's gather requirements here first. 

Cc @JamieMagee @corecanarias

**Comment by rarkins** [comment]
This is half implemented already via #3020 and #3028. It should already fully support java (maven) versioning for exact versions, but not yet Maven ranges.

**Comment by rarkins** [comment]
https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification

**Comment by rarkins** [comment]
Remaining: range syntax support

**Comment by derkoe** [comment]
I found an issue with versions when trying out the new Maven feature: many Maven projects use a 4-stage versioning scheme including a qualifier. Examples for this are Spring and Hibernate (two of the most used frameworks).

Here is the message from the log:
```
DEBUG: Dependency org.springframework.boot/spring-boot-starter-parent has unsupported value 2.1.1.RELEASE (repository=koc/angular-spring-heroes)
```

Spring uses this versioning scheme:
https://github.com/spring-projects/spring-build-gradle/wiki/Spring-project-versioning

Hibernate (and all other JBoss projects) uses this one:
https://developer.jboss.org/wiki/JBossProjectVersioning

**Comment by rarkins** [comment]
@derkoe thanks for reporting this. I think we may be using `semver` versioning by mistake. Once confirmed, it should hopefully be completely fixed by switching to the `maven` versioning scheme we already have ready.

**Comment by derkoe** [comment]
@rarkins works! Parent updates work as expected (#3164).
