### ISSUE TITLE
Add caching to datasource.getPkgReleases

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2996]
Add a common caching layer inside `lib/datasource/index.js`

Currently we skip caching for npm private modules to avoid accidentally giving a response to a repo that has no valid npmjs authentication. So either the npm datasource needs to return something in its response (private: true, or cache: false), or we need a hardcoded rule for npm/private repos.

**Comment by viceice** [comment]
Closing this, as we have a `run` cache already
