### ISSUE TITLE
Detect a positive review for automerge.

### ISSUE THREAD

**Issue by rtaum** [renovatebot/renovate#3012]
**What Renovate type are you using?**
Renovate CLI, Renovate GitHub App, or Renovate Pro?

**Describe the bug**
There was a task to prevent automerge if changes were requested (#2949). Now automerge is being stopped even if later that change request was approved.
Looks like we have a dificulties to detect if the change request was approved.
Actually the PR could be approved by other collaborators, so we need to decide if we are going to merge it or not?

**To Reproduce**

1. Create any PR on some github repo.
2. Configure automerge for the github (for details check the [documentation](https://renovatebot.com/docs/configuration-options/#automerge)).
2. Request some changes for it.
3. Approve it.
4. Run any version of Renovate (Renovate CLI is fine for the test) on that repo.

**Expected behavior**
The PR should be merged.

**Actual behavior**
The PR is not being merged.

**Summary**
There are two unclear moments for me.
1. If the same user has added multiple reviews, should we check only the last one to detect if it is approved?
2. If an user has requested changes, should we condider the PR approved if someone else gives a possitive review?

**Comment by rarkins** [comment]
I think we block automerge if any “changes requested” review is still outstanding. Ie don’t care even if another 100 have approved. They may be approving for some other reason.

It’s strange that we can’t detect if the person who requested changes has subsequently approved. Do those show up as two separate reviews for the PR?

**Comment by rtaum** [comment]
> Do those show up as two separate reviews for the PR

Yep. I was unable to find any marker, showing that the requested change and the approve are related to the same issue.
We can detect the author though. So, potentially if author of the change approved the PR later, it could be considered as a positive review.
Still it does not solve the issue with different users. In that case, to run automerge, the PR should be approved by the same user who has created the change request.

**Comment by rarkins** [comment]
So it sounds like we need to do this?
- Retrieve all reviews (or maybe 100 or whatever is a reasonable limit)
- If there are any "changes requested" reviews, check if an approved review from the same author has followed

**Comment by rtaum** [comment]
Sounds like a plan.
