### ISSUE TITLE
Lockfile maintenance PR closed/deleted unexpectedly

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#3018]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Renovate closed/deleted the lockfile maintenance PR/branch when this was not expected/desired.

**Did you see anything helpful in debug logs?**
`INFO: Deleting lock file maintenance branch as it is conflicted`
(https://renovatebot.com/dashboard#github/mozilla/treeherder/37041099)

**To Reproduce**

1.  Go on vacation
2. When back merge several Renovate bot dependency PRs, saving the lockfile PR for last
3. Open the lockfile PR at the end ready to merge it (https://github.com/mozilla/treeherder/pull/4399)
4. Find that the PR has been closed unexpectedly

**Expected behavior**
Lockfile PR is still open and automatically rebased if conflicted.

**Comment by rarkins** [comment]
Could this be summarised as "rebase lock file maintenance PRs when conflicted instead of autoclosing them"?

I actually forget the reasoning/logic behind it although it sounds like it was deliberate!

**Comment by edmorley** [comment]
Perhaps - though this wasn't the behaviour in the past, which is why it now seemed unintentional?

**Comment by rarkins** [comment]
Taking a guess, I think it was related to cleaning up closed maintenance PRs. e.g. let's say you have a maintenance PR that's conflicted and you close the PR but forget to delete the branch. In current functionality it means it gets cleaned up rather than regenerated and replacement PR created.

The ideal solution would be one if we can check if an existing PR existed, but it's actually quite challenging.

**Comment by edmorley** [comment]
Happened again, though this time I'd pressed the rebase checkbox before conflicts were reported?
https://github.com/neutrinojs/neutrino/pull/1271

**Comment by edmorley** [comment]
Is happening repeatedly in:
https://github.com/mozilla/treeherder/pull/4608

The PR won't stay open 😢

**Comment by rarkins** [comment]
Sorry, let me assess if just pulling this logic can be done without adverse effect

**Comment by alexandernanberg** [comment]
@rarkins Is the fix live for the GitHub app? I'm experiencing a similar issue, I can open another PR with more details if this issue is fixed

**Comment by esetnik** [comment]
I believe i'm having the same issue on the gitlab app. My lockfile maintenance MRs are getting closed instead of updated when I make other changes to the project that cause them to become conflicted.
