### ISSUE TITLE
429 (rate limit exceeded) for Bitbucket files endpoint

### ISSUE THREAD

**Issue by OscarBarrett** [renovatebot/renovate#3024]
**What Renovate type are you using?**
CLI

**Describe the bug**
Running renovate for the first time on a Bitbucket repo that has a large number of files/folders, it fails with `Error retrieving git tree - no files detected`.

**Did you see anything helpful in debug logs?**
 Exposing [the actual error](https://github.com/renovatebot/renovate/blob/960648abbe40fefabe9106bdaf8c2530c8abb741/lib/platform/bitbucket/index.js#L147) manually shows that the requests to the files endpoint is getting rate limited.

```
ERROR: Repository has unknown error (repository=<user>/<repo>)
      "err": {
         "name": "HTTPError",
         "host": "api.bitbucket.org",
         "hostname": "api.bitbucket.org",
         "method": "GET",
         "path": "/2.0/repositories/<user>/<repo>/src/<commit>/<some>/<path>/?pagelen=100",
         "protocol": "https:",
         "url": "https://api.bitbucket.org/2.0/repositories/<user>/<repo>/src/<commit>/<some>/<path>/?pagelen=100",
         ....
         "statusCode": 429,
         "statusMessage": "Unknown Status Code",
         "headers": {
           ....
         },
         "body": "Rate limit for this resource has been exceeded",
         "message": "Response code 429 (Unknown Status Code)",
         "stack": "HTTPError: Response code 429 (Unknown Status Code)\n    at EventEmitter.emitter.on (/..../node_modules/renovate/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
```

The directory it fails on is about 165 folders into the repo going DFS alphabetically.

**To Reproduce**

1.  Run `renovate` on a repository with a large number of folders.

**Expected behavior**
Limit the requests or back off when getting a 429 response code so there is no failure.

**Comment by rarkins** [comment]
Thanks for the info. Inside those "headers", do they include any retry-after or similar that guides us as to when we can back off to?

Most likely the solution though is to move Bitbucket Cloud to use our "gitFs", which will come after #2774 lands and we copy the changes over. This means we get the file list using git and not the API.

**Comment by OscarBarrett** [comment]
Here are the response headers, nothing useful that I can see and unfortunately their docs don't mention the exact rate limit here.

```
         "headers": {
           "server": "nginx",
           "vary": "Authorization",
           "cache-control": "no-cache, no-store",
           "content-type": "text/plain",
           "x-oauth-scopes": "pullrequest:write, account",
           "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
           "date": "Fri, 04 Jan 2019 06:16:16 GMT",
           "x-served-by": "app-141",
           "x-static-version": "b44f75ebbd3d",
           "etag": "\"62dcd5481fd29816ecc5ae00be2da0b0\"",
           "x-render-time": "0.0136690139771",
           "x-credential-type": "apppassword",
           "x-accepted-oauth-scopes": "repository",
           "connection": "close",
           "x-version": "b44f75ebbd3d",
           "x-request-count": "438",
           "x-frame-options": "SAMEORIGIN",
           "content-length": "46"
         }
```

Using git instead of the API for this would definitely be a plus :+1:
