### ISSUE TITLE
Run local tests

### ISSUE THREAD

**Issue by IlyaSavchuk** [renovatebot/renovate#3025]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
When I run any type of tests locally, I get an error in tests in datasource folder (pypi.spec.js, terraform.spec.js, packagist.spec.js, github.spec.js, nuget.spec.js, gitlab.spec.js, docker.spec.js, orb.spec.js, go.spec.js).

**Did you see anything helpful in debug logs?**

```
  ● Test suite failed to run

    TypeError: Cannot set property 'recreate' of undefined

      at Object.<anonymous> (node_modules/gl-got/index.js:37:26)
      at Object.<anonymous> (lib/platform/gitlab/gl-got-wrapper.js:836:65)
      at Object.<anonymous> (lib/datasource/gitlab/index.js:296:64)
      at Object.<anonymous> (lib/datasource/index.js:1020:67)
      at Object.<anonymous> (test/datasource/packagist.spec.js:8:20)

```

**To Reproduce**

1. clone the project
2. follow the instructions to start the project
3. try to run the test with - yarn test

**Expected behavior**
Tests work properly :)

**Screenshots**
![image](https://user-images.githubusercontent.com/33482666/50678728-cf95e200-1008-11e9-8b5c-e771dc7e3c1e.png)

**Additional context**
If you go to node_modules/gl-got/index.js:37:26 and remove this line, tests start to work without any problem, also if you switch the version gl-got from 9.0.2 to 7.0.0, this also resolves the problem.

**Comment by rarkins** [comment]
We did only just add the gitlab datasource to master today, which is probably not a coincidence. But I'm surprised to see the errors you're getting. Maybe try nuking your node_modules again if necessary.

**Comment by IlyaSavchuk** [comment]
@rarkins I tried, but it wasn't very helpful. If it works on the server and locally for others, I can change it locally and never push these changes. If any other deveolpers have this error in the future, they can easily find the solution for it in - Additional context. So I think we can close this issue :)

**Comment by rarkins** [comment]
I would like to get to the bottom of it though. FYI tests run fine for me locally and fine on Travis.
