### ISSUE TITLE
Include depName in changelog release name patterns

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#30297]
### Describe the proposed change(s).

Currently we look for github releases either by version (e.g. `1.0.0`) or `packageName-release`, e.g. (`foo-1.0.0`). We should include `depName` in this search too.

Discussion with reproduction: https://github.com/renovatebot/renovate/discussions/29943 (test-dep update to v1.2.0)

**Comment by usmonster** [comment]
Proposed fix: #30395.
