### ISSUE TITLE
Extend Maven datasource caching

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#30419]
### Describe the proposed change(s).

The Maven datasource does not appear to have `caching = true` set. When run on a repo like https://github.com/renovate-reproductions/net.twisterrob.gradle caching does not seem to be working or efficient, e.g. repeated runs still take 42 seconds for lookup on my laptop, even though all registries are public ones.

Logs should 0 set cache methods performed. Ideally all results should be cached such that potentially 0 requests to registries are required when the cache is "hot". On the other hand I note a comment `// cache non-null responses unless marked as private` and I'm not sure why we're being so conservative about not caching null.

We need to:
- Review the Maven datasource to ensure `isPrivate` is set reliably, and
- Enable caching

**Comment by rarkins** [comment]
Related: https://github.com/renovatebot/renovate/issues/30420

**Comment by rarkins** [comment]
If we achieve 100% caching for this repo but it still seems that the lookup is subjectively slow, create a new issue for further investigation.

**Comment by rarkins** [comment]
I played around with this diff:

```diff
diff --git a/lib/modules/datasource/index.ts b/lib/modules/datasource/index.ts
index 006a0023c..4f677016c 100644
--- a/lib/modules/datasource/index.ts
+++ b/lib/modules/datasource/index.ts
@@ -70,7 +70,7 @@ async function getRegistryReleases(
       cacheKey,
     );
     // istanbul ignore if
-    if (cachedResult) {
+    if (cachedResult !== undefined) {
       logger.trace({ cacheKey }, 'Returning cached datasource response');
       return cachedResult;
     }
@@ -80,13 +80,13 @@ async function getRegistryReleases(
     res.registryUrl ??= registryUrl;
   }
   // cache non-null responses unless marked as private
-  if (datasource.caching && res) {
+  if (datasource.caching) {
     const cachePrivatePackages = GlobalConfig.get(
       'cachePrivatePackages',
       false,
     );
-    if (cachePrivatePackages || !res.isPrivate) {
       logger.trace({ cacheKey }, 'Caching datasource response');
+    if (cachePrivatePackages || !res?.isPrivate) {
       const cacheMinutes = 15;
       await packageCache.set(cacheNamespace, cacheKey, res, cacheMinutes);
     }
diff --git a/lib/modules/datasource/maven/index.ts b/lib/modules/datasource/maven/index.ts
index 3476ded21..4d2f18de7 100644
--- a/lib/modules/datasource/maven/index.ts
+++ b/lib/modules/datasource/maven/index.ts
@@ -68,6 +68,8 @@ export class MavenDatasource extends Datasource {
 
   override readonly defaultVersioning: string = mavenVersioning.id;
 
+  override readonly caching = true;
+
   override readonly registryStrategy: RegistryStrategy = 'merge';
 
   override readonly releaseTimestampSupport = true;
```

**Comment by zharinov** [comment]
For `null` values, we can't determine whether it's private or not, so I think it's better not to cache nulls

**Comment by rarkins** [comment]
You mean private but missing credentials? Why not cache that?

**Comment by zharinov** [comment]
I mean `null` results for private packages

**Comment by rarkins** [comment]
What can go wrong if we cache those?
