### ISSUE TITLE
Add Hex versioning 

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3042]
https://hexdocs.pm/elixir/v1.7/Version.html

Ranges look pretty similar to npm’s so only a small wrapper should be necessary, eg like cargo or composer.

**Comment by rarkins** [comment]
This can be 100% wrapper to start with, e.g. like composer or terraform but with no customisations. We can extend it later if necessary.

To go in lib/versioning/hex

**Comment by Dmitry9** [comment]
@rarkins link you posted in the top comment not working anymore. Did you meant [this page](https://hexdocs.pm/elixir/Version.html).

**Comment by rarkins** [comment]
Yes but I just realised that it's a duplicate of #3299 and @KonstantinKurganov may be working on it already. Please hold off for now, sorry.

**Comment by Dmitry9** [comment]
Ok, I will pause. Just for your information I did introductory minor research and think that I understood the requirements of this issue. From my understanding, the `composer2npm` function translates composer syntax for `semverstring` to npm-way of denoting versions and allow versions comparison,  `hex2npm` function should be implemented as an adapter to the HEX-way of representing `semverstring` (~> and so on). Then I would reuse general case (the logic of how npm handles types of `rangestrategy` : pin ,bump ...) in `getNewValue` function with respect to the HEX-way of representing `semverstring`. 
@rarkins I am just curious weather I was on the right way?

**Comment by rarkins** [comment]
Yes, that’s the right way!
