### ISSUE TITLE
Add "hex" datasource (Elixir/Erlang)

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3043]
Example: 
https://hex.pm/api/packages/certif

Need to also handle private packages with auth.

**Comment by rarkins** [comment]
I'd recommend to start by copying from the Cargo datasource structure, and updating to match the hex metadata.

**Comment by hewsut** [comment]
Howdy! We're using Renovate with a NodeJS repo to great success.

We're looking at some new tech in new projects. Does this PR mean Renovate fully supports Elixir/Erlang now?

**Comment by rarkins** [comment]
@hewsut Elixir/Erlang is not quite supported yet. Supporting a new language means up to three new pieces maybe required:

- datasource
- version scheme
- extract and update functions

So far we have the first 2 merged, which will be common for both mix and rebar, and the last part for Mix is in this PR: https://github.com/renovatebot/renovate/pull/3248

If you subscribe to it then you'll know when Mix is ready for resting. Rebar will come after in a separate PR.

**Comment by hewsut** [comment]
Subscribed, looking forward to it!

We are happy paying customers. Great job building all this out so thoughtfully.
