### ISSUE TITLE
Rewrite hostRules

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3044]
- [x] Rename `platform` to be `hostType` (e.g. github/docker/pypi/etc)
- [ ] Clarify host vs endpoint. Do we need endpoint or only host? Endpoint may only be necessary if we need different rules for different endpoint prefixes

**Comment by pyaillet** [comment]
Would this feature allow to use different credentials for different hosts of the same platform ?

I.E.: I would like to run renovate to check docker images on our local docker registry and on the docker hub, but they do not share the same credentials.

**Comment by rarkins** [comment]
You can already do that - credentials today are already host-based

**Comment by pyaillet** [comment]
Thank you !
I should ask a question on renovatebot/config-help I guess :)
