### ISSUE TITLE
Unhandles exceptions in dashboard when enabling a gitlab project

### ISSUE THREAD

**Issue by mjrider** [renovatebot/renovate#3045]
**What Renovate type are you using?**
Gitlab

**Describe the bug**
after activating renovate on an project, the following error  is reported in the console of the browser
```
POST https://v1.renovateapi.com/gitlab/repos/pipeline-components/snyk/webhooks 403
Uncaught (in promise) 
(anonymous) @ dashboard.js:405
async function (async)
(anonymous) @ dashboard.js:388
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

this seems to originate from the following lines (around 392) in dashboard.js in the function `('#installModalBody').on('change', '.switch', async function() {`
```
    await renovate('/gitlab/repos/' + repo.path_with_namespace + '/webhooks', {
      type: 'POST'
    });
```

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

**To Reproduce**

1. open dashboard with a gitlab account
2. add new project
3. watch the browser output

**Expected behavior**
No unhandled errors

**Screenshots**
![image](https://user-images.githubusercontent.com/213105/50817440-198e0900-1324-11e9-9ba5-5be4052ff1bb.png)

**Comment by mjrider** [comment]
I'm guessing this is related, when i try to view the jobs:
![image](https://user-images.githubusercontent.com/213105/50823295-e94e6680-1333-11e9-812b-fdb41f44cf96.png)

**Comment by rarkins** [comment]
Thanks for the additional info. If you disable/enable the repository or log out / log in, does the same error keep appearing in the console?

**Comment by mjrider** [comment]
yes, i also tried on an other repository i didn't try before, and it gives the same 403 when posting to `https://v1.renovateapi.com/gitlab/repos/pipeline-components/XXXX/webhooks`
due to this, the webhook for the project is never created

**Comment by rarkins** [comment]
I think I found the problem and have fixed it. In short: group permissions weren't detected properly, so only direct permissions (which were `null`) were considered. Can you try again?

**Comment by mjrider** [comment]
thx it seems to work now
