### ISSUE TITLE
bumpVersion not applied to non-npm updates

### ISSUE THREAD

**Issue by karfau** [renovatebot/renovate#3057]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Although the configuration says `"bumpVersion": "patch"` this PR https://github.com/bettermarks/bm-tslint-rules/pull/72 did not bump the version (which is why the CI job fails since it checks for an increased version).

**Did you see anything helpful in debug logs?**
1. Those logs only go back 3 days but the PR was created 14 days ago.
2. I checked the rebase/retry checkbox and the log from that build didn't produce anything that looked unnormal to me.
3. But it just occurred to me that the node version in the `.nvmrc` file was also not increased to the correct version (10.15 currently) but this might be a different issue.

**To Reproduce**
I guess taking bettermakrs/bm-tslint-rules@fac5d31b0f511f374974bce967c6bf01fc3dbfef and letting the renovate bot do it's thing?

**Expected behavior**
- version field in `package.json` and `package-lock.json` should have been bumped to 0.7.7
- (`.nvmrc` file should have changed from `10.14` to `10.15`, should I file a separate issue for this one?)

**Comment by karfau** [comment]
Currently every version landing on master has to have a distinct version. so it has to yes.
But in this case knowing that something will be coming that will update the nvmrc I'll wait for this one and then do the bump manually.

Thx for the fast response.
Feel free to close this if there are no plans of changing this behaviour.

**Comment by rarkins** [comment]
See https://github.com/bettermarks/bm-tslint-rules/pull/72/files for updated PR with `.nvmrc` included

I'll leave this open as a low-priority feature request for now. I think the current behaviour makes sense as the default, so then maybe we need to add a "force" or "always" option somehow, e.g. `"bumpVersion": "always-patch"`

**Comment by rarkins** [comment]
Right now this didn't fit into our architecture so is too hard to do
