### ISSUE TITLE
python requirements.txt matched but not take as package files

### ISSUE THREAD

**Issue by WangZhiYao** [renovatebot/renovate#30701]
### What would you like help with?

I think I found a bug
the minimal reproduction template repository is here: [renovate-reproduction-template](https://github.com/WangZhiYao/renovate-reproduction-template).

### How are you running Renovate?

Mend Renovate hosted app on github.com

### Please tell us more about your question or problem

requirements.txt is in the root directory of my project
here is my requirements.txt content:

```
APScheduler==3.10.4
beanie==1.26.0
paho-mqtt==2.1.0
pydantic==2.8.2
pydantic-settings==2.3.4
requests==2.32.3
pytz==2024.1
motor==3.5.1
```

### Logs (if relevant)

<details><summary>Logs</summary>

```

DEBUG: Matched 1 file(s) for manager dockerfile: Dockerfile
DEBUG: Matched 1 file(s) for manager github-actions: .github/workflows/notify_update.yml
DEBUG: Matched 1 file(s) for manager pip_requirements: requirements.txt
DEBUG: manager extract durations (ms)
{
  "managers": {
    "dockerfile": 69,
    "github-actions": 68,
    "pip_requirements": 69
  }
}

DEBUG: Found dockerfile package files
DEBUG: Found github-actions package files
DEBUG: Found 2 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "master"
  "stats": {
    "managers": {
      "dockerfile": {
        "fileCount": 1,
        "depCount": 1
      },
      "github-actions": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 2,
      "depCount": 2
    }
  }
}

```

</details>

_Originally posted by @WangZhiYao in https://github.com/renovatebot/renovate/discussions/30199_

**Comment by RahulGautamSingh** [comment]
There are some unicode charcherts are there at the beginning of your `requirements.txt` file. Try copying it and you will find it.

**Comment by WangZhiYao** [comment]
@RahulGautamSingh 

I'm using `pip freeze > requirements.txt` command in Windows to generate `requirements.txt` file, and that makes the file was encoded as UTF-16LE. I never considered this aspect. 

Thanks for your help.
