### ISSUE TITLE
typo in the doc

### ISSUE THREAD

**Issue by noraj** [renovatebot/renovate#3072]
It is not a bug in Renovate but a typo in the documentation.

Page: https://renovatebot.com/docs/dependency-pinning/

Sentence:

> This might require even manually looking through the lock file diffs line by line. Maybe dep blahblah also broke at teh same time, to make it even harder.

of course it is `the` instead of `teh`.

PS : as long as the doc is created with MkDocs, why don't you open-source the user documentation in addition to the pro documentation and the dev documentation ?

**Comment by rarkins** [comment]
Thanks for reporting. The user documentation is already in this repo under `website/docs`

**Comment by noraj** [comment]
@rarkins My bad, I only saw `docs` which contains the dev docs but i didnt see `website/docs`.

**Comment by rarkins** [comment]
Yeah, I thought again about moving it all to docs/website but the reason for the current structure was that I wanted to eventually open source more of the site, not just the docs
