### ISSUE TITLE
Bundler: use specified Ruby version

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3074]
In Bundler, the required Ruby version can be specified: https://bundler.io/v1.12/gemfile_ruby.html

When running using the Ruby 2.6.0 Docker image, you can get these types of errors:

```
Fetching gem metadata from https:\/\/rubygems.org\/.........
Fetching gem metadata from https:\/\/rubygems.org\/..
Could not find gem 'ruby\u0000 (~> 2.5.3)' in the local ruby installation.
The source contains 'ruby\u0000' at: 2.6.0.0
```

Options:
1. Dynamically pick matching Bundler Docker image based on what's in the `Gemfile` (preferred, but hardest)
2. Specify Bundler to ignore this value (there doesn't appear to be an option for this)
3. Delete the Ruby version from the `Gemfile` before running `bundle lock`. But could this generate wrong results?

**Comment by rarkins** [comment]
@bjeanes for reference, can you tell me how/where you specify the Ruby version in your `Gemfile`?

**Comment by rarkins** [comment]
This Dockerfile preinstalls a number of Ruby versions so that they can be more quickly switched between: https://github.com/tcnksm/dockerfile-rbenv/blob/master/Dockerfile

**Comment by bjeanes** [comment]
> @bjeanes for reference, can you tell me how/where you specify the Ruby version in your `Gemfile`?

this is the first few lines of my `Gemfile` which is indicative of most of it (other than groupings):

``` ruby
# frozen_string_literal: true

source "https://rubygems.org"
ruby "~> 2.5.3"

# Force Github repos to load over HTTPS, instead of insecure git: protocol
# This will be the default in Bundler 2, and this code can be removed
# https://stackoverflow.com/a/39190158/56690
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Boot
gem "bootsnap", "~> 1.3", require: false
gem "dotenv-rails", "~> 2.6", require: "dotenv/rails-now", groups: %i[test development]

# Rails
gem "rails", "~> 5.2.2"

# Database
gem "pg", "~> 1.1"

# Web server and middleware
gem "puma", "~> 3.12"
gem "rack-cors", "~> 1.0", require: "rack/cors"
```

**Comment by bjeanes** [comment]
> 1. Dynamically pick matching Bundler Docker image based on what's in the `Gemfile` (preferred, but hardest)

Agreed that this would be ideal.

> 2. Specify Bundler to ignore this value (there doesn't appear to be an option for this)
> 3. Delete the Ruby version from the `Gemfile` before running `bundle lock`. But could this generate wrong results?

You could potentially strip out that line from the `Gemfile`. The ruby version check only occurs if it is specified (much like `engines` in `package.json`).

It _could_ generate wrong results only where gems specify the versions they support, which would affect which candidates Bundler would consider. For the most part, if you could identify the correct _minor_ version of Ruby, this would likely be very rare.

**Comment by rarkins** [comment]
So it seems like:
- `Gemfile` can specify the `ruby` version to use, and Bundler will exit if there's a mismatch. This ruby version can be a range.
- The `Gemfile.lock` notes which version of Bundler was used to generate the lock file. It will warn - not error - if the version is different, and also I think it might *update* the lock file each time to match whatever we ran with

For Ruby version, in the short term we can remove the ruby line from `Gemfile` prior to `bundle lock` and it should satisfy most cases, but in the medium-long term we should always run `bundle lock` from the correct Ruby so we always end up with correct versions.

For Bundler version, ideally we should also run with the version specified in `Gemfile.lock`.

One option is to have a large number of Docker images with many combinations of Ruby and Bundler and then do some type of dynamic tag selection.

Another option is to have some type of "mega" image that preinstalls many versions of Ruby and Bundler such that we can use the same image each time but pick which Ruby/Bundler versions to run.

The two main ways to configure Ruby version are RVM and `rbenv`. rbenv seems lighter weight and better suited to Renovate's needs. We can consider whether to install every single Ruby version for the past x months/years, or perhaps the latest patch of each minor release.

We also need to work out how to specify Ruby version. You can do it manually, e.g. `rbenv shell 2.5.3` or via a `.ruby-version` file or `RBENV_VERSION` variable. We need to consider also what to do if a repository has the Ruby specified in more than one location, e.g. a `ruby` line in the `Gemfile` but also in `.ruby-version`. I think:
- If the repo already has a `.ruby-version` then leave it as-is, even if it conflicts with the ruby version in `Gemfile`
- If not, then we write it before `bundle lock` using the version found in `Gemfile`

We may also need to support multiple versions of Bundler. Ideally these versions can be stored independently of the Ruby versions, i.e. so we don't need to install X versions of Bundler into Y versions of Ruby.

Note: Heroku doesn't actually support customisable versions of Bundler! Should we? Right now they even use `v1.15.2`. More on their reasoning here: https://devcenter.heroku.com/articles/bundler-version

Also, some repositories do this to keep rbenv and Bundler in sync:
![image](https://user-images.githubusercontent.com/6311784/51243309-7a4fbe00-1982-11e9-8928-2f99c5c714d7.png)

References:
[rbenv](https://github.com/rbenv/rbenv)
[rbenv-aliases](https://github.com/tpope/rbenv-aliases)
[rbenv-bundler](https://github.com/carsomyr/rbenv-bundler)
[rbenv-bundler-ruby-version](https://github.com/aripollak/rbenv-bundler-ruby-version)

**Comment by bjeanes** [comment]
There's also chruby

**Comment by rarkins** [comment]
Yes that might be even better

**Comment by rarkins** [comment]
https://www.ruby-lang.org/en/downloads/branches/

**Comment by rarkins** [comment]
I'm nearly done with this, but not 100% sure I've got it right. Here's the plan:

- Install multiple Ruby versions in parallel into a Docker image
- Fall back to latest Ruby if none is specified via `.ruby-version` or `RUBY_VERSION`
- Install the specified Bundler version at "run time" (when we call `bundle lock`) and fall back to latest

In theory the above means we can use the exact Ruby and Bundler versions that the project uses.

Here are the difficult parts:

1. Ruby version may be specified inside the `Gemfile` and may also be a *range*. Somewhere we need to convert this from a range to a version unless there's also a `.ruby-version` present

2. We can find the version of Bundler from the `Gemfile.lock` "BUNDLED WIDTH" statement. It should be an exact version so works well for us

3. It's probably not possible to dynamically install Ruby at run time - it takes too long - and is quite burdensome to install every single version into the container. But if we don't support every single possible version that users will have, then it's guaranteed at some point to have a mismatch. 

Possible ways we can make things simpler:
- Insist that repositories have a `.ruby-version` if they need a specific version of Ruby (i.e. instead of us extracting a range from `Gemfile`)
- Support only stable/non end of life Ruby versions in our image. To use Renovate's Bundler functionality you must be on a supported version of Ruby

But in general I don't like such restrictions unless they're absolutely necessary.

@bjeanes @sleekybadger what do you think?

**Comment by rarkins** [comment]
Actually, a minute after I typed that I think the solution hit me. Instead of a big image containing many Ruby versions, I think I just need to publish *many* images with different tags - one for each Ruby version. That way although it's somewhat painful to build every image, at least it's only done once.

**Comment by sleekybadger** [comment]
I think it’s okay to support ruby versions above latest EOL. 

P.S. Check [dobi](https://github.com/dnephin/dobi). I’ve been used it few times to automate such build tasks.

**Comment by rarkins** [comment]
Actually the EOL problem should be self-fixing soon anyway because we don’t *delete* old tags as we progress - they’ll still exist, we just won’t build/refresh them anymore.

**Comment by bjeanes** [comment]
I don't think you need to support exact versions if you are able to strip the `ruby` call from the Gemfile. Just the latest patch version of each minor version (whether supported or not). 2.3.x, 2.4.x, 2.5.x, etc. For bundling purposes, the exact versions should rarely matter much.

**Comment by rarkins** [comment]
I think once we have a process in place to always build a new image/tag when it’s released, then we’ll naturally end up with a set of “trailing” releases anyway. Eg once 2.6.1 is out we need to build it, and later for 2.6.2. So then there’s no point supporting “only” 2.6.2 because we have 2.6.1 anyway. The main inconvenience is just up front when I need to build 20 images now
