### ISSUE TITLE
lockFileMaintenance settings in packageRules not being applied correctly

### ISSUE THREAD

**Issue by alan-agius4** [renovatebot/renovate#3075]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
When I add `lockFileMaintenance` into a `packageRules` section it doesn't have any effect.
```js
"packageRules": [
  {
    "paths": ["packages/nested/package.json"],
    "lockFileMaintenance": {
      "enabled": true,
      "schedule": [
        "every weekday"
      ]
    }
  }
],
```

However, if I place this under the root section it does update all package locks.

**Did you see anything helpful in debug logs?**
https://pastebin.com/aKihq0Sm

**Expected behavior**
That lock file maintenance can be executed on specified packages, based on the `packageRules`

**Additional context**
@rarkins, mentioned that this configuration should be supported. In fact it seems that it is being parsed incorrectly to;
```js
 "packageRules": [
      {
        "paths": [
          "packages/nested/package.json"
        ]
      },
      {
        "paths": [
          "packages/nested/package.json"
        ],
        "updateTypes": [
          "lockFileMaintenance"
        ],
        "enabled": true,
        "schedule": [
          "every weekday"
        ]
      }
    ]
```

**Comment by rarkins** [comment]
Somewhere in the code we're looking for something like `if (config.lockFileMaintenance.enabled) {// do it}` so it's not found when it's embedded in a packageRule. We need to think or a way to either rewrite the logic *or* to change how we massage the packageRule.

A good first step would be a simple repo where we can reproduce it.
