### ISSUE TITLE
Reached PR creation limit is not respected with self-hosted approach

### ISSUE THREAD

**Issue by rapgut-WittGruppe** [renovatebot/renovate#3077]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate is running in a docker container. It logs `Reached PR creation limit` after only 2 Pull Requests. The flag `--pr-hourly-limit` is not being respected and omitting the flag does not result in an unlimited PR creation count.

**Did you see anything helpful in debug logs?**
```
 INFO: Reached PR creation limit - skipping branch creation
 INFO: Reached PR creation limit - skipping branch creation
 INFO: Reached PR creation limit - skipping branch creation
```

**To Reproduce**
1.  Run renovate-cli on any repository
2.  See in the DEBUG log that only 2 PR's can be created even though it should be unlimited

**Expected behavior**
The cli-flag should be respected and the default should be unlimited.

**Comment by rarkins** [comment]
If the repository has a config that specifies PR limits, it will override the config specified in the bot. Are you using the "config:base" preset in the repository's config, for example?

Recommended approach: make sure you are not specifying a config in repositories that overrides your bot's config

Alternative approach: use `--force-cli=true` flag in bot to force override all settings.

Also, in future it's preferred that you raise questions into the [config-help](https://github.com/renovatebot/config-help) repository first. They can always be transferred here if/when confirmed to be a bug.

**Comment by rarkins** [comment]
FYI for clarity: the bot itself has no default pr hourly limit. The only way you are getting one is if you have configured one.

**Comment by rapgut-WittGruppe** [comment]
Yeah this was exactly the problem. We are extending from "config:base" which has the 2 hour limit. Thanks for the speedy help.

**Comment by danielbayerlein** [comment]
Have a look at the [ignorePresets](https://renovatebot.com/docs/configuration-options/#ignorepresets) configuration option.
