### ISSUE TITLE
Noise on issues/PRs from Renovate PR changelog links

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#3082]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The filtering of changelog entries in Renovate PR descriptions to ensure that they don't cause issue backlinks isn't always working, in that:
* the issues still get linked with a real link (rather than the redirect domain), so cause linkback spam on the issues in question
* (less important) the formatting of the changelog ends up broken

**To Reproduce**
Follow one of the issues linked in the Renovate PR here:
https://github.com/mozilla/treeherder/pull/4472

...eg:
https://github.com/yannickcr/eslint-plugin-react/issues/2131

...and see all of the links backs that are from Renovate.

**Expected behavior**
The changelog section rewritten to use the `togithub.com` redirect domain.

**Comment by edmorley** [comment]
Thank you :-)

I'm guessing it's due to the use of the reference link style?
https://github.com/yannickcr/eslint-plugin-react/blame/e63596406028aa1177056192694d3e7557a29016/CHANGELOG.md#L18

**Comment by rarkins** [comment]
@edmorley 	yes I think you're exactly right

**Comment by rarkins** [comment]
This fix should be rolled out to the app shortly. As you're probably aware though, even once we update the PRs across github.com, it doesn't *unlink* any of the existing "link spam" so it will only help for future PRs.

**Comment by edmorley** [comment]
Amazing - thank you for the quick response!
