### ISSUE TITLE
When enabled `osvVulnerabilityAlerts` creates updates for inirect dependencies

### ISSUE THREAD

**Issue by wolf-michl** [renovatebot/renovate#30873]
When using `osvVulnerabilityAlerts` we notice that indirect go dependencies are updated. However to [documentation](https://docs.renovatebot.com/configuration-options/#osvvulnerabilityalerts) states that only direct dependencies will get vulnerability alerts.

For example we have this renovate config:
```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "osvVulnerabilityAlerts": true,
  "vulnerabilityAlerts": {
      "enabled": true
  }
}
```
a GitHub Token and a go.mod file like

```go
module example.com/m

go 1.21

require (
  github.com/argoproj/argo-cd/v2 v2.3.17
  k8s.io/kubernetes v1.24.2 // indirect
)
```
If we now run renovate we get security updates for `k8s.io/kubernetes` but since it is an indirect dependency that should not happen. When we set `osvVulnerabilityAlerts` to `false` we do not get the PR.

_Originally posted by @samuelstadler in https://github.com/renovatebot/renovate/discussions/20542#discussioncomment-10337429_

The [doumentation](https://docs.renovatebot.com/configuration-options/#osvvulnerabilityalerts) states:

You will only get OSV-based vulnerability alerts for direct dependencies.

It still creates updates for indirect dependencies, even if no direct dependency is being updated, which would lead to an update of the indirect dependency.

This leads to unwanted behaviour:
We get updates of indirect dependencies, even if the direct dependency leading to the indirect dependency is not being updated. This could then introduce breaking behaviour.

The default of not updating indirect dependencies is not being taken into account here, which seems to be the root cause for this issue.

**Comment by rarkins** [comment]
@wolf-michl users are asked not to open issues directly in this repo. This is not a bug, just needs updated documentation.
