### ISSUE TITLE
Updating Pipfile.lock fails with PermissionError

### ISSUE THREAD

**Issue by martin-sucha** [renovatebot/renovate#3089]
**What Renovate type are you using?**
Renovate Gitlab app

**Describe the bug**
Updating Pipfile.lock fails with:
```
Command failed: docker run --rm -v /mnt/renovate/gl/horam/horam2:/mnt/renovate/gl/horam/horam2 -e LC_ALL -e LANG -e PIPENV_CACHE_DIR -w /mnt/renovate/gl/horam/horam2 renovate/pipenv pipenv lock
[...snip...]
PermissionError: [Errno 13] Permission denied: '/mnt/renovate/tmp'
```

This can be seen in the MR https://gitlab.com/horam/horam2/merge_requests/2 (I guess this will change when fixed though) and also dashboard https://renovatebot.com/dashboard#gitlab/horam/horam2/40449484

**To Reproduce**

1.  Create repository using Pipenv on Gitlab.com
2.  Configure renovate bot to use Pipenv

**Expected behavior**
Updating lock file should not fail.

**Comment by rarkins** [comment]
Thanks for raising the issue. I'll check the bot's directory permissions first to make sure there's nothing wrong there.

**Comment by martin-sucha** [comment]
Hi @rarkins, thanks for looking into this! If there is any way I can help you with fixing the issue, please let me know.

**Comment by rarkins** [comment]
Fixed in https://github.com/renovatebot/renovate/commit/cbc29acb61dd4c8fe13c18a4358c9ac127055bdb

Thanks for reporting, @martin-sucha. You should be able to tick the "rebase" checkbox in your PR and have Renovate recreate/fix the PR the next time it runs on your repo

**Comment by martin-sucha** [comment]
It works! Thank you!
