### ISSUE TITLE
Missing release notes for django-filter, github release notes available

### ISSUE THREAD

**Issue by Fandekasp** [renovatebot/renovate#3092]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
release notes in github releases (7h ago): https://github.com/carltongibson/django-filter/releases
package to upgrade: django-filter
PR created 6h ago (release notes were therefore already available) without release notes:
![](https://i.imgur.com/JocLxDZ.png)

**Comment by rarkins** [comment]
This might be related to the non-semantic nature of their "Version 2.1.0" release naming. I'll take a look.

**Comment by rarkins** [comment]
To reproduce: create a repo with a `requirements.txt` containing the line `django-filter==2.0.0` and a `renovate.json` containing `{}`. Run Renovate and verify if the changelogs/releases are found.

Maybe when we are trying to match release headings we can add a Massage to remove "Version " before comparing. We are probably trying to compare "2.0.0" with "Version 2.0" and that's returning false. Comparing "2.0" or "v2.0" would probably return true.
