### ISSUE TITLE
Automerge can happen after a force-push without waiting for tests

### ISSUE THREAD

**Issue by abraham** [renovatebot/renovate#3099]
**What Renovate type are you using?**

Renovate GitHub App

**Describe the bug**

V8.0.0 of ts-node was released an update PR was opened, and the tests pass. v8.0.1 of ts-node is released and the PR is force-pushed with the new version, the PR is immediately merged without waiting for a new CI run.

**Did you see anything helpful in debug logs?**

Based on [40758419](https://renovatebot.com/dashboard#github/abraham/abrah.am/40758419) it looks like the PR was updated and merged in the same job.

**To Reproduce**

Get an update PR, have CI succeed, find new update for same package.

**Expected behavior**

I would expect force-pushing a PR to wait until CI runs succeed to merge.

**Screenshots**

This is a screenshot of the PR just after the PR was merged showing pending checks:

![screenshot from 2019-01-21 20-22-13](https://user-images.githubusercontent.com/3341/51508573-7923f400-1dbb-11e9-9aa1-a74d03b69c73.png)

**Additional context**

This seems to have happened on a half-dozen or so of my repos.

**Comment by rarkins** [comment]
I missed the exact log link you gave originally. Copy/pasting from that run:

```
No branch protection found
getBranchStatus(renovate/ts-node-8.x)
"state":"pending","statuses":[],"msg":"branch status check result"
"result":{"total_count":0,"check_runs":[]},"msg":"No check runs found"
automerge":true,"automergeType":"pr","automergeComment":"automergeComment","msg":"Checking #217 for automerge"
PR is configured for automerge
Automerging #217
mergePr(217, renovate/ts-node-8.x)
```

**Comment by rarkins** [comment]
Added an extra branch status check to check for this edge case where we're pushing to a PR that had previously passed tests. Thanks @abraham

**Comment by abraham** [comment]
Awesome! Thanks.
