### ISSUE TITLE
Overly strict engines check

### ISSUE THREAD

**Issue by zephraph** [renovatebot/renovate#3104]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
The CLI has a [strict engines check](https://github.com/renovatebot/renovate/blob/e8a487a90f8e5cc05ea813685dfec6e1a9925491/package.json#L73) which is causing parts of our CI to fail due to not being able to go through the install process. Does it _absolutely_ require `>=10.14`? Could it just be `>=10`?

**Comment by rarkins** [comment]
We can make it `>=10.13` as that was when v10 went LTS
