### ISSUE TITLE
Renovate is no longer creating MRs

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#3114]
**What Renovate type are you using?**
Renovate Docker

**Describe the bug**
Using the Master issue approval, I ticked a load of dependencies to tell Renovate to generate me some MRs

However, those MRs are never created and I have no idea why. Checking the renovate logs in my CI, it thinks `composer` has errored even though `composer` is producing a successful response.

**Did you see anything helpful in debug logs?**
Full log: https://gitlab.com/momentumstudio/renovate/-/jobs/151403557

The project I am expecting to create MRs is `stafford_taxis`

**To Reproduce**

No idea really.

**Expected behavior**
After ticking items in the master issue, I expect renovate to either error (not create the MR) or create the MR. The successful response should be creating MRs.

**Screenshots**
N/A

**Additional context**

**Comment by rarkins** [comment]
No access to that log. Can you copy it to a gist?

**Comment by Jamesking56** [comment]
Sorry @rarkins - https://gist.github.com/Jamesking56/de96694c59390cbe90fc3e205f444732

**Comment by rarkins** [comment]
It says "branch created". Does the branch exist? Your config also has ":prNotPending" in its config, so I wouldn't expect a PR to be raised immediately after the branch is created.

**Comment by Jamesking56** [comment]
Ah yeah I think its the `:prNotPending` as the next run created the MR. Cheers :+1:
