### ISSUE TITLE
Add PR suffix to automerge commit titles

### ISSUE THREAD

**Issue by zephraph** [renovatebot/renovate#3116]
**What would you like Renovate to be able to do?**
When automerging a PR, add the PR # at the end of the commit message

**Describe the solution you'd like**
For [this commit](https://github.com/artsy/reaction/commit/59e805223d54dca29bf013ba42a0be892d5c92af) the message would be be 

```
Update dependency @artsy/palette to v2.35.0 (#1964)
```

**Additional context**

This just makes it a little easier to trace back to the original PR.

**Comment by rarkins** [comment]
It looks like picking a customer commit title is possible via the API: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

Need to check if it behaves as expected for all types of commit though (merge, squash, rebase).

Then next question is whether to do this automatically or via config. Usually we want to make everything configurable.

**Comment by AhmedAbdraboh** [comment]
We can add the PR number to the options object in mergePR method with the key commit_message
https://github.com/renovatebot/renovate/blob/master/lib/platform/github/index.js#L1357
so the options can be 
  const options = {
    commit_message: ` (#${prNo})`,
  };

**Comment by rarkins** [comment]
That's the right API call/parameter, but I think you'll need to specify the *full* commit message, not just the suffix you wish to add. i.e. it will be something like this: `${pr.title} (#${pr.number})`

**Comment by rarkins** [comment]
GitHub's API didn't behave as we expected. Therefore this might need to be done manually and also not for every merge type.

If you merge with rebase, it would have to match the commit. But you can't know the PR number before you make the commit.

If you *squash* merge, then it's probably possible - update the PR title and then squash merge.
