### ISSUE TITLE
Lockfile update rebasing problem

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3123]
Not reproduced/confirmed yet, but I suspect the new lock file update feature doesn't accurately handle rebases when master changes. Discussion on it starts here: https://github.com/renovatebot/renovate/issues/1382#issuecomment-457916018

Cc @felixfbecker who noticed it

**Comment by xPaw** [comment]
We've also run into this problem today: https://github.com/thelounge/thelounge/pull/2947
