### ISSUE TITLE
cannot enable renovatebot

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3128]
I have installed renovatebot but it doesn't open any PRs for my public repos.
e.g. no PR for this one https://github.com/piotr-s-brainhub/joi-router using `package.json`

<img width="1432" alt="screen shot 2019-01-28 at 16 26 09" src="https://user-images.githubusercontent.com/20856232/51846244-812ee700-2319-11e9-9a6a-12f5417959f4.png">
<img width="1427" alt="screen shot 2019-01-28 at 16 26 28" src="https://user-images.githubusercontent.com/20856232/51846246-81c77d80-2319-11e9-81c2-9e3d0cab40ee.png">

**Comment by rarkins** [comment]
Renovate skips forked repositories by default. If you want it to run then you'll need to add a `renovate.json` file to the repo with `"includeForks": true` in its config.

**Comment by rarkins** [comment]
This is all that's been detected for your account:

![image](https://user-images.githubusercontent.com/6311784/51884692-a4dd4600-2388-11e9-87a6-7b68995f6f01.png)

i.e. all public

**Comment by piotr-s-brainhub** [comment]
@rarkins 

sorry, I have already used my free trial so @pavelbely helped me to activate for `dmx-io/dmx-inventory` (a private repo)

**Comment by rarkins** [comment]
It looks like it ran about 7 minutes ago

**Comment by piotr-s-brainhub** [comment]
OK, now I can see

**Comment by piotr-s-brainhub** [comment]
@rarkins 

we configured renovate to work for all repos in `dmx-io` organization but it opened only for some of them:
- `dmx-dashboard`
- `dmx-appraise-it`
- `npm-edmunds`
- `dmx-vehicle-info`
- `dmx-authentication`
- `dmx-api-gateway`
- `dmx-appraisals`
- `dmx-inventory`
- `npm-dmx-utils`

but for most repos after several hours there's still no PR:
- core-microservice
- dmx-admin-2
- dmx-admin
- dmx-auctions
- dmx-cli
- dmx-data-ingestion
- dmx-grade-it
- dmx-grades
- dmx-media
- dmx-mobile
- dmx-notifications-legacy
- dmx-notifications
- dmx-payments
- dmx-reports
- dmx-scheduling
- dmx-slackbot
- dmx-webhooks
- ingestion-files
- koa-joi-router
- msvc-market-data
- nodejs-buildpack
- npm-black-book
- npm-carfax
- npm-data-models
- npm-dmx-sdk
- npm-fca
- npm-forest-data-models
- npm-galves
- npm-grade-it-tools
- npm-kelley-blue-book
- npm-koa-qs
- npm-logform
- npm-logger
- npm-manheim
- npm-market-data
- npm-motor
- npm-winston-slack
- npm-winston
- test-helpers
- validation-schemas
- winston-loggly

So what is the maximum time to open a PR when renovate is activated or some library is available in a new version?
Can this time be lower after upgrading our plan to `Organization Large`?

**Comment by rarkins** [comment]
@piotr-s-brainhub those repositories were all in the job queue. The account `dmx-io` currently has no plan detected (not even a trial) so therefore jobs take the lower priority. Priority as you probably guessed goes Large -> Medium -> Small. I bumped your jobs up to high priority *manually* just now so that you can see the effect.

**Comment by piotr-s-brainhub** [comment]
Thanks very much. @rarkins

**Comment by piotr-s-brainhub** [comment]
@rarkins 

do you happen to know why I have `### Lock file problem` - `An unexpected error occurred: "https://registry.yarnpkg.com/@dmx%2fnpm-logger: Not found".` at https://github.com/dmx-io/npm-black-book/pull/17 ?

I hardcoded the NPM token and it seems to work in all the microservices and some libraries in `dmx-io` organization but for many libraries I get `Lock file problem`

**Comment by rarkins** [comment]
@piotr-s-brainhub please raise an issue in the config help repo and include as much info as possible on your config and what you have observed. e.g. do private modules work on some repos and not others? for some packages but not others? etc.

That error message is generated by Yarn itself btw.

**Comment by piotr-s-brainhub** [comment]
@rarkins 

I created lockfile issue in https://github.com/renovatebot/renovate/issues/3184
