### ISSUE TITLE
If the org contains a renovate-config repo, the Configure Renovate PR should automatically extend it

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#3130]
**What Renovate type are you using?**
Renovate GitHub App

Frequently getting Configure Renovate PRs where people don't know that they need to change the `extends` field before merging. It would be great if this could be automatic.

**Comment by rarkins** [comment]
Good idea, but one small challenge I need to overcome first - some organisations have a `github.com/company/renovate-config` repository that they publish as an npm-hosted preset `@company/renovate-config`. So I first need to work out a foolproof way to know and remember which is which.
