### ISSUE TITLE
npmToken with template secrets and npmrc does not work

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#31303]
For context, my original setup—which needed migration—looks like this:

```json
"encrypted": {
  "npmToken": "wcFMA/xDdHCJBTolAQ/........."
}
"npmrc": "@<ORG_NAME>:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}",
```

> [!NOTE]
> `<ORG_NAME>` is replaced with the actual organization name that contains private NPM packages

I couldn't get `npmToken` to work again after migrating to secret and unwrapping it from the `encrypted` object. Renovatebot complains that it has no access to the private packages, indicating it has issues access the secret.

I've tried:

- Copying the old encrypted token and pasting it as a secret ("migrate" secret)
- Copying the unencrypted token and pasting it

Neither worked. 

```json
// WARNING: This does not work
"npmToken": "{{ secrets.NPM_TOKEN }}",
"npmrc": "@<ORG_NAME>:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}",
```

What worked for me is to introduce it as a `hostType` entry:

```json
"hostRules": [
  {
    "matchHost": "https://npm.pkg.github.com/",
    "hostType": "npm",
    "token": "{{ secrets.NPM_TOKEN }}"
  }
],
"npmrc": "@<ORG_NAME>:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}",
```

_Originally posted by @terrymun in https://github.com/renovatebot/renovate/discussions/31253#discussioncomment-10582777_

**Comment by terrymun** [comment]
Thanks for looking into this @rarkins ❤️

**Comment by viceice** [comment]
we should deprecate `npmToken` and migrate it to a host rule

**Comment by btimo** [comment]
Quick question around this solution:
We are using the `secrets` object to define the `hostRules.*.token`.
But then we are using the env var `NPM_TOKEN` in the `npmrc`.
What's the relation between the `token` and the env var `NPM_TOKEN`?
What do we write in the `npmrc` property if the secret is not named `NPM_TOKEN`?

Should we use the same name in both properties, as in the example below?
```
"hostRules": [
  {
    "matchHost": "https://npm.pkg.github.com/",
    "hostType": "npm",
    "token": "{{ secrets.RANDOM_SECRET_NAME }}"
  }
],
"npmrc": "@<ORG_NAME>:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${RANDOM_SECRET_NAME}",
```

**Comment by rarkins** [comment]
@btimo please use discussions for questions, not issues

**Comment by zharinov** [comment]
> please use discussions for questions, not issues

The question is good, though

**Comment by zharinov** [comment]
@btimo So let me answer this one here: from [what I see here](https://github.com/renovatebot/renovate/blob/bc4077e0254e5a508d721d37f44801588c730e1c/lib/config/decrypt.ts#L176), the `${NPM_TOKEN}` is just a hard-coded placeholder to be replaced with `npmToken` value, so it has nothing to do with any sort of external environment holding `NPM_TOKEN` key.

**Comment by TrejGun** [comment]
Hey guys! I have a very similar setup
in my case I use I have two files

```json
{
   ...
   "npmrc": "@ethberry:registry=https://npm.pkg.github.com/",
}
```

```json
{
  "extends": [
    "github>ethberry/renovate-config:rules"
  ],
  "hostRules": [
    {
      "matchHost": "https://npm.pkg.github.com/",
      "hostType": "npm",
      "token": "{{ secrets.GITHUB_TOKEN_ETHBERRY }}"
    }
  ]
}
```

I mean there is currently no need to add `//npm.pkg.github.com/:_authToken=${NPM_TOKEN}`
