### ISSUE TITLE
Gradle: /usr/bin/gradle not found instead of using the wrapper

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#3135]
**What Renovate type are you using?**
Renovate CLI. Both directly via node or via docker.

**Describe the bug**

When I enable gradle, I'm expecting renovate to use the gradlew wrapper instead. But yet it tries to reach `/usr/bin/gradle` which is not there (not installed). I've tried to enable gradle-wrapper in `renovate.json` too, but it does not change anything (not sure what it is for, [the docs not explaining totally](https://renovatebot.com/docs/configuration-options/#gradle-wrapper)). 

To sum up, my renovate.json contains:

```json
{
        ...
	"gradle": { "enabled": true		 },
	"gradle-wrapper": { "enabled": true		 },
}
```

**Did you see anything helpful in debug logs?**

```
$ node lib/renovate.js --token "XXX" bagage/gradle-template
 INFO: Extracting dependencies from all gradle files (repository=user/repository)
 WARN: Gradle command gradle --init-script init.gradle dependencyUpdates -Drevision=release failed. Exit code: 127. (repository=user/repository)
       "err": {
         "name": "ChildProcessError",
         "code": 127,
         "childProcess": {},
         "stdout": "",
         "stderr": "/bin/sh: 1: gradle: not found\n",
         "message": "Command failed: gradle --init-script init.gradle dependencyUpdates -Drevision=release\n/bin/sh: 1: gradle: not found\n `gradle --init-script init.gradle dependencyUpdates -Drevision=release` (exited with error code 127)",
         "stack": "ChildProcessError: Command failed: gradle --init-script init.gradle dependencyUpdates -Drevision=release\n/bin/sh: 1: gradle: not found\n `gradle --init-script init.gradle dependencyUpdates -Drevision=release` (exited with error code 127)\n    at callback (/home/user/code/renovate/renovate/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:298:5)\n    at ChildProcess.emit (events.js:182:13)\n    at maybeClose (internal/child_process.js:961:16)\n    at Socket.stream.socket.on (internal/child_process.js:380:11)\n    at Socket.emit (events.js:182:13)\n    at Pipe._handle.close (net.js:595:12)"
       }
 INFO: Gradle Wrapper (repository=user/repository, depType=gradle-wrapper)
       "purl": "pkg:gradleVersion",
       "depName": "gradle",
       "currentValue": "5.1.1",
       "lineNumber": 2,
       "versionScheme": "semver",
       "gradleWrapperType": "all"
 INFO: Found gradle-wrapper package files (repository=user/repository)
```

**To Reproduce**

1.  Fork repository `https://github.com/bagage/gradle-template`
2.  Remove `gradle` from path if present (`which gradle` should fail)
3. Run `node lib/renovate.js --token XXX you/gradle-template

**Expected behavior**
I'd expect renovate to use `./gradlew` binary instead of `/usr/bin/gradle`. And then to create [this MR](https://github.com/bagage/gradle-template/pull/3). Instead, it fails. (I simlinked gradlew to /usr/bin/gradle to make renovate create the PR).

**Screenshots**

**Additional context**
The issue also raises when using the docker image in which `gradle` binary is not installed.

**Comment by rarkins** [comment]
Actually `gradle-wrapper` in config is an option to upgrade the version of gradle specified in the wrapper. It's not an option that's meant to say "run gradle using the version of gradle in gradle wrapper". This would be an enhancement/feature, not a bug.

**Comment by rarkins** [comment]
Also, if you are running Renovate locally and want Renovate to run gradle, it's a pre-requisite that you have a valid gradle installed as well. The only binaries that Renovate bundles with `npm i -g renovate` are `npm` and `yarn`, and those will be going away in the next major release too.

i.e. this step is kind of the opposite of what you should be doing if you want to run Gradle via renovate CLI:

> 2. Remove gradle from path if present (which gradle should fail)

i.e. it's our expectation that you should be *installing* gradle before running, not uninstalling.

An alternative is setting `--binary-source=docker` if you have Docker installed. In that case it will pull and run a version of Gradle from docker hub.

Now if it fails in Renovate's official Docker image, that's another matter. Ideally we should be shipping the Docker image with a default binary version installed.

**Comment by bagage** [comment]
> Also, if you are running Renovate locally and want Renovate to run gradle, it's a pre-requisite that you have a valid gradle installed as well. 
I'm not sure to understand it fully, I am not much familiar with gradle. But I don't get why you pre-requisite that gradle is installed on the system, while [gradle itself argues to use the wrapper instead](https://docs.gradle.org/current/userguide/gradle_wrapper.html)? Gradle projects do not need gradle to be installed, because it will be downloaded by the wrapper the first time you run it. Am I wrong?

**Comment by rarkins** [comment]
Hi, thanks for the extra perspective. I'm not an active Gradle user so I wasn't aware of that approach and will research it more. I'm actually hoping to *remove* the need for the Gradle binary for extracting dependency references though. If you see any other gaps w.r.t. Gradle please feel free to raise as many feature requests as you think appropriate.

**Comment by bagage** [comment]
Thanks @rarkins for the explanations, much appreciated. I investigated the different approachs you suggested:

- `--binary-source=docker` indeed runs gradle via docker, so we do not need it installed. Unfortunately I need to provide extra files to docker to make it works, eg I need to provide a `~/.gradle/gradle.properties` file containing some variables. It seems not supported so I cannot use this approach (yet).
- I started to look if `gradle` could be replaced via `./gradlew` (via a config boolean for instance), but actually only `.gradle` files are kept when the project is retrieved so it is not available.

1. I could either add an optional parameter for extra docker variables for first approach, or 
2. I could keep `./gradlew` executable and `./gradle` folder when doing the retrieving, so that it is available to use.

Do you think one of these approach makes sense? Or due to the new gradle plugin/else, they won't be integrated anyway because not the valid approach?

**Comment by bagage** [comment]
I've POCed 2nd approach on https://github.com/bagage/renovate/tree/gradle_usegradlew, and it works great. If you think it's OK, I can clean it up and do a PR for it, adding an option in `gradle` config for it (`useGradlew: boolean` for instance?).

**Comment by rarkins** [comment]
@bagage if you need extra files, what if you run with `--git-fs=https`? This is another under-documented feature I've been working on. Instead of retrieving files via the API (and hence is limited to whatever files we have in the `fileMatch`), it instead does a shallow clone so all files are available.

**Comment by bagage** [comment]
Indead I wasn't aware of `--git-fs=https` option, would have been helpful for this. But if I add an option `gradle.useGradlew`, can I make it depend on that option? Eg. not actionable independently?

**Comment by bagage** [comment]
OK so indeed it works great with `--git-fs`. Basically, the only thing left to do is replacing `gradle` system binary with `./gradlew` instead.

Maybe the simplest solution is to add an `gradle:useGradlew` option, and expliciting in its documentation `if enabled, you must use gitFs option` for instance? If that suits you, I can do a PR for that.

**Comment by bagage** [comment]
I do not see reasons to not use gradlew when available, as soon as you use gitFs and `./gradlew` is available.
Regarding scenarios, it works with CLI and CLI + binarySource=docker (because the binary is not used anyway), however it fails yet in Docker because there is no Java installed:

>          "stdout": "\nERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation.\n\n",

**Comment by rarkins** [comment]
@bagage thanks again for this info. I suggest:

1. We update the Dockerfile so that all three approaches work
2. We implement the following logic:

1. If gradlew is found in the project, and gitFs is enabled then we simply use it
2. If gradlew is found in the project, and gitFs is not enabled, then we log a warning and don't use it
3. If gradlew is not found in the project, we don't use it

Do you think that would work?

**Comment by bagage** [comment]
It looks great. I'll do a PR for that probably on Monday :).
