### ISSUE TITLE
Downloading non text files through gitlab API corrupts file

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#3144]
**What Renovate type are you using?**
Renovate CLI, see #3135 

**Describe the bug**

Currently, platforms seem to only allow downloading text files through `getFile()` API. On #3135, I POCed and I needed to download a `.jar` file, but I had to modify `getFile` method (see https://github.com/bagage/renovate/commit/e7019170d2ab765463ee0d28a8647d71bbc6d10a).

Currently `getFile()` [stringify the downloaded file](https://github.com/renovatebot/renovate/blob/master/lib/platform/gitlab/storage.js#L208), **even if this is a binary file like `.jar`**.

**To Reproduce**

1.  Download a `.jar` through `fileMatch` regexes for instance from a gitlab repository.
2.  Compare the downloaded md5 with the real one.

**Expected behavior**

size and MD5 should match. But instead the downloaded file is twice bigger and corrupted.

**Screenshots**

**Additional context**
I think the problem is not only present on Gitlab platform but almost all of them. There seems no way of downloading such files yet.

**Comment by rarkins** [comment]
For now, the solution is to use gitFs. For GitLab that means ssh-based gitFs.

I don't have the perfect example/documentation for it on GitLab, but there is an example of Kubernetes for GitLab that is close to what you need: https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md#kubernetes-for-gitlab-using-git-over-ssh

FYI I plan to deprecate non-gitFs in probably the next major release anyway, once all platforms support it.
