### ISSUE TITLE
Deprecated releases are missing from release notes

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#3150]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The release notes/changelog for a PR that updates react-hot-loader to a version that's two versions newer (v4.6.3 -> v4.6.5), only shows the changelog entries for the most recent version (v4.6.5), and not also the interim version (v4.6.4) that is included in the range.

**Did you see anything helpful in debug logs?**
Didn't look since suspect won't help in this case.

**To Reproduce**

1.  Have Renovate enabled on mozilla/treeherder when `package.json` had react-hot-loader pinned to the exact version of `4.6.3`
2.  Once Renovate opens a PR to update it to `4.6.5`, look at the release notes section in its description

**Expected behavior**
For the release notes section in mozilla/treeherder#4542 to includes entries for both `4.6.4` and `4.6.5`, derived from:
https://github.com/gaearon/react-hot-loader/blob/v4.6.5/CHANGELOG.md#465-2019-01-31
https://github.com/gaearon/react-hot-loader/blob/v4.6.5/CHANGELOG.md#464-2019-01-31

**Comment by edmorley** [comment]
The same happened in this PR for `prop-types`:
https://github.com/mozilla/treeherder/pull/4624

The update was for `15.6.2` -> `15.7.1`, but only `15.7.1` appeared in the release notes.

This issue makes it easy to miss important changes when upgrading a package, making the upgrades seem safer than they are.

**Comment by rarkins** [comment]
The reason why `prop-types@15.7.0` was skipped in release notes was that it was deprecated on npmjs and so not included in our list of filtered releases, which is the source list for the release notes lookup. I'll need to think about how to handle this.

**Comment by rarkins** [comment]
Same reason for `react-hot-loader@4.6.4`

**Comment by rarkins** [comment]
I think this is fixed now, e.g.

![image](https://user-images.githubusercontent.com/6311784/77892179-756ae780-7272-11ea-8d55-f18db6da6834.png)

**Comment by edmorley** [comment]
Thank you :-)
