### ISSUE TITLE
Add python and pipenv binaries to Dockerfile 

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3152]

**Comment by Dmitry9** [comment]
[WIP PR](https://github.com/renovatebot/renovate/pull/3171)
I can run renovate using Docker as per https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md#docker
After my modifications I run:
```shell
$ sudo docker build .
```
I got a successful output.

**Comment by Dmitry9** [comment]
Please see PR:
https://github.com/renovatebot/docker-python/pull/5

I cannot base of https://github.com/renovatebot/docker-pipenv as you asked because I have no access to it.
![pipenvnotpresent](https://user-images.githubusercontent.com/22542906/52522045-f048fb80-2c88-11e9-9088-9eac1801b360.png)

**Comment by rarkins** [comment]
Thanks @Dmitry9, I was able to fix it within the Dockerfile of this repo
