### ISSUE TITLE
Broken changelog compare links

### ISSUE THREAD

**Issue by Flydiverny** [renovatebot/renovate#3162]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Links to compare to scoped npm packages (at least our private ones) are broken.

**To Reproduce**
Not sure, in our case its private scoped packages from our lerna managed repo.

**Expected behavior**
Links to work 🙃 

**Screenshots**
```
### [`v1.0.7`](https://togithub.com/xxx/yyy/compare/@&#8203;xxx/zzz@1.0.6...@&#8203;xxx/zzz@1.0.7)
```

Theres some suspicious `&#8203;` in the url, removing it and the link works fine. Doesn't show in chromes address bar tho so kind of confusing.

**Comment by Flydiverny** [comment]
@rarkins Made a recreation with public repo, with public packages

Set up a standard lerna repo here with scoped packages https://github.com/Flydiverny/renovate-3162
And then a repository which depends on one of the scoped packages here https://github.com/Flydiverny/renovate-3162-dep

Which renovate then generated this PR https://github.com/Flydiverny/renovate-3162-dep/pull/2
Which has the broken links as reported above :)

**Comment by rarkins** [comment]
@Flydiverny thanks very much for reproducing it! I think the new patch should fix your problems
