### ISSUE TITLE
Implement got pagination support

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3163]
**What would you like Renovate to be able to do?**

Support GitHub's pagination in a `got` wrapper.

**Describe the solution you'd like**

I would like to add a `lib/util/got/github-pagination.js` instance that expands on the default instance and returns a paginated `res.body` if `opts.paginate` is set to `true` in the request. 

**Describe alternatives you've considered**

Writing pagination logic manually at the application layer every time.

**Additional context**

I started writing `lib/util/got/*` wrappers already.

**Comment by rarkins** [comment]
@szmarczak do you have any suggestions for how to do this elegantly? I think I could probably do this with `got.create()` and `handler` BUT the default got instance I wrote that uses caching already has a handler so I don't think it's possible to "merge" two instances with handlers, right?

In that case I think I need to create a new got instance that then "calls" my existing one instead of merges with it.

**Comment by szmarczak** [comment]
> I don't think it's possible to "merge" two instances with handlers, right?

Of course you can! :)

You're right, handlers should do the job. But pagination should be supported in Got natively.

**Comment by szmarczak** [comment]
> have you ever thought about the semantics for a pagination "API"?

Not yet. Let's continue the talk at https://github.com/sindresorhus/got/issues/722

I'll sketch something out.
