### ISSUE TITLE
Maven: support parents

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3164]
As requested by @derkoe in https://github.com/renovatebot/renovate/issues/3029#issuecomment-459260870:

Parent looks like this:
```xml
<parent>
  <groupId>org.springframework.data.build</groupId>
  <artifactId>spring-data-parent</artifactId>
  <version>2.2.0.BUILD-SNAPSHOT</version> <!-- update here -->
</parent>
```

A good example is Spring Data REST: https://github.com/spring-projects/spring-data-rest

**Comment by derkoe** [comment]
When looking at the current implementation of the extract function the parent update should already work because it just looks at XML nodes with groupId/artifactId/version in it.

**Comment by rarkins** [comment]
Thanks @derkoe
