### ISSUE TITLE
Gradle dependencies not processed

### ISSUE THREAD

**Issue by ChristianMurphy** [renovatebot/renovate#3170]
**What Renovate type are you using?**

Renovate CLI

**Describe the bug**

When upgrading from renovate 14.9.3 to renovate 14.10.0, gradle dependencies are no longer being processed.

**Did you see anything helpful in debug logs?**
```
INFO: Gradle Wrapper (repository=Jasig/uPortal, depType=gradle-wrapper)
       "datasource": "gradleVersion",
       "depName": "gradle",
       "currentValue": "4.10.3",
       "lineNumber": 2,
       "versionScheme": "semver",
       "gradleWrapperType": "bin",
       "checksumLineNumber": 3
```

Jasig/uPortal has a build notification plugin enabled, while running renovate I received a notification that tasks had been run successfully.
Most likely the issue is in processing that happens after the Gradle wrapper report is generated.

**To Reproduce**

1.  fork https://github.com/Jasig/uPortal or https://github.com/Jasig/NotificationPortlet
2.  `renovate --token {github token} {username}/uPortal`

**Expected behavior**

renovate should open several Gradle related dependency PRs.

**Additional context**

Possibly related to https://github.com/renovatebot/renovate/pull/3062

**Comment by rarkins** [comment]
I've rolled back that change until we work out what's changed or gone wrong

**Comment by corecanarias** [comment]
I'll try again. I've tested it with uPortal and it worked fine https://github.com/corecanarias/uPortal/pulls Did you get any error in the logs?

**Comment by ChristianMurphy** [comment]
No errors in the CLI output, is there another set of logs I should check?

**Comment by ChristianMurphy** [comment]
@corecanarias :bell: ping
This is something I like to help out on, not sure which additional logs to be looking at to help trace the issue.

**Comment by corecanarias** [comment]
Hi, yes. Sorry for being disconnected, I'll have a look the current state of all the gradle stuff during the weekend, does it that works?

**Comment by ChristianMurphy** [comment]
Sure, let me know if there's additional info I can provide that can help.

**Comment by corecanarias** [comment]
Hi, I just tried again with this branch: https://github.com/renovatebot/renovate/pull/3223/files

and I got this https://github.com/corecanarias/uPortal/pulls

Please, try yourself in a test fork to confirm is working as expected
