### ISSUE TITLE
Checkbox to enable automerge per PR

### ISSUE THREAD

**Issue by abraham** [renovatebot/renovate#3172]
**What would you like Renovate to be able to do?**

Automerge specific PRs after status checks pass.

**Describe the solution you'd like**

A checkbox similar to the "check to rebase" feature except checking the box will enable automerge for this specific PR.

**Describe alternatives you've considered**

There is enabling automarege for everything but I usually want to avoid that for non-devDependencies. This could also be handled by GitHub if they were to implement automerge as a feature.

**Additional context**

#1355 looks related.

Something like this:

![screenshot from 2019-02-04 14-05-07](https://user-images.githubusercontent.com/3341/52234085-7084f080-2886-11e9-89d2-9e39a31c625b.png)

**Comment by rarkins** [comment]
@abraham one challenge is that people with permission to edit a PR body (i.e. collaborators) may not have permissions to *write to master*. But this feature were opt-in - i.e. someone with master permission would need to enable it via config - then do you think that would suit you?

**Comment by abraham** [comment]
Interesting I hadn't thought of that. I mean the obvious solution is to parse the diffs of the issue text and make sure the author of the diff that change that checks the bos has write permissions. (I'm kidding).

#1355 might just be the all around better solution. Even if a comment isn't as elegant as a checkbox.

**Comment by rarkins** [comment]
Proposal:
- [ ] Add a new automergeCheckbox option, which defaults to false
- [ ] If automergeCheckbox is true, the add a check box below rebase which allows to automerge
- [ ] If checked, automerge if the branch is green and unedited. Don't "undo" the check on a run, even if automerge is not possible

This way admins of a repo can still choose to enable this feature, and we don't have to worry about checking permissions.

Alternatively, here's how we could check permissions: https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level

But this only shows us that a user has write or admin permissions, not necessarily who can write to master. Maybe we could default to allowing only admins to check the box but have a config option to also allow all writers to automerge.

**Comment by abraham** [comment]
That would work for me.

**Comment by fastman** [comment]
I think those tickets are about the same thing:
- https://github.com/renovatebot/renovate/issues/2645
- https://github.com/renovatebot/renovate/issues/1355

**Comment by grit96** [comment]
Would the automerge checkbox be reset if the branch is updated with a new version of a package?

**Comment by azu** [comment]
>  Merge using comments #1355 

It maybe different context, but #1355 is closed by this issue, and I comment here.

dependabot has this feature .
We can comment `@dependabot merge` and dependabot merge it.

Merge via comment is useful for me.
GitHub/GitLab supports commenting via email and I can merge the dependabot's PR from email client like gmail.

- [Reply to Comments from Email - The GitHub Blog](https://github.blog/2011-03-10-reply-to-comments-from-email/)

UseCase: renovatebot/dependabot create same Pull Request to multiple repositories at same time.
It is hard that open each PRs and click merge button.
Instead of it, I can just reply `@dependabot merge` from email client.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/19714/102346908-fa558700-3fe2-11eb-9ff7-c971dd23d4a0.png">

checkbox approach may not cover this case.

**Comment by rarkins** [comment]
@azu I have reopened #1355 with your comment

**Comment by azu** [comment]
@rarkins Thanks for reopening.

FYI: GitHub has released auto-merge as a beta.
This feature sounds similar to this solution.

- [Pull request auto-merge public beta - GitHub Changelog](https://github.blog/changelog/2020-12-16-pull-request-auto-merge-public-beta/)

**Comment by TWiStErRob** [comment]
I was about to raise a feature request: "Disable auto-merge when label exists"
> Right now there's no way to stop Renovate from auto-merging, except by pushing a commit or closing the PR, but sometimes I want to prevent merges easily upon receiving the email that Renovate raised a PR.

This solution is way better, would be nice to see it through, as it would allow my use-case right from the PR description while I'm looking at it. One tap on my phone, and Renovate will wait until I get home and fix something (e.g.: CI would pass, but I realize something would break based on release notes).

**Comment by abraham** [comment]
My original feature request is resolved with GitHub's built in [auto-merge feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request).

**Comment by TWiStErRob** [comment]
Ugh, so should I raise a separate one? Because that checkbox can be toggle off too, not just on, so it would solve a wider problem. Note that there are several tickets duplicated against this one... @rarkins any idea what to do here?

**Comment by rarkins** [comment]
I'm happy to reopen this but not sure @abraham can unsubscribe himself from his own issue if so?

**Comment by viceice** [comment]
> I'm happy to reopen this but not sure @abraham can unsubscribe himself from his own issue if so?

yes, you can unsubscribe from any issue
