### ISSUE TITLE
Unify Maven and Gradle dependency names

### ISSUE THREAD

**Issue by derkoe** [renovatebot/renovate#3173]
Gradle uses the following scheme for dependencies "groupId:artifactId" - which is also used in renovate. Maven on the other hand has no representation of groupId and artifactId in a single string - renovate uses "groupId/artifactId". Since Gradle and Maven share the Maven Central repository it would be better to use the same notation in renovate - I would suggest "groupId:artifactId".

This would make presets like "group:hibernateCore" reusable between the two (and some others).

**Comment by rarkins** [comment]
sounds like a good idea
