### ISSUE TITLE
Failed to parse setup.py

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3174]
**What Renovate type are you using?**

App

**Describe the bug**

setup.py is not parsed

**Did you see anything helpful in debug logs?**

`docker run -i --rm -v /mnt/renovate/gh/plotly/dash:/mnt/renovate/gh/plotly/dash -v /usr/src/node_modules/renovate/lib/manager/pip_setup:/usr/src/node_modules/renovate/lib/manager/pip_setup -w /mnt/renovate/gh/plotly/dash renovate/pip python /usr/src/node_modules/renovate/lib/manager/pip_setup/extract.py setup.py` (exited with error code null)`

**To Reproduce**

Run against https://raw.githubusercontent.com/plotly/dash/master/setup.py

**Expected behavior**

It parses

**Comment by hawkrives** [comment]
I am running in to the same issue with https://github.com/StoDevX/cs251-toolkit/blob/master/setup.py;

```
Command failed: docker run -i --rm -v /mnt/renovate/gh/StoDevX/cs251-toolkit:/mnt/renovate/gh/StoDevX/cs251-toolkit -v /usr/src/node_modules/renovate/lib/manager/pip_setup:/usr/src/node_modules/renovate/lib/manager/pip_setup -w /mnt/renovate/gh/StoDevX/cs251-toolkit renovate/pip python /usr/src/node_modules/renovate/lib/manager/pip_setup/extract.py setup.py

Unable to find image 'renovate/pip:latest' locally
latest: Pulling from renovate/pip
[snip]

`docker run -i --rm -v /mnt/renovate/gh/StoDevX/cs251-toolkit:/mnt/renovate/gh/StoDevX/cs251-toolkit -v /usr/src/node_modules/renovate/lib/manager/pip_setup:/usr/src/node_modules/renovate/lib/manager/pip_setup -w /mnt/renovate/gh/StoDevX/cs251-toolkit renovate/pip python /usr/src/node_modules/renovate/lib/manager/pip_setup/extract.py setup.py` (exited with error code null)
```

I'm not entirely sure where to start looking to be helpful, but I'm willing to poke around if needed.

**Comment by rarkins** [comment]
When testing this locally I discovered a few things:

1. You need either Python 3.7, or Python 2.7 with mock installed
2. Docker needs to be able to access the shared folders - on OSX this is not the case by default, so set RENOVATE_TMPDIR=/tmp to fix
3. The deprecation of `imp` in Python 3.4+ leads to a false negative warning, that is now filtered out
