### ISSUE TITLE
Cannot override gradle.timeout value

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#3175]
**What Renovate type are you using?**
Renovate CLI, related to #3135 

**Describe the bug**
The default timeout (100s) is too small for my project that takes approximately 300s the first time to fetch all dependencies (then I cache them and it's much faster). I'd like to modify the timeout value but it seems I cannot simply modify renovate.json with:

```json
	"gradle": {
		"enabled": true,
		"timeout": 1000
	},
```

**Did you see anything helpful in debug logs?**

```
       "error": {
         "configFile": "renovate.json",
         "validationError": "The renovate configuration file contains some invalid settings",
         "validationMessage": "Invalid configuration option: `gradle.timeout`"
       }
```

**To Reproduce**

1.  Create repository with '...'
2.  Configure '....'

**Expected behavior**
I'd expect this parameter to be customizable, for bigger projects (maybe the 100s limit is fine for normal projects though).

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
Can you try using a `config.js` to configure *the bot* (i.e. global config for all repos) like this:

```
module.exports = {
  "gradle": {
    "enabled": true,
    "timeout": 1000
  }
}
```

Timeout is not something I wish to have configurable via the repository config, hence why it gets rejected there.

**Comment by bagage** [comment]
Yes OK, it can work that way. With docker, we have to use `-v $PWD/config.js:/usr/src/app/config.js:ro` but it seems to do the trick. Thanks :).
