### ISSUE TITLE
Validate packageRules>managers

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3180]
If the user includes a manager name that doesn't exist, we should raise a config validation error. (https://github.com/renovatebot/renovate/blob/master/lib/config/validation.js)

We should keep this validation in sync with our list of supported package managers that's here: https://github.com/renovatebot/renovate/blob/4c26d593b95752d93b757d6215d089e5dbac06d6/lib/manager/index.js#L1-L26

**Comment by Dmitry9** [comment]
Waiting for review of the [PR](https://github.com/renovatebot/renovate/pull/3240)
