### ISSUE TITLE
Pin dependencies sometimes doesn't pin them

### ISSUE THREAD

**Issue by Arcanemagus** [renovatebot/renovate#3181]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
On some repositories with NPM dependencies the initial PR to pin the dependencies occasionally only pins `devDependencies`, completely missing pinning the `dependencies`.

**Did you see anything helpful in debug logs?**
[An example log](https://renovatebot.com/dashboard#github/AtomLinter/linter-sass-lint/44057610) doesn't go into how it made the choices, it just shows that it only picked up the `devDependencies` to be pinned.

**To Reproduce**

1.  Create repository with both `dependencies` and `devDependencies` specified as ranges
2.  Configure Renovate using the default `"config:base"` configuration.

**Expected behavior**
_All_ dependencies are pinned, not just `devDependencies`.

**Screenshots**
N/A.

**Additional context**

It looks like this has actually been happening for _most_ of the repositories I have been enabling it on after going through and double checking them all.

Here are some example PR's where this happened:
* https://github.com/AtomLinter/linter-sass-lint/pull/214
* https://github.com/AtomLinter/linter-bootlint/pull/116
* https://github.com/AtomLinter/linter-lsc/pull/37
* https://github.com/AtomLinter/linter-ruby/pull/145
* https://github.com/AtomLinter/linter-scss-lint/pull/229
* https://github.com/AtomLinter/linter-scalac/pull/84
* https://github.com/AtomLinter/linter-jshint/pull/627
* https://github.com/AtomLinter/linter-eslint/pull/1179
* https://github.com/AtomLinter/linter-pycodestyle/pull/150
* https://github.com/AtomLinter/linter-jscs/pull/363
* https://github.com/AtomLinter/linter-tslint/pull/236
* https://github.com/AtomLinter/atom-linter-pug/pull/49
* https://github.com/AtomLinter/linter-js-yaml/pull/155
* https://github.com/AtomLinter/linter-moonscript/pull/32
* https://github.com/AtomLinter/linter-golinter/pull/125
* https://github.com/AtomLinter/linter-lintr/pull/114
* https://github.com/AtomLinter/linter-swagger/pull/74
* https://github.com/AtomLinter/linter-glsl/pull/84

I also had one repository where dependencies weren't pinned at all, likely because it has no `devDependencies` right now: https://github.com/AtomLinter/linter-pydocstyle/pull/74

**Comment by rarkins** [comment]
This is by design. The `config:base` preset has `rangeStrategy=auto`, and for `auto` it only pins `dependencies` if it can be sure that the repository is an app and not a library. It can be sure only if `private=true` or there is a missing `main` in the `package.json`. Otherwise we may end up pinning a library's `dependencies`, which would be a bad idea.

Set `rangeStrategy=pin` in your `renovate.json` and you'll get the behaviour you desire.

**Comment by Arcanemagus** [comment]
> It can be sure only if `private=true`

Ah ha! It probably worked as I was expecting on the repositories where that's been set. Thanks for letting me know!
