### ISSUE TITLE
Azure DevOps - Failed to add reviewers

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#3183]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
With the following `renovate.json` I am unable to automatically add reviewers to PRs created by renovate.

```json
{
  "extends": ["config:base", ":rebaseStalePrs"],
  "reviewers": ["MY_EMAIL_ADDRESS"]
}
```

**Did you see anything helpful in debug logs?**
```
Failed to add reviewers (repository=..., dependencies=gradle, branch=renovate/gradle-5.x)
"assignees": [],
"err": {
  "message": "azureApiCore.getTeamMembers is not a function",
  "stack": "TypeError: azureApiCore.getTeamMembers is not a function\n    at Promise.all.teams.map (/home/jamie/.npm/_npx/24728/lib/node_modules/renovate/lib/platform/azure/index.js:574:28)\n    at Array.map (<anonymous>)\n    at Object.addReviewers (/home/jamie/.npm/_npx/24728/lib/node_modules/renovate/lib/platform/azure/index.js:571:11)\n    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
}
```

**Expected behavior**
I expect to be able to add required reviewers to PRs based on email address

**Comment by rarkins** [comment]
It seems that the API endpoint(s) used for Azure DevOps have changed and we need to work out the new way or disable reviewers completely for Azure so that we don't error.

Replace or remove: https://github.com/renovatebot/renovate/blob/1d9167b081476fa820095ece5ec2731d74a5a73c/lib/platform/azure/index.js#L480-L522

**Comment by JamieMagee** [comment]
There's a new major version of `azure-devops-node-api` (breaking? Not sure if they follow semver). Perhaps that's useful? @renovate[bot] opened a PR about it in #2958.

**Comment by rarkins** [comment]
Yes, there's a new major available. I'll trigger the PR so that we can test it and see if the breaking changes affect us or not.
