### ISSUE TITLE
configuration checkboxes

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3192]
**What would you like Renovate to be able to do?**
`Repository access`->`Only select repositories`

- instead of a multiselect, I would like to have a checkbox for each repo
- when I switch from `All repositories` to `Only select repositories`, all the checkboxes should be checked as default

**Comment by rarkins** [comment]
Unfortunately this is 100% GitHub's UX and not Renovate's and we have no control over it. I'd love to have a better UX on that screen too and plenty of app developers have suggested it to GitHub.
