### ISSUE TITLE
Yarn integrity hashes being removed during lock file maintenance

### ISSUE THREAD

**Issue by ZauberNerd** [renovatebot/renovate#3203]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
We are using the "lockFileMaintenance" feature of renovate to re-generate our yarn.lock every week.
Unfortunately renovate does not use the correct yarn version and therefore all "integrity" hashes are being removed from our lock file, which results in massive diffs.

Here is an example Pull Request made by renovate: https://github.com/xing/hops/pull/792

We are using yarn workspaces and lerna.

**Did you see anything helpful in debug logs?**
https://renovatebot.com/dashboard#github/xing/hops/44912284

```
DEBUG: packageFiles with updates
{
  "config": {
    "npm": [{
      "deps": [{
          "depType": "engines",
          "depName": "yarn",
          "currentValue": ">=1.10.1",
          "datasource": "npm",
          "commitMessageTopic": "Yarn",
          "prettyDepType": "engine",
          "updates": [],
          "warnings": [],
          "sourceUrl": "https://github.com/yarnpkg/yarn",
          "releases": []
      }],
      "packageFile": "package.json",
      "manager": "npm",
      "packageJsonName": "hops-lerna-root",
      "yarnLock": "yarn.lock",
      "lernaDir": ".",
      "lernaClient": "yarn",
      "yarnWorkspacesPackages": ["packages/*"],
      "yarnIntegrity": true
    }]
  }
}
```
It does seem like renovate detects that the repository is using yarn and lerna and that the yarn.lock file uses "integrity" hashes, as seen in the config section above (`"yarnIntegrity": true`), but when it actually comes to selecting a yarn version to use (https://github.com/renovatebot/renovate/blob/ddb78f637f525e23d1bd0e0c54caa420b1ca9b0a/lib/manager/npm/post-update/yarn.js#L28) it does not seem to contain a truthy value, because in the config output I can see the following line:

```
INFO: Using nested bundled yarn@1.9.4 for install
```

Also, as seen above, we have the yarn version specified in the engines field, but that does not seem to have any effect on this operation.

**To Reproduce**

I haven't created a simple repository to reproduce this behavior yet, but if it makes things easier, I will go and create one.

**Expected behavior**
Renovate should select the correct yarn version either from the information in the `"engines"` field or by checking whether the yarn.lock file contains `integrity` fields or not and then create a Pull Request that only contains changes to the updated packages.

**Additional context**

Our renovate config:
```json
{
  "extends": ["config:base", "schedule:nonOfficeHours"],
  "pinVersions": false,
  "ignorePaths": ["packages/build-config/shims/", "packages/spec/mock/"],
  "semanticPrefix": "chore:",
  "dependencies": {
    "semanticPrefix": "chore:"
  },
  "prCreation": "not-pending",
  "lockFileMaintenance": {
    "enabled": true
  },
  "packageRules": [
    {
      "packagePatterns": ["^@untool/"],
      "groupName": "Update untool monorepo packages"
    }
  ]
}
```

There are a few other issues mentioning this problem, but they all seem to be resolved already:
- #2593 
- #2589 
- #2567 
- #2566 
- #2565

**Comment by rarkins** [comment]
First step is we need to reproduce this by taking an oldish yarn.lock with integrity hashes and seeing if lockFileMaintenance always results in dropped integrity hashes. If so then we need to make sure we correctly autoselect the version of yarn to use.
