### ISSUE TITLE
gitFs "unknown revision or path" failure on Windows

### ISSUE THREAD

**Issue by ViceIce** [renovatebot/renovate#3204]
**What Renovate type are you using?**
Renovate CLI - 14.16.1, Windows 18.03.17134.523, git version 2.20.1.windows.1

**Describe the bug**
Renovate onboarding pr does not work and will crash with error message:
`fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.`
it is crasing here:
https://github.com/renovatebot/renovate/blob/c52e749177fe2f447c228d4fbba80019510acc27/lib/platform/git/storage.js#L257-L279

I think it is because the checkout will set the parent to master branch on windows.
so the commit will be pushed to `origin renovate/configure:master` by default.
After this he can not find `origin/renovate/configure` because it does not exist.

It is currently happening with `bitbucket-server`, but i think  it won't work with `github` too

**Did you see anything helpful in debug logs?**
```
fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**To Reproduce**

1.  Create repository with a simple `package.json` and an outdated dependency.
2.  Configure:
```json
{
    gitFs: 'https',
    onboarding: true,
    onboardingConfig: {
      extends: ['config:base'],
    }
}
```

**Expected behavior**
Simply allow using renovate on windows.

**Comment by rarkins** [comment]
Are you able to test if the exact same config works on non-windows, such as Linux or OSX?

**Comment by ViceIce** [comment]
Same config works on bionic and docker.

On git for Windows git checkout automatically tracks the base branch.
That's the cause. I've debugged a little. Then the push pushes to master as described above.
