### ISSUE TITLE
Ensure getPrList() results integrity mid-run

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#32040]
### Describe the proposed change(s).

It's important that `platform.getPrList()` returns an accurate list, particularly after PRs are created.

Check each platform to make sure that createPr() and updatePr() both mutate/update any saved PR lists for each platform.

**Comment by rarkins** [comment]
While looking into this, please also check on whether the PR list is cached reliably too.

**Comment by RahulGautamSingh** [comment]
Related Info:

| Platform | getPrList() info stored in | createPr updates stored info | updatePr updates stored info  |
|-|-|-|-|
| Azure | local config | ✅ | ✅ | 
| Bitbucket Cloud | repo cache | ✅ | ❌ | 
| Bitbucket Server | local config | ✅ | ❌ | 
| CodeCommit | local config | ❌  | ❌ | 
| Gerrit | function not used | ❌  | ❌ | 
| Gitea | repo cache | ✅ | ✅ | 
| Github | local config & repo cache | ✅ | ✅ | 
| Gitlab | loca config | ✅ | ❌ | 

Tasks:
- [ ] Add the logic in platforms Bitbucket Cloud & Server, Gitlab such that `updatePr()` function, updates the prList in config or cache. Should we implement the same for codecommit/gerrit they need it but I doubt they are priority?

_Test the following cases for all the platforms:_
- [ ] After pr creation log the prList to check if created pr is available
- [ ] On next run, the created pr should be available in the result of `getPrList()`
- [ ] After pr is updated "by bot" the updated info should be available in the result of `getPrList()`
- [ ] On next run the updated pr should be returned from `getPrList()` 
- [ ] Modify any pr from platform UI. Then run the bot ... now `getPrList()` should return updated info for that modified PR ie. validate cache reconciliation which happens the first time `getPrList()` is called during the run and cache is initialzed

**Comment by rarkins** [comment]
Code Commit can be skipped as it's deprecated. Gerritt also unless it's really quick. Ideally all platforms would update the PR cache correctly too

**Comment by rarkins** [comment]
@RahulGautamSingh it's important to close the gap for Bitbucket Cloud and Azure

**Comment by RahulGautamSingh** [comment]
Should we close this as the main objective is completed? And move the task of adding cache to the Azure, BitbucketServer, Gitlab platforms to another issue.

**Comment by rarkins** [comment]
Please create separate issues then close this one
