### ISSUE TITLE
GitHub Enterprise support for Terraform

### ISSUE THREAD

**Issue by nathanpower** [renovatebot/renovate#3209]
Currently, if I'm not misreading the config docs, renovate supports github.com sources for terraform, but not GHE. 

Are there any plans to add this?

Thanks

**Comment by rarkins** [comment]
How are those sources specified? e.g. can you give me an example of your module definitions? It can hopefully be supported quite easily

**Comment by nathanpower** [comment]
I'm a tad removed from it, trying to help someone on another team. I will see if I can get module definition. The documented semver ref approach in the docs should work fine (just with GHE domain)

e.g. `github.com/hashicorp/example?ref=v1.0.0.`

**Comment by nathanpower** [comment]
Modules are defined e.g.:

```
module "<module-name>" {

    source = "git::https://<ghe.domain.com>/<org>/<repo>?ref=v1.0.0"
}
```

**Comment by rarkins** [comment]
Thanks @nathanpower. And in your use case, would this also happen to be the same GHE server that Renovate is running against?

One challenge is how to identify that it's GitHub vs GitLab etc (because the source line would look pretty similar in both cases) but if it is the exact same host as Renovate is running against then I think we can add a simply if statement to check that and proceed.

**Comment by nathanpower** [comment]
> And in your use case, would this also happen to be the same GHE server that Renovate is running against?

Good question. In our case it is, yes.

**Comment by jakauppila** [comment]
Very interested in this, but for BitBucket Server.

```
DEBUG: packageFiles with updates (repository=PROJECT/REPO)
       "config": {
         "terraform": [
           {
             "packageFile": "modules/standard/security-groups.tf",
             "manager": "terraform",
             "deps": [
               {
                 "moduleName": "default-vpc-security-groups",
                 "managerData": {"terraformDependencyType": "module"},
                 "source": "git::https://bitbucket.contoso.com/scm/PROJECT/REPO.git//modules/vpc-defaults?ref=v0.7.1",
                 "currentValue": "~> 0.7",
                 "skipReason": "no-version",
                 "updates": []
               }
             ]
           }
         ]
       }
```

**Comment by secustor** [comment]
@rarkins  I think this can be closed, as gitTags are already implemented in the Terraform manager
