### ISSUE TITLE
composer.lock merge conflict

### ISSUE THREAD

**Issue by Mochaka** [renovatebot/renovate#3219]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I'm getting merge conflicts for a lot of the composer packages when i merge a PR, all subsequent PRs that are already opened now have a merge conflict.

**Screenshots**
<img width="592" alt="2019-02-15_11-37-18" src="https://user-images.githubusercontent.com/948073/52826733-3208f480-3116-11e9-8668-7bcaa4202b6a.png">
<img width="1085" alt="2019-02-15_11-37-56" src="https://user-images.githubusercontent.com/948073/52826734-3208f480-3116-11e9-8c2c-0ab6c3580ed8.png">

**Comment by rarkins** [comment]
That’s just how git works and is unavoidable. Renovate will rebase conflicted branches the next time it runs.
