### ISSUE TITLE
Retry checkbox does not work for PRs that have been edited

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#3221]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Ticking the "rebase/retry" checkbox does not override the "PR has been edited, Renovate will stop making changes" feature.

**To Reproduce**

1.  Have a PR where the "PR has been edited message" was left, eg https://github.com/mozilla/treeherder/pull/4649
2.  Tick the retry box in the PR description
3. Wait for Renovate to rebase the PR

**Expected behavior**
The PR is rebased, since the "PR has been edited message" message says:

> If you wish to abandon your changes and have Renovate start over you may click the "rebase" checkbox in the PR body/description.

**Comment by rarkins** [comment]
I was just wondering why the checkbox wasn't working for you, thanks for narrowing it down to edited PRs.

**Comment by rarkins** [comment]
@edmorley 	confirmed fixed in https://github.com/mozilla/treeherder/pull/4649

**Comment by edmorley** [comment]
Works great - thank you :-)
