### ISSUE TITLE
path of bitbucket-server endpoint config not respected

### ISSUE THREAD

**Issue by PixnBits** [renovatebot/renovate#3225]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Using a configuration with endpoint of `https://www.example.com/vcs` currently renovate attempts to hit URLs like `https://www.example.com/rest/api/1.0/...` instead of `https://www.example.com/vcs/rest/api/1.0/...`.

**Did you see anything helpful in debug logs?**
URLs like `https://www.example.com/rest/api/1.0/...` and the subsequent 404s.

**To Reproduce**

follow https://github.com/renovatebot/renovate/blob/master/lib/platform/bitbucket-server/README.md#testing _except_:
1. create an nginx/apache server and reverse proxy the bitbucket-server server on a path, like `/vcs`
2. use `export RENOVATE_ENDPOINT=https://localhost:{nginx/apache port}/vcs`

**Expected behavior**
Renovate using URLs including the endpoint path, like 'vcs' in `https://www.example.com/vcs/rest/api/1.0/...`.

**Screenshots**
(probably not too helpful in this case)

**Additional context**
Manually changing the URLs to remove the leading slashes in `lib/platform/bitbucket-server/index.js` (ex: from `'/rest/api/1.0/projects'` to `'rest/api/1.0/projects'`) allowed renovate to continue on merrily and it worked great.

**Comment by rarkins** [comment]
With the existing/old code, if you set the path as `https://www.example.com/vcs/` (with trailing slash) does everything work? And if you then use the same endpoint but with your new code, does it still work?

**Comment by PixnBits** [comment]
Good idea! I don't have access to the real server today, but trying on another computer with the literal values:
```
$ RENOVATE_PLATFORM=bitbucket-server \
   RENOVATE_ENDPOINT=http://www.example.com/vcs/ \
   RENOVATE_GIT_FS=http \
   RENOVATE_USERNAME=renovate-bot \
   RENOVATE_PASSWORD=abc123456789! \
   LOG_LEVEL=debug \
   node lib/renovate.js --autodiscover --dry-run
```
I see in the logs:
```
DEBUG: getRepos(http://www.example.com/vcs/)
ERROR: bitbucket getRepos error
```
with a URL of `http://www.example.com/rest/api/1.0/projects?limit=100"` so I don't believe the trailing slash helps (currently).

**Comment by PixnBits** [comment]
I want to submit a PR with changes to fix this, but want to avoid regressions of the (probably more common) case of no path in the `endpoint` so I'm looking at the test cases in `test/platform/bitbucket-server/index.spec.js`. They're set up for the no-path case so it might be a bit of a refactor as I'm thinking of using the full URL instead of just the API path.

IMO requiring the trailing slash as part of the fix makes sense as that affects how the URL constructor resolves paths
```
$ node
> new url.URL('rest/api/1.0/projects?limit=100', 'https://www.example.com/vcs').href
'https://www.example.com/rest/api/1.0/projects?limit=100'
> new url.URL('rest/api/1.0/projects?limit=100', 'https://www.example.com/vcs/').href
'https://www.example.com/vcs/rest/api/1.0/projects?limit=100'
```

**Comment by rarkins** [comment]
I think we can/should massage in the trailing slash if it's not present.

**Comment by PixnBits** [comment]
The good news is I believe massaging is done today via https://github.com/renovatebot/renovate/blob/master/lib/util/host-rules.js#L46
