### ISSUE TITLE
a dependency not updated after rebasing

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3231]
**What Renovate type are you using?**
Renovate Pro

**Describe the bug**
- `@dmx/npm-winston-slack@2.2.12` was published a few minutes ago
- in https://github.com/dmx-io/npm-logger/pull/53, I checked `* If you want to rebase/retry this PR, check this box`
- `renovate/all` branch was force-pushed
- but `@dmx/npm-winston-slack` is unchanged in `package.json` in this PR (still `    "@dmx/npm-winston-slack": "^2.2.11",`)

**Comment by piotr-s-brainhub** [comment]
even after closing this PR, renovate opens a new PR without updating `@dmx/npm-winston-slack`

**Comment by rarkins** [comment]
Please check the logs for this repository. There is a 404 lookup failure for this dependency that needs to get resolved first.

**Comment by rarkins** [comment]
Is this the token you've configured? `"token":"73********************************3f"`

**Comment by piotr-s-brainhub** [comment]
@rarkins 

Thanks, it worked after token updating, the old one has been deleted.

However it would be good to post some info in the PR, not only in logs.
