### ISSUE TITLE
Inline/prettify baseBranch log metadata

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#32331]
### Describe the proposed change(s).

Example of current log:

```
DEBUG: Found existing branch PR (branch="renovate/com.appsamurai.storyly-storyly-3.x")
{
  "baseBranch": "dev"
}
```

How it should look instead:

```
DEBUG: Found existing branch PR (baseBranch="dev", branch="renovate/com.appsamurai.storyly-storyly-3.x")
```

**Comment by RahulGautamSingh** [comment]
Cannot reproduce the above log:

I got this:
![image](https://github.com/user-attachments/assets/f07e0a9c-c703-47dc-b1f5-84812da08cb1)
