### ISSUE TITLE
Nuget feeds support authentication

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3239]
**What would you like Renovate to be able to do?**

Use `hostRules` to be able to configure authentication for Nuget feeds.

**Describe the solution you'd like**

Once a hostRule for a matching host is defined, the nuget datasource should use it to populate requests.

**Additional context**

Suggested by @fgreinacher in https://github.com/renovatebot/renovate/pull/3148#issuecomment-465141488

**Comment by rarkins** [comment]
What type of authentication is needed - Basic, Bearer, or both?

**Comment by fgreinacher** [comment]
For our scenarios (privately hosted Artifactory server) Basic auth would be fine as a first step.

**Comment by Elufimov** [comment]
I tested basic auth against proget and it works.
