### ISSUE TITLE
Detect all Maven dependencies when upgrading property value

### ISSUE THREAD

**Issue by msimperi** [renovatebot/renovate#3247]
**What would you like Renovate to be able to do?**
It would be nice to get only single PR for all dependencies, when Renovate tries to update Maven dependencies by upgrading property value. The property value might be used for 1 to many dependency as version number.

**Describe the solution you'd like**
Instead of multiple PRs, single PR should be created if single version number affects to multiple dependencies.

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/2699541/53156295-bef4f780-35c7-11e9-8fbc-b657a33e1a14.png)

![image](https://user-images.githubusercontent.com/2699541/53156317-ce744080-35c7-11e9-87b5-623160b4e3f6.png)

**Comment by msimperi** [comment]
All PRs had the same "changeset", single property updated from 502 to 503.

**Comment by rarkins** [comment]
You can always use `packageRules` to define your own groupings by config, and I agree that these packages should be updated together. Example:

```json
{
      "packageRules": [
        {
          "packagePatterns": [
            "^com.amazonaws:java-sdk-"
          ],
          "groupName": "aws java sdk"
        }
}
```

We also have some default/embedded groupings that these aws ones could be added to. Here's an example: https://github.com/renovatebot/presets/blob/9835db3696ca889ec59b166860ce9d2547a49c87/packages/renovate-config-group/package.json#L235-L242

Do you think the entire `com.amazonaws:*` should be grouped together by default, or only the `java-sdk-*` subset as I wrote in the above example?

A future capability might be to dynamically detect groupings based on the prefix and version number, but this could be a bit challenging with a few edge cases.

**Comment by msimperi** [comment]
AWS dependencies I think should be always updated at once, but that kind of "groups" there are lot more.

I was referring only to the case where Renovate updates a property value from 1.0.X to 1.0.Y and does not detect that the property value is used with multiple dependencies. PR change shows only that Renovate is updating single dependency, but actually it might update quite many.

This is might be tricky to detect 👍 


Example pom.xml were single property value is used with multiple dependencies.
```
    <!-- AWS -->
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-dynamodb</artifactId>
      <version>${aws.version}</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-sqs</artifactId>
      <version>${aws.version}</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-sts</artifactId>
      <version>${aws.version}</version>
    </dependency>

...

<properties>
    <aws.version>1.11.505</aws.version>
  </properties>

´´´

**Comment by rarkins** [comment]
Oh, good point! I missed that originally

**Comment by rarkins** [comment]
Here's what I'm thinking:

First strategy is to have a good set of presets that catch and group the most common of these.

Second strategy is to document how users can manually add groupings if they have a use case which isn't applicable to shared presets.

Third strategy might be to have a configuration option for Maven that lets you specify to use the variable name in the branch name instead of the full dep name. That way in this example the branch would be like `renovate/aws.version-1.x` and they'd all be grouped into a single PR as a result.

**Comment by rarkins** [comment]
@zharinov we should update the extract function so that the variable name (e.g. `aws.version`) if used is included with every extracted dependency.

**Comment by noelmccrory** [comment]
It appears that this is already in place?

However, I was wondering if it is possible to configure the branch name when Renovate is making updates based off a Maven property. E.g. I have updated my branchTopic to `{{{depNameSanitized}}}-{{{toVersion}}}` and it gives me for example `renovate/org.hamcrest-hamcrest-core-2.2`. But for dependencies that you a maven property for their version, the branch name just uses the name of the property, e.g. `renovate/spring.boot.version`.

**Comment by viceice** [comment]
@noelmccrory I think you need to override `groupName` as it is set explicit by `maven` manager

**Comment by HonkingGoose** [comment]
Just checking what the status of this is now, as this is labeled `priority-5-triage` right now, and I'm not fully clear on if we need more stuff to be done before we can close this issue.

@rarkins said:

> Here's what I'm thinking:
> 
> First strategy is to have a good set of presets that catch and group the most common of these.
> 
> Second strategy is to document how users can manually add groupings if they have a use case which isn't applicable to shared presets.
> 
> Third strategy might be to have a configuration option for Maven that lets you specify to use the variable name in the branch name instead of the full dep name. That way in this example the branch would be like `renovate/aws.version-1.x` and they'd all be grouped into a single PR as a result.

For the first strategy we only have the `aws-java-sdk monorepo` as a monorepo preset for `amazon` dependencies, do we want/need more presets here maybe?

The second strategy is met by:
- the `packageRules` docs: https://docs.renovatebot.com/configuration-options/#packagerules
- by the versioning docs here: https://docs.renovatebot.com/modules/versioning/ 
 
PR #9017 is improving the current versioning docs, so we might want to mention the Amazon use-case?

I'll let the maintainers decide on what we need for the third strategy.
