### ISSUE TITLE
'baseBranchList' for 'packageRules'

### ISSUE THREAD

**Issue by Lechindianer** [renovatebot/renovate#3255]
**What would you like Renovate to be able to do?**
Being able to set base branches for specific packages. 

**Describe the solution you'd like**
Something like

```json
"packageRules": [
    {
      "packageNames": ["eslintt"],
      "baseBranches": "master[, develop]"
    },
  ]
```

**Describe alternatives you've considered**

**Additional context**
For linters it would be nice if you could configure specific branches it should go to. Our default branch is `develop`, so renovate chooses that as baseBranch. When we do fixes to our `master` branch, the linter on `master` may support different rules than `develop` which leads to backmerging issues.

**Comment by rarkins** [comment]
Is your desire that you can have Renovate submit PRs to both `develop` as well as `master`? Or `develop` only? The `baseBranches` config option may do what you want, although it's for putting at the root of your config and not in `packageRules`. If uncertain, please share your config so far.

**Comment by Lechindianer** [comment]
Our base branch for most packages is fine - it's `develop`. Only for that 2 or 3 linters we use in our project it would be nice to keep the linting rules at the same version. Setting `master` as base branch for the linters would be totally fine, we could backmerge manually to `develop`.

**Comment by rarkins** [comment]
So to start, you will need to have both develop and master listed in baseBranches. But then the problem is that you need a way to *ignore* packages per base branch. packageRules is probably the way to go, but slightly different to what you suggest.

If we had a `baseBranchesList` field in `packageRules` then you could do like this to ignore all except `eslint` in `master`:

```json
  "packageRules": [{
	"baseBranchList": ["master"],
    "excludePackagePatterns": ["^eslint"],
    "enabled": false
  }]
```

Basically this means "disable all package updates for master baseBranch except those starting with eslint". Whether or not you add a rule to disable them for develop branch or not doesn't really matter - either way would work. Keeping them enabled probably means less backmerging necessary.

Do you agree that this would suit your requirements?

**Comment by Lechindianer** [comment]
That sounds like a solution to our problem!

**Comment by ViceIce** [comment]
I'm looking for such a feature too.

I would like to be able to block updates for specific release branches.
But i would like to receive bugfix and security releases.

Another example is an angular cli based project.

On master we are up to date, but on older releases (lts) we only would like to receive patch releases.

**Comment by ViceIce** [comment]
I think this is related to #2496

**Comment by rarkins** [comment]
Related yes, but doesn’t solve. This approach could be a kind of workaround

**Comment by ViceIce** [comment]
Are you planning to implement this? or should somebody send a pr for this?

**Comment by rarkins** [comment]
A PR would be welcomed if you have a need for it yourself. Otherwise I'll probably get to it in the next week or two. I think it should hopefully be a fairly short one and if you look at the package-rules.js history you can see example of similar previous functionality being added.

**Comment by rarkins** [comment]
@ViceIce btw I'm still thinking about whether it works best to configure everything in the default branch (e.g. `master`) or also support configs within other base branches. It could certainly lead to confusion at times if we implement #2496 and people configure conflicting things in master as well as another branch, so the question is: does supporting configs in alternative branches enable anything that couldn't be done elegantly with this packageRules feature, or does it make it significantly easier?

**Comment by ViceIce** [comment]
@rarkins I think it depends on the specific branching model.

 If the default branch is the release branch, it could be difficult to update the config as described in #2496.

If your base branch is the mostly up to date devel branch, all config should be done there. So we don't have the conflicting configs.

**Comment by ViceIce** [comment]
For me, this feature would be suffusant, because our base branch is not our release branch.
