### ISSUE TITLE
Maven datasource does not handle authentication credentials

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#3262]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
With #3223 landed, private repositories do not work anymore:

>  WARN: Unknown error requesting https://my.private.repo.com/snapshot/org/jetbrains/kotlin/kotlin-stdlib/maven-metadata.xml Error Code: 401

I don't see any way to provide credentials to it though.

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

**To Reproduce**

1.  Create repository with '...'
2.  Configure '....'

**Expected behavior**
Allow user to specify auth for given URL repository, or better use the one defined in gradle, for me:

```
		maven {
			url "https://my.repo.com/repository/maven-all"
			credentials {
				username = 'bar'
				password = 'foo'
			}
		}
```

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
Which Gradle file is that in? Can you link me to a reference for its various options if possible?

**Comment by bagage** [comment]
Unfortunately it's on a private repository so cannot link it to you. The repository is a [nexus](https://help.sonatype.com/repomanager3) with auth required.

Using `credentials { username = 'foo' ; password = 'bar }` in gradle allows gradle to connect to it. Maybe renovate should parse these and use `https://username:password@repository`?

**Comment by rarkins** [comment]
I’m also looking for the Gradle spec that describes these fields, but we can try finding it during implementation.

**Comment by corecanarias** [comment]
The gradle datasource doesn't support authentication yet.

**Comment by Dmitry9** [comment]
@rarkins please look into [draft PR](https://github.com/renovatebot/renovate/pull/3302). All tests are passed. Maybe you can suggest an option regarding the test against a real server. How renovate.json should look like and if it possible without setting up a private repo.
