### ISSUE TITLE
Maven datasource: invalid version detection

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#3268]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
I'm using some library with version **1.0.0-RC14**, but then Renovate creates a PR for version **1.0.0.RC9.2**. [See PR](https://github.com/bagage/gradle-template/pull/7)

The release name was wrong before RC10, eg there was a dot `.` instead of a dash `-` between version and `RC` (`version.RC` instead of `version-RC`). But somewhat Renovate should handle that I believe? Or maybe I can fix it on my side?

**To Reproduce**

1.  Clone repository https://github.com/bagage/gradle-template/
2. Start renovate

**Expected behavior**
Since RC9.2 is before RC14, there should be no PR created.

**Comment by rarkins** [comment]
We need to verify using Maven's embedded ComparableVersion as documented here: https://octopus.com/blog/maven-versioning-explained

**Comment by rarkins** [comment]
This might be another approach: https://blog.soebes.de/blog/2017/02/04/apache-maven-how-version-comparison-works/

**Comment by rarkins** [comment]
@zharinov could you take a look at this?

**Comment by zharinov** [comment]
Of course

**Comment by zharinov** [comment]
Unfortunately, it seems we have no reliable enough generic solution :(

We're using this rule from spec `".qualifier" < "-qualifier" < "-number" < ".number"` and extending it's logic may lead to bugs in another places.

One possible solution is to use internal "major prefixes" consisting in `<versions>` section of [artifact metadata](http://repo1.maven.org/maven2/io/gitlab/arturbosch/detekt/detekt-core/maven-metadata.xml), like `7-1.0.0-RC14` vs `3-1.0.0.RC9.2`. But as I know, the right order is not guaranteed.

Another one is to just drop all the versions greater than `<latest>`, but it won't help if one of these is already used.

**Comment by rarkins** [comment]
I believe @zharinov also tested this with the Java versioning library to confirm. Therefore, closing as we are behaving as per spec. @bagage if you have any ideas or think we got it wrong, please add your comment :)

**Comment by bagage** [comment]
As far as it is compliant with specs, it's fine by me. Thanks for investigating the issue!

**Comment by rarkins** [comment]
I'm reopening this to discuss more. I noticed another example of a "weird" upgraded in Maven: https://github.com/aerogear/mobile-developer-console/pull/204

![image](https://user-images.githubusercontent.com/6311784/53964815-4d9d6480-40f0-11e9-912e-753f963208ed.png)

Now of course `20020829` is a larger number than `1.0b3` but how do Maven and other tools handle these cases? Are they all prompting people to upgrade or is there some other trick/rule being used that we're not aware of?

**Comment by zharinov** [comment]
I can only suggest it uses metadata, so... well, we should do it too

**Comment by rarkins** [comment]
What do you mean specifically by metadata? Is it some endpoint we are not querying yet that we should add to datasource?

**Comment by zharinov** [comment]
I mean [this file](http://repo1.maven.org/maven2/ant-contrib/ant-contrib/maven-metadata.xml), but as I cann see now, it doesn't even contain newer versions.

**Comment by zharinov** [comment]
Maybe we should additionally parse [index html](http://repo1.maven.org/maven2/ant-contrib/ant-contrib/) files. At the another hand, as we discussed earlier, it seems to be affecting old artifacts only.

**Comment by rarkins** [comment]
Even if we parse that directory, it still contains the 20020829 entry. I guess, for now we just raise the occasional "weird" update, people close them unmerged, and then it's done.
