### ISSUE TITLE
Incorrect Tagging

### ISSUE THREAD

**Issue by mdi** [renovatebot/renovate#3269]
**What Renovate type are you using?**
Renovate CLI, Renovate GitHub App, or Renovate Pro?

**Describe the bug**

As evidenced by [this commit](https://github.com/azdanov/azdanov.github.io/commit/3ddba4a80370e399045e37b11c9fbbe0b8f3a87d), my GitHub username is being tagged in commits that are not related to me, but a package specifically. I've seen this with many commits related to that package, so please do something to help cut down on the unnecessary notifications that this causes.

Thanks.

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

**To Reproduce**

1.  Create repository with '...'
2.  Configure '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
As mentioned in https://github.com/azdanov/azdanov.github.io/commit/3ddba4a80370e399045e37b11c9fbbe0b8f3a87d#commitcomment-32478829, this commit isn't by Renovate, so can't be fixed here.
