### ISSUE TITLE
Add option rebaseConflictedPrs or Fix the checkbox to work during non scheduled hours

### ISSUE THREAD

**Issue by christophehurpeau** [renovatebot/renovate#3275]
**What would you like Renovate to be able to do?**
Prevent prs with conflicts to be rebased

**Describe the solution you'd like**
Add an option `rebaseConflictedPrs` witch defaults to true, allows to prevent rebasing conflicted prs when set to true the same way rebaseStalePrs works

**Describe alternatives you've considered**
use `updateNotScheduled`, but we still want the ability to rebase the pr when checking the checkbox

**Additional context**
staled prs:
https://github.com/renovatebot/renovate/blob/123bdd4572959d7d647f7a0b4a70999dc4c40e35/lib/workers/branch/parent.js#L43-L47

conflicted prs:
https://github.com/renovatebot/renovate/blob/123bdd4572959d7d647f7a0b4a70999dc4c40e35/lib/workers/branch/parent.js#L62

**Comment by rarkins** [comment]
By this do you want to achieve no automatic rebased ever, ie only manual?

**Comment by christophehurpeau** [comment]
@rarkins yes

**Comment by christophehurpeau** [comment]
Or it could be done on scheduled hours.
We can sometimes have a lot of PRs opened and don't want them to affect our ci during working hours

**Comment by rarkins** [comment]
And did you verify that the checkbox rebase doesn’t work if you set `updateNotScheduled` to `false`?

**Comment by christophehurpeau** [comment]
Also, most our renovate prs create conflicts with each other so instead of having to wait each time for the other prs to run on the ci, we can choose the order and avoid waiting too much

**Comment by christophehurpeau** [comment]
@rarkins yes the checkbox doesn't work

**Comment by christophehurpeau** [comment]
our config is here: https://github.com/ornikar/shared-configs/blob/master/%40ornikar/renovate-config/package.json we reverted the commit with `updateNotScheduled`: https://github.com/ornikar/shared-configs/blob/b752e0dddcb2b407214cf273bca3f85e49e5e890/%40ornikar/renovate-config/package.json#L16-L17

**Comment by rarkins** [comment]
It sounds like fixing the checkbox to work during non scheduled hours would be better for you then?

**Comment by christophehurpeau** [comment]
@rarkins yes :)

**Comment by rarkins** [comment]
@christophehurpeau according to my code review, `updateNotSheduled` should work with the master issue checkbox. Here is the only place where the logic is checked, and it's inside an `if` statement that only is true if the master issue isn't checked. If the master issue is checked then `updateNotScheduled` is not checked:

https://github.com/renovatebot/renovate/blob/87cf1350d495b0c318e8eacc7b817c869ff82314/lib/workers/branch/index.js#L166-L174

Please test again and let me know if somehow the checkbox doesn't work when you have updateNotScheduled=true. If so then we need to look at the logs.

**Comment by LentnerStefan** [comment]
@rarkins I restored our original config  : 
```
      "rebaseStalePrs": true,
      "updateNotScheduled": false,
```
And the rebase checkbox does indeed work outside of schedule. I don't know what was happening last time, sorry for the confusion and thanks for your time !

**Comment by rarkins** [comment]
No problem! Thanks very much for letting me know
