### ISSUE TITLE
Assignee /Reviewer on failed PR

### ISSUE THREAD

**Issue by ViceIce** [renovatebot/renovate#3276]
**What Renovate type are you using?**
Renovate self hosted, bitbucket server

**Describe the bug**
Currently when renovate detects a pr (automergable) which has failed status it simply updates the state to `Disabled due to failing status checks.`

**Expected behavior**
It should add the default reviewers / asignees on pr's with failed status checks. So someone gets informed about the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/1798109/53499227-33d49f80-3aa8-11e9-9063-3ee555798386.png)
![image](https://user-images.githubusercontent.com/1798109/53499246-3fc06180-3aa8-11e9-8031-be69846a1de8.png)

**Comment by rarkins** [comment]
I thought we had this already, but maybe the logic is different between GH and BB. The idea was to skip assignees/reviewers when automerging but add them in if tests fail. Or maybe it’s related to the branch automerge case specifically.

**Comment by ViceIce** [comment]
debug log:
```
"msg":"PR is configured for automerge"
"msg":"getBranchStatus(renovate/grunt-msbuild-0.4.x, requiredStatusChecks=true)"
"commitStatus":{"successful":0,"inProgress":0,"failed":1},"msg":"branch status check result"
"msg":"PR is not ready for merge (branch status is failed)"
```

**Comment by rarkins** [comment]
You’d need to check the log from exactly when the PR was created. We only assign at the time of PR creation so that users have the ability to unassign and not have the bot keep assigning again

**Comment by ViceIce** [comment]
OK, maybe here is another cache problem.

```
"pr":26,"msg":"PR created"
"msg":"getBranchStatus(renovate/grunt-msbuild-0.4.x, requiredStatusChecks=true)"
"commitStatus":{"successful":0,"inProgress":0,"failed":0},"msg":"branch status check result"
"branchStatus":"pending","branchName":"renovate/grunt-msbuild-0.4.x","msg":"getBranchStatus() result"
"msg":"Skipping assignees and reviewers as automerge=true"
"msg":"Created Pull Request #26"
"msg":"Ensuring comment \":warning: Artifact update problem\" in #26 is removed"
"msg":"Found 0 comments"
"automerge":true,"automergeType":"pr","automergeComment":"automergeComment","msg":"Checking #26 for automerge"
"msg":"PR is configured for automerge"
"msg":"PR is not ready for merge"

```

**Comment by ViceIce** [comment]
The following run

```
msg":"Processing existing PR"
"msg":"getBranchStatus(renovate/grunt-msbuild-0.4.x, requiredStatusChecks=true)"
"commitStatus":{"successful":0,"inProgress":0,"failed":1},"msg":"branch status check result"
"branchStatus":"failed","branchName":"renovate/grunt-msbuild-0.4.x","msg":"getBranchStatus() result"
"prTitle":"Update dependency grunt-msbuild to v0.4.5","oldPrBody":"This PR contains the following update ...","msg":"PR body changed"
"msg":"updatePr(26, title=Update dependency grunt-msbuild to v0.4.5)"
"msg":"getPr(26)"
"msg":"getPr(26)"
"committedFiles":false,"pr":26,"msg":"PR updated"
"automerge":true,"automergeType":"pr","automergeComment":"automergeComment","msg":"Checking #26 for automerge"
"msg":"PR is configured for automerge"
"msg":"getBranchStatus(renovate/grunt-msbuild-0.4.x, requiredStatusChecks=true)"
"commitStatus":{"successful":0,"inProgress":0,"failed":1},"msg":"branch status check result"
"msg":"PR is not ready for merge (branch status is failed)"
```

**Comment by ViceIce** [comment]
Ok, our jenkins marked the pr as pending, so renovate is skipping merge.
Next time the branch state is failed, here renovate should add reviewers / assignees.

**Comment by ViceIce** [comment]
Found [prCreation](https://renovatebot.com/docs/configuration-options/#prcreation), setting it to 'not-pending'

**Comment by ViceIce** [comment]
Arg, found a bug in ensurepr. sending pr.

checks for `failure` not for `failed`.
