### ISSUE TITLE
Hex versionScheme

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3299]
Reference: https://hexdocs.pm/elixir/Version.html#module-requirements

This can be implemented as a wrapper around npm similar to how we did with Composer, Hashicorp, etc.

First step is to identify (here in this issue) all the syntax that differs from npm's semver.

**Comment by KonstantinKurganov** [comment]
Hex versoning differences from npm:
1. Support of `~>`, `==`, `!=` operstors
1. Use of `or` , `and` keywords
