### ISSUE TITLE
Include a link to Intrinsic's Package Diff in PRs

### ISSUE THREAD

**Issue by blowery** [renovatebot/renovate#3304]
**What would you like Renovate to be able to do?**
Include a link to [Instrinsic's Package Diff](https://diff.intrinsic.com/) in revision update PRs.

**Describe the solution you'd like**
I'd like to be able to easily and quickly see a package diff between the current version and the proposed version in the PR. Since NPM packages can be published without corresponding source updates, linking to the source repo is less reliable than doing a diff of the actual packages.

**Describe alternatives you've considered**
At the moment I build the links by hand, but it would be great to have it automated.

**Additional context**
Motivated by the recent release of webpack-rtl-plugin@1.8.1, which had no corresponding github release and appeared to be a suspicious release.

**Comment by blowery** [comment]
Motivating PR: https://github.com/Automattic/wp-calypso/pull/31138

Compare Source links to https://togithub.com/romainberger/webpack-rtl-plugin/compare/v1.8.0...a6c7241b9705d4c14b13bbcc1fd4d0f153cfcd75, which is empty

Sample package diff: https://diff.intrinsic.com/webpack-rtl-plugin/1.8.0/1.8.1

**Comment by blowery** [comment]
Thanks @rarkins!

**Comment by sjparkinson** [comment]
This doesn't seem to work for a number of our packages.

https://diff.intrinsic.com/@financial-times/n-myft-ui/18.5.6/18.6.2

I've emailed Intrinsic with the feedback. Love the idea though!

**Comment by rarkins** [comment]
Hopefully it's a small bug they can fix. Maybe a file exists in one but not the other or something like that.

**Comment by sjparkinson** [comment]
Got an email back 🎉 

> Samuel,
> 
> We fixed the bug you encountered:
> https://diff.intrinsic.com/@financial-times/n-myft-ui/18.5.6/18.6.2
> 
> Your hunch was correct, it had to do with files within dot directories.
> 
> Thanks for the report,
> Thomas Hunter II

**Comment by leethree** [comment]
This package diff thing doesn't work for me ever. I'm always getting `Cannot GET xxx`

https://diff.intrinsic.com/redux-devtools-extension/2.13.5/2.13.8
https://diff.intrinsic.com/react-native-svg/9.3.7/9.4.0
https://diff.intrinsic.com/@types/graphql/14.0.5/14.2.0
https://diff.intrinsic.com/@types/jest/22.2.3/24.0.11

**Comment by rarkins** [comment]
I know they don't support major updates, so ideally we shouldn't link for those. For others, maybe they have a problem with their backend right now. For any "old" links like those in previous comments here, they all still work.

**Comment by tlhunter** [comment]
@leethree @rarkins we had a bug with our cache reaper which led to a full disk. It should be fixed now.

We did specifically disable major to major comparison (and minor to minor comparison where the minor difference is > 5). This was chosen because we assumed diffs would be massive and that Package Diff wouldn't be a good tool to visualize them. If Renovate needs such a feature we can remove the limitation.
