### ISSUE TITLE
Incorrect document on how to use Docker image

### ISSUE THREAD

**Issue by joshuaavalon** [renovatebot/renovate#3325]
**What Renovate type are you using?**
Docker image

**Describe the bug**
In `self-hosting.md`, it stated that you run `docker run renovate/renovate` or use the `renovate/renovate` image with Kubernetes CronJob but it does not work.

This is because the docker image run `--help` instead of actually running `renovate`.

https://github.com/renovatebot/renovate/blob/73c760e37dcf2f1293629584becd2e54c6a8c4ac/Dockerfile#L142

**Did you see anything helpful in debug logs?**
N/A

**To Reproduce**
```
docker run renovate/renovate
```

**Expected behavior**
Either it should run `renovate` automatically or it needs to update documentation.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rarkins** [comment]
Usage of the docker image is exactly the same as for the CLI tool it's based off. You need to keep reading to the "Usage" section.

**Comment by joshuaavalon** [comment]
@rarkins The CLI part just tell you to run `renovate`. But you need to run `docker run renovate/renovate` is **NOT** the same as `renovate`, it is `renovate --help` instead.

Also, the use CronJob YAML in the documentation is also affect by this. 

> Then you just need to add Git author, and mount volumes The final configuration should look like something like this

The CronJob is just print help every hour.

**Comment by rarkins** [comment]
You’re welcome to submit a documentation PR if you think there’s something that would help future users
