### ISSUE TITLE
Release notes includes changes from too many versions for react-hot-loader

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#3330]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The Renovate PR "Release Notes" section for mozilla/treeherder/pull/4767 includes more versions than is updated by the PR.

Specifically: The PR updates [react-hot-loader](https://togithub.com/gaearon/react-hot-loader) from `4.7.2` to `4.8.0`, however the release notes section also includes changes for `4.7.1` and `4.7.2`. (CC @sarah-clements)

**Did you see anything helpful in debug logs?**
N/A

**To Reproduce**

1.  Look at release notes section on mozilla/treeherder/pull/4767

**Expected behavior**
That "release notes" only include the changes for `4.8.0`, since it's the only new version since the existing version.

Many thanks :-)

**Comment by rarkins** [comment]
I noticed this the other day. It's breaking our changelog parser because they are using h1 headings for minor releases and h2 for patches:

![image](https://user-images.githubusercontent.com/6311784/54020181-6c9e0400-418d-11e9-95c1-de13a1bb7d9c.png)

I was thinking to ask them if they'd consider not doing that, as I haven't seen it done before and it makes parsing the changelog pretty close to impossible unless I hardcode a rule in just for their repo.

Have you seen anything like it before and do you think it's "fair" to suggest to them to normalize their headings like other repos?

**Comment by rarkins** [comment]
By the way it's kind of a fluke that the changelog you see is so close to what you need. In Renovate's eyes, the changelogs for all patch releases are missing so it's just showing you the 4.8.0 changelog, which happens to have embedded all 4.7.x patches too

**Comment by edmorley** [comment]
Thank you for your reply :-)
Ah yes makes sense given the difference in heading types. I haven't seen that style anywhere else from what I can remember.

**Comment by theKashey** [comment]
Probably you shall look at https://github.com/conventional-changelog/releaser-tools - RHL uses it for changelogs.

**Comment by rarkins** [comment]
@hutson can we get your opinion/expertise here? I’m surprised to see this varying header length as something deliberate rather than accidental.

**Comment by rarkins** [comment]
Actually I’m a little lost. That tool appears to generate GitHub releases and not Changelog.md

**Comment by theKashey** [comment]
Ok, so then it's about https://github.com/conventional-changelog/standard-version
Sorry, RHL's pipeline was made not by me, and I am not using the same configuration elsewhere.

**Comment by rarkins** [comment]
Thanks. So it appears it’s definitely not unintended (the conventional changelog repo itself uses h1 for Major and minor and h2 for patch) so we need a way to detect and support it.

**Comment by rarkins** [comment]
I know this issue is older, but let's track this feature in #5181 instead
