### ISSUE TITLE
gitFs learn git author/email via API

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3332]
Right now you need to configure `gitAuthor` if using `gitFs`, so that Renovate knows which name/email to use for commits. Ideally we should do a "who am I?" query in teh global worker and learn our username/email and only require `gitAuthor` for cases/platforms where such an API call is not supported.

The query could probably be done in lib/worker/global and saved to global config. That way it could still be overwritten on a per-repo basis if desired.

We should research for each platform (github, gitlab, bitbucket cloud, bitbucket server, azure devops) if a suitable API endpoint exists to learn the name/email of the authorized user (i.e. token).

**Comment by rishabh1403** [comment]
These are the corresponding apis I found related to all platforms
Github :- https://developer.github.com/v3/users/#get-the-authenticated-user
Bitbucket cloud :- https://developer.atlassian.com/bitbucket/api/2/reference/resource/user
Bitbucket Server :- https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8285279136
Gitlab :- https://docs.gitlab.com/ee/api/users.html
Azure :- https://docs.microsoft.com/en-us/rest/api/azure/devops/profile/profiles/get?view=azure-devops-rest-5.0

@rarkins Please confirm, we are currently using these apis for other operations

**Comment by rarkins** [comment]
I think that looks right

**Comment by PixnBits** [comment]
For bitbucket-server [it looks like](https://jira.atlassian.com/browse/BSERV-10169?focusedCommentId=1614339&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1614339) the `X-AUSERNAME` header is available on requests (ex: [`/rest/api/1.0/dashboard/pull-requests`](https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8287078800) which is useful in conjunction with the  [`/rest/api/1.0/users/{userSlug}`](https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8283169424) endpoint

**Comment by rarkins** [comment]
Stepping back a bit:

- `git` needs *someone* to commit as. If the system that Renovate runs on already has a git user configured (e.g. globally) then it will use that.
- We could default the git user to be Renovate Bot - it's not a bad option
- We could also learn the git user associated with the token for some APIs (as discussed above)
- We allow manual configuration via `gitAuthor`
- In theory you can learn a name/email from `gitPrivateKey` if configured

I think this logic might work best:
- If `gitAuthor` is configured then use that
- If no `gitAuthor` is configured but the API supports learning the author, then detect it
- Otherwise, fall back to using `Renovate Bot <bot@renovateapp.com>`
- Ignore the system git user setting completely

**Comment by rarkins** [comment]
Detection and decision making can be done in the global worker, but setting should be done locally per-repo in gitFs's initRepo

**Comment by rarkins** [comment]
I'm going to skip this. If none is configured then we default to the Renovate Bot name/email instead.
