### ISSUE TITLE
limit autodiscover to repos in project

### ISSUE THREAD

**Issue by PixnBits** [renovatebot/renovate#3341]
**What would you like Renovate to be able to do?**
I'd like to limit renovate to autodiscover the repositories in specific Bitbucket Server projects, but not autodiscover _all_ of the projects.

**Describe the solution you'd like**
`$ npx renovate project-name --autodiscover` to look for `projects/project-name/repos/a-repo` but not `projects/another-project/repos/other-repo`

**Describe alternatives you've considered**
I've considered using another tool to list out the repositories (from the API) and then supplying the full list on the CLI
`$ npx renovate project-name/repo-a project-name/repo-b ... project-name/repo-z`

**Additional context**
I'm happy to work on the PR, opening the issue first to see if such a PR would be desired and if maybe I missed something 😅 .

**Comment by rarkins** [comment]
Can you help me understand - why would you have Renovate added to projects that you don't want it to run on? Do you run on those other ones some other time, or never?

**Comment by PixnBits** [comment]
I wouldn't have added renovate, but others could have. The idea is that there are a large number of other projects that could have added our renovate user but I don't necessarily want to spend my compute on their projects. (Ex: could have a couple hundred repos in my projects but tens of thousands in other projects)

**Comment by rarkins** [comment]
In that case I'd suggest a field named `autodiscoverFilter` that takes a Regex string as argument. If present then the autodiscovered repository list would then be filtered based on regex match.

**Comment by rarkins** [comment]
Ideally this would be applied within lib/workers instead of lib/platform so that it's not Bitbucket-specific.
