### ISSUE TITLE
Onboarding PR is only created when it finds valid package managers.

### ISSUE THREAD

**Issue by 123Haynes** [renovatebot/renovate#3343]
**What Renovate type are you using?**
Renovate CLI, Renovate GitHub App, or Renovate Pro?
Renovate Pro for Gitlab

**Describe the bug**
I tried activating renovate for https://gitlab.com/haynes/renovatetest, but because the maven package manager is still deactivated by default, renovate doesn't even create the onboarding PR.

Imho Renovate should always create the Onboarding PR regardless.

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).
```
INFO: Renovating repository
DEBUG: Using localDir: /mnt/renovate/gl/haynes/renovatetest
DEBUG: Setting hostRule
{
  "config": {
    "name": "GitLab",
    "endpoint": "https://gitlab.com/api/v4/",
    "token": "***********",
    "platform": "gitlab",
    "default": true
  }
}
DEBUG: GET
{
  "path": "projects/haynes%2Frenovatetest"
}
DEBUG: haynes/renovatetest default branch = master
DEBUG: GET
{
  "path": "user"
}
DEBUG: Enabling Git FS
INFO: Initialising git repository into /mnt/renovate/gl/haynes/renovatetest
INFO: git clone completed
{
  "cloneSeconds": 3.9
}
DEBUG: GET
{
  "path": "projects/haynes%2Frenovatetest/merge_requests?per_page=100"
}
DEBUG: resetMemCache()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: findFile(.github/renovate.json)
DEBUG: findFile(.renovaterc)
DEBUG: findFile(.renovaterc.json)
DEBUG: config file not found
DEBUG: findPr(renovate/configure, Configure Renovate, !open)
DEBUG: Found no closed onboarding PR
INFO: Repo is not onboarded
DEBUG: getBranchPr(renovate/configure)
DEBUG: Onboarding PR does not exist
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible
DEBUG: Using file match: (^|/)WORKSPACE$ for manager bazel
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite
DEBUG: bundler is disabled
DEBUG: cargo is disabled
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/)Dockerfile$ for manager dockerfile
DEBUG: Using file match: ^\.github/main.workflow$ for manager github-actions
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci
DEBUG: Using file match: (^|/)go.mod$ for manager gomod
DEBUG: gradle is disabled
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: maven is disabled
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Detecting Lerna and Yarn Workspaces
DEBUG: Finding locked versions
DEBUG: Using file match: \.csproj$ for manager nuget
DEBUG: Using file match: ^.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: pip_setup is disabled
DEBUG: pipenv is disabled
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: travis is disabled
DEBUG: Found 0 package file(s)
INFO: Repository has no package files - skipping
INFO: Finished repository
```
**To Reproduce**

1. create a repository that doesn't contain a package manager that is enabled by default.
2. start renovate on that repo for the first time.

**Expected behavior**

The Onbording PR should be created.

**Comment by rarkins** [comment]
The default behaviour should definitely remain as-is, because people often add Renovate to all projects with the understanding that it will only "bother" them for projects that actually have package files. But I'm open to the idea of a config option to enable for the bot owner that does what you suggest - opens onboarding regardless of whether it finds package files.

**Comment by rarkins** [comment]
By the way you can overcome this in the short term by adding `maven: { enabled: true }` to your bot's `config.js`.

**Comment by rarkins** [comment]
I just realised you're referring to the hosted app. In this case the behaviour cannot change, or it will result in thousands of unwelcome PRs. In the meantime though I have defaulted maven to enabled for all gitlab repos and it will be defaulted to enabled for github too next week.

**Comment by 123Haynes** [comment]
@rarkins hmm i tend to disagree.  

>I just realised you're referring to the hosted app. In this case the behaviour cannot change, or it will result in thousands of unwelcome PRs. 

Why is that? To be clear I'm only talking about changing the default for the onboarding PR.  
I don't see how that would result in thousands of unwanted PRs.  
It would only create 1 PR per repo that has enabled renovate, but does not contain any packages that renovate can handle at the moment.  
I can't imagine that this applies to a lot of repos.
Imho an onboarding PR with a warning that renovate can't find anything at the moment would be more transparent than not showing anything and forcing the user to look through the logs.

**Comment by 123Haynes** [comment]
For the hosted version you could also configure it to only apply this for new repos that are being added. That way you won't have to worry about creating a lot of PRs on existing repos at all.

**Comment by rarkins** [comment]
Renovate has nearly 60k repos installed and a lot of those have no package files. Pretty much  every single onboarding PR that results from this (ie thousands) would be “unwelcome”. Users who want to opt into alpha/beta features need to be aware that they need to do so manually.

**Comment by 123Haynes** [comment]
@rarkins  Ok. I understand.  

My point is, at the moment you can't use any alpha/beta features with the hosted app and that it currently fails silently without informing the user.  
I agree with you that it doesn't make sense to change it for existing repos, but it could be something that only works for new repos.  
If we take your idea of adding a config option that allows to open a onboarding pr, that could be something that users can enable in the hosted version.

I'm thinking of a set of boolean flags that are disabled by default, for each repo.  
Something like:
* enable onboarding PR even if no packages are found
* enable alpha/beta feature x for this repo
* enable alpha/beta feature y for this repo

the enable alpha feature xy would simply change the onboardingConfig or create a reconfigure PR.

**Comment by rarkins** [comment]
Such an option could maybe be set for GitLab though, because in that case users have a better say as to which repositories are added to Renovate and presumably don't add it to ones where they don't want an onboarding PR.

In the GitHub case though, it's inconvenient for users to add repositories one by one and therefore most pick the "all repositories" option. In the majority of cases here's what would happen:

- Renovate opens a pointless onboarding PR for a repo with no detected package files
- The user closes the PR unmerged because it's not nice to have it hanging around. This disables Renovate.
- In future, when either the user adds a supported package file, or Renovate adds capabilities to detect new types of package files, the onboarding PR would never come because one has already been closed to disable Renovate.

For such a user, the experience is worse in two ways: they get an onboarding PR when there's no point, and they don't get one when it's useful.

BTW right now there's no way for users to change onboarding settings via the dashboard, but for some large users I have customised their onboarding manually.

**Comment by rarkins** [comment]
> at the moment you can't use any alpha/beta features with the hosted app

By the way, this is not correct. You can add the `renovate.json` manually rather than via the onboarding config, and Renovate will run. 

e.g. add:
```json
{
  "extends": ["config:base"],
  "maven": { "enabled" true }
}
```
