### ISSUE TITLE
Support Versions without Numbers for maven

### ISSUE THREAD

**Issue by 123Haynes** [renovatebot/renovate#3350]
**What would you like Renovate to be able to do?**

Currently renovate does not recognize some maven releases as a version because they don't contain a digit, but instead are ordered alphabetical.
An example would be the Spring Cloud Release trains.

```
               {
                 "datasource": "maven",
                 "depName": "org.springframework.cloud:spring-cloud-dependencies",
                 "currentValue": "Greenwich.SR1",
                 "fileReplacePosition": 4806,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "skipReason": "not-a-version",
                 "updates": []
               },
```

http://central.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/

This bundles a bunch of other components, so one update will normally update ~10-20 dependencies.

**Describe the solution you'd like**

Ideally I would like renovate to recognize this alphabetical version scheme as versions and be able to handle it, because this dependency will be used in a lot of java projects.

**Describe alternatives you've considered**

The alternative would be to document that renovate does not support this versioning scheme so users know that they have to take care of that one themselfs.

**Comment by rarkins** [comment]
If the Maven versioning spec says these are valid versions and happily evaluates/compares them then that means we're non-compliant and should update our lib/versioning/maven.

If it's not valid according to Maven then to support this we'd want to use or extend our existing "loose" versioning. It seems that even pure alphabetical comparisons could work in this case, because the first part/name is deliberately alphabetical over time (e.g. Greenwich > Finchley) and also SR2 > SR1 > RELEASE.

**Comment by rarkins** [comment]
@zharinov could you check this out and let me know what the Maven spec/implementation does?

**Comment by alekseibevzenko** [comment]
@rarkins @zharinov Hi, guys
I'm facing with problem when renovate (release 19.98.0) trying to update dependency to older version:
Hoxton.SR1 to Hoxton.RELEASE
https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies

Log:
  {
"datasource": "maven",
 "depName": "org.springframework.cloud:spring-cloud-dependencies",
 "currentValue": "Hoxton.SR1",
"fileReplacePosition": 1283,
"registryUrls": [
      "https://repo.maven.apache.org/maven2",
      "http://some-private-artifactory/artifactory/repo"
],
"groupName": "spring.cloud.version",
"updates": [
     {
     "fromVersion": "Hoxton.SR1",
      "toVersion": "Hoxton.RELEASE",
      "newValue": "Hoxton.RELEASE",
     "newMajor": null,
     "newMinor": 0,
     "updateType": "minor",
     "isSingleVersion": true
}
 ]

**Comment by rarkins** [comment]
@alekseibevzenko please raise a new issue. It would be helpful to know:

1. Did this behaviour change, and if so then in which release
2. Do you have a reference to `SR` syntax within the Maven version specification?
