### ISSUE TITLE
Allow arbitrary encrypted properties

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#3361]
**What would you like Renovate to be able to do?**

From my reading of the code and the documentation, you can encrypt any property (and there is some special handling for `npmToken`), but I can't see any way to encrypt authentication for `hostRules`

**Describe the solution you'd like**

My ideal solution would be something like this

```json
"encrypted": {
    "gradlePassword": "..."
  },
  "hostRules": [
    {
      "platform": "gradle",
      "endpoint": "...",
      "username": "...",
      "password": "${GRADLE_PASSWORD}"
    }
  ]
```

**Describe alternatives you've considered**

I think I could hijack `npmToken`, as there's special handling for that, but ideally I'd like to have any amount of encrypted strings in my config

**Additional context**

**Comment by rarkins** [comment]
When I wrote it, I was intending it to work like this:

```
  "hostRules": [
    {
      "platform": "gradle",
      "endpoint": "...",
      "username": "...",
      "encrypted": {
        "password": "skldfjalsdjflasjflasjdflajslfjaslkfjals"
      }
    }
  ]
```

Although, it was a long time ago and before hostRules. Also: there's no platform=gradle, you probably want platform=maven as Gradle looks up the Maven datasource.

**Comment by JamieMagee** [comment]
Ah! I can't believe I missed this. I'll try it now. Thank you!
