### ISSUE TITLE
url field in http_archive rule in a Bazel WORKSPACE file wasn't updated

### ISSUE THREAD

**Issue by smukherj1** [renovatebot/renovate#3369]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
In [PR](https://github.com/bazelbuild/rules_k8s/pull/279), renovate is attempting to update the version of com_google_protobuf. It updated the sha256 digest and strip-url correctly but did not update the commit sha in the url field.

**Did you see anything helpful in debug logs?**
My repo doesn't show up in the logs. It's possible this happens because I wasn't the one who configured renovate in our org.

**To Reproduce**
I suspect http_archive using the "url" field may have this problem. I haven't confirmed this. [PR](https://github.com/bazelbuild/rules_k8s/pull/278) using the "urls" field worked fine.

**Expected behavior**
Expected the commit sha in the "url" field [here](https://github.com/bazelbuild/rules_k8s/pull/279/files#diff-09498dbadf45966909850dc8a47ebb13R26) to be updated.

**Comment by smukherj1** [comment]
https://github.com/bazelbuild/rules_docker/pull/718/files is another case where we have the "urls" field with two tarball links but neither was updated. So maybe this problem is not limited to just the "url" field?

**Comment by rarkins** [comment]
@smukherj1 in the initial support for http_archive, it was limited to `url` only. I suspect/hope that the issue is just a matter of better regex, but for urls it will take some more work.

Can you raise a separate issue documenting your requirements for `urls` support with `http_archive`? e.g. exactly how the bazel build mirror is calculated or if the commit hash can just be copied across from the github url?

**Comment by rarkins** [comment]
@smukherj1 could you tick the Rebase/retry box on PRs like this? https://github.com/bazelbuild/rules_k8s/pull/279

**Comment by Dmitry9** [comment]
@rarkins Do we need a test for this issue?

**Comment by rarkins** [comment]
@Dmitry9 it would be good to add one as per @smukherj1's example, but we already had 100% coverage and you'd verified it manually so I decided to merge already so it can be tested in the field too

**Comment by smukherj1** [comment]
@rarkins I edited the comment by ticking the Rebase/retry box but Renovate doesn't seem to be submitting a change?

**Comment by smukherj1** [comment]
Nevermind. It just sent a commit and it updated the url correctly. Thanks!

Referring to https://github.com/bazelbuild/rules_k8s/pull/279
