### ISSUE TITLE
Support "urls" field in Bazel WORKSPACE files

### ISSUE THREAD

**Issue by smukherj1** [renovatebot/renovate#3370]
**What would you like Renovate to be able to do?**
In [PR](https://github.com/bazelbuild/rules_docker/pull/718/files), renovate skipped over the "urls" field because it had more than one link. Apparently renovate doesn't support updating multiple urls at the same time if specified in an http_archive. 

This is a follow up to the comment [here](https://github.com/renovatebot/renovate/issues/3369#issuecomment-472062898).

**Describe the solution you'd like**
Consider using https://github.com/google/skylark to natively parse Skylark files so that multiple items in the "urls" list can be updated without the need for potentially flaky regex.

**Describe alternatives you've considered**
Presently manually updating these dependencies.

**Comment by smukherj1** [comment]
For the Bazel mirror link [here](https://github.com/bazelbuild/rules_docker/pull/718/files), updating here would be replacing the old commit sha in the link with the new commit sha. Maybe renovate can simply try to replace the occurrence of the <old commit sha>.tar.gz in every link specified to "url" with <new commit sha>.tar.gz?

**Comment by rarkins** [comment]
Thanks @smukherj1. If we can "dumbly" replace the tar.gz in every link with the same value then it definitely makes the implementation much easier.

**Comment by Dmitry9** [comment]
@smukherj1 is mirror urls for Bazel serve as a list of sources to fetch from, and have Bazel try them in some order before failing?

**Comment by rarkins** [comment]
@Dmitry9 we don’t need to worry about that. We can just replace the tar gz ref

**Comment by smukherj1** [comment]
@Dmitry9 not 100% sure but it seems it's highly likely that Bazel tries each of the links in order picking the first one that works. If all of them fail, Bazel declares the repository rule target a failure.

**Comment by Dmitry9** [comment]
When I do:
```shell
$ curl https://mirror.bazel.build/github.com/bazelbuild/bazel-toolchains/archive/d665ccfa3e9c90fa789671bf4ef5f7c19c5715c4.tar.gz
```
success.
also in browser:
```url
https://github.com/bazelbuild/bazel-toolchains/archive/d665ccfa3e9c90fa789671bf4ef5f7c19c5715c4.tar.gz
```
success.
Now I try to replace a hash part with last commit sha e.g. 
...archive/{REPLACEMENT}.tar.gz 
```shell
curl -s https://api.github.com/repos/bazelbuild/bazel-toolchains/commits/master | jq '.sha'
"6cde7149ff8deae7cdb7366ba392249e4832cad3"
```
[upgrade.newDigest](https://github.com/renovatebot/renovate/blob/master/lib/manager/bazel/update.js#L8)
"6cde7149ff8deae7cdb7366ba392249e4832cad3"

In browser:
```url
https://mirror.bazel.build/github.com/bazelbuild/bazel-toolchains/archive/6cde7149ff8deae7cdb7366ba392249e4832cad3.tar.gz
```
success.

But:
```url
https://mirror.bazel.build/github.com/bazelbuild/bazel-toolchains/archive/6cde7149ff8deae7cdb7366ba392249e4832cad3.tar.gz
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: bazel-mirror/github.com/bazelbuild/bazel-toolchains/archive/6cde7149ff8deae7cdb7366ba392249e4832cad3.tar.gz</Details></Error>

**Comment by rarkins** [comment]
I think it's OK to ignore the internals of how bazel does their mirroring. I think the mirror is just there for times when GitHub could be down or someone deletes an archive that is relied on, so it's OK if it's not a real-time mirror.

**Comment by smukherj1** [comment]
@Dmitry9 what @rarkins said is correct. We don't back up every commit to the Bazel mirror, only specific commits we deem to be important. Thus, I think renovate doesn't need to concern itself with which commits are safe to dumbly replace and which are not.
