### ISSUE TITLE
Configure Renovate PR opened though renovate is already configured

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3371]
**What Renovate type are you using?**
Renovate GitHub App?

**Describe the bug**
- today (March 12, 2019, 15:26:58 UTC) renovate suddenly closed https://github.com/dmx-io/dmx-webhooks/pull/111 (from `renovate/docker-all-dependencies` branch)
- in the same time it opened https://github.com/dmx-io/dmx-webhooks/pull/112 from `renovate/configure` branch

**Did you see anything helpful in debug logs?**
I see:
```
INFO: Bad credentials
```

**Additional context**
The current `renovate.json`:
```json
{
  "commitMessagePrefix": "[renovate] ",
  "groupName": "all dependencies",
  "labels": [
    "renovate"
  ],
  "npmToken": "<redacted>",
  "packageRules": [
    {
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    },
    {
      "managers": [
        "circleci"
      ],
      "schedule": "at any time"
    }
  ],
  "rangeStrategy": "bump",
  "schedule": "before 3am on the first day of the month"
}
```

the new `renovate.json` (in the opened PR):
```json
{
  "extends": [
    "config:base"
  ]
}
```

The opened PR displays:
```
Failed to look up dependency @dmx/koa-joi-router
Failed to look up dependency @dmx/npm-dmx-sdk
Failed to look up dependency @dmx/npm-dmx-utils
Failed to look up dependency @dmx/npm-koa-qs
Failed to look up dependency @dmx/npm-logger
```
so maybe it's a temporal problem with NPM.

**Comment by rarkins** [comment]
Hi, thank you for alerting me to this and sorry for the inconvenience. It should now be resolved and that mistaken onboarding PR has been autoclosed.

FYI we saw a temporary glitch with GitHub returning "bad credentials" for some queries and unfortunately our "getFileList()" function was designed to catch errors and return an empty file array. Instead it should have just thrown the error and exited, which I've now fixed.
