### ISSUE TITLE
Rubygems queries can trigger 429 Too Many Requests

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3373]
The Rubygems host appears to be much more strict on queries than others, and even on a single repo we can get 429 errors.

There's some discussion here: https://meta.discourse.org/t/rubygems-too-many-requests-problem-returns/102499/16

That discussion implies you wouldn't get rate limited if it wasn't for thousands of requests, which I doubt we are doing. But we either need to (a) reduce the concurrent queries, or (b) cache better.

Something I was interested to see was that Bundler uses this file: https://index.rubygems.org/versions

It's 23MB uncompressed but it appears to contain a list of every version of every package. One idea is:

- Fetch the master versions feed and cache that file once per 5 minutes
- For each dependency we need, check if we have a cached version of it (no expiry) and if the versions in the cache match the versions in the master versions feed. If so then reuse, if not then fetch again and overwrite the cache

This way, once the cache is initially populated, we should only be fetching package metadata after it has a new version published.

Cc @sleekybadger @bjeanes

**Comment by rarkins** [comment]
We could also potentially do HTTP caching (e.g. to get 304 responses if content hasn't changed) but according to the above logic, we should only be querying when we know content *has* changed, and also I'm sure the Rubygems index is updated at least every 5 minutes.

**Comment by rarkins** [comment]
Examples of URLs we currently use (according to [the api](https://guides.rubygems.org/rubygems-org-api/)):
https://index.rubygems.org/api/v1/gems/activesupport.json
https://index.rubygems.org/api/v1/versions/activesupport.json

Maybe we should use:
https://index.rubygems.org/info/activesupport

**Comment by bjeanes** [comment]
I think pulling the index is a pretty good idea, to be honest. IIRC, Bundler does something like this internally for exactly this reason.

**Comment by rarkins** [comment]
Right how we collect these fields from the full JSON:
```
    const releases = versions.map(
      ({
        number: version,
        platform: rubyPlatform,
        created_at: releaseDate,
        rubygems_version: rubygemsVersion,
        ruby_version: rubyVersion,
      }) => ({
        version,
        rubyPlatform,
        releaseDate,
        rubygemsVersion,
        rubyVersion,
      })
    );
```

Using the non-JSON "info" result, I think we can get ruby and ruby gems version, and maybe also platform too - but I haven't found an example to verify that. It looks like we *won't* get release date, but right now we don't use that field within Renovate anyway.

**Comment by rarkins** [comment]
*Presumably* these fields only work with rubygems and we still need to use the official API for non-rubygems datasources

**Comment by rarkins** [comment]
Now I just noticed that the versions file on rubygems.org says `created_at: 2017-03-27T04:38:13+00:00` and probably hasn't been updated since. The last `activesupport` entry there is `5.1.0.rc1`, while its [rubygems page](https://rubygems.org/gems/activesupport) confirms it was published `March 20, 2017 (359 KB)`. In short: that `versions` URL seems pointless now and I'm not sure if/why Bundler would query it.

@indirect is there any chance you could offer some quick guidance?

**Comment by rarkins** [comment]
Rate limiting: https://github.com/rubygems/rubygems-infrastructure/blob/7b2bedec0d5b08f02d6b3bcde162304f10c0daa3/cookbooks/rubygems-balancer/templates/default/site.conf.erb#L13-L15

**Comment by rarkins** [comment]
Right now we query all managers in parallel, 5 package files at a time per manager, and 10 deps at a time per package file. Our code performs two queries per dependency: https://github.com/renovatebot/renovate/blob/cace89eeec5aed87be8652459004008bbe9eb3d7/lib/datasource/rubygems/get.js#L53-L68

**Comment by rarkins** [comment]
It looks like Bundler may use the dependencies API and query all deps at once? https://github.com/bundler/bundler/blob/d44d803357506895555ff97f73e60d593820a0de/lib/bundler/fetcher/dependency.rb#L75-L79

**Comment by rarkins** [comment]
We could query the info endpoint once a day per dependency, as the home page / source URLs should not change often - this would reduce queries by nearly half.

**Comment by rarkins** [comment]
When you query the versions API like we do now, you get this type of entry, including ruby and rubygems versions:
![image](https://user-images.githubusercontent.com/6311784/54303399-30223c00-45c3-11e9-9ce1-8d4e26fcb630.png)

If you query http://index.rubygems.org/api/v1/dependencies.json?gems=activesupport, you miss out on those ruby requirements:
![image](https://user-images.githubusercontent.com/6311784/54303455-4defa100-45c3-11e9-89e1-568cc1c72a2c.png)

**Comment by bjeanes** [comment]
Buy you can re-query just the ones which have an update, surely?

**Comment by rarkins** [comment]
Hmm, good idea. More complex but less API requests.

**Comment by indirect** [comment]
Please use the /versions and /info/* endpoints to get information about gems. The dependencies.json API is both very costly on the server-side and contains far less information. The thinking behind the versions API is written up at more length here: https://andre.arko.net/2014/03/28/the-new-rubygems-index-format/.

**Comment by indirect** [comment]
(Bundler uses gzip transport compression to reduce the network traffic down to 4-5MB when nothing is cached, and then uses HTTP range requests to fetch only the portion of the file after the end of the file it already has cached. You can use the md5 in the etag header on the response to verify that your combined file on disk matches the md5 of the entire file on the server.)

**Comment by rarkins** [comment]
@indirect thanks very much for your advice. The `/versions` endpoint appears to be serving up March 2017 data though, so I can't see its utility. Or am I somehow doing something wrong?

**Comment by indirect** [comment]
@rarkins the `created_at` date is not the last time the file was updated, it's the timestamp that the file was last fully cache-busted and realphabetized from scratch. That file continuously has new gems added to the end of it as the gems are published.

**Comment by rarkins** [comment]
@indirect thanks. I naively picked a package to check the releases of and didn't realise that there could be *multiple* lines per package.

**Comment by rarkins** [comment]
So here's what I think we need to do:

1. Download and cache `/versions`
2. Periodically (every 5 minutes? 10 minutes?) check if it's changed. If we do need to refresh it then ideally use a http range request like Bundler does to only download the differential
3. Package metadata (where we fetch home page and source URL from) can be cached for maybe a day
