### ISSUE TITLE
Reconsider/document global variables

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3376]
- [ ] appMode  #6371
- [ ] gitAuthor #6540
- [ ] renovateCache (partial done) #6198
- [ ] trustLevel #6541
- [x] updateRubyGemsVersions ( can stored in module scope ?) #6199

**Comment by rarkins** [comment]
#### global.appMode

In the past we've needed to adjust GitHub behaviour at times depending on whether it's running as a regular user or an app.

1. `lib/config/index.js`: skip setting default credentials if in app mode
2. `lib/platform/github/gh-got-wrapper.js`: Setting mandatory app request headers
3. Changing format of gitFs URL if it's an app or not

**Comment by rarkins** [comment]
#### global.repoCache

This is used for any datasource or platform to cache data in memory that should be cleared for every repository. Previously we used to host this cache separately but then it made it a challenge to find and reset all the various uses throughout the repo.

Used in many places, but maybe we can add a lib/util/cache module that's required by the functions that use it.

**Comment by rarkins** [comment]
#### global.trustLevel

If it's "high", it means the bot owner trusts the repo admins, and so some security settings are loosened. Right now this is mostly just whether or not to pass the full env to calls like "npm install"

**Comment by rarkins** [comment]
#### global.testNpmRetries

Used only for testing

**Comment by rarkins** [comment]
#### global.logger

Pretty much every single file in the repository needs access to the logger. Before, this meant lots of requires like `require('../../../util/logger')`. Moving it to global removed the need for such code. If there's a better trade-off, I'm open to it.

**Comment by rarkins** [comment]
#### global.renovateError

This is used for the simple reason of making sure `renovate ...` exits with a non-zero code if any `logger.error()` messages were seen.

**Comment by rarkins** [comment]
#### global.renovateUsername

This is used just in GitHub-only for now, initially to filter issues by creator. We could maybe move this to lib/util/identity.js or something in lib/workers/global

**Comment by rarkins** [comment]
#### global.renovateVersion

This is detected in global and then printed for each repository init. It's useful to know exactly which Renovate version was used for each run.

**Comment by rarkins** [comment]
#### global.platform

Like logger, platform calls were used nearly everywhere until they were made into a global. It's not perfect, but makes things more clean. Most files in lib/worker make calls to platform.

**Comment by rarkins** [comment]
#### global.renovateCache

This is used for caching both between repos as well as between renovate runs. The app sets its own global.renovateCache to save from needing to "monkey patch" the file within the renovate repo.

**Comment by rarkins** [comment]
Ideas:

- Create a `lib/util/metadata.js` that stores/replaces appMode, trustLevel, renovateUsernam, renovateVersion
- Create `lib/util/cache/repo.js` and `lib/util/cache/persistent.js` to replace `repoCache` and `renovateCache`

**Comment by ViceIce** [comment]
`global.logger` already removed, see #3671

**Comment by rarkins** [comment]
Closing in favor of child issues
