### ISSUE TITLE
Maven not supporting packageRules allowedVersions operator "!="

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#3390]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
When using [something like](https://github.com/bagage/gradle-template/blob/master/renovate.json#L2-L15):

```
	"packageRules": [
		{
		    "packageNames": ["io.gitlab.arturbosch.detekt:detekt-formatting"],
		    "allowedVersions": "!=1.0.0.RC9.2"
		},
```
Renovate yields that this is an invalid version and it ignores it:

>  WARN: Invalid allowedVersions: "!=1.0.0.RC9.2" (repository=bagage/gradle-template)
       "depName": "io.gitlab.arturbosch.detekt:detekt-formatting"

**To Reproduce**

1.  Clone https://github.com/bagage/gradle-template
2.  Run renovate

**Expected behavior**
allowedVersions should be handled as in other versioning systems.

**Comment by rarkins** [comment]
I think it may be parsed using npm semver in the validation so it might be the version string that’s rejected and not the `!=`

**Comment by bagage** [comment]
The issue is the same if I use `!=5.2.0` for instance:

```
 WARN: Invalid allowedVersions: "!=5.2.0" (repository=bagage/gradle-template)
       "versionScheme": "semver",
       "depName": "gradle"
```

**Comment by rarkins** [comment]
`< 5.2.0 || > 5.2.0` should pass validation but then might fail *later* when the packageRule is applied using maven versioning

**Comment by bagage** [comment]
While it works for "simple" version (5.2.0), it still not works for maven odd versions:

>  WARN: Invalid allowedVersions: "< 1.0.0.RC9.2 || > 1.0.0.RC9.2" (repository=bagage/gradle-template)

**Comment by rarkins** [comment]
Are you able to create a test repo to reproduce this? We *do* attempt to use the right versionScheme when evaluating allowedVersions, so I'm confused as to what's going on.

**Comment by rarkins** [comment]
actually never mind - I see you did reference a public repo in the initial description

**Comment by rarkins** [comment]
If we're using maven version scheme though, it means we need to use maven syntax. Can you try using the syntax on the left side of this table? https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

**Comment by bagage** [comment]
Hmm indeed it looks better. At least there are no more errors, but there seems to be another issue.

To sum up, I am declaring `detekt-formatting RC13` [in code](https://github.com/bagage/gradle-template/blob/master/build.gradle#L18), but `RC14` is available. I tell Renovate [to ignore RC-9.2](https://github.com/bagage/gradle-template/blob/master/renovate.json#L13). 

I would expect Renovate to create a MR for RC14 but it does not. In logs, there are no `updates` nor `releases` filled for detekt formatting while there should be (see [central repository](https://repo.maven.apache.org/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/)):

```
               {
                 "name": "detekt-formatting",
                 "depGroup": "io.gitlab.arturbosch.detekt",
                 "depName": "io.gitlab.arturbosch.detekt:detekt-formatting",
                 "currentValue": "1.0.0-RC13",
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2/",
                   "https://repo.spring.io/snapshot",
                   "https://repo.spring.io/milestone"
                 ],
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": "https://github.com/arturbosch/detekt",
                 "homepage": "https://arturbosch.github.io/detekt",
                 "releases": []
               },
```

**Comment by rarkins** [comment]
One problem is that there are multiple versions that count as greater than your current RC:
![image](https://user-images.githubusercontent.com/6311784/54616714-6139bb00-4a60-11e9-8a40-d709eea10ee7.png)

But the reason for no upgrade is that our maven versioning appears to filter out *all* versions with this `allowedVersions`:
![image](https://user-images.githubusercontent.com/6311784/54616866-a4942980-4a60-11e9-9493-5c20659e84b8.png)

**Comment by rarkins** [comment]
Ugh. The problem is that our Maven versioning doesn't actually support range matching: https://github.com/renovatebot/renovate/blob/006b28ec821fdedd0f89cacf172f445b5b07732f/lib/versioning/maven/index.js#L99

Cc @zharinov

**Comment by rarkins** [comment]
This is now resolved, thanks @zharinov!

Config: https://github.com/renovate-tests/gradle-template/blob/cb2088edbb339edd71cd02ac1623877987837c84/renovate.json#L13
PR: https://github.com/renovate-tests/gradle-template/pull/3
