### ISSUE TITLE
Azure - Support linked work items

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#3395]
**What would you like Renovate to be able to do?**
Azure DevOps supports branch protections, and one of these protections is that every pull request has to have a linked work item (See details [here](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#check-for-linked-work-items)). I would like to have renovate link a work item to each PR that it opens

**Describe the solution you'd like**
I would like to have a work item id in the renovate config, that could be linked to each pull request that is opened against that repository. I think having renovate create a work item would be too much noise, and simply having a single work item that renovate can link all it's PRs against would be sufficient

**Describe alternatives you've considered**
An alternative would be for renovate to create individual work items, and link them to an individual PR. However, I think this would create too much noise. Additionally in my organisation there are restrictions on which fields need to be filled in when a work item is created, which would also add to the complexity of renovate creating work items.

**Comment by rarkins** [comment]
I agree that it sounds best to have a single work item created out of band, which is then used in every create PR call.

Sounds like we'd need a new configuration option, as it doesn't fit into any existing config I can think of.

The remaining question is how it is passed around - e.g is it set once at the start of a repo run or is it passed through every call until it is eventually passed to the create PR function.

**Comment by JamieMagee** [comment]
I think it would be simpler to implement if this was just set once at the start of the repo run.

**Comment by rarkins** [comment]
I'm wondering if the Renovate "master issue" (currently undocumented and about to be released - see example here: #2958) could serve as the work item? Note that for Azure I don't think its markdown supports the checkboxes like GitHub and GitLab do, so it would not be a fully functional master issue on Azure DevOps.

Alternatively we can just have a new config option `azureWorkItem` or `azureWorkItemId` that is passed as part of `platform.initRepo`. If set then we create PRs referencing it and the user is responsible for creating the work issue in advance.

**Comment by JamieMagee** [comment]
Possibly, but I can only see how it would work if `masterIssue` had dual purpose, as a boolean for platforms where it's possible for renovate to create issues, and a number on Azure DevOps, where it's not really possible to create issues on the fly. Unless there was some other configuration property `masterIssueId`, but then that's just Azure DevOps specific anyway, and it might just as well be `azureWorkItem`/`azureWorkItemId`.

I think that having an azure specific configuration property, that is passed at `platform.initRepo`, might be the cleanest option. I can't see renovate ever being able to support work item creation on Azure DevOps. Like Jira, it's just too customisable.

**Comment by JamieMagee** [comment]
@rarkins I'll go ahead and implement an `azureWorkItemId` property.

**Comment by JamieMagee** [comment]
After some investigation, it's currently not possible to link work items with the API. See https://developercommunity.visualstudio.com/content/idea/366535/link-pull-request-to-work-items-using-the-rest-api.html

**Comment by rarkins** [comment]
Closing until this is possible
