### ISSUE TITLE
Support Bazel dependencies declared in files other than WORKSPACE

### ISSUE THREAD

**Issue by smukherj1** [renovatebot/renovate#3413]
**What would you like Renovate to be able to do?**
One common pattern seen in a lot of Bazel repositories is to declare a list of external dependencies of a project in a macro (example https://github.com/bazelbuild/rules_docker/blob/968e0b7c8b3bc7e009531231ac926325cd2745bc/repositories/repositories.bzl#L55).

With such a pattern, in order to import the project I linked to, you can do:
```
http_archive(
    name = "io_bazel_rules_docker",
    ...
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()
```

I would like renovate to update http_archive, git_repository, etc declarations it finds in *any* *.bzl file, not just the WORKSPACE file so that these dependencies are updated as well.

**Describe the solution you'd like**
Include all *.bzl files when searching for Bazel targets that need to be updated.

**Describe alternatives you've considered**
No viable alternatives as far as I know. We are just updating these dependencies manually for now.

**Additional context**
N/A

**Comment by rarkins** [comment]
We can do this in just one line (bazel's `fileMatch`) however I'd want to check first that we gracefully handle the extra white space that's present in the bzl file you linked to.

**Comment by rarkins** [comment]
- [ ] extend bazel's fileMatch to include *.bzl files
- [ ] verify that existing extract and update functions are flexible enough with white space or if they need improving
