### ISSUE TITLE
Support Renovating helm charts

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3414]

**Comment by prateeknayak** [comment]
+1 for this issue

Looks like following code is what checks if it is updating kubernetes manifests or not and skips values.yaml even if it is found by the regex. 
`  
const isKubernetesManifest =
    content.match(/\s*apiVersion\s*:/) && content.match(/\s*kind\s*:/);
  if (!isKubernetesManifest) {
    return null;
  }
`
Could this check be skipped somehow? or do you reckon a new manager needs to be implemented for this?

**Comment by rarkins** [comment]
Disclaimer: I don't use kubernetes or helm daily, but it sounded to me like they're different managers even if the syntax is similar. I assume there would need to be other if/else checks and logic differences between k8s and helm too?

Cc @mxey who wrote the k8s part originally

**Comment by prateeknayak** [comment]
Thanks for your quick response. 

Another manager sounds good, but I think the code base would be pretty similar. Because yamls in helm charts are templated manifests. 

Also, I would also like to understand how renovate would handle 
- multiple images in a one deployment manifest
- multiple deployment manifests in one repo

**Comment by rarkins** [comment]
It's pretty common to have multiple package files per repo and multiple dependencies per package file, so Helm would be no different. Each dependency is tracked to a package file, which is identified by file name. The way dependencies within a package file are identified varies per-manager. In this case it's probably done by line number.

**Comment by srueg** [comment]
This looks like an awesome feature. Thanks @nchashch for your work!

I would also be interested in having support for Helm release CRDs like the [flux Helm operator](https://github.com/fluxcd/helm-operator) uses: https://docs.fluxcd.io/projects/helm-operator/en/latest/references/helmrelease-custom-resource.html

I guess the indexer could be reused from this?
