### ISSUE TITLE
Multiple encrypted npmrc registry entries, new lines not recognised

### ISSUE THREAD

**Issue by fabianbru** [renovatebot/renovate#3417]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I'm trying to add an encrypted npmrc with a NPM_TOKEN for the npm registry and also another PRIVATE_NPM_TOKEN for a private registry, but it won't find the packages. I'm in the initialisation process with the initial PR from renovate. I always get the "Dependency Lookup Warnings".

The content of my project .npmrc:
```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
@privatepackage:registry=https://privatepackageregistry.com/
//privatepackageregistry.com/:_authToken=${PRIVATE_NPM_TOKEN}
```

I can not use different "npmToken" properties, so I decided to hardcode the Tokens and encrypt the whole file (\n for new lines).

The content of the encrypted npmrc:
```
//registry.npmjs.org/:_authToken=xxxxxxxxxxx\n@privatepackage:registry=https://privatepackageregistry.com/\n//privatepackageregistry.com/:_authToken=yyyyyyyyyyy
```

I pasted this into the encryption tool: https://renovatebot.com/encrypt

And used the result in my "package.json":
```
"encrypted": {
  "npmrc": "XYZABC"
},
"ignoreNpmrcFile": true
```

In the logs when yarn tries to get the package it resolves with a 404 error code. In the response object there is a "token" property with:
```
DEBUG: Response code 404 (Not Found)
...
"token": "xx*****************yy"
```
So it looks like it used the first token with all other lines appended, like:
```
"token": "xxxxxxxxxxx\n@privatepackage:registry=https://privatepackageregistry.com/\n//privatepackageregistry.com/:_authToken=yyyyyyyyyyy"
```

If I use only the "normal" registry with auth token line (only 1st line) it will work for those packages. If I use only the two lines (2nd and 3rd line) for scoped packages in a private registry it also won't find them.

```
INFO: Dependency lookup failure: unauthorized
{
  "pkgUrl": "https://privatepackageregistry.com//n//privatepackageregistry.com/:_authToken=yyyyyyyyy/@privatepackage%2Fprivatepackagename",
...
```

It looks like the new line is converted to "/n" and is not recognised as new line? I definitely used "\n" before encryption. Both issues look for me like new lines are buggy/broken?

**To Reproduce**

1.  Add encrypted npmrc content with multiple registries with auth token
2.  Use yarn

**Expected behavior**
If I use an encrypted npmrc file content with multiple entries, all of the registries with specified auth tokens should work.

**Additional context**

**Comment by rarkins** [comment]
> I'm trying to add an encrypted npmrc with a NPM_TOKEN for the npm registry and also another PRIVATE_NPM_TOKEN for a private registry

Unfortunately this won't work. `NPM_TOKEN` is a special case we look for - we don't look for any others.

> I can not use different "npmToken" properties, so I decided to hardcode the Tokens and encrypt the whole file (\n for new lines).

I'm surprised you didn't hit the encryption limit. But if you *didn't*, then I agree that this would be the best approach to take.

> So it looks like it used the first token with all other lines appended

Thank you for troubleshooting this. From your analysis it definitely looks like there's a problem with newlines.

**Comment by rarkins** [comment]
@fabianbru thanks again for documenting your troubleshooting so well. Of course after all that it turned out to be a one-line fix: https://github.com/renovatebot/renovate/commit/5d74650195cea3341f474915df3a17d99ebc5e6f

Please let me know how you go with that encrypted npmrc another time - it should work now

**Comment by fabianbru** [comment]
Thanks @rarkins for your quick response and also a **fix, that solves the problem! Great work!** 🎉 

> I'm surprised you didn't hit the encryption limit.

I tested it out, I have about 40-50 characters left. So for a third registry it won't work, but for two it's enough.

**Comment by rarkins** [comment]
Thanks for the confirmation!
