### ISSUE TITLE
renovatebot blind to new releases of some python module dependencies

### ISSUE THREAD

**Issue by porridge** [renovatebot/renovate#3418]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

Never sends a PR to update [this line](https://github.com/mesosphere/dcos-commons/blob/7dc1a18/frozen_requirements.txt#L91) even though it does send PRs for plenty of other dependencies in this file ([example](https://github.com/mesosphere/dcos-commons/pull/2984), and this version is so old that it's not even available on PyPI anymore.

**Did you see anything helpful in debug logs?**
It seems that it does not see any releases for this dependency on PyPI. The log contains:
```
{ "depName": "pygobject", "currentValue": "==3.26.1", "lineNumber": 90, "datasource": "pypi", "updates": [], "warnings": [], "sourceUrl": null, "homepage": "https://pygobject.readthedocs.io", "releases": [] }, 
```

**To Reproduce**

1.  Create repository with the aforementioned line in `requirements.txt`
2.  Configure renovatebot

**Expected behavior**
PRs should be sent to update the aforementioned dependency.

**Additional context**
Could the root cause be that the letter case does not match? The module name is in camel case on https://pypi.org/project/PyGObject/#history

**Comment by rarkins** [comment]
It could be because of case, but also perhaps because 3.26.1 is missing from the list of releases. We'll need to debug.
