### ISSUE TITLE
Provide capability to store configuration in .renovate\renovate.json

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/renovate#3426]
**What would you like Renovate to be able to do?**
Store configuration in a subfolder such as `.renovate`

**Describe the solution you'd like**
Provide capability to store configuration in following locations:
- `.renovate\renovate.json`
- `renovate.json`

**Additional context**
This allows us to keep the root of our repo nice & clean

**Comment by rarkins** [comment]
You can use .github/renovate.json already if that works

**Comment by tomkerkhove** [comment]
Great to hear, didn't see this in the docs here - https://renovatebot.com/docs/configuration-options/

Shall I send a PR?

**Comment by rarkins** [comment]
Yes to both. FYI here are the file names supported: https://github.com/renovatebot/renovate/blob/9ac80ddd037c68c6150ec8598b6388ec00d636f9/lib/config/app-strings.js#L5-L11
