### ISSUE TITLE
Bitbucket server hostname is undefined and servers are not aligned

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/renovate#3427]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
1. When git clone happens, hostname seems to be undefined
2. The rest api lives at port 80 but the clone url lives at port 7999
   - Current work around is to avoid using git.storage.getUrl and instead just hardcode my personal url `ssh://git@${host}:7999/${repository}.git`. Obviously this won't work for everyone. With this minor change though, I was able to create a renovate onboarding PR on my bitbucket server so kudos to everyone who chipped into that endeavor!

**Did you see anything helpful in debug logs?**
1. Issue seems to be around `initRepo` where I think the property being passed in is `host` instead of `hostname`. 

**To Reproduce**

My configuration file:
```
module.exports = {
  platform: "bitbucket-server",
  endpoint: "https://stash.where-i-work.com",
  gitFs: "ssh",
  username: "username",
  password: "Fat chance I'll leak this",
  autodiscover: false,
  repositories: ["abc/sesame-street"],
  dryRun: false,
  logLevel: "debug"
};
```

npm run renovate

**Expected behavior**
Renovate to run on boarding successfully

**Comment by rarkins** [comment]
BitBucket Server was designed for https or http gitFs. What if you leave out the gitFs line from your config? It defaults to https if not configured manually.

**Comment by k2snowman69** [comment]
Ha yep, that did it :-). Thanks!

**Comment by rarkins** [comment]
Thanks. We will make it so that the setting is autodetected one day

**Comment by k2snowman69** [comment]
I may have spoken too soon... I think my local edits may have actually caused a false positive. This may reopen early next week when I have more time to explore this.

**Comment by k2snowman69** [comment]
From what I can tell it's maybe because I have spaces in my password and when it's sent via the url spaces are translated to `%20`which then results in a bad password? That's all I can figure if this works for other people :-)

**Comment by rarkins** [comment]
It’s a possibility. Not sure GitHub lets you reopen if I closed but open a new one if so
