### ISSUE TITLE
Provide documentation preview in PR experience

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/renovate#3430]
**What would you like Renovate to be able to do?**
Provide documentation preview in PR experience via Netlify

**Describe the solution you'd like**
PRs that include documentation changes should be available in a rendered way to verify that the markup is rendered correctly.

Netlify is a great way to do this which I'm using for https://github.com/tomkerkhove/promitor.

**Additional context**
This is not a must, just giving a suggestion to improve PR review flow

**Comment by rarkins** [comment]
Unfortunately this won't be possible. The website is actually built from another repo, and its builds are triggered by webhooks, and.. long story short it's not really feasible to have a Netlify preview based on PRs in *this* repo. I think if GitHub preview shows the markup as OK, that's the best we can do
