### ISSUE TITLE
Maven: support nested version placeholders

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3461]
**What would you like Renovate to be able to do?**

Renovate placeholders in pom.xml files.

**Describe the solution you'd like**

Renovate correlates variables and uses those for lookup.

Example reference: 

https://github.com/swagger-api/swagger-parser/blob/f94d751a13c824c5220c0ce75281e1041ef8da17/modules/swagger-parser/pom.xml#L40

https://github.com/swagger-api/swagger-parser/blob/f94d751a13c824c5220c0ce75281e1041ef8da17/pom.xml#L290

**Comment by zharinov** [comment]
It will be more sophisticated solution than we have right now. I'll research it.

**Comment by rarkins** [comment]
We'll need to do it like npm, where we first parse all files individually, and then we run a "correlation" across all of them to enrich each package file (such as ignoring local dependencies in monorepos). We could use the same approach to perform variable correlation across files.

**Comment by zharinov** [comment]
What if one placeholder is used to many dependencies? Find the greatest common version?

**Comment by rarkins** [comment]
@zharinov in a perfect world, yes - but I worry it may be too complex to implement.
