### ISSUE TITLE
Pipfile with extras specifications and no version fails to parse

### ISSUE THREAD

**Issue by Delphinator** [renovatebot/renovate#3477]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
reonvate fails to parse a Pipfile with a dependency with extras and no version

**Did you see anything helpful in debug logs?**
```
 INFO: Renovating repository (repository=my/repository)
 INFO: Repository config (repository=my/repository)
       "configFile": "renovate.json",
       "config": {
         "extends": ["config:base"],
         "pipenv": {"enabled": true},
         "pip_setup": {"enabled": true},
         "labels": ["dependencies"]
       }
 INFO: Found gitlabci package files (repository=my/repository)
 INFO: Found npm package files (repository=my/repository)
ERROR: Repository has unknown error (repository=my/repository)
       "err": {
         "message": "Cannot convert object to primitive value",
         "stack": "TypeError: Cannot convert object to primitive value\n    at RegExp.exec (<anonymous>)\n    at Object.entries.map.x (/builds/continous-integration/renovate/node_modules/renovate/lib/manager/pipenv/extract.js:65:47)\n    at Array.map (<anonymous>)\n    at extractFromSection (/builds/continous-integration/renovate/node_modules/renovate/lib/manager/pipenv/extract.js:47:6)\n    at Object.extractPackageFile (/builds/continous-integration/renovate/node_modules/renovate/lib/manager/pipenv/extract.js:32:8)\n    at module.exports.(anonymous function).params (/builds/continous-integration/renovate/node_modules/renovate/lib/manager/index.js:67:34)\n    at getManagerPackageFiles (/builds/continous-integration/renovate/node_modules/renovate/lib/workers/repository/extract/manager-files.js:54:25)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Finished repository (repository=my/repository)
```

**To Reproduce**

1.  Create repository with the following pipfile
```
[packages]
raven = {extras = ['flask']}
```
2. Enable pipenv for the repository
3. Run renovate

**Expected behavior**
`"*"` is used as version and the additional dependencies added by the extras are considered.

**Comment by Delphinator** [comment]
I've been thinking about this a little more. This bug, #3462 and #3282 have a common underlying problem. The code in `lib/manager/pipenv/extract.js` assumes a string if none of the special cases match (like an object with a `version` or `git` property).

As far as I understand the Pipfile-format `"<PEP508-version-spec>"` is just a shorthand for `{version: "<PEP508-version-spec>"}` and `"*"` is the default version. As a result `{}` is a perfectly acceptable version specifier equivalent to `"*"`  (full example Pipfile below).

Wouldn't it be better to convert the shorthand to an object and then do `version = version_specifier.version || "*"` to get the actual PEP50-version-spec. This would work in all cases where the source of the package is a pypi-repository and not for example a git repository. Packages from git repositories get ignored currently so those should not be an issue anyway.

### [1] Pipfile with a few equivalent version specifications

```
[packages]
# all of these version specifiers make pipenv use the same version as "*"
Flask = "*"
Flask-Caching = '*'
flask-mako = {}
Flask-SQLAlchemy = {version = "*"}
Flask-Login = {editable = true}
```

**Comment by rarkins** [comment]
@Delphinator I agree with your suggestion - we should just massage the object to include a `*` version if it's not found.

**Comment by Dmitry9** [comment]
In progress.

**Comment by Dmitry9** [comment]
@rarkins please look into this comment: 
For the [test repo](https://github.com/Dmitry9test/renovate-test/blob/master/Pipfile) I assume that
`raven = {extras = ['flask']}` should map to
```
raven = '*'
flask='*'
```
but got:
```
DEBUG: Skipping dependency with malformed version specifier "*". (repository=Dmitry9test/renovate-test)
```
At the same time for the [records](https://github.com/kennethreitz/records) dependancy, which is `extars free` I don't understand why `fromVersion` is equal to `0.5.3` when
```javascript
allSatisfyingVersions[0] === '0.4.2'
true

rangeStrategy === 'replace'
true
```

![draft22](https://user-images.githubusercontent.com/22542906/56096353-c235a100-5eef-11e9-8aa0-1fd995315166.png)
![draft3](https://user-images.githubusercontent.com/22542906/56096435-ba2a3100-5ef0-11e9-8ad8-049e71194020.png)

**Comment by rarkins** [comment]
Be sure to add a `skipReason` to any `*` deps so that they’re not looked up.

**Comment by rarkins** [comment]
Also, I don’t know what the nested terminology really means but I know it won’t matter of the value is `*` because we won’t upgrade it anyway.

**Comment by Delphinator** [comment]
>raven = {extras = ['flask']} should map to
> ```
>    raven = '*'
>    flask='*'
> ```

shouldn't it map to
```
raven = "*"
Flask = ">=0.8"
blinker = ">=1.1"
```

(according to https://github.com/getsentry/raven-python/blob/master/setup.py#L40 and https://github.com/getsentry/raven-python/blob/master/setup.py#L130)

> but I know it won’t matter of the value is * because we won’t upgrade it anyway.

That's true. Probably best to just ignore extras, as the additional dependencies they pull in have no effect for our purposes here.

**Comment by Dmitry9** [comment]
Thank you @Delphinator your comment above is a very valuable help.
