### ISSUE TITLE
renovate autoclosed PRs

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3481]
**What Renovate type are you using?**
Renovate GitHub App?

**Describe the bug**
Renovate closed most of open PRs in `dmx-io` organization. In the logs I see, it's because the current time is after the scheduled time. E.g. this PR https://github.com/dmx-io/dmx-scheduling/pull/135 was autoclosed.

**Did you see anything helpful in debug logs?**
```
DEBUG: Does not match schedule because 69614 is later than 64800(dependencies=["mongoose"], branch="renovate/all")
DEBUG: Package not scheduled(dependencies=["mongoose"], branch="renovate/all")
INFO: Skipping branch creation as not within schedule(dependencies=["mongoose"], branch="renovate/all")
DEBUG: branchPrefix: renovate/
DEBUG: Found 0 Renovate PRs
{
  "renovatePrs": []
}
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/all"
  ],
  "renovateBranches": [
    "renovate/mongoose-5.x"
  ]
}
DEBUG: remainingBranches=renovate/mongoose-5.x
DEBUG: findPr(renovate/mongoose-5.x, null, open)
DEBUG: Found PR #135
DEBUG: updatePr(135, [renovate] Update dependency mongoose to ^5.4.21 - autoclosed, body)
DEBUG: PR updated
{
  "pr": 135
}
INFO: Deleting orphan branch(branch="renovate/mongoose-5.x")
INFO: PR autoclosed
{
  "prNo": 135,
  "prTitle": "[renovate] Update dependency mongoose to ^5.4.21"
}
DEBUG: ensureIssueClosing()
```

**Expected behavior**
I expect the schedule to be checked only when opening PRs but if a PR stays unmerged, it shouldn't be autoclosed. It's extraordinary strange because a few hours ago I set the schedule to be `before 6pm on the 3rd day of the month` so during the scheduled time the PR should be updated but not closed.

**Additional context**
My current `renovate.json`:
```
{
  "automerge": false,
  "commitMessagePrefix": "[renovate] ",
  "labels": [
    "renovate"
  ],
  "npmToken": "<redacted>",
  "rangeStrategy": "bump",
  "schedule": "before 6pm on the 3rd day of the month",
  "packageRules": [
    {
      "allowedVersions": "1.13.0",
      "packageNames": [
        "yarn"
      ]
    }
  ],
  "groupName": "all"
}
```

**Comment by rarkins** [comment]
The "not sheduled" message was for branch renovate/all, not renovate/mongoose-5.x. Based on your config, I'd expect the only branch to be renovate/all so if a mongoose branch existed then I'd expect it to be autoclosed. The question is more about why/when was it created in the first place? How long ago did you add the groupName=all setting? If you added it after the mongoose branch was created then this behaviour is correct and expected.

**Comment by piotr-s-brainhub** [comment]
@rarkins 

Thanks. I changed the groups to obtain updates in one PR. However I expect creating a new PR within about one hour after closing the old one but some PRs were closed above 90 minutes ago and still no new PR was created.

**Comment by rarkins** [comment]
New PRs will be created according to schedule, so this behaviour is expected and correct. i.e. old PRs were closed because with the new config they were invalid, while new PRs weren't created because your config limits what schedule they can be created in.

If you want to override your configured schedule on any PR, you can enable the master issue option and tick the checkbox there once the issue is created. It should be also be handy for you to view pending PRs each month seeing as you set it to monthly.
