### ISSUE TITLE
renovate job is run too rarely

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3483]
**What Renovate type are you using?**
Renovate GitHub App?

**Describe the bug**
For all the repos in `dmx-io` organization, the last renovate job was run 5 or 6 hours ago (except of one where it was 4 hours ago).

**Expected behavior**
I expect renovate jobs to be run once per hour, preferably once per hour in each repo but if it's an overload, once per hour there should be run renovate jobs in at least several `dmx-io` repos.

**Screenshots**
<img width="1125" alt="Screenshot 2019-04-04 at 02 48 58" src="https://user-images.githubusercontent.com/20856232/55522306-a840c680-5684-11e9-8d7e-e7f4b44873d7.png">

**Comment by rarkins** [comment]
Sorry, there was a problem with priority scheduling that is now fixed. You should see it regularly now:

![image](https://user-images.githubusercontent.com/6311784/55564909-8f2a2b00-5701-11e9-800f-160fd65e5ab3.png)

**Comment by piotr-s-brainhub** [comment]
thanks

I see in each repo there were hourly jobs for the last 21 hours.
