### ISSUE TITLE
Support json5 in renovate.json

### ISSUE THREAD

**Issue by tonyxiao** [renovatebot/renovate#3484]
**What would you like Renovate to be able to do?**
Support json5 and i.e. comments

What our current renovate.json looks like

```
{
  "extends": ["config:base", ":preserveSemverRanges", "group:all"]
}
```

What we want it to look like

```
{
  // Re-evaluate group:all once up and running with renovate
  // https://github.com/renovatebot/config-help/issues/201
  "extends": ["config:base", ":preserveSemverRanges", "group:all"]
}
```

Migrated from https://github.com/renovatebot/config-help/issues/201

**Comment by rarkins** [comment]
Let's support `renovate.json5` as an additional filename. If found then we parse with `json5.parse()` instead of `json.parse()`.

**Comment by tonyxiao** [comment]
yay!!
