### ISSUE TITLE
Add sourceUrl/homepage lookup from crates API for cargo datasource

### ISSUE THREAD

**Issue by nchashch** [renovatebot/renovate#3486]
**What would you like Renovate to be able to do?**
Add sourceUrl/homepage lookup from crates API with 24 hour caching.
Note that crates.io has a crawler policy forbidding more than 1 request per second,
so the solution should respect this restriction.
**Additional context**
This is related to #3442.
See [this comment](https://github.com/renovatebot/renovate/pull/3474#issuecomment-478915448).

**Comment by rarkins** [comment]
The rate limiting solution for this could be implemented in a generic way, inside `lib/util/got` libraries. i.e. we could implement a generic "requests per second" host option for which crates.io will be configured as 1.

There are probably some elegant ways to implement this in JS using promises and some type of ordered list. We could potentially simplify things and be even more conservative and set a 1s timer *after receiving each result*, ensuring we're always 1+ seconds between requests. Then we basically have an ordered list of requests and after the first one is fulfilled we sleep 1s and then process the next one.

**Comment by rarkins** [comment]
Related: #3670

**Comment by rarkins** [comment]
Blocked by #11024

**Comment by rarkins** [comment]
The crates.io API policy still restricts bots to 1 request per second, and it's the only way to find the source URL of a crate. We use a distributed set of workers for the Renovate app, so the best we could possibly achieve is 1 request per second per VM.

How crates.io could solve this:
- A robust registry API with CDN backing and no rate limiting, e.g. like npm
- Publish source URL to the repository. Today it contains information about releases, but not metadata about the package. e.g. https://raw.githubusercontent.com/rust-lang/crates.io-index/master/ca/de/cadence

How we could solve this:
- Implement rate limiting per second: #6359 (currently we just have concurrent request rate limiting per host, which could mean more than one per second if the API responds quickly)
- Implement `getPackageMeta()` in #11024 so that we can separate package metadata lookups and caching from package release lookups/caching. Package metadata can be cached for e.g. 24 hours to reduce the average requests per day to crates.io to much less than 1 per second

Cc @Turbo87 who also was hoping to fix this

**Comment by lfrancke** [comment]
Just so I understand correctly: Renovate parses Cargo.toml and gets a bunch of names, it then needs to translate those names into source repositorie Urls because it checks those for Github (e.g.) releases and CHANGELOG files?

And the issue here is that the only way to retrieve those source URLs from crates.io is via that API call which is rate limited?

**Comment by rarkins** [comment]
Yes, that's how I understand it today.

**Comment by lfrancke** [comment]
Thank you @rarkins!

@Turbo87 May I ask if you have any concrete plans to work on any of this?
I'd be happy to see if we can help move this forward but you being on the crates.io team seem in a much better position than us to affect change there if needed.

I'm a novice at both Renovate and the crates.io implementation.

**Comment by Turbo87** [comment]
@lfrancke I don't have any immediate plans to work on this myself, due to time constraints, but I'm happy to answer questions :)

**Comment by rarkins** [comment]
Is the crates API the only way to map package name to source URL?

**Comment by Turbo87** [comment]
> Is the crates API the only way to map package name to source URL?

no, not necessarily.

data access options are described at https://crates.io/data-access. we currently have three options:

- the crates index (does not contain the source URL)
- the daily database dump (contains the source URLs, but needs to be imported into a database)
- the crates.io API (contains the source URLs, but has a somewhat aggressive rate limit)

the API would be the easiest solution, but if you can think of a solution that uses the database dump instead then that could also work.

I'd personally prefer if we could drop some of the rate limits on crates.io and use aggressive caching instead, but for several reasons that sounds easier than it is 😅

**Comment by carols10cents** [comment]
If you know the crate name and version number, you can construct the source URL:

```
https://static.crates.io/crates/[crate name]/[crate name]-[version number].crate
```

For example, the source for the rand crate version 0.8.4 is available from:

```
https://static.crates.io/crates/rand/rand-0.8.4.crate
```

We have no plans to change this URL format.

These URLs go directly to CloudFront and downloading through these URLs bypasses the crates.io application and rate limiting entirely.

Is this what you need?

**Comment by Turbo87** [comment]
@carols10cents I believe what is needed is the path to the source code repository to figure out if there is a changelog etc.

I guess that would be a fourth option though if you're extracting the crate file (gzipped tarball) and parsing the Cargo.toml file.

Seems quite excessive for large crates though.

**Comment by carols10cents** [comment]
Ah, I misunderstood what "source URL" meant in this context; I thought it meant "source code of the crate".

**Comment by lfrancke** [comment]
Thanks for jumping in @carols10cents 

I assume that we'd help more than the renovate project if we found a good solution here.
We could change the package file format to include the source URL, I'm not sure how open you are to that?

Or (@Turbo87 suggested this offline to me) a new endpoint that contains only the information needed by these kinds of bots (renovate, dependabot, ...)

**Comment by carols10cents** [comment]
It looks like [dependabot uses the crates.io API](https://github.com/dependabot/dependabot-core/blob/2f0db3e851ba2cc43d0b6dcd70da5e69d5b63eb6/cargo/lib/dependabot/cargo/metadata_finder.rb#L54), why is renovate having the problem of hitting the API more than the rate limit and dependabot isn't?

**Comment by lfrancke** [comment]
I'm speculating (I'm not involved with renovate or dependabot) so take this with a grain of salt:

@rarkins mentioned above that renovate uses a bunch of VMs to do the crawling that don't seem to communicate with each other which makes it hard to implement "global" rate limiting. They could implement rate limiting per VM but that wouldn't guarantee to stay under your limits.

I guess the dependabot folks have smarter/global rate limit options.

But as I said: Total guess from what I read here.

**Comment by lfrancke** [comment]
FYI: I've started a discussion over at crates.io: https://github.com/rust-lang/crates.io/discussions/4503

**Comment by lfrancke** [comment]
The crates.io team discussed our proposal and they agreed to look at a solution where the existing metadata endpoint would be changed to only return the most basic information, bringing down the number of DB requests from 8 or so to 1 (hopefully) for which the rate limit could then be raised (or lifted). We'll look into implementing this now.

**Comment by lfrancke** [comment]
The crates.io change has now been merged and should be available soon.

Could anyone help in making the relevant renovate changes or at least point us in the right direction?
The codebase is not only unfamiliar to us it's also not a language we use :)

**Comment by rarkins** [comment]
Next step: https://github.com/renovatebot/renovate/issues/11024 (crates datasource could be the first user of this)

**Comment by lfrancke** [comment]
There is now a PR for this (that does not build on #11024): https://github.com/renovatebot/renovate/pull/15214

Thank you @Turbo87
