### ISSUE TITLE
Bazel support breaks lint check

### ISSUE THREAD

**Issue by alexeagle** [renovatebot/renovate#3487]
Renovate sent this PR:
https://github.com/bazelbuild/rules_nodejs/pull/661/files
it removes a blank line and therefore the PR failed our lint check.

Seems like renovate should be making the minimal syntactic edit to avoid this.

**Comment by rarkins** [comment]
This is new functionality just activated today. You may recall that previously Renovate only processed `WORKSPACE` files. Seems there's an errant newline being replaced by mistake.

@Dmitry9 is this something you can fix?

**Comment by rarkins** [comment]
I think this should be fixed now - will roll out to the app soon
