### ISSUE TITLE
Cargo platform-specific dependencies errored/ignored

### ISSUE THREAD

**Issue by bearcage** [renovatebot/renovate#3504]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
The cargo manager fails to parse [platform-specific dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies).

**Did you see anything helpful in debug logs?**
[Here](https://gist.github.com/bearcage/7975d1dd9170d91f80c783ac7358e9ba)'s a log with level trace from the current master. Case-sensitive Ctrl-F for `ERR` in the [raw log](https://gist.githubusercontent.com/bearcage/7975d1dd9170d91f80c783ac7358e9ba/raw/d579bba51f18eeecf964d30dfe25beba7b21391f/renovate.log) since github truncates the view, and this is the only error logged. 

You're after this: `ERROR: Error updating branch: Cannot read property 'input' of null`

It's failing with a null reference at [here](https://github.com/renovatebot/renovate/blob/master/lib/manager/cargo/extract.js#L135), passed in from [here](https://github.com/renovatebot/renovate/blob/master/lib/manager/cargo/update.js#L22).

I'm not certain what the original intent with the regex match `dependencies[.]` was, but I'm guessing it's meant to handle dependencies that look like

```
[dependencies.foo]
version = "1.0.0"
```

but it's winding up getting called for this manifest (the actual section of manifest this is failing on):

```
# --- Web dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.37"
js-sys = "0.3.14"
js_relative_import = { path = "../../common/js_relative_import" }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.14"
features = [
    "AudioBuffer",
    "AudioBufferSourceNode",
    "AudioContext",
    "AudioDestinationNode",
    "AudioNode",
]
```

While I was in here I noticed that the platform-specific dependency forms used in the upper block don't appear to be getting renovate updates, and the one in the lower block causes renovate to ERROR out.

**To Reproduce**

1.  Create a new project (`cargo new whatever`)
2. Add a platform-specific, but out of date, dependency
3. Run renovate against it, with cargo enabled.

**Expected behavior**
Updates should get suggested for platform-specific dependencies.

**Screenshots**
NA

**Additional context**
cc @pyrrho

**Comment by rarkins** [comment]
@nchashch I think we should consider switching to a regular TOML parser now, as there are too many edge cases to try to parse manually

**Comment by bearcage** [comment]
Well that was super quick! Let me know if there's anything else y'all need, or something I can do to help :-)
