### ISSUE TITLE
Renovate not running, can't update plan 

### ISSUE THREAD

**Issue by heldinz** [renovatebot/renovate#3506]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Renovate is no longer running. When we try to configure our plan via the Marketplace (Organization Starter) it offers us to "Try free for 14 days" but when we try to "Complete order and begin installation" it tells us that Renovate has already been installed. It then directs us back to our organizations's Settings → Installations → Renovate page where we can see the three repositories we selected Renovate to run on, but this is still not happening. We seem to be stuck in a configuration loop.

**Did you see anything helpful in debug logs?**
The result of each job is "no-plan" for all three private repositories.

**To Reproduce**
N/A

**Expected behavior**
I expect Renovate to run on our three selected private repositories. 

**Screenshots**
N/A

**Additional context**
We initially installed Renovate outside the GitHub marketplace.

**Comment by rarkins** [comment]
@heldinz can you email some screenshots of each step and what you see to support@renovatebot.com? Please include your account name too if it's not obvious from the screenshots. Start from https://github.com/marketplace/renovate/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNjA1#pricing-and-setup
