### ISSUE TITLE
Renovate removes blank line in Bazel WORKSPACE file resulting in lint failures

### ISSUE THREAD

**Issue by smukherj1** [renovatebot/renovate#3510]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
See https://github.com/bazelbuild/rules_k8s/pull/304

Specifically, renovate removed the blank line [here](https://github.com/bazelbuild/rules_k8s/pull/304/files#diff-09498dbadf45966909850dc8a47ebb13L179) which is breaking our Starlark linter we run as part of our presubmit CI.

**Did you see anything helpful in debug logs?**
I don't have access to the renovate logs.
**To Reproduce**
Download https://github.com/bazelbuild/rules_k8s at commit 8b2d62aef3f495cc7d8c14184b8ccc954dd915a8 and run renovate for the dependency updated by https://github.com/bazelbuild/rules_k8s/commit/e0a21c91b3903089d1633e962a3dd2caf5303df1

**Expected behavior**
Only change the fields of the http_archive rule. Don't remove the blank line after the http_archive rule which breaks the linter.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rarkins** [comment]
@smukherj1 can you tick the rebase/retry checkbox in the PR and see if the problem is cleared? This problem should already have been fixed.

**Comment by rarkins** [comment]
Looks like it’s resolved now
