### ISSUE TITLE
Dashboard timing out when fetching logs

### ISSUE THREAD

**Issue by porridge** [renovatebot/renovate#3513]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

https://renovatebot.com/dashboard#github/mesosphere/dcos-commons never shows logs, API times out.

**Did you see anything helpful in debug logs?**

I would sure like to see them :-)

**To Reproduce**

Going to https://renovatebot.com/dashboard#github/mesosphere/dcos-commons keeps showing the three-dot spinner in the main pane. Looking in network console of firefox shows a `504` being returned to the GET for https://v1.renovateapi.com/github/repos/mesosphere/dcos-commons/jobs with the following message:

```

504 ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
If you received this error while trying to use an app or access a website, please contact the provider or website owner for assistance.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by following steps in the CloudFront documentation (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-504-gateway-timeout.html).

Generated by cloudfront (CloudFront)
Request ID: FQqdOp6I45VaUVhUR6UlO8_033iYU_33mnpy_pCzCaK1B8zEdGnCXA==
```

**Expected behavior**

Logs shown eventually via retries, or better - not timing out.

**Screenshots**
![Zrzut ekranu z 2019-04-09 10-48-55](https://user-images.githubusercontent.com/489420/55786726-1f2af480-5ab5-11e9-9987-abfc35382d31.png)

**Comment by rarkins** [comment]
@porridge could you check if the problem is still persisting for you? I tried logging in right now and I can't reproduce the problem when looking at any of my own logs, e.g.:
![image](https://user-images.githubusercontent.com/6311784/55789354-7bdcde00-5aba-11e9-91d8-944955380c83.png)

So I wonder if it's either a transient error or something specific to your account. But the type of error would imply it is not account-specific.

**Comment by porridge** [comment]
Works now! FWIW I did retry a few times before filing the report..

**Comment by rarkins** [comment]
No worries, sorry for the trouble. Could have been a CDN glitch
