### ISSUE TITLE
Throwing preset error

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#3518]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
After release 15.10.0, I am unable to run renovate CLI. It works with the previous release, 15.9.0. I think #3507 is the cause.

**Did you see anything helpful in debug logs?**
```
$ npx renovate@15.10.0
 INFO: Throwing preset error
FATAL: Fatal error: config-validation
       "err": {
         "message": "config-validation",
         "stack": "Error: config-validation\n    at resolveConfigPresets (/home/jamie/.npm/_npx/12850/lib/node_modules/renovate/lib/config/presets.js:50:25)\n    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)\n    at findNodeScript.then.existing (/usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)"
       }
```

**Comment by rarkins** [comment]
My first attempt to reproduce resulted in a regular run. How do you configure Renovate, e.g. `config.js` or environment? Any special settings apart from platform, endpoint and token?

**Comment by rarkins** [comment]
```
$ npx renovate@15.10.0
$ export RENOVATE_TOKEN=$GITHUB_TOKEN
$ npx renovate@15.10.0 renovate-tests/test1
 INFO: Renovating repository (repository=renovate-tests/test1)
 INFO: Authenticated as user: renovate-tests (repository=renovate-tests/test1)
 INFO: Using renovate version: 15.10.0 (repository=renovate-tests/test1)
 INFO: Repository config (repository=renovate-tests/test1)
       "configFile": "renovate.json",
       "config": {"extends": ["config:base"]}
 INFO: Processing 0 branches:  (repository=renovate-tests/test1)
 INFO: Request stats (repository=renovate-tests/test1)
       "rateLimit": 5000,
       "requestCount": 9,
       "rateLimitRemaining": 4963
 INFO: Finished repository (repository=renovate-tests/test1)
 INFO: Renovate finished
```

**Comment by rarkins** [comment]
If you run in debug mode you should see some logs about directories. e.g. 

```
DEBUG: Using baseDir: /var/folders/p_/rdmc6q4s7r1bcwsxxy0d3x6w0000gn/T/renovate
DEBUG: Using cacheDir: /var/folders/p_/rdmc6q4s7r1bcwsxxy0d3x6w0000gn/T/renovate/cache
DEBUG: Initializing Renovate internal cache into /var/folders/p_/rdmc6q4s7r1bcwsxxy0d3x6w0000gn/T/renovate/cache/renovate/renovate-cache-v1
 INFO: Renovating repository (repository=renovate-tests/test1)
DEBUG: Using localDir: /var/folders/p_/rdmc6q4s7r1bcwsxxy0d3x6w0000gn/T/renovate/repos/github/renovate-tests/test1 (repository=renovate-tests/test1)
```

It would seem like one of those directories has a problem in your case, but I can't guess why yet.

**Comment by JamieMagee** [comment]
Yeah, I'm using a `config.js`. I'll try and get a minimum reproducible `config.js`

**Comment by JamieMagee** [comment]
Here's my minimum reproducible `config.js`
```js
module.exports = {
  extends: ['config:base'],
  token: '...'
};
```

I can't get it to output debug logs for some reason. I've tried `logLegel: 'debug'` in `config.js`, as well as running `npx renovate@15.10.0 --log-level debug`, but neither work. I just get the same error.

```
 INFO: Throwing preset error
FATAL: Fatal error: config-validation
       "err": {
         "message": "config-validation",
         "stack": "Error: config-validation\n    at resolveConfigPresets (/home/jamie/.npm/_npx/23547/lib/node_modules/renovate/lib/config/presets.js:50:25)\n    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)\n    at findNodeScript.then.existing (/usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)"
       }
```

What OS are you running on? I'm on Arch Linux

```sh
$ uname -a
Linux jamagee-laptop 5.0.6-arch1-1-ARCH #1 SMP PREEMPT Wed Apr 3 09:35:20 UTC 2019 x86_64 GNU/Linux
```

**Comment by rarkins** [comment]
@JamieMagee you can try `LOG_LEVEL=debug npx renovate@15.10.0`

Having presets in the *bot* config.js wasn't intended to be supported, although I did my best to get it to work. I think in this case it's created a race condition where the cache has not been initialized before we attempt to resolve the bot's config.

What is recommended for bot admins is:
- Set up your own preset, e.g. in an npm package or host it on github or gitlab. This can just be `extends: ['config:base']` for example.
- Configure your `onboardingConfig` to be `{ extends: ['your/preset'] }`

This way all repositories you add will have your custom preset as their base in `renovate.json`, so any time in the future you wish to change behaviour for all repos you can adjust that preset.

**Comment by JamieMagee** [comment]
Ah, I see that now. The first step of `presets.js` is to grab the presets, and merge them into the config. Now that the cache directory can be manually defined, it's not initialised when the config is being parsed.

My use case doesn't have individual `renovate.json` in each repository, as we have a large number of repositories. This makes it easier to keep renovate config consistent across all repos, without having to manually update many repos. Instead I have all the config in `config.js`.

Would it be possible to initialise the cache twice [here](https://github.com/renovatebot/renovate/blob/b5c0897a737f056c4e783588a35b300881247a53/lib/workers/global/index.js#L21-L25), to replicate the old behaviour? Once, before local config is parsed, the cache can be initialised into `os.tmpdir()` like before. For most users this wouldn't even create a directory, and it will allow my use case to continue to work.

**Comment by rarkins** [comment]
I *think* that seems OK
