### ISSUE TITLE
GitHub: refactor issues retrieval to use GraphQL

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3525]
Part of #2409 but probably the most urgent

In the v3 (REST) API, when you query issues then you also get Pull Requests (every Pull Request is an issue..). So for heavy Renovate users, it means we need to retrieve every Pull Request in order to get just the few Issues that the bot has created.

With GraphQL, we can explicitly just get issues. Example:

```graphql
{
  repository(owner: "renovatebot", name: "renovate") {
    issues(states: [CLOSED], first: 100, orderBy: {field: UPDATED_AT, direction: DESC}, filterBy: {createdBy: "renovate[bot]"}) {
      nodes {
        number
        title
        body
      }
    }
  }
}
```

Rewrite getIssueList() to use GraphQL instead. Note that two queries will probably be required: OPEN and CLOSED. Logic can be mostly copied from existing `getOpenPrs` function which also uses GraphQL.

**Comment by psyb0t** [comment]
doesn't need two requests https://github.com/renovatebot/renovate/pull/3808/files#diff-42751e8fceb1062d8a0a4456e13bd2aeR646
