### ISSUE TITLE
Azure-got-wrapper test snapshot mismatch (not present entries: _allowRetries,_maxRetries)

### ISSUE THREAD

**Issue by Dmitry9** [renovatebot/renovate#3531]
FAIL  test/platform/azure/azure-got-wrapper.spec.js
  ● platform/azure/azure-got-wrapper › gitApi › should set token and endpoint

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "platform/azure/azure-got-wrapper gitApi should set token and endpoint 1".
    - Snapshot    + Received
    @@ -7,18 +7,16 @@          "ignoreSslError": false,
        },        "rest": RestClient {
          "client": HttpClient {
            "_allowRedirects": true,
    -       "_allowRetries": false,
            "_certConfig": undefined,
            "_disposed": false,
            "_httpProxy": undefined,
            "_ignoreSslError": false,
            "_keepAlive": false,
            "_maxRedirects": 50,
    -       "_maxRetries": 1,
            "_socketTimeout": undefined,
            "handlers": Array [
              PersonalAccessTokenCredentialHandler {
                "token": "myToken",
              },
    @@ -35,18 +33,16 @@
          "basePath": "myEndpoint/",
          "baseUrl": "myEndpoint/",
          "restClient": RestClient {
            "client": HttpClient {
              "_allowRedirects": true,
    -         "_allowRetries": false,
              "_certConfig": undefined,
              "_disposed": false,
              "_httpProxy": undefined,
              "_ignoreSslError": false,
              "_keepAlive": false,
              "_maxRedirects": 50,
    -         "_maxRetries": 1,
              "_socketTimeout": undefined,
              "handlers": Array [
                PersonalAccessTokenCredentialHandler {
                  "token": "myToken",
                },

      26 | 
      27 |       // We will track if the lib azure-devops-node-api change
    > 28 |       expect(res).toMatchSnapshot();
         |                   ^
      29 |     });
      30 |   });
      31 | });

      at Object.toMatchSnapshot (test/platform/azure/azure-got-wrapper.spec.js:28:19)

 › 1 snapshot failed.

```shell
$ yarn jest
```
**Expected behavior**
All tests passed.

**Additional context**
node v10.13.0
yarn 1.13.0
OS Linux Fedora 28 (Twenty Eight)

**Comment by rarkins** [comment]
Make sure you run “yarn” after pulling. The tests should then pass

**Comment by Dmitry9** [comment]
@rarkins you are correct. After running
```shell
$ yarn
```
tests passed.
