### ISSUE TITLE
Support for gradle inside sub-directories

### ISSUE THREAD

**Issue by jansauer** [renovatebot/renovate#3537]
At the moment the gradle manager requires a gradle configuration file in the project root directory. 
https://github.com/renovatebot/renovate/blob/bd17e021e55236eb60d130ca5253aa9daa8415b4/lib/manager/gradle/index.js#L14

In our setup we have projects with ..
```
README.md
/angular -> npm build
/server -> gradle build
...
```

In this case the gradle manager get's skipped and no gradle dependencies get updated.

**Comment by rarkins** [comment]
@corecanarias do you recall how much work/complexity there would be if we support non-root gradle projects?

**Comment by ikesyo** [comment]
I assume this is also important for apps using React Native.
