### ISSUE TITLE
Assignee per file regex

### ISSUE THREAD

**Issue by Fandekasp** [renovatebot/renovate#3543]
Similarly to CODEOWNERS github rules for reviewers, I would like to assign members depending on some rule (member A will be assigned to renovate PRs for the package.json file, member B to requirements*txt, and member C to Dockerfile changes).

The following syntax could be a solution:
```json
{
  "assignees": [
    ["package.json", "memberA"],
    ["requirements*txt", "memberB"]
  ]
}
```

Thanks for considering this feature.

**Comment by rarkins** [comment]
I think a package rule that uses paths and assignees fields should already work for this.

Please post to the renovatebot/config-help repository if you need help configuring it. If we can’t work out a solution via config then we can reopen this issue as a feature request.
