### ISSUE TITLE
Github App not creating PRs after configuration branch is merged

### ISSUE THREAD

**Issue by dpikt** [renovatebot/renovate#3545]
I added Renovate to a private repository and merged the configuration branch, after changing the config file a bit. In the body of the PR, it said:

`With your current configuration, Renovate will create 10 Pull Requests.`

But I merged it a few days ago and no new pull requests have appeared.
The only change I made to the branch was a version bump in my `package.json` and edits to the config resulting in the following:

```
{
  "extends": [
    "config:base"
  ],
  "bumpVersion": "patch",
  "minor": {
    "enabled": false
  },
  "patch": {
    "enabled": false
  },
  "pin": {
    "enabled": false
  },
  "prHourlyLimit": 0
}
```

Any ideas on how to troubleshoot this? Thanks!

**Comment by rarkins** [comment]
Can you email the repo name to support@renovatebot.com so I can look it up? Or mention it here if it’s not a secret

**Comment by dpikt** [comment]
Sure thing, it's `LaunchPadLab/client-template`. Thanks for the quick response!

**Comment by rarkins** [comment]
This is an interesting edge case. First of all, if you go to https://renovatebot.com/dashboard you can see that Renovate has been running regularly. You can see it expects to create 11 branches but then they all report something like `Branch renovate/bourbon-5.x is blocked by a Pin PR`.

Renovate holds back upgrades for any dependency where there is also a pin PR pending. But in your case you've suppressed the pin PR so it's an unfortunate standoff. If you add the preset `:preserveSemverRanges` then it should stop any pin PRs from being created in the first place, hence nothing to suppress, and then nothing to block upgrades.

**Comment by dpikt** [comment]
@rarkins I'll give that a shot. Thank you!
