### ISSUE TITLE
Change list missing from Releases page

### ISSUE THREAD

**Issue by Turbo87** [renovatebot/renovate#3556]
**Describe the bug**
https://github.com/renovatebot/renovate/releases used to show what changes were included in a release, but the latest releases (e.g. v16.0.4) just have blank descriptions 🤔

**Comment by rarkins** [comment]
Semantic release (which does our releasing and release notes) doesn’t include any “refactor” commits in release notes. So any release that’s refactor-only will have “missing” release notes. If anyone knows how to configure semantic release to include them, I’d welcome a PR.

**Comment by Turbo87** [comment]
I see. I guess the other option would be to configure the release process to only actually do a release if there are non-refactor changes to be released.

**Comment by rarkins** [comment]
I like to release refactors “just in case”. If a refactor accidentally breaks things then it’s far easier to pinpoint by release.

**Comment by rarkins** [comment]
I've decided to disable new versions of Renovate for build and refactor updates, which is one way to make the problem go away.

**Comment by Turbo87** [comment]
awesome, thanks for the quick response :)
