### ISSUE TITLE
Failed to renovate lerna monorepo in  Gitlab Ci

### ISSUE THREAD

**Issue by whtsky** [renovatebot/renovate#3567]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Running renovate cli in Gitlab Ci to renovate a lerna monorepo, result in `Artifact update problem`

```
### :warning: Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this MR as-is.

:recycle: Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you check the rebase/retry checkbox if found above, or
 - you rename this MR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: durian/package-lock.json

```
lerna notice cli v3.13.3
lerna info ci enabled
lerna info Bootstrapping 5 packages
lerna info Installing external dependencies
lerna ERR! npm ci --package-lock-only --no-audit exited 1 in 'durian'
lerna ERR! npm ci --package-lock-only --no-audit stderr:
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's @types/express@4.16.0 does not satisfy @types/express@4.16.1
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/renovate_cache/others/npm/_logs/2019-04-19T10_54_34_343Z-debug.log

lerna ERR! npm ci --package-lock-only --no-audit exited 1 in 'durian'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.

```


```

**To Reproduce**

1.  Create a lerna monorepo 
2.  Run renovate cli in gitlab ci to renovate it

**Additional context**

Adding `--no-ci` when running lerna should solve this ( https://github.com/lerna/lerna/tree/master/commands/bootstrap#--no-ci ).

**Comment by whtsky** [comment]
I'll raise a PR for this once I confirm https://github.com/whtsky/renovate/commit/a540f8c3e798d9fff2c44f1aaea0014f8ae33677 fixed this.

**Comment by rarkins** [comment]
@whtsky do you have an `.npmrc` that is forcing CI from npm? I'm not sure why Renovate would otherwise run with the CI option.

Also, we need to make sure that the solution is compatible with Yarn too, as it's commonly used with lerna too. If Yarn ignores the `--no-ci` flag then it's *probably* OK, but ideally we don't set it at all in the Yarn case.

**Comment by whtsky** [comment]
@rarkins Yes.

> When using the default --npm-client, lerna bootstrap will call npm ci instead of npm install in CI environments. To disable this behavior, pass --no-ci:

https://github.com/lerna/lerna/tree/master/commands/bootstrap#--no-ci


`--no-ci` is passed to `lerna`, not npm.

**Comment by rarkins** [comment]
Oh ok. So it’s the CI environment causing it in particular.
