### ISSUE TITLE
provide changelog for maven packages

### ISSUE THREAD

**Issue by BigMichi1** [renovatebot/renovate#3568]
**What would you like Renovate to be able to do?**
renovate should also be able to provide a changelog in merge requests for updates of maven packages in a java project (possibly it can be reused for every package that is based on pom.xml)

**Describe the solution you'd like**
when an update is detected by renovate the changelog can be retrieved from github if the package is from github. how this should work:
- without inheritance in pom.xml of the updated version
    - take a look at the new pom.xml from the updated version
    - read url tag inside the scm tag under the root tag to find out the location of the repository (https://maven.apache.org/pom.html#SCM)
    - if the tag is present extract the github url and provide the changelog
- with inheritance in pom.xml of the updated version (**should never happen when an artifact is published to mavencentral**)
    - if there is no scm tag in the current pom.xml and a parent is specified the parent must be parsed to find the scm tag
    - this can happen multiple times but it should stop if there is a change in the groupId (some projects using a genaralized parent pom from different project which contains some defaults (plugin configurations) for artifact publishing)

Example `pom.xml`: https://github.com/redisson/redisson/blob/master/pom.xml
Example Tag: `<url>scm:git:git@github.com:redisson/redisson.git</url>`

**Describe alternatives you've considered**
an alternative way of finding the url for the changelog might be calling `mvn help:effective-pom` (http://maven.apache.org/plugins/maven-help-plugin/usage.html#The_help:effective-pom_Goal) which will generate onw "huge" pom xml

**Additional context**

**Comment by rarkins** [comment]
The very latest commit I pushed to master today should actually solve this for the majority of cases. Before, we weren’t massaging the `scm:` URLs but this should be happening now. So any package with a GitHub URL and release notes should be covered.

**Comment by rarkins** [comment]
This commit is in the CLI already and will be pushed to the app hopefully today.

**Comment by BigMichi1** [comment]
with the new version 16.1.1 i got some changelogs for github but not for all.

having these dependencies in my pom.xml
```xml
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.196</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.3.21</version>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>2.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>3.5.3</version>
        </dependency>
```

results in the following 4 merge requests

h2: no changelog -> github project
kotlin-stdlib-jdk8: everthing is fine
webdrivermanager: no changelog -> github project
liquibase: no changelog, no references -> github project but definitions of urls in parent pom

**Comment by rarkins** [comment]
To get changelogs for a Maven dependency requires a few things to all work:

1. The Maven API must include the source URL
2. Renovate must successfully find that source URL
3. The source URL must be github (we don't support others yet)
4. The source URL/repo must include a changelog file format we support, or use GitHub Releases

So for each of those that are missing, we'd need to work out at which step they are failing.

**Comment by rarkins** [comment]
Index: http://central.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/maven-metadata.xml
Latest: http://central.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.30/kotlin-stdlib-jdk8-1.3.30.pom

Content:
```xml
<scm>
<connection>scm:git:https://github.com/JetBrains/kotlin.git</connection>
<developerConnection>scm:git:https://github.com/JetBrains/kotlin.git</developerConnection>
<url>https://github.com/JetBrains/kotlin</url>
</scm>
```

Then using h2:

Latest: http://central.maven.org/maven2/com/h2database/h2/1.4.199/h2-1.4.199.pom

Content:
```xml
<scm>
<connection>scm:git:https://github.com/h2database/h2database</connection>
<url>https://github.com/h2database/h2database</url>
</scm>
```

That repo uses GitHub Releases: https://github.com/h2database/h2database/releases

@BigMichi1 can you confirm that the correct source URL is linked to from the PR body?

**Comment by BigMichi1** [comment]
this is how it looks like in the pull requests, just the table which shows the version upgrade and project links

<table data-sourcepos="3:1-5:146" dir="auto">
<thead>
<tr data-sourcepos="3:1-3:42">
<th data-sourcepos="3:2-3:10">Package</th>
<th data-sourcepos="3:12-3:19">Update</th>
<th data-sourcepos="3:21-3:28">Change</th>
<th data-sourcepos="3:30-3:41">References</th>
</tr>
</thead>
<tbody>
<tr data-sourcepos="5:1-5:146">
<td data-sourcepos="5:2-5:20">com.h2database:h2</td>
<td data-sourcepos="5:22-5:28">patch</td>
<td data-sourcepos="5:30-5:53">
<code>1.4.196</code> -&gt; <code>1.4.199</code>
</td>
<td data-sourcepos="5:55-5:145">
<a href="http://www.h2database.com" rel="nofollow noreferrer noopener" target="_blank">homepage</a>, <a href="https://github.com/h2database/h2database" rel="nofollow noreferrer noopener" target="_blank">source</a>
</td>
</tr>
</tbody>
</table>


<table data-sourcepos="3:1-5:159" dir="auto">
<thead>
<tr data-sourcepos="3:1-3:42">
<th data-sourcepos="3:2-3:10">Package</th>
<th data-sourcepos="3:12-3:19">Update</th>
<th data-sourcepos="3:21-3:28">Change</th>
<th data-sourcepos="3:30-3:41">References</th>
</tr>
</thead>
<tbody>
<tr data-sourcepos="5:1-5:159">
<td data-sourcepos="5:2-5:42">org.jetbrains.kotlin:kotlin-stdlib-jdk8</td>
<td data-sourcepos="5:44-5:50">patch</td>
<td data-sourcepos="5:52-5:73">
<code>1.3.21</code> -&gt; <code>1.3.30</code>
</td>
<td data-sourcepos="5:75-5:158">
<a href="https://kotlinlang.org/" rel="nofollow noreferrer noopener" target="_blank">homepage</a>, <a href="https://github.com/JetBrains/kotlin" rel="nofollow noreferrer noopener" target="_blank">source</a>
</td>
</tr>
</tbody>
</table>

<table data-sourcepos="3:1-5:189" dir="auto">
<thead>
<tr data-sourcepos="3:1-3:42">
<th data-sourcepos="3:2-3:10">Package</th>
<th data-sourcepos="3:12-3:19">Update</th>
<th data-sourcepos="3:21-3:28">Change</th>
<th data-sourcepos="3:30-3:41">References</th>
</tr>
</thead>
<tbody>
<tr data-sourcepos="5:1-5:189">
<td data-sourcepos="5:2-5:40">io.github.bonigarcia:webdrivermanager</td>
<td data-sourcepos="5:42-5:48">minor</td>
<td data-sourcepos="5:50-5:69">
<code>2.1.0</code> -&gt; <code>2.2.5</code>
</td>
<td data-sourcepos="5:71-5:188">
<a href="https://github.com/bonigarcia/webdrivermanager" rel="nofollow noreferrer noopener" target="_blank">homepage</a>, <a href="https://github.com/bonigarcia/webdrivermanager" rel="nofollow noreferrer noopener" target="_blank">source</a>
</td>
</tr>
</tbody>
</table>

<table data-sourcepos="3:1-5:61" dir="auto">
<thead>
<tr data-sourcepos="3:1-3:29">
<th data-sourcepos="3:2-3:10">Package</th>
<th data-sourcepos="3:12-3:19">Update</th>
<th data-sourcepos="3:21-3:28">Change</th>
</tr>
</thead>
<tbody>
<tr data-sourcepos="5:1-5:61">
<td data-sourcepos="5:2-5:31">org.liquibase:liquibase-core</td>
<td data-sourcepos="5:33-5:39">minor</td>
<td data-sourcepos="5:41-5:60">
<code>3.5.3</code> -&gt; <code>3.6.3</code>
</td>
</tr>
</tbody>
</table>

**Comment by rarkins** [comment]
Could you paste in here a minimal pom.xml to reproduce this problem with the 4 packages discussed here? It will help me troubleshoot it sooner if so.

**Comment by BigMichi1** [comment]
uploaded an example project here with the reduced `pom.xml`
https://github.com/BigMichi1/renovate-example

**Comment by rarkins** [comment]
For `io.github.bonigarcia:webdrivermanager`, the problem is probably this non-markdown changelog format: https://github.com/bonigarcia/webdrivermanager/blob/master/changelog

It's also possible that their use of empty GitHub Releases could throw off our parser too.

**Comment by rarkins** [comment]
`org.liquibase:liquibase-core` is not detecting any source repository. We need to check if any is specified in the registry metadata

**Comment by BigMichi1** [comment]
> `org.liquibase:liquibase-core` is not detecting any source repository. We need to check if any is specified in the registry metadata

this is maybe because all metadata information is in http://central.maven.org/maven2/org/liquibase/liquibase-parent/3.6.3/liquibase-parent-3.6.3.pom which is the parent of http://central.maven.org/maven2/org/liquibase/liquibase-core/3.6.3/liquibase-core-3.6.3.pom

**Comment by rarkins** [comment]
@BigMichi1 thanks for that clarification. What logic should Renovate use? e.g. if no scm found in the current package then check if there's a parent scm?

**Comment by BigMichi1** [comment]
yes because this is a common pattern in the maven world that you provide a parent module/pom which contains these information to not suplicate it for every module

**Comment by BigMichi1** [comment]
a fuzzy search shows a lot of pakages which are using this parent thing (https://mvnrepository.com/search?q=-parent)

**Comment by rarkins** [comment]
`org.jetbrains.kotlin:kotlin-stdlib-jdk8` is now showing a changelog correctly.

`org.jetbrains.kotlin:kotlin-maven-plugin` is not showing any source repository but it's parent is showing an scm (same repo as `kotlin-stdlib-jdk8`, strangely - seems they must have defined that scm directly).

`com.h2database:h2` shows the source repo but fails to find the release notes here: https://github.com/h2database/h2database/releases

**Comment by rarkins** [comment]
Looks like if we recursively fetch metadata from a package's parent then that should solve most of them. After that, we just have some "typical" changelog problems, e.g. strangely formatted changelog files, empty releases, etc.

**Comment by BigMichi1** [comment]
yep but these different formats is something that can't be changed, will try to request a parseable format of the changelog in the projects which we are interested in

**Comment by BigMichi1** [comment]
than lets focus here on the recursive parsing and not digging into the changelog format problem

**Comment by rarkins** [comment]
I think in most cases we can't change the format so it's OK if we have to do some work to accommodate new formats. But I agree, the recursive parent SCM fetching should get us the best results

**Comment by ctasada** [comment]
@rarkins What's the status of this ticket? I'm having the same issue. Basically the `scm` configuration is on the parent (or parent-parent) so I cannot see release notes for most of my MR :(

**Comment by rarkins** [comment]
@BigMichi1 @ctasada we have a fix now ready for testing. Could you provide one or more complete `pom.xml` files that we can use to test again? i.e. ones that are missing changelogs today but you think should have them included.
