### ISSUE TITLE
Renovate not running for private repos

### ISSUE THREAD

**Issue by djcsdy** [renovatebot/renovate#3572]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Renovate doesn’t run for any of my private repositories at @softwareventures, even though I’ve signed up for an Organisation – Medium account.

**Did you see anything helpful in debug logs?**
All jobs on private repositories are failing with “no plan”.

**Comment by rarkins** [comment]
Sorry for the inconvenience, I’ll look into it by end of day

**Comment by djcsdy** [comment]
Seems to be working now. I’m not sure if you did something to fix it or if the fiddling about I did this morning took effect effect belatedly and fixed the problem.

Either way, thank you :-).

**Comment by rarkins** [comment]
Hi @djcsdy I was able to add a manual override a little earlier that seems to have taken effect. Now been able to force a marketplace sync and can confirm that your account/plan is valid and registered so there should be no further interruption. Thanks very much for signing up!
