### ISSUE TITLE
Support for NPM package alias

### ISSUE THREAD

**Issue by nathanpower** [renovatebot/renovate#3575]
**What would you like Renovate to be able to do?**
Declare dependencies using new NPM alias syntax

**Describe the solution you'd like**
The [latest NPM CLI](https://github.com/npm/cli/releases/tag/v6.9.0) supports aliases for dependencies in package.json. Would be great if renovate supported this new syntax, example shown in [this tweet from hapijs](https://twitter.com/hapijs/status/1120237590668386304). Maybe this is supported already, haven't been able to find any mention in docs. 

**Describe alternatives you've considered**
Changing all `require` statements across multiple projects (vs. changing only the package.json in those projects)

**Additional context**
Example from tweet linked above:

```JSON
{
   "dependencies": {
      "hapi": "npm:@hapi/hapi@18.x.x"
   }
}
```
This will load @hapi/hapi under hapi

**Comment by rarkins** [comment]
@nathanpower thanks for raising this. We need to adapt our npm extract and update functions for this.
