### ISSUE TITLE
bug(nuget): Failed to look up dependency

### ISSUE THREAD

**Issue by ViceIce** [renovatebot/renovate#3591]
**What Renovate type are you using?**
Renovate GitHub App (, Renovate CLI ?)

**Describe the bug**
Renovate fails to find an update for some nuget packages, eg [MinVer](https://www.nuget.org/packages/MinVer/1.0.0)

**Did you see anything helpful in debug logs?**
```
INFO: Dependency lookup failure: not found in all feeds
{
  "lookupName": "MinVer"
}
INFO: Failed to look up dependency MinVer (MinVer)(packageFile="EPPlus/Directory.Build.props", dependency="MinVer")
```

**To Reproduce**
See https://github.com/VisualOn/EPPlus

**Expected behavior**
Renovate should find an update for MinVer.

**Additional context**
I think it could be a semver 2.0 problem, because the MinVer realease version is `1.0.0+build.203`

**Comment by ViceIce** [comment]
Same prolem for [Microsoft.SourceLink.GitHub](https://www.nuget.org/packages/Microsoft.SourceLink.GitHub/1.0.0-beta2-18618-05), but here he schouln't find an update.

**Comment by rarkins** [comment]
If it says `Failed to look up dependency` then that indicates it happens *before* we start looking at versions.

I assume MinVer can be found in the regular/public nuget registry?

**Comment by rarkins** [comment]
It uses this default feed: https://api.nuget.org/v3/index.json

Query URL becomes https://api-v2v3search-0.nuget.org/query?q=PackageId:MinVer

Result is empty:

```json
{
    "@context": {
        "@vocab": "http://schema.nuget.org/schema#",
        "@base": "https://api.nuget.org/v3/registration3/"
    },
    "totalHits": 0,
    "lastReopen": "2019-04-25T07:00:15.4097934Z",
    "index": "v3-lucene2-v2v3-20171018",
    "data": []
}
```

Picking one of the other packages in that repo produces a result, e.g. https://api-v2v3search-0.nuget.org/query?q=PackageId:System.Data.SqlClient works

So what's special about MinVer or what's wrong with the query url we have?

Paging @fgreinacher and @Elufimov in case they have any idea

**Comment by rarkins** [comment]
Even a broader search like https://api-v2v3search-0.nuget.org/query?q=title:MinVer fails to return results

From https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-for-packages it says, "An unlisted package should never appear in search results." but I presume MinVer is "listed"

**Comment by rarkins** [comment]
There doesn't seem to be any problem with its name/case, e.g. `dotnet add package MinVer --version 1.0.0` is the recommended install command

**Comment by rarkins** [comment]
Found it.

https://api-v2v3search-0.nuget.org/query?q=PackageId:MinVer&semVerLevel=2.0.0

![image](https://user-images.githubusercontent.com/6311784/56716730-521eea80-673b-11e9-9f0f-105076dd94f7.png)

**Comment by rarkins** [comment]
I also added the `prerelease=true` query param while I was at it, so that nuget returns both stable and unstable results and Renovate can then do the filtering later.
