### ISSUE TITLE
Support updating non semver tags for Github repos in Bazel workspaces

### ISSUE THREAD

**Issue by smukherj1** [renovatebot/renovate#3595]
**What would you like Renovate to be able to do?**
For the external dependency declared [here](https://github.com/bazelbuild/rules_nodejs/blob/9c52f4e11ba66b5bce5e91a79777d8c7274d7c07/package.bzl#L81), renovate seems to ignore new Github releases made to the bazel-toolchains repo [here](https://github.com/bazelbuild/bazel-toolchains/releases). I feel this might be because the bazel-toolchains repo is tagged with short commit shas instead of traditional version strings like x.1, x.2, etc. Does this seem accurate?

**Describe the solution you'd like**
I would be interested in exploring the possibility of configuring renovate to always update a http_archive Github dependency to the latest tagged release. This way, if we have our own custom versioning system, renovate should not try to infer a semver from the release tag and simply pick the latest one.

**Describe alternatives you've considered**
One possibility is for rules_nodejs to switch to using regular commits. But the desire here is to stick to tagged releases which are less frequent and more stable instead of staying at HEAD.

**Additional context**
N/A

**Comment by rarkins** [comment]
To clarify, the idea is *not* to be confused with regular "digest updating", where you always take the latest commit. Instead, it is to keep the value updated to the latest "release" even though those releases are confusingly named after their commits.

The challenge here is this seems like a unique/one-off solution and we want to avoid making Renovate's core logic too complicated for such a narrow use case. Therefore we need to see if this can be done simply without adding a technical burden.

BTW I'm not sure of exactly where/why this currently causes Renovate to skip it. It may be as you say that we check if it's a valid semver and if not then skip.
