### ISSUE TITLE
CLI exit code is 0 (indicating success) even if an error occurs

### ISSUE THREAD

**Issue by Livven** [renovatebot/renovate#3605]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
The exit code from the `renovate` command is `0` even if an error occurs. Same as in #1338. 

**To Reproduce**

1.  `yarn add renovate`
2. `.\node_modules\.bin\renovate`

Output from last command:
```
FATAL: Fatal error: No authentication found for platform https://api.github.com/ (github)
       "err": {
         "message": "No authentication found for platform https://api.github.com/ (github)",
         "stack": "Error: No authentication found for platform https://api.github.com/ (github)\n    at Object.parseConfigs [...]"
       }
```

**Expected behavior**
The exit code from the last command should be non-zero, but is `0` instead.

**Additional context**
There is a fix in #1625 but I think it does not work here because the error message is written to stdout instead of stderr.

**Comment by rarkins** [comment]
It might because we only hook into logger.error and not logger.fatal
