### ISSUE TITLE
Support local git/clone run

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3609]
**What would you like Renovate to be able to do?**

Allow Renovate to do a type of "dry run" on a locally cloned repo, particularly to be able to test config changes.

**Describe the solution you'd like**

Run Renovate on a local git clone. It shouldn't matter if it's github/gitlab/bitbucket/azure as the interface will be gitFs.

First step would be to perform a dry run, maybe later even to create the branches too - but PRs/Issues cannot be created or updated.

**Describe alternatives you've considered**

Forking a hosted repository to test against.

**Additional context**

Requested by @Hongarc in https://github.com/renovatebot/config-help/issues/223

**Comment by jnewland** [comment]
I'd like something like this to be able test something slighly different than config changes: I'd like to confirm in a CI job that packages added to a repository in a pull request are properly parsed and managed by renovate. Right now I'm able to parse the logs of a dry run to be able to see when a package can't be resolved, but only after a package or configuration rules that manage it are on a repository's default branch. Allowing a dry-run to be triggered against a branch would allow this case to be detected and resolved before merge using CI guardrails.

**Comment by rarkins** [comment]
I think this should be possible if combined with `dryRun` concepts.

- New global option `local` which defaults to false. e.g. you can run `renovate --local=true`
- It will skip all cloning and initializing and essentially do the same as the new `dryRun=extract` before exiting

In a subsequent feature issue later we can support also `dryRun=lookup although we'll need to think if there's any problems if the platform isn't initialized etc.

**Comment by rarkins** [comment]
I suggest we use `--platform=local`, which implicitly enables `--dry-run=lookup`.

We could support the `cwd` by default, e.g. `renovate --platform=local` means the current directory, but possibly also allow a path, e.g. `renovate --platform=local ../foo`.

**Comment by nielsbasjes** [comment]
I'm not sure what these dryrun settings do. What would be awesome if a command like this would output the changes it would output in a diff or something similar.

**Comment by viceice** [comment]
i think this can be implemented as platform, where issues are not supported. maybe renovate can clone the selected repo via file url and then doing normal work. just return success for PR creation.

PR merge could be push local branch to remote  base branch.
status check should always return success.

**Comment by nielsbasjes** [comment]
Extending what @rarkins sketched yesterday.
The `--platform=local` and the part of working on either the current or a specified directory sound great tome.

I am in doubt about the `--dry-run=lookup` though as this does not seem to produce the changes the tool will propose (couldn't find it when trying). 
I see two useful ways of providing the output from renovate in this `--platform=local` situation:
1) Branches in this local repository (i.e. similar to the normal operating way).
2) Patch/diff files in a separate directory.

I'm not sure what is easiest to your guy to build.
My primary usecase is local development/debugging of the config that I put in the for example the `renovate.json` (especially manual pattern matching with regex managers like [this one](https://docs.renovatebot.com/modules/datasource/gitlab-tags/) ), both of these options would be fine for this.

**Comment by rarkins** [comment]
Draft PR: #22010

**Comment by rarkins** [comment]
I'm going to mark this as Closed by #22010 although it does not contain every idea mentioned within here. Once it's released, please start new Discussions on any further ideas and we'll decide whether to convert them into feature requests
