### ISSUE TITLE
yarn.lock changes in CI when using yarn dedupe

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#3624]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
We have a CI check that ensures yarn.lock doesn't change.
In many cases, it fails on Renovate PRs.
This meant for me that I had to manually fix 90% of the Renovate PRs.

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

**To Reproduce**

1.  Create repository with '...'
2.  Configure '....'

**Expected behavior**
yarn.lock should be stable.

**Screenshots**

**Additional context**
Example PR: https://github.com/sourcegraph/sourcegraph/pull/3736/files, https://github.com/sourcegraph/sourcegraph/pull/3717/files

Diff detected in CI:
```
[2019-05-02T23:22:08Z] diff --git a/yarn.lock b/yarn.lock
--
  | [2019-05-02T23:22:08Z] index 50edf018cd..ef33180a24 100644
  | --- a/yarn.lock
  | +++ b/yarn.lock
  | [2019-05-02T23:22:08Z] @@ -1459,7 +1459,8 @@
  | [2019-05-02T23:22:08Z]    integrity sha512-Te7F1RQJLBH4C8wQ2xz0nPC2vpe13F80V+Yv+c3GySOoh4DcLNN4P5u51Kh4aZPqeS5DJ7CKvHyX2SM/1EBXNg==
  | [2019-05-02T23:22:08Z]
  | [2019-05-02T23:22:08Z]  "@sourcegraph/extension-api-types@link:packages/@sourcegraph/extension-api-types":
  | [2019-05-02T23:22:08Z] -  version "2.0.0"
  | [2019-05-02T23:22:08Z] +  version "0.0.0"
  | [2019-05-02T23:22:08Z] +  uid ""
  | [2019-05-02T23:22:08Z]
  | [2019-05-02T23:22:08Z]  "@sourcegraph/prettierrc@^2.2.0":
  | [2019-05-02T23:22:08Z]    version "2.2.0"
  | [2019-05-02T23:22:08Z] @@ -12852,7 +12853,7 @@ saxes@^3.1.9:
  | [2019-05-02T23:22:08Z]    dependencies:
  | [2019-05-02T23:22:08Z]      xmlchars "^1.3.1"
  | [2019-05-02T23:22:08Z]
  | [2019-05-02T23:22:08Z] -scheduler@^0.13.2, scheduler@^0.13.6:
  | [2019-05-02T23:22:08Z] +scheduler@^0.13.6:
  | [2019-05-02T23:22:08Z]    version "0.13.6"
  | [2019-05-02T23:22:08Z]    resolved "https://registry.npmjs.org/scheduler/-/scheduler-0.13.6.tgz#466a4ec332467b31a91b9bf74e5347072e4cd889"
  | [2019-05-02T23:22:08Z]    integrity sha512-IWnObHt413ucAYKsD9J1QShUKkbKLQQHdxRyw73sw4FN26iWr3DY/H34xGPe4nmL1DwXyWmSWmMrA9TfQbE/XQ==
  | [2019-05-02T23:22:08Z] @@ -13341,7 +13342,8 @@ source-map@^0.6.0, source-map@^0.6.1, source-map@~0.6.0, source-map@~0.6.1:
  | [2019-05-02T23:22:08Z]    integrity sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==
  | [2019-05-02T23:22:08Z]
  | [2019-05-02T23:22:08Z]  "sourcegraph@link:packages/sourcegraph-extension-api":
  | [2019-05-02T23:22:08Z] -  version "23.0.1"
  | [2019-05-02T23:22:08Z] +  version "0.0.0"
  | [2019-05-02T23:22:08Z] +  uid ""
  | [2019-05-02T23:22:08Z]
  | [2019-05-02T23:22:08Z]  space-separated-tokens@^1.0.0:
  | [2019-05-02T23:22:08Z]    version "1.1.2"
  | [2019-05-02T23:22:08Z] 🚨 Error: The command exited with status 1
```

What might be special about our setup:
Our folder structure looks like this: 
- yarn.lock
- package.json
- cmd/
  - management-console/
    - web/
      - yarn.lock
      - package.json

i.e. we have some sort of nested package if you will, and in the PR above a dependency was updated that was in both package.jsons.

We have `yarn-deduplicate` enabled.

**Comment by rarkins** [comment]
It's possible the `yarn-deduplicate` is causing it, although I suspect it's not. The main problem seems to be with the "linked" sourcegraph packages, is that right? e.g. the Renovate PR changes them from a "0.0.0" to an actual version.

![image](https://user-images.githubusercontent.com/6311784/57120361-3c2fac00-6d71-11e9-9be6-d56e10086699.png)

I haven't seen that terminology before ("0.0.0", etc) so need to understand it first, if that's actually the expected result.

**Comment by rarkins** [comment]
If I check out the `renovate/react-monorepo` branch locally and run `yarn` then I also get a diff.

If I do this though:
- clone repo
- manually edit package.json to update react
- run "yarn"

The I also get the same changes:
![image](https://user-images.githubusercontent.com/6311784/57122343-16a89f80-6d7d-11e9-8728-db98a5695af0.png)

i.e. without yarn deduplicate.

Full cmd:

```
/tmp/sourcegraph master
❯ nano package.json

/tmp/sourcegraph master* 11s
❯ rm -rf node_modules

/tmp/sourcegraph master*
❯ yarn
yarn install v1.15.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > graphiql@0.13.0" has unmet peer dependency "prop-types@>=15.5.0".
warning "graphiql > codemirror-graphql@0.7.1" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface@1.3.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-parser@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-config@2.0.1" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-language-service-types@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-language-service-utils@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphiql > codemirror-graphql > graphql-language-service-interface > graphql-config > graphql-import@0.4.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "@sourcegraph/stylelint-config > stylelint-config-prettier@5.0.0" has incorrect peer dependency "stylelint@^9.1.1".
warning "@sourcegraph/stylelint-config > stylelint-scss@3.4.0" has incorrect peer dependency "stylelint@^8.0.0 || ^9.0.0".
warning " > @storybook/addon-console@1.1.0" has unmet peer dependency "prop-types@*".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ gulp generate && yarn --cwd shared -s run tslint:build-rules
[08:24:21] Requiring external module ts-node/register
Using mode development
[08:24:25] Using gulpfile /private/tmp/sourcegraph/gulpfile.ts
[08:24:25] Starting 'generate'...
[08:24:25] Starting 'schema'...
[08:24:25] Starting 'graphQLTypes'...
[08:24:25] Finished 'schema' after 439 ms
[08:24:26] Finished 'graphQLTypes' after 1.03 s
[08:24:26] Finished 'generate' after 1.03 s
✨  Done in 99.33s.

/tmp/sourcegraph master* 1m 40s
❯ git diff

/tmp/sourcegraph master* 19s
❯ yarn --version
1.15.2
```

I had thought the problem might because either (a) yarn-deduplicate, or (b) not running scripts. But it doesn't seem to be the case.

**Comment by rarkins** [comment]
I can't work out what Renovate should do differently in this case, or what's causing the "diffs". I thought maybe it could be caused by updating a dependency in both the main package.json and a subdirectory one, however you said it's 90% of PRs and you don't have anything close to 90% overlap of deps so that rules it out if so. If you can help narrow it down any, that would help. Otherwise I'm at a loss for now as to what specific combination is causing this or how to reproduce it manually.

**Comment by felixfbecker** [comment]
What yarn version is Renovate running? We're running v1.15.2 in CI and locally.

Does Renovate always run `yarn` in both the root and in the subdir? Maybe it's some hoisting of parent ndoe_modules/yarn.lock.

What exact steps does Renovate do to upgrade? `yarn upgrade`? Or edit package.json, then run `yarn`? Can these be reproduced locally to reproduce the state that then causes another diff when runnning `yarn`?

**Comment by rarkins** [comment]
Assuming Renovate detects hashes in your `yarn.lock` (i.e. you're using a recent Yarn), then it will current execute v1.15.2 of Yarn: https://github.com/renovatebot/renovate/blob/c6b4e70324c0ec49c524b42bd23d5f756d73f6d2/package.json#L147

Renovate will run `yarn` in essentially every folder that has a `yarn.lock` and a changed `package.json`. It edits the version in `package.json` first and then runs `yarn`. It's kind of non-deterministic about the order of which directories it runs first though.

What I found strange was:
- By checking out master manually, editing a version manually, and running `yarn`, I saw the 0.0.0 -> 2.0.0 change locally
- By checking out an existing Renovate branch I saw the change from 2.0.0 -> 0.0.0 that you're seeing in CI

I don't think there was anything "wrong" with the simple steps I did, so I wonder what leads it to change away from 0.0.0 in one case and to 0.0.0 in another.

**Comment by felixfbecker** [comment]
@rarkins I think the 2.0.0 -> 0.0.0 might be a red herring. We are using symlinks for that package, so I almost some weirdness.
But what I saw consistently was changes like this (also included in the diff in the issue description):

```

  | [2019-05-02T23:22:08Z] -scheduler@^0.13.2, scheduler@^0.13.6:
  | [2019-05-02T23:22:08Z] +scheduler@^0.13.6:
  | [2019-05-02T23:22:08Z]    version "0.13.6"
  | [2019-05-02T23:22:08Z]    resolved "https://registry.npmjs.org/scheduler/-/scheduler-0.13.6.tgz#466a4ec332467b31a91b9bf74e5347072e4cd889"
  | [2019-05-02T23:22:08Z]    integrity sha512-IWnObHt413ucAYKsD9J1QShUKkbKLQQHdxRyw73sw4FN26iWr3DY/H34xGPe4nmL1DwXyWmSWmMrA9TfQbE/XQ==
  | [2019-05-02T23:22:08Z] @@ -13341,7 +13342,8 @@ source-map@^0.6.0, source-map@^0.6.1, source-map@~0.6.0, source-map@~0.6.1:
  | [2019-05-02T23:22:08Z]    integrity sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==
  | [2019-05-02T23:22:08Z]
```

where some apparently some transitive dependency disappears/gets merged into one.

**Comment by rarkins** [comment]
@felixfbecker I was pretty sure that was due to the deduplication.

Also, sometimes - and maybe this is more of an npm thing and not yarn - the result you get can change based on whether you have node_modules or not. So you can really go around in circles thinking you've reproduced a problem, then not, etc. Clearly something is up here though.

**Comment by felixfbecker** [comment]
But how can it be of deduplication? That would mean running `yarn` in CI or locally, _after Renovate deduplicated_, somehow _removed_ a transitive dependency (note there is no addition in the diff of `scheduler` as a non-deduped-package, it is just a removal of one requirement). But running `yarn-deduplicate -s fewer` _again_ locally or in CI after that doesn't do anything (like producing the same diff again that Renovate produced).

What version of `yarn-deduplicate` is Renovate running and which `--strategy` does it pass?

**Comment by rarkins** [comment]
What I witnessed one time while playing around was:

1. At first, there were separate "objects" in yarn.lock for `scheduler@^0.13.2` and `scheduler@^0.13.6`
2. `yarn-deduplicate` combined them into a single object/line
3. A subsequent run of `yarn` removed the `^0.13.2` part of the line, as you show on your diff just above. Somehow it's not needed?

**Comment by felixfbecker** [comment]
Does Renovate run `yarn` again after running `yarn-deduplicate`? If not, could you try making it do that? Sounds like that would "stabilize" the yarn.lock / create the same "corrections" that we are observing locally/in CI

**Comment by rarkins** [comment]
Right now it doesn't but it sounds like a good idea to do so

**Comment by felixfbecker** [comment]
This is still happening :(
The majority of our Renovate PRs this month are failing and cannot be merged without additional human work

**Comment by rarkins** [comment]
Sorry, I forgot about this one. I’ll try to add the extra “yarn” like you suggest

**Comment by rarkins** [comment]
@felixfbecker I've implemented as we discussed, but just putting it live in the app in about 5 minutes time.
