### ISSUE TITLE
Drop Node.js 6 from LTS 

### ISSUE THREAD

**Issue by ErisDS** [renovatebot/renovate#3637]
Node.js v6 went end of life on April 30th: https://github.com/nodejs/Release

This means updating the array here: https://github.com/renovatebot/renovate/blob/a9332a8db078a73d69e5ffde17df20d8b88b5c1e/lib/manager/travis/package.js#L12

I can submit a PR to do this, although I believe that also means updating some tests.

I am not sure if there are any other considerations before diving into these changes, or if it's desirable for me to put a PR together?

**Comment by rarkins** [comment]
Thanks. I’ll push a fix today as it should be quick enough to do

**Comment by ViceIce** [comment]
maybe we can use [schedule.json](https://github.com/nodejs/Release/blob/master/schedule.json) to find current versions?

**Comment by ViceIce** [comment]
@rarkins What do you think about reading the `schedule.json`?

**Comment by rarkins** [comment]
@ViceIce good idea, we can discuss in #1269
