### ISSUE TITLE
Request to support automatic update of pre-release semver tag

### ISSUE THREAD

**Issue by smukherj1** [renovatebot/renovate#3645]
**What would you like Renovate to be able to do?**
This is a follow up from #3595. Since renovate doesn't pick up a custom tag format, we decided to use a semver style versioning for our repository [bazelbuild/bazel-toolchains](https://github.com/bazelbuild/bazel-toolchains). Our releases are tied to Bazel releases as well as another internal artifact. The thing is Bazel already uses a x.y.z release tag and we wanted to have the Bazel version in our release tag for usability (easier for our customers to tell which Bazel version a particular release of our repository works with). Thus, in order to support the additional internal artifact, we decided to use the pre-release semver format explained [here](https://semver.org/#spec-item-9).

Thus for the following releases:
1. Bazel 0.24.1
2. Internal release
3. Bazel 0.25.0
4. Internal release
5. Internal release

the bazel-toolchains releases will be tagged as follows:
1. 0.24.1-0
2. 0.24.1-1
3. 0.25.0-0
4. 0.25.0-1
5. 0.25.0-2

I wasn't sure if renovate supports this already so I set up the test target [here](https://github.com/bazelbuild/bazel-toolchains/blob/4b3f507f3104a69299c1fb8d242e4269fa50f5c5/WORKSPACE#L416) and created the releases in the source repository [here](https://github.com/smukherj1/renovate-src/releases). It seems renovate doesn't want to update the tag from `0.24.1-0` to `0.24.1-1`.

**Describe the solution you'd like**
Would it be possible for renovate to support semver updates of the format described [here](https://semver.org/#spec-item-9)? This should allow renovate to support the scenario I described above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rarkins** [comment]
@smukherj1 so *all* bazel-toolchains releases will look like an unstable/pre-release version, but you just want Renovate to keep updating them as if they were normal/sortable stable releases?

**Comment by rarkins** [comment]
If you can provide me with a repo to reproduce with, I can look into why it's not being updated already. We do "support" this format although it gets classified as unstable and that itself can affect how the logic proceeds.

**Comment by smukherj1** [comment]
Hi @rarkins,

To test, please use [this](https://github.com/smukherj1/renovate-src/releases) repo. This is what I was using to test the target [here](https://github.com/bazelbuild/bazel-toolchains/blob/4b3f507f3104a69299c1fb8d242e4269fa50f5c5/WORKSPACE#L416)

Thanks

**Comment by rarkins** [comment]
@smukherj1 in my test WORKSPACE, it does upgrade: https://github.com/renovate-tests/bazel7/pull/2/files

What it's not doing is "jumping" versions it thinks are unstable though, perhaps that's what you want?

**Comment by rarkins** [comment]
Right now that repo only has 2 releases, and Renovate is updating to the latest one: https://github.com/smukherj1/renovate-src/releases

I think if you create a new release like `0.25.0-0` then you won't see Renovate updating by default, however if you set "ignoreUnstable" to `false` then it should work.

**Comment by smukherj1** [comment]
@rarkins Thanks for the tip about the `ignoreUnstable` tip! I'll try it out and report if it works for me

**Comment by smukherj1** [comment]
Ok I did set ignoreUnstable to false [here](https://github.com/bazelbuild/bazel-toolchains/blob/master/renovate.json#L5) but renovate doesn't seem to be sending a PR to update [this](https://github.com/bazelbuild/bazel-toolchains/blob/master/WORKSPACE#L416). Any ideas?

**Comment by rarkins** [comment]
@smukherj1 that repository doesn't show up as being installed. It was added on 26th feb and then this PR was merged: https://github.com/bazelbuild/bazel-toolchains/pull/320

But at some point it's been flagged as inactive/uninstalled. Can you or an org admin double check what the settings are for the app? Probably under https://github.com/apps/forking-renovate

**Comment by rarkins** [comment]
I checked the logs and only these show up as installed:
```
    "bazelbuild/bazel-integration-testing",
    "bazelbuild/bazel-watcher",
    "bazelbuild/rules_cc",
    "bazelbuild/rules_docker",
    "bazelbuild/rules_k8s",
    "bazelbuild/rules_nodejs",
    "bazelbuild/rules_scala"
```

Someone probably changed from "All repositories" to "Select repositories" and did not include this one. The Configure Renovate PR may have just been left hanging.

**Comment by smukherj1** [comment]
Ok thanks for help figuring it out! I'll need to get in touch with the admin of our org

**Comment by rarkins** [comment]
Let me know if that resolves it

**Comment by smukherj1** [comment]
@rarkins thanks a lot! Renovate just sent a PR to update this target https://github.com/bazelbuild/bazel-toolchains/pull/495

**Comment by rarkins** [comment]
Awesome!
