### ISSUE TITLE
CircleCI orb not updated after checking the retry checkbox

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3655]
**What Renovate type are you using?**
Renovate GitHub App?

**Describe the bug**
- I updated CircleCI orb to 1.10.159
- renovate opened a PR updating the orb to 1.10.159
- I updated orb to 1.10.160
- I checked `If you want to rebase/retry this PR, check this box`
- renovate started a new build but still with the old orb (1.10.159) though the newest orb was already published

**Did you see anything helpful in debug logs?**
```
DEBUG: orb.getPkgReleases()
{
  "lookupName": "dmx-io/base"
}
DEBUG: packageFiles with updates
{
  "config": {
    "circleci": [
      {
        "packageFile": ".circleci/config.yml",
        "manager": "circleci",
        "deps": [
          {
            "depType": "orb",
            "depName": "dmx_base",
            "currentValue": "1.10.137",
            "lineNumber": 2,
            "datasource": "orb",
            "lookupName": "dmx-io/base",
            "commitMessageTopic": "{{{depName}}} orb",
            "versionScheme": "npm",
            "rangeStrategy": "pin",
            "updates": [
              {
                "fromVersion": "1.10.137",
                "toVersion": "1.10.159",
                "newValue": "1.10.159",
                "newMajor": 1,
                "newMinor": 10,
                "updateType": "minor",
                "isSingleVersion": true
              }
            ],
            "warnings": [],
            "sourceUrl": null,
            "homepage": "https://circleci.com/orbs/registry/orb/dmx-io/base",
            "releases": [
              "1.10.137",
              "1.10.157",
              "1.10.158",
              "1.10.159"
            ]
          }
        ]
      }
    ],
```

**Expected behavior**
Renovate should update the orb to 1.10.160

**Additional context**
My `renovate.json`:
```
{
  "automerge": false,
  "commitMessagePrefix": "[renovate] ",
  "labels": [
    "renovate"
  ],
  "npmToken": "<redacted>",
  "rangeStrategy": "bump",
  "packageRules": [
    {
      "automerge": true,
      "groupName": "DMX dependencies",
      "managerBranchPrefix": "",
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    },
    {
      "automerge": true,
      "groupName": "DMX dependencies",
      "managers": [
        "circleci"
      ],
      "managerBranchPrefix": "",
      "schedule": "at any time"
    },
    {
      "allowedVersions": "1.13.0",
      "packageNames": [
        "yarn"
      ]
    },
    {
      "groupName": "mongoose",
      "managerBranchPrefix": "mongoose",
      "packageNames": [
        "mongoose"
      ],
      "rangeStrategy": "pin",
      "schedule": "at any time"
    }
  ],
  "groupName": "other than DMX",
  "schedule": "before 3am on the first day of the month"
}
```

**Comment by piotr-s-brainhub** [comment]
I see not only info that a new orb has been published but it's even publicly available at https://circleci.com/orbs/registry/orb/dmx-io/base so it's strange that renovate cannot see it.

**Comment by rarkins** [comment]
Renovate caches Orb results for 30 minutes: https://github.com/renovatebot/renovate/blob/e78fe7cfb7717fe098f05fe6bab66f4d95570965/lib/datasource/orb/index.js#L52

This is so that we don't "hammer" their API and risk getting banned.

**Comment by rarkins** [comment]
Did this resolve on the next run?

**Comment by piotr-s-brainhub** [comment]
After some waiting it updated but it would be good to be able to disable cache in some situations.

**Comment by rarkins** [comment]
The cache is service-wide for now so not easily configurable per-user. It's important that we keep within what services consider to be reasonable use - we've already run into rate limiting by pretty much every service there is! I'll reduce cache time to 15 minutes and close this issue when that's done.
