### ISSUE TITLE
Add back metadata for rubygems.org packages to get release notes / changelog

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3670]
**What would you like Renovate to be able to do?**

Add back rubygems package and version metadata (e.g. package home page, version release date, and ruby compatibility) that was "lost" in #3669.

**Describe the solution you'd like**

Rely on the CDN to get a full view of every version of every package, but when we detect it's changed then we should do an API-based fetch of the package and versions.

I think this should work well:

1. Query the versions file to get a full list of releases for the package
2. Query our cache for full metadata of the package. If the cache is empty for this package, or the versions list does not match what we found in the CDN file, then we refresh and overwrite it. No expiry date, but we should add a "last fetched" field of our own.

Also:
- We need to make sure we don't hit the Rubygems API [rate limits](https://guides.rubygems.org/rubygems-org-api/#rate-limits). Rate limiting per second needs to be built into the fetcher, something conservative like 5 per second.
- We need to defensively program against querying the API every time if there's a permanent mismatch. Our internal "last fetched" date can help wtih this

**Describe alternatives you've considered**

The `/info/*` endpoint for packages is CDN-based but is missing the release date of each version, which I think is really important. Therefore we need to query the API endpoints for the full data.

Another consideration was whether we need to re-query the package metadata (source URL, homepage, etc) periodically but I think it makes sense to only refresh it if there's a new *version* published, and this approach will be much more efficient.

**Additional context**

See #3373

**Comment by JamieMagee** [comment]
I'm refactoring the `rubygems` datasource right now, and was wondering about this API.

Do you think this refactoring is possible to do with the robust caching we have in place right now?

**Comment by rarkins** [comment]
No, it will need https://github.com/renovatebot/renovate/issues/11024 first so that we can greatly reduce the number of times we need to query the rubygems API

**Comment by 100terres** [comment]
Hi :wave: On one of the project I'm working, we are currently migrating from dependabot to renovate :tada: :slightly_smiling_face:

But we've noticed that PRs opened for `rubygems` do not include the change logs/release notes and the link to the repository as it does for `npm`. It's also a feature provided by `dependabot`. It is probably related to [this current issue](https://github.com/renovatebot/renovate/issues/3670), because we are not fetching the metadata from rubygems. If that's the case, do you have an ETA of when we could expect these features to be back? :slightly_smiling_face:

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by rarkins** [comment]
Blocked by #11024

**Comment by mscrivo** [comment]
This still seems to not work, should it be? Is it still being worked on?

**Comment by rarkins** [comment]
@mscrivo it's an open and unassigned issue, so you don't need to ask those questions

**Comment by mscrivo** [comment]
> @mscrivo it's an open and unassigned issue, so you don't need to ask those questions

Apologies, I looked through all the linked issues and thought that it was closed as resolved and this issue was just forgotten/dangling. Thanks for clarifying.
