### ISSUE TITLE
Move CI to CircleCI

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3675]
I'd like to explore running CI with CircleCI instead of TravisCI. Perhaps we can also utilise some parallelisation to get faster builds.

**Comment by nihal9ns** [comment]
We only need jobs for tests and deployments ryt? And the build should be triggered for deployments from any branch or only master?

**Comment by rarkins** [comment]
I think initially, we keep it simple:
- No parallelisation
- No deploy.. yet. That will need credentials and is hard to test anyway

Hopefully we will do the same as we do here with TravisCI, i.e.
- Run for all PRs
- Don't run for branch pushes unless it's master

**Comment by rarkins** [comment]
In short, the current travis config can be seen as the requirements spec

**Comment by rarkins** [comment]
BTW we could also record the steps here and blog it - I'm sure it would help others in future

**Comment by nihal9ns** [comment]
Sure thing! blog would be a good one! It's a bit cumbersome for newbees!

**Comment by nihal9ns** [comment]
Where do you want the blog to be? medium? or in our docs?

**Comment by rarkins** [comment]
On the website, I would need to publish it. If you write it in markdown then it will work

**Comment by nihal9ns** [comment]
okay

**Comment by nihal9ns** [comment]
what all the doc should contain? setting up circleci, writing a simple config and migrating from travis ci to circle ci?

**Comment by rarkins** [comment]
I was just thinking "Diary of migrating a TravisCI config to CircleCI"

i.e. the kind of thing I would have liked to find if I'd done it myself

**Comment by nihal9ns** [comment]
sounds good! by the way, I was just testing the circle ci build and by mistakenly created a PR to renovatebot/renovate master branch. please ignore that :p

**Comment by nihal9ns** [comment]
the circleci config and its relevant doc is done

**Comment by nihal9ns** [comment]
will create a PR
