### ISSUE TITLE
includeForks config doesn't work on Gitlab

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/renovate#3679]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
We're using the default setting for ignoreForks - but renovate is creating configuration MRs for forked repositories

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

**To Reproduce**
Use `autodiscover` with the self-hosted renovate on gitlab and give permission to renovate for a group containing forked repositories

**Expected behavior**
For it to ignore the forks

**Additional context**
It looks like the `isFork` parameter is not being set in the gitlab platform code, but it is in github/bitbucket

**Comment by rarkins** [comment]
Which exact version of Renovate are you running?

**Comment by mikebryant** [comment]
Apologies, should have said: `renovate/renovate:14.51.0@sha256:593a519aa6363804c9aea395e172f37631787a0c3c3373324d3ca1b7bd2b362c`

**Comment by rarkins** [comment]
We would be fixing this in v17 though, i.e. not backporting to v14.

I don't see the string "isFork" in the lib/platform/gitlab files, so somehow it seems left out.

We might want to check for the `forked_from_project` field/object in the project response.
