### ISSUE TITLE
latest tag on Docker Hub is 16.13.6, not 17.3.5

### ISSUE THREAD

**Issue by Delphinator** [renovatebot/renovate#3692]
**What Renovate type are you using?**
Renovate CLI Docker Image

**Describe the bug**
The `latest` tag on Docker Hub is currently equivalent to 16.13.6, not 17.3.5.

**Did you see anything helpful in debug logs?**
`setup.py` failed to parse, probably some old, long fixed bug.

**To Reproduce**

`docker run -it --rm renovate/renovate --version` or go to https://hub.docker.com/r/renovate/renovate/tags

**Expected behavior**
The `latest` tag is the most recent version, even if maintenance releases to older major (or minor) versions are made.

**Comment by Delphinator** [comment]
Since 17.3.5 shows the same error in the logs, here it is:

```
 INFO: Renovating repository (repository=my/repo)
 INFO: Initialising git repository into /tmp/renovate/repos/gitlab/my/repo (repository=my/repo)
 INFO: git clone completed (repository=my/repo)
       "cloneSeconds": 0.5
 INFO: Setting git author (repository=my/repo)
       "gitAuthor": {"name": "Renovate Bot", "email": "renovate-bot@my-domain.example.com"}
 INFO: Repository config (repository=my/repo)
       "configFile": "renovate.json",
       "config": {"extends": ["config:base"], "pip_setup": {"enabled": true}}
 INFO: Found gitlabci package files (repository=my/repo)
 INFO: Running python via global command (repository=my/repo)
 WARN: Failed to read setup.py file (repository=my/repo)
       "err": {
         "name": "ChildProcessError",
         "code": null,
         "childProcess": {},
         "stdout": "",
         "stderr": "",
         "message": "Command failed: python3.7 /usr/src/app/dist/manager/pip_setup/extract.py setup.py\n `python3.7 /usr/src/app/dist/manager/pip_setup/extract.py setup.py` (exited with error code null)",
         "stack": "ChildProcessError: Command failed: python3.7 /usr/src/app/dist/manager/pip_setup/extract.py setup.py\n `python3.7 /usr/src/app/dist/manager/pip_setup/extract.py setup.py` (exited with error code null)\n    at callback (/usr/src/app/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:189:13)\n    at maybeClose (internal/child_process.js:970:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       }
 INFO: Processing 0 branches:  (repository=my/repo)
 INFO: Finished repository (repository=my/repo)
```

log on v16.13.6:

```
 INFO: Renovating repository (repository=my/repo)
 INFO: Repository config (repository=my/repo)
       "configFile": "renovate.json",
       "config": {"extends": ["config:base"], "pip_setup": {"enabled": true}}
 INFO: Found gitlabci package files (repository=my/repo)
 INFO: Running python via global command (repository=my/repo)
 WARN: Failed to read setup.py file (repository=my/repo)
       "err": {
         "name": "ChildProcessError",
         "code": null,
         "childProcess": {},
         "stdout": "",
         "stderr": "",
         "message": "Command failed: python3.7 /usr/src/app/lib/manager/pip_setup/extract.py setup.py\n `python3.7 /usr/src/app/lib/manager/pip_setup/extract.py setup.py` (exited with error code null)",
         "stack": "ChildProcessError: Command failed: python3.7 /usr/src/app/lib/manager/pip_setup/extract.py setup.py\n `python3.7 /usr/src/app/lib/manager/pip_setup/extract.py setup.py` (exited with error code null)\n    at callback (/usr/src/app/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:189:13)\n    at maybeClose (internal/child_process.js:970:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       }
 INFO: Processing 0 branches:  (repository=my/repo)
 INFO: Finished repository (repository=my/repo)
```

**Comment by rarkins** [comment]
There's a few things going on here:

1. Docker's concept of "latest" isn't the same as npm's. I'm not sure if there's anything I can do to prevent backported releases (in this case 16.x) from getting Docker's "latest" tag

2. In the very earliest 17.x release we weren't copying extract.py into "dist" but that problem never existed in 16.x and should be fixed in all 17.x now. I'm not sure if your extract.py error is something else and not because it's not found. In your #3672 issue the error read differently: `"stderr": "python3.7: can't open file '/usr/src/app/dist/manager/pip_setup/extract.py': [Errno 2] No such file or directory\n"`

**Comment by Delphinator** [comment]
> 1. Docker's concept of "latest" isn't the same as npm's. [...]

Ah, the joys of packaging. Well, I guess I'll use the 17 tag instead and make sure I don't miss a new major version.

> 2. In the very earliest 17.x release we weren't copying extract.py into "dist" but that problem never existed in 16.x and should be fixed in all 17.x now.

This one is just odd tbh. The last ~10 runs overnight (German, so UTC+2) were fine with ~50% failing in the hours before. But this was mostly about the docker tag, so... let's ignore this until I can reproduce it or it at least happens with a somewhat consistent chance.

**Comment by rarkins** [comment]
Yes, pinning to `renovate/renovate:17` is a good idea. Please raise another issue if you reproduce anything with the `extract.py`
