### ISSUE TITLE
Renovate fails to parse Dockerfile FROM when using custom registry:port

### ISSUE THREAD

**Issue by pyaillet** [renovatebot/renovate#3698]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate fail to parse Dockerfile FROM when using custom registry:port

**Did you see anything helpful in debug logs?**
```
DEBUG: packageFiles with updates (repository=piail/renovate-test)
       "config": {
         "dockerfile": [
           {
             "packageFile": "Dockerfile",
             "manager": "dockerfile",
             "deps": [
               {
                 "depName": "registry.internal",
                 "currentFrom": "registry.internal:4567/docker/base/production/base:9.6-3-161",
                 "currentDepTag": "registry.internal:4567/docker/base/production/base:9.6-3-161",
                 "currentValue": "4567/docker/base/production/base",
                 "datasource": "docker",
                 "lineNumber": 0,
                 "fromPrefix": "FROM",
                 "fromSuffix": "",
                 "depType": "final",
                 "updates": [],
                 "warnings": [],
                 "skipReason": "unsupported-value"
               }
             ]
           }
         ]
       }
```

**To Reproduce**

1.  Create repository with a Dockerfile and a FROM like this:
`FROM registry.internal:4567/docker/base/production/base:9.6-3-161
2.  Configure renovate cli to check this repo

**Expected behavior**
I expected renovate to parse the FROM clause and identify correctly the depName/currentValue used later in the process.

**Additional context**
I think the [current tests](https://github.com/renovatebot/renovate/blob/master/test/manager/dockerfile/__snapshots__/extract.spec.js.snap#L228) are broken.

**Comment by pyaillet** [comment]
I would want to work on this issue as I need it fixed to properly evaluate `renovate`

**Comment by rarkins** [comment]
@pyaillet actually I have it fixed and about to push it to master

**Comment by rarkins** [comment]
Thanks for your offer though :)

**Comment by rarkins** [comment]
I just realised it's a little harder than I first expected. I probably won't get back to it until 5-6 hours time, so feel free to raise a PR before that if you prefer. We need to handle both these cases:

```
FROM registry.internal:4567/docker/base/production/base
FROM registry.internal:4567/docker/base/production/base:9.6-3-161
```

**Comment by rarkins** [comment]
Actually maybe I do have it solved now. Pushing in 5 minutes

**Comment by pyaillet** [comment]
Wow, this is fast :)
Thank you very much !
