### ISSUE TITLE
Sanitize all HTML comments on Bitbucket/Bitbucket Server

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3715]
e.g. so we don't see this:

![image](https://user-images.githubusercontent.com/6311784/57841832-98f88100-77cb-11e9-8200-6cab0aea9eca.png)

**Comment by rarkins** [comment]
Where to add: https://github.com/renovatebot/renovate/blob/8f6e12499834689f1ca8554480cc108f6ffa0b0d/lib/platform/bitbucket-server/index.js#L924-L932

And same place for Bitbucket

**Comment by psyb0t** [comment]
Could you give an example screenshot of a comment that needs to be cleaned up? The sshot above is of a master issue and that's been fixed.
![Screenshot_2019-05-23_14-06-54](https://user-images.githubusercontent.com/12934156/58248177-2572e880-7d64-11e9-84f5-6325b6e61e36.png)

**Comment by rarkins** [comment]
This was more of a backup plan in case we miss any in future. Right now I’m not aware of any but we may start adding hidden metadata to PRs which would need to be stripped for BB

**Comment by psyb0t** [comment]
https://regex101.com/r/OCq1Hl/1

That's a PR body from a repo of mine with the current regex rules in place. Do you see anything else that needs to be cleaned up?

**Comment by rarkins** [comment]
I thought we already had some replaces to handle those examples? I was just more thinking a generic `<!-- ..... -->` replacement to be added to what we already have.
