### ISSUE TITLE
rangeStrategy=pin not working for maven

### ISSUE THREAD

**Issue by jamesmmchugh** [renovatebot/renovate#3716]
### Which Renovate are you using? CLI, App, or Pro
OSS docker

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I have this config:

```
{
  "extends": [
    "config:base"
  ],
  "maven": {
    "ignoreDeps": ["org.apache.commons:commons-math3"]
  },
  "packageRules": [
    {
      "managers": ["maven"],
      "packageNames": ["com.google.guava:guava"],
      "versionScheme": "docker"
    },
    {
      "managers": ["maven"],
      "packageNames": ["org.projectlombok:lombok"],
      "rangeStrategy": "pin"
    }
  ]
}
```

With this lombok dependency in my maven pom:

```
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>[1.12.6,1.18.6]</version>
        </dependency>
```

And the latest version of lombok being 1.18.8.

Which, if I understand correctly, should pin the lombok dependency version to the version `1.18.8` when it get's updated. However, the onboarding PR states:

`Upgrade org.projectlombok:lombok to [1.12.6,1.18.8]`

Am i misunderstanding, or mis-configuring renovate?

Cheers

**Comment by rarkins** [comment]
Tada

**Comment by rarkins** [comment]
@zharinov could you take a look at this?

**Comment by zharinov** [comment]
@rarkins sure
