### ISSUE TITLE
Feature request: Never close or force push modified pull requests

### ISSUE THREAD

**Issue by dylang** [renovatebot/renovate#3724]
**What would you like Renovate to be able to do?**

We have an updated eslint plugin that we've been working on a few weeks to make our code lint with the changes from the plugin. 

Before this work was merged, a newer version of the plugin was released. 

Renovate closed the PR that we were contributing to and opened a new one with the new version, meaning our contributions to the renovate pull request were lost in this process.

We had already updated the original PR to that new version, and updated the title to match that version.

Now that the original PR has been deleted, we need to redo those changes in the new pull request.

**Describe the solution you'd like**

In order of priority:

1. When Renovate pull requests have been modified and not merged, never close, delete, or merge those pull requests.
2. Instead of deleting and replacing, just add a comment that a newer version is available.
3. When closing an unmodified pull request to replace with a newer version, add a comment to the pull request being closed explaining why it's being closed.
4. When opening a replacement pull request, include a mention of the outdated pull request so they link to each other.

**Describe alternatives you've considered**

**Additional context**

* Self hosted renovate@17.5.1.

<img width="823" alt="Screen Shot 2019-05-16 at 10 31 46 AM" src="https://user-images.githubusercontent.com/51505/57862122-d823d380-77c5-11e9-8434-9554d98b44c3.png">

**Comment by rarkins** [comment]
It doesn’t sound right that Renovate would close a modified PR. Normally it posts a comment noting it won’t touch the PR after you add a commit. Can you give even more details? Was it a new major version perhaps?

**Comment by tmax** [comment]
not just that, it wrote over the commits that were made to the earlier branch it opened, so those commits is no longer salvageable.

**Comment by rarkins** [comment]
I’ll need a lot more details, including Renovate logs.

**Comment by rarkins** [comment]
By the way, when you click on the bolded commits in the "force push" comments (in screenshot above) you should be able to see the code. GitHub doesn't actually remove/prune it so there is no such things as really "writing over" commits. It can write over which commit the branch points to, but not write over the old commit itself.

**Comment by rarkins** [comment]
Looking at that sequence of events:
- "PR has been edited" comment: this is what I'd expect if you added commits to it
- Then it says the bot force pushed 4 times. Presumably by then it had "overwritten" the branch's human commits?
- talmiski then changed the title. Why was this?
- who made commit be912a1? it looks like the bot did. But did talmiski predict that change before the bot made it?
- there doesn't seem to have been a rename of the PR before it was closed? this indicates it *wasn't* deliberately autoclosed.

One thing I'll flag is that, based on the name of your bot, it looks like you probably run more than just Renovate Bot using that account, is that right? If another bot writes or modifies Renovate branches in any way using the same user account as Renovate, there's a chance to cause problems. There would even be doubt if it was Renovate itself deleting the branch/closing the PR until I know what the other bots on the same account are.

**Comment by rarkins** [comment]
What do you see when you click on the very last commit made? Is it a regular renovate commit with the latest of this package, or is it an empty commit with no changes from master?

Also, are you using gitFs?

**Comment by dylang** [comment]
Let's see if I can answer all of your questions:

While this PR was open, a newer version of the dependency this PR was upgrading came out. I upgraded the dependency a week ago. `talmiski` saw the change, and renamed the pull request to match that version. Then, I believe that evening or next morning Renovate force-pushed updates from Master as other renovate PR's were being approved and merged.

* One renovate bot. `service-continuous-deliver` is the name on the Github Enterprise api key we use, and it seems like `Renovate Bot` is the name used in Git.
* Who did change `be912a1`: `Renovate Bot` did, and this change updates the version to match the title, because the force push before this one was updating from `master`, which undid the version upgrade.
* What we see now: just a normal renovate PR with `package.json` and `yarn lock` changes, nothing else.

I reached out to `talmiski` so see if he might have checked this box, haven't heard back yet, I'll update when he does. He's new to Renovate and might not have realized it would force-push over our changes. I didn't realize either.

<img width="737" alt="Screen Shot 2019-05-17 at 1 37 11 PM" src="https://user-images.githubusercontent.com/51505/57946247-df241200-78a9-11e9-8c21-f6a2f79a166d.png">

Maybe that checkbox should be removed once it has been edited?

**Comment by rarkins** [comment]
The “PR has been edited” comment contains a description of what happens if you rebase/retry.  If we take away the checkbox then people who do want to start over can’t do it easily, although I wonder how many times it’s caused problems like this.

**Comment by dylang** [comment]
`talmiski` did not check the box. I found another case of an edited PR being force-pushed over and then deleted when the module was updated. Same outdated module, we've been working on this for a while!

<img width="841" alt="Screen Shot 2019-05-17 at 2 08 57 PM" src="https://user-images.githubusercontent.com/51505/57947641-7343a880-78ad-11e9-90bb-e90178d467ff.png">

**Comment by dylang** [comment]
Last commit for both look like the normal Renovate commits. It's the only commit in the history for these pull requests.

<img width="1311" alt="Screen Shot 2019-05-17 at 2 11 25 PM" src="https://user-images.githubusercontent.com/51505/57947764-c9b0e700-78ad-11e9-9d3f-81c7814f82c9.png">

**Comment by rarkins** [comment]
So you have any Renovate logs from when it happened?

**Comment by dylang** [comment]
Haven't had time to find the logs.

**Comment by rarkins** [comment]
TODO: Before autoclosing (or deleting a branch), check if Renovate was the last committer to it. If it's not the last committer, then do not delete the branch. If a PR exists, then add a comment to it saying it was due to be autoclosed but will be skipped as the last committer does not match the bot. We can probably reuse our existing pr.canRebase logic
