### ISSUE TITLE
Multiple docker hosts in the config file is not supported

### ISSUE THREAD

**Issue by pyaillet** [renovatebot/renovate#3743]
### Which Renovate are you using? CLI, App, or Pro
renovate cli

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
gitlab

### Have you checked the logs? Don't forget to include them if relevant
with this in my config.js:
```json
  hostRules: [
    {
      platform: 'docker',
      host:     'myregistry.internal:4567',
      username: 'piail',
      password: '<password>',
    },
    {
      platform: 'docker',
      host:     'docker.io',
    },
  ],
```

I end up with this in platforms object (used in host-rules, I added logs):
```json
       "platforms": {
         "docker": {"platform": "docker", "host": "docker.io"},
         "gitlab": {
           "gitlab.internal": {
             "name": "GitLab",
             "endpoint": "https://gitlab.internal/api/v4/",
             "platform": "gitlab",
             "username": null,
             "password": null,
             "token": "<TOKEN>",
             "default": true
           }
         }
       }
```

See [this discussion](https://github.com/renovatebot/config-help/issues/240) for more details

**Comment by rarkins** [comment]
@pyaillet could you test out the v18 of Renovate to see if it solves your problems?

FYI: v18 actually contains a couple of major rewrites (including hostRules) so it's still labeled as "next" and not "latest", until there's been more testing.

Your config should be like this:

```js
 hostRules: [
    {
      hostType: 'docker',
      baseUrl:  'https://myregistry.internal:4567',
      username: 'piail',
      password: '<password>',
    },
    {
      hostType: 'docker',
      domainName: 'docker.io',
      username: 'piail',
      password: '<other password>',
    },
  ]
```

Note the change in terminology, docs are here: https://renovatebot.com/docs/configuration-options/#hostrules

Also note that we use domainName, hostName and baseUrl as selectors. In your case you have a port, which only applies to `host` and not `hostname` so I have shown it as a `baseUrl` instead, assuming you have `https`.

**Comment by pyaillet** [comment]
It works ! Many thanks :)
