### ISSUE TITLE
Gitlab Dashboard shows no repositories

### ISSUE THREAD

**Issue by faceleg** [renovatebot/renovate#3755]
**What Renovate type are you using?**
Renovate on GitLab

**Describe the bug**
The dashboard (https://renovatebot.com/dashboard) does not show any repositories after logging in with my GitLab account.

**To Reproduce**
1. Go to https://renovatebot.com/dashboard
2. Login with my GitLab account that belongs to the relevant GitLab group containing my repository	
3. Wait ...

**Expected behavior**
My repositories appear in the sidebar and I can select them to enable renovate.

**Screenshots**
![Screen Shot 2019-05-20 at 4 14 16 PM](https://user-images.githubusercontent.com/1000759/58051410-34ac3780-7ba6-11e9-841e-5a5798ff69de.png)

**Comment by rarkins** [comment]
@faceleg please fill out the issue so that we can look at your issue. Please also include screenshots and any relevant console logs from your browser.

**Comment by faceleg** [comment]
@rarkins sorry! I filled it all in then must have clicked something on github that cleared it.

**Comment by rarkins** [comment]
@faceleg do you already have some installed? Or is this the first time logging in? What if you click the Settings icon in the left side and wait for that to load?

**Comment by faceleg** [comment]
Oh, when I opened it it just sat there empty for about 10 seconds, I assumed it was broken. Leaving it open for much longer saw it begin to fill, I'll close this issue? 

Adding a loading indicator would have prevented me from assuming it was broken.

**Comment by rarkins** [comment]
Thanks. Yes, we need a loading indicator!

**Comment by faceleg** [comment]
@rarkins how long after I've "activated" my repo on the dashboard before I should see it has created a webhook? 

This repo was previously working on GitHub, so it has a renovate.json etc.

**Comment by faceleg** [comment]
It seems to be doing things, thanks for your help!

**Comment by esetnik** [comment]
I had the same issue. Initially, after onboarding via gitlab login I had no idea what to do. And then when I clicked the settings wheel nothing showed for awhile so I assumed it wasn't working. There definitely needs to be a loading indicator here.
