### ISSUE TITLE
Unable to `npm install`

### ISSUE THREAD

**Issue by dominykas** [renovatebot/renovate#3757]
**What Renovate type are you using?**

Renovate CLI

**Describe the bug**

`npm install renovate` fails or hangs.

**Additional context**

This is because of a GitHub based dependency introduced in https://github.com/renovatebot/renovate/pull/3732. `yarn` does the right thing and presumably installs this over `git+https`, whereas `npm` uses `git+ssh` by default. If the local setup (e.g. a CI system) does not have a public key set up for public GitHub - the installation will fail, with something like `npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/rarkins/ruby-semver.git`

Resolution options:

* wait it out until snyk accepts and publishes https://github.com/snyk/ruby-semver/pull/22
* reference `git+https://github.com/rarkins/ruby-semver.git#semverfix` in `package.json`
* publish a separate scoped version of this on npm

**Comment by dominykas** [comment]
🤦‍♂ the container this was running it was missing the `git` binary... although I'm still failing to install this locally - seems to hang forever - but I'll see what the actual reason for that is.

**Comment by dominykas** [comment]
Upd: locally it just takes a very long time (10 minutes) - not sure which dep causes that, but probably a problem with `npm` (`yarn` behaves better).

**Comment by gjvis** [comment]
hi :wave:, in case it turns out to be relevant, we've accepted and merged https://github.com/snyk/ruby-semver/pull/22 – changes are published in version 2.0.2

**Comment by rarkins** [comment]
Thanks @gjvis, we've now released a new Renovate version with v2.0.2
