### ISSUE TITLE
Implement ensureIssue/ensureIssueClosing for Bitbucket Server

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3766]
Source: https://github.com/renovatebot/renovate/blob/05ec931f36ad844dcf06c2f1fccd9703a29dbd32/lib/platform/bitbucket-server/index.ts#L408-L449

Although the API is different, these functions can be modelled from Bitbucket Cloud, GitHub, GitLab, etc.

**Comment by ViceIce** [comment]
This is related to #3796. Bitbucket Server has no issue capabillities on it's own.

**Comment by rarkins** [comment]
Closing in favour of #3796
