### ISSUE TITLE
missing changlog in merge request since 17.10.0

### ISSUE THREAD

**Issue by BigMichi1** [renovatebot/renovate#3774]
**What Renovate type are you using?**
Renovate CLI (latest version i tested is 17.11.4)

**Describe the bug**
i'm using renovate also for updating itself in my personal gitlab repository. but since version 17.10.0 i don't have a changlog anymore in the merge requests for renovate updates of renovate itself.

**Did you see anything helpful in debug logs?**
i found nothing in the logs

**To Reproduce**
1. create repository in gitlab
2. add package.json with a dependency to renovate
3. run renovate against the repo
4. take a look at the generated pull request

**Expected behavior**
the changelog should be displayed like before version 17.10.0

**Screenshots**
changelog included in merge request
![Bildschirmfoto vom 2019-05-21 12-07-53](https://user-images.githubusercontent.com/91786/58087621-2f101b00-7bc1-11e9-94d4-a706272de8fb.png)
changelog not included in merge request
![Bildschirmfoto vom 2019-05-21 12-08-05](https://user-images.githubusercontent.com/91786/58087619-2e778480-7bc1-11e9-8f11-08b48b995672.png)

**Additional context**

**Comment by rarkins** [comment]
I am not able to reproduce this. Do you configure a personal access token for github.com? If so, how? If not, then you need to.

**Comment by BigMichi1** [comment]
looks like after the update to 17.12.0 everything is fine again
