### ISSUE TITLE
Test against Node.js v12

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3778]
Renovate appears to *run* fine in Node.js v12 however testing fails:

```
Test Suites: 3 failed, 198 passed, 201 total
Tests:       114 failed, 1912 passed, 2026 total
Snapshots:   2 failed, 689 passed, 691 total
```

To reproduce:
```
n 12.2.0
yarn build
yarn test
```

**Comment by nihal9ns** [comment]
For me trying the above steps gives this output : 
```
➜  renovate git:(hotfix/3778) ✗ yarn build test
yarn run v1.12.3
$ yarn clean && tsc -p tsconfig.app.json && yarn copy-static-files test
$ rimraf dist
$ copyfiles -u 1 lib/**/*.json lib/**/*.py dist/ test
✨  Done in 14.96s.
➜  renovate git:(hotfix/3778) ✗ node -v
v12.2.0
```

**Comment by nihal9ns** [comment]
@rarkins  Running the tests gives me this : 
```
Snapshot Summary
 › 2 snapshots failed from 1 test suite. Inspect your code changes or run `yarn run jest -u` to update them.

Test Suites: 4 failed, 197 passed, 201 total
Tests:       115 failed, 1910 passed, 2025 total
Snapshots:   2 failed, 687 passed, 689 total
Time:        91.278s
Ran all test suites.
```

**Comment by nihal9ns** [comment]
@rarkins But however looking at the logs for the failing tests it seems it's unable to fetch the npm registry

**Comment by rarkins** [comment]
@nihal9ns yes I get the same type of registry errors. I wonder if the mocking we use in tests is not working in Node.js v12 or something  like that

**Comment by nihal9ns** [comment]
@rarkins tried to dig deeper, the error is coming from `lib/datasource/npm/get.js` 
```const raw = await got(pkgUrl, {
      json: true,
      retry: {
        errorCodes: [
          'ECONNRESET',
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN',
        ],
      },
      // TODO: Move to configurable host rules
      timeout: 60 * 1000,
      headers,
    });
```
It throws an illegal arg error. First param must be a string, buffer....
However, after adding a `JSON.stringify(pkgURl)` as it's first param, the above error disappeared and a new error popped up. `err: GotError [RequestError]: connect ECONNREFUSED 127.0.0.1:443`

Trying to figure it out

**Comment by nihal9ns** [comment]
@rarkins Found the issue, the problem is with `nock` and `got`. `nock` is not being able to intercept the requests that we have made using `got`. `got` is expecting a string or an array buffer as it's first parameter, but with `nock` being grumpy, `got` receives a function. When I removed `nock` and `got` and replaced them with `node-fetch-mock` and `node-fetch` respectively, tests seem to be working fine. `node-fetch-mock` is an alternative to `nock` but particularly for `node-fetch`. I am not sure if we would want to replace `got` with `node-fetch` completely and refactor our tests as well, this would be a tedious task. The current stable version of node is 10.16.0 and we are already trying with node 12. I believe we can wait for some time for node 12 to become stable and then check back again.

**Comment by rarkins** [comment]
We definitely want to keep `got` for the foreseeable future as we are using some of its unique features. Can you work out if there are any open issues on GitHub related to this that we should follow?

**Comment by nihal9ns** [comment]
@rarkins Sure thing, makes sense.

**Comment by nihal9ns** [comment]
@rarkins There is this one : https://github.com/sindresorhus/got/issues/799 
Somewhat relevant.

**Comment by nihal9ns** [comment]
Apart from that I could not find any related issues. But let's keep this open so that we can keep a track of it.

**Comment by nihal9ns** [comment]
`fs` is also breaking for files which are accessed outside of the current directory. Tried with absolute paths, but still doesn't work.

**Comment by nihal9ns** [comment]
Lets wait until node 12 gets a bit more stable.

**Comment by szmarczak** [comment]
Maybe this? https://github.com/sindresorhus/got/issues/817
