### ISSUE TITLE
TypeError: Cannot read property 'endpoint' of null

### ISSUE THREAD

**Issue by mastermatt** [renovatebot/renovate#3787]
**What Renovate type are you using?**
Renovate CLI
`INFO: Using renovate version: 17.11.6`

The issue started with 17.11.6 and is still an issue with 17.14.0.

**Describe the bug**
```
TypeError: Cannot read property 'endpoint' of null at Object.initRepo
(/usr/local/lib/node_modules/renovate/dist/platform/github/index.js:124:14)\n    at getPlatformConfig
(/usr/local/lib/node_modules/renovate/dist/workers/repository/init/apis.js:4:43)\n    at initApis
(/usr/local/lib/node_modules/renovate/dist/workers/repository/init/apis.js:12:20)\n    at initRepo
(/usr/local/lib/node_modules/renovate/dist/workers/repository/init/index.js:18:20)\n    at Object.renovateRepository
(/usr/local/lib/node_modules/renovate/dist/workers/repository/index.js:23:24)
```

**To Reproduce**
In a `node:10` Docker container:
```
npm install -g renovate
GITHUB_COM_TOKEN=**** renovate --token **** --endpoint=enterprise.host org/repo
```

**Expected behavior**
No repos hosted in our Github Enterprise are able to be processed.

**Comment by rarkins** [comment]
Do you have any hostRules in use?

**Comment by mastermatt** [comment]
I'm not positive if we have any, but I know that most of the repos don't.

**Comment by mastermatt** [comment]
We do make heavy use of `.npmrc` files with `registry=` defined pointing to our Artifactory install. 
Not sure if that helps, just trying to give you data.

**Comment by rarkins** [comment]
I think I've found the error, fixing now

**Comment by mastermatt** [comment]
Thanks @rarkins 
I'll post an update here after I try the new version.

**Comment by rarkins** [comment]
I couldn't *reproduce* it btw, but spotted it through code inspection. Please let me know the result

**Comment by mastermatt** [comment]
Confirmed. 17.14.1 resolved the issue.

**Comment by rarkins** [comment]
Thanks for letting me know!
