### ISSUE TITLE
fetching available versions from docker hub fails

### ISSUE THREAD

**Issue by Delphinator** [renovatebot/renovate#3791]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
renovate errors out (and autocloses related PRs / MRs) if there are dependencies on docker hub.

**Did you see anything helpful in debug logs?**
```
 INFO: Renovating repository (repository=kneipy/kneipy-core)
 INFO: Initialising git repository into /tmp/renovate/repos/gitlab/kneipy/kneipy-core (repository=kneipy/kneipy-core)
 INFO: git clone completed (repository=kneipy/kneipy-core)
       "cloneSeconds": 0.5
 INFO: Setting git author (repository=kneipy/kneipy-core)
       "gitAuthor": {"name": "Renovate Bot", "email": "renovate-bot@jensgutermuth.de"}
 INFO: Repository config (repository=kneipy/kneipy-core)
       "configFile": "renovate.json",
       "config": {
         "extends": ["config:base"],
         "pipenv": {"enabled": true},
         "pip_setup": {"enabled": true}
       }
 INFO: Found gitlabci package files (repository=kneipy/kneipy-core)
 INFO: Running python via global command (repository=kneipy/kneipy-core)
 INFO: Found pip_setup package files (repository=kneipy/kneipy-core)
 WARN: Error obtaining docker token (repository=kneipy/kneipy-core)
       "registry": "https://index.docker.io",
       "dockerRepository": "library/postgres",
       "err": {
         "message": "Cannot set property 'json' of null",
         "stack": "TypeError: Cannot set property 'json' of null\n    at getAuthHeaders (/usr/src/app/dist/datasource/docker/index.js:49:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Failed to look up dependency postgres (repository=kneipy/kneipy-core, packageFile=.gitlab-ci.yml, dependency=postgres)
 INFO: Failed to look up dependency postgres (repository=kneipy/kneipy-core, packageFile=.gitlab-ci.yml, dependency=postgres)
 INFO: Processing 0 branches:  (repository=kneipy/kneipy-core)
 INFO: Finished repository (repository=kneipy/kneipy-core)
```

**To Reproduce**

1.  Create repository with docker dependencies renovate recognizes like a .gitlab-ci.yml with
```
image: 3.7.3-stretch

test:
  script:
    - python -v
```
2.  run renovate on it

**Expected behavior**
renovate finds the latest version of dependencies on docker hub without failing and also doesn't mass-autoclose MRs / PRs on errors.

**Additional context**
17.13.0 seems to be fine, 17.14.0 is broken.

**Additional Notes**
renovate is (also) a commercial product. This bug just autoclosed a whole bunch of MRs for me without any obvious reason. I had to look at renovate logs to figure this out. I'm guessing the bot on Gitlab and Github just did the same thing. Am I really the first one to notice this?

**Comment by rarkins** [comment]
@Delphinator thanks for taking the time to raise the issue. You're right that this bug autoclosed a bunch of "commercial" users' PRs too. You were not the first but unfortunately we didnt't catch it before it had done a bunch of autoclosing. We've since fixed the bug and continued forward and the PRs are now recreated.
