### ISSUE TITLE
Test against hosted Artifactory and document the settings

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3798]
Jfrog's hosted artifactory service is pretty common. I want to make sure there's no compatibility issues and also document exactly what type of configuration is necessary, e.g. npmrc file.

**Comment by rarkins** [comment]
I can't actually find where you sign up for the hosted version from here: https://jfrog.com/artifactory/free-trial/#saas

@eladchen can you clarify if what you're using is jfrog-hosted or self-hosted? I assumed jfrog-hosted as I've seen plenty of cases of people with jfrog.io in their registry domain

**Comment by eladchen** [comment]
@rarkins  jfrog-hosted

Did you choose the region from the dropdown menu?

**Comment by eladchen** [comment]
let me know if I can help with this issue.

**Comment by cambiph** [comment]
We have an on-site instance of Jfrogs Artifactory, I can test things out if you want.

**Comment by rarkins** [comment]
@cambiph thanks. The on-site version seems pretty widely used and I'm not worried about it, so I was interested in the hosted version (i.e. ending in jfrog.io I think). If anyone already uses it and can confirm it works, I can close this.

**Comment by sluongng** [comment]
I am a bit confused with the `endpoint` config in https://github.com/renovatebot/renovate/blob/master/docs/usage/java.md#custom-registry-support-and-authentication

Is this a mistake or is it a special config for artifactory/maven?

**Comment by rarkins** [comment]
@sluongng it documents a special case where two artifactory servers are in use. if you only have one, then your config would be simpler

**Comment by jef** [comment]
How would we read secrets (GitHub Secret) if we didn't want to commit them to our repository?

**Comment by viceice** [comment]
Renovate can't read github secrets. Please open a new [issue](https://github.com/renovatebot/config-help/issues/new?labels=&template=config-help.md&title=) if you need configuration help.

**Comment by jef** [comment]
I got this setup correctly using an [encrypted password](https://renovatebot.com/encrypt).

`hostRules`:

```json
  "hostRules": [
    {
      "hostType": "maven",
      "endpoint": "https://${serverName}.jfrog.io/artifactory/${maven-repo}",
      "username": "artifactoryUsername",
      "encrypted": {
        "password": "***"
      }
    }
  ]
```

and `packageRules`:

```json
  "packageRules": [
    {
      "managers": [
        "maven"
      ],
      "registryUrls": [
        "https://${server-name}.jfrog.io/artifactory/${maven-repo}"
      ]
    }
```
