### ISSUE TITLE
Renovate fails to get Docker tags from AWS ECR

### ISSUE THREAD

**Issue by erikkrieg** [renovatebot/renovate#3800]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
When trying to get Docker image tags from AWS ECR, the request is rejected because the `maxResults` exceeds the limits for ECR.

Here you can see the query parameter, `n`, being set to `10000`: https://github.com/renovatebot/renovate/blob/d50179096572e9522b4bbea93661c48089828187/lib/datasource/docker/index.js#L263

AWS ECR will reject the request with the following:

```json
{
  "errors": [
    {
      "code": "UNSUPPORTED",
      "message": "Invalid parameter at 'maxResults' failed to satisfy constraint: 'Member must have value less than or equal to 1000'"
    }
  ]
}
```

I found [reference to `maxResults` in AWS docs for ECR](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DescribeRepositories.html#API_DescribeRepositories_RequestSyntax) that state they accept values less than or equal to `1000`.

**Expected behaviour**
Renovate should be able to integrate with AWS ECR. This value should either be:
1. Configurable.
1. Conditionally set to an appropriate value if AWS ECR is detected as the registry.
1. Hardcoded to a lower value.

Probably the first two options are safer, since behaviour would not change for existing implementations.

**Comment by rarkins** [comment]
How would we detect? Eg consistent domain suffix?

**Comment by erikkrieg** [comment]
Hey, @rarkins. Thanks for taking interest :D

Looking at the [docs for AWS ECR registries](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html), they say:

> The URL for your default registry is https://aws_account_id.dkr.ecr.region.amazonaws.com.

In their example, `aws_account_id` and `region` are placeholders. Account ID is an integer, while region is a string.

This suggests the URL can be changed, but I am not sure how common changing the URL is.

If detection is still a desirable approach, then I think the following regex might work:
```js
const exampleRegistry = '123456789.dkr.ecr.us-east-1.amazonaws.com';
const AWS_ECR_REGEX = /^\d+\.dkr\.ecr\.[-a-z0-9]+\.amazonaws\.com/;
AWS_ECR_REGEX.test(exampleRegistry); // true
```

**Comment by rarkins** [comment]
@erikkrieg thanks for the additional info. Are you able to paste the full error message from the log? i.e. that you already copy pasted from earlier? One other possibility to consider is that we catch that error and retry with 1000 instead of 10000. I'd also like to see the headers that are returned in such a case. 

Also, are you able to manually query the URL with a low `n` value to see what type of pagination response is returned?

**Comment by faceleg** [comment]
I've run into the same thing, here is the full error I'm getting:

```JSON
 WARN: Error getting docker image tags (repository=namespace/repo)
       "registry": "https://REDACTED.dkr.ecr.ap-southeast-2.amazonaws.com",
       "dockerRepository": "namespace/private",
       "err": {
         "name": "HTTPError",
         "host": "REDACTED.dkr.ecr.ap-southeast-2.amazonaws.com",
         "hostname": "REDACTED.dkr.ecr.ap-southeast-2.amazonaws.com",
         "method": "GET",
         "path": "/v2/namespace/private/tags/list?n=10000",
         "protocol": "https:",
         "url": "https://REDACTED.dkr.ecr.ap-southeast-2.amazonaws.com/v2/namespace/private/tags/list?n=10000",
         "gotOptions": {
           "path": "/v2/namespace/private/tags/list?n=10000",
           "protocol": "https:",
           "slashes": true,
           "auth": "USER:PASSWORD",
           "host": "REDACTED.dkr.ecr.ap-southeast-2.amazonaws.com",
           "port": null,
           "hostname": "REDACTED.dkr.ecr.ap-southeast-2.amazonaws.com",
           "hash": null,
           "search": "?n=10000",
           "pathname": "/v2/namespace/private/tags/list",
           "href": "https://REDACTED.dkr.ecr.ap-southeast-2.amazonaws.com/v2/namespace/private/tags/list?n=10000",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 405,
         "statusMessage": "Method Not Allowed",
         "headers": {
           "content-type": "application/json; charset=utf-8",
           "date": "Wed, 12 Jun 2019 03:48:40 GMT",
           "docker-distribution-api-version": "registry/2.0",
           "content-length": "164",
           "connection": "Close"
         },
         "body": {
           "errors": [
             {
               "code": "UNSUPPORTED",
               "message": "Invalid parameter at 'maxResults' failed to satisfy constraint: 'Member must have value less than or equal to 1000'"
             }
           ]
         },
         "message": "Response code 405 (Method Not Allowed)",
         "stack": "HTTPError: Response code 405 (Method Not Allowed)\n    at EventEmitter.emitter.on (/builds/user/repo/renovate-gitlab/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
¨```

**Comment by rarkins** [comment]
It sounds like we can either:
1. Look for hostname matching `dkr.ecr.*.amazonaws.com` and if found then change n=10000 to n=1000, or
2. Look for 405 responses, and check if `err.body && err.body.errors && err.body.errors.length && err.body.errors[0].message && err.body.errors[0].message.includes('Member must have value less than or equal to 1000')
