### ISSUE TITLE
Feature Request: Auto merge for repos without status checks, via timeout

### ISSUE THREAD

**Issue by jamesmmchugh** [renovatebot/renovate#3802]
More of a suggestion than request:

**What would you like Renovate to be able to do?**
Renovate won't auto-merge on repositories that have no status checks, as Renovate cannot be sure if open PRs truly have no status checks, or if a CI system etc. is yet to report the status check state.

**Describe the solution you'd like**
Looking at GitHubs API docs, i cannot see an obvious way to do this deterministically.

A non deterministic solution would be to provide a configuration option like `statusCheckTimeout` that specifies a min duration in time, from when the PR was created, after which status checks will be ignored by Renovate. With the value zero representing infinity (i.e. never ignore status checks).

Perhaps this is not the most elegant solution but it would give users more flexibility (at their own risk).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rarkins** [comment]
We prefer this to be explicit using `ignoreTests=true`
