### ISSUE TITLE
Support vcs type for private packages in composer.json

### ISSUE THREAD

**Issue by jessedobbelaere** [renovatebot/renovate#3811]
**What would you like Renovate to be able to do?**
We started using the Renovatebot docker container on our company's private Gitlab server. It work's great with our projects that use NPM. But our most important project is using PHP and we developed a lot of smaller packages that we use. 

Each package has it's own Gitlab repository. We tried a few solutions and what worked best is to release a version on git, then specify the package as following in `composer.json`:

```
    "require": {
		"companyname/php-toolbox": "1.2.0",
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "git@gitlab.companyname.io:companyname/php-toolbox.git"
        },
		...
	]
```

However, when scanning, Renovatebot prints out: 

```
 INFO: Dependency lookup failure: not found (repository=companyname/our-php-project, dependency=companyname/php-toolbox)
 INFO: Failed to look up dependency companyname/php-toolbox (repository=companyname/our-php-project, packageFile=composer.json, dependency=companyname/php-toolbox)
 INFO: Unsupported Packagist registry URL (repository=companyname/our-php-project)
       "regUrl": {"type": "vcs", "url": "git@gitlab.companyname.companyname/php-toolbox.git"}
```

By looking at the code in https://github.com/renovatebot/renovate/blob/master/lib/datasource/packagist/index.js#L250-L263 it looks like `vcs` is not a supported type.

**Describe the solution you'd like**
Add support for `vcs` php packages in composer.json if possible. We already pass an access token for Gitlab (with api scope) as `RENOVATE_TOKEN`.

More info:
 
* https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository
* https://barryvanveen.nl/blog/55-installing-a-private-package-with-composer

**Describe alternatives you've considered**
For now, we will just manually update those packages without renovatebot automation.

**Additional context**
/

**Comment by rarkins** [comment]
Are versions identified by tags within that repo? And is it the same GitLab server that Renovate runs against? Ie same credentials?

Finally, are there any alternative syntaxes that would work too, or only that exact one?

**Comment by jessedobbelaere** [comment]
Hi, yes, versions are just tags (1.0.1, 1.0.2, 1.0.3).
We use the same Gitlab server to host our projects, host our php package code repositories with git tags, and where Renovate runs on.

`vcs` is the recommended way to use some private php packages, e.g. https://pineco.de/hosting-private-laravel-packages-gitlab/ (without having to setup your own private registry)

Maybe Artifactory is a workaround but we haven't looked into that yet. Recently, packagist launched their [private packagist](https://packagist.com/agencies) but we haven't tried that and for security reasons, we like to keep our packages on Gitlab. We host our own private npm server though, but that was easy to configure in renovatebot thanks to `.npmrc` and a NPM token.

**Comment by xbenjii** [comment]
@rarkins I believe `git` is an alias to `vcs`.

**Comment by rarkins** [comment]
Option 1: we detect/handle VCS types specifically, e.g. GitHub and GitLab. Not sure we can easily do it except like in this case where it's the same server as the "endpoint" configured in Renovate.

Option 2: we have generic git capabilities and use `git ls-remote --tags ...`

For option 2, we need to solve:

1. How can Renovate know which package name is represented there? e.g. does it need to pluck the `composer.json` from the repo?

2. How to handle authentication? e.g. if we have a url of `git@gitlab.companyname.io:companyname/php-toolbox.git` then can we insert the personal access token we know into that URL? In GitLab's case, it looks like we need to know to convert that to URL like `git clone https://username:token@gitlab.com/user/repo.git`, meaning (a) we need to determine it's GitLab, and (b) we need to determine the username

**Comment by rarkins** [comment]
@jessedobbelaere can you think of any way to replicate this situation with a public GitLab account/repo? I would like to get it working with public repos first and then convert them to private to get the auth part working.

**Comment by rarkins** [comment]
It seems that composer itself also does some "detection" of github.com and others, and doesn't use raw git all the time. Ref: https://getcomposer.org/doc/05-repositories.md#git-alternatives
