### ISSUE TITLE
Feature Request: Partial Lockfile Maintenance

### ISSUE THREAD

**Issue by Crashthatch** [renovatebot/renovate#3817]
**What would you like Renovate to be able to do?**
Most of our repos have package.json set to allow minor updates (using ^), and we rely on renovate's lockfile maintenance to automatically accept any new in-range versions of dependencies if the build passes. However, often (weekly) a minor or patch change happens somewhere in open-source land for one of our (maybe transitive) dependencies which causes the lockfile maintenance build to fail (usually it's that the package hasn't followed semver properly, and has accidentally broken something in a patch update). This halts all future lockfile maintenance from occurring and ANY new versions of dependencies being pulled in (because the build keeps failing) until a developer investigates and takes action (usually by pinning the offending package to the exact version (no ^) that we had before the breaking change). Example in the "Additional Context" section below.

To make things worse, the lockfile maintenance PR usually continues to be updated by renovate so that by the time someone has a look, many many packages have been changed and it's not obvious which one caused the failure. 

It would be good if renovate could continue to update all OTHER packages (ones that do not cause failures) so that we remain relatively up to date, and one non-semver change in a single dependency does not completely stop lockfile maintenance from occurring.

**Describe the solution you'd like**
Unfortunately I don't really know how renovate can know which dependency caused the failure if several packages changed during the maintenance. 

1) Perhaps there could be an option to force "incremental lockfile maintenance" where it only tries to update a single dependency at a time (perhaps in parallel, with one build per dependency), and only merges the builds that succeed, skipping merging dependencies that caused the build to fail?

2) Or perhaps a binary search where if the initial maintenance build fails, it triggers 2 more builds, each with half the packages changed, and merges only the one that succeeds, and recurses down until only failing package remains? 

Perhaps you have better ideas?

**Describe alternatives you've considered**
See 1 and 2 above. 

**Additional context - An Example**
Example package.json:
```json
dependencies: {
   "depA": "^1.0.0",
   "depB": "^1.0.0"
}
```
And package-lock.json:
```json
dependencies: {
   "depA": "1.0.3",
   "depB": "1.0.3"
}
```

Now imagine that 1.0.4 of both depA and depB are released. depA@1.0.4 is fine, but depB@1.0.4 contains a breaking change which will be caught by my unit tests when we depend on it. The lockfile maintenance will try to update package-lock to: 
```json
dependencies: {
   "depA": "1.0.4",
   "depB": "1.0.4"
}
```
The build will fail because it contains the "broken" depB@1.0.4. Neither depA nor depB will be updated on master and the lockfile maintenance PR will remain red and broken until someone takes a look.

What I would like to happen is that another build happens with package-lock:
```json
dependencies: {
   "depA": "1.0.4",
   "depB": "1.0.3"
}
```
This will succeed because it does not contain the broken depB@1.0.4, and so will be merged to master.

**Comment by nihal9ns** [comment]
@rarkins Will a dependency that is stable ever break an app? Im not sure about that, may be no but there can be some exceptional cases where it would but such chances are really less. So a possible solution to this could be that we only increment the version if we know that it is stable?
