### ISSUE TITLE
"PR has been edited" claimed when no commits have been pushed

### ISSUE THREAD

**Issue by foolip** [renovatebot/renovate#3818]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
On these pull requests:
https://github.com/GoogleChromeLabs/confluence/pull/415
https://github.com/GoogleChromeLabs/confluence/pull/416
https://github.com/GoogleChromeLabs/confluence/pull/418

Renovate claims that "PR has been edited" and will not automerge, but no commits have been pushed to the branch.

**Did you see anything helpful in debug logs?**
I'm not able to find the job where the comment was initially posted because it's 3 days back, but https://renovatebot.com/dashboard#github/GoogleChromeLabs/confluence/68452930 does contain "PR has been edited". It doesn't say *why* the PR was considered edited.

**To Reproduce**
I don't know, perhaps cloning https://github.com/GoogleChromeLabs/confluence and doing the same setup would reproduce the problem. Not attempted.

**Expected behavior**
When "PR has been edited" is posted, the cause should be clear. The claimed cause "has received other commits" is not true for these PRs.

**Screenshots**
N/A

**Additional context**
I'm using Codecov which has posted comments right before the "PR has been edited" comment, but that doesn't seem to be the cause, as https://github.com/GoogleChromeLabs/confluence/pull/418 has no such comment.

**Comment by foolip** [comment]
It happened on https://github.com/GoogleChromeLabs/confluence/pull/419 too, well before the Codecov comment and before I had even looked at the PR.

**Comment by rarkins** [comment]
Sorry, this is related to a special rule to try to appease the Google CLA bot (it doesn't like if the Pull Request creator and git committer are different). I will work out a fix ASAP

**Comment by foolip** [comment]
Aha, I'm glad you knew the cause, because figuring that would have been frustrating to try reproducing in a fork :D

**Comment by rarkins** [comment]
I've had to add some new debug statements to work out what's going on. Here's the logic behind the fault:

1. Bots/Apps on GitHub do not get given "real" email addresses and cannot associate real ones, therefore they cannot sign commits
2. Instead, we use the "real" account of `@renovate-bot` (which is separate from the pseudo-user bot account of `@renovate[bot]` to make and sign commits
3. Google CLA bot does not approve a PR unless the git committer matches the PR creator, even if both have signed the CLA!
4. For Google orgs, we manually override the committer email back to the email GitHub assigns - `renovate[bot]@users.noreply.github.com` - which also happens to be an invalid email address according to the RFC

Now something else is going wrong. I suspect that GitHub's GraphQL interface may not be returning `renovate[bot]@users.noreply.github.com` when we query the PR, but have added a debug message now to check within the next hour or two

**Comment by rarkins** [comment]
Now my problem is no open PRs to check :)

**Comment by foolip** [comment]
Sorry, I merged them all manually. I can revert one, but unless I add some configuration I think that won't cause it to be recreated?

**Comment by rarkins** [comment]
It’s ok. I’ve put a watch on that repo and will keep an eye out on others

**Comment by foolip** [comment]
Alright, I'll check back here if/when there's another PR that unexpectedly isn't merged, and then *not* merge it manually so you can use it for debugging.

**Comment by Jamesking56** [comment]
I'm also getting the same issue on GitLab, using Renovate Docker with my own GitLab user for the bot.

**Comment by rarkins** [comment]
@Jamesking56 in your case, you need to configure `gitAuthor` in your bot config to match the account name/email of the bot

**Comment by rarkins** [comment]
This should now be resolved for the Google accounts on the GitHub app. Sad to say it was simply a one character typo in the email address.

**Comment by foolip** [comment]
Thanks @rarkins for getting to the bottom of this!
