### ISSUE TITLE
Cannot resolve versions of SBT dependencies with variables

### ISSUE THREAD

**Issue by daniel-shuy** [renovatebot/renovate#3827]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
When the SBT build file contains a dependency with its version set by a variable, eg.
```scala
val sbtReleaseVersion = "1.0.11"
// ...
"com.github.gseitz" % "sbt-release" % sbtReleaseVersion
```
Renovate detects the version as `null`.

See daniel-shuy/scripted-scalatest-sbt-plugin#10 for an example.

**Did you see anything helpful in debug logs?**
No

**To Reproduce**

1.  Create repository with `build.sbt`
2.  Configure `build.sbt` with:
```scala
val sbtReleaseVersion = "1.0.11"
addSbtPlugin("com.github.gseitz" % "sbt-release" % sbtReleaseVersion)
```

**Expected behavior**
Renovate should detect dependency versions set by variables.

**Additional context**
May want to refer to [scala-steward](https://github.com/fthomas/scala-steward) to see how they are handling it.

**Comment by rarkins** [comment]
@zharinov can we support this?

**Comment by zharinov** [comment]
Hi folks, will fix it asap

**Comment by zharinov** [comment]
It wont support lexical scopes well, but I think it will be good enough

**Comment by daniel-shuy** [comment]
Wow that was fast, thanks! How can I re-generate the PR?

**Comment by rarkins** [comment]
@daniel-shuy I'll push it live into the hosted app soon and will let you know
