### ISSUE TITLE
semanticCommitType not applied correctly

### ISSUE THREAD

**Issue by Roms1383** [renovatebot/renovate#3854]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Expect commit message from Renovate to contain emoji prefix as configured, which wasn't applied correctly

**Did you see anything helpful in debug logs?**
Job ID [#70208446](https://renovatebot.com/dashboard#github/Roms1383/semantic-release-kroms/70208446) : project config being correctly used from `.renovaterc`.

**To Reproduce**

1.  Create repository with `.renovaterc` : 
```json
{
  ...,
  "semanticCommitType": ":arrow_up:",
  "semanticCommitScope": null,
  "packageRules": [
    {
      "updateTypes": [
        "lockFileMaintenance",
        "pin"
      ],
      "semanticCommitType": ":pushpin:"
    },
    {
      "updateTypes": [
        "rollback"
      ],
      "semanticCommitType": ":arrow_down:"
    },
    {
      "updateTypes": [
        "digest",
        "bump"
      ],
      "semanticCommitType": ":bookmark:"
    }
  ]
}
```
2.  Wait next PR opened by RenovateBot to upgrade dependencies

**Expected behavior**
e.g. with PR [Update dependency @commitlint/cli to v8](https://github.com/Roms1383/generator-kroms/pull/12)
I would have expected the commit message to be :
`⬆️Update dependency @commitlint/cli to v8`
Instead I got :
`Update dependency @commitlint/cli to v8`

**Screenshots**
<img width="1024" alt="Screen Shot 2562-06-01 at 14 15 13" src="https://user-images.githubusercontent.com/21016014/58745189-ecc7c300-8477-11e9-8854-7e0dd6b62d52.png">
or directly [here](https://github.com/Roms1383/generator-kroms/pull/12/commits)

**Additional context**
I heavily rely on these `semanticCommitType` to be applied correctly, as I use a special preset for [semantic-release](https://github.com/semantic-release/semantic-release) based on [gitmoji](https://gitmoji.carloscuesta.me).

**Comment by rarkins** [comment]
Are you extending any of Renovate’s other presets?

**Comment by Roms1383** [comment]
No, I just use this [.renovaterc](https://github.com/Roms1383/generator-kroms/blob/master/.renovaterc) only.

**Comment by Roms1383** [comment]
It follows our former discussion [here](https://github.com/renovatebot/presets/issues/122) :)

**Comment by rarkins** [comment]
Can you replicate this in a public repo with similar config? That will make it a lot faster to debug

**Comment by Roms1383** [comment]
Yes : https://github.com/Roms1383/test-renovate

**Comment by Roms1383** [comment]
I also added you as a collaborator on the repo in case you want to process some additional tests 👍

**Comment by rarkins** [comment]
I worked out the problem, but perhaps it now uncovers a new one. The ⬆️ symbol is not being translated in the title in my test repo:
![image](https://user-images.githubusercontent.com/6311784/58745928-36a0b100-8458-11e9-9bad-0e71266cb2c0.png)

Is that expected?

**Comment by Roms1383** [comment]
Yes => `:arrow_up:`

**Comment by Roms1383** [comment]
The only thing that matters for `semantic-release` is `:arrow_up:` (or other emoji code), then usually Github display it with a nice symbol like ⬆️ (which is just formatted on display)

**Comment by rarkins** [comment]
Strange thing is that GitHub isn't formatting it nicely for me when I test.

Anyway, the solution is to add this config: `"semanticCommits": true`. I also released a patch [18.7.2](https://github.com/renovatebot/renovate/releases/tag/18.7.2) that makes sure you don't end up with two semicolons in a row.

**Comment by Roms1383** [comment]
That's awesome, thanks !

**Comment by Roms1383** [comment]
One last thing @rarkins : can I delete the [test repository](https://github.com/Roms1383/test-renovate) ?

**Comment by rarkins** [comment]
Yes go ahead
