### ISSUE TITLE
rangeStrategy=cap

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3861]
**What would you like Renovate to be able to do?**

Support a new `rangeStrategy` called "cap" whose purpose is retain ranges but to make sure they have a "cap" (ceiling/maximum).

**Describe the solution you'd like**

Renovate should determine if the current range is capped or uncapped, and cap it if necessary. For example if the current range is `^1.0.0` then it can be capped by converting that range to `^1.0.0 <=1.2.0` (assuming `1.2.0` is the latest version).

One way to approach this would be these steps:
- If the currentValue is a range, find the highest existing version that satisfies it
- Increment that highest existing version by the minimum possible (e.g. patch) and test if the incremented version also satisfies the current range
- If it satisfies it, it means we need to cap and can add `<=` or equivalent to the range
- Double check make sure the incremented version doesn't satisfy the new capped range. If it does, we want to raise a warning because we have an edge case.

I think we can start with `npm`, but `maven` and `ruby` versioning are also important.

**Comment by mrkamel** [comment]
am i right that the `cap` strategy would solve https://github.com/renovatebot/renovate/discussions/13347 as well?!

**Comment by rarkins** [comment]
No, it's solving a different problem
