### ISSUE TITLE
Renovate autoclosing and creating PR's out of schedule.

### ISSUE THREAD

**Issue by alekhrycaiko** [renovatebot/renovate#3867]
**What Renovate type are you using?**
Renovate GitHub App.

**Describe the bug**
Renovatebot decided to open a PR for a package in order to pin versions. The schedule I've setup is for after 10am and 5pm on wednesday - although it's Sunday now in UTC. In addition, it decided to autoclose a number of PR's at the same time. 

**Did you see anything helpful in debug logs?**

Nothing too particular. I've noticed that there is no schedule defined in the logs for `js-cookie` - but other steps have a schedule defined. Why this is the case is unclear to me. 
e.g. 

```
DEBUG: Checking if PR has been edited(dependencies=["@types/js-cookie"], branch="renovate/pin-dependencies")
DEBUG: Checking schedule(, null)(dependencies=["@types/js-cookie"], branch="renovate/pin-dependencies")
DEBUG: No schedule defined
```

**Expected behavior**
- Nothing should occur on Sunday utc.

**Comment by rarkins** [comment]
Can you paste your config?

Currently autoclosing can happen because it's kind of a separate routine that's done right at the end - making sure to clean up after itself. Do you think that the ones it autoclosed were *wrong*, or just preferred they had remained open?

**Comment by alekhrycaiko** [comment]
I don't believe I've specified anything in my current config that should warrant PR's being closed. However the PR's were rather old and opened on a much different `renovate.json` schema. We've been having some issues with renovate since our latest schema config update - which is a bit of a smell. I can see that the old PR's were never updated to match the current renovate schema/rules.  Should I expect that old PR's are updated with new configuration rules? Would renovate clean these up now that the configurations don't match? 

config: 
```
{
  "extends": ["config:base", "docker:disable"],
  "vulnerabilityAlerts": {
    "labels": ["security"],
    "assignees": ["@alekhrycaiko"]
  },
  "packageRules": [
    {
      "packagePatterns": "^[a-k]",
      "groupName": ["a-k packages python"],
      "languages": ["python"]
    },
    {
      "excludePackagePatterns": "^[a-k]",
      "groupName": ["other packages python"],
      "languages": ["python"]
    },
    {
      "packagePatterns": "^[a-k]",
      "groupName": ["a-k packages javascript"],
      "languages": ["javascript"]
    },
    {
      "excludePackagePatterns": "^[a-k]",
      "groupName": ["other packages javascript"],
      "languages": ["javascript"]
    }
  ],
  "ignoreDeps": ["pylibmc", "rq"],
  "schedule": ["after 10am and before 3pm on wednesday"]
}
```

**Comment by rarkins** [comment]
Is Renovate honouring the schedule in general? i.e. you haven't seen any more cases of opening or closing out of schedule?

Please log into https://renovatebot.com/dashboard and see if you can still locate the job log for when this occurred, and tell me the job ID. If it's too late (only last 3 days are shown in the dashboard) then please let me know the repo name and timestamp according to GitHub.

**Comment by rarkins** [comment]
Re: cleaning up, Renovate should attempt to do that no matter what the schedules. It's essentially just a final sweep that does, "Do any Renovate branches exist that shouldn't? If so then autoclose them". I would expect autoclosing would happen the first time Renovate successfully run after any major config update. If you're using schedules, you should see all PRs closed that need to (regardless of schedule), but their replacements *not* opened at the same time unless the schedule is met.

**Comment by alekhrycaiko** [comment]
the job is: # 70200733 where I've found the log below. I believe this is where the creation occurred. 
```
DEBUG: Creating PR(dependencies=["@types/js-cookie"], branch="renovate/pin-dependencies")
{
  "prTitle": "Pin dependency @types/js-cookie to 2.2.2"
}
DEBUG: Creating PR(dependencies=["@types/js-cookie"], branch="renovate/pin-dependencies")
{
  "title": "Pin dependency @types/js-cookie to 2.2.2",
  "head": "sokanu:renovate/pin-dependencies",
  "base": "master"
}
DEBUG: PR created(dependencies=["@types/js-cookie"], branch="renovate/pin-dependencies")
{
  "pr": 1410
}
```
There have been no more anomalies so far with renovate, nothing has been closed or opened. I also have not merged in anything related to renovate as well.

**Comment by alekhrycaiko** [comment]
Regarding your comment about closing, the strange thing here is that our latest `renovate.json` change was around a month ago. Since that last change, we haven't had any activity from RenovateBot besides this PR closing/creation issue occurring out of schedule.

**Comment by rarkins** [comment]
Confirming that pin PRs being out of schedule is intentional: https://github.com/renovatebot/renovate/blob/6b700eb3e89976f779fc788b72486b0a2d86c863/lib/workers/repository/updates/generate.js#L260-L263

I only half recall this decision from long ago, but I think it was mostly because it's meant to be a "no op" PR (no effective change to what's installed). I'm fine to reconsider it.

Additionally, for some reason it looks like 2nd of June was the first time Renovate ran on the repo for a long time. Usually this happens because Renovate thinks the repo has been disabled from reason, so it ceases running on usual schedules and just checks it periodically.

**Comment by alekhrycaiko** [comment]
Probably a reconsideration here is a good idea. The current behaviour is a bit confusing as a consumer when the schedule dictates that PR's shouldn't be opening outside my schedule.
Strange, I'm not sure why the 2nd point would occur... but hopefully it continues running. If I come across more problems, I'll file a separate issue.

**Comment by rarkins** [comment]
By the way if you're using scheduling, I recommend you consider enabling Renovate's Master Issue functionality so you get visibility. Details: https://renovatebot.com/blog/master-issue
