### ISSUE TITLE
Incorrect major version resolution for org.clojure:clojurescript 0.0-1552

### ISSUE THREAD

**Issue by mkarp** [renovatebot/renovate#3876]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Hey there! 

Renovate keeps opening pull requests to update `org.clojure:clojurescript` despite us having the latest version already. Latest stable version is `1.10.520`. Renovate would keep opening pull requests for old prerelease versions (for example, `0.0-1552`).

<img width="789" alt="Screenshot 2019-06-03 at 18 02 02" src="https://user-images.githubusercontent.com/318902/58816474-e5e0b200-8629-11e9-90f1-b59e6c0be985.png">

What's interesting is that in the column "Change" the version number is displayed correctly `0.0-1552`, while in the pull request title it says "Update to v1552".

**Did you see anything helpful in debug logs?**
I'm seeing that major version is incorrectly resolved:

```
...
              {
                "fromVersion": "1.10.520",
                "toVersion": "0.0-1552",
                "newValue": "0.0-1552",
                "newMajor": 1552,
                "newMinor": 0,
                "updateType": "major",
                "isSingleVersion": true
              },
```

**To Reproduce**

1.  Create repository with `deps.edn`:

```clojure
{:deps {org.clojure/clojurescript {:mvn/version "1.10.520"}}
```

2.  Configure Renovate to use deps-edn manager:

```json
{
  "enabledManagers": [
    "deps-edn"
  ]
}
```

**Expected behavior**
I would expect for Renovate Bot not to open pull requests trying to update from version of a dependency like `1.10.520` to a version like `0.0-1552`.

**Additional context**
I've tried comparing the version with semver and it throws an exception saying that `0.0-1552` is an invalid version number. Unfortunately early ClojureScript versions didn't follow semver rules.

I would appreciate if a special case can be added such that major version for `0.0-1552` would be `0`.

**Comment by rarkins** [comment]
@zharinov what would be the best way for us to handle this?

**Comment by rarkins** [comment]
@mkarp 	this package rule should work around the problem for you:

```
  "packageRules": [{
    "packageNames": ["org.clojure:clojurescript"],
    "allowedVersions": ">= 1.7.10"
}]
```

@zharinov can you look into this as to whether we can fix it automatically at the root cause? I'm also confused why we call it "v3308" too.

**Comment by zharinov** [comment]
Hey folks, I'll take a look today on how to fix it

**Comment by mkarp** [comment]
Thank you all!

**Comment by rarkins** [comment]
@mkarp the root cause fix should be live in the app within 5 minutes and after that no package rule should be necessary
