### ISSUE TITLE
PR shouldn't be named after @types page name

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#3887]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
If a PR contains both `@types/package` and `package`, it is named "Update dependency @types/package". This gives a false sense of security that the PR is safe to merge, and can make the viewer think Renovate will automerge the PR if configured, but it won't.

**Expected behavior**
The PR should be named "Update dependency 'package'"

**Additional context**
https://github.com/sourcegraph/sourcegraph/pull/4296

**Comment by rarkins** [comment]
Agreed. Pretty sure it used to work how you describe too, because I remember adding a special sort just for this case at the time I added the implicit grouping.

**Comment by rarkins** [comment]
Unfortunately, I was not able to reproduce on the first try, so there must be some factor I'm not considering.

**Comment by felixfbecker** [comment]
Interesting, it's been happening pretty consistently for us 🤔 
Maybe different update types? We pin @types/ packages but bump others

**Comment by rarkins** [comment]
I tried extending your sourcegraph config at first but it didn't work as it's private. Perhaps can you copy/paste the relevant config for me so that I can replicate it? Then finally if I still can't replicate with a dummy repo then I'll fork sourcegraph/sourcegraph and wait for one.

FYI here's my replication repo so far: https://github.com/renovate-tests/types1/pull/2

**Comment by felixfbecker** [comment]
Yeah it's private cause there are access tokens in it. Here's a censored version:

```json
{
  "$schema": "http://json.schemastore.org/renovate",
  "extends": ["config:base"],
  "timezone": "America/Los_Angeles",
  "schedule": ["on the 1st through 7th day of the month"],
  "prBodyDefinitions": {
    "Sourcegraph": "REDACTED"
  },
  "prBodyColumns": ["Package", "Type", "Update", "New value", "References", "Sourcegraph"],
  "masterIssue": true,
  "updateNotScheduled": true,
  "prCreation": "immediate",
  "prHourlyLimit": 10,
  "prConcurrentLimit": 50,
  "rangeStrategy": "bump",
  "postUpdateOptions": ["yarnDedupeFewer"],
  "assignees": ["felixfbecker"],
  "golang": {
    "assignees": ["slimsag"],
    "masterIssueApproval": true
  },
  "docker": {
    "assignees": [],
    "pinDigests": true
  },
  "packageRules": [
    {
      "packagePatterns": ["^@sourcegraph/"],
      "rangeStrategy": "bump",
      "schedule": []
    },
    {
      "packageNames": ["sourcegraph"],
      "rangeStrategy": "bump",
      "schedule": [],
      "automerge": true
    },
    {
      "packagePatterns": ["^@types/"],
      "rangeStrategy": "pin",
      "assignees": [],
      "automerge": true
    },
    {
      "packageNames": ["@sourcegraph/codeintellify"],
      "assignees": ["felixfbecker", "ijsnow"]
    },
    {
      "packageNames": ["@sourcegraph/basic-code-intel"],
      "assignees": ["chrismwendt"]
    },
    {
      "packagePatterns": ["^golang.org/x/"],
      "masterIssueApproval": false,
      "assignees": [],
      "automerge": true
    },
    {
      "packagePatterns": ["prettier"],
      "groupName": "prettier"
    },
    {
      "packagePatterns": ["prettier", "lint", "^@sourcegraph/tsconfig$"],
      "depTypeList": ["devDependencies"],
      "automerge": true
    },
    {
      "packagePatterns": ["^vscode-"],
      "groupName": "vscode"
    }
  ]
}
```

**Comment by rarkins** [comment]
Full config did not manage to reproduce the problem so now onto a full fork and config.. stay tuned

**Comment by rarkins** [comment]
Success reproducing: https://github.com/renovate-tests/sourcegraph/pull/18
