### ISSUE TITLE
Renovate bot doesn't handle "strip_prefix" argument for Bazel updates

### ISSUE THREAD

**Issue by achew22** [renovatebot/renovate#3888]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

When trying to update the dependency on `com_google_protobuf` in Bazel projects, renovate bot correctly updates most, but not all of the required fields. For example: in https://github.com/bazelbuild/rules_k8s/pull/356, it updated the `sha256`, and the `url`, but the `strip_prefix` needs to be updated as well.

`strip_prefix` removes an artifact of the Github tagging system where the zip that represents the tag starts with an inner directory of `${PROJECT_NAME}_${TAG_NAME}` which needs to be removed.

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

**To Reproduce**

1.  Create repository with the following `WORKSPACE` file:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")

http_archive(
    name = "com_google_protobuf",
    sha256 = "f1748989842b46fa208b2a6e4e2785133cfcc3e4d43c17fecb023733f0f5443f",
    strip_prefix = "protobuf-3.7.1",
    url = "https://github.com/google/protobuf/archive/v3.7.1.tar.gz",
)
```

2.  Configure renovate to run it

**Expected behavior**
This PR should have been generated instead

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")

http_archive(
    name = "com_google_protobuf",
    sha256 = "03d2e5ef101aee4c2f6ddcf145d2a04926b9c19e7086944df3842b1b8502b783",
    strip_prefix = "protobuf-3.8.0",
    url = "https://github.com/google/protobuf/archive/v3.8.0.tar.gz",
)
```

https://github.com/bazelbuild/rules_k8s/pull/357

**Additional context**
Happy to provide more information if you need it.

Thanks so much!

**Comment by achew22** [comment]
A little more context, this rule really only applies to Github hosted projects. On github,In the case of a commit, it would be the commit hash and in the case of a tag it would be the tag name. Thanks to @alex1545 for pointing that out.

**Comment by rarkins** [comment]
Fixed in https://github.com/renovatebot/renovate/commit/522ecc39280045088c30508e1c308ba930ddfcef
