### ISSUE TITLE
JS-based build.gradle parser

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3898]
Example files:
- https://github.com/Jasig/uPortal/blob/master/build.gradle
- https://github.com/Jasig/NotificationPortlet/blob/master/build.gradle
- https://github.com/bagage/gradle-template/blob/master/build.gradle
- https://github.com/bagage/gradle-template/blob/master/module1/build.gradle
- https://github.com/apereo/cas/blob/master/build.gradle

**Comment by viceice** [comment]
Isn't this a duplicate of #3608
