### ISSUE TITLE
Syntax error in update to Bazel WORKSPACE

### ISSUE THREAD

**Issue by rohansingh** [renovatebot/renovate#3902]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Pull request to update an `http_archive` rule in `WORKSPACE` has a syntax error:

```
 WORKSPACE | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/WORKSPACE b/WORKSPACE
index 14ccde967d..d17fe2a7a5 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -397,6 +397,9 @@ kind_cluster(
 http_archive(
     name = "tilt_linux_x86_64",
     build_file_content = "exports_files(['tilt'])",
+    sha256 = "7b9dd86b6de03830d2dea77e8a0e6d4744d21b53b9ae74adb965345a817e42a2",
+    urls = ["https://github.com/windmilleng/tilt/releases/download/v0.8.8/tilt.0.7.13.linux.x86_64.tar.gz"],
+)",
     sha256 = "9139e76faa40c559baabcf5a9bed6c89b6554532e9dd95abde9a0229827fea5c",
     urls = ["https://github.com/windmilleng/tilt/releases/download/v0.7.13/tilt.0.7.13.linux.x86_64.tar.gz"],
 )
```

It looks like the underlying issue is that new lines are being added, but the old lines are not being deleted.

**Did you see anything helpful in debug logs?**
Not in particular.

**To Reproduce**
I haven't attempted to reproduce this in a clean room. But we are seeing it with this and another similar `http_archive` rule.

**Expected behavior**
Expected the generated patch to be syntactically valid.

**Comment by rarkins** [comment]
If you are able to create a public repo to recreate the problem, it will definitely help time to resolve. Otherwise I'll try to reproduce myself soon.
