### ISSUE TITLE
Dependency lookup failure for SBT plugins published to Maven Central

### ISSUE THREAD

**Issue by daniel-shuy** [renovatebot/renovate#3907]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Renovate fails to lookup SBT plugins that were published to Maven Central, eg.
```scala
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
```

See daniel-shuy/sbt-release-mdoc#10 for an example

**Did you see anything helpful in debug logs?**
SBT plugins published to Maven have a `_<scala version>_<sbt version>` suffix, eg. [sbt-scalafmt_2.12_1.0](https://repo.maven.apache.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/).

The logs indicate that Renovate is looking for the SBT plugins in Maven Central without the suffix, eg.
`DEBUG: Url not found https://repo.maven.apache.org/maven2/org.scalameta/sbt-scalafmt`

**To Reproduce**

1.  Create repository with `project/plugins.sbt`
2.  Configure `project/plugins.sbt` with:
```scala
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
```

**Expected behavior**
Renovate should be able to lookup SBT plugins that were published to Maven Central

**Additional context**
My guess is that Renovate is currently only searching for dependencies in Maven with the version suffix if the double percent (`%%`) symbol is used.

**Comment by rarkins** [comment]
@zharinov is this something we can resolve without major refactoring?

**Comment by zharinov** [comment]
@rarkins I think, yes. Need to see debug messages

**Comment by daniel-shuy** [comment]
Thanks again @zharinov, really appreciate your contributions
