### ISSUE TITLE
CLI : enable onboarding-config parameter

### ISSUE THREAD

**Issue by jgarec** [renovatebot/renovate#3908]
**What would you like Renovate to be able to do?**
Specify content of onboardingConfig on command line instead of only in config.js

**Describe the solution you'd like**
Allow this parameter to be set on command line

**Describe alternatives you've considered**
enable `--onboarding-config` parameter

**Additional context**
I tried to modify onboardingConfig in definitions.js but it doesn't work (cli: true) and run renovate with : 
`--onboarding-config={\"extends\":[\"my_preset_package\"]}`

but it is always considered as a string parameter (DEBUG LOG): 
`"onboardingConfig": "{\"extends\":[\"my_preset_package\"]}",`

Do you think it's an issue ? 
I also tried to set another `<object>` parameter like `--js` and this is the same result.

**Comment by rarkins** [comment]
Which OS are you using?

**Comment by jgarec** [comment]
Hi,

Windows 10 / renovate 18.10.5

**Comment by jgarec** [comment]
Does it make sense to you if we add an "object" function here to parse this type of argument ?
```js
const coersions = {
        boolean: val => {
            if (val === 'true' || val === '')
                return true;
            if (val === 'false')
                return false;
            throw new Error("Invalid boolean value: expected 'true' or 'false', but got '" +
                val +
                "'");
        },
        array: val => {
            if (val === '') {
                return [];
            }
            try {
                //console.log(val)
                return JSON.parse(val);
            }
            catch (err) {
                return val.split(',').map(el => el.trim());
            }
        },
        object: val => {
            try {
                return JSON.parse(val);
            }
            catch (err) {
                throw new Error(
                    "Invalid JSON value: '" +
                      val +
                      "'"
                );
            }
        },
        string: val => val,
        integer: parseInt,
    };
```

I've made a test to check if it works : 
`--js="{\"foo\": \"bar\"}`: ✔️
`--js="{foo: bar}` : 🛑
```
FATAL: Fatal error: Invalid JSON value: '{foo: bar}'
       "err": {
         "message": "Invalid JSON value: '{foo: bar}'",
```
