### ISSUE TITLE
Question: Monorepo setup with full automation (e.g. npm publish on CI), possible endless PR loop?

### ISSUE THREAD

**Issue by tunnckoCore** [renovatebot/renovate#3915]
I'm not following the template, because it's a question and I'm not sure what category is that.

---

So. Let's say you have a monorepo setup and full automation on it, like semantic-release and such - meaning that you follow conventional commits and create GitHub releases with some GitHub App or Lerna, and you publish new versions from the CI. In addition, you may also have `automerge` enabled. 

1. You have tons of packages in monorepo
2. Renovate raise a PR to update deps of one package (e.g. `foo`)
3. Everything is green in that PR, so automerged successfuly
4. When it's merged it triggers a new build on master and after everything is green again on the CI, it then publishes new version from the CI
5. So, Renovate will see the new version of `foo` package and will raise new PR to update it in few packages (`bar`, `qux` and `zaz`), then points 2-4 are repeated and PR is merged again.
6. From the CI, new versions (of `bar`, `qux` and `zaz`) are published, so Renovate will raise couple new PRs
7. And so on.

Does Renovate handle that so it won't jump into endless raising of PRs for updates? If it not works and the behaving is what I'm assuming, is there some configuration approach to avoid that? Also, is there some way to detect recursion?

I'm also raising this issue so I can back to it when and if that happens.

/cc @rarkins

**Comment by tunnckoCore** [comment]
By the way, I was always thinking about that. Even without monorepo setup, but normal workflow with separate repos in org.

**Comment by tunnckoCore** [comment]
The (real) use case: Thinking to move as much as possible of my packages in to a monorepo, where I will have a build step which bundles are dependencies, so all of them will be in `devDependency` field and will configure the Renovate to use `fix` conventional commits type, so I can auto-publish new versions from the CI when my deps are updated.

**Comment by rarkins** [comment]
By default with lerna and yarn workspaces, Renovate won’t update versions of any internal packages within other packages. Shouldn’t that stop it from even starting, assuming you haven’t rolled your own monorepo structure?

**Comment by tunnckoCore** [comment]
Oh cool, so I'll see. :)

> assuming you haven’t rolled your own monorepo structure?

Nope.

**Comment by tunnckoCore** [comment]
> Renovate won’t update versions of any internal packages within other packages.

Hm. So it won't do the (5) step? Interesting. So it won't raise PR when `foo` is upgraded to v2 but in `bar` and `qux` is used v1? Interesting.

**Comment by rarkins** [comment]
If `foo` is an internal package (e.g. covered by the package globs of lerna or Yarn workspaces) then its version will be ignored in every other package within the repo (e.g. in `bar`). i.e. it's up to you to update the versions of cross-dependencies within a monorepo. This was pretty much the first lerna feature people asked for and nobody's ever asked for a change to that behaviour so I haven't thought about it.

**Comment by tunnckoCore** [comment]
Oooh yea yea, right. I just forgot that Lerna handles that part and updates them. Cool.
