### ISSUE TITLE
Create alpine based docker images

### ISSUE THREAD

**Issue by jonathanmorley** [renovatebot/renovate#3916]
**What would you like Renovate to be able to do?**
I would like to be able to run renovate from docker without using a 1GB ubuntu-based image

**Describe the solution you'd like**
Ideally, an alpine-based docker image should be created and pushed to dockerhub for every release, alongside the existing ubuntu-based one

**Comment by rarkins** [comment]
It would be too challenging to get all the binaries we need working with Alpine. But importantly: 80%+ of the space you see used is from the binaries we bundle and not from Ubuntu 18.04, which is already quite slim. Alpine might only save you 10-20% maximum.

What we do plan to support instead is publishing a Renovate image that doesn't include any third party binaries and instead Renovate will dynamically pull down sister containers for any binaries it needs.
