### ISSUE TITLE
Dependency Prioritization 

### ISSUE THREAD

**Issue by chriscantu** [renovatebot/renovate#3917]
**What would you like Renovate to be able to do?**
**AS A** Pro (Enterprise) Renovate User
**I WANT TO** be able to prioritize some dependencies over others 
**SO THAT** I can ensure critical dependencies are updated first

**Describe the solution you'd like**
For large scale applications with lots of dependencies, we would like the ability to configure prioritization for certain dependencies which are more mission critical. In the case where a repo has set a limit for the # of PRs that can be submitted, renovate would close a lower priority PR when a more important is queued.  Also, Renovate should apply a label indicating the configured priority assigned to the dependency so it's clear for the maintainers which updates are more important. 

**Describe alternatives you've considered**
To date, we apply labels specifying our priority based on the "packagePatterns" .  However if our queue is full, new higher priority PRs are not submitted.  We want to be able to see those high priority updates as soon as possible. 

**Additional context**
N/A

**Comment by rarkins** [comment]
Something else we need to now decide: 

Presumably it makes sense to name it like `prPriority` and make it a number. But what should be the default? No number, or a "mid" range number. Having a mid number would all you to not only prioritise but also de-prioritise certain dependencies without needing to add a priority to all.

So I'm thinking either a 1-9 scale with default 5, or set the default to 0 and let people configure positive or negative numbers.

**Comment by qswitcher** [comment]
Personally I prefer the latter of defaulting to `0` and allowing arbitrary positive and negative numbers for maximum flexibility.

**Comment by herb-ng** [comment]
hello, I work with @chriscantu and I will be working on this.

**Comment by rarkins** [comment]
@herb-ng that's awesome. Summing up what was discussed here:

- New config option `prPriority` that is of type 'integer' and defaults to 0
- Disable CLI and env for this option (in its config definition)
- Use `prPriority` as the first sorting criteria in https://github.com/renovatebot/renovate/blob/master/lib/workers/repository/process/sort.js

Note: we don't currently have any existing config options with type `integer` so there's a chance there may need to be some code added just for it.
