### ISSUE TITLE
Renovate doesn't create MRs after initial Onboarding MR is merged on Gitlab

### ISSUE THREAD

**Issue by Xenonym** [renovatebot/renovate#3918]
**What Renovate type are you using?**
Renovate Gitlab App.

**Describe the bug**
After we have added Renovate to our repository from the Dashboard, Renovate creates an onboarding MR. However, it does not create any more MRs after we have merged the onboarding MR even after a day.

**Did you see anything helpful in debug logs?**
The initial onboarding MR job was `#72202298`. No other jobs have been scheduled after this one.

**Expected behavior**
MRs should be created to update packages.

**Additional context**
It is a private repository, if that is relevant.

**Comment by rarkins** [comment]
Hi, your repo was stuck with status "onboarding" in our backend DB which meant it was only scheduled for daily checks. It would have been picked up eventually today but I enqueued a manual job just now and you should now see it alive and in action.

**Comment by Xenonym** [comment]
It works now, thank you so much!
