### ISSUE TITLE
[bug] empty Composer lock file maintenance PRs if no changes required 

### ISSUE THREAD

**Issue by evilebottnawi** [renovatebot/renovate#3919]
**What Renovate type are you using?**

Renovate CLI

**Describe the bug**

Renovate creates MR with empty lock files when try to update them (npm/composer). This happens only when lock files already updated (for example you can manually update deps and lock files no need update)

**Did you see anything helpful in debug logs?**
Nothing bad in logs (CLI), only strange line:
```
INFO: empty displayFrom/displayTo (repository=itgalaxy/insteria, branch=renovate/lock-file-maintenance
```
But i think it is unrelated.

**To Reproduce**

1. Create repository with any deps in `package.json` and `composer.json`
2. Install deps and generate lock files (both tools automatically generate lock files by default). 
3.  Put configuration:
```
{
  "extends": [
    "config:base",
    ":maintainLockFilesWeekly",
    ":semanticCommitTypeAll(chore)"
  ]
}
```
4. Run Renovate CLI with any `--schedule` value.

**Expected behavior**
Do not create MR if nothing update in lock files.

**Screenshots**
![FireShot Capture 006 - chore(deps)_ lock file maintenance (!3245) · Merge Requests · itgalax_ - gitlab itgalaxy company](https://user-images.githubusercontent.com/4567934/59277008-0c28d200-8c68-11e9-9e29-f29e90af6eda.png)

**Additional context**

We use self-hosted gitlab

**Comment by rarkins** [comment]
Unfortunately I am unable to reproduce this. Repo: https://gitlab.com/renovate-tests/lock1

If you can reproduce the problem in a public github.com or gitlab.com then I can take another look

**Comment by evilebottnawi** [comment]
thanks for answer, strange, i will update renovate to latest version (maybe bug in previous versions) and will try to reproduce problem in near future for more feedback

**Comment by evilebottnawi** [comment]
Can't reproduce with latest version (18.17.1), closed
