### ISSUE TITLE
package-diffs doesn't work with npm scoped packages

### ISSUE THREAD

**Issue by teppeis** [renovatebot/renovate#3920]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

https://renovatebot.com/package-diff?name=@types%2fpino&from=5.8.7&to=5.8.8 doesn't return the response.

PR: https://github.com/teppeis/duck/pull/106
Link before redirect: https://renovatebot.com/diffs/npm/@types%2fpino/5.8.7/5.8.8

**Screenshots**

<img width="703" alt="スクリーンショット 2019-06-12 9 22 30" src="https://user-images.githubusercontent.com/26476/59315184-a4b86400-8cf3-11e9-9a9c-a937422507d5.png">

**Comment by teppeis** [comment]
FYI: 
- npmfs works: https://npmfs.com/compare/@types/pino/5.8.7/5.8.8/
- intrinsic doesn't work: https://diff.intrinsic.com/@types/pino/5.8.7/5.8.8

**Comment by rarkins** [comment]
In our case it could be linked to the lack of `package` dir too. I don't suppose you know anything about that structure of npm tarballs?

**Comment by rarkins** [comment]
Now fixed, thanks for raising the issue

**Comment by teppeis** [comment]
@rarkins thanks!
