### ISSUE TITLE
Renovate not running jobs on newly installed gitlab repos

### ISSUE THREAD

**Issue by ext** [renovatebot/renovate#3926]
**What Renovate type are you using?**
Renovate GitLab App

**Describe the bug**
RenovateBot doesn't seem to run anything since initial onboarding PR, trying to reconfigure doesn't help either.

Installing/uninstalling adds/removes the @renovate-bot user as developer but not webhook is added. Using devtool on dashboard shows requests to `https://v1.renovateapi.com/gitlab/repos/.../webhooks` giving 404.

**Did you see anything helpful in debug logs?**
Dashboard lists project but no jobs, the initial onboarding job disappeared.

**Expected behavior**
Renovatebot should start running jobs.

**Additional context**

I first tried renovate on a single repo in organization. Worked fine.

When trying to add it to others the first additional one installed properly, the rest got onboarding PRs but nothing after merging it.

* [html-validate/html-validate-angular](https://gitlab.com/html-validate/html-validate-angular) (recently removed renovate config and renamed onboarding PR in an attempt to re-onboard)
* [html-validate/html-validate-vue](https://gitlab.com/html-validate/html-validate-vue) (onboarding merged 4 days ago, tried reinstalling using dashboard yesterday)
* [html-validate/grunt-html-validate](https://gitlab.com/html-validate/grunt-html-validate) (onboarding merged 5 days ago, left untouched)
* [html-validate/example-plugin](https://gitlab.com/html-validate/example-plugin) (onboarding merged 5 days ago, tried reinstalling using dashboard today)

**Comment by rarkins** [comment]
We have logic to detect "stale" repos with no commits for months, and then take them off the regular hourly/daily schedules. In this case most of the ones in this org fall into that:

![image](https://user-images.githubusercontent.com/6311784/59386124-33fe5f80-8d66-11e9-848c-76c4df8b3907.png)

What's a pity is that your merging of the onboarding MR itself hasn't achieved the result of removing that status.

I have manually removed the status of each repo and they should hopefully be picked up within the next hour or two.

**Comment by ext** [comment]
Thanks for the quick response! That makes sense, perhaps it could indicate somewhere (dashboard?) to the user as well that it is considered stale?

**Comment by rarkins** [comment]
Yes, that's a good idea. We have a lot of plans to make that dashboard more informative..

**Comment by ext** [comment]
Confirmed working for all repos, thanks again! Closing this issue now.

**Comment by noraj** [comment]
@rarkins Same issue here. I installed the renovate app on my gitlab.com repos but I'm not receiving any onboarding (MR, by the way PR are for github see [Comparing confusing terms in GitHub, Bitbucket, and GitLab (2017)](https://about.gitlab.com/blog/2017/09/11/comparing-confusing-terms-in-github-bitbucket-and-gitlab/)) 

- https://gitlab.com/rawsec/Rawsec-website
- https://gitlab.com/rawsec/rawsec-cybersecurity-list
- https://gitlab.com/noraj/itdis
- https://gitlab.com/noraj/nvd_api

And the dashboard remains empty, no error or stale satus display:

![image](https://user-images.githubusercontent.com/16578570/67848005-21fa3f00-fb04-11e9-8052-b473f009b975.png)
