### ISSUE TITLE
New option prCreation=approval

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3928]
**What would you like Renovate to be able to do?**

Create branches for testing but do not create PRs unless they are approved in the master issue.

**Describe the solution you'd like**

I think there should be a new heading/category for updates that are (a) created as a branch, but (b) awaiting approval for PR creation.

Essentially, masterIssueApproval=true will (still) mean approval needed before creating branches, while prCreation=approval will mean approval needed before creating PRs.

**Comment by rarkins** [comment]
1. Create new `prCreation` value "approval"
2. Update Master Issue logic so that there's a new category/heading "Awaiting PR Creation Approval" for each branch that has been created but not yet approved.

**Comment by gjoseph** [comment]
FWIW, this option isn't documented at https://docs.renovatebot.com/configuration-options/#prcreation (the value is, but not its behaviour)
