### ISSUE TITLE
Configuration option unstablePattern is not evaluated anymore

### ISSUE THREAD

**Issue by tisoft** [renovatebot/renovate#3929]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
The configuration option unstablePattern introduced with #1125 is still mentioned in the docs, but with #2280 it is not evaluated anymore.

**To Reproduce**

1.  Configure an unstablePattern
2.  docker tags matching the pattern are not marked as unstable, so they are not ignored.

**Expected behavior**
The unstablePattern should either be working, or it should be removed from the documentation.

**Comment by rarkins** [comment]
You are right. Sorry for the confusion. I'm going to remove it now.
