### ISSUE TITLE
Update all `resolutions` in package.json

### ISSUE THREAD

**Issue by Mstrodl** [renovatebot/renovate#3930]
**What would you like Renovate to be able to do?**
My project uses `yarn install --flat` in order to produce a smaller file size, but renovate never updates my resolutions

**Describe the solution you'd like**
I would like it if there were a configuration option to recreate the functionality of `yarn install --flat` in renovate that would allow me to choose the latest version of each conflicting dependency (think multiple packages with different versions of babel needed by each)

**Describe alternatives you've considered**
Technically, I could declare every resolution as a dependency so that renovate would need to update them, but this is a bad solution because it defeats the purpose of things like pnpm

**Additional context**
Renovate already updates `resolutions` for declared dependencies, just not for things that aren't listed in `dependencies`

**Comment by rarkins** [comment]
I wasn't aware of this requirement until now, thanks for raising it. Can you create an example public repo that includes a package.json/yarn.lock that would require updating of resolutions, so I can check it out? Simpler the better.

**Comment by Mstrodl** [comment]
@rarkins Sure! [Mstrodl/renovate-resolutions-example](https://github.com/Mstrodl/renovate-resolutions-example)

Resolutions key was created by using `yarn install --flat` and choosing the newest version of the given choices. Currently, Renovate's PRs break my CI step because there is no TTY available to ask for resolutions.

**Comment by douglasduteil** [comment]
Any news @rarkins ?

**Comment by rarkins** [comment]
If someone is interested in working on this or at least moving forward the requirements then that would be welcomed, but unfortunately otherwise I don't see our core team having time for this for quite some time.

It's quite possible that it's a really simple enhancement. e.g. can we just treat `resolutions` like `dependencies` and `devDependencies` without needing to understand how they're generated or how they relate to definitions within those others?

**Comment by Jerska** [comment]
> can we just treat resolutions like dependencies and devDependencies without needing to understand how they're generated or how they relate to definitions within those others?

I believe you can, in which case it would just need to be added to the list of `depTypes` for `npm`.

**Comment by viceice** [comment]
I'll have a look at this, cause we have resolutions at renovate too.
