### ISSUE TITLE
Support validation/parsing of JSON5 correctly

### ISSUE THREAD

**Issue by rohansingh** [renovatebot/renovate#3931]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Unfortunately can't seem to login to the dashboard on mobile.

### What is your question?

We have a `renovate.json5` in our repository. It is valid JSON5, and Renovate runs successfully with the configuration therein.

However, the Renovate bot comments on all PR's that modify the configuration with:

> ### Renovate Configuration Errors
> `renovate.json5`: Invalid JSON

Is the bot able to validate JSON5 correctly? Is there something we need to do to make it work?

**Comment by rohansingh** [comment]
Got it, thanks for the prompt response! In the meantime, is there any way to disable the config check altogether to avoid the red ❌ on pull requests?

**Comment by rarkins** [comment]
@rohansingh the fix was pretty easy, so it should be live within the app within an hour or two and you should see any existing crosses turn to ticks

**Comment by rohansingh** [comment]
Wow, amazing. Thanks again!

**Comment by rarkins** [comment]
You're welcome. FYI:

```
"msg":"Ensuring comment \"Renovate Configuration Errors\" in #1270 is removed"
```
