### ISSUE TITLE
Support for .gitlab-ci.yml include:file

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/renovate#3932]
**What would you like Renovate to be able to do?**
I'd like renovate to be able to renovate pinned versions of https://docs.gitlab.com/ee/ci/yaml/#includefile

e.g. a section in .gitlab-ci.yml like:
```
  - project: 'my-group/my-project'
    ref: v1.0.0
    file: '/templates/.gitlab-ci-template.yml'
```

**Describe the solution you'd like**
For renovate to update this to the latest tag of the referenced project

**Describe alternatives you've considered**
Haven't considered alternatives

**Comment by rarkins** [comment]
Could you create an example on gitlab.com? Both to help me understand it better but also for use in validating an future implementation.

**Comment by mikebryant** [comment]
Here's a source project: https://gitlab.com/mikebryant/include-source-example

And then referencing it: https://gitlab.com/mikebryant/include-renovate-example

The second project is the one where I'd like to enable renovate

**Comment by rarkins** [comment]
I think I understand now. So the references are the tags? I think we can make it work if it’s a sibling repo and Renovate has access to it.

**Comment by mikebryant** [comment]
Yup, that's right :)

**Comment by mikebryant** [comment]
(Also worth explicitly calling our we need this on a local Gitlab EE installation. In general the dependency to look at is in the same Gitlab instance as the repository referencing it, rather than that repo name on gitlab.com)

**Comment by mikebryant** [comment]
I'm giving this a shot, but one thing is tricky - the `gitlabci` manager currently sets language: `docker` - but this inherits settings for all dependencies, even though my new type of dependency isn't docker..

I'm currently making this a separate type of manager, but this feels a little off. Any suggestions?

**Comment by mikebryant** [comment]
@rarkins There's some work in progress, would appreciate any feedback you might have :)
