### ISSUE TITLE
Optimization: check for disabled renovate.json before cloning

### ISSUE THREAD

**Issue by svenbs** [renovatebot/renovate#3934]
**What would you like Renovate to be able to do?**
Renovate should be able to parse the repo configuration (renovate.json) before checking out the repo. This would speed up processing of big repos as renovate would not have to download the whole repos to find it's disabled by repo configuration.

**Describe the solution you'd like**
Download the renovate.json from the repo using some http call not `git clone`.

**Comment by rarkins** [comment]
What’s your reason for adding them to the bot if they are then subsequently disabled? I’d like to understand use cases where such things happen. 

Technically we support 5+ filenames apart from `renovate.json`, but maybe this feature could be dependent on use of that file only.

**Comment by rarkins** [comment]
Also: which platform? Eg GitHub enterprise ?

**Comment by svenbs** [comment]
Platform: Gitlab EE and CE on-prem.

We have a team responsible for the renovate service. And we have other teams responsible for multiple repos or projects.
We enable renovate per [group](https://docs.gitlab.com/ee/user/group/) so a project or a team can use renovate for it's repos. The teams responsible for the group will add their repo configuration via renovate.json. Sometimes they don't want to enable renovate on certain repos.

Of course we could filter out certain repos in the main configuration. Or we could downgrade renovates permissions on certain repos so it won't see them. Both scenarios would introduce organizational overhead we would like to prevent. Also we want to keep things simple for our developers to increase acceptance for the tools.

**Comment by rarkins** [comment]
This would need to be implemented platform-by-platform as part of initRepo. We'd want to use the REST API of each respective platform to fetch `renovate.json` from the default branch. If it exists, and parses, and `enabled` is `false`, then we skip the repo without cloning. Apart from that, we don't care what's in the file or if it exists.

**Comment by ViceIce** [comment]
@rarkins Can we reopen, because of the other platforms? I will send a pr the next days.
