### ISSUE TITLE
Incorrect update of a Bazel go_repository target

### ISSUE THREAD

**Issue by alex1545** [renovatebot/renovate#3938]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The bug occurred in the following [PR](https://github.com/bazelbuild/rules_docker/pull/890).
Renovate attempted to to update a `go_repository` target that has already been at the latest commit. It looks like it tried to update it to the latest release (according to the comment that was added). When doing that, it update the target with a non-existing commit sha.

**Did you see anything helpful in debug logs?**
No

**To Reproduce**
Running renovate to update the same `go_repository` target called [com_github_pkg_errors](https://github.com/bazelbuild/rules_docker/blob/6a3ef0d24371d406c5511351bac7b3c8f4af82b1/WORKSPACE#L325-L329) shoud yield the same result (update to an unknown commit).

**Expected behavior**
I expect a `go_repository` target to be always updated with a valid commit sha.
When a Go repository contains releases, then I expect `go_repository` targets to be updated according to the latest release. When the repo has no releases, then I would expect it to fall back to the latest merged commit.

**Screenshots**
The [PR](https://github.com/bazelbuild/rules_docker/pull/890) where bug occurred should be sufficient.

**Additional context**
N/A

**Comment by rarkins** [comment]
It appears that [v0.8.1](https://github.com/pkg/errors/releases/tag/v0.8.1) is indeed the latest release, so that part is to be expected. According to GitHub, the commit for that tag is ba968bfe8b2f7e042a574c888954fccecfa385b4.

The URL Renovate queries is https://api.github.com/repos/pkg/errors/git/refs/tags/v0.8.1

```
{
  "ref": "refs/tags/v0.8.1",
  "node_id": "MDM6UmVmNDg2NDM1MTA6djAuOC4x",
  "url": "https://api.github.com/repos/pkg/errors/git/refs/tags/v0.8.1",
  "object": {
    "sha": "05ac58a23b8798a296fa64f7d9c1559904db4b98",
    "type": "tag",
    "url": "https://api.github.com/repos/pkg/errors/git/tags/05ac58a23b8798a296fa64f7d9c1559904db4b98"
  }
}
```

Maybe we should instead then be querying https://api.github.com/repos/pkg/errors/git/tags/05ac58a23b8798a296fa64f7d9c1559904db4b98 to get:

```
{
  "node_id": "MDM6VGFnNDg2NDM1MTA6MDVhYzU4YTIzYjg3OThhMjk2ZmE2NGY3ZDljMTU1OTkwNGRiNGI5OA==",
  "sha": "05ac58a23b8798a296fa64f7d9c1559904db4b98",
  "url": "https://api.github.com/repos/pkg/errors/git/tags/05ac58a23b8798a296fa64f7d9c1559904db4b98",
  "tagger": {
    "name": "Dave Cheney",
    "email": "dave@cheney.net",
    "date": "2019-01-05T02:13:09Z"
  },
  "object": {
    "sha": "ba968bfe8b2f7e042a574c888954fccecfa385b4",
    "type": "commit",
    "url": "https://api.github.com/repos/pkg/errors/git/commits/ba968bfe8b2f7e042a574c888954fccecfa385b4"
  },
  "tag": "v0.8.1",
  "message": "errors v0.8.1\n",
  "verification": {
    "verified": false,
    "reason": "unsigned",
    "signature": null,
    "payload": null
  }
}
```

**Comment by rarkins** [comment]
Found and fixing

**Comment by rarkins** [comment]
@alex1545 this will take a few hours until the fix is properly live. The main reason is that we use a 2 hour cache for tag commits because in theory they shouldn't change! After that though you should see these all being correct. Thanks for raising the issue to notify us.
