### ISSUE TITLE
Not recognized dockerfiles with suffix

### ISSUE THREAD

**Issue by matoous** [renovatebot/renovate#3940]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate bot successfully updates Dockerifle `tests/e2e/Dockerfile` but fail to update `Dockerfile.ourapp` and `Dockerifle.ourapp-debug` in the root directory of the project.

**To Reproduce**

1.  Create repository with 'Dockerfile.suffix'
2.  Configure image in the dockerifle to some old version
3. Run renovate and see that nothing happens

**Expected behavior**
All files matching `Dockerfile.*` and `Dockerfile` are updated by the docker manager.

**Comment by rarkins** [comment]
You can use the `fileMatch` field to manually override the pattern for any manager. If you think our default match for Dockerfile should be expanded than a PR would be welcomed too

**Comment by rarkins** [comment]
You can use the `fileMatch` field to manually override the pattern for any manager. If you think our default match for Dockerfile should be expanded than a PR would be welcomed too

**Comment by matoous** [comment]
Oh, nice! I am sorry that I didn't notice. I think that the correct config is ok if it's possible to change for which files the docker manager looks. Thank you very much, closing the issue.

**Comment by rarkins** [comment]
IMO matching `Dockerfile.*` by default is probably a good idea though

**Comment by matoous** [comment]
Then please point me to the where the changes can be made and I will submit PR.

**Comment by rarkins** [comment]
Edit the regex in this line: https://github.com/renovatebot/renovate/blob/2142007737aa6939723990cdcd1ca0360d1fa097/lib/config/definitions.js#L1427

You can either make the existing Regex more complex or add a second regex to the array. The main thing we want to avoid is accidentally matching an entire directory. e.g. we should not match `foo/Dockerfile/readme.md` but we could match `foo/Dockerfile_readme`.

Once that's done, we need to run `yarn create-json-schema` to update the JSON schema to match.

**Comment by matoous** [comment]
https://github.com/renovatebot/renovate/pull/3941 here, please check it when you have some time. Also, thanks for navigating me to the right place!
