### ISSUE TITLE
SHA256 digest for Bazel http_archive is incorrect

### ISSUE THREAD

**Issue by rohansingh** [renovatebot/renovate#3947]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The `sha256` field is being filled with an incorrect digest in commits generated by Renovate. Here are two examples:

```
 http_archive(
     name = "tilt_linux_x86_64",
     build_file_content = "exports_files(['tilt'])",
-    sha256 = "9139e76faa40c559baabcf5a9bed6c89b6554532e9dd95abde9a0229827fea5c",
-    urls = ["https://github.com/windmilleng/tilt/releases/download/v0.7.13/tilt.0.7.13.linux.x86_64.tar.gz"],
+    sha256 = "61de3bd5b2e75844a515eee488551bbb9cce8b4c4a5df8dc5adea4fe448c0012",
+    urls = ["https://github.com/windmilleng/tilt/releases/download/v0.9.0/tilt.0.9.0.linux.x86_64.tar.gz"],
 )
```

```
 http_archive(
     name = "tilt_mac_x86_64",
     build_file_content = "exports_files(['tilt'])",
-    sha256 = "659db55ccdb12a5f77ca640680c6069a161343229d9c2aecbfc26c01442aa8e5",
-    urls = ["https://github.com/windmilleng/tilt/releases/download/v0.7.13/tilt.0.7.13.mac.x86_64.tar.gz"],
+    sha256 = "61de3bd5b2e75844a515eee488551bbb9cce8b4c4a5df8dc5adea4fe448c0012",
+    urls = ["https://github.com/windmilleng/tilt/releases/download/v0.9.0/tilt.0.9.0.mac.x86_64.tar.gz"],
 )
```

In both cases, the `sha256` value doesn't match the actual file. In fact, these are definitely two different files but the new `sha256` value in both cases is the same, so it can't possibly be correct.

**Did you see anything helpful in debug logs?**
Log shows the incorrect digest value, but not sure where it's coming from:
```
DEBUG: Failed to download release download - trying archive instead(dependencies=["tilt_linux_x86_64"], branch="renovate/tilt_linux_x86_64-0.x")
DEBUG: (dependencies=["tilt_linux_x86_64"], branch="renovate/tilt_linux_x86_64-0.x")
{
  "oldDef": "http_archive(\n    name = \"tilt_linux_x86_64\",\n    build_file_content = \"exports_files(['tilt'])\",\n    sha256 = \"9139e76faa40c559baabcf5a9bed6c89b6554532e9dd95abde9a0229827fea5c\",\n    urls = [\"https://github.com/windmilleng/tilt/releases/download/v0.7.13/tilt.0.7.13.linux.x86_64.tar.gz\"],\n)",
  "newDef": "http_archive(\n    name = \"tilt_linux_x86_64\",\n    build_file_content = \"exports_files(['tilt'])\",\n    sha256 = \"61de3bd5b2e75844a515eee488551bbb9cce8b4c4a5df8dc5adea4fe448c0012\",\n    urls = [\"https://github.com/windmilleng/tilt/releases/download/v0.9.0/tilt.0.9.0.linux.x86_64.tar.gz\"],\n)"
}
```

**To Reproduce**
Create repository with a `WORKSPACE` containing the `http_archive` examples above.

**Expected behavior**
Correct SHA256 digests for the actual archive files.

**Comment by rarkins** [comment]
What's your own approach for calculating/verifying the SHA256 for a while? e.g. do you have a CLI command that works?

**Comment by rohansingh** [comment]
For a given file I can get the correct SHA256 with something like this:

```
$ curl -sL https://github.com/windmilleng/tilt/releases/download/v0.9.0/tilt.0.9.0.mac.x86_64.tar.gz | shasum -a256
b808671863e1449adf3cad4ae259cd6df6b9e8f9191c12a9a0c7be01f240fd1e  -
```

The SHA256 there matches what Bazel expects as well, based on the error I see in our CI for these patches:

```
$ bazel <some command>
ERROR: An error occurred during the fetch of repository 'tilt_mac_x86_64':
--
  | java.io.IOException: Error downloading [https://github.com/windmilleng/tilt/releases/download/v0.9.0/tilt.0.9.0.mac.x86_64.tar.gz] to /buildkite/builds/bazel-root/7bc053ab37133f43e1b83f99f62acb58/external/tilt_mac_x86_64/tilt.0.9.0.mac.x86_64.tar.gz: Checksum was b808671863e1449adf3cad4ae259cd6df6b9e8f9191c12a9a0c7be01f240fd1e but wanted 61de3bd5b2e75844a515eee488551bbb9cce8b4c4a5df8dc5adea4fe448c0012
```

**Comment by rarkins** [comment]
Thanks, I'll try to work out what's going wrong

**Comment by rarkins** [comment]
Although Node.js crypto hashing is still mostly a mystery to me, I've worked out how to get the necessary result and will patch this hopefully today. Thanks for the bug report

**Comment by rohansingh** [comment]
Sure thing, thanks once again for the quick response.

**Comment by rarkins** [comment]
Actually there's a bigger problem than just the hash. The problem is that Renovate is attempting to download `https://github.com/windmilleng/tilt/releases/download/v0.9.0/tilt-v0.9.0.tar.gz` instead of `https://github.com/windmilleng/tilt/releases/download/v0.9.0/tilt.0.9.0.mac.x86_64.tar.gz`. Once that fails it falls back to `https://github.com/windmilleng/tilt/archive/v0.9.0.tar.gz`, which works. This is why both have the same hash. It's actually a correct hash but wrong file. I'll need more time to fix unfortunately.

**Comment by rohansingh** [comment]
Ah, that's tricky. Good to know where the hash is actually coming from though.
