### ISSUE TITLE
Pinning duplicated dependency instead of pinning to locked version

### ISSUE THREAD

**Issue by zephraph** [renovatebot/renovate#3951]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Normally during the pinning process it pins the dependency to the version found in the lock file. In a pin PR we received on one of our repos, it added a new dependency entry in the lock file instead of pinning to the lock version. 

See https://github.com/artsy/arc/pull/3/commits/44eb1265bd5db24baafec35742fa8754bb24809f

**Comment by rarkins** [comment]
We should have detected the locked version to be 4.3.2 and pinned to that. Need to work out where it decided 4.3.1 was the currently locked version

**Comment by zephraph** [comment]
Turns out there was another version of the dependency under `dependencies` in a different package which caused the duplication. False alarm.
