### ISSUE TITLE
Renovate fails with invalid version at SemVer

### ISSUE THREAD

**Issue by rohansingh** [renovatebot/renovate#3952]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Approximately 10 hours ago, the Renovate GitHub App stopped functioning for our repo. The dashboard shows "unknown-error".

**Did you see anything helpful in debug logs?**
Yes, in the Renovate dashboard:

```
ERROR: Repository has unknown error
{
  "err": {
    "message": "Invalid Version: 10",
    "stack": "TypeError: Invalid Version: 10\n    at new SemVer (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/semver/semver.js:323:11)\n    at Range.test (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/semver/semver.js:1264:15)\n    at satisfies (/home/ubuntu/renovateapp/node_modules/renovate/node_modules/semver/semver.js:1318:16)\n    at packageRules.forEach.packageRule (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/package-rules.js:119:33)\n    at Array.forEach ()\n    at applyPackageRules (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/package-rules.js:13:18)\n    at flattenUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/updates/flatten.js:34:40)\n    at branchifyUpgrades (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/updates/branchify.js:23:21)\n    at extractAndUpdate (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/extract-update.js:18:38)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
```

Unfortunately it's not clear which dependency could be causing this.

**To Reproduce**
Unfortunately I don't have a simple set of repro steps since I'm not even sure what's causing this.

**Additional context**
This started occurring 10 hours ago, but there were no commits in our repo within several hours of that (by Renovate or otherwise). There were some commits to Renovate itself around that time, but I don't see how they could be related.

The error reads `Invalid Version: 10`, but the only thing I'm aware of that we have in this repo with a version "10" is a Docker image for Postgres. But that should be using the `docker` version scheme, not `semver`, so it doesn't seem to match the error above.

**Comment by rarkins** [comment]
Is that docker postgres 10 definition in a Dockerfile or similar or a bazel definition?

**Comment by rohansingh** [comment]
@rarkins It is a `container_pull()` in the Bazel `WORKSPACE`. Perhaps this snippet from my Renovate config is responsible?

```
"bazel": {
  "packageRules": [
    {
      "packagePatterns": ["*"],
      "depTypeList": ["container_pull"],

      // use the "docker" version scheme for container_pull. this ensures
      // that image tag suffixes (like "1.0-ubuntu") are respected.
      "versionScheme": "docker",
    },
  ],
},
```

I added that very recently, but we've also had several successful Renovate runs since then.

**Comment by rarkins** [comment]
Is it a public repository I can use to try to reproduce with?

**Comment by rohansingh** [comment]
Unfortunately it's a private repository. I've attempted to make a minimal repro here with stuff from that repo: https://github.com/Hustle/renovate-repro

But... Renovate seems to run fine there. I'll try ripping out the `packageRules` snippet above in the private repo and see how that goes.

**Comment by rohansingh** [comment]
Removing that snippet fixed the issue. Now I'm trying to figure out why that would be.

**Comment by rarkins** [comment]
In short, the problem seems to be that we’re asking the `semver` library to do some type of comparison without first checking `semver.valid()`. One way or another there’s a bug here, sounds like it could be in our packageRules. Strange that it’s triggered by you setting versionScheme to `docker`

**Comment by rarkins** [comment]
@rohansingh do you have any packageRules utilising `matchCurrentVersion` ?

**Comment by rarkins** [comment]
I've added an extra check to packageRules which I think should prevent this error. Will roll it out to the app later today.
