### ISSUE TITLE
Convert versioning schemes to TypeScript

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3953]
Starting with [npm](https://github.com/renovatebot/renovate/tree/master/lib/versioning/npm), convert each versioning scheme to TS. Versioning schemes should all share a common "interface", which should then be stabilized by the time we complete all the conversions.

**Comment by ViceIce** [comment]
So next part are versioning folder?

**Comment by ViceIce** [comment]
@rarkins Can you assign this to me?

**Comment by ViceIce** [comment]
part of #1261
