### ISSUE TITLE
Whitelist a single project path in a monorepo

### ISSUE THREAD

**Issue by sebarthel89** [renovatebot/renovate#3964]
**What Renovate type are you using?**
Renovate docker container

**Describe the bug**
I have multiple projects within a single single github monorepo. Therefore, I updated the ignore path using a glob patther. That didn't work. I also tried to enable it manually by define a package rule, but that didn't work either.

Target is to only check:

`test/webapp/src/main/resources/static-resources/package.json`

My configuration:
```
{
  "extends": [
    "config:base",
    "default:preserveSemverRanges"
  ],
  "lockFileMaintenance": {
    "enabled": true,
    "schedule": "before 11am on monday"
  },
  "ignoreDeps": [],
  "ignorePaths": [
    "!test/webapp/src/main/resources/static-resources"
  ],
  "packageRules": [
    {
      "paths": [
        "test/webapp/src/main/resources/static-resources/package.json"
      ],
      "enabled": true
    }
  ]
}

```

**Did you see anything helpful in debug logs?**
I don't see anything happening in the debug logs. I expect at least `Found npm package files` that doesn't exist.

**To Reproduce**

1.  Create repository with multiple java/js/docker ... projects
2.  Try to whitelist a single path similar to my config.

**Expected behavior**
It should only analyze and maintain the single path that is whitelisted.

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
I would expect this to work:

```json
{
  "extends": [
    "config:base",
    "default:preserveSemverRanges"
  ],
  "lockFileMaintenance": {
    "enabled": true,
    "schedule": "before 11am on monday"
  },
  "ignorePaths": [
    "!test/webapp/src/main/resources/static-resources/package.json"
  ]
}
```

FYI Renovate uses `minimatch` for glob patterns so you could test it here: http://pthrasher.github.io/minimatch-test/

**Comment by sebarthel89** [comment]
works! thank you
