### ISSUE TITLE
Renovate CLI with dry run creates master issue

### ISSUE THREAD

**Issue by jgarec** [renovatebot/renovate#3966]
**What Renovate type are you using?**
CLI

**Describe the bug**
It should not create the master issue in dry run mode.

**Did you see anything helpful in debug logs?**
-

**To Reproduce**
Master issue is enabled on the repository :
```
{
  masterIssue: true
}
```
Renovate runs with `--dry-run=false`

**Expected behavior**
It should not create / update / delete any issue.

**Additional context**
I think we should modify master-issue.js and any `await platform.xxxx()` calls like this
```
      if (config.dryRun) {
        logger.info('DRY-RUN: Would close Master Issue ' + config.masterIssueTitle);
      } else {
        await platform.ensureIssueClosing(config.masterIssueTitle);
      }
```

**Comment by jgarec** [comment]
@rarkins Any reason why istanbul ignore the content of the file : https://github.com/renovatebot/renovate/blob/f5e4c32d3807420bf66635ff8807c30b009843af/lib/workers/repository/master-issue.js#L7-L8

https://github.com/renovatebot/renovate/blob/f5e4c32d3807420bf66635ff8807c30b009843af/lib/workers/repository/master-issue.js#L25-L26

Juste a lack of Unit Tests ?

**Comment by rarkins** [comment]
I think it was just laziness at the time of development, ideally it should be covered properly
