### ISSUE TITLE
Repeat PRs being opened and autoclosed

### ISSUE THREAD

**Issue by joho** [renovatebot/renovate#3969]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

Repeat PRs being opened and autoclosed. See screenshot below.

**Did you see anything helpful in debug logs?**

```
DEBUG: remainingBranches=renovate/puma-4.x,renovate/skylight-4.x
DEBUG: findPr(renovate/puma-4.x, null, open)
DEBUG: Found PR #258
DEBUG: updatePr(258, Update dependency puma to v4 - autoclosed, body)
DEBUG: PR updated
{
  "pr": 258
}
INFO: Deleting orphan branch(branch="renovate/puma-4.x")
DEBUG: Deleted remote branch
{
  "branchName": "renovate/puma-4.x"
}
DEBUG: No local branch to delete
{
  "branchName": "renovate/puma-4.x"
}
INFO: PR autoclosed
{
  "prNo": 258,
  "prTitle": "Update dependency puma to v4"
}
DEBUG: findPr(renovate/skylight-4.x, null, open)
DEBUG: Found PR #259
DEBUG: updatePr(259, Update dependency skylight to v4.1.1 - autoclosed, body)
DEBUG: PR updated
{
  "pr": 259
}
INFO: Deleting orphan branch(branch="renovate/skylight-4.x")
```
from https://renovatebot.com/dashboard#github/joho/hecate/75730878

**To Reproduce**

Have a repository with bundler support enabled and wait?

**Expected behavior**
A single PR per dependency to be opened and not autoclosed and later recreated.

**Screenshots**

![image](https://user-images.githubusercontent.com/4092/60142647-07ceee00-97fe-11e9-9ca0-e2f0e27e1958.png)

**Additional context**
Sorry for the initial post without details, github somehow refreshed and ate my original description.

**Comment by rarkins** [comment]
This presumably happens because occasionally Renovate can't find updates for a dependency because of an error, but doesn't *realise* it's an error condition and keeps going instead of aborting. For the job you referenced, it detects zero updates for puma:

```json
{"depName":"puma","lineNumber":10,"currentValue":"3.12.1","datasource":"rubygems","updates":[],"warnings":[],"sourceUrl":null,"releases":[]}
```

I'll try to work out if this is machine-level corruption of a cache or something else ephemeral that can affect any machine at any time.

**Comment by joho** [comment]
![image](https://user-images.githubusercontent.com/4092/60774684-19e45100-a15b-11e9-989c-79e9d2ba6c10.png)

Any progress on the fix? The extra emails this is spitting out is getting kind of annoying.

**Comment by rarkins** [comment]
@joho I'm pretty sure I've spotted and fixed the logic error causing this. Should be live in the app in an hour or so. I will monitor and reopen if it does not resolve it, of course.
