### ISSUE TITLE
feat: different schedules for branch, pr and automerge

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#3970]
**What would you like Renovate to be able to do?**
The current schedule is only used for branch and pr creation. I would be able to schedule the automerge window. So we have a fixed time when automerges can happen.

**Describe the solution you'd like**
Add new options `branchSchedule`, `prSchedule`, `automergeSchedule` to configure specific schedules

**Describe alternatives you've considered**
Only alternate is to merge manually on desired schedule. Not really an option.

**Additional context**
none

**Comment by foray1010** [comment]
+1 for this feature. The reason for separate schedules for pr create & automerge is it is great to reduce noise by scheduling pr created on non-working hours, but it is fatal to automerge on non-working hours because maybe no one will be able to support if anything goes wrong.

**Comment by sebarthel89** [comment]
any updates or workarounds to that ?

We try to only create branches, PRs and automerge within a certain time range (Monday, 7-9). 

As described, renovate still merges PRs although it's not part of the defined schedule window.

**Comment by zbianca** [comment]
Could be partially built with #15475
