### ISSUE TITLE
`postUpdateOptions.npmDedupe` clears `package-lock.json`

### ISSUE THREAD

**Issue by merlinnot** [renovatebot/renovate#3972]
**What Renovate type are you using?**

Renovate GitHub App (paid plan).

**Describe the bug**

After adding `postUpdateOptions.npmDedupe`, content of `package-lock.json` is being removed.

**Did you see anything helpful in debug logs?**

I did look at the logs, I saw this:

```
added 1504 packages in 15.66s\nup to date in 0.454s\nfound 0 vulnerabilities\n\n
```

which does not correspond with the observed behaviour.

**To Reproduce**

Config I'm using:

```
{
  "automerge": false,
  "commitMessageAction": "update",
  "packageRules": [
    {
      "enabled": false,
      "packageNames": ["@types/node"],
      "updateTypes": ["major"]
    }
  ],
  "postUpdateOptions": ["npmDedupe"],
  "rangeStrategy": "bump",
  "rebaseStalePrs": true,
  "recreateClosed": true
}
```

**Expected behavior**

There should ba packages in the lockfile.

**Screenshots**

Look at the number of removed lines:

![Screenshot 2019-06-26 at 18 08 17](https://user-images.githubusercontent.com/10390061/60196552-b2b2cc80-983d-11e9-95f1-cf060b490984.png)

What's left in the file is:

![Screenshot 2019-06-26 at 18 09 14](https://user-images.githubusercontent.com/10390061/60196469-86974b80-983d-11e9-8512-b212ff514966.png)

**Additional context**

Example job: https://renovatebot.com/dashboard#github/ridedott/functions/75879581

**Comment by rarkins** [comment]
How widely observed is this? e.g. has it done this to all Renovate PRs, or are some OK? It seems like the "npm dedupe" function is somehow removing most of the file.

**Comment by merlinnot** [comment]
It's 100% reproducible, on all PRs Renovate creates. As you can see it's quite a lot, since we're updating each dependency as soon as it's released.

**Comment by merlinnot** [comment]
The result is always the same, `package-lock.json` contains just the five lines in a screenshot above.

**Comment by rarkins** [comment]
And if you disable the dedupe, it produces normal lock file updates?

**Comment by mad-it** [comment]
After `npmDedupe` was introduced, all the PR's provided by renovatebot were "broken".

**Comment by merlinnot** [comment]
Yes, that is correct. We changed this particular setting yesterday morning and ever since we observe this issue. No other changes to the configuration have been made.

**Comment by mad-it** [comment]
@merlinnot Lets see if disabling `npmDedupe` fixes the problem. If it does that means `npmDedupe` functionality is broken.

**Comment by mad-it** [comment]
Issue confirmed. Disabling `npmDedupe` fixes the `package-lock.json` issue. 

That means that `npmDedupe` functionality is broken.

**Comment by rarkins** [comment]
After some quick testing, I think `npm dedupe` may fail like this if there's no `node_modules`. By default we run `npm i --package-lock-only` to update the `package-lock.json` so this could explain it

**Comment by rarkins** [comment]
Can you add `"skipInstalls": false` to your renovate config and rebase a PR to see if that fixes it?

**Comment by merlinnot** [comment]
At a first glance it seems to fix the issue, I'll run a couple more tests to confirm. Shall I leave the issue open until it's addressed in the codebase? I guess it should be either documented or the other flag should be applied automatically.

**Comment by merlinnot** [comment]
Confirmed, now it does work.

**Comment by rarkins** [comment]
I guess we’ll need to apply the flag automatically for it to be considered resolved.
