### ISSUE TITLE
Deprecate Docker v1 API support

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3993]
It would make it simpler if we officially deprecate Docker v1 support and support v2 only. This would be done in a major Renovate release although the assumption is that it hopefully doesn't *affect* users.

Docker themselves have begun deprecating v1: https://engineering.docker.com/2019/03/registry-v1-api-deprecation/

Related: #3989

**Comment by rarkins** [comment]
@mikebryant I noticed that you retained v1 support for label retrieval in the Docker datasource. Are you aware of any Docker-compatible services/servers that don't support v2 yet, or were you just being conservative with your implementation?

Doing this would also help Renovate deprecate the unmaintained Joyent docker client, which has both old and vulnerable transitive dependencies.

**Comment by mikebryant** [comment]
I was being conservative. I'm fine with v1 support being dropped
