### ISSUE TITLE
No docker image for 18.21.0

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/renovate#3996]
**Describe the bug**
No build for 18.21.0, though it's been a couple of hours since release

```
$ docker pull renovate/renovate:18.21.0
Error response from daemon: manifest for renovate/renovate:18.21.0 not found
```

**Expected behavior**
I was expecting a dockerhub autobuild or similar to happen soon after the tag was released

**Additional context**
18.20.0 was also never released

**Comment by rarkins** [comment]
Unfortunately Docker Hub sometimes just fails to build. It has built subsequent releases now though

**Comment by mikebryant** [comment]
Have been able to use the new images :+1:
