### ISSUE TITLE
Not setting HTTP_PROXY, HTTPS_PROXY or NO_PROXY will result in an error

### ISSUE THREAD

**Issue by Tanuel** [renovatebot/renovate#4014]
**What Renovate type are you using?**
Renovate CLI (self hosted)

**Describe the bug**
This bug happens since this commit: https://github.com/renovatebot/renovate/commit/36b938cd1dbe4b459ec42cf6f85295680a295d07

When not setting any of the env vars, authentication will fail:

>  Error authenticating with GitLab. Check that your token includes "user" permissions

and

> "message": "Unsupported `GLOBAL_AGENT.HTTP_PROXY` configuration value: URL protocol must be \"http:\"."

**Did you see anything helpful in debug logs?**
see above

**To Reproduce**
Do not set any of the variables and try to run it via cli

**Expected behavior**
Should work as usual. By commenting out the changes in the mentioned commit, everything works.

**Additional context**
I will create a merge request following up this issue

**Comment by rarkins** [comment]
Thanks. I've pushed a revert of the bad commit and a new version should be released. I'll re-implement and test better and close this issue with a new commit later.

**Comment by Tanuel** [comment]
> Thanks. I've pushed a revert of the bad commit and a new version should be released soon. I'll re-implement and test better and close this issue with a new commit later.

I created a fix that was ready before your revert, but you were too fast. I rebased it on master, maybe it is still useful
