### ISSUE TITLE
bundler: `bundle: not found` error occurs when running renovate using Docker

### ISSUE THREAD

**Issue by ikesyo** [renovatebot/renovate#4016]
**What Renovate type are you using?**
Renovate CLI (Docker)

**Describe the bug**
When running Renovate CLI using Docker for a repository which have Gemfile, `bundle: not found` error occurs.

**Did you see anything helpful in debug logs?**
```
 INFO: Running bundler via global bundler (repository=redacted, dependencies=cocoapods, branch=renovate/cocoapods-1.x)
 WARN: Failed to generate Gemfile.lock (unknown error) (repository=redacted, dependencies=cocoapods, branch=renovate/cocoapods-1.x)
       "err": {
         "name": "ChildProcessError",
         "code": 127,
         "childProcess": {},
         "stdout": "",
         "stderr": "/bin/sh: 1: bundle: not found\n",
         "message": "Command failed: bundle lock --update cocoapods\n/bin/sh: 1: bundle: not found\n `bundle lock --update cocoapods` (exited with error code 127)",
         "stack": "ChildProcessError: Command failed: bundle lock --update cocoapods\n/bin/sh: 1: bundle: not found\n `bundle lock --update cocoapods` (exited with error code 127)\n    at callback (/usr/src/app/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Socket.stream.socket.on (internal/child_process.js:389:11)\n    at Socket.emit (events.js:198:13)\n    at Pipe._handle.close (net.js:606:12)"
       }
```

**To Reproduce**

1.  Create repository with a Gemfile whose contents are outdated
2.  Running Renovate CLI with Docker for that repository

**Expected behavior**
Successfully finishing the execution.

**Screenshots**

**Additional context**
Looks like [the Dockerfile](https://github.com/renovatebot/renovate/blob/7090fb516755611825dce997dcefc7c6af21db73/Dockerfile) does not set up Ruby and bundler so that will be the cause.

**Comment by ikesyo** [comment]
This is a bit related to #3860, so if I use `--binary-source=docker` that may work (Docker in Docker).

**Comment by rarkins** [comment]
Bundler will only work with binarySource=docker because of the importance of running the exact Ruby and Bundler version the project requires. Ie if we added one specific version to the Dockerfile then it would be “wrong” for a large proportion of users. 

Bundler is the first package manager to need this, and it’s still so we’re a bit lacking in docs, but we plan to roll it out for all binaries and then publish a much smaller Renovate default image that pulls the other images as needed.

**Comment by ikesyo** [comment]
Okay now I understand the situation, thanks for the clarification! It would be great 

- If we could add a docs for bundler (Gemfile)
- If we could add a (temporary) fix for the situation: adding another condition whether the process is running in Docker here https://github.com/renovatebot/renovate/blob/c911a2dfafde13e2a54d4bb5423cc319a2e8f93a/lib/manager/bundler/artifacts.js#L52

**Comment by rarkins** [comment]
I don’t understand your second point. Could you describe in more detail what you mean?

I should have said that you *can* run Bundler using globals, but for that to work with the Docker distribution you’ll need to add Ruby/bundler to the image yourself.

**Comment by ikesyo** [comment]
> I don’t understand your second point. Could you describe in more detail what you mean?

What I want is that Renovate CLI would run Bundler using Docker even if `binarySource=docker` is not specified when Renovate CLI is executed by Docker (running in a container). I just want the `renovate/renovate` image supports Bundler out-of-the-box without specifying `binarySource=docker`.

> but for that to work with the Docker distribution you’ll need to add Ruby/bundler to the image yourself.

I see that you won't to support the case, so please feel free to close this.

**Comment by rarkins** [comment]
Actually it’s not “docker in docker” so that’s not possible unless you map in the Docker socket to Renovate

**Comment by ikesyo** [comment]
#3153, #3222

**Comment by shushugah** [comment]
@ikesyo, My team has the exact same issue. I am unclear what you did to fix this. I can open a new issue if necessary. Here is my error, when running it locally

```bash
WARN: Failed to generate Gemfile.lock (unknown error) (repository=payment/test-gems, dependencies=rails, branch=PAY-1729-Renovaterails-6-x)
       "err": {
         "killed": false,
         "code": 127,
         "signal": null,
         "cmd": "bundle lock --update rails",
         "stdout": "",
         "stderr": "/bin/sh: 1: bundle: not found\n",
         "message": "Command failed: bundle lock --update rails\n/bin/sh: 1: bundle: not found\n",
         "stack": "Error: Command failed: bundle lock --update rails\n/bin/sh: 1: bundle: not found\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Socket.stream.socket.on (internal/child_process.js:389:11)\n    at Socket.emit (events.js:198:13)\n    at Pipe._handle.close (net.js:606:12)"
       }
```

**Comment by rarkins** [comment]
@shushugah app or cli?

**Comment by shushugah** [comment]
> @shushugah app or cli?

CLI and Gitlab version `11.9.4-ee` (enterprise edition)

I have included a `.ruby-version` with `ruby 2.6.3`, which is additionally specified in the Gemfile as well.

**Comment by rarkins** [comment]
@shushugah the error you paste indicates that `bundle` is not found. You can't update Gemfiles without bundler installed. If you can't get it working, please post a new issue to https://github.com/renovatebot/config-help/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc so it can be triaged there

**Comment by shushugah** [comment]
> @shushugah the error you paste indicates that `bundle` is not found. You can't update Gemfiles without bundler installed. If you can't get it working, please post a new issue to https://github.com/renovatebot/config-help/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc so it can be triaged there

Continuing conversation here, as it's related https://github.com/renovatebot/config-help/issues/336#issuecomment-524865045
