### ISSUE TITLE
Gemfile source not extracted correctly

### ISSUE THREAD

**Issue by parenparen** [renovatebot/renovate#4021]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate might incorrectly parse the Gemfile if the Gemfile contains a mixture of single quotes and double quotes. 

/dist/manager/bundler/extract.js uses a delimiter to parse the Gemfile. The delimiter is a single quote or double quote and is determined based on which the Gemfile contains more of. If it guesses the delimiter wrong, Renovate cannot parse out the registry URL and Renovate fails to update the Gemfile.lock.

**Did you see anything helpful in debug logs?**
```
DEBUG: Using delimeter " to parse Gemfile
```

```
"config": {
         "bundler": [
           {
             "packageFile": "Gemfile",
             "manager": "bundler",
             "registryUrls": [],
             "deps": [
               {
                 "depName": "rake",
                 "lineNumber": 5,
                 "currentValue": "12.3.1",
                 "datasource": "rubygems",
                 "updates": [],
                 "warnings": [
                   {
                     "updateType": "warning",
                     "message": "Failed to look up dependency rake"
                   }
                 ]
               },
```

**To Reproduce**

1.  Create a repository with Gemfile that uses mostly double quotes, but specify the source with single quotes:
```
source 'https://rubygems.org'
```
2.  Attempt to update the repository with Renovate CLI

**Expected behavior**
Renovate is able to look up the dependencies specified in the Gemfile and update the Gemfile.lock.

**Comment by rarkins** [comment]
I understand that you *can* mix delimiters in a file, but is there any reason why you *must*? i.e. is there anything preventing users from refactoring the Gemfile for delimiter consistency?

**Comment by parenparen** [comment]
I wouldn't think there would be anything preventing someone from refactoring and making the quotes consistent. But there's not a clear indication in the logs from what I could tell that parsing failed. This issue might be tricky for people to track down if their Gemfile has the wrong mix of single and double quotes.

**Comment by rarkins** [comment]
I'm wondering even about a simple but perhaps effective approach:
- Parse using both and merge, or
- Parse using both, and if the "lesser" use delimiter parsing does produce some results, then WARN

The first approach might solve the problem, but I'm not sure it would really work. The second approach would at least make it easier to track down.
