### ISSUE TITLE
Support ssh for git-tags datasource

### ISSUE THREAD

**Issue by Tanuel** [renovatebot/renovate#4022]
First of all i want to apologize if this issue is a bit messy, there are just so many points to consider.

This issue emerges from Issue #3811 and PR #4019 

**What would you like Renovate to be able to do?**
I want the git-tags datasource to support getting info via ssh for improved integration with managers, in this case for composer (#3811)

This is mostly applicable for self-hosted renovate.

**Describe the solution you'd like**
Refactor git-tags to use simple-git instead of isomorphic-git.

[simple-git](https://www.npmjs.com/package/simple-git) is a wrapper around native git.

[isomorphic-git](http://isomorphic-git.org) is a full javascript git implementation which is currently [not supporting ssh](https://github.com/isomorphic-git/isomorphic-git/issues/231)

**Describe alternatives you've considered**
[ssh2 npm package](https://www.npmjs.com/package/ssh2) instead of native ssh. Could tell git to use that package instead of native ssh and provide a ssh key via config?

**Additional context**
simple-git will require the host system to provide git and ssh (the latter being required only for ssh calls with git@domain:repo)

We can get around the requirement for ssh by using a regex with host rules. This would actually be easier with isomorphic-git, but will not work if the server has [disabled https](https://stackoverflow.com/a/1348632) (might be an edge case?)
```javascript
const { username, password } = hostRules.find({
  hostType: 'git',
  url: lookupName,
});
if(username && password) {
 // transform urls with ssh://git@ (or just git@) to https urls
  lookupName.replace(/^(?:ssh:\/\/)?git@(.+?):(.+)/, `https://${USER}:${PASS}@$1/$2`);
}
// look up tags via simple-git:
const lsRemote = await simpleGit.listRemote(['--quiet', '--sort=-v:refname', '--tags', repo]); //*/
return lsRemote.match(/refs\/tags\/([\d.]+)/g).map(tag => tag.replace('refs/tags/', ''));
```

When using ssh, we will be confronted with additional hurdles:
-  git+ssh will prompt for known hosts. this can be worked around in two ways:
    - Add the domain to known_hosts via ssh-keyscan 
`ssh-keyscan domain.com >> /root/.ssh/known_hosts`.
 This should be done ahead of running renovate, e.g. when using a docker image
    - Tell git to to disable strict host key checking:
      `process.env.GIT_SSH_COMMAND = "ssh -o StrictHostKeyChecking=no";`
      This can be done at runtime and add the domain to known_hosts
- git+ssh will not allow to provide a password automatically (as far as my googling skills took me). Possible Solutions:
    - Add ssh key to the host system, e.g. using docker:
      `ARG SSH_PRIVATE_KEY`
      `RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa`

As a result of the above mentioned points, git+ssh is probably only usable in self-hosted renovate. Alternatively, could a js based ssh client be used? The [ssh2 npm package](https://www.npmjs.com/package/ssh2) seems to support both password and ssh-key authentication.

**Comment by rarkins** [comment]
In your use case, it’s a private git repo, right? But it does happen to support https auth too? Is it the same host as your platform or different?

**Comment by Tanuel** [comment]
> In your use case, it’s a private git repo, right? But it does happen to support https auth too? Is it the same host as your platform or different?

Yes, it is a private repo in a gitlab installation not available from outside our intranet. 

From my experience, most Git tools (GitHub, GitLab, BitBucket etc.) will allow cloning via ssh or https from the same url, meaning ssh `git@my-domain:my/repo.git` equals `https://my-domain/my/repo.git`. I guess `http` would also be supported in many cases

**Comment by rarkins** [comment]
I'm happy if we solve the problem of self-hosted only first, i.e. a situation where you could use Docker volumes to map an SSH key into `/home/ubuntu/.ssh/id_rsa`.

For the known hosts problem, this is perhaps something we could solve as part of the `git-tags` datasource. e.g. if we get an SSH url for a domain we haven't seen before then we call out to child process first to `ssh-keyscan`. I'm not sure though if this is practically any more secure than setting `ssh -o StrictHostKeyChecking=no` in env, but it's probably a better idea.

**Comment by Tanuel** [comment]
> I'm happy if we solve the problem of self-hosted only first, i.e. a situation where you could use Docker volumes to map an SSH key into /home/ubuntu/.ssh/id_rsa.

Users could provide a ssh key via host rule or other config, this gets put in a temporal file, then tell git to use that specific file for the host something like `GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_example"` [source](https://superuser.com/a/912281) (or [write in in a config](https://superuser.com/a/232406))

Would still be much easier to just fully mount the .ssh directory or how we use it in a self-created docker image:
```docker
FROM alpine:3.10 as intermediate
ARG SSH_PRIVATE_KEY
RUN apk add --update --no-cache openssh
RUN mkdir /root/.ssh
RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa
RUN ssh-keyscan example.com >> /root/.ssh/known_hosts
RUN chmod 600 /root/.ssh/id_rsa

FROM alpine:3.10
COPY --from=intermediate /root/.ssh /root/.ssh
# install everything needed: yarn git curl openssh php7 composer renovate etc.
CMD ["yarn", "renovate"]
```

> For the known hosts problem, this is perhaps something we could solve as part of the `git-tags` datasource. e.g. if we get an SSH url for a domain we haven't seen before then we call out to child process first to `ssh-keyscan`. I'm not sure though if this is practically any more secure than setting `ssh -o StrictHostKeyChecking=no` in env, but it's probably a better idea.

Im pretty sure scanning a host at runtime could always impose a security risk, however, here are a few ideas I came up with:

**Solution 1:** Users provide a known_hosts file via mount

**Solution 2:** Users provide known_hosts entries via config

**Solution 3:** Users can allow `ssh -o StrictHostKeyChecking=no` via config, e.g.

```javascript
{
  git: {
    strictHostKeyChecking: false
  }
}
