### ISSUE TITLE
Maven: implicit grouping by placeholder 

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4024]
If the Maven pom uses placeholders then we should support the option to group by placeholder implicitly. Maybe even use the placeholder name for “depName”.

This way all dependencies that share the same placeholder will always upgrade together in the same branch.

**Comment by rarkins** [comment]
@zharinov let's back off the PR and discuss again here. I'm not sure my last idea was a good one.

If multiple packages share a placeholder, then we want their updates grouped together implicitly. Grouping is pretty simple - if updates share the same branch name, they'll share the same PR.

If a placeholder is used only for one package, we ideally don't want any substantial change.
If more than one package is updated by a PR, we ideally want them all listed in the PR body like with normal grouping.

Could this be as simple as setting `groupName` equal to the placeholder name? In that case:
- Branch name will always be based off the placeholder name, so updates will be grouped
- If there's only one package updated then the package name will be used in the PR title
- If there's more than one package then the placeholder name (i.e. groupName) will be used in the PR title, and the version should be there too

**Comment by zharinov** [comment]
Yes, `groupName` usage may be the way to go I think
