### ISSUE TITLE
[Question] Renovate updating version property rather than individual dependency

### ISSUE THREAD

**Issue by Mert-Z** [renovatebot/renovate#4031]
### Which Renovate are you using?
CLI (self-hosted)

### Which platform are you using?
Self hosted GitHub

### Have you checked the logs? Don't forget to include them if relevant
Yes, logs are not relevant.

### What is your question?
So we have the following dependencies in our pom.xml (just including only relevant parts);
```
...
<properties>
    ...
       <jackson.version>2.9.9</jackson.version>
    ...
</properties>
<dependencies>
    ...
       <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>
    ...
</dependencies>
```

RenovateBot detected a new version for "jackson-databind" which is 2.9.9.1 and raised a PR as expected.

However changeset includes this;
```
<properties>
    ...
-        <jackson.version>2.9.9</jackson.version>
+        <jackson.version>2.9.9.1</jackson.version>
    ...
</properties>
```
eventually this causes an update of the other jackson dependencies which relies on "jackson.version" placeholder (as if they are grouped) and causes PR build to fail as those components don't have such a version released.

So can renovate just update the version of the related dependency? Is there some kind of limitation on renovate around sharing version properties? What would be the best practices if that's the case? Should we have individual version properties for the components? Can renovate try to locate common denominator version for multiple dependencies relying on same version property?

Thanks

**Comment by rarkins** [comment]
Will close this in favour of #4024
