### ISSUE TITLE
[python] Add support for --extra-index-url

### ISSUE THREAD

**Issue by aexvir** [renovatebot/renovate#4035]
In our current setup, we don't want to enforce the registry to be used, and we usually specify an extra index url where the packages can be found.

This can be found in the `requirements.txt` and `requirements.in` files

Example `requirements.txt`:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
--extra-index-url https://pypi.example.com/pypi

arrow==0.12.1
attrs==17.4.0
certifi==2018.1.18        # via requests
cffi==1.11.4              # via pynacl
chardet==3.0.4            # via requests
click==6.7                # via flask
```

Generated from some `requirements.in` file like:

```
structlog
raven
redis
requests
webargs

--extra-index-url https://pypi.example.com/pypi
our-private-package
```

**Comment by rarkins** [comment]
Can you provide an example file?

Also, how are you using `requirements.in` and `requirements.txt` with Renovate today? I thought that's something we don't really have complete support for already, because we'd need to (a) skip updating `requirements.txt` directly, (b) auto-update it instead any time `requirements.in` is changed

**Comment by aexvir** [comment]
Updated my first message with an example. Sorry if my message has been misleading. We don't use the `requirements.in` files directly. We use [`pip-compile`](https://github.com/jazzband/pip-tools) to generate the `requirements.txt` files and we have those committed to our repository.

We don't use the `*.in` files anything else than generating the `*.txt` files

**Comment by rarkins** [comment]
Do I understand this right?
- specify index-url and it overrides the default/public pypi
- specify only extra-index-url and it provides a second index to check if packages aren’t found on the public pypi registry

**Comment by aexvir** [comment]
Yep, that is correct, mostly.

If [`--index-url`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-index-url) is not set then it's assumed to be https://pypi.org/simple
[`--extra-index-url`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-extra-index-url) allows specifying more indexes where to search besides on the `--index-url`

So both can be used at the same time. From your message I'm not sure if that's considered.

**Comment by rarkins** [comment]
Ok so by default (no URLs) we leave `registryUrls` blank.

If index URL is found then we populate `registryUrls` with that URL.

Now:
- if extra URLs are found then put them all in `registryUrls` array
- if no index URL in addition then add the default index at the start of the array

**Comment by aexvir** [comment]
That should work. Although it might be simpler this way:

default: `registryUrls = [https://pypi.org/simple/]`
if `index-url`: `registryUrls = [https://custom.index.org]`
if `extra-index-url`: `registryUrls.push(...extraIndexes)`

The downside would be that if nothing it's set you would still hardcode the index to `https://pypi.org/simple/`, which could cause some issues. But it seems [that's already the case?](https://github.com/renovatebot/renovate/blob/cfaa33423660a5e4f7880933078c22513af94bc7/lib/datasource/pypi/index.js#L31)

Also, I haven't checked fully, so I'm not 100% sure how `pip` it's being run by `renovatebot`. But this configuration could also be leveraged to the standard `pip.conf` file, the same way as the `.netrc` file can be used for authenticating to those private PyPI repositories.

**Comment by rarkins** [comment]
It’s a little subtle but we don’t want to fill in `registryUrls` with the default as otherwise it makes it harder for someone to override it via config. 

We also do all lookups internally and don’t use `pip` itself. 

Finally IIRC we prefer to use the non-simple pypi.org registry as it provides richer metadata.

But in general we’re in agreement on the steps to take

**Comment by aexvir** [comment]
Oh, I see... so how would the authentication to the private registries work? The only way I can see that working would be by setting the credentials in the URL itself, but that doesn't seem to be a good solution for the configuration saved in the repository itself.

In our case we are self-hosting it, so I'd probably do the configuration in the server level, and I wanted to use the `.netrc` and `pip.conf` standard files for this, but it won't work if `renovatebot` doesn't use pip underneath

**Comment by rarkins** [comment]
You can set credentials using `hostRules`, including in the bot's `config.js`. Renovate itself doesn't detect `.netrc` or `pip.conf` when self-hosting although that's a feature we could consider a PR for if anyone really wanted it.
