### ISSUE TITLE
Gitea support

### ISSUE THREAD

**Issue by jgarec** [renovatebot/renovate#4042]
**What would you like Renovate to be able to do?**
Add gitea as a supported platform (like gitlab / github / ...)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
URL : https://gitea.com
Sandbox : https://try.gitea.io
API : https://gitea.com/api/swagger

**Comment by tobru** [comment]
I would love to see Gitea support. It's sad to see that the work in #4039 hasn't been progressed more.

**Comment by ppmathis** [comment]
I am also interested in Renovate supporting Gitea as a platform. I started working on implementing this feature and will submit a PR in a few days once I've ironed out some details.
