### ISSUE TITLE
Release candidate version detected

### ISSUE THREAD

**Issue by alexsavio** [renovatebot/renovate#4047]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
We have in our Pipfile a dependency `marshmallow==2.9.1` which has had many release candidate releases `3.0.0rc` in the last years: https://pypi.org/project/marshmallow/#history
The Renovate bot has done a PR to our repository: https://github.com/enter-at/lambda-handlers/pull/49 pinning the version 3.0.0 which is not available yet. Of course, CI/CD fails to find the version pinned by Renovate.

**Did you see anything helpful in debug logs?**
https://renovatebot.com/dashboard#github/enter-at/lambda-handlers/79266959
A wrong `toVersion` value:
``` 
{
    "depType": "dev-packages",
    "depName": "marshmallow",

    "currentValue": "==2.19.5",
    "datasource": "pypi",
    "updates": [{
        "fromVersion": "2.19.5",
        "toVersion": "3.0.0",
        "newValue": "==3.0.0"
    }]
}
```

**Comment by rarkins** [comment]
Thanks for reporting. I've found the problem within our pypi datasource, will fix.
