### ISSUE TITLE
No debug logs in Dashboard

### ISSUE THREAD

**Issue by Xenonym** [renovatebot/renovate#4053]
**What Renovate type are you using?**
Renovate GitLab App.

**Describe the bug**
There are no repository job logs in the dashboard for the private repo `bantulife/workspace`, and a requested rebase on a PR has not been performed even after a day. I am unsure if Renovate is missing our repository or there are no recent logs to view. 

**Did you see anything helpful in debug logs?**
I don't see any debug logs. 😓 

**Expected behavior**
I should be able to see some debug logs / the PR should have been rebased.

**Comment by rarkins** [comment]
This repo got flagged as stale (no commits to base branch for 2+ months) so skipped out from regular servicing. Ideally we should show this in the dashboard and have a way to trigger a manual job in such a case.

I have unflagged it as stale and you should see it picked up for a job in the next few hours.

**Comment by Xenonym** [comment]
Thanks for looking into it @rarkins!

> This repo got flagged as stale (no commits to base branch for 2+ months)

Could I clarify what you mean by `base branch`? The only branch listed in `baseBranches` of `renovate.json` has definitely been active (commits daily). Is there another setting for this I should configure?

**Comment by rarkins** [comment]
I should have actually written *default branch*. I think our check for this may need to be updated to look at base branch. I'm guessing your base branch is different from default branch?

**Comment by Xenonym** [comment]
> I'm guessing your base branch is different from default branch?

That's right.

However, even considering only the default branch (is this `master`?), I just checked and we only added Renovate to the repository almost exactly one month ago, so it can't have been stale for 2+ months.

**Comment by rarkins** [comment]
This should now be resolved
