### ISSUE TITLE
[Question] Bitbucket-server removes approvals on update

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/renovate#4060]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket Server v5.16.6

### Have you checked the logs? Don't forget to include them if relevant
If I can get the issue to show up again I will. Maybe a few days though.

### What is your question?
A bit of background into the scenario, assuming there are two PRs to the same project:
1. User approves both PRs
2. Renovate runs and merges one
3. Renovate runs and rebases
    Note: This causes the approval to be removed
4. Renovate runs but doesn't merge because PR no longer has approvals

Under Pull Requests -> General we do have the following settings
![Screen Shot 2019-07-12 at 17 30 45 PM](https://user-images.githubusercontent.com/3490825/61164572-4c7baa00-a4cb-11e9-98fb-ef84dca641b7.png)

But to my knowledge Renovate doesn't change the source branch when rebasing so I'm unsure why we are losing the approvals. Other information that maybe useful:
 - We have turned everything off in Merge checks
 - Merge strategy is Fast-forward--ff
 - The only workflow hooks that are enabled are a commit checker to make sure an issue is attached to the PR and the Jenkins CI hook

The ultimate question here is what config can I setup so that upon rebase, I don't lose approvals?

**Comment by rarkins** [comment]
Transferring this to the main repo for discussion with @ViceIce and @iamstarkov.

I would expect approvals to be lost if you had the "Unapprove automatically on new changes" option checked. But as you mention, we're not changing the source branch. We do a "git force push" which does not change the source branch, but maybe BB server could have a bug that is triggered by it.

**Comment by ViceIce** [comment]
bb server removes approvals on all source code changes and a force push is a change for bb.

**Comment by rarkins** [comment]
@ViceIce 	that seems to contradict this option, doesn't it?
![image](https://user-images.githubusercontent.com/6311784/61168882-eb98b400-a554-11e9-9f7a-1e7524090c77.png)

**Comment by ViceIce** [comment]
ok, then it seems that force push is a source branch change.

a force push changes to ref so this is ideed a source branch change

**Comment by rarkins** [comment]
So it sounds like the option is incorrectly labeled if so. It says "source branch" but it seems to be behaving as "source ref"

**Comment by ViceIce** [comment]
i think it is because a force push can change anything

**Comment by rarkins** [comment]
Yes but the PR hasn't changed its target branch, no matter what we force push, so that's why I think their option is either (a) incorrectly described, or (b) buggy

**Comment by k2snowman69** [comment]
Thanks to this conversation I was able to determine the set of google keywords to search and stumbled on a Jira ticket seemingly related to this
https://jira.atlassian.com/browse/BSERV-7673

I'll see if I can determine which version of the plugin we are using (will require me hunting down an admin) but I'm unsure the PR attached to the issue would prevent removals after a force push

**Comment by rarkins** [comment]
OK, I'm going to close this issue then as it doesn't seem like we can do anything. Please update if/once you find out an answer to this, in case anyone in future stumbles on the issue too

**Comment by iamstarkov** [comment]
Yes, it’s not related to renovate adapter
