### ISSUE TITLE
[Feature Request] Add support for GOPROXY env variable

### ISSUE THREAD

**Issue by tzilist** [renovatebot/renovate#4071]
**What would you like Renovate to be able to do?**
I'd like to be able to use the GOPROXY env variable when renovate runs the `go get` command while updating. 

**Describe the solution you'd like**
I think this could be something you set when you start renovate, perhaps? Ideally this should be passed to the `go get` command or just set wherever the command is run.

**Describe alternatives you've considered**

**Additional context**
N/A

**Comment by rarkins** [comment]
Is this for self hosted?

**Comment by tzilist** [comment]
Ah sorry should have specified! Yes, this would be for self hosted 😊
