### ISSUE TITLE
Idea: separate npm/yarn/pnpm/lerna package managers

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4093]
The existing "npm" manager in Renovate is really complex, partly due to its combination of npm/pnpm/yarn/lerna. I wonder if it would be feasible to separate them into separate package managers, albeit with a lot of shared code.

npm - if `package-lock.json` or `npm-shrinkwrap.json` are present, or no other managers are present (i.e. it's the default)
yarn - if `yarn.lock` is present. But not if there's lerna?
pnpm - look for pnpm's lock files
lerna - does it take precedence over yarn workspaces, or does yarn workspaces mean we can ignore lerna?

**Comment by viceice** [comment]
superseeded by #5607
