### ISSUE TITLE
config-validator in docker image

### ISSUE THREAD

**Issue by ZyanKLee** [renovatebot/renovate#4097]
**What would you like Renovate to be able to do?**
when running renovate/renovate docker image I would like to use renovate-config-validator for CI purposes.

**Describe the solution you'd like**
Please add the renovate-config-validator.js to the docker image as well

**Describe alternatives you've considered**
I might continue to build my own docker image for this purpose

**Comment by rarkins** [comment]
We use the main `renovate` process as the entrypoint for the image. The validator is still there. You might be able to run it as long as you modify the entrypoint, e.g. something like `docker run --rm --entrypoint=/usr/src/app/dist/bin/config-validator.js ....`

**Comment by ZyanKLee** [comment]
Thanks for your quick reply.

I override the entrypoint to circumvent problems with jenkins, so that's not an issue for us.

Though I can't find the directory `/usr/src/app/dist/bin` - `renovate.js` is directly in `/usr/src/app/dist/`.

**Comment by rarkins** [comment]
Sorry, if it’s there then it will be under ./bin/ and not ./dust/bin/. We can add it if missing

**Comment by ZyanKLee** [comment]
There is only a `yarn-1.9.4.js` in ./bin

**Comment by rarkins** [comment]
We need to update https://github.com/renovatebot/renovate/blob/master/.dockerignore and see if the validator works after that build
