### ISSUE TITLE
Optional stale branch pruning

### ISSUE THREAD

**Issue by richardcornelissen** [renovatebot/renovate#4106]
**What would you like Renovate to be able to do?**

We've setup Renovate for our BitBucket Cloud repositories, but Renovate autoclosed PR's and deleted "orphan" branches that were still in progress.

I believe this behavior is due to the expectation that branches automatically get all commits from the main development branch merged into them. ❓

With our workflow, Renovate almost accidentally deleted code it shouldn't have.

**Describe the solution you'd like**
Add a config flag `enablePruning` (default `true`) to make stale branch pruning optional. If false, skip pruning but log what would have been applied if it was enabled (same as dryRun).

**Describe alternatives you've considered**
None

**Additional context**
* We're using BitBucket Cloud
* Renovate is run on a scheduled BitBucket pipeline

**Comment by rarkins** [comment]
I'm wondering if this is because we are not detecting "modified" PRs in Bitbucket Cloud yet? @ViceIce @iamstarkov

**Comment by ViceIce** [comment]
https://github.com/renovatebot/renovate/blob/642deb0b8330a9fafdc6a1f5c80ed14eb8d01178/lib/platform/bitbucket/index.ts#L539-L549

We only look for a single commit here, but we don't check if it's our commit. so we should add somthing like tthat for server:
https://github.com/renovatebot/renovate/blob/642deb0b8330a9fafdc6a1f5c80ed14eb8d01178/lib/platform/bitbucket-server/index.ts#L803-L833

**Comment by ViceIce** [comment]
I'll send a fix

**Comment by ViceIce** [comment]
@richardcornelissen do you have some debug logs for us? That would help to identify the problem. 

Some time ago i had a similiar issue: renovate could not find the updates on second run and has deleted the branch / autoclosed the pr.

**Comment by richardcornelissen** [comment]
@ViceIce I'll check whether I can create some locally with debug logging
In the meantime, I did create a PR for configuring pruning

**Comment by richardcornelissen** [comment]
@ViceIce I'll try to reproduce it tomorrow on a separate bitbucket cloud repository (otherwise we'll get the same issues with branches disappearing)

**Comment by ViceIce** [comment]
@richardcornelissen #4111 hopefully fixes your issue. Renovate should now detect changed pr's.
