### ISSUE TITLE
PR title not updated with right dependency version

### ISSUE THREAD

**Issue by simoneb** [renovatebot/renovate#4112]
**What Renovate type are you using?**

GitHub App

**Describe the bug**

1) Renovate created a PR to update a dep version to 0.2.7 (build was broken, not sure if it makes any difference)
2) The Renovate PR received commits by using the GitHub "Update Branch" button which updates the PR branch with the main branch
3) a new version of the dep was released, 0.2.8
5) Meanwhile this issue happened: https://github.com/renovatebot/presets/issues/131
6) I checked the "If you want to rebase/retry this PR, check this box" so that Renovate would retry the PR
7) Renovate force pushed to the PR to update the dep to version 0.2.8, but the PR kept the title "fix(deps): update dependency {...} to v0.2.7"

**Did you see anything helpful in debug logs?**

No

**Expected behavior**

Renovate should also update the PR title to match the version of the dependency that the PR contains.

**Comment by simoneb** [comment]
oh, and of course as soon as I created this issue Renovate decided to update the PR title. so this is no longer an issue, but ~30 minutes passed between Renovate force pushing the commit where it updated the version to 0.2.8 and the change to the PR title to include 0.2.8 instead of 0.2.7. it's a bit misleading, it would be nice if the two things were happening at approximately the same time

**Comment by rarkins** [comment]
Can you locate the job number where the force push happened? From dashboard logs

**Comment by simoneb** [comment]
Must be either 80830398 or 80835125 based on the timing, can't see a reference to the specific commit anywhere though.

**Comment by rarkins** [comment]
80835125 logs that the PR was updated successfully with the new title. I've never seen this fail, so I can only conclude that there was some type of caching problem in the GitHub UI
