### ISSUE TITLE
Composer: Inject custom repositories via config

### ISSUE THREAD

**Issue by Tanuel** [renovatebot/renovate#4115]
**What would you like Renovate to be able to do?**
Composer Plugins can define custom repositories via [RepositoryManager](https://getcomposer.org/apidoc/1.0.0-alpha11/Composer/Repository/RepositoryManager.html)

Renovate's `composer/extract.js` has no chance of detecting such custom configuration from plugins.

To work around this, i would like to be able to inject a custom repositories configuration.

**Edit:** i have described the problem more in detail [here](https://github.com/renovatebot/renovate/pull/4055#issuecomment-511116694)

**Describe the solution you'd like**

Add a configuration field under [composer](https://renovatebot.com/docs/configuration-options/#composer) named customRepositories (alternative naming suggestions are welcome)

This solution only requires 4 lines of code (and a bunch of documentation and tests).

**Describe alternatives you've considered**

I came up with two alternatives, which are suboptimal and more complex to implement

1. Read source from composer.lock file
1.1 Add all sources from composer.lock to repositories - would result in fully working around packagist (really bad idea)
1.2 Look up dependencies inside extract.js, if not found read from lockfile and use that source. This solution feels confusing and unpredictable compared to how composer works.
1.3 If a package changes its source-url, renovate might not be able to update it (edge case, but a possibility)
2. Use native `composer outdated`, but this [should be avoided](https://github.com/renovatebot/renovate/pull/4055#issuecomment-511114214)

**Additional context**
I have created an implementation and will create a PR

**Comment by rarkins** [comment]
@Tanuel can this be solved by adding `registryUrls` now?

**Comment by Tanuel** [comment]
I didn't follow the recent changes closely, did i miss something or has this been possible all along?
