### ISSUE TITLE
Integrity check failure for yarn offline mirror

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4126]
Mm, one more clue maybe: I returned back to master and deleted the branch to continue working on something else. Then I returned back, checked out the MR again and there was no problem suddenly (`yarn install` was happy). So I deleted local Yarn cache (`yarn cache clean`) and tried again. This time I got this error:

```text
yarn install v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error https://registry.yarnpkg.com/flow-bin/-/flow-bin-0.103.0.tgz: Integrity check failed for "flow-bin" (computed integrity doesn't match our records, got "sha512-kTWKyK819ZuRxHBrkfup49QcMHvmIay8zgjph9e30/Xb49mcNUyQm+VLKipSeh6lWZsJ1S/F4jwJx8CwP9ZY6w==")
```

Something is definitely not OK with these MRs. Thanks for having a look.

_Originally posted by @mrtnzlml in https://github.com/renovatebot/renovate/pull/4102#issuecomment-513124459_

**Comment by rarkins** [comment]
My best guess is an issue with encoding. Does anyone know which CLI command can be used to generate the same checksum? e.g. `sha512sum x.tgz`?

**Comment by rarkins** [comment]
Whoops, there was an unneeded `utf8` in a readFile that was corrupting tgz files. I hadn't tested properly myself (e.g. clearing cache, offline, etc) sorry. Should be released and then live in the app soon.

**Comment by mrtnzlml** [comment]
Thanks! Looking forward to test it again. :)
