### ISSUE TITLE
Rate limit rebaseStalePrs

### ISSUE THREAD

**Issue by philippe-granet** [renovatebot/renovate#4145]
**What would you like Renovate to be able to do?**
Have a new parameter `rebaseStalePrsHourlyLimit` : 
Rate limit Rebase stale PRs to maximum x rebased per hour. 0 (default) means no limit.

**Comment by rarkins** [comment]
We can hopefully work out an elegant way to do this, but it needs some digging into the code and how we'd achieve it.

**Comment by rez-** [comment]
This would great for reducing the amount of concurrent builds in Jenkins whenever the merge requests need to be rebased.

**Comment by rarkins** [comment]
The amount of rebasing of stale PRs is directly tied to the number of open PRs. Why not reduce concurrent PRs further?

Also, I assume that you're really just wanting to limit how many commits you have, because every commit triggers a job? It's not necessarily about staleness alone?

**Comment by jjonescz** [comment]
Imagine you have 10 PRs created over time, with e.g., 1 hour between each PR created, so CI builds run in sequence, no pressure there. Then you merge one PR, the other 9 are rebased immediately and now all 9 CI builds run in parallel. That's my use-case.

Sure, there are solutions to this (disabling automatic rebase and triggering it manually; or limiting open PRs and manually selecting them in Dependency Dashboard), but option `rebaseStalePrsHourlyLimit` doesn't require manual input. For example, I could trigger "auto merge" on some of the open PRs, then forget about them and let Renovate + CI do their job without having many concurrent CI jobs (which create unnecessary pressure on the CI host).

**Comment by rarkins** [comment]
I had in mind the existing solution of `prConcurrentLimit`. 

Why have e.g. 10 concurrently open PRs in the first place and not e.g. 3? What good is a stale PR (i.e. stale because of this new feature blocking rebasing) compared to it simply being in the queue to be created once one of the three open ones are merged or closed? This approach also doesn't require manual input.

**Comment by philippe-granet** [comment]
> Imagine you have 10 PRs created over time, with e.g., 1 hour between each PR created, so CI builds run in sequence, no pressure there. Then you merge one PR, the other 9 are rebased immediately and now all 9 CI builds run in parallel. That's my use-case.

At work, we have the same problem, but with Gitlab-CI.  
To reduce pressure on our Gitlab runners, I have do that:
* launch renovate bot only at night, when developers sleep
* use tags (https://docs.gitlab.com/ee/ci/yaml/#tags) to launch jobs on branches `renovate/*` only on specific runners with limited concurrent build:
```yaml
variables:
  RENOVATE_TAG: ""

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^renovate\//
      variables:
        RENOVATE_TAG: "renovate"

build:
  tags:
    - tag-for-maven-jobs
    - $RENOVATE_TAG
  script: maven deploy ....
```
So build launched by renovate bot only execute on runners with tags `tag-for-maven-jobs` and `renovate`.

I think you can do similar thing with Jenkins using a specific agent with a low number of executors on that Jenkins agent, and build `renovate/*` branches only on that Jenkins agent.

But a `rebaseStalePrsHourlyLimit` option would be great :smile:
