### ISSUE TITLE
Renovate git dependencies

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#415]
Example: gulpjs/gulp.git#4.0

gulp 4 is not release to npm, even as a "future" or prerelease, so this is pointing to a branch in the repo: https://github.com/gulpjs/gulp/tree/4.0

Could we:
- Detect new tags/branches within a repo (e.g. 4.0.0, 4.0.1, 4.1, etc)?
- Detect when gulp 4.0 is released to npm and raise a PR for that?

I'm not sure the first is feasible, but the second would be desirable.

We could try this approach:

- If a git reference is used, then get the package's package.json off github to look up its npm package
- check if package name in that package.json matches the name in user's package.json (exit if not - it's probably a fork or something)
- get the package from npm and make sure that the repository matches (if not, it's probably a fork)
- see if there are any matching releases on npm
- we need a new classification - it would not pinning or upgrading, it would be..  "converting" dependency gulp from github to npm

I wonder how common this type of setup is though? e.g. how often does a repo:
(1) not publish a pre-release
(2) name a work-in-progress branch with a valid semver

**Comment by hbetts** [comment]
> Detect when gulp 4.0 is released to npm and raise a PR for that?

This would, as you said, be a really desirable feature. I'm not sure, though, how you would know whether the transition from repo URL reference to npm reference is desired on the part of the renovated repository owner? Would such a PR against my repository be unwanted?

Why I would want such a feature is for the following reasons:
* Pulling packages from an npm-compatible registry is considered best practice. Projects move around on GitHub/GitLab all the time. However, a project's name on an npm-compatible registry is static. It will never be moved, and probably never unpublished. While I currently encourage a lot of developers to use version 4 of GulpJS from GitHub, the instant version 4 is available on the npm registry, I plan on encouraging everyone to switch over.
* Once version 4 is available on the npm registry, I don't see the Gulp maintainers continuing the `4` branch on GitHub (they actually deleted the semver branch for the `gulp-cli` version that supports Gulp 4 after they published that version of `gulp-cli` to npm). Therefore, _converting_ package references is a way of maintaining continuity for consumers, and helping to align them with a project maintainer's current practice.

> I wonder how common this type of setup is though?

Well, semver support for GitHub is now a first-class feature in npm version 5. 

npm 5 release notes (`user/repo#semver:^1.2.3`) - http://blog.npmjs.org/post/161081169345/v500

So npm developed a feature to make it easier to use git repositories directly. That seems to anticipate a large desire to use branches on platforms like GitHub and GitLab.

**Comment by rarkins** [comment]
> Well, semver support for GitHub is now a first-class feature in npm version 5

Seems like this issue then has at least two parts:
1. Support git semver ranges starting with GitHub
2. "Porting" git URL dependencies back to npm

This second one is definitely "tricky" though:
- How to match to npm
- How to determine if there's a version on npm worth moving to

A common use case I've seen for GitHub URLs is that someone forks a package's repository, fixes a problem themselves - or perhaps hacks a feature - and then depends on `#master` of their own fork. In such cases I don't think there's anything `renovate` can do except warn the user that we're not watching/upgrading that. More generally, I think that if the repository they are depending on is not the same repository as l listed in the corresponding npm package's metadata (i.e. in package>repository>url) then we have to ignore. Perhaps though we still check if that tag exists on the repository and warn if it doesn't?

Then we're back to the case where someone is depending on a tag on the actual repository of the dependency, such as this gulp case. I can think of at least three ways this might be done:
1. Explicit semver ranges, e.g. instead of `gulpjs/gulp.git#4.0` it might be `gulpjs/gulp.git#semver:4.0`
2. Pointing to a branch/tag that happens to also look like a version, e.g. `gulpjs/gulp.git#4.0`
3. Other (e.g. `#master`, `#next`, `#fix/foo`

I can't see any way to renovate (3). (1) can definitely be renovated, e.g. to branch `4.1` if it gets created. Then, can (1) or (2) be intelligently "ported" back to npm? Is it enough to check:
- Is this the proper repository of the package of the same name?
- Are there any versions on npm matching the git tag being used currently?

**Comment by hbetts** [comment]
> I think that if the repository they are depending on is not the same repository as l listed in the corresponding npm package's metadata (i.e. in package>repository>url) then we have to ignore

Agreed.

For (2), I would just treat it as a pinned dependency, and when converting it to npm, just match it against a specific version.

I think, given that, your two bullet points are sufficient to make to convert a git repository reference to an npm package registry reference.

**Comment by felixfbecker** [comment]
I have a use case for this, for a repo we decided to depend on it raw from git because we just want the source. It would be great if Renovate was able to simply increase the commit hash specified after `#` to the latest HEAD of the default branch of the repository when new commits are pushed.

**Comment by rarkins** [comment]
@felixfbecker can you copy/paste what the exact reference looks like in your `package.json`?

**Comment by felixfbecker** [comment]
Yep:
```json
  "dependencies": {
    "@sourcegraph/webapp": "sourcegraph/sourcegraph#a0bb5545dec1faab7e7df35b58a375522b66c1a0"
  },
```
where the repo is github.com/sourcegraph/sourcegraph (private) and the commit hash is `a0bb5545dec1faab7e7df35b58a375522b66c1a0`

**Comment by rarkins** [comment]
I’ve been experimenting with this today and already have this particular use case working actually. Just need a little time to round off the edge cases and add tests. Expect it to be live in the app early next week.

**Comment by rarkins** [comment]
Unfortunately I need to take that back a little. GitHub *authentication* for private repositories is a whole other matter which would need to be worked out after in #817. We can update the lockfile but if `npm install` doesn't have credentials then the lock file part will fail. Seems npm only supports either (a) explicitly adding username/password into the `package.json` or (b) falling back to system git credentials. I will look into that afterwards.

**Comment by felixfbecker** [comment]
What authentication does Renovate have through the GitHub app?
I could also supply a GitHub token in Renovate config.
You can use a GitHub token in a GitHub git clone URL, and you could maybe write that to ~/.ssh/config.
But we’re also gonna open source that particular repo soon so if that already works that’s great.

**Comment by rarkins** [comment]
It's documented a little in #817. To `npm install` a private GitHub repo you need either an SSH key that's been authorised to the private repo being installed, or you need a full username:password exposed in the `package.json` to authenticate over HTTPS. As far as I'm aware, there's no way to take an app's token (specific for an installation only, valid for one hour) and use that for SSH authentication, so the only option is a username:password in the `package.json` definition. I'm thinking whether I can do a search/replace before and after lock file update to temporarily add the bot's token to the `package.json` before then removing it again after from it and the lock file.

**Comment by rarkins** [comment]
Yes, I was definitely meaning token but wrote `username:password` instead. I am doing some experimenting now with tokens and substitution.
