### ISSUE TITLE
Option: enable assignee/reviewer on automerging PRs too

### ISSUE THREAD

**Issue by jspenguin2017** [renovatebot/renovate#4153]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

https://renovatebot.com/dashboard#github/NanoAdblocker/NanoCore2/81437452

```
...
    "labels": [],
    "assignees": [
      "jspenguin2017"
    ],
    "reviewers": [],
...
```

### What is your question?

Although it looks like Renovate is picking up the correct config, it is not setting the assignee. 

In this PR: https://github.com/NanoAdblocker/NanoCore2/pull/12
Renovate did not set the assignee and I did it manually. 

The config file is here: https://github.com/jspenguin2017/Config/blob/master/renovate/package.json
I checked NPM registry, it has the correct config published. 

Is Renovate waiting for status check to pass before setting assignee? Is it possible to have it set assignee immediately?

**Comment by rarkins** [comment]
I've transferred this issue into the main repo to treat as a feature request

**Comment by jspenguin2017** [comment]
I can contribute, but I'm traveling this week, so it'll be next week or the week after.

**Comment by jspenguin2017** [comment]
Hi @rarkins , I just created a PR that implements this feature. Please review, thanks!
