### ISSUE TITLE
Slim Docker image

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4156]
Create a slim Docker image that doesn't include any of the third party binaries and instead uses Docker side containers for child processes.

**Comment by ViceIce** [comment]
Steps:

- [ ] add new `slim.Dockerfile` for slim build
- [ ] add new build rule to hub from branch `master` with location `slim.Dockerfile` and tag name `slim`
- [ ] add new build rule to hub from tag `/^v([0-9.]+)$/` with location `slim.Dockerfile` and tag name `{\1}-slim`
- [ ] add more rules for additional short version tags?

**Comment by ikesyo** [comment]
> `slim.Dockerfile`

IMO `Dockerfile.slim` seems more natural.

**Comment by ViceIce** [comment]
Was just a sample name. 😅

**Comment by ViceIce** [comment]
you have to add `-slim` to the docker tag

**Comment by rarkins** [comment]
Yes: `DOCKERFILE_PATH`

**Comment by ViceIce** [comment]
otherwise you will overwrite the other tag

**Comment by rarkins** [comment]
Good point.. I'm suspecting one or both of the hook scripts will fail though

**Comment by ViceIce** [comment]
no, i think they will simply skip because `SEMVER_REGEX` will not match

**Comment by rarkins** [comment]
That's what I meant by fail :)

**Comment by ViceIce** [comment]
but the slim tag should be there for testing :-)
