### ISSUE TITLE
ONLY rebase a branch if requested

### ISSUE THREAD

**Issue by andrewnitu** [renovatebot/renovate#4184]
**What would you like Renovate to be able to do?**
Currently Renovate is rebasing whenever there is a merge conflict with master. This is good behaviour, however unfortunately it is costing us a lot of CI cycles. 

There are currently a lot of big upgrades in our repo which are sitting idle with nobody working on them yet, so we don't need to keep them up to date with master. 

Hence I think it would make sense if you can entirely disable the auto-rebasing, so that now it only rebases if you tick the checkbox or apply a label. It would not rebase even if there are merge conflicts with master.

**Describe the solution you'd like**
A configuration option that disables auto-rebasing entirely, not sure what the name would be. Also it would be super helpful if it could be based on some sort of timer, e.g. if the PR is older than 1 week then do not auto-rebase anymore. I'm not sure if the timing condition is currently supported.

**Describe alternatives you've considered**
~~I can't think of any any alternatives to get this behaviour~~
Actually we could get around it by enabling that Renovate opens PRs only by approval from the master issue... but it doesn't really solve this problem, just avoids it by adding extra steps

**Additional context**
n/a

**Comment by rarkins** [comment]
Need to add new option `rebaseConflictedPrs` which is `true` by default
