### ISSUE TITLE
no-plan after changing billing mechanism

### ISSUE THREAD

**Issue by simoneb** [renovatebot/renovate#4214]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

Initially reported in https://github.com/renovatebot/config-help/issues/308. After changing the billing mechanism all our repos have been disabled and in the logs we would always see `no-plan`. Now we have purchased Renovate licenses again but the repos still show the same message.

**Additional context**

An example job: 83708507

**Comment by rarkins** [comment]
@simoneb your company's invoice still shows up as unpaid (sent to Stephanie on Friday). Please notify us at billing@renovatebot.com once it's paid so that we can activate the account.
