### ISSUE TITLE
packagist datasource: rename to composer?

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4216]
Is it more semantically correct that our "packagist" datasource should actually be named "composer"?

Ref: https://getcomposer.org/doc/05-repositories.md#composer

As suggested by @Tanuel

**Comment by rarkins** [comment]
Next question: is there any problem or major confusion if we have datasources named the same as package managers? e.g. We already have npm/npm and this would now be composer/composer.

**Comment by Tanuel** [comment]
Gonna provide some thoughts and background knowledge for those out of the picture (but who else reads this anyways?)

So this thought came to my mind during #4180.
Before the PR, `packagist.org` would be added within `datasource/packagist`, but this task has now been moved to `manager/composer/extract.js`.

While packagist is the default datasource of composer packages, it is not required and can be disabled, meaning composer can work entirely without packagist (e.g. using a dependency proxy like artifactory).
You can do similar stuff with npm using a `.npmrc` and point to your own registry `registry="https://my-registry.com"`

Regarding the confusion part: The composer docs themselves call it `Composer Repository` and there are no other package managers using this datasource. Renaming the datasource to composer could make this a bit more clear. A rivaling concept to composer does not really exist, but could arise, similar to yarn vs npm, but is not that likely atm.

To avoid confusion, it would maybe be helpful to provide a bit more documentation on the datasources, e.g. add a readme (`lib/datasource/packagist/readme.md`) or more in-file documentation, shortly explaining how the datasource works?

Tbh, I can't really make up my mind if this change makes sense. Devs who are experienced with composer should know that packagist is related to composer.

**Comment by rarkins** [comment]
I actually needed to add back functionality to packagist datasource to have it insert packagist.org if the registryUrls is empty. Any composer.json that’s missing a `repositories` entry needed this. In general we usually insert default registries in the datasource anyway, rather than managers.

**Comment by rarkins** [comment]
Adding a note: there's also a big advantage to avoiding confusion between manager and datasource names, by keeping them as separate names even if a little incorrect
