### ISSUE TITLE
Merge npmrc

### ISSUE THREAD

**Issue by Djaler** [renovatebot/renovate#4224]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate doesn't merge values from user .npmrc and project .npmrc. For example, I have this line in my `~/.npmrc`:
`registry=http://registry.npmjs.org/`.
I need this because my proxy doesn't work well with https.
And I have .npmrc in my project repo, where I set address for private registry.
And after this renovate can't check npm packages info because it looks to registry by https instead of http.

On this lines we can see that every new call to `setNpmrc` will overwrite previous config.
https://github.com/renovatebot/renovate/blob/0f19abd3443e3732ee02fa1659589b77660ce609/lib/datasource/npm/npmrc.js#L24

**Expected behavior**
I think values of all npmrc files should be merged instead of overwriting

You can check result npmrc config by adding log to this place:
https://github.com/renovatebot/renovate/blob/0f19abd3443e3732ee02fa1659589b77660ce609/lib/datasource/npm/get.js#L42

**Comment by rarkins** [comment]
Can we check if npm itself merges npmrc files? And if so then is it a simple merge or any complicated logic?

**Comment by Djaler** [comment]
Yes, it merges npmrc files. https://docs.npmjs.com/files/npmrc#files

**Comment by Djaler** [comment]
What about just do something like:
` npmrc = {...existingNpmrc, ...ini.parse(input.replace(/\\n/g, '\n'))};`

**Comment by rarkins** [comment]
As this is technically a breaking change for some, I need a little time to think about the best way to handle it. Having Renovate read off the local file system is something I'd prefer to avoid, because it's cleaner to have everything in the app.

**Comment by Djaler** [comment]
> What about just doing something like:
> ` npmrc = {...existingNpmrc, ...ini.parse(input.replace(/\\n/g, '\n'))};`

You don't need to read file system

**Comment by Djaler** [comment]
Hey, @rarkins, so what about it? ^

**Comment by rarkins** [comment]
We need to capture the various ways we can get npmrc configuration today, e.g.
- From the file system
- From config (e.g. `"npmrc": "aaaaaaaaaaaaaaa"`)
- From the repo (typically in the root of the repo, but not necessarily)

For the first two, I think that the configuration settings are applied "globally", i.e. to every `package.json` regardless if they're in a subfolder. For the last one, it only applies to the same directory `package.json` that the `.npmrc` is in.

I am tempted by one of the following:
- Completely stop supporting/detecting `.npmrc` files on disk (e.g. `~/.npmrc`)
- Support them, but read them once at startup and import them into config explicitly

**Comment by rarkins** [comment]
Doing this way would make merging much more predictable.

**Comment by ViceIce** [comment]
Currently it is also not possible to store repository credentials globally, because if we configure `npmrc` only that config is used.

if we do not set a config [registry-auth-token/registry-url](https://github.com/rexxars/registry-auth-token/blob/021fe4ae4e264c553e331cc188be9958b39decdb/registry-url.js#L2) falls back to `https://registry.npmjs.org/` but all available configs are read from disk with `rc` module.

I would like to overide the registry like on any other manager with `reggistryUrls`.

And we should support `hostRules` to pass authentication information for specific registry.

**Comment by rarkins** [comment]
Do you think we can safely “craft” an npmrc based on our regustryUrls and secrets config?

**Comment by ViceIce** [comment]
`NPM_PASSWORD` has to be `base64` of cause

**Comment by ViceIce** [comment]
Idea for config merging:

* Make `npmrc` option object
* Add config migrate for `npmrc` option
* Parse `.npmrc` as ini at `manager/npm/extract` (so default config merge works)
* Use `npmrc` object from config at `datasource/npm/npmrc`

Use [rc](https://www.npmjs.com/package/rc) package to find additional npmrc config files?

**Comment by rarkins** [comment]
> Make npmrc option object

I'm not sure about this. Do you mean like one key/pair for each line in the file? Also I think we won't be able to validate this, e.g. with JSON schema. What would we gain from this instead of making it a string with `\n`s and making sure we do an intelligent merge somewhere?

**Comment by rarkins** [comment]
btw I think ini is intelligent enough that later lines override earlier lines, right? i.e. to "merge" init files you can actually just concatenate them and then let ini handle the duplication/overrides?

**Comment by rarkins** [comment]
Also a key point is where/how to deal with npmrc files within the repo when we are calling "npm install". e.g.
- Leave it in place and put our own "handcrafted" `.npmrc` into `~/.npmrc` and let `npm` merge?
- What if the one in the repo contain environment variables, causing npm to fail because it can't resolve them? Do we let users configure us to *remove* the repository `.npmrc` file before install, or let them configure environment variables instead?

**Comment by ViceIce** [comment]
> btw I think ini is intelligent enough that later lines override earlier lines, right? i.e. to "merge" init files you can actually just concatenate them and then let ini handle the duplication/overrides?

Could be an option too, but then we have to extend our config merge algorithm, because currently it will simply override the global npmrc with the repo specific.

**Comment by ViceIce** [comment]
Renovate uses the global npmrc config for fetching presets.
But when fetching updates it use the repo config.

**Comment by rarkins** [comment]
Renovate has dropped support for user `~/.npmrc` so we won't be implementing this.
