### ISSUE TITLE
docs: Improve docker registry authentication  documentation

### ISSUE THREAD

**Issue by RmStorm** [renovatebot/renovate#4227]
**What would you like Renovate to be able to do?**
I would like to request a change to the documentation: https://renovatebot.com/docs/docker/

**Describe the solution you'd like**
I would like to add a clear example of how to add multiple docker hostrules for different image repositories.

**Describe alternatives you've considered**
I tried to find if I could contribute to the docs directly but only the developer docs are in the repository, e.g. [here](https://github.com/renovatebot/renovate/tree/master/docs). These are fine, it's the main documentation that I would like to improve.

**Additional context**
Currently [this section](https://renovatebot.com/docs/docker/#registry-authentication) says:
- If you are running your own Renovate bot, add this to your `config.js`:

I think this is a typo and should be changed to:
- If you are running your own docker registry, add this to your `config.js`:

In addition to that small change I think the example config should have an example of how to use multiple repositories, this works:
``` javascript
module.exports = {
  hostRules: [
    {
      hostType: 'docker',
      baseUrl: 'https://index.yourdomain.io',
      username: '<your-username>',
      password: '<your-password>',
    },
    {
      hostType: 'docker',
      username: '<a-default-username>',
      password: '<a-default-password>',
    },
    {
      hostType: 'docker',
      baseUrl: 'https://index.docker.io',
      username: '',
      password: '',
    },
  ],
};
```
and that configuration is identical to:

``` javascript
module.exports = {
  hostRules: [
    {
      hostType: 'docker',
      baseUrl: 'https://index.yourdomain.io',
      username: '<your-username>',
      password: '<your-password>',
    },
    {
      hostType: 'docker',
      baseUrl: 'https://index.docker.io',
      username: '',
      password: '',
    },
  ],
};
```
with `DOCKER_USERNAME=a-default-username` and `DOCKER_PASSWORD=a-default-password`

Renovatebot works really well! But this configuration was quite hard to figure out. It would be nice to save other people whom pull images from multiple repositories the difficulty of figuring it out on their own.

Being able to make PR's directly to the main documentation would also be nice to have.

**Comment by rarkins** [comment]
Hi, thanks for the suggestions. You can find that doc page here: https://github.com/renovatebot/renovate/blob/master/website/docs/docker.md

**Comment by RmStorm** [comment]
thanks @rarkins I will make a PR with some suggested changes.
