### ISSUE TITLE
Fix or replace codecov

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4247]
Status checks fail to be set on up to half of PRs. It seems to be a known problem for a while and possibly related to CircleCI. Codecov support has acknowledged and will look into it next week.

Either:
- fix codecov
- switch to coveralls (in the past I got a better impression of codecov though)
- custom (eg use circleCI's native coverage UI + fail the test run if 100% not achieved)

**Comment by rarkins** [comment]
Based on past bug reports, I'm guessing that the problem is related to both node 10 and node 12 uploading reports.

Also, the codecov orb seems like a simple wrapper around the bash uploader and no point in using instead.

**Comment by ViceIce** [comment]
Isn't this fixed with #4295?
