### ISSUE TITLE
Bug: changing PR/MR target branch causes endless rebases

### ISSUE THREAD

**Issue by dmfay** [renovatebot/renovate#4248]
**What Renovate type are you using?**
Renovate Bot on GitLab

**Describe the bug**
Renovate Bot opened a merge request updating a dependency in my Node.js project to a new major version. Not wanting to land this on `master` yet, I retargeted the merge request to the `v6` branch where work on _my_ next major version is happening. Renovate Bot proceeded to get stuck in a loop committing the same package.json and package-lock.json changes over and over again until I closed the merge request.

**Did you see anything helpful in debug logs?**
No logs, but [here's the merge request in question](https://gitlab.com/dmfay/massive-js/merge_requests/710). The three commits landing at once before the spam starts seem of particular interest: I had been managing a few other Renovate merge requests within a few minutes of the incident, and one (which got merged into `master`) had updated the same dependency to a new patch version. It appears to have rolled this prior commit into the merge request, even though that commit should only appear on `master`.

**To Reproduce**
Uncertain, but here's what I suspect might have caused it:

1. Before anything happened, pg-promise was at 8.7.4 on both the `master` and `v6` branches.
2. I merged Renovate Bot's pull request updating pg-promise to 8.7.5 on `master`.
3. I retargeted Renovate Bot's pull request updating pg-promise to 9.0.0 on `v6`.

**Expected behavior**
Renovate Bot should have rebased its changes cleanly onto the new branch without including the new commits on `master` and without spamming the merge request.

**Comment by rarkins** [comment]
Based on the logs, this logic path is being taken: https://github.com/renovatebot/renovate/blob/6de255e18de288ac39a4c678fc79db2e19ab229c/lib/platform/gitlab/index.ts#L731-L734

At the same time, it seems like we're returning pr.canRebase=true because Renovate Bot is still the last committer for the MR.

Ideally we could detect the change of target branch and return pr.canRebase=false. I'm surprised that GitLab returns `pr.merge_status === 'cannot_be_merged'` every time though.

**Comment by rarkins** [comment]
Solution (I think): check if the MR's target branch is still equal to `config.baseBranch` and if not then set pr.canRebase=false

**Comment by dmfay** [comment]
Another merge request has gone horribly wrong, this time several days after I changed the target branch: https://gitlab.com/dmfay/massive-js/merge_requests/700

**Comment by rarkins** [comment]
Please try not to change target branch until we can resolve the issue. If we get runaway accounts we unfortunately have no choice but to block them. 

FYI it is possible for you to configure multiple "baseBranches" using Renovate config, e.g. directing major-only updates to your dev branch and minor/patch updates to your master, so please use that as an alternative.
