### ISSUE TITLE
Bug with renovate automerge config

### ISSUE THREAD

**Issue by Fandekasp** [renovatebot/renovate#4250]
I setup the renovate configuration to auto-merge all non-major releases, but only patches seem to be auto-merged at the moment.

renovate config:

```json
{
  "automerge": true,
  "major": {
    "automerge": false
  },
  "requiredStatusChecks": null
}
```

![](https://i.imgur.com/RQLdIit.png)

**Comment by rarkins** [comment]
Does the PR say "Automerge: enabled" or "Automerge: disabled by config"?

Are you 100% certain that patches are automerged?

And if you search a log file on dashboard, what does it say about automerge and that branch?

**Comment by Fandekasp** [comment]
@rarkins you're right. Maybe it's better to use this link instead then: https://github.com/wagtail/wagtail/tree/master/docs/releases

**Comment by Fandekasp** [comment]
@rarkins looks like a false alert. The PR finally got merged, although much later than others. Closing, thanks for the quick reply
