### ISSUE TITLE
Volta support

### ISSUE THREAD

**Issue by maraisr** [renovatebot/renovate#4262]
**What would you like Renovate to be able to do?**
Much like renovate upgrades node in a `.nvmrc` file, it would also be nice to upgrade it in the volta property in the package.json file too.

**Describe the solution you'd like**
Whenever yarn, or node gets an upgrade within the ranges outlined in a config or something, to also upgrade it in the package.json file in the volta config.

**Describe alternatives you've considered**
Well right now, I just use a bash script to sync the volta properties from `.nvmrc`, but yarn I have to do manually. 

**Additional context**
See [volta.sh](https://volta.sh/) for more details or https://github.com/volta-cli/volta

**Comment by nihal9ns** [comment]
@rarkins I'll take this up!
