### ISSUE TITLE
yarn policies set-version support

### ISSUE THREAD

**Issue by lwilkins** [renovatebot/renovate#4263]
yarn supports enforcing a version of yarn to be used across the entirety of a project with `yarn policies set-version` (https://yarnpkg.com/lang/en/docs/cli/policies/). Running this command creates an artefact in a .yarn folder and adds an entry to the local .yarnrc file. I'd like Renovate to manage this update for me.

I've had a look for existing issues on this and the closest I've found is https://github.com/renovatebot/renovate/issues/2565. From what I understand, that issue is based around the version Renovate itself uses to make changes to the package.json and yarn.lock artefacts. This issue is focused on consumers of the repository which Renovates manages and the version of yarn they use. That said, Renovate could use the policies set-version mechanism to achieve the same goal?

**Comment by rarkins** [comment]
Do you know of any public repositories using this approach, or can you create a working example?

**Comment by lwilkins** [comment]
I've not come across it in the public repositories I've looked at recently. 

I've created a superficial example to help show what artefacts it creates https://github.com/lwilkins/yarn-set-policies-version-example

**Comment by bigpopakap** [comment]
I have an example of this [in this repository](https://github.com/bigpopakap/shared-node-tools), which is the monorepo for all my linting configs.

In there, you'll find a `.yarnrc` file and a `.yarn/releases` directory which are generated when I run `yarn policies set-version`. It would be awesome to have Renovate update this!

**Comment by pixelastic** [comment]
Same here; I use `yarn policies set-version` to download a local version of yarn in my project, to ensure the exact same version will be used by all contributors and CI servers.

You can see it in action in this repository: https://github.com/pixelastic/import2require

The `.yarnrc` file at the root of the repo is automatically generated by running `yarn policies set-version`

```.yarnrc
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


yarn-path ".yarn/releases/yarn-1.22.4.js"
```

It also creates the `.yarn` folder and directories like this:
```
.yarn
└── releases
    └── yarn-1.22.4.js
```

Note that running `yarn policies set-version` always updates to the latest released yarn version (unless a specific version is provided). But it **does not** delete previous versions from the `.yarn/releases` folder; this is something that ideally renovate should automatically do

FYI, I currently have a custom script that I use to automatically update my local yarn version and clean the `.yarn/release` folder:

```zsh
#!/usr/bin/env zsh
set -ex

# Download latest version
yarn policies set-version

# Rename current yarn so we don't delete it
currentYarn=`yarn config get yarn-path`;
mv ${currentYarn} ${currentYarn}.back

# Delete all old yarn
rm -r ./.yarn/releases/*.js

# Move yarn back
mv ${currentYarn}.back ${currentYarn}
```

**Comment by pixelastic** [comment]
> Note that running yarn policies set-version always updates to the latest released yarn version (unless a specific version is provided). But it does not delete previous versions from the .yarn/releases folder; this is something that ideally renovate should automatically do

Just added a clarification. It seems that latest 1.x yarn version do actually remove previous releases now.

**Comment by rarkins** [comment]
Out of interest, is it the same for Yarn v2?

**Comment by pixelastic** [comment]
I haven't fully switched to v2 so take that with a grain of salt but:

- v2 uses `.yarnrc.yml` instead of `.yarnrc`
- The command became `yarn set version {version}` after v1.22 (it was `yarn policies set-version {version}` before)
- v2 no longer uses a `node_modules/` folder but a logical wrapper on top (files are stored in `.yarn/cache` IIRC)

**Comment by bencooper222** [comment]
Would love support for this. If there's firm confirmation that it would be accepted, I could look into writing a PR for it.

**Comment by rarkins** [comment]
@bencooper222 please go ahead! Can you ensure it works for Yarn 1-3 though?

**Comment by thejan2009** [comment]
I think this was solved in https://github.com/renovatebot/renovate/issues/5230

**Comment by bigpopakap** [comment]
Hi, is it actually solved? It looks like that issue is about supporting Yarn V2, which to my knowledge doesn't necessarily mean it added support for updating the `yarn policy`.

It's still possible and likely that projects are on Yarn V1, but have a yarn policy specifying which _exact_ version they want. So if a new feature or bugfix comes out for Yarn V1, we'll want our projects updated.

Yarn V2 is not a simple migration for many projects, so I don't think "migrate to Yarn 2" is a good enough answer at this tim. (Hopefully at some point that will be more feasible, but it is not right now)

**Comment by viceice** [comment]
please provide a new reproduction repository to show invalid behavior of renovate and open a new discussion with that. then we can decide if there's anything missing.

I've now migrated some projects from yarn V1 to V3 (with node modules linker) and didn't had any major issues ( just some small package.json script changes), so a migration is no longer a pain or hard work
