### ISSUE TITLE
Allow packageRules based on npm semver ranges

### ISSUE THREAD

**Issue by UnleashMayhem** [renovatebot/renovate#4268]
**What would you like Renovate to be able to do?**
I would like to be able to set a package rule based on npm semver ranges, specifically for updates that fall within the ranges of `^1.0.0` or `~1.0.0` for example.  

This is so that I can automerge updates that fall within semver ranges, while still using a 'bump' range strategy to keep track of my updates.

**Describe the solution you'd like**
Something like: 
```
packageRules: [
    {
      updateTypes: ['semver-patch'],
      automerge: true
    }
```
where an update to something with range `~1.0.0` to `1.0.1` would automerge, but `1.1.0` would not. Have the same behaviour with 'semver-minor' but for `^` with the same behaviour. Or combine them both into the same updateType, I don't mind.

**Describe alternatives you've considered**
I've considered not using a 'bump' range strategy, but it has been really valuable to be able to see updates to npm packages in the `package.json` that could otherwise have been silent  or not easy to read when only updating `package-lock.json`.

**Additional context**
The conclusion of this article explains this idea in more detail: [How should you pin your npm dependencies and why?](https://medium.com/the-guild/how-should-you-pin-your-npm-dependencies-and-why-2b8d545c7312)

**Comment by rarkins** [comment]
Instead of "`~1.0.0` to `1.0.1`" did you mean "`~1.0.0` to `~1.0.1`"?

I'm trying to understand what you're really after. Is it your goal that you can use semver range symbols to control automerging? e.g. `~1.0.0` means Renovate should automerge any 1.0.x but not anything >= 1.1.0? And `^1.0.0` means automerge any 1.x?

Also have you evaluated rangeStrategy=bump vs rangeStrategy=update-lockfile? That may be a way to achieve what you want but you will have decreased visibility within `package.json`.

**Comment by UnleashMayhem** [comment]
Yes, that is exactly what I am asking for! My goal is to automerge based on semver range symbols.

If I were to change the rangeStrategy, would using updateTypes=['lockFileMaintenance'] work for automerging?
I have thought about trying to get something resembling what you suggested, but I really like the visibility shown with rangeStrategy=bump. Hence why I made this request.

**Comment by rarkins** [comment]
If you use rangeStrategy=bump then you'll get visibility in both `package.json` and the lock file, however there is no way to automerge based on whether it's an in-range or out-of-range update (as you observed).

If you use rangeStrategy=update-lockfile then you should be able to use updateTypes=['lockfileUpdate'] in a packageRule, *but* you lose some visibility from `package.json`.

**Comment by UnleashMayhem** [comment]
Yup I understand, thanks for explaining :) I have used lockfile updates before, but I haven't tried automerging based on lockfile updates.

But currently I prefer the visibility of the `package.json` over automerge. Ideally I would like both, and that's what I'm asking for here, an 'in-range`/`out-of-range` package rule of some kind.

**Comment by rarkins** [comment]
This is now supported via `matchCurrentValue`
