### ISSUE TITLE
Typos in Developer Docs

### ISSUE THREAD

**Issue by rakeshtembhurne** [renovatebot/renovate#4277]
**Describe the issue**
It's not a bug, but typos in the developer documentation. These docs are in `renovate/docs` section. 

**Expected results**
File: `renovate/docs/adding-a-package-manager.md`

> This document describes the steps to take if you are interest in adding new language/package manager support.

`are interest` should be `are interested`

**Other observations**
There are also many changes suggested by Grammarly apps about missing articles/determiner (a, an, the), missing commas and so on.

**Comment by rarkins** [comment]
I guess it’s fine to do a grammar sweep every now and then. I prefer not to have too many pedantic grammar changes in small batches
