### ISSUE TITLE
rate limit per org (or renovate run)

### ISSUE THREAD

**Issue by jsi-ka** [renovatebot/renovate#4279]
**What would you like Renovate to be able to do?**
- I want a max num of PR creation per renovate run (not per repo)

**My problem**
- I have 150 micro services
- our jenkins based CICD can get swamped easily
- we want to automatically maintain the dependencies and the Dockerfiles with Renovate
- I use github repo autodiscovery and filter the repos (one per service, I have 150 to process)
- my problem is if Alpine change his image version - for example - our jenkins is swamped with PR validations jobs 

**Describe the solution you'd like**
I want a prHourlyLimitGlobal to set a maximum PR creation (or modification) per Renovate run and exit after the max is reached

**Describe alternatives you've considered**
- breakdown my repos list in smaller batches of 10-20 repos and schedule them every 2 hours but it s not very maintainable
- prHourlyLimit ? but it s per repo so for me it not useful apparently

**Additional context**

**Comment by rarkins** [comment]
`prHourlyLimitGlobal` sounds fine as a new option, should be classified as admin-only

**Comment by jsi-ka** [comment]
Hi ! yes or prChangeMax.. In my mind it s not a rate really it s just a number of changes per run. My suggested naming of this new parameter was not good really

**Comment by rarkins** [comment]
I guess that's true, because we probably wouldn't cache the hourly number to disk between runs, so implementing a maximum per run is a lot easier too.

**Comment by bmish** [comment]
I'm also very interested in a per-run PR rate limit, see my ideas in #4413.
