### ISSUE TITLE
Bitbucket Server LFS File Locking

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4289]
I discovered today that Bitbucket Server apparently supports a feature to "lock" files, which could include files that Renovate needs access to, such as `package.json` or `pom.xml`. I'm raising this issue to discuss whether there's anything we need to do specially to handle this scenario. 

If, for example, a `package.json` is locked then would that prevent us from making a PR in a renovate branch? i.e. does this locking apply to every branch or just to the one being locked, e.g. `master`? If so then it would only prevent automerging, and is perhaps already handled gracefully today, even if we don't "know" why the error occurs.

**Comment by rarkins** [comment]
Cc @ViceIce @iamstarkov

**Comment by ViceIce** [comment]
I've never used git lfs. 🤔 

https://github.com/git-lfs/git-lfs/wiki/File-Locking

**Comment by setchy** [comment]
@rarkins - should this be labelled with `platform:bitbucket-server` instead?
