### ISSUE TITLE
rubygems datasource hangs for hours on third party registries

### ISSUE THREAD

**Issue by mastermatt** [renovatebot/renovate#4291]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
I have a Ruby app that uses a hosted Artifactory instance instead of rubygems.org. When Renovate runs against it, the process hangs for 20+ hours.

There are a couple issues in the rubygems datasource implementation that are leading tho this, plus an overall shortcoming of Artifactory. 

First there is a bug in the way the URL is being compiled when making requests to the registry here:
https://github.com/renovatebot/renovate/blob/c42d6cb21d3fe2eeeb3f52a5d673aea8bb277c0f/lib/datasource/rubygems/get.js#L45-L46
This results in `name` equaling something like `/nokogiri.json`, while `baseUrl` equals `https://artifactory.myorg.net/artifactory/api/gems/gems///api/v1/gems`. Those triple slashes aren't something `got` will auto remove so the request fails. 

Replacing those two lines with the following fixes that:
```js
    const name = `${path}/${dependency}.json`;
    const baseUrl = registry;
```

Second, there is a bug in the retry logic that causes the time delay to be 1000 longer than it should. The culprit is here:
https://github.com/renovatebot/renovate/blob/c42d6cb21d3fe2eeeb3f52a5d673aea8bb277c0f/lib/datasource/rubygems/retriable.js#L19
`getDefaultDelay` is seemingly returning the delay in milliseconds, but if you examine the use of the returned value, it's meant to be whole seconds.
Example from log output
> INFO: RubyGems registry: Internal Server Error Retry in 1000 seconds.

The third issue relates to a shortcoming in Artifactory. It's API does not support the `/api/v1/versions` route. 
[rubygems.org docs](https://guides.rubygems.org/rubygems-org-api/#gem-version-methods)
[Artifactory REST API docs](https://www.jfrog.com/confluence/display/RTF/RubyGems+Repositories#RubyGemsRepositories-UsingtheRESTAPI)
[Artifactory ticket to add the route](https://www.jfrog.com/jira/browse/RTFACT-19012)
What's worse, when the route is hit, it returns a 400 instead of a 404. This means Renovate executes the retry logic then eventually exits because a `registry-failure` error is thrown.

**Did you see anything helpful in debug logs?**
In order to debug this, I had to go in and add more logging. Specifically, the logger is never sent which dependency the datasource is working on until *after* a request is made to a registry, plus the URL being requested is not logged either. I think the former should be a debug level log while the latter should be added as a trace log.

**To Reproduce**
Host Artifactory version 6.7.3
Run Renovate 19.25.2 on a repo with a `Gemfile` including:
```ruby
source 'https://artifactory.myorg.net/artifactory/api/gems/gems/'
```

**Expected behavior**
Renovate should:
 - Hit the correct API paths
 - Use sane retry timings 
 - Gracefully ignore registries that don't support the required API routes

I'll have a PR ready in a few minutes to fix the first two issues that are Renovate bugs. As for how to gracefully ignore the bad API, I'll leave that for discussion first.

**Comment by rarkins** [comment]
@mastermatt thanks for the excellent troubleshooting. I think that we can also remove the retriable logic if that's desired, because `got` now implements its own customisable retry logic.

**Comment by rarkins** [comment]
Any suggestions for our choices with dealing with Artifactory?

**Comment by mastermatt** [comment]
I'm not familiar enough with the how the response is used. Is have the versions a requirement to proceed processing a Gemfile?

**Comment by rarkins** [comment]
Normally what we do is treat the default registry as critical (e.g. npmjs.org or docker.io) but all others Renovate skips over errors and continues. We also normally should skip over 4xx too because that indicates a user error and not registry failure.

So I think the shortest term fix is to not throw a registry-failure for 4xx results, and later attempt to fix compatibility with Artifactory ruby.

**Comment by mastermatt** [comment]
Will the changeset in my current PR accomplish that?

**Comment by rarkins** [comment]
I didn't notice any changes to 4xx vs 5xx handling, or did I miss something subtle?

**Comment by mastermatt** [comment]
For example `https://artifactory.myorg.net/artifactory/api/gems/gems/api/v1/versions/colorize.json` returns a 400. So that means Renovate will skip it, right?

**Comment by rarkins** [comment]
It should, but it depends on each datasource. I need to check the code here because it was contributed by someone else.

**Comment by HonkingGoose** [comment]
What's the status of this issue?

It seems PR #4292 fixed some parts of the problem reported by the OP:

> Fixes the some of the issues outlined in the original gh issue where the
incorrect path was being requested and the retry logic was using too
large of numbers for the milliseconds to wait.

I think we haven't decided on how to deal with the Artifactory issue yet? @rarkins said:

> Any suggestions for our choices with dealing with Artifactory?

> So I think the shortest term fix is to not throw a registry-failure for 4xx results, and later attempt to fix compatibility with Artifactory ruby.

**Comment by mastermatt** [comment]
The issue of stalling for hours was resolved by the mentioned PR.

Because of the shortcoming in Artifactory, at my company we've never been able to successfully enabled Renovate for Ruby repos. According to the linked Jira ticket, it seems Artifactory might support the route as of 7.11.1 that came out recently. But we haven't updated to 7.x yet so I can't confirm. 

I'm going to close this issue, as the Renovate aspect itself was resolved.
