### ISSUE TITLE
Bug: docker / docker-compose drops `v` prefix from tag

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#4339]
**What Renovate type are you using?**
ALL versions affected

**Describe the bug**
While renovating a docker-compose file renovate is dropping the `v` prefix from docker tag.
But it is not always removed, so it could be flipped.

**Did you see anything helpful in debug logs?**

```
DEBUG: packageFiles with updates
{
  "config": {
    "docker-compose": [
      {
        "packageFile": "docker-compose.yml",
        "manager": "docker-compose",
        "deps": [
          {
            "depName": "traefik",
            "currentValue": "v1.7.13-alpine",
            "currentDigest": "sha256:7304d493488785296c51469cf49406540ca3305f54c8af0f599b47d233d007c2",
            "datasource": "docker",
            "managerData": {
              "lineNumber": 3
            },
            "updates": [
              {
                "fromVersion": "v1.7.13",
                "toVersion": "1.7.14",
                "newValue": "1.7.14-alpine",
                "newMajor": 1,
                "newMinor": 7,
                "updateType": "minor",
                "isSingleVersion": true,
                "newVersion": "1.7.14",
                "newDigest": "sha256:71277423c9a133eb747a2c14796e594a4228f151d286279c7b98f66b4239a8ca",
                "newDigestShort": "7127742"
              }
            ],
            "warnings": [],
            "sourceUrl": null,
            "dockerRegistry": "https://index.docker.io",
            "dockerRepository": "library/traefik",
            "releases": [
              "v1.7.13",
              "1.7.14",
              "v1.7.14"
            ]
          }
        ]
      },
      {
        "packageFile": "lb/docker-compose.yml",
        "manager": "docker-compose",
        "deps": [
          {
            "depName": "traefik",
            "currentValue": "v1.7.13-alpine",
            "currentDigest": "sha256:7304d493488785296c51469cf49406540ca3305f54c8af0f599b47d233d007c2",
            "datasource": "docker",
            "managerData": {
              "lineNumber": 3
            },
            "updates": [
              {
                "fromVersion": "v1.7.13",
                "toVersion": "1.7.14",
                "newValue": "1.7.14-alpine",
                "newMajor": 1,
                "newMinor": 7,
                "updateType": "minor",
                "isSingleVersion": true,
                "newVersion": "1.7.14",
                "newDigest": "sha256:71277423c9a133eb747a2c14796e594a4228f151d286279c7b98f66b4239a8ca",
                "newDigestShort": "7127742"
              }
            ],
            "warnings": [],
            "sourceUrl": null,
            "dockerRegistry": "https://index.docker.io",
            "dockerRepository": "library/traefik",
            "releases": [
              "v1.7.13",
              "1.7.14",
              "v1.7.14"
            ]
          }
        ]
      }
    ]
  }
}
```

**To Reproduce**
See https://github.com/ViceIce/renovate-test/pull/1/files

**Expected behavior**
Renovate should not remove any prefix.

**Screenshots**
![image](https://user-images.githubusercontent.com/1798109/63356869-ccb5ea80-c368-11e9-9b29-63b947e3b85c.png)

![image](https://user-images.githubusercontent.com/1798109/63356889-d4758f00-c368-11e9-90d2-469e65ad9f06.png)

**Additional context**
Looks like renovate is switching between the prefixed version and the unprefixed version of `traefik` docker tag.  They publish `v1.7.13-alpine` and `1.7.13-alpine` and renovate uses the tag, which is published first.

See https://renovatebot.slack.com/archives/CAFH752JU/p1566187040390000 for more discussions.

**Comment by ViceIce** [comment]
![image](https://user-images.githubusercontent.com/1798109/63357538-e441a300-c369-11e9-9dd5-e29e60cedcda.png)

**Comment by ViceIce** [comment]
here a `v` prefix is skipped
https://github.com/renovatebot/renovate/blob/bbb34078cda17486b9ab8c9d86204e8c8f331e43/lib/versioning/docker/index.ts#L5

so both version tags are valid, so maybe the sorting is not stable?

**Comment by ViceIce** [comment]
https://github.com/renovatebot/renovate/blob/master/lib/versioning/docker/index.ts#L20-L44

so it depends on the tag order we get from docker datasource

**Comment by ViceIce** [comment]
maybe we can simply add a prefix to the generic version and use that for `isCompatible`

**Comment by rarkins** [comment]
> maybe we can simply add a prefix to the generic version and use that for `isCompatible`

Problem is, if you had `2.0.0` and *only* `v2.0.1` was available then you'd probably want to take it instead of Renovate skipping it when it's "incompatible"

**Comment by adamdecaf** [comment]
This happened to me with a traefik `v2.3` update PR. I can help debug or try out a branch if needed. 

See: https://github.com/moov-io/auth-example/pull/5

**Comment by rarkins** [comment]
We should probably stop massaging `v` prefixes implicitly in datasource and instead require it to be configured with `extractVersion` once this is merged: https://github.com/renovatebot/renovate/pull/7307

**Comment by viceice** [comment]
Sounds good

**Comment by jokay** [comment]
> > maybe we can simply add a prefix to the generic version and use that for `isCompatible`
> 
> Problem is, if you had `2.0.0` and _only_ `v2.0.1` was available then you'd probably want to take it instead of Renovate skipping it when it's "incompatible"

Agree, but when `2.0.1` gets available too, I would expect the pull request to be updated from `v2.0.1` to `2.0.0` in a subsequent run of renovate.

**Comment by rarkins** [comment]
> Agree, but when `2.0.1` gets available too, I would expect the pull request to be updated from `v2.0.1` to `2.0.0` in a subsequent run of renovate.

I don't think you can have both. Either Renovate can be strict and wait for `2.0.1` or it can be flexible and use `v2.0.1` and not care when `2.0.1` is released.

**Comment by jokay** [comment]
> I don't think you can have both. Either Renovate can be strict and wait for `2.0.1` or it can be flexible and use `v2.0.1` and not care when `2.0.1` is released.

Ok then the workaround would be to delete the pull request once `2.0.1` is available to keep the desired tag and wait for another run which will then correctly identify `2.0.1` *(or to make us of packageRules as described [here](https://github.com/renovatebot/renovate/discussions/10549#discussioncomment-908785))*.
