### ISSUE TITLE
Add additional debug logging when NPM get fails

### ISSUE THREAD

**Issue by tvsbrent** [renovatebot/renovate#4343]
**What would you like Renovate to be able to do?**
Due to some issues with our internal, private repository, requests to get certain packages were failing due to JSON parse errors. Specifically, an unexpected end to the JSON input. However, the response from the registry returned a 200. Unfortunately, I wasn't aware of the specifics of the error, because the `get.ts` code swallows all errors that aren't 401-404 or specifically have to do with `https://registry.npmjs.org`.

**Describe the solution you'd like**
I'd like the catch block to provide more errors for these types of situations. Either by modifying the conditional located at the link below or adding a new conditional:

https://github.com/renovatebot/renovate/blob/master/lib/datasource/npm/get.ts#L255

**Describe alternatives you've considered**
I have hacked into the dist code and added the logging I needed, but otherwise, not sure what alternatives exist.

**Additional context**
I can certain make PR with this additional logging, if you'd like.

**Comment by rarkins** [comment]
So our ideal is to abort and throw a registry-failure exception like we do with registry.npmjs.org?

**Comment by tvsbrent** [comment]
Sorry, I've been away from this for a while, but I believe so, yes. I wouldn't think a user would want an error swallowed like that, no matter the registry being used.
