### ISSUE TITLE
Refactor baseBranches validation

### ISSUE THREAD

**Issue by frbuceta** [renovatebot/renovate#4346]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Bitbucket

### Have you checked the logs? Don't forget to include them if relevant

They are not relevant, if I have reviewed them

### What is your question?

When I run renovate-config-validator it tells me that baseBranches is not valid, only when I put it in the array `['master', 'dev']` but in the config.js it works ...

**Comment by rarkins** [comment]
We need to remove this check from inside the validation file and instead throw a config validation error from lib/workers if a base branch is not found.

**Comment by frbuceta** [comment]
even so, if you configure this in the renovate.json does not apply it and search in master only

**Comment by rarkins** [comment]
Let's keep the topics separate. baseBranches appears to be working for others on other platforms at least.

**Comment by frbuceta** [comment]
then I created another issue?

**Comment by rarkins** [comment]
Yes, but see if you can reproduce on a simple public Bitbucket repo so it’s easier to fix
