### ISSUE TITLE
Port user-facing regex parsing to re2

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4351]
Any use-facing regex (e.g. `packagePatterns` in `packageRules`) should use `re2` instead of `RegExp`. This has already been initiated in the `regex` `versionScheme`.

This will remove the need for `safe-regex`. We should have equivalent checking/config warnings after the change.

**Comment by nihalanisumit** [comment]
@rarkins I will take this.

**Comment by nihalanisumit** [comment]
@rarkins I will take this.
