### ISSUE TITLE
Unable to install Renovate since node-re2 was added

### ISSUE THREAD

**Issue by mastermatt** [renovatebot/renovate#4356]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Attempting to install Renovate fails due to permission issues since v19.30.11 on a fresh container. 

**To Reproduce**
```
> docker run -it node:10 /bin/bash

:/# node --version
v10.16.3

:/# npm install -g renovate
/usr/local/bin/renovate -> /usr/local/lib/node_modules/renovate/dist/renovate.js
/usr/local/bin/renovate-config-validator -> /usr/local/lib/node_modules/renovate/bin/config-validator.js

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/10.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/renovate/node_modules/re2/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/renovate/node_modules/re2/.node-gyp'
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/renovate/node_modules/re2
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! re2@1.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the re2@1.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-23T14_46_01_169Z-debug.log
```

**Comment by rarkins** [comment]
re2 needs Python 2.x and `make` in order to be built. It wasn't something I was aware of when developing/merging and unfortunately I'm not aware of any way to make it easier, but it's still a tradeoff I'm willing to make due to the danger of user-derived regexes. Happy to take any suggestions!

**Comment by boredland** [comment]
Hi! Is there a way to use renovate without python?

**Comment by rarkins** [comment]
It needs Python 2.x to install, but not to run.

**Comment by boredland** [comment]
But when the setup fails, you can't run it. I think it would be very nice if one could opt-out python dependencies completely. Until v19.30.10 I was able to run it as a google cloud function...

**Comment by rarkins** [comment]
@ViceIce any thoughts on this?

**Comment by rarkins** [comment]
I can only think of using Google's "Cloud run" with the renovate slim container instead (assuming you're just using npm/yarn).

**Comment by rarkins** [comment]
And does this mean that GCF fails for any and all `node-gyp`? I think it requires Python 2.x no matter what.

**Comment by boredland** [comment]
Gcf emits an error message for v19.30.10, but works anyway. Since the update this isn't the case. The nice thing about gcf in this case is the option to schedule...

**Comment by ViceIce** [comment]
Python and any c++ is only required to build renovate because of the native node add-on from re2.

Isn't it possible to use the renovate slim image on gcf? It will have all deps pre-installed without any build deps.

**Comment by ViceIce** [comment]
@rarkins I've an idea.

1. We move the re import to `util/regex` and import `re2` with a `try ... catch`.
2. In `versioning/regex` we throw a `config-validation` error if re2 is not available.
3. We move the `re2` package to `optionalDependencies`.
4. We install `optionalDependencies` on docker images.

**Comment by rarkins** [comment]
Can we also fall back to regular RegExp if it's not found? I just want re2 to protect the app. If anyone *wants* to not have it and is happy to settle for RegExp, I don't need to stop them.

**Comment by ViceIce** [comment]
Good idea. So we issue a warning and fall back to `RegExp`.

**Comment by ViceIce** [comment]
I'll send a pr

**Comment by rarkins** [comment]
@boredland can you verify?

**Comment by boredland** [comment]
Works like a charm @rarkins ! Thank you very much!

**Comment by rarkins** [comment]
Most thanks to @ViceIce in this case! And thanks to you too for alerting us to it and confirming the fix.

**Comment by boredland** [comment]
Oh, sorry! Thank you @ViceIce and if sb cares, this is the node10 cloud function I'm using:
```index.js
const { execSync } = require('child_process');

exports.renovate = () => {
    console.info("Starting renovate bot");
    execSync('npm run renovate', {
        cwd: process.cwd(),
        detached: true,
        stdio: "inherit"
    });
    console.info("Finished renovate bot");
};
```
```package.json
{
  "name": "renovate-function",
  "main": "index.js",
  "author": "Jonas Strassel",
  "engines": {
    "node": ">=10.0.0"
  },
  "scripts": {
    "renovate": "RENOVATE_PLATFORM=github RENOVATE_TOKEN=??? npx renovate@latest [user]/[repo]",
    "renovate-test": "node -e 'require(\"./index.js\").renovate()'"
  },
  "dependencies": {
    "prebuild-install": "^5.3.0"
  }
}
```
