### ISSUE TITLE
RubyGems Datasource needs trailing slash

### ISSUE THREAD

**Issue by shushugah** [renovatebot/renovate#4376]
**What Renovate type are you using?**
Renovate CLI on Gitlab EE 11.9.4

**Describe the bug**
When a custom RubyGems source is specified in `Gemfile`, without a trailing slash, for example
```ruby
 source 'http://private_domain:8081/content/repositories/brand-rubygems' do
  gem 'ba_rubocop'
end
```

In the logs

These lines with the double `//` indicated the trailing slash was an issue
```
"href": "http://private_domain:8081/content/repositories/brand_name-rubygems//api/v1/gems/sane_logging.json",

"baseUrl": "private_domain:8081/content/repositories/brand_name-rubygems//api/v1/gems/"
```

**To Reproduce**
Create any repository, with a private rubygems source without a trailing slash. After adding a trailing slash in `Gemfile`, this issue no longer occured

**Expected behavior**
Whether a RubyGems source includes a trailing slash or not, (something Gemfile.lock parses correctly either way) it should append sub routes correctly

**Related Issues**
This issue also has the double slash problem https://github.com/renovatebot/renovate/issues/4291

**Comment by zharinov** [comment]
Seems to be fixed
