### ISSUE TITLE
bug(bitbucket-server): Rate limiting

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#4381]
**What Renovate type are you using?**
Renovate CLI or Renovate Pro?

**Describe the bug**
Bitbucket Server 6.6 comes with a [rate limiting](https://confluence.atlassian.com/bitbucketserver/improving-instance-stability-with-rate-limiting-976171954.html) feature (DataCenter license required).
It will return a HTTP 429 error.

**Did you see anything helpful in debug logs?**
Nothing yet.

**To Reproduce**

1.  Enable `rate-limit`
2.  Run renovate against bb-server

**Expected behavior**
The [`bb-got-wrapper`](https://github.com/renovatebot/renovate/blob/master/lib/platform/bitbucket-server/bb-got-wrapper.ts) should handle that.

**Comment by ViceIce** [comment]
We should catch and throw a `rate-limit-exceeded` error like github.

https://github.com/renovatebot/renovate/blob/a28f688b7732596601e8596765ca64be8abf5f70/lib/platform/github/gh-got-wrapper.ts#L124-L126

**Comment by olegkrivtsov** [comment]
I'd like to help with this one.

**Comment by viceice** [comment]
@olegkrivtsov I think we can close this. because bitbucket server is deprecated and i no longer use it 😉

**Comment by rarkins** [comment]
I don't mind if it's a few by lines. Still a few years worth left

**Comment by viceice** [comment]
Seems nobody trapped into this beside me (while reading release notes) 🤷‍♂️
