### ISSUE TITLE
Reduce docker image (switch from ubuntu to debian:slim or alpine?)

### ISSUE THREAD

**Issue by bagage** [renovatebot/renovate#4395]
Currently, Renovate docker images [are quite huge](https://hub.docker.com/r/renovate/renovate/tags): 2GB for latest, and 170MB for slim one.

In the mean time, [debian images](https://hub.docker.com/_/debian?tab=tags) are 51MB for normal, 30MB for slim one.

It would be great if renovate could lose some weight, either:

1. by changing base image from `amd64/ubuntu:18.04` (27MB) to ~~`debian:slim` (actually 51MB?) or even better~~ [`alpine` (3MB)](https://hub.docker.com/_/alpine?tab=tags)
2. by using [docker-squash](https://github.com/jwilder/docker-squash) or similar to reduce the final image size.

**Comment by rarkins** [comment]
Let's track in #3153 instead. I'm not too interested in replacing ubuntu with alpine though. The extra time it will cost us initially and ongoing is not justified by the download savings.
