### ISSUE TITLE
Golang mirror/ proxy support 

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4410]
Do we need to make changes to accommodate this? Maybe it makes life easier for us though?

https://blog.golang.org/module-mirror-launch

**Comment by HonkingGoose** [comment]
Do we still want/need this? It's been a long time since this issue was raised, and I'm just checking in here to see what we think about it now.

**Comment by rarkins** [comment]
Let's use #8677 instead, I didn't remember this one was open
