### ISSUE TITLE
v20 planning

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4426]
Proposed changes:
- [x] Default unicodeEmoji=true
- [x] Drop embedded yarn v1.9.4
- [x] Drop Node v10
- [x] Remove embedded package managers (yarn, pnpm, npm)

**Comment by rarkins** [comment]
Let's add any breaking changes here as we think of them. I also have a [breaking](https://github.com/renovatebot/renovate/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abreaking) issue label in use too.

**Comment by ViceIce** [comment]
remove `yarn-1.9.4.js` ?

**Comment by ViceIce** [comment]
Should we pin this issue?

**Comment by viceice** [comment]
done
