### ISSUE TITLE
TypeError: Cannot read property 'initRepo' of undefined since v19.40.0

### ISSUE THREAD

**Issue by dominik-bln** [renovatebot/renovate#4458]
#### This is a:

- [x] Bug report (non-security related)
- [ ] Feature request
- [ ] I'm not sure which of those it is

#### I'm using:

- [ ] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [x] Self-hosted GitLab
- [ ] Self-hosted Azure DevOps

#### Please describe the issue:

We automatically upgraded renovate-bot to `v19.40.0` a few hours ago and since then all our runs are failing with the following errors:

```bash
ERROR: Repository has unknown error (repository=alpha/render-prosemirror)
       "err": {
         "message": "Cannot read property 'initRepo' of undefined",
         "stack": "TypeError: Cannot read property 'initRepo' of undefined\n    at getPlatformConfig (/usr/src/app/dist/workers/repository/init/apis.js:5:43)\n    at initApis (/usr/src/app/dist/workers/repository/init/apis.js:13:20)\n    at initRepo (/usr/src/app/dist/workers/repository/init/index.js:20:20)\n    at Object.renovateRepository (/usr/src/app/dist/workers/repository/index.js:26:24)"
       }
```

**Comment by dominik-bln** [comment]
I should maybe add that the same error occurs for all repositories.

**Comment by rarkins** [comment]
Yes sorry, we pushed a bad commit earlier today (v19.40.0). It was reverted in v19.40.1 about 5 hours ago so you may need to manually select that version or greater if v19.40.0 is cached. If you find any registry/repository where v19.40.0 is still the latest, please let us know.

Cc @ViceIce

**Comment by dominik-bln** [comment]
Ah, that's the flipside of having renovate update itself, we didn't get the newer update because the runs were failing 😅 Thanks for the info.

We do a `--dry-run` on our renovate config repo branches in CI to somewhat mitigate this case being merged, but that passed without incident, i. e. just as a thought, maybe there is some way to make `--dry-run` work more similar to full run in this case

**Comment by rarkins** [comment]
That's really strange - I would have thought dry run should have failed at the same step.
