### ISSUE TITLE
Automerge is not working for protected branches even if given push access

### ISSUE THREAD

**Issue by robertying** [renovatebot/renovate#4460]
**What Renovate type are you using?**

The hosted App on GitHub Apps

**Describe the bug**

Renovate automerge is not working for protected branches even if renovate app is included in the [list which allows pushing access](https://developer.github.com/changes/2019-09-05-apps-protected-branches-api/)

Branch Protection enabled (see the screenshot below for details):
1. Pull request review required
1. Status check pass required

Edit:
I then turned off the status check pass requirement and the automergr still would not work.

**Did you see anything helpful in debug logs?**

<details>
<summary>Logs</summary>
INFO: Renovating repository
DEBUG: Using localDir: /mnt/renovate/gh/eesast/renovate-branch-protection
DEBUG: initRepo("eesast/renovate-branch-protection")
INFO: Authenticated as user: renovate[bot]
INFO: Using renovate version: 19.39.1
DEBUG: eesast/renovate-branch-protection owner = eesast
DEBUG: eesast/renovate-branch-protection default branch = master
DEBUG: Using app token for git init
INFO: Initialising git repository into /mnt/renovate/gh/eesast/renovate-branch-protection
INFO: git clone completed
{
  "cloneSeconds": 0.5
}
DEBUG: latest commit
{
  "latestCommitDate": "2019-09-10 02:00:18 +0800"
}
DEBUG: Git private key configured, but not being set
INFO: Setting git author
{
  "gitAuthor": {
    "name": "Renovate Bot",
    "email": "bot@renovateapp.com"
  }
}
DEBUG: resetMemCache()
DEBUG: detectSemanticCommits()
DEBUG: getCommitMessages
DEBUG: Semantic commits detection: unknown
DEBUG: No semantic commits detected
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: config file exists
DEBUG: ensureIssueClosing(Action required: Add a Renovate config)
DEBUG: Retrieving issueList
DEBUG: Retrieved 0 issues
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "automerge": true
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "config:base"
    ],
    "automerge": true
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "config:base"
    ],
    "automerge": true
  }
}
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**"
  ]
}
DEBUG: checkBaseBranch()
DEBUG: config.repoIsOnboarded=true
DEBUG: Setting baseBranch to master
DEBUG: latest commit
{
  "branchName": "master",
  "latestCommitDate": "2019-09-10 02:00:18 +0800"
}
DEBUG: Setting branchPrefix: renovate/
DEBUG: No vulnerability alerts found
DEBUG: processRepo()
DEBUG: No baseBranches
DEBUG: extractAndUpdate()
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible
DEBUG: Using file match: (^|/)WORKSPACE$ for manager bazel
DEBUG: Using file match: \.bzl$ for manager bazel
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite
DEBUG: bundler is disabled
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/)Dockerfile$ for manager dockerfile
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci
DEBUG: github-actions is disabled
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci-include
DEBUG: Using file match: (^|/)go.mod$ for manager gomod
DEBUG: gradle is disabled
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen
DEBUG: Using file match: \.pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Matched 1 file(s) for manager npm: package.json
DEBUG: npm file package.json has name "renovate-branch-protection"
DEBUG: Detecting Lerna and Yarn Workspaces
DEBUG: Finding locked versions
DEBUG: yarn.lock uses integrity hashes
INFO: Found npm package files
DEBUG: Using file match: \.csproj$ for manager nuget
DEBUG: Using file match: ^.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup
DEBUG: pipenv is disabled
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub
DEBUG: Using file match: \.sbt$ for manager sbt
DEBUG: Using file match: (^|/)Package\.swift for manager swift
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: travis is disabled
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Found 1 package file(s)
DEBUG: manager.fetchUpdates()
DEBUG: packageFiles with updates
{
  "config": {
    "npm": [
      {
        "packageFile": "package.json",
        "manager": "npm",
        "deps": [
          {
            "depType": "dependencies",
            "depName": "is-number",
            "currentValue": "6.0.0",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "lockedVersion": "6.0.0",
            "updates": [
              {
                "fromVersion": "6.0.0",
                "toVersion": "7.0.0",
                "newValue": "7.0.0",
                "newMajor": 7,
                "newMinor": 0,
                "updateType": "major",
                "isSingleVersion": true,
                "releaseTimestamp": "2018-07-04T15:08:58.238Z",
                "canBeUnpublished": false
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/jonschlinkert/is-number"
          },
          {
            "depType": "dependencies",
            "depName": "serve",
            "currentValue": "11.1.0",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "lockedVersion": "11.1.0",
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/zeit/serve"
          }
        ],
        "packageJsonName": "renovate-branch-protection",
        "packageJsonVersion": "1.0.0",
        "packageJsonType": "library",
        "yarnLock": "yarn.lock",
        "skipInstalls": true,
        "yarnIntegrity": true
      }
    ]
  }
}
DEBUG: branchifyUpgrades
DEBUG: 1 flattened updates found: is-number
DEBUG: Returning 1 branch(es)
DEBUG: generateBranchConfig(1)(branch="renovate/is-number-7.x")
DEBUG: hasGroupName: false(branch="renovate/is-number-7.x")
DEBUG: groupEligible: false(branch="renovate/is-number-7.x")
DEBUG: useGroupSettings: false(branch="renovate/is-number-7.x")
DEBUG: config.repoIsOnboarded=true
INFO: Processing 1 branch: renovate/is-number-7.x
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 2 Pull Requests
DEBUG: currentHourStart=1568052000000
DEBUG: PR hourly limit remaining: 2
DEBUG: Enforcing prConcurrentLimit (20)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 20
DEBUG: processBranch with 1 upgrades(branch="renovate/is-number-7.x")
DEBUG: Setting baseBranch to master(branch="renovate/is-number-7.x")
DEBUG: latest commit(branch="renovate/is-number-7.x")
{
  "branchName": "master",
  "latestCommitDate": "2019-09-10 02:00:18 +0800"
}
DEBUG: getBranchPr(renovate/is-number-7.x)(branch="renovate/is-number-7.x")
DEBUG: findPr(renovate/is-number-7.x, null, open)(branch="renovate/is-number-7.x")
DEBUG: branchExists=false(branch="renovate/is-number-7.x")
DEBUG: Branch has 1 upgrade(s)(branch="renovate/is-number-7.x")
DEBUG: recreateClosed is false(branch="renovate/is-number-7.x")
DEBUG: findPr(renovate/is-number-7.x, Update dependency is-number to v7, !open)(branch="renovate/is-number-7.x")
DEBUG: prAlreadyExisted=false(branch="renovate/is-number-7.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/is-number-7.x")
DEBUG: No schedule defined(branch="renovate/is-number-7.x")
INFO: Branch needs creating(branch="renovate/is-number-7.x")
DEBUG: Using parentBranch: undefined(branch="renovate/is-number-7.x")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/is-number-7.x")
DEBUG: npm.updateDependency(): dependencies.is-number = 7.0.0(branch="renovate/is-number-7.x")
DEBUG: Replacing "6.0.0" with "7.0.0" at index 273(branch="renovate/is-number-7.x")
DEBUG: Updating packageFile content(branch="renovate/is-number-7.x")
DEBUG: Updated 1 package files(branch="renovate/is-number-7.x")
DEBUG: Getting updated lock files(branch="renovate/is-number-7.x")
DEBUG: lock file dirs(branch="renovate/is-number-7.x")
{
  "dirs": {
    "yarnLockDirs": [
      "yarn.lock"
    ],
    "npmLockDirs": [],
    "pnpmShrinkwrapDirs": [],
    "lernaDirs": []
  }
}
DEBUG: Writing package.json files(branch="renovate/is-number-7.x")
{
  "packageFiles": [
    "package.json"
  ]
}
DEBUG: Writing yarn.lock(branch="renovate/is-number-7.x")
DEBUG: Writing any updated package files(branch="renovate/is-number-7.x")
DEBUG: Writing package.json(branch="renovate/is-number-7.x")
DEBUG: Generating yarn.lock for .(branch="renovate/is-number-7.x")
DEBUG: Spawning yarn install to create /mnt/renovate/gh/eesast/renovate-branch-protection/yarn.lock(branch="renovate/is-number-7.x")
DEBUG: Using yarn: node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js(branch="renovate/is-number-7.x")
DEBUG: yarn stdout: yarn install v1.17.3 [1/4] Resolving packages... success Saved lockfile. Done in 0.70s. (branch="renovate/is-number-7.x")
DEBUG: yarn stderr: (branch="renovate/is-number-7.x")
INFO: Generated lockfile(branch="renovate/is-number-7.x")
{
  "seconds": 1,
  "type": "yarn.lock",
  "stdout": "yarn install v1.17.3\n[1/4] Resolving packages...\nsuccess Saved lockfile.\nDone in 0.70s.\n",
  "stderr": ""
}
DEBUG: yarn.lock needs updating(branch="renovate/is-number-7.x")
DEBUG: Updated 1 lock files(branch="renovate/is-number-7.x")
{
  "updatedArtifacts": [
    "yarn.lock"
  ]
}
DEBUG: 2 file(s) to commit(branch="renovate/is-number-7.x")
DEBUG: Committing files to branch renovate/is-number-7.x(branch="renovate/is-number-7.x")
INFO: files committed(branch="renovate/is-number-7.x")
DEBUG: Checking if we can automerge branch(branch="renovate/is-number-7.x")
DEBUG: mergeStatus=no automerge(branch="renovate/is-number-7.x")
DEBUG: Ensuring PR(branch="renovate/is-number-7.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/is-number-7.x")
DEBUG: getBranchPr(renovate/is-number-7.x)(branch="renovate/is-number-7.x")
DEBUG: findPr(renovate/is-number-7.x, null, open)(branch="renovate/is-number-7.x")
DEBUG: getBranchStatus(renovate/is-number-7.x)(branch="renovate/is-number-7.x")
DEBUG: branch status check result(branch="renovate/is-number-7.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/is-number-7.x")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
DEBUG: Creating PR(branch="renovate/is-number-7.x")
{
  "prTitle": "Update dependency is-number to v7"
}
DEBUG: Creating PR(branch="renovate/is-number-7.x")
{
  "title": "Update dependency is-number to v7",
  "head": "eesast:renovate/is-number-7.x",
  "base": "master"
}
DEBUG: PR created(branch="renovate/is-number-7.x")
{
  "pr": 3
}
DEBUG: Adding labels to #3(branch="renovate/is-number-7.x")
INFO: PR created(branch="renovate/is-number-7.x")
{
  "pr": 3
}
DEBUG: getBranchStatus(renovate/is-number-7.x)(branch="renovate/is-number-7.x")
DEBUG: branch status check result(branch="renovate/is-number-7.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/is-number-7.x")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
DEBUG: getBranchStatus() result(branch="renovate/is-number-7.x")
{
  "branchStatus": "pending",
  "branchName": "renovate/is-number-7.x"
}
DEBUG: Skipping assignees and reviewers as automerge=true(branch="renovate/is-number-7.x")
INFO: Created Pull Request #3(branch="renovate/is-number-7.x")
DEBUG: Ensuring comment ":warning: Artifact update problem" in #3 is removed(branch="renovate/is-number-7.x")
DEBUG: Retrieved closed PR list with graphql(branch="renovate/is-number-7.x")
{
  "prNumbers": [
    1,
    2
  ]
}
DEBUG: Getting comments for #3(branch="renovate/is-number-7.x")
DEBUG: Found 0 comments(branch="renovate/is-number-7.x")
DEBUG: Checking #3 for automerge(branch="renovate/is-number-7.x")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/is-number-7.x")
INFO: PR is not ready for merge(branch="renovate/is-number-7.x")
DEBUG: branchPrefix: renovate/
DEBUG: Found 0 Renovate PRs
{
  "renovatePrs": []
}
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/is-number-7.x"
  ],
  "renovateBranches": [
    "renovate/is-number-7.x"
  ]
}
DEBUG: remainingBranches=
DEBUG: No branches to clean up
DEBUG: ensureIssueClosing(Action Required: Fix Renovate Configuration)
INFO: Finished repository
</details>

I only saw those two lines relevant:
```
DEBUG: PR is configured for automerge(branch="renovate/is-number-7.x")
INFO: PR is not ready for merge(branch="renovate/is-number-7.x")
```
and renovate is not giving anything more useful.

My thinking is that the status check is blocking it, because of this log:

```
DEBUG: branch status check result(branch="renovate/is-number-7.x")
{
  "state": "pending",
  "statuses": []
}
```

**To Reproduce**

1. Create repository with renovate and renovate-approve
2. Add a CI so the repo has some status check to do before merging.
2. Configure the project branch protection settings to the following:

  ![image](https://user-images.githubusercontent.com/22592111/64555632-4fcacf00-d370-11e9-958e-670b240b0520.png)

reproducing repo: https://github.com/eesast/renovate-branch-protection

**Expected behavior**

renovate-approve takes care of the pull request review and CI passes, so renovate should be able to auto merge this pr.

**Comment by rarkins** [comment]
This log being printed would normally mean that you have no tests:

```
DEBUG: branch status check result(branch="renovate/is-number-7.x")
{
  "state": "pending",
  "statuses": []
}
```

Is that the case here?

**Comment by robertying** [comment]
I did add a Travis CI to my repo so there are two status checks running for each pr.

**Comment by robertying** [comment]
Hi @rarkins! I checked another log after I turned off required status checks to narrow down the issue. The automerge still did not work. And here are the logs several hours after the pr was created (it seems renovate was trying to merge it again):

<details>
<summary>Details</summary>

INFO: Renovating repository
DEBUG: Using localDir: /mnt/renovate/gh/eesast/renovate-branch-protection
DEBUG: initRepo("eesast/renovate-branch-protection")
INFO: Authenticated as user: renovate[bot]
INFO: Using renovate version: 19.39.1
DEBUG: eesast/renovate-branch-protection owner = eesast
DEBUG: eesast/renovate-branch-protection default branch = master
DEBUG: Using app token for git init
INFO: Initialising git repository into /mnt/renovate/gh/eesast/renovate-branch-protection
INFO: git clone completed
{
  "cloneSeconds": 0.5
}
DEBUG: latest commit
{
  "latestCommitDate": "2019-09-10 02:14:42 +0800"
}
DEBUG: Git private key configured, but not being set
INFO: Setting git author
{
  "gitAuthor": {
    "name": "Renovate Bot",
    "email": "bot@renovateapp.com"
  }
}
DEBUG: resetMemCache()
DEBUG: detectSemanticCommits()
DEBUG: getCommitMessages
DEBUG: Semantic commits detection: unknown
DEBUG: No semantic commits detected
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: config file exists
DEBUG: ensureIssueClosing(Action required: Add a Renovate config)
DEBUG: Retrieving issueList
DEBUG: Retrieved 0 issues
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "automerge": true
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "config:base"
    ],
    "automerge": true
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "config:base"
    ],
    "automerge": true
  }
}
DEBUG: Found repo ignorePaths
{
  "ignorePaths": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/examples/**",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**"
  ]
}
DEBUG: checkBaseBranch()
DEBUG: config.repoIsOnboarded=true
DEBUG: Setting baseBranch to master
DEBUG: latest commit
{
  "branchName": "master",
  "latestCommitDate": "2019-09-10 02:14:42 +0800"
}
DEBUG: Setting branchPrefix: renovate/
DEBUG: No vulnerability alerts found
DEBUG: processRepo()
DEBUG: No baseBranches
DEBUG: extractAndUpdate()
DEBUG: Using file match: (^|/)tasks/[^/]+\.ya?ml$ for manager ansible
DEBUG: Using file match: (^|/)WORKSPACE$ for manager bazel
DEBUG: Using file match: \.bzl$ for manager bazel
DEBUG: Using file match: buildkite\.ya?ml for manager buildkite
DEBUG: Using file match: \.buildkite/.+\.ya?ml$ for manager buildkite
DEBUG: bundler is disabled
DEBUG: Using file match: (^|/)Cargo.toml$ for manager cargo
DEBUG: Using file match: (^|/).circleci/config.yml$ for manager circleci
DEBUG: Using file match: (^|/)([\w-]*)composer.json$ for manager composer
DEBUG: Using file match: (^|/)deps\.edn$ for manager deps-edn
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/)Dockerfile$ for manager dockerfile
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile
DEBUG: Using file match: (^|/).drone.yml$ for manager droneci
DEBUG: github-actions is disabled
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci
DEBUG: Using file match: ^\.gitlab-ci\.yml$ for manager gitlabci-include
DEBUG: Using file match: (^|/)go.mod$ for manager gomod
DEBUG: gradle is disabled
DEBUG: Using file match: (^|/)gradle/wrapper/gradle-wrapper.properties$ for manager gradle-wrapper
DEBUG: Using file match: ^Formula/[^/]+[.]rb$ for manager homebrew
DEBUG: Using file match: (^|/)project\.clj$ for manager leiningen
DEBUG: Using file match: \.pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)pom\.xml$ for manager maven
DEBUG: Using file match: (^|/)package.js$ for manager meteor
DEBUG: Using file match: (^|/)package.json$ for manager npm
DEBUG: Matched 1 file(s) for manager npm: package.json
DEBUG: npm file package.json has name "renovate-branch-protection"
DEBUG: Detecting Lerna and Yarn Workspaces
DEBUG: Finding locked versions
DEBUG: yarn.lock uses integrity hashes
INFO: Found npm package files
DEBUG: Using file match: \.csproj$ for manager nuget
DEBUG: Using file match: ^.nvmrc$ for manager nvm
DEBUG: Using file match: (^|/)([\w-]*)requirements.(txt|pip)$ for manager pip_requirements
DEBUG: Using file match: (^|/)setup.py$ for manager pip_setup
DEBUG: pipenv is disabled
DEBUG: Using file match: (^|/)pyproject\.toml$ for manager poetry
DEBUG: Using file match: (^|/)pubspec\.ya?ml$ for manager pub
DEBUG: Using file match: \.sbt$ for manager sbt
DEBUG: Using file match: (^|/)Package\.swift for manager swift
DEBUG: Using file match: \.tf$ for manager terraform
DEBUG: travis is disabled
DEBUG: Using file match: (^|/)\.ruby-version$ for manager ruby-version
DEBUG: Found 1 package file(s)
DEBUG: manager.fetchUpdates()
DEBUG: packageFiles with updates
{
  "config": {
    "npm": [
      {
        "packageFile": "package.json",
        "manager": "npm",
        "deps": [
          {
            "depType": "dependencies",
            "depName": "is-image",
            "currentValue": "2.0.0",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "lockedVersion": "2.0.0",
            "updates": [
              {
                "fromVersion": "2.0.0",
                "toVersion": "3.0.0",
                "newValue": "3.0.0",
                "newMajor": 3,
                "newMinor": 0,
                "updateType": "major",
                "isSingleVersion": true,
                "releaseTimestamp": "2019-04-19T13:13:51.039Z",
                "canBeUnpublished": false
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/sindresorhus/is-image"
          },
          {
            "depType": "dependencies",
            "depName": "is-number",
            "currentValue": "7.0.0",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "lockedVersion": "7.0.0",
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/jonschlinkert/is-number"
          },
          {
            "depType": "dependencies",
            "depName": "serve",
            "currentValue": "11.1.0",
            "datasource": "npm",
            "prettyDepType": "dependency",
            "lockedVersion": "11.1.0",
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/zeit/serve"
          }
        ],
        "packageJsonName": "renovate-branch-protection",
        "packageJsonVersion": "1.0.0",
        "packageJsonType": "library",
        "yarnLock": "yarn.lock",
        "skipInstalls": true,
        "yarnIntegrity": true
      }
    ]
  }
}
DEBUG: branchifyUpgrades
DEBUG: 1 flattened updates found: is-image
DEBUG: Returning 1 branch(es)
DEBUG: generateBranchConfig(1)(branch="renovate/is-image-3.x")
DEBUG: hasGroupName: false(branch="renovate/is-image-3.x")
DEBUG: groupEligible: false(branch="renovate/is-image-3.x")
DEBUG: useGroupSettings: false(branch="renovate/is-image-3.x")
DEBUG: config.repoIsOnboarded=true
INFO: Processing 1 branch: renovate/is-image-3.x
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 4 Pull Requests
DEBUG: currentHourStart=1568080800000
DEBUG: PR hourly limit remaining: 2
DEBUG: Enforcing prConcurrentLimit (20)
DEBUG: 1 PRs are currently open
DEBUG: PR concurrent limit remaining: 19
DEBUG: processBranch with 1 upgrades(branch="renovate/is-image-3.x")
DEBUG: Setting baseBranch to master(branch="renovate/is-image-3.x")
DEBUG: latest commit(branch="renovate/is-image-3.x")
{
  "branchName": "master",
  "latestCommitDate": "2019-09-10 02:14:42 +0800"
}
DEBUG: getBranchPr(renovate/is-image-3.x)(branch="renovate/is-image-3.x")
DEBUG: findPr(renovate/is-image-3.x, null, open)(branch="renovate/is-image-3.x")
DEBUG: Found PR #4(branch="renovate/is-image-3.x")
DEBUG: Returning from graphql open PR list(branch="renovate/is-image-3.x")
DEBUG: branchExists=true(branch="renovate/is-image-3.x")
DEBUG: Branch pr rebase requested: false(branch="renovate/is-image-3.x")
DEBUG: Branch has 1 upgrade(s)(branch="renovate/is-image-3.x")
DEBUG: Checking if PR has been edited(branch="renovate/is-image-3.x")
DEBUG: Found existing branch PR(branch="renovate/is-image-3.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/is-image-3.x")
DEBUG: No schedule defined(branch="renovate/is-image-3.x")
DEBUG: Branch already exists(branch="renovate/is-image-3.x")
DEBUG: getBranchPr(renovate/is-image-3.x)(branch="renovate/is-image-3.x")
DEBUG: findPr(renovate/is-image-3.x, null, open)(branch="renovate/is-image-3.x")
DEBUG: Found PR #4(branch="renovate/is-image-3.x")
DEBUG: Returning from graphql open PR list(branch="renovate/is-image-3.x")
DEBUG: Found branch protection(branch="renovate/is-image-3.x")
DEBUG: Branch protection: PR Reviews are required before merging(branch="renovate/is-image-3.x")
DEBUG: Branch protection: Pushing to branch is restricted(branch="renovate/is-image-3.x")
{
  "users": [],
  "teams": []
}
DEBUG: Branch does not need rebasing(branch="renovate/is-image-3.x")
DEBUG: Using parentBranch: renovate/is-image-3.x(branch="renovate/is-image-3.x")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/is-image-3.x")
DEBUG: npm.updateDependency(): dependencies.is-image = 3.0.0(branch="renovate/is-image-3.x")
DEBUG: No package files need updating(branch="renovate/is-image-3.x")
DEBUG: Getting updated lock files(branch="renovate/is-image-3.x")
DEBUG: lock file dirs(branch="renovate/is-image-3.x")
{
  "dirs": {
    "yarnLockDirs": [],
    "npmLockDirs": [],
    "pnpmShrinkwrapDirs": [],
    "lernaDirs": []
  }
}
DEBUG: Writing package.json files(branch="renovate/is-image-3.x")
{
  "packageFiles": [
    "package.json"
  ]
}
DEBUG: Writing yarn.lock(branch="renovate/is-image-3.x")
DEBUG: Writing any updated package files(branch="renovate/is-image-3.x")
DEBUG: No updated lock files in branch(branch="renovate/is-image-3.x")
DEBUG: No files to commit(branch="renovate/is-image-3.x")
DEBUG: Checking if we can automerge branch(branch="renovate/is-image-3.x")
DEBUG: mergeStatus=no automerge(branch="renovate/is-image-3.x")
DEBUG: Ensuring PR(branch="renovate/is-image-3.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/is-image-3.x")
DEBUG: getBranchPr(renovate/is-image-3.x)(branch="renovate/is-image-3.x")
DEBUG: findPr(renovate/is-image-3.x, null, open)(branch="renovate/is-image-3.x")
DEBUG: Found PR #4(branch="renovate/is-image-3.x")
DEBUG: Returning from graphql open PR list(branch="renovate/is-image-3.x")
DEBUG: Found existing PR(branch="renovate/is-image-3.x")
DEBUG: getBranchStatus(renovate/is-image-3.x)(branch="renovate/is-image-3.x")
DEBUG: branch status check result(branch="renovate/is-image-3.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: check runs result(branch="renovate/is-image-3.x")
{
  "checkRuns": [
    {
      "name": "Travis CI - Pull Request",
      "status": "completed",
      "conclusion": "success"
    },
    {
      "name": "Travis CI - Branch",
      "status": "completed",
      "conclusion": "success"
    }
  ]
}
DEBUG: Processing existing PR(branch="renovate/is-image-3.x")
DEBUG: getBranchStatus(renovate/is-image-3.x)(branch="renovate/is-image-3.x")
DEBUG: branch status check result(branch="renovate/is-image-3.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: check runs result(branch="renovate/is-image-3.x")
{
  "checkRuns": [
    {
      "name": "Travis CI - Pull Request",
      "status": "completed",
      "conclusion": "success"
    },
    {
      "name": "Travis CI - Branch",
      "status": "completed",
      "conclusion": "success"
    }
  ]
}
DEBUG: getBranchStatus() result(branch="renovate/is-image-3.x")
{
  "branchStatus": "success",
  "branchName": "renovate/is-image-3.x"
}
DEBUG: Pull Request #4 does not need updating(branch="renovate/is-image-3.x")
DEBUG: Checking #4 for automerge(branch="renovate/is-image-3.x")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/is-image-3.x")
DEBUG: getBranchStatus(renovate/is-image-3.x)(branch="renovate/is-image-3.x")
DEBUG: branch status check result(branch="renovate/is-image-3.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: check runs result(branch="renovate/is-image-3.x")
{
  "checkRuns": [
    {
      "name": "Travis CI - Pull Request",
      "status": "completed",
      "conclusion": "success"
    },
    {
      "name": "Travis CI - Branch",
      "status": "completed",
      "conclusion": "success"
    }
  ]
}
DEBUG: Automerging #4(branch="renovate/is-image-3.x")
DEBUG: mergePr(4, renovate/is-image-3.x)(branch="renovate/is-image-3.x")
INFO: Branch protection: Cannot automerge PR when push protection is enabled(branch="renovate/is-image-3.x")
{
  "prNo": 4
}
DEBUG: branchPrefix: renovate/
DEBUG: Found 0 Renovate PRs
{
  "renovatePrs": []
}
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/is-image-3.x"
  ],
  "renovateBranches": [
    "renovate/is-image-3.x"
  ]
}
DEBUG: remainingBranches=
DEBUG: No branches to clean up
DEBUG: ensureIssueClosing(Action Required: Fix Renovate Configuration)
INFO: Finished repository

</details>

I can see renovate has already seen both the successful checks:

```
DEBUG: check runs result(branch="renovate/is-image-3.x")
{
  "checkRuns": [
    {
      "name": "Travis CI - Pull Request",
      "status": "completed",
      "conclusion": "success"
    },
    {
      "name": "Travis CI - Branch",
      "status": "completed",
      "conclusion": "success"
    }
  ]
}
```

but still unable to merge because of `INFO: Branch protection: Cannot automerge PR when push protection is enabled(branch="renovate/is-image-3.x")`.

I've ensured the setting:

![image](https://user-images.githubusercontent.com/22592111/64581789-0e611080-d3be-11e9-987f-878988fa0e5b.png)

**Comment by rarkins** [comment]
This should go live in the app within 1-2 hours

**Comment by robertying** [comment]
@rarkins that was great! Thanks for the quick fix! 👍

**Comment by jfairley** [comment]
I'm sorry to revive an old thread, but I'm having the same issue, and I don't know what more to try.

I too have branch protection enabled:

<details>
<summary>click for screenshot</summary>

<img width="926" alt="Screen Shot 2020-07-12 at 11 04 10 PM" src="https://user-images.githubusercontent.com/992483/87269880-c4d4cc80-c48b-11ea-8108-a5ae7b81012a.png">

</details>

... and I tried explicitly adding renovate as a user who could push (this was previously unchecked) ...

<details>
<summary>click for screenshot</summary>

<img width="922" alt="Screen Shot 2020-07-12 at 11 04 20 PM" src="https://user-images.githubusercontent.com/992483/87270011-1bdaa180-c48c-11ea-9dbd-da35a4c8412f.png">

</details>

... but renovate is unable to push from a branch ...

```
DEBUG: Found PR #170(branch="renovate/docker-circleci-node-12")
DEBUG: Returning from graphql open PR list(branch="renovate/docker-circleci-node-12")
DEBUG: Found branch protection(branch="renovate/docker-circleci-node-12")
DEBUG: Branch protection: PR Reviews are required before merging(branch="renovate/docker-circleci-node-12")
DEBUG: Branch protection: Pushing to branch is restricted(branch="renovate/docker-circleci-node-12")
{
  "users": [],
  "teams": []
}
DEBUG: Branch is stale and needs rebasing(branch="renovate/docker-circleci-node-12")

```
