### ISSUE TITLE
Run eslint --fix in pre-commit hook of husky

### ISSUE THREAD

**Issue by nihalanisumit** [renovatebot/renovate#4465]
**What would you like Renovate to be able to do?**
So there was some issue with my eslint on vscode due to which the lint issues were not getting highlighted but the CI was failing due to linting errors which I had to solve manually, rebase commit and force push again. This step could have been avoided if, at the time of commit, husky stopped my commit if there were eslint issues.

**Describe the solution you'd like**
I would like husky to run linters against staged git files using. "lint-staged"

**Comment by nihalanisumit** [comment]
@rarkins I have given a proposed solution for this issue in my pr.
https://github.com/renovatebot/renovate/pull/4466

**Comment by ViceIce** [comment]
This would massive slow down rebases.

**Comment by rarkins** [comment]
I think our linting is too slow to run every time. I don't find it a burden to run linting manually before I push to GitHub, and don't want to slow down everyone's development.
