### ISSUE TITLE
Gradle lookup errors - Registry error

### ISSUE THREAD

**Issue by mmoayyed** [renovatebot/renovate#4467]
**What Renovate type are you using?**

Renovate CLI running on schedule via Travis CI

**Describe the bug**

Running command:

```
renovate --labels=Bot --git-author=renovatebot@apereo.org --git-fs=https --token=... apereo/cas --log-level trace
```

Produces the following warning:

```
 WARN: Gradle command sh gradlew --init-script renovate-plugin.gradle renovate failed. Exit code: null. (repository=apereo/cas)
       "err": {
         "killed": true,
         "code": null,
         "signal": "SIGTERM",
         "cmd": "sh gradlew --init-script renovate-plugin.gradle renovate",
         "stdout": "To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.1/userguide/gradle_daemon.html.\nDaemon
 will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n> Task :renovate\n> Task :api:renovate\n> Task :core:renovate\n> Task 
:docs:renovate\n> Task :support:renovate\n> Task :webapp:renovate\n> Task :api:cas-server-core-api:renovate\n> Task :api:cas-server-core-api-audit:renovate\n> Task :api:cas-server-core-api-
authentication:renovate\n> Task :api:cas-server-core-api-configuration:renovate\n> Task :api:cas-server-core-api-configuration-model:renovate\n> Task :api:cas-server-core-api-cookie:renovat
e\n> Task :api:cas-server-core-api-events:renovate\n> Task :api:cas-server-core-api-logout:renovate\n> Task :api:cas-server-core-api-mfa:renovate\n> Task :api:cas-server-core-api-monitor:re
novate\n> Task :api:cas-server-core-api-protocol:renovate\n",
         "stderr": "Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m\n",
         "message": "Command failed: sh gradlew --init-script renovate-plugin.gradle renovate\nPicked up _JAVA_OPTIONS: -Xmx2048m -Xms512m\n",
         "stack": "Error: Command failed: sh gradlew --init-script renovate-plugin.gradle renovate\nPicked up _JAVA_OPTIONS: -Xmx2048m -Xms512m\n\n    at ChildProcess.exithandler (child_pro
cess.js:290:12)\n    at ChildProcess.emit (events.js:200:13)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:28
3:5)"
       }
 INFO: Aborting Renovate due to Gradle lookup errors (repository=apereo/cas)
 INFO: Registry error - skipping (repository=apereo/cas)
```

**Did you see anything helpful in debug logs?**

Logs more or less show the same error: https://app.renovatebot.com/dashboard#github/apereo/cas/94540226

**To Reproduce**

1. Fork `https://github.com/apereo/cas`
2. Install CLI:

```
nvm install 12.5.0
node -v
npm install -g renovate
```

3. Run `renovate --labels=Bot --git-author=renovatebot@apereo.org --token=... cloneuser/cas --log-level trace`

A similar job a few days ago also notes quite a large number of errors around dependency lookups, though it may have been related to sonatype:
https://travis-ci.org/apereo/cas/jobs/581042705

Running Gradle 5.6.1 with JDK 11.

**Expected behavior**

Pull requests created with dependency updates. It's worth noting that I *think* this issue started to manifest only a few days ago.

**Comment by rarkins** [comment]
I got the following error when running locally:
```
DEBUG: Start gradle command (repository=renovate-tests/cas)
       "cmd": "docker run --rm -v /tmp/renovate/repos/github/renovate-tests/cas:/tmp/renovate/repos/github/renovate-tests/cas -w /tmp/renovate/repos/github/renovate-tests/cas renovate/gradle gradle --init-script renovate-plugin.gradle renovate"
ERROR:  Process killed. Possibly gradle timed out. (repository=renovate-tests/cas)
```

Also edited the reproduction steps above btw

**Comment by rarkins** [comment]
I'm going to run without a timeout setting and see if it completes. Cc @corecanarias @ikesyo

**Comment by rarkins** [comment]
This time it ran for 12 minutes but still eventually failed. Relevant error this time appears to be: `FAILURE: Build failed with an exception.\n\n* What went wrong:\nGradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)`

This is one of the reasons why I was so keen to use a JS-based parsing approach for extraction instead of native gradle.

**Comment by mmoayyed** [comment]
Would it make sense to disable the gradle daemon when the command runs?

**Comment by rarkins** [comment]
I'm not a gradle user myself so I would need to leave it to @corecanarias or @ikesyo to best judge.

**Comment by ikesyo** [comment]
It makes sense for me to disable the daemon with adding `--no-daemon` option.

**Comment by rarkins** [comment]
I'll test locally

**Comment by mmoayyed** [comment]
Hey folks, thanks very much for taking the time and looking into this. Is there anything I can help with to move this issue forward?

**Comment by rarkins** [comment]
I still got the daemon error when running locally with `--no-daemon`. Kind of confusing.

**Comment by ChristianMurphy** [comment]
https://github.com/Jasig/uPortal is running into the same issue https://app.renovatebot.com/dashboard#github/Jasig/uPortal/98443608

Able to reproduce the issue locally as well.

**Comment by ChristianMurphy** [comment]
This appears to have been resolved for uPortal running on hosted renovate

**Comment by chakrihacker** [comment]
I am using react native and got this error

**Comment by rarkins** [comment]
Resolution: use gradle-lite package manager instead
