### ISSUE TITLE
Go mod doesn't work with dependencies using mercurial

### ISSUE THREAD

**Issue by gracenoah** [renovatebot/renovate#4468]
**What Renovate type are you using?**
Hosted app.

**Describe the bug**
When upgrading go modules that have mercurial dependencies, renovate fails.

**Did you see anything helpful in debug logs?**

```
go: bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: hg clone -U https://bitbucket.org/ww/goautoneg . in /tmp/renovate-cache/others/go/pkg/mod/cache/vcs/59c2185b80ea440a7c3b8c5eff3d8abb68c53dea1f20f615370c924c4150b27f: exec: "hg": executable file not found in $PATH
```

**To Reproduce**

1.  Create repository with a go.mod file that includes a dependency on `bitbucket.org/ww/goautoneg`
2.  Try to upgrade it.

**Expected behavior**
mercurial is available

**Screenshots**
n/a

**Additional context**
n/a

**Comment by rarkins** [comment]
The Dockerfile we use is here: https://github.com/renovatebot/docker-go/blob/master/Dockerfile

If you know exactly what needs to be added, can you raise a PR there?

**Comment by gracenoah** [comment]
Done. I'm on a slow internet connection, so I haven't actually tried building the image. I did verify that's the right package name though.

**Comment by gracenoah** [comment]
confirmed that it buidls and hg is available

**Comment by viceice** [comment]
@gracenoah Do you have or know a public mercurial repo to test against?
