### ISSUE TITLE
Python private registry support for pipenv

### ISSUE THREAD

**Issue by emman27** [renovatebot/renovate#4487]
**What would you like Renovate to be able to do?**
We are using Gemfury (gemfury.io) to host some of our private packages. Gemfury hosts it's index at `https://<some-secret>@pypi.fury.io/<org-name>`. Ideally, we'd not want to commit this URL into our repository into the Git repo as that would leave our credentials exposed as plaintext.

However, Renovate can't fetch this extra index without having these credentials to check our dependencies...

**Describe the solution you'd like**
A User Interface for us to key in credentials to be stored securely

**Describe alternatives you've considered**
Just commiting our credentials, which isn't really great.

**Comment by rarkins** [comment]
@emman27 	I've moved this into the main Renovate repo as a feature request. It looks like you could get the *lookup* part of Renovate to work if you added a packageRule like this:

```json
{
  "hostRules": [
    {
      "baseUrl": "https://pypi.fury.io/org-name/",
      "username": "your token",
      "password": ""
    }
  ]
}
```

However after that `pipenv` would fail to update the lock file if we haven't passed the same credentials to it.

- [ ] Verify that hostRules can be used to authenticate pypi furi packages
- [ ] Research how to pass credentials to pipenv without them leaking into the lock file

**Comment by emman27** [comment]
@rarkins thanks! Looks good. However, this would then only notify us that our packages are outdated, but not do the actual updating in that case?

**Comment by HonkingGoose** [comment]
What's the current status of this issue? The last comment was from september 2019, so I think a lot might have changed already. 😄
