### ISSUE TITLE
More options needed when setting autocomplete on azure devops.

### ISSUE THREAD

**Issue by stocksr** [renovatebot/renovate#4514]
**What would you like Renovate to be able to do?**
Control the options used when a dev ops pull request auto completes, currently this is hard coded to squash merge and we don't use squash merges in our setup. (this is a policy decision that we are not changing)

**Describe the solution you'd like**
I would like an option that lets me control the options passed in this azure api call.
https://github.com/renovatebot/renovate/blob/cc1233b7d6f344df983b0fdf155dfa603417fe39/lib/platform/azure/index.ts#L380
specifically the merge type.
see :  here for the options.
https://github.com/microsoft/azure-devops-node-api/blob/f21b5bf4c9b49d53c81eedf771ccd4165b58d1d0/api/interfaces/GitInterfaces.ts#L1732

**Describe alternatives you've considered**
Not using auto complete 

**Additional context**

**Comment by JamieMagee** [comment]
@stocksr Thanks for opening the issue. Would a solution similar to how we manage merges for GitHub work? [See here](https://github.com/renovatebot/renovate/blob/master/lib/platform/github/index.ts#L247-L256). We iterate over all merge types until we find one that works? We can use the [Policy Configurations - Get](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/policy%20configurations/get?view=azure-devops-rest-5.1) API to retrieve branch policies.

**Comment by stocksr** [comment]
That would definitely be better than the current behaviour, and would work for me as we only allow one type.  

My only comment would be that the order you iterate might not work for everybody, I guess this boils down to opinionated vs configurable software, and I don't have a strong opinion either way in this case.

**Comment by JamieMagee** [comment]
Yeah, I think having it as a configuration option is definitely the best way to do this, but I'd like to implement that for all platforms—not just Azure DevOps.

I think the quickest solution to solve your immediate problem is to implement selection of merge type the same as in GitHub, and then add a configuration option that works for all platforms.
