### ISSUE TITLE
BitBucket-Cloud: manually added reviewers get purged

### ISSUE THREAD

**Issue by ZyanKLee** [renovatebot/renovate#4515]
**What Renovate type are you using?**
self-hosted cli

**Describe the bug**
Depending on renovate.json and repository settings, renovate may create PRs without reviewers. So we add them manually.
Sometimes we need to add another reviewer to the PR for various reasons.

If we add reviewers manually, somehow the PR body seems to change when clicking the SAVE button. 
On next renovate run the Body seems to have been changed (well, it was) and is updated by renovate, but apparently updatePr() (https://github.com/renovatebot/renovate/blob/master/lib/platform/bitbucket/index.ts#L662) does not submit reviewers, so they will be removed. Same holds true for the toggle button that configures if the PR's branch should be removed after merging.

```
DEBUG: Found PR #17 (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
DEBUG: Found existing PR (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
DEBUG: Repository URL does not match any known hosts (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
DEBUG: Processing existing PR (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
DEBUG: PR body changed (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
       "prTitle": "chore(deps): update dependency org.mockito:mockito-core to v3",
       "oldPrBody": "This PR contains the following updates:\r\n\r\n| Package | Update | Change |\r\n| --- | --- | --- |\r\n| [org.mockito:mockito-core](https://github.com/mockito/mockito) \\([source](https://github.com/mockito/mockito)\\) | major | `2.28.2` -> `3.0.0` |\r\n\r\n---\r\n\r\n### Renovate configuration\r\n\r\n:date: **Schedule**: At any time \\(no schedule defined\\).\r\n\r\n:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\r\n\r\n:recycle: **Rebasing**: Whenever PR becomes conflicted.\r\n\r\n:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.\r\n\r\n---\r\n\r\nThis PR has been generated by [Renovate Bot](https://renovatebot.com).",
       "newPrBody": "This PR contains the following updates:\n\n| Package | Update | Change |\n|---|---|---|\n| [org.mockito:mockito-core](https://github.com/mockito/mockito) ([source](https://github.com/mockito/mockito)) | major | `2.28.2` -> `3.0.0` |\n\n---\n\n### Renovate configuration\n\n:date: **Schedule**: At any time (no schedule defined).\n\n:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n:recycle: **Rebasing**: Whenever PR becomes conflicted.\n\n:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.\n\n---\n\nThis PR has been generated by [Renovate Bot](https://renovatebot.com)."
DEBUG: updatePr(17, chore(deps): update dependency org.mockito:mockito-core to v3, body) (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
 INFO: PR updated (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
       "committedFiles": false,
       "pr": 17
DEBUG: Checking #17 for automerge (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
       "automerge": false,
       "automergeType": "branch",
       "automergeComment": "automergeComment"
DEBUG: No automerge (repository=team/repository, dependencies=org.mockito:mockito-core, branch=renovate/org.mockito-mockito-core-3.x)
```

**Did you see anything helpful in debug logs?**
see bug description

**To Reproduce**

1.  edit and save PR that was created by renovatebot
2.  wait for renovatebot to come by again

**Expected behavior**

* renovate should at the very least post the complete PR every time it updates it (reviewers, if branch should be removed, etc)
* better yet: renovate should get the whole PR including reviewers and re-submit anything that has not been changed

**Comment by rarkins** [comment]
Looks like maybe a bug where Renovate thinks the PR body is changed when it’s not?

And then second problem is that apparently we need to submit the reviewers with updated PRs even if we’re not changing them?

**Comment by ZyanKLee** [comment]
In fact the body is being changed. On each `\n` a `\r` is inserted on PR editing. (strange thing, imho)

**Comment by ViceIce** [comment]
This looks like the same problem we hat some time ago with `bitbucket-server`. So we need to post the existing reviewers.

**Comment by ZyanKLee** [comment]
I created #5772 to track the body changes during saving etc.

Here I would like to continue tracking the issue concering reviewers getting lost when renovate updates a PR on bitbucket.


**requirement**
* when updating PRs renovate needs to first get a list of the reviewers already in the PR and re-send that list with the PR-update

**Comment by PhilipAbed** [comment]
this is different for each platform,
For bitbucket specifically, 
![image](https://user-images.githubusercontent.com/42116482/166137904-20768814-9ffb-4f4c-a3e8-b56ef2d7ca4e.png)

I can see that someone has added code that will get the reviewers in 1/june/2020

then in 2/december/2020 someone added the reviewers to the PR in :
![image](https://user-images.githubusercontent.com/42116482/166138020-74843319-7e04-487d-b393-0e9c2a7ab24e.png)


this is a very old issue i think it has already been resolved in this case..
I dont see any reproduction data to test..
@rarkins  should i ping the author for this to test again on newer versions? or is it too long ago?
