### ISSUE TITLE
Renovate rebases when maven placeholder dependencies share no common version

### ISSUE THREAD

**Issue by blacelle** [renovatebot/renovate#4522]
**What Renovate type are you using?**
Github App

**Describe the bug**
My projects depends on maven and it has a dependency on hibernate-core. Renovate opens a PR to update it, however I do not want to upgrade. I tried closing the PR but it is re-open as immortal, seemingly because hibernate-c3p0 is also concerned:

This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [org.hibernate:hibernate-core](http://hibernate.org/orm) ([source](https://togithub.com/hibernate/hibernate-orm)) | minor | `5.2.12.Final` -> `5.4.5.Final` |
| [org.hibernate:hibernate-c3p0](http://hibernate.org) ([source](https://togithub.com/hibernate/hibernate-orm)) | patch | `5.2.12.Final` -> `5.2.18.Final` |

However, the proposed change is:

```
		-<hibernate.version>5.2.12.Final</hibernate.version>
		+<hibernate.version>5.2.18.Final</hibernate.version>
```

**Did you see anything helpful in debug logs?**
Nothing I find useful, but it might help you:

```
DEBUG: latest commit(branch="renovate/hibernate-core")
{
  "branchName": "ap5.7",
  "latestCommitDate": "2019-09-13 15:39:42 +0200"
}
DEBUG: getBranchPr(renovate/hibernate-core)(branch="renovate/hibernate-core")
DEBUG: findPr(renovate/hibernate-core, null, open)(branch="renovate/hibernate-core")
DEBUG: Found PR #115(branch="renovate/hibernate-core")
DEBUG: Returning from graphql open PR list(branch="renovate/hibernate-core")
DEBUG: branchExists=true(branch="renovate/hibernate-core")
DEBUG: Branch pr rebase requested: false(branch="renovate/hibernate-core")
DEBUG: Branch has 2 upgrade(s)(branch="renovate/hibernate-core")
DEBUG: Checking if PR has been edited(branch="renovate/hibernate-core")
DEBUG: Found existing branch PR(branch="renovate/hibernate-core")
DEBUG: Checking schedule(at any time, null)(branch="renovate/hibernate-core")
DEBUG: No schedule defined(branch="renovate/hibernate-core")
DEBUG: Branch already exists(branch="renovate/hibernate-core")
DEBUG: getBranchPr(renovate/hibernate-core)(branch="renovate/hibernate-core")
DEBUG: findPr(renovate/hibernate-core, null, open)(branch="renovate/hibernate-core")
DEBUG: Found PR #115(branch="renovate/hibernate-core")
DEBUG: Returning from graphql open PR list(branch="renovate/hibernate-core")
DEBUG: Branch does not need rebasing(branch="renovate/hibernate-core")
DEBUG: Using parentBranch: renovate/hibernate-core(branch="renovate/hibernate-core")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/hibernate-core")
INFO: Need to update package file so will rebase first(branch="renovate/hibernate-core")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/hibernate-core")
DEBUG: Updating packageFile content(branch="renovate/hibernate-core")
DEBUG: Updating packageFile content(branch="renovate/hibernate-core")
DEBUG: Updating packageFile content(branch="renovate/hibernate-core")
DEBUG: Updating packageFile content(branch="renovate/hibernate-core")
DEBUG: Updated 1 package files(branch="renovate/hibernate-core")
DEBUG: No updated lock files in branch(branch="renovate/hibernate-core")
DEBUG: 1 file(s) to commit(branch="renovate/hibernate-core")
DEBUG: Committing files to branch renovate/hibernate-core(branch="renovate/hibernate-core")
INFO: files committed(branch="renovate/hibernate-core")
DEBUG: Checking if we can automerge branch(branch="renovate/hibernate-core")
DEBUG: mergeStatus=no automerge(branch="renovate/hibernate-core")
DEBUG: Ensuring PR(branch="renovate/hibernate-core")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/hibernate-core")
DEBUG: getBranchPr(renovate/hibernate-core)(branch="renovate/hibernate-core")
DEBUG: findPr(renovate/hibernate-core, null, open)(branch="renovate/hibernate-core")
DEBUG: Found PR #115(branch="renovate/hibernate-core")
DEBUG: Returning from graphql open PR list(branch="renovate/hibernate-core")
DEBUG: Found existing PR(branch="renovate/hibernate-core")
DEBUG: Removing duplicate release notes(branch="renovate/hibernate-core")
{
  "depName": "org.hibernate:hibernate-c3p0"
}
DEBUG: Processing existing PR(branch="renovate/hibernate-core")
DEBUG: updatePr(115, Update hibernate core, body)(branch="renovate/hibernate-core")
DEBUG: PR updated(branch="renovate/hibernate-core")
{
  "pr": 115
}
INFO: PR updated(branch="renovate/hibernate-core")
{
  "committedFiles": true,
  "pr": 115
}
DEBUG: Checking #115 for automerge(branch="renovate/hibernate-core")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/hibernate-core")
```

**To Reproduce**
I would suggest having a look directly into the PR:
https://github.com/cormoran-io/apex/pull/115

**Expected behavior**
The PR should not be forced-push if the content is not changed. Else it triggers CI, and my other CI jobs are slowed-down by these useless jobs (60 force-pushes in 1 week).

**Comment by rarkins** [comment]
This an unfortunate edge case where these two packages share the same version placeholder yet do not publish synchronised versions. The ultimate solution is to remove the shared placeholder if it can't be relied on to have common releases, until we can work out a way to ignore it.

**Comment by rarkins** [comment]
BTW when you provide actual reproduction steps for issues it usually speeds up solving by a lot. When users don't provide steps, we usually don't even attempt for a delayed time, because it can be seen as a sign it's not too important for them. Pointing us to a PR is not a way to reproduce, and when it's a private PR we can't actually browse to it anyway. A public repo with the simplest possible reproduction example will always result in a faster fix than no reproduction.

**Comment by blacelle** [comment]
@rarkins Thanks a lot for the fast response, even if I skipped the repro repo :).

Still, shouldn't renovate be able to detect it is pointless to force-push given commit as it is identical to previous PR head?

Also, what are the constrain is term of synchronicity between artifacts?
https://mvnrepository.com/artifact/org.hibernate/hibernate-core
https://mvnrepository.com/artifact/org.hibernate/hibernate-c3p0

They both have a 5.4.5.Final (but possibly not released the same day. We see 5.2.18.Final has beenb released with a delay of 2 months between the 2 artifacts)

**Comment by rarkins** [comment]
If they both have 5.4.5 and we are not detecting it then that’s a bug we should address first.

**Comment by rarkins** [comment]
@zharinov

**Comment by zharinov** [comment]
Hi @blacelle, thank you for reporting this bug, right now I'm investigating it on my own example repo

**Comment by zharinov** [comment]
Just found [hibernate-c3p0 metadata](https://repo.maven.apache.org/maven2/org/hibernate/hibernate-c3p0/maven-metadata.xml) still contains obsolete versions with `5.2.18.Final` as latest stable one. If you're okay to ignore this package, `"ignoreDeps": ["org.hibernate:hibernate-c3p0"]` in `renovate.json` should fix your issue.

**Comment by zharinov** [comment]
Ignoring just one package should cause one more additional PR for `hibernate-core` though. More bulletproof option is to ignore both: `"ignoreDeps": ["org.hibernate:hibernate-core", "org.hibernate:hibernate-c3p0"]`

**Comment by blacelle** [comment]
Fixed by excluding dependencies. Thanks. Is it normal Renovate force-pushed identical commits anyway? I let you close this if this is considered a normal behavior.

**Comment by zharinov** [comment]
Great! I think it's bad edge-case and I need research more on how to address it

**Comment by rarkins** [comment]
I think this behavior shouldn't happen anymore. Renovate checks that each force push is not empty/duplicate
