### ISSUE TITLE
Composer: Don't skip composer scripts on updating/installing

### ISSUE THREAD

**Issue by archnode** [renovatebot/renovate#4531]
**What would you like Renovate to be able to do?**
I'd like composer to run scripts (and refresh the autoloader) on updating dependencies.

**Describe the solution you'd like**
Remove the ```--no-scripts``` and ```--no-autoloader``` options from composer/artifact.ts

**Describe alternatives you've considered**
None

**Additional context**
Skipping scripts prevents plugins from being run. This can be a problem for dependency management as it disables plugins like https://github.com/cweagans/composer-patches which apply additional modifications to files after package installation and scaffolding scripts.

**Comment by rarkins** [comment]
Self hosted or app?

**Comment by archnode** [comment]
Thank you for the quick reply! Self-hosted, I use the latest docker container image.

**Comment by rarkins** [comment]
We could make this as part of our [trustLevel](https://docs.renovatebot.com/self-hosted-configuration/#trustlevel) setting
