### ISSUE TITLE
Transient unit test failures due to network access

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#4538]
**What Renovate type are you using?**
n/a

**Describe the bug**
See [test failures on Azure DevOps](https://dev.azure.com/renovatebot/renovate/_test/analytics?definitionId=1&contextType=build) and narrow down to test failures on master only.

There are 2 categories of tests that appear to have transient issues:

- workers/pr/changelog getChangeLogJson
- datasource/github getDigest

I see that `gh-got-wrapper` is mocked, but it appears as if the tests are still making network requests. I'll need to investigate further.

**Did you see anything helpful in debug logs?**

**To Reproduce**
See [test failures on Azure DevOps](https://dev.azure.com/renovatebot/renovate/_test/analytics?definitionId=1&contextType=build).

We run ~750k tests/week so sometimes the full test logs are not available

**Expected behavior**
Tests should work without network access

**Comment by rarkins** [comment]
@JamieMagee I turned off wifi and ran `yarn jest` successfully just now, so I'm going to close this assuming that tests now work without network access

**Comment by ViceIce** [comment]
@rarkins I think this was fixed by #4870
