### ISSUE TITLE
Receiving Renovate PRs and updates out of schedule

### ISSUE THREAD

**Issue by moorara** [renovatebot/renovate#4544]
**What Renovate type are you using?**

We're using Renovate GitHub app from GitHub Marketplace.

**Describe the bug**

We have a single source of truth for our Renovate configurations which is as follows:

```json
{
  "extends": [
    "config:base"
  ],
  "timezone": "America/Toronto",
  "schedule": [ "before 6am" ],
  "postUpdateOptions": [ "gomodTidy" ],
  "automerge": true,
  "automergeType": "pr",
  "major": {
    "automerge": false
  },
  "packageRules": [
    {
      "packagePatterns": [ "^golang.org/x/" ],
      "groupName": "sub-repository packages",
      "schedule": [ "every weekend" ]
    },
    {
      "packageNames": [ "github.com/aws/aws-sdk-go" ],
      "schedule": [ "every weekend" ]
    }
  ]
}
```

Our problem is we receiving updates from Renovate out of the schedule (12:00am - 6:00am).
I think this is only the case when a Renovate PR already exists and when developers merge other PRs to a repo, Renovate PRs get updated!

**Did you see anything helpful in debug logs?**

Not really!

**To Reproduce**

Some example Job IDs:
  - 98422817
  - 98423079
  - 98419751

**Expected behavior**

We'd like to not receive any Renovate PR or updates to Renovate PRs out of the schedule.

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
We'll solve this with #4866
