### ISSUE TITLE
#4353 in 19.52.0 causes git clone error / platform error due to private repository

### ISSUE THREAD

**Issue by ajcann** [renovatebot/renovate#4547]
**What Renovate type are you using?**
GitHub hosted

**Describe the bug**
A private repository is configured with renovate. This repository has a private github repository submodule. The latest release of renovate attempts to checkout the submodule but fails with a permissions error. There is no way to disable this behavior currently.

**Did you see anything helpful in debug logs?**

> DEBUG: git clone error
> {
>   "err": {
>     "message": "Cloning into '.'...\nSubmodule 'private repo' (git@github.com:org/private repo.git) registered for path 'private repo'\nCloning into '/mnt/renovate/gh/org/project/private repo'...\nERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@github.com:org/private repo.git' into submodule path '/mnt/renovate/gh/org/project/private repo' failed\nFailed to clone 'private repo'. Retry scheduled\nCloning into '/mnt/renovate/gh/org/project/private repo'...\nERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@github.com:org/private repo.git' into submodule path '/mnt/renovate/gh/org/project/private repo' failed\nFailed to clone 'private repo' a second time, aborting\n",
>     "stack": "Error: Cloning into '.'...\nSubmodule 'private repo' (git@github.com:org/private repo.git) registered for path 'private repo'\nCloning into '/mnt/renovate/gh/org/project/private repo'...\nERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@github.com:org/private repo.git' into submodule path '/mnt/renovate/gh/org/project/private repo' failed\nFailed to clone 'private repo'. Retry scheduled\nCloning into '/mnt/renovate/gh/org/project/private repo'...\nERROR: Repository not found.\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\nfatal: clone of 'git@github.com:org/private repo.git' into submodule path '/mnt/renovate/gh/org/project/private repo' failed\nFailed to clone 'private repo' a second time, aborting\n\n    at /home/ubuntu/renovateapp/node_modules/simple-git/promise.js:62:29\n    at Git. (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:214:18)\n    at Function.Git.fail (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1474:18)\n    at fail (/home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1432:20)\n    at /home/ubuntu/renovateapp/node_modules/simple-git/src/git.js:1441:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
>   }
> }
> INFO: Platform error - skipping

**To Reproduce**

1.  Create repository with submodule which is a private repository
2. Allow renovate to run

**Expected behavior**
The submodule recurse should probably have a way to specify credentials but also there should be a way to disable the submodule recurse checkout from happening as an option.

**Comment by rarkins** [comment]
Renovate should be able to complete the clone of both of the repos are private and both are added to Renovate (even if the submodule repo is not onboarded).

**Comment by ajcann** [comment]
> Renovate should be able to complete the clone of both of the repos are private and both are added to Renovate (even if the submodule repo is not onboarded).

In this case both repos are added to Renovate (both are onboarded as well).

**Comment by rarkins** [comment]
@JamieMagee let’s default this functionality to false until we can test more. It’s strange if Renovate is being denied access using a token that theoretically should grant it access.

**Comment by ajcann** [comment]
@rarkins Does renovate checkout via http rather than ssh? (Probably if using a token, right?). Our .gitmodules specifies submodules as ssh checkout (i.e. url = git@github.com:[...].git ). I suspect that may be an issue.

**Comment by rarkins** [comment]
@ajcann yes, https. GitHub Apps cannot have ssh keys. This would explain it.

**Comment by ajcann** [comment]
Looks like this might be solvable on the user side via https://stackoverflow.com/questions/40841882/automatically-access-git-submodules-via-ssh-or-https
Which would involve using a relative path to the submodule allowing the inheriting of checkout method from the parent. This way both ssh and https should continue to function.

**Comment by JamieMagee** [comment]
@rarkins I'll try and send out a PR later this evening

**Comment by JamieMagee** [comment]
Okay, what I've come up with is delaying the init of submodules, and instead cloning each individually in a try/catch after the initial clone. What do you think?

I think it is probably the behaviour that most users expect, and if we are unable to clone the submodules correctly you'll get a couple of warnings in your logs.
