### ISSUE TITLE
Use yarn to install lerna if npmClient=yarn

### ISSUE THREAD

**Issue by bmish** [renovatebot/renovate#4566]
**What Renovate type are you using?**
Self-hosted. Bitbucket Server. We run Renovate with a cronjob every 15 minutes.

**Describe the bug**

Renovate successfully updates dependencies inside workspace folders. But it fails to update dependencies mentioned in the top-level package.json of the repository. It will create those update PRs but the yarn.lock file will be missing, and the PR will have the following error:

```
Artifact update problem
Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.
File name: yarn.lock
/bin/sh: npm: command not found
```

**Did you see anything helpful in debug logs?**
I looked at the logs and did not see this error mentioned.

**To Reproduce**

1. Create a yarn workspace repository.
2. Wait for a dependency update PR to be created for a top-level package.json dependency.

**Expected behavior**

Renovatebot should be able to successfully create dependency update PRs for top-level package.json dependencies in the yarn workspace.

**Comment by rarkins** [comment]
Are you using lerna?

**Comment by bmish** [comment]
Yes, looks like all the repositories I tried it on are using lerna. I can try out a monorepo without lerna to confirm if lerna is the cause. Is lerna supported?

Looks like this issue could be related to #3317.

**Comment by rarkins** [comment]
Can you paste in your lerna.json?

**Comment by bmish** [comment]
// top-level package.json (minimized)
```
{
  "private": true,
  "name": "some name",
  "engines": {
    "node": ">= 8"
  },
  "repository": {
    "type": "git",
    "url": "ssh://git@some-url.git"
  },
  "workspaces": [
    "packages/*"
  ]
}
```

lerna.json
```
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

**Comment by rarkins** [comment]
I thought it might be failing because you hadn't configured `npmClient`. We will need a reproduction of this problem on a public GitHub repo to be able to troubleshoot it further, unless you can dig deeper into your own logs, particularly when `package.json` is getting extracted.

**Comment by bmish** [comment]
I just removed lerna from one of my repositories (it was easily replaced by the `yarn workspaces run` command in my case) and the problem is now fixed. So this issue is specific to lerna.

I'll try making an example repo when I have a chance.

**Comment by bmish** [comment]
@rarkins: Some good news, I was finally able to find a relevant error message in the logs that indicates that this error message is coming from an npm command executed by a child process in [lerna.ts](https://github.com/renovatebot/renovate/blob/master/lib/manager/npm/post-update/lerna.ts):

```
INFO: lock file error (repository=~myRepo/my-repo, branch=renovate/pin-dependencies)
      "cmd": "npm i -g -C ~/.npm/lerna@^3.19.0 lerna@^3.19.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@^3.19.0/bin/lerna bootstrap --no-ci -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
      "err": {
        "killed": false,
        "code": 127,
        "signal": null,
        "cmd": "npm i -g -C ~/.npm/lerna@^3.19.0 lerna@^3.19.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@^3.19.0/bin/lerna bootstrap --no-ci -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
        "stdout": "",
        "stderr": "/bin/sh: npm: command not found\n",
        "message": "Command failed: npm i -g -C ~/.npm/lerna@^3.19.0 lerna@^3.19.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@^3.19.0/bin/lerna bootstrap --no-ci -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: npm: command not found\n",
        "stack": "Error: Command failed: npm i -g -C ~/.npm/lerna@^3.19.0 lerna@^3.19.0 && yarn install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 && ~/.npm/lerna@^3.19.0/bin/lerna bootstrap --no-ci -- --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\n/bin/sh: npm: command not found\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
      },
      "type": "lerna",
      "lernaClient": "yarn"
```

We were able to fix this by adding `node_modules/.bin` to our `PATH` environment variable before running the renovate cli command. This may be needed in part because we don't have npm available globally on our machines.

Now I'm wondering:
1. Is this is the right fix? 
2. Could renovatebot be improved to either:
    a. Avoid the need for this fix
    b. Check and warn upfront about npm being missing
    c. Improve documentation around this (I did later notice that the [self-hosting doc](https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md) briefly hints at modifying `PATH` in one of its examples)

**Comment by rarkins** [comment]
Thanks for the update @bmish.

I think if lernaClient=yarn then we should be using `yarn` to install globally instead of `npm` (assuming the same cache trick is available). I'm a little surprised that you have a Node.js installation but `npm` is not in the path? I've always seen it implicitly/automatically added. Do you know what it is about your installations that make it "special"?

It's possible that Renovate could alter the PATH passed to child process so that its own node_modules/.bin is added to the path, however that would be only a temporary solution because in a future breaking release we plan to stop bundling npm/yarn/pnpm as dependencies of Renovate.

**Comment by bmish** [comment]
Fixing renovatebot to use `yarn` to install globally in this case makes sense.

In my setup, we copy a Node binary into our deployed artifact, but it seems that we forgot to copy `npm` as well, so that's why it's missing for us.

Giving this learning, and since renovatebot won't bundle npm/yarn/pnpm in the future, adding `node_modules/.bin` to the `PATH` sounds like the wrong solution.
