### ISSUE TITLE
Wrong update version for go module in subdirectory

### ISSUE THREAD

**Issue by hairyhenderson** [renovatebot/renovate#4589]
**What Renovate type are you using?**

Hosted

**Describe the bug**

See https://github.com/hairyhenderson/gomplate/pull/603#issuecomment-538607763 for the error.

Looks like renovate picked up the `github.com/hashicorp/consul` `v1.6.1` tag, however the `github.com/hashicorp/consul/api` module is at `v1.2.0` still. This is reflected by the presence of an `api/v1.2.0` tag.

**Did you see anything helpful in debug logs?**

Nope!

**To Reproduce**

1.  Create repository with a dependency on the `github.com/hashicorp/consul/api` package
2. Watch renovate get confused and try to bump the version for that module to `v1.2.0`!

**Expected behavior**

Renovate should understand the `api/v1.2.0` tag.

**Screenshots**

See https://github.com/hairyhenderson/gomplate/pull/603

**Comment by rarkins** [comment]
Here's the update:
![image](https://user-images.githubusercontent.com/6311784/66265076-6b5eb380-e810-11e9-9949-77fad1572557.png)

It's basing this on the raw hashicorp/consul releases:
![image](https://user-images.githubusercontent.com/6311784/66265085-8df0cc80-e810-11e9-8a80-b6f12cc29b65.png)

But actually it should be following the api/* releases:
![image](https://user-images.githubusercontent.com/6311784/66265088-9f39d900-e810-11e9-9169-95f3c90dd57e.png)

@hairyhenderson I don't suppose you already know where this Go behaviour is specified? I want to make sure there's nothing else we're missing.

**Comment by rarkins** [comment]
@ViceIce I'm thinking we might need to try to leverage our "compatibility" versioning concept here, like we do with Docker suffixes

**Comment by ViceIce** [comment]
What about to have prefix and suffix options?

**Comment by rarkins** [comment]
I'm trying to locate some Go specs on this first before making a decision. For example I want to see if this is always how the versions work, if there is any fallback to non-prefixed releases, and if there is possibility to nest more than one deep. I don't suppose @bcmills can point us in the right direction documentation/specification-wise? Thanks

**Comment by hairyhenderson** [comment]
> I don't suppose you already know where this Go behaviour is specified? I want to make sure there's nothing else we're missing.

There is some mention here in the Go Modules wiki: https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories:

With some somewhat-cryptic statements like:

```
The tag for version 1.2.3 of module "my-repo/foo/rop" is "foo/rop/v1.2.3".
```

I haven't found anything more "official" than that though...

**Comment by rarkins** [comment]
Thanks for that. Sounds like we need to support arbitrary depth then.

**Comment by rarkins** [comment]
You're specifically referring to `go list -m -versions`, right?

**Comment by rarkins** [comment]
dummy example:
```
❯ cat go.mod
module arkins.net/test1

go 1.13

require rsc.io/quote v1.5.2
```

Get all deps:
```
❯ go list -m all
arkins.net/test1
golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
rsc.io/quote v1.5.2
rsc.io/sampler v1.3.0
```

Get all updates:
```
❯ go list -m -versions all
arkins.net/test1
golang.org/x/text v0.1.0 v0.2.0 v0.3.0 v0.3.1 v0.3.2
rsc.io/quote v1.0.0 v1.1.0 v1.2.0 v1.2.1 v1.3.0 v1.4.0 v1.5.0 v1.5.1 v1.5.2 v1.5.3-pre1
rsc.io/sampler v1.0.0 v1.2.0 v1.2.1 v1.3.0 v1.3.1 v1.99.99
```

Get one update at a time:
```
❯ go list -m -versions rsc.io/sampler
rsc.io/sampler v1.0.0 v1.2.0 v1.2.1 v1.3.0 v1.3.1 v1.99.99
```

Try to get an update for a module not in the go.mod:
```
❯ go list -m -versions github.com/hashicorp/consul/api
go: finding github.com/hashicorp/consul/api v1.2.0
github.com/hashicorp/consul/api v1.0.0 v1.0.1 v1.1.0 v1.2.0
```

Attempting to look up versions from a random directory:
```
❯ mkdir /tmp/gomodtest2 && cd /tmp/gomodtest2 && go list -m -versions github.com/hashicorp/consul/api
go list -m: not using modules
```

In conclusion: if we have a "dummy" modules project to run the child process from, it seems we can indeed shell out to `go` for the lookups.

The main thing I'd been worried about was that we wouldn't get back the full list of versions, but it appears that's not a problem here. So I think this approach is indeed compatible with Renovate's logic.

One more concern: Can this `go list` command be run concurrently (same working directory, but for different modules), or must they be run sequentially?

**Comment by bcmills** [comment]
> You're specifically referring to `go list -m -versions`, right?

`-versons`, but also `go list -m $MODULE@$COMMIT`, which will resolve `$COMMIT` to the pseudo-version the `go` command would use for that commit.

> `go list -m: not using modules`

You can set `GO111MODULE=on` explicitly to activate module mode when outside of a module.

**Comment by bcmills** [comment]
> Can this `go list` command be run concurrently (same working directory, but for different modules), or must they be run sequentially?

`go list` in module mode has been safe for concurrent use since [Go 1.12](https://golang.org/doc/go1.12#modules).

**Comment by bcmills** [comment]
For example:
```

$ GO111MODULE=on go1.13.1 list -m github.com/hashicorp/consul/api@6439af8
go: finding github.com/hashicorp/consul/api 6439af8
github.com/hashicorp/consul/api v1.2.1-0.20191007211523-6439af86ebe3
```

**Comment by rarkins** [comment]
It just occurred to me that the list all command is including indirect dependencies, which I don’t think Renovate should be updating. Is there any lost command that lists all direct dependencies but no indirect?

**Comment by bcmills** [comment]
There isn't a simple one at the moment, no.
(But there is probably a complicated one: see https://github.com/golang/go/issues/27887#issuecomment-435402090.)

**Comment by tbpg** [comment]
What about iterating through the `"Require"` list of `go mod edit -json`, passing each `"Path"` to `go list -m -versions $path`?

**Comment by bcmills** [comment]
Yes, you could do that — just be sure to check the `Indirect` field.

**Comment by vvakame** [comment]
another examples https://github.com/googleapis/google-cloud-go/releases

**Comment by HonkingGoose** [comment]
Pinging @rarkins to take a look at this, as the last movement on this issue has been in November of 2019. So I think it's due a slight nudge/update. 😉 

I've marked the issue `priority-3-normal` as it does seem that this is something that @rarkins wants to implement.

**Comment by nabeelsaabna** [comment]
Hi @rarkins, 
Any reason why we are not simply implementing a smart lookup for Go ?
In case of `github.com/org-name/my-repo/foo/rop`  to check the tags starting with `foo/rop/`

Is there a consideration to actually using the `go` command ?

**Comment by viceice** [comment]
> 
> Is there a consideration to actually using the `go` command ?

Yes, we only use those binaries for artifacts updating (performance)

**Comment by nabeelsaabna** [comment]
Then we are left with only the first option 😃

**Comment by nabeelsaabna** [comment]
@rarkins is there any reason to not implement the first suggested solution ?

**Comment by rarkins** [comment]
No reason. We should try to mimic Go's logic (including if it falls back to using plain tags)
