### ISSUE TITLE
Monorepo grouping no longer working for Neutrino

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#4607]
**What Renovate type are you using?**
Hosted app

**Describe the bug**
The Neutrino monorepo is listed here:
https://github.com/renovatebot/presets/blob/ab46073f25d9c08b15ac9a7b14ab20fc5f55f614/packages/renovate-config-monorepo/generate.js#L64

...however recent package updates from the Neutrino monorepo are not being grouped together into one PR:
https://github.com/mozilla/treeherder/pull/5464
https://github.com/mozilla/treeherder/pull/5462

...even though they were for updates in the past, eg:
https://github.com/mozilla/treeherder/pull/4955

ie: This looks like a regression sometime since May 2019?

**Comment by rarkins** [comment]
Do all packages declare their source repository correctly ? We moved to a system where we group based on source repo which is more reliable assuming packages are published with correct metadata

**Comment by edmorley** [comment]
Hi! For the 9.0.0 release candidate releases, the repository is defined as:
https://github.com/neutrinojs/neutrino/blob/v9.0.0-rc.4/package.json#L8

However for `stable` (v8.X.X) the repository is defined as the old location (we renamed the repo some time ago):
https://github.com/neutrinojs/neutrino/blob/release/v8/package.json#L8

If I visit npmjs, I see it doesn't show per-version metadata, and instead reports the metadata from the stable release, even when viewing another version, eg:
https://www.npmjs.com/package/neutrino/v/9.0.0-rc.4

Is Renovate perhaps using that metadata, rather than what's in the package itself?

**Comment by edmorley** [comment]
Looking at the package.json inside the actual package, it looks like [Lerna]() sets the repository URL to the subdirectory for that package inside the repo:
https://unpkg.com/browse/neutrino@9.0.0-rc.4/package.json
https://unpkg.com/browse/@neutrinojs/react@9.0.0-rc.4/package.json

Is Renovate perhaps comparing the URLs for equality without stripping off the path component of the URL?

**Comment by rarkins** [comment]
I think we're just looking for the repo: https://github.com/renovatebot/presets/blob/5a7f1c08946cc19c715b2fc5f853e21a9d5fcca7/packages/renovate-config-monorepo/generate.js#L64

The syntax being used currently is actually wrong - it should not be expressed that way. Here's how it should:

![image](https://user-images.githubusercontent.com/6311784/66387343-1368ae00-e9c4-11e9-9734-ff6271cc0385.png)

(ref: https://docs.npmjs.com/files/package.json#repository)

**Comment by rarkins** [comment]
I don't think it's Lerna doing it btw, I think these paths are already hardcoded into the repo, e.g. https://github.com/neutrinojs/neutrino/blob/60e3c0364f95920d8e41710b5c05deef67b32680/packages/airbnb-base/package.json#L14

**Comment by edmorley** [comment]
Oh you're right - looks like we should fix those then. Thank you for the spec link!

**Comment by edmorley** [comment]
@rarkins Hi! I updated the package metadata for the Neutrino monorepo packages in:
https://github.com/neutrinojs/neutrino/pull/1482

However for our latest release (`9.0.0-rc.5`) Renovate still opened separate PRs rather than grouping them, eg:
https://github.com/mozilla-frontend-infra/firefox-performance-dashboard/pull/250
https://github.com/mozilla-frontend-infra/firefox-performance-dashboard/pull/249
https://github.com/mozilla-frontend-infra/firefox-performance-dashboard/pull/247

Also the Renovate PR descriptions still reference the old repository location (`mozilla-neutrino/neutrino-dev`). Those links were last used in the Neutrino v8 release series (the current NPM `latest`). 

Is it possible Renovate is pulling metadata from `latest` (ie stable v8) and not the RC version being referenced?

**Comment by rarkins** [comment]
> Is it possible Renovate is pulling metadata from latest (ie stable v8) and not the RC version being referenced?

Yes that's probably the case. IIRC Renovate will use the information found at the top level of the package metadata on npmjs. e.g.

![image](https://user-images.githubusercontent.com/6311784/68863842-f1d6a280-06a4-11ea-9fc7-4290fab496fb.png)

(Source: http://registry.npmjs.org/@neutrinojs%2freact)

Going deeper into that package information, I can confirm I see the correct syntax for the RC version:
![image](https://user-images.githubusercontent.com/6311784/68863924-2185aa80-06a5-11ea-9a14-0311dfe8e4b7.png)

So I guess this is an edge case that Renovate doesn't handle right now

**Comment by rarkins** [comment]
@edmorley I will close this now, as I added the old monorepo to the existing neutrino preset and I think that fixes it for old packages too: https://github.com/renovatebot/presets/blob/d62d05e49d35475333c13a227558b46e92c530f3/packages/renovate-config-monorepo/package.json#L300

**Comment by edmorley** [comment]
Thank you :-)
