### ISSUE TITLE
Renovate attempts to pin  deprecated version of dependency

### ISSUE THREAD

**Issue by djcsdy** [renovatebot/renovate#4608]
**What Renovate type are you using?**
Hosted app, GitHub.

**Describe the bug**
See this PR raised by Renovate: https://github.com/djcsdy/wildflower-codec/pull/2

Renovate is attempting to pin the crate "bitflags" to "=1.0.5", but that version is "yanked" from Cargo, meaning it is deprecated.

Yanked versions are still available to download, but Cargo will refuse to create a new lockfile that locks a dependency to a yanked version. Since the lockfile is not checked in with this project, pinning the dependency to a yanked version causes the build to fail.

**Did you see anything helpful in debug logs?**
```
        {
            "depName": "bitflags",
            "depType": "dependencies",
            "currentValue": "1.0",
            "managerData": {
              "nestedVersion": false
            },
            "datasource": "cargo",
            "updates": [
              {
                "updateType": "pin",
                "isPin": true,
                "newValue": "=1.0.5",
                "newMajor": 1
              },
              {
                "fromVersion": "1.0.5",
                "toVersion": "1.2.0",
                "newValue": "=1.2.0",
                "newMajor": 1,
                "newMinor": 2,
                "updateType": "minor",
                "isSingleVersion": true,
                "isRange": true,
                "blockedByPin": true
              }
            ],
            "warnings": [],
            "sourceUrl": null
          }
```

**To Reproduce**

1. Create new Rust project with the following dependencies in `Cargo.toml`:
```toml
[dependencies]
bitflags = "1.0"
```

2. Configure Renovate to pin dependencies:
renovate.json
```json
{
  "extends": [
    "config:base",
    ":pinAllExceptPeerDependencies"
  ]
}
```

3. Check in and push `Cargo.toml` and `renovate.json`. **Do not check in `Cargo.lock`.**

4. Activate Renovate on the repository and wait for Renovate to create a PR.

**Expected behavior**
Renovate should pin the dependency to =1.0.4, which is the latest non-yanked version matching the specified dependency range. This is the version that cargo would select if a developer checked out a fresh copy of the repository and ran `cargo install`.

Note that the lockfile (`Cargo.lock`) is not checked into this repository. This is the recommended practice for Rust libraries. If the lockfile were checked in, I would expect Renovate to pin the version to the exact version specified in the lockfile, **even if that version is deprecated**. This would not fail the build since Cargo will allow the existing dependency lock to remain in place.

**Additional context**
I remembered that there was some discussion about handling yanked dependencies when Rust support was first added (#2795), so I took a look at the relevant code: https://github.com/renovatebot/renovate/blob/master/lib/datasource/cargo/index.ts#L84-L86

I compared this implementation with the [bitflags JSON from crates.io](https://raw.githubusercontent.com/rust-lang/crates.io-index/master/bi/tf/bitflags) and it seems to match up. I think renovate is marking the yanked version as deprecated correctly.

The problem seems to be that renovate ignores the `isDeprecated` flag when pinning. I searched the code for `isDeprecated` and the only occurrence I found (other than data sources setting the flag) was here: https://github.com/renovatebot/renovate/blob/master/lib/workers/repository/process/lookup/filter.ts#L40-L52

I am not sure if this code is called at all when pinning dependencies but if it is then it is ineffective.

I want to reiterate that I am pretty sure this problem **can only happen if the lockfile is not committed**.

I am pretty sure this problem can occur for npm/yarn projects too. If it hasn’t come up before then that’s probably because it’s rare for the last release in a release series to be deprecated :-).

**Comment by djcsdy** [comment]
Looks like the problem is here: https://github.com/renovatebot/renovate/blob/master/lib/workers/repository/process/lookup/index.ts#L392-L396

Notice `allVersions` includes deprecated versions, and `version.maxSatisfyingVersion(allVersions, currentValue)` will return a deprecated version if the maximum version satisfying the range is deprecated.

**Comment by rarkins** [comment]
Interesting edge case!

**Comment by djcsdy** [comment]
I don’t think this is specific to Cargo. I’m pretty sure this will affect any datasource that includes deprecated versions (currently Cargo and npm).

**Comment by rarkins** [comment]
Npm does not have the same behaviour for deprecated versions
