### ISSUE TITLE
[Question] Ignore gradle package

### ISSUE THREAD

**Issue by LeJeanbono** [renovatebot/renovate#4632]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Gitlab.com

### Have you checked the logs? Don't forget to include them if relevant
``` javascript
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "gradle": {
      "enabled": true
    },
    "branchPrefix": "dependance/",
    "packageRules": [
      {
        "managers": [
          "gradle"
        ],
        "packagePatterns": [
          "^com.limark.gitflowsemver"
        ],
        "enabled": false
      }
    ]
  }
}
```

``` javascript
WARN: Gradle command docker run --rm -v /mnt/renovate/gl/csuite/datawarehouse/api:/mnt/renovate/gl/csuite/datawarehouse/api -w /mnt/renovate/gl/csuite/datawarehouse/api renovate/gradle gradle --init-script renovate-plugin.gradle renovate failed. Exit code: 1.
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm -v /mnt/renovate/gl/csuite/datawarehouse/api:/mnt/renovate/gl/csuite/datawarehouse/api -w /mnt/renovate/gl/csuite/datawarehouse/api renovate/gradle gradle --init-script renovate-plugin.gradle renovate",
    "stdout": "To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html.\nDaemon will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n",
    "stderr": "\nFAILURE: Build failed with an exception.\n\n* Where:\nBuild file '/mnt/renovate/gl/csuite/datawarehouse/api/build.gradle' line: 50\n\n* What went wrong:\nPlugin [id: 'com.limark.gitflowsemver', version: '0.4.0-alpha.7'] was not found in any of the following sources:\n\n- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)\n- Plugin Repositories (could not resolve plugin artifact 'com.limark.gitflowsemver:com.limark.gitflowsemver.gradle.plugin:0.4.0-alpha.7')\n  Searched in the following repositories:\n    Gradle Central Plugin Repository\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 28s\n",
    "message": "Command failed: docker run --rm -v /mnt/renovate/gl/csuite/datawarehouse/api:/mnt/renovate/gl/csuite/datawarehouse/api -w /mnt/renovate/gl/csuite/datawarehouse/api renovate/gradle gradle --init-script renovate-plugin.gradle renovate\n\nFAILURE: Build failed with an exception.\n\n* Where:\nBuild file '/mnt/renovate/gl/csuite/datawarehouse/api/build.gradle' line: 50\n\n* What went wrong:\nPlugin [id: 'com.limark.gitflowsemver', version: '0.4.0-alpha.7'] was not found in any of the following sources:\n\n- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)\n- Plugin Repositories (could not resolve plugin artifact 'com.limark.gitflowsemver:com.limark.gitflowsemver.gradle.plugin:0.4.0-alpha.7')\n  Searched in the following repositories:\n    Gradle Central Plugin Repository\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 28s\n",
    "stack": "Error: Command failed: docker run --rm -v /mnt/renovate/gl/csuite/datawarehouse/api:/mnt/renovate/gl/csuite/datawarehouse/api -w /mnt/renovate/gl/csuite/datawarehouse/api renovate/gradle gradle --init-script renovate-plugin.gradle renovate\n\nFAILURE: Build failed with an exception.\n\n* Where:\nBuild file '/mnt/renovate/gl/csuite/datawarehouse/api/build.gradle' line: 50\n\n* What went wrong:\nPlugin [id: 'com.limark.gitflowsemver', version: '0.4.0-alpha.7'] was not found in any of the following sources:\n\n- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)\n- Plugin Repositories (could not resolve plugin artifact 'com.limark.gitflowsemver:com.limark.gitflowsemver.gradle.plugin:0.4.0-alpha.7')\n  Searched in the following repositories:\n    Gradle Central Plugin Repository\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 28s\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  }
}
INFO: Aborting Renovate due to Gradle lookup errors
```
### What is your question?
The package `com.limark.gitflowsemver` is on a private repositorie
In my `build.gradle` I put :
``` javascript
repositories {
    mavenLocal()
    mavenCentral()
    maven {
      url "http://nexus.tools.mydomain.io/repository/maven-group/"
      credentials {
        username = "MyUser"
        password = "MyPassword"
      }
    }
  }
```
Renovate don't take care of that private repository.
So I would like to ignore the dependancie.
My conf seems to not work, what did I miss ?
Thanks !

**Comment by rarkins** [comment]
I think we need to move this into the main repo as I'm not sure anything can be done with config here.

This error is happening in our `extractAllPackageFiles` gradle function, which means it's too early to "disable" any dependencies (the job of extractAllPackageFiles is to extract them, before we then apply rules).

I'm not a Gradle user, but I'd think we want to see some changes to how we approach this:
1. If credentials are provided, we should use them
2. If we fail to look up private repositories, we should ideally continue updating the others anyway

@corecanarias @ikesyo can we look into (2) first, i.e. being more robust and not just quitting if we fail on one package?

**Comment by ikesyo** [comment]
> If we fail to look up private repositories, we should ideally continue updating the others anyway

Actually this is about fail to look up private `dependencies`, not `repositories` (`com.limark.gitflowsemver` in this case). To do that, we need to comment out `com.limark.gitflowsemver` dependency from input gradle files.

**Comment by rarkins** [comment]
@ikesyo do you have any suggestions for how Renovate can handle this gracefully? Normally we happily continue as far as we can even if some dependencies can't be resolved.

**Comment by ikesyo** [comment]
@rarkins  Unfortunately no at least for now.

@LeJeanbono Are you sure that you private repository settings for your private plugin dependency (looks like `com.limark.gitflowsemver:com.limark.gitflowsemver.gradle.plugin` is a Gradle plugin) is configured in `buildscript { repositories { ... } }` or `settings.gradle`'s ` pluginManagement { repositories { .. } }`?

Ref: https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management

**Comment by LeJeanbono** [comment]
@ikesyo All my gradle conf is in the `gradle.build` file.
I have `repositories` conf in the root of the file and in `buildscript`

**Comment by falkenhawk** [comment]
I tried to use renovatebot but it can't go through it's initialization state because of gradle command failing (i.a. job id: 118261648). I'd love to hear if an option to skip commands / recover from errors is in the works. Or maybe a per-repository setting to ignore specified folders. I resorted to using dependabot for now, but I'd love to try renovate because it's much more flexible in configuration. 💚

**Comment by rarkins** [comment]
@falkenhawk I notice this error causing it to bail:

`Could not read script '[**redacted**]/cordova.variables.gradle' as it does not exist.`

You should be able to see the full unredacted path via the dashboard. Does that particular file existing in the git repo?

For now this type of error is kind of terminal for Gradle, so the only option until it's fixed would be to disable gradle.

**Comment by viceice** [comment]
@LeJeanbono Does this error still occure? I think the current gradle implementation should log and skip gradle if command fails. Can you please try with the latest renovate version / current renovate app.

**Comment by LeJeanbono** [comment]
Seems ok, thanks @viceice
