### ISSUE TITLE
Azure DevOps Dashboard widgets

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4633]
**What would you like Renovate to be able to do?**

Enhance visibility of dependencies for Azure DevOps users by pushing data into a dashboard.

**Describe the solution you'd like**

At the end of each run, Renovate builds a summary and pushes the results into Azure DevOps dashboard widgets.

**Additional context**

https://docs.microsoft.com/en-us/azure/devops/report/dashboards/overview?view=azure-devops

**Comment by rarkins** [comment]
@jycouet @JamieMagee what do you think?

**Comment by JamieMagee** [comment]
Yeah, sounds like a good idea and fairly easy to implement. A couple of ideas:
1. A widget showing open PRs from Renovate
2. A chart showing breakdown by upgrade type e.g. major, minor, patch, etc.
3. A number tile showing PRs merged/created by Renovate
