### ISSUE TITLE
Python Compatibility Option 

### ISSUE THREAD

**Issue by chodges15** [renovatebot/renovate#4652]
**What Renovate type are you using?**
Self-hosted 19.61.1 with GitHub Enterprise

**Describe the bug**
Using the following the [documented](https://docs.renovatebot.com/configuration-options/#compatibility) configuration results in an invalid config error.

```
"compatibility": {
  "python": "2.7"
}
```

**Did you see anything helpful in debug logs?**
This shows up during repo scan:
```
 INFO: Found renovate config errors (repository=chodges/testRenovateConfig)
       "errors": [
         {
           "depName": "Configuration Error",
           "message": "Configuration option `compatibility.python` should be a json object"
         }
       ]
 INFO: Repository has invalid config (repository=chodges/testRenovateConfig)
       "error": {
         "configFile": "renovate.json",
         "validationError": "The renovate configuration file contains some invalid settings",
         "validationMessage": "Configuration option `compatibility.python` should be a json object"
       }
```

**To Reproduce**

1.  Create repository with a config.json that includes:
```
"compatibility": {
  "python": "2.7"
}
``` 
2.  Run renovate and observe error

**Expected behavior**
The ability to use previously functional Python compatibility checks to limit the amount of non-mergeable PRs that are raised by Renovate in older Python repos.

**Clues**
It was observed that when #2736 was merged, the `python` configuration type was json. It seems like this feature may have broken when `python` was change from `json` to `object` in #3434. It also seems like the following code is not expecting `python` configuration to be an object. https://github.com/renovatebot/renovate/blob/f1073965ab8cdc1b982d5e9fb8568a6571976d4b/lib/datasource/pypi/index.ts#L26

**Comment by rarkins** [comment]
Sorry, this is now resolved.
