### ISSUE TITLE
Fix git url retreival for non-github projects for npm.

### ISSUE THREAD

**Issue by vivanov00** [renovatebot/renovate#4654]
As per @rarkins 's comments in  https://github.com/renovatebot/renovate/issues/3323
At present, renovate's npm datasource can only retrieve and set sourceUrl for github.com based projects.

It is possible that this affects other datasources dependant on the aforementioned library https://github.com/tj/node-github-url-from-git/
A fix/workaround for this behaviour should be provided, with a potential option for it to be transferable to other datasources, perhaps via an utils library function.

**Comment by rarkins** [comment]
At minimum, let's push it into datasource/index so that the same logic applies to all datasources and not just npm's. i.e. datasources return the raw URL and the datasource/index wrapper massages it.

**Comment by vivanov00** [comment]
Hi, @rarkins  I have added an url extractor/prettifies as per your request, also a simplified function for hostRules retrieval, for some reason the one used for search deletes a number of parameters, so for compatibility's sake I decided to write a new one.
