### ISSUE TITLE
Config errors due to new RegEx library

### ISSUE THREAD

**Issue by fgreinacher** [renovatebot/renovate#4655]
**What Renovate type are you using?**
Self-hosted

**Describe the bug**
The changes in #4441 lead to a lot of config errors in our (previously working) repos.

The log says:

```
INFO: Found renovate config errors (repository=foo/bar)
       "errors": [
         {
           "depName": "Configuration Error",
           "message": "Invalid regExp for packageRules[0].packagePatterns: `\\/foo\\/`"
         }
       ]
INFO: Repository has invalid config (repository=foo/bar)
      "error": {
        "configFile": "renovate.json",
        "validationError": "The renovate configuration file contains some invalid settings",
        "validationMessage": "Invalid regExp for packageRules[0].packagePatterns: `\\/foo\\/`"
      }
```

For a config that looks like this:

```
{
  "packageRules": [
    {
      "packagePatterns": ["\\/foo\\/"],
      "groupName": "Foo images",
      "automerge": true
    }
  ]
}
```

Is this an accidential regression or a conscious behavior change?

**Comment by rarkins** [comment]
Rolling this change back, stay tuned

**Comment by rarkins** [comment]
Reverted the commit that caused this, thanks for notifying. Will test more widely before it is applied again!

**Comment by fgreinacher** [comment]
Thanks! Seems like CI failed for the master commit (https://github.com/renovatebot/renovate/commit/f524557f21951e5df417a79ead9dbe6403b50368), blocking the release
