### ISSUE TITLE
Removes packages from package-lock.json

### ISSUE THREAD

**Issue by tjoskar** [renovatebot/renovate#4658]
**What Renovate type are you using?**
I'm using the hosted App on Github.

**Describe the bug**
I'm using Renovate in a few different projects (both private and public) but I have two mono repo projects with [lerna](https://github.com/lerna/lerna) where the renovate bot removes packages from `package-lock.json` for some reason. 

Take this PR for example: https://github.com/episodehunter/episodehunter/pull/51

It installs `@typescript-eslint/eslint-plugin` in one project but removes a lot of packages in all `packages-lock.json`. It looks like it removes all the packages that are located in the repo. For example: [@episodehunter/kingsguard](https://github.com/episodehunter/episodehunter/tree/master/packages/kingsguard) is removed in all `package-lock.json` files ([for example](https://github.com/episodehunter/episodehunter/pull/51/files#diff-c38d9c26894d3cc3be4a7fca22b16ea2L602)) but it is included in the package.json file ([for example](https://github.com/episodehunter/episodehunter/blob/aeb93ed5675804bdcac2fc467104c886c899088e/packages/scrobble/package.json#L47)). 

`npm ci` will then fail because the package-lock.json is not intact with the error:
```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
Missing: @episodehunter/logger@^4.1.5
```
https://github.com/episodehunter/episodehunter/pull/51/checks?check_run_id=259529608

**Did you see anything helpful in debug logs?**
No, not really. I found this lines (for this PR: https://github.com/episodehunter/episodehunter/pull/52):
```
INFO: Generated lockfile(branch="renovate/jest-24.x")
{
  "type": "lerna",
  "seconds": 230,
  "lernaClient": "npm",
  "stdout": "/home/ubuntu/.npm/lerna@3.17.0/bin/lerna -> /home/ubuntu/.npm/lerna@3.17.0/lib/node_modules/lerna/cli.js\n+ lerna@3.17.0\nupdated 1 package in 120.86s\nadded 697 packages in 4.233s\n",
  "stderr": "lerna notice cli v3.17.0\nlerna info versioning independent\nlerna info Bootstrapping 10 packages\nlerna info Installing external dependencies\nlerna info Symlinking packages and binaries\nlerna success Bootstrapped 10 packages\n"
}
```
https://app.renovatebot.com/dashboard#github/episodehunter/episodehunter/103641972

What is `type` lerna? Are you doning something special with lerna repos? Can I disabled that? And why do I get `stderr` here? It does not look like errors and it is a `INFO` line.

**To Reproduce**
I'm not sure how to reproduce it but you can find 3 PRs here: https://github.com/episodehunter/episodehunter/pulls that all has the same problem.

**Expected behavior**
I expect renovate to update packages, not remove packages that are still in `package.json` 🙂

**Additional context**
Config file: https://github.com/episodehunter/episodehunter/blob/master/.github/renovate.json

Thanks for an awesome service!

**Comment by rarkins** [comment]
We do call `npm` via `lerna` if the latter is found, and don't have any way to disable that approach.

Checking your logs, I see that we're using the default behaviour of calling `npm install --package-lock-only`. Unfortunately the `--package-lock-only` command has been known to generate incorrect lock file updates in certain complex scenarios, so this could be one of them. 

We have an admin option called `skipInstalls` that falls back to doing a full node_modules install. I have enabled it on your repository just now. If you can tick the "If you want to rebase/retry this PR, check this box" then I'd be interested to see if the replacement commit is correct or not.

**Comment by tjoskar** [comment]
Do you know how I can investigate this further?

**Comment by rarkins** [comment]
Renovate runs `lerna` and not `npm` directly. Here's from the last time it updated the lock files:

```
{"msg":"Spawning lerna with npm to create lock files"}
{"msg":"Using lerna version 3.17.0"}
{"cmd":"npm i -g -C ~/.npm/lerna@3.17.0 lerna@3.17.0 && npm install --ignore-scripts  --no-audit && ~/.npm/lerna@3.17.0/bin/lerna bootstrap --no-ci -- --ignore-scripts  --no-audit","msg":""}
{"msg":"npm stdout:\n/home/ubuntu/.npm/lerna@3.17.0/bin/lerna -> /home/ubuntu/.npm/lerna@3.17.0/lib/node_modules/lerna/cli.js\n+ lerna@3.17.0\nupdated 1 package in 53.937s\nadded 697 packages from 375 contributors in 35.524s\n"}
{"msg":"npm stderr:\ninfo cli using local version of lerna\nlerna notice cli v3.17.0\nlerna info versioning independent\nlerna info Bootstrapping 10 packages\nlerna info Installing external dependencies\nlerna info Symlinking packages and binaries\nlerna success Bootstrapped 10 packages\n"}
{"type":"lerna","seconds":448,"lernaClient":"npm","stdout":"/home/ubuntu/.npm/lerna@3.17.0/bin/lerna -> /home/ubuntu/.npm/lerna@3.17.0/lib/node_modules/lerna/cli.js\n+ lerna@3.17.0\nupdated 1 package in 53.937s\nadded 697 packages from 375 contributors in 35.524s\n","stderr":"info cli using local version of lerna\nlerna notice cli v3.17.0\nlerna info versioning independent\nlerna info Bootstrapping 10 packages\nlerna info Installing external dependencies\nlerna info Symlinking packages and binaries\nlerna success Bootstrapped 10 packages\n","msg":"Generated lockfile"}
```

You can see it's running this command: `npm i -g -C ~/.npm/lerna@3.17.0 lerna@3.17.0 && npm install --ignore-scripts  --no-audit && ~/.npm/lerna@3.17.0/bin/lerna bootstrap --no-ci -- --ignore-scripts  --no-audit`

You can then see these files are updated:
``
File is updated: /mnt/renovate/gh/episodehunter/episodehunter/packages/dragonstone/package-lock.json
File is updated: /mnt/renovate/gh/episodehunter/episodehunter/packages/image-proxy/package-lock.json
File is updated: /mnt/renovate/gh/episodehunter/episodehunter/packages/kingsguard/package-lock.json
File is updated: /mnt/renovate/gh/episodehunter/episodehunter/packages/scheduler/package-lock.json
File is updated: /mnt/renovate/gh/episodehunter/episodehunter/packages/scrobble/package-lock.json
File is updated: /mnt/renovate/gh/episodehunter/episodehunter/packages/show-update/package-lock.json
```

The best way for you to help trouble shoot this would be:
1. Install npm@6.12.0 globally
2. Clone your repo or check out master branch fresh
3. Make this change: 
![image](https://user-images.githubusercontent.com/6311784/66936337-cfb61a00-f03d-11e9-869e-d148e3816b83.png)
4. Run `npm i -g -C ~/.npm/lerna@3.17.0 lerna@3.17.0 && npm install --ignore-scripts  --no-audit && ~/.npm/lerna@3.17.0/bin/lerna bootstrap --no-ci -- --ignore-scripts  --no-audit` from the root of the repository.

In theory that should result in the same `git diff` as you are seeing in the PR, although it's not a perfect plan because you might have some local caches that Renovate does not. But it's worth trying as a first step.

**Comment by tjoskar** [comment]
Yeah, I'm getting the same `git diff` so apparently have I misunderstood how `lerna bootstrap` is working. The problem seems not to be in `renovate` (even though it would be nice to configure to not use lerna).  

Thanks for your time and thanks once again for a fantastic service!
