### ISSUE TITLE
Support releaseDate for github-tags datasource

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4660]
This will allow support for [stabilityDays](https://docs.renovatebot.com/configuration-options/#stabilitydays)

npm datasource can be referenced as an example datasource that returns release dates for each release.

**Comment by ViceIce** [comment]
Isn't this handled with #4689 ?

**Comment by HonkingGoose** [comment]
@rarkins Maybe we can close this issue?

`github-releases` has _releaseDate_ support according to https://github.com/renovatebot/renovate/issues/4689#issuecomment-670003139.

`github-tags` has a open issue at https://github.com/renovatebot/renovate/issues/7062 to add a _releaseTimestamp_, and a non-merged PR at https://github.com/renovatebot/renovate/pull/5760.

**Comment by viceice** [comment]
@HonkingGoose I think this is still missing, as the tag only gets a time stamp if it has a corresponding release

**Comment by HonkingGoose** [comment]
@viceice OK! I just wanted to check. 😄
