### ISSUE TITLE
Add releaseTimestamp to missing datasources

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4689]
Let's do a review of each datasource and confirm which is true:
- releaseTimestamp already supported
- releaseTimestamp could be supported immediately (just add/parse an extra field)
- releaseTimestamp could be supported but we need to change how we retrieve releases
- releaseTimestamp is not possible to support (the origin provides no information on the date/time of the release)

Then we decide which ones to update.

**Comment by nihal9ns** [comment]
@rarkins I'll take this up

**Comment by nihal9ns** [comment]
@rarkins 
List of Datasources :
```
cargo
dart
docker
git-tags
github
gitlab
go
gradle-version
helm
hex
maven
npm
nuget
orb
packagist
pypi
ruby-version
rubygems
sbt
terraform
```

List of Datasources that support `releaseTimestamp` already :
```
npm
packagist
pypi
ruby-version
rubygems
```


List of Datasources that could be supported immediately :

```
docker
github
gitlab
go 
gradle-version
helm
hex 
nuget
orb
terraform
```

List of Datasources that could not be supported (the origin provides no information on the date/time of the release) :

```
cargo
dart
```

List of datasources regarding which I am not sure whether their origin provides any such info or not : 
```
git-tags
maven
sbt
```

**Comment by rarkins** [comment]
@nihal9ns great! Can you start adding the timestamps to each? One per PR is for so it’s easy to review.

**Comment by nihal9ns** [comment]
@rarkins 👍

**Comment by zharinov** [comment]
Can't find timestamps for Terraform: https://registry.terraform.io/v1/modules/gruntwork-io/network/google/versions. Maybe, I need some another URL?

**Comment by rarkins** [comment]
Looks like you'd need to query each version one by one: https://www.terraform.io/docs/registry/api.html#sample-request-6

But such querying could be cached for a very long time, similar to how we did with maven datasource found/not found results although for much longer.

**Comment by rarkins** [comment]
@zharinov which are left? Can you create a checklist if any

**Comment by zharinov** [comment]
| Datasource | Done | Parse | Query | N/A | Comment |
| --- | :-: | :-: | :-: | :-: | --- |
| cdnjs |  |  |  | x | Can't see anything relevant in API documentation |
| clojure |  |  |  | x | Clojars dependencies don't respect "Last-Modified" header |
| crate |  |  |  | x | [crates.io index](https://github.com/rust-lang/crates.io-index/blob/master/li/bc/libc) doesn't contain timestamp info |
| dart | x |  |  |  |  |
| docker |  | ? |  |  | https://github.com/renovatebot/renovate/issues/5773 |
| galaxy | x |  |  |  |  |
| git-refs |  |  |  | x | Can be partially supported via GitHub and GitLab |
| git-submodules |  |  |  | x | Can be partially supported via GitHub and GitLab |
| git-tags |  |  |  | x | Can be partially supported via GitHub and GitLab |
| github-releases | x |  |  |  |  |
| github-tags |  |  | ? |  | https://github.com/renovatebot/renovate/pull/5760 |
| gitlab-tags | x |  |  |  |  |
| go | ? |  |  |  | See: github-tags |
| gradle-version | x |  |  |  |  |
| helm | x |  |  |  |  |
| hex | x |  |  |  |  |
| jenkins-plugins | x |  |  |  |  |
| maven |  | x |  |  | Maven Central maintains "Last-Modified" header which can be obtained from HEAD responses |
| npm | x |  |  |  |  |
| nuget |  |  |  |  |  |
| orb | x |  |  |  |  |
| packagist | x |  |  |  |  |
| pod |  |  |  | x |  |
| pypi | x |  |  |  |  |
| repology |  |  |  | x | Seems like it's available on per-repoName basis (e.g. from Debian or Arch linux sites) |
| ruby-version | x |  |  |  |  |
| rubygems | x |  |  |  |  |
| sbt-package |  | x |  |  | Can be partially supported for Maven Central artifacts |
| sbt-plugin |  |  | x |  | SBT plugin repo seems to be respecting "Last-Modified" headers |
| terraform-module |  |  | x |  | Query+cache for each version (see comments above) |
| terraform-provider |  |  | x |  | Query+cache for each version (see comments above) |

**Comment by zharinov** [comment]
What's left is on their own issues now
