### ISSUE TITLE
Node 10 required as of at least 19.64.1

### ISSUE THREAD

**Issue by obartra** [renovatebot/renovate#4696]
**What Renovate type are you using?**

npm package `renovate@19.64.1` and `renovate@19.64.2`

**Describe the bug**

Breaking change on latest version changing node requirements (to v.10 or above), seems related to an update to the `boolean` package from `roarr`. I've filed a ticket on roarr [here](https://github.com/gajus/roarr/issues/25)

**Did you see anything helpful in debug logs?**

```sh
$ ./node_modules/.bin/renovate
{path}/node_modules/roarr/node_modules/boolean/build/lib/boolean.js:5
        return /^(?<truthy>true|t|yes|y|on|1)$/iu.test(value.trim());
        ^

SyntaxError: Invalid regular expression: /^(?<truthy>true|t|yes|y|on|1)$/: Invalid group
    at boolean (/{path}/node_modules/roarr/node_modules/boolean/build/lib/boolean.js:5:9)
    at Object.<anonymous> (/{path}/node_modules/roarr/dist/log.js:24:38)
```
**To Reproduce**

- Switch to node 8
- run renovate from the CLI

**Additional context**

NA

**Comment by rarkins** [comment]
We deprecated support for Node 8 runtime in Renovate some time ago actually, so I will close this. FYI we plan to deprecate Node 10 soon too now that Node 12 is LTS.

**Comment by rarkins** [comment]
https://github.com/renovatebot/renovate/blob/a4ffc1df6188db05acedf7cb890da492fd2a6523/package.json#L94

**Comment by obartra** [comment]
Oh man you guys are living on the edge! Ok cool good to know, I'll just lock the dependency for then, thanks for the info!

**Comment by rarkins** [comment]
We only deprecate if we have a reason to. For Node 8 it was because we needed named regex groups. For Node 10 it’s because we need Node-gyp and only Node 12 supports python 3 for that
