### ISSUE TITLE
@sanity deps are not grouped

### ISSUE THREAD

**Issue by pvinis** [renovatebot/renovate#4713]
`react` and `gatsby` are grouped and updated as one, but `sanity` deps are not. See here https://github.com/pvinis/pvinis-db-sanity/pull/7 and https://github.com/pvinis/pvinis-db-sanity/pull/5 for example.

Is that something I can fix with a custom config, or is it something that renovate should detect?

**Comment by rarkins** [comment]
This is not something that Renovate can automatically assume (there are many cases where dependencies within the same scope have independent release cycles). You can propose a new grouping within the https://github.com/renovatebot/presets repository though, as this is where we add the groupings manually.
