### ISSUE TITLE
How to get release notes from CHANGELOG?

### ISSUE THREAD

**Issue by simoneb** [renovatebot/renovate#4724]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

We're publishing some packages which are used by our applications and as part of an improvement of the package publishing process we're now generating and including a CHANGELOG file in the package.
We thought that this would be enough to get the Release Notes section to show in the PRs created by Renovate but it turns out it's not the case. Checking other packages I realized that the release notes are probably coming from GitHub's releases page instead.

Is there a reason why the CHANGELOG file isn't used instead? I feel it would make more sense for release notes to come from a file within the package rather than the platform where the source code of the package is hosted.

**Comment by simoneb** [comment]
Thanks for looking into this @rarkins. 

From what I see in the code nested changelog files don't seem to be supported. I've set up renovate locally to see if I could contribute an improvement, but it looks like this would be an entirely new feature, and I'm not sure how to go about it. The function you linked to above probably needs to be modified quite a bit to account for nested packages, so it would have to have knowledge of monorepos and the specific package manager. 

I am easily missing something as I'm not familiar with the Renovate codebase, but a straightforward implementation would require to look into the specific package we're trying to bump, pull  itsread `package.json` file, figure out what is the path of the package in order to pick up the right CHANGELOG file. But surely there is more complexity than this to make sure that we're staying compliant with tech stacks other than Node.js.

**Comment by rarkins** [comment]
@simoneb I was hoping that there would be a variable `sourceDirectory` passed through to the changelog step that can then be used to directly look for the changelog. I'll try to debug your example to see if that's true

**Comment by rodoabad** [comment]
@simoneb are you using `git`, `git+https` or `https`? in your repository declaration in `package.json`?

**Comment by simoneb** [comment]
> @simoneb are you using `git`, `git+https` or `https`? in your repository declaration in `package.json`?

A mix of the various options across different repositories. Is there one option that is expected to work?

I could update the [repro](https://github.com/renovatebot/renovate/issues/4724#issuecomment-545357495) to include that and see if it works.

**Comment by sppatel** [comment]
If the change log is only in the published npm package will renovate discover this and use it for the release notes, or does it reach out to the source repository and extract it from there?  In my scenario, the CHANGELOG is not sourced, and only exists in each package distribution on the registry.

**Comment by rarkins** [comment]
Only the source repo. We don't download/extract artifacts from registries

**Comment by cawa-93** [comment]
Could you take a look at this PR:
https://github.com/cawa-93/vite-electron-builder/pull/192

I do not understand why the release notes are not loaded. I recently [added](https://github.com/vitejs/vite/commit/0ecff9417ee0ccfea9132fb9df39eb4398c11eaf) `repository.directory` to all  `packages/**/package.json` in this monorepo, but it didn't help (

**Comment by BeeeQueue** [comment]
Would it be possible to extract changelogs from the package files when updating? Packages that have them often include them when publishing

![image](https://user-images.githubusercontent.com/472500/117460174-152c8780-af01-11eb-8171-d5b2cc8e1479.png)

**Comment by jasikpark** [comment]
Could documentation be added about where renovatebot looks for changelogs in monorepos? We're trying to get detection working with https://github.com/snowpackjs/astro/ and I was hoping just specifying the source URL would fix things.

**Comment by rarkins** [comment]
Renovate should follow the convention described here for monorepos: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository

e.g.

```json
{
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/react.git",
    "directory": "packages/react-dom"
  }
}
```

If it's still not working, please create a simply reproduction repo  upgrading one of your monorepo packages (and failing to show the release notes) and we can take a look and fix things if necessary.

**Comment by jasikpark** [comment]
Sure thing! I did that, but it's still not working: https://github.com/jasikpark/my-astro-project/pull/7
```
  "repository": {
    "type": "git",
    "url": "https://github.com/snowpackjs/astro.git",
    "directory": "packages/astro"
  },
```
https://github.com/snowpackjs/astro/blob/e7b2a6d8dd163dbddf8d2bdf380e48b336c56a75/packages/astro/package.json#L8-L12

**Comment by rarkins** [comment]
FYI I have reproduced this problem using your project and have a fix in progress

**Comment by viceice** [comment]
Isn't this fixed ?
- #10501
