### ISSUE TITLE
Meta: Automatic formatting of Dockerfile

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4727]
I noticed that my and @ViceIce's IDEs are flip flopping on Dockerfile formatting, particularly indentations. If there is a way to enforce a single approach amongst collaborators, e.g. using eslint or prettier, then we should apply it to make it simpler for all.

**Comment by ViceIce** [comment]
🤔 I just copied the nodejs image code

Maybe they use another indentation?
