### ISSUE TITLE
Avoid "Action Required: Fix Renovate Configuration" during GitLab platform errors

### ISSUE THREAD

**Issue by monochromata** [renovatebot/renovate#4729]
**What Renovate type are you using?**

GitLab.com

**Describe the bug**

Similar to the [previously reported (and fixed) problem for GitHub](https://github.com/renovatebot/renovate/issues/4152) Renovate Bot creates issues like "Action Required: Fix Renovate Configuration" with body

> There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop MRs until it is resolved.
> 
> Error type: Cannot find preset's package (gitlab>monochromata-de/renovate-config-presets)

The bot closes them automatically soon after.

**Did you see anything helpful in debug logs?**

https://app.renovatebot.com/dashboard#gitlab/monochromata-de/de.monochromata.event/106738600 contains the following:

```
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "gitlab>monochromata-de/renovate-config-presets"
    ]
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "gitlab>monochromata-de/renovate-config-presets"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "gitlab>monochromata-de/renovate-config-presets"
    ]
  }
}
DEBUG: Failed to retrieve renovate.json from repo
{
  "err": {
    "message": "platform-failure",
    "stack": "Error: platform-failure\n    at get (/home/ubuntu/renovateapp/node_modules/renovate/dist/platform/gitlab/gl-got-wrapper.js:36:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
DEBUG: Preset fetch error
{
  "err": {
    "message": "dep not found",
    "stack": "Error: dep not found\n    at Object.getPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/gitlab/index.js:27:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
INFO: Throwing preset error
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (gitlab>monochromata-de/renovate-config-presets)"
  }
}
DEBUG: raiseConfigWarningIssue()
DEBUG: getBranchPr(renovate/configure)
DEBUG: ensureIssue()
WARN: Config Warning
{
  "configError": {
    "validationError": "Cannot find preset's package (gitlab>monochromata-de/renovate-config-presets)"
  },
  "res": "created"
}
INFO: Finished repository
```

**To Reproduce**

This happens on all of my repos at https://gitlab.com/monochromata-de/ that use Renovate Bot.

**Additional context**

Gitlab is unreliable obviously. I'm not sure how much of the fix for GitHub (https://github.com/renovatebot/renovate/issues/4152) is already present in the GitLab code, too.

**Comment by olegkrivtsov** [comment]
I'd like to help with this one.

**Comment by PhilipAbed** [comment]
@rarkins 
Hi, are you saying that the "Cannot Find Preset" is not a Config Error? but a network error?

i see in code that it is considered a `config_validation` error :
![image](https://user-images.githubusercontent.com/42116482/165740836-66327747-2f45-4e98-be7b-c0ddd6f9cead.png)

now if i change that i might ruin something, as if it was coded like this, then it might be a configuration error in some cases right?

So, lets say its not a config validation error, i should remove it as an Error from there so it will avoid opening a config validation 
Issue 

What is expected instead? how should the code react to such error?

**Comment by rarkins** [comment]
There are multiple reasons why a preset may not be found:
- It's the wrong name
- It was the right name but it's removed
- Permissions
- GitLab/GitHub down
- Network problem

Some are temporary, some permanent. We should continue raising the issue by default because of the risk of permanent ones being missed.

Regardless of whether we create a config warning issue, we should abort the run and log the warning.

**Comment by PhilipAbed** [comment]
so what should i do ? shouldnt this be part of https://github.com/renovatebot/renovate/pull/15296 ?
where we just add a flag to suppress issues in this case?
 
the issues are being autoclosed if they are temporary anyway no? as far as i know

so basically this issue can be closed if we finish the suppressNotifications config error flag??

**Comment by rarkins** [comment]
This seems like a subset of the other one. Someone might still want an issue if they have a typo in their config, but they don't want issues if a remote preset is temporarily unavailable.

**Comment by PhilipAbed** [comment]
Cool! so im here to cleanup and understand if this task needs closing or to work on it.. if what you say is true then its still a bug that we need to work on, 
we opened a task for it.

let me summarize this:

Renovate creates an ISSUE in case of failure in config validation. see `error-config.ts` where we `ensureIssue`.

then auto closes it in finaliseRepo

`await platform.ensureIssueClosing(`Action Required: Fix Renovate Configuration`);`

The reason for validations may Vary, see above.
But in this case we have Failed to reach Remote connection

we want to suppress ensuring the issue in `error-config.ts`


is that right?

**Comment by rarkins** [comment]
Yes, ideally there would be a way to determine if the config violation was thrown due to missing presets, and offer the option to suppress it (Even if we don't keep going). If it's not easy to make this elegant due to the way it's currently written/architected, we may want to pass on this.
