### ISSUE TITLE
Go Environment Vars and Go Version

### ISSUE THREAD

**Issue by wywfalcon** [renovatebot/renovate#4752]
**What Renovate type are you using?**

Using `renovate/renovate:19.65` Docker Image.

**Describe the bug**
Many dependencies are still not compatible with Go 1.13. While that is ideal, it is impractical at least for the use cases I face in my organization. Even when using `GOPROXY=direct` and `GOSUMDB=off` explicitly, `go get -d ./...` and `go mod tidy` result in the following errors.

**Did you see anything helpful in debug logs?**

`replace` directive issue:
```
go: github.com/apache/thrift@v0.12.0 used for two different module paths (git.apache.org/thrift.git and github.com/apache/thrift)
```

Version Tag issue:
```
......
	gopkg.in/mgutz/dat.v2/dat tested by
	gopkg.in/mgutz/dat.v2/dat.test imports
	gopkg.in/stretchr/testify.v1/assert: cannot find module providing package gopkg.in/stretchr/testify.v1/assert
```

**To Reproduce**

Run Renovate in any mode (Docker or CLI) for a repository that include `gopkg.in/stretchr/testify.v1` as a dependency. Added debug line in source code to show env var when running `go get -d ./...` and `go mod tidy` through `renovate.js`. It shows that `GOSUMDB `is not being passed to the child process.

**Additional context**

Maybe we can install two versions of Go and allow the user to specify which one to run? Or just use Go 1.12 because it works. See https://github.com/renovatebot/renovate/pull/4748

**Comment by rarkins** [comment]
Renovate *should* try to pick the right version of go to use now when running with binarySource=docker. However I'm not sure if we fall back to the old go 1.12 or fall forward to the latest. @wywfalcon are you still experiencing this problem?
