### ISSUE TITLE
Security Vulnerability Alerts for JavaScript on GitLab

### ISSUE THREAD

**Issue by ndbroadbent** [renovatebot/renovate#4761]
* [Original config-help issue](https://github.com/renovatebot/config-help/issues/405#issuecomment-548693830)
* [I opened the same issue for Ruby](https://github.com/renovatebot/renovate/issues/4763)

**What would you like Renovate to be able to do?**

I would like to get vulnerability alerts working with GitLab, so that Renovate Bot opens a Merge Request instead of silently merging in a passing branch.

**Describe the solution you'd like**

When using the `"automergeType": "branch"` strategy, updating from a vulnerable version to a fixed version should always open a Merge Request (to send an email notification). The title of the MR (and email subject) should indicate that this is a security update.

I think Renovate Bot could integrate with some security vulnerability APIs (e.g. the same ones used by `yarn audit`), and maintain a database of vulnerable package versions.

**Describe alternatives you've considered**

I believe that there are some other paid services that can handle vulnerability alerts, like Snyk, or moving the repo to GitHub.

Another solution is to set `automergeType="pr"`, but that has similar problems. Instead of getting no notifications, I might start to get too many notifications, so I will start archiving the notification emails without paying any attention.

**Additional context**

Before setting up Renovate Bot, I had a scheduled job in GitLab CI that would run all my tests, but would also run `yarn audit` and `bundle audit` to check for security vulnerabilities. Now that Renovate Bot is automatically (and usually silently) updating my dependencies, I can no longer rely on this behavior. (I also just found out about GitLab CI's [Dependency Scanning](https://docs.gitlab.com/ee/user/application_security/dependency_scanning/) feature, so I might try that as well.)

**Comment by chengjianhua** [comment]
Is there any new progress?

**Comment by philippe-granet** [comment]
Release https://github.com/renovatebot/renovate/releases/tag/34.129.0 add feature-flagged support for OSV (https://github.com/renovatebot/renovate/issues/20226) ([a91ca62](https://github.com/renovatebot/renovate/commit/a91ca62b466b57aa9a18f4e15bd04eb5552278b1)), working with GitLab.

https://docs.renovatebot.com/configuration-options/#osvvulnerabilityalerts
> Renovate integrates with [OSV](https://osv.dev/), an open-source vulnerability database, to check if extracted dependencies have known vulnerabilities.
> Set osvVulnerabilityAlerts to true to get pull requests with vulnerability fixes (once they are available).
