### ISSUE TITLE
Request: Add a way to disable rebasing for a specific GitLab MR

### ISSUE THREAD

**Issue by ndbroadbent** [renovatebot/renovate#4766]
Related to: https://github.com/renovatebot/renovate/issues/4184

**What would you like Renovate to be able to do?**

I would like to be able to disable the default rebasing behavior for a specific GitLab Merge Request. This is because some major version upgrades may take a lot of development time, so I want to leave them open, but I don't want to keep burning CI minutes just to re-run the failing tests.

Most of the time I want to rebase MRs automatically, but I want to explicit disable some of them while keeping them open.

**Describe the solution you'd like**

Maybe add another checkbox to the GitLab Merge Requests. Something like:

[ ] If you want to rebase/retry this MR, check this box
[ ] If you want to disable automatic rebasing for this MR, check this box

**Describe alternatives you've considered**

I could set `rebaseConflictedPrs: false`, and manually check the checkbox if I want to rebase any MRs. But I would rather preserve the default rebasing behavior, and manually disable a few MRs for some difficult upgrades.

**Comment by rarkins** [comment]
Why are they being rebased today? Only when there’s a conflict?

For now you could also add an empty commit on top of Renovate’s and that would disable automatic rebasing, but obviously it’s not convenient.

**Comment by ndbroadbent** [comment]
Hello, they are being rebased today because I set up Renovate Bot recently, so I am merging a large number of MRs to update dependencies, and this often causes merge conflicts in my `package.json` files. I guess these rebases will start to slow down once I get through most of the MRs and packages are being updated less frequently. 

Thanks for the idea, for now I think I will push an empty commit to each of the branches that I want to disable for now. (And my idea is for a new checkbox that provides exactly the same behavior as pushing an empty commit.)

**Comment by rarkins** [comment]
Also consider setting `masterIssueApproval` to `true` for major updates like we do here in the Renovate repo. Then the MRs are only opened on demand

**Comment by ndbroadbent** [comment]
Wow, that's awesome! I didn't see that "Master Issue" option before. (For anyone else who reads this: https://renovatebot.com/blog/master-issue)

I think this is exactly what I want:

```
{
  "major": { "masterIssueApproval": true }
}
```

So I can easily opt-in to any major version updates, but automatically apply updates for minor and patch versions. I think this will be a great setup.

Thanks for all of your work on Renovate Bot, it's a really amazing service!
