### ISSUE TITLE
Support custom version URLs that can be saved to a path

### ISSUE THREAD

**Issue by ndbroadbent** [renovatebot/renovate#4813]
**What would you like Renovate to be able to do?**

This is related to my comment about `apt` packages: https://github.com/renovatebot/renovate/issues/3722#issuecomment-554066042

I forgot to mention that I also have these lines in my CI Dockerfile:

```
# Install Google Chrome
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | \
  apt-key add - \
  && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> \
  /etc/apt/sources.list.d/google-chrome.list \
  && apt-get -y update \
  && apt-get -y install google-chrome-stable \
  && rm -rf /var/lib/apt/lists/* \
  && google-chrome --version

# Install Chrome WebDriver
# Get latest version: curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE
RUN CHROMEDRIVER_VERSION="78.0.3904.70" \
  && mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION \
  && curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip \
  && unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION \
  && rm /tmp/chromedriver_linux64.zip \
  && chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver \
  && ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver \
  && chromedriver --version
```

This is really tricky, because `chromedriver` and Google Chrome have to stay in sync (plus the `capybara` and `selenium-webdriver` gems that I use to run integration tests.)
So it would be amazing if RenovateBot could help me manage these versions.

**Describe the solution you'd like**

One solution might be to specify a HTTP endpoint, and a file path where the response should be saved in the repo. e.g. `renovate.json` could contain something like:

```
  "version_urls": [
    {
      "url": "https://chromedriver.storage.googleapis.com/LATEST_RELEASE",
      "path": ".chromedriver-version"
    }
  ],
```

Then RenovateBot would run `curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE`, and push a new branch whenever the `.chromedriver-version` needs to be updated.

I would then update my GitLab CI config to install the new chromedriver version whenever it changed, and I can also use the version from `.chromedriver-version` whenever I'm rebuilding the base image.

**Describe alternatives you've considered**

An alternative would be to add a new `chromedriver` option to the RenovateBot config, and handle the version updates as usual.

**Comment by ndbroadbent** [comment]
I was reading through some of the other issues, and I just found #4759 (Support new "file sync" manager), which is very similar to what I had in mind!

However, it would be really useful if RenovateBot could also parse the version from the downloaded file, so that I could specify different behaviors for major, minor, patch updates. Maybe the "file sync" manager could be extended with optional support for versions?

**Comment by JamieMagee** [comment]
If I'm reading this issue and #4814 right, you want Renovate to provide updates for arbitrary URLs. The only difference between this and #4814 is that this is for any URL, and #4814 is for GitHub specifically. Is that correct?

I've added some comments to #4759 about a possible approach we could take to achieve this. Please give it a read, and let me know what you think.

**Comment by ndbroadbent** [comment]
Hi @JamieMagee, yes that's right! I wasn't sure if I could get the latest release from GitHub from a similar URL, so I thought that might need some custom logic. But I was also thinking about suggesting a URL + regex to parse the first version from any webpage. jsonpath would also be great!

So maybe I will close these two issues, and we can keep the conversation in #4759

**Comment by JamieMagee** [comment]
I'm glad we're on the same page :smile: Yeah, let's focus our discussion there, and I'll wait to see what @rarkins comments—He's at GitHub Universe right now!
