### ISSUE TITLE
Remove poetry workaround from Docker image

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#4839]
The change in https://github.com/renovatebot/renovate/commit/dce1c7e4060ff45394b9e8d5adf6b520e99db111 should be removed once poetry `0.12.18` or `1.0.0` is released. Either of these should provide full support for Python 3.8.

Tracking https://github.com/sdispater/poetry/issues/1377#issuecomment-543369545

**Comment by ViceIce** [comment]
fixed in #4999
