### ISSUE TITLE
Support rangeStrategy=bump for pep440 versioning

### ISSUE THREAD

**Issue by itajaja** [renovatebot/renovate#4855]
**What Renovate type are you using?**

saas

**Describe the bug**

our current config:

```
{
  "extends": [
    "config:base",
    ":disablePeerDependencies",
    ":semanticCommitTypeAll(chore)",
    "group:allNonMajor",
    "schedule:daily"
  ],
  "rangeStrategy": "bump",
  "semanticCommits": true
}
```

dependencies in pyproject.toml were updated, but the poetry.lock file was not committed.

**Did you see anything helpful in debug logs?**

not sure if this is relevant, the only error I could see was:

```
DEBUG: Unsupported range type for rangeStrategy=bump: <2.0.0
WARN: getNewValue error
{
  "err": {
    "message": "Cannot read property 'split' of null",
    "stack": "TypeError: Cannot read property 'split' of null\n    at npm2poetry (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/poetry/index.js:25:10)\n    at Object.getNewValue (/home/ubuntu/renovateapp/node_modules/renovate/dist/versioning/poetry/index.js:70:23)\n    at lookupUpdates (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/lookup/index.js:125:43)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  },
  "currentValue": "<2.0.0",
  "rangeStrategy": "bump",
  "fromVersion": "0.0.1",
  "toVersion": "0.0.2"
}
```

I see a bunch of them.

also:

```
DEBUG: No updated lock files in branch(branch="renovate/all-minor-patch")
```

was the only line that came out searching for "lock".

not sure if it's related to  https://github.com/renovatebot/renovate/issues/4843, but we don't see the same error

**Comment by rarkins** [comment]
I don't think that rangeStrategy "bump" is supported for Python's pep440 versioning yet. Please remove that config or ensure it's applied to npm only, and then test again.

**Comment by itajaja** [comment]
yeah so I tested in another repo, same rangeStrategy, but no dependency with `<`, only `^`, specified in pyproject.toml. this time it worked. so it's specific to that range specifier, it seems.

what rangeStrategy should I use then?

**Comment by rarkins** [comment]
If you're building an app (i.e. your repo is not a library), then I recommend you use "pin" and let Renovate remove ranges from the `poetry.toml`. Renovate will then incrementally upgrade you whenever a new version is available.

**Comment by itajaja** [comment]
ok! up to you if you want to close this, seems like the error is specifically related to `<` ranges, which I am not sure is an actual bug, or expected, per your initial comment.
thanks!

**Comment by rarkins** [comment]
I think it "mostly" works kind of by accident so far. I'm fine to leave this open for us to track the `<` failure although I can't guarantee that's the only problem.

**Comment by itajaja** [comment]
I see. so far it seems to work, we'll switch to pin if it stops working. is there a parent issue to track the progress of supporting pep440 with different range strategies?

**Comment by rarkins** [comment]
I've created this as a documentation issue: https://github.com/renovatebot/renovate/issues/4858

**Comment by Gabriel-Ladzaretti** [comment]
[Bump strategy support for pep440](https://docs.renovatebot.com/modules/versioning/#pep440-versioning) was added recently, demonstration can be seen in this example [PR ](https://github.com/ladzaretti/issue-4855/pull/2) (including lockfile maintenance).


Ran with the following configuration:

renovate.json
```
{
	"extends": [
		"config:base"
	],
	"rangeStrategy": "bump",
	"semanticCommits": true,
	"lockFileMaintenance": {
		"enabled": true
	}
}
```

pyproject.toml containing:
```
[tool.poetry.dependencies]
python = "^3.10"
numpy = "<1.22.0"
```
