### ISSUE TITLE
Enable vulnerability alerts on GitHub Enterprise Server

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/renovate#4905]
As of GitHub Enterprise Server (GHE) 2.17 vulnerability alerts are now supported. Currently we explicitly disable them [here](https://github.com/renovatebot/renovate/blob/master/lib/platform/github/index.ts#L1784-L1789).

It should be fairly safe to remove this check, as 2.17 is the oldest supported version of GHE, so any older version is unsupported anyway.

**Comment by rarkins** [comment]
@JamieMagee where did you pull the official support status of GHE from?

**Comment by JamieMagee** [comment]
I was basing it on the help pages not having content for versions prior to 2.17, however looking at the [releases page](https://enterprise.github.com/releases) it looks like 2.16.x is still active.

**Comment by rarkins** [comment]
FWIW I wasn't able to locate any publicly available statement on supported versions

**Comment by JamieMagee** [comment]
From [the documentation for GHE 2.16](https://help.github.com/en/enterprise/2.16/user)

> This version of GitHub Enterprise will be discontinued on January 22, 2020

So it looks like we can make these changes from January 23rd onward.
