### ISSUE TITLE
Renovate only updates one configuration of a repeated dependency in Gradle

### ISSUE THREAD

**Issue by gjoseph** [renovatebot/renovate#4910]
**What Renovate type are you using?**

Self-hosted

**Describe the bug**

One of my gradle builds looks like this:
```
        implementation platform("org.immutables:value:2.8.1")
        annotationProcessor platform("org.immutables:value:2.8.1")
        testAnnotationProcessor platform("org.immutables:value:2.8.1")
```
This is a bit silly, but Gradle sorta forces me to do this (I could use a property to set the version, but I'd rather avoid using properties if possible)

Renovate creates a PR for this, but only changes the _first_ of these 3 dependency declarations. The resulting PR looks like this:
```
-        implementation platform("org.immutables:value:2.8.1")
+        implementation platform("org.immutables:value:2.8.2")
         annotationProcessor platform("org.immutables:value:2.8.1")
         testAnnotationProcessor platform("org.immutables:value:2.8.1")
```

**Did you see anything helpful in debug logs?**

Nothing in logs that I could see - if I manage to run locally, i'll turn debug on (we currently run renovate over a lot of repos, so debug logs would be ... noisy)

**To Reproduce**

Add the above to any gradle build in the dependencies sections

**Additional context**

**Comment by rarkins** [comment]
@gjoseph can you create a simple repository on github.com to reproduce this? i.e. something that a developer can first reproduce against and then fix against

Cc @ikesyo

**Comment by gjoseph** [comment]
@rarkins @ikesyo here you go: https://github.com/gjoseph/renovate-bugs-gradle

**Comment by gjoseph** [comment]
Just confirming that particular repo demonstrates the issue:
<img width="764" alt="Screen Shot 2019-12-12 at 17 51 12" src="https://user-images.githubusercontent.com/74627/70689311-09d32d80-1d08-11ea-91f6-9303a97ebc25.png">

**Comment by rarkins** [comment]
Thanks, we’ll fork and then try to see how complicated the fix is

**Comment by gjoseph** [comment]
I (think I) just gave you direct access to the repo if you'd like

**Comment by rarkins** [comment]
Now forked to https://github.com/renovate-reproductions/4910 but needs testing against the new JS-based Gradle manager we have

**Comment by PhilipAbed** [comment]
I've tried to reproduce this but got:
```
DEBUG: Wrong offset (repository=StinkyLord/4910, branch=renovate/org.immutables-value-2.x)
       "depName": "org.immutables:value",
       "currentValue": "2.8.1",
       "newValue": "2.9.0"
DEBUG: **Error updating file** (repository=StinkyLord/4910, branch=renovate/org.immutables-value-2.x)
       "existingContent": "plugins {\n    id \"java\"\n}\n\ndependencies {\n    implementation platform(\"org.immutables:value:2.8.1\")\n    annotationProcessor platform(\"org.immutables:value:2.8.1\")\n    testAnnotationProcessor p
latform(\"org.immutables:value:2.8.1\")\n}\n",
```

for some reason it errors out to update the file, The descriptions says it uploads wrongly.. on my machine its failing to start the change and the PR ,
should i open another issue for my case on this repository?

**Comment by PhilipAbed** [comment]
issue is not reproducible , its already fixed i think please check it out https://github.com/StinkyLord/4910/pull/3/files

![image](https://user-images.githubusercontent.com/42116482/158411819-8f34a290-183b-404c-a457-7eb982aa932a.png)

**Comment by Churro** [comment]
Just confirmed, this is resolved: https://github.com/renovate-demo/4910/pull/2
