### ISSUE TITLE
Specify labels for Dependency Dashboard

### ISSUE THREAD

**Issue by rpadovani** [renovatebot/renovate#4911]
**What would you like Renovate to be able to do?**
As for merge requests, I'd like to be able to specify the labels to attach to the master issue

**Describe the solution you'd like**
A new option, working as `labels`, for specifying master issue labels

**Describe alternatives you've considered**
Using the same labels for master issues as well. However, I think more flexibility is better :-)

**Additional context**
I am willing to work on this, if the feature is approved

**Comment by rarkins** [comment]
This is my idea right now, feedback welcome:

1. Change the existing `masterIssue` from a boolean into an object in its definition

2. [Massage](https://github.com/renovatebot/renovate/blob/master/lib/config/massage.ts) existing config like so: `"masterIssue": true` -> `"masterIssue": { "enabled": true }`

3. Add support for `labels` field inside this object

I don't think that we need to "merge" the object, we can just add logic like: `if (config.masterIssue && is.nonEmptyArray(config.masterIssue.labels)`

**Comment by rarkins** [comment]
@rpadovani if you think this sounds like what you want and would like to work on it, let me know and I'll assign this issue to you.

**Comment by rpadovani** [comment]
> @rpadovani if you think this sounds like what you want and would like to work on it, let me know and I'll assign this issue to you.

Works for me, let's do it :-)

**Comment by HonkingGoose** [comment]
@rpadovani I see that you were assigned to this issue. I also see that you made a initial PR, that did not get merged.

Are you able/willing to work on this in the near future? If not, that's fine as well, but please say so. That way we can remove your assignment so that somebody else can try making the feature.

**Comment by rpadovani** [comment]
Hi @HonkingGoose,
sorry, I totally forgot about this one. Please remove the assignment to myself, I'm not planning working on this any time soon.

**Comment by rarkins** [comment]
Implemented with new option `dependencyDashboardLabels`

**Comment by HonkingGoose** [comment]
I think we can close this issue then?

Quote for the new feature from our docs: [^docs]

> ## dependencyDashboardLabels
>
> These labels will always be applied on the Dependency Dashboard issue, even when they have been removed manually.
>
> Name | Value
> -- | --
> type | array
> subType | string
>
> The labels only get updated when the Dependency Dashboard issue updates its content and/or title. It is pointless to edit the labels, as Renovate bot restores the labels on each run.

[^docs]: https://docs.renovatebot.com/configuration-options/#dependencydashboardlabels
