### ISSUE TITLE
Custom Composer Repositories are looked up on Packagist

### ISSUE THREAD

**Issue by nadar** [renovatebot/renovate#4924]
**What Renovate type are you using?**

docker latest (renovate/renovate:latest)

**Describe the bug**

When using PHP private(custom) composer repositories, the renovate bot trys to to load the data from packagist.org, which results in a 404

**Did you see anything helpful in debug logs?**

It is looking up the url on packagist, which won't work:

```
INFO: Dependency lookup failure: not found (repository=myrepo, dependency=THE_PRIVATE_GITLAB_REPO)
DEBUG: Response code 404 (Not Found) (repository=myrepo)
       "err": {
         "name": "HTTPError",
         "host": "packagist.org",
         "hostname": "packagist.org",
         "method": "GET",
         "path": "/p/THE_PRIVATE_GITLAB_REPO.json",
         "protocol": "https:",
         "url": "https://packagist.org/p/THE_PRIVATE_GITLAB_REPO.json",
         "gotOptions": {
           "path": "/p/THE_PRIVATE_GITLAB_REPO.json",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "packagist.org",
           "port": null,
           "hostname": "packagist.org",
           "hash": null,
           "search": null,
           "query": null,
           "pathname": "/p/THE_PRIVATE_GITLAB_REPO.json",
           "href": "https://packagist.org/p/THE_PRIVATE_GITLAB_REPO.json",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "nginx",
           "date": "Wed, 04 Dec 2019 09:46:55 GMT",
           "content-type": "text/html; charset=UTF-8",
           "content-length": "146",
           "connection": "close"
         },
         "body": "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n",
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/usr/src/app/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
```
**To Reproduce**

I use the following composer.json values:

```json
"repositories": [
        {
            "type": "vcs",
            "url":  "https://USER:TOKEN@gitlab.com/PATH_TO_REPO.git"
        },
```
and in the require section:

```php
"NAME_OF_MY_PRIVATE_REPO" : "^1.0",
```

I was searching in the issues and saw comments about type "gitlab" so i also tryed `"type":"gitlab"` which does not work as well. I also tried to use type `git`, which won't work as well.

https://github.com/renovatebot/renovate/issues/3811#issuecomment-498668896

Is there something i can configure on the server or client. Or change how the private repositories are configured? If there is a solution i would also send a PR to the guide, so others won't have the same problem.

**Comment by rarkins** [comment]
If you're able to help debug it, I can help guide as to what needs to be done code-wise.

First of all we need to make sure that we're extracting enough information in this step: https://github.com/renovatebot/renovate/blob/master/lib/manager/composer/extract.ts

If you add a debugger line on that file and check what result it's producing, then we can determine if we have extracted enough information from your `composer.json`, or if we're missing something.

Then the next step will be to see how we're handling it in the packagist "datasource" and if we need to improve the logic there.

**Comment by nadar** [comment]
In the docker images there is no editor to edit the files and sudo is not possible to run apt-get commands. So i have to fix that first  :smile:

**Comment by rarkins** [comment]
If you can reproduce in a public repo then I can look. I use Chrome debugger with the raw source code.

**Comment by nadar** [comment]
i started to read and "debug" the code with my config:

https://github.com/renovatebot/renovate/blob/master/lib/manager/composer/extract.ts#L50
Here you defined that when type is git, processing with package name should proceed.

While with `composer`: 

https://github.com/renovatebot/renovate/blob/master/lib/manager/composer/extract.ts#L52-L53
the repo url should be taken to lookup and resolve the composer.json, which is correct for package repositories. This expects a packages.json (https://packagist.org/packages.json or another popular one https://asset-packagist.org/packages.json).

So what i can say "now" is that repositories contains an undefined name which won't find the repo url:

https://github.com/renovatebot/renovate/blob/master/lib/manager/composer/extract.ts#L131 console.log on repositories.

```
{
  undefined: {
    type: 'git',
    url: 'https://____MY_PRIVATE_REPO_URL'
  }
}
```

So my problem might start here:

https://github.com/renovatebot/renovate/blob/master/lib/manager/composer/extract.ts#L44


Does that help?

**Comment by nadar** [comment]
So i tested with `name`, then it works, but its not "valid" based on composer.json documentation:

```json
{
    "require": {
        "myvendor/mypackage" : "^1."
    },
    "repositories": [
        {
           "name" :  "myvendor/mypackage",
            "type": "git",
            "url":  "https://whatver:ever@gitlab.com/my_repo.git"
        }
    ]
}
```

So this "name" identifier which should match the repo works as expected! Composer won't throw an error when this additional key is defined. So it works.

I guess composer itself does that different. They resolve the repositories, which then contain the name. So if you would resolve the private git url the name would be available.

**Comment by rarkins** [comment]
I guess from a Renovate point of view we'd be hoping to already know the package name -> VCS mapping, but Composer's approach is that you resolve the VCS to find out the name.

In general I prefer not to make people change the way they use package managers to work around Renovate limitations, so we should think about how we could achieve this without requiring the addition of "name" to VCS repositories.

**Comment by nadar** [comment]
Then the solution would be:

1. If type is `git` or `vcs`
2. Get content of the provided `url` (which is by defintion followed by `composer.json` file). url + 'composer.json'
3. Get content of the composer.json's `name` property, which is required by defintion.
4. Set the name for the given git url.

then, as far as i can see, this would work out of the box as expected.

**Comment by rarkins** [comment]
If the VCS is type git but url type http/https, is there any way we can get the `composer.json` file with a single request? i.e. assume we don't know if it's github or gitlab or something completely different. We ideally want just the single file without a full git shallow clone.

**Comment by nadar** [comment]
I would say if: type is `vcs` or `git` and protocol is `http`/`https` you can CURL the content of composer.json, it does not mater whether it's github or gitlab as the http url is either public or contains the credentials.

**Comment by rarkins** [comment]
I’ve found it’s normally more collocates than that. Eg for GitHub you need to have a `tree/master` as part of the URL. I guess though we’ll need more than just the composer.json eventually though. Eg perhaps a list of tags too?

**Comment by nadar** [comment]
Well than we need to clone the repo url, read the composer.json and remove the git repo again. This is maybe even better as it will also work for ssh connected repositories?

**Comment by phumberdroz** [comment]
What is missing to see some progress on this?

**Comment by nadar** [comment]
@phumberdroz You can improve the definition inside your composer.json for the given packages and it works as expected. Yes its a annoying to do so, but it seems to be the only solution. 

See this example:

```php
{
    "require": {
        "myvendor/mypackage" : "^1."
    },
    "repositories": [
        {
           "name" :  "myvendor/mypackage",
            "type": "git",
            "url":  "https://whatver:ever@gitlab.com/my_repo.git"
        }
    ]
}
```
