### ISSUE TITLE
Avoid dots in branch names

### ISSUE THREAD

**Issue by alclonky** [renovatebot/renovate#4951]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.
pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### What is your question?

How to avoid dots in Branch Name? Gitlab has limited support for the protected branch configuration, so we have to avoid using dots in normal branch names. Or proteced branch pattern is *.*.* 

I found the branchTopic option, but whould need to replace the dots in depNameSanitized too?
Is this currently possible?

**Comment by alclonky** [comment]
is there a possibility to replace the dots using the handlebars template? Both ways should work for us

Thx

**Comment by rarkins** [comment]
Handlebars doesn't support replacing natively but in theory it might be possible to add a helper for it. Still needs development though.

**Comment by rarkins** [comment]
Here's an example: https://github.com/sparkartgroup/handlebars-helper/blob/master/lib/helpers/replace.js (but it's replace, not replace all)

**Comment by tarioch** [comment]
Is there any workaround for this? Our corp policy doesn't allow any . in the branch names, therefore a lot of prs don't get created :(

**Comment by rarkins** [comment]
Here's a workaround that seems to work: https://github.com/renovate-reproductions/no-dots/blob/bcd17df9e6bcf021336fac719a4a0894322613f4/renovate.json#L2

**Comment by tarioch** [comment]
Hmm, I'm getting

```
 INFO: Repository has invalid config (repository=......)
       "error": {
         "validationSource": "renovate.json",
         "validationError": "The renovate configuration file contains some invalid settings",
         "validationMessage": "Invalid template in config path: branchName",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at mergeRenovateConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/merge.ts:183:19)\n    at getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:16:12)\n    at initRepo (/usr/src/app/node_modules/renovate/lib/workers/repository/init/index.ts:31:12)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:44:14)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:122:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
       }
```


Version: 30.2.0

config looks like this:

```
....
  "branchName": "{{{branchPrefix}}}{{{additionalBranchPrefix}}}{{{replace '\\.' '-' branchTopic}}}",
...
```

**Comment by rarkins** [comment]
Sorry, you need 30.2.1 to avoid that validation error

**Comment by tarioch** [comment]
Just upgraded to 30.2.1, but still doesn't seem to work, produces branch like this:

```
feature/RENOVATE_org.projectlombok-lombok-1-x
```

if this makes any difference, I'm using bitbucket server

**Comment by rarkins** [comment]
If you can reproduce it in a public github repo, then I can take a look. Note thought that the app is not yet upgraded

**Comment by tarioch** [comment]
I think this is tied to maven artifacts. If you look at the example

```
feature/RENOVATE_org.projectlombok-lombok-1-x

<groupId>org.projectlombok</groupId>
<artifactId>lombok</artifactId>
<version>1.18</version>

```

It seems to do the correct thing for the last part lombok-1-x but not for the groupId.

**Comment by tarioch** [comment]
Hmm,

I now tried

```
"branchName": "{{{branchPrefix}}}{{{replace '\\.' '-' additionalBranchPrefix}}}{{{replace '\\.' '-' branchTopic}}}",
```

but it still doesn't work, will now try to replace also in branchPrefix, just to be sure

**Comment by rarkins** [comment]
It might be because the branchTopic contains a nested template which is not replaced

**Comment by tarioch** [comment]
I had also tried with

```
"branchTopic": "{{{replace '\\.' '-' depNameSanitized}}}-{{{newMajor}}}{{#if separateMinorPatch}}{{#if isPatch}}.{{{newMinor}}}{{/if}}{{/if}}.x{{#if isLockfileUpdate}}-lockfile{{/if}}"
```

which didn't help either

**Comment by tarioch** [comment]
I created https://github.com/renovate-reproductions/no-dots/pull/4 which hopefully would reproduce the issue in your repo.

**Comment by tarioch** [comment]
Compared how it looks with and without the workaround, there is at least some effect

Without
```
feature/RENOVATE_org.projectlombok-lombok-1.x
```

With
```
feature/RENOVATE_org.projectlombok-lombok-1-x
```

**Comment by tarioch** [comment]
Is the issue that replace only replaces the last dot instead of all of them? That could be another explanation.

**Comment by viceice** [comment]
`"branchTopic": "{{{replace '\\.' '-' depNameSanitized}}}-{{{newMajor}}}{{#if separateMinorPatch}}{{#if isPatch}}.{{{newMinor}}}{{/if}}{{/if}}.x{{#if isLockfileUpdate}}-lockfile{{/if}}"` has explicit dots and you only replace them in `depNameSanitized`.

We use `g` flag for replace, so all dots should be replaced.
https://github.com/renovatebot/renovate/blob/a86eceb7d4f8650b2b62c4d8450e0c68a3e4af8c/lib/util/template/index.ts#L13-L18

**Comment by rarkins** [comment]
BranchTopic gets overridden in a few configs option objects though

**Comment by viceice** [comment]
So he needs to use `branchName`?

**Comment by rarkins** [comment]
I'm not sure it will fully work as is. The dot is coming from an implicit group name

**Comment by tarioch** [comment]
is there any way to do the replacement on that implicit group?

**Comment by viceice** [comment]
I think you can manually override the group slug

**Comment by tarioch** [comment]
Yes, but can I change the pattern? I don't want to change all groups manually. So it should stay the group from pom but just replace . With -

**Comment by viceice** [comment]
Currently not possible. Sorry

**Comment by mikaello** [comment]
Seems like the option [`branchNameStrict`](https://docs.renovatebot.com/configuration-options/#branchnamestrict) has been added (https://github.com/renovatebot/renovate/pull/17216) since this issue was created, which would solve the issue by replacing all special characters (including `.`) with `-`.

So I guess this issue can be closed?
