### ISSUE TITLE
Follow yarn.lock symlinks

### ISSUE THREAD

**Issue by esetnik** [renovatebot/renovate#4955]
**What would you like Renovate to be able to do?**
Renovate should ignore or follow symlinks when processing yarn.lock files in monorepo subdirectories.

The problem I'm having is I have a repo like this:
root
  - yarn.lock
  - package.json
  - package-a
    - yarn.lock -> ../yarn.lock
    - package.json

Renovate fails with a `lockfile-error` like the following:
```
DEBUG: Spawning yarn install to create /mnt/renovate/gl/xx/mono/yarn.lock(branch="renovate/koa-router-8.x")
DEBUG: Using yarn: node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js(branch="renovate/koa-router-8.x")
INFO: lock file error(branch="renovate/koa-router-8.x")
{
  "cmd": "node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js",
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879",
    "stdout": "yarn install v1.19.2\ninfo If you think this is a bug, please open a bug report with the information provided in \"/mnt/renovate/gl/xx/mono/yarn-error.log\".\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n",
    "stderr": "error An unexpected error occurred: \"Cannot use 'in' operator to search for 'husky' in ../yarn.lock\".\n",
    "message": "Command failed: node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\nerror An unexpected error occurred: \"Cannot use 'in' operator to search for 'husky' in ../yarn.lock\".\n",
    "stack": "Error: Command failed: node /home/ubuntu/renovateapp/node_modules/yarn/bin/yarn.js install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879\nerror An unexpected error occurred: \"Cannot use 'in' operator to search for 'husky' in ../yarn.lock\".\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  },
  "type": "yarn"
}
```

**Describe the solution you'd like**
It appears that renovate is searching the symlink itself for the string "husky", but instead ideally it would follow the symlink and search that file instead.

**Describe alternatives you've considered**
Unfortunately due to the way netlify works with monorepos it's required to symlink yarn.lock into each subdirectory. The only other solution would be to use something like lerna which has it's own set of challenges.

**Additional context**

**Comment by rarkins** [comment]
Technically this is `yarn` itself generating the error instead of anything Renovate is doing directly. Can you reproduce this problem in a simplified public repo that can be tested against?

**Comment by esetnik** [comment]
I see that it is a yarn error but this only happens when renovate runs yarn install. When I run locally I don't get any such error. I will create a public repo to reproduce.

**Comment by rarkins** [comment]
btw I'm confused as to how it's meant to work though. If you run `yarn` in `package-a` then wouldn't it remove all dependencies in `yarn.lock` that are not in `package-a/yarn.lock`?

**Comment by esetnik** [comment]
> btw I'm confused as to how it's meant to work though. If you run `yarn` in `package-a` then wouldn't it remove all dependencies in `yarn.lock` that are not in `package-a/yarn.lock`?

SInce the `yarn.lock` is symlinked into `package-a` then running `yarn` in `package-a` will install all package versions using the monorepos locked package versions. The thing is that due to yarn workspaces the symlink isn't actually necessary but it is for netlify to correctly identify that it needs to run `yarn install`.

https://community.netlify.com/t/difficulty-with-new-monorepo-deployment-options/4381/3
https://community.netlify.com/t/build-monorepo-project-on-netlify/3975/7
https://github.com/netlify/build-image/issues/196

The suggested comment https://github.com/netlify/build-image/issues/196#issuecomment-562328172 re. creating an empty `yarn.lock` works fine on the netlify side but causes renovate to fail. I tried symlinking but it it doesn't work either, which is why I opened this issue.

**Comment by rarkins** [comment]
But just so you know, yarn will update that lock file so it still probably isn’t a good idea for you

**Comment by rarkins** [comment]
Both these approaches sound like invalid approaches to working around a Netlify limitation though. Maybe you could try Yarn Workspaces as an easier solution than Lerna

**Comment by esetnik** [comment]
Unfortunately this is using yarn workspaces and not lerna. I haven't tried switching the whole project to lerna but i'm confident I'd face similar issues as it uses yarn workspaces under the hood. I agree it's not an ideal approach. I will try to find a different solution on the Netlify side. Thanks for your help.

**Comment by rarkins** [comment]
Yes you’re right, I made a mistake with that idea. Another idea if no other is possible: use the empty lock file approach again but submit a patch to Renovate so that it treats an empty lock file as if no file exists at all

**Comment by HonkingGoose** [comment]
@rarkins What is the status of this issue right now? It has not seen any movement since December 2019. Do we still want this issue around, or do we need to do some more thinking, or something else?

**Comment by rarkins** [comment]
I think we need a reproduction for sure if we are to get any further.

**Comment by esetnik** [comment]
I think this can be closed. I'm not using yarn workspaces anymore so I don't experience the issue. And nobody else has reported similar problems so it's probably not worth worrying about.
