### ISSUE TITLE
Updating nodenv version when updating node version

### ISSUE THREAD

**Issue by vschoener** [renovatebot/renovate#4959]
**What would you like Renovate to be able to do?**
Actually renovate is able to update the node version from docker file and `.nvmrc`, that would be nice if you can handle the `.node-version` file as well 👍

https://github.com/nodenv/nodenv

**Describe the solution you'd like**
Updating the `.node-version` file when present

**Describe alternatives you've considered**
Doing by hands but not really productive :)

**Comment by rarkins** [comment]
As a workaround it should be possible to add a custom rule using our new regex-based manager: https://docs.renovatebot.com/modules/manager/regex/

**Comment by vschoener** [comment]
Pretty nice too, I'll give it a try

**Comment by ViralRuparel** [comment]
assign this to me @rarkins
