### ISSUE TITLE
Override schedule of lock file maintenance by vulnerability alert for transient dependency

### ISSUE THREAD

**Issue by henrist** [renovatebot/renovate#4961]
**What would you like Renovate to be able to do?**
If a vulnerability alert is given for `package-lock.json` for a transient dependency, that will be resolved by updating the lock file, the schedule of lock file maintenance should be overriden.

**Describe the solution you'd like**
I think the hard part here is that we do not know if the vulnerability alert will be fixed by updating the lock file before after we have tried to do the update, so not sure if this can be solved in any easy way.

**Describe alternatives you've considered**
None.

**Additional context**
Job ID that shows this issue: 120040335

This is partly related to #3080, but the difference is that this is solveable by only recreating the lock file, not by updating an explicit dependency.

**Comment by rarkins** [comment]
Right now this will only work if it is a direct dependency in a lock file, and not for transitive dependencies. We haven't yet implemented logic that works out if a transitive vulnerable dependency can be fixed just be recreating the lock file.

**Comment by henrist** [comment]
Yes, this is covering transient dependencies. I've updated the title and text to reflect this.
