### ISSUE TITLE
gradle: stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by alclonky** [renovatebot/renovate#4971]
**What Renovate type are you using?**
pro

**Describe the bug**

Gradle project with warnings produces stdout maxBuffer length exceeded error

**Did you see anything helpful in debug logs?**

`Welcome to Gradle 5.6.2!\n\nHere are the highlights of this release:\n - Incremental Groovy compilation\n - Groovy compile avoidance\n - Test fixtures for Java projects\n - Manage plugin versions via settings script\n\nFor more details see https://docs.gradle.org/5.6.2/release-notes.html\n\nStarting a Gradle Daemon (subsequent builds will be faster)\n\n> Configure project :androidTestSupport\nWARNING: The option setting 'android.jetifier.blacklist=guava' is experimental and unsupported.\n\nWARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..\n\n> Configure project :cmis\nWARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..\n\n> Configure project :cmisLibrary\nWARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..\n\n> Configure project :faba5Utils\nWARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..\n\n> Configure project :testLibrary\nWARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..\n\n> Configure project :worklist\nWARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..\n\n> Configure project :worklistLibrary\nWARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish' does not specify a custom pom path.\nCannot publish pom for project ':cmis' since it does not contain the Maven plugin install task and task ':cmis:artifactoryPublish
...
         "stderr": "",
         "message": "stdout maxBuffer length exceeded",
         "stack": "RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded\n    at Socket.onChildStdout (child_process.js:354:14)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:265:13)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)"
       }
 INFO: Aborting Renovate due to Gradle lookup errors (repository=)
 INFO: Registry error - skipping (repository=)

`

**Comment by rarkins** [comment]
We might be able to work around this by passing `maxBuffer` to the child process. Something like 10MB should hopefully be enough, e.g. `10 * 1024 * 1024`.

**Comment by alclonky** [comment]
Tried a quick patch in https://github.com/renovatebot/renovate/blob/5c62cdafc60dc9fea3a50734c128d648a7e3187d/lib/manager/gradle/index.ts#L75 with 10 * 1024 * 1024 which seems to help for my case.

**Comment by rarkins** [comment]
Waiting on #2863
