### ISSUE TITLE
Branch automerges too early on Bitbucket when using unpublishSafe

### ISSUE THREAD

**Issue by ext** [renovatebot/renovate#4973]
**What Renovate type are you using?**

Self-hosted

**Describe the bug**

I have the same issue as #4622 (except I run on Bitbucket Server instead of Cloud). The fix from that issue partially works (i.e. 0 statuses -> pending).

However, when using `unpublishSafe` the status count contains one successful status thus triggering the bug anyway:

>         {
>            "dateAdded": 1575995659773,
>            "description": "Packages cannot be unpublished",
>            "key": "renovate/unpublish-safe",
>            "name": null,
>            "state": "SUCCESSFUL",
>            "url": "https://renovatebot.com"
>        }

**Did you see anything helpful in debug logs?**

With `unpublishSafe`:

> {"commitStatus":{"successful":1,"inProgress":0,"failed":0},"msg":"branch status check result"}
> {"msg":"Automerging branch"}

Without `unpublishSafe`:

> {"commitStatus":{"successful":0,"inProgress":0,"failed":0},"msg":"branch status check result"}
> {"branchStatus":"pending","branchName":"renovate/html-validate-2.x","msg":"getBranchStatus() result"}
> {"msg":"Branch is configured for branch automerge, branch status) is: pending"}

**To Reproduce**

Bitbucket Server, configure renovate, enable `unpublishSafe`.

**Additional context**

Not sure if it is the best solution but maybe test for 1 build instead of 0 when `unpublishSafe` is enabled?

**Comment by rarkins** [comment]
What is your full config?

**Comment by ext** [comment]
```js
{
  extends: ["config:js-lib"],
  rebaseStalePrs: true,
  prHourlyLimit: 2,
  prCommitsPerRunLimit: 2,
  semanticCommits: false,
  commitMessagePrefix: "Chore:",
  commitMessageSuffix: "(refs ...)",
  automerge: true,
  automergeType: "branch",
  unpublishSafe: true,
  prCreation: "not-pending",
  major: { automerge: false }
}
```

**Comment by rarkins** [comment]
So this is a branch automerge that's happening? And I'm assuming it's for some packages that are > 24 hours old?

**Comment by ext** [comment]
Yes. And because the real builds hasn't run yet it sometimes causes the master branch to get builds failures due to the automerged dependencies.

**Comment by rarkins** [comment]
I guess we could consider filtering out `renovate/` statuses from https://github.com/renovatebot/renovate/blob/427fb1ce67cf05330ff071b20969709fe1211d42/lib/platform/bitbucket/index.ts#L386-L420

**Comment by souravdasslg** [comment]
Hi @rarkins ,if this isn't assigned already, I would love to take a look at it 🙂

**Comment by HonkingGoose** [comment]
@rarkins What is the status of this issue nowadays? It's been a long time since this issue was reported, so maybe this is now fixed?

**Comment by rarkins** [comment]
I think it possibly still applies

**Comment by HonkingGoose** [comment]
@rarkins Ah okay. Do we want to wait for the assigned user to complete the work, or do we want to free up the issue for somebody else to work on?

I don't know why a comment was deleted, so I'll let you deal with that. 😄

**Comment by ext** [comment]
I haven't tried it out recently because we ended up disabling `unpublishSafe`. But leaving it disabled is causing issues since we also use a npm dependency proxy so sometimes when package A is being updated dependency B might not be in the proxy cache yet yielding an error when running `npm install`.

But I could try enabling it again (well I guess it is `stabilityDays` now) to see if the issue persists and try to implement a bugfix if it is.

**Comment by viceice** [comment]
I know some time ago `stabilityDays` did not work for [proget](https://inedo.com/proget), because proget returns  now as published date, when the package wans't in cache yet, so renovate opened the pr. on next run the npm package was in cache, so renovate makred the pr as pending.

So maybe nexus has a similar issue.

I think this problem is not solvable by renovate, so we can close this.
