### ISSUE TITLE
git fetch failing with persistRepoData=true

### ISSUE THREAD

**Issue by Djaler** [renovatebot/renovate#4978]
**What Renovate type are you using?**

Self-hosted Renovate with GitLab.

**Describe the bug**

Renovate can't fetch repository after first launch.

```
ERROR: git fetch error (repository=lib/vuetify-utils)
       "err": {
         "message": "fatal: Couldn't find remote ref refs/heads/renovate/configure\n",
         "stack": "Error: fatal: Couldn't find remote ref refs/heads/renovate/configure\n\n    at /home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/promise.js:62:29\n    at Git.<anonymous> (/home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/src/git.js:1549:20)\n    at Function.Git.fail (/home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/src/git.js:1474:18)\n    at fail (/home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/src/git.js:1432:20)\n    at /home/kromanov/.npm-packages/pnpm-global/3/node_modules/.pnpm/registry.npmjs.org/simple-git/1.126.0/node_modules/simple-git/src/git.js:1441:16\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
```

**To Reproduce**

1. Clear renovate workdir (/tmp/renovate)
2. Run renovate
3. Run renovate again
4. See error in logs

**Additional context**

I found this in renovate workdir in `.git/config`:
```
...
[remote "origin"]
	url = ...
	fetch = +refs/heads/master:refs/remotes/origin/master
	fetch = +refs/heads/master:refs/remotes/origin/master
	fetch = +refs/heads/renovate/configure:refs/remotes/origin/renovate/configure
...
```

At first, here are two same entries for heads/master. And at second - here is explicit fetching for renovate/configure, that may be absent on remote

**Comment by rarkins** [comment]
OK, moved this back to the main repo. For now I recommend switching back to the default, but it would be nice to understand the root cause. Maybe we need to do some type of `git reset` or something. The `.git/config` is never touched directly by us, but instead by `git` itself.

Cc @ViceIce

**Comment by ViceIce** [comment]
i think this has somethig todo with our repo init on `GitStorage` class. 🤔
