### ISSUE TITLE
special casing needed for Go kubernetes client updates

### ISSUE THREAD

**Issue by jmhodges** [renovatebot/renovate#4991]
**What Renovate type are you using?**

GitHub App

**Describe the bug**

When Renovate updates a Go repository with a dependency on k8s client code, things get wonky. 

For instance, with k8s.io/client-go, two different pull requests will be made when a new version is released. One is broken with an odd version: https://github.com/jmhodges/lekube/pull/75 while the other is correct: https://github.com/jmhodges/lekube/pull/73

I'm not sure what happened here.

**Comment by ikesyo** [comment]
Looks like the library authors switched to correct semver versioning scheme for proper Go Modules support recently: https://github.com/kubernetes/client-go/commit/7624422635d15c33463f6a85ac2ccb1b0db452ec

But it's odd that there is fairly old v12.0.0 tag: https://github.com/kubernetes/client-go/releases/tag/v12.0.0. Renovate detects the tag as a major version bump. I assume the tag is the cause, so filing an issue to request remove/rename the tag on that repository will be good.

**Comment by rarkins** [comment]
The go client probably has some magic to know to ignore this. We may need to give up doing our own version resolution and calling out to `go` as discussed here: https://github.com/renovatebot/renovate/issues/4589
