### ISSUE TITLE
Refactor complex platform function calls to use an object parameter

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#4996]
We would benefit from refactoring some functions to take a typed object as their single/only parameter rather than multiple parameters. Example: https://github.com/renovatebot/renovate/blob/932aeefa40112788b0ebfc572708e28de2a4e04f/lib/platform/github/index.ts#L556-L567

Additionally the typing should of course be generic and shared by all platforms.

**Comment by souravdasslg** [comment]
Is "common.ts" is the appropriate place to define the typed object?

**Comment by rarkins** [comment]
Under platform, yes. Common for all platforms. There should be some other examples within platform files already

**Comment by souravdasslg** [comment]
As I understand the problem after looking at it,
1. Every platform has its own `commitFilesToBranch` function.
2. This function is getting called in
    worker>branch>commit.ts 
 Line 42 to Line 47
```
      await platform.commitFilesToBranch(
        config.branchName,
        updatedFiles,
        config.commitMessage,
        config.baseBranch || undefined
      );
```


I'm thinking of creating an interface named BranchFileParams in "common.ts" under the platform.
```
export interface BranchFileParams {
  branchName: string;
  files: File[];
  message: string;
  parentBranch: string;
}
```
I need to import this interface to worker>branch>commit.ts and change the parameter of `platform.commitFilesToBranch`

**Comment by rarkins** [comment]
Sounds ok

**Comment by souravdasslg** [comment]
I just wanted to discuss this, as I'm not sure.
Should the `BranchFileParams` be Type or Interface?

**Comment by souravdasslg** [comment]
I was thinking, this might be a good idea that every function is accepting only 1 argument throughout the codebase. It will improve consistency and readability.

We need to consider the predictable naming pattern for the argument types and a specific location to keep them.

**Comment by rarkins** [comment]
Yea, any time when a function call is shared between multiple files (platforms and datasources especially)

**Comment by rarkins** [comment]
Duplicate of #1458
