### ISSUE TITLE
Execute custom scripts to be committed

### ISSUE THREAD

**Issue by tschuchortdev** [renovatebot/renovate#5004]
### Which Renovate are you using? x the right box:

Renovate Open Source CLI

### Which platform are you using? x the right box:

GitLab self-hosted

### What is your Question?

Is it possible to execute a custom script in the repository before/after renovate commits the dependency updates? Use case is I want to update the project build version automatically as well, so that the CI pipeline can publish the artifact with a new version.

**Comment by tschuchortdev** [comment]
My use case:

We have a self-hosted gitlab CI pipeline that tries to publish a maven artifact automatically on commit to master. All development happens on feature branches before being merged to master. Naturally the same artifact version can not be published twice (and we want to avoid relying on SNAPSHOTs for reproducability reasons), so it is the developer's responsibility to increase the version number in the build file when they make a pull request. We would like renovate to call a script that does this increasing of the build version number so that the renovate PR can be merged automatically and the pipeline can publish the changes.

**Comment by rarkins** [comment]
We have a similar “native” feature for npm called bumpVersion. Could this be adapted to support Maven too?

**Comment by tschuchortdev** [comment]
The build system that we use is SBT, it just uses a maven repository. IIRC Maven is all dumb XML, so it shouldn't be too hard. SBT files on the other hand are more or less regular Scala code, so it's not as easy to update the version number in a general way since it could be hidden behind other functions and variables (the same is true for Gradle and a number of other build systems as well). Usually the version number is hard coded so we would just do a simple regex replace on the file. However that's kinda hacky and not something I'd be comfortable making official. 
I think making it possible to execute arbitrary scripts at different points of the renovate lifecycle would be the most flexible solution. You can't accommodate everyone with a one-size-fits-all configuration. 

A simple solution could be to add the option for a script that is executed on cloning a repository. This could be used to symlink other scripts in the repository into the .git/hooks folder and be able to change files in pre-/post-commit hooks, though that's not very user friendly.

**Comment by rarkins** [comment]
Please see https://docs.renovatebot.com/self-hosted-configuration/#allowedpostupgradecommands and https://docs.renovatebot.com/configuration-options/#postupgradetasks
