### ISSUE TITLE
feat(terraform-provider): add alias names to provider display names

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#5014]
**What would you like Renovate to be able to do?**
If two providers of the same type, e.g. two AWS providers, are used two MRs with the same names are created. This makes it necessary to go into the changes to find out for which provider is the target of the update.  

**Describe the solution you'd like**
The display name should contain the alias name to for better identification. 

Suggested naming convention:
       `<provider>.<alias>`         
e.g. `aws.west`
``` terraform
provider "aws" {
  alias  = "west"
  region = "us-west-2"
}
```
I prefer this convention as it is more akin to how variables are referenced in `Terraform`.    
``` terraform
resource "aws_eip" "ip" {
    vpc = true
    instance = aws_instance.example.id
}
```

**Describe alternatives you've considered**
Alternative naming strategies could be: 
-  `<alias>.<provider>`
-  `<provider>/<alias>`

**Comment by rarkins** [comment]
Can you give an example of what you mean, or better yet a reproduction repo?

I guess you mean that the PR title is not clear?

**Comment by secustor** [comment]
My bad, I misunderstood the default behaviour as bug.

It would be still from my point of view to beneficial if we would add an additional column to package list with unique naming to better identify the packages.

Here is an example: https://github.com/secustor/renovatebot-duplicateprovidertest/pull/2

**Comment by rarkins** [comment]
The columns in the PR tables are customisable. Check out the `renovate.json` in this repo for an example. You could possibly add an `alias` column just for the terraform provider and use `{{managerData.alias}}` if you extract the value too.
