### ISSUE TITLE
"Cannot find preset's package" error when using custom Github endpoint

### ISSUE THREAD

**Issue by maxmil7** [renovatebot/renovate#5020]
**What Renovate type are you using?**
Self hosting renovate
Using our enterprise Github instance as the endpoint

**Describe the bug**
We have a self-hosted renovate instance that we are using against our enterprise Github instance.
We would like to use Github based renovate presets to share our config with multiple repositories.

Here are the steps followed:
1. Created a `renovate-config` repo in our enterprise instance and tried to extend it in the `renovate.json` configuration file
2. Renovate was unable to find this repo and threw the following error:
```
"error": {
   "validationError": "Cannot find preset's package
}
```
3. I tried to debug a little locally and realized that Renovate [uses](https://github.com/renovatebot/renovate/blob/master/lib/datasource/github/index.ts#L14) public Github to fetch the presets.
4. Tried creating a config repo on `github.com` but again got the same error

**Did you see anything helpful in debug logs?**

**Additional context**

I think renovate is using the enterprise Github token to fetch the presets from public Github and hence unable to find it.

**Comment by rarkins** [comment]
Self-hosted presets are not yet supported and being tracked in #3019 so I will close this as a duplicate.

Re: 

> I think renovate is using the enterprise Github token to fetch the presets from public Github and hence unable to find it.

This is unlikely but please raise an issue if you become sure of it and have some logs to substantiate it. You should have configured a token for both your GHE as well as github.com and if you have not for github.com then it's more likely that you're being blocked/rate limited for submitting too many unauthenticated requests. See https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#githubcom-token-for-release-notes for details

**Comment by maxmil7** [comment]
Thanks for the quick reply. I tried setting up a public token but still got the same error. Will try to debug some more and see if I can get some more logs around it.
