### ISSUE TITLE
Bundler: support passing credentials to bundler CLI

### ISSUE THREAD

**Issue by aaronjensen** [renovatebot/renovate#5023]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [x] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

```
WARN: Gemfile.lock update failed due to missing credentials(branch="renovate/elided-2.x")
{
  "err": {
    "killed": false,
    "code": 17,
    "signal": null,
    "cmd": "docker run --rm -v \"/mnt/renovate/gh/myorg/myrepo\":\"/mnt/renovate/gh/myorg/myrepo\" -w \"/mnt/renovate/gh/myorg/myrepo/api\" renovate/ruby:2.5.5 bash -l -c \"ruby --version && gem install bundler -v 1.17.3 --no-document && bundle lock --update elided\"",
    "stdout": "ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]\nSuccessfully installed bundler-1.17.3\n1 gem installed\nAuthentication is required for gems.somewhere.com.\nPlease supply credentials for this source. You can do this by running:\n bundle config gems.somewhere.com username:password\n",
    "stderr": "",
    "message": "Command failed: docker run --rm -v \"/mnt/renovate/gh/myorg/myrepo\":\"/mnt/renovate/gh/myorg/myrepo\" -w \"/mnt/renovate/gh/myorg/myrepo/api\" renovate/ruby:2.5.5 bash -l -c \"ruby --version && gem install bundler -v 1.17.3 --no-document && bundle lock --update elided\"\n",
    "stack": "Error: Command failed: docker run --rm -v \"/mnt/renovate/gh/myorg/myrepo\":\"/mnt/renovate/gh/myorg/myrepo\" -w \"/mnt/renovate/gh/myorg/myrepo/api\" renovate/ruby:2.5.5 bash -l -c \"ruby --version && gem install bundler -v 1.17.3 --no-document && bundle lock --update elided\"\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  }
}
```

### What would you like to do?

Inform renovate of the username and password necessary to access the private gem source.

**Comment by rarkins** [comment]
Reference: https://bundler.io/v1.16/bundle_config.html#CREDENTIALS-FOR-GEM-SOURCES

First step though is that we would require `hostRules` to be configured and for the lookup to succeed prior to when we call `bundle`

**Comment by bilby91** [comment]
@rarkins Do you see this as a `bundler` configuration options. Something like:

```
  ...
  enabledManagers: [
    'bundler',
  ],
  bundler: {
    privateGemRepositories: [
      "https://my.private.repo"
   ],
...
```

**Comment by rarkins** [comment]
No, I thought it should hopefully only require `hostRules`, where there is the capability to define `hostType=bundler` as part of the rule.

**Comment by bilby91** [comment]
So, we would iterate over the `hostRules` looking for a rule that has `hostType=bundler`, if so, we inject the `bundle config` call ? Wouldn't be redundant to name it `hostType` if it would be inside the `hostRules` key ?

**Comment by bilby91** [comment]
I see that `hostType` is already a thing, ignore my last comment.

**Comment by rarkins** [comment]
Yes, that's right. A new hostRules api/function would be required, but I think it would be the same as the `findAll` in this other PR: https://github.com/renovatebot/renovate/pull/5164/files

So: findAll where hostType=bundler and then inject one `bundler config` call to the `docker run` command per-rule.

**Comment by bilby91** [comment]
That makes sense. 

Any preference on how to configure bundler ? We can inject the `bundle config` call or we can inject environment variables with the format `BUNDLE_MY__PRIVATE__REPO=user:pass`

**Comment by bilby91** [comment]
Another approach that could probably be more scalable long term is to support injecting env variables to all `docker run` invocations.

**Comment by rarkins** [comment]
Passing via env seems more manageable. BTW we also have a refactor of bundler execution in #5058 which we should merge first and then adding them should be much simpler

**Comment by bilby91** [comment]
So, currently this one would be blocked by #5058 and #5164 . I can take this one after those PRs land master.

**Comment by aaronjensen** [comment]
@rarkins Thanks for merging! Is this live yet? It doesn't appear to work, so just wanted to see if it's pending a deployment or I'm doing something wrong.

**Comment by rarkins** [comment]
@aaronjensen yes, it's live. I added some documentation here: https://docs.renovatebot.com/modules/manager/bundler/#authenticating-private-registry

**Comment by aaronjensen** [comment]
@rarkins Thanks, though those docs appear to be inaccurate. `hostname` is invalid (`hostName`)? And I think I need `username` and `password`, not `token`, right?

**Comment by bilby91** [comment]
@aaronjensen Yes, it should be `hostName`. You can use `username` and `password` if that is your authentication mechanisms. `token` is also supported.

**Comment by aaronjensen** [comment]
Thank you, I was able to get this working.
