### ISSUE TITLE
Support for Gradle behind proxy

### ISSUE THREAD

**Issue by patrickmarabeas** [renovatebot/renovate#5024]
Gradle unable to get required resources. Should these be baked into image?

`renovate.json`
```
{
  "gradle": {
    "enabled": true
  }
}
```

Log output:
```
DEBUG: Creating init.gradle file (repository=XXX/XXX)
--
  | DEBUG: Start gradle command (repository=XXX/XXX)
  | "cmd": "gradle --init-script init.gradle dependencyUpdates -Drevision=release"
  | WARN: Gradle command gradle --init-script init.gradle dependencyUpdates -Drevision=release failed. Exit code: 1. (repository=XXX/XXX)
  | "err": {
  | "name": "ChildProcessError",
  | "code": 1,
  | "childProcess": {},
  | "stdout": "\nWelcome to Gradle 4.10.2!\n\nHere are the highlights of this release: ...
  | "stderr": "Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'XXXXX'
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve gradle.plugin.se.patrikerdes:gradle-use-latest-versions-plugin:0.2.3.
     Required by:
         project :
      > Could not resolve gradle.plugin.se.patrikerdes:gradle-use-latest-versions-plugin:0.2.3.
         > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/se/patrikerdes/gradle-use-latest-versions-plugin/0.2.3/gradle-use-latest-versions-plugin-0.2.3.pom'.
             > Could not GET  
...

```

**Comment by rarkins** [comment]
I've transferred this into the main repo because it relates to a proxy feature for Gradle that is not specific to the Pro version

**Comment by rarkins** [comment]
From https://stackoverflow.com/a/22666646/3005034

Looks like we can pass to `gradlew` through CLI: `gradlew -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 - Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3129 -Dhttps.proxyUser=user -Dhttps.proxyPassword=pass -Dhttp.proxyUser=user -Dhttp.proxyPassword=pass -Dhttp.nonProxyHosts=host1.com|host2.com`

**Comment by rarkins** [comment]
I'm marking this as `ready` but would need someone willing and able to test out a feature branch with a real setup before I would start it.

**Comment by Ch4rl3x** [comment]
Hey. Any updates? Seems we are struggeling with the same issue. 

`./gradlew --init-script renovate-plugin.gradle renovate` 

throws ConnectionException behind proxy. GRADLE_OPTS and http_proxy/https_proxy are not working.

**Comment by viceice** [comment]
A community pr would be welcome, as no maintainer is using a proxy setup. 🙃

**Comment by Ch4rl3x** [comment]
I switched to the new gradle-lite manager. Seems to work 😃

**Comment by eifinger** [comment]
Thank you @ch4rl3x 
I was able to use the proxy env vars with the following environment variables for the docker image:
```yaml
...
RENOVATE_EXTENDS: 'github>whitesource/merge-confidence:beta, :switchToGradleLite'
RENOVATE_GRADLE_LITE_ENABALED: 'true'
...
```

**Comment by rarkins** [comment]
Yes, I'm going to close this as resolved. The gradle-lite manager does not rely on gradle itself and therefore uses configure `hostRules`, proxy settings, etc.
