### ISSUE TITLE
Poetry fails to create virtual environment to update lockfile

### ISSUE THREAD

**Issue by keimlink** [renovatebot/renovate#5029]
**What Renovate type are you using?**

We're using the GitHub App.

**Describe the bug**

Poetry fails to create a virtual environment when updating `poetry.lock` for the first update.

#4999 deactivated in-project virtual environments. But since Poetry 1.0.0 a `poetry.toml` file can be used to configure this per project:

```toml
[virtualenvs]
in-project = true
```

If a project is configured like this, Poetry [creates the virtual environment](https://github.com/python-poetry/poetry/blob/1.0.0/poetry/utils/env.py#L104) using the `venv` module when updating the lockfile.

As the log output below shows this fails because the `python3-venv` package is not installed.

If another Python dependency is updated after this, Poetry will [skip the creation](https://github.com/python-poetry/poetry/blob/1.0.0/poetry/utils/env.py#L590) of the virtual environment. I assume this happens because the `.venv` directory exists, although it doesn't contain all necessary files. Poetry does not verify the contents of the `.venv` directory.

Therefore the [update of Django to v2.2.9](https://github.com/keimlink/renovate-poetry-ensurepip-not-available/pull/2) fails while the [update of Django to v3](https://github.com/keimlink/renovate-poetry-ensurepip-not-available/pull/3) succeeds.

**Did you see anything helpful in debug logs?**

Log output from Renovate job `122798668`:

```json
{
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm -v \"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\":\"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\" -w \"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\" renovate/poetry poetry update --lock --no-interaction Django",
    "stdout": "Creating virtualenv renovate-poetry-ensurepip-not-available in /mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available/.venv\nThe virtual environment was not created successfully because ensurepip is not\navailable.  On Debian/Ubuntu systems, you need to install the python3-venv\npackage using the following command.\n\n    apt-get install python3-venv\n\nYou may need to use sudo with that command.  After installing the python3-venv\npackage, recreate your virtual environment.\n\nFailing command: ['/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available/.venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']\n\n",
    "stderr": "",
    "message": "Command failed: docker run --rm -v \"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\":\"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\" -w \"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\" renovate/poetry poetry update --lock --no-interaction Django\n",
    "stack": "Error: Command failed: docker run --rm -v \"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\":\"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\" -w \"/mnt/renovate/gh/keimlink/renovate-poetry-ensurepip-not-available\" renovate/poetry poetry update --lock --no-interaction Django\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
  }
}
```

The important part in `stdout` seems to be:

```console
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv
```

**To Reproduce**

[keimlink/renovate-poetry-ensurepip-not-available](https://github.com/keimlink/renovate-poetry-ensurepip-not-available) reproduces the bug.

**Additional context**

**Comment by rarkins** [comment]
Reopened this to fix it in the docker/app version

**Comment by rarkins** [comment]
This is now fixed in the Docker `renovate/poetry` image and hence in the app too. Reproduced then fixed here: https://github.com/renovate-tests/renovate-poetry-ensurepip-not-available/pulls

Thanks @keimlink
