### ISSUE TITLE
Full list of branch template tags?

### ISSUE THREAD

**Issue by baohx2000** [renovatebot/renovate#5039]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [ ] WhiteSource Renovate App
- [X] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [X] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

I can't seem to find any documentation listing all of the variable tags available for doing something like modifying the branchName. Maybe I missed it, but searching the few I know do not turn up anything.

**Comment by rarkins** [comment]
We don't have the list anywhere, so I've transferred this issue into the main repo as a feature request. We should ideally have an explicit array of which fields are supported and then filter the full object before applying templates. The array can then be used as a source of documentation for which fields are supported.

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by rarkins** [comment]
This work has been completed in https://github.com/renovatebot/renovate/blob/main/lib/util/template/index.ts and https://docs.renovatebot.com/templates/ but I forgot to close this
