### ISSUE TITLE
"Update" force pushes replace package.json upgrades with smaller yarn.lock changes

### ISSUE THREAD

**Issue by taion** [renovatebot/renovate#5052]
**What Renovate type are you using?**

GitHub hosted app.

**Describe the bug**

See e.g. https://github.com/4Catalyzer/selenium-sandbox/pull/23. Just now, Renovate force-pushed from https://github.com/4Catalyzer/selenium-sandbox/commit/59230bd836f8806aca6db7ad301c985204761c91 to https://github.com/4Catalyzer/selenium-sandbox/commit/5487bae479fec54c524bbf9971b3c8d9e807ad35. The former commit actually updated all of my dependencies, while the latter just did a single update in a lockfile. I expect the second force push not to remove the earlier updates like that. Something similar happens in https://github.com/4Catalyzer/javascript/pull/547 where the PR somehow got auto-closed.

**Did you see anything helpful in debug logs?**

I believe it's https://app.renovatebot.com/dashboard#github/4Catalyzer/selenium-sandbox/124158181.

**To Reproduce**

See both repos.

**Additional context**

N/A

**Comment by rarkins** [comment]
Did you make any config changes in this time?

**Comment by taion** [comment]
Nope; the configs haven't changed in a while: https://github.com/4Catalyzer/renovate-config

**Comment by taion** [comment]
Also, it seems to go back and forth a bit. Some commits include the full (maybe?) package.json changes, while others just change a couple of things in the lockfile.

**Comment by rarkins** [comment]
In that case this is strange behaviour. We’d need to identify and compare the logs from both the old (correct?) commit run as well as the new one to see if we can get some hints as to why the result is different. It looks like there were many force pushes since PR creation so maybe it was flip flopping? We usually need to compare the time stamps off GitHub with those in the jobs to be sure.

**Comment by taion** [comment]
Maybe taking a smaller example from 

https://github.com/4Catalyzer/javascript/pull/547

PR created: https://app.renovatebot.com/dashboard#github/4Catalyzer/javascript/123985138
PR closed: ... I think in https://app.renovatebot.com/dashboard#github/4Catalyzer/javascript/123993700 ?

I don't see any other logs around that time.

Immediately prior:


https://github.com/4Catalyzer/javascript/pull/546

Created: https://app.renovatebot.com/dashboard#github/4Catalyzer/javascript/123973524
Closed?: https://app.renovatebot.com/dashboard#github/4Catalyzer/javascript/123977688

The second set of logs might be slightly better... they show Renovate trying to update the PR, and then immediately upon trying to merge it, seeing that it's actually now closed.

**Comment by taion** [comment]
If it's useful, here's an example of a smaller update where the force-pushes are going back and forth between updating just `yarn.lock` and updating both `package.json` and `yarn.lock`: https://github.com/4Catalyzer/astroturf/pull/538

And here are a few more examples of PRs closing themselves for "no changes":
- https://github.com/4Catalyzer/graphql-explorer/pull/19#event-2922975692
- https://github.com/4Catalyzer/cli/pull/145#event-2923002624
- https://github.com/4Catalyzer/javascript/pull/552#event-2923003604

One thing that's interesting is that these last 3 repos are all monorepos. The `astroturf` repo isn't, though.

**Comment by rarkins** [comment]
I think it's some combination of (a) grouping, and (b) `update-lockfile` `rangeStrategy`.

Here's the log from the run before, when no update was done:

```
{"msg":"Branch does not need rebasing","time":"2020-01-06T11:43:16.009Z"}
{"msg":"Using parentBranch: renovate/all-minor-patch","time":"2020-01-06T11:43:16.009Z"}
{"msg":"manager.getUpdatedPackageFiles()","time":"2020-01-06T11:43:16.009Z"}
{"msg":"npm.updateDependency(): dependencies.css-loader = ^3.0.0","time":"2020-01-06T11:43:16.064Z"}
{"msg":"npm.updateDependency(): devDependencies.dtslint = ^2.0.3","time":"2020-01-06T11:43:16.133Z"}
{"msg":"No package files need updating","time":"2020-01-06T11:43:16.133Z"}
```

Here's the same functionality logged the next run when it force pushed:

```
{""msg":"Branch does not need rebasing","time":"2020-01-06T12:38:33.667Z"}
{""msg":"Using parentBranch: renovate/all-minor-patch","time":"2020-01-06T12:38:33.667Z"}
{""msg":"manager.getUpdatedPackageFiles()","time":"2020-01-06T12:38:33.667Z"}
{""msg":"npm.updateDependency(): dependencies.css-loader = ^3.0.0","time":"2020-01-06T12:38:33.711Z"}
{""msg":"npm.updateDependency(): devDependencies.dtslint = ^2.0.3","time":"2020-01-06T12:38:33.741Z"}
{""msg":"Replacing \"^2.0.2\" with \"^2.0.3\" at index 2639","time":"2020-01-06T12:38:33.741Z"}
{""msg":"Need to update package file so will rebase first","time":"2020-01-06T12:38:33.744Z"}
{""msg":"manager.getUpdatedPackageFiles()","time":"2020-01-06T12:38:33.744Z"}
{""msg":"npm.updateDependency(): dependencies.css-loader = ^3.0.0","time":"2020-01-06T12:38:33.783Z"}
{""msg":"npm.updateDependency(): devDependencies.dtslint = ^2.0.3","time":"2020-01-06T12:38:33.820Z"}
{""msg":"Replacing \"^2.0.2\" with \"^2.0.3\" at index 2639","time":"2020-01-06T12:38:33.821Z"}
{""msg":"Updating packageFile content","time":"2020-01-06T12:38:33.821Z"}
{""msg":"Updated 1 package files","time":"2020-01-06T12:38:33.830Z"}
```

So far I'm not sure what's causing the problem.

**Comment by taion** [comment]
Ah! Perhaps noteworthy here is that it's not _just_ `update-lockfile` – I'm using `update-lockfile` for prod dependencies, but `bump` for `devDependencies`... so maybe something strange when multiple range strategies apply in a single grouped PR?

**Comment by taion** [comment]
Okay, on closer inspection, it looks like my Renovate config didn't quite work at all. I was trying to get "bump for dev dependencies, update lockfile for prod dependencies", but it turns out that it was just alternating between the two – either only bumping dev deps, or only updating lockfile for prod deps.
