### ISSUE TITLE
Run Renovate on currently checked out repository

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/renovate#5073]
**What would you like Renovate to be able to do?**
When creating a base shareable config for my GitLab repos, I need some way where I can test config changes so that Renovate doesn't break in every repo using my base configuration.

**Describe the solution you'd like**
A way to run Renovate's Docker container inside of GitLab CI on the current checked out branch only (local repository instead of external). I can then run Renovate in dry run mode so that it simply lints the configuration without creating any MRs.

**Describe alternatives you've considered**
Alternative would be a lint command that we can run in CI that lints a given config. However, this places a lot of code on your end to maintain this command.

**Comment by rarkins** [comment]
I want to make sure I understand what you mean.

You have a **preset** config, right? And you want ways to test changes to it carefully, because if you make a mistake then that mistakes affects every repo that uses it?

**Comment by Jamesking56** [comment]
Yeah I have a custom preset that I add to all of my projects which is a private GitLab repo.

I want to make changes to it in a safe way by using MRs and GitLab CI to test my renovate preset config in dry run mode.

However, Renovate only seems to test against remote repositories and adding the preset as a remote repo only checks the `master` branch (not my MR branch)

**Comment by rarkins** [comment]
OK, so you have a centralised preset, and you create a change for it in a new branch/MR. How do you suggest your CI (presumably on a downstream repo) would then know (a) to use that branch instead of master, and (b) to use dry-run?

**Comment by Jamesking56** [comment]
Well GitLab CI checks out the MR code and puts in into the Docker container. So if renovate could use a currently checked out code instead of using a remote repo - we could then check the MRs code of the preset and run renovates dry run on it.

Hope that makes sense

**Comment by rarkins** [comment]
When you say "renovate" should do things, isn't this Renovate that you're running as part of your CI? And how do you expect to know if something is wrong? e.g. you will ready through the dry-run logs manually on your MR before merging? And presumably it's testing against *itself* (i.e. the local repository) which may not have any dependencies?

**Comment by Jamesking56** [comment]
Well I'd hope Renovate would return an exit code of >0 if the config is invalid, which would cause CI to fail.

True that itself won't have dependencies, but this is more for linting the config than testing it.

**Comment by rarkins** [comment]
Renovate ships with a validation command in its bin/ dir. Can you run that as part of your CI?

**Comment by Jamesking56** [comment]
@rarkins Thanks very much this works perfectly.

For reference, here is my GitLab CI config for it (add to `.gitlab-ci.yml` in root of repo):

```yaml
lint:
    image:
        name: renovate/renovate
        entrypoint: [""]
    script:
        - node /usr/src/app/bin/config-validator.js
```
