### ISSUE TITLE
Show Release notes in Gitlab MR

### ISSUE THREAD

**Issue by gperdomor** [renovatebot/renovate#5079]
**What would you like Renovate to be able to do?**
Show release notes in Gitlab merge requests...

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
In Github the PR created by renovate have more context, like the changeling/release notes

**Comment by rarkins** [comment]
How are you running Renovate?

**Comment by gperdomor** [comment]
using this --> https://app.renovatebot.com

**Comment by grit96** [comment]
I've also noticed that I don't get release notes in my GitLab merge requests. I am running renovate from the CLI via cron.

**Comment by viceice** [comment]
@grit96 have configured a GitHub token?

**Comment by rarkins** [comment]
Yes, Renovate needs a github.com token defined or it won't attempt to add Release Notes. See https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md#githubcom-token-for-release-notes
