### ISSUE TITLE
Support for Terraform modules located in GHE repository

### ISSUE THREAD

**Issue by patrickmarabeas** [renovatebot/renovate#5115]
Looks like support for Terraform modules is limited to github.com repositories (as per the docs) for Renovate Pro as well.

Log:

```
DEBUG: packageFiles with updates (repository=org/repository)
  "config": {
    "terraform": [
      {
        "packageFile": "module.tf",
        "manager": "terraform",
        "deps": [
          {
            "moduleName": "module",
            "managerData": {},
            "source": "git::https://github.corp.domain/org/module.git?ref=v1.0.0 ",
            "skipReason": "no-version",
            "updates": []
          }
        ]
      }
    ]
  }
```

I can probably work around this by using Git Submodules in the mean time as they are supported by Terraform Enterprise.

**Comment by rarkins** [comment]
@patrickmarabeas this would need implementing within the core Renovate code so I have transferred the issue and classified it as a feature request.

**Comment by jakauppila** [comment]
This appears to be a duplicate of https://github.com/renovatebot/renovate/issues/3209 ?

**Comment by rarkins** [comment]
Possibly. We have two different datasources for Terraform (ref: https://github.com/renovatebot/renovate/tree/master/lib/datasource) so possibly we'd have two different issues to close this.

**Comment by secustor** [comment]
@rarkins This is a duplicate, as it is not possible to manually define the location of Terraform providers ( except on the local file system).     

This issue is about Terraform modules.
