### ISSUE TITLE
Pipenv not updating the `Pipfile.lock`

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5117]
renovate doesn't update the `Pipfile.lock`. I didn't manage to find what renovate runs. Do you run `pipenv update --dev`?

Doing this will update the lock file, and make sure dev deps are updated as well

_Originally posted by @ElPicador in https://github.com/renovatebot/config-help/issues/471#issuecomment-572468195_

**Comment by rarkins** [comment]
@ElPicador Renovate first updates `Pipfile` and then runs `pipfile lock`. Source: https://github.com/renovatebot/renovate/blob/fc0b3d3026bd823c1ec81bc2c9c35a79aec1f6b6/lib/manager/pipenv/artifacts.ts#L54

**Comment by ElPicador** [comment]
I checked-out locally a branch from renovate that updates a dep:

```
➜ git checkout renovate/sendgrid-6.x
Branch 'renovate/sendgrid-6.x' set up to track remote branch 'renovate/sendgrid-6.x' from 'origin'.
Switched to a new branch 'renovate/sendgrid-6.x'

➜ git log --stat
commit 0c70058d4f0b61aa681f575ec1c84f7d581525a5 (HEAD -> renovate/sendgrid-6.x, origin/renovate/sendgrid-6.x)
Author: Renovate Bot <bot@renovateapp.com>
Date:   Mon Dec 23 14:23:52 2019 +0000

    Update dependency sendgrid to v6

 Pipfile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

➜ pipenv lock
Locking [dev-packages] dependencies…
✔ Success! 
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (1e7ee6)!

➜ git status                  
On branch renovate/sendgrid-6.x
Your branch is up to date with 'origin/renovate/sendgrid-6.x'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Pipfile.lock
```

It seems renovate forgot to add `Pipfile.lock` to the commit. Maybe that's the root issue?

**Comment by rarkins** [comment]
I think that's showing a local modification of `Pipfile.lock` though, isn't it? i.e. it's because of a `pipenv` command you ran locally.

**Comment by ElPicador** [comment]
Indeed, but look at the `git log --stat` of the commit from renovate. It's only `Pipfile` no `Pipfile.lock`. 

I ran `pipenv` manually to show that it does modify the `Pipfile.lock`, but renovate didn't commit it.

Does that make sense?

**Comment by rarkins** [comment]
But did you run `pipenv lock` like Renovate does, or another command?

**Comment by ElPicador** [comment]
as shown above, only `pipenv lock`

> ➜ pipenv lock
Locking [dev-packages] dependencies…
✔ Success! 
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (1e7ee6)!

**Comment by rarkins** [comment]
Sorry, I missed that. This is useful and I’ll check it out

**Comment by rarkins** [comment]
Can you locate the job id for when the lock file update was missed? renovatebot.com/dashboard. You’ll need to correlate based on timestamp of the *commit*

**Comment by ElPicador** [comment]
As we have the issue on all renovate PR, the latest job, #129402672, should be good.

**Comment by rarkins** [comment]
Renovate won't regenerate lock files every single run, so it needs to be a job where the Pipfile/Pipfile.lock was updated. I found job 129390877 with the following log included:

```
{"msg":"Returning updated Pipfile.lock","time":"2020-01-09T11:53:58.451Z"}
{"msg":"Updated 1 package files","time":"2020-01-09T11:53:58.452Z"}
{"updatedArtifacts":["Pipfile.lock"],"msg":"Updated 1 lock files","time":"2020-01-09T11:53:58.452Z"}
{"msg":"2 file(s) to commit","time":"2020-01-09T11:53:58.463Z"}
{"msg":"Committing files to branch renovate/regex-2020.x","time":"2020-01-09T11:53:58.463Z"}
```

It appears to have detected the changed `Pipfile.lock` and then prepared to commit it. Can you check this branch?

**Comment by ElPicador** [comment]
Indeed this PR has the `Pipfile.lock` updated. And now when I force a rebase of a PR, the `Pipfile.lock` is updated. 

So it seems to work 🤷‍♂

**Comment by rarkins** [comment]
OK, let's close this for now, but if you get any PRs in future with a missing `Pipfile.lock` then please let me know so that we can debug it.

**Comment by benlangfeld** [comment]
@rarkins Still broken for us: https://app.renovatebot.com/dashboard#github/powerhome/APP/192098447

Does it matter that the Pipfile/Pipfile.lock is in a sub-directory, not the repo root?

```
{16:04}~/code/APP:renovate/certifi-2020.x ✓ [2.7.0]
141 ↵ ➭ cd base_images/deployer/config_kube_context 
{16:04}~/code/APP/base_images/deployer/config_kube_context:renovate/certifi-2020.x ✓ [2.7.0]
➭ pipenv lock
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (b0940f)!
{16:04}~/code/APP/base_images/deployer/config_kube_context:renovate/certifi-2020.x ✗ [2.7.0]
➭ git --no-pager diff
diff --git a/base_images/deployer/config_kube_context/Pipfile.lock b/base_images/deployer/config_kube_context/Pipfile.lock
index 7b37c78..a5f6468 100644
--- a/base_images/deployer/config_kube_context/Pipfile.lock
+++ b/base_images/deployer/config_kube_context/Pipfile.lock
@@ -1,7 +1,7 @@
 {
     "_meta": {
         "hash": {
-            "sha256": "1cd5df330e8aea15c99b815c91359e11c4ad588d622853314c307b03be3cd756"
+            "sha256": "02e1704929c0e305b219ca0d555583ebd354cc13e93efe7fea04850eb3b0940f"
         },
         "pipfile-spec": 6,
         "requires": {
@@ -18,11 +18,11 @@
     "default": {
         "certifi": {
             "hashes": [
-                "sha256:5ad7e9a056d25ffa5082862e36f119f7f7cec6457fa07ee2f8c339814b80c9b1",
-                "sha256:9cd41137dc19af6a5e03b630eefe7d1f458d964d406342dd3edf625839b944cc"
+                "sha256:5930595817496dd21bb8dc35dad090f1c2cd0adfaf21204bf6732ca5d8ee34d3",
+                "sha256:8fc0819f1f30ba15bdb34cceffb9ef04d99f420f68eb75d901e9560b8749fc41"
             ],
             "index": "pypi",
-            "version": "==2020.4.5.2"                                         +            "version": "==2020.6.20"
         },
         "chardet": {
             "hashes": [
@@ -50,8 +50,9 @@
         },
         "requests": {
             "hashes": [
-                "sha256:43999036bfa82904b6af1d99e4882b560e5e2c68e5c4b0aa03b655f3d7d73fee",
-                "sha256:b3f43d496c6daba4493e7c431722aeb7dbc6288f52a6e04e7b6023b0247817e6"
+                "sha256:5d2d0ffbb515f39417009a46c14256291061ac01ba8f875b90cad137de83beb4",
+                "sha256:b3f43d496c6daba4493e7c431722aeb7dbc6288f52a6e04e7b6023b0247817e6",
+                "sha256:43999036bfa82904b6af1d99e4882b560e5e2c68e5c4b0aa03b655f3d7d73fee"
             ],
             "index": "pypi",
             "version": "==2.23.0"
```

**Comment by rarkins** [comment]
If you’re able to reproduce the problem (in a public repo) then please create a fresh issue so we can take a look.
