### ISSUE TITLE
Incorrect version bump?

### ISSUE THREAD

**Issue by NullVoxPopuli** [renovatebot/renovate#5122]
**What Renovate type are you using?**
GitHub

**Describe the bug**
Why would it downgrade?
https://github.com/NullVoxPopuli/emberclear/pull/398/files

**To Reproduce**
Project is open source

**Comment by JamieMagee** [comment]
Unfortunately it looks like `shoelace-css` doesn't strictly follow semantic versioning:

![image](https://user-images.githubusercontent.com/1358764/72107003-c385e400-3330-11ea-940a-fba5a2c17e0a.png)

semver expects pre-release numbers to be separated by `.` i.e. it's expecting `1.0.0-beta.24`.

**Comment by NullVoxPopuli** [comment]
ah!
I'll open an issue on shoelace. thanks!
