### ISSUE TITLE
ignore "empty" Go module updates

### ISSUE THREAD

**Issue by jmhodges** [renovatebot/renovate#5123]
So, I'm getting lots of PRs like https://github.com/jmhodges/lekube/pull/94, where the only changes are to the commit hash in the 3 files managed by the Go module system. There's no actual code changes in there beyond the version bump, because the Go module system (correctly) sees there were no relevant updates to the subpackages used by lekube.

It'd be cool if these "empty" PRs didn't happen. I get them every few days because those repos have new commits often. It's making pay less attention to all of my renovate PRs, because these "empty" PRs are far more common than the useful PRs.

**Comment by rarkins** [comment]
Do you have any ideas for how Renovate could "know" that? e.g. would an option "skip the PR completely if there's no change to `vendor/`" work?

**Comment by jmhodges** [comment]
If the update only changes the files `go.mod`, `go.sum`, and `vendor/modules.txt`, then it's an empty one. So, "almost yes" to your question because `vendor/modules.txt` always changes when the commit sha is bumped even though no code does.

**Comment by rarkins** [comment]
Is the only way to determine this is after `go mod vendor` and check the results?

**Comment by jmhodges** [comment]
Since I don’t know renovate’s codebase, I don’t think I can answer the question

**Comment by rarkins** [comment]
It's a Go question, not a Renovate question. If a Go dependency is not using modules (uses commits instead) and the commit is updated, can you tell if it's an "empty" change without running `go mod vendor`?

**Comment by jmhodges** [comment]
Man, I’m sorry but I’m doing this on my free time. I have no idea how deep into the guts you need to go to not run the whole “go mod vendor” stuff. There’s clearly a world in which you can dig into that code to do less work but I have no idea what it entails

**Comment by thejan2009** [comment]
Hello there, 
except for the files created by `go mod vendor`, I haven't found any other way to list changed dependency source code when upgrading a `go.mod` file.

Is there a way to gracefully abort and then ignore the upgrade with a PostUpgradeTask? That would allow us to detect and  solve the above issue in a self-hosted deployment.

**Comment by rarkins** [comment]
Possibly a script which:
- Uses git to check for any changes to the vendor dir
- If no changes to the vendor dir, it uses git to reset the `go.mod` and `go.sum` values back to the base branch

Although manipulating `git` is usually not a good idea, this *might* end up working if it tricks Renovate into thinking there's no changes and to skip the branch.

Essential that someone can create a reproduction

**Comment by thejan2009** [comment]
See here: https://github.com/thejan2009/renovate-go-5123

`catch.sh` attempts to do what you described, but for some reason resetting the git folder does nothing and Renovate still finds the 3 files to update (`go.mod`, `go.sum` and `vendor/modules.txt`).

**Comment by rarkins** [comment]
Confirmed I could get the anticipated result with a bit of code mod:

```
 WARN: Detected empty commit - aborting git push (repository=renovate-reproductions/5123, branch=renovate/github.com-stretchr-testify-1.x)
       "commitRes": {
         "author": null,
         "branch": "",
         "commit": "",
         "root": false,
         "summary": {"changes": 0, "insertions": 0, "deletions": 0}
       }
```

But I need to think if there's a cleaner way

**Comment by rarkins** [comment]
Blocked by #18609

**Comment by rarkins** [comment]
I think this should now be supported, as long as a GOPROXY is in use.
