### ISSUE TITLE
Grade qualifier dependencies should not be replaced

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5150]
**Describe the bug**

Description by @walschap:

In gradle qualifier dependencies can be used. e.g. testBuilder, when used in combination with contraints, the version can be ommited.  e.g: mysql:mysql-connector-java::mockServer is a valid definition. It's version is determined by a contraint

```
 dependencies {
            implementation "mysql:mysql-connector-java::mockServer"
            constraints {
                implementation "mysql:mysql-connector-java:6.0.5"
            }
 }
```

renovate updates this when a new version is found. `mysql:mysql-connector-java::mockServer` -> `mysql:mysql-connector-java:7.0.0` which it shouldn't.

**To Reproduce**

See test case in `fix/gradle-qualifier`. Still needs reproduction in a repository.

**Additional context**

https://github.com/renovatebot/renovate/pull/5149

**Comment by JamieMagee** [comment]
@walschap What's the expected behaviour here? Should renovate upgrade the constraint, and leave the dependency alone? If so we need to differentiate between dependencies and constraints as the output from the current script isn't enough to know the difference:

```json
[
  {
    "project": "gradle-constraint",
    "repositories": [
      "https://jcenter.bintray.com/",
      "https://plugins.gradle.org/m2"
    ],
    "dependencies": [
      {
        "name": "mysql-connector-java",
        "group": "mysql",
        "version": null
      },
      {
        "name": "mysql-connector-java",
        "group": "mysql",
        "version": "6.0.5"
      }
    ]
  }
]
```

**Comment by walschap** [comment]
@JamieMagee  I think the key is the 3 colons i.s.o 2, only the space after the 2nd colon and before the optional 3rd one can contain a version.

**Comment by JamieMagee** [comment]
Yes, I understand that, but with the example listed above what is the expected outcome.

```groovy
implementation "mysql:mysql-connector-java::mockServer"
constraints {
  implementation "mysql:mysql-connector-java:6.0.5"
}
```

In my mind there are 2:

- Increment the constraint

```
implementation "mysql:mysql-connector-java::mockServer"
constraints {
  implementation "mysql:mysql-connector-java:7.0.0"
}
```

- Increment the explicit dependency (and remove the constraint?)

```
implementation "mysql:mysql-connector-java:7.0.0:mockServer"
```

**Comment by walschap** [comment]
@JamieMagee For me this means incrementing the constraint only. Leaving the dependency with the implicit version. It's flavour using explicit dependencies without constraints or implicit with constraints, so I wouldn't want to be forced in one or the other. Only updating explicit versions does that.

**Comment by JamieMagee** [comment]
Okay, I think I've got enough information to implement this now.

Renovate should pin/update a dependency without a version, only if no constraint exists. If a constraint exists, Renovate should update the constraint, and leave the dependency as-is.

Thanks for all your help in nailing down the expected behaviour.

**Comment by rarkins** [comment]
@zharinov can you take a look at this for `gradle-lite`?

**Comment by zharinov** [comment]
@rarkins works fine: https://github.com/renovate-testing/test-5150-gradle-wrong-replacement/pulls

**Comment by rarkins** [comment]
If this is still a problem for anyone, please see the `:enableGradleLite` and `:switchToGradleLite` presets.
