### ISSUE TITLE
Unify Branch Status

### ISSUE THREAD

**Issue by souravdasslg** [renovatebot/renovate#5173]
Unify similar branch statuses.
e.g 

```
export const BRANCH_STATUS_FAILED = 'failed';
export const BRANCH_STATUS_FAILURE = 'failure';
```

#### This is a:

- [x] Refactor

**Comment by rarkins** [comment]
Let's also consider if any of the others can be unified too. I wonder if all we need is pending | success | failed and that a few others (such as "error" and "running") could be massaged at the platform layer instead of the worker layer.

**Comment by rarkins** [comment]
I think to avoid accidental conflicts it's good to unify under green/yellow/red. I started on this and it's definitely harder than it looks.
