### ISSUE TITLE
Support "standard-version" changelog format

### ISSUE THREAD

**Issue by simoneb** [renovatebot/renovate#5181]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [X] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [X] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

Show releases notes from the target package's CHANGELOG.md file formatted using semantic versioning tooling.

Right now, if the target package has a CHANGELOG.md file formatted in a way similar to this (using the `standard-version` toolchain):

```
# Changelog

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

### [0.1.13](https://github.com/org/pkg/compare/v0.1.12...v0.1.13) (2020-01-15)

### Features

* some feature ([a813e4c](https://github.com/org/pkg/commit/a813e4cc3db9fed5d86fa7391aeec0a62bc9d1f4))

### [0.1.12](https://github.com/org/pkg/compare/v0.1.10...v0.1.12) (2020-01-14)

### Features

* some other feature ([f21e1dd](https://github.com/org/pkg/commit/f21e1dd6f81e098322e9598195da9cc24fa6f868))
```

In a Renovate PR for bumping that package version, say from 0.1.12 to 0.1.13 I get something similar to this:

![image](https://user-images.githubusercontent.com/20181/72523956-31666a00-3861-11ea-9db7-369a1dbcbbb0.png)

Meaning that it can somehow pick some version information, but I would like to see the actual features introduced similarly to what's in the CHANGELOG.md file rather than just the version number and a link to the diff.

**Comment by rarkins** [comment]
I've transferred this issue into the main repo as a feature request and added the latest standard-version changelog as a text fixture in this branch: https://github.com/renovatebot/renovate/tree/feat/standard-version-changelog-support

Still needs:
- [ ] Failing test case
- [ ] Implementation to detect and parse this format

**Comment by simoneb** [comment]
Is there anything else I can provide?

**Comment by rarkins** [comment]
You could submit a pull request to that branch adding a failing test case for the standard-version fixture. Example test case: https://github.com/renovatebot/renovate/blob/982d5e9d4d83b9251a31b125933d26712bb592b1/test/workers/pr/changelog/release-notes.spec.ts#L149-L165

In this case though it is not enough to just check that it's not null. We need to check that the patch versions in the new fixture are included, e.g. `7.0.1`.

**Comment by simoneb** [comment]
Ok done that, but the test doesn't fail and I would use some help to figure out what's wrong. The CHANGELOG is parsed, but it seems it's simply parsed, not sure how to check that all the versions are being picked up.

https://github.com/renovatebot/renovate/pull/5183

**Comment by rarkins** [comment]
Tests are now failing in that branch

**Comment by simoneb** [comment]
@rarkins I see you merged my PR. In that PR the checks were all green, how do I see the tests failing for the branch the PR merged into? On GH actions all seems good as far as I can see

**Comment by rarkins** [comment]
Actually I just merged it in order for me to make some changes to your tests to get them to fail. See https://github.com/renovatebot/renovate/commit/66213cb2c63a559e90b374fe2b6d757d4b301c2c

**Comment by simoneb** [comment]
Thanks!

**Comment by setchy** [comment]
@rarkins - i was briefly exploring this this morning and it looks like Renovate does support standard-version changelogs

* recreation https://github.com/setchy/renovate-changelog-refactor/pull/9
* release-notes.spec.ts yarg fixture tests

Anything left on this or should we close it?
