### ISSUE TITLE
Reconsider Docker base image

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5191]
Currently Renovate and its associated helper containers (e.g. `renovate/ruby`, `renovate/pipenv`, etc) are based off Ubuntu 18.04. At 29MB in size I find this to be a much better idea than trying to get all the tools we need to work in Ubuntu.

This issue is a placeholder to discuss if that remains the best choice for the next 1-2 years or if there are others worth considering

**Comment by rarkins** [comment]
## Ubuntu 18.04

We use this today, will probably migrate to 20.04 in 2020. As a base image it's only 29MB compressed, which I think is small enough to not be concerned about.

#### Advantages

Probably has the most "help" posts on the internet today, which can be really important when it comes to getting stuff to work.

Most tools have an "Installing on Ubuntu" guide, because of its popularity.

#### Disadvantages

It focuses on stability and LTS which means that you have to work to get the latest releases of everything to install.

**Comment by rarkins** [comment]
## Debian

Ubuntu is based on this.

#### Advantages

Easier than Ubuntu - but not foolproof - to get newer packages to install.

More up to date than Ubuntu.

Lower attack surface?

####

Less support articles available when trying to get things to install (although instructions for Ubuntu may work)

**Comment by rarkins** [comment]
## CentOS

#### Advantages

More common in enterprise?

#### Disadvantages

Moderately larger in size (~60MB) than Ubuntu

**Comment by rarkins** [comment]
## Fedora CoreOS

This just came out of preview on January 17: https://fedoramagazine.org/fedora-coreos-out-of-preview/

#### Advantages

Purpose-built for a containerized world.

More secure?

Native Podman support if we want to use it.

#### Disadvantages

Very new. We might hit a problem that's unsolvable or takes days to solve because we can't find a StackOverflow post about it already.

**Comment by souravdasslg** [comment]
**Alpine**

**Pros :** 
Extremely small memory footprints.
All about security.
Extremely small binary, only 5 MB
Only two vulnerabilities are present in current release.

**cons**
Installing tools are not as easy as ubuntu
