### ISSUE TITLE
Artifact Error: File name: yarn.lock Unable to find image 'undefined:latest' locally

### ISSUE THREAD

**Issue by ErisDS** [renovatebot/renovate#5200]
**What Renovate type are you using?**

Hosted App w/ GitHub 
**Describe the bug**

We're getting the same artifact error as present on this PR: https://github.com/renovatebot/renovate/pull/5198

```
The artifact failure details are included below:

File name: yarn.lock
Unable to find image 'undefined:latest' locally
docker: Error response from daemon: pull access denied for undefined, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Did you see anything helpful in debug logs?**

Sadly I can't see anything in the debug logs 

**To Reproduce**

Example PR here: https://github.com/TryGhost/migrate/pull/55

Trying to rebase doesn't solve the issue 

**Additional context**

Sorry for the minimal bug report but this looks like a platform-level error as I can see the same thing happening on this repo.

**Comment by rarkins** [comment]
Yes this seems to be a platform problem. I’ll take a look

**Comment by rarkins** [comment]
Hi @ErisDS, I rolled back a change that caused this. Could you click the retry checkbox in that PR and confirm that it's properly recreated the second time? Thanks for your help.

**Comment by daniellockyer** [comment]
@rarkins Looks like it's fixed :)

**Comment by ErisDS** [comment]
Thanks so much for the quick fix ❤️
