### ISSUE TITLE
Renovate PR stuck after platform issue (retry checkbox not working)

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#5210]
**What Renovate type are you using?**

GitHub app

**Describe the bug**

The PR neutrinojs/neutrino/pull/1521 was affected by the Renovate platform issue described in #5200. Now that the platform issue is resolved, I have tried clicking the "retry" checkbox in the PR description, however the PR has not been updated, even though I've tried unchecking and re-checking several times.

The "retry" checkbox did work for other PRs affected by the platform incident (eg neutrinojs/neutrino/pull/1520), so not sure what is different about this PR.

**Did you see anything helpful in debug logs?**

```
DEBUG: Found PR #1521(branch="renovate/lint-staged-10.x")
DEBUG: Returning from graphql open PR list(branch="renovate/lint-staged-10.x")
DEBUG: branchExists=true(branch="renovate/lint-staged-10.x")
DEBUG: Branch pr rebase requested: true(branch="renovate/lint-staged-10.x")
DEBUG: Branch has 1 upgrade(s)(branch="renovate/lint-staged-10.x")
DEBUG: Checking if PR has been edited(branch="renovate/lint-staged-10.x")
DEBUG: Found existing branch PR(branch="renovate/lint-staged-10.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/lint-staged-10.x")
DEBUG: No schedule defined(branch="renovate/lint-staged-10.x")
INFO: Skipping branch creation due to unpublishSafe + status checks(branch="renovate/lint-staged-10.x")
```

From https://app.renovatebot.com/dashboard#github/neutrinojs/neutrino/133838832

**To Reproduce**

See PR links above.

**Additional context**

The debug log mentions "Skipping branch creation due to unpublishSafe + status checks", however (a) unpublishSafe is green already for that PR, (b) the other status checks should be somewhat irrelevant, since I've forced a retry.

**Comment by rarkins** [comment]
I agree that it doesn't seem correct to be held up and there must be a logic error there. So you're not waiting, you can do this instead:
- Rename the PR title in any way (e.g. add ` - old`)
- Close the PR
- Delete the source branch

Next time Renovate runs, it should create a replacement from scratch.

**Comment by stefee** [comment]
Renovate seems to be stuck for us as well but there's nothing in the logs to suggest why (no errors as far as I can see). The logs just seem to have gone quiet 15 hours ago. 😴 

https://app.renovatebot.com/dashboard#github/CondeNast/rocket

**Comment by stefee** [comment]
I've tried renaming and closing all of our renovate PRs that were open + the master issue, but no difference.

**Comment by rarkins** [comment]
Hi, there's an issue currently with the GitHub API returning a truncated list of installations, which then prevents Renovate from running over those it thinks are uninstalled. Trying to pinpoint what's going wrong for now. Note: this is unrelated to the original topic of this issue.

**Comment by stefee** [comment]
Thanks @rarkins 🌈

**Comment by stefee** [comment]
Looks like we’re back to normal.
