### ISSUE TITLE
Go mod: Removed //indirect dependencies in a Renovate branch triggers force rebase/push on each subsequent runs.

### ISSUE THREAD

**Issue by glavoie** [renovatebot/renovate#5215]
**Self-hosted/GitHub, version 19.92**

When an update of a Go module removes `//indirect` dependencies, the next run of Renovate on an existing branch/PR may trigger the `go.mod current line doesn't contain dependency` error as the line numbers for dependencies in the `go.mod` file from the existing Renovate branch don't match anymore the line numbers from the source `go.mod` file. 

https://github.com/renovatebot/renovate/blob/9b16e1c7578f8e1453dbe4e48e5443bd72c91b4f/lib/manager/gomod/update.ts#L26

When this occurs, Renovate forces a rebase of the target branch and force updates the PR, every hour in our case (which triggers CI builds, notifications, etc).  

**To reproduce**
Update of the following Go module to the latest version removed a few `//indirect` dependencies. When Renovate processes the updates for other dependencies dependencies in the file from the existing `renovate/external` branch the error is triggered.

` github.com/atlassian/go-sentry-api v0.0.0-20190903054757-be9fc06f9ed7`
to
`github.com/atlassian/go-sentry-api v0.0.0-20200117001222-a9ccec16c98b`

Diff (contains entire go.mod file with diff):
```
diff --git a/go.mod b/go.mod
index 2a15fe9..6b26912 100644
--- a/go.mod
+++ b/go.mod
@@ -3,27 +3,23 @@ module github.com/myorg/myproject
 go 1.13
 
 require (
-       github.com/atlassian/go-sentry-api v0.0.0-20190903054757-be9fc06f9ed7
+       github.com/atlassian/go-sentry-api v0.0.0-20200117001222-a9ccec16c98b
        github.com/bndr/gojenkins v1.0.1
-       github.com/certifi/gocertifi v0.0.0-20190905060710-a5e0173ced67 // indirect
        github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd // indirect
-       github.com/getsentry/raven-go v0.2.0 // indirect
        github.com/golang/protobuf v1.3.2
        github.com/google/go-github/v29 v29.0.2
        github.com/grpc-ecosystem/go-grpc-middleware v1.1.0
        github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
-       github.com/grpc-ecosystem/grpc-gateway v1.12.1
+       github.com/grpc-ecosystem/grpc-gateway v1.12.2
        github.com/joho/godotenv v1.3.0
-       github.com/kr/pretty v0.1.0 // indirect
        github.com/opentracing/opentracing-go v1.1.0
        github.com/prometheus/client_golang v1.3.0
        github.com/sirupsen/logrus v1.4.2
        github.com/stretchr/testify v1.4.0
-       github.com/uber/jaeger-client-go v2.21.1+incompatible
+       github.com/uber/jaeger-client-go v2.22.1+incompatible
        github.com/uber/jaeger-lib v2.2.0+incompatible
        golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
-       google.golang.org/genproto v0.0.0-20191230161307-f3c370f40bfb
+       google.golang.org/genproto v0.0.0-20200122232147-0452cf42e150
        google.golang.org/grpc v1.26.0
        gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 // indirect
-       gopkg.in/yaml.v2 v2.2.4 // indirect
 )
```

**Debug log**
```
15:33:46  DEBUG: Found PR #100 (repository=myorg/myproject, branch=renovate/external)
15:33:46  DEBUG: Returning from graphql open PR list (repository=myorg/myproject, branch=renovate/external)
15:33:46  DEBUG: No branch protection found (repository=myorg/myproject, branch=renovate/external)
15:33:46  DEBUG: Branch does not need rebasing (repository=myorg/myproject, branch=renovate/external)
15:33:46  DEBUG: Using parentBranch: renovate/external (repository=myorg/myproject, branch=renovate/external)
15:33:46  DEBUG: manager.getUpdatedPackageFiles() (repository=myorg/myproject, branch=renovate/external)
15:33:46  DEBUG: gomod.updateDependency: v0.0.0-20190903054757-be9fc06f9ed7 (repository=myorg/myproject, branch=renovate/external)
15:33:46  DEBUG: gomod.updateDependency: v2.22.1 (repository=myorg/myproject, branch=renovate/external)
15:33:46  DEBUG: go.mod current line doesn't contain dependency (repository=myorg/myproject, branch=renovate/external)
15:33:46         "lineToChange": "\tgoogle.golang.org/genproto v0.0.0-20200117163144-32f20d992d24",
15:33:46         "depName": "github.com/uber/jaeger-client-go"
15:33:46   INFO: Rebasing branch after error updating content (repository=myorg/myproject, branch=renovate/external)
```

**Comment by rarkins** [comment]
Good catch. Unfortunately, not an obviously easy one to fix. It seems we'll need to move beyond line-matching and instead search/find the dependency before updating, without introducing any other edge cases.

In better news, assuming this is usually an "empty" force push each run - i.e. identical content - then this was fixed in https://github.com/renovatebot/renovate/releases/tag/19.102.2

After upgrading, you would still see the "go.mod current line doesn't contain dependency" message however later on you'll see the new commit is not actually pushed once it's found to be identical to the existing one.

**Comment by glavoie** [comment]
@rarkins workaround works well. PRs look good after the version bump.

Thank you!
