### ISSUE TITLE
Automerge is not working

### ISSUE THREAD

**Issue by lourenci** [renovatebot/renovate#5256]
**What Renovate type are you using?**

Github app

**Describe the bug**

I've configured the bot to automerge patches and pins, but it doesn't seem to be working. Could someone help me with that? Thank you.

`renovate.json`
```json
{
  "extends": ["config:base"],
  "packageRules": [
    {
      "updateTypes": ["patch", "pin"],
      "automerge": true
    }
  ]
}
```

Patch PR opened by renovatebot:
![image](https://user-images.githubusercontent.com/2339362/73386151-2114ad00-42ad-11ea-8f97-f5cc6b8591b0.png)

![image](https://user-images.githubusercontent.com/2339362/73386161-25d96100-42ad-11ea-8635-b5d42dff38d6.png)

**Comment by JamieMagee** [comment]
`packageRules` works with the `packageNames` or `packagePatterns` option. I think the configuration you want is

```json
"patch": {
  "automerge": true
},
"pin": {
  "automerge": true
}
```

If you need any more help with config, you can open an issue over at https://github.com/renovatebot/config-help.

**Comment by MasaGon** [comment]
Is this sample in document obsoleted? or any other meaning?
https://docs.renovatebot.com/configuration-options/#automerge

```
{
  "packageRules": [
    {
      "updateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    }
  ]
}
```

**Comment by rarkins** [comment]
@MasaGon in most cases, either approach should work (nested inside an object or inside a package rule). I recommend packageRules wherever possible. Feel free to ask in https://github.com/renovatebot/config-help
