### ISSUE TITLE
Create new manager template

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5281]
**What would you like Renovate to be able to do?**

Provide an easy way for contributors to get started releasing a new manager.

**Describe the solution you'd like**

Once #5278, #5279 and #5280 are done, we should have everything a manager needs within `lib/manager/x`. We could therefore create a "template" new manager branch within the repo that won't need regular rebasing as it won't have merge conflicts.

**Describe alternatives you've considered**

We could have a scaffolding command, but that's probably far more than needed.

**Comment by HonkingGoose** [comment]
The issues that we wanted to solve before starting on this are done.

It would be cool to have a template "new manager" branch on GitHub, that contributors can use to start working on new package managers. It could even be something like "color in the numbered spaces" where you have NEW-PACKAGE-MANAGER comments in the code where contributors need to do work.

A scaffolding command would be even cooler... 😄 

What do you want to do with my draft PR #9937?

**Comment by rarkins** [comment]
I think the questionnaire is still good. It triggered my memory that I used to have a questionnaire/template for new managers, and found an example of it (filled out) in a PR: https://raw.githubusercontent.com/nchashch/renovate/3a5876c56cc63cc9364f4f7d9515d8a5b136a14a/lib/manager/cargo/readme.md
