### ISSUE TITLE
Maven dependencies that don't follow version scheme are being pulled in starting with 19.90.3

### ISSUE THREAD

**Issue by klieber** [renovatebot/renovate#5303]
**What Renovate type are you using?**

Renovate Open Source CLI
Bitbucket Server

**Describe the bug**

After upgrading from `19.90.2` to `19.90.3` renovate began creating several pull requests for maven dependencies that didn't follow the normal semver format.  In `19.90.2`, a version like `1.2.17-atlassian-1` would have been ignored but in `19.90.3` it is not longer ignored as you can see in the log output below.  I have also confirmed that this same bug is occurring in the latest version of renovate `19.120.1`.

I tracked the problem down to this pull request: https://github.com/renovatebot/renovate/issues/5091

From reading that it sounds like this might be expected behavior now but I'm not really clear on that or if this is a bug.  I thought renovate should never try to upgrade to a version that has a `compatibility` portion unless you were already using that `compatibility`.  So if my current version was `1.2.17-atlassian-1` then I might expect it to upgrade me to `1.2.18-atlassian-1` but if my current version is `1.2.17` then I should not ever get upgraded to a version that adds the `atlassian-1` portion.

If this isn't a bug then there will need to be a way for me to exclude these dependencies in my config otherwise I will always have these cluttering things up.

**Did you see anything helpful in debug logs?**

```
               {
                 "datasource": "maven",
                 "depName": "log4j:log4j",
                 "currentValue": "1.2.17",
                 "fileReplacePosition": 1710,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "groupName": "log4j.version",
                 "updates": [
                   {
                     "fromVersion": "1.2.17",
                     "toVersion": "1.2.17-atlassian-1",
                     "newValue": "1.2.17-atlassian-1",
                     "newMajor": 1,
                     "newMinor": 2,
                     "updateType": "minor",
                     "isSingleVersion": true
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": "https://bitbucket.org/atlassian/log4j1",
                 "homepage": "http://logging.apache.org/log4j/1.2/"
               },
```

```
DEBUG: processBranch with 1 upgrades (repository=team/project, dependencies=log4j:log4j, branch=feature/renovate/log4j.version)
DEBUG: Setting baseBranch to master (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: latest commit (repository=team/project, branch=feature/renovate/log4j.version)
       "branchName": "master",
       "latestCommitDate": "2020-02-03 21:43:03 +0000"
DEBUG: branchExists(feature/renovate/log4j.version) (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: getBranchPr(feature/renovate/log4j.version) (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: findPr(feature/renovate/log4j.version, "undefined", "open") (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: getPrList() (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: returning cached PR list (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: DID NOT Found PR from branch #feature/renovate/log4j.version (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: branchExists=false (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Branch has 1 upgrade(s) (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: recreateClosed is false (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: findPr(feature/renovate/log4j.version, "chore(deps): upgrade log4j:log4j to v1.2.17-atlassian-1", "!open") (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: getPrList() (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: returning cached PR list (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: DID NOT Found PR from branch #feature/renovate/log4j.version (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: prAlreadyExisted=false (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Checking schedule(at any time, null) (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: No schedule defined (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: branchExists(feature/renovate/log4j.version) (repository=team/project, branch=feature/renovate/log4j.version)
 INFO: Branch needs creating (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Using parentBranch: undefined (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: manager.getUpdatedPackageFiles() (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: getFile(pom.xml, undefined) (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Updating packageFile content (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Updated 1 package files (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: No updated lock files in branch (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: 1 file(s) to commit (repository=team/project, branch=feature/renovate/log4j.version)
 INFO: DRY-RUN: Would commit files to branch feature/renovate/log4j.version (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Checking if we can automerge branch (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: mergeStatus=no automerge (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Ensuring PR (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: There are 0 errors and 0 warnings (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: getBranchPr(feature/renovate/log4j.version) (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: findPr(feature/renovate/log4j.version, "undefined", "open") (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: getPrList() (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: returning cached PR list (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: DID NOT Found PR from branch #feature/renovate/log4j.version (repository=team/project, branch=feature/renovate/log4j.version)
 INFO: Repository URL does not match any known hosts - skipping changelog retrieval (repository=team/project, branch=feature/renovate/log4j.version)
       "manager": "maven",
       "depName": "log4j:log4j",
       "sourceUrl": "https://bitbucket.org/atlassian/log4j1"
DEBUG: getPrBody(This PR contains the following updates:) (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Creating PR (repository=team/project, branch=feature/renovate/log4j.version)
       "prTitle": "chore(deps): upgrade log4j:log4j to v1.2.17-atlassian-1"
 INFO: DRY-RUN: Would create PR: chore(deps): upgrade log4j:log4j to v1.2.17-atlassian-1 (repository=team/project, branch=feature/renovate/log4j.version)
 INFO: DRY-RUN: Would add reviewers to PR #0 (repository=team/project, branch=feature/renovate/log4j.version)
 INFO: Created Dry run PR (repository=team/project, branch=feature/renovate/log4j.version)
DEBUG: Checking #0 for automerge (repository=team/project, branch=feature/renovate/log4j.version)
       "automerge": false,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: No automerge (repository=team/project, branch=feature/renovate/log4j.version)
```

**To Reproduce**

Here is an example repo: https://github.com/klieber/renovate-19.90.3-bug/pull/2

**Additional context**

**Comment by klieber** [comment]
I also just noticed one of my other Github projects shows another example of this:

https://github.com/BerkleyTechnologyServices/restdocs-spec/pull/64

Notice the `maven-enforcer-plugin` would get upgraded from `1.4.1` to `1.4.2.jenkins-1`.

**Comment by rarkins** [comment]
Is this “compatibility” concept a part of the maven versioning standard, or an unofficial convention that some have adopted? We would like to have the ability to support it either way, but it’s an important distinction between whether this is part of the standard or not.

**Comment by klieber** [comment]
I was using that term from your documentation for `versionScheme`: https://docs.renovatebot.com/configuration-options/#versionscheme

> compatibility: this value defines the "build compatibility" of a given dependency. A proposed Renovate update will never change the specified compatibility value. For example, if you are pinning to 1.2.3-linux (and linux is captured as the compatbility value), Renovate will not update you to 1.2.4-osx.

Maven does have a `classifier` property that I think is similar to what is being described there but it's use isn't really restricted to one purpose.  Most common is either for platform specific artifacts or related artifacts (like documentation, source code, etc).

**Comment by klieber** [comment]
In the examples above I believe these are both just "vendor patched" versions of the projects.  My guess is that Atlassian is applying some patch on top of log4j so they are building their own version.  Same with the maven-enforcer-plugin and Jenkins.  Why they are using the same Group ID is beyond me.  Maven central does not allow that but these particular artifacts are coming from [Bintray JCenter](https://bintray.com/bintray/jcenter) which is a lot more loose with the rules.

**Comment by rarkins** [comment]
That `compatibility` term on the docs refers to only the *regex* versionScheme. Maven has no such concept that I’m aware of although even Google has done it once (IIRC it’s the guava package). We can hopefully use the regex scheme for your needs here (will require opt-in configuration) but this is not a bug and default  behaviour should not change if Renovate is behaving in compliance with Maven versioning while the package authors are not.

**Comment by klieber** [comment]
I get what you are saying but then why was this working fine before? I'm just not sure why we wouldn't want to make it work as "compatibility" is described in your docs. If I don't have a text value in the current version then don't add one. That would fit more with the maven standards. Otherwise, how do you resolve which version is newer between `1.2`, `1.2-windows`, `1.2-linux`? This doesn't make sense and I can't really think of any scenario where I've ever seen a project that I would actually want to go from one of those versions to the other. 9 times out of 10 those are unstable releases which is how I think they used to get classified before `19.90.3`.

**Comment by rarkins** [comment]
> I get what you are saying but then why was this working fine before?

Our Maven implementation was non-compliant in the way it was doing comparisons, so we corrected it.

> I'm just not sure why we wouldn't want to make it work as "compatibility" is described in your docs.

Because our default behaviour should always follow the standards, the Maven versioning has no concept of compatibility suffixes. You are either misunderstanding both our docs as well as my clarification here that "That compatibility term on the docs refers to only the regex versionScheme", or being unnecessarily argumentative.

> If I don't have a text value in the current version then don't add one.

No. If Maven defines that a version is newer than you currently have, and is stable, then Renovate will upgrade you to it. e.g. `1.0.0` -> `1.1.0-ga` or `1.2.0-final`.

> Otherwise, how do you resolve which version is newer between `1.2`, `1.2-windows`, `1.2-linux`?

By referring to the Maven specification for how to compare versions. And if in doubt, to the implementation of Maven's ComparableVersion: https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java

> This doesn't make sense and I can't really think of any scenario where I've ever seen a project that I would actually want to go from one of those versions to the other. 9 times out of 10 those are unstable releases which is how I think they used to get classified before `19.90.3`.

We're not going to *default* to non-compliant behaviour. Adding a suffix to a Maven version does not make it unstable. As a Renovate user, you can choose to change the version scheme in use for a specific package though. For example if you just need regular semver behaviour then configure versionScheme=semver for that package (but note that any future release not complying to semver will be ignored).

Please raise an issue within the config-help repo if you have any questions regarding configuring versionScheme. The `maven` versionScheme here needs to remain compliant to the specification.

**Comment by klieber** [comment]
> Because our default behaviour should always follow the standards, the Maven versioning has no concept of compatibility suffixes. You are either misunderstanding both our docs as well as my clarification here that "That compatibility term on the docs refers to only the regex versionScheme", or being unnecessarily argumentative.

I apologize if I came off as argumentative here.  Totally not my intention, Renovate is an awesome project and I really appreciate the work you put into it.  I was really just suggesting that the behavior of how the regex works sounds like it would fit better in most scenarios.

I will try playing around with changing the version scheme to see if I can find something that will work.  Again, truly sorry if I came off wrong above and hope you don't judge me on one comment.  Thanks for your help.

**Comment by philippe-granet** [comment]
Since this PR #5979, you can also filter `allowedVersions` with regular expressions, and it supports negation.  Example:
```json
{
    "managers": ["maven"],
    "allowedVersions": "!/-jboss-|-redhat-|-jenkins-|-patch-|-atlassian-|-NODEP$|-atlassian$|-jbossorg-|-SNAPSHOT$|-PFD-|-jbossas-|-does-not-exist|-tc$|-jahia1$/"
}
```
