### ISSUE TITLE
renovate-bot open a PR with wrong Markdown table rendering result

### ISSUE THREAD

**Issue by ocavue** [renovatebot/renovate#5397]
**What Renovate type are you using?**

Hosted GitHub App.

**Describe the bug**

I use `"rangeStrategy": "widen"` in my renovate configuration. So Renovate will upgrade my dependency from `^24.0.0` to `^24.0.0 || ^25.0.0`. 

In the PR Renovate generated for this upgrade, Renovate wrote something like below in the PR description:

```
| Package | Type | Update | Change |
|---|---|---|---|
| jest | dependencies | major | [`^24.0.0` -> `^24.0.0 || ^25.0.0`](https://url.io/) |
```

This table will be rendered as the HTML below:

| Package | Type | Update | Change |
|---|---|---|---|
| jest | dependencies | major | [`^24.0.0` -> `^24.0.0 || ^25.0.0`](https://url.io/) |

![image](https://user-images.githubusercontent.com/24715727/73953768-db568500-493b-11ea-81bd-7e69ad37da1d.png)

The `|| ^25.0.0` part is gone because of the Markdown table syntax.

**Did you see anything helpful in debug logs?**

N/A

**To Reproduce**

https://github.com/ocavue/jest-puppeteer-istanbul/pull/17#issue-371959702

**Additional context**

This rendering error can be fixed by adding a `\` before `|`.

```
| Package | Type | Update | Change |
|---|---|---|---|
| jest | dependencies | major | [`^24.0.0` -> `^24.0.0 \|\| ^25.0.0`](https://url.io/) |
```

| Package | Type | Update | Change |
|---|---|---|---|
| jest | dependencies | major | [`^24.0.0` -> `^24.0.0 \|\| ^25.0.0`](https://url.io/) |

**Comment by rarkins** [comment]
I wonder if this is as simple as escaping all `|` symbols within table contents, or if that itself would introduce any undesirable outcomes.

**Comment by ocavue** [comment]
If we use HTML instead of Markdown, we don't need escape `|` symbols.

```html
<table>
    <thead>
        <tr>
            <th>Package</th>
            <th>Type</th>
            <th>Update</th>
            <th>Change</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>jest</td>
            <td>dependencies</td>
            <td>major</td>
            <td>
                <a href="https://url.io/" rel="nofollow">
                    <code>^24.0.0</code> -&gt; <code>^24.0.0 || ^25.0.0</code>
                </a>
            </td>
        </tr>
    </tbody>
</table>
```

<table>
    <thead>
        <tr>
            <th>Package</th>
            <th>Type</th>
            <th>Update</th>
            <th>Change</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>jest</td>
            <td>dependencies</td>
            <td>major</td>
            <td>
                <a href="https://url.io/" rel="nofollow">
                    <code>^24.0.0</code> -&gt; <code>^24.0.0 || ^25.0.0</code>
                </a>
            </td>
        </tr>
    </tbody>
</table>


However, we have to escape `>` symbol in this example 😂. So there is always something to escape. 

Based on [GitHub Flavored Markdown Spec](https://github.github.com/gfm/#tables-extension-), there seems no other way.

**Comment by ocavue** [comment]
If we use HTML instead of Markdown, we don't need escape `|` symbols.

```html
<table>
    <thead>
        <tr>
            <th>Package</th>
            <th>Type</th>
            <th>Update</th>
            <th>Change</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>jest</td>
            <td>dependencies</td>
            <td>major</td>
            <td>
                <a href="https://url.io/" rel="nofollow">
                    <code>^24.0.0</code> -&gt; <code>^24.0.0 || ^25.0.0</code>
                </a>
            </td>
        </tr>
    </tbody>
</table>
```

<table>
    <thead>
        <tr>
            <th>Package</th>
            <th>Type</th>
            <th>Update</th>
            <th>Change</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>jest</td>
            <td>dependencies</td>
            <td>major</td>
            <td>
                <a href="https://url.io/" rel="nofollow">
                    <code>^24.0.0</code> -&gt; <code>^24.0.0 || ^25.0.0</code>
                </a>
            </td>
        </tr>
    </tbody>
</table>


However, we have to escape `>` symbol in this example 😂. So there is always something to escape. 

Based on [GitHub Flavored Markdown Spec](https://github.github.com/gfm/#tables-extension-), there seems no other way.

**Comment by rarkins** [comment]
Thanks for checking that out. I prefer we stick with markdown for now anyway (more cross-platform compatible) so we'll work on escaping the `||`.
