### ISSUE TITLE
Unit Tests for gradle-updates-report

### ISSUE THREAD

**Issue by jGleitz** [renovatebot/renovate#5408]
**What would you like Renovate to be able to do?**
[`gradle-updates-report`](https://github.com/renovatebot/renovate/blob/master/lib/manager/gradle/gradle-updates-report.ts) does not seem to be covered by unit tests, which makes it prone to regressions.

**Describe the solution you'd like**
We cover the file with unit tests. Maybe we should wait for #2863 before writing the tests. I don’t know if it will affect the methods the tests would call.

**Describe alternatives you've considered**
Leaving everything as it is and living with the danger of regressions — not a good idea, I think.

**Additional context**
Note that #5398 was not a regression, the type check was always missing, but nobody hit the bug previously. Nevertheless, when fixing the bug, I made some changes that could potentially introduce regressions.

**Comment by rarkins** [comment]
This is a good idea. I don't think #2863 should change any of the commands that are called btw.
