### ISSUE TITLE
Use GitHub Pages for hosting docs.renovatebot.com

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5414]
docs.renovatebot.com is currently hosted using Netlify, using mkdocs and their build. I would like to investigate moving it all onto GitHub Pages.

Two possibilities:
- Create `github.com/renovatebot/renovatebot.github.io` as an "Organization" pages site
- Use branch `gh-pages` within this repo

The problem with the latter is that once a CNAME is used (i.e. docs.renovatebot.com) then it would be https://docs.renovatebot.com/renovate/* and break links. So I think we need to use a dedicated repository for it.

The next challenge is how to build it. Every time there is a commit to master in renovatebot/renovate, we want an Actions script to run that:
- builds the site using `mkdocs`
- commits the newly updated site to the pages repo

It seems we need either a push or pull approach:
- renovatebot/renovate actions script runs after every commit to master, and has permissions (somehow) to push to renovatebot/renovatebot.github.io, OR
- commits to renovatebot/renovate trigger (somehow) an action to run on renovatebot/renovatebot.github.io that then clones renovatebot/renovate and commits locally with its own permissions

**Comment by rarkins** [comment]
This can be used to trigger GitHub Actions from outside the docs repo: https://developer.github.com/v3/repos/#create-a-repository-dispatch-event

**Comment by rarkins** [comment]
Steps:
- [ ] Create dedicated gh pages repository
- [ ] Replicate Netlify build using GitHub Actions
- [ ] Get remote triggers working
- [ ] Move CNAME
- [ ] Consider alternative build approach (e.g. Gatsby + Algolia)

**Comment by ViceIce** [comment]
I can help, only need access to the new repo 😅

**Comment by rarkins** [comment]
> I can help, only need access to the new repo 😅

https://github.com/renovatebot/renovatebot.github.io/invitations

**Comment by ViceIce** [comment]
do we need to stay on mkdocs or can we maybe switch to Jekyll (gh integrated)?

**Comment by rarkins** [comment]
I think mkdocs gives us a lot “for free” that’s hard to replicate. We’d need the urls to stay the same too plus I wouldn’t want to go backwards in terms of look and feel and screen responsiveness

**Comment by ViceIce** [comment]
Remote trigger now nessesarry, case renovate will update git submodules now.

**Comment by viceice** [comment]
Done 🎉
