### ISSUE TITLE
Refactor: Dynamic datasource loading

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5419]
The current static approach is here: https://github.com/renovatebot/renovate/blob/master/lib/datasource/index.ts

**Comment by rarkins** [comment]
There are two challenges:
1. We've used camelCase for the datasource names, so will need to migrate that to match the directory names
2. We use datasource name constants throughout a lot of other code (especially within lib/manager)

The first is fairly easily done using our existing config migration capabilities.

For the second, we would no longer have a constants file, so either:
- We go back to using string literals like 'pypi', or
- Managers refer to datasources

I'm thinking we could enforce a rule that each datasource should export a field called `name` that matches with its directory name. e.g. `export const name = 'pypi'`. Then the python-based managers would refer to `pypi.name` instead of `DATASOURCE_PYPI`.

@ViceIce what do you think?

**Comment by ViceIce** [comment]
I think exporting the name is the way to go. Manager should do that to.

I will try to build a lint rule, so that datasources are not allowed to import code from managers.

**Comment by rarkins** [comment]
OK, and let's also use the approach described in #5421 too

**Comment by rarkins** [comment]
- [ ] Delete the DATASOURCE constants file
- [ ] Have every lib/datasource/x export a `name` field, equal to `x`
- [ ] Have `lib/datasource/index.ts` dynamically load each datasource and validate that its directory name matches with its exported `name`
- [ ] Have other code reference e.g. `pypi.name` instead of `DATASOURCE_PYPI`.
- [ ] Refactor any validation routines to be like the existing manager ones

**Comment by zharinov** [comment]
Too much cycle dependencies because of usage of constants. Let's use string literals matching directory names.

**Comment by rarkins** [comment]
Ok but let’s aim to remove the cyclic dependencies as soon as we can.

**Comment by ViceIce** [comment]
Maybe we should first fix cycles, then this

**Comment by ViceIce** [comment]
I hopefully finish moving datasources tests in a few minutes

**Comment by rarkins** [comment]
Does dynamic datasource loading work (no cyclic problems) if the constants remain as-is?

**Comment by zharinov** [comment]
Created two versions to choose. Unfortunately, usage of module-level `const name` would mean we should declare it in separate file to avoid cycles. Too much boilerplate.

**Comment by ViceIce** [comment]
I would prefer pr without global constants
