### ISSUE TITLE
Many warnings for repository after URI update

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5434]
Since #5428, the Renovate app has seen many warnings like "No repositories defined for org.bitcoinj:bitcoinj-core". Example repo: https://github.com/ArkEcosystem/java-crypto

Was this a regression, or a correct warning that is now being surfaced?

**Comment by rarkins** [comment]
Cc @jGleitz

**Comment by JamieMagee** [comment]
Looks like #5431 is a more complete fix. I'd focus on getting that in.

**Comment by rarkins** [comment]
Looks like there was a spike in autoclosed PRs at the same time, which indicates it's a regression

**Comment by jGleitz** [comment]
I can confirm that the errors for https://github.com/ArkEcosystem/java-crypto don’t happen on my PR (#5431).

**Comment by rarkins** [comment]
@jGleitz your recent help on Gradle is much appreciated! Perhaps the biggest challenge of a polygot tool like Renovate is having contributors whose collective use spans all the supported languages.

**Comment by jGleitz** [comment]
I am glad if I can help. Renovate has proven to be a very useful tool for me, so I am happy if I can make it a little more useful for others as well.
