### ISSUE TITLE
Cache our docker intermediate layer to speedup builds

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#5439]
We should use the caching feature of docker buildx to reuse build layers which do not have changes.

To get started we need
* [x] create new docker hub repo, eg `renovate/testing`
* [x] create new docker hub deploy account, eg `renovatebot`
* [x] add new account and  @ViceIce  with permissions to push/delete
* [x] generate a token for that new account, to be put into github actions

After these steps we can enable build caching in our github workflows

* [ ] add `renovaterelease` account with permissions to push/delete to `renovate/renovate` docker repo
* [ ] replace workflow variable `DOCKER_REPO` with `renovate/renovate`
https://github.com/renovatebot/renovate/blob/a3614f8bbe0b02574662743e8794567407287e5f/.github/workflows/dockerimages.yml#L12-L13

when we want to start to deploy release docker images
* [ ] replace workflow variable `DOCKER_REPO` with `renovate/renovate`
https://github.com/renovatebot/renovate/blob/a3614f8bbe0b02574662743e8794567407287e5f/.github/workflows/release.yml#L10-L11

**Comment by rarkins** [comment]
New docker hub repo: `renovate/cache-test`

New docker hub deploy account: `renovaterelease`

Added both the new account and `kriese` with read-write team permissions to `renovate/cache-test`

Added Docker Hub user `renovaterelease` access token into Actions secret `DOCKER_RENOVATERELEASE_TOKEN`

**Comment by ViceIce** [comment]
refactored the docker workflows. Now we can merge to master and test.

If it is working fine we need more steps to do

**Comment by rarkins** [comment]
@ViceIce can this now be closed?

**Comment by ViceIce** [comment]
no, i will try to use github file cache, so we don't need to push the cache to dockerhub
