### ISSUE TITLE
Release Notes support for Non-GitHub private packages

### ISSUE THREAD

**Issue by Bibz87-CG** [renovatebot/renovate#5452]
**What would you like Renovate to be able to do?**
Renovate's release notes feature is pretty nice for GitHub hosted packages but it doesn't work for Azure DevOps feeds.

**Describe the solution you'd like**
I would like Renovate to be able to add release notes for Azure DevOps private packages.

**Describe alternatives you've considered**
I've tried to simply add a new entry to `hostRules` for our Azure DevOps feed but it seems that the URL's structure doesn't match GitHub and thus gets ignored.

I've also looked at #3323 but I'm not sure it applies to Azure DevOps feeds.

**Additional context**
* We're running Renovate on Azure DevOps using the [Renovate Me](https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me) extension.
* Renovate is able to properly communicate with the private feed, as it is able to see version changes in our packages.
* We're getting a `Invalid github URL found` error message, which seems to come from [this line](https://github.com/renovatebot/renovate/blob/8598a15a3bee62b328bb91ac244d25d6547fa44c/lib/workers/pr/changelog/source-github.ts#L95)

**Comment by rarkins** [comment]
Right now we don't support non-github release notes *at all*. What filename are the release notes in, e.g. `CHANGELOG.md`? And what is the URL that's being returned?

**Comment by Bibz87-CG** [comment]
We have a CHANGELOG.md that matches the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.

This is the URL's format: https://**[organizationName]**@dev.azure.com/**[organizationName]**/**[projectName]**/_git/**[packageName]**

I'm not sure about to tags and releases fallbacks but I assume that retrieving release notes from the CHANGELOG.md file should be fairly straightforward, given Renovate already has access to the repository. Is that correct?

**Comment by rarkins** [comment]
> Is that correct?

Actually not. Renovate normally "accesses" a repository before scanning by cloning it. We don't want to do a full clone of each upstream repo just to access a single file (i.e. CHANGELOG.md, but it can vary). Instead, we'd want to write a changelog module for Azure Devops specifically that retrieves a file list and can fetch individual files via it's API, like the github changelog module does.

Authentication is another complexity with that type of URL, but hopefully not a big one.

**Comment by Bibz87-CG** [comment]
Ah, I see.

Let me know what I can do to help.

**Comment by rarkins** [comment]
> https://**[organizationName]**@dev.azure.com/**[organizationName]**/**[projectName]**/_git/**[packageName]**

Do you know if it's mandatory for that organizationName to appear twice? e.g. is the bit before `@` mandatory?

> Let me know what I can do to help.

Most likely if you really need this then you or a colleague would need to implement it. Otherwise it's unlikely to get added unless someone else with the same need decides to, considering it's very environment-dependent.

We are in the process of adding GitLab changelog support for changelogs soon though. Once that's done, it may be more obvious as to where/how Azure DevOps support would fit in.

**Comment by Bibz87-CG** [comment]
> Do you know if it's mandatory for that organizationName to appear twice? e.g. is the bit before @ mandatory?

The URL I've given is the one Azure DevOps gives for repository cloning. I haven't been able to find any official documentation regarding this but from what I could test the organization name before `@` isn't mandatory for both cloning and using a web browser to navigate the repository.

> We are in the process of adding GitLab changelog support for changelogs soon though. Once that's done, it may be more obvious as to where/how Azure DevOps support would fit in.

It would've been nice to have it if it was easy to implement but since we don't have a lot of private packages and we're aware of each versions' changes, it is not a big problem for us.

Having release notes for all of our dependencies (both public and private) would've streamlined the update process but it's definitely not mandatory.

I'll close the issue and it can be reopened later if/when Renovate wants to add Release Notes support for Azure DevOps feeds.

Thanks!
