### ISSUE TITLE
Configuration Warning for unsupported enabledManagers value

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5453]
**What would you like Renovate to be able to do?**

Raise a Configuration Warning issue if `enabledManagers` includes a value that isn't supported (e.g. `"yarn"`).

**Describe the solution you'd like**

Perform this as part of config validation. Perhaps also in JSON schema?

**Describe alternatives you've considered**

Right now it's invisibly ignored, which isn't easy for a user to detect.

**Additional context**

https://github.com/renovatebot/config-help/issues/523#issuecomment-584814508

**Comment by dmt0** [comment]
Probably good to do it for all the fields that have an enumeration.

**Comment by rarkins** [comment]
> Probably good to do it for all the fields that have an enumeration.

Yes, we aim for that normally

**Comment by HonkingGoose** [comment]
@rarkins Is this issue closed with the merge of PR #9541? Or do we need more work?

**Comment by rarkins** [comment]
Yes, closed!
