### ISSUE TITLE
Environment variables not inherited by Gradle child process

### ISSUE THREAD

**Issue by doorhinge** [renovatebot/renovate#5456]
**What Renovate type are you using?**

Self-hosted (we run it as a Docker container in AWS Fargate).

**Describe the bug**

It appears as of version 19.92.1 that environment variables are not passed into the child Gradle process (this may be the case for other "managers" too). In our case we pass in various environment variables prefixed with `ORG_GRADLE_PROJECT_` which Gradle will read and use in the build.gradle, settings.gradle, etc. files. For example we pass in `ORG_GRADLE_PROJECT_artifactoryUrl`, `ORG_GRADLE_PROJECT_artifactoryUsername`, and `ORG_GRADLE_PROJECT_artifactoryPassword` environment variables which Gradle then translates into variables that are used in our projects' build.gradle files:

```groovy
publishing {
  repositories {
    maven {
      url "$artifactoryUrl/some-repo"
      credentials {
        username = artifactoryUsername
        password = artifactoryPassword
      }
    }
  }
}
```

The Gradle child process launched by Renovate then complains that the `artifactoryUrl` is an unknown property. I think it has something to do with [this addition](https://github.com/renovatebot/renovate/commit/5fd6361c56e51bac3e465f680a079d1648da2dc3#diff-3b0e1705d43a6f5eff4feb348c60db1eR16), since the Gradle "manager" (https://github.com/renovatebot/renovate/blob/master/lib/manager/gradle/index.ts#L71) doesn't seem to pass in any `inheritEnvVars` property to the `ExecOptions` class.

**Did you see anything helpful in debug logs?**

```
Command failed: ./gradlew --init-script renovate-plugin.gradle renovate
FAILURE: Build failed with an exception.
* Where:
Build file '/tmp/renovate/repos/bitbucket-server/SOMEPROJECT/some-repository/build.gradle' line: 34
* What went wrong:
A problem occurred evaluating root project 'plugins'.
> Could not get unknown property 'artifactoryUrl' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 11s
```

**To Reproduce**

Create or use a minimal Gradle project that uses the following `repositories` section in the **build.gradle** file:

```groovy
repositories {
    maven {
        url artifactoryUrl
    }
}
```

Make sure the project is pushed to some remote repository (such as in Github). Now run Renovate 19.92.1 and pass in the following environment variable (the actual value of the variable can really be anything it just has to exist): `ORG_GRADLE_PROJECT_artifactoryUrl=https://jcenter.bintray.com`. Once it pulls down the project it should output an error about `artifactoryUrl` being undefined. If you then run it with Renovate 19.92.0 it works.

**Comment by rarkins** [comment]
Are you running with `trustLevel="high"` in your bot config? By default Renovate does not pass the full set of environment variables to child processes unless you configure trustLevel to be high.

**Comment by doorhinge** [comment]
Yep that seems to have done the trick. Not sure why it worked in 19.92.0 though. Thank you!
