### ISSUE TITLE
Documentation refers to allowedPostUpgradeTasks; should be allowedPostUpgradeCommands

### ISSUE THREAD

**Issue by a7medkamel** [renovatebot/renovate#5461]
19.118.0

Self hosted - CLI

Documentation refers to allowedPostUpgradeTasks; should be allowedPostUpgradeCommands

ref: https://github.com/renovatebot/renovate/pull/5202/files#diff-d7d44abc63e6b4050701c2301b9538eeR1107

**Comment by rarkins** [comment]
https://github.com/renovatebot/renovate/blob/master/docs/usage/configuration-options.md

**Comment by HonkingGoose** [comment]
I'm not sure what the problem is here, as there is not enough information for me to fix this... 😕 
Do we still have a problem with the current docs?

**Comment by rarkins** [comment]
Not sure but anyone finding it in future can feel free to submit a PR directly
