### ISSUE TITLE
Disambiguate modules

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5489]
I would like to see if it's possible to have unique names that do not overlap between our types of modules.

Examples of existing conflicts:
- `docker` is a language and a datasource
- `cargo` and `npm` are both managers as well as datasources

The benefit would be that shorthand config like the following would be less ambiguous:

```json
{
  "docker": {
     "foo": "bar"
  }
}
```

**Comment by rarkins** [comment]
An example of where this has caused a problem has been with `docker`. `circleci` and `ansible` are examples of managers that extract docker dependencies, but also other dependencies too. To apply `docker` settings over everything they extract causes problems. Such problem would be prevented if the settings were applied to the `docker` *datasource* instead.

Something I'm considering is removing `language` configuration altogether and shifting it to the datasource. The main downside is that I think some people have used the `docker` object as a way to disable extraction altogether, e.g.

```json
{
  "docker": {
    "enabled": false
  }
}
```

The above could potentially be detected and massaged to disable `dockerfile`, `docker-compose`, etc.

**Comment by rarkins** [comment]
- [ ] `cargo` manager and datasource. Rename datasource to `crate` or `cargo-crate`?
- [ ] `dart` language and datasource. Rename datasource to `pubdev`? (manager is `pub`)
- [ ] `docker` language and datasource. Rename datasource to `dockerimage`?
- [ ] `git-submodules` manager and datasource. 
- [ ] `github` datasource and platform. Split `github` datasource into `github-tags` and `github-releases`?
- [ ] `gitlab` datasource adn platform. Rename datasource to be `gitlab-tags`?
- [ ] `maven` manager and datasource. 
- [ ] `npm` manager and datasource. 
- [ ] `nuget` manager and datasource.
- [ ] `ruby-version` manager and datasource.
- [ ] `sbt` manager and datasource
- [ ] `terraform` manager and datasource

**Comment by rarkins** [comment]
Another possibility:
- Disambiguate where it makes the user's life easier (e.g I think `github-tags` is more understandable, and maybe `docker-image` also would be
- Leave some with double meaning
- Apply config twice if necessary (e.g. to `maven` manager and `maven` datasource)
- If needing to differentiate, users should use `packageRules` instead of these shortcuts

**Comment by ViceIce** [comment]
`maven` -> `maven-repo` ?
`npm` -> `node-modules` ?

**Comment by ViceIce** [comment]
also somehow related to #4726

**Comment by ViceIce** [comment]
so simply deprecate top-level objects completly and go to `packageRules` would also solve the disambiguations too

**Comment by rarkins** [comment]
> so simply deprecate top-level objects completly and go to `packageRules` would also solve the disambiguations too

It would make things simpler, but I think the current config objects (e.g. `"maven": { ... }"`) are very user-friendly that it's nice to keep them in.

**Comment by JamieMagee** [comment]
What about a similar solution to our constants? Clarify with a prefix depending on type i.e. `datasource-`, `manager-`, `platform-`?

**Comment by rarkins** [comment]
> What about a similar solution to our constants? Clarify with a prefix depending on type i.e. `datasource-`, `manager-`, `platform-`?

I worry it would make things less clean and maybe understandable though. So choices seem like:
- Keep things as-is with some overlaps. In such cases it essentially results in two package rules, and I can't think of many cases where that would be a problem. Worst case: write packageRules directly
- Rename all to have prefixes, e.g. `manager-`
- Use renaming minimum possible to de-conflict
