### ISSUE TITLE
Allow custom commit message for onboarding commit

### ISSUE THREAD

**Issue by biergit** [renovatebot/renovate#5495]
**What would you like Renovate to be able to do?**
Support the onboarding PR process in environments that expect certain commit message patterns.

**Describe the solution you'd like**
Add a configuration option `onboardingCommitMessage` to be able to override the onboarding commit message.

**Describe alternatives you've considered**
Don't use the onboarding PR process. It works but the onboarding PR leaves just a great impression when you try to convince people of using Renovate.

**Additional context**
I have to work with repositories that expect all commit messages to be prefixed with a corresponding JIRA issue id. It would be nice if I could configure the onboarding commit message to adhere to this pattern.

**Comment by rarkins** [comment]
Please edit your issue to use the [feature request template](https://github.com/renovatebot/renovate/issues/new?template=4-Feature_request.md)

**Comment by hazendaz** [comment]
@rarkins Is it possible to get the onboarding event to include at least the prefix that exists for all other pull request commits and pull request message?  This seems like an easy one given the logic is already present for reuse.

**Comment by rarkins** [comment]
I'm happy to accept a PR for configuring the entire onboarding commit message

**Comment by jparnone** [comment]
@rarkins for this update:

- Would it be reasonable to reuse the existing `commitMessagePrefix` config option or would you prefer an onboarding-specific prefix option added?
- In reviewing https://github.com/renovatebot/renovate/blob/master/lib/workers/repository/onboarding/branch/create.ts#L17, it looks like semanticCommits are currently allowed for onboarding commits. With the new ability to specify a prefix, would the prefix be added to the semantic commit message or override the semantic commit message all together?
  - If the former, what would be the preferred order?
    - [Semantic Commit] [My Prefix]: onboarding commit message
    - [My Prefix] [Semantic Commit]: onboarding commit message
- For customizing the onboarding commit message itself, would a new single option of `onboardingCommitMessageBody`, effectively replacing `'Add ' + defaultConfigFile` suffice, automatically prefixing with the semanticCommit or commitPrefix based on the answers to the previous questions?

**Comment by rarkins** [comment]
Have you tried just using `semanticCommitType` ?

**Comment by jparnone** [comment]
@rarkins I did not consider using that because I thought it could lead to some odd looking commits since `semanticCommitScope` could still be applied leading to something like `MYJIRAID-1234(deps): add renovate.json`

I could see value/need in providing a prefix like a JIRA ID while also maintaining semantic commit values, I am just not certain of what the correct ordering would be, or if it should be one or the other. Code wise they both would be relatively straightforward to implement from my current understanding. 

Non-placeholder examples:
- chore(deps) MYJIRAID-1234: Onboarding to Renovate
- MYJIRAID-1234 chore(deps): Onboarding to Renovate

**Comment by rarkins** [comment]
Try `semanticCommitScope=null` with `semanticCommType="MYJIRAID-1234"` ?

**Comment by jparnone** [comment]
@rarkins I think I may not been clear initially. My questions were geared towards if I were to make a PR to customize the full message, how you want would those items handled -not how could I accomplish this with the current available options.  Sorry about that!
