### ISSUE TITLE
Renovate does not learn update from wagtail 2.7.1 to 2.8

### ISSUE THREAD

**Issue by cfra** [renovatebot/renovate#5506]
**What Renovate type are you using?**

We are using the Renovate GitHub app.

**Describe the bug**

We have a project using Poetry to manage Python dependencies.

We have Wagtail as a dependency.

The project currently contains Wagtail 2.7.1, but 2.8 is already released on PyPI.

Renovate should open an update pr, but it doesn't.

**Did you see anything helpful in debug logs?**

[Here](https://app.renovatebot.com/dashboard#github/cfra/poetry-problem/142863713), it seems like Renovate doesn't see the version 2.8 which was released on PyPI.

**To Reproduce**

See https://github.com/cfra/poetry-problem

**Comment by zharinov** [comment]
Should work after mentioned PR: https://github.com/zharinov/poetry-problem/pull/1

**Comment by keimlink** [comment]
@zharinov Thank you for fixing this! 🙏 Works now for our Python pre-release dependencies. 💯
