### ISSUE TITLE
Bitbucket Cloud comments should not reference checkboxes

### ISSUE THREAD

**Issue by tmack8001** [renovatebot/renovate#5510]
**What Renovate type are you using?**

self-hosted

**Describe the bug**

In Bitbucket Cloud PRs, the "PR has been edited" comment is incorrectly referencing a "checkbox in body/description". This isn't a supported dynamic feature in the body/description of the Bitbucket Cloud PRs being generated and thus isn't correct messaging to the user on how to resolve this state.

Example "PR has been edited" comment:

```
PR has been edited
This PR has received other commits, so Renovate will stop updating it to avoid conflicts or other problems. If you wish to abandon your changes and have Renovate start over you may click the "rebase" checkbox in the PR body/description.
```

**Did you see anything helpful in debug logs?**

No, as the comment is created successfully, just referencing a feature that isn't ported to Bitbucket Cloud yet.

**To Reproduce**

Create PR on Bitbucket Cloud
Manually modify a file on that branch

**Additional context**

**Comment by rarkins** [comment]
We should aim to fix this using the `getPrBody()` function

**Comment by setchy** [comment]
@rarkins - this too can be closed as it was resolved via https://github.com/renovatebot/renovate/pull/20482
