### ISSUE TITLE
Support updating Gradle dependency lockfiles

### ISSUE THREAD

**Issue by kamatama41** [renovatebot/renovate#5534]
**What would you like Renovate to be able to do?**
Gradle supports locking dependencies [since 4.8](https://docs.gradle.org/4.8/release-notes.html#locking-of-dynamic-dependencies) like `yarn.lock`. So I'd like Renovate to update them in a dependency update.

Currently my Gradle project uses it with Renovate but CI fails with inconsistency between lock files and `build.gradle`

**Describe the solution you'd like**
Renovate automatically detects the `lockfile`s then update them by the following command after update `build.gradle`

```
(gradle or ./gradlew) dependencies --write-locks
```
(then commit updated files, of course)

ref: https://docs.gradle.org/current/userguide/dependency_locking.html#generating_and_updating_dependency_locks

**Describe alternatives you've considered**
Provide a `postUpdateOptions` to update lockfiles like `gomodtidy`

**Additional context**
It might be better to use [`gradle classes --update-locks`](https://docs.gradle.org/current/userguide/dependency_locking.html#selectively_updating_lock_state_entries) to update specific module. But I always use the --write-locks option and I don't understand the difference accurately.

**Comment by rarkins** [comment]
This is a great idea. Can you create a reference repository on GitHub using Gradle lock files that can be used to test against? e.g. should ideally require at least a few PRs too.

**Comment by kamatama41** [comment]
Got it, I've created https://github.com/kamatama41/gradle-dependency-lock-example for the purpose, and will add a Gradle project which uses dependency locking.

**Comment by kamatama41** [comment]
I've set up the repository. It has a Gradle project with dependency locking and Renovate is configured.

For example, CI of [the Renovate's PR](https://github.com/kamatama41/gradle-dependency-lock-example/pull/3) failed with the following error message

```
   > Could not resolve com.sparkjava:spark-core:2.9.1.
     Required by:
         project :
      > Cannot find a version of 'com.sparkjava:spark-core' that satisfies the version constraints:
           Dependency path ':gradle-dependency-lock-example:unspecified' --> 'com.sparkjava:spark-core:2.9.1'
           Constraint path ':gradle-dependency-lock-example:unspecified' --> 'com.sparkjava:spark-core:{strictly 2.7.2}' because of the following reason: dependency was locked to version '2.7.2'


   > Could not resolve com.sparkjava:spark-core:{strictly 2.7.2}.
     Required by:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
         project :
      > Cannot find a version of 'com.sparkjava:spark-core' that satisfies the version constraints:
           Dependency path ':gradle-dependency-lock-example:unspecified' --> 'com.sparkjava:spark-core:2.9.1'
           Constraint path ':gradle-dependency-lock-example:unspecified' --> 'com.sparkjava:spark-core:{strictly 2.7.2}' because of the following reason: dependency was locked to version '2.7.2'
```

ref: https://github.com/kamatama41/gradle-dependency-lock-example/runs/461517525

**Comment by kamatama41** [comment]
FYI: As a workaround, I created a GitHub Action to correct the lockfiles and apply it to Renovate PRs. https://github.com/kamatama41/gradle-lockfiles-update-action 

Here is an example of Renovate PR that the Action is applied. I'd like lockfiles to be updated like this. https://github.com/kamatama41/nsocket/pull/57/files

**Comment by ghilainm** [comment]
@rarkins Seems like a nice feature, do you have any plan to work on this?

I could maybe help on the topic maybe, but no clue where to start with.

**Comment by rarkins** [comment]
Next steps would be to confirm which commands work. For example:
- Take a repo with a gradle lock file
- Get Renovate to generate a PR, updating only the build.gradle and not lock file
- Use the `renovate/gradle` image to verify the command works

```
docker run --rm -v `pwd`:`pwd` -w `pwd` renovate/gradle ./gradlew dependencies --write-locks
```

**Comment by achimgrimm** [comment]
Hi @rarkins,

is there any update on this feature? 

Regards

**Comment by rarkins** [comment]
No. See my previous comment about next steps

**Comment by achimgrimm** [comment]
I ran the docker image on my project and the output looks good.
But I did not find the lock file on my local project afterwards. Is that correct?

If I run the command `./gradlew dependencies --write-locks` without the docker images, the lock file is generated.

**Comment by rarkins** [comment]
We need to work out which command can be run with our existing Docker image. A "works on my machine" solution doesn't get us as far as we need.

**Comment by achimgrimm** [comment]
Is this something I can help you with? The command itself is a regular gradle command. see https://docs.gradle.org/current/userguide/dependency_locking.html#generating_and_updating_dependency_locks

**Comment by viceice** [comment]
Do the steps are
- implement update artifacts function
- detect lockfiles
- update lockfiles if they are found

**Comment by viceice** [comment]
I would also only support this with Gradle wrapper, so we can use the java docker images. And don't need to install Gradle globally.

**Comment by rarkins** [comment]
We first need someone to verify the exact commands to run and that it works. @achimgrimm seemed to indicate that the lock file was missing when he ran it via Docker.

**Comment by achimgrimm** [comment]
I am wondering if I could generate/update a lock file with a post upgrade command like this.
```
{
  "postUpgradeTasks": {
    "commands": [
      "./gradlew dependencies --write-locks"
    ],
    "fileFilters": [
      "gradle.lockfile"
    ]
  }
}
```

I will give it a go today and see if it works.

**Comment by rarkins** [comment]
Only if self-hosted, and you're running with the full image or have Java preinstalled

**Comment by michel-zimmer** [comment]
Hi, I'm wondering how Renovate updates Gradle itself, then.
I was under the assumption that something along the lines of `gradle wrapper --gradle-version 7.3.3` is called by Renovate.
Does that also only work under the conditions mentioned above?
Or is Gradle updated manually by editing the files?

**Comment by viceice** [comment]
We use `gradlew wrapper ...`. currently we fallback to global gradle if no wrapper is found.

In future we like to skip install global gradle to speedup runs.

**Comment by viceice** [comment]
On app we use docker mode.

**Comment by subesokun** [comment]
fyi, following worked for me

renovate.json
```json
{
  "postUpgradeTasks": {
    "commands": [
      "./gradlew dependencies --write-locks"
    ],
    "fileFilters": [
      "gradle.lockfile"
    ],
    "executionMode": "branch"
  }
}
```

config.js (globally for Renovate)
```javascript
module.exports = {
  customEnvVariables: {
    CI_JOB_TOKEN: process.env.CI_JOB_TOKEN  // Required in our case to pull private packages during the dependency update
  },
  allowPostUpgradeCommandTemplating: true,
  allowedPostUpgradeCommands: ['^.\/gradlew dependencies --write-locks$'],
};
```
and make sure that you've checked in your Gradle wrapper too (`./gradlew`).
