### ISSUE TITLE
Handle mismatches between maven-metadata.xml and the directories

### ISSUE THREAD

**Issue by hisener** [renovatebot/renovate#5538]
**What Renovate type are you using?**

Renovate Open Source CLI (using the docker image `renovate/renovate:19.141.0`)

**Describe the bug**

When a registry (nexus repository in my case) has a reference to a non-existing artifact version (`1.0-SNAPSHOT`) in `maven-metadata.xml`. Renovate tries to upgrade to that version even though the artifact doesn't exist.

```
<metadata modelVersion="1.1.0">
    <groupId>com.google.auto.service</groupId>
    <artifactId>auto-service</artifactId>
    <version>1.0-rc6</version>
    <versioning>
        <latest>1.0-SNAPSHOT</latest>
        <release>1.0-rc6</release>
        <versions>
            <version>HEAD-SNAPSHOT</version>
            <version>1.0-rc1</version>
            <version>1.0-rc2</version>
            <version>1.0-rc3</version>
            <version>1.0-rc4</version>
            <version>1.0-rc5</version>
            <version>1.0-rc6</version>
            <version>1.0-SNAPSHOT</version>
        </versions>
        <lastUpdated>20190717034937</lastUpdated>
    </versioning>
</metadata>
```

The local `.m2` repository:

```
$ pwd
/Users/halil/.m2/repository/com/google/auto/service/auto-service
$ ll
total 24
drwxr-xr-x  4 halil  staff   128B Nov 28  2018 1.0-rc1
drwxr-xr-x  4 halil  staff   128B Nov 28  2018 1.0-rc2
drwxr-xr-x  7 halil  staff   224B Jan  1 14:31 1.0-rc3
drwxr-xr-x  9 halil  staff   288B Dec  2  2018 1.0-rc4
drwxr-xr-x  6 halil  staff   192B Apr 30  2019 1.0-rc5
drwxr-xr-x  6 halil  staff   192B Aug 23 13:39 1.0-rc6
-rw-r--r--  1 halil  staff   645B Feb 17 14:21 maven-metadata.xml
-rw-r--r--  1 halil  staff    40B Feb 17 14:21 maven-metadata.xml.sha1
-rw-r--r--  1 halil  staff   204B Feb 17 14:21 resolver-status.properties
```

It doesn't exist on Nexus either.

The PR has been created by Renovate: https://github.com/hisener/maven6/pull/4

**Did you see anything helpful in debug logs?**

N/A

**To Reproduce**

It should be possible to reproduce by creating a non-existing entry in `maven-metadata.xml`.

**Additional context**

Please also refer to the discussion at https://github.com/renovatebot/config-help/issues/529.

**Comment by rarkins** [comment]
To sanity check the metadata xml versions, what do we need to do?

- Validate the directory name-only? or
- Validate directory + file name

Although this will add requests to do, I think we can do it efficiently by:
- Using a `HEAD` query merely to check it exists
- For each dependency, storing a list of yes/no results for each version and then caching it aggressively (e.g. for a day). That means they only need to be requeried if the list of versions in the metadata xml changes.

**Comment by hisener** [comment]
> To sanity check the metadata xml versions, what do we need to do?
>
> * Validate the directory name-only? or
> * Validate directory + file name

I think the latter would be better. I am not sure it can happen on registries but I have seen empty directory and a directory without `.jar` file (only `.pom` file) on a local maven repository.

**Comment by rarkins** [comment]
In that case is the `.jar` file deterministically named? e.g. `${url}/${version}/${artifact-id}-${version}.jar`?

**Comment by hisener** [comment]
Yes, I think so. Found this question, https://stackoverflow.com/a/13371622/3528626. 
According to https://cwiki.apache.org/confluence/display/MAVENOLD/Repository+Layout+-+Final

The layout enforces to use the following:
```
/$groupId[0]/../${groupId[n]/$artifactId/$version/$artifactId-$version.$extension
/$groupId[0]/../$groupId[n]/$artifactId/$version/$artifactId-$version-$classifier.$extension
```

**Comment by rarkins** [comment]
Thanks. 

I think we can go with this new logic:

- Check cache for existing result. If found, return it.
- Otherwise, query metadata xml
- If found, query cache for artifact results
- If no artifact cache, or it doesn't include any of the metadata versions, then query each artifact URL with a HEAD request to see if it exists. Cache the results
- Use the artifact results to filter the metadata results, and then cache and return that as the final result
