### ISSUE TITLE
Test coverage: complete datasource

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5554]
`yarn jest datasource` should result in 100% coverage of `lib/datasource`. Today it does not, meaning that we rely on code in other sections (e.g. workers) to fully test it. We can keep the other tests, but we should add to what we have so that `datasource` can be tested completely on its own.

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/75604613-d4560900-5ada-11ea-85fa-5e158567398b.png)

To reproduce:
- Run `yarn jest datasource` locally
- Open the `coverage/index.html` file

**Comment by viceice** [comment]
Also we need to add test for branch coverage. There are a lot of missing else tests.

**Comment by rarkins** [comment]
Maybe create a new issue for that?
