### ISSUE TITLE
Autodetect GitLab fast-forward branch controls

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5565]
**What would you like Renovate to be able to do?**

Detect this setting:
![image](https://user-images.githubusercontent.com/6311784/75160871-1cf87580-571b-11ea-84a8-35e1e281d08d.png)

And if `rebaseWhen=auto` then change this to `rebaseWhen=behind-base-branch`, like we do with GitHub's branch protection.

**Describe the solution you'd like**

Exactly like the same in GitHub

**Describe alternatives you've considered**

Right now attempted automerges of Renovate MRs that are behind base branch fail with a 406 error.

**Additional context**

https://github.com/renovatebot/config-help/issues/549

**Comment by viceice** [comment]
[project-merge-method](https://docs.gitlab.com/ee/api/projects.html#project-merge-method)
