### ISSUE TITLE
Release notes ordering issue

### ISSUE THREAD

**Issue by wyardley** [renovatebot/renovate#5574]
**What Renovate type are you using?**
pro (self-hosted) - 18.x

**Describe the bug**
With internal (and now some external dependencies), sometimes we'll see release notes repeated, e.g., if there are two releases, the release notes for the most recent are repeated twice under each version.

This one doesn't seem to have GH releases, so maybe it's weirdness with NPM itself?
Compare this:
![image](https://user-images.githubusercontent.com/10714426/75271810-ab1f3b00-57b1-11ea-88b9-68f14044e9a7.png)
with
https://github.com/googleapis/nodejs-pubsub/blob/master/CHANGELOG.md
and
https://www.npmjs.com/package/@google-cloud/pubsub

**Did you see anything helpful in debug logs?**
n/a

**To Reproduce**

See repro:
- Old entries for typescript-eslint/typescript-eslint: viceice-tests/renovate-changelog1#1
- Duplicate entries for traefik: viceice-tests/renovate-changelog1#2

**Additional context**
Will try to track down an example of the similar / same issue with an internal repo.

**Comment by rarkins** [comment]
This might be resolved by #5807. If you can reproduce it in a public repo then I can test it with the CLI to confirm.

**Comment by ViralRuparel** [comment]
> This might be resolved by #5807. If you can reproduce it in a public repo then I can test it with the CLI to confirm.

![image](https://user-images.githubusercontent.com/21654339/77893790-056c5980-7292-11ea-823c-f2b68699127a.png)
Fixed!

**Comment by viceice** [comment]
Seeing more wron changelogs, repro: [viceice-tests/renovate-changelog1](https://github.com/viceice-tests/renovate-changelog1)

- Old entries for typescript-eslint/typescript-eslint: viceice-tests/renovate-changelog1#1
- Duplicate entries for traefik: viceice-tests/renovate-changelog1#2

**Comment by viceice** [comment]
It's manager independend

**Comment by viceice** [comment]
Missing changelog at all here: renovatebot/github-action#538

Changelog is here: https://github.com/wagoid/commitlint-github-action/blob/master/CHANGELOG.md
Releases are empty.
