### ISSUE TITLE
upgrade curl/wget dependencies (.travis.yml) 

### ISSUE THREAD

**Issue by adamdecaf** [renovatebot/renovate#5575]
**What would you like Renovate to be able to do?**
It would be fantastic if renovatebot could upgrade curl/wget commands where a version is identified. I've found this happens in HTML (`<script>` tag updates). 

**Describe the solution you'd like**
A pull request like [the following](https://github.com/moov-io/moov-io/pull/39), but for curl/wget commands. 

An example manual PR I've created is this: https://github.com/moov-io/paygate/pull/382 which does contain the version twice, but other examples in that `.travis.yml` file contain the version once.

**Comment by adamdecaf** [comment]
I have no idea what's involved with renovatebot to do this, but I'd help out with some guidance.

**Comment by rarkins** [comment]
Hi @adamdecaf, thanks for suggesting this use case. I don't think we'd add a *manager* specifically for this, but instead allow you to configure it using a generic regex-based approach described in #1938. I'll close this one and please subscribe there for updates of when it's implemented.
