### ISSUE TITLE
Allow `endpoint` to be overridden for Bitbucket Cloud

### ISSUE THREAD

**Issue by bengummer** [renovatebot/renovate#5585]
**What would you like Renovate to be able to do?**
I work on the Bitbucket Cloud team and we're trying to use Renovate for some of our repos, which live on our internal instance of Bitbucket Cloud so the base URL is different to `api.bitbucket.org`. We have tried configuring Renovate with our custom `endpoint` but are getting the error `Bitbucket Cloud endpoint can only be https://api.bitbucket.org/`.

**Describe the solution you'd like**
Can the [restriction](https://github.com/renovatebot/renovate/blob/ecd981bf6403723868f37d96b380a8fcdde864a2/lib/platform/bitbucket/index.ts#L53) that produces the `Bitbucket Cloud endpoint can only be https://api.bitbucket.org/` init error message can be relaxed/removed? I'm happy to create a PR if so.

**Describe alternatives you've considered**

**Additional context**

**Comment by rarkins** [comment]
@bengummer please go ahead with a PR. The main idea was to try to catch people making the mistake of configuring platform `bitbucket` thinking it was Bitbucket Server. Could be good to add an explicit log early along the lines of "Running in Bitbucket Cloud mode on custom endpoint".

**Comment by rarkins** [comment]
By the way, I've been interested to add bitbucket.org as a supported host in the free hosted app I run at WhiteSource. If you'd like to discuss that any time, please drop me an email.

**Comment by bengummer** [comment]
Awesome thanks @rarkins i'll put up a PR - and will fwd your message re: WhiteSource to a PM on the Bitbucket Cloud team.

**Comment by bengummer** [comment]
@rarkins i've got a PR up at #5587 - happy to make any changes you suggest

**Comment by bengummer** [comment]
Got a PR up at #5587 which i think is good to go if anyone has some time to review & merge 👍
