### ISSUE TITLE
Automate `hostType` insertion for datasource requests

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5596]
`hostType` is an important field for the application of `hostRules`. Currently, each datasource implementation must remember to add the field to the `got` options it sends. Perhaps we could abstract this away by having a common `got` wrapper that takes the datasource's `id` as a parameter and extends the util/got implementation to automatically add the `hostType` to options on every request it receives.

**Comment by viceice** [comment]
Sounds good

**Comment by viceice** [comment]
Forgotten. 😅
