### ISSUE TITLE
Add and enforce `readme.md` for all managers

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5597]
This readme is then used to build docs.renovatebot.com too. An example of a manager which has a readme.md: https://docs.renovatebot.com/modules/manager/nuget/

The enforcement can be part of `loadModules`

**Comment by viceice** [comment]
I think we should use a test case for that. Because the markdown files are not there at runtime.

**Comment by rarkins** [comment]
Good point. I maybe did that for versioning already and forgot :)
