### ISSUE TITLE
"No repositories defined for.." warnings

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5609]
**What Renovate type are you using?**

Log messages come from the hosted app

**Describe the bug**

**Did you see anything helpful in debug logs?**

Lots like this:

```
    "msg": "No repositories defined for org.jetbrains.kotlin:kotlin-stdlib",
```

**To Reproduce**

Fork https://github.com/adrw/misk-web and run Renovate against it

**Comment by zharinov** [comment]
We can get rid of `warn` using default `registryUrl`. But for this particular repo Renovate produces Gradle json report containing Kotlin-specific packages only, without actual dependencies from `packageFile` content 🤷‍♀️
