### ISSUE TITLE
Dependency dashboard issue out of sync, listing PRs as open when they are not

### ISSUE THREAD

**Issue by ChristianMurphy** [renovatebot/renovate#5668]
**What Renovate type are you using?**

Hosted renovate, with GitHub on https://github.com/Jasig/uPortal-start

**Describe the bug**

The dependency dashboard issue lists several PRs as open (unlinked) when they have not been opened.

https://github.com/Jasig/uPortal-start/issues/440

---
screenshot:

![Screenshot_2020-03-08 Update Dependencies (Renovate Bot) · Issue #440 · Jasig uPortal-start](https://user-images.githubusercontent.com/3107513/76170392-c473a000-613e-11ea-8788-7edbaccad55a.png)

---

**Did you see anything helpful in debug logs?**

https://app.renovatebot.com/dashboard#github/Jasig/uPortal-start/149872446

**To Reproduce**

https://github.com/Jasig/uPortal-start
this _may_ be related to rate limiting, previously they were in the rate limited section, they were manually checked, now have been caught in an intermediate state for several builds:
* https://app.renovatebot.com/dashboard#github/Jasig/uPortal-start/149832043
* https://app.renovatebot.com/dashboard#github/Jasig/uPortal-start/149872310
* https://app.renovatebot.com/dashboard#github/Jasig/uPortal-start/149872445
* https://app.renovatebot.com/dashboard#github/Jasig/uPortal-start/149872446

**Additional context**

Possibly related to https://github.com/renovatebot/renovate/issues/4803

**Comment by rarkins** [comment]
Can you tell me for the ones that aren't linked, do they:
- all exist?
- some exist but some don't?
- none exist?

**Comment by ChristianMurphy** [comment]
none exist

**Comment by rarkins** [comment]
Thanks. I would like to see if it resets to correct on the next run too, i.e is it temporary or permanent.

**Comment by ChristianMurphy** [comment]
Next run appears to have finished, https://app.renovatebot.com/dashboard#github/Jasig/uPortal-start/149878694
PRs and master issue are the same after.

**Comment by rarkins** [comment]
Seems like they're stuck in an "intermediate state" as you say. Converting all our return values/result values into TypeScript enums at the moment, after that we should hopefully catch the problem.

**Comment by ChristianMurphy** [comment]
> Converting all our return values/result values into TypeScript enums at the moment, after that we should hopefully catch the problem.

:+1: 
linking related PR https://github.com/renovatebot/renovate/pull/5664

**Comment by rarkins** [comment]
I'm working on a branch that should solve this once and forever, but so far it's like pulling on a thread that keeps going - changes needed in a lot of code.

**Comment by rarkins** [comment]
This should be resolved in renovate@25.37.1
