### ISSUE TITLE
Composer lockfile updates hanging

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5671]
**What Renovate type are you using?**

App

**Describe the bug**

Composer updates never return.

**Did you see anything helpful in debug logs?**

From testing manually:

```
❯ docker run --rm -v `pwd`:`pwd` -w `pwd` renovate/composer bash -l -c "composer update laravel/framework --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader"
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

**To Reproduce**

1. Git clone https://github.com/geea-develop/heroku-laravel-mongodb
2. Manually update `laravel/framework` in `composer.json` to `5.8.37`
3. Run `docker run --rm -v `pwd`:`pwd` -w `pwd` renovate/composer bash -l -c "composer update laravel/framework --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader"`

**Comment by rarkins** [comment]
Seems like it's a Composer problem with no solution: https://github.com/composer/composer/issues/7665

**Comment by zharinov** [comment]
So do we need mechanism for timeout process termination?

**Comment by rarkins** [comment]
Yes. A general one seems essential now but I’m working on pushing through a Composer-specific commit today
