### ISSUE TITLE
repository-changed error

### ISSUE THREAD

**Issue by simoneb** [renovatebot/renovate#5683]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Repository started
{
  "renovateVersion": "19.167.0"
}
INFO: Repository has changed during renovation - aborting
INFO: Repository finished
```

### What would you like to do?

I'm seeing all the recent jobs in a repository showing this output. I am noticing that the master issue in that repository is out of date and doesn't match the PRs that are open, for instance, but I'm not sure if it's related. The log output suggests that Renovate is not completing successfully.

![image](https://user-images.githubusercontent.com/20181/76303981-dbdb9600-62c2-11ea-89cc-83865762b981.png)

**Comment by rarkins** [comment]
Looks like we're not sending the `state` field in the POST body.

**Comment by rarkins** [comment]
Patch in progress

**Comment by rarkins** [comment]
I'll let you know once the release is live in the app, so you can confirm the fix. I was able to reproduce and verify locally though.

**Comment by simoneb** [comment]
Awesome, thanks. Once it is, is there any action I need to do on the repo(s), which are affected?

**Comment by rarkins** [comment]
I would expect they'd "just work" the next time they are checked
