### ISSUE TITLE
Go modules.txt files are breaking on missing `## explicit`

### ISSUE THREAD

**Issue by jmhodges** [renovatebot/renovate#5705]
When renovatebot updates a Go go.mod file (like this PR https://github.com/jmhodges/howsmyssl/pull/314/files ), it's removing the "## explicit" lines in `modules.txt`. That's breaking the build when are run with `go install -mod=vendor` is run with Go 1.14.

See https://travis-ci.org/github/jmhodges/howsmyssl/builds/660876132 (exact problem in the details below)

<details>
============go: inconsistent vendoring in /go/src/github.com/jmhodges/[secure]:
	cloud.google.com/go@v0.49.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	cloud.google.com/go/logging@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/dgryski/go-sip13@v0.0.0-20190329191031-25c5027a8c7b: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/dgryski/go-topk@v0.0.0-20191119021947-593b4f2374c9: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/crypto@v0.0.0-20200221231518-2aa609cf4a9d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/net@v0.0.0-20200226121028-0de0cce0169b: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/oauth2@v0.0.0-20200107190931-bf48bf16ab8d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	google.golang.org/api@v0.20.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	google.golang.org/grpc@v1.28.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
</details>

And here was the build of a fix I pushed: https://travis-ci.org/github/jmhodges/howsmyssl/builds/661429642

**Comment by rarkins** [comment]
Renovate does not touch that `modules.txt` file directly - it is only updated by `go` itself when Renovate calls `go mod vendor`. Is it possibly caused by a mismatch in `go` versions, e.g. if behavior changed between versions?

**Comment by StinkyLord123** [comment]
Yes there's an ## explicit in modules txt, started in version go "1.14"
dos anyone know what the ##explicit is for?

**Comment by rarkins** [comment]
I'm updating our Go image right now so within an hour or two the app should be running all `go` commands with 1.14. Only concern is if there's any backwards-incompatibility, so we should switch to supporting dynamic versioning.

**Comment by opdude** [comment]
@rarkins It seems we still have this issue, did you manage to upgrade to 1.14?

**Comment by viceice** [comment]
latest go should be 1.14.2 : https://hub.docker.com/r/renovate/go/tags

**Comment by opdude** [comment]
Currently, I am using the `renovate/renovate:19`images which still has 1.13.4

**Comment by viceice** [comment]
ok, you are using the full image. update should come after renovatebot/docker-renovate#9

**Comment by HonkingGoose** [comment]
@rarkins @viceice What's the status of this issue? Did we manage to improve any of this with newer releases?

Also what priority level do we want for this?
