### ISSUE TITLE
Renovate requires force push capabilities

### ISSUE THREAD

**Issue by biergit** [renovatebot/renovate#5718]
**What Renovate type are you using?**

Selfhosted Bitbucket Server

**Describe the bug**

Renovate created a first PR successfully for a new version of dependency `x` but it is not merged before the next version of the same dependency `x` happens.

**Did you see anything helpful in debug logs?**

```
...
DEBUG: Branch does not need rebasing ...
...
INFO: Need to update package file so will rebase first ...
...
DEBUG: Updated 1 package files ...
DEBUG: No updated lock files in branch ...
DEBUG: 1 file(s) to commit ...
...
DEBUG: Error commiting files ...
...
remote: Rewriting history is not allowed for branch ...
```

**To Reproduce**

Sorry don't have a public Bitbucket repo / account.

**Comment by biergit** [comment]
Ok, it seems it is intended behavior as I've found in this doc: https://github.com/renovatebot/renovate/blob/master/docs/development/branches-commits.md

I definitely need a workaround for this as allowing force pushes is a no go in my environment.

**Comment by rarkins** [comment]
Force pushing is essential to Renovate's workflow, unfortunately that means there is no workaround available.

Any time Renovate needs to update a branch, it performs a force-push. This includes:
- A new version is available, or
- The existing branch has become conflicted, or
- Renovate has been configured to keep all its branches up to date with master

The conflicted case in particular would be extremely difficult to manage without force pushing, and all other use cases would be much harder and more complicated.

**Comment by viceice** [comment]
@biergit you should disable history rewrite for renovate branches only.

**Comment by biergit** [comment]
Thanks guys I'll try to convince the right people to allow this :)

**Comment by hazendaz** [comment]
This should be reopened as the bitbucket isn't is not a pure force push issue.  I'm opening a PR that should address this and will note that in the PR.
