### ISSUE TITLE
Current regexManager docu is wrong

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#5726]
The [current documentation](
https://docs.renovatebot.com/modules/manager/regex/#advanced-capture) for the generic regexManager does not work.

```Dockerfile
ENV POETRY_VERSION=1.0.0 # github-releases/python-poetry/poetry
```

`Syntax error - can't find = in "#". Must be of the form: name=value`

Workaround is to provide separate manager for each `ENV`

**Comment by rarkins** [comment]
The examples I used were the ones I tested with during development. We should definitely not need one manager per env

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/76734269-de2a6e00-6762-11ea-9190-5e5c6cd284fa.png)

VSCode is complaining too, does normal docker build works?

**Comment by rarkins** [comment]
oh, hmm - now I see what you mean, sorry. Can't recall if I ran `docker build` :o)

**Comment by rarkins** [comment]
https://stackoverflow.com/a/51021890/3005034 relevant?

**Comment by rarkins** [comment]
I guess we could put comments *above* each ENV line instead

**Comment by viceice** [comment]
If regex matching works it would be a better option

**Comment by viceice** [comment]
tested locally, build always fails with syntax error
![image](https://user-images.githubusercontent.com/1798109/76734867-1b433000-6764-11ea-8466-b3e5416a9f2a.png)

**Comment by rarkins** [comment]
Sorry, it's the `docker build` itself that's failing.. not the parsing

**Comment by ZyanKLee** [comment]
we moved to a multiline attempt due to this restriction in docker build:

**Dockerfile:**
```
# pypi: awscli
ENV AWS_CLI_VERSION=1.16.198
```

**renovate config.js**
```
    {
      // # pypi : cfn-lint
      // ENV CFNLINT_VERSION="0.28.4"
      // # npm:cfn-lint
      // ENV cfnlint_version='0.28.4'
      // # git-tag: "cfn-lint"
      // ARG CFNLINT=latest
      // # docker "kkeu/cfn-lint"
      // ARG CFNLINT=latest@sha256:deadbeef12345678908653afafafaf

      fileMatch: ["(^|/)Dockerfile.*$"],
      matchStrings: [
        String.raw`#\s*(?<datasource>[^\s:]+)[\s:"']+(?<depName>[^"\s]+)["']?\s(?:ENV|ARG)\s+[^\s=]+["'\s=]+(?<currentValue>[^@\s"']+)(?:@(?<currentDigest>sha256:[a-f0-9]+))?`
      ]
    }
```

**Comment by viceice** [comment]
this is now fixed and live at https://docs.renovatebot.com/modules/manager/regex/#advanced-capture
