### ISSUE TITLE
@rarkins @JamieMagee We should move the regexes to module scope, otherwise they are recreated on every loop iteration, which is unnessessary

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5741]
@rarkins @JamieMagee We should move the regexes to module scope, otherwise they are recreated on every loop iteration, which is unnessessary

_Originally posted by @viceice in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM5NDE1MjQ1OA==/comments/review_comment_

**Comment by viceice** [comment]
fixed by #5742

**Comment by JamieMagee** [comment]
Was this comment made from the new GitHub app by any chance? Cause the formatting and link is very strange 🤔

**Comment by rarkins** [comment]
No, it was created using the web UI but I did it from mobile so couldn't be bothered to edit it once I created it. It's this option when you view a comment:

![image](https://user-images.githubusercontent.com/6311784/77006384-a722ab00-6962-11ea-8323-6c3e6a5e2aa4.png)
