### ISSUE TITLE
Snapshot tests failing locally lib/manager/gomod/artifacts.spec.ts

### ISSUE THREAD

**Issue by stuart-warren** [renovatebot/renovate#5751]
**What Renovate type are you using?**

Running master branch tests as per `docs/development/local-development.md`

**Describe the bug**

Failing snapshot tests in one file (lib/manager/gomod/artifacts.spec.ts) due to differing `GOPATH` env variable and differing volume directory passed into a `docker run` command

```
        Object {
    -     "cmd": "docker run --rm --name=renovate_go --label=renovate_child --user=foobar -v \"/tmp/github/some/repo\":\"/tmp/github/some/repo\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -v \"/tmp/renovate/cache/others/go\":\"/tmp/renovate/cache/others/go\" -e GOPATH -e GOPROXY -e GONOSUMDB -e CGO_ENABLED -w \"/tmp/github/s
ome/repo\" renovate/go bash -l -c \"git config --global url.\\\"https://x-access-token:some-token@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go mod tidy\"",
    +     "cmd": "docker run --rm --name=renovate_go --label=renovate_child --user=foobar -v \"/tmp/github/some/repo\":\"/tmp/github/some/repo\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -v \"/home/me\":\"/home/me\" -e GOPATH -e GOPROXY -e GONOSUMDB -e CGO_ENABLED -w \"/tmp/github/some/repo\" renovate/go bash -l -c \"gi
t config --global url.\\\"https://x-access-token:some-token@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go mod tidy\"",
          "options": Object {
            "cwd": "/tmp/github/some/repo",
            "encoding": "utf-8",
            "env": Object {
              "CGO_ENABLED": "1",
              "GONOSUMDB": "1",
    -         "GOPATH": "/tmp/renovate/cache/others/go",
    +         "GOPATH": "/home/me",
```

```
Snapshot Summary
 › 6 snapshots failed from 1 test suite. Inspect your code changes or run `yarn run jest -u` to update them.

Test Suites: 1 failed, 1 skipped, 273 passed, 274 of 275 total
Tests:       6 failed, 2 skipped, 2880 passed, 2888 total
Snapshots:   6 failed, 1109 passed, 1115 total
Time:        233.176s
Ran all test suites.
error Command failed with exit code 1.
```

**Did you see anything helpful in debug logs?**

**To Reproduce**

follow the instructions in `docs/development/local-development.md` which don't mention needing to run in a certain directory or specify the local environment further

**Additional context**

Looks like these directories need to be mocked or to add instructions on running inside of an environment that matches the snapshots like a docker image

**Comment by rarkins** [comment]
Looks like it might be because it's picking up your local `GOPATH` setting. Possibly we could manually override `process.env.GOPATH` in that test file to make the result predictable

**Comment by rarkins** [comment]
Can you locate the artifacts test file and play around with setting or unsetting `GOPATH`? e.g. maybe just a `delete process.env.GOPATH;` in the file might work

**Comment by stuart-warren** [comment]
that worked, will raise a PR 

🥂
