### ISSUE TITLE
Make git-tags work with hostRules

### ISSUE THREAD

**Issue by micheelengronne** [renovatebot/renovate#5800]
**What would you like Renovate to be able to do?**
I would like to be able to use `git-tags` datasource with private repositories and credentials set in `hostRules`.

**Describe alternatives you've considered**
Currently, as the projects are in a private instance, I hardcode the credentials in the repositories. But that canno't be used in a production environment.

**Additional context**
Here is the related `config-help` issue https://github.com/renovatebot/config-help/issues/589

**Comment by micheelengronne** [comment]
AFAIK. We just need to alter `lookupName` here :

https://github.com/renovatebot/renovate/blob/5ba8570699b041ea273cfb33a5a574cce84bf072/lib/datasource/git-refs/index.ts#L35

And just for this line.

**Comment by micheelengronne** [comment]
I know I can make it work with ssh keys. But, that means 2 secrets systems to maintain (2 times the attack surface): the `config.js` and the `ssh key`.

**Comment by rarkins** [comment]
So do we have a reliable way to check if the lookupName matches with the configured endpoint? e.g. parse both and compare hostname?

**Comment by rarkins** [comment]
We use git to fetch git tags. Defaults to over `http`. Therefore we need `git` to honor a `.netrc` file for example. Moving this back to "Needs requirements" status as we don't understand the full requirement yet. If we are to write a `.netrc` file to home directory for example then we'd want to do that inside a container instead of potentially polluting the host machines home dir.

**Comment by viceice** [comment]
Instead of netrc we can pass additional config argument to pass an authorization header like we do for azure platform.

https://github.com/renovatebot/renovate/blob/addfd4ef837f471b44eadb1e34a89083e0b4edb8/lib/platform/azure/azure-helper.ts#L20-L33

https://github.com/renovatebot/renovate/blob/addfd4ef837f471b44eadb1e34a89083e0b4edb8/lib/util/git/index.ts#L233-L239

**Comment by kirrmann** [comment]
Just stumbled upon this issue by using private terraform modules. Is there anything I can do to move this forward?

**Comment by kirrmann** [comment]
Btw. seems that using `.netrc` solves this issue with git-tags, as simple-git npm is using this file if it exists.

**Comment by ocofaigh** [comment]
@kirrmann Do you have renovate working for bumping terraform modules stored in a private github repo over SSH?
This is something I am trying to get working currently.

We define our modules like so in .tf files:
```
module "my_module" {
  source               = "git@github.ibm.com:my-org/my-module?ref=1.5.1"
}
```
The environment that is running renovate has the following git config to convert SSH to HTTPS:
```
git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.ibm.com/".insteadOf "https://github.ibm.com/"
git config --global url."https://github.ibm.com/".insteadOf git@github.ibm.com:
git config --global url."https://github.ibm.com".insteadOf ssh://git@github.ibm.com
echo -e "machine github.ibm.com\n  login ${GITHUB_TOKEN}" > ~/.netrc
```

But still no joy.

**Comment by viceice** [comment]
@ocofaigh yo are using ghe, so try to assign `github-tags` as datasource and use the https url as registry url if the existing url doesn't work.

That way renovate will use the ghe api instead of git

**Comment by rarkins** [comment]
Depends on what the `lookupName` already is. If it's a fully qualified git URL then it will fail if remapped to `github-tags`

**Comment by ocofaigh** [comment]
Are you suggesting I try something like this?
```
{
  "packageRules": [
    {
      "matchManagers": ["terraform"],
      "matchDepTypes": ["module"],
      "matchDatasources": ["github-tags"],
      "enabled": true
    }
  ]
}
```

This is probably the wrong place for this conversation, so maybe we move it to: https://github.com/renovatebot/renovate/discussions/11556

**Comment by ocofaigh** [comment]
@viceice @rarkins Lets move the conversation over to https://github.com/renovatebot/renovate/discussions/11556

**Comment by Shegox** [comment]
As of #22983 (35.151.0) Renovate should be now able to use host rules to authenticate for git-tags and git-refs datasources against private or self-hosted GitHub Enterprise Server.
