### ISSUE TITLE
Display age/release date for updates

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5822]
**What would you like Renovate to be able to do?**

Give a clear indication to users about when an update was released (if we have that data)

**Describe the solution you'd like**

We might need to offer various approaches. Here are the possibilities I can think of:
- Raw release timestamp (accurate, but not user-friendly)
- Pretty timestamp (e.g. `16-Mar` if it's same year, or `12-Sep-2018` if it's older than a year)
- Relative age generated by Renovate at runtime (e.g. "2 days ago")
- Relative age generated by a hosted service using SVG (e.g. "2 days ago" but it's dynamically updated without the need for Renovate to run)

People will have different preferences, so we could satisfy this by exposing multiple values per-update to the PR body templates, e.g.

- `timestampRaw`: `20200320T140201Z`
- `timestampPrettyDay`: `16-Mar-2020`
- `timestampPrettyDayShort`: `16-Mar`
- `timestampAge`: `2 hours`

**Comment by ViralRuparel** [comment]
will it go to each version like below:

![image](https://user-images.githubusercontent.com/21654339/78825277-518b6c80-79fd-11ea-97af-edcc76b9e0a3.png)

or only to the latest version to which we are upgrading? 

and also will it look pretty in the PR body if we show this four formats, would't it make sense to just show one thing probably `timestampPrettyDay`, I think.

**Comment by rarkins** [comment]
I was anticipating this to just be shown in the table, which would mean it reflects the latest version. Also, not to show all four at once but to give people the choice of which to display (because we support templates).

**Comment by ViralRuparel** [comment]
> I was anticipating this to just be shown in the table, which would mean it reflects the latest version. Also, not to show all four at once but to give people the choice of which to display (because we support templates).

Okay, got it.

**Comment by rarkins** [comment]
I think for this we need:
- sanitized timestamp from datasource
- an SVG server which returns a relative "badge" which can be embedded 

Otherwise the PR will need to be regularly updated, which generates noise.

**Comment by HonkingGoose** [comment]
We already have badges with the relative package age in our "Merge Confidence table":

![package-age-merge-confidence](https://user-images.githubusercontent.com/34918129/154229540-095b58ee-876e-4aae-ba05-53f2b50fab53.png)

Do you want to keep this issue around and do more work, or are you happy to close it and just rely on the Merge Confidence badges?
