### ISSUE TITLE
Error when using Renovate on Github Actions

### ISSUE THREAD

**Issue by Djiit** [renovatebot/renovate#5881]
**What Renovate type are you using?**

Self-hosted Renovate, run on Github Actions periodically (see https://github.com/wikiwarsgg/webapp/blob/master/.github/workflows/schedule.yml)

**Describe the bug**

I have this error when running Renovate on a PR (see https://github.com/wikiwarsgg/webapp/pull/22)

```
`Error: EACCES: permission denied, mkdir '/github/home/.npm'
TypeError: Cannot read property 'get' of undefined
    at errorMessage (/usr/lib/node_modules/npm/lib/utils/error-message.js:38:39)
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:201:13)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:78:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:225:22)
    at /usr/lib/node_modules/npm/lib/npm.js:263:24
    at /usr/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:171:20)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/lib/node_modules/npm/lib/utils/error-handler.js:97:27)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:311:20)
    at process._fatalException (internal/process/execution.js:164:25)
```

**Did you see anything helpful in debug logs?**

See above

**To Reproduce**

All the links above are open.

**Comment by viceice** [comment]
I don't know what's happening, but you can try our official github [action](https://github.com/renovatebot/github-action)

**Comment by Djiit** [comment]
Shouldn't it be under the renovate org ?
Also, the action use a `config.js` file, which ask me to have two config files : `renovate.config.js` (or whatever I want) and `renovate.json` (created when onboarding with only one line reffering to a remote schema).

I think we should be able to use a unique json file. (`renovate.json`imho)

**Comment by viceice** [comment]
the action is on our renovatebot org. The action runs the selfhosted cli version of the bot, so it will use the `config.js` for admin config. You can use an simple  empty export for this

```js
module.exports = {};
```

**Comment by Djiit** [comment]
Ok, my bad, I don't know why I ended up in https://github.com/vidavidorra/github-action-renovate.

Can we provide this empty object as a default if there is no configurationFile ?

**Comment by viceice** [comment]
Sure, the repo you've found is the old one, we cloned to our org. Can you please file an issue there for a default config.

**Comment by Djiit** [comment]
Sure, let's close this one. Thanks !
