### ISSUE TITLE
Include cron in the official docker image

### ISSUE THREAD

**Issue by kolaente** [renovatebot/renovate#5883]
**What would you like Renovate to be able to do?**
It would be cool if the renovate docker image would contain configurable cron support to run at a certain schedule automatically.

**Describe the solution you'd like**
An environment variable which would configure the cron schedule, something like `CRON_SCHEDULE=0 * * * *` - if provided the docker image would stay running and execute renovate at the schedule instead of exiting after running once. To provide backwards compatibility, it would not run if the env variable is not set.

**Describe alternatives you've considered**
Running manually or with an external scheduler.

**Additional context**
I understand usually, the docker image is meant to run on a schedule controlled by something like kubernetes. However, for smaller setups like mine which does not use kubernetes it seems a bit overkill to need an additional scheduler only for renovate. 

If such functionality seems like a good idea, I'd be happy so send a pr.

**Comment by rarkins** [comment]
The existing Docker image doesn’t require kubernetes.

**Comment by kolaente** [comment]
@rarkins I know I can run it without kubernetes but when starting the docker image, it will run the CLI once and exit afterwards. If I want renovate to check for updates in my repos, I need to manually run the docker image every time or with an external cron tool. Kubernetes has such functionality and is mentioned for this in the docs. I could also stick a shell script in the crontab on my server to run the docker container every hour, but IMHO it would be a lot cleaner if the docker image would proved that out of the box.

It could very well be I misinterpreted some part of the docs, but I could not find something indicating the docker image is capable of scheduling renovate itself (without relying on an external tool to start renovate at a defined schedule)

**Comment by rarkins** [comment]
It’s intended that you use cron on your server to schedule it as we prefer to keep the image simple. At this point we are not wanting to support a stateful container due to the additional edge cases it introduces (eg error/restart handling or memory clearing).
