### ISSUE TITLE
Problem updating private Docker registry implicit library/ image

### ISSUE THREAD

**Issue by mmaeller** [renovatebot/renovate#5894]
### Which Renovate are you using?
Renovate docker image 19.156.0

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```
 WARN: Error getting docker image tags (repository=backend/myproject)
       "registry": "https://artifactoryDomain",
       "dockerRepository": "backend-docker/openjdk",
       "err": {
         "name": "HTTPError",
         "host": "artifactoryDomain",
         "hostname": "artifactoryDomain",
         "method": "GET",
         "path": "/v2/backend-docker/openjdk/tags/list?n=10000",
         "protocol": "https:",
         "url": "https://artifactoryDomain/v2/backend-docker/openjdk/tags/list?n=10000",
         "gotOptions": {
           "path": "/v2/backend-docker/openjdk/tags/list?n=10000",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "artifactoryDomain",
           "port": null,
           "hostname": "artifactoryDomain",
           "hash": null,
           "search": "?n=10000",
           "pathname": "/v2/backend-docker/openjdk/tags/list",
           "href": "https://artifactoryDomain/v2/backend-docker/openjdk/tags/list?n=10000",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "authorization": "** redacted **",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate"
           },
           "hooks": {
             "beforeError": [],
             "init": [],
             "beforeRequest": [],
             "beforeRedirect": [],
             "beforeRetry": [],
             "afterResponse": []
           },
           "retry": {"methods": {}, "statusCodes": {}, "errorCodes": {}},
           "decompress": true,
           "throwHttpErrors": true,
           "followRedirect": true,
           "stream": false,
           "form": false,
           "json": true,
           "cache": false,
           "useElectronNet": false,
           "method": "GET",
           "gotTimeout": {"request": 60000}
         },
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "server": "nginx/1.17.7",
           "date": "Mon, 30 Mar 2020 13:22:58 GMT",
           "content-type": "application/json",
           "transfer-encoding": "chunked",
           "connection": "close",
           "vary": "Accept-Encoding",
           "x-artifactory-id": "qwertz",
           "docker-distribution-api-version": "registry/2.0",
           "strict-transport-security": "max-age=15724800; includeSubDomains",
           "content-encoding": "gzip"
         },
         "body": {
           "errors": [
             {
               "code": "NAME_UNKNOWN",
               "message": "Repository name not known to registry.",
               "detail": {"name": "openjdk"}
             }
           ]
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at EventEmitter.emitter.on (/usr/local/lib/node_modules/renovate/node_modules/got/source/as-promise.js:74:19)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"
       }
```

### What would you like to do?
The gitlab project `myproject` in gitlab group backend contains a Dockerfile.
This file is being scanned, but the tags cannot be resolved since the URL is not built properly.
It should read https://artifactoryDomain/v2/backend-docker/library/openjdk/tags/list?n=10000 instead of https://artifactoryDomain/v2/backend-docker/openjdk/tags/list?n=10000, since our artifactory has grouped repositories.

Is there any configuration option to fix this?

I already tried 

```
  "hostRules": [
    {
      "hostType": "docker",
      "baseUrl": "https://artifactoryDomain/backend-docker"
    }
  ],
```
but got the same result.
For me it seems like https://github.com/renovatebot/renovate/blob/master/lib/datasource/docker/index.ts#L372 is a poor condition in this case, because the repository reads `backend-docker/openjdk`.

The Dockerfile starts with
`FROM artifactoryDomain/backend-docker/openjdk:12-alpine
`

**Comment by mmaeller** [comment]
I'm wondering because this should be a common issue, since artifactory provides this repository grouping as a common feature. :(

**Comment by mmaeller** [comment]
Hi @rarkins,

Isn't the issue, that https://github.com/renovatebot/renovate/blob/25eb7bf359af4a4f61035d326c3d59bdb776dfc6/lib/datasource/docker/index.ts#L59 doesn't take the configured baseUrl into account?
The registry result value should contain the backend-docker path instead of just the registry URL without any path.

**Comment by rarkins** [comment]
> doesn't take the configured baseUrl into account?

Which configured baseUrl? Do you mean in `hostRules`?

**Comment by mmaeller** [comment]
> > doesn't take the configured baseUrl into account?
> 
> Which configured baseUrl? Do you mean in `hostRules`?

Yes

**Comment by rarkins** [comment]
hostRules come much after that logic. At this point in the parsing our task is to work out what the image is, including possibly a host. hostRules are matched later before the lookup occurs.

**Comment by mmaeller** [comment]
So then later the hostRules should ensure, that the correct registry path should be https://artifactory.company.com/backend-docker/ instead of https://artifactory.company.com/ when I configured the hostRules baseUrl https://artifactory.company.com/backend-docker/.
Seems not.
It still uses the dockerRepository "backend-docker/openjdk" instead of sanitizing the data by the provided hostRules.
Sorry questioning that much, but I just want to solve that issue. Currently I got the feeling it's a bug instead of a configuration issue. :(

**Comment by rarkins** [comment]
This still captures the problem:

> somehow Renovate should be able to know that `FROM artifactoryDomain/backend-docker/openjdk:12-alpine` means a registry of `artifactoryDomain/backend-docker` instead of `artifactoryDomain` alone, or if it has to just try/fail/try again.

So is there anything about this URL which lets a client know for sure which of these it is?
1. endpoint `artifactoryDomain/` and image `backend-docker/openjdk` (current) or
2. endpoint `artifactoryDomain/backend-docker/` and image `openjdk`

If there's no way from looking at that string to know which it is, then it means that the datasource needs to add some try/fail/try logic instead.

**Comment by mmaeller** [comment]
My naive opinion is that it's the baseUrl's job to verify that.

I configure the baseUrl "https://artifactoryDomain/backend-docker", so if the determined dockerRepository is "backend-docker/imagePath/image" and the determined registry is "artifactoryDomain", then renovate could recognize that a part of the dockerRepository is actually the registry and should be removed from the dockerRepository-String.

What is the intention of the baseUrl? According the [docs](https://docs.renovatebot.com/configuration-options/#baseurl) it's designed for adding a path, but exactly this seems not to work in the docker implementation.

**Comment by rarkins** [comment]
> What is the intention of the baseUrl?

To match against requests in `hostRules` if `hostName` is not specific enough. It's got nothing to do with extraction.

**Comment by mmaeller** [comment]
Well, hm, I got no clue how to get this working. The only workaround seems to be checking every image whether it's part of this docker library repository and already add "library/" to the image name.

**Comment by rarkins** [comment]
I've pushed a fix just now that I think might solve it for you, although I don't have a private registry handy to test it against. Once the next release is out, you will need to define your registry in `registryUrls`, e.g. like this:

```
{
  "docker": {
    "registryUrls": ["https://artifactory.company.com/backend-docker/"]
  }
}
```

`registryUrls` sort of means what you thought `endpoint` did, but I needed to add a little logic to make sure it will retry with the `library/` prefix.

**Comment by mmaeller** [comment]
Hi Rhys,
thx for the fix, but unfortunately we missed a spot.
The config results in https://artifactoryDomain/backend-docker//v2/library/openjdk/tags/list?n=10000 which looks quite ok at first glance, but it must be https://artifactoryDomain/v2/backend-docker/library/openjdk/tags/list?n=10000
Damn it, our simple approach won't work.

And that's probably the reason why "backend-docker" is part of the dockerRepository, because the artifactory API requires the version after the domain. So you could only solve that issue by you remembering the virtual repository group. Look's like that. :(

**Comment by krohrsb** [comment]
I've got the same exact use-case. Artifactory with a manual specification of a repository, unfortunately.

Do let me know if I can also help in any way.

**Comment by viceice** [comment]
I don't think that docker itself supports the implicit `library/` to arbitrary image names.

**Comment by mmaeller** [comment]
> I've got the same exact use-case. Artifactory with a manual specification of a repository, unfortunately.
> 
> Do let me know if I can also help in any way.

Hi, I stumbled over this and just to let you know: the main issue was that the Artifactory "Docker Access Method" was configured as "Repository Path". This is just intended for testing/trial purposes. For running Artifactory in production you should switch to "Sub Domain" (JFrog recommended approach, see image at [docs](https://www.jfrog.com/confluence/display/JFROG/HTTP+Settings#HTTPSettings-UsingDirectAccess)). The embedded Tomcat will handle everything further concerning virtual repositories etc.
