### ISSUE TITLE
[CE] Webhook

### ISSUE THREAD

**Issue by strarsis** [renovatebot/renovate#5901]
**What would you like Renovate to be able to do?**
Being triggered by a repository system like GitLab.

**Describe the solution you'd like**
Add minimal webhook support.

**Describe alternatives you've considered**
Put renovate on schedule. But could it run each minute? All 10 seconds? Are race conditions avoided by its programming (e.g. lockfile)?

**Additional context**
Is a webhook something hard to implement, so this is only provided by the EE (Enterprise Edition) of Renovate?

**Comment by rarkins** [comment]
This is not within the scope of this repository, as this is a CLI tool. You're welcome to check out https://renovate.whitesourcesoftware.com/on-premises/, which is free to use with registration.

**Comment by strarsis** [comment]
@rarkins: Nice! Just a question though: When the CLI tool is used, it would be normally set on schedule for a GitLab repository?

**Comment by rarkins** [comment]
Most people schedule it to be run hourly or daily.

**Comment by strarsis** [comment]
@rarkins: So when I run the docker container of renovate, it will exit itself after it finished.
Should I set the container to `restart: always`?

**Comment by rarkins** [comment]
You’ll probably exhaust your rate limits if you do so. It’s meant to be “docker run”, not “docker up”. Schedule it using pipelines or cron.

**Comment by strarsis** [comment]
@rarkins: Thanks! With pipelines the GitLab pipelines are meant?

**Comment by rarkins** [comment]
Yes. If you google it you can find a few people have blogged about their setups

**Comment by strarsis** [comment]
@rarkins: Thanks! `renovate` is great! I use it mainly for updating WordPress plugins (composer-based roots.io Bedrock setup).
