### ISSUE TITLE
Docker Image 19.207.1 broke Gradle projects

### ISSUE THREAD

**Issue by Pascalmh** [renovatebot/renovate#5963]
**What Renovate type are you using?**

self-hosted Renovate on GitLab CI using 

**Describe the bug**

When we updated to the newest version of renovate this morning our Gradle Projects started failing. 

**Did you see anything helpful in debug logs?**

```
ERROR: Repository has unknown error (repository=xxx)
        "err": {
          "message": "Cannot read property 'length' of null",
          "stack": "TypeError: Cannot read property 'length' of null\n    at fetchDepUpdates (/usr/src/app/dist/workers/repository/process/fetch.js:46:25)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
        }
```

**To Reproduce**

[Use this Docker Image](https://hub.docker.com/layers/renovate/renovate/latest/images/sha256-e02b1242d4f2cb458d10ba70f5ba7f5d711f85e49e37c8970b4be469f2970d56?context=explore)

**Additional context**

We reverted back to the docker image tagged with 19.206.0 - and it works as expected again.

We use a internally hosted artifactory where the dependencies are hosted.

**Comment by rarkins** [comment]
Thanks for reporting. I've pushed a fix in 19.208.1 for that particular line, however I wasn't able to reproduce the problem with my own demo gradle repo. If the problem still occurs, we'll need an example *repository* that can reproduce the problem.

**Comment by TVNOWAccountSQ** [comment]
Thank you @rarkins - that was quick! We are back on the "latest" image and it works again as expected!

**Comment by Pascalmh** [comment]
Thank you @rarkins - that was quick! We are back on the "latest" image and it works again as expected!
