### ISSUE TITLE
Maven: 1.4.12-java7 considered stable and sorted higher than 1.4.12

### ISSUE THREAD

**Issue by manuelleduc** [renovatebot/renovate#5977]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I have a maven project which depends of `com.thoughtworks.xstream:xstream:1.4.11.1`.

Renovate opened a pull request for `com.thoughtworks.xstream:xstream:1.4.12-java7` but I would prefer to see an pull request with `com.thoughtworks.xstream:xstream:1.4.12` since I am using Java 8.

How can I configure my renovate.json file to specify that, for the groupId `com.thoughtworks.xstream` and the artifactId `xstream`, I do not want to receive PR when the version ends with `-java7`?

**Comment by manuelleduc** [comment]
Thanks a lot @rarkins  & @zharinov !

Another more question. Let's say that in another maven module, I only want to receive PR for new versions that end with `/\d+\.\d+\.\d+-java7/`.
How could I define such constraint in my renovate.json file ?

PS: If you prefer I ask that question again in a new issue, let me know.

**Comment by elharo** [comment]
"1.4.12-java7" is not a misuse of Maven versioning. Maven makes no claim about what any part of any version number "means". It does not assume this means stability, compatibility, or anything else. It simply defines an algorithm for ordering version strings. 

semver might define that but not every project follows semver.

**Comment by rarkins** [comment]
@elharo if you insist that Maven versioning is meaningless except for sorting then be sure not to expect that clients can somehow know that `1.4.11-java7` -> `1.4.12-java7` is a valid upgrade while `1.4.11-java7` -> `1.4.12` is not. You can't have it both ways. A very large majority of maven packages do numbering sensibly and small majority do not.

FYI semver has no compatibility concept so not relevant in this discussion. Semver's *sorting* of suffixes is also a mess other than the fact that `alpha`, `beta` and `pre` happen to sort alphabetically in the order people expect.

**Comment by rarkins** [comment]
Back to the topic, Maven does define the sorting of certain qualifiers: https://github.com/apache/maven/blob/ec92934bf08f11e8541e897c0f466f1f03c73a78/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java#L44-L55

Copy/pasting with some cleanup:

----

Features:
<ul>
<li>mixing of '<code>-</code>' (hyphen) and '<code>.</code>' (dot) separators,</li>
<li>transition between characters and digits also constitutes a separator:
    <code>1.0alpha1 =&gt; [1, 0, alpha, 1]</code></li>
<li>unlimited number of version components,</li>
<li>version components in the text can be digits or strings,</li>
<li>strings are checked for well-known qualifiers and the qualifier ordering is used for version ordering.
    Well-known qualifiers (case insensitive) are:<ul>
    <li><code>alpha</code> or <code>a</code></li>
    <li><code>beta</code> or <code>b</code></li>
    <li><code>milestone</code> or <code>m</code></li>
    <li><code>rc</code> or <code>cr</code></li>
    <li><code>snapshot</code></li>
    <li><code>(the empty string)</code> or <code>ga</code> or <code>final</code></li>
    <li><code>sp</code></li>
    </ul>
    Unknown qualifiers are considered after known qualifiers, with lexical order (always case insensitive),
  </li>
<li>a hyphen usually precedes a qualifier, and is always less important than something preceded with a dot.</li>
</ul>

----

Is this the important part?
> Unknown qualifiers are considered after known qualifiers, with lexical order (always case insensitive)

In that case `1.4.12-java` *does* sort higher than `1.4.12`?

i.e. the only qualifiers that should be considered unstable are the well-known ones ["alpha", "beta", "milestone", "rc", "snapshot"](https://github.com/apache/maven/blob/ec92934bf08f11e8541e897c0f466f1f03c73a78/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java#L357)

**Comment by rarkins** [comment]
Assuming that the above is correct, it means that our default behavior currently is correct, and that this is not a bug to be fixed.

We then need to work on *features* to help users overcome this:
- For users who don't want suffixes like `-java7` then they probably would like an option to opt into non-suffixed versions only (i.e. to avoid being updated from `1.14.1.1` to `1.14.2`.
- If we supported natively the concept of a fourth version part after major.minor.patch (e.g. major.minor.patch.build) then users could use that with the `regex` versioning
- Implement #5537 to allow regex filtering of versions

**Comment by elharo** [comment]
Maven defines the sorting, not the meaning. From the perspective of Maven "alpha", for example, is just a string that is sorted in a certain order. There is no meaning, except arguably for "SNAPSHOT". It certainly doesn't distinguish between stable and unstable. 

The comparison algorithm is not always obvious, but I think that 1.4.12-java7 does sort higher than 1.4.12.

**Comment by rarkins** [comment]
In that case I think we're in agreement that the current behavior is correct in terms of the Maven spec, so this was a mistaken bug report by myself. @manuelleduc you should follow #5537 to achieve what you need

**Comment by rarkins** [comment]
PR ready: #5979
