### ISSUE TITLE
 Document versionScheme in packageRules #2914 

### ISSUE THREAD

**Issue by elharo** [renovatebot/renovate#5978]
#2914 added support for versionScheme in packageRules. However this is not mentioned in https://docs.renovatebot.com/configuration-options/#packagerules

**Comment by rarkins** [comment]
`versionScheme` was renamed to `versioning` and is documented here: https://docs.renovatebot.com/configuration-options/#versioning

Although it's most commonly used in `packageRules`, it's not exclusively so. e.g. you could possibly change the default for a manager:

```json
{
  "docker": {
    "versioning": "semver"
  }
}
```

`packageRules` allow dozens of our existing options apart from `versioning`, so I don't think it's appropriate to single it out. However I can't think of any *good* reason to use `versioning` outside of `packageRules`, so we could potentially limit its use and bring it inside `packageRules`.

**Comment by henrist** [comment]
I was also looking up the docs for this field I had previously used, but wasn't able to find it except for googling after it (and reaching this issue). Would it be an idea to keep deprecated names available for searching in the documentation as long as the config migration supports it?

**Comment by rarkins** [comment]
We've never removed a field from migration so our documentation would be quite messy and confusing if we left in every option. I hope to add a feature to propose PRs that automatically migrate config soon. Once we do that, and then fully deprecate in a following major release, then it might be feasible to start maintaining documentation for migrated fields.

**Comment by henrist** [comment]
PRs for config migration sounds great!
