### ISSUE TITLE
Autodiscovery UX improvements suggestions

### ISSUE THREAD

**Issue by augi** [renovatebot/renovate#6020]
**What would you like Renovate to be able to do?**
First of all, this is a great tool! I've just tried to use the autodiscover feature but it took me a few hours to make it work, so I have a few suggestions on what would help me.

**Describe the solution you'd like**
1. Autodiscovered repositories are not listed even with `trace` log level. This would be helpful.
2. I expected that [logLevel](https://docs.renovatebot.com/self-hosted-configuration/#loglevel) can be set using `RENOVATE_` prefixed envvar, so `RENOVATE_LOG_LEVEL`. Unfortunately, this doesn't work. Plain `LOG_LEVEL` works well. It would be great to document this. Or better, support also reading from `RENOVATE_LOG_LEVEL`, to keep consistency.
3. I saw in the log just `None of the discovered repositories matched the filter`. So I tried to tune the `autodiscoverFilter` parameter. But then I accidentally found [this issue](https://github.com/renovatebot/renovate/issues/4140) that describes that Renovate fetches just first 1000 repositories. For this, I have two suggestions:
   1. Print a warning message when the limit of 1000 repositories is hit.
   2. Document the `RENOVATE_PAGINATE_ALL` in the documentation for self-hosting.

As I wrote, Renovate is absolutely great tool! ❤️ It would be great if you could apply some of these suggestions as they could help future users.

**Comment by viceice** [comment]
You nee to set `LOG_LEVEL=debug`

**Comment by rarkins** [comment]
1. This should be logged at debug level
2. Although we support `LOG_LEVEL` we should add `RENOVATE_LOG_LEVEL` as an alternative
3. I can't see why we can't default to paginating all for autoDiscover

**Comment by secustor** [comment]
Fixed in e990c6b24cdd933b5f3e0c544209339ed6e1ce28
