### ISSUE TITLE
Question: How exactly renovatebot updates Gradle wrapper

### ISSUE THREAD

**Issue by remal** [renovatebot/renovate#6030]
I have a few questions:
1. Does renovatebot updates Gradle wrapper to the latest version or not? As I can see version in [fixtures](https://github.com/renovatebot/renovate/blob/29d5e48bf5991ad89d8f4cbc42058b3f408e62a9/lib/manager/gradle/__fixtures__/gradle-wrappers/6/gradle/wrapper/gradle-wrapper.properties) is not the latest.
1. Does renovatebot updates Gradle wrapper from 5.* to 6.*?
1. Does renovatebot keep `distribution-type` the same? What if I have `distributionUrl=https://services.gradle.org/distributions/gradle-6.0-all.zip` (gradle-6.0-**all**.zip)? Will it become `distributionUrl=https://services.gradle.org/distributions/gradle-6.3-all.zip`?

**Comment by rarkins** [comment]
1. `__fixtures__` are always test files and not relevant
2. As far as I'm aware this should work
3. I suspect right now we switch it to `-bin` because that's what's in the gradle API response. It would require some dev work to figure out a way to look up the `-all` instead if it's not in the API
