### ISSUE TITLE
Constant `registry-failure` happening for elastic/kibana

### ISSUE THREAD

**Issue by spalger** [renovatebot/renovate#6031]
**What Renovate type are you using?**

Github App

**Describe the bug**

Renovate stopped opening PRs, updating the master issue, seems to be failing every time it executes.

**Did you see anything helpful in debug logs?**

The dashboard shows all jobs failing with result `registry-failure` and two of them failing with `no-token`... Looks like the registry failures are caused by timeouts, maybe we have too many dependencies?

https://app.renovatebot.com/dashboard#github/elastic/kibana/167756298

**To Reproduce**

**Additional context**

**Comment by rarkins** [comment]
It's not too many dependencies. Some *specific* ones cause problems when we query npmjs, particularly `@typescript-eslint/eslint-plugin` and `@storybook/*`. As a workaround I'll try disabling `@typescript-eslint/eslint-plugin` for your repo server-side tomorrow and see if the rest go through.

**Comment by spalger** [comment]
Just a little reminder :) This is still happening

**Comment by rarkins** [comment]
This condition is somewhat alleviated now btw (without disabling - I just increased backoff and a few other things). Now there's a yarn failure - any idea where this `@babel/core` error is coming from? I haven't seen it before:

```
      "stdout":"yarn install v1.22.4
info If you think this is a bug, please open a bug report with the information provided in \"/mnt/renovate/gh/elastic/kibana/yarn-error.log\".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
",
      "stderr":"error An unexpected error occurred: \"Cannot use 'in' operator to search for '@babel/core' in ../yarn.lock\".
```

**Comment by spalger** [comment]
I haven't seen that before, is there maybe a stack trace in yarn-error.log?
