### ISSUE TITLE
gitlabci-include does not update all include statements

### ISSUE THREAD

**Issue by Stefan-J-Hanke** [renovatebot/renovate#6032]
#### This is a:

- [x] Bug report (non-security related)
- [ ] Feature request
- [ ] I'm not sure which of those it is

#### I'm using:

- [ ] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [x] Self-hosted GitLab
- [ ] Self-hosted Azure DevOps

#### Please describe the issue:

We use more than one `include` keyword in our `.gitlab-ci.yml` files. We recently noticed that not all of those, but only one instance was updated. The update itself was a major one (that is, an update from `1.x.y` to `2.z.a`).

**Comment by fgreinacher** [comment]
Maybe related to the new autoreplace feature?

**Comment by rarkins** [comment]
Needs a reproduction repo

**Comment by fgreinacher** [comment]
Working on a repro

**Comment by fgreinacher** [comment]
For some reason Renovate does not run against my project (see https://app.renovatebot.com/dashboard#gitlab/fgreinacher/renovate-include-consumer). Can you take a look @rarkins? I added https://gitlab.com/renovate-bot more than an hour ago.

**Comment by rarkins** [comment]
@fgreinacher Unfortunately the app is really slow to detect new GitLab repos - usually a few hours. This is because we don't have a reliable way to get notified when we're added to new repos.

**Comment by rarkins** [comment]
Recommend you test out on github.com when possible because it's app interface is so much better in this case.

**Comment by fgreinacher** [comment]
> Recommend you test out on github.com when possible because it's app interface is so much better in this case.

I'll try that, thanks!

**Comment by fgreinacher** [comment]
Wow, that was MUCH faster: Here is the PR showing the problem: https://github.com/fgreinacher/renovate-include-consumer/pull/2

**Comment by rarkins** [comment]
@fgreinacher actually, how did you get this working on github? I tried forking it but it's not working for me in this repo: https://github.com/renovate-tests/renovate-include-consumer

**Comment by fgreinacher** [comment]
I also tried to debug this locally and it's now also failing because it cannot look up the included dep. That's really strange. Maybe it's working because I have the exact same repos on GitLab with Renovate Bot added as Developer.

**Comment by fgreinacher** [comment]
Now it ran again and the changes are OK now. This behavior seems to be a bit sporadic.

**Comment by rarkins** [comment]
FYI I made a change earlier today that may help this scenario, but I'm not sure how to verify it. Do you think it would work if I forked your two repos into my own account on gitlab.com ?

**Comment by fgreinacher** [comment]
TBH I'm not sure ❓ 

In the meantime Renovate also picked up my GitLab repos: https://gitlab.com/fgreinacher/renovate-include-consumer/-/merge_requests/2 - I also don't see the error there anymore.

**Comment by rarkins** [comment]
Looks fixed to me?

**Comment by fgreinacher** [comment]
Seems so - what’s the change you mentioned?

**Comment by rarkins** [comment]
It was this one: https://github.com/renovatebot/renovate/commit/f61c416f8a0d5dff170b078caa5fda1012534999

autoReplace was initially failing in some edge cases where people managed to group multiple conflicting updates into the same branch/PR. e.g. one updating from 1.0.0 to 1.1.0 and another from 1.0.0 to 1.2.0. 

I added de-duplication but that was too aggressive and forgot about the case where you genuinely have two updates in the same file for different locations of the same dependency. So the fix yesterday was for that, which seems to describe the gitlab-ci problem too.
