### ISSUE TITLE
Renovate appends the docker digest twice

### ISSUE THREAD

**Issue by schuch** [renovatebot/renovate#6033]
**What Renovate type are you using?**
Reproducible with
- GitHub App
- Selfhosted v19.216.6

**Describe the bug**
Renovate appends the docker digest twice in a `gitlab-ci.yml`:
```
image: node:12@sha256:44d3b16983346c5f48b27de2f52301d8dca64698c2680764d77198d81d9d1dc8@sha256:44d3b16983346c5f48b27de2f52301d8dca64698c2680764d77198d81d9d1dc8
```

There is another row in the file that should receive a digest pin, maybe somehow renovates inserts this pin to the wrong place.

**Did you see anything helpful in debug logs?**
no

**To Reproduce**
The error can be seen in Repo https://github.com/schuch/renovate-6033 in Pull Request
https://github.com/schuch/renovate-6033/pull/3/files

**Comment by schuch** [comment]
The first digest pin was appended in https://github.com/schuch/renovate-6015/pull/15/files
In this PR renovate also missed the second digest pin in [line 11](https://github.com/schuch/renovate-6015/pull/15/files#diff-96edf7a6f008de9e928d04e1ae5e12a5L11)

**Comment by rarkins** [comment]
Which release/version of Renovate was this tested against?

**Comment by rarkins** [comment]
Also, can you add a description in the readme for the reproduction repo? It's a little confusing knowing what's going on as there are three Dockerfiles and 5 PRs

**Comment by schuch** [comment]
> Which release/version of Renovate was this tested against?

Tested with the Github Application, I don't know which version of renovate is running there. Latest?

> Also, can you add a description in the readme for the reproduction repo? It's a little confusing knowing what's going on as there are three Dockerfiles and 5 PRs
Sorry for the mess. I was in the process of reproducing another bug when this came up.
I will extract this reproduction to a separate repo get rid of the noise.

**Comment by schuch** [comment]
Raised repo https://github.com/schuch/renovate-6033

In PR https://github.com/schuch/renovate-6033/pull/2 (a pin digest PR) you can see, that renovate misses to update the second image reference.

This could be the related to the duplicated docker digest, that follows in PR https://github.com/schuch/renovate-6033/pull/3

**Comment by rarkins** [comment]
This should now be resolved, as per this forked reproduction: https://github.com/renovate-tests/renovate-6033/pull/2/files
