### ISSUE TITLE
[SBT] Misleading interval

### ISSUE THREAD

**Issue by waghanza** [renovatebot/renovate#6048]
Hi,

The bot has opened the-benchmarker/web-frameworks#2563.

The idea is to replace [0.21,0.22) to [0.21,0.20.21).

Assuming my very few skills on scala :

+ [0.21,0.22), means any version in **0.21.x**
+ [0.21,0.20.21) means any version greater than **0.21** but (strictly) lower than **0.20.21**

I don't understand the idea of this PR

Regards,

**Comment by waghanza** [comment]
@rarkins Thanks for your fix, but I'm not a `scala` developper. I'm not sure my analysis are OK here

/cc @whiplash Are my conclusions `here` ok, according to **SBT** ?

**Comment by rarkins** [comment]
@waghanza I think your analysis was correct - it was a mistaken PR that shouldn't happen now

**Comment by whiplash** [comment]
`[0.21,0.22)` looks correct to me.
