### ISSUE TITLE
[SPM] Using interval

### ISSUE THREAD

**Issue by waghanza** [renovatebot/renovate#6070]
Hi,

The `swift` tracker update my dependencies in https://github.com/the-benchmarker/web-frameworks.

However, I prefer to use range, using `.upToNextMinor` to use the last _patch_ of the series.

The following `PR`, are then misleading :

+ https://github.com/the-benchmarker/web-frameworks/pull/2601
   + `from: "2.9.0" -> from: "2.9.1"` is correct but
   + their is a `.upToNextMinor` meaning that any of **2.9** is accepted
+ https://github.com/the-benchmarker/web-frameworks/pull/2602
   + `from: "3.0.0" -> from: "3.0.23"` is correct but
   + there is `.upToNextMinor` meaning that any of **3.0.x** is accepted

Regards,

**Comment by rarkins** [comment]
What is the effect without `.upToNextMinor` - anything up to the next major is accepted?

**Comment by waghanza** [comment]
No. `.upToNextMinor` means any patch level

**Comment by rarkins** [comment]
I asked about *without*. Any minor update?

**Comment by waghanza** [comment]
Ah sorry, it was too late ... `from: "3.0.0"` means the **exact** tag

**Comment by rarkins** [comment]
Thanks for the clarification. So `from: "3.0.0"` essentially means "exactly 3.0.0"? Strange syntax if so!

**Comment by waghanza** [comment]
Yep

I prefer `ruby` one `~> 3.0.0`, but I'm a little biased :stuck_out_tongue:

**Comment by waghanza** [comment]
Same use case for https://github.com/the-benchmarker/web-frameworks/pull/2619
