### ISSUE TITLE
Cannot find preset's package (config:base)

### ISSUE THREAD

**Issue by JustArchi** [renovatebot/renovate#6076]
**What Renovate type are you using?**

Self-hosted renovate with self-hosted gitlab server via official slim docker container.

**Describe the bug**

```
 INFO: Throwing preset error (repository=myrepo/path)
 INFO: Repository has invalid config (repository=myrepo/path)
       "error": {"validationError": "Cannot find preset's package (config:base)"}
```

**Did you see anything helpful in debug logs?**

I didn't have opportunity to run with debug logs yet.

**To Reproduce**

This is a regression, our private company setup has worked just fine, but broke today, I think there might be some problem with latest `19.221.0` version. I'm attaching `renovate.json` config for all the repos that we use:

```
{
  "extends": [
    "config:base",
    ":automergeDigest",
    ":automergeMinor",
    ":disableRateLimiting"
  ]
}
```

**Additional context**

It used to work just fine, the error happened maximum a few hours ago.

Thank you in advance for taking a look.

**Comment by JustArchi** [comment]
Let me know in case you need more info, I think it should be trivial to reproduce this 🙂.

**Comment by rarkins** [comment]
We switched the `config:*` preset hosting from npm to GitHub today. Does your company setup have access to api.github.com? And have you configured GITHUB_COM_TOKEN ?

**Comment by JustArchi** [comment]
You're right, we don't have `GITHUB_COM_TOKEN` configured, as we didn't need it previously for renovate to work fine. It's used for our private gitlab server exclusively.

Do you believe there is anything to address in regards to this, so there is no need to supply the token for that? I mean, if the official fix is to use the token and github then it's fine and I can set it up, but perhaps we could make a solution that doesn't require one?

**Comment by rarkins** [comment]
One possibility is that you can use your own hosted presets instead of our ones, as then there will be no need to access github.

**Comment by viceice** [comment]
I think we should document `GITHUB_COM_TOKEN`  as requirement for self-hosted renovate

**Comment by JustArchi** [comment]
I'm also wondering if `GITHUB_COM_TOKEN` is really required, to the best of my knowledge it's used only for increasing limits, and preset in this case would be a single request across whole renovate's bot running, at least for our own case.

Wouldn't it make sense for renovate to at least try accessing the github resources without token, and failing if the rate limit has been reached?

**Comment by JustArchi** [comment]
For the reference, adding `GITHUB_COM_TOKEN` has fixed the issue for us, thank you for your asistance.

I'm leaving this issue open until you decide that it's no longer needed. I believe that it's at least worth checking if the token is really needed, as I believe for this specific use-case it'd be just one request per unique preset at maximum, and that shouldn't hit any sort of rate-limiting, even without any token.

**Comment by rarkins** [comment]
It is very easy to trigger GitHub's rate limits if you have no token, so this means you get no release notes. By adding the token, you should also see the benefit of release notes being added to all open source MRs.

**Comment by JustArchi** [comment]
I realize the limits are pretty low, but in case I've decided to disable release notes and guarantee that all repos have one single `config:base` preset, it'd still equal just one request for a whole run, right?

I mean, I'd prefer renovate to optimize the amount of requests sent (which is a good coding practice, regardless if token or not), and attempt to do what it's configured to do without a token - if it hits rate limit, it'd state it in the logs (perhaps even with an instruction of adding token to config) and run exactly the same as without one. This way if GitHub really rate-limits the user running renovate, it's on him to add the token, realizing that it's truly needed, as opposed to enforcing the token on all setups, even those that make a single request for base preset across whole run.

**Comment by rarkins** [comment]
Renovate does attempt to fetch the preset regardless of whether the token is set. If it's failing, it's because the IP address has already tripped the API limits (either by Renovate or any other tool that makes queries).

**Comment by JustArchi** [comment]
Okay, thanks, then I guess there is nothing else to improve on it, I'll close the issue, but feel free to re-open if you find a need, thanks again for your help ❤️.
