### ISSUE TITLE
Some wrong logging for flattened updates

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#6134]
![image](https://user-images.githubusercontent.com/1798109/81071406-f1e18d80-8ee4-11ea-826f-4f1507d22f76.png)

https://github.com/renovatebot/renovate/blob/aa38ddf4283eb2fb6299105e61829734a094118b/lib/workers/repository/updates/branchify.ts#L40-L43

Looks like `depName` is sometimes missing

**Comment by rarkins** [comment]
Could be lock file maintenance?

**Comment by viceice** [comment]
Maybe, couldn't see it because the repo run was to big for my terminal buffer 🙈

**Comment by hasanawad94** [comment]
@rarkins
Perhaps we should change the filter to only take strings that aren't empty?
The way it is now, it is not filtering strings having only white spaces

**Comment by hasanwhitesource** [comment]
@rarkins should this issue be resolved now ?

**Comment by rarkins** [comment]
Yes, next time you can add eg `Closes #1234` in your PR description to have it happen automatically
