### ISSUE TITLE
When checking the index of a Helm registry, the specified path is stripped

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#6150]
**What Renovate type are you using?**

WhiteSource Renovate App

**Describe the bug**

Given the following config; the _registryUrl_ is specified as `https://kubernetes.github.io/ingress-nginx/`. However, on inspection of the logs Renovate seems to ignore `/ingress-nginx/` and attempts to reach `https://kubernetes.github.io/index.yaml` instead of `https://kubernetes.github.io/ingress-nginx/index.yaml`.

I've attempted the same config with and without the trailing slash on the _registryUrl_.

```json
{
  "extends": ["config:base"],
  "regexManagers": [
    {
      "fileMatch": ["\\.yaml$"],
      "matchStrings": [
        "chart:\n *repository: (?<repository>.*?)\n *name: (?<depName>.*?)\n *version: (?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "helm"
    }
  ],
  "packageRules": [
    {
      "datasources": ["helm"],
      "managers": ["regex"],
      "packageNames": [
        "ingress-nginx"
      ],
      "registryUrls": ["https://kubernetes.github.io/ingress-nginx/"]
    }
  ]
}
```

**Did you see anything helpful in debug logs?**

#173578276
```json
DEBUG: Helm Chart not found
{
  "err": {
    "name": "HTTPError",
    "hostname": "kubernetes.github.io",
    "method": "GET",
    "path": "/index.yaml",
    "protocol": "https:",
    "url": "https://kubernetes.github.io/index.yaml",
...
```

**To Reproduce**

Reproduced [here](https://github.com/ChipWolf/renovate-6150).

**Comment by ChipWolf** [comment]
As a sidebar to this, I also use the registry `https://charts.bitnami.com/bitnami`, but it looks like they have a 301 redirect set up for `/index.yaml` to `/bitnami/index.yaml`.

**Comment by rarkins** [comment]
Relevant: https://github.com/renovatebot/renovate/blob/c1f9c416617ead3c2fb31c04a3190960aa9ca5cd/lib/datasource/helm/index.ts#L22

**Comment by rarkins** [comment]
It should work with a trailing slash. Your failing repo does not have one for example.

Test: https://runkit.com/embed/sktklrqjxrao

Drop the trailing slash and it fails like in your logs.

**Comment by ChipWolf** [comment]
I assume at that relevant line `repository` is equal to `https://kubernetes.github.io/` instead of `https://kubernetes.github.io/ingress-nginx/` for whatever reason.

**Comment by rarkins** [comment]
I'm not sure what you mean by that, but the reason the test I linked to is relevant is because of this: https://github.com/renovatebot/renovate/blob/c1f9c416617ead3c2fb31c04a3190960aa9ca5cd/lib/util/http/index.ts#L40

When there is no subdirectory, trailing slash is irrelevant to the result.

Based on code inspection, trailing slash should work. If you find it doesn't, please reproduce it so that we can debug.

**Comment by ChipWolf** [comment]
#173578276
```
      "baseUrl": "https://kubernetes.github.io/ingress-nginx/"
...
DEBUG: Helm Chart not found
{
  "err": {
    "name": "HTTPError",
    "hostname": "kubernetes.github.io",
    "method": "GET",
    "path": "/index.yaml",
    "protocol": "https:",
    "url": "https://kubernetes.github.io/index.yaml",
...

```

**Comment by rarkins** [comment]
OK, can you reproduce in a public repo so I can clone and test? https://github.com/HRZNStudio/playhrzn-k8s/blob/86179f592464fb769774bd3536fcf21232636b5c/renovate.json#L56 is still without trailing

**Comment by ChipWolf** [comment]
Ah yeah, I dropped that commit, will set up a repo.

**Comment by ChipWolf** [comment]
https://github.com/ChipWolf/renovate-6150 @rarkins

**Comment by ChipWolf** [comment]
Despite replicating the exact config on both repos, same failure on HRZNStudio/playhrzn-k8s, but works perfectly as expected on ChipWolf/renovate-6150

**Comment by rarkins** [comment]
Oh.. that’s maybe some caching I added today :(

It should cache bust whenever you commit to the base branch though

**Comment by rarkins** [comment]
Btw we can probably add a trailing slash anyway

**Comment by ChipWolf** [comment]
Yeah, I just committed some nonsense without modifying the config and it's back in working order now. Must've been the caching change.
Is this one resolved?

**Comment by JamieMagee** [comment]
Like Rhys said, we can deal with this more intelligently. I'll tag this as a bug. Thanks for the help getting to the root cause!

**Comment by rarkins** [comment]
https://github.com/renovate-reproductions/6150/pull/1
