### ISSUE TITLE
Support default versioning of datasources

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#6173]
**What would you like Renovate to be able to do?**
_regexManagers_ should default to the _versioningTemplate_ for the selected _datasourceTemplate_

**Describe the solution you'd like**
Instead of this:
```
{
  "extends": ["config:base"]
  "regexManagers": [
    {
      "fileMatch": ["^cloudbuild.yaml$"],
      "matchStrings": [
        "name: (?<depName>.*):(?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "docker",
      "versioningTemplate": "docker"
    }
  ]
}
```

I'd prefer this:
```
{
  "extends": ["config:base"]
  "regexManagers": [
    {
      "fileMatch": ["^cloudbuild.yaml$"],
      "matchStrings": [
        "name: (?<depName>.*):(?<currentValue>.*)\n"
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```

**Describe alternatives you've considered**
I've specified both the _datasourceTemplate_ and _versioningTemplate_ with the same value.

**Comment by rarkins** [comment]
Yes, this is a good idea. It's actually more general - any manager should be able to specify a datasource and have the default versioning used. I started a branch of this a month ago but never completed it.

**Comment by HonkingGoose** [comment]
> Yes, this is a good idea. It's actually more general - any manager should be able to specify a datasource and have the default versioning used. I started a branch of this a month ago but never completed it.

@rarkins I saw that you assigned this issue to yourself, but it's been a long time since we had meaningful movement on this issue, or at least it _seems_ that way from looking at the current issue.

Did you end up making any progress on this? Maybe you already fixed it somewhere else in the code but forget to close the issue?

I'll let you decide on the proper priority for this issue. 😉

**Comment by rarkins** [comment]
Yes, this is already implemented but I missed closing this issue. Example: https://github.com/renovatebot/renovate/blob/7fe97bfd2c9c811c2723cb441226a1d41fbd11b6/lib/datasource/docker/index.ts#L23
