### ISSUE TITLE
poetry pin deps get extra '=' in version

### ISSUE THREAD

**Issue by Trim21** [renovatebot/renovate#6189]
**What Renovate type are you using?**

github app

**Describe the bug**

when `"rangeStrategy": "pin"`, pinned version like `0.750` will be updated to `==0.770` instead of `0.770`

**To Reproduce**

pin: https://github.com/Trim21/renovate-mypy2/pull/4
non-pin: https://github.com/Trim21/renovate-mypy/pull/9

relatived issue: https://github.com/renovatebot/renovate/issues/6176

**Comment by rarkins** [comment]
I don't consider the addition of `==` to be a problem (assuming `0.770` and `==0.770` produce the same result), however `0.750` should be considered already pinned and not updated in the first place.
