### ISSUE TITLE
Update all Gradle Wrapper files

### ISSUE THREAD

**Issue by augi** [renovatebot/renovate#6197]
**What would you like Renovate to be able to do?**
Now, renovate updates just the `gradle/wrapper/gradle-wrapper.properties` file.

It would be great if it updated also `gradlew`, `gradew.bat`, and also `gradle/wrapper/gradle-wrapper.jar` files because they are also changed from time to time.

Unfortunately, I'm not aware of any authoritative endpoint (like [this](https://services.gradle.org/)) that provides these files for a specific version. The only way (I know) to obtain these files is to update the `gradle/wrapper/gradle-wrapper.properties` and then execute `./gradlew wrapper`.

**Comment by viceice** [comment]
see #5837, files should be updated if nessessary

**Comment by viceice** [comment]
Maybe you are also hit by #6187 ?
