### ISSUE TITLE
Renovate local dotnet-tools

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#6201]
**What would you like Renovate to be able to do?**
I would like to renovate repo local dotnet tools.

**Describe the solution you'd like**
I think this can be done by existing `nuget` manager? The `.config/dotnet-tools.json` json file is easy to read and i think we can use the autoreplace for that.
`nuget` datasource can be used for that too.

**Describe alternatives you've considered**
Maybe a regex manager can be used.

**Additional context**

https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use

*.config/dotnet-tools.json*
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "minver-cli": {
      "version": "2.0.0",
      "commands": ["minver"]
    }
  }
}
```

**Comment by fgreinacher** [comment]
Dup of https://github.com/renovatebot/renovate/issues/4816?

**Comment by viceice** [comment]
Sure
