### ISSUE TITLE
Renovate does not consider gradle.properties variable that are on a higher level in the file system

### ISSUE THREAD

**Issue by Nitrael86** [renovatebot/renovate#6220]
**What Renovate type are you using?**

WhiteSource Renovate App

**Describe the bug**

We have moved the version numbers for gradle to a gradle.properties file. Now if we use this variable in the same directory everything works. But as soon as the dependencies.gradle file is one level below, it no longer works.

Sample

source/gradle.properties  --> xxx_version=11.22.33.44
source/dependencies.gradle -->   OK
source/folder1/folder2/dependencies.gradle  --> NOK

**To Reproduce**

Create a gradle.properties file and a dependencies.gradle file in the same  folder. If this works, using the variable from the gradle.properties file in a dependencies.gradle file in a subfolder.

**Comment by ikesyo** [comment]
This is relevant code: https://github.com/renovatebot/renovate/blob/53ca91301f6a36c0c87e7d6b06b1bd8c9ec1b283/lib/manager/gradle/index.ts#L172

**Comment by rarkins** [comment]
This code has now changed a lot, so I'm going to close this. Happy to have it reopened or a replacement issue if someone can reproduce it today.
