### ISSUE TITLE
OS major version renovate

### ISSUE THREAD

**Issue by micheelengronne** [renovatebot/renovate#6252]
**What would you like Renovate to be able to do?**
I would like to be able to update my ubuntu OS version automatically through renovate.

For instance, bionic => eoan...

It could be generalized to multiple OS types.

**Describe the solution you'd like**
Using the regex manager, I would like to point to a bash variable that contains the OS version name and renovate it when a new version name arises.

**Describe alternatives you've considered**
A bash script using `postUpgradeTasks` but I lack a good datasource for that as I tweeted here:

https://twitter.com/MicheeLengronne/status/1261287994016874496

**Comment by viceice** [comment]
@micheelengronne Can you pleas fill the issue template completly

**Comment by rarkins** [comment]
I'm not sure how we'd do this if it's names instead of versions. Maybe a very custom version scheme?

**Comment by viceice** [comment]
Ubuntu also always have a version number, so we can check that.

@micheelengronne I think we have a issue for a Ubuntu datasource.

**Comment by micheelengronne** [comment]
You are right @viceice I will complete on this one https://github.com/renovatebot/renovate/issues/6060
