### ISSUE TITLE
variable substitution is wrong

### ISSUE THREAD

**Issue by robstoll** [renovatebot/renovate#6293]
**What Renovate type are you using?**
GitHub

**Describe the bug**
Variable gets replaced without adding quotes.

**To Reproduce**

See https://github.com/tegonal/atrium-ktor/pull/64/commits/f80b7ad5aa6f87263b9b0e547e053bf5cd834f77

**Comment by rarkins** [comment]
Please provide a clean reproduction repo we can test against

**Comment by robstoll** [comment]
Isn't the one above not good enough?

**Comment by rarkins** [comment]
No:
- It's an already merged commit
- There are multiple other PRs/updates for the same repo

An ideal reproduction has as much information as necessary to reproduce, and no more. e.g. 1 dependency and 1 PR, if that's all it takes

**Comment by robstoll** [comment]
Feel free to close the issue, it was easy to work around. 
For me it is too much work to provide you with a clean repo as you want.
But I can give you a short description on what you need to do:
```
git clone https://github.com/tegonal/atrium-ktor/`
git reset --hard c37b3d268d4bb2a1d5cf0114badc2d80e4f45ec4
```
push to a new repo and configure renovate
