### ISSUE TITLE
Add workaround for bitbucket's lazy ref creation

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/renovate#6294]
**What would you like Renovate to be able to do?**
Bitbucket server apparently [lazily generates pull request refs](https://jira.atlassian.com/browse/BSERV-12284) when pull requests are created. If renovate is running across enough repositories, this lazy ref generation backs up and if the CI for that branch gets kicked off before the lazy ref generation completes, the first CI fails because it is unable to perform a git fetch of that ref.

**Describe the solution you'd like**
I'm going to start with, yes I know this sounds like a hack... however it is the hack that Bitbucket actually suggests. 
After creating the PR, have renovate perform a GET request to $BASE_URL/projects/KEY/repos/slug/pull-requests/ID/merge which will then trigger the PullRequestService to update the refs. This is documented in the bitbucket bug as a work around which is where this idea comes from.

**Describe alternatives you've considered**
I think the alternative is the more "correct" solution... however we would be waiting months/years for it due to requirements. Basically, if Bitbucket provided an event that notifiied Webhooks that the Pull Request Ref has been created and all CI webhooks implemented this event listener we wouldn't need to force the creation of these pull request hooks.

However considering the number of projects/teams required to perform that solution (though not a bad idea to get started) I doubt that it's feasible. 

**Additional context**
I believe this applies to both bitbucket-server and bitbucket cloud. If I'm reading the code, it should be a pretty simple addition into [the bitbucket platform code](https://github.com/renovatebot/renovate/blob/master/lib/platform/bitbucket/index.ts#L768). I know it's not really Renovate's role but due to Bitbucket's implementation, i think it would be the easiest way to get a higher initial successful CI ratio... right now my success ratios are in the single digits for the first run.

I'm happy to make this change... this issue is mostly trying to figure out if this is palatable enough to open a PR for.

**Comment by rarkins** [comment]
Doesn’t the problem apply to all PRs created, and if so wouldn’t the plugin by Charles K be a more complete solution?

**Comment by viceice** [comment]
I know this problem too, but that should be fixed on ci side, not on renovate.

See bitbucket-branch-source-plugin#287 and jenkinsci/bitbucket-branch-source-plugin#294 for jenkins

**Comment by k2snowman69** [comment]
Thanks @viceice !
