### ISSUE TITLE
Npm aliased packages are removed from lockfile during unrelated update

### ISSUE THREAD

**Issue by frangio** [renovatebot/renovate#6303]
**What Renovate type are you using?**

GitHub App

**Describe the bug**

My package.json contains package aliases. Those aliased packages are being removed from package-lock.json in an update PR (that doesn't involve those dependencies at all).

The pull request is https://github.com/OpenZeppelin/solidity-docgen/pull/204.

This is the error in the CI run for Renovate's PR showing the dependencies that have been removed. The error is due to package.json and package-lock.json now being out of sync.

```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! Missing: solc-0-5@npm:solc@^0.5.14
npm ERR! Missing: solc-0-4@npm:solc@^0.4.24
```

**Did you see anything helpful in debug logs?**

I ran the same `npm install` commands locally on my computer and these packages weren't removed from the lockfile.

**To Reproduce**

I can't build a minimal reproduction because I don't know how to run renovate locally.

**Comment by rarkins** [comment]
Please provide more details about what specifically is wrong in the PR you linked to, e.g. which lines are the problematic ones?

Please also look into the logs via app.renovatebot.com for when the PR was created and paste in here the `npm` commands that were run during the update.

**Comment by frangio** [comment]
This line range is removed but should be left untouched: https://github.com/OpenZeppelin/solidity-docgen/pull/204/files#diff-32607347f8126e6534ebc7ebaec4853dL5356-L5574

The command that renovate is running is `node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit @oclif/plugin-help@3.0.1 @types/lodash@4.14.152 @types/node@10.17.24 @types/semver@7.2.0 codecov@3.7.0 typescript@3.9.3`

Trying a bit more I was now able to reproduce the bug. It didn't happen before because I had an existing `node_modules` directory (only containing my dependencies, nothing else). But if the directory isn't present, and I run the above command, I get the same result as renovate, and the aliased dependencies are deleted from the lockfile. So this does seem like an npm bug.

**Comment by rarkins** [comment]
What if you run the same command but omit `--package-lock-only` ? (removing `node_modules` first again)

**Comment by frangio** [comment]
Without `--package-lock-only` npm is also removing these packages from the lockfile.

**Comment by rarkins** [comment]
That’s a pity! Can you test if:
- it fails the same way if you run any one of the updates alone? Or
- it’s one particular package that is causing it?

Either way it may unfortunately need an npm CLI fix.

**Comment by frangio** [comment]
I migrated to Yarn as a workaround.

Reported to npm as https://github.com/npm/cli/issues/1369

**Comment by rarkins** [comment]
Thanks for the info. I'm going to close this because there's nothing we can do in the meantime, and nothing we need to do even once it's fixed, because we already adopt the latest `npm` each time anyway.
