### ISSUE TITLE
Can't use changelog in commit body template

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/renovate#6337]
**What Renovate type are you using?**

Hosted Github App

**Describe the bug**

I'm trying to use #5966 to put the release notes into the commit body, but I can't find a workable method. There's a bunch of stuff tried here: https://github.com/mikebryant/renovate-test-changelogjson/blob/master/renovate.json, with the output here: https://github.com/mikebryant/renovate-test-changelogjson/pull/2/commits/ab443397dd07cbb8612a747375f134512ce1565d

In particular:
- `releases` key isn't present.
- `upgrades` key isn't present.
- `logJSON` key isn't present.

**Did you see anything helpful in debug logs?**

**To Reproduce**

See https://github.com/mikebryant/renovate-test-changelogjson/blob/master/renovate.json

**Additional context**

I think the first two issues are because [lib/workers/pr/index.ts] is where they're generated, and that's not before branch/commit creation happens?

I think the latter issue (logJSON) is because it's not an allowed field in [lib/util/template/index.ts]

I'm not sure what the desired route forward would be - should the upgrade / releases field creation be moved up into the [lib/workers/repository/index.ts], where logJSON creation is? Or should logJSON (and all of the nested fields) be an allowed field?

**Comment by rarkins** [comment]
I think logJSON could be an allowed field.

**Comment by mikebryant** [comment]
Ok, thanks. I'll work on that

**Comment by mikebryant** [comment]
Been doing debugging, it's actually a deeper issue.

#5966 refactored things so that logJSON was set prior to compiling the commit message templates.

But then 6a8ceab6883cd0ba030f1cc4a3b21384ad73fc62 has refactored it again, back to being after. The commit messages are generated down inside `extractDependencies`, which is now before the call to generate the changelogs

**Comment by rarkins** [comment]
I don't actually remember why that change was made. I know that the changelog refactoring *had* caused problems so it was perhaps part of a few steps to fix those. However we do want to move that logic earlier again so that it can be used as part of the commit message.

**Comment by mikebryant** [comment]
I've been trying to figure out where best to move it to - currently I'm working on calling it in the middle of `branchifyUpgrades`, to be able to retain the concurrency.

Alternatively it could be moved inside `generateBranchConfig` - but then the changelog generation can't be concurrent on it's own - though maybe all of generateBranchConfig could be?

I'm not sure what would be best - do you have any thoughts on where you'd like it to sit?

**Comment by rarkins** [comment]
Changelog lookups currently takes a significant percentage of total time (e.g. ~20% of total) so it would ideally be done with concurrency. `branchifyUpgrades` uses a sequential `for` loop so putting it *inside* that would not yield concurrency. It might make most sense to put it inside the `extract` function right before `branchifyUpgrades`.

**Comment by mikebryant** [comment]
I tried in extract, but the actual conversion to the upgrades objects doesn't occur until inside branchify at the moment, and refactoring that looked more complicated. I think I've got it in between the two sequential loops in branchify though, so we should still get concurrency.

**Comment by mikebryant** [comment]
@rarkins I'm not sure what you need of me here? It still needs #6346 merged for this to work
