### ISSUE TITLE
Support configurable Composer version

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#6352]
Detect the best version of composer to user when binarySource=docker.

To decide
- Is it fast enough to dynamically install Composer? If so then we would decide which PHP base image to use and then install Composer
- Otherwise, we need to build every Composer version

**Comment by rarkins** [comment]
I'm unable to find any standardized way to specify which Composer version to install, so I think instead we should check the `composer.json` for a `php` constraint and use choose `renovate/php` instead, and then install Composer dynamically.

**Comment by viceice** [comment]
composer 1.10.0 add the used version to the lockfile

**Comment by rarkins** [comment]
> composer 1.10.0 add the used version to the lockfile

@viceice do you have a reference for that? I don't notice any version in some example lock files I tried

**Comment by viceice** [comment]
@rarkins  see [1.10.0](https://github.com/composer/composer/releases/tag/1.10.0)

![image](https://user-images.githubusercontent.com/1798109/86434671-53b04f00-bcfe-11ea-8dd4-96c6aaba9c07.png)

Test repo: https://github.com/viceice/composer-test
https://github.com/viceice/composer-test/blob/bef51381cb72470caa703207314d831dd95868ea/composer.lock#L61

**Comment by rarkins** [comment]
It doesn't make it very easy for us. We will need to manually track which versions `1.1.0` stands for and note if it changes?

**Comment by viceice** [comment]
🤔 This will currently only allow to distiguish major versions. i've not found any mapping from api version to composer version.

**Comment by rarkins** [comment]
I'm wondering if for now it means we leave this one as Blocked and instead focus on https://github.com/renovatebot/docker-php/issues/7 so that we can pick the correct PHP version instead

**Comment by viceice** [comment]
yes, good idea

**Comment by viceice** [comment]
we can check the require section. some user add `composer` there.

**Comment by rarkins** [comment]
Great, that will do - we can then support both PHP and Composer versions dynamically as originally planned.

**Comment by viceice** [comment]
We can check the `plugin-api-version` as fallback to distiguish between major versions, when composer v2 will be released

**Comment by kochen** [comment]
@viceice @rarkins Is this one obsolete?
now that we updated to `composer v2`.

**Comment by viceice** [comment]
@kochen No, as we plan to support the required php version if there are any deps on that. Also installing xomposer on the fly seems to be very fast. so we can switch to a mode like we already do on node, where we install npm / yarn / pnpm and lerna on the fly.

**Comment by mbrodala** [comment]
Not sure what the latest status here is but are there plans to make the Composer version configurable? Aside from a few known issues on our side (mostly outdated / not yet updated Composer plugins) the bump to Composer 2.x also leads to unnecessarily large `composer.lock` changes. (Using `update-lockfile` as `rangeStrategy`)

**Comment by viceice** [comment]
you should be able to pin composer by adding a explicit dependency to `composer/composer` package

**Comment by rarkins** [comment]
This now supported: https://github.com/renovatebot/renovate/blob/d8d26a1abafd5c2776dd6563d9e60e074e1514df/lib/manager/composer/artifacts.ts#L133

**Comment by mbrodala** [comment]
@rarkins What exactly does this mean? How can one enforce a specific Composer version from now on?

**Comment by rarkins** [comment]
The logic for extracting compatible Composer version is here: https://github.com/renovatebot/renovate/blob/d8d26a1abafd5c2776dd6563d9e60e074e1514df/lib/manager/composer/utils.ts#L20-L48

**Comment by mbrodala** [comment]
OK, to spell it out: a regular project should do a `composer require composer-runtime-api:^1.0` to force Composer 1.x on Renovate. With `composer-runtime-api:^2.0` or nothing, Composer 2.x will be used.

**Comment by viceice** [comment]
You can also depend on composer directly to pin to a specifc composer version. see L31-L36

**Comment by mbrodala** [comment]
True, but that's not an option for regular projects. ;-)
