### ISSUE TITLE
Support limiting concurrent requests per host

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#6358]
**What would you like Renovate to be able to do?**

Provide a configurable way and sensible defaults for concurrent limits per host.

**Describe the solution you'd like**

Implement it in the util/http logic. Mostly it should just work, but users can tweak it using hostRules. 

**Describe alternatives you've considered**

Today we try to rate limit by manager and package file, etc. It would be easier to have full concurrency of those and rely on the http layer to do rate limiting instead.

**Comment by rarkins** [comment]
- [ ] New option for `hostRules` called `concurrentRequestLimit`
- [ ] If unconfigured or set to `0` then there's no limit (same behaviour as today)
- [ ] Otherwise, maintain a count of outstanding requests per-host, as well as a queue of waiting requests
- [ ] When responses (or errors) are received then start the next queued job if found, or decrement the count if none

**Comment by glavoie** [comment]
@rarkins, I'm looking at the attached PR and I'm wondering if calls to the GitHub API are also done concurrently (to fetch tags/releases for example) today? 

If yes, would this change help throttling the API calls?

Our on-prem Renovate setup started triggering the GitHub Abuse Detection Mechanism a lot recently: 
```
16:13:54           "body": {
16:13:54             "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
16:13:54             "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
16:13:54           },
16:13:54           "message": "Response code 403 (Forbidden)",
```

We also hit that problem with some other internal tools doing concurrent requests and it appears that GitHub may now be more sensitive to it: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#abuse-rate-limits

**Comment by rarkins** [comment]
@glavoie please raise a separate issue, otherwise this one will diverge into unrelated topics if I'm to answer you fully
