### ISSUE TITLE
Unable to pin mcr.microsoft.com/windows docker images

### ISSUE THREAD

**Issue by donny-dont** [renovatebot/renovate#6388]
**What Renovate type are you using?**

Currently using the open source Renovate GitHub app at https://github.com/WebKitForWindows/docker-webkit-dev to pin docker versions in our base images.

**Describe the bug**

RenovateBot is unable to pin `mcr.microsoft.com/windows` images.

Recently Microsoft released the 2004 update for Windows 10 so I added a Dockerfile that referenced `mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-2004` without a SHA . RenovateBot opened https://github.com/WebKitForWindows/docker-webkit-dev/pull/69 which pinned that digest. The commit https://github.com/WebKitForWindows/docker-webkit-dev/commit/b93c0e750fa1ad8a7e38bdc0f1703ca9adb9b42f also added a Dockerfile that referenced `mcr.microsoft.com/windows:2004`. No PR for pinning was ever sent for it.

**Did you see anything helpful in debug logs?**

In https://app.renovatebot.com/dashboard#github/WebKitForWindows/docker-webkit-dev/183010608 its definitely trying to figure out the SHA but just can't.

**To Reproduce**

Add a Dockerfile referencing `mcr.microsoft.com/windows` and try and pin its digest.

**Comment by HonkingGoose** [comment]
Just asking here, do we have enough to start work with the basic reproduction of:

> Add a Dockerfile referencing `mcr.microsoft.com/windows` and try and pin its digest.

Or do we need a reproduction repository, or are we waiting on something else?

I'm asking because the only thing that changed on this issue is that we've been labeling it a lot, but not really making any progress on it. 😄

**Comment by viceice** [comment]
I think this should work with latest renovate.

ref: #8450  #8474

**Comment by viceice** [comment]
verified, works: https://github.com/viceice-tests/docker-manifest-list/pull/6

linux docker job fails as expected
