### ISSUE TITLE
The "renovate/verify" status check sometimes fails to be set

### ISSUE THREAD

**Issue by jspenguin2017** [renovatebot/renovate#6416]
**What Renovate type are you using?**

GitHub marketplace app. 

**Describe the bug**

The `renovate/verify` status check sometimes fails to be set. Example PR with this issue: 

https://github.com/jspenguin2017/SimpleGitGUI/pull/112

I'm confident that my config is correct, but here are my config files just in case: 

https://github.com/jspenguin2017/Config/blob/master/renovate/package.json
https://github.com/jspenguin2017/SimpleGitGUI/blob/master/renovate.json

**Did you see anything helpful in debug logs?**

In the job log, it looks like Renovate tried to set the status check, but I'm not sure why the actual PR doesn't have it: 

https://app.renovatebot.com/dashboard#github/jspenguin2017/SimpleGitGUI/183885623

**To Reproduce**

I don't have a specific reproduction steps, but I've been experiencing this issue from time to time starting last month (maybe 2 to 3 weeks ago). From my experience, it tend to happen more often to private repos. 

**Additional context**

It doesn't happen every time but it has been happening from time to time for a few weeks. I checked Renovate's code, and I can't figure out why this is happening. I'm assuming that the GitHub API is sometimes wonkey. Maybe have Renovate to double-check the PR when a rebase is requested manually?

**Comment by rarkins** [comment]
This feature was deprecated during our last major release. Please run the [renovate-config-validator](https://github.com/renovatebot/renovate/blob/a0b23148442e274a7a7e5dcdb330f977b2b42d84/package.json#L7) command that ships with Renovate if you need to validate a config.
