### ISSUE TITLE
Can't run under react native repositories

### ISSUE THREAD

**Issue by yangm97** [renovatebot/renovate#6427]
**What Renovate type are you using?**

Renovate Pro (self hosted)

**Describe the bug**

It seems like renovate doesn't run `yarn` before running the gradlew command, resulting in errors due missing files.

**Did you see anything helpful in debug logs?**

```
DEBUG: Start gradle command (repository=mycompany/app/react)
       "cmd": "./gradlew --init-script renovate-plugin.gradle renovate"
 WARN: Gradle command ./gradlew --init-script renovate-plugin.gradle renovate failed. Exit code: 1. (repository=mycompany/app/react)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "./gradlew --init-script renovate-plugin.gradle renovate",
         "stdout": "",
         "stderr": "\nFAILURE: Build failed with an exception.\n\n* Where:\nSettings file '/tmp/renovate/gitlab/mycompany/app/react/android/settings.gradle' line: 2\n\n* What went wrong:\nA problem occurred evaluating settings 'mycompany'.\n> Could not read script '/tmp/renovate/gitlab/mycompany/app/react/node_modules/react-native-unimodules/gradle.groovy' as it does not exist.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 1s\n",
         "message": "Command failed: ./gradlew --init-script renovate-plugin.gradle renovate\n\nFAILURE: Build failed with an exception.\n\n* Where:\nSettings file '/tmp/renovate/gitlab/mycompany/app/react/android/settings.gradle' line: 2\n\n* What went wrong:\nA problem occurred evaluating settings 'mycompany'.\n> Could not read script '/tmp/renovate/gitlab/mycompany/app/react/node_modules/react-native-unimodules/gradle.groovy' as it does not exist.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 1s\n",
         "stack": "Error: Command failed: ./gradlew --init-script renovate-plugin.gradle renovate\n\nFAILURE: Build failed with an exception.\n\n* Where:\nSettings file '/tmp/renovate/gitlab/mycompany/app/react/android/settings.gradle' line: 2\n\n* What went wrong:\nA problem occurred evaluating settings 'mycompany'.\n> Could not read script '/tmp/renovate/gitlab/mycompany/app/react/node_modules/react-native-unimodules/gradle.groovy' as it does not exist.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 1s\n\n    at ChildProcess.exithandler (child_process.js:294:12)\n    at ChildProcess.emit (events.js:198:13)\n    at ChildProcess.EventEmitter.emit (domain.js:448:20)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)"
       }
 INFO: Aborting Renovate due to Gradle lookup errors (repository=mycompany/app/react)
 INFO: Registry error - skipping (repository=mycompany/app/react)
 INFO: Finished repository (repository=mycompany/app/react)
```

**To Reproduce**

I suppose it's enough to create a react native app from the boilerplate though I haven't tried reproducing that way just yet. As it can be inferred from the logs above, this app uses unimodules, as it used to be an expo managed app which is now ejected. So maybe we would have better luck starting from expo and then ejecting.

**Additional context**

Perhaps a generic solution for this issue would be creating a `preUpgradeTasks`, just like `postUpgradeTasks`. But maybe we want Renovate to "just work" with multiple, interdependent package providers, such as all package managers such as `yarn/npm install`, `pod install`, etc. get triggered before proceeding to the next steps in the upgrade process?

**Comment by rarkins** [comment]
I don't think this is a pre *upgrade* issue, isn't it a pre *extract* issue? I think having to do a full install of yarn/pod/etc just to extract Gradle dependencies is something we should try to avoid. Are you Gradle dependencies *changed* in any way based on the results of running yarn? Or is the only reason to run it just so that our gradle command doesn't error?

**Comment by yangm97** [comment]
> Or is the only reason to run it just so that our gradle command doesn't error?

Precisely. 

For instance, [react-native-unimodules](https://github.com/unimodules/react-native-unimodules):

> ## 🤖 Configure Android
> 
> **In `android/settings.gradle`**
> 
> 1. At the top add `apply from: '../node_modules/react-native-unimodules/gradle.groovy'`
> 1. Then call `includeUnimodulesProjects()` on the next line.
> 

This makes gradle commands depend, at very least, on a `yarn/npm install` to precede them.

**Comment by rarkins** [comment]
@yangm97 I have another idea I'd like to try. Can you get me a confirmed reproduction repo I can use?

**Comment by rarkins** [comment]
To clarify: a public repository which fails as you describe. I've tried a few including the react-native-unimodules and it doesn't.

**Comment by yangm97** [comment]
Managed to reproduce at: https://github.com/yangm97/renovate-rn-repro

https://app.renovatebot.com/dashboard#github/yangm97/renovate-rn-repro/185559544

```
WARN: Gradle extraction failed
{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/yangm97/renovate-rn-repro\":\"/mnt/renovate/gh/yangm97/renovate-rn-repro\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -w \"/mnt/renovate/gh/yangm97/renovate-rn-repro/android\" renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\n\nFAILURE: Build failed with an exception.\n\n* Where:\nSettings file '/mnt/renovate/gh/yangm97/renovate-rn-repro/android/settings.gradle' line: 3\n\n* What went wrong:\nA problem occurred evaluating settings 'myNewProject'.\n> Could not read script '/mnt/renovate/gh/yangm97/renovate-rn-repro/node_modules/react-native-unimodules/gradle.groovy' as it does not exist.\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 33s\n"
}
```

**Comment by rarkins** [comment]
There’s a new release of Pro (now renamed) that syncs up Renovate versions. I’ll check out the repo, thanks

**Comment by rarkins** [comment]
@yangm97 if you're still using Renovate and having a problem with this, can you test if the new `gradle-lite` manager satisfies your requirements? Enable it by adding `:enableGradleLite` to your presets and switch to it permanently by disabling the previous `gradle` manager with `:switchToGradleLite`

**Comment by yangm97** [comment]
Thank you for looking into this! And sorry for the delay in getting back to you...

I can confirm `:switchToGradleLite` makes the error go away and I now see some renovations from gradle dependencies happening, both from the reproduction repo and the one in which I first noticed the issue.

However I do wonder, what's the difference from `gradle` to `gradle-lite`?

**Comment by rarkins** [comment]
The gradle manager uses gradle itself to extract dependencies so if gradle fails to load then it doesn't work at all. 

Gradle-lite uses JS parsing of files so is faster and more robust, although may miss some edge cases. We will switch to it by default soon.
