### ISSUE TITLE
Fix aliases validation

### ISSUE THREAD

**Issue by adusumillipraveen** [renovatebot/renovate#6428]
Unable to make aliases work for helm requirements, have tried few settings like :

```
{
  "helm-requirements": 
    {
      "enabled": true,
      "fileMatch": ["\\Chart.yaml|requirements.yaml$"]
    },
   "aliases": {
        "stable": "https://kubernetes-charts.storage.googleapis.com/"
      }
}
```

and 

```
{
  "helm-requirements": 
    {
      "aliases": {
        "stable": "https://kubernetes-charts.storage.googleapis.com/"
      },
      "enabled": true,
      "fileMatch": ["\\Chart.yaml|requirements.yaml$"]
    }
}
```

### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?
GitHub.com

### Have you checked the logs? Don't forget to include them if relevant
INFO: Found renovate config errors
```
{
  "errors": [
    {
      "depName": "Configuration Error",
      "message": "Invalid configuration option: aliases.stable"
    }
  ]
}
```
INFO: Repository has invalid config
```
{
  "error": {
    "configFile": ".github/renovate.json",
    "validationError": "The renovate configuration file contains some invalid settings",
    "validationMessage": "Invalid configuration option: aliases.stable"
  }
}
```

### What would you like to do?

An example of how to configure aliases for helm-requirements will be very helpful

**Comment by rarkins** [comment]
I think the solution is to add `aliases` awareness to https://github.com/renovatebot/renovate/blob/master/lib/config/validation.ts

We should check:
- aliases is an object
- The object is one deep
- values of each field are valid URIs

**Comment by adusumillipraveen** [comment]
@rarkins It isn't working unfortunately. It just goes to the next step. 
Config in logs:

```
DEBUG: Found .github/renovate.json config file
DEBUG: Repository config
{
  "configFile": ".github/renovate.json",
  "config": {
    "helm-requirements": {
      "enabled": true,
      "fileMatch": [
        "\\Chart.yaml|requirements.yaml$"
      ]
    },
    "aliases": {
      "hmctspublic": "https://hmctspublic.azurecr.io/helm/v1/repo/",
      "hmctsprivate": "https://hmctsprivate.azurecr.io/helm/v1/repo/"
    }
  }
}
```

But it doesn't upgrade hmctspublic charts, instead skips them with `"skipReason": "placeholder-url",` . I am suspecting the actual config is not getting till the manager https://github.com/renovatebot/renovate/blob/master/lib/manager/helm-requirements/extract.ts#L60  . I am traversing through the code to find, but any leads will be appreciated

DEBUG: packageFiles with updates
{
  "config": {
    "helm-requirements": [
      {
        "packageFile": "charts/demo-chart/requirements.yaml",
        "manager": "helm-requirements",
        "deps": [
          {
            "depName": "nodejs",
            "currentValue": "~1.8.0",
            "registryUrls": [
              "@hmctspublic"
            ],
            "skipReason": "placeholder-url",
            "depIndex": 0,
            "updates": []
          }
        ],
        "datasource": "helm"
      },
      {
        "packageFile": "charts/demo-chart/Chart.yaml",
        "manager": "helm-requirements",
        "deps": [
          {
            "depName": "nodejs",
            "currentValue": "~1.8.0",
            "registryUrls": [
              "@hmctspublic"
            ],
            "skipReason": "placeholder-url",
            "depIndex": 0,
            "updates": []
          },
          {
            "depName": "java",
            "currentValue": "~1.8.0",
            "registryUrls": [
              "@hmctspublic"
            ],
            "skipReason": "placeholder-url",
            "depIndex": 1,
            "updates": []
          },
          {
            "depName": "postgresql",
            "currentValue": "8.0.0",
            "registryUrls": [
              "https://kubernetes-charts.storage.googleapis.com/"
            ],
            "depIndex": 2,
            "updates": [
              {
                "fromVersion": "8.0.0",
                "toVersion": "8.6.4",
                "newValue": "8.6.4",
                "newMajor": 8,
                "newMinor": 6,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "2020-06-04T14:29:36.969Z"
              }
            ],
            "warnings": [],
            "sourceUrl": "https://github.com/bitnami/bitnami-docker-postgresql",
            "homepage": "https://www.postgresql.org/"
          }
        ],
        "datasource": "helm"
      }
    ]
  }
}

**Comment by rarkins** [comment]
Please raise a new issue, as it's a new problem.

Codewise, it's this:

```
if (dep.repository.startsWith('@')) {
        const repoWithAtRemoved = dep.repository.slice(1);
        const alias = config.aliases[repoWithAtRemoved];
        if (alias) {
          res.registryUrls = [alias];
          return res;
        }

        res.skipReason = SkipReason.PlaceholderUrl;
      }
```

Also, I suggest putting your `aliases` inside `helm-requirements`.

**Comment by adusumillipraveen** [comment]
> Please raise a new issue, as it's a new problem.
> 
> Codewise, it's this:
> 
> ```
> if (dep.repository.startsWith('@')) {
>         const repoWithAtRemoved = dep.repository.slice(1);
>         const alias = config.aliases[repoWithAtRemoved];
>         if (alias) {
>           res.registryUrls = [alias];
>           return res;
>         }
> 
>         res.skipReason = SkipReason.PlaceholderUrl;
>       }
> ```
> 
> Also, I suggest putting your `aliases` inside `helm-requirements`.

That seems to have done the trick. Thanks
