### ISSUE TITLE
Add PRs to GitHub Projects

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#6439]
**What would you like Renovate to be able to do?**

Support the option to add newly created PRs to GitHub Projects, similarly to how Assignees and Reviewers work.

**Describe the solution you'd like**

A configurable option to add one or more projects (including Organization projects) at PR creation. Should add them regardless of whether PR is automerging or not. Might need to support a project column option too?

**Describe alternatives you've considered**

Standalone bot for this.

ref: https://github.com/renovatebot/projects-bot/issues/1

**Comment by viceice** [comment]
Bot for moving issues on projects: https://github.com/apps/project-bot
