### ISSUE TITLE
Artifact errors are not propagated

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#6444]
Artifact failures are not propagated when branch status is `pending`
https://github.com/renovatebot/renovate/blob/59ea152087c22ef657b5321ede9235a652e5ee3f/lib/workers/branch/index.ts#L570

So the artifact status and comment checks should before the return event if pr is `pending` or `needs-pr-approval`.

**Comment by viceice** [comment]
I think we simply need to move the return checks below the artifact checks

**Comment by rarkins** [comment]
Do you mean prCreation=not-pending ?

**Comment by rarkins** [comment]
I think artifact errors are always “lost” if the PR isn’t created in the same run as the commit

**Comment by viceice** [comment]
maybe, but we can add artifact branch status before returning, so we can see the state after branch was created

**Comment by rarkins** [comment]
True

**Comment by rarkins** [comment]
Needs reproduction steps plus a plan of action.

I guess the reproduction is to create a repo with an update needed, prCreation=not-pending, and an intentionally failing test. We should see the PR created on the second run, but with no artifacts error comment or status check? Or is it just the comment which is missing?
