### ISSUE TITLE
GitLab: Renovate cannot merge without `CODEOWNERS` approval

### ISSUE THREAD

**Issue by toinehartman** [renovatebot/renovate#6473]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitLab.com

### Have you checked the logs? Don't forget to include them if relevant

The logs confirm that the MR merge is rejected.

### What would you like to do?

I would like to configure Renovate to automerge (non-major) updates. The only requirement is that the pipeline should pass.

For our repository, we set up `CODEOWNERS` approvals. Because `package.json` and `yarn.lock` are explicitly owned (as are all other files), the MR requires manual approval.

An obvious solution is to remove ownership of `package.json` and `yarn.lock`. As far as I'm aware, the [`CODEOWNERS`](https://docs.gitlab.com/ee/user/project/code_owners.html) syntax would require us to explicitly name each and every root-level directory or file (except the aforementioned two), making it cumbersome and error-prone. A solution like the following would be preferred but does not seem to be available.
```
* @me
!package.json
!yarn.lock
```

I would like help on the following possible solutions:
- Set Renovate as a `CODEOWNER` for the named files. Can Renovate be configured to approve its own MRs before merging?
- The `approval` value for the [prCreation](https://docs.renovatebot.com/configuration-options/#prcreation) config setting. This sounds like it could be useful, but is undocumented. What does this entail?

Thanks in advance.

**Comment by mrclrchtr** [comment]
I have exactly the same problem and would be very happy if there would be a possibility that the bot can approve his own MR.

**Comment by rarkins** [comment]
It needs to be worked out how Renovate can know that it needs to approve its own MR, and then when it should do it. e.g. is it something to detect once per-repo per-run, or does it need to be detected per-MR? And should it set the approval immediately after MR creation?

**Comment by viceice** [comment]
I think a better solution is to create a separate bot to do the approval, It can be triggered by repo pr pipeline.

**Comment by secustor** [comment]
I suggest the following: 
1. check approval rule API on the repo level. https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-project-level-rules  
1. If  any approval rules are defined --> approve merge requests using https://docs.gitlab.com/ee/api/merge_request_approvals.html#approve-merge-request
2. Continue with current logic

**Comment by SamuelCabralCruz** [comment]
I personally solved the problem by excluding dependency related files from CODEOWNERS like the following:
```
# CODEOWNERS prevent renovate automerge since it will automatically ask for review
# See documentation for more details: https://docs.renovatebot.com/automerge-configuration/
# Solution: make files used by renovate owned by everyone
**/*/go.mod
**/*/package.json
**/*/yarn.lock
```

**Comment by SamuelCabralCruz** [comment]
I don't know if it is of any help, but I personally solved the problem by excluding dependency related files from CODEOWNERS.

```
* @me

# CODEOWNERS prevent renovate automerge since it will automatically ask for review
# See documentation for more details: https://docs.renovatebot.com/automerge-configuration/
# Solution: make files used by renovate owned by everyone
**/*/go.mod
**/*/package.json
**/*/yarn.lock
```

Instead of using the negate, I simply assigned those file to nothing which is the equivalent of making them owned by everyone!

**Comment by matteosilv** [comment]
> @toinehartman I don't know if it is of any help, but I personally solved the problem by excluding dependency related files from CODEOWNERS.
> 
> ```
> * @me
> 
> # CODEOWNERS prevent renovate automerge since it will automatically ask for review
> # See documentation for more details: https://docs.renovatebot.com/automerge-configuration/
> # Solution: make files used by renovate owned by everyone
> **/*/go.mod
> **/*/package.json
> **/*/yarn.lock
> ```
> 
> Instead of using the negate, I simply assigned those file to nothing which is the equivalent of making them owned by everyone!

This cannot be accepted for our use case, e.g. upgrading flux HelmReleases. 

I think a call to the approve endpoint and some fine tuning can do the trick

**Comment by adam-moss** [comment]
Been looking at some issues today with automerge and this is affecting us too. Like @matteosilv changing the code owners to exclude the renovated files isn't a realistic option as that would, for example, remove all controls from `.gitlab-ci.ynl`

**Comment by Chibas** [comment]
Making owner for a file type doesn't exclude the folder owner, for some reason.
example
src/components/sample/ @team1
*.snap (also tried src/**/*.snap)

when you change src/components/sample/__test__/sample.js.snap, gitlab MR shows OPTIONAL *.snap, but requires approval from @team1 as the owner of src/components/sample/

**Comment by adam-moss** [comment]
Just looking at the API https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-configuration, seems there is an option `selective_code_owner_removals` which might just do the trick here, but I haven't had the chance to dig into it

**Comment by Chibas** [comment]
> 
That will just reset their approvals on changes.

It appeared that the owner applies by the last  rule in every single section. The solution is either to remove all sections or add this file type for every folder in this section and are everybody it’s owner. 
Example
`
[team1]
src/components @team1
src/services @team1

 [Excludes]
 *.snap
`
Solution 
`
[team1]
src/components @team1
src/services @team1
src/components/*.snap
src/services/*.snap

 [Excludes]
 *.snap
`

**Comment by MaxWinterstein** [comment]
Solution by @Chibas works fine, just adds some ugly warning:

![image](https://user-images.githubusercontent.com/5927148/231448939-e7cbdd58-f1e7-45c5-a1c1-d4b2f48c1a07.png)

But maaaaaaaaybe this will be fixed one day...

**Comment by rarkins** [comment]
Closing in favor of #6473
