### ISSUE TITLE
Same pull requests grouping

### ISSUE THREAD

**Issue by augi** [renovatebot/renovate#6474]
**What would you like Renovate to be able to do?**
It would be great if Renovate didn't open multiple pull requests that contain exactly the same change.

**Describe the solution you'd like**
Instead of creating multiple pull requests with exactly the same _source code_ change, create just one PR. In different words, group the same pull requests to a single one.

**Describe alternatives you've considered**
I don't see any alternative for this issue.

**Additional context**
Real worlds example is update of gRPC dependencies on [this project](https://github.com/avast/grpc-java-jwt/pulls?q=is%3Apr+is%3Aclosed).

It is a Gradle project and we have multiple dependencies on gRPC libraries so we extracted the gRPC version to a Gradle variable.
What happened is that Renovate opened 5 pull requests with exactly the same code change (changing the variable value):
 * https://github.com/avast/grpc-java-jwt/pull/94/files
 * https://github.com/avast/grpc-java-jwt/pull/95/files
 * https://github.com/avast/grpc-java-jwt/pull/96/files
 * https://github.com/avast/grpc-java-jwt/pull/97/files
 * https://github.com/avast/grpc-java-jwt/pull/98/files

Please note that we are also using Dependabot (your best bot friend in the world), and it created [just one PR](https://github.com/avast/grpc-java-jwt/pull/100) as expected.

**Comment by ikesyo** [comment]
ref: #4673

**Comment by HonkingGoose** [comment]
Could we fix this in a "band-aid" way by making a new group/mono-repo preset for the `gRPC` libraries? We don't currently group `gRPC` packages at all (but maybe that's for a good reason... 😄).

That way we might fix the immediate problem until we have time to fix it in a more proper global fashion?

**Comment by viceice** [comment]
Shouldn't this work with `gradle-lite` ?

**Comment by rarkins** [comment]
https://docs.renovatebot.com/modules/manager/gradle-lite/

**Comment by Churro** [comment]
PR https://github.com/renovatebot/renovate/pull/12534 added dependency grouping based on variable names by adding `dep.groupName = key` in `handleAssignment()`. 

As also visible in the initial reproduction repo, grouping now works as expected, e.g. https://github.com/avast/grpc-java-jwt/pull/386
