### ISSUE TITLE
Wrong parsing of nuget constraint

### ISSUE THREAD

**Issue by waghanza** [renovatebot/renovate#6487]
Hi,

**What Renovate type are you using?**

I'm using hosted version of `renovatebot`

**Describe the bug**

I have this
```json
{
        "packageFile": "fsharp/suave/suaveapp.fsproj",
        "manager": "nuget",
        "deps": [
          {
            "depType": "nuget",
            "depName": "Suave",
            "currentValue": "2.5.*",
            "datasource": "nuget",
            "skipReason": "not-a-version",
            "depIndex": 0,
            "updates": []
          }
        ]
      }
```
appearing on my logs.

However, `2.5.*` is a valid version constraint, like said at https://github.com/the-benchmarker/web-frameworks/pull/2922#discussion_r438276600

To verify, I have create a `F#` manifest, with :
+ `<PackageReference Include="Frank" Version="5.0.*" />` and I have **Frank/5.0.5**
+ `<PackageReference Include="Frank" Version="[5.0,5.1)" />` and I have **Frank/5.0.0**

Using X.Y.* is definitevely a version, despite what the doc is say at https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges.

However the doc specify also
> When using the PackageReference format, NuGet also supports using a floating notation, *, for Major, Minor, Patch,

Regards,

**Comment by rarkins** [comment]
Needs a change in https://github.com/renovatebot/renovate/blob/master/lib/versioning/nuget/index.ts

`2.5.*` is valid for npm's semver, however our nuget versioning is leaning on the `loose` versioning scheme. We can maybe add a specific exception case for this for now, even though it would be a little hacky.

**Comment by waghanza** [comment]
Actually `[2.5,2.6)` is the understood. However, this could lead to have `2.5.0` (even if **2.5.4** is available). 

Their is 2 solutions :
1. using 2 possibilities, `[2.5,2.6)` and `2.5.*`
2. using 1 possibility **only**, `2.5.*`

Both are working, according to what `renovatebot` purpose -> keeping dependency up-to-date

The first solution has the advantage to let user decide to use a `loose` dependency version or not.
The second solution force the use to keep to last `patch`

I'm in favour or the first since the `loose` choice is, afaic, a design choice

**Comment by olegkrivtsov** [comment]
I'd like to help with this one.

**Comment by rarkins** [comment]
Let's get a reproduction first, including lock file if it's relevant
