### ISSUE TITLE
Poetry: Trying to look up Python as dependency causes warning

### ISSUE THREAD

**Issue by janjagusch** [renovatebot/renovate#6500]
**What Renovate type are you using?**

Self-Hosted (v20.20)

**Describe the bug**

In the `pyproject.toml` file the required Python version is specified among actual Python packages in the tool.poetry.dependencies section (more details here: https://github.com/python-poetry/poetry/issues/2551). However, contrary to all other element in that section, Python is not a package. This means that renovate should not try to lookup "python" in the package index or update it.

Currently it does though, which causes the following warning.

```
Failed to look up dependency python
```

**Comment by rarkins** [comment]
Fixed by #6490 ?

**Comment by janjagusch** [comment]
Looks good to me, @rarkins. Looking forward to the merge.
