### ISSUE TITLE
Refactor: fs-extra -> gitfs

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#6617]
Replace use of `fs-extra` with our util fs wherever possible. Any reads/writes within a *repository* should use fs.

**Comment by rarkins** [comment]
Waiting on #6607

**Comment by rarkins** [comment]
We can maybe also add commands like `ensureCacheDir` if that represents the majority of remaining `fs-extra` use.

**Comment by zharinov** [comment]
Can this be closed?

**Comment by viceice** [comment]
nope, there are some imports left
![image](https://user-images.githubusercontent.com/1798109/87676466-f1813080-c778-11ea-8b40-93744aa04363.png)

**Comment by rarkins** [comment]
Also we proxied but didn't remove some?

I'm ok if we have some left as long as they're not worth changing.

**Comment by viceice** [comment]
yes, we didn't proxy `ensureDir`, also `gradle` and `gradle-wrapper` managers as using fs-extra directly

**Comment by zharinov** [comment]
Strange, I missed `ensureDir` proxying for bundler and cocoapods, will do PR soon

**Comment by zharinov** [comment]
For gradle/maven, I don't think it will make any sense, these are very specific

**Comment by rarkins** [comment]
The *main* reason for this was to make lazy git be able to be done later. So ones during artifacts update are late enough to not help there (we'd already have cloned)

**Comment by zharinov** [comment]
Okay, I'm just wondering did we cover all the cases needed for lazy git. Seems like it's tricky to get rid of `extra-fs` direct imports completely.

**Comment by rarkins** [comment]
I think we mostly have
