### ISSUE TITLE
[Maven] Mis-understood range in pom.xml

### ISSUE THREAD

**Issue by waghanza** [renovatebot/renovate#6619]
Hi @rarkins,

**What Renovate type are you using?**

+ Platform : https://github.com
+ Renovate : https://renovatebot.com

**Describe the bug**

The version `1.9.0` of `act` is out
https://search.maven.org/artifact/org.actframework/act/1.9.0/jar

As I am using https://github.com/the-benchmarker/web-frameworks/blob/839da5f0c8b7baf2aad1e36873bc0cfb470a74c6/java/act/pom.xml#L16, meaning from `1.8` to `1.9` where **1.9** is excluded, I expected `renovateot` to create a `PR` to update `act`

**Did you see anything helpful in debug logs?**

In log, I've found that `renovate` found  `Found 64 new versions for org.actframework:act-starter-parent in repository https://repo.maven.apache.org/maven2/`

Regards,

**Comment by rarkins** [comment]
Why do you think the range is misunderstood? Just an assumption? I don't see anything in the log line that confirms it as the root cause yet.

**Comment by waghanza** [comment]
I can see in the logs `DEBUG: Looking up org.actframework:act-starter-parent in repository https://repo.maven.apache.org/maven2/`, however I have not any `PR` from `renovate` that updates to **1.9**

As I understand http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html, `)` means excluded, then **1.9** is not in the above range. That's why their is a need for a `PR`

**Comment by waghanza** [comment]
PS : Feel free to change the title, the one I choose is just an assumption (and it could be more precise with the cause ;))

**Comment by rarkins** [comment]
What does the "packageFiles with updates" log message reveal?

**Comment by zharinov** [comment]
Here is what I'm getting for [org.actframework:act-starter-parent](https://repo1.maven.org/maven2/org/actframework/act-starter-parent/maven-metadata.xml) in debugger. With my test repo, it extends current range and creates this PR:
![image](https://user-images.githubusercontent.com/1239644/85946609-9e287900-b956-11ea-99a5-672dad5cdb8c.png)

**Comment by waghanza** [comment]
I have this now https://github.com/the-benchmarker/web-frameworks/pull/3053

@zharinov @rarkins everything is OK now

BTW, the range is not good for me, but this issue could be close

**Comment by rarkins** [comment]
Can you raise a New issue for better range creation? Ie so it's 1.10 not 1.9.0.1

**Comment by waghanza** [comment]
Of course

**Comment by waghanza** [comment]
@rarkins 

> What does the "packageFiles with updates" log message reveal?

```json
{
        "datasource": "maven",
        "packageFile": "java/act/pom.xml",
        "deps": [
          {
            "datasource": "maven",
            "depName": "org.actframework:act-starter-parent",
            "currentValue": "[1.8,1.9)",
            "fileReplacePosition": 541,
            "registryUrls": [
              "https://repo.maven.apache.org/maven2"
            ],
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": null
          }
        ],
        "parent": "java/pom.xml",
        "managerPackageFileList": [
          "java/act/pom.xml",
          "java/blade/pom.xml",
          "java/javalin/pom.xml",
          "java/jooby/pom.xml",
          "java/rapidoid/pom.xml",
          "java/spring-boot/pom.xml",
          "java/spring-framework/pom.xml",
          "java/struts2/pom.xml"
        ]
      },
```

The first time, but the second time I have

```json
{
        "datasource": "maven",
        "packageFile": "java/act/pom.xml",
        "deps": [
          {
            "datasource": "maven",
            "depName": "org.actframework:act-starter-parent",
            "currentValue": "[1.8,1.9)",
            "fileReplacePosition": 541,
            "registryUrls": [
              "https://repo.maven.apache.org/maven2"
            ],
            "depIndex": 0,
            "updates": [
              {
                "fromVersion": "1.8.33.0",
                "toVersion": "1.9.0.1",
                "newValue": "[1.8,1.9.0.1)",
                "newMajor": 1,
                "newMinor": 9,
                "updateType": "minor",
                "isSingleVersion": false,
                "isRange": true
              }
            ],
            "warnings": [],
            "sourceUrl": null
          }
        ],
        "parent": "java/pom.xml",
        "managerPackageFileList": [
          "java/act/pom.xml",
          "java/blade/pom.xml",
          "java/javalin/pom.xml",
          "java/jooby/pom.xml",
          "java/rapidoid/pom.xml",
          "java/spring-boot/pom.xml",
          "java/spring-framework/pom.xml",
          "java/struts2/pom.xml"
        ]
      },
```

everything is OK, perhaps I'm too impatient :stuck_out_tongue_closed_eyes:
