### ISSUE TITLE
Cannot update go.sum when corresponding go.mod has `replace` statement with relative path

### ISSUE THREAD

**Issue by astj** [renovatebot/renovate#6647]
**What Renovate type are you using?**

hosted app at GitHub

**Describe the bug**

When Renovate try to update gomod dependencies and the target go.mod has `replace` which replaces some module to relative path, Renovate fails to update go.sum.

example of go.mod: https://github.com/astj/renovate-sandbox-go-mod-replace/blob/7fa529bfa6960969c2d5d49ebcb54b63564500a4/module1/go.mod#L5

example of update failure: https://github.com/astj/renovate-sandbox-go-mod-replace/pull/2
I chose pkg/errors for this example, but this problem is irrelevant to which module to be updated.

NOTE: I believe this usage of `replace` in go.mod is not something magical in Go modules (ref: https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive), and is useful with monorepo.

**Did you see anything helpful in debug logs?**

log url: https://app.renovatebot.com/dashboard#github/astj/renovate-sandbox-go-mod-replace/197001801

**To Reproduce**

minimal repo to reproduce: https://github.com/astj/renovate-sandbox-go-mod-replace/

**Additional context**

Maybe this behaviour is caused by this replacement of `go.mod` contents:
https://github.com/renovatebot/renovate/blob/ec15985/lib/manager/gomod/artifacts.ts#L50-L53

With the replacement, the `go.mod` should be something like:

```go
module github.com/astj/renovate-sandbox-go-mod-replace/module1

go 1.14

// renovate-replace replace github.com/astj/renovate-sandbox-go-mod-replace/module2 => ../module2

require (
	github.com/astj/renovate-sandbox-go-mod-replace/module2 v0.0.0-00010101000000-000000000000
	github.com/pkg/errors v0.9.0
)
```

And with this `go.mod`, `go get -d ./...` will search `000000000000 ` revision from https://github.com/astj/renovate-sandbox-go-mod-replace, but it fails because such revision does not exist.

**Comment by rarkins** [comment]
As you've noticed, Renovate massages replace statements into comments. It is not really the absence of this replace statement that causes the problem though - it's the fact that the version it's replacing is invalid. If that version were valid, wouldn't it work?

I think we can maybe fix this specific reproduction by checking if the replacement path falls within the repository, and if so then *not* replacing it. However for the cases when the replacement falls outside the repo and we need to massage it, I think it's going to fail if the version it's replacing is invalid. Can you experiment with using a valid version instead of invalid?

**Comment by astj** [comment]
Sorry for late reply.

I've tried with some variants (see https://github.com/astj/renovate-sandbox-go-mod-replace/pulls?q=is%3Apr )

As you suggest, specifying real revision make renovate jobs pass! (with https://github.com/astj/renovate-sandbox-go-mod-replace/compare/4b97483ad5d7ba1b0309f53e84c571393ebc8a62...c5c5fc01fa4e079dc234feec08fdfc21e1b8af76 https://github.com/astj/renovate-sandbox-go-mod-replace/pull/3)

But, with that revision specification, Renovate treats the version specification differently than real usage:
- In real, module1 should depends on ../module2 of the same git revision
  - This is what `replace` directive does
- Renovate treats as if module1 depends on module2 of specified revision in `module1/go.mod`, which is intended to be ignored

The difference causes some inconsistent updates like:
- Unnecessary entry in `module1/go.sum` which points to module2 https://github.com/astj/renovate-sandbox-go-mod-replace/pull/3/files#diff-debe90dcd5ef6d31ed34d400daca1e17R1-R2
- On updating dependencies of module2, only `module2/go.sum` is updated but in fact `module1/go.sum` should be updated too https://github.com/astj/renovate-sandbox-go-mod-replace/pull/8
- On updating dependencies of module1, indirect dependency from module2 is removed from `module1/go.sum` if `gomodTidy` is enabled https://github.com/astj/renovate-sandbox-go-mod-replace/pull/9

Those updates may not be critical, but is not the best experience with Golang monorepo.

I suppose this replace behaviour is introduced to ignore out-of-repo reference https://github.com/renovatebot/renovate/issues/2596 .
So I'd like to request that Renovate keeps ignoring out-of-repository `replace` reference but does not ignore `replace` reference within the repository.

Thank you.

**Comment by rarkins** [comment]
I'm still not convinced that putting an *invalid* version is correct behavior, however I think we can do what you suggest without it being a problem:

- Instead of commenting out every `replace`, first look for relative references, resolve them, and check if they fall within the repository
- Leave the replace statements that fall within the repo, but continue commenting all others

**Comment by astj** [comment]
Thank you for consideration. For me it seems very nice!

ps: Hmm, Maybe my previous description around revisions was not good, sorry.
When using `replace` with relative paths, Go mod does not use CVS to resolve dependencies so the specified revision in `go.mod` is meaningless. (Even without any revision `v0.0.0` should work: https://github.com/golang/go/wiki/Modules#can-i-work-entirely-outside-of-vcs-on-my-local-filesystem )
For example, when `replace` is present in go.mod but corresponding `require` is not, `go get` adds `require` entry with artificial revision `000000000000`.

```
$ go get ./...
go: found github.com/astj/renovate-sandbox-go-mod-replace/module2 in github.com/astj/renovate-sandbox-go-mod-replace/module2 v0.0.0-00010101000000-000000000000
$ git diff
diff --git a/module1/go.mod b/module1/go.mod
index 000e4df..306a00f 100644
--- a/module1/go.mod
+++ b/module1/go.mod
@@ -5,5 +5,6 @@ go 1.14
 replace github.com/astj/renovate-sandbox-go-mod-replace/module2 => ../module2

 require (
+       github.com/astj/renovate-sandbox-go-mod-replace/module2 v0.0.0-00010101000000-000000000000
        github.com/pkg/errors v0.9.0
 )
```

**Comment by rarkins** [comment]
So do you think Renovate should skip replaced dependencies altogether, even if they have a valid version in the go.mod

**Comment by astj** [comment]
Yes, I think so.

**Comment by rajatagarwal** [comment]
We are facing a similar kind of issue. Is there any update on this ticket?

**Comment by MatthiasWinzeler** [comment]
we're hitting the same issue with our golang monorepo. Is there any way how we could give a hand?

**Comment by geoah** [comment]
Having this issue when using multiple modules in the same repo.
The structure is something like this:

* `/` is `package nimona.io`
* `/examples` imports `nimona.io v0.0.0` and has a `replace nimona.io => ../`
* `/apps` imports `nimona.io v0.0.0` and has a `replace nimona.io => ../`

Tried ignoring the package, and also disabling replace updates but without luck.

```
    {
      "matchPackageNames": ["nimona.io"],
      "enabled": false
    },
    {
      "matchDepTypes": ["replace"],
      "enabled": false
    }
```

**Comment by rarkins** [comment]
First of all, anyone is free to propose a solution and/or PR regarding this. 

But I'd like to understand: do you all have a *need* to specify a non-existing version in the go.mod? Eg why not specify a valid version that exists and let Renovate keep it up to date?

**Comment by MatthiasWinzeler** [comment]
> Eg why not specify a valid version that exists and let Renovate keep it up to date?

@rarkins I do not quite understand what you mean with that. 

The idea of referencing a neighbouring module in the same repo with `replace` is that it always references the version of the module which is in the same repo. 

So if the whole repo has a version (which in golang is specified with a git tag) v1, module a will implicitly specify v1 of module b, if the repo has tag v2, it will require v2 - it will always correspond to the 'current' version of the repo/the requiring module.

I think in the 'replace' case, the version number is actually not used at all - so that's why `v0.0.0-00010101000000-000000000000` or some other bogus version is put there.

**Comment by SamuelCabralCruz** [comment]
I just faced same issue.
Solved my problem using:
```
    {
      "groupName": "Backend - Ignore Monorepo",
      "matchPaths": ["backend"],
      "matchPackagePatterns": ["^<common module name>"],
      "enabled": false,
    },
`
``
Just replace with the proper <common module name> above.

**Comment by SamuelCabralCruz** [comment]
Finally, my reply above is wrong.
The way I succeed to fix is by specifying the "placeholder version" in the replace statement.

Example:

```
require (
    <common module name>/lib/core v0.0.0
)

replace <common module name>/lib/core v0.0.0 => ../lib/core
```

**Comment by eriksw** [comment]
@SamuelCabralCruz's fix worked for me too.

It would be great if renovate could either do this automatically (add the version from the require directive to the replace directive so that they match) or at least a hint about it in the error message.

**Comment by SamuelCabralCruz** [comment]
@eriksw Just to make it clear, I guess you are referring to my second approach right?

**Comment by eriksw** [comment]
@SamuelCabralCruz Correct. (No changes to the renovate config, just adding a matching version to the replace directive.)

**Comment by eriksw** [comment]
Hm, adding the false version cause problems for a downstream project. It complains that it can't fetch the invalid version.

    Repo A (monorepo):
        .../module alpha:
            (nothing interesting)
        .../module beta:
            relatively requires and replaces alpha using an invalid version

    Repo B:
        .../module gamma:
            requires beta. can't be built because the invalid version of alpha can't be retrieved.

**Comment by rarkins** [comment]
Now succeeds: https://github.com/renovate-reproductions/6647/pull/2
