### ISSUE TITLE
Artifacts coordinates translation configuration

### ISSUE THREAD

**Issue by adalgrim** [renovatebot/renovate#6656]
### What would you like to do?

I noticed that some artifacts published to private Nexus repository cannot be found because groupId translation into folder(s) is different than expected by Renovate.

Example:
There is a library com.acme.test:acme-logging:0.0.1 built with gradle and then published to Nexus (2.1.X)

Using sbt manager in Renovate this groupId is translated into the path like:
https://repositoryUrl/nexus/content/repositories/public/com/acme/test/acme-logging/0.0.1/

however renovate is looking for:
https://repositoryUrl/nexus/content/repositories/public/com.acme.test/acme-logging/0.0.1/
notice: **com.acme.test**

which ends with 404.

Is there a way to add additional pattern layout to check or to add the second one as a fallback for the first one?

**Comment by rarkins** [comment]
@zharinov is this correct behavior from us? I thought maven registries always used `/` separators.

@adalgrim can you give an example of the package file this is being extracted from?

**Comment by adalgrim** [comment]
@rarkins unfortunately I cannot give more specific example. 

However you can reproduce this. Create dummy library and publish it to local nexus. Then use 2 different managers for different projects: one where gradle will be used, the second one with sbt.

For gradle the dependency is updated but for sbt:
`{
                 "registryUrls": [
                   "https://repo.maven.apache.org/maven2",
                   "https://repositories.acme.com/nexus/content/repositories/deploy.milestones/",
                   "https://repositories.acme.com/nexus/content/repositories/3rd-party.releases.gradle-plugins/",
                   "https://repositories.acme.com/nexus/content/repositories/deploy.snapshots/"
                 ],
                 "depName": "com.acme.test:acme-logging",
                 "lookupName": "com.acme.test:acme-logging",
                 "currentValue": "1.0.6",
                 "datasource": "sbt-package",
                 "depIndex": 22,
                 "updates": [],
                 "warnings": [
                   {
                     "depName": "com.acme.test:acme-logging",
                     "message": "Failed to look up dependency com.acme.test:acme-logging"
                   }
                 ]
               },`

**Comment by zharinov** [comment]
Can't 404 error be caused by something else, as we're trying request [both slash- and dot-separated URLs](https://github.com/renovatebot/renovate/blob/master/lib/datasource/sbt-package/index.ts#L80)?

**Comment by rarkins** [comment]
@adalgrim if we try both approaches, is there actually any problem?

**Comment by adalgrim** [comment]
@rarkins the latest version works like a charm :) Thanks!
