### ISSUE TITLE
PR is not ready for merge - `"canMergeReason": undefined`

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/renovate#6699]
**What Renovate type are you using?**

Self-hosted via node against a Bitbucket v6.10.3 server

**Describe the bug**

When I run renovate across one of my repositories (the others seem to be fine) Renovate states that the `PR is not ready for merge` however the merge button is enabled and the merge API responds with canMerge: true

**Relevant debug logs**

```
DEBUG: Checking #1944 for automerge (repository=js/libs, branch=renovate/rollup-plugin-commonjs-13.x)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=js/libs, branch=renovate/rollup-plugin-commonjs-13.x)
DEBUG: PR is not ready for merge (repository=js/libs, branch=renovate/rollup-plugin-commonjs-13.x)
       "canMergeReason": undefined
```

I checked the code and it looks like it's making an api to the merge rest api in Bitbucket. It had this response:
```
{
  "canMerge": true,
  "conflicted": false,
  "outcome": "CLEAN",
  "vetoes": []
}
```

**To Reproduce**

I can provide the API responses so we can reproduce this in unit tests. This is a private server so I'm unsure how I would reproduce outside of the server.

**Comment by bytestream** [comment]
I had to set `requiredStatusChecks: null` because the repo had no tests and make sure the Renovate Bot user had permission to merge.

After looking over the code, the `"canMergeReason": undefined` error looks it can occur fairly easily. It could probably do with some improvement.
