### ISSUE TITLE
Publish using renovate??

### ISSUE THREAD

**Issue by mmkal** [renovatebot/renovate#6708]
**What would you like Renovate to be able to do?**

It'd be great if renovate could also be configured to go "the other way" - to release packages. What renovate currently does has a lot in common with a useful publishing flow.

Something that isn't possible without a patchwork of not-quite-ideal-tools, is semi-automated publishing. That is, publishing performed by a build server, but with a human in control of when it happens. Looking at the npm ecosystem:
- [semantic-release](https://npmjs.com/package/semantic-release) generates nice release notes and tags, but is optimised for a workflow where every commit to main gets published. It also doesn't understand monorepos without third-party libraries, and it doesn't include the package version in source control, which makes it hard to determine using git when a package version was released.
- [lerna](https://npmjs.com/package/lerna) has `lerna publish` and `lerna version` commands which understand conventional-commits, bump versions in monorepos, and generate changelogs. But it has the opposite problems to semantic-release, it's a little _too_ manual. It's optimised for a human running `lerna publish` from the command line. And it _only_ understands monorepos.
- [yarn v2](https://yarnpkg.com/features/release-workflow) has an experimental new release workflow, which involves updating a `.yarn/versions` yaml config. However as well as being experimental, there's also some manual work that needs to be done that really _should_ be done by a machine to generate the versions config, and only approved by a human.
- [RollingVersions](https://github.com/RollingVersions/RollingVersions) works similarly to the below flow, but is very new and adds another hosted, potentially-expensive dependency, at least for non-public repos.

Ideally renovate could do the following, assuming some kind of `"publish": true` config option is set (note: this definitely requires more thought, and there are edge cases that an initial version like this wouldn't cover. It assumes a js monorepo using lerna, since that can already do most of these tasks. But likely if this were to become a renovate feature something slightly lower-level than the lerna cli would be a better approach):

- when renovate runs, look for previous releases using git tags
- look at all the commits to the main branch since the last release
- analyse the commits to determine which packages have changed
- if there are changes, generate a changelog and calculate new versions for each package (likely, using conventional commits)
- push a git commit which edits package.json files (and changelog.md files, if applicable)
- open a `chore: release` PR with these changes, and update it as necessary if new commits go into main before it gets merged
- when it's merged, run the `publish` command (maybe `npm publish` by default, and overridable in renovate.json)
- after a successful publish, create tags for published versions and create a GitHub/GitLab release, using the calculated changelog as release notes

That way, publishing a new version doesn't involve a single person having the magic token that can publish to GitHub releases/npm - it's automated but still a deliberate action, which can only be performed by repository code owners. It also allows for performing checks before releasing. An example would be usage of [expiring-todo-comments](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/expiring-todo-comments.md#package-version), which can flag TODOs that should have been done before a particular version, as a lint failure. Violations would become visible and clearly actionable as a red X on a pull request. With most flows that exist now, it'd only be flagged _after_ the package is published.

**Did you already have any implementation ideas?**

lerna already does almost everything needed for this, so it might be possible to use it under-the-hood, at least for projects that already use it:

`lerna version --yes --no-git-tag-version --no-push` will bump version numbers, following the dependency graph within a repo, and generate changelog entries. This could be used to create the initial PR, with a little bit of reverse-engineering (get release notes and PR content by looking at the changelog.md git diff). Similarly `lerna publish` creates GitHub/GitLab releases already, but doesn't work properly if you've already created the changes with `lerna version --no-push`.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

I've experimented with a hacky GitHub Action which creates pull requests and merges them using something along the lines of the lerna commands above. But renovate is already really good at managing pull requests, git branches, rebasing, changelog parsing, etc. etc. And a lerna-based flow doesn't cover repos that don't use it (e.g. single-package repos, yarn-only monorepos, non-javascript repos). So even if only lerna repos were supported to begin with, it'd make sense if renovate could eventually abstract the implementation details, with a single configuration like `"publish": true`. That'd also allow for future features like being able to manually upgrade a minor bump to a major when a breaking change was accidentally not specified in the conventional commits, etc.

**Is this a feature you'd be interested in implementing yourself?**

Sure - but it's a fairly big feature request, so it'd depend on the renovate team being willing to maintain it!

**Comment by rarkins** [comment]
This is a really interesting idea. I'm not 100% sure that it should be *Renovate* doing it, but I agree that a lot of our concepts can be reused, and maybe this could be something spat out of the same monorepo as Renovate, for example. 

However, it's a pretty big wheel to be inventing or reinventing. I think releasing and updating are two sides of the same coin, and actually started work on https://github.com/apps/release long ago before realizing I needed to focus on Renovate as it's already got a lot of things still to do.

Have you seen https://github.com/googleapis/repo-automation-bots/tree/master/packages/release-please
