### ISSUE TITLE
Renovate for SBT updates version numbers of unrelated dependencies

### ISSUE THREAD

**Issue by ChristianMurphy** [renovatebot/renovate#6723]
**What Renovate type are you using?**

* Renovate Hosted for GitHub

**Describe the bug**

When updating one dependency renovate also bundles updates for other dependencies not listed in the description.
If those dependencies current version number happens to match the one being updated.

**Relevant debug logs**

Example PR: https://github.com/openequella/openEQUELLA/pull/1996
Logs for PR: https://app.renovatebot.com/dashboard#github/openequella/openEQUELLA/200872838

**To Reproduce**

Have `io.swagger:swagger-core` version `1.6.1` (with `1.6.2` available), ` dom4j:dom4j` version `1.6.1`, and `org.apache.ws.security:wss4j` version `1.6.19`

**Expected Results**

`io.swagger:swagger-core` is updated to `1.6.2`.
`dom4j:dom4j` and `org.apache.ws.security:wss4j` are not updated

**Actual Result**

`io.swagger:swagger-core` is updated to `1.6.2`.
`dom4j:dom4j` is updated to `1.6.2`.
`org.apache.ws.security:wss4j` is updated to `1.6.29`.

**Additional context**

**Comment by zharinov** [comment]
@ChristianMurphy, can you provide minimal reproduction `build.sbt`? Unfortunately, I can't reproduce it with my fork (after setting older versions).

**Comment by ChristianMurphy** [comment]
I'm not able to reproduce the issue currently, if it appears again, will open a new issue with a minimal repro.
Thanks for taking a look @zharinov!
