### ISSUE TITLE
GHE automerge not working for protected branches, even with push access

### ISSUE THREAD

**Issue by krohrsb** [renovatebot/renovate#6728]
**What Renovate type are you using?**

Self Hosted Whitesource Renovate -- Github Enterprise

**Describe the bug**

Renovate is still configured to not automerge if branch protection is enabled.

https://github.com/renovatebot/renovate/blob/ce8ce887d703215211fb4d753725c22efb2c4b4b/lib/platform/github/index.ts#L1619

Even if we give the Renovate Github Application access to push (along with repo admins etc)

**Relevant debug logs**

Still receive the error `Branch protection: Cannot automerge PR when push protection is enabled`

**To Reproduce**

Enable branch protection on `master` in Github Enterprise, have renovate work on an automergable PR/branch.

**Additional context**

Looks like it used to be this way for public github too, but was resolved here: https://github.com/renovatebot/renovate/issues/4460

I suppose i'm not sure why GHE needs this check still, i'm not familiar. Perhaps there was an API limitation?

![Screen Shot 2020-07-10 at 2 29 16 PM](https://user-images.githubusercontent.com/321544/87200432-c64e9b00-c2b9-11ea-9410-9afa8b7b50a1.png)

**Comment by rarkins** [comment]
GHE trails github.com in features and at the time of #4460 it still had the old problem. Sounds like we can remove the check now.

**Comment by krohrsb** [comment]
I suspected something like that. Thanks for confirming.

**Comment by rarkins** [comment]
Fixed in https://github.com/renovatebot/renovate/commit/9b8f010f99fef9d8514e9290f09f05ce81342d04 and will be available in the next WS Renovate release
