### ISSUE TITLE
baseBranches config is missing in documentations

### ISSUE THREAD

**Issue by EricMasonFa** [renovatebot/renovate#6755]
Hi, Thanks for your great product.
I'm using self-hosted Renovate, on a self-hosted GitLab.

I noticed although `baseBranches` config is working on self-hosted app, the config is missing in [docs](https://github.com/renovatebot/renovate/blob/master/docs/usage/self-hosted-configuration.md).

If the missing doc is not intentional, I'll create a pull request.

**Comment by viceice** [comment]
It's here: https://docs.renovatebot.com/configuration-options/#basebranches

Those options works for all renovate tools if not specified otherwise.

**Comment by EricMasonFa** [comment]
So [self-hosted-configuration](https://docs.renovatebot.com/self-hosted-configuration) are basically self-hosted-only configs in addition to all [configuration-options](https://docs.renovatebot.com/configuration-options/)! It's a bit ambiguous, I got that wrong.

Thanks.

**Comment by viceice** [comment]
Yes, that are additional options for self hosted renovate. Feel free to open a PR to add some general explanation to the docs. 🙃
