### ISSUE TITLE
Kubernetes: Reference/Display changelog when bumping docker image tag

### ISSUE THREAD

**Issue by linki** [renovatebot/renovate#6814]
**What would you like Renovate to be able to do?**

Renovate can already update Kubernetes manifests with new versions of the docker image specified ([docs](https://docs.renovatebot.com/modules/manager/kubernetes/)).

However, it doesn't reference the CHANGELOG when doing so.

**Did you already have any implementation ideas?**

The CHANGELOG is already referenced when bumping Golang dependencies ([example](https://github.com/googleapis/google-api-go-client/pull/579)).
It should do a similar thing when bumping docker images within Kubernetes manifests.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Don't know any.

**Is this a feature you'd be interested in implementing yourself?**

With some help getting started and an understanding of how it works for Golang I could give it try. It's probably trickier because going from the docker image tag to a git tag might be more ambiguous than in the pure git tag-based data sources.

**Comment by rarkins** [comment]
Unfortunately the main problem is that most Docker images don't specify their source repository in their metadata. For those that do (e.g. Renovate's own image), we try to locate release notes in the source repo. Choices are:

- File PRs with the upstream Docker projects so that they add source URL labels to their images, or
- Submit a PR here with manual source URL mappings: https://github.com/renovatebot/renovate/blob/008f781d42c5f2a4438ac840d0eb986d051aa6af/lib/datasource/metadata.ts#L44

**Comment by linki** [comment]
Thanks, I didn't know about source labels. I think's it a reasonable thing to do.

Are you talking about [these labels](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys) and specifically something like that in the Dockerfile?

```
LABEL org.opencontainers.image.source=https://github.com/renovatebot/renovate
```

Does it work with non-public GitHub Enterprise repositories as well in some way?

**Comment by rarkins** [comment]
Yes, that's what I'm referring to. To my knowledge that's the official way for a Docker image to reference it's source repository, which is what Renovate needs to know in order to fetch release notes. I believe it should work with non-public GHE repositories too, assuming it's the same as your configured `endpoint`

**Comment by linki** [comment]
I'll try that out and also check if can/should adopt some of those labels for our images in general.

What I meant regarding GitHub Enterprise is: we have several public images that public Renovate can find but the source repositories of them are private. In hindsight that looks like a weird use case.

But in general: Is there support in public Renovate to query private docker registry and private GitHub Enterprise instances? Or would you run Renovate on your own infrastructure in that case (if that's possible)?

**Comment by rarkins** [comment]
You can access private registries, using `registryUrls` if necessary and `hostRules` to add username/password or token. Check the config-help repo for lots of existing questions and discussions.

I'm not sure if it would work where "public" Renovate (you mean the hosted app?) can access a private GHE repository just for changelogs. Renovate may not be able to detect what type of host it is so never try.

**Comment by linki** [comment]
Thanks for clarifying that and the pointer to the config-help repo. Yes, with "public" I meant the hosted app.

**Comment by rarkins** [comment]
Also, are you OK that Renovate's PRs to public repos on github.com would then "leak" the changelogs of private GHE repos?

**Comment by linki** [comment]
I think that depends on the repository. So maybe that should be made configurable similar to how one can ignore certain dependencies.

**Comment by rarkins** [comment]
I think if you don't want to leak private information to public repositories then don't configure a token in the first place. It's quite an anti-pattern anyway.

**Comment by rarkins** [comment]
FYI in the hosted app when we generate a token for a public repo, we scope it to the current repo only, that way it cannot access any private repos within the same org and leak data. Whereas for private repos the token is scoped for the entire org, so that you can depend on and retrieve release notes from other private repos.

**Comment by insertjokehere** [comment]
Would it be worth while adding something to allow specifying a source URL in the renovate config? Being able to specify something like:

```
"packageRules": [
    {
      "packageNames": ["quay.io/wekan/wekan"],
      "sourceURL": "https://github.com/wekan/wekan"
    }
]
```
or
```
"sourceURLs": {
  "docker": {
    "quay.io/wekan/wekan": "https://github.com/wekan/wekan"
  }
}
```
Would solve my immediate problem if/until I can get upstream to add the label needed to get this picked up automatically

(not picking on Wekan specifically, just the first example I could find)

**Comment by viceice** [comment]
@insertjokehere You can already use `sourceUrl` in package urls to assign custom / missing source urls.

**Comment by viceice** [comment]
so this should work, see different `sourceUrl` casing.
```json
"packageRules": [
    {
      "packageNames": ["quay.io/wekan/wekan"],
      "sourceUrl": "https://github.com/wekan/wekan"
    }
]
```

**Comment by insertjokehere** [comment]
@viceice thanks for the tip, but I get `Invalid configuration option: packageRules[3].sourceUrl` when specifying this. I'll open a help issue to avoid taking this issue even further off topic

**Comment by viceice** [comment]
I'll send a PR soon to allow this

**Comment by AverageMarcus** [comment]
@viceice Did this ever get implemented? I've got quite a few docker images I'd like to be able to configure the source URL for.

**Comment by viceice** [comment]
this should already work as mentioned above. the manual sourceUrl override only works inside shared presets and can't be validated.

**Comment by AverageMarcus** [comment]
Is there any documentation on this? I wasn't able to find it but maybe I'm looking for the wrong thing?
When you say "only works in shared presets" does that mean I'm not able to just add `packageRules` to my `renovate.json` with this configuration?

**Comment by viceice** [comment]
> Is there any documentation on this? I wasn't able to find it but maybe I'm looking for the wrong thing?

no, as it's not a official feature.

> When you say "only works in shared presets" does that mean I'm not able to just add `packageRules` to my `renovate.json` with this configuration?

yes, normal renovate.json would cause a config error on validation.
