### ISSUE TITLE
make Pr.createAt availabe for prBody / prTitle

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#6825]
**What would you like Renovate to be able to do?**

Use the pr creation date in PR title or body.

see https://github.com/renovatebot/config-help/issues/764#issuecomment-662860229 for discussion.

https://github.com/renovatebot/renovate/blob/d6bfaa665f695e2788f19ead083621a66de05948/lib/platform/common.ts#L44

**Comment by rarkins** [comment]
It's a bit circular though. We need to decide a prTitle before the PR is created.

**Comment by viceice** [comment]
right 🤔
