### ISSUE TITLE
There is a problem with using config-validator when config file is json5

### ISSUE THREAD

**Issue by tyankatsu0105** [renovatebot/renovate#6858]
**What Renovate type are you using?**

**Describe the bug**
https://github.com/renovatebot/renovate/blob/master/lib/config-validator.ts#L49
This condition is not correct.
Unfortunately, when we use the config file as json5, the file is parsed with JSON.parse.

Correct is:
```diff
- if (file.endsWith('.json5)')) {

+ if (file.endsWith('.json5')) {
```

**Relevant debug logs**

**To Reproduce**

**Additional context**

**Comment by rarkins** [comment]
Closed in https://github.com/renovatebot/renovate/commit/f10cafbaad3900f97f2cf60bc43fbc65edadb768
