### ISSUE TITLE
Preset config versioning

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#686]
Currently we always fetch the "latest" on npmjs for a preset config. e.g. if the user configures `"docker:disable"` then we fetch the latest release of `renovate-config-docker`.

Instead, we should give users the *option* of pinning the version of presets in their project root `package.json > devDependencies` so that updates to them are raised as PRs with changelogs like any other dependency update, including `eslint` shared configs.

If a repository's renovate config references a particular preset package in its configuration, and that same package is versioned in devDependencies, then we find the highest matching version of it in the registry. Ignore whatever version is in the lock file though - we should encourage it to be pinned and not a range.

**Comment by rarkins** [comment]
Location: `devDependencies` of project root `package.json`
Relevant too: all `renovate-config-*` packages and `@*/renovate-config`
Probably should support semver

If a project references a particular preset package in its configuration, and that same package is versioned in devDependencies, then we find the highest matching version of it in the registry. Ignore whatever version is in the lock file.

Best way to use this is to pin the preset, obviously.

**Comment by ahmadnassri** [comment]
that's certainly useful to some ... and my first approach until recently!

in my use-case, we have TOO MANY `*-config` things to maintain, and we're looking to simplify the impact of a version bump / change on one `*-config` type package, with a potential 500+ upstream repos that rely on it...

the path we're now going is with removing all those from `devDependencies` and pre-installing them in our [docker base image](https://github.com/telus/build-essential/blob/master/Dockerfile#L16) used in CI/CD, you can see that image pre-installs a bunch of [`peerDependencies`](https://github.com/telus/build-essential/blob/master/package.json#L30-L40) to be used later in CI/CD steps through `npx`...

> _Note: using `peerDependencies` mainly because of `eslint`, all plugins, and configs, need to be either direct dependencies, or fully global_ 🤷‍♂️

**Comment by fgreinacher** [comment]
@rarkins I'm missing this feature for platform-hosted presets. As those seem to be the way forward (vs npm-hosted) should we update this issue to include platform-hosted scenarions, where the "version" could be a ref (branch, tag, commit) in the preset repo?

**Comment by rarkins** [comment]
Yes, we should work out a way to do this with git refs. It may require us to change our presets implementation a little first though

**Comment by rarkins** [comment]
Needs study of our current syntax and if we can gracefully accomodate git refs or at least tags

**Comment by suzuki-shunsuke** [comment]
This issue seems to be solved by https://github.com/renovatebot/renovate/pull/11565 .
