### ISSUE TITLE
Add possibility to add comments to json configuration

### ISSUE THREAD

**Issue by sebarthel89** [renovatebot/renovate#6874]
**What would you like Renovate to be able to do?**
Configurations are getting more complicated over time. It would be awesome to store some comments in configuration files.

**Did you already have any implementation ideas?**
For instance:
```
"packageRules": [
    {
      "_comment": "Merge all packages excluding major versions",
      "updateTypes": [
        "minor",
        "patch",
        "pin",
        "digest"
      ],
      "automerge": true
    },
```

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Didn't find anything yet

**Is this a feature you'd be interested in implementing yourself?**

Could do

**Comment by rarkins** [comment]
Try the "description" field. It is allowed in most configuration objects

**Comment by sebarthel89** [comment]
works! thanks for pointing me to this.
