### ISSUE TITLE
Passing repository-changed error up(branch="renovate/actions-checkout-2.x")

### ISSUE THREAD

**Issue by yurake** [renovatebot/renovate#6890]
**What Renovate type are you using?**

* hosted App
* GitHub

**Describe the bug**

Cannot push new branch for merge, response was `git-receive-pack (1157 bytes) error`.

**Relevant debug logs**

```DEBUG log
DEBUG: 2 file(s) to commit(branch="renovate/actions-checkout-2.x")
DEBUG: Committing files to branch renovate/actions-checkout-2.x(branch="renovate/actions-checkout-2.x")
DEBUG: Error commiting files(branch="renovate/actions-checkout-2.x")
{
  "err": {
    "task": {
      "commands": [
        "push",
        "origin",
        "renovate/actions-checkout-2.x:renovate/actions-checkout-2.x",
        "--force",
        "-u",
        "--no-verify",
        "--verbose",
        "--porcelain"
      ],
      "concatStdErr": true,
      "format": "utf-8"
    },
    "message": "Pushing to https://**redacted**@github.com/yurake/test-github-actions.git\nPOST git-receive-pack (1157 bytes)\nerror: failed to push some refs to 'https://**redacted**@github.com/yurake/test-github-actions.git'\n",
    "stack": "Error: Pushing to https://**redacted**@github.com/yurake/test-github-actions.git\nPOST git-receive-pack (1157 bytes)\nerror: failed to push some refs to 'https://**redacted**@github.com/yurake/test-github-actions.git'\n\n    at GitExecutorChain.onFatalException (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain. (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw ()\n    at rejected (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks ()\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
  }
}
DEBUG: Passing repository-changed error up(branch="renovate/actions-checkout-2.x")
INFO: Repository has changed during renovation - aborting
```
More Details:
https://app.renovatebot.com/dashboard#github/yurake/test-github-actions/209856338

**Comment by rarkins** [comment]
How long ago did you install the Renovate app?

GitHub put security restrictions in place preventing apps from pushing to Actions workflows but told me recently it should work now. However you need to have granted the permissions to Renovate to update workflows.

**Comment by yurake** [comment]
Thank you @rarkins. Installed a month ago. 
> However you need to have granted the permissions to Renovate to update workflows.

Would you tell me some instruction for granted?

**Comment by rarkins** [comment]
If you installed a month ago then there should be no permissions problem. Most likely answer is that there's still a restriction at GitHub's side. Can you reproduce this in a public repo to share?

**Comment by yurake** [comment]
Here is a test repo.
https://github.com/yurake/test-github-actions

**Comment by rarkins** [comment]
Can you simplify to a minimal reproduction? i.e. one actions dependency so one update and one branch? I prefer not to overwhelm GitHub with a complicated repo if I need to raise this fault with them.

**Comment by yurake** [comment]
I created simple one, this would be correct you want?
https://github.com/yurake/test-renovate

And renovate outcome debug logs
https://app.renovatebot.com/dashboard#github/yurake/test-renovate/210097288

**Comment by yurake** [comment]
I think this issue is same as #5733.
