### ISSUE TITLE
Docker image suffix not preserved

### ISSUE THREAD

**Issue by tuckbick** [renovatebot/renovate#6905]
**What Renovate type are you using?**

I am using the Whitesource On-Prem version of Renovate. (v21.6.6)

**Describe the bug**

Upon updating from `0.18.5` of Renovate Pro to `1.0.1` of Whitesource On-Prem, PRs to update our `node` docker image fail to include the suffix:

![Screen Shot 2020-08-03 at 5 21 43 PM](https://user-images.githubusercontent.com/230995/89236735-9c358380-d5ae-11ea-966d-c3b04059722f.png)

With version `0.18.5` of Renovate Pro, this updates to `node:12.18.3-alpine`. ✅ 
With version `1.0.1` of Whitesource On-Prem, this updates to `node:12.18.3`. ❌ 

**Relevant debug logs**

![Screen Shot 2020-08-03 at 5 37 38 PM](https://user-images.githubusercontent.com/230995/89237430-5da0c880-d5b0-11ea-9543-610b310ff0c7.png)
![Screen Shot 2020-08-03 at 5 35 36 PM](https://user-images.githubusercontent.com/230995/89237423-5a0d4180-d5b0-11ea-98ae-d95067c59ed1.png)

**To Reproduce**

Dockerfile looks like this:

```docker
FROM node:12.18.2-alpine
```

**Additional context**

**Comment by rarkins** [comment]
This does not reproduce in Renovate CLI 21.6.6: https://github.com/renovate-tests/docker18/pull/2/files

```
DEBUG: packageFiles with updates (repository=renovate-tests/docker18)
       "config": {
         "dockerfile": [
           {
             "packageFile": "Dockerfile",
             "manager": "dockerfile",
             "deps": [
               {
                 "depName": "node",
                 "currentValue": "12.18.2-alpine",
                 "replaceString": "node:12.18.2-alpine",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "commitMessageTopic": "Node.js",
                 "depType": "final",
                 "depIndex": 0,
                 "updates": [
                   {
                     "fromVersion": "12.18.2",
                     "toVersion": "12.18.3",
                     "newValue": "12.18.3-alpine",
                     "newMajor": 12,
                     "newMinor": 18,
                     "updateType": "minor",
                     "isSingleVersion": true,
                     "newVersion": "12.18.3"
                   },
                   {
                     "fromVersion": "12.18.2",
                     "toVersion": "14.7.0",
                     "newValue": "14.7.0-alpine",
                     "newMajor": 14,
                     "newMinor": 7,
                     "updateType": "major",
                     "isSingleVersion": true,
                     "newVersion": "14.7.0"
                   }
                 ],
                 "warnings": [],
                 "sourceUrl": "https://github.com/nodejs/node",
                 "dockerRegistry": "https://index.docker.io",
                 "dockerRepository": "library/node"
               }
             ]
           }
         ]
       }
```

This presumably means either:
- It's something specific to WhiteSource Renovate (which I would normally consider very unlikely because it doesn't change any of this type of core logic), or
- It's related to your config, but I can't think of any config that could change this, or
- It's related to your environment - e.g. do you use a custom Docker registry? Again I can't think why this would cause it

I'll try to boot up a WhiteSource Renovate v1.0.1 server to see if I can reproduce that way. First though, please confirm that you can reproduce using a clean repo with nothing but a Dockerfile (i.e. like the linked renovate-tests/docker18)

**Comment by tuckbick** [comment]
Solved. In my Renovate config I was using this:
```json
    "dockerfile": {
        "versioning": "semver"
    }
```

So really, the older version has a bug that was not respecting the above config. v1 seems to have corrected the problem.

Thanks. I appreciate your time. 🙇
