### ISSUE TITLE
Simplify and/or better document PR mergeability status

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#6908]
We mostly use `pr.canMerge`:

- bitbucket: https://github.com/renovatebot/renovate/blob/6aa86d32ffb9dee3d75b46a3dd87182bd062b2a8/lib/platform/bitbucket/index.ts#L287 (only looks at conflict status, so is redundant)

- bitbucket-server: https://github.com/renovatebot/renovate/blob/6aa86d32ffb9dee3d75b46a3dd87182bd062b2a8/lib/platform/bitbucket-server/index.ts#L279 (uses platform's mergeability status)

- gitea: https://github.com/renovatebot/renovate/blob/6aa86d32ffb9dee3d75b46a3dd87182bd062b2a8/lib/platform/gitea/index.ts#L103 (uses platform's mergeability status)

- github: https://github.com/renovatebot/renovate/blob/6aa86d32ffb9dee3d75b46a3dd87182bd062b2a8/lib/platform/github/index.ts#L625-L633 (uses PR's mergeStateStatus plus checks for negative reviews)

- gitlab: https://github.com/renovatebot/renovate/blob/6aa86d32ffb9dee3d75b46a3dd87182bd062b2a8/lib/platform/gitlab/index.ts#L449-L458 (leans on platform mergeability statuses)

We also have `getBranchStatus()`:

- azure: returns red if branch.aheadcount = 0
- bitbucket: returns red if any failed statuses, yellow if any pending, green if all passed
- bitbucket-server: returns red if failed count > 0, yellow if any pending or no successful, green if all successful
- github: combines status checks and check runs. Returns yellow if no tests
- gitlab: queries combined status of branch, ignores any that allow failure

Based on the above, I don't think we have enough uniformity to abstract any of this up to the application layer and our current approach is suitable. The missing link is probably to help users with a "cannot merge because X" message, especially for things like "no tests results found".

**Comment by rarkins** [comment]
Proposal:

- Where possible, return a `pr.cannotMergeReason` string field along with `pr.canMerge`
- Log this in the application layer if automerge is enabled and `pr.canMerge=true`
- Also work out a way to return and log that "branch status is pending because no test results found"

**Comment by raspy8766** [comment]
Not sure why this issue was [abruptly closed without comment](https://github.com/renovatebot/renovate/issues/11307). @rarkins do you have any insight as to why this might be happening or workarounds to fix it?
