### ISSUE TITLE
Clear datasource memcache after lookups complete

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#6910]
**What would you like Renovate to be able to do?**

Clear/delete all cached datasource lookups after all datasource lookups are complete.

**Did you already have any implementation ideas?**

Here is where we get/set cached got responses: https://github.com/renovatebot/renovate/blob/6aa86d32ffb9dee3d75b46a3dd87182bd062b2a8/lib/util/http/index.ts#L114-L126

We need a way to tag/identify which requests are datasource ones and then be able to delete their keys later.

I don't think we can delete *all* got requests because some of them will be platform ones.

Possibly we need to add a new internal classifier for platform vs datasource requests (or a new http middleware). Also a challenge because the platform can also be a datasource.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

It works currently but all cached results are held in memory until the run is complete.

**Is this a feature you'd be interested in implementing yourself?**

Maybe

**Comment by rarkins** [comment]
@viceice @JamieMagee @zharinov need ideas on how we can somehow tag/identify datasource requests and delete them all efficiently later. Most datasources call `util/http` directly but some will call util/http/github or util/http/gitlab etc. Maybe we can be pragmatic and not delete the cache for platform requests? If so then we can maybe add util/http/datasource.ts and use that as a way to tag/classify.

BTW our datasources do pass `hostType` with requests and those will be like `DATASOURCE_PACKAGIST` however they resolve to strings like `packagist` so can't be identified by prefix.

**Comment by JamieMagee** [comment]
Http is a class, so we could create a subclass, `HttpDatasource`, extract the caching logic to a separate method and override it in the `HttpDatasource` class. Then we can have a separate cache just for datasource requests, and we can clear it easily.

What do you think?

**Comment by rarkins** [comment]
That could work, assuming you're ok with my idea to *not* clear datasource lookups on the same platform (e.g. github).

**Comment by zharinov** [comment]
What if we introduce optional `namespace` parameter for `util/cache/memory.ts` functions? Then we can pass it if needed from new option of `Http` methods (or treat string values of `useCache: string | boolean` as namespaces). After that, cleaning up the entire namespace should be straightforward.

**Comment by rarkins** [comment]
Sounds ok if it can be implemented elegantly.

**Comment by rarkins** [comment]
BTW I'm still trying to think if there's a more elegant / more maintainable way to achieve this. Searching our source code, I see the following memCache.set() calls:

- The datasource index caches lookups based on datasource + lookupName + registryURls
- Packagist datasource has its own cache, IIRC this is because of the compatibility part (which we should maybe move into datasource common index)
- util/http caches every GET
- Release notes caching (multiple)

Ignore packagist for now - it's an isolated case.

So then we're back to the http cache as the main memory hog. In the lookup phase, there's just two uses for it:
- Caching platform GET requests (e.g. github, bitbucket)
- Caching datasource lookups

The datasource index cache + http cache probably duplicate each other a lot, assuming that duplicate datasource lookups have a high hit rate of same `lookupName` + `registryUrls`.

**Comment by zharinov** [comment]
Also, I see it's somehow related to #6575
