### ISSUE TITLE
`postUpdateOptions` not used for lockfile maintenance

### ISSUE THREAD

**Issue by Turbo87** [renovatebot/renovate#6915]
**What Renovate type are you using?**

Self-hosted on internal GitLab instance

**Describe the bug**

We are using the `"postUpdateOptions": ["yarnDedupeHighest"]` option, to ensure that we don't ship too many copies of the same dependency to our clients. Generally this seems to work fine, but we lately enabled the `:maintainLockFilesWeekly` option, and it seems that `yarn-deduplicate` is not running after that lockfile update. The lockfile maintenance MR is instead duplicating one of the relevant dependencies which is failing one of our linting steps that was created to catch these sorts of issues.

**Relevant debug logs**

**To Reproduce**

In our setup we have a main project with dependencies A and B (both pinned), and B also has a dependency on A (`^` constraint). There was a new release of A, so now the lockfile maintenance tries to update the A dependency, but only for B, not the main project, since that has a pinned dependency. 

`yarn-deduplicate` should resolve the situation by reverting to the old version, but it does not appear to run.

**Additional context**

**Comment by rarkins** [comment]
Hi, we will need a reproduction repo in a public github.com repo

**Comment by HonkingGoose** [comment]
@rarkins It's been 6 months from when we requested a reproduction, and we don't have one yet. Do you want to give them 2 weeks with the bot, or do you want to close the issue?
