### ISSUE TITLE
Support Composer 2.x when binarySource=docker

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#6946]
**What would you like Renovate to be able to do?**

Detect when a repo is using Composer 2.x and use that image version when running `renovate/composer`

**Did you already have any implementation ideas?**

This needs us to build and version `renovate/composer` images too: https://github.com/renovatebot/docker-composer/issues/45

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Until we implement this, any repo using 2.x will likely fail.

**Is this a feature you'd be interested in implementing yourself?**

Maybe

**Comment by viceice** [comment]
One problem persists, we don't know which composer version was used.

* One check can be direct dependency to composer, used by some projects.
  Here we can easily extract version
* We need to check `plugin-api-version` field in lockfile, but that only references a major composer version.[ThibaultVlacich/renovate-composer/composer.lock#L1672](https://github.com/ThibaultVlacich/renovate-composer/blob/83c14960b5ca36ce04b42e289a52b7260db30f13/composer.lock#L1672)

**Comment by viceice** [comment]
Another possibillity is to check all deps listed in lockfile for composer references

[ThibaultVlacich/renovate-composer/composer.lock#L599](https://github.com/ThibaultVlacich/renovate-composer/blob/83c14960b5ca36ce04b42e289a52b7260db30f13/composer.lock#L599)

**Comment by rarkins** [comment]
Another possibility: we introduce a configuration setting to specify the binary version/range to use (manager-agnostic), and its first use can be Composer.

But really Composer itself should have a better way to indicating it - maybe a suggestion we can put to them before 2.0.0 GA?

**Comment by viceice** [comment]
sure, best would be a property in lockfile which represents the last used composer version 🎉

**Comment by rarkins** [comment]
> People can either require `composer-runtime-api` in their composer.json to enforce a given composer version, or indeed by default you can now read the presence of `plugin-api-version` in the lock file, if it's missing it's a 1.x.

Reference: https://github.com/composer/composer/issues/9114

**Comment by massto** [comment]
> > People can either require `composer-runtime-api` in their composer.json to enforce a given composer version, or indeed by default you can now read the presence of `plugin-api-version` in the lock file, if it's missing it's a 1.x.
> 
> Reference: [composer/composer#9114](https://github.com/composer/composer/issues/9114)

**Comment by massto** [comment]
> > People can either require `composer-runtime-api` in their composer.json to enforce a given composer version, or indeed by default you can now read the presence of `plugin-api-version` in the lock file, if it's missing it's a 1.x.
> 
> Reference: [composer/composer#9114](https://github.com/composer/composer/issues/9114)

**Comment by kochen** [comment]
> One problem persists, we don't know which composer version was used.
> 
> * One check can be direct dependency to composer, used by some projects.
>   Here we can easily extract version
> * We need to check `plugin-api-version` field in lockfile, but that only references a major composer version.[ThibaultVlacich/renovate-composer/composer.lock#L1672](https://github.com/ThibaultVlacich/renovate-composer/blob/83c14960b5ca36ce04b42e289a52b7260db30f13/composer.lock#L1672)
> 
> ref #6945

The issue deepens when platform requirements are NOT ignored.
i.e:
```
  "composerIgnorePlatformReqs": false
```
see for example here: https://github.com/kochen/renovate-composer-2/pull/1

**Comment by viceice** [comment]
Would composer 2 be backward compatible if we move the `latest` docker tag to v2? Or would composer do an incompatible upgrade?

We now have composer v2 docker images, but v1 is tagged as latest 
https://hub.docker.com/r/renovate/composer/tags

**Comment by kochen** [comment]
It should be, and `composer v1` is EOL-ish, so everybody is encouraged to upgrade anyway: https://blog.packagist.com/composer-2-0-is-now-available/

**Comment by viceice** [comment]
My question is, will we break existing v1 users, if we use v2 to update the lockfile and they then use v1 to install on there dev system?

**Comment by kochen** [comment]
As long as v2 doesn't update a packages that requires v2, we don't break:
> composer.lock files are interoperable between versions, so you can upgrade to 2.0 and roll back easily if needed.

**Comment by viceice** [comment]
build done https://github.com/renovatebot/docker-composer/runs/1332219847?check_suite_focus=true

~3 min for 21 versions 🙃

**Comment by viceice** [comment]
@kochen can you retry your test repo above (tick the retry checkbox in pr)?

**Comment by kochen** [comment]
> @kochen can you retry your test repo above (tick the retry checkbox in pr)?

Passed!

**Comment by kochen** [comment]
@rarkins @viceice Thanks for the quick [re]action!

btw, self-hosted renovate still doesn't seem to use `composer v2`...

**Comment by viceice** [comment]
are you using the full image?

**Comment by kochen** [comment]
> are you using the full image?

yes!

**Comment by viceice** [comment]
ok, you nee to wait for https://github.com/renovatebot/docker-renovate-full/runs/1332372885?check_suite_focus=true then all latest renovate tags should be updated to composer v2

**Comment by viceice** [comment]
you could test with `npx renovate --binary-source=docker` until full image is rebuild
