### ISSUE TITLE
[terraform] support custom provider registries (since v0.13)

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#6954]
**What would you like Renovate to be able to do?**

With terraform v0.13 is is possible to have private / internal registries: [registry protocol](https://www.terraform.io/docs/internals/provider-registry-protocol.html)

**Did you already have any implementation ideas?**

Sure, we can simply handle it as other managers / datasource registryUrls.
The source can have two forms:
* `:namespace/:type` (eg: `hashicorp/aws`), here we simply use default registry `registry.terraform.io`
* `:registry/:namespace/:type` (eg: `registry.company.com/hashicorp/aws`), here we use registry as `regristryUrl`

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

nope, no alternative.

**Is this a feature you'd be interested in implementing yourself?**

Maybe, currently not in use.

ref #6953

**Comment by secustor** [comment]
This should be already working for both providers and modules.
