### ISSUE TITLE
Conda environment support for python projects

### ISSUE THREAD

**Issue by gerbenoostra** [renovatebot/renovate#6969]
**What would you like Renovate to be able to do?**

To also verify python package versions in conda environment files (`environment.yml`)

**Did you already have any implementation ideas?**
no

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Conda environments can also include pip requirememnts, a workaround is to put those in a separate txt file, and have renovatebot check those.
`environment.yml` would then be:
```
dependencies:
- python=3.7
- jupyter
- pip
- pip:
  - -rrequirements.txt
```
This workaround however does not work for the conda packages (like the python=3.7 here, and any conda packages installed, like jupyter in this case)

**Is this a feature you'd be interested in implementing yourself?**
maybe

**Comment by gerbenoostra** [comment]
Relates to #931

**Comment by rarkins** [comment]
Duplicate of #2213? If so then can you transfer your comments there and close this one?

**Comment by gerbenoostra** [comment]
Indeed duplicate of #2213
