### ISSUE TITLE
refactor: Replace git.getFileList() with fs.getFileList()

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7004]
**What would you like Renovate to be able to do?**

Use a file system approach to retrieving the current branch's file list.

**Did you already have any implementation ideas?**

Remove `getFileList()` from git and add to fs. Needs to call `syncGit()` from git first though.

**Comment by rarkins** [comment]
Consider https://github.com/thecodrr/fdir

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by rarkins** [comment]
@zharinov am I imagining things or did you do some performance testing of this a year or more ago and found that git's file list retrieval is fairly fast, and the FS approach wasn't any faster?

**Comment by rarkins** [comment]
@olegkrivtsov please hold off on this one until we're sure it's a good idea.

**Comment by zharinov** [comment]
> @zharinov am I imagining things or did you do some performance testing of this a year or more ago and found that git's file list retrieval is fairly fast, and the FS approach wasn't any faster?

My concurrent node-based implementation of `getFileList()` wasn't that fast, though I didn't try `fdir` or some other solution that really into performance.

**Comment by rarkins** [comment]
Thanks. I think let's leave as-is unless we can confirm there's a performance problem in future
