### ISSUE TITLE
PR recreation fails due to GitLab API error

### ISSUE THREAD

**Issue by k-yle** [renovatebot/renovate#7060]
**What Renovate type are you using?**

GitLab hosted app

**Describe the bug**

If you close a PR unmerged, renovate lists it in the master issue. You can click a checkbox to ask renovate to recreate the PR (see figure 1 below).

![image](https://user-images.githubusercontent.com/16009897/90969197-ef657b00-e549-11ea-902d-1a341d4b06e3.png)

However, checking the box doesn't work - renovate creates a branch and then deletes it a few minutes later.

**Relevant debug logs**

Log files: https://gist.github.com/k-yle/9db57f3b7a37ffe851cc43ff64abf8e2#file-renovate-job-220169821-log-L98-L159

Based on line 98 onwards, it looks like the GitLab API returned a 500 when trying to create the PR which is why renovate decided to give up and delete the branch. 
 

**To Reproduce**

- Close a PR unmerged (`eslint-7.x` in our case)
- Check the box in the master issue to re-create it
- Note how the branch is created, the CI pipelines start to run
- Note how renovate tries to create a new PR but the GitLab API returns a status code 500, causing renovate to abort and delete the branch
- re open the master issue and note how the checkbox is now back to unchecked

**Additional context**

<details>
<summary>.rennovaterc.json file</summary>

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":githubComToken(REDACTED)"
  ],
  "labels": ["Dependencies"],
  "packageRules": [
    {
      "packageNames": ["react-intl"],
      "stabilityDays": 2,
      "prCreation": "not-pending"
    },
    {
      "packagePatterns": ["^eslint-", "^@types/"],
      "labels": ["Dependencies", "Ready to review"]
    }
  ],
  "masterIssue": true,
  "rangeStrategy": "bump"
}
```

</details>

**Comment by rarkins** [comment]
A 500 error is a server saying "It's my fault, not yours". What you're describing is expected recovery behavior from Renovate, i.e. delete the branch so that it can be attempted again next run. Do you think there's anything Renovate should do differently?

**Comment by k-yle** [comment]
I suppose that makes sense. It seems to have been an error on GitLab's end which is now resolved. So I'll close this.
