### ISSUE TITLE
Add releaseTimestamp for "github-tags" datasource

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#7062]
**What would you like Renovate to be able to do?**

Obtain timestamps for dependencies obtained from Github tags.

**Did you already have any implementation ideas?**

See abandoned PR: #5760
See also: #4689

**Is this a feature you'd be interested in implementing yourself?**

Maybe

**Comment by rarkins** [comment]
@zharinov is this done?

**Comment by zharinov** [comment]
Yes
