### ISSUE TITLE
yarn insall: The requested URL returned error: 400 - crypto-browserify 

### ISSUE THREAD

**Issue by marleypowell** [renovatebot/renovate#7072]
**What Renovate type are you using?**

Self Hosted (Azure Devops).

**Describe the bug**

When running renovate bot in azure pipelines I get issues when trying to update the yarn.lock. I get error 400 which stops the yarn.lock from being updated. This issue doesn't happen when running renovate bot locally.

**Relevant debug logs**

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/dominictarr/crypto-browserify.git
Directory: /tmp/renovate/repos/azure/Hosted Signatures/exclaimercloud-ui-library/exclaimer
Output:
fatal: unable to access 'https://github.com/dominictarr/crypto-browserify.git/': The requested URL returned error: 400
```

**To Reproduce**

Use `docker run renovate/renovate:latest` in azure pipelines where the yarn lock for the project has `https://github.com/dominictarr/crypto-browserify.git/` as a dependancy.

**Additional context**

Using a standard azure pipelines agent.

**Comment by viceice** [comment]
I's a yarn issue, because the git repo was moved to https://github.com/crypto-browserify/crypto-browserify
