### ISSUE TITLE
pip_requirements: Renovate does not handle some python library version

### ISSUE THREAD

**Issue by alecgerona** [renovatebot/renovate#7167]
**What Renovate type, platform and version are you using?**

Hosted App

**Describe the bug**

[black](https://github.com/psf/black) is a python code formatter that does not follow SemVer. Its version follows XX.YYbZ. Somehow, although it appears to follow PEP440, it's not handled by Renovate properly. It's not pulling the latest version. 

**Relevant debug logs**

```json
{
            "depName": "black",
            "currentValue": "==19.10b0",
            "datasource": "pypi",
            "fromVersion": "19.10b0",
            "depIndex": 0,
            "updates": [],
            "warnings": [],
            "sourceUrl": "https://github.com/psf/black",
            "changelogUrl": "https://github.com/psf/black/blob/master/CHANGES.md"
          },
```

**To Reproduce**
Please refer to the sample repository to replicate the issue. 
https://github.com/alecgerona/unparsed-dependency-test

**Comment by rarkins** [comment]
It reproduces without loose versioning though, right? That was a mistake by me to recommend. Please create a simple repo which reproduces with the default config.

**Comment by alecgerona** [comment]
If without the loose versioning it doesn't appear in the logs at all.

**Comment by rarkins** [comment]
That's ok, then we debug it.

**Comment by alecgerona** [comment]
Hi @rarkins, I've added the test repository. Looks like it shows up in the logs but it's still not getting the latest version.

**Comment by raabf** [comment]
Just as a note if someone needs it for reference. There is a PEP440 compliant implementation in [packaging.version.Version](https://packaging.pypa.io/en/latest/version/#packaging.version.Version):

```python
>>> from packaging.version import Version
>>> a = Version("19.10b0")
>>> b = Version("19.10b1")
>>> a < b
True
>>> c = Version("19.11b0")
>>> b < c
True
```

**Comment by viceice** [comment]
maybe we need to return `pep440` versioning for deps extracted by `pip_requirements` manager ?

**Comment by rarkins** [comment]
I thought we did already

**Comment by viceice** [comment]
Don't really know, is there any packageRule which assigns pep440 to python language? because there is no ref to pep440 in manager. 🤔

**Comment by rarkins** [comment]
`python` specifies pep440 default in our config: https://github.com/renovatebot/renovate/blob/e4fafdc3ac1b2dec18f417464cfc19de9b2de16a/lib/config/definitions.ts#L1573-L1582

And then we have this:

![image](https://user-images.githubusercontent.com/6311784/98247212-a67f6900-1f73-11eb-97c7-b3f9d683dea7.png)

I guess if we debug the example repo then we can hopefully work out what's going on.

**Comment by viceice** [comment]
ok, running debugger now

**Comment by viceice** [comment]
looks like it's the pep440 versioning
![image](https://user-images.githubusercontent.com/1798109/98260829-0d0c8300-1f84-11eb-8183-f0e70b0a5755.png)

we dont get any version.
can be here
https://github.com/renovatebot/renovate/blob/36849511ccae94809cfcf3d33d6616806aa1ab81/lib/workers/repository/process/lookup/index.ts#L290

or here
https://github.com/renovatebot/renovate/blob/40ae43817a6713423a9e968296806614740bef01/lib/workers/repository/process/lookup/filter.ts#L142-L148

not easy to debug 🙃

**Comment by rarkins** [comment]
So there's no skip reason, but there's also no updates? So either the newer version looks invalid to us or we think it's lower?

**Comment by HonkingGoose** [comment]
Di we make further progress with debugging the problem? Reading this issue, I'm not sure that we're actually `status:ready`, because we don't know the cause of the issue???

**Comment by rarkins** [comment]
Actually there is a reproduction repo, so I think it's OK to leave as `ready`
