### ISSUE TITLE
Concurrency limit blocks PR creation for existing branches

### ISSUE THREAD

**Issue by 72636c** [renovatebot/renovate#7197]
In the SEEK-Jobs GitHub org, we make broad use of a configuration like this:

- [`schedule`](https://docs.renovatebot.com/configuration-options/#schedule) limited to certain days, e.g. `"before 7am on Tuesday"`
- [`prConcurrentLimit`](https://docs.renovatebot.com/configuration-options/#prconcurrentlimit) set to 3
- [`:prNotPending`](https://docs.renovatebot.com/presets-default/#prnotpending) to wait for checks to run, with a one hour timeout via [`prNotPendingHours`](https://docs.renovatebot.com/configuration-options/#prnotpendinghours)

This used to work just fine, except that the concurrency limit was not always respected per https://github.com/renovatebot/renovate/issues/7075. Over the past two weeks or so, we've observed the following behaviour:

- [x] Branches are created at the scheduled time. (It seems like these can exceed `prConcurrentLimit`, but that's not a big issue.)
- [x] PRs are not created on the same run due to `prNotPending`.
- [ ] On a subsequent run, PR creation is blocked by the concurrency limit.

I gave the code a squiz and I believe the issue is that the concurrency limit is tested against the number of branches rather than PRs, and this doesn't gel well with `prNotPending`. It seems @rarkins was alluding to this here: https://github.com/renovatebot/renovate/pull/7099/files#r476657839

**Comment by rarkins** [comment]
Cc @zharinov, is this what you’d expect to see?

**Comment by rarkins** [comment]
We now support separate branch and PR limits
