### ISSUE TITLE
datasource defaultConfig overrides user-configured values

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7281]
**What Renovate type, platform and version are you using?**

Not applicable

**Describe the bug**

Values in a datasource's `defaultConfig` override user configuration.

**Relevant debug logs**

None

**To Reproduce**

Repo: https://github.com/renovate-tests/additionalprefix3

You can see both Docker branches ignore the configured `additionalBranchPrefix`

**Additional context**

None

**Comment by rarkins** [comment]
`docker` datasource configures additionalBranchPrefix here: https://github.com/renovatebot/renovate/blob/c3969d9c28142113a2debb7f871e6f68d8f4056e/lib/datasource/docker/index.ts#L24

This then is applied with mergeChildConfig() here: https://github.com/renovatebot/renovate/blob/ad52ac9b13e7fdd87fbfcedfdfbfcf44a052ae0e/lib/workers/repository/process/fetch.ts#L30-L31

**Comment by rarkins** [comment]
You can overcome this by configuring `additionalBranchPrefix` within a package rule, e.g.

```
{
  "packageRules": [{
    "packagePatterns": ["*"],
    "additionalBranchPrefix": "prefix-"
  }]
}
```

**Comment by rarkins** [comment]
So how do we have default configs for datasources, without overriding user configs?

**Comment by hasanwhitesource** [comment]
Could this be fixed now or am I not fully understanding the case.
I have forked and tried to reproduce but I have received the branch prefix that was set in the user config [my run](https://github.com/hasanwhitesource/additionalprefix3).
I also saw that the config isn't being overridden after the merge. Am mistaken @rarkins ?

**Comment by rarkins** [comment]
@hasanwhitesource you're not mistaken.. the problem was that my example was outdated. We decided to remove `additionalBranchPrefix` from datasource default configs after I created this issue.

Here's Docker's current default config: https://github.com/renovatebot/renovate/blob/079c219f49a1f3bcbb1c367d74bb60dd2044d941/lib/modules/datasource/docker/index.ts#L305-L330

I think we've now removed enough of the problematic datasource defaults that we can now close this issue
