### ISSUE TITLE
Renovate's README in Docker Hub seems to be outdated

### ISSUE THREAD

**Issue by dominguezcelada** [renovatebot/renovate#7348]
There's a link in [Renovate's Docker Hub](https://hub.docker.com/r/renovate/renovate/) description which is broken:
![image](https://user-images.githubusercontent.com/2574275/93861924-982a0600-fcc1-11ea-941c-b0d091fa72de.png)

⚠️ https://github.com/renovatebot/renovate/blob/master/docs/development/self-hosting.md ⚠️ 

The right link should be:
https://github.com/renovatebot/renovate/blob/master/docs/usage/self-hosting.md

---

Checking `REAME.md` in master, the link is the right one so it looks something related to an outdated README.md in Docker Hub.

https://github.com/renovatebot/renovate/blob/master/readme.md#L62

Is this process automated but something failed or the process of updating the README.md is not automated and it should?

**Comment by rarkins** [comment]
I think it was automatically updated back when it was auto-built using Docker Hub, but that stopped once we moved to our own build process. I manually edited/updated it - thanks for the heads-up

**Comment by dominguezcelada** [comment]
> I think it was automatically updated back when it was auto-built using Docker Hub, but that stopped once we moved to our own build process. I manually edited/updated it - thanks for the heads-up

Should I create a follow-up issue to automate it or you don't plan to automate it?

**Comment by viceice** [comment]
@dominguezcelada do you know a way to automate it without using docker cloud build?

**Comment by rarkins** [comment]
I think let's not automate it for now. I also took the opportunity to remove some parts of the README that aren't applicable to the Docker Image (e.g. hosted app instructions) so it wouldn't be a simple 1:1 sync anyway. We might maybe want to have a standalone file in our docs/ folder that is sync'd to Docker Hub if it's possible.

**Comment by dominguezcelada** [comment]
> @dominguezcelada do you know a way to automate it without using docker cloud build?

Nope... I was thinking about a Github Action (https://github.com/peter-evans/dockerhub-description <-- this could be an example) but if it's not a priority now as @rarkins pointed (plus this sync problem, etc). I guess the issue can be closed + keep maintaining it manually for the moment 👍🏽

**Comment by viceice** [comment]
Ok, I've looked at the mentioned GitHub action an it seems to be easy to update the docker hub readme with a simple patch request.

So maybe we can open an issue with low prio to sync hub description from a file in docs folder.
