### ISSUE TITLE
Central dependency dashboard

### ISSUE THREAD

**Issue by fgreinacher** [renovatebot/renovate#7372]
**What would you like Renovate to be able to do?**

I'd like to have one central dependency dashboard across all our repositories (in our case all below one GitLab group) so that I can easily get an overview about pending work and can e.g. perform mass operations from there.

In my opinion the simplest way to configure this would be to point Renovate to the repository where the central dashboard should be created. Something like this:

```json
{
   "dependencyDashboard": true,
   "dependencyDashboardRepository": "path-to/my-repo"
}
```

**Did you already have any implementation ideas?**

Not yet.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Yes, we can search for all dependency dashboards across our group and process each of them individually.

**Is this a feature you'd be interested in implementing yourself?**

Generally yes, just not sure when.

**Comment by viceice** [comment]
An interesting idea, but I think difficult to implement, because we would need to sync multiple different repo runs.

**Comment by fgreinacher** [comment]
> An interesting idea, but I think difficult to implement, because we would need to sync multiple different repo runs.

Totally true, up to now I did not think about concurrency and parallelism of Renovate a lot (see also https://github.com/renovatebot/renovate/issues/7401). Now that I did I think adding such a feature would introduce a lot of complexity for a questionable benefit.

**Comment by lemonbakeoff** [comment]
@fgreinacher have you had any success with this?
Trying to find someway to collect data across multiple dependencies for sake of allocating dev resources.

**Comment by fgreinacher** [comment]
> @fgreinacher have you had any success with this?
> Trying to find someway to collect data across multiple dependencies for sake of allocating dev resources.

We're using GitLab and stick to MR labels for discoverability and automatic MR assignment for responsibility. It's OK-ish for our team of around 50 people.
