### ISSUE TITLE
errors interacting with GHE v2.22 API

### ISSUE THREAD

**Issue by rvillane** [renovatebot/renovate#7374]
**What Renovate type, platform and version are you using?**
Self-hosted renovate CLI connected to GHE running in debug mode
I updated renovate (npm i -g renovate) before executing, logs indicate -> "renovateVersion": "23.36.4"
GHE was recently updated to version 2.22 in case that is relevant

**Describe the bug**

We are seeing the following error all over the place from renovate interacting with GHE API
Error: fatal: git fetch-pack: expected shallow list

**Relevant debug logs**

```
ERROR: Repository has unknown error (repository=CTAgile/original-direct-order-updater)
       "err": {
         "task": {
           "concatStdErr": true,
           "format": "utf-8",
           "commands": [
             "fetch",
             "origin",
             "refs/heads/renovate/*:refs/remotes/origin/renovate/*",
             "--depth=2",
             "--force"
           ]
         },
         "message": "fatal: git fetch-pack: expected shallow list\n",
         "stack": "Error: fatal: git fetch-pack: expected shallow list\n\n    at GitExecutorChain.onFatalException (/opt/node-v10.17.0-linux-x64/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/opt/node-v10.17.0-linux-x64/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/opt/node-v10.17.0-linux-x64/lib/node_modules/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
```

**Comment by rarkins** [comment]
What version of git is installed in your system?

**Comment by rvillane** [comment]
that box has:

```
git --version
git version 1.8.3.1

```

it has not changed recently and is interesting that renovate was working fine in those repos until recently, but I can't tell exactly when started getting those failures as it ran as a cronjob and didn't check logs

**Comment by viceice** [comment]
You should update. Git to a more recent git version, maybe the new ghe version has changed somehow,vso that the old hit us unable to use the new backend.

**Comment by rarkins** [comment]
Got 1.8.3 is apparently 7 years old. You're welcome to roll back your GHE to test.. but otherwise I'm going to assume that was it.

**Comment by rvillane** [comment]
just to close the loop, you were right, once git got updated to 2.28.0, renovate had a smooth execution
