### ISSUE TITLE
Ability of config in JS format

### ISSUE THREAD

**Issue by arxeiss** [renovatebot/renovate#7378]
**What would you like Renovate to be able to do?**

Currently, the repo configuration is placed in JSON file. This is enough for simpler configuration but can be tricky when more sophisticated ones are needed. 

Having the ability to write a small JS script and export result similarly as like in Self-Hosted configuration would help for example with this issue: https://github.com/renovatebot/renovate/issues/6503. With few `for` loops, it would be easy to manage it.

Also, the JSON file does not support comments, but with a JS file, it would be possible.

**Did you already have any implementation ideas?**

Not sure, but it could be supported by "simply copying code" from the self-hosted configuration part.

**Comment by viceice** [comment]
you can use `json5`, which should support comments. Also js files are not planned, because of security implications
