### ISSUE TITLE
Support limits for branches created per hour

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#7387]
**What would you like Renovate to be able to do?**

Add new option `branchHourlyLimit` that limits branches created per hour.

**Did you already have any implementation ideas?**

We're doing rebase and force-pushes, but maybe we can somehow leverage Git create commit/author time separation to know exact branch creation time.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

🤔 

**Is this a feature you'd be interested in implementing yourself?**

Yes

**Comment by zharinov** [comment]
Instead of working around our force-pushes, I wonder if we can leverage Dependency Dashboard for hourly scheduling, such that (1) users can see what to expect and (2) we can use same information to initialize counters before processing.

**Comment by rarkins** [comment]
I think we should refocus on commits per hour, and counting commits from currently existing branches for simplicity reasons
