### ISSUE TITLE
Early exit with http2 enabled

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#7389]
**What Renovate type, platform and version are you using?**

Self-hosted renovate docker slim image, auto updated to latest against bitbucket server (latest)

**Describe the bug**

When enabling `http2` support, renovate willl mostly exit early without any log message.
Exit code is zero.
Disabled http2 explicit for our bitbucket.
My guess is that it has something to do with some wrong `got` handling.

**Relevant debug logs**

Nothing relevant there, renovate simply stops.

**To Reproduce**

I think this is hard to reproduce, because it starts happening after around processing ~8 repos.
Maybe it depends on some of our custom registries.

**Additional context**

tried to catch unhandled promies and exceptions with

```js
process.on('unhandledRejection', (reason, p) => {
    console.log("UNHANDLED REJECTION:", p, " reason: ", reason);
    process.exit(100);
});

process.on('uncaughtException', function(err) {
    console.log('UNHANDLED ERROR:', err.stack);
    process.exit(100);
});

require('/usr/src/app/dist/renovate.js')
```

but don't got any error logged.

**Comment by rarkins** [comment]
Can you enable http2 selectively per-host to try to narrow it down?

**Comment by viceice** [comment]
sure

**Comment by rarkins** [comment]
This reminds me of when a user had crashes due to the global agent software. Perhaps anything that patches core libraries like `http` runs the chance of "silent" crashes?

**Comment by viceice** [comment]
🤔 Yes, can be the case. `global-agent` shouldn't be usined in my infrastructure, as i'm not using any proxy. Also if the `global-agent` is active, `http2` will not be enabled.

https://github.com/renovatebot/renovate/blob/bbea59939ebd9870b5bffd070c4be6803c36369a/lib/util/http/host-rules.ts#L35-L37

**Comment by viceice** [comment]
Ok, disable http2 for our internal registries seems to fix this issue.

I now see some 503 error on our proget server behind a traefik proxy. They all failed for nuget v3 registry. So i think this is the root cause for the silent exit when using http2.

I know there are some fixes for http2 on node v14, so will retry there when lts and got v12 is fully node v14 compatible.

Can also confirm http2 (if really used) works file for public registries:
* docker hub
* nuget
* npm

I'll investigate got request & response, maybe we can track http2 usage somehow.
