### ISSUE TITLE
Renovate not working with new Github repositories

### ISSUE THREAD

**Issue by frbuceta** [renovatebot/renovate#7394]
**What Renovate type, platform and version are you using?**

Renovate App for Github

**Describe the bug**

Github changes the name of the main branch today October 1 to "main". For these new repositories, renovate does not create PRs without configuration.

See https://github.com/github/renaming

**Comment by rarkins** [comment]
I just tested it and this repo with `main` has an onboarding PR https://github.com/renovatebot/testmain/pull/1 plus a regular PR: https://github.com/renovatebot/testmain/pull/2

Please provide more details about why you think it's not working.

**Comment by frbuceta** [comment]
Sorry @rarkins. I had a renovate.json at a lower level. I close the issue
