### ISSUE TITLE
Merged PR remains on dashboard, even after multiple rebases/retries/bot runs

### ISSUE THREAD

**Issue by valentijnscholten** [renovatebot/renovate#7443]
**What Renovate type, platform and version are you using?**

github app in public repo: https://app.renovatebot.com/dashboard#github/DefectDojo/django-DefectDojo

**Describe the bug**

A PR that was succesfully merged remains on the dashboard as open.
https://github.com/DefectDojo/django-DefectDojo/issues/2937

How can I "fix" this? Maybe I should intentionally downgrade the version again?

**Relevant debug logs**
https://app.renovatebot.com/dashboard#github/DefectDojo/django-DefectDojo

The PR (2967) is not occurring in the logs in normal runs. When rebasing or restoring the branch, it gets deleted by renovate:

```
DEBUG: findPr(renovate/rabbitmq-6.x, undefined, open)
DEBUG: Deleting orphan branch(branch="renovate/rabbitmq-6.x")
```

Which makes sense as the PR is merged. But it remains on the dashboard under Open PRs.

**To Reproduce**
See public dashboard: https://github.com/DefectDojo/django-DefectDojo/issues/2937

**Additional context**

**Comment by rarkins** [comment]
It looks like that issue hasn't been edited since 30/9. What do the logs say about the dashboard?

**Comment by valentijnscholten** [comment]
It has been edited in the mean time, couple of days ago I approved 4 or 5 PRs and merged them. This remaining is one of them.
![image](https://user-images.githubusercontent.com/4426050/95674514-feaf8f00-0bb0-11eb-9e49-aae7b5caf0d8.png)

logs only say it found the dashboard, but not much more.
full logs: https://pastebin.com/JCbh1BfJ

**Comment by rarkins** [comment]
Can you try adding dependencyDashboard=true in addition to dependencyDashboardApproval=true ? It's not meant to be necessary but I wonder if it will fix it.

Also you should delete the renovate/configure branch too, but that shouldn't be affecting the dashboard

**Comment by valentijnscholten** [comment]
The logs say that renovte is deleting that orphan branch, but it seems to remain:
```
DEBUG: remainingBranches=renovate/configure
DEBUG: findPr(renovate/configure, undefined, open)
DEBUG: Last commit author does not match git author email - branch has been modified
{
  "branchName": "renovate/configure",
  "lastAuthor": "valentijnscholten@gmail.com",
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: Deleting orphan branch(branch="renovate/configure")
DEBUG: ensureIssueClosing(Action Required: Fix Renovate Configuration)
```

I think most of the time I see this `DEBUG: ensureIssueClosing(Action Required: Fix Renovate Configuration)` in the logs, not sure if that means the config is broken or that it just means it is checking for broken configs.

added suggested config, deleted configure branch, but issue remains.

**Comment by rarkins** [comment]
That ensureIssueClosing is logged every time and is unrelated.

**Comment by valentijnscholten** [comment]
I don't know exactly when, but the PR has now vanished from the dashboard.

**Comment by valentijnscholten** [comment]
and it's back :-)

**Comment by valentijnscholten** [comment]
We see this problem from time to time and it resolves itself after a couple of days / weeks. The suggested rename seems to have worked for now for this specific point in time,

**Comment by rarkins** [comment]
The dashboard correctly reflects the state of the repo. One of the PRs is blocking a new PR in the same repo due to this configuration: https://github.com/DefectDojo/django-DefectDojo/blob/aab58b08e7f309158373e6ab68ec0cf2a8bb5bf7/.github/renovate.json#L12-L13

**Comment by valentijnscholten** [comment]
What that config is does is add the current version to the PR title. But it's the same as the new version, which is already in the PR title. What is causing the problem so we can change it? We would like to keep the current version in the title so it's clear if it's a major/minor/patch update.

**Comment by rarkins** [comment]
The problem is that digest updates need a different format, but you are overwriting it. Please create a discussion issue describing what you are hoping to achieve compared to the default behavior and we can recommend an alternative approach.
