### ISSUE TITLE
Renovate removed a or clause when updating node engines in package.json

### ISSUE THREAD

**Issue by jelhan** [renovatebot/renovate#7469]
**What Renovate type, platform and version are you using?**

I'm using hosted Renovate on GitHub.

**Describe the bug**

Renoate tried to update Node.js `10.*` to `10.* >= v10.22.1`. This only affected one side of an OR (`||`) condition: `10.* || >= 12` Renovate dropped the other part of the OR condition without warning.

Instead of updating to `10.* >= v10.22.1 || >= 12` it changed to `10.* >= v10.22.1` and therefore dropped support for node 12 and later.

**Relevant debug logs**

Please see this pull request created by Renovate: https://github.com/jelhan/ember-autoresize-modifier/pull/61/files

**Comment by viceice** [comment]
`10.* || >= 12` looks ugly to me. is that a valid range? shouldn't this be something like `^10 || >= 12` ?

**Comment by viceice** [comment]
also related to #2084

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/96003241-5280d900-0e3a-11eb-896c-e7a63c539c38.png)

Strange. Is it reproducible in a simple repo?

**Comment by jelhan** [comment]
> `10.* || >= 12` looks ugly to me. is that a valid range? shouldn't this be something like `^10 || >= 12` ?

This is the syntax used by Ember CLI to generate new [Ember.js projects](https://emberjs.com/): https://github.com/ember-cli/ember-new-output/blob/ed88fd1f967a17887d94ae911eaa7283e713e088/package.json#L55 Ember.js is a well established JavaScript framework to create single page applications. Not arguing what range might be better. Just wanted to point out that this engines configuration is used by many enterprise applications in production.

> Is it reproducible in a simple repo?

What do you mean by *simple repo*? I would consider the repository linked a simple one. :wink:

**Comment by rarkins** [comment]
A simple repository is one with minimum possible files to reproduce the problem.

**Comment by jelhan** [comment]
I haven't had the time to setup a reproduction but I noticed that another repository is affected as well: https://github.com/jelhan/croodle/pull/421/files
