### ISSUE TITLE
Onboarding PRs are not compiled with handlebars

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7526]
**What Renovate type, platform and version are you using?**

WhiteSource Renovate App

**Describe the bug**

The job log footer is not compiled so looks like this: 

```
This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#{{platform}}/{{repository}}).
```

**Relevant debug logs**

None

**To Reproduce**

Onboard a repo with the app, look at the PR source markdown.

**Additional context**

Mentioned by @gr2m on Twitter

**Comment by cypher7682** [comment]
Same issue here. We're seeing 

`{{#if isMajor}}` statements, along with all the major release information, in all our onboarding PRs D:

**Comment by PhilipAbed** [comment]
@rarkins is this still relevant?
