### ISSUE TITLE
feat(gitlab): gitlab-releases

### ISSUE THREAD

**Issue by lukasmrtvy** [renovatebot/renovate#7534]
**What would you like Renovate to be able to do?**
Would be nice to have also gitlab-releases datasource

**Did you already have any implementation ideas?**
Should be similar to this:
- https://github.com/renovatebot/renovate/tree/master/lib/datasource/gitlab-tags
- https://github.com/renovatebot/renovate/tree/master/lib/datasource/github-releases

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**
no

**Is this a feature you'd be interested in implementing yourself?**
no

Docs: https://docs.gitlab.com/ee/api/releases/

**Comment by cykl** [comment]
I had be interested in having Gitlab release description embedded in renovate merge request too. How can I help to clarify requirements ?

**Comment by rarkins** [comment]
I think if we implement it similarly to GitHub Releases then that should be enough from a requirements perspective.
