### ISSUE TITLE
Config bumpVersion updating scripts.version and not version

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/renovate#7558]
**What Renovate type, platform and version are you using?**

npm cli tool - v23.53.1. Bitbucket server (self hosted)

**Describe the bug**

Renovate overwrites the version script if defined instead of the version number

**Relevant debug logs**

Logs not useful (renovate ran successfully from it's standpoint and created the PR)

**To Reproduce**

On a project that has renovate enabled on it.

1. Add a new script `version` in the package json
1. Make sure the scripts property is above the version property

So your package.json should look something like this:

```
{
  "scripts": {
    "build": "rollup -c rollup.config.prod.js",
    "build:dev": "rollup -c rollup.config.debug.js",
    "clean": "rimraf coverage dist",
    "prepare": "npm run clean && npm run build",
    "test": "jest",
    "version": "echo version"
  },
  "version": "2.1.4"
}
```

Now run renovate in a way that opens a PR. Now view that PR and you'll find that your package.json file's scripts.version has been updated but the root version has not.

```
{
  "scripts": {
    "build": "rollup -c rollup.config.prod.js",
    "build:dev": "rollup -c rollup.config.debug.js",
    "clean": "rimraf coverage dist",
    "prepare": "npm run clean && npm run build",
    "test": "jest",
    "version": "2.1.5"
  },
  "version": "2.1.4"
}
```

**Additional context**

Sadly I don't have a public repository to show this off in (found it internally) but hopefully this is enough context to create a reproduction environment or a unit test.

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/c33da16aba2e3fff357ead02c79343ca614f827a/lib/manager/npm/update.ts#L37-L40

Happens because we use simple regex to replace. We should add the old value to the regex to replace

**Comment by rarkins** [comment]
In the meantime I assume you can work around this by moving the `version` field before `scripts`
