### ISSUE TITLE
Decouple postUpgradeTasks from trustLevel=high

### ISSUE THREAD

**Issue by dominykas** [renovatebot/renovate#7570]
**What would you like Renovate to be able to do?**

Run `postUpgradeTasks` without setting `trustLevel` to `high`.

Since the commands have to be added to `allowedPostUpgradeCommands` anyways, lowering the `trustLevel` is not necessary and probably undesirable? It's up to the admin whether they want to enforce it or not?

Not sure if setting the trust level implies an absolute zero of env vars - at the very least `PATH` could be useful?

**Did you already have any implementation ideas?**

Seems like it would need a single check removed?

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

**Is this a feature you'd be interested in implementing yourself?**

Sure

**Comment by rarkins** [comment]
Sounds fine by me

**Comment by rarkins** [comment]
Done in v25
