### ISSUE TITLE
Migrate deprecated internal presets

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#7572]
**What Renovate type, platform and version are you using?**

GitHub hosted app.

**Describe the bug**

I'm confused about what the correct base configuration is...

The docs for [config:base-js](https://docs.renovatebot.com/presets-config/#configbase-js) say this is deprecated:

```json
{
  "extends": [
    "config:base"
  ]
}
```

But that's what the Renovate bot gives me with its on-boarding pull requests.

I noticed that there are separate configurations for web-apps and libraries:
- [config:js-app](https://docs.renovatebot.com/presets-config/#configjs-app)
- [config:js-lib](https://docs.renovatebot.com/presets-config/#configjs-lib)

Shouldn't the bot try to use either `config:js-app` or `config:js-lib` in the on-boarding pull request?

**Relevant debug logs**

**To Reproduce**

~Take a look at this on-boarding pull request I got for a Docusaurus v2 web app: https://github.com/RoostingGeese/git-gosling/pull/47/commits/0cff58955f3166b247ebf73e54e0c73e79032ae6.~
~The bot used the deprecated `config:base-js` template instead of the `config:js-app` template.~
EDIT: Whoops! I totally misread the docs on this part, ignore the strike-through text.

**Additional context**

I think the Renovate bot already tries to determine if you have a web-app or library, to determine if it should pin your dependencies or not? So maybe this logic can be plugged into the onboarding pull request code?

**Comment by JamieMagee** [comment]
The PR you shared only shows `config:base` in `renovate.json`. This looks correct to me?

I don't think we need to explicity specify `config:js-app` or `config:js-lib`, as `config:base` already has `:autodetectPinVersions`, which deals with app/lib detections.

**Comment by rarkins** [comment]
`config:js-app` is deprecated. `config:base` is not. But actually now presets are internalized we could remove them completely and instead migrate them.

**Comment by HonkingGoose** [comment]
> The PR you shared only shows `config:base` in `renovate.json`. This looks correct to me?

The bot uses the right `config:base` item in `renovate.json`, so that part was me not reading the docs properly, whoops! :smile: 

---

> But actually now presets are internalized we could remove them completely and instead migrate them.

I don't really understand what this means, but I'll let you deal with this report how you see fit. :smile: :wink:

**Comment by rarkins** [comment]
We don't have too many presets mentioned as deprecated:

![image](https://user-images.githubusercontent.com/6311784/97311120-4fd3aa00-1864-11eb-9f8d-7d1318a1dc15.png)

For each of these we should remove them and instead add a migration rule in https://github.com/renovatebot/renovate/blob/master/lib/config/migration.ts

**Comment by HonkingGoose** [comment]
> 
> 
> We don't have too many presets mentioned as deprecated:
> 
> ![image](https://user-images.githubusercontent.com/6311784/97311120-4fd3aa00-1864-11eb-9f8d-7d1318a1dc15.png)
> 
> For each of these we should remove them and instead add a migration rule in https://github.com/renovatebot/renovate/blob/master/lib/config/migration.ts

@rarkins maybe this issue can be moved from "needs requirements" to "ready" on the Renovate project board? Seeing as you already gave the "recipe" of the changes?

**Comment by rarkins** [comment]
We now don't have any presets with deprecated in their description
