### ISSUE TITLE
Separate adminConfig

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7574]
During global initialization, we should separate out "admin" config (fields that cannot be overridden by users) from the rest (which might be overridden by user config).

I suggest we add a new lib/config/admin logic, which would have a `getAdminConfig()` function that can be called from anywhere to get the value of an admin setting. A similar `setAdminConfig()` function could be added that does the following:
- Takes the raw global config
- Detects admin fields and saves them in global admin state
- Returns back a filtered "remaining" config that is then used instead of the raw global one

One important reason to do this is to reduce the chance we could be susceptible to privilege escalation e.g. via prototype pollution. If the `config` we pass around contains admin fields which control permissions, then it provides a target for someone to try to overwrite them through any means to then overwrite admin controls.

**Comment by zharinov** [comment]
Are we okay to separate all the fields in `RenovateAdminConfig` interface?
https://github.com/renovatebot/renovate/blob/bb9e30f64a95d772421faa2483c6b9eab0f1c661/lib/config/common.ts#L70

**Comment by viceice** [comment]
Yes, that was one of the causes why i introduced this interface. So it can be removed from normal renovate config if we like. 🙃 

I think we need to move some more admin properties to that. I'm prety sure there are some inconsistencies

**Comment by zharinov** [comment]
> I think we need to move some more admin properties to that. I'm prety sure there are some inconsistencies

Okay, just let me know here while I'm migrating existing ones.

**Comment by rarkins** [comment]
Any new code should do this programmatically though, e.g. by checking the `admin` flag in the config definitions. Maybe there's a way to use TS to help us know what's missing?

**Comment by viceice** [comment]
> Maybe there's a way to use TS to help us know what's missing?

not really, we would need to generate some code from the config flags to support that
