### ISSUE TITLE
lint-fix bot

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7575]
**What would you like Renovate to be able to do?**

It would be nice if we had an automated process to run our `lint-fix` and commit changes back automatically to Pull Requests, especially because it's so easy to have `prettier` errors.

**Did you already have any implementation ideas?**

1. Theres's probably some attempts at `prettier` bots, but I'd like to have something which does our full `lint-fix`.

2. Run a GitHub Action to run `yarn lint-fix` and commit back any changes if so. However such a commit using the `GITHUB_TOKEN` won't trigger a CI run, plus the original commit will still get tested and fail

3. Can our current test run `lint-fix` instead of `lint` (which would mean it *passes* the tests it can fix, instead of fails them like today) and then push the additional commits back? So instead of today's:

```
          yarn eslint -f ./tmp/tools/eslint-gh-reporter.js
          yarn prettier
```

It might be like:

```
          yarn eslint -f ./tmp/tools/eslint-gh-reporter.js --fix
          yarn prettier --fix
          git add --all && git commit -m "lint fixes" && git push
```

Note that our process squash merging PRs to master means we don't care about extra commits.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Manual fixes

**Is this a feature you'd be interested in implementing yourself?**

@viceice is better at these things :D

**Comment by rarkins** [comment]
I already realized that the above isn't great. Although (3) might be achievable, only the *original* commit would be marked as checked and the new commit would not get its own check runs, meaning the PR can't be merged.

So then maybe a separate/new action runs for each non-master commit and uses a PAT to push changes back to the repo, which would then cancel all other actions which had already started on the original commit and start new tests?

The problem: PAT needs to be a *maintainer* PAT, in order to have rights to commit not only to this repo but also to forks (assuming the forker granted permissions, which they usually do).

**Comment by viceice** [comment]
maybe we can use something like [pull_request_target](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target) to allow retrigger a lint workflow and then trigger a test workflow with a PAT.

`pull_request_target` runs on base commit and has full access to secrets.

Another solution would to create a simple bot app, which triggers / syncs the required workflows. eg trigger test after pr sync

**Comment by viceice** [comment]
maybe [workflow_run](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run) will work too

**Comment by rarkins** [comment]
Sure if the current lint action has the ability trigger a fix action if linting fails, then that would be great. it will give feedback on the current commit as well as triggering tests on the new one

**Comment by viceice** [comment]
this can be challenging for pr, because we maybe aren't allowed to push back changes. 🤔 

the only event to trigger on a specific ref is [workflow_dispatch](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch)

also the github action token never triggers any workflow

**Comment by rarkins** [comment]
I wonder if when users tick "maintainers can modify", whether the `GITHUB_TOKEN` has rights to push back to the branch or not. I'm guessing not. @JamieMagee do you know?

Seems challenging:
- Assume that only a maintainer PAT can commit to a forked PR
- secrets (e.g. the maintainer PAT) are rightfully not exposed to forked PRs

Relevant discussions: 
- https://github.community/t/allow-secrets-to-be-shared-with-forks-from-trusted-actions/16525/5
- https://github.community/t/make-secrets-available-to-builds-of-forks/16166/35

**Comment by rarkins** [comment]
I don't think an app is going to be able to push a commit to forked PRs either

**Comment by viceice** [comment]
> I don't think an app is going to be able to push a commit to forked PRs either

true



> I wonder if when users tick "maintainers can modify", whether the `GITHUB_TOKEN` has rights to push back to the branch or not. I'm guessing not. @JamieMagee do you know?
> 
> Seems challenging:
> 
> * Assume that only a maintainer PAT can commit to a forked PR
> * secrets (e.g. the maintainer PAT) are rightfully not exposed to forked PRs
> 
> Relevant discussions:
> 
> * https://github.community/t/allow-secrets-to-be-shared-with-forks-from-trusted-actions/16525/5
> * https://github.community/t/make-secrets-available-to-builds-of-forks/16166/35

the only trigger i know is `pull_request_target`, which uses the workflows from base branch instead of merge commit and allows to use secrets on fork pr's

**Comment by rarkins** [comment]
A PAT with write permissions to non-protected branches is *hopefully* boring enough that nobody would try advanced techniques to compromise it.

**Comment by viceice** [comment]
yes, but it's even not available on normal fork pr's [pull_request](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request) event

**Comment by JamieMagee** [comment]
> I wonder if when users tick "maintainers can modify", whether the GITHUB_TOKEN has rights to push back to the branch or not. I'm guessing not. @JamieMagee do you know?

I'm not sure. [The documentation](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) says that `GITHUB_TOKEN` has read/write permissions to pull requests, but whether that extends to forks or not, it's not quite clear. There's one way to find out!

**Comment by rarkins** [comment]
@JamieMagee unfortunately it seems not.

[Working action on a PR from within the repo](https://github.com/rarkins/action-pr-commit/runs/1321040182?check_suite_focus=true)
[Failing action on a PR from a forked repo](https://github.com/rarkins/action-pr-commit/runs/1321047304?check_suite_focus=true)

**Comment by rarkins** [comment]
Another idea:

Have a dedicated repo in the org with a GitHub Action that can be triggered using dispatches. It is provisioned with a PAT which has "maintainer" rights to all the other repos you want run the bot on. i.e. privileges to edit PRs from forks.

The dispatch event needs to be sent info about the source repo and the PR.

The action does: clone the (other) repo, check out the branch, install `node_modules`, run a lint fix command, commit back any changes.

We don't want the PAT to be sniffable by rogue scripts added in the forked PR, so we'd need to run the install and lint commands within a Docker container with no access to the actions's env.

Keep this for public repos only to make it simpler, although I don't yet see any problem with private ones being supported other than that the dedicated repo would need to be private too.

Pretty heavy to do a full `node_modules` install every PR commit though, and I can't think of a good way to cache them for every single repo separately. Both `eslint` and `prettier` can use extensions/plugins so running `npx .....` won't work.

**Comment by viceice** [comment]
What about checkout base branch install and cache node_modules / yarn cache folder.
Then mount them to the lint container and run install / lint again. this would reduce the install load a bit or fully if no deps changes.

Maybe exclude renovate pr's fully? So no deps changes most of the time

**Comment by rarkins** [comment]
Yes but what I mean is that repo might need to check out and install for dozens or hundreds of its sibling repos, not sure you can cache that much..

**Comment by ylemkimon** [comment]
> Here's how I'd try to do it securely:
> 
> * Determine the base (`master` branch) commit of the PR
> * Clone (shallow)
> * Check out that base commit
> * Install (still using master)
> * Check out the PR's head commit

A malicious actor may check in a modified eslint or prettier binary, which would overwrite node_module installed via master.

**Comment by viceice** [comment]
new idea:
* use [pull_request_target](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target) to run on safe workflow
* check out merge sha
* run prettier
* if changes found, configure git PAT and push back changes

That way, the rettier action doesn't need a PAT, and we controll the git auth and push

**Comment by rarkins** [comment]
Important to have a way to not allow arbitrary JS to be run, e.g. as done by the prettifier bot ([link(https://www.prettifier.io/configure/prettier-configuration/)):

![image](https://user-images.githubusercontent.com/6311784/97847648-3c0ac680-1cf0-11eb-9bf3-bee357ede55d.png)

**Comment by rarkins** [comment]
Prettifier achieves this by calling prettier programmatically and loading allowed config files itself: https://github.com/kevgo/prettifier/blob/master/bot/src/on-pull-request.ts

**Comment by viceice** [comment]
right, as we have to use `persist-credentials=false` on checkout to remove our `GIHUB_TOKEN` from disk. Then the code can only change the checked out code. The code can't access any secrets by default.

And because we use `pull_request_target` the the code can't modify the running lint workflow. So we can only push attacket code back to the fork branch, which would trigger a new ci run with readlony github token and no secrets!

So i think my idea is very safe.

**Comment by rarkins** [comment]
Agreed, if we read non-interpreted config files only and call prettier programmatically, it should be pretty tight.

**Comment by ylemkimon** [comment]
It'd be possible for PRs to overwrite the prettier binary. So it should be checked whether the PR includes `node_modules` (I'm not sure this would be enough) or ideally run the linter in an isolated container.

**Comment by viceice** [comment]
as long as the action has no access to tokens / secrets, it can only change local code, which would be pushed back to origin branch (in a later action, which only runs some predefined git commands defined on base branch), as would an attacker directly try to send us malcious code. so we can review before merge.

We would also need to check last commit, so if it is our prettier fix, we can skip running again. That way we don't get a endless loop.


So the important things to do are running the lint from `pull_request_target` event and run normal checks on `pull_request` event.

That way an attacker needs to bypass our review and get his pr merged, which should never happen.

**Comment by viceice** [comment]
That way we can also run eslint fixes, if they are auto fixable

**Comment by viceice** [comment]
I'll assemble a pr to show how it can work, leaving the pat out for testing

**Comment by ylemkimon** [comment]
> as long as the action has no access to tokens / secrets,

This assumption wouldn't hold once a code has been executed.

1. The code may install a Git hook, which gets executed after adding the PAT
2. The code may start a daemon to monitor the PAT

It's also not 100% sure that the token is not accessible with `persist-credentials=false`, though this would be a vulnerability on GitHub Actions.

> That way we can also run eslint fixes, if they are auto fixable

eslint accepts executable `.js` configuration file.

**Comment by viceice** [comment]
ok, i've opened a basic pr to discuss this further.

basic workflow:
* checkout base commit
* install deps (with cache)
* checkout pr head commit
* run lint in docker container
* commit and push with `--no-verify` to suppres git hooks

So we will only commit existing changed files, if there are changes.

**Comment by jeff-cook** [comment]
Any thoughts of adding this as a renovate feature? 

The thought is to add a manager/data source that would run a command. (`yarn prettier --fix`)
Then if there are changes to the files create a PR for the fix.
This could then be used by almost any lint-style tool with a fix option. 

I think it would also resolve some of your security concerns because it is doing the exact same thing renovate is currently doing.

An outstanding question would be how to get the tools into the renovate image?

**Comment by rarkins** [comment]
@jeff-cook not the same topic as this issue. This issue is about lint fixing human PRs to this repo. Running fixes like prettier has been an idea we've toyed with for years but not yet added, so you might find an existing old issue for it still open if you search carefully. Otherwise please open a new issue

**Comment by nschloe** [comment]
I just started pre-commit's CI service, and it does pretty much what you want. pre-commit by itself isn't bad since it rejects commits that don't satisfy your linter (if you `pre-commit install`ed at some point). For everyone else, the CI fixes lint errors automatically.
