### ISSUE TITLE
Support rangeStrategy=update-lockfile when currentValue is not a version or version range

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7623]
**What would you like Renovate to be able to do?**

Support updating lock file versions in scenarios where the currentValue is not a valid version or range. e.g. in Cocoapods:

```
pod 'SwiftLint'
```

Or in npm with a `package.json` version like:

```
  "dependencies": {
    "lodash": "*"
  }
```

**Did you already have any implementation ideas?**

I think our workers/repository/process/lookup logic sets skipReason if the currentValue is not valid but we may need to either extend the definition of "valid" or else add a check to see if there's a `lockedVersion` before skipping it.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

No

**Is this a feature you'd be interested in implementing yourself?**

Maybe

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by rarkins** [comment]
Actually this might already be done - at least, in the lookupUpdates() function. There might be some per-manager work left to be done for some, but they should be split into separate issues with their own reproductions. Closing this.
