### ISSUE TITLE
Use automation to enforce one sentence per line

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#7630]
**What would you like Renovate to be able to do?**

We need an automatic way to enforce the "one sentence per line" standard, that @HonkingGoose just implemented in PR #7625.
@JamieMagee said that we could try making our own Prettier plugin.

At the most basic level, if this is the Markdown input:

```markdown
This is a sentence. This is a second sentence. This is a third sentence.
```

Then the Prettier plugin should fix it up like this:

```markdown
This is a sentence.
This is a second sentence.
This is a third sentence.
```

**Did you already have any implementation ideas?**

I've checked for viable ways to fix this with an existing package, but I haven't found a well maintained package.
This is discussed in https://github.com/renovatebot/renovate/issues/7545 (scroll trough the issue to see mentions of alternatives that were considered).

@viceice said:
> I think it should be easy doable to write a prettier plugin based on the textlint rule

Quote from @rarkins:
> I'm ok with that as long as we don't end up needing too many ignore statements throughout our markdown.

I'm willing to help where I can, I can at least write input and output files that you can use to test the plugin. :smile:

**Comment by HonkingGoose** [comment]
@JamieMagee Did you have any thoughts on how to get started with this?

I was thinking that maybe I can write some test cases, if you supply me with a "template" that I can fill in, so that I can see how the testcase works?

**Comment by HonkingGoose** [comment]
I've reviewed some incoming PRs that were not (yet) using the new style, and made suggestions to fix the style errors.
While I was doing this, I thought: "I don't know if we should enforce a style that we can't automate. It's a bit unfair to ask contributors to change their work when the linter says it's good to go....".
I also think this is a bit of a unfair surprise to spring on honest contributors.

Maybe we should:

- Tell me to stop reviewing for style "issues"
- Automate the problem with the linter plugin and then enforce the rule.

Or we could:

- Leave it be and focus attention on something else.

I don't know what the team's thoughts are on this?

**Comment by rarkins** [comment]
I agree, if we can't enforce and fix automatically using a linter then it's best to do the updating manually in batches instead of causing friction in PRs

**Comment by HonkingGoose** [comment]
> I agree, if we can't enforce and fix automatically using a linter then it's best to do the updating manually in batches instead of causing friction in PRs

I'll stop reviewing for these kinds of issues then. :+1:

**Comment by JamieMagee** [comment]
I have a prettier plugin for this working locally. Just need to deal with some edge cases where we don't want to break on every `.`. For example: `e.g.`, `i.e.`, `etc.`, `...`

**Comment by rarkins** [comment]
Just keep running it on the code base and adding "if" statements until it's good :D

**Comment by JamieMagee** [comment]
I'm going to park this for now. The corner cases have ended up being a lot larger than I assumed. It's things like markdown links, comments, etc.

I looked at the suggested plugins ([JoshuaKGoldberg/sentences-per-line](https://github.com/JoshuaKGoldberg/sentences-per-line), and [IQTLabs/textlint-rule-one-sentence-per-line](https://github.com/IQTLabs/textlint-rule-one-sentence-per-line)), and they don't deal with these corner cases either.

**Comment by rarkins** [comment]
![so close](https://user-images.githubusercontent.com/6311784/99251933-71460700-280e-11eb-8d78-52ba23329f2e.gif)

**Comment by HonkingGoose** [comment]
@rarkins Have you decided that we don't want to pursue this anymore? It was a really tricky problem to solve with automation, so I can understand just closing this. But wanted to check the reasoning with you. 😉

**Comment by rarkins** [comment]
I think it is unlikely we'll find an automated solution. And if a solution does get invented and one of us discovers it, I think we'd add it regardless of the state of this issue.

**Comment by HonkingGoose** [comment]
> I think it is unlikely we'll find an automated solution. And if a solution does get invented and one of us discovers it, I think we'd add it regardless of the state of this issue.

Ah okay, so we don't need to track this, because when we do find the solution, we'll just add it straight away. 😄 Gotcha!
