### ISSUE TITLE
Post-upgrade commands compile as templates

### ISSUE THREAD

**Issue by IKatsuba** [renovatebot/renovate#7633]
**What would you like Renovate to be able to do?**

I would like to configure Angular migrations for some npm packages. For this feature, I have to know about the previous and current package versions in post-upgrade commands. But it is possible only if commands will compile as templates in the changing context. For example
```json
{
  "postUpgradeTasks": {
    "commands": [
      "npm ci --ignore-scripts",
      "npx ng update {{{depName}}} --from={{{fromVersion}}} --to={{{toVersion}}} --migrateOnly --allowDirty --force"
    ],
    "fileFilters": ["**/**"]
  }
}
```

**Did you already have any implementation ideas?**

I have the PR #7632  :)

**Comment by IKatsuba** [comment]
This feature is closed by the `trustLevel === 'high'` flag. Allowed fields filter data for templating. Any thoughts on the additional security implications?

**Comment by viceice** [comment]
> This feature is closed by the `trustLevel === 'high'` flag. Allowed fields filter data for templating. Any thoughts on the additional security implications?

There is a idea to drop `trustLevel === 'high'` requirement, see #7570.

**Comment by IKatsuba** [comment]
Ok. But are `allowedPostUpgradeCommands` still exists?)

**Comment by viceice** [comment]
yes, but with #7570 you won't needs to set `trustLevel === 'high'`, which means less attack level, because renovate only pass limited env to child processes.

**Comment by IKatsuba** [comment]
@viceice do you have any thoughts? I don't understand what I have to do

**Comment by rarkins** [comment]
I agree, having `allowedPostUpgradeCommands` should already be secure enough.

But make sure it's validated similar to this (keeping in mind it's an array, not string): https://github.com/renovatebot/renovate/blob/9b96086f7777181d7477945a5add1732d2862725/lib/config/validation.ts#L115-L121

And also properly defined in here: https://github.com/renovatebot/renovate/blob/master/lib/util/template/index.ts

**Comment by rarkins** [comment]
One more question: is it possible that someone could have a "regular" post upgrade command that (a) doens't need or use a template, but (b) fails handlebars compilation, or produces a result which is undesirable?

I assume the answer is that yes it's possible, but in that case we need to think how to handle this, so we don't break any existing users of this feature, either by requiring a new syntax for templated commands or even a new config option.

**Comment by IKatsuba** [comment]
I can propose the `allowPostUpgradeCommandTemplating` flag (`false` by default) for enable/disable feature.

**Comment by rarkins** [comment]
> I can propose the `allowPostUpgradeCommandTemplating` flag (`false` by default) for enable/disable feature.

Although I dislike adding new config options unless we we have to, what you suggest is probably the most user-friendly approach instead of inventing a new syntax for the existing fields. @viceice what do you think?

The other items of validation and security still apply though

**Comment by viceice** [comment]
> > I can propose the `allowPostUpgradeCommandTemplating` flag (`false` by default) for enable/disable feature.
> 
> Although I dislike adding new config options unless we we have to, what you suggest is probably the most user-friendly approach instead of inventing a new syntax for the existing fields. @viceice what do you think?

🤔 not sure here, but for compatibillity it's best to add that flag

> 
> The other items of validation and security still apply though

maybe we need to filter the config object to only pass allowed values to the compile stage. 🤔

**Comment by rarkins** [comment]
> maybe we need to filter the config object to only pass allowed values to the compile stage. 🤔

We do: https://github.com/renovatebot/renovate/blob/e4fafdc3ac1b2dec18f417464cfc19de9b2de16a/lib/util/template/index.ts#L33-L85

**Comment by IKatsuba** [comment]
@rarkins @viceice can you review the linked PR? I added the `allowPostUpgradeCommandTemplating` flag
