### ISSUE TITLE
Lockfile maintenance branch not deleted automatically

### ISSUE THREAD

**Issue by peterjuras** [renovatebot/renovate#7636]
**What Renovate type, platform and version are you using?**

I'm using the hosted app on GitHub

**Describe the bug**

When merging a lockfile maintenance PR, the `renovate/lock-file-maintenance` branch is not deleted. When merging any other renovate PR, the branches are deleted automatically.

**Relevant debug logs**

/

**To Reproduce**

Not sure how to easily reproduce, but you can look at these two PRs:

1. https://github.com/peterjuras/react-time-sync/pull/324
2. https://github.com/peterjuras/react-time-sync/pull/323

At the end of the second PR you see that renovate deleted the branch after merging. The first PR - which was a lockfile maintenance PR - did not delete the branch.

**Additional context**

/

**Comment by HonkingGoose** [comment]
You might want to take a look at the [GitHub docs, automatic deletion of branches](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-the-automatic-deletion-of-branches).
If you turn on **Automatically delete head branches**, GitHub will delete the branch when the pull request is merged.
Note that this setting affects **all PRs** not just those from the Renovate bot.

**Comment by HonkingGoose** [comment]
This comment is for the maintainers of Renovate: I saw that the peterjuras/react-time-sync#324 branch was force-pushed by the Renovate bot. Maybe that confuses the Renovate bot when it tries to delete the branch?

**Comment by rarkins** [comment]
Yes, the problem is that if the branch exists then it will be reused.

We could minimize the impact of this by deleting branches after automerge (both in cases of branch or PR automerge). See https://github.com/renovatebot/renovate/issues/7412 for an already-existing issue for that.

But otherwise to fully resolve this issue we'd need to do something like this:
- If the update is lock file maintenance, and we've found that the branch exists, then try to find if there's a merged PR that points to the same commit SHA
- If so, assume it's an old branch and delete it before resuming regular logic

The only caution is to think how this works in the case of people mixing lock file maintenance with other types of updates.

**Comment by Turbo87** [comment]
FWIW in https://github.com/rust-lang/crates.io we have the same issue. I always have to manually delete the lockfile branches, but the other branches are deleted automatically.

I can't confirm though that the existing branches are reused. If I don't delete the lockfile branches then no new PRs will be opened in the next week until those branches are deleted.

**Comment by rarkins** [comment]
@Turbo87 so your use case is that you have the bors bot do the merge, but it doesn't delete the branch after? Can you enable automatic branch deletion using GitHub's features or does something block that?

**Comment by Turbo87** [comment]
> your use case is that you have the bors bot do the merge, but it doesn't delete the branch after?

yeah, correct.

> Can you enable automatic branch deletion using GitHub's features or does something block that?

I don't seem to have access to that setting, but I can ask to enable it 👍 

the easiest for us would be if renovate would delete the branch after the PR is merged, just like it does for regular dependency update PRs, but from your comment above it sounds like there are reasons that make this a little more complicated.

**Comment by rarkins** [comment]
Yeah, the challenge is knowing 100% sure that the branch is "abandoned" and not needed.

**Comment by Turbo87** [comment]
we have moved away from using bors and enabled the automatic branch removal since then, so I guess we can close the issue if nobody else has the same problem :)
