### ISSUE TITLE
"JavaScript heap out of memory" on "yarn install" step

### ISSUE THREAD

**Issue by Luchanso** [renovatebot/renovate#7665]
**What Renovate type, platform and version are you using?**
Self-hosted with bitbucket, image version: latest

**Describe the bug**

I running renovate bot on instance with 1024 mb memory and got error on `yarn install` in repository with many dependencies

**Relevant debug logs**
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa093f0 node::Abort() [node]
 2: 0xa097fc node::OnFatalError(char const*, char const*) [node]
 3: 0xb8431e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb84699 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd31055  [node]
 6: 0xd316e6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd3df65 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd3ee15 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd418cc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd0f7bc v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [node]
11: 0xf4f682 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [node]
12: 0x108919c v8::internal::Runtime_StringCharCodeAt(int, unsigned long*, v8::internal::Isolate*) [node]
13: 0x13cf099  [node]
Aborted (core dumped)
```

**To Reproduce**

This can reproduce on any repository with option `--max_old_space_size=128` I getting the same error
```
NODE_OPTIONS=--max_old_space_size=128 yarn install --force
```
Or any middle size JS/TS repository (I mean) with cypress 🤔 and machine with memory limit 1024 mb

**Additional context**
I was try to add env `NODE_OPTIONS=--max_old_space_size=2048`, but it's doesn't any effect
In my development environment this help for yarn: `NODE_OPTIONS=--max_old_space_size=2048 yarn install --force`

**Comment by JamieMagee** [comment]
To clarify, is this during a `yarn install` of Renovate (this repository), or as a post-update step while running Renovate against another repository?

**Comment by Luchanso** [comment]
While running Renovate on another repository

**Comment by JamieMagee** [comment]
Okay. There are a couple of things here:

1. Renovate uses in-memory caching heavily, to improve runtime. If you're running Renovate against several repositories at once, on an instance with small amounts of memory, you may run out of memory. If increasing the instance memory isn't possible, you can try running against one repository at a time, instead of several at once.

2. It sounds like we're not respecting `NODE_OPTIONS` environment variable. I haven't verified this, but I can't find it in the codebase, so we might not be passing it to Docker when running npm/yarn commands.

**Comment by rarkins** [comment]
Unless he's using binarySource=docker then it sound be a plain child process call and not Dockerized.

**Comment by rarkins** [comment]
Assuming it happens while yarn is running, it could be yarn itself running out of memory or also renovate running out of memory while buffering the stdout

**Comment by viceice** [comment]
`NODE_OPTIONS` would only passed to child process, if `trustLevel=high` is set.

**Comment by Luchanso** [comment]
@rarkins, yes, you right, I call renovate from JS:
```js
const renovate = spawn("docker-entrypoint.sh", {
    cwd: '/usr/src/app',
    stdio: "inherit",
    stderr: "inherit",
});
```

My docker file:
```Dockerfile
FROM renovate/renovate
WORKDIR /usr/src
COPY ./config.js ./app
COPY ./src ./cron/src
COPY ./yarn.lock ./cron
COPY ./package.json ./cron
USER root
RUN cd ./cron && yarn
USER 1000

CMD ["node", "./cron/src/index.js"]
```

I'll try `trustLevel=high` later, thank you

**Comment by Luchanso** [comment]
@viceice, yes `trustLevel=high` help pass NODE_ENV in `yarn install`, but now system kill application with out of memory error.

@JamieMagee how to run only single repository at a time? Config now looks like:
```js
module.exports = {
    endpoint: 'http://example.com/',
    platform: 'bitbucket-server',
    logLevel: 'debug',
    onboardingConfig: {
      extends: ['local>balbla/renovate-config']
    },
    repositories: [
      'blabla/abc-ui-1',
      'blabla/abc-ui-2',
      'blabla/abc-ui-3',
    ],
    gitAuthor: "Renovate Bot <renovate@whitesourcesoftware.com>",
    trustLevel: "high"
};
```

**Comment by Luchanso** [comment]
And guys, thank you all for help and for this amazing tool 👍

**Comment by rarkins** [comment]
Renovate will always run on a single repository at a time. 

I appreciate your thanks but unfortunately the way you're running it with a custom image isn't a supported configuration so I urge you to run our official image and/or submit a feature request describing what is missing to enable you to do so.
