### ISSUE TITLE
Suggest alternative libraries

### ISSUE THREAD

**Issue by ichiman** [renovatebot/renovate#7667]
**What would you like Renovate to be able to do?**

We are having couple of internal dependencies stored on private artifactory. Is it possible from Renovate to suggest alternative public libraries that can be used instead?

**Did you already have any implementation ideas?**

Npm packages are using keywords, maybe those keywords can be used to determine what alternative package is

**Comment by rarkins** [comment]
I doubt we could do that without most attempts being bad suggestions. I can envision a similar feature where we have a crowd-sourced list of public->public replacement recommendations, Eg from moment to luxon

**Comment by HonkingGoose** [comment]
Maybe this is something that the package maintainers themselves should add to their deprecation messages.

From the [NPM docs, deprecating and un deprecating packages](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions):
> To deprecate an entire package, run the following command, replacing `<package-name>` with the name of your package, and `"<message>"` with your deprecation message: `npm deprecate <package-name> "<message>"`

So the package maintainer can use that `message` field to say: "Package `snarglebarf` is deprecated but you can use `snarglebarf-replacement` instead."

I suppose other package managers will have a way to leave a message on a deprecated package as well, but I can't go and check for all package managers that Renovate supports... :smile:

**Comment by JamieMagee** [comment]
#5558 may cover this scenario.

**Comment by HonkingGoose** [comment]
PR #5558 is merged. 🥳 

You'll now get a special `replacement` PR to update from a deprecated npm package to the community suggested replacement. [^presets]
You can also make your own replacement PR rules, for `npm` packages. [^docs]

I'm not sure what we should do with this issue now that we have `npm` replacement support.
Do you want a new issue to track adding replacement PR support for more package managers?

[^presets]: https://docs.renovatebot.com/presets-replacements/
[^docs]: https://docs.renovatebot.com/configuration-options/#replacementversion

**Comment by rarkins** [comment]
I think let's close this one. @JamieMagee how many separate issues do you think are necessary for the remaining replacement logic? 1 for auto replace plus 1 for each manager which implements its own update logic?

**Comment by JamieMagee** [comment]
Let me get the PR out for autoreplace, and then I can open the others. I haven't had much time for renovate development recently, but that's what Christmas is for, right? 😅
