### ISSUE TITLE
dep.registryUrls value is wrong (function fetchDepUpdates@lib/workers/repository/process/fetch.ts)

### ISSUE THREAD

**Issue by zbyufei** [renovatebot/renovate#7681]
**What Renovate type, platform and version are you using?**

type:  https://github.com/renovatebot/renovate
version:  23.72.0

**Describe the bug**

my config.js:

```typescript
  packageRules: [
    {
      managers: ["maven"],
      registryUrls: [
        "http://xxx.com/repository/group-releases",
        "http://xxx.com/repository/group-snapshots"
      ]
    }
```
but when i debug dep.registryUrls (function fetchDepUpdates@lib/workers/repository/process/fetch.ts)
it show default value ["https://repo.maven.apache.org/maven2"]

**Relevant debug logs**

**To Reproduce**

**Additional context**

**Comment by rarkins** [comment]
Please reproduce in a public repository. The URLs you use shouldn't matter if they are not being looked up anyway
