### ISSUE TITLE
Release notes on GitLab are lossing formats.

### ISSUE THREAD

**Issue by wxsms** [renovatebot/renovate#7689]
**What Renovate type, platform and version are you using?**

self hosted, docker renovate/renovate:23.74, GitLab 10.3.2

**Describe the bug**

This screenshot should be clear enough:

![image](https://user-images.githubusercontent.com/5960988/98614561-a5fc1f00-2333-11eb-8c9e-3d33107cd7ec.png)

**Relevant debug logs**

This issue should have nothing to do with logs.

**To Reproduce**

Run renovate on GitLab with default config.

**Additional context**

Because the GitLab version is not under my control, I know that it's a bit out of date but I have no right to upgrade it. It looks like that gitlab has ignore the markdown syntax inside `<detail>` tag. Maybe an option to provide the ability to do not wrap changelogs in `<detail>` could solve this problem?

**Comment by rarkins** [comment]
Which version of GitLab are you using?

Can you reproduce the same behaviour on Gitlab.com?

**Comment by wxsms** [comment]
@rarkins GitLab 10.3.2. This problem do not happen on GitLab.com

**Comment by rarkins** [comment]
If it's due to an old or buggy GitLab release, we won't make changes to work around it.

You can set fetchReleaseNotes=false in config to disable release notes fetching if you consider the current result to be too messy to be useful

**Comment by wxsms** [comment]
@rarkins Thank you for the response. I understand that it is not possible to provide every work arounds for old platforms. But maybe we can provide an option to allow not using the `<details>` tag but plain markdowns? Or maybe there's already an option can use but I don't know yet?

If the option idea sounds good, I am happy to submit a PR to do so lately.

**Comment by wxsms** [comment]
> If it's due to an old or buggy GitLab release, we won't make changes to work around it.
> 
> You can set fetchReleaseNotes=false in config to disable release notes fetching if you consider the current result to be too messy to be useful

Btw, I really like the changelog feature and do not want to disable it.

**Comment by rarkins** [comment]
As a general rule: if a feature or option benefits a very small number of users, we can't justify adding it to the codebase.

Anything added to the code base needs ongoing maintenance and contributes ever so slightly to increased docs size, more to read for newcomers, etc.

Therefore unless the feature would be more widely beneficial or somehow reduce the maintenance burden elsewhere, we need to decline such a PR.

FYI the handlebars template that generates the text in question is here: https://github.com/renovatebot/renovate/blob/master/lib/workers/pr/changelog/hbs-template.ts

You could perhaps try building your own image with a modified version of that file, or even just `sed` replace parts of it at runtime. You can find it at `dist/workers/pr/changelog/hbs-template.js` in the built/distributed version.

**Comment by wxsms** [comment]
@rarkins Thank you for your fast and kindly help. I understand what you said, and will try the solutions you provided. 

If more people come up with such issue with GitLab or other platforms, you might reconsider my suggestion. I can help with this any time.

Thank you again for creating this decent tool.
