### ISSUE TITLE
Bump container image versions referenced in Helm charts

### ISSUE THREAD

**Issue by jaysiee** [renovatebot/renovate#7690]
**What would you like Renovate to be able to do?**

Helm charts can reference a number of container images each with it's own version. We would like renovate to check for these tags and bump them to a current version.

**Did you already have any implementation ideas?**

I haven't worked with renovate before, so I don't have any in detail ideas on how to do this.

In general, image tags are specified through yaml files (e.g. the values.yaml file). Each helm-chart instance can have multiple values files (e.g. for different environments). Thus, to identify all relevant keys renovate would have to scan each values file and change tags based on:

- conventions: identify versions based on yaml-structure and update specific keys (e.g. the "tag" key) - the default helm-chart created by Helm could be a starting point for a convention like this.
- configurable structures: give renovate yq-like parameter that specifies which tags are to be treated as images and bump versions in these tags where possible 

I'd be open to help adding this feature if there is positive feedback regarding the described use case.

**Comment by viceice** [comment]
We already have a helm values manager, so please check the docs if it's usable for you.

If you need another convention, you can always use a regex manager to update arbitrary strings in text files.

**Comment by jaysiee** [comment]
Ah, my bad. I didn't see that part in the documentation. I'll check it out and let you know if that solves our use-case. Thanks a lot!
