### ISSUE TITLE
docs: document new Terragrunt functionality

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#7713]
PR #7653 added `terragrunt` as a new manager.
This functionality is not yet documented in the https://github.com/renovatebot/renovate/blob/master/docs/usage/modules/manager.md file.

We need to update the docs to reflect the new functionality.

**Comment by HonkingGoose** [comment]
Or are the docs updated automatically?

```markdown
## Supported Managers

<!-- Autogenerate in https://github.com/renovatebot/renovatebot.github.io -->
<!-- Autogenerate end -->
```

**Comment by rarkins** [comment]
It's automatic

**Comment by rarkins** [comment]
See https://docs.renovatebot.com/modules/manager/terragrunt/

**Comment by HonkingGoose** [comment]
Whoops, sorry for opening this unnecessary issue!
