### ISSUE TITLE
NodeJS updates in package.json engines.node add v prefix

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#7715]
**What Renovate type, platform and version are you using?**

GitHub

**Describe the bug**

See https://github.com/felixfbecker/svg-screenshots/pull/7

Renovate adds the `v` prefix in the `engines.node` field, which is valid, but very unconventional in package.json (dependencies don't use it).

**Comment by viceice** [comment]
Try `extractVersion`

https://docs.renovatebot.com/configuration-options/#extractversion

**Comment by rarkins** [comment]
@viceice we should also try to figure out a way to do this automatically though.

**Comment by viceice** [comment]
We can do this for the official actions, but they can change the input with next major version.

I think the maintenance overhead would be pretty high.

**Comment by viceice** [comment]
Use a predefined regexManager with a special renovate comment postfix for match would be easier to do and maintain

**Comment by viceice** [comment]
Ups, wrong issue. Sure we can try to detect this issue here.

**Comment by viceice** [comment]
@felixfbecker  I can't see a `v` prefix in your pr.

@rarkins Did you change something?

**Comment by viceice** [comment]
there is `extractVersion` configured now

**Comment by viceice** [comment]
@felixfbecker can you provide a small reproduction repo without `extractVersion`, so we can debug against?

**Comment by felixfbecker** [comment]
@viceice I updated the config per your suggestions. Maybe you could fork the repo and reset the main branch to the commit that had the previous config?

**Comment by olegkrivtsov** [comment]
I'd like to take this one.

**Comment by viceice** [comment]
Please create a new reproduction, this is maybe already  fixed
