### ISSUE TITLE
Renovate bot not upgrading plugin version in Gradle Kotlin DSL script

### ISSUE THREAD

**Issue by BasicWolf** [renovatebot/renovate#7777]
**What Renovate type, platform and version are you using?**

* Initially discovered via Renovate-bot running on self-hosted Gitlab repositories; renovate/renovate:23.84.6-slim
* Tested and confirmed on Renovate Github application integration for public repositories. A link to a repository which reproduces the bug is provided at the end of the bug description.

**Describe the bug**

The project's `build.gradle.kts` definition has the following entries:

```kts
group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    jcenter()
}

plugins {
    java
    kotlin("jvm") version "1.3.71"
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("org.junit.jupiter:junit-jupiter:5.6.0")
}
```
Renovate-bot's pull request description contains updates to both *plugins* and dependencies:

![kuva](https://user-images.githubusercontent.com/1289161/99826551-31aa5280-2b61-11eb-8fbc-089ec3f12ed5.png)

However if we check the diff, dependencies and gradle is updated, but the plugins versions are not:

![kuva](https://user-images.githubusercontent.com/1289161/99826660-57cff280-2b61-11eb-814e-82bec34e947a.png)

**Relevant debug logs**
<details>
<summary>DEBUG logs</summary>
<pre>
DEBUG: Package releases lookups complete
{
  "baseBranch": "main"
}
DEBUG: packageFiles with updates
{
  "config": {
    "gradle": [
      {
        "packageFile": "build.gradle.kts",
        "datasource": "maven",
        "deps": [
          {
            "name": "org.jetbrains.kotlin.jvm.gradle.plugin",
            "depGroup": "org.jetbrains.kotlin.jvm",
            "depName": "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 0,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "dependencyUrl": "org/jetbrains/kotlin/jvm/org.jetbrains.kotlin.jvm.gradle.plugin"
          },
          {
            "name": "kotlin-stdlib-jdk8",
            "depGroup": "org.jetbrains.kotlin",
            "depName": "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 1,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Thu, 19 Nov 2020 08:30:08 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "sourceUrl": "https://github.com/JetBrains/kotlin",
            "homepage": "https://kotlinlang.org/",
            "dependencyUrl": "org/jetbrains/kotlin/kotlin-stdlib-jdk8"
          },
          {
            "name": "logback-classic",
            "depGroup": "ch.qos.logback",
            "depName": "ch.qos.logback:logback-classic",
            "currentValue": "1.2.3",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 2,
            "updates": [],
            "warnings": [],
            "fixedVersion": "1.2.3",
            "dependencyUrl": "ch/qos/logback/logback-classic"
          },
          {
            "name": "junit-jupiter",
            "depGroup": "org.junit.jupiter",
            "depName": "org.junit.jupiter:junit-jupiter",
            "currentValue": "5.6.0",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 3,
            "updates": [
              {
                "fromVersion": "5.6.0",
                "toVersion": "5.7.0",
                "newValue": "5.7.0",
                "newMajor": 5,
                "newMinor": 7,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Sun, 13 Sep 2020 13:14:44 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "5.6.0",
            "sourceUrl": "https://github.com/junit-team/junit5",
            "homepage": "https://junit.org/junit5/",
            "dependencyUrl": "org/junit/jupiter/junit-jupiter"
          },
          {
            "name": "kotlin-scripting-compiler-embeddable",
            "depGroup": "org.jetbrains.kotlin",
            "depName": "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 4,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Thu, 19 Nov 2020 08:28:00 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "sourceUrl": "https://github.com/JetBrains/kotlin",
            "homepage": "https://kotlinlang.org/",
            "dependencyUrl": "org/jetbrains/kotlin/kotlin-scripting-compiler-embeddable"
          }
        ]
      },
      {
        "packageFile": "gradle.properties",
        "datasource": "maven",
        "deps": [
          {
            "name": "org.jetbrains.kotlin.jvm.gradle.plugin",
            "depGroup": "org.jetbrains.kotlin.jvm",
            "depName": "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 0,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "dependencyUrl": "org/jetbrains/kotlin/jvm/org.jetbrains.kotlin.jvm.gradle.plugin"
          },
          {
            "name": "kotlin-stdlib-jdk8",
            "depGroup": "org.jetbrains.kotlin",
            "depName": "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 1,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Thu, 19 Nov 2020 08:30:08 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "sourceUrl": "https://github.com/JetBrains/kotlin",
            "homepage": "https://kotlinlang.org/",
            "dependencyUrl": "org/jetbrains/kotlin/kotlin-stdlib-jdk8"
          },
          {
            "name": "logback-classic",
            "depGroup": "ch.qos.logback",
            "depName": "ch.qos.logback:logback-classic",
            "currentValue": "1.2.3",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 2,
            "updates": [],
            "warnings": [],
            "fixedVersion": "1.2.3",
            "dependencyUrl": "ch/qos/logback/logback-classic"
          },
          {
            "name": "junit-jupiter",
            "depGroup": "org.junit.jupiter",
            "depName": "org.junit.jupiter:junit-jupiter",
            "currentValue": "5.6.0",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 3,
            "updates": [
              {
                "fromVersion": "5.6.0",
                "toVersion": "5.7.0",
                "newValue": "5.7.0",
                "newMajor": 5,
                "newMinor": 7,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Sun, 13 Sep 2020 13:14:44 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "5.6.0",
            "sourceUrl": "https://github.com/junit-team/junit5",
            "homepage": "https://junit.org/junit5/",
            "dependencyUrl": "org/junit/jupiter/junit-jupiter"
          },
          {
            "name": "kotlin-scripting-compiler-embeddable",
            "depGroup": "org.jetbrains.kotlin",
            "depName": "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 4,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Thu, 19 Nov 2020 08:28:00 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "sourceUrl": "https://github.com/JetBrains/kotlin",
            "homepage": "https://kotlinlang.org/",
            "dependencyUrl": "org/jetbrains/kotlin/kotlin-scripting-compiler-embeddable"
          }
        ]
      },
      {
        "packageFile": "settings.gradle.kts",
        "datasource": "maven",
        "deps": [
          {
            "name": "org.jetbrains.kotlin.jvm.gradle.plugin",
            "depGroup": "org.jetbrains.kotlin.jvm",
            "depName": "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 0,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "dependencyUrl": "org/jetbrains/kotlin/jvm/org.jetbrains.kotlin.jvm.gradle.plugin"
          },
          {
            "name": "kotlin-stdlib-jdk8",
            "depGroup": "org.jetbrains.kotlin",
            "depName": "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 1,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Thu, 19 Nov 2020 08:30:08 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "sourceUrl": "https://github.com/JetBrains/kotlin",
            "homepage": "https://kotlinlang.org/",
            "dependencyUrl": "org/jetbrains/kotlin/kotlin-stdlib-jdk8"
          },
          {
            "name": "logback-classic",
            "depGroup": "ch.qos.logback",
            "depName": "ch.qos.logback:logback-classic",
            "currentValue": "1.2.3",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 2,
            "updates": [],
            "warnings": [],
            "fixedVersion": "1.2.3",
            "dependencyUrl": "ch/qos/logback/logback-classic"
          },
          {
            "name": "junit-jupiter",
            "depGroup": "org.junit.jupiter",
            "depName": "org.junit.jupiter:junit-jupiter",
            "currentValue": "5.6.0",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 3,
            "updates": [
              {
                "fromVersion": "5.6.0",
                "toVersion": "5.7.0",
                "newValue": "5.7.0",
                "newMajor": 5,
                "newMinor": 7,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Sun, 13 Sep 2020 13:14:44 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "5.6.0",
            "sourceUrl": "https://github.com/junit-team/junit5",
            "homepage": "https://junit.org/junit5/",
            "dependencyUrl": "org/junit/jupiter/junit-jupiter"
          },
          {
            "name": "kotlin-scripting-compiler-embeddable",
            "depGroup": "org.jetbrains.kotlin",
            "depName": "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable",
            "currentValue": "1.3.71",
            "registryUrls": [
              "https://repo.maven.apache.org/maven2/",
              "https://jcenter.bintray.com/",
              "https://plugins.gradle.org/m2"
            ],
            "depIndex": 4,
            "updates": [
              {
                "fromVersion": "1.3.71",
                "toVersion": "1.4.20",
                "newValue": "1.4.20",
                "newMajor": 1,
                "newMinor": 4,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "Thu, 19 Nov 2020 08:28:00 GMT"
              }
            ],
            "warnings": [],
            "fixedVersion": "1.3.71",
            "sourceUrl": "https://github.com/JetBrains/kotlin",
            "homepage": "https://kotlinlang.org/",
            "dependencyUrl": "org/jetbrains/kotlin/kotlin-scripting-compiler-embeddable"
          }
        ]
      }
    ],
    "gradle-wrapper": [
      {
        "packageFile": "gradle/wrapper/gradle-wrapper.properties",
        "manager": "gradle-wrapper",
        "deps": [
          {
            "depName": "gradle",
            "currentValue": "6.3",
            "datasource": "gradle-version",
            "versioning": "gradle",
            "depIndex": 0,
            "updates": [
              {
                "fromVersion": "6.3",
                "toVersion": "6.7.1",
                "newValue": "6.7.1",
                "newMajor": 6,
                "newMinor": 7,
                "updateType": "minor",
                "isSingleVersion": true,
                "releaseTimestamp": "2020-11-16T17:09:24+0000"
              }
            ],
            "warnings": [],
            "fixedVersion": "6.3",
            "sourceUrl": "https://github.com/gradle/gradle",
            "homepage": "https://gradle.org"
          }
        ]
      }
    ]
  }
}
DEBUG: branchifyUpgrades
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin:kotlin-stdlib-jdk8 is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.junit.jupiter:junit-jupiter is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin:kotlin-stdlib-jdk8 is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.junit.jupiter:junit-jupiter is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin:kotlin-stdlib-jdk8 is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.junit.jupiter:junit-jupiter is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable is part of group Gradle packages
DEBUG: Using group branchName template
DEBUG: Dependency gradle is part of group Gradle packages
DEBUG: 13 flattened updates found: org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, org.jetbrains.kotlin:kotlin-stdlib-jdk8, org.junit.jupiter:junit-jupiter, org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, org.jetbrains.kotlin:kotlin-stdlib-jdk8, org.junit.jupiter:junit-jupiter, org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, org.jetbrains.kotlin:kotlin-stdlib-jdk8, org.junit.jupiter:junit-jupiter, org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, gradle
DEBUG: Returning 1 branch(es)
DEBUG: config.repoIsOnboarded=true
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/gradle-packages
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 1 Pull Requests
DEBUG: currentHourStart=2020-11-20T11:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/gradle-packages)
DEBUG: findPr(renovate/gradle-packages, undefined, open)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 20
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 2
}
DEBUG: getBranchPr(renovate/gradle-packages)(branch="renovate/gradle-packages")
DEBUG: findPr(renovate/gradle-packages, undefined, open)(branch="renovate/gradle-packages")
DEBUG: processBranch with 13 upgrades(branch="renovate/gradle-packages")
DEBUG: Setting current branch to main(branch="renovate/gradle-packages")
DEBUG: latest commit(branch="renovate/gradle-packages")
{
  "branchName": "main",
  "latestCommitDate": "2020-11-20T13:53:54+02:00"
}
DEBUG: getBranchPr(renovate/gradle-packages)(branch="renovate/gradle-packages")
DEBUG: findPr(renovate/gradle-packages, undefined, open)(branch="renovate/gradle-packages")
DEBUG: branchExists=false(branch="renovate/gradle-packages")
DEBUG: Branch has 5 upgrade(s)(branch="renovate/gradle-packages")
DEBUG: recreateClosed is true(branch="renovate/gradle-packages")
DEBUG: Checking schedule(at any time, null)(branch="renovate/gradle-packages")
DEBUG: No schedule defined(branch="renovate/gradle-packages")
DEBUG: Branch needs creating(branch="renovate/gradle-packages")
DEBUG: Using reuseExistingBranch: false(branch="renovate/gradle-packages")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/gradle-packages")
{
  "reuseExistingBranch": false,
  "branchName": "renovate/gradle-packages"
}
DEBUG: Starting search at index 131(packageFile="gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-packages")
{
  "depName": "gradle"
}
DEBUG: Found match at index 131(packageFile="gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-packages")
{
  "depName": "gradle"
}
DEBUG: gradle-wrapper.extractPackageFile()(branch="renovate/gradle-packages")
DEBUG: Gradle Wrapper(branch="renovate/gradle-packages")
{
  "depName": "gradle",
  "currentValue": "6.7.1",
  "datasource": "gradle-version",
  "versioning": "gradle"
}
DEBUG: Contents updated(packageFile="gradle/wrapper/gradle-wrapper.properties", branch="renovate/gradle-packages")
{
  "depName": "gradle"
}
DEBUG: gradle.updateDependency(): packageFile:settings.gradle.kts depName:org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:gradle.properties depName:org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:build.gradle.kts depName:org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:settings.gradle.kts depName:org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:gradle.properties depName:org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:build.gradle.kts depName:org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:settings.gradle.kts depName:org.jetbrains.kotlin:kotlin-stdlib-jdk8, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:gradle.properties depName:org.jetbrains.kotlin:kotlin-stdlib-jdk8, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:build.gradle.kts depName:org.jetbrains.kotlin:kotlin-stdlib-jdk8, version:1.3.71 ==> 1.4.20(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:settings.gradle.kts depName:org.junit.jupiter:junit-jupiter, version:5.6.0 ==> 5.7.0(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:gradle.properties depName:org.junit.jupiter:junit-jupiter, version:5.6.0 ==> 5.7.0(branch="renovate/gradle-packages")
DEBUG: gradle.updateDependency(): packageFile:build.gradle.kts depName:org.junit.jupiter:junit-jupiter, version:5.6.0 ==> 5.7.0(branch="renovate/gradle-packages")
DEBUG: Updating packageFile content(packageFile="build.gradle.kts", branch="renovate/gradle-packages")
{
  "depName": "org.junit.jupiter:junit-jupiter"
}
DEBUG: gradle-wrapper.updateArtifacts()(branch="renovate/gradle-packages")
{
  "updatedDeps": [
    "gradle"
  ]
}
DEBUG: Updating gradle wrapper: "./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-6.7.1-bin.zip"(branch="renovate/gradle-packages")
DEBUG: Using docker to execute(branch="renovate/gradle-packages")
DEBUG: No tag or tagConstraint specified(branch="renovate/gradle-packages")
{
  "image": "docker.io/renovate/gradle"
}
DEBUG: Docker image is already prefetched: docker.io/renovate/gradle(branch="renovate/gradle-packages")
DEBUG: Executing command(branch="renovate/gradle-packages")
{
  "command": "docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/BasicWolf/renovate-kotlin-gradle-dsl-plugins-bug-showcase\":\"/mnt/renovate/gh/BasicWolf/renovate-kotlin-gradle-dsl-plugins-bug-showcase\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/BasicWolf/renovate-kotlin-gradle-dsl-plugins-bug-showcase\" docker.io/renovate/gradle bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-6.7.1-bin.zip\""
}
DEBUG: exec completed(branch="renovate/gradle-packages")
{
  "cmd": "docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/BasicWolf/renovate-kotlin-gradle-dsl-plugins-bug-showcase\":\"/mnt/renovate/gh/BasicWolf/renovate-kotlin-gradle-dsl-plugins-bug-showcase\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/BasicWolf/renovate-kotlin-gradle-dsl-plugins-bug-showcase\" docker.io/renovate/gradle bash -l -c \"./gradlew wrapper --gradle-distribution-url https://services.gradle.org/distributions/gradle-6.7.1-bin.zip\"",
  "durationMs": 242967,
  "stdout": "Downloading https://services.gradle.org/distributions/gradle-6.7.1-bin.zip\n.........10%..........20%..........30%..........40%..........50%.........60%..........70%..........80%..........90%..........100%\n\nWelcome to Gradle 6.7.1!\n\nHere are the highlights of this release:\n - File system watching is ready for production use\n - Declare the version of Java your build requires\n - Java 15 support\n\nFor more details see https://docs.gradle.org/6.7.1/release-notes.html\n\nTo honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.7.1/userguide/gradle_daemon.html.\nDaemon will be stopped at the end of the build stopping after processing\nConfiguration on demand is an incubating feature.\n> Task :wrapper\n\nBUILD SUCCESSFUL in 4m 0s\n1 actionable task: 1 executed\n",
  "stderr": ""
}
DEBUG: Returning updated gradle-wrapper files(branch="renovate/gradle-packages")
{
  "files": [
    "gradle/wrapper/gradle-wrapper.properties",
    "gradle/wrapper/gradle-wrapper.jar",
    "gradlew"
  ]
}
DEBUG: Updated 2 package files(branch="renovate/gradle-packages")
DEBUG: Updated 3 lock files(branch="renovate/gradle-packages")
{
  "updatedArtifacts": [
    "gradle/wrapper/gradle-wrapper.properties",
    "gradle/wrapper/gradle-wrapper.jar",
    "gradlew"
  ]
}
DEBUG: 4 file(s) to commit(branch="renovate/gradle-packages")
DEBUG: Committing files to branch renovate/gradle-packages(branch="renovate/gradle-packages")
INFO: Branch created(branch="renovate/gradle-packages")
{
  "commitSha": "2e30fc7"
}
DEBUG: Ensuring PR(branch="renovate/gradle-packages")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/gradle-packages")
DEBUG: getBranchPr(renovate/gradle-packages)(branch="renovate/gradle-packages")
DEBUG: findPr(renovate/gradle-packages, undefined, open)(branch="renovate/gradle-packages")
DEBUG: Removing duplicate release notes(branch="renovate/gradle-packages")
{
  "depName": "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}
DEBUG: Creating PR(branch="renovate/gradle-packages")
{
  "prTitle": "Update Gradle packages"
}
DEBUG: Creating PR(branch="renovate/gradle-packages")
{
  "title": "Update Gradle packages",
  "head": "BasicWolf:renovate/gradle-packages",
  "base": "main",
  "draft": false
}
DEBUG: PR created(branch="renovate/gradle-packages")
{
  "pr": 3,
  "draft": false
}
DEBUG: Adding labels '' to #3(branch="renovate/gradle-packages")
INFO: PR created(branch="renovate/gradle-packages")
{
  "pr": 3,
  "prTitle": "Update Gradle packages"
}
DEBUG: Created Pull Request #3(branch="renovate/gradle-packages")
DEBUG: Retrieved closed PR list with graphql(branch="renovate/gradle-packages")
{
  "prNumbers": [
    1
  ]
}
DEBUG: Getting comments for #3(branch="renovate/gradle-packages")
DEBUG: Found 0 comments(branch="renovate/gradle-packages")
DEBUG: Checking #3 for automerge(branch="renovate/gradle-packages")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/gradle-packages")
DEBUG: getBranchPr(renovate/gradle-packages)
DEBUG: findPr(renovate/gradle-packages, undefined, open)
DEBUG: Found PR #3
DEBUG: Returning from graphql open PR list
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/gradle-packages"
  ],
  "renovateBranches": [
    "renovate/configure",
    "renovate/gradle-packages"
  ]
}
DEBUG: remainingBranches=renovate/configure
DEBUG: findPr(renovate/configure, undefined, open)
DEBUG: Last commit author does not match git author email - branch has been modified
{
  "branchName": "renovate/configure",
  "lastAuthor": "zaur@znasibov.info",
  "gitAuthorEmail": "bot@renovateapp.com"
}
INFO: Deleting orphan branch(branch="renovate/configure")
DEBUG: No remote branch to delete
{
  "branchName": "renovate/configure"
}
DEBUG: No local branch to delete
{
  "branchName": "renovate/configure"
}
DEBUG: Repository timing splits (milliseconds)
{
  "splits": {
    "init": 3275,
    "extract": 243771,
    "lookup": 17719,
    "update": 251683
  },
  "total": 517583
}
DEBUG: http statistics
{
  "hostStats": [
    "api.github.com, 29 requests, 2082ms request average, 0ms queue average",
    "jcenter.bintray.com, 4 requests, 152ms request average, 0ms queue average",
    "plugins.gradle.org, 6 requests, 331ms request average, 0ms queue average",
    "repo.maven.apache.org, 4 requests, 86ms request average, 0ms queue average",
    "services.gradle.org, 1 request, 308ms request average, 0ms queue average"
  ],
  "totalRequests": 44
}
INFO: Repository finished
{
  "durationMs": 517583
}
</pre>
</details>

**To Reproduce**
The example repository with open pull request from Renovate: 
https://github.com/BasicWolf/renovate-kotlin-gradle-dsl-plugins-bug-showcase

Renovate has been suspended for the repository to keep its bug demostration state intact.

**Comment by charleskorn** [comment]
Is this something that is being actively worked on? This is quite annoying for me as I have to manually update a number of different projects. 

Alternatively, if this is something that is easy to fix, could you provide some pointers for where to look? I'm happy to try to pull together a PR if it's going to be an easy fix.

**Comment by rarkins** [comment]
@charleskorn can you test if the same problem applies to the gradle-lite manager?

**Comment by charleskorn** [comment]
@rarkins the `gradle-lite` manager seems to work fine - https://github.com/charleskorn/kaml/pull/108 and https://github.com/charleskorn/kaml/pull/107/files are both examples of PRs generated by gradle-lite that I'd expect the default `gradle` manager to generate.

**Comment by zharinov** [comment]
Also, I've just checked it out with the reproduction repo: https://github.com/renovate-testing/test-7777-try-gradle-lite/pull/1/files

**Comment by viceice** [comment]
@rarkins switching to gradle-lite on next major?

**Comment by BasicWolf** [comment]
Shall this issue be closed? Seems that things are fixed and working with `gradle-lite`.
