### ISSUE TITLE
feat(git-refs): git datasource should support auth from hostRules

### ISSUE THREAD

**Issue by lukasmrtvy** [renovatebot/renovate#7783]
**What Renovate type, platform and version are you using?**
- kustomize ( remote bases )
- gitlab selfhosted
- renovate/renovate:23.84.8

**Describe the bug**

Multiple nested groups url groups in Gitlab does not work in kustomize manager  ( remote bases ).
For example URL like https://gitlab.example.com/group/nestedgroup/nestedgroup/nestedgroup/repository.git

**Relevant debug logs**

```
         "kustomize": [
           {
             "packageFile": "kustomization.yaml",
             "manager": "kustomize",
             "deps": [
               {
                 "datasource": "git-tags",
                 "depName": "gitlab.example.com/group/nestedgroup",
                 "depNameShort": "group/nestedgroup",
                 "lookupName": "https://gitlab.example.com/group/nestedgroup",
                 "currentValue": "1.0.0",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [
                   {
                     "depName": "gitlab.example.com/group/nestedgroup",
                     "message": "Failed to look up dependency gitlab.example.com/group/nestedgroup"
                   }
                 ],
                 "fixedVersion": "1.0.0"
               },
...
```

**To Reproduce**

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://gitlab.example.com/group/nestedgroup/nestedgroup/nestedgroup/repository.git?ref=1.0.0
```

**Comment by viceice** [comment]
Can you please provide some more debug logs. We need the errors logged at lookup phase. They should be logged before the updates summary

**Comment by lukasmrtvy** [comment]
@viceice 
Do I need to configure also:
```
    hostRules: [{
      domainName: "gitlab.example.com",
      username: process.env.DEPLOY_RO_TOKEN_USERNAME,
      password: process.env.DEPLOY_RO_TOKEN_PASSWORD,
      enabled: true
    }],
```
for kustomize remote base expansion? Or is this handled via `RENOVATE_TOKEN` ? Its technically pointing to same selfhosted Gitlab and Renovate member has rights to view this ( kustomize remote base ) git repository.


I believe that problem is here:
```
DEBUG: Datasource unknown error (repository=engineering/environments/ondemand)
       "datasource": "git-tags",
       "lookupName": "https://gitlab.example.com/engineering/cd",
       "err": {
         "task": {
           "commands": ["ls-remote", "https://gitlab.example.com/engineering/cd"],
           "format": "utf-8"
         },
         "message": "fatal: could not read Username for 'https://gitlab.example.com': No such device or address\n",
         "stack": "Error: fatal: could not read Username for 'https://gitlab.example.com': No such device or address\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:66:77)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:58:21)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
```

**Comment by viceice** [comment]
1. You do not need the `enabled: true` 
1. Currently git datasources doesn't support auth, see renovatebot/renovate#6566 😕

**Comment by viceice** [comment]
duplicates #5471

**Comment by lukasmrtvy** [comment]
@viceice 

3. Seem its also not possible to use `process.env.MYENV` in hostRules 
4. not sure if https://github.com/renovatebot/renovate/issues/5471 covers also git over http, and kustomize is using https://github.com/hashicorp/go-getter, so there may be additional formats of remote bases.

**Comment by viceice** [comment]
Kustomize currently only supports git urls. it has a special handling for github.com to use `github-tags` datasource.
For all other urls it uses the `git-tags` datasource, which depends on `git-refs`.

`git-refs` currently doesn't support any hostRules. You can try to use a package rule to redirect to `gitlab-tags` datasource, which supports self-hosted gitlab and auth.

**Comment by lukasmrtvy** [comment]
@viceice I created https://github.com/renovatebot/config-help/issues/1013
