### ISSUE TITLE
docs: mention Merge Confidence in some way

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#7795]
**What Renovate type, platform and version are you using?**

Doesn't matter.

**Describe the bug**

I'm missing a link/reference/short explanation of Merge Confidence in the docs for the Renovate bot.

**Relevant debug logs**

None.

**To Reproduce**

Search in current `master` source code for string `merge confidence`: 0 hits.

**Additional context**

I think we should probably at least have a link/reference to this new functionality.
This will also help steer the reader in the right direction for support.

I was thinking of making a PR, but I don't know what the scope should be, and where it would be best placed.
So I'm opening this issue to discuss this first.
Of course, as always, I'm willing to make a draft PR for your review. :wink:

**Comment by rarkins** [comment]
There's a pinned issue, and there's also a page on docs.renovatebot.com. Maybe enough?

**Comment by HonkingGoose** [comment]
I saw the pinned issue, but I couldn't find it mentioned in the `master` source by searching for a relevant string, so I thought we are missing something here...

Now that I check on the live site, I see the new page that you are autogenerating from the repository. :nerd_face: 

It's keeps confusing me that you autogenerate some things from another repository as source, as then I can't search for them in the main source files. This makes it a bit harder to see if things are actually present or not in the documentation. :confused: 

Should I consider the published site as the "source of truth" for what's included then in future?

I'm closing this issue, as the original issue is fixed.

**Comment by rarkins** [comment]
The documentation repository is the single source of truth for docs.renovatebot.com. I hope it can be moved into this repo soon.

Merge Confidence is currently independent of this repo's code so therefore appropriate to have in its own repo. We may pull more external files into the documentation site in future.
