### ISSUE TITLE
Support lein-parent as a dependency for clojure projects

### ISSUE THREAD

**Issue by skaasten** [renovatebot/renovate#7815]
**What would you like Renovate to be able to do?**

Recognize parent-project as a dependency and check for updates on that version.

[Lein-parent](https://github.com/achin/lein-parent#managed-dependencies) allows dependencies to be inherited from another project.

**Did you already have any implementation ideas?**

Possibly update the logic in https://github.com/renovatebot/renovate/blob/master/lib/manager/leiningen/extract.ts#L142 to look for the `:parent-project` key and add that as a dependency to be checked.

I could take a stab at implementing myself.

**Comment by rarkins** [comment]
Can you create an example repository to demonstrate what you mean? I assume the latent project is within the same repo?

**Comment by skaasten** [comment]
Technically the parent-project can be in the same repo, but I think it would only be necessary to support external parents, such as this [example](https://github.com/puppetlabs/clj-kitchensink/blob/master/project.clj#L8).

**Comment by rarkins** [comment]
So is it the 4.0.0 that you expect to get updated?

**Comment by skaasten** [comment]
Yes, that's correct.

**Comment by skaasten** [comment]
Let me know if there's any more information needed to prioritize.

**Comment by rarkins** [comment]
This would be the file that needs changing: https://github.com/renovatebot/renovate/blob/master/lib/manager/leiningen/extract.ts

**Comment by HonkingGoose** [comment]
@skaasten do you still want to work on this? We could assign you to this issue, so that we know you would be working on it. But feel free to refuse, no pressure! 😄

**Comment by skaasten** [comment]
> @skaasten do you still want to work on this? We could assign you to this issue, so that we know you would be working on it. But feel free to refuse, no pressure! 😄

😄 I have a work-around, so we can close this if no-one else is asking for it.
