### ISSUE TITLE
Renovate downgrades spring cloud dependency for maven

### ISSUE THREAD

**Issue by jfneis** [renovatebot/renovate#7817]
**What Renovate type, platform and version are you using?**

Self-hosted, Bitbucket Cloud, 23.86.2

**Describe the bug**

When scanning a project that has spring-cloud-starter-parent as a dependency using Edgware.RELEASE, Renovate suggests upgrade to 1.0.2.RELEASE, which is an older version. It should suggest Edgware.SR6 as a minor or Hoxton.SR9 as a major.

**Relevant debug logs**

```
{
                 "datasource": "maven",
                 "depName": "org.springframework.cloud:spring-cloud-starter-parent",
                 "currentValue": "Edgware.RELEASE",
                 "fileReplacePosition": 1325,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "depIndex": 0,
                 "updates": [
                   {
                     "fromVersion": "Edgware.RELEASE",
                     "toVersion": "1.0.2.RELEASE",
                     "newValue": "1.0.2.RELEASE",
                     "newMajor": 1,
                     "newMinor": 0,
                     "updateType": "minor",
                     "isSingleVersion": true,
                     "releaseTimestamp": "Wed, 06 May 2015 10:53:46 GMT"
                   }
                 ],
                 "warnings": [],
                 "fixedVersion": "Edgware.RELEASE",
                 "homepage": "http://projects.spring.io/spring-cloud",
                 "dependencyUrl": "org/springframework/cloud/spring-cloud-starter-parent"
               }
```

**To Reproduce**

Any maven project with the following dependency:

```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-parent</artifactId>
				<version>Edgware.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

**Additional context**

Seems a similar issue was related [here](https://github.com/renovatebot/renovate/issues/5182), but in that case the downgrade was inside the same major version.

**Comment by rarkins** [comment]
The Maven versioning scheme we use sorts characters before digits, which seems consistent with https://octopus.com/blog/maven-versioning-explained#a-sorted-list-of-versions

This would explain why `1.0.2.RELEASE` sorts higher than `Edgware.RELEASE`. Why does the `1.0.2` prefix even exist if they are using alphabetic release names? You could ignore it using Renovate's `allowedVersions` using a negative regex match.

I'm also not sure we have the concepts of major/minor/patch when version strings are not versions, however Hoxton would sort after Edgware so you'd probably see an update to Hoxton if it weren't for the `1.0.2` existing.

**Comment by rarkins** [comment]
Can you try adding this? I think it will result in you getting a Hoxton update.

```json
  "packageRules": [{
    "packageNames": ["org.springframework.cloud:spring-cloud-starter-parent"],
    "allowedVersions": "/^[A-Z]/"
  }]
```

**Comment by jfneis** [comment]
Perfect @rarkins , thanks for your prompt response! Worked like a charm with this configuration.

As I found another issues about Spring Cloud non-numeric versioning I believed it could be a similar problem, but I also believe Renovate's behavior is ok.

**Comment by rarkins** [comment]
Thanks for confirming, I'm going to add this to our workarounds preset so that anyone using `config:base` gets this ignored by default
