### ISSUE TITLE
nuget: Support global.json sdk config

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#7825]
**What would you like Renovate to be able to do?**

We should support updates and constraints for [`global.json`](renovatebot/docker-buildpack/issues/72) files

**Did you already have any implementation ideas?**

sure 🙃 

~blocked by: renovatebot/docker-dotnet#18~

**Comment by dannyBies** [comment]
This is a feature I am looking for as well.

**Comment by ChangeTheCode** [comment]
This feature should now be available in renovate bot
