### ISSUE TITLE
Gradle: Renovate sometimes downgrades versions when it thinks it's updating

### ISSUE THREAD

**Issue by Meemaw** [renovatebot/renovate#7834]
**What Renovate type, platform and version are you using?**

Whitesource Renovate Github app

**Describe the bug**

It seems that in some cases Renovate downgrades dependency versions? I've seen this happening with Gradle plugins.

**To Reproduce**

https://github.com/insights-io/Insight/pull/948

**Comment by rarkins** [comment]
That's definitely not intended. You can see from the PR body that it thinks it's upgrading from 4.1.1 to 4.2.0.

**Comment by rarkins** [comment]
Hi, I tried reproducing this locally but the large size of the example repo makes debugging impractical. We need a *minimal* reproduction if we are to take a further look (e.g. spotbugs only)
