### ISSUE TITLE
Versions with suffix 'ea' should be treated as unstable

### ISSUE THREAD

**Issue by remal** [renovatebot/renovate#7836]
Hello Renovate authors,

Recently some `ea` versions were released for [Immutables library](https://mvnrepository.com/artifact/org.immutables/value). It's not a release suffix and it should be treated as unstable.

Corresponding issue in Immutables repository: https://github.com/immutables/immutables/issues/1251

**Comment by rarkins** [comment]
Unfortunately Maven versioning is not intuitive on this matter like SemVer is - the presence of a suffix does not imply unstable, even if the package authors intend it that way. Package authors should use one of the standard unstable suffixes such as `alpha`, `beta`, or `rc`.

I learned this on an earlier issue here: https://github.com/renovatebot/renovate/issues/5977

Please see a suggested workaround here: https://github.com/renovatebot/config-help/issues/994
