### ISSUE TITLE
add/allow label for dependencyDashboard 

### ISSUE THREAD

**Issue by haghabozorgi** [renovatebot/renovate#7848]
**What would you like Renovate to be able to do?**

Renovate currently allows adding labels to PRs. It would be nice if  labels could be added to the dependencyDashboard issue that gets create as well.

**Did you already have any implementation ideas?**

Perhaps the current labels implementation would be sufficient for a first iteration. If labels set at top-level config, dependencyDashboard logic uses those labels for its issue creation call.

**Comment by HonkingGoose** [comment]
I think this feature request might be a duplicate of #4911.

**Comment by viceice** [comment]
Yes, sounds like a duplicate.

I think there is another issue for an `addLabel` like option, which might be in progress by a contributor. 🤔

**Comment by HonkingGoose** [comment]
> I think there is another issue for an `addLabel` like option, which might be in progress by a contributor. 🤔

I haven't been able to find that issue yet...

@viceice can you close this with your "Duplicate of" thing? I don't have the rights to mark things as a duplicate.

**Comment by viceice** [comment]
Ok, not a duplicate but related to #6503 😏

**Comment by rarkins** [comment]
Duplicate of #4911
