### ISSUE TITLE
Incorrect stability check

### ISSUE THREAD

**Issue by iyhammad** [renovatebot/renovate#7855]
**What Renovate type, platform and version are you using?**
Self Hosted, Azure DevOps

**Describe the bug**
Renovate doesn't create PRs even if the update met stability days requirements.

**Relevant debug logs**
```
DEBUG: Updated 2 package files (repository=MyCompany/ProjectX, branch=renovate/microsoft-applicationinsights-packages)
DEBUG: No updated lock files in branch (repository=MyCompany/ProjectX, branch=renovate/microsoft-applicationinsights-packages)
DEBUG: 2 file(s) to commit (repository=MyCompany/ProjectX, branch=renovate/microsoft-applicationinsights-packages)
DEBUG: Committing files to branch renovate/microsoft-applicationinsights-packages (repository=MyCompany/ProjectX, branch=renovate/microsoft-applicationinsights-packages)
 INFO: Branch created (repository=MyCompany/ProjectX, branch=renovate/microsoft-applicationinsights-packages)
       "commitSha": "067fd1f"
DEBUG: Updating renovate/stability-days status check state to green (repository=MyCompany/ProjectX, branch=renovate/microsoft-applicationinsights-packages)
DEBUG: setBranchStatus(renovate/microsoft-applicationinsights-packages, renovate/stability-days, Updates have met stability days requirement, green, https://docs.renovatebot.com/) (repository=MyCompany/ProjectX, branch=renovate/microsoft-applicationinsights-packages)
DEBUG: Branch status pending (repository=MyCompany/ProjectX, branch=renovate/microsoft-applicationinsights-packages)
       "commitSha": "067fd1f"
```

**To Reproduce**

1. Set stabilityDays: X
2. Set prCreation: "not-pending"
3. Add dependency that pass stabilityDays period.
4. Run renovate

**Additional context**
I think it's somehow related to this bug #4884

**Comment by rarkins** [comment]
Please reproduce in a public azure devops repo so we can confirm and debug.

**Comment by JamieMagee** [comment]
I'm self-assigning as it's an Azure DevOps related issue, but I'll wait for a repro.

**Comment by iyhammad** [comment]
I could regenerate the issue in a public repo.
If you look [at this renovate run](https://dev.azure.com/ihatest/ProjectX/_build/results?buildId=218&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=35f53584-79fc-539f-463c-6471d0663a3a&l=559), you will find the call for `setBranchStatus(Updates have met stability days requirement)` then immediately after that `Branch status pending`.
I had to run the pipeline twice to have the pull requests created.

**Comment by viceice** [comment]
You are using `"prCreation": "not-pending"`, so it's by design to need two renovate runs.

Renovate will break early because it pushed a new commit. If a new commit is pushed and `"prCreation": "not-pending"`, renovate assumes there will be a running pipeline which needs some time to complete.

We've added this because otherwise renovate had automerged branches before, as it added the green check and the ci was not fast enough to send a pending state, so renovate had automerged to fast.

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/b12c522e0bcef6a6d6061f1feea6865905c7b0d5/lib%2Fworkers%2Fbranch%2Findex.ts#L499-508

**Comment by viceice** [comment]
ref #4511 #5594

**Comment by rarkins** [comment]
Yes, don't use not-pending if you want branches created instantly anyway

**Comment by viceice** [comment]
> Yes, don't use not-pending if you want branches created immediately anyway

branches -> pr's ?

**Comment by iyhammad** [comment]
If I remove `not-pending`, the pull request is created even if it doesn't meet the stability days requirements. How can I prevent renovate from creating these pull requests?

**Comment by viceice** [comment]
Then your only option is to use `not-pending` and wait for a second renovate run

**Comment by iyhammad** [comment]
I tried that and seems to be working. Thank you.
