### ISSUE TITLE
Can we add more documentation around registryURL?

### ISSUE THREAD

**Issue by bavedarnow** [renovatebot/renovate#7906]
Can we add more documentation around this feature? I just spent a lot of time trying to figure out why renovate wasn't picking up an upgrade, only to find out it was because we're using our GHE instance in the global configs and the repo didn't exist on it

Another thing to point out is that the registry URL for github has to be exactly `https://github.com`, otherwise it will try to use GHE API endpoints, which were failing for me. (I used `https://www.github.com`)

_Originally posted by @bavedarnow in https://github.com/renovatebot/renovate/issues/7792#issuecomment-738236813_

**Comment by rarkins** [comment]
@bavedarnow I don't understand your problem based on the current description so the best thing would be for you to create a docs PR yourself and note if there's any points you need help filling in.

**Comment by HonkingGoose** [comment]
Do we want to close the issue (as it's been quite a while without a response), or do we want to nudge the user again, and see what happens?
