### ISSUE TITLE
CODEOWNERS file not working for outside contributors

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#7927]
## Problem description:

I'm listed as a code owner for any Markdown files:
https://github.com/renovatebot/renovate/blob/f18b7f3504c3bdb799f1ff15fbe977cefb24641d/.github/CODEOWNERS#L1

But I'm not receiving any automated review requests for pull requests that touch Markdown files.

## What the GitHub docs say about code owners:

Relevant quote from [about code owners, GitHub docs](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners):
> People with admin or owner permissions can set up a CODEOWNERS file in a repository.
> 
> The people you choose as code owners must have write permissions for the repository. When the code owner is a team, that team must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

From reading the docs, it seems that you can only list a user as a code owner if that user has **write** level rights on the repository. I have triage level rights so I'm not getting pinged.

I suspect that the other outside contributor @ppmathis is also not getting automated review requests for Gitea stuff?
https://github.com/renovatebot/renovate/blob/f18b7f3504c3bdb799f1ff15fbe977cefb24641d/.github/CODEOWNERS#L6

## Recommended fix:

The easiest and safest thing to do is to remove the outside contributors from the CODEOWNERS file, and only use the CODEOWNERS for existing write level users.

It's a bit disappointing that you cannot use the CODEOWNERS file with outside contributors without granting extra rights...

**Comment by rarkins** [comment]
We could write an Action or see if one already exists to do this. Would need to check each time code is committed to a PR, Eg if people add docs last

**Comment by HonkingGoose** [comment]
> It's a bit disappointing that you cannot use the CODEOWNERS file with outside contributors without granting extra rights...

I figured out _why_ GitHub requires CODEOWNERS to have `write` level rights.

https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#submitting-your-review

Relevant quotes from the "tips" section at the bottom of the page:

> If required reviews are enabled and a collaborator with write, admin, or owner access to the repository submits a review requesting changes, the pull request cannot be merged until the same collaborator submits another review approving the changes in the pull request.

> If your repository requires approving reviews from people with write or admin permissions, then any approvals from people with these permissions are denoted with a green check mark, and approvals from people without these permissions have a gray check mark. Approvals with a gray check mark do not affect whether the pull request can be merged.

My reviews as `triage` level collaborator have a gray check mark, and do not affect whether the pull request can be merged. So even though I'm listed as a codeowner, I cannot affect any PRs mergeability.

I think the reasoning from GitHub is to only allow listed CODEOWNERS to get pinged if they have `write` rights , as it wouldn't make sense to ping somebody who doesn't actually have the "power to block a PR from being merged".

**Comment by rarkins** [comment]
The original reason I had for holding back users with write permission was because anyone with that permission - or anyone who compromised that person's account - could disclose the repo secrets (such as our npm or Docker credentials). Is that still the case with Actions? e.g. someone with write access could add or modify an action such that the base64 of credentials are written to logs and thus disclosed? I couldn't work it out from https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions

**Comment by HonkingGoose** [comment]
@rarkins Do you want a new issue from me to track the migration of secrets out of the main `renovatebot/renovate` repository?

**Comment by HonkingGoose** [comment]
I'm going to close this issue. There's nothing **we** can do about GitHub requiring code owners to have `write` access to the repository.

We still should remove all secrets from the main `renovatebot/renovate` repository, if possible. So we can hand out `write` rights to more people, so they can be codeowners. See:

- #12608
