### ISSUE TITLE
[Feature-Request] RegexManager Checksum-Download Support

### ISSUE THREAD

**Issue by Preisschild** [renovatebot/renovate#7928]
**What would you like Renovate to be able to do?**

I use a regexmanager (with github-releases datasource) to update versions of tooling inside Dockerfiles. in the end it looks like this:

```Dockerfile
# renovate: datasource=github-releases depName=GoogleContainerTools/skaffold
ARG SKAFFOLD_VERSION=v1.16.0
ARG SKAFFOLD_CHECKSUM=9041feb75a5fc15c1159f1e25d0dd781ecf0ff9fe37190174e61822a47c60b1d
```

With the RegexManager looking like this.
```json
"regexManagers": [
    {
      "fileMatch": ["(^|/|\\.)Dockerfile$", "(^|/)Dockerfile\\.[^/]*$"],
      "matchStrings": [
        "# renovate: datasource=(?<datasource>[a-z-]+?) depName=(?<depName>.+?)(?: versioning=(?<versioning>[a-z-0-9]+?))?\\s(?:ENV|ARG) .+?_VERSION=(?<currentValue>.+?)\\s"
      ],
      "versioningTemplate": "{{#if versioning}}{{versioning}}{{else}}semver{{/if}}"
    }
]
```

This works great for updating the Version, but it would also be cool if Renovate could update the Checksum (in this example `ARG SKAFFOLD_CHECKSUM`).

**Did you already have any implementation ideas?**
We could add a capture group that captures `checksumUrl` and another one that captures `currentChecksumValue`. This signals to renovate that it should update the checksum by downloading `checksumUrl` and passing the `body`.

Edit: We'd also need to allow inserting the new version into the url

**Comment by Preisschild** [comment]
@HonkingGoose I think the manager got mislabeled. I mean the regexmanager.

**Comment by HonkingGoose** [comment]
We don't have a RegEx manager label yet, so I thought this seems to apply to Dockerfiles, I'll stick a `manager:dockerfile` label on it.

I'll remove the `manager:dockerfile` label. 😄
