### ISSUE TITLE
Document which config options can appear in packageRules

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#7959]
> The docs seem to be outdated, we'll fix this soon. We have a json schema, you need a schema aware editor like vscode.
> 
> ```json
> {
>   "$schema": "https://docs.renovatebot.com/renovate-schema.json",
>   ...
> }
> ```
> 
> @rarkins @HonkingGoose  We need to extend the packageRules ~and fix the nuget samples~

_Originally posted by @viceice in https://github.com/renovatebot/renovate/issues/7912#issuecomment-743116288_

**Comment by rarkins** [comment]
For us to document which fields can be included in packageRules means we need to *know* which fields are allowed to be in packageRules. For that we'll need to work out a new tagging scheme for our configuration option definitions

**Comment by viceice** [comment]
yes, but the nuget samples should be fixed asap

**Comment by HonkingGoose** [comment]
Maybe split this issue into 2 then? One for the NuGet samples, and one for the extension of the `packageRules`?

**Comment by rarkins** [comment]
Yes, I'll fix the NuGet ones now

**Comment by rarkins** [comment]
Right now our config options can be divided into categories:
- Admin options, for bot admin only
- Options which are only for inside `packageRules`
- Options which are only for inside `hostRules`
- Everything else

But not everything else is appropriate inside packageRules, so we need a way to flag either:
- Every option which is valid inside packageRules, or
- Every option which is NOT valid inside packageRules
