### ISSUE TITLE
PR summary with adoption rate 0%, passig rate 100% and high confidence.

### ISSUE THREAD

**Issue by Masa-Shin** [renovatebot/renovate#7980]
**What Renovate type, platform and version are you using?**

hosted App, Github.

**Describe the bug**

<img width="827" alt="スクリーンショット 2020-12-08 12 44 08" src="https://user-images.githubusercontent.com/34234442/102004891-3923dc80-3d58-11eb-9f37-335eb21d1fb0.png">

Renovate bot made a PR and in the summary there is an update whose adoption rate was 0%, passig rate was 100%, and confidence was `high`. I suppose it is not a valid estimate. 

**Relevant debug logs**

It happens at 5 days ago and the log is not available now.

**To Reproduce**

Install `@storybook/vue` package of version `6.0.28` by npm/yarn and run renovate bot.

**Additional context**

I suppose when adoption rate is exactly equals to 0%, passing rate should also be equals to 0%. Or if it was nearly 0% and got rounded, its confidence might not be so high.

**Comment by rarkins** [comment]
Hi, please raise any questions about Merge Confidence in https://github.com/whitesource/merge-confidence
