### ISSUE TITLE
Update images on the GitHub Apps "storefronts" for Renovate App

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#8003]
**What Renovate type, platform and version are you using?**

GitHub hosted app.

**Describe the bug**

The installation page for the GitHub hosted app shows outdated images, with the old Renovate brand icon.
Also one image clearly shows outdated GitHub PR styling.

I think it's a good idea to update all the images here to be current again.
This helps with making a good first impression on potential new users.

**Relevant debug logs**

**To Reproduce**

1. Go to https://github.com/apps/renovate
1. Images use old Renovate logo
1. GitHub interface shown in images is outdated (Example: the green "open" status badge in the PR view uses rounded corners nowadays instead of square corners)
1. Go to https://github.com/marketplace/renovate, this also uses outdated imagery

**Additional context**

We fixed outdated images elsewhere with #7527 and #7517, so it makes sense to fix the GitHub App storefront pages as well.

**Comment by rarkins** [comment]
done
