### ISSUE TITLE
ci: test runner problems?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#8006]
**What Renovate type, platform and version are you using?**

Problem seems to be with Renovate GitHub actions CI tests, more specifically the unit tests.

**Describe the bug**

I've noticed some really slow unit test executing on the macOS runners when using Node 12.
I don't know what causes this, and I don't know how to find more examples to verify the problem.

| Test runner | Unit test execution time | Remarks |
| --- | ---: | --- |
| ubuntu-latest, 12, 3.8, 8 | 4m 38s | | 
| ubuntu-latest, ^14.15.0, 3.8, 8 | 3m 29s | | 
| macos-latest, 12, 3.8, 8 | 11m 48s | The job running on runner GitHub Actions 4 has exceed maximum execution time of 30 minutes. | 
| macos-latest, ^14.15.0, 3.8, 8 | 5m 43s | | 
| windows-latest, 12, 3.8, 8 | 5m 53s | |
| windows-latest, ^14.15.0, 3.8, 8 | 4m 42s | | 

Source of data from table: https://github.com/renovatebot/renovate/actions/runs/420901386

Log for `macos-latest, 12, 3.8, 8` run: https://github.com/renovatebot/renovate/runs/1550640846?check_suite_focus=true
The Bitbucket tests are taking an extremely long time: 105 seconds and 129 seconds.

**Relevant debug logs**

**To Reproduce**

I'm not sure how reproducible this is.
I think the only way to verify the problem is to trawl through the GitHub actions logs?

**Additional context**

I don't know why the tests sometimes error out, I've noticed this in a lot of my PR's, that tests seem to randomly error out. I'm not sure what runners are at fault precisely.

I'm just opening this issue for discussion and review by the Renovate team, and to see what the team's experience is with the tests.

**Comment by viceice** [comment]
https://www.githubstatus.com/incidents/3jr0nb7zjpbm

**Comment by HonkingGoose** [comment]
Thanks @viceice for the link. I hadn't thought of GitHub-side maintenance yet... 😄 

Are we overall happy with the test performance? It's still really weird that those Bitbucket unit tests took 105 seconds and 129 seconds. Are we sure that is caused by the macOS virtual environment maintenance? I've checked some other GitHub Action unit tests logs, and I see that some tests are marked with a red background, probably due to excessive time usage.

**Comment by viceice** [comment]
Yes these slow tests are annoying. On my local machine i only see the git tests that are very slow. Maybe they Overprovision the MacOS GitHub Runner to much?

**Comment by HonkingGoose** [comment]
Are we still unhappy with overall test runner performance?

This issue was originally raised because the macOS runners were timing out.
This is fixed because the GitHub-side maintenance is done.
In addition we only test on Node 14 for macOS now.

I don't know if we still want to take a look at/improve basic test performance across all platforms?
If not, I think this issue has run its course and can be closed.
