### ISSUE TITLE
optimizeForDisabled should support other locations than renovate.json 

### ISSUE THREAD

**Issue by cykl** [renovatebot/renovate#8032]
I had like to use `optimizeForDisabled` with a specific configuration file location  rather than `renovate.json`. 

We have configured renovate with `autodiscover: true` and `requireConfig: true` and had like to enable `optimizeForDisabled`. However, current implementation expects the configuration file location to be `renovate.json` and does not support alternative locations. Since we are optimizing for disabled, it makes sense to not probe the 9 supported locations. However, I would be great if we could configure the location to probe or a filter to trim down the location to probe.

**Did you already have any implementation ideas?**

Current implementation uses the first configFileNames:

```js
const defaultConfigFile = configFileNames[0];

async function validateOptimizeForDisabled(
  config: RenovateConfig
): Promise<void> {
  if (config.optimizeForDisabled) {
    const renovateConfig = await platform.getJsonFile(defaultConfigFile);
    if (renovateConfig?.enabled === false) {
      throw new Error(REPOSITORY_DISABLED);
    }
  }
}
````

A new configuration option could be added to provide the location or to filter configFileNames and loop over all remaining locations.

**Comment by rarkins** [comment]
There is already an onboardingConfigFileName option which allows the default config file name to be changed, so it would be a good match for this.

**Comment by cykl** [comment]
I forgot to rebase my clone and was reading few weeks old code, sorry about that :facepalm: 

onboardingConfigFileName seems to do exactly what I need. However, a quick test surfaced an issue. 

I set onboardingConfigFileName to `".gitlab/renovate.json"` and `optimizeForDisabled` to `true`

```
DEBUG: backend/pilot-java-api http URL = https://gitlab.xxx/backend/pilot-java-api.git (repository=backend/pilot-java-api)
DEBUG: GitLab API 404 (repository=backend/pilot-java-api)
       "url": "https://gitlab.xxx/api/v4/projects/backend%2Fpilot-java-api/repository/files/.gitlab/renovate.json?ref=master"
```

According to [GitLab documentation](https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository) `file_path` must be URL encoded.

**Comment by rarkins** [comment]
Sorry, I meant the functionality needs updating - but it shouldn't need a new option

**Comment by cykl** [comment]
Code seems already there:

```js
const defaultConfigFile = (config: RenovateConfig): string =>
  configFileNames.includes(config.onboardingConfigFileName)
    ? config.onboardingConfigFileName
    : configFileNames[0];

async function validateOptimizeForDisabled(
  config: RenovateConfig
): Promise<void> {
  if (config.optimizeForDisabled) {
    const renovateConfig = await platform.getJsonFile(
      defaultConfigFile(config)
    );
    if (renovateConfig?.enabled === false) {
      throw new Error(REPOSITORY_DISABLED);
    }
  }
}
````

It just doesn't work for configuration within a sub directory. I'm not a typescript developer but shouldn't something like that fix the issue:

```patch
diff --git a/lib/platform/gitlab/index.spec.ts b/lib/platform/gitlab/index.spec.ts
index fadc4cd03..9357d5c8b 100644
--- a/lib/platform/gitlab/index.spec.ts
+++ b/lib/platform/gitlab/index.spec.ts
@@ -1407,12 +1407,12 @@ These updates have all been created already. Click a checkbox below to force a r
       const scope = await initRepo();
       scope
         .get(
-          '/api/v4/projects/some%2Frepo/repository/files/file.json?ref=master'
+          '/api/v4/projects/some%2Frepo/repository/files/dir%2Ffile.json?ref=master'
         )
         .reply(200, {
           content: Buffer.from(JSON.stringify(data)).toString('base64'),
         });
-      const res = await gitlab.getJsonFile('file.json');
+      const res = await gitlab.getJsonFile('dir/file.json');
       expect(res).toEqual(data);
       expect(httpMock.getTrace()).toMatchSnapshot();
     });
diff --git a/lib/platform/gitlab/index.ts b/lib/platform/gitlab/index.ts
index 8b8439910..cb7851b5d 100644
--- a/lib/platform/gitlab/index.ts
+++ b/lib/platform/gitlab/index.ts
@@ -137,11 +137,12 @@ function urlEscape(str: string): string {
 
 export async function getJsonFile(fileName: string): Promise<any | null> {
   try {
+    const escapedFileName = urlEscape(fileName);
     return JSON.parse(
       Buffer.from(
         (
           await gitlabApi.getJson<{ content: string }>(
-            `projects/${config.repository}/repository/files/${fileName}?ref=${config.defaultBranch}`
+            `projects/${config.repository}/repository/files/${escapedFileName}?ref=${config.defaultBranch}`
           )
         ).body.content,
         'base64'
```

**Comment by HonkingGoose** [comment]
@rarkins does #8034 being merged close this issue or is more work needed?
