### ISSUE TITLE
Invalid configuration option: masterIssue

### ISSUE THREAD

**Issue by xuhdev** [renovatebot/renovate#8135]
**What Renovate type, platform and version are you using?**

Local, npm-config-validator, version 24.10.2

**Describe the bug**

I ran `npm-config-validator` in the [following content](https://github.com/xuhdev/flake8-executable/blob/362bca057b421dc126caecce9a83147fdc4d5718/.github/renovate.json5):

```json
{
    "extends": [
        "config:base"
    ],

    "pip_requirements": {
        "fileMatch": ["\.requirements.*\.txt$"]
    },

    "labels": [
        "renovate"
    ],

    "masterIssue": true,

    "schedule": [
        "before 1am on Saturday"
    ],

    "packageRules": [
        {
            "packagePatterns": [
                "*"
            ],
            "updateTypes": [
                "minor",
                "patch"
            ],
            "groupName": "all non-major dependencies",
            "groupSlug": "all-minor-patch"
        }
    ]
}
```

It outputs:

```
.github/renovate.json5 contains errors:

[
  {
    "depName": "Configuration Error",
    "message": "Invalid configuration option: masterIssue"
  }
]
Validating config.js
```

But the bot works properly.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
masterIssue was renamed to dependencyDashboard

**Comment by HonkingGoose** [comment]
Closing this issue, I made a PR at the bug reporters repository that resolves the problem. See https://github.com/xuhdev/flake8-executable/pull/30 for the PR I made.

**Comment by xuhdev** [comment]
Thanks! Could you add a note to your blog post https://www.whitesourcesoftware.com/free-developer-tools/blog/introducing-renovates-master-issue/ ? This is always the page that usually hits top for me, so perhaps clarifying there can help reduce confusion :)

**Comment by HonkingGoose** [comment]
@xuhdev and @rarkins, I made a new issue (#8140) to track the update of the Whitesource blogpost.
