### ISSUE TITLE
Pipenv lock command fails for older version of Python when binary source is set to global

### ISSUE THREAD

**Issue by hisener** [renovatebot/renovate#8163]
**What Renovate type, platform and version are you using?**

Self-hosted (`renovate/renovate:24.10.4` docker image) on GitHub.com

**Describe the bug**

As I flagged in https://github.com/renovatebot/renovate/pull/8136, Renovate cannot update lock Pipfile files for older versions of Python when the global binary source is used. It's because the image has Python 3.9 installed.

The error message:
```
File name: python-test/Pipfile.lock

Command failed: pipenv lock
Warning: Python 3.8 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
```

**Relevant debug logs**

```
DEBUG: pipenv lock command (repository=PicnicSupermarket/picnic-scratch, branch=renovate/tenacity-6.x)
       "cmd": "pipenv lock"
DEBUG: Executing command (repository=PicnicSupermarket/picnic-scratch, branch=renovate/tenacity-6.x)
       "command": "pipenv lock"
DEBUG: Failed to update Pipfile.lock (repository=PicnicSupermarket/picnic-scratch, branch=renovate/tenacity-6.x)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "pipenv lock",
         "stdout": "",
         "stderr": "Warning: Python 3.8 was not found on your system...\nNeither 'pyenv' nor 'asdf' could be found to install Python.\nYou can specify specific versions of Python with:\n$ pipenv --python path/to/python\n",
         "message": "Command failed: pipenv lock\nWarning: Python 3.8 was not found on your system...\nNeither 'pyenv' nor 'asdf' could be found to install Python.\nYou can specify specific versions of Python with:\n$ pipenv --python path/to/python\n",
         "stack": "Error: Command failed: pipenv lock\nWarning: Python 3.8 was not found on your system...\nNeither 'pyenv' nor 'asdf' could be found to install Python.\nYou can specify specific versions of Python with:\n$ pipenv --python path/to/python\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:467:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
       }
DEBUG: Updated 1 package files (repository=PicnicSupermarket/picnic-scratch, branch=renovate/tenacity-6.x)
```

**Have you created a minimal reproduction repository?**

You can reproduce using https://github.com/hisener/renovate-tests/. https://github.com/hisener/renovate-tests/pull/28 is what I get when I use the following config:
```
module.exports = {
    token: '...',
    repositories: ['hisener/renovate-tests']
};
```

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Maybe we can install `pyenv` in the Renovate docker image to solve this issue.

**Comment by viceice** [comment]
I don't see any chance to fix it, as wa can only have a single python version in the full image.

**Comment by rarkins** [comment]
This is by design. You need to either build your own image using your preferred version of python or else use the Docker binary source.

**Comment by hisener** [comment]
I can understand the limitation but this is counterintuitive. For example, [Renovate helm chart](https://github.com/renovatebot/helm-charts/blob/master/charts/renovate/values.yaml#L17) also uses the same image. So if you are using that, it means Python is not supported.

**Comment by viceice** [comment]
Python is supported, you need to allow newer versions if you are using the full image / helm chart

**Comment by rarkins** [comment]
@hisener what is the alternative though?

1. Renovate full image uses latest stable Python image (current behavior)
2. Renovate full image uses whatever `<insert current username here>` is using (does not scale)
3. Renovate full image is preinstalled with every stable version of Python (bloated)
4. Dynamically install non-root python at runtime?

I guess you hope for (4) somehow?

This need is why the binarySource=docker was invented. If that approach is not amenable then we'd also welcome requirements for doing it the k8s way too (i.e. assuming that the main renovate container has privileges to ask k8s to create its sibling containers)

**Comment by hisener** [comment]
> you need to allow newer versions if you are using the full image 

What do you mean by that?

@rarkins As I said before, I totally understand the limitation, but one could expect to work out of the box just like in other package managers. I am not an expert in Python area, so I don't even know why it requires a specific Python version for dependency resolution. I am just pointing the issue here.

Anyway, I am ok to switch to the sidecar solution if it's not possible to achieve in full image. :)

**Comment by rarkins** [comment]
It's pipenv rejecting the newer python version, not Renovate

**Comment by viceice** [comment]
@hisener @rarkins let's continue at a new discussion. So we can workout a nice kubernetes solution with current renovate possibilities. When done we can add it to our docs, so new users have a starter.

**Comment by hisener** [comment]
I get that :) But when I run the same command locally it can update the lock file with a warning. 🤷‍♂️ 

```
$ pipenv lock             
Warning: Your Pipfile requires python_version 3.8, but you are using 3.9.0 (/Users/halil/.local/share/v/p/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (3ea598)!

$ git status
...
    modified:   Pipfile.lock
```

**Comment by rarkins** [comment]
Is pipenv exiting with a non zero exit code because of that warning?

**Comment by hisener** [comment]
`echo $?` prints `0`.
