### ISSUE TITLE
Support dotnet tools manager

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#8179]
**What would you like Renovate to be able to do?**

Support the dotnet tools manager: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool

**Did you already have any implementation ideas?**

New manager for this JSON file, but otherwise existing datasource and versioning is hopefully enough.

**Comment by viceice** [comment]
I think this is already supported by Bürger manager. 🤔

**Comment by fgreinacher** [comment]
I'd also say this is covered by https://github.com/renovatebot/renovate/pull/6335

**Comment by viceice** [comment]
@rarkins Should we move this to a separate manager?

**Comment by rarkins** [comment]
I think it's ok to leave as-is if it's already done
