### ISSUE TITLE
Support Bitbucket Cloud platform for local presets

### ISSUE THREAD

**Issue by ablekhman** [renovatebot/renovate#8217]
**What would you like Renovate to be able to do?**

We host many of our repositories on Bitbucket Cloud. While this platform is supported by Renovate for regular scans, the local presets cannot be stored on Bitbucket Cloud.

**Did you already have any implementation ideas?**

I don't have specific implementation ideas, but I would like to be able to store configuration presets independently of the current platform. Presets syntax supports GitHub, GitLab, Gitea. It seems that adding another location is not such a big change.

**Comment by viceice** [comment]
ref: #7448

**Comment by setchy** [comment]
@rarkins - looks like this is now supported due to closing #9171 .  Is that correct?
