### ISSUE TITLE
Avoid maven pom.xml renovate upgrade when version is managed by BOM 

### ISSUE THREAD

**Issue by AndreasPresthammer** [renovatebot/renovate#8248]
This applies to maven upgrades.

Assuming the pom.xml contain a dependency that has it's version controlled by a BILL-OF-MATERIALS (BOM) import pom (spring-boot-dependencies in my specific case), we DON'T specify the version on the dependency. We would, correctly, only want to specify the groupId and the artifactId, since the version is specified in the import BOM file.

Renovate still triggers a pull request where it tries to insert the `<version>...</version>` tag with the latest version of the dependency. This is NOT what I want, I want to fully rely on the version specified in the BOM (even if it's outdated).

I know I can disable the dependency tracking explicitly through the renovate.json ignore system, but I would think this is something Renovate itself should be able to support. Meaning it should NOT upgrade dependencies which don't have the `<version>` tag specified AND have a version specified through the `<dependencyManagement>` system either directly in the pom.xml itself OR through a pom import of a BOM file.

**Comment by rarkins** [comment]
Please edit this issue description to use the [Bug report template](https://github.com/renovatebot/renovate/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), and a minimal reproduction repo will be needed.

**Comment by AndreasPresthammer** [comment]
I'm unable to reproduce this. Not sure why. Closing this.
