### ISSUE TITLE
For pip dependencies, Renovate bot can't detect version pinning when there's whitespace around `==`

### ISSUE THREAD

**Issue by xuhdev** [renovatebot/renovate#8257]
**What Renovate type, platform and version are you using?**

GitHub.

**Describe the bug**

For pip dependencies, Renovate bot can't detect version pinning when there's whitespace around `==`. A real world example is at https://github.com/CODAIT/pydax/pull/137: Renovate is trying to "pin" package versions that have already been pinned.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by HonkingGoose** [comment]
Closed by the merge of PR #9910.
