### ISSUE TITLE
Customize npm version based on lock file version

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#8262]
**What would you like Renovate to be able to do?**

When binarySource=docker, pick either npm 6.x or 7.x intelligently.

**Did you already have any implementation ideas?**

if there is no npm constraint specified, or the constraint satisfies both <7 and >=7, then check if there's a lock file and lockFileVersion to determine which npm version to install. i.e. install <7 for lockFileVersion=1 and >7 for lockFileVersion=2.

**Comment by HonkingGoose** [comment]
Bumping this up to priority-2-important, because it's related to npm 7 support, which was bumped to priority-2-important as well.
Feel free to drop this down if you disagree. 😄 😉

**Comment by viceice** [comment]
I think this is already implemented. 🤔

**Comment by rarkins** [comment]
Yep, I added it the day npm 7 went GA

**Comment by HonkingGoose** [comment]
https://github.com/renovatebot/renovate/pull/8506 maybe?

**Comment by viceice** [comment]
#8506
