### ISSUE TITLE
Support Helm charts private repositories

### ISSUE THREAD

**Issue by Djiit** [renovatebot/renovate#8275]
**What would you like Renovate to be able to do?**

I'd like to renovate repos where I'm using charts from private charts repository

**Did you already have any implementation ideas?**

Maybe have a look at how FluxCD and their Helm Operator does this : https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/chart-sources/#authentication-and-certificates

Thanks!

**Comment by Djiit** [comment]
Actually, it already support this. This comment was the key https://github.com/renovatebot/config-help/issues/384#issuecomment-543004405. Should we add something clearer in the documentation ?

**Comment by viceice** [comment]
Feel free to send a pr to update the docs 🙃

**Comment by Djiit** [comment]
Sure! Any pointer? Is the doc website in this repo ? Thanks

**Comment by rarkins** [comment]
There's no perfect location for it, but maybe adding it to the bottom of https://github.com/renovatebot/renovate/blob/master/docs/usage/docker.md will let some people find it in future
