### ISSUE TITLE
Unexpect Error because of undefined reference

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#8296]
**What Renovate type, platform and version are you using?**
github app, but unrelated

**Describe the bug**

Renovate thows an error if a datasource doen't exist. But it should be catched gracefully with a config error and not a unknown error.

Exception : `Cannot use 'in' operator to search for 'getDigest' in undefined`
crashes here:
https://github.com/renovatebot/renovate/blob/5896d9cb37447151f2e13d0b8570bc1618dfbca4/lib/datasource/index.ts#L298
https://github.com/renovatebot/renovate/blob/6f7b4afd1e712b0b43f38d1f59d0d88980842ce8/lib/workers/repository/process/lookup/index.ts#L382

**Relevant debug logs**

![image](https://user-images.githubusercontent.com/1798109/104583972-1d1aa000-5662-11eb-8d0a-903e4152d9f3.png)

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Can be siply reproduced with a regexmanager assigning a not exsiting datasource. I think the solution is to check for undefined and log an error and return  `null`.
https://github.com/renovatebot/renovate/blob/5896d9cb37447151f2e13d0b8570bc1618dfbca4/lib/datasource/index.ts#L298

**Comment by rarkins** [comment]
Do you think best would be to abort the repo and raise a config error?

**Comment by viceice** [comment]
I think best is to log an error and  return false for `supportsDigest` so renovate will skip that dependency, but because of the error log it will be visible to the user in the logs and on dashboard
