### ISSUE TITLE
Run on repositoriy-groups

### ISSUE THREAD

**Issue by strowi** [renovatebot/renovate#8300]
**What would you like Renovate to be able to do?**

In Gitlab for example it's possible to create groups and subgroups of repositories. It would be quite usefull if it were possible to specify those for the renovatebot to work on instead of all repositories line by line.

regards,
strowi

**Comment by viceice** [comment]
Already doable, checkout [autodiscoverFilter](https://docs.renovatebot.com/self-hosted-configuration/#autodiscoverfilter).

You need to use multiple renovate runner for this

**Comment by viceice** [comment]
Please extend your discription, your information what to do is very limited.

**Comment by viceice** [comment]
Feel free to reopen, when you have filled the issue template completly with a full sample scenario what renovate should do for you.
