### ISSUE TITLE
New Dependency Dashboard issue created on every run

### ISSUE THREAD

**Issue by statik** [renovatebot/renovate#8304]
**What Renovate type, platform and version are you using?**

Hi! I'm using self-hosted renovate in a GitHub action, and have set up a minimal example to reproduce the issue. I am using the renovate docker image version 24.16.4: https://github.com/kindlyops/examples/blob/b203df028ed1db1c33d2befae056ff37055a43d8/.github/workflows/update.yml#L30

**Describe the bug**

I have enabled dependencyDashboard in my config:
https://github.com/kindlyops/examples/blob/b203df028ed1db1c33d2befae056ff37055a43d8/renovate.js#L15
```
  dependencyDashboard: true,
```
One each renovate run, a new dependency dashboard issue is created, because the existing dependency dashboard issue was not discovered. At first I suspected a permissions issue, but I have granted full read-write access to issues, and the new issues are being created.

**Relevant debug logs**

I can see in the debug log that no issues were found when looking for the dependency dashboard. I did not see any other info. This is a deep link into the public log: https://github.com/kindlyops/examples/runs/1703018692?check_suite_focus=true#step:5:2524
```
DEBUG: findIssue(Dependency Dashboard) (repository=kindlyops/examples)
DEBUG: Retrieving issueList (repository=kindlyops/examples)
DEBUG: Retrieved 0 issues (repository=kindlyops/examples)
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Thanks for your help! I am not sure how to get additional diagnostic information about why this is failing, and am happy to help if you have suggestions for debugging.

**Comment by viceice** [comment]
This is not a bug. You are using app auth, so you need to remove / fix the username. 

Because you are setting `username=renovatebot` renovate searches only for pr and issues created by that username. But your app user is something else.

Next time you need config help please use our discussions. Thanks.

**Comment by viceice** [comment]
BTW: app mode is officially only supported for the hosted renovate app.

**Comment by statik** [comment]
Thank you @viceice, I really appreciate the help! This makes sense now.
