### ISSUE TITLE
Errors resolving digest for go modules with +nocompatible 

### ISSUE THREAD

**Issue by statik** [renovatebot/renovate#8305]
**What Renovate type, platform and version are you using?**

**Describe the bug**

I noticed in the debug logs that for any go dependencies that have the `+incompatible` suffix, the digest resolution lookup fails with a 404 on github, because the real release tag does not have the `+incompatible` suffix. I think this suffix should be trimmed before doing the tag lookup.

Note that despite this error in the log, renovate is successfully processing updates to this dependency, as seen in https://github.com/kindlyops/examples/pull/26.

Probably it would make sense to include a dep that has `+incompatible` in the test fixture for the gomod manager. I'd be happy to contribute a PR if there is agreement about how to solve this.

**Relevant debug logs**

Here is an example from a minimal repro repository that I set up. This is a deep link to the log, excerpt pasted below for convenience.
https://github.com/kindlyops/examples/runs/1703033891?check_suite_focus=true
```
DEBUG: GitHub 404 (repository=kindlyops/examples)
       "url": "api.github.com/repos/dgrijalva/jwt-go/git/refs/tags/v3.2.0+incompatible"
DEBUG: Error getting tag commit from GitHub repo (repository=kindlyops/examples)
       "githubRepo": "dgrijalva/jwt-go",
       "err": {
         "name": "HTTPError",
         "timings": {
           "start": 1610640163980,
           "socket": 1610640163980,
           "lookup": 1610640163985,
           "connect": 1610640164031,
           "secureConnect": 1610640164040,
           "upload": 1610640164040,
           "response": 1610640164103,
           "end": 1610640164104,
           "phases": {
             "wait": 0,
             "dns": 5,
             "tcp": 46,
             "tls": 9,
             "request": 0,
             "firstByte": 63,
             "download": 1,
             "total": 124
           }
         },
         "message": "Response code 404 (Not Found)",
         "stack": "HTTPError: Response code 404 (Not Found)\n    at Request.<anonymous> (/usr/src/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
         "options": {
           "headers": {
             "user-agent": "renovatebot/renovate",
             "accept-encoding": "gzip, deflate",
             "accept": "application/vnd.github.machine-man-preview+json",
             "authorization": "***********"
           },
           "url": "api.github.com/repos/dgrijalva/jwt-go/git/refs/tags/v3.2.0+incompatible",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         },
         "response": {
           "statusCode": 404,
           "statusMessage": "Not Found",
           "body": {
             "message": "Not Found",
             "documentation_url": "docs.github.com/enterprise/2.18/user/rest/reference/git#get-a-reference"
           },
           "headers": {
             "server": "GitHub.com",
             "date": "Thu, 14 Jan 2021 16:02:44 GMT",
             "content-type": "application/json; charset=utf-8",
             "transfer-encoding": "chunked",
             "status": "404 Not Found",
             "x-poll-interval": "300",
             "x-github-media-type": "github.v3; param=machine-man-preview; format=json",
             "x-ratelimit-limit": "12500",
             "x-ratelimit-remaining": "12098",
             "x-ratelimit-reset": "1610643404",
             "x-ratelimit-used": "402",
             "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
             "access-control-allow-origin": "*",
             "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
             "x-frame-options": "deny",
             "x-content-type-options": "nosniff",
             "x-xss-protection": "1; mode=block",
             "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
             "content-security-policy": "default-src 'none'",
             "vary": "Accept-Encoding, Accept, X-Requested-With",
             "content-encoding": "gzip",
             "x-github-request-id": "0401:258A:A3EC1:123FA9:60006B24",
             "connection": "close"
           },
           "httpVersion": "1.1"
         }
       }
DEBUG: Could not getDigest (repository=kindlyops/examples)
       "newValue": "v3.2.0+incompatible"
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
I'm not a Go user so not 100% sure on the best approach. Definitely we shouldn't be querying GitHub tags with +incompatible though.

Based on our existing tests it seems we extract them with the suffix, e.g. `"currentValue": "v3.5.0+incompatible",`. I wonder if we'd be better off extracting like `"currentValue": "v3.5.0",` instead, although I don't know how much *other* code would need to change.

Whatever change we do should be specific to the `lib/manager/gomod/*` code though not `lib/datasource/*`.
