### ISSUE TITLE
Major version bumps not getting opened for Dockerfiles

### ISSUE THREAD

**Issue by dominykas** [renovatebot/renovate#8306]
**What Renovate type, platform and version are you using?**

Latest, self-hosted

**Describe the bug**

Not getting any PRs for Dockerfile major versions (I _think_ this used to work fairly recently, and it may also be working in some repositories and not some others).

**Relevant debug logs**

I ran renovate with `trace` debugging and spotted the following:

```
TRACE: mergeChildConfig (repository=wave2/docker-rethinkdb-backup)
       "parent": {


         /* ... snip ... */


         "major": {"enabled": true}, // we have it enabled, but it gets overwritten by the default version


         /* ... snip ... **/


       },
       "child": {
         "additionalBranchPrefix": "docker-",
         "commitMessageTopic": "{{{depName}}} Docker tag",
         "major": {"enabled": false},
         "commitMessageExtra": "to v{{#if isMajor}}{{{newMajor}}}{{else}}{{{newVersion}}}{{/if}}",
         "digest": {
           "branchTopic": "{{{depNameSanitized}}}-{{{currentValue}}}",
           "commitMessageExtra": "to {{newDigestShort}}",
           "commitMessageTopic": "{{{depName}}}{{#if currentValue}}:{{{currentValue}}}{{/if}} Docker digest",
           "group": {"commitMessageTopic": "{{{groupName}}}", "commitMessageExtra": ""}
         },
         "pin": {
           "commitMessageExtra": "",
           "groupName": "Docker digests",
           "group": {
             "commitMessageTopic": "{{{groupName}}}",
             "branchTopic": "digests-pin"
           }
         },
         "group": {"commitMessageTopic": "{{{groupName}}} Docker tags"}
       }
```

It seems that our config is getting overwritten by the manager's default config - I'm not entirely sure how that happens, as there is a _loooot_ of `mergeChildConfig` calls in the logs and in the codebase, but happy to look into any further clues or debug this further.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I'll try to add a public repository at some point later, if there aren't enough clues in here just yet.

**Comment by viceice** [comment]
Docker major updates are disabled by default. Use `docker:enableMajor` preset to enable.

**Comment by viceice** [comment]
https://docs.renovatebot.com/modules/datasource/

**Comment by dominykas** [comment]
Sorry, not following. We _do_ have `{ docker: { major: { enabled: true } } } ` in our config. Is that not what the preset does?

**Comment by dominykas** [comment]
Hmmm, apparently it does more. Thanks, I'll double check.
