### ISSUE TITLE
Gradle dependency Version using variable and set()

### ISSUE THREAD

**Issue by vgropp** [renovatebot/renovate#8307]
**What Renovate type, platform and version are you using?**

we are using https://gitlab.com/renovate-bot/renovate-runner/-/blob/master/templates/renovate.gitlab-ci.yml as an include in gitlab-ci

**Describe the bug**

When generating a sample project at start.pring.io for gradle im getting this (I already changed BOM as found in #4614 to platform()):

```
plugins {
	id 'org.springframework.boot' version '2.4.1'
	id 'io.spring.dependency-management' version '1.0.10.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
}

ext {
	set('springCloudVersion', "Hoxton.SR8")
}

dependencies {
	implementation platform("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
	implementation 'org.springframework.cloud:spring-cloud-starter-sleuth'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
	useJUnitPlatform()
}

```
Renovate fails to upgrade `  set('springCloudVersion', "Hoxton.SR8")`, using `springCloudVersion = "Hoxton.SR8"` it does work.
regex to match this : `set\(\s*['"](.+)['"]\s*,\s*['"](.+)['"]\s*\)` and replacement: `$1 = "$2"`

Is there any chance to get this gradle syntax supported?

**Relevant debug logs**

```
DEBUG: gradle.updateDependency(): packageFile:settings.gradle depName:org.springframework.cloud:spring-cloud-dependencies, version:Hoxton.SR8 ==> 2020.0.0 (repository=23671976, branch=renovate/major-spring-cloud)
DEBUG: gradle.updateDependency(): packageFile:build.gradle depName:org.springframework.cloud:spring-cloud-dependencies, version:Hoxton.SR8 ==> 2020.0.0 (repository=23671976, branch=renovate/major-spring-cloud)
DEBUG: No package files need updating (repository=23671976, branch=renovate/major-spring-cloud)
DEBUG: No updated lock files in branch (repository=23671976, branch=renovate/major-spring-cloud)
DEBUG: No files to commit (repository=23671976, branch=renovate/major-spring-cloud)
```

**Have you created a minimal reproduction repository?**

https://gitlab.com/vgropp/renovate-spring-gradle-sample

**Comment by vgropp** [comment]
We use this set() notation to ovveride Spring IO dependencies, using springCloud.version = "" is not possible in build.gradle: https://docs.spring.io/platform/docs/current/reference/html/getting-started-overriding-versions.html

**Comment by rarkins** [comment]
@zharinov can you scope or fix this for both gradle and gradle-lite?

**Comment by zharinov** [comment]
Sure, let's see...

**Comment by zharinov** [comment]
Well, I wonder why `gradle` execution fails to extract report and extract any dep from the sample fork.
But merging #8315 is merged and enabling `"gradle-lite": { "enabled": true }` in config should be enough to resolve the issue.

**Comment by vgropp** [comment]
Thanks alot for the fast fix for `gradle-lite`, i'll try to test it soon. But using gradle-lite will probably be blocked for us cause of #8188, is adding this to `gradle` still in skope or should it already work and we are missing some other config?

**Comment by zharinov** [comment]
Okay, also I'll unblock #8188 for you soon ;)

**Comment by zharinov** [comment]
@vgropp can you please check if all your use-cases is covered by `gradle-lite` or not?

**Comment by vgropp** [comment]
Hi, thanks again for the fast help. Our current use-cases seemes to be covered after enabling gradle-lite
