### ISSUE TITLE
Support for remote package file locations

### ISSUE THREAD

**Issue by tomakita** [renovatebot/renovate#8317]
**What would you like Renovate to be able to do?**

First off, thanks for maintaining Renovate!  It's a great tool.

I have a number of Java repositories in GitLab.  Each repo has a corresponding pom.xml, but the pom.xml isn't stored in the repo itself.  Instead, it's stored in Nexus.  Is there a way to supply a "custom package resolver" that will allow me to specify that, for each repo, Renovate should read the pom.xml from Nexus?  If not, would I need to write a custom manager for this?  Or is there a better way of solving this problem?

**Did you already have any implementation ideas?**

Not really, but suggestions would be very much appreciated!

**Comment by viceice** [comment]
Can you please clarify what file you want to be updated? Renovate should be able to fetch updates from nexus via ma en datasource.

**Comment by tomakita** [comment]
Oh, good question -- I suppose I left that part out.  Each GitLab repo has a custom lockdown file that we use to specify dependency versions to be used at build and run time.  Renovate would modify that file, and submit the changes in a PR to each GitLab repo.  I have a feeling that would be another thing I'd need to implement myself.

**Comment by viceice** [comment]
If that lockdown file is a text file, you can try our regex manager.

I think you need to extend your issue description with a full sample scenario about what you expect to happen.

- which files should be updated?
- how do they look like?
- where to find new versions (seems to be nexus maven repo)?

**Comment by tomakita** [comment]
Thanks, I'll look into the regex manager.  Here's a sample scenario for updating the dependencies of a project called `my-library`:

Contents of git repo hosted @ `x.gitlab.com/my-library`:

- /src
- .lockdown

The lockdown file is just a text file in which each dependency of `my-library` is listed on its own line, in a `dependencyName=version` format.  Contents of `x.gitlab.com/my-library/.lockdown`:

com.google.guava:guava=30.1-jre
org.apache.commons:commons-lang3=3.11

`my-library` has a pom.xml file which also lists the above dependencies.  That pom.xml file is located in a Nexus repo @ `x.nexus.com/pom/my-library`.

The above dependencies (guava, apache commons) are also hosted in a Nexus repo @ `x.nexus.com/repo`.

When Renovate runs for `my-library`, the goal is that it will read `my-library`'s pom.xml from `x.nexus.com/pom/my-library`, find updated dependencies in `x.nexus.com/repo`, update the lockdown file in `x.gitlab.com/my-library`, and submit a PR to `x.gitlab.com/my-library` with those changes.

**Comment by viceice** [comment]
Why renovate should read the pin file in nexus when it can read them from your git repo lockdown file?

**Comment by tomakita** [comment]
I didn't know that Renovate could do that.

**Comment by viceice** [comment]
Sure, checkout the regex manager. 😉

**Comment by tomakita** [comment]
Checking it out now, thanks!

**Comment by viceice** [comment]
Open a new discussion if you need help for configuration. 🙃

**Comment by tomakita** [comment]
Sounds good, will do!
