### ISSUE TITLE
Update or remove TODO comments

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#8358]
TODO comments in code generally get forgotten, although they can be helpful for someone browsing the code to see in-context if there's still work to be done.

Resolution: each TODO comment code should have an associated issue which is referenced in the comment too. If the TODO is not worth having an issue for, then it should be removed.

**Comment by HonkingGoose** [comment]
This seems more of a `type:refactor` issue than a `type:docs` issue, so I've changed the label.

**Comment by rarkins** [comment]
@zharinov did you finish this?

**Comment by zharinov** [comment]
As I can remember, remaining TODOs are pretty hard, so I've done with most of them
