### ISSUE TITLE
Repository has unknown error: content.matchAll is not a function

### ISSUE THREAD

**Issue by theexiile1305** [renovatebot/renovate#8383]
**What Renovate type, platform and version are you using?**
- self-hosted
- GitLab 13.3.9
- `"renovateVersion": "24.24.0"` (npm)

For a specific repo renovate sporadically logs this error:

**Describe the bug**
For a specific repo renovate sporadically logs this error:

`ERROR: Repository has unknown error`

Message:
`"content.matchAll is not a function"`

Strangely, this doesn't happen 100% of the time and it is possible to reproduce it in a dry run.
This error happens when upgrading from version `24.23.0` to version `24.24.0`.

**Relevant debug logs**
```
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "D8CyzgPom",
           "repository": "project/sample",
           "err": {
             "message": "content.matchAll is not a function",
             "stack": "TypeError: content.matchAll is not a function\n    at Object.extractPackageFile (/builds/project/renovate/node_modules/renovate/dist/manager/dockerfile/extract.js:84:33)\n    at Object.extractPackageFile (/builds/project/renovate/node_modules/renovate/dist/manager/index.js:64:13)\n    at Object.getManagerPackageFiles (/builds/project/renovate/node_modules/renovate/dist/workers/repository/extract/manager-files.js:41:41)"
           },
           "msg": "Repository has unknown error"
         },
   ]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! renovate-bot@0.0.0 renovate: `renovate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the renovate-bot@0.0.0 renovate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-21T20_56_55_930Z-debug.log
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**
It could very well be that this is not a renovate bug, but a problem with gitlab. But maybe someone in the community has experienced this problem before?

**Comment by rarkins** [comment]
It's coming from this source line: https://github.com/renovatebot/renovate/blob/951d795dbd7b0919ecde500aec60b4545d6f8614/lib/manager/dockerfile/extract.ts#L69-L71

If its not reproducible then that's surprising. Can you find where that log is first written, and what are the lines before it?

Cc @casdevs

**Comment by viceice** [comment]
@theexiile1305 which mode version are you using? You need at least node v12 lts.

**Comment by casdevs** [comment]
string.matchAll is supported in node >= 12

or maybe somehow your string prototype has been changed?

**Comment by theexiile1305** [comment]
@viceice Oh yea i get it, I've used node 10 as base image in my gitlab ci pipe. Now, I've upgraded the base image to `node:14` and it works!

@rarkins @viceice @casdevs Thanks for your all support 😆
