### ISSUE TITLE
Provide capability to opt-out of rebase option

### ISSUE THREAD

**Issue by tomkerkhove** [renovatebot/renovate#8387]
**What would you like Renovate to be able to do?**

Provide capability to opt-out of rebase option which is added as a checkbox. This is because PR checks, such as [`task-list-completed`](https://github.com/marketplace/task-list-completed), will always block the PR because of the checkbox.

![image](https://user-images.githubusercontent.com/4345663/105463281-1b6b6080-5c90-11eb-8d30-784846ce1371.png)

**Did you already have any implementation ideas?**

Provide an opt-out in the Renovate configuration.

**Comment by viceice** [comment]
You need to override [`prBodyTemplate`](https://docs.renovatebot.com/configuration-options/#prbodytemplate).

Remove the `{{{controls}}}` from default template, that should remove the checkbox.

**Comment by rarkins** [comment]
Add this to your config:

```json
"prBodyTemplate": "{{{header}}}{{{table}}}{{{notes}}}{{{changelogs}}}{{{configDescription}}}{{{footer}}}"
```

**Comment by tomkerkhove** [comment]
Thanks a ton! I was hoping for a simple flag but this makes sense as well.

**Comment by rarkins** [comment]
You're welcome to contribute a PR to this repo to make a simple *preset* that does the same, if you want your own config to look nice and cleaner.

**Comment by tomkerkhove** [comment]
It's ok, didn't want to sound harsh - Sorry!

Closing as this is fine, thanks for the help! (should've been a GH Discussion, sorry)
