### ISSUE TITLE
Renovate ENV variables in Dockerfiles

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#839]
As discussed in https://github.com/singapore/renovate/pull/734

Example:
```
ENV FOO_VERSION 1.1.0
```

The challenge is how Renovate can determine (a) the original package name and (b) the package manager (npm, etc). For package name we could default to stripping _VERSION and then converting to lower case. For package manager we may need to invent our own convention and put that in a comment, eg

```
ENV FOO_VERSION 1.1.0 # npm
```

Alternatively

```
ENV FOO_VERSION 1.1.0 # npm:foo
```
(Assuming `:` is a suitable delimiter, or we pick something else)

**Comment by rarkins** [comment]
Maybe we should make it clearer and annotate with Renovate too, eg

```
ENV FOO_VERSION 1.1.0 # renovate npm:foo
```

Also need to keep in mind that this probably won't be the only "custom" renovate type in future (we find other non-official package/version files to renovate) so making it as generic and reusable as possible is desirable

**Comment by destroyerofbuilds** [comment]
Annotating the line seems to me as the only way to clearly know that line needs to be updated, and where to find the metadata for the update.

**Comment by rarkins** [comment]
Would this also apply to ARG as well?

**Comment by rarkins** [comment]
The official Node.js Dockerfiles have a few version references, e.g.

```
FROM alpine:3.6

ENV NODE_VERSION 8.11.0

ENV YARN_VERSION 1.5.1
```

Here's an example of bumping node and yarn versions: https://github.com/nodejs/docker-node/commit/4c7763dc2cb067becf12ea4bd55e88b881ccba2b

**Comment by rarkins** [comment]
One approach we could support us like:

```
ENV WEBPACK_NPM_VERSION 1.5.0
```

and then we’d take whatever is before the `_NPM_VERSION` and lower-case it before looking up from npmjs. 

One challenge: scoped package names, but I think we can solve it like:

```
ENV ANGULAR_CORE_NPM_VERSION 5.0.0
```

**Comment by destroyerofbuilds** [comment]
> `ANGULAR_CORE_NPM_VERSION`

What is the behavior in the event that I publish a package called `angular_core`?

**Comment by rarkins** [comment]
When I googled from my phone I had thought it could be only lower case alphabet and hyphen in a package name, but seems it's actually less restrictive: https://docs.npmjs.com/files/package.json#name

Wondering if this is valid and feasible instead:

```
ENV ANGULAR/CORE_NPM_VERSION 5.0.0
```

**Comment by mxey** [comment]
Unix environment variables do not allow slashes.

**Comment by rarkins** [comment]
@mxey thanks. In that case I'm still looking for a character/delimiter that is valid in unix environment variables but forbidden by npm package names.

Here are characters that need url encoding and hence are not allowed by npm for package names:
![image](https://user-images.githubusercontent.com/6311784/42704550-8912526c-86d0-11e8-8374-fcc21da24775.png)

Meanwhile Unix env variables apparently must conform to `[a-zA-Z_]+[a-zA-Z0-9_]*`

Which I think means we're out of luck to find a foolproof solution. A compromise could be that we use a double underscore to replace forward slashj and have the disclaimer that if any npm packages *actually have a double underscore in their name too* then they are out of luck and can't use this shortcut. e.g. `ANGULAR__CORE_NPM_VERSION`

**Comment by mxey** [comment]
Renovate is not limited to npm though. I don't think trying to find the magical characters is fruitful. Why not go with the original comment idea?

**Comment by ForbesLindesay** [comment]
I think the comment proposal will work better:

```dockerfile
ENV FOO_VERSION 1.1.0 # renovate npm:foo
```

This would then be extensible. In my current use case, I actually want to pull from GitHub releases (https://github.com/FFmpeg/FFmpeg/releases)

**Comment by viceice** [comment]
is simply doable with [regex](https://docs.renovatebot.com/modules/manager/regex/) manager
