### ISSUE TITLE
GitHub App ignoring additionalReviewers so not adding reviewers to PR

### ISSUE THREAD

**Issue by nhojpatrick** [renovatebot/renovate#8403]
**What Renovate type, platform and version are you using?**

GitHub App

**Describe the bug**

Using this `"additionalReviewers" : ["nhojpatrick"],` in `.github/renovate.json` does not add `nhojpatrick` as a reviewer to the pull request.

**Relevant debug logs**

I can't see any error, but I do see;
```
DEBUG: Repository config
{
  "fileName": ".github/renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "dependencyDashboard": true,
    "excludeCommitPaths": [
      "relocation_**"
    ],
    "labels": [
      "dependencies"
    ],
    "additionalReviewers": [
      "nhojpatrick"
    ],
    "prHourlyLimit": 0,
    "separateMinorPatch": true,
    "separateMultipleMajor": true
  }
}
```

The below that I can see a branch being created and the pull request being created, the label is added but the reviewer section appears to be ignored.

```
DEBUG: Committing files to branch renovate/plugins.maven.maven-project-info-reports-plugin(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
INFO: Branch created(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
{
  "commitSha": "99de59a"
}
DEBUG: Ensuring PR(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
DEBUG: getBranchPr(renovate/plugins.maven.maven-project-info-reports-plugin)(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
DEBUG: findPr(renovate/plugins.maven.maven-project-info-reports-plugin, undefined, open)(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
DEBUG: Creating PR(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
{
  "prTitle": "Update dependency org.apache.maven.plugins:maven-project-info-reports-plugin to v3.1.1"
}
DEBUG: Creating PR(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
{
  "title": "Update dependency org.apache.maven.plugins:maven-project-info-reports-plugin to v3.1.1",
  "head": "nhojpatrick:renovate/plugins.maven.maven-project-info-reports-plugin",
  "base": "develop",
  "draft": false
}
DEBUG: PR created(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
{
  "pr": 24,
  "draft": false
}
DEBUG: Adding labels 'dependencies' to #24(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
INFO: PR created(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
{
  "pr": 24,
  "prTitle": "Update dependency org.apache.maven.plugins:maven-project-info-reports-plugin to v3.1.1"
}
DEBUG: Created Pull Request #24(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
DEBUG: Checking #24 for automerge(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/plugins.maven.maven-project-info-reports-plugin")
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Check any of my public repos, they all have renovate enabled, the same config and the same issue.

https://github.com/nhojpatrick/nhojpatrick-qa-ruleset-checkstyle/blob/develop/.github/renovate.json

**Comment by HonkingGoose** [comment]
I think you need to use the `reviewers` configuration option instead.

From the way I read the docs, the `additionalReviewers` config option is meant to add to the **existing** reviewers list.
You don't have any reviewers listed yet, so there's nothing to add.

It seems to me that `additionalReviewers` is meant to augment a preset or base list, without replacing a original `reviewers` list.
Quote from `additionalReviewers` docs:

> Additional reviewers for Pull Requests (in contrast to `reviewers`, this option adds to the existing reviewer list, rather than replacing it)

> In contrast to `reviewers`, this option adds to the existing reviewer list, rather than replacing it. This makes it suitable for augmenting a preset or base list without displacing the original, for example when adding focused reviewers for a specific package group.

---

Quote from `reviewers` docs:

> Requested reviewers for Pull Requests (either username or email address depending on the platform)
> Must be valid usernames. If on GitHub and assigning a team to review, use the prefix `team`:, e.g. provide a value like `team:someteam`.

---

I have opened a PR at your repository, with what I think is a better config (https://github.com/nhojpatrick/nhojpatrick-qa-ruleset-checkstyle/pull/30).

I recommend that you wait until the Renovate team has verified that my config is better, before you merge it in. 😄

**Comment by nhojpatrick** [comment]
@HonkingGoose yes I want to ensure a specifier reviewer is added to a PR. And I would quote the same documentation you highlighted.

Example
- Pull Request gets created and using `reviewer` abc is added.
- Total of 1 reviewer.
- User def is manually added.
- Total of 2 reviewers.
- Pull Request is now rebase.
- I would expect renovate to wipe out user def from the pull request, as `reviewers` is configured to be just `abc`.
- What is the rebase include an update to the the renovate configuration, should the new renovate configuration be used to update/overwrite the existing pull request.

Reading `additionalReviewers` I would expect it to work with `null`, `0` or `more than 1` reviewers.

If the documentation changes to state `1 or more` reviewers need to be defined before `additionalReviewers` is looked at, I would close this. I would then raise a feature request to add `ensureReviewers` that would work with `null`, `0` or `more than 1` reviewers where it ensures specified reviewers have been added to a pull request. Reading the previous issues opened which resulted in `additionalReviewers` being added, that is how I would expect it to work.

**Comment by rarkins** [comment]
Reviewers are not added or reset upon rebase.

**Comment by rarkins** [comment]
Please re-test with `reviewers` and confirm if that fixes behaves as expected. If not then a minimal reproduction repo is necessary.
