### ISSUE TITLE
Add option to disable list of presets

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#841]
Users should be able to configure an array of presets that are ignored/disabled.

New configuration option: `ignorePresets` which is of type list (array) of strings. Any presets listed here get ignored any time they are found, no matter how deep.

**Comment by rarkins** [comment]
This perhaps needs to work in "reverse" order, otherwise if you load preset A then B, and preset B disables a preset that A extends, then it would be too late.

**Comment by olstenlarck** [comment]
Yeap. Thought for that feature too.

**Comment by rarkins** [comment]
Need to think more about this A - B use case mentioned above, with a real use case example for clarity.

**Comment by rarkins** [comment]
Example config:

```json
{
  "extends": ["config:base"],
  "ignorePresets": [":prHourlyLimit2"]
}
```

The above would mean that the user would get all the presets in `config:base` except `:prHourlyLimit2`.
