### ISSUE TITLE
Unexpected error: Cannot find preset's package (@)

### ISSUE THREAD

**Issue by JounQin** [renovatebot/renovate#8419]
**What Renovate type, platform and version are you using?**

GitHub bot

**Describe the bug**

I have https://unpkg.com/browse/@1stg/renovate-config@0.7.0/package.json with `renovate-config` configed, but the bot still complains.

**Relevant debug logs**

https://github.com/rx-ts/babel-preset-proposal-typescript/issues/114

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

https://github.com/rx-ts/babel-preset-proposal-typescript/issues/114

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
Please change `"extends": "@1stg"` to `"extends": ["@1stg"]`
