### ISSUE TITLE
Add support for monorepos change-log files

### ISSUE THREAD

**Issue by Gherciu** [renovatebot/renovate#8425]
Problem: Most monorepo (specially built with Lerna) generate Changelog files for each package in part but not one concatenated for all packages in the root folder.

Feat Request: Would be nice to collect change-logs from each package in part and show these correct in Release Notes PR section opened by renovate bot.

**Comment by rarkins** [comment]
Duplicate of #2926 

Some more specifics would help progress the topic, including a reproduction repo with a PR containing a wrong or missing changelog from a monorepo
