### ISSUE TITLE
composer: support @dev versions

### ISSUE THREAD

**Issue by lazka** [renovatebot/renovate#8446]
**What would you like Renovate to be able to do?**

I have renovate with "update-lockfile" and a composer project, there I have

```json
"require": {
        "somepackage": "@dev",
},
 "repositories": [
        {
            "type": "vcs",
            "url": "here is where somepackage lives"
        },
]
```

as a requirement and renovate says

```
Dependency somepackage has unsupported value @dev
```

I wouldn't mind if it would ignore that dep, but it also ignores all transitive deps and doesn't update anything even though
`composer outdated` gives me a list of 10 packages that can be updated.

**Comment by viceice** [comment]
Can you please create a minimal reproduction repo to verify and debug against.

**Comment by lazka** [comment]
ok, I'll give it a try.

**Comment by monstro805** [comment]
dependencies/Pipfile.lock

**Comment by monstro805** [comment]
hey just posted this let me know if it works
