### ISSUE TITLE
Lombok update not complete for Gradle project

### ISSUE THREAD

**Issue by Xendar** [renovatebot/renovate#8454]
**What Renovate type, platform and version are you using?**

Self hosted Renovate, using an on premise BitBucket server.

**Describe the bug**

I got a new Lombok update this morning, and not all Gradle dependencies (inside `build.gradle`) are updated:
![image](https://user-images.githubusercontent.com/24693144/106250245-acec4c80-6213-11eb-935b-f20ade324125.png)

However, Maven update is fine:
![image](https://user-images.githubusercontent.com/24693144/106250578-1e2bff80-6214-11eb-8556-e11b4b5365b1.png)

**Relevant debug logs**

Nothing relevant in the logs:
```
[2021-01-29T00:02:29.441Z]  INFO: Branch created (repository=myproject/myrepo, branch=renovate/org.projectlombok-lombok-1.x)
[2021-01-29T00:02:29.441Z]        "commitSha": "91b1ffd"
[2021-01-29T00:02:29.441Z]  INFO: PR created (repository=myproject/myrepo, branch=renovate/org.projectlombok-lombok-1.x)
[2021-01-29T00:02:29.441Z]        "pr": 58,
[2021-01-29T00:02:29.441Z]        "prTitle": "Update dependency org.projectlombok:lombok to v1.18.18"
```

**Have you created a minimal reproduction repository?**

Will try to create one (private company repository)

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by viceice** [comment]
Please try the [`gradle-lite`](https://docs.renovatebot.com/modules/manager/gradle-lite/) manager

```json
{
  "gradle": {
    "enabled": false
  },
  "gradle-lite": {
    "enabled": true
  }
}

**Comment by rarkins** [comment]
If still not resolved, please create a minimal reproduction repo so that we can debug it

**Comment by Xendar** [comment]
> Please try the [`gradle-lite`](https://docs.renovatebot.com/modules/manager/gradle-lite/) manager
> 
> ```json
> {
>   "gradle": {
>     "enabled": false
>   },
>   "gradle-lite": {
>     "enabled": true
>   }
> }

I was not aware of this one, I can give it a try

**Comment by Xendar** [comment]
Issue reproduced!
Here's the link to the PR: https://github.com/Xendar/renovate-bot-lombok/pull/2

**Comment by viceice** [comment]
Did you tried the `gradle-lite` manager?

**Comment by Xendar** [comment]
> Did you tried the `gradle-lite` manager?

That's the next step 🙂

**Comment by Xendar** [comment]
> > Did you tried the `gradle-lite` manager?
> 
> Hey @viceice
> I created a new repository enabling the `gradle-lite` manager. Let's see what Renovate does about it :)
> https://github.com/Xendar/renovate-bot-lombok-lite

The PR is correct with Gradle Lite: https://github.com/Xendar/renovate-bot-lombok-lite/pull/2

**Comment by viceice** [comment]
We focus on gradle-lite, so won't fix the old gradle manager

**Comment by Xendar** [comment]
> We focus on gradle-lite, so won't fix the old gradle manager

So is it fully functional and ready to be used broadly?

**Comment by viceice** [comment]
For most cases yes, but we need more feedback to be sure. 🙃

**Comment by Xendar** [comment]
I found an issue with the Gradle Lite manager, linked here, but if there is not intend on investing on the Gradle one, should we close this issue?
