### ISSUE TITLE
renovate not checking all the relevant files before doing a merge commit for aws-cdk packages.

### ISSUE THREAD

**Issue by Ranjith072** [renovatebot/renovate#8484]
**What Renovate type, platform and version are you using?**

hosted App

**Describe the bug**

Renovate is updating the files partially since last week, we are using a aws cdk which uses both node js package.json and individual python packages from pypy, whenever there is a new version is released renovate should update both package.json and python setup.py file in the same pull request and it was working well till the last merge made by renovate .
in the last merge renovate only updated the package.json didnt update the setup.py .

**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

![image](https://user-images.githubusercontent.com/57263575/106427877-63486f80-6468-11eb-803c-ed7b12c5976f.png)

**Comment by Ranjith072** [comment]
[debug_logs.txt](https://github.com/renovatebot/renovate/files/5902513/debug_logs.txt)

**Comment by viceice** [comment]
**renovate.json**
```json
{
  "fileName": "renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "automergeType": "branch",
    "automerge": true,
    "masterIssue": true,
    "major": {
      "automerge": false
    },
    "pin": {
      "automerge": true
    },
    "pinDigests": true,
    "packageRules": [
      {
        "packageNames": [
          "awscli",
          "aws-sdk",
          "boto3",
          "boto3-stubs",
          "botocore"
        ],
        "extends": [
          "schedule:monthly"
        ],
        "stabilityDays": 0,
        "prNotPendingHours": 0,
        "groupName": "aws packages"
      },
      {
        "packagePatterns": [
          "^org\\.jetbrains\\.kotlinx:"
        ],
        "versionScheme": "semver"
      }
    ],
    "lockFileMaintenance": {
      "enabled": true
    },
    "ignorePaths": [
      "sql-server-dependency/Dockerfile"
    ],
    "stabilityDays": 3,
    "prNotPendingHours": 74,
    "timezone": "Europe/Oslo",
    "semanticCommits": true
  }
```

**Comment by viceice** [comment]
Please provide a minimal reproduction repo and fully fill the issue template

**Comment by Ranjith072** [comment]
i am not if this can be reproduced as it happened for the first time, whenever aws cdk releases new version it will usually update both  setup.py and package.json together.

**Comment by rarkins** [comment]
Please reopen if you can reproduce

**Comment by Ranjith072** [comment]
for reproduction ,i have reverted the package.json and package-lock.json and an hour after i see the PR back with the same changes.
![image](https://user-images.githubusercontent.com/57263575/106448820-90564b80-6483-11eb-8980-7a379eb69643.png)

**Comment by viceice** [comment]
@Ranjith072 Please read [this](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) and create a public reproduction repo.
