### ISSUE TITLE
24.30.0 validator fails non-migrated packageRules

### ISSUE THREAD

**Issue by roock** [renovatebot/renovate#8485]
**What Renovate type, platform and version are you using?**

Self hosted Gitlab with self hosted renovate bot
Working version: 24.28.4
non-working version 24.30.2

**Describe the bug**

The changes in #6939 seem to have introduced breaking changes which should have triggered a major version number increment.

A configuration file running fine with 24.28.4, isn't valid anymore with 24.32.2

The relevant information tests and logs can be found here:
https://gist.github.com/roock/5db4afdb5cc3c112c7866adc73102917

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [X] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Comment by viceice** [comment]
It's only the validator which fails, renovate will work fine with that config.

**Comment by rarkins** [comment]
Can we update the validation to perform the migration first in such cases?

**Comment by viceice** [comment]
should be possible

**Comment by roock** [comment]
thx for the quick response. I was indeed not running renovate itself, but only the validator.

**Comment by HonkingGoose** [comment]
It looks like some kind of config migration is happening in our current `config-validator.ts` code:

https://github.com/renovatebot/renovate/blob/ab7f6793649f80d4443bc25dccfd6fce9e5e5962/lib/config-validator.ts#L19-L50

Did this PR resolve this issue?

- https://github.com/renovatebot/renovate/pull/8503

**Comment by roock** [comment]
@HonkingGoose I don't think I can reproduce the issue again with current versions of renovate. I would suggest closing the issue

**Comment by HonkingGoose** [comment]
@roock Thanks for the comment. I see the maintainer closed the issue now.
