### ISSUE TITLE
OnboardingConfig in config.js is not respected if organization onbarding preset exists

### ISSUE THREAD

**Issue by rebeccatang16** [renovatebot/renovate#8490]
**What Renovate type, platform and version are you using?**

Github, self-hosted whitesource/renovate:1.2.0

**Describe the bug**

This is a continuation of the discussion from here https://github.com/whitesource/renovate-on-prem/issues/132

I have a config.js that specifies an onboardingConfig, but onboarding PRs are still being made with:

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>orgName/renovate-config"
  ]
}
```
The config.js looks like:

```
module.exports = {
  onboardingConfig: {
    extends: ["github>orgName/renovate-config"]
  },
  ...
};
```
It's mounted into the Kubernetes pod via a secret rather than a configmap because of some sensitive stuff we put in the rest of it. I can confirm from exec'ing into the pod that the config exists at /usr/src/app/config.js and appears to have the right contents.

Do you have any suggestions about why this is happening and how I can fix it?

**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by viceice** [comment]
As mentioned in the parent issue, this behavior is by design. So please update your descriontion to reflect your desired behavior.

Currently renovate searches the following files for overriding onboarding config:

1. `{orgname}/renovate-config/default.json`
1. `{orgname}/renovate-config/renovate.json`
1. `{orgname}/.{platform}/renovate-config.json`

**Comment by rarkins** [comment]
Working per design, but would accept a feature request or PR to make the behaviour customizable if desired (i.e. turn OFF this automatic preset insertion if desired).
