### ISSUE TITLE
force.constraints will override any constraints detected by package managers

### ISSUE THREAD

**Issue by yoavain** [renovatebot/renovate#8526]
**What Renovate type, platform and version are you using?**
hosted, GitHub

**Describe the bug**
Renovate do not honor node constraints and updates lock file to version 2

**Relevant debug logs**
![image](https://user-images.githubusercontent.com/644871/106803986-7d06d400-666d-11eb-96ee-52570960d460.png)

**Have you created a minimal reproduction repository?**
No, But here's the PR:
https://github.com/yoavain/webpack-playground/pull/324/files

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [X] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

My renovate.json contains the following:
```json
    "force": {
        "constraints": {
            "node": "< 15.0.0"
        }
    },
```

**Comment by viceice** [comment]
Please add npm constraint too, as v7 is now tagged as latest.

We already fixed the lockfile version detection in renovate, but it's probably not yet published to the hosted  app.

**Comment by rarkins** [comment]
Your `force` config is overriding the `constraints` which are detected in the `package.json`. In other words, it's your config making it not work.

If you remove it, it works as expected: https://github.com/renovate-tests/webpack-playground/pull/1/files
