### ISSUE TITLE
Private submodules fail to update

### ISSUE THREAD

**Issue by koterpillar** [renovatebot/renovate#8532]
**What Renovate type, platform and version are you using?**

Hosted app for GitHub.

**Describe the bug**

Private submodule not being kept up-to-date in Renovate.

We have repositories A and B both enabled for Renovate, with B being a submodule in A. There are no PRs raised for updating B in A even though it is behind on the same branch.

Renovate config looks like this:

```
{
  "extends": [
    "config:base"
  ],
  "packageRules": [
    /* omitted */
  ],
  "prCreation": "not-pending",
  "git-submodules": {
    "enabled": true
  }
}
```

**Relevant debug logs**

(Repository names changed to A and B, organisation name changed to ORG)

```
DEBUG: Cloning git submodule at submodules/B
WARN: Unable to initialise git submodule at submodules/B

...

WARN: Error mapping git submodules during extraction
{
  "err": {
    "task": {
      "commands": [
        "ls-remote",
        "--symref",
        "https://github.com/ORG/B.git",
        "HEAD"
      ],
      "format": "utf-8"
    },
    "message": "fatal: could not read Username for 'https://github.com': No such device or address\n",
    "stack": "Error: fatal: could not read Username for 'https://github.com': No such device or address\n\n    at GitExecutorChain.onFatalException (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:61:87)\n    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:52:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/ubuntu/renovateapp/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
  }
}
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

The `WARN: Error mapping git submodules during extraction` doesn't appear in _every_ run, I have been unable to determine what triggers it.

**Comment by viceice** [comment]
see discussion at #8529. You need to configure a hostRule to allow access private git repositories
