### ISSUE TITLE
pep440 handle complex minor ranges

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#8537]
**What Renovate type, platform and version are you using?**

Hosted app, but not relevant

**Describe the bug**

Renovate can't successfully update `==3.2.*,>=3.2.2`.

**Relevant debug logs**

```
currentValue | ==3.2.*,>=3.2.2
msg | pep440: failed to calculate newValue
result | ==4.0.*,>=3.2.2
toVersion | 4.1.1
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Proposed new test:

```
 it('simplifies complex ranges', () => {
    const invalid = getNewValue({
      currentValue: '==3.2.*,>=3.2.2',
      rangeStrategy: 'replace',
      fromVersion: '3.2.5',
      toVersion: '4.1.1',
    });
    expect(invalid).toEqual('===4.1.*');
  });
```

**Comment by olegkrivtsov** [comment]
I'd like to help with this one.

**Comment by olegkrivtsov** [comment]
My plan for fixing this issue:

1. Modify `lib/versioning/pep440/index.spec.ts` and add the new test as suggested.
2. Modify `lib/versioning/pep440/range.ts` and introduce a new function `simplifyComplexRanges()` which would check if the `currentValue` contains something like `==3.2.*,>=3.2.2` and transform it into `~=3.2.2` (according to this page: https://www.python.org/dev/peps/pep-0440/#version-matching)
3. Modify this block
https://github.com/renovatebot/renovate/blob/1a9f51851321d6ebee2a81ce2c04f817bdd9f9dd/lib/versioning/pep440/range.ts#L97-L109
and simplify the complex ranges first before calculating `newValue`.

**Comment by viceice** [comment]
Blocked by #13334

**Comment by olegkrivtsov** [comment]
Hi @viceice it seems that https://github.com/renovatebot/renovate/pull/13334 is now Merged. Can I proceed  with this one?

**Comment by viceice** [comment]
Yes

**Comment by olegkrivtsov** [comment]
Hi @viceice is my plan for this issue acceptable?

**Comment by rarkins** [comment]
Make sure that the simplify function doesn't migrate people to it unnecessarily when there's no update to do

**Comment by MaronHatoum** [comment]
duplicates: https://github.com/renovatebot/renovate/issues/8324 
it has been fixed in: https://github.com/renovatebot/renovate/pull/14598

just in case, I also ran the suggested test in the description and it passed successfully.

```
  it('simplifies complex ranges', () => {
    const invalid =  pep440.getNewValue({
      currentValue: '==3.2.*,>=3.2.2',
      rangeStrategy: 'replace',
      currentVersion: '3.2.5',
      newVersion: '4.1.1',
    });
    expect(invalid).toBe('==4.1.*');
  });
```
- I believe we can close this issue
