### ISSUE TITLE
Suggestion: ingoreImmature

### ISSUE THREAD

**Issue by onsails** [renovatebot/renovate#8565]
**What would you like Renovate to be able to do?**

It's common sence in rust that packages with version starting from 0, like 0.1.2, are considered immature and lack semver compatibility guarantees, minor version change can cause breaking changes. But 1.* versions mostly follow semver. Currently there is no option for rust projects to enable automergeMinor without risk of breaking project. CI can't help because for example new minor update of [sled](https://github.com/spacejam/sled) can be api-compatible with previous minor version but introduce a breaking change in a storage format.

**Did you already have any implementation ideas?**

**Comment by rarkins** [comment]
See `matchCurrentVersion`. You can add it to any package rule where you enable automerge

**Comment by onsails** [comment]
> See `matchCurrentVersion`. You can add it to any package rule where you enable automerge

I see, thanks
