### ISSUE TITLE
Android SDK not found

### ISSUE THREAD

**Issue by jonathanmorley** [renovatebot/renovate#8596]
**What Renovate type, platform and version are you using?**

Self-hosted renovate v24.11.6

**Describe the bug**

Renovate errors against android repositories with

```
android {
    buildFeatures {
        dataBinding = true
    }
}
```

in their build.gradle

**Relevant debug logs**

```
"errMessage": "Command failed: ./gradlew --init-script renovate-plugin.gradle renovate
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/tmp/renovate/repos/bitbucket-server/REDACTED/REDACTED/local.properties'.
```

**Have you created a minimal reproduction repository?**

build.gradle:

```

```

Related to https://github.com/renovatebot/renovate/issues/2707

**Comment by rarkins** [comment]
Can you try disabling the `gradle` manager and trying `gradle-lite` and see if it detects/upgrades everything you need? Config:

```json
{
  "gradle": {
    "enabled": false
  },
  "gradle-lite": {
    "enabled": true
  }
}
```

**Comment by jonathanmorley** [comment]
Already tried that, it does

**Comment by jonathanmorley** [comment]
Is `gradle-lite` recommended over `gradle`?
Is `gradle-lite` GA?
Is `gradle` no longer getting support for issues?

**Comment by viceice** [comment]
* yes
* yes 🙃 
* only critical bugs
