### ISSUE TITLE
Request: Update Browserslist

### ISSUE THREAD

**Issue by service-paradis** [renovatebot/renovate#8615]
**What would you like Renovate to be able to do?**

As stated in [Browserslist documentation](https://github.com/browserslist/browserslist#browsers-data-updating), we can run `npx browserslist@latest --update-db` from time to time to update browsers list.

It would be great if renovatebot was able to detect that browserslist is in use (maybe by checking if there is a `.browserslistrc` file) and run this command while renovating.

**Did you already have any implementation ideas?**

- Detect if Browserslist is used
- Run the update command
- Create a PR with the updated list

**Comment by rarkins** [comment]
Please provide a minimal reproduction repo with an outdated browser list so we can look at the structure.

**Comment by service-paradis** [comment]
@rarkins Sure, thank you for the follow up!

Youi can use this [minimal repo](https://github.com/service-paradis/renovate-browserslist).
As you can see, there is a single dependency (`autoprefixer`). It does not need any update (`10.2.4` is the latest version to this date). We got no results by running `npm outdated`.

If we take a look min `package-lock.json`, we can see the a peer dependency `caniuse-lite` using version `1.0.30001181`. The [latest version is `1.0.30001185`](https://github.com/ben-eb/caniuse-lite/blob/master/CHANGELOG.md).
```json
"caniuse-lite": {
      "version": "1.0.30001181",
      "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001181.tgz",
      "integrity": "sha512-Fpi4kVNtNvJ15H0F6vwmXtb3tukv3Zg3qhKkOGUq7KJ1J6b9kf4dnNgtEAFXhRsJo0gNj9W60+wBvn0JcTvdTg=="
    }
```

We can obtain the latest version by running `npx browserslist@latest --update-db`. It will gives the following results:
![image](https://user-images.githubusercontent.com/12817388/107536299-9f2db400-6b8f-11eb-8d7a-4a49abce1b7a.png)

If we take another look at `package-lock.json`, we will see the updated dependency:
```json
"caniuse-lite": {
      "version": "1.0.30001185",
      "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001185.tgz",
      "integrity": "sha512-Fpi4kVNtNvJ15H0F6vwmXtb3tukv3Zg3qhKkOGUq7KJ1J6b9kf4dnNgtEAFXhRsJo0gNj9W60+wBvn0JcTvdTg=="
    },
```

In this minimal repo, there was no target browsers changes (`No target browser changes`). It sometimes change and gives a result similar to the following:
![image](https://user-images.githubusercontent.com/12817388/107536762-224f0a00-6b90-11eb-91a2-47d627a71a66.png)

Hope it helps!

**Comment by viceice** [comment]
Lockfile maintenance will do this for you. No need for a new feature.

https://docs.renovatebot.com/configuration-options/#lockfilemaintenance

**Comment by service-paradis** [comment]
🤦‍♂️ How did I miss that! Will try it soon!
Thank you for your support!

**Comment by HonkingGoose** [comment]
Hi @service-paradis, 

Renovate can only update **all** dependencies within the lockfile, you cannot pick-and-choose what you like Renovate to update within the lockfile.
By default if you enable lockfileMaintenance, you'll get a lockfile update PR "once  a week on monday", but you can increase/decrease the frequency of lockfile updates via the `schedule` configuration option.

See https://docs.renovatebot.com/configuration-options/#schedule for more on scheduling.

**Comment by service-paradis** [comment]
Ok, thank you for your answer.
Looks like it does not solve what I'm trying to achieve. I think it would be great to be able to manage this use case using Renovate (updating caniuse db), but I understand it might not be something you want to add.
I will continue managing it using a workaround. Thank you all for your time!
