### ISSUE TITLE
Support Go proxies if GOPROXY is set

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#8677]
**What would you like Renovate to be able to do?**

Support Go Proxies

**Did you already have any implementation ideas?**

If `GOPROXY` is set, try that first before falling back to a manually lookup like we have today. We should also think about how to use `GOPRIVATE` and whether that needs to be tied into our host rules.

**Comment by fgblomqvist** [comment]
Is there any updates on this? I am unable to get GOPROXY to work, resulting in errors like:
```
Command failed: go get -d ./...
go: <private-go-lib>: verifying go.mod: <private-go-lib>/go.mod: reading <private-go-lib>: 410 Gone
	server response: not found: <private-go-lib>: unrecognized import path "<private-go-lib>": https fetch: Get "<private-go-lib>?go-get=1": dial tcp: lookup <private-go-lib-domain> on [2001:4860:4860::8888]:53: server misbehaving
```
(pasting this here so that it's easier for others with the same issue to find this)

**Comment by rarkins** [comment]
@fgblomqvist do you mean that your private go lib is only fetchable via your go proxy? Your log seems to indicate that it's trying to fetch direct.

**Comment by fgblomqvist** [comment]
Sorry I think I butchered the log too much, fixed it up. `<private-lib>` is a lib/repo path, such as "my-company.com/libs/foo". Does it make more sense now?

**Comment by fgblomqvist** [comment]
Technically, speaking, since I have access to the (private) repo that hosts the source, it might be possible to download the package without GOPROXY I suppose? However, GOPROXY ensures that the package is retrieved from the package mirror.

**Comment by rarkins** [comment]
Just to confirm, you are wanting to use private proxy?

But in your log it's connecting to the public one, is that Renovate's default behavior somehow or as a result of you trying to configure it with env variables?

**Comment by fgblomqvist** [comment]
Yes, I want to use a private proxy, correct. Usually we set it up by just setting `GOPROXY` on the machine and then it's a done deal.

I haven't tried to run Renovate without GOPROXY set yet, but I can potentially do that. Based on this so far, I'm guessing that Renovate is perhaps overriding the GOPROXY when executing the code. However, I haven't dove into the code enough. Maybe I'll do that if I find some time. I'm guessing @zharinov would be able to answer that question.

**Comment by rarkins** [comment]
Do you know why go was querying the gosumdb if you hadn't configured anything? I hadn't expected that unless explicitly configured

**Comment by fgblomqvist** [comment]
I do not, I haven't configured anything except for GOPROXY 🤔

**Comment by rarkins** [comment]
Maybe it gets implicitly set by go if the proxy is set. I misread your earlier comment as meaning you hadn't configured GOPROXY

**Comment by fgblomqvist** [comment]
We got rid of our problem: turns out we forgot to set `GOPRIVATE` for the internal packages (it was indeed GOSUM-related as you guessed). Thanks for the advice @rarkins and apologies for polluting this issue!
