### ISSUE TITLE
Update experimental manager docs section

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#8690]
**What would you like Renovate to be able to do?**
For some peoble it's unclear that [experimental-manager](https://docs.renovatebot.com/modules/manager/#enabling-experimental-managers) is only a placeholder for a real manager name.

**Did you already have any implementation ideas?**

Maybe @HonkingGoose has an idea 🙃 

ref #8689

**Comment by rarkins** [comment]
Closed by https://github.com/renovatebot/renovate/commit/2d3b44401c9b6b72d1549d92e8852f1b3a417b69
