### ISSUE TITLE
fix: mention race condition in Renovate dashboard text

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#8722]
**What would you like Renovate to be able to do?**

I think we should warn the user that they can get the bot stuck in a race condition by clicking too many buttons at once on the dashboard. We can remove the warning text once we've fixed the race condition.

See #4355 and #8719.

**Did you already have any implementation ideas?**

We could probably add a warning after this line:

https://github.com/renovatebot/renovate/blob/68f89c48165d67a40933e448e393611ef5a3f81a/lib/config/definitions.ts#L463

Also need to update the Jest fixture/snapshot so that they match the new code.

**Comment by rarkins** [comment]
The bot won't be stuck in a race condition - it's just that not all the ticked boxes will get executed if you tick them too slowly.

**Comment by HonkingGoose** [comment]
Should the warning be something like this then?

```
Do not tick more than one checkbox at a time or the bot might skip some ticked boxes.
Check if the bot has made the ticked PR before ticking another checkbox.
```

**Comment by HonkingGoose** [comment]
Even better! Thank you! 😄
