### ISSUE TITLE
Testing against GitLab

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#875]
Lately has seen quite a few compatibility issues with GitLab. It's hard for me to tell how much is this about GitLab transitioning from APIv3 to APIv4 or with non-version-related bugs when transitioning from 9.4 to 9.5 to 10.0, or which are Renovate bugs.

At the very least I'd like to have a better way to reproduce errors myself, as previously I've relied on the public gitlab.com instance but this doesn't give me the flexibility to test against specific versions.

This approach should:
- Allow any "supported" GitLab version, not just the latest
- Be reasonably quick/painless to spin up
- Be very low cost (ideally charged per minute or per hour and can be torn down when no longer needed)

Can any GitLab user help suggest a way? One particular approach I've used in the past for other projects is Google Compute Platform, because of its support for maintaining disk storage while not paying for the VM (CPU/RAM/etc) itself. e.g. you can boot up a powerful VM with 20GB storage for an hour, then tear it down for a month and pay only for the 20GB storage while it's inactive. Perhaps this + Docker could be a good combination.

**Comment by haswalt** [comment]
@rarkins how about running GitLab in docker on GCE? could be run for a very short amount of time for little money and shutdown straight afterwards. You could run any version then with lightweight requirements.

**Comment by rarkins** [comment]
@haswalt thanks for the suggestion. In your experience how much time does it take from booting a GitLab to image and actually being able to use it? Wondering how many admin steps there are to get a repo set up for testing and hence whether to start completely from scratch each time or keep state saved between runs. In the latter case I might keep one state for each minor version.
