### ISSUE TITLE
Autodiscover filter expanding braces with forward slash

### ISSUE THREAD

**Issue by vitoyucepi** [renovatebot/renovate#8761]
**What Renovate type, platform and version are you using?**

self-hosted on gitlab, Version 24.53.0

**Describe the bug**

I'm using autodiscover filter with multiple groups. But I can't include subgroups in braces expansion section because they contains forward slash `/`.

```
--autodiscover=true --autodiscover-filter=@(example1|example2/test)/*
```

I want to discover repos in groups
- `example1/*`
- `example2/test/*`

But works in other way. This glob matches only
- `@(example1|example2/test)/test-project`

I can do something like `@(example1|example2)/**` but It has own disadvantages.
Instead of that I've created separate tasks with different filters.
1. ```
    --autodiscover=true --autodiscover-filter=example1/*
    ```
1. ```
    --autodiscover=true --autodiscover-filter=example2/test/*
    ```
**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**
My repos are here https://gitlab.com/vito-renovate-example1

1. RENOVATE_EXTRA_FLAGS: `--autodiscover=true --autodiscover-filter=@(vito-renovate-example1|vito-renovate-example1/renovate-subdir-example1)/*`
    https://gitlab.com/vito-renovate-example1/renovate-runner-test/-/jobs/1039889272
1. RENOVATE_EXTRA_FLAGS: `--autodiscover=true --autodiscover-filter=vito-renovate-example1/**`
    https://gitlab.com/vito-renovate-example1/renovate-runner-test/-/jobs/1039954490
1. RENOVATE_EXTRA_FLAGS: `--autodiscover=true --autodiscover-filter=vito-renovate-example1/*`
    https://gitlab.com/vito-renovate-example1/renovate-runner-test/-/jobs/1039960534

I've done some testing with minimatch.
1. Simple expansion with one level
```
var minimatch = require("minimatch");

var match='@(example1|example2)/*'

var test=[
        'example1/test-project',
        'example2/test-project',
        'example3/test/test-project'
];

console.log(test.filter(minimatch.filter(match)));
```
Outputs
```
[ 'example1/test-project', 'example2/test-project' ]
```
2. Expansion with two levels
```
var minimatch = require("minimatch");

var match='@(example1|example2/test)/*'

var test=[
        'example1/test-project',
        '@(example1|example2/test)/test-project',
];

console.log(test.filter(minimatch.filter(match)));
```
Outputs
```
[ '@(example1|example2/test)/test-project' ]
```

**Comment by rarkins** [comment]
So is this a minimatch/ glob pattern limitation or something Renovate is doing to cause the problem?

Perhaps the user-friendliest solution is to allow the filter to be an array with *or* matching.

**Comment by vitoyucepi** [comment]
It's minimatch and glob problem.
The possible solutions are:
- multiple`--autodiscover-filter` options like `--autodiscover=true --autodiscover-filter=vito-renovate-example1/* --autodiscover-filter=vito-renovate-example1/renovate-subdir-example1/*`
- regexp support `/(vito-renovate-example1|vito-renovate-example1\/renovate-subdir-example1)\/.*/`

**Comment by rarkins** [comment]
In any case this is not a bug so please close this or edit to use the feature request format.

**Comment by vitoyucepi** [comment]
Not a bug. Opened a feature request.
