### ISSUE TITLE
github private repo artifacts problem

### ISSUE THREAD

**Issue by vtolstov** [renovatebot/renovate#8788]
https://github.com/unistack-org/cms-panel/pull/6
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/unistack-org/cms-typescript-sdk.git
npm ERR! 
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/unistack-org/cms-typescript-sdk.git/'
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/renovate-cache/others/npm/_logs/2021-02-20T23_41_11_479Z-debug.log
```

i'm try to add encrypted github token to renovate.json in hostRules but error present

**Comment by rarkins** [comment]
Please reopen as a discussion not issue and providing much more details than the above, otherwise we cannot guess what's going wrong. It looks like you even linked to a private issue, which doesn't help at all.

In future please create only Discussions if you have a question.

**Comment by vtolstov** [comment]
thanks, i'm create discussion https://github.com/renovatebot/renovate/discussions/8789
