### ISSUE TITLE
Gitlab Repo lookup by "path_with_namespace" is not working anymore for the "api/v4" endpoint

### ISSUE THREAD

**Issue by lazy-val-b** [renovatebot/renovate#8793]
**What Renovate type, platform and version are you using?**
Renovate type: latest docker image
Platform: Gitlab
Version: GitLab Community Edition 13.8.4 (issue exists on normal GitLab too)

**Describe the bug**
When using the `repositories` config option or after having autodiscovered projects, renovate makes a request to the GitLab Api to get a single repo and the request URL results in a 404 error, resulting in `repository is not found` on the log.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**
This seems to have worked in past versions of the GitLab api, since I find a lot of examples online using this approach for GitLab. The new way of accessing projects with the given endpoint seems to be `gitlab.domain.com/api/v4/PROJECT_ID` (for self-hosted as well as normal gitlab). Renovate uses `gitlab.domain.com/api/v4/projects/path_with_namespace` which doesn't work anymore.

Renovate discovers all repos with:
`gitlab.domain.com/api/v4/projects` and receives the correct list.

Using the repository config  option `repositories` in the format `['group/name', 'name']` results in a `repository is not found` error. Providing the project ID instead works.

Looking at the source code this is the current behaviour:
https://github.com/renovatebot/renovate/blob/master/lib/platform/gitlab/index.ts#L127
`repo.path_with_namespace` will result in an URL of the format `gitlab.domain.com/api/v4/projects/GROUP/NAME` which returns a 404. Using the id instead should fix the issue (e.g., `repo.id`).

**Comment by rarkins** [comment]
The GitLab API v4 has been supported since 2017 and works fine. Please provide:
- Your `config.js` file
- What is the exact CLI command you run
- The full debug log

**Comment by lazy-val-b** [comment]
Hello again,

thank you for the fast response!

After creating the minimal reproduction repo, I understood that GitLab api v4 supports the _encoded_ path name and not the decoded one. The issue was our reverse proxy which decoded any encoded URI. It works now like a charm.

I still think it would be better to look up autodiscovered repos by id, since it is less error-prone.
