### ISSUE TITLE
PyPi Simple endpoint end slash handling

### ISSUE THREAD

**Issue by dlouzan** [renovatebot/renovate#8817]
**What Renovate type, platform and version are you using?**

Self-hosted latest

**Describe the bug**

At the moment I'm not sure if this is an actual bug, but wanted to open a discussion about it.

While combining renovate self-hosted with JFrog's artifactory and the PyPi Simple index, renovate is not being able to find dependencies on Artifactory due to handling of the end slash in the index endpoint.

The issue happens in combination with https://www.jfrog.com/jira/browse/RTFACT-14235, which basically is a problem on Artifactory redirecting HTTPS to HTTP (yeah 😒). So for instance:

```
# This works
curl -v https://internal.domain/artifactory/api/pypi/pypi-all/simple/

# This is redirected to HTTP with slash at the end
curl -v https://internal.domain/artifactory/api/pypi/pypi-all/simple
...
< HTTP/1.1 302 Found
< Date: Mon, 22 Feb 2021 19:36:40 GMT
< Server: Artifactory/x.x.x
< X-Artifactory-Id: xxx
< Location: http://internal.domain/artifactory/api/pypi/pypi-all/simple/
< Content-Length: 0
```

While this looks to me an artifactory issue, the [relevant PEP itself](https://www.python.org/dev/peps/pep-0503/) points to all addresses ending in slash, so at the moment I'm not sure where the issue really is. Should per spec all URLs end in slash?

But I'm relatively sure, if renovate appended the slash, everything would work because there wouldn't be any redirects involved :bow:

I'd be happy for some guidance or opinions.

/cc @max-wittig @fh1ch @nejch

**Comment by dlouzan** [comment]
The PEP says:

> All URLs which respond with an HTML5 page MUST end with a / and the repository SHOULD redirect the URLs without a / to add a / to the end.

While Artifactory clearly behaves incorrectly here by redirecting an HTTPS to HTTP, I think renovate would be safe to append / ensure `/` to all simple requests?

**Comment by viceice** [comment]
I think this can be easily fixed by `ensureEndingSlash` on  `lookupName` here:

https://github.com/renovatebot/renovate/blob/94be71c6c3ce915e3d7a62c64cc3d4feff5fe644/lib/datasource/pypi/index.ts#L251

**Comment by rarkins** [comment]
Where is the URL coming from? e.g. Renovate config, requirements.txt, etc?

Is it the plain registry url that's getting a 302, or one which we construct with dependency name too?

**Comment by viceice** [comment]
Url is constructed here:

https://github.com/renovatebot/renovate/blob/94be71c6c3ce915e3d7a62c64cc3d4feff5fe644/lib/datasource/pypi/index.ts#L178-L180

**Comment by nejch** [comment]
Just one thing to keep in mind also is that some proxies don't handle double/multiple slashes very well (mostly Apache I think, resulting in 404), so it should only append if needed. I know python-gitlab is doing the opposite (stripping trailing slashes from base urls) for this reason (https://github.com/python-gitlab/python-gitlab/pull/1027).

**Comment by viceice** [comment]
> Just one thing to keep in mind also is that some proxies don't handle double/multiple slashes very well (mostly Apache I think, resulting in 404), so it should only append if needed. I know python-gitlab is doing the opposite (stripping trailing slashes from base urls) for this reason ([python-gitlab/python-gitlab#1027](https://github.com/python-gitlab/python-gitlab/pull/1027)).

That's why we have a util function for it 😉 

https://github.com/renovatebot/renovate/blob/d8df51f20ebf018cf827512ec9c4f0cc95a25541/lib/util/url.ts#L3-L5
