### ISSUE TITLE
Include zero width space in CHANGELOG wrote on PR

### ISSUE THREAD

**Issue by do-su-0805** [renovatebot/renovate#8823]
**What Renovate type, platform and version are you using?**

- GitHub hosted

**Describe the bug**

- ( I found it in a private repository )
- Apparently zero width space ( `&#8203;` ) comes in under certain conditions in CHANGELOG wrote on PR.
  - from this CHANGELOG [eslint-config-prettier/CHANGELOG.md at main · prettier/eslint-config-prettier](https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md). I want you to see this
    - `"prettier/@typescript-eslint",`
  - however, In the quoted one, it says ( e.g. [Update dependency eslint-config-prettier to v8 by renovate · Pull Request #73 · casaub0n/markdown-link-script](https://github.com/casaub0n/markdown-link-script/pull/73) )
    - `"prettier/@&#8203;typescript-eslint",`

**Relevant debug logs**

- Judged unnecessary

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
  - https://github.com/search?p=2&q=%22update+dependency+eslint-config-prettier+to+v8%22+is%3Apublic&type=Issues
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

- I don't think it's a problem, but I found it and reported it.

**Comment by viceice** [comment]
Please readd deleted issues template sections

**Comment by rarkins** [comment]
I've marked this as a low priority bug. We definitely want to err on the careful side of `@` escaping because it's a huge pain to open source developers if they suddenly get hundreds or thousands of notifications because an `@`user reference escaped our sanitizing.

**Comment by do-su-0805** [comment]
@viceice sorry, I don't understand what i readd. I filled it all up.
@rarkins I didn't think so much.You're right. thanks you.
