### ISSUE TITLE
docs: mention migrated/deprecated config options

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#8843]
**What would you like Renovate to be able to do?**

If a user searches for a migrated/deprecated configuration option, they get zero hits in the docs search functionality.

This can lead to confusion: "Hey I used to have docs for `packagePatterns` but now I'm not finding anything!"
The user needs to figure out somehow that `packagePatterns` is now `matchPackagePatterns`.

I have already opened a issue to propose that we migrate users to newer terms automatically via a Renovate PR, so that would be the preferred and proper fix, see #8235.

As a stop-gap until we implement #8235, do we want to have a separate page that lists all the old outdated terms and refers users to the new terms?

**Did you already have any implementation ideas?**

I'm thinking of putting a table like this on a separate page. After implementing #8235 we would remove the page with the table and rely on the automatic migrations from the Renovate bot PRs.

| Old term | New term|
| --- | --- |
| `packagePatterns`  | `matchPackagePatterns` |
| `masterIssue` | `dependencyDashboard` |

**Comment by HonkingGoose** [comment]
@rarkins I was wondering if you want me to work on a PR to fix this issue, or if you'd rather just close it and focus on doing #8235 instead?

**Comment by rarkins** [comment]
Yes, let's do that
