### ISSUE TITLE
Warn louder if configuration prevents post-upgrade tasks from running

### ISSUE THREAD

**Issue by languitar** [renovatebot/renovate#8845]
**What would you like Renovate to be able to do?**

Right now, if a post-upgrade tasks is prevented from being executed by the whitelisting options, not much can be found in the logs on info level. This makes detecting such issues pretty hard. A louder warning in this case would help finding out about such issues. It would even be better if that message was forwarded to the created MR.

**Comment by rarkins** [comment]
We could possibly even earn another this

**Comment by languitar** [comment]
Anything that makes this configuration issue more clear to the user is highly appreciated!

**Comment by rarkins** [comment]
So, let's detect if postUpgradeTasks are attempted in the repo but aren't permitted by the bot config, and log a warning.

**Comment by languitar** [comment]
Does the warning then also propagate to the MR description? Or is it only visible in the bot logs?

**Comment by rarkins** [comment]
Logs: Yes
DependencyDashboard: Added here too, but could be removed again if they don't appear every run
PR: We'd need to try to work that out, but it would be a good idea to make them like an artifact error

**Comment by lmilbaum** [comment]
I have few clarification requests which I will post one by one. Could you please provide an example for a post-upgrade tasks? Where in the codebase the execution of those tasks are handled?

**Comment by lmilbaum** [comment]
> We could possibly even log warn about this

@rarkins If I am not mistaken #15482 is covering this request. WDYT?

**Comment by rarkins** [comment]
Closes by #15482
