### ISSUE TITLE
Gitlab: mutliple assignees error

### ISSUE THREAD

**Issue by strowi** [renovatebot/renovate#8847]
**What Renovate type, platform and version are you using?**
self-hosted Renovate v24.63.0 + Gitlab 13.9.1

**Describe the bug**
Following config only assigns user1 to the MR:
```json
{
  "separateMultipleMajor": true,
  "assignees": [
    "@user1",
    "@user2",
    "@user3",
    "@user4"
  ],
  "packageRules": [
    {
      "matchPackagePatterns": [
        "*"
      ],
      "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
      "groupName": "all non-major dependencies",
      "groupSlug": "all-minor-patch"
    }
  ]
}
```

**Relevant debug logs**
```
 INFO: PR created (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
       "pr": 47,
       "prTitle": "Update renovate/renovate Docker tag to v24.64.1"
DEBUG: Adding assignees 'user1, user2, user3, user4' to #47 (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
ERROR: Failed to add multiple assignees (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
       "iid": 47,
       "assignees": ["user1", "user2", "user3", "user4"]
DEBUG: Added assignees (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
       "assignees": ["user1", "user2", "user3", "user4"]
DEBUG: Searching for CODEOWNERS file (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
DEBUG: No CODEOWNERS file found (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
DEBUG: Created Merge Request #47 (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
DEBUG: Checking #47 for automerge (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
       "automerge": false,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: No automerge (repository=sys/ci/renovate, branch=renovate/docker-all-minor-patch)
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to gitlab.com/strowi/renovate-test
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly
- [ ] Unable to to do since the gitlab.com integration seems [offline right now](https://docs.renovatebot.com/install-gitlab-app/)

regards,
strowi

**Comment by strowi** [comment]
added a link to a public repo

**Comment by rarkins** [comment]
There is no MR in that project to verify the reproduction. Also, multiple assignees is a premium feature for gitlab. Have you confirmed it works when you assign the same user list manually?

**Comment by strowi** [comment]
Sorry, mixed up the links after noticing renovatebot was deactivatd on gitlab.com. (premium-account)
Running this on a 3d gitlab-server it seems to work, will debug this more first. 

Sorry for the hassle!
