### ISSUE TITLE
Cannot access dashboard

### ISSUE THREAD

**Issue by evanstoddard23** [renovatebot/renovate#8851]
**What Renovate type, platform and version are you using?**

hosted app

**Describe the bug**

Get GitHub and GitLab login options on dashboard. I choose GitHub and sign in, then am redirected back to the options page. Cannot get past this page on Chrome or Safari.

**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by alperovitz** [comment]
Ya I fixed that my google youtube vanced is 16.04.38

**Comment by alperovitz** [comment]
You can get it for my google drive p.s uninstall youtube vanced be for you install my copy my copy fixed the buffer problem on my google tv box

**Comment by alperovitz** [comment]
You might see the YouTube icon is missing hopefully someone can fix that
