### ISSUE TITLE
updateInternalDeps default is true

### ISSUE THREAD

**Issue by Hoishin** [renovatebot/renovate#8858]
**What Renovate type, platform and version are you using?**

Self-hosted Renovate on Linux machine for npm, version 24.64.1 as of now

**Describe the bug**

The addition of updateInternalDeps (https://github.com/renovatebot/renovate/pull/8809) says that

> To opt in to letting Renovate update internal package versions normally, set this configuration option to true.

But it seems the default option is already true, as well as the documentation.

https://docs.renovatebot.com/configuration-options/#updateinternaldeps

**Relevant debug logs**

This isn't really something to do with runtime logs. Documentation and settings are already incorrect compared to the PR and apparent intention.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by viceice** [comment]
A code review shows `updateInternalDeps==undefined` by default, with is `!updateInternalDeps == true`, so they should have `skipReason=InternalPackage` below

https://github.com/renovatebot/renovate/blob/9171e712d483ca20be02e499510a920cb1dcce5a/lib/manager/npm/extract/monorepo.ts#L51-L57

https://github.com/renovatebot/renovate/blob/9171e712d483ca20be02e499510a920cb1dcce5a/lib/manager/npm/extract/monorepo.ts#L66-L72

**Comment by HonkingGoose** [comment]
@viceice Do we know what we need to fix this issue?

I'm labeling it `status:requirements` for now, feel free to update the label if you feel we have what we need to proceed.

**Comment by rarkins** [comment]
At the moment I don't think this is a bug and we are awaiting a reproduction

**Comment by HonkingGoose** [comment]
Oh okay, I'll remove the bug label then. 😄

**Comment by rarkins** [comment]
Sorry, I was able to confirm this. I forgot that our booleans default to `true`.. which was a bad design choice. Now fixed for this option.

**Comment by Hoishin** [comment]
Thanks! I've also confirmed this was fixed in the latest release.
