### ISSUE TITLE
ci: http2-wrapper package complains about nodejs versions we use

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#8870]
**What Renovate type, platform and version are you using?**

Not relevant, problem is with repository itself.

**Describe the bug**

Multiple CI runs are failing because of this:

```
error http2-wrapper@1.0.0: The engine "node" is incompatible with this module. Expected version ">=15.10.0". Got "12.20.2"
error Found incompatible module.
```

Our CI uses Node 12 and 14.

Previous builds on `master` were passing just fine, so this problem is really recent.
I've no clue what causes this.

**Relevant debug logs**

See logs, check the `E2E` section/tab:
https://github.com/renovatebot/renovate/pull/8863/checks?check_run_id=1980509025
https://github.com/renovatebot/renovate/runs/1980540091

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

I have linked the logs above to reproduce.

**Additional context**

I've no clue what went wrong, our previous builds were fine, it's only just now breaking...

**Comment by viceice** [comment]
I'm a little confused, because this only happens sometimes 🤔 😕

**Comment by HonkingGoose** [comment]
> 
> 
> I'm a little confused, because this only happens sometimes 🤔 😕

You're right, the tests on a newer PR of mine are passing just fine now...
It sure is confusing! 😄

**Comment by viceice** [comment]
Closing this, as i've don't seen this issue in latest builds
