### ISSUE TITLE
[github-actions] Dependency extraction is to greedy

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#8897]
**What Renovate type, platform and version are you using?**

Hosted app, but doesn't matter. Regression of #8829

**Describe the bug**

Since #8829 renovate supports `jobs.<job_id>.container.image` but the regex is to greedy and also finds `jobs.<job_id>.steps[*].with.image`

https://github.com/renovatebot/renovate/blob/d409618984ceace42a62c3f8655f5d5f94bc2f9b/lib/manager/github-actions/extract.ts#L16

**Relevant debug logs**
not relevant.
See pr renovatebot/internal-tools#203

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by viceice** [comment]
I think we need to use the yaml parser to securely extract relevant deps.

**Comment by rarkins** [comment]
Let's revert - see new PR
