### ISSUE TITLE
Helm values updates are ignored during successive runs when bumpVersion is enabled

### ISSUE THREAD

**Issue by chgl** [renovatebot/renovate#8919]
**What Renovate type, platform and version are you using?**

Renovate GitHub App.

**Describe the bug**

If bumpVersion is enabled and the helm-values manager attempts to update an image version in values.yaml and additionally tries to bump the Chart.yaml when updating a helm chart, there seems to be an ordering issue where sometimes both files are correctly updated and sometimes just the Chart.yaml version bump is applied.

For example, in my helm chart repo there are currently 2 PRs open which update helm-values. Renovate is configured to bumpVersion in the Chart.yaml as well: https://github.com/chgl/charts/pulls.

1. https://github.com/chgl/charts/pull/40/files
    incorrectly just bumps the Chart.yaml:
    
    ![image](https://user-images.githubusercontent.com/5307555/109520485-92282480-7aac-11eb-945a-710f11322f22.png)

1. https://github.com/chgl/charts/pull/45/files
    correctly updates both Chart.yaml and values.yaml:

    ![image](https://user-images.githubusercontent.com/5307555/109520612-b6840100-7aac-11eb-894e-cd482c45dabc.png)

However, I noticed that renovate tries to constantly update both PRs and everytime it does, the "correctness" of the PR is swapped, ie. the next time renovate will run, https://github.com/chgl/charts/pull/40 will be corrected to update both files and https://github.com/chgl/charts/pull/45 will only update the Chart.yaml ( - which just happened as I was typing).

Note that this is definitely a result of something I messed up in https://github.com/renovatebot/renovate/pull/8240. We could revert https://github.com/renovatebot/renovate/commit/662a60a87e36a92138a98fadddf4235deb03e75b for now to fix it. I can't quite figure out what I did wrong, but at least I can reproduce it to some extent.

**Relevant debug logs**

[renovate-logs-310092033.txt](https://github.com/renovatebot/renovate/files/6062764/renovate-logs-310092033.txt)

**Have you created a minimal reproduction repository?**

In https://github.com/chgl/charts/pulls the two PRs 40 and 45 flip-flop between being correctly updated and missing the values.yaml update.

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I think it's something I didn't consider in https://github.com/renovatebot/renovate/blob/98d55394e64eed2bc4ae5b9efe76e636ae01c48d/lib/workers/branch/get-updated.ts#L118 when updating values.yaml. If it runs correctly, the logs show "Contents updated" for the values.yaml file.

**Comment by rarkins** [comment]
I'm reverting it in PR #8926 as I can't work out what could be causing this behavior. Can you resubmit the feature with fix in a new PR if/once you work it out?

**Comment by chgl** [comment]
I will! Thank you!

**Comment by Ornias1993** [comment]
@chgl Nice work on the issue report, looking forward to your renewed PR!

**Comment by viceice** [comment]
closing this in favor of #8231
