### ISSUE TITLE
Post upgrade task failure causes Renovate failure

### ISSUE THREAD

**Issue by fgreinacher** [renovatebot/renovate#8922]
**What Renovate type, platform and version are you using?**

Self-hosted GitLab

**Describe the bug**

Renovate exits with an error code when a postUpgradeTask fails. I'd expect this to be reflected in the MR instead. 

**Relevant debug logs**

```text
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "NS6DefVh_",
           "repository": "fgreinacher/renovate-post-upgrade-task-error",
           "branch": "renovate/docker-renovate-renovate-24.x",
           "dep": "renovate/renovate",
           "err": {
             "killed": false,
             "code": 1,
             "signal": null,
             "cmd": "echo 'Failing' && false",
             "stdout": "Failing\n",
             "stderr": "",
             "message": "Command failed: echo 'Failing' && false\n",
             "stack": "Error: Command failed: echo 'Failing' && false\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:315:20)\n    at ChildProcess.EventEmitter.emit (domain.js:467:12)\n    at maybeClose (internal/child_process.js:1048:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"
           },
           "msg": "Error updating branch: Command failed: echo 'Failing' && false\n"
         }
       ]
```

See https://gitlab.com/fgreinacher/renovate-post-upgrade-task-error/-/jobs/1064173334 for the full output. 

**Have you created a minimal reproduction repository?**

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository: https://gitlab.com/fgreinacher/renovate-post-upgrade-task-error/-/tree/master
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Comment by rarkins** [comment]
Duplicate of #8856 ? Can you add the reproduction there if so?

Also to clarify: it doesn't cause Renovate to *exit* immediately, but it does cause Renovate to exit with a non-zero exit code ("fail") once it's *finished?

**Comment by fgreinacher** [comment]
> Duplicate of #8856 ? Can you add the reproduction there if so?
> 
> Also to clarify: it doesn't cause Renovate to _exit_ immediately, but it does cause Renovate to exit with a non-zero exit code ("fail") once it's *finished?

Yes, same issue. I added my repro there!
