### ISSUE TITLE
chore: replace `status:` label from issue with `status:in-progress` once targeted with PR

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#8965]
**What would you like Renovate to be able to do?**

Issues get labeled `status:requirements` and `status:ready` on a consistent basis, which is good.
We are nowhere near as consistent with applying the `status:in-progress` label for things that are in progress.

I see issues targeted with a PR still say: `status:requirements` or `status:ready`, while they should be `status:in-progress`.. 😄 

**Did you already have any implementation ideas?**

Find a way to automate replacing the `status:ready` and `status:requirements` labels with `status:in-progress` when a PR targets the issue for closure. If the issue gets targeted with a PR, that's a definite sign that somebody is working on implementation.

**Comment by rarkins** [comment]
On PR open or PR body update we should:

- Check the PR body for any instances of the following syntax: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
- If found, ensure the issue(s) have `status:requirements` if they are open

FYI I checked GitHub's GraphQL scheme for `PullRequest` and it doesn't appear to have any way to query a PR to find the list of associated issues it resolves, so therefore I suggest doing the query ourselves

**Comment by HonkingGoose** [comment]
> * If found, ensure the issue(s) have `status:requirements` if they are open

Don't we miss the `status:ready` labels then?
How about this:

* If found, ensure the issue(s) have `status:requirements` OR `status:ready` if they are open

**Comment by rarkins** [comment]
Sorry, that was a typo. I have fixed it to `status:in-progress`
