### ISSUE TITLE
Support a git-submodule using a non-standard port

### ISSUE THREAD

**Issue by jjathman** [renovatebot/renovate#8986]
**What would you like Renovate to be able to do?**

This is related to the discussion here: https://github.com/renovatebot/renovate/discussions/8529. We have a Git submodule which is accessed over ssh on the non-standard port of 7999. When the Renovate `git-submodule` adjusts the URL from the submodule from `ssh` to `https` it still uses the existing non-standard port of 7999. I would like Renovate to be able to use a different port.

**Did you already have any implementation ideas?**

Being able to specify the port in `hostRules` would work, but that object does not support a port from what I can tell. All we really want is for renovate to just use the Bitbucket connection that we define as the `endpoint` in our self-hosted configuration.

**Comment by rarkins** [comment]
Is this submodule needed for the purpose of *updating* it (using the git submodules manager in Renovate) or because the files in it are needed for other dependency updates?

e.g. would skipping git submodule initialization work as an alternative?

**Comment by jjathman** [comment]
Yes in this case skipping the submodule completely would also work which I think is already an issue? https://github.com/renovatebot/renovate/issues/8936 seems to cover that case. That was the original thing I attempted to do but it didn't work how I expected. Is there a way to globally disable cloning of submodules? I didn't see anything [here](https://docs.renovatebot.com/self-hosted-configuration/) that looked like it was possible.

**Comment by rarkins** [comment]
Are you self-hosted though? I assumed from the ports you may be running Bitbucket. Self-hosted submodule disablement should work if you put it in the bot's config.js or env

**Comment by jjathman** [comment]
Yes, we are running self-hosted. Do you mean put `cloneSubmodules: false` in to the bot's configuration?

**Comment by jjathman** [comment]
@rarkins that seemed to work! I don't think I ever realized that the self-hosted configuration options allowed for putting all the regular configuration options at that level. Very helpful, thank you!

**Comment by rarkins** [comment]
Yes, either that or `RENOVATE_CLONE_SUBMODULES=false` in env. The problem in that issue is that the decision whether to clone submodules is taken before the repo config is read. But if the value is added to bot config it should function as intended
