### ISSUE TITLE
Use configured GitlabToken for Docker datasource authorization 

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#8987]
**What would you like Renovate to be able to do?**
We are using a self hosted instance of Gitlab and Renovate.     
The docker registry provided by Gitlab is served under another domain ( e.g. gitlab.example.com vs registry.example.com )   
Because the registry is served by Gitlab, the Gitlab token configured by `gitlab_api_token` should be reused for authentication.    

**Did you already have any implementation ideas?**
self hosted configuration: 
``` json
{
  "endpoint": "https://gitlab.example.com/api/v4/",
  "platform": "gitlab",
  "token": "xxxxxxxxx"
}
```

I see to implementation variants:    
1. Implement a separate function in the `docker` data source which tries to authorize against the registry URL with the API token.   This could be optional maybe. 
2. add variable expansion in the host rules to insert the `gitlab_api_token` in the `password` field with:   
  a. From environment variables e.g.: 
``` json
{
  "hostRules": [
    {
      "domainName": "registry.example.com",
      "username": "renovate",
      "password": "${GITLAB_API_TOKEN}"
    }
  ]
}
```
  b. From other configurations e.g. 
``` json
{
  "hostRules": [
    {
      "domainName": "registry.example.com",
      "username": "renovate",
      "password": "{{config.token}}"
    }
  ]
}
```

**Comment by rarkins** [comment]
Can you add `hostRules` using the bot config (e.g. `config.js`) which allows variable substitution? e.g.

```js
module.exports = {
  hostRules: [
    {
      domainName: "registry.example.com",
      username: "renovate",
      password: process.env.GITLAB_API_TOKEN}
    }
  ]
}
```

**Comment by secustor** [comment]
Thx that works!    

But maybe a reuse of other configuration values could be helpful feature. WDYT?

**Comment by viceice** [comment]
@secustor checkout #8070

**Comment by secustor** [comment]
@viceice  yeah that would fit my use case
