### ISSUE TITLE
renovate-config-validator accepts bad supportPolicy strings

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#9005]
**What Renovate type, platform and version are you using?**

I'm "black-box testing" the `renovate-config-validator` where I'm just feeding it bad stuff and seeing if it raises a warning. 😄 

**Describe the bug**

**Steps to reproduce:**

1. Create a `renovate.json` file that looks like this:

```json
{
  "extends": ["config:base"],
  "node": {
    "supportPolicy": ["lts_lates"]
  }
}
```

2. `supportPolicy` has a bad string in it: `lts_lates` is misspelled, it should be `lts_latest`
3. Install `renovate-config-validator` with `npm i -g renovate`.
4. Type in `renovate-config-validator` in your terminal to run the validator.
5. File validates properly:

```
 INFO: Validating renovate.json
 INFO: Config validated successfully
```

**Expected behavior:**

1. Renovate-config-validator checks if the input given to `supportPolicy` matches a array of valid strings.
2. If input for `supportPolicy` is not valid: warn user that they're not using one of the supported strings.
3. Print list of supported strings on the console.

**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I hope I'm doing this right. 😄

**Comment by HonkingGoose** [comment]
Hi @rarkins,

I'm willing to "black-box" test this validator more, and report any bugs or weird stuff that I find.

Do you like this idea or not?
Do you have any suggestions for the process that I should follow (maybe make a separate `renovate-config-black-box` repository with branches for each separate reproduction?)

I will hold off on making more issues until I get a "go / no go" on this idea. 😄 

This is to prevent me from opening issues that you don't care about, and to prevent spamming you with stuff you might label "wont-fix" anyways... 😄

**Comment by rarkins** [comment]
I don't mind having an issue for each of these but they'd mostly be classified as low priority and unlikely to be done unless yourself or someone from the community strongly cares.

**Comment by HonkingGoose** [comment]
I care about the validator being correct, but I'm not able to fix it for you, unfortunately. 😞 So we would be relying on community fixes for this.

I don't think there's much point in me going hunting for bugs that will not get fixed in a reasonable time-frame, as that just clutters up the repository issue list. Developer time is limited, so you must prioritize what to do first, so I'm not mad at you for saying this is "low priority" stuff. 😉

I hope you're happy with my contributions so far, and find them valuable, and I'm not honking at you too much. 😄 
I'll go focus on the docs then, as I think you like those contributions better than this wild-goose bug hunt. 😄 

I'll keep this issue open so that somebody else can take a shot at fixing it. 😄

**Comment by HonkingGoose** [comment]
@rarkins I think this can be labeled status ready if you're happy with this as the end-result?

> * Renovate-config-validator checks if the input given to `supportPolicy` matches a array of valid strings.
> 
> * If input for `supportPolicy` is not valid: warn user that they're not using one of the supported strings.
> 
> * Print list of supported strings on the console.

**Comment by rarkins** [comment]
`supportPolicy` has been removed
