### ISSUE TITLE
Use GitHub environments for releasing

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#9008]
Link: https://docs.github.com/en/actions/reference/environments

@viceice or @JamieMagee do you have your head around these yet? Could we use this to further protect our main branches in repos, including for the secrets we need like the Docker Hub token?

**Comment by viceice** [comment]
I haven't used them yet. But can maybe improve security.

**Comment by rarkins** [comment]
Based on the UI it seems like Organization secrets don't belong to environments and therefore wouldn't be relevant/benefited by such a thing. @JamieMagee can you confirm?

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/110308681-b6ca5200-8000-11eb-9214-318e2300c033.png)

I wonder if the above is needed anymore but worry about the implications if I were to delete it :)

I thought our GH Pages were fully built in github.com/renovatebot/renovatebot.github.io

**Comment by rarkins** [comment]
@JamieMagee I've assigned this one to you as I hope you are best placed to conclude if using environments provides any practical security benefit for our deployment scenario

**Comment by JamieMagee** [comment]
I don't think we're the target audience for environments. They're really designed for end-user applications that go through multiple deployment stages, from staging to production. Our concerns, as an npm library, aren't really the same.

I'd recommend reading [the documentation for the equivalent feature in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops) to get a more in depth understanding.
