### ISSUE TITLE
Newer version of npm being used despite 'engines.npm' constraints

### ISSUE THREAD

**Issue by abernix** [renovatebot/renovate#9036]
**What Renovate type, platform and version are you using?**

Hosted App via GitHub; Renovate (`24.77.0` according to the dashboard)

**Describe the bug**

Despite having `engines.npm` set to a 6.x range within the `package.json`, the renovation is still happening with npm 7.  Here is the output showing that :

From https://github.com/apollographql/apollo-server/pull/4998#issuecomment-792746046:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '>=6 <15', npm: '^6.14.11' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.1' }
npm WARN EBADENGINE }
```

Since I thought that the `npm` value in `engines` was meant to constraint the version that Renovate uses to install, I believe that this output alone seems to frame the problem, but happy to provide more!

**Relevant debug logs**

I'm not seeing anything in the [Dashboard run](https://app.renovatebot.com/dashboard#github/apollographql/apollo-server/313997434) that suggests anything about the Node.js or Npm version that the Renovation itself is choosing (nor any designator about the Docker image), but here is a snippet that demonstrates the `constraints` that are applied to the project:

... A snippet from the `renovate.json5` configuration — note that `npm` is not defined here:

```json
{
  "fileName": "renovate.json5",
  "config": {
    "extends": [
      "apollo-open-source"
    ],
    "force": {
      "constraints": {
        "node": "< 15.0.0"
      }
    },
```

The `constraints` that were taken (and amended with `<7`, it seems, from the `package.json`):
 
```json
        "packageJsonName": "apollo-server-monorepo",
        "packageJsonType": "app",
        "npmLock": "package-lock.json",
        "lernaDir": ".",
        "lernaClient": "npm",
        "lernaPackages": [
          "packages/*"
        ],
        "skipInstalls": false,
        "constraints": {
          "node": ">=6 <15",
          "npm": "^6.14.11 <7"
        },
        "lockFiles": [
          "package-lock.json"
        ]
      },
```

Here is the `package.json` from the project:

https://github.com/apollographql/apollo-server/blob/5f3351d4e62c2e136bf4675e7042154cda8729ad/package.json#L23-L26

**Have you created a minimal reproduction repository?**

- [x] I don't have time for that, but it happens in a public repository I have linked to
- [x] I may have time later, and I'd love to help. 😁 
 
**Additional context**

* https://github.com/renovatebot/renovate/issues/7474#issuecomment-792762416
* https://github.com/renovatebot/renovate/issues/7474#issuecomment-792764401

**Comment by rarkins** [comment]
Which version of `node` was selected for the `docker run`? Can you locate and paste the full command in here?

**Comment by abernix** [comment]
@rarkins I'd looked, but I don't see any output regarding the `docker run` command within the log output on the Renovate Dashboard.  Where should I be looking?

The only reference to `docker` I can find in the output (with browser's Cmd-F) is:

```
DEBUG: Using file match: (^|/)docker-compose[^/]*\.ya?ml$ for manager docker-compose
DEBUG: Using file match: (^|/|\.)Dockerfile$ for manager dockerfile
DEBUG: Using file match: (^|/)Dockerfile\.[^/]*$ for manager dockerfile
``` 

.... which I'm sure is not what you're looking for. 😉

**Comment by rarkins** [comment]
You'll need to make sure you find the job log that matches with the timestamp of the commit which failed. "Docker run" commands aren't repeated every run so that's why you wouldn't see it on other runs

**Comment by rarkins** [comment]
I think this is *caused* by your `force` object, because it overrides the detected `constraints` from `package.json`. I've raised a fix PR here: https://github.com/apollographql/apollo-server/pull/5020

**Comment by abernix** [comment]
Thanks very much, @rarkins.  And thanks for the PR to fix it.
