### ISSUE TITLE
Maven: support for nested placeholders in properties

### ISSUE THREAD

**Issue by dserkowski** [renovatebot/renovate#9043]
**What would you like Renovate to be able to do?**

Before I created this issue, I noticed https://github.com/renovatebot/renovate/issues/3461. However, my case is more complex. I have a project in which I am using properties that nested other properties, i.g.
```
<properties>
    <tomcat.version>8.5.57</tomcat.version>
    <tomcat.artifact.version>${tomcat.version}-atlassian-hosted</tomcat.artifact.version>
<properties>
```
and `<tomcat.artifact.version>` is used as a version of some of my dependencies. After reviewing Renovate logs, I found something like this
```
{"datasource":"maven","depName":"org.apache.tomcat:apache-tomcat","currentValue":"${tomcat.version}-atlassian-hosted","fileReplacePosition":5833,"registryUrls":["https://repo.maven.apache.org/maven2"],"groupName":"tomcat.artifact.version","skipReason":"version-placeholder","editFile":"pom.xml","depIndex":22,"updates":[]}
```
so it seems that Renovate doesn’t process nested properties like this at the moment. Don't know if it is a bug or more of a feature suggestion, but my question is could you add support for this?

**Did you already have any implementation ideas?**

Not really. Hope, that https://github.com/renovatebot/renovate/issues/3461 will be handy

**Comment by dserkowski** [comment]
I prepared an example repo: https://github.com/dserkowski/renovateTest
* configured pom.xml to present the above issue. In this case, Renovate should create PR for [bumping org.apache.struts.struts2-core version](https://github.com/dserkowski/renovateTest/blob/main/pom.xml#L20)
* run on the latest docker image (renovate/renovate:24.86-slim) - [see runRenovate.sh file](https://github.com/dserkowski/renovateTest/blob/main/runRenovate.sh)
* dumped debug logs (I had during last execution) and pushed them to the repo - [nestedPropertyPlaceholder-renovate.log file](https://github.com/dserkowski/renovateTest/blob/main/nestedPropertyPlaceholder-renovate.log)


**Actual:**
* any PR for bumping org.apache.struts.struts2-core version is not created

**Expected**
* PR for bumping org.apache.struts.struts2-core version from 2.5.22-atlassian-1 to 2.5.26-atlassian-2 (currently the latest version) should be created


Insights:
* in logs you can see that the processing is skipped - [LINK](https://github.com/dserkowski/renovateTest/blob/main/nestedPropertyPlaceholder-renovate.log#L293)

**Comment by rarkins** [comment]
Have you confirmed that Renovate happily upgrades from 2.5.22-atlassian-1 to 2.5.26-atlassian-2 when there's *not* any complications like nested placeholders? I would like to rule out that it's anything related to the version suffix changing.

**Comment by dserkowski** [comment]
Yes, after joining those two properties into one, this PR has been created https://github.com/dserkowski/renovateTest/pull/9. 
And as you can see, after applying the current configuration, the PR has been automatically declined by Renovate.

**Comment by falkenbt** [comment]
I have a similar case when using [jib ](https://github.com/GoogleContainerTools/jib) to build container images and I would like to renovate the image version in the pom.xml:  

```xml
  <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                        <version>2.2.0</version>
                            <from>
                                <image>myregistry.com/somepath/openjdk11:11.0.3.7-1
                                </image>
                            </from>
```

**Comment by rarkins** [comment]
@falkenbt not the same thing, please create a discussion so we can assess if it's solvable in config or needs a new feature
