### ISSUE TITLE
Support for npm flag --legacy-peer-deps

### ISSUE THREAD

**Issue by EllieMaeUI** [renovatebot/renovate#9090]
**What would you like Renovate to be able to do?**

With npm 7 there is a breaking change that ensures whether package.json satisfies all peer dependency constraints. in npm 6 it was a warning rather an error. Currently there is not an option to pass the --legacy-peer-deps npm install flag to renovate and let it use the flag in post update lifecycle
https://github.com/renovatebot/renovate/blob/master/lib/manager/npm/post-update/npm.ts#L57

**Did you already have any implementation ideas?**

environment flag or configuration option to enable this and read those values in https://github.com/renovatebot/renovate/blob/master/lib/manager/npm/post-update/npm.ts#L57 and apply the flag

**Comment by rarkins** [comment]
Can't you put it on an npmrc which you commit to the repo?

**Comment by EllieMaeUI** [comment]
@rarkins that works. thanks for the suggestion. we can close this feature request
