### ISSUE TITLE
replace null/false/true with auto/disabled/enabled respectively

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#9100]
**What would you like Renovate to be able to do?**

Quote from @rarkins while reviewing (https://github.com/renovatebot/renovate/pull/9082#pullrequestreview-610615109), emphasis mine:

> This seems to be a recurring challenge with config which is user-derived. Although internally we should assume such fields are mandatory, they originate as optional in user config prior to us massaging to defaults if empty. But we also have the complication where users _can_ configure `null` and override a non-null default. **I wonder if we could remove `null` as a valid value in options, e.g. like we did some times by changing null/false/true to be auto/disabled/enabled.**

I think that having `null` mean many different things is a recipe for confusion. The fact that you can apparently use `null` to override a value that was `non-null` makes no sense to me.

I like the idea to replace `null` with `auto`, as that infers that Renovate bot will use a sensible default value for that option, and overriding it with `disabled` or `enabled` makes semantic sense as an obvious "toggle" to change the behavior.

Table of suggested replacements:

| Old term | New terms |
| --- | --- |
| `null` | `auto` |
| `false` | `disabled` |
| `true` | `enabled` |

**Did you already have any implementation ideas?**

I think this is going to be more difficult than just doing a find/replace on the old terms in the code and docs... 😄

**Comment by rarkins** [comment]
Thanks! Can you check out existing definitions file for how many Boolean options default to null?

Once we address those we can move on to non-Boolean fields like strings to consider how to handle null

**Comment by HonkingGoose** [comment]
> Thanks! Can you check out existing definitions file for how many Boolean options default to null?

I think you want me to trawl through this file? https://github.com/renovatebot/renovate/blob/master/lib/config/definitions.ts
Just checking before I start work, as it's no good to work on the wrong file. 🙃 

How detailed do you want me to be? Do you just want a generic list of: `<number> of Boolean options that default to null` or do you want more information in a table format or something?

**Comment by viceice** [comment]
I think a table would be great 🙃

**Comment by HonkingGoose** [comment]
@viceice What information should the table display then? 🙃 Can you make a mock-up of the fields you care about?

**Comment by rarkins** [comment]
List is fine I think. Not sure what other info needed?

**Comment by HonkingGoose** [comment]
## List of Boolean options that default to `null`

Sourced from `lib/config/definitions.ts` from `master` branch.

### Explictly lists `null` as the `default:` value:

| Name           | Default |
| -------------- | ------- |
| `skipInstalls` | `null`  |

## List of Boolean options missing a explicit `default:` value:

Name:

- `enabled`
- `onboarding`
- `updateNotScheduled`
- `updateLockFiles`
- `separateMajorMinor`
- `ignoreUnstable`
- `respectLatest`
- `insecureRegistry`

**Comment by HonkingGoose** [comment]
@rarkins @viceice Was this list what you had in mind to start with?

**Comment by HonkingGoose** [comment]
## I think I'm done for now

> Thanks! Can you check out existing definitions file for how many Boolean options default to null?
> 
> Once we address those we can move on to non-Boolean fields like strings to consider how to handle null

I have done the top part of the quote (check out existing definitions file), and have removed my assignment from this issue, so that somebody else can do the necessary refactoring in the code.

## But ping me again for the second part

> [later] we can move on to non-Boolean fields like strings to consider how to handle null

Ping me once the code is in the proper state for me create a list for that part.

**Comment by HonkingGoose** [comment]
Well I managed to create a duplicate here... 🙈 

See: https://github.com/renovatebot/renovate/issues/4890

I'll let @rarkins decide what to keep/merge/close. 😉

**Comment by rarkins** [comment]
`skipInstalls` is the only one remaining - and it's a special case
