### ISSUE TITLE
refactor extractPackageFile to use js-yaml

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#9115]
**What would you like Renovate to be able to do?**

From @viceice:

> @HonkingGoose Please open a new issue:

> Refactor `extractPackageFile` to use `js-yaml` and reuse already parsed object from `extractAllPackageFiles`.
> So we should extract a new function `parseDoc` to be reused by both extract functions.

**Did you already have any implementation ideas?**

~If we're going to be using `js-yaml` here, might be a good idea to migrate from `js-yaml` v3 to v4 first (see issue #8234)?~ That way you're doing the refactoring on top of up-to-date packages.

**Comment by HonkingGoose** [comment]
I'll label this `status:blocked` until we've updated to `js-yaml` version 4. I think it makes more sense to update our version first, then refactor the code.

**Comment by HonkingGoose** [comment]
The Renovate code wizards can do the refactoring now, as we have updated `js-yaml` to version 4.

**Comment by viceice** [comment]
@HonkingGoose do you remember to which manager this is applying? 🤔

**Comment by HonkingGoose** [comment]
I think you meant for this to apply to `lib/manager/gitlabci/extract.ts`, at least that's where you put the original comment: https://github.com/renovatebot/renovate/pull/8810#discussion_r593723535
