### ISSUE TITLE
Allow to autoassign config issues

### ISSUE THREAD

**Issue by Stefan-J-Hanke** [renovatebot/renovate#9134]
**What would you like Renovate to be able to do?**

We are not _really_ using Issues in GitLab, so I was unaware of a config error that I did make. It surfaced as GitLab issue and I just recently found out...

**Did you already have any implementation ideas?**

Add a config option, at the point of creating the config issue, assign it. For consistency reasons, I'd prefer something akin to the _assigneesFromCodeOwners_ option, however I'd like to also just assign it to a specific person.

----

If accepted, this could be a smallish PR. Happy to help out.

**Comment by fgreinacher** [comment]
Duplicate of https://github.com/renovatebot/renovate/issues/8359?

**Comment by viceice** [comment]
Duplicate of #8359
