### ISSUE TITLE
Renovate getting the wrong latest tag with the docker datasource

### ISSUE THREAD

**Issue by eyalzek** [renovatebot/renovate#9157]
**What Renovate type, platform and version are you using?**

hosted app on Github

**Describe the bug**

renovate uses the wrong tag in the `getLabels` request for the image: `quay.io/bitnami/sealed-secrets-controller`.

**Relevant debug logs**

```
DEBUG: getLabels(https://quay.io, bitnami/sealed-secrets-controller, build-683905581-683905588-linux-arm) (repository=eyalzek/renovate-test)
```

**Have you created a minimal reproduction repository?**

reproduction is done here (the relevant image is `quay.io/bitnami/sealed-secrets-controller`) https://github.com/eyalzek/renovate-test

**Additional context**

it's hard to test this, but I assume the problem is with the following line:
https://github.com/renovatebot/renovate/blob/f8580a1d936eab95f0bf663147c90de28045b373/lib/datasource/docker/index.ts#L640

because the registry for this image does actually include a `latest` - although it's out of date, it still gets the last element from the `tags` array. Though I have no idea why the last element comes out to be `build-683905581-683905588-linux-arm`, browsing through the registry it seems like tags are ordered properly (https://quay.io/repository/bitnami/sealed-secrets-controller?tab=tags).

**Comment by rarkins** [comment]
The reproduction repository seems different from the description here. Can you please double check and clarify?

**Comment by eyalzek** [comment]
> The reproduction repository seems different from the description here. Can you please double check and clarify?

It's not, it just had some additional stuff in there. I cleaned it up so it's more obvious.
