### ISSUE TITLE
Gradle kotlin 3 argument notation dependency is not updated

### ISSUE THREAD

**Issue by twarner-sofi** [renovatebot/renovate#9164]
**What Renovate type, platform and version are you using?**

Self hosted v24.83.0, pointed at gitlab.com

Gradle 6.8.3

**Describe the bug**

When using Gradle kotlin build scripts, dependencies using the three argument notation (looks like `implementation("group", "name", "version")` are not updated, even though they are detected and listed in the MR description. If no other dependencies updates are detected, no MR is even made.

Note: Using the single argument compact notation works as expected. 

**Relevant debug logs**

```
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:settings.gradle.kts depName:com.fasterxml.jackson.core:jackson-databind, version:2.10.5 ==> 2.12.2 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:gradle.properties depName:com.fasterxml.jackson.core:jackson-databind, version:2.10.5 ==> 2.12.2 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:build.gradle.kts depName:com.fasterxml.jackson.core:jackson-databind, version:2.10.5 ==> 2.12.2 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:settings.gradle.kts depName:io.jsonwebtoken:jjwt-api, version:0.11.0 ==> 0.11.2 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:gradle.properties depName:io.jsonwebtoken:jjwt-api, version:0.11.0 ==> 0.11.2 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:build.gradle.kts depName:io.jsonwebtoken:jjwt-api, version:0.11.0 ==> 0.11.2 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:settings.gradle.kts depName:org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, version:1.4.20 ==> 1.4.31 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:gradle.properties depName:org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, version:1.4.20 ==> 1.4.31 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:build.gradle.kts depName:org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin, version:1.4.20 ==> 1.4.31 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:settings.gradle.kts depName:org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, version:1.4.20 ==> 1.4.31 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:gradle.properties depName:org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, version:1.4.20 ==> 1.4.31 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: gradle.updateDependency(): packageFile:build.gradle.kts depName:org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable, version:1.4.20 ==> 1.4.31 (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: No package files need updating (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: No updated lock files in branch (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
renovate-local    | DEBUG: No files to commit (repository=twarner-sofi/renovate-bug-repro, branch=renovate/all)
```

**Have you created a minimal reproduction repository?**

https://gitlab.com/twarner-sofi/renovate-bug-repro

self-hosted config (minus tokens, endpoints and stuff):

    groupName: "all",
    prHourlyLimit: 0

Running renovate on the above detects dependencies to be updated but does not actually update them in the files, this commits nothing and makes no MR.

**Additional context**

Most likely just a missed notation when parsing the file.

**Comment by rarkins** [comment]
Could you try out our new `gradle-lite` manager to see if it handles your use case? It's based on JS parsing and updating instead of using `gradle` directly.

Change your config to:

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:base",
    ":switchToGradleLite"
  ]
}

```

**Comment by twarner-sofi** [comment]
Switching to gradle-lite fixed this particular issue, but I ran into other issues when trying on a larger project:

- Could not use custom repositories to find new versions of internal libraries.
- Could not update dependencies using the notation `api("com.fasterxml.jackson.core:jackson-databind:${property("jacksonVersion")}")`
- Did not respect packageRules excluding certain dependencies from major version upgrades.
- Seemed to disregard grouping with `groupName: "all"` (made separate branches) but only for a few dependencies.

On the plus side it was very fast!

I can make minimal repros and individual issues for each of these if you would like.

**Comment by rarkins** [comment]
Yes, minimal reproductions for each separately would be perfect. Cc @zharinov

**Comment by HonkingGoose** [comment]
> Switching to gradle-lite fixed this particular issue,

Closing this specific issue, as it was fixed by using `gradle-lite`.

For the other issues you listed:

> * Could not use custom repositories to find new versions of internal libraries.
> 
> * Could not update dependencies using the notation `api("com.fasterxml.jackson.core:jackson-databind:${property("jacksonVersion")}")`
> 
> * Did not respect packageRules excluding certain dependencies from major version upgrades.
> 
> * Seemed to disregard grouping with `groupName: "all"` (made separate branches) but only for a few dependencies.

We would very much like separate issues and reproductions. 😉 
Thanks for helping out! 🚀
