### ISSUE TITLE
Improve documentation for using renovate GitHub Plugin with private maven repositories

### ISSUE THREAD

**Issue by ahoeing** [renovatebot/renovate#9200]
**What would you like Renovate to be able to do?**

I read that renovate is able to scan private repositories. But I have not found any documentation about how to configure the credentials in GitHub.  All I found was: https://docs.renovatebot.com/java/

Maybe you can Improve the documentation or maybe it is not possible for the GitHub plugin?

**Comment by HonkingGoose** [comment]
> I read that renovate is able to scan private repositories.

Renovate can scan private repositories just fine if you're using the GitHub hosted app, see: https://docs.renovatebot.com/install-github-app/

How are you using Renovate bot right now?

---

I'm moving this to the discussion tab, as it seems more of configuration help problem than a problem with the current docs.
