### ISSUE TITLE
docs: explain better how to lookup private Maven repositories

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#9205]
**What would you like Renovate to be able to do?**

A Renovate user was missing proper documentation on how to configure Renovate bot to fetch results from a private Maven repository (#9200).

The user looked in https://docs.renovatebot.com/java/ for help, but did not get what they needed out of that.

**Did you already have any implementation ideas?**

@rarkins mentioned the solution:

> You still need `hostRules` but you can add them to `renovate.json` instead in JSON format, using `encrypted`. Here's a similar older question I found: [renovatebot/config-help#426](https://github.com/renovatebot/config-help/issues/426).

I don't know enough to know if that solution is general enough to put in the docs, or if we need to adjust it somehow.

**Comment by rarkins** [comment]
Can you assess how feasible it would be to make the current private modules doc generic instead of npm-specific, or if we should create a new doc which is generic?

**Comment by HonkingGoose** [comment]
I notice I'm already trying to update the current private modules doc (see PR #8906) so might want to take a look at that and get that merged before I start on another branch... 😄

**Comment by HonkingGoose** [comment]
> Can you assess how feasible it would be to make the current private modules doc generic instead of npm-specific, or if we should create a new doc which is generic?

We now have a generic private modules doc (See https://github.com/renovatebot/renovate/blob/main/docs/usage/private-modules.md), but it only mentions `maven` once:

> `hostType` is not particularly important at this step unless you have different credentials for the same host, however it is sometimes useful in later steps so is good to include if you can.
It can be either a "platform" name (e.g. `github`, `azure`, etc) or a "datasource" name (e.g. `npm`, `maven`, `github-tags`, etc).

I don't know enough about this whole private-modules-thing to assess if the current docs help a Maven user configure the bot properly...

**Comment by rarkins** [comment]
The current generic documentation is sufficient
