### ISSUE TITLE
Regression in 24.89.2

### ISSUE THREAD

**Issue by bytestream** [renovatebot/renovate#9244]
**What Renovate type, platform and version are you using?**

GitLab self-hosted

**Describe the bug**

See https://github.com/renovatebot/renovate/pull/9211#issuecomment-803646077

**Relevant debug logs**

See above

**Have you created a minimal reproduction repository?**

* Version 24.91.2 - `npm install` fails and comment is added to MR
  https://gitlab.com/bytestream/renovate-bot/-/jobs/1117160215
* Version 24.89.1 - `npm install` works and comment is removed
  https://gitlab.com/bytestream/renovate-bot/-/jobs/1117173042

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
Where is the `.npmrc` coming from? i.e. the one referred to by `Error: Failed to replace env in config: ${GITLAB_TOKEN}`.

e.g. is it a `.npmrc` that's mounted into the home directory of the GitLab runner? I don't see it in the repository.

**Comment by bytestream** [comment]
It's in the repository that renovate is running on: https://gitlab.com/bytestream/renovate-npm/-/blob/master/.npmrc

**Comment by rarkins** [comment]
I think it's possible that prior, Renovate used to *delete* that `.npmrc` file temporarily before running `npm install`. Would that have still worked?

**Comment by bytestream** [comment]
Yes I think so too. I run `npm config` before running renovate which at the moment does the same thing as the `.npmrc` file, so I guess that's why it still works in `v24.89.1`

The `.npmrc` file is there to ease setup in the repository, and the environment variable replacement is a documented npm feature.  https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file

**Comment by rarkins** [comment]
If you are the owner of both the bot and the repos then setting `trustLevel=high` in config.js will mean that environment variables are used in `.npmrc` files.

**Comment by rarkins** [comment]
You can also manually configure using `customEnvVariables`, e.g. 

```
  customEnvVariables: {
    GITLAB_TOKEN: process.env.GITLAB_TOKEN
  }
```

**Comment by bytestream** [comment]
It looks like `customEnvVariables` has done the trick; I'll continue to monitor. Thanks very much @rarkins
