### ISSUE TITLE
Add a way to disable auto rebase for a specific PR

### ISSUE THREAD

**Issue by holc-tkomp** [renovatebot/renovate#9246]
Basically #4766, we're using Github though.

**What would you like Renovate to be able to do?**

I'd like to be able to temporarily disable auto-rebase functionality for specific PRs.

Long story short: We're currently having an issue with our pipeline, which causes the tests to fail. The more agents/jobs are ran in quick succession, the higher is the chance for more of them to fail. Running them (renovate PRs) one by one has much higher success rate, so it would be nice to be able to temporarily disable renovate's autorebase, so we can just trigger them one by one manually. We could just set the `"rebaseWhen"` to `never`, but I'm hoping that the issue in our pipeline is just temporary, so setting it on per-PR basis would be more convenient (and more foolproof, as we wouldn't need to remember to revert that later on).

**Did you already have any implementation ideas?**

Maybe `disable-auto-rebase` label, which would override the global `"rebaseWhen"` (set it to `never` for given PR)?

\+ (from #4766):
> Maybe add another checkbox to the GitLab Merge Requests. Something like:
> 
> [ ] If you want to rebase/retry this MR, check this box
> [ ] If you want to disable automatic rebasing for this MR, check this box

**Comment by viceice** [comment]
Are those pr's automerge enabled? normally renovate only rebase if required, when `rebaseWhen=auto`

**Comment by holc-tkomp** [comment]
> Are those pr's automerge enabled? normally renovate only rebase if required, when `rebaseWhen=auto`

Yes, automerge is enabled.

**Comment by holc-tkomp** [comment]
For example, lets say we have 5 renovates pending, which failed for one reason or another.

- One is re-runned (re-running tests manually), then merged once it's green.
- The 4 left are then automatically rebased and I already know that they'll (the tests) mostly fail due to issue on our pipeline (thus would prefer to prevent them from auto-rebasing, so I can trigger the rebase manually).

**Comment by viceice** [comment]
So there is no option for this. I thought already about something like a `concurrentAutomergePrLimit` but not had the time to do so. That would maybe help here. Maybe another option is to limit your pipeline concurrency.

**Comment by rarkins** [comment]
If you add a commit - including any empty one - on top of a PR then it will disable rebasing

**Comment by holc-tkomp** [comment]
`concurrentAutomergePrLimit` doesn't sound like it would help here, more like `concurrentAutorebasePrLimit` 😛.

I created this as a feature request as from what I searched there was nothing like this available (as you just said). Maybe if we get more people interested in this we could get it done. I'll maybe look into some renovate's code, but given that I haven't yet and I've been using it for not even yet 2 months, I don't expect much from this.

**Comment by holc-tkomp** [comment]
> If you add a commit - including any empty one - on top of a PR then it will disable rebasing

Yeah, but that's more of a workaround and also not a pretty one 😕.

**Comment by viceice** [comment]
another workaround is to close them temporary

**Comment by buffcode** [comment]
@holc-tkomp 
> I created this as a feature request as from what I searched there was nothing like this available

Can you link the issue? I am looking for something like this as well.
Renovate has ~50 open PR which are configured to automerge. The tests fail and will require developer attention.
When a new MR is created and merged, the others are behind and get rebased, resulting in 40+ Pipelines getting started that will of course still fail, so there is no need in auto-rebasing here.

This is a major bummer for us as it is burning CI minutes rapidly.

**Comment by holc-tkomp** [comment]
> @holc-tkomp
> 
> > I created this as a feature request as from what I searched there was nothing like this available
> 
> Can you link the issue? I am looking for something like this as well.

**This IS** the feature request 😏.

**Comment by rarkins** [comment]
Closing in favor of #20940
