### ISSUE TITLE
bumpVersion for maven package manager

### ISSUE THREAD

**Issue by pellmont** [renovatebot/renovate#9257]
**What would you like Renovate to be able to do?**
We would like to do version bumps based on maven dependency updates.
Use case is for example if you repackage or reassemble an external library you would want to reflect the semantic version behavior of your dependency

**Did you already have any implementation ideas?**
no

**Comment by HonkingGoose** [comment]
@rarkins @viceice Is the feature description clear enough for you guys? I think it's a little light on information on why this is a good thing, but maybe it's clear for you.

Also can you tag this issue with the `priority` label that you like, I don't know if you want this or not. 😉

**Comment by rarkins** [comment]
Let's start with a reproduction repo with example PR to identify exactly what else should be updated.

**Comment by kajstrom** [comment]
@rarkins @HonkingGoose This issue can be closed as #14201 has been merged

**Comment by HonkingGoose** [comment]
This feature is available in Renovate version [`31.86.0`](https://github.com/renovatebot/renovate/releases/tag/31.86.0).
