### ISSUE TITLE
Post-upgrade modifications can be dropped

### ISSUE THREAD

**Issue by croachrose** [renovatebot/renovate#9271]
**What Renovate type, platform and version are you using?**

v24.17.2
self-hosted renovate in GitHub actions

**Describe the bug**

1. Use go vendor to upgrade a go dependency and copy to `vendor/`
2. `go vendor` deletes all BUILD.bazel files from `vendor/`
3. Our post-upgrade script regenerates build files
4. renovate ignores the undeleted files because they are now identical in content to how they were before the upgrade

This same thing happens if the script unmodifies a file from the upgrade

**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I have a fork with a fix and test https://github.com/renovatebot/renovate/compare/master...evenco:patrick/reset-artifacts

**Comment by HonkingGoose** [comment]
@croachrose Can you try a newer version of Renovate? Your version (24.17.2) is from 14 January 2021. Maybe the problem is fixed already in the latest release.

- Please copy and paste your logs (remove private stuff!), as we have no output from the logs to help us debug the problem. 
- Please tick the relevant box in the "Have you created a minimal reproduction repository?"

**Comment by croachrose** [comment]
@HonkingGoose I have reproduced the issue on master

Here is a fix and test https://github.com/renovatebot/renovate/compare/master...evenco:patrick/reset-artifacts

**Comment by HonkingGoose** [comment]
@rarkins Can you take a look at the fix and test that the original poster provided, and tell us what you need/want next?

1. Pull request with fix and test.
1. Reproduction repository.
1. Retry with newer Renovate version.

**Comment by rarkins** [comment]
I'm not certain that the suggested fix is safe enough not to cause problems with other use cases. It needs a reproduction to start with.

**Comment by croachrose** [comment]
@rarkins ok, I'll work on a minimal reproduction

**Comment by croachrose** [comment]
https://github.com/croachrose/renovate9271

This repo has an outdated aws-sdk-go module. I have a post-upgrade task that runs `git checkout .` which should undo the `go.mod`, `go.sum`, and any `vendor/` updates. Renovate does not detect that those files have been unmodified and keeps the results of `go mod vendor`.

**Comment by rarkins** [comment]
Unfortunately we don't support post-update tasks manipulating `git` commands, so anything related to that is unsupported. Can you reproduce the problem in any other way?

**Comment by croachrose** [comment]
@rarkins this was the easiest way to reproduce the issue. Our codebase doesn't issue git commands either but it does restore files. I'll try to update the repo.

**Comment by croachrose** [comment]
Ok, I updated it to not use git commands to do the same thing.

**Comment by rarkins** [comment]
I don't think this reproduces.  See https://github.com/renovate-tests/renovate9271/pull/1/files after I changed the command to echo a string instead of touch.

Notably:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/6311784/114202173-38423680-9957-11eb-96b0-6da11310ba1f.png">

i.e. this shows the the BUILD.bazel *is* added back

**Comment by croachrose** [comment]
@rarkins that is because you changed the contents. The original file is blank.

**Comment by rarkins** [comment]
In your real use case, the file is not blank, right? Let's not use blank files in the reproduction unless the bug is specifically about blank files, in case they cause some other undesired problem.

I updated my fork to have `abc123` in the `BUILD.bazel` and then echo the same thing. Now I'm seeing:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/6311784/114203028-11d0cb00-9958-11eb-8464-85af999e1e51.png">

Not sure if that's a line return change or reproducing the bug? Renovate is definitely not "ignoring" it now.

**Comment by rarkins** [comment]
Here is the log, for record:

```
DEBUG: Updated 1 package files (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
DEBUG: Updated 5 lock files (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "updatedArtifacts": [
         "go.sum",
         "vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go",
         "vendor/github.com/aws/aws-sdk-go/aws/version.go",
         "vendor/modules.txt",
         "vendor/BUILD.bazel (delete)"
       ]
DEBUG: Executing post-upgrade task (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "cmd": "echo 'abc123' > vendor/BUILD.bazel"
DEBUG: Executing command (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "command": "echo 'abc123' > vendor/BUILD.bazel"
DEBUG: exec completed (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "cmd": "echo 'abc123' > vendor/BUILD.bazel",
       "durationMs": 9,
       "stdout": "",
       "stderr": ""
DEBUG: Executed post-upgrade task (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "cmd": "echo 'abc123' > vendor/BUILD.bazel",
       "stdout": "",
       "stderr": ""
DEBUG: Post-upgrade file saved (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "go.mod",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "go.sum",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "vendor/BUILD.bazel",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "vendor/github.com/aws/aws-sdk-go/aws/version.go",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=renovate-tests/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "vendor/modules.txt",
       "pattern": "**/*"
```

**Comment by croachrose** [comment]
@rarkins I updated the repo to have the original contents be `abc123` and the update command echos that back. The PR now shows the file as deleted (since the post-upgrade command restores the original contents).

**Comment by croachrose** [comment]
The log:
```
DEBUG: Updated 1 package files (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
DEBUG: Updated 5 lock files (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "updatedArtifacts": [
         "go.sum",
         "vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go",
         "vendor/github.com/aws/aws-sdk-go/aws/version.go",
         "vendor/modules.txt",
         "vendor/BUILD.bazel (delete)"
       ]
DEBUG: Executing post-upgrade task (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "cmd": "echo abc123 > vendor/BUILD.bazel"
DEBUG: Executing command (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "command": "echo abc123 > vendor/BUILD.bazel"
DEBUG: exec completed (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "cmd": "echo abc123 > vendor/BUILD.bazel",
       "durationMs": 9,
       "stdout": "",
       "stderr": ""
DEBUG: Executed post-upgrade task (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "cmd": "echo abc123 > vendor/BUILD.bazel",
       "stdout": "",
       "stderr": ""
DEBUG: Post-upgrade file saved (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "go.mod",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "go.sum",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "vendor/github.com/aws/aws-sdk-go/aws/version.go",
       "pattern": "**/*"
DEBUG: Post-upgrade file saved (repository=croachrose/renovate9271, branch=renovate/github.com-aws-aws-sdk-go-1.x)
       "dep": "github.com/aws/aws-sdk-go",
       "file": "vendor/modules.txt",
       "pattern": "**/*"
```

**Comment by rarkins** [comment]
So I think we need to do this?

- For the added/modified/deleted file lists 
- compare them against the post-upgrade fileFilters
- If they are missing from the latest "git status" (indicating that their contents are now restored to be the same), then remove them from the updated file list

**Comment by croachrose** [comment]
Agreed. I think my change was more aggro in that is just wiped the original list and added from `git status`. Is it not safe/correct to just re-import the info from `git status`?

**Comment by rarkins** [comment]
In theory the current controls allow you to change/ignore a different set of files to what the original update changes. Replacing the whole list would not be backwards compatible for some edge cases
