### ISSUE TITLE
Dependency Dashboard shows everything as "awaiting schedule" rather than "open" when updateNotScheduled is false

### ISSUE THREAD

**Issue by anomiex** [renovatebot/renovate#9275]
**What Renovate type, platform and version are you using?**

Hosted app. Github.

**Describe the bug**

https://github.com/Automattic/jetpack/issues/19284 shows everything under "Awaiting Schedule". I'd expect the ones that have an open PR to be listed under "Open" instead.

PRs only show up under "Open" when I check the checkbox to ignore the schedule, then the next run will move them to "Open". And then they'll move back to "Awaiting Schedule" again on the next run.

**Relevant debug logs**

Here's an excerpt from https://app.renovatebot.com/dashboard#github/Automattic/jetpack/323280505
```
DEBUG: processBranch with 58 upgrades(branch="renovate/pin-dependencies")
DEBUG: Setting current branch to master(branch="renovate/pin-dependencies")
DEBUG: latest commit(branch="renovate/pin-dependencies")
{
  "branchName": "master",
  "latestCommitDate": "2021-03-24T15:34:38-04:00"
}
DEBUG: getBranchPr(renovate/pin-dependencies)(branch="renovate/pin-dependencies")
DEBUG: findPr(renovate/pin-dependencies, undefined, open)(branch="renovate/pin-dependencies")
DEBUG: Found PR #19291(branch="renovate/pin-dependencies")
DEBUG: PR not found in open or closed PRs list - trying to fetch it directly(branch="renovate/pin-dependencies")
{
  "prNo": 19291
}
DEBUG: branchExists=true(branch="renovate/pin-dependencies")
DEBUG: Branch pr rebase requested: false(branch="renovate/pin-dependencies")
DEBUG: Branch has 25 upgrade(s)(branch="renovate/pin-dependencies")
DEBUG: Checking if PR has been edited(branch="renovate/pin-dependencies")
DEBUG: Found existing branch PR(branch="renovate/pin-dependencies")
DEBUG: Checking schedule(before 3am on the first day of the month, UTC)(branch="renovate/pin-dependencies")
DEBUG: Found timezone(branch="renovate/pin-dependencies")
{
  "timezone": "UTC"
}
DEBUG: Adjusting now for timezone(branch="renovate/pin-dependencies")
DEBUG: Checking 1 schedule(s)(branch="renovate/pin-dependencies")
DEBUG: Checking schedule "before 3am on the first day of the month"(branch="renovate/pin-dependencies")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          10800
        ],
        "D": [
          1
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: schedule.D(branch="renovate/pin-dependencies")
{
  "schedule_D": [
    1
  ]
}
DEBUG: Package not scheduled(branch="renovate/pin-dependencies")
DEBUG: Skipping branch update as not within schedule(branch="renovate/pin-dependencies")
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

Reproduction repo is https://github.com/anomiex/renovate-test

**Additional context**

I suspect you might fix this by changing https://github.com/renovatebot/renovate/blob/3ae05a27f15b53b16d7367bfeca8e4fced3fde7a/lib/workers/branch/index.ts#L247-L255 to
```ts
      // istanbul ignore if
      if (!branchPr) {
        logger.debug('Skipping PR creation out of schedule');
        return ProcessBranchResult.NotScheduled;
      }
      if (config.updateNotScheduled === false && !config.rebaseRequested) {
        logger.debug('Skipping branch update as not within schedule');
        return ProcessBranchResult.Done;
      }
```
Or create a new ProcessBranchResult constant if you don't want to reuse Done.

**Comment by rarkins** [comment]
Although a reproduction is always best, we might try fixing this through code inspection alone as proposed.

**Comment by anomiex** [comment]
It was past the end of my day yesterday. I've now created a reproduction repo at https://github.com/anomiex/renovate-test.

* https://app.renovatebot.com/dashboard#github/anomiex/renovate-test/323793091 is the initial run on the repo, which created [the dashboard](https://github.com/anomiex/renovate-test/issues/1) in that repo.
* https://app.renovatebot.com/dashboard#github/anomiex/renovate-test/323793099 is where I checked the checkbox to ignore the schedule so it would create https://github.com/anomiex/renovate-test/pull/2
* https://app.renovatebot.com/dashboard#github/anomiex/renovate-test/323793104 is where I checked the "Check this box to trigger a request for Renovate to run again on this repository" checkbox to have it re-run and reproduce the bug.

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/121077943-94e79380-c7d8-11eb-8a47-6f8744f27cd9.png)
