### ISSUE TITLE
Regression in applying yarnrc configuration

### ISSUE THREAD

**Issue by riconnon** [renovatebot/renovate#9288]
For the last week or so, the latest builds of renovate have not been respecting my yarnrc configuration
This seems like a regression of #6884 and I suspect it may have been caused by #9211

**Comment by rarkins** [comment]
Please be sure to follow the bug report template in future.

**Comment by riconnon** [comment]
I see that this feature has been deprecated, so I'm not gonna spend too much time trying to figure it out. I'll just stop using it.

**Comment by rarkins** [comment]
@riconnon please let me know if your scenario *requires* it somehow, or there's some yarnrc massaging we need to add?

**Comment by riconnon** [comment]
@rarkins in my use case I had a `.yarnrc` which was intended only for use within my docker build and which broke renovate if it was in place during its runs, so I added an empty `yarnrc` in my renovate config.
I have now switched to an alternate approach where I have renamed this to `yarnrc.docker` and used the docker `COPY` command to name it `.yarnrc` inside the container, which means there's no need for the renovate config.
