### ISSUE TITLE
Support python

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#931]
As suggested by @khornberg and @hbetts in #121

This issue is for building up (a) support (please +1 if you would like to see python support) and (b) requirements, e.g. helping suggest what scope is required and what APIs can be used.

**Comment by rarkins** [comment]
#### Files

File names: `requirements.txt`
Can be multiple in same repo: yes

#### Registry

PyPi

Example URL: https://pypi.python.org/pypi/Versio/json

#### Versioning

Similar to semver, defined in https://www.python.org/dev/peps/pep-0440/

**Comment by rarkins** [comment]
Either write python version logic in JS, or call external python script, e.g. https://stackoverflow.com/questions/23450534/how-to-call-python-function-from-nodejs

The regex is mega: https://stackoverflow.com/questions/37972029/regex-to-match-pep440-compliant-version-strings

**Comment by khornberg** [comment]
Since suggesting python, I have found https://github.com/pyupio/pyup
I have found it to be easy to work with and seems to be basically the same except targeting Python.

**Comment by rarkins** [comment]
Some discussions relevant to the python requirements process:
https://news.ycombinator.com/item?id=11210370
https://www.reddit.com/r/Python/comments/3uzl2a/setuppy_requirementstxt_or_a_combination/

**Comment by mxey** [comment]
The officially recommended tool for Python is now Pipenv, which uses Pipfile and Pipfile.lock: https://docs.pipenv.org/basics/#example-pipfile-pipfile-lock

**Comment by hbetts** [comment]
For context, I found `pipenv` used as the official tool in the official Python documentation - https://packaging.python.org/tutorials/managing-dependencies/

**Comment by keimlink** [comment]
Python packaging tools and requirement files that should be supported:

* [conda](https://conda.io/docs/) - used by many scientific projects
    * `environment.yml`
* [pip](https://pip.pypa.io/) - Python packaging tool currently used by the majority of projects
    * `requirements.txt` (could be also called `requirements.pip`, some projects use several files for production, testing and development requirements)
    * `setup.cfg` - see [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)
    * `tox.ini` - used by [tox](https://tox.readthedocs.io/en/latest/)
* [pipenv](https://docs.pipenv.org/) - The latest Python packaging tool, more projects start using it
    * `Pipfile`
    * `Pipfile.lock`

**Comment by rarkins** [comment]
We've added basic `requirements.txt` support just now - it works on pinned versions (e.g. v1.2.3) only. More advanced support like npm, as well as other files/managers will be added later. To enable or test this initial support:

```
  "pip_requirements": {
    "enabled": true
  }
```

**Comment by rarkins** [comment]
Next step is to implement (port) pep440 to JS so that we can use its validation and comparison functions instead of semver. 

We may do this in a stand-alone repo to avoid any licensing concerns with related python implementations.

**Comment by khornberg** [comment]
Thanks @rarkins

**Comment by rarkins** [comment]
Python support has now been expanded to support all stable "equals" values (e.g. `==x`, `==x.y`, `==x.y.z`) plus all related core Renovate capabilities (e.g. major/minor separation, etc).

It remains disabled by default, so you need to manually enable it as mentioned previously.

I have opened #2085 to specifically track support for advanced PEP440 specifiers.

**Comment by dserodio** [comment]
Thank you for your work @rarkins. It seems that the basic support for Python is already done, but it isn't mentioned in the documentation. Are you waiting for some milestone to be reached, or are you just waiting for a volunteer to document it? :)

**Comment by destroyerofbuilds** [comment]
> Are you waiting for some milestone to be reached, or are you just waiting for a volunteer to document it? :)

I'm not @rarkins, but I'd love to see documentation for Renovate's Python support. We've already started to use it in our organization, and I don't personally have any concerns with advertising it's usage to our wider community through dedicated, top-level, Renovate documentation.

**Comment by rarkins** [comment]
I left this *issue* open because the list of requirements in it was only partially complete. However it is true that `pip` `requirements.txt` support is complete (including ranges) and available. I think what we should do is:

- [ ] Break further functionality described here into new/separate issues
- [ ] Mark this issue as resolved
- [ ] Add documentation for Python
- [ ] Flip the switch to make it enabled by default

@dserodio I wasn't explicitly waiting for a volunteer but you are very welcome to jump in :)

**Comment by rarkins** [comment]
I've now added a few new issues to track remaining functionality for python. All have the new [#python](https://github.com/renovatebot/renovate/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%23python) hashtag

**Comment by rarkins** [comment]
Python support is now enabled by default, so closing this issue. Thanks for everyone's help and suggestions
