### ISSUE TITLE
Build dynamic docs in this repo

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#9313]
**What would you like Renovate to be able to do?**

Move documentation generation logic for this repo from `renovatebot/renovatebot.github.io` to here.

**Did you already have any implementation ideas?**

Scripts like this should be moved here: https://github.com/renovatebot/renovatebot.github.io/blob/build/bin/generate-modules.js

Then I suggest the best way to do this would be to put them into `dist/docs/`.

Should they be published to npm in the tarball? Maybe, maybe not. We can use `.npmignored` to remove them if we don't.

Can they be published as a `docs.zip` file with each release? e.g. https://github.com/renovatebot/renovate/releases/tag/24.97.1

Part of the use for this would be so that downstream users of Renovate, including WhiteSource Renovate On-Premises and the hosted app can use these markdown files. The problem today is that downstream editions can be on older versions of Renovate with different config options, and there's no easy way to browse old docs.

**Comment by rarkins** [comment]
First step can be:
- Copy docs build scripts into this repo and include them with `yarn build`
- ignore them from npm publishing
- Update the docs repo to use them instead of building them (i.e. and de-duplicate the scripts out of the docs repo at the same time)

**Comment by HonkingGoose** [comment]
I did some digging to find out if we can create a nice readable PDF or set of HTML files out of our docs.

### Publish files with GitHub release example

> Can they be published as a `docs.zip` file with each release? e.g. https://github.com/renovatebot/renovate/releases/tag/24.97.1

Yes this is a thing that you can do on GitHub, for a example look at the [ProGit2 repo, releases tab](https://github.com/progit/progit2/releases). They use Travis CI with a `rake` script to run _Asciidoctor_ and build the pdf/epub/html files, and publish them on each release.  Keep in mind that [Asciidoctor](https://asciidoctor.org/) needs the Ruby programming language and ecosystem to work.

### Docusaurus v2 supports versioning doesn't it?

Docusaurus v2 supports versioning, but it's complex to use, from what I can see on the Docusaurus repo... When a contributor wants to update the Docusaurus v2 docs, they need to edit the file in **2 places**, they also regularly scrub old release docs by hand.

Docusuarus v2 manually creates new releases, and so only need to update their docs once a month or so. When they release, they remove a old version of the docs. Renovate uses CI to release a new release every time a PR gets merged. It's a total no go to make a new doc for each version, as that will result in a docs folder with thousands of versioned docs in it....

- Read the [Docusaurus v2 repo, CONTRIBUTING.md#versioned-docs](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#versioned-docs).
- Read the official [Docusaurus v2 docs on versioning](https://docusaurus.io/docs/versioning).

### Can I export static offline HTML files with Docusaurus v2?

Docusaurus v2 does **not** support exporting offline HTML files that you can use without a server. There's a issue open to request this feature though, see [Docusaurus repo issue 3825](https://github.com/facebook/docusaurus/issues?q=is%3Aissue+is%3Aopen+3825). I don't think it's likely that this feature will land soon as Docusaurus is still in alpha and they're busy on a lot of things right now.

### What should we do?

I think that @rarkins idea to just bundle the current Markdown files in a `.zip` file each release is probably the easiest way to get at least some kind of versioned docs/historical record to our users.

**Comment by rarkins** [comment]
Should be a GitHub Action, and run after a release.

@viceice do you think a custom plugin for Semantic Release makes most sense, or a separate GitHub Action? Essentially it would zip up `./dist/docs/` and attach to the release

**Comment by viceice** [comment]
I think we can use a simple plugin to semantic release to publish the zip, should be easy to do. Maybe there is already a release upload plugin to reuse, so we only need to create the zip file

**Comment by viceice** [comment]
I think we can reuse parts from the docusaurus branch, as most buildscripts are already there

**Comment by rarkins** [comment]
I think I removed that branch, sorry. Do you still have it?

**Comment by HonkingGoose** [comment]
I think the branch is still there: https://github.com/renovatebot/renovate/tree/docs/docusaurus

**Comment by HonkingGoose** [comment]
From a earlier post in this thread:

> First step can be:
> 
>     * Copy docs build scripts into this repo and include them with `yarn build`
> 
>     * ignore them from npm publishing
> 
>     * Update the docs repo to use them instead of building them (i.e. and de-duplicate the scripts out of the docs repo at the same time)

I think we did step 1 of this list, @viceice recently moved the files from the docs side to the main repo side, you can find these files here now: https://github.com/renovatebot/renovate/tree/main/tools/docs, also see PR https://github.com/renovatebot/renovate/pull/11429

I don't know what the status is of step 2 and 3 of your list though...

**Comment by viceice** [comment]
I think we can close this, as the docs are already published as release asset.
