### ISSUE TITLE
Support autodiscover excludes

### ISSUE THREAD

**Issue by buffcode** [renovatebot/renovate#9330]
**What would you like Renovate to be able to do?**

Currently renovate supports `autodiscover` and `autodiscoverFilter`, whereas the filter is a minimatch inclusion filter.
In our self-hosted GitLab instances we have a monorepo whose libaries get subtree-splitted into read-only repositories (comparable to Symfony).
A second, renovate-enabled project requires access to this library in order to update composer dependencies.
For this to work, I have to grant the renovate bot user access to the read-only repository, which in turn would create a onboarding PR.

An option `autodiscoverExcludes` which is an array of minimatch pattern would help, so multiple exclusion patterns can be configured. Exclusion filters are applied after inclusion filters (`autodiscoverFilter`).

Using minimatch/glob negations inside `autodiscoverFilter` is not sufficient, as the glob patterns have limited functionality to both include and exclude on multiple paths.

**Did you already have any implementation ideas?**

```json
{
  "autodiscoverExcludes": [
    "projectA/read-only/**",
    "**/archived/**"
  ]
}
```

**Comment by viceice** [comment]
@buffcode Why you give renovate write access to a readonly repo? You should only give readonly access, so renovate will automatically ignore that repo.

**Comment by buffcode** [comment]
@viceice Thanks for pointing out!

I thought the autodiscovery would merely check if access was granted, but in case of GitLab only projects with at least developer access are discovered, so giving the bot reporter access does indeed work.
