### ISSUE TITLE
docs: add or rewrite self-hosted configuration page

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#9375]
We should have a page on how to configure Renovate which is much more clear about the options (file, env, CLI) including their precedence and examples. The info is distributed here and there right now.

This page should link to it at the top and also include the env and cli syntax where applicable: https://docs.renovatebot.com/self-hosted-configuration/ (perhaps a separate issue)

**Comment by HonkingGoose** [comment]
I scrolled through the `type:docs` issues and found these related issues: #8464, #8013, #7430 and finally #5563.

Do you want to keep these issues, or copy/paste the important points into this issue (#9375), or close them outright?

**Comment by rarkins** [comment]
Most related to #5563 but I think I'll keep all open
