### ISSUE TITLE
Renovate through Azure pipeline not working for repostory with special characters in the name

### ISSUE THREAD

**Issue by bramve-fenetre** [renovatebot/renovate#9475]
**What Renovate type, platform and version are you using?**
Self-hosted on azuredevops through azure pipelines

**Describe the bug**
So i wanted to setup renovatebot since it looks to contain all the features i'm looking for when it comes to dependency updating. The setup i use is exactly like the guide: https://docs.renovatebot.com/setup-azure-devops/

I have tested this exact setup in my personal repository where it works. The project and repo is named: "DemoProject/DemoProject".

However at the company i work for we have repository names with special characters. So for example "DemoProject/Têst Repo".
For this i tested the exact same setup as above, however this results in an error see log below:

<details><summary>Click me to see logs</summary>

```
INFO: Repository started (repository=DemoProject/T%C3%AAst%20Repo)
       "renovateVersion": "24.110.0"
ERROR: Repository has unknown error (repository=DemoProject/T%C3%AAst%20Repo)
       "err": {
         "message": "Cannot read property 'defaultBranch' of null",
         "stack": "TypeError: Cannot read property 'defaultBranch' of null\n    at Proxy.initRepo (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/platform/azure/index.js:101:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getPlatformConfig (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/repository/init/apis.js:56:28)\n    at async Object.initApis (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/repository/init/apis.js:65:14)\n    at async Object.initRepo (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/repository/init/index.js:19:14)\n    at async Object.renovateRepository (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/repository/index.js:62:18)\n    at async Object.start (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/global/index.js:98:13)\n    at async /home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/renovate.js:33:24"
       }
 INFO: Repository finished (repository=DemoProject/T%C3%AAst%20Repo)
       "durationMs": 256
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "D4_sTYmvO",
           "repository": "DemoProject/T%C3%AAst%20Repo",
           "err": {
             "message": "Cannot read property 'defaultBranch' of null",
             "stack": "TypeError: Cannot read property 'defaultBranch' of null\n    at Proxy.initRepo (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/platform/azure/index.js:101:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async getPlatformConfig (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/repository/init/apis.js:56:28)\n    at async Object.initApis (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/repository/init/apis.js:65:14)\n    at async Object.initRepo (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/repository/init/index.js:19:14)\n    at async Object.renovateRepository (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/repository/index.js:62:18)\n    at async Object.start (/home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/workers/global/index.js:98:13)\n    at async /home/vsts/.npm/_npx/1546/lib/node_modules/renovate/dist/renovate.js:33:24"
           },
           "msg": "Repository has unknown error"
         }
       ]

```
</details>

**Have you created a minimal reproduction repository?**
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

Its on devops, i cannot make it public. However repro path on devops is: 
- create repository on devops with the name "Têst Repo"
- follow the guide setup on devops guide as provided by https://docs.renovatebot.com/setup-azure-devops/
- See error in pipeline

**Additional context**
-

**Comment by viceice** [comment]
Please fill our bug template complely

**Comment by bramve-fenetre** [comment]
Sorry, updated it now

**Comment by rarkins** [comment]
Classifying as a feature as it will be too big for a patch release anyway

**Comment by bramve-fenetre** [comment]
@rarkins I'm not much of a javascript guy but to me it doesn't sound like there is any need of supported special characters.

I think right here just needs an adjustment: https://github.com/renovatebot/renovate/blob/2211910b79d1044dd344bebaed670d608db40093/lib/platform/azure/util.ts#L198

So i assume that the `name : string` parameter in the method is the name as defined in the config. In which case the user (in this case me) can just put the URL encoded name. In my example like `DemoProject/T%C3%AAst%20Repo`.

Then were it probably goes wrong currently is that the name you retrieve from azure which you then compare this name against is probably not encoded. So just an simple encode wherever you retrieve repository names should do it. 

If i see it correctly at least, if not then please ignore this comment then im just a dumbass :)

**Comment by rarkins** [comment]
You could be right. Can you paste in your (sanitised) config.js?

**Comment by bramve-fenetre** [comment]
Oh actually i'm closing this ticket... I based my configs on what i used in dependabot before, in which i already pasted my encoded project name because it expected it like that

But i see if i just put the plain project name it works just fine in renovate. Sorry for the inconvience..
