### ISSUE TITLE
Config validator wants to migrate hotstRules which use env

### ISSUE THREAD

**Issue by jgarec** [renovatebot/renovate#9477]
**What Renovate type, platform and version are you using?**

Self hosted

**Describe the bug**

With this minimal config file :
```
module.exports = {
    hostRules: [
      {
        // do not use docker credentials for this registry
        hostType: 'docker',
        username: process.env.DOCKER_USERNAME,
        password: process.env.DOCKER_PASSWORD
      }
    ]
  };
```

No migration required if config file is :
```
module.exports = {
    hostRules: [
      {
        // do not use docker credentials for this registry
        hostType: 'docker',
        username: 'usr',
        password: 'pwd'
      }
    ]
  };
```

**Relevant debug logs**

```
 WARN: Config needs migrating
       "originalConfig": {"hostRules": [{"hostType": "docker"}]},
       "migratedConfig": {"hostRules": [{"hostType": "docker"}]}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
FYI `DOCKER_USERNAME` and `DOCKER_PASSWORD` are special env which product a host rule automatically, so the rule is not actually needed.

**Comment by HonkingGoose** [comment]
@rarkins There's a typo in the current PR title, probably best to change `hotstRules` -> `hostRules`. 😉

**Comment by jgarec** [comment]
Sorry my test case was wrong !
DOCKER_USERNAME & DOCKER_PASSWORD were not sets when i ran my test ....

No migration is expected if i correctly set those env variables.
