### ISSUE TITLE
renovate github gradle error

### ISSUE THREAD

**Issue by ikovalyov** [renovatebot/renovate#9514]
**What Renovate type, platform and version are you using?**

GitHub

**Describe the bug**

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
WARN: Gradle extraction failed
{
  "errMessage": "Command failed: docker run --rm --name=renovate_gradle --label=renovate_child -v \"/mnt/renovate/gh/ikovalyov/kotlin-blogpost-engine\":\"/mnt/renovate/gh/ikovalyov/kotlin-blogpost-engine\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GRADLE_OPTS -w \"/mnt/renovate/gh/ikovalyov/kotlin-blogpost-engine\" docker.io/renovate/gradle bash -l -c \"./gradlew --init-script renovate-plugin.gradle renovate\"\nError: Could not find or load main class org.gradle.wrapper.GradleWrapperMain\nCaused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain\n"
}
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

That's a new repo I just started

**Comment by ikovalyov** [comment]
https://github.com/ikovalyov/kotlin-blogpost-engine

**Comment by rarkins** [comment]
Please test if https://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain solves your problem

**Comment by ikovalyov** [comment]
yeah, didn't think renovate is using gradle from the project, it solves the issue, thanks.
