### ISSUE TITLE
[Feature Request] Open/Automerge if confidence above a threshold

### ISSUE THREAD

**Issue by mercuriete** [renovatebot/renovate#9540]
**What would you like Renovate to be able to do?**

I want to open/automerge a PR only when confidence is high.
I want to open/automerge a PR only when adoption is above X%
I want to open/automerge a PR only when passing is above Y%

**Did you already have any implementation ideas?**
No

Thanks for your amazing project. :)

If you think this issue is too complex feel free to close this ticket.

**Comment by rarkins** [comment]
Yes, this is a feature we would like to implement. Not just for automerging but also for deciding when to open a PR or not.

**Comment by jojomatik** [comment]
I'm a huge fan of automation and was therefore looking into renovate. This feature would definitely convince me to using renovate over dependabot.

I don't feel to confident about auto-merging anything based on version changes that are partially still changed by users. Using the automatically computed confidence value for libraries with a large userbase would give me enough confidence to automatically bump to new patch and minor versions.

Is there any rough schedule for this feature?

Keep up the great work, looking into the project nonetheless and very excited to try it out.

**Comment by or-adar** [comment]
Hi @rarkins 
saw that master has some refrences regarding that feature, and the config file introduces a "minimumConfidence" field for that purpose.
I'm running renovate on a self-hosted gitlab runner, so if I'll pull the latest image of renovate, will I be able to experiment with that feature? or is it not yet published to the public?

and regardless, your doing an awsome job! love this project!

**Comment by rarkins** [comment]
No, this is not currently a publicly available feature. The necessary API does/will require authentication

**Comment by or-adar** [comment]
@rarkins 
Thanks for the response!
what do you mean? There's no option for the public to experiment with this feature?

**Comment by jojomatik** [comment]
> Hi @rarkins 
> saw that master has some refrences regarding that feature, and the config file introduces a "minimumConfidence" field for that purpose. 
> I'm running renovate on a self-hosted gitlab runner, so if I'll pull the latest image of renovate, will I be able to experiment with that feature? or is it not yet published to the public?

Oh this is interesting. I will add some of my immediate questions below:

Would I be able to build from source with some adaptions to get this working on my own runner for testing purposes?

Are there any particular reasons other than not extensive enough testing for this feature not to roll out?

**Comment by rarkins** [comment]
> what do you mean? There's no option for the public to experiment with this feature?

There's no option

**Comment by rarkins** [comment]
> Are there any particular reasons other than not extensive enough testing for this feature not to roll out?

It can't work without access to an API fronting a large database. This requires maintenance and operation by a team so that it maintains accuracy and availability. As such, it will likely be free for open source but not private or self-hosted repos.

**Comment by remal** [comment]
@rarkins are there any news about this feature?

**Comment by gabfelp** [comment]
@rarkins thanks for the tool and thanks for working on this.

I was about to fill in an issue/question asking how to "Enable/Disable Automerge based on a 'function'"(like using git checkout, checking things and etc before deciding whether that PR should be auto merged). But given these responses, I'm correct in thinking this is not yet implemented. Is this right? Just wanted to confirm.

**Comment by rarkins** [comment]
There's currently no support for that type of logic

**Comment by JackBailey** [comment]
Any update on this @rarkins?

**Comment by rarkins** [comment]
There is now an experimental package rule matcher called `matchConfidence` which can be used to achieve automerge as described by this issue (so I will close it as completed). Please create a new discussion for follow-ups, as I may miss comments on closed issues.

The matcher requires access to Mend's developer API, and is currently in _internal_ testing. Soon, it will be made available to Mend customers, and later on we plan to make it available to public repos on github.com and other platforms too. At this point it is not intended to make the API access available for non-customer private repos or self-hosters.

We will also be exploring the viability of offering paid Renovate-only plans for users who wish to support Renovate and gain access to Mend APIs for this purpose, but not interested to yet become a customer of Mend's SCA or SAST products.
