### ISSUE TITLE
GitLab email in CODEOWNERS are not supported

### ISSUE THREAD

**Issue by alaingiller** [renovatebot/renovate#9564]
**What Renovate type, platform and version are you using?**
GitLab

**Describe the bug**

With the config `assigneesFromCodeOwners: true` renovate read the CODEOWNERS file to get the assignees.
GitLab support group, username or email in this file but the query to get the UserId differ.
renovate do a GET like this `https://gitlab.com/api/v4/users?username={user}` (https://github.com/renovatebot/renovate/blob/master/lib/platform/gitlab/http.ts#L7) but if `{user}` is an email, the correct request should be `https://gitlab.com/api/v4/users?search={user}.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: addAssignees error (repository=company/path, branch=renovate/docker-deploy-image-77.x)
       "err": {
         "message": "Cannot read property 'id' of undefined",
         "stack": "TypeError: Cannot read property 'id' of undefined\n    at Proxy.addAssignees (/home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/platform/gitlab/index.js:673:94)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async addAssigneesReviewers (/home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/workers/pr/index.js:63:21)\n    at async Object.ensurePr (/home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/workers/pr/index.js:392:13)\n    at async Object.processBranch (/home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/workers/branch/index.js:548:42)\n    at async Object.writeUpdates (/home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/workers/repository/process/write.js:32:21)\n    at async Object.update (/home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/workers/repository/process/extract-update.js:110:15)\n    at async Object.renovateRepository (/home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/workers/repository/index.js:66:21)\n    at async Object.start (/home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/workers/global/index.js:98:13)\n    at async /home/dev/.nvm/versions/node/v14.16.0/lib/node_modules/renovate/dist/renovate.js:28:24"
       }
 WARN: Failed to add assignees (repository=company/path, branch=renovate/docker-deploy-image-77.x)
```

</details>

**Have you created a minimal reproduction repository?**

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

The workaround is quite simple, use only username in CODEOWNERS file even if GITLAB support also emails.

The fix seems also quite easy, check if `username` contains an `@` to call the correct GET request

**Comment by viceice** [comment]
This bug is easily reproducable on a public gitlab hosted project

**Comment by alaingiller** [comment]
I can provide a PR.
