### ISSUE TITLE
Use dynamic detection of public repos instead of a static list

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#9587]
**What would you like Renovate to be able to do?**

See: `whitelistedPublicScopes` in `lib/datasource/npm/get.ts`

**Did you already have any implementation ideas?**

**Comment by rarkins** [comment]
Depends on https://github.com/renovatebot/renovate/issues/8473

**Comment by HonkingGoose** [comment]
Applying the `status:blocked` label due to:

> Depends on #8473
