### ISSUE TITLE
Add long-term cache for requests to releases.hashicorp.com

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#9590]
**What would you like Renovate to be able to do?**

See: `queryReleaseBackend()` function

**Did you already have any implementation ideas?**

**Comment by JamieMagee** [comment]
How long-term is long-term? Is this easily achievable with the cache decorator? #10203

**Comment by rarkins** [comment]
It's referring to here: https://github.com/renovatebot/renovate/blob/7daa93a78dca223b3e52aa99e7c3fae168d7975f/lib/datasource/terraform-provider/index.ts#L56-L82

I can then see the comment was added by @viceice in #6959

**Comment by JamieMagee** [comment]
Yeah, I came across it during #10362.
