### ISSUE TITLE
Add connection check for Bitbucket platform init

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#9594]
**What would you like Renovate to be able to do?**

Check that endpoint/token combination are valid

**Did you already have any implementation ideas?**

Be ready to perform huge refactoring of tests and mocks

**Comment by setchy** [comment]
@zharinov @rarkins - is Bitbucket connection check here sufficient?

https://github.com/renovatebot/renovate/blob/d9b025bf63427475bdfc69ed2d0f379638c68020/lib/modules/platform/bitbucket/index.ts#L83

**Comment by rarkins** [comment]
@setchy seems to be
