### ISSUE TITLE
Force cloning over ssh

### ISSUE THREAD

**Issue by WoodenAndrew** [renovatebot/renovate#9607]
**What Renovate type, platform and version are you using?**

Selfhosted with bitbucker-server

**Describe the bug**

Renovate cli tool attempts to clone over HTTP

**Relevant debug logs**

```
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "6czLLB-SZ",
           "repository": "wootenand/renovate-sample-application",
           "err": {
             "task": {
               "commands": [
                 "ls-remote",
                 "--heads",
                 "https://wootenand:token@bitbucket.intra/scm/wootenand/renovate-sample-application.git"
               ],
               "format": "utf-8"
             },
             "message": "fatal: unable to access 'https://bitbucket.intra/scm/wootenand/renovate-sample-application.git/': SSL certificate problem: unable to get local issuer certificate\n",
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly
- [x] None of above. 

**Additional context**

Renovate should be cloning via SSH instead, and only using the API to create pull requests.

User note: I am well aware the issue is with our self signed certificates, but it is easily solved by cloning via ssh instead.

**Comment by rarkins** [comment]
This was addressed for some users in #8115. Is the reason it doesn't work for you because you leave HTTPS enabled?

**Comment by WoodenAndrew** [comment]
Yeah, it's still enabled. We don't control the configuration of bitbucket server, so forcing it via some flags would be preferable instead.

**Comment by rarkins** [comment]
It's pretty easy to add custom certificates to a Node.js application like Renovate. Is there something preventing you doing that? And if you cloned via SSH would it be unauthenticated, or would you be needing to utilize an SSH key?

**Comment by HonkingGoose** [comment]
> It's pretty easy to add custom certificates to a Node.js application like Renovate. Is there something preventing you doing that? And if you cloned via SSH would it be unauthenticated, or would you be needing to utilize an SSH key?

Does any of this help you @WoodenAndrew?

It's been a while since you opened the issue, do you still have the problem, or did you manage to find a way to get things working?

**Comment by WoodenAndrew** [comment]
No, the issue was postponed for now. Sadly, installing certificates is not an option either.

**Comment by rarkins** [comment]
I think *this* issue is the feature request for what you want, isn't it? So a PR would be welcome, but I recommend you first propose here how you think the configuration should work, so that we can save you any time by letting you know early if it would be feasible or not

**Comment by viceice** [comment]
@GCHQDeveloper926 i think you are waiting for this
- #13875

**Comment by GCHQDeveloper926** [comment]
@rarkins @viceice Thanks for the comments, I think this will solve my problem too so I will keep an eye on and contribute where I can!
