### ISSUE TITLE
Fix "migrateConfig" argument types

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#9611]
**What would you like Renovate to be able to do?**

`parentKey` should not contain `any` type.

**Did you already have any implementation ideas?**

**Comment by RahulGautamSingh** [comment]
Couldn't find `parentKey`? Seems outdated issue.
![image](https://github.com/renovatebot/renovate/assets/76607510/adab9f7a-7fc4-4b16-bc67-835498f7d4a8)
