### ISSUE TITLE
Fix coverage for Bitbucket Server platform tests

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#9624]
**What would you like Renovate to be able to do?**

Add tests for `matchesState()`, `isRelevantPr()`, `getPrList()` and `findPr()` functions, remove `istanbul ignore` annotations.

**Did you already have any implementation ideas?**

**Comment by viceice** [comment]
@rarkins why not planned? we should remove those comments as much as possible.

**Comment by rarkins** [comment]
Not worth the time to write them unless/until we have commercial use. I think 3y is long enough to wait for the community to have done so

**Comment by viceice** [comment]
ok
