### ISSUE TITLE
Allow Renovate to read ENV variables from .env file

### ISSUE THREAD

**Issue by DesignyourCode** [renovatebot/renovate#9655]
**What would you like Renovate to be able to do?**

Renovate fails to complete a `composer update` because one of the packages: `advanced-custom-fields/advanced-custom-fields-pro` requires a licence key. By default this licence key is set within a .env file in the root of the project (this is all based around Bedrock which is essentially a composer wrapper for WordPress.

So when `composer update` is run, ACF_PRO_KEY needs to be available.

**Did you already have any implementation ideas?**

Dependabot has a global location for setting this variable. Is renovate able to apply something similar? Or better than this, just have a syntax for importing .env variables: `{{process.env.ACF_PRO_KEY}}`

Some addition details. Dependabot seems to not play nicely with wpackagist which is why we are trying Renovate as an alternative. But The above above is a show stopper for using Renovate.

**Comment by rarkins** [comment]
Are you self-hosted or running the hosted app?

**Comment by DesignyourCode** [comment]
This is running on Github

**Comment by DesignyourCode** [comment]
We are in the process of trying to run a bash file to make the env variable available by running a `pre-update-cmd` but for some reason Renovate is using ignore scripts even though by default it is set to false.

**Comment by rarkins** [comment]
"Running on GitHub" does not answer clearly enough if it's the hosted app or you are running self hosted.

**Comment by DesignyourCode** [comment]
Oh sorry. I've only been trying Renovate since this morning so still getting to grips with the terminology.

We are using the hosted app. We have set up nothing custom.

**Comment by rarkins** [comment]
If it is the hosted app, which dot env *file* did you have in mind when you were creating the issue? Eg were you already or planning to commit the api key into the repository itself?

**Comment by DesignyourCode** [comment]
At this stage we need are just trying to work out what option will work. Ideally being able to put the variable into Github's secrets would be great. But otherwise if we can get it loading via a bash script from a file then we could at least commit the file and run it from there.

Longer term, we ideally we wouldn't want to commit the .env. But not being able to load the variable from somewhere is a show stopper.

**Comment by viceice** [comment]
If you run renovate self-hosted, eg with our github action, you can configure custom environment variables.

**Comment by viceice** [comment]
Yes, in the hosted app it's a security concern, so disabled.

**Comment by DesignyourCode** [comment]
Ok. I think some sort of messaging in the docs would be helpful.

I think we will have to switch back to Dependabot and try to fix our issues there. Thanks anyways.
