### ISSUE TITLE
Add Monorepo Preset for Hot Chocolate NuGet Packages

### ISSUE THREAD

**Issue by RehanSaeed** [renovatebot/renovate#9687]
**What would you like Renovate to be able to do?**

Add Monorepo Preset for [Hot Chocolate](https://github.com/ChilliCream/hotchocolate) NuGet Packages. So all NuGet packages starting with `HotChocolate.*` [on NuGet](https://www.nuget.org/packages?q=hotchocolate) are updated together.

**Comment by rarkins** [comment]
Needs to be added to https://github.com/renovatebot/renovate/blob/2cc751a0a1ba2e0d3bc35f51eed4cdaf07f8282c/lib/config/presets/internal/monorepo.ts#L4

**Comment by RehanSaeed** [comment]
PR Created in https://github.com/renovatebot/renovate/pull/9700

**Comment by HonkingGoose** [comment]
This issue is resolved now that PR #9700 is merged. Closing this issue.

**Comment by HonkingGoose** [comment]
@RehanSaeed Congratulations on getting your first PR landed! Well done! 🎉 ✨ 

Did you know that you can use the `closes`, `resolves` or `fixes` keywords to close a issue with a PR automatically?

For example:
If you had put `Closes #9687` into the PR text of PR `#9700`, GitHub would automatically close issue `#9700` when the PR got merged.

For more information on this cool feature read the [GitHub docs, linking a pull request to an issue using a keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
