### ISSUE TITLE
Make sure we put warning in PR body when branch reuse isn't possible

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#9720]
**What would you like Renovate to be able to do?**

In `lib/workers/branch/reuse.ts`, search for those lines:

```ts
logger.debug('Cannot rebase branch as it has been modified');
```

and 

```ts
logger.debug(`Branch is not mergeable but can't be rebased`);
```

**Did you already have any implementation ideas?**

**Comment by rarkins** [comment]
@zharinov did you mean this text in the PR?

![image](https://user-images.githubusercontent.com/6311784/149493962-14a89f52-5e04-4702-8124-0073685d93ef.png)

Don't we already note when the branch is modified? Or do you mean an extra warning that (a) it's not rebaseable and (b) it needs rebasing?

**Comment by zharinov** [comment]
Hm, I can't remember what I meant 😅 Can be closed, I think
