### ISSUE TITLE
Reviewers dont work on BitBucket Cloud

### ISSUE THREAD

**Issue by Chr1stian** [renovatebot/renovate#9737]
**What Renovate type, platform and version are you using?**

"renovateVersion": "24.104.0"
Self-hosted BitBucket Cloud

**Describe the bug**

We are using the "new" shared local config preset for BitBucket Cloud and want to have one reviewer picked at random for each pull-request using this config:

```
"reviewers": ["BitBucketUserName1", "BitBucketUserName2", "BitBucketUserName3"],
 "reviewersSampleSize": 1
```

I have tried both usernames and email addresses for the reviewers, but it does not add a reviewer on the pull requests.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by rarkins** [comment]
This should be possible to demonstrate in a public repo.

**Comment by Chr1stian** [comment]
> This should be possible to demonstrate in a public repo.

How can it be demonstrated when we use a self-hosted bot?

**Comment by rarkins** [comment]
I was thinking:
- Create a public repository with one outdated dependency and a renovate.json using `reviewers` and `reviewersSampleSize`
- Make sure the reviewers are added to the repository too (i.e. have permissions to be added by Renovate as reviewers)
- Run your bot against the repo, and capture the logs
- Observe the resulting PR/logs

**Comment by Chr1stian** [comment]
Seems like this "bug" fixed itself upon a subsequent run this week.
