### ISSUE TITLE
Off the shelf vs custom parsers

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#9740]
We need to make a project design decision on how and when we choose to use off-the-shelf parsing (e.g. JSON.parse, yaml.load, etc) versus custom parsing, whether regex or lexer-based.

Advantages of full parsers:
- Much simpler to maintain
- Encourages community contributions much more easily

Disadvantages of full parsers:
- They only work if the input file is valid JSON/YAML/XML/etc. Sometimes projects have templates

So if the "real" problem here is that not all input file are valid syntax, then we are maybe shooting ourselves in the foot by adding custom and harder-to-maintain parsers.

An alternative would be to add pre-extract "transforms", such as discussed in #7333

@viceice @zharinov @JamieMagee

**Comment by viceice** [comment]
I like the `moo` base parsers, as they look pretty clean and easy. 

Most regex based parsers need a lot of custom parser functions too as seen on terraform.
I think a moo based parser would be a lot more simple for terraform that the current regex stuff.

For simple yaml files like `gitlabci` we should use the yaml parser as long we can simply workaround the custom gitlab hooks.
But if there is a simple `moo` parser i would accept it too.

Yes, the `moo` based parsers can be a lot harder to fix for new contributers.

**Comment by rarkins** [comment]
I would prefer to use regular parsers whenever one exists instead of writing our own. When there's no other choice, we then need to decide on regex (if it's simple enough) or moo if it's structured/complex.

What's the "custom gitlab hooks"? e.g. do you mean they don't use valid YAML?

**Comment by viceice** [comment]
> I would prefer to use regular parsers whenever one exists instead of writing our own. When there's no other choice, we then need to decide on regex (if it's simple enough) or moo if it's structured/complex.

Agree

> 
> What's the "custom gitlab hooks"? e.g. do you mean they don't use valid YAML?
Yes, the invalid yaml anchors (which are currently removed before parsing)

**Comment by rarkins** [comment]
I guess GitLab CI is a special case where we could massage/remove spec violations we know about prior to parsing, because it's part of the GitLab CI spec itself.

**Comment by zharinov** [comment]
More full-parser cons:
- Once we need write custom `update.ts`, we're forced to implement some sort of ad-hoc parsing anyway
- Some libraries can fail even for valid inputs (that's why I didn't use any clojure EDN parser available at the moment)

Although, I support third-party parsers as long as they just work

**Comment by JamieMagee** [comment]
I think all the main points have been mentioned at this stage. My main suggestion is that if we go the custom parser route, with `moo`, the parser should be a package external to the main renovate repository. I expect we're not the only ones that would like to parse these formats in the JavaScript ecosystem, and I think that these packages can be useful to the wider open source community.

**Comment by rarkins** [comment]
Decision: we favor off-the-shelf parsers, and implement #7333
