### ISSUE TITLE
Artifact update problem in Go repos: permission denied

### ISSUE THREAD

**Issue by codyoss** [renovatebot/renovate#9748]
**What Renovate type, platform and version are you using?**

forking-renovate

**Describe the bug**

This week our dependency updates in multiple Go repos started to fail. The bot correctly identifies that there was an issue and leaves a comment titled, "⚠️ Artifact update problem". 

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Command failed: docker run --rm --name=renovate_go --label=renovate_child -v "/mnt/renovate/gh/googleapis/gapic-generator-go":"/mnt/renovate/gh/googleapis/gapic-generator-go" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -v "/tmp/renovate-cache/others/go":"/tmp/renovate-cache/others/go" -e GOPATH -e CGO_ENABLED -w "/mnt/renovate/gh/googleapis/gapic-generator-go" docker.io/renovate/go:1.13.15 bash -l -c "git config --global url.\"https://**redacted**@github.com/\".insteadOf \"https://github.com/\" && go get -d ./... && go mod tidy && go mod tidy"
go: finding google.golang.org/genproto eac7f76ac494
go: downloading gitlab.com/golang-commonmark/markdown v0.0.0-20191127184510-91b5b3c99c19
go: extracting gitlab.com/golang-commonmark/markdown v0.0.0-20191127184510-91b5b3c99c19
go: downloading gitlab.com/golang-commonmark/html v0.0.0-20191124015941-a22733972181
go: downloading gitlab.com/golang-commonmark/mdurl v0.0.0-20191124015652-932350d1cb84
go: extracting gitlab.com/golang-commonmark/html v0.0.0-20191124015941-a22733972181
go: extracting gitlab.com/golang-commonmark/mdurl v0.0.0-20191124015652-932350d1cb84
go: downloading gopkg.in/yaml.v2 v2.4.0
go: extracting gopkg.in/yaml.v2 v2.4.0
go: downloading gitlab.com/golang-commonmark/linkify v0.0.0-20191026162114-a0c2df6c8f82
go: extracting gitlab.com/golang-commonmark/linkify v0.0.0-20191026162114-a0c2df6c8f82
go: downloading gitlab.com/golang-commonmark/puny v0.0.0-20191124015043-9f83538fa04f
go: extracting gitlab.com/golang-commonmark/puny v0.0.0-20191124015043-9f83538fa04f
go: downloading github.com/google/go-cmp v0.5.5
go: downloading github.com/russross/blackfriday v2.0.0+incompatible
go: extracting gopkg.in/yaml.v2 v2.4.0
go: downloading gitlab.com/opennota/wd v0.0.0-20180912061657-c5d65f63c638
go: extracting gitlab.com/opennota/wd v0.0.0-20180912061657-c5d65f63c638
go: extracting github.com/google/go-cmp v0.5.5
go: extracting github.com/russross/blackfriday v2.0.0+incompatible
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: extracting github.com/shurcooL/sanitized_anchor_name v1.0.0
github.com/googleapis/gapic-generator-go/internal/gengapic imports
	gopkg.in/yaml.v2: fstatat /tmp/renovate-cache/others/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0: permission denied
```
</details>

**Additional context**

Here are all the PRs that I noticed the issue in:

- https://github.com/googleapis/gapic-generator-go/pull/594/
- https://github.com/googleapis/google-cloud-go/pull/4011
- https://github.com/googleapis/google-cloud-go/pull/4010

The similar link between them seems to be the permission denied errors occurring reading dependencies that names start with `gopkg.in `. The PRs are left in a state where the pseudo module version is incorrect, example: https://github.com/googleapis/gapic-generator-go/blob/37d8065bffee433cbe67ced4e7ed9fcc7020d4a8/go.mod#L8

**Comment by rarkins** [comment]
I have noticed that `gopkg.in` modules are written to our cache using `0444` permissions and suspect this cannot be a coincidence. Were these failing PRs the first PRs created on the run or second? I ask because I wonder if it's failing to override a cached dependency it created itself or one which was created by a previous run.

**Comment by rarkins** [comment]
Definitely seeing some hits about go module cache permissions problems, e.g. https://github.com/golang/go/issues/27455

**Comment by rarkins** [comment]
@bcmills do you happen to know why `gopkg.in` modules specifically would have read-only permissions while other domains do not?

**Comment by bcmills** [comment]
@rarkins, all modules in the module cache should be written to disk as read-only unless the `-modcacherw` flag is set.

**Comment by bcmills** [comment]
This could be https://github.com/golang/go/issues/42344 if the `gopkg.in` modules were originally fetched using a `go` command older that Go 1.16.

**Comment by rarkins** [comment]
@bcmills thanks for the quick response. I just noticed `-modcacherw` in the go 1.14 release notes:

![image](https://user-images.githubusercontent.com/6311784/116308812-43df8b00-a7a8-11eb-95d9-ece8261a127e.png)

On a related topic, Renovate uses the *minimum* go version specified in the go.mod, e.g. if `go 1.15` is specified then we'll run something like go `1.15.1`. Would it be safe for us to treat `go 1.15` as `>= 1.15` instead and therefore pick the latest (in this case go 1.16)?

**Comment by bcmills** [comment]
> Would it be safe for us to treat `go 1.15` as `>= 1.15` instead and therefore pick the latest (in this case go 1.16)?

Yes. In general only the latest two major Go releases (1.16 and 1.15 today) receive bug-fixes, and even then only if the bugs are severe. We try to preserve compatibility between Go versions, so (for example) the Go 1.16 release of `cmd/go` knows how to interpret `go.mod` files that specify `go 1.15`.

(It should always be ok to use a newer `go` command to edit an older module; if you find that is not the case, please do file a bug so we can fix it. 🙂)

**Comment by rarkins** [comment]
Thanks. My concern had more been whether the project *actually* used e.g. `go 1.15.1` in tooling and then Renovate would update something like `go.sum` to use `1.16` features which then break the project's CI running on `1.15`. However I was already leaning towards using latest Go version anyway prior to your recommendation, so I'm going to go with that!

**Comment by johanbrandhorst** [comment]
Is there a workaround for this? It seems to be affecting all renovate repos with a `gopkg.in` dependency anywhere in the tree.

**Comment by lindell** [comment]
It seems to be working again after the `25.7.2` release 😄

**Comment by clok** [comment]
I am seeing this across many of my repos now. They are using the GitHub installed application.  According the to the run logs on `app.renovatebot.com` the version is:
```json
{
  "renovateVersion": "24.119.17"
}
```

I am consistently seeing this failure with `gopkg.in` modules. 

Any timeline for when the reported fixed version of `25.7.2` will role out to the GitHub app?

---

A few examples:
https://github.com/clok/ghlabels/pull/3
```text
Command failed: docker run --rm --name=renovate_go --label=renovate_child -v "/mnt/renovate/gh/clok/ghlabels":"/mnt/renovate/gh/clok/ghlabels" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -v "/tmp/renovate-cache/others/go":"/tmp/renovate-cache/others/go" -e GOPATH -e CGO_ENABLED -w "/mnt/renovate/gh/clok/ghlabels" docker.io/renovate/go:1.16.3 bash -l -c "git config --global url.\"https://**redacted**@github.com/\".insteadOf \"https://github.com/\" && go get -d ./... && go mod tidy && go mod tidy"
go: downloading github.com/AlecAivazis/survey/v2 v2.2.12
go: downloading github.com/clok/cdocs v1.2.0
go: downloading github.com/google/go-github/v35 v35.1.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/oauth2 v0.0.0-20210413134643-5e61552d6c78
github.com/clok/ghlabels/helpers imports
	gopkg.in/yaml.v2: fstatat /tmp/renovate-cache/others/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0: permission denied
```

https://github.com/clok/hev-cli/pull/3
```text
Command failed: docker run --rm --name=renovate_go --label=renovate_child -v "/mnt/renovate/gh/clok/hev-cli":"/mnt/renovate/gh/clok/hev-cli" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -v "/tmp/renovate-cache/others/go":"/tmp/renovate-cache/others/go" -e GOPATH -e CGO_ENABLED -w "/mnt/renovate/gh/clok/hev-cli" docker.io/renovate/go:1.16.3 bash -l -c "git config --global url.\"https://**redacted**@github.com/\".insteadOf \"https://github.com/\" && go get -d ./... && go mod tidy && go mod tidy"
go: downloading github.com/clok/cdocs v1.2.0
go: downloading github.com/clok/kemba v1.1.1
go: downloading github.com/urfave/cli/v2 v2.3.0
go: downloading github.com/OrlovEvgeny/go-mcache v0.0.0-20200121124330-1a8195b34f3a
go: downloading github.com/umahmood/haversine v0.0.0-20151105152445-808ab04add26
go: downloading github.com/gomodule/redigo v1.8.4
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/gookit/color v1.3.8
go: downloading github.com/kr/pretty v0.2.1
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/stretchr/testify v1.7.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
github.com/clok/hev-cli imports
	github.com/clok/cdocs tested by
	github.com/clok/cdocs.test imports
	github.com/stretchr/testify/assert imports
	gopkg.in/yaml.v3: fstatat /tmp/renovate-cache/others/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c: permission denied
```

**Comment by jalavosus** [comment]
Can confirm that I'm still seeing this issue as well; I've tried rebasing/rerunning at least twice a day for the past week, and it's been consistently failing.

**Comment by rarkins** [comment]
Is anyone able to check if adding `-modcacherw` to <1.14 go will cause it to *fail* (e.g. unknown option) or will it ignore it gracefully? If ignored then we can add it as a default option pretty quickly and deploy. Otherwise needs a bit more advanced logic to determine when to add it to the commands.

**Comment by jalavosus** [comment]
@rarkins it looks like the `go` command is generally not happy with unknown flags (read: passing the flag *will* fail for go versions < 1.14). 

In terms of checking the currently installed Go version, you could use something like 

```shell
GOVERSION=$(go version | grep -Eo '([1-9]\.[0-9]{1,3}\.*[0-9]{0,3})')
MINORVER=$(echo $GOVERSION | awk '{ split($$0, array, ".") } { print array[2] }')
```
(or whatever the JS equivalent is... I'm a Go guy, I don't know how JS does `exec` :P) and then work with that output. It shouldn't be much more of a pain than 
```
flags = [array of whatever flags are already being used]

if MINORVER >= 14 then flags.append("modcacherw")

exec(go get [splat flags here])
```

**Comment by jalavosus** [comment]
@rarkins let me know if I can save you any amount of time by authoring a PR for this change, I'd love to be able to procrastinate on what I actually need to get done :)

**Comment by jalavosus** [comment]
(Apologies for spamming) 

Is there a specific reason that packages from `gopkg.in` get filtered out [here](https://github.com/renovatebot/renovate/blob/main/lib/manager/gomod/artifacts.ts#L38)?

**Comment by rarkins** [comment]
@jalavosus thanks, that is really helpful. Let's see if we can take it from here @zharinov

**Comment by clok** [comment]
For my repos, #9889 has resolved this issue for me. Thank you!

**Comment by codyoss** [comment]
Seems like this is still happening for us: https://github.com/googleapis/google-cloud-go/pull/4108

**Comment by rarkins** [comment]
Why is it always `gopkg.in`...

**Comment by clok** [comment]
@codyoss @rarkins For a few of my repos I had to disable renovate, rename and close the original PRs, then enable renovate. This seemed to jump start the process from a clean slate. On others, I didn't have to do this. It was only needed on 2 out of the 12 projects I manage, so I wasn't sure if it was a transient issue or not.

**Comment by rarkins** [comment]
I've added some app debugging and can confirm that there's cache problems because of `gopkg.in`, e.g.

```
Command failed: chmod -R u+w /tmp/renovate-cache
chmod: cannot access '/tmp/renovate-cache/others/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0': Permission denied
chmod: cannot access '/tmp/renovate-cache/others/go/pkg/mod/gopkg.in/warnings.v0@v0.1.2': Permission denied
chmod: cannot access '/tmp/renovate-cache/others/go/pkg/mod/gopkg.in/src-d': Permission denied
`chmod -R u+w /tmp/renovate-cache` (exited with error code 1)
```

Trying to work out the right combination of chmod/chown to remove them each run

**Comment by rarkins** [comment]
`chmod -R u+wx` fix applied, which I think might work. But the upgrade itself cleared the cache, so now it's going to take a while for a worker to get polluted with read-only cache before I can confirm it gets successfully cleared.

**Comment by rarkins** [comment]
I've applied a solution to:
- rm -rf cache
- if error thrown, sleep 5s to let rm -rf finish
- chmod -R u+wx
- rm -rf

So far it's worked 3/3 times, so fingers crossed it stays that way.
