### ISSUE TITLE
Support ASDF versions file

### ISSUE THREAD

**Issue by secustor** [renovatebot/renovate#9759]
**What would you like Renovate to be able to do?**

Renovate `.tool-versions`file which contains a list of tools and versions e.g. ruby, python, terraform, node.js, yarn, terragrunt, ..
This tool chain is getting then installed by https://github.com/asdf-vm/asdf

**Did you already have any implementation ideas?**
This is basically a new manager.     

Logic and datasources can be reused from specific implementations of version files e.g. terraform-version or terragrunt-version

**Comment by rarkins** [comment]
Duplicate of #4051 ?

**Comment by secustor** [comment]
Ah damit. you are correct closing

**Comment by HonkingGoose** [comment]
Duplicate of #4051
