### ISSUE TITLE
Bazel docker digest update uses manifest digest

### ISSUE THREAD

**Issue by croachrose** [renovatebot/renovate#9786]
**What Renovate type, platform and version are you using?**
Latest npm release v25.5.0
Self-hosted in Github Actions

**Describe the bug**

When pinning digests in `container_pull`, the digest is computed using the manifest header rather than the correct image for the platform. I think this issue was introduced by https://github.com/renovatebot/renovate/pull/8428/files.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: Found 2 definitions (repository=croachrose/renovate-bazel-docker)
       "definitions": [
         "http_archive(\n    name = \"io_bazel_rules_docker\",\n    sha256 = \"59d5b42ac315e7eadffa944e86e90c2990110a1c8075f1cd145f487e999d22b3\",\n    strip_prefix = \"rules_docker-0.17.0\",\n    urls = [\"https://github.com/bazelbuild/rules_docker/releases/download/v0.17.0/rules_docker-v0.17.0.tar.gz\"],\n)",
         "container_pull(\n    name = \"nginx\",\n    digest = \"sha256:480395b7be07df06368c93469df41343c1e6285f5b37d387b5a17f2e8708a2a3\",\n    registry = \"docker.io\",\n    repository = \"library/nginx\",\n    tag = \"1.19.10-alpine\",\n)"
       ]
DEBUG: Checking bazel definition (repository=croachrose/renovate-bazel-docker)
       "def": "http_archive(\n    name = \"io_bazel_rules_docker\",\n    sha256 = \"59d5b42ac315e7eadffa944e86e90c2990110a1c8075f1cd145f487e999d22b3\",\n    strip_prefix = \"rules_docker-0.17.0\",\n    urls = [\"https://github.com/bazelbuild/rules_docker/releases/download/v0.17.0/rules_docker-v0.17.0.tar.gz\"],\n)"
DEBUG:  (repository=croachrose/renovate-bazel-docker, dependency=io_bazel_rules_docker)
       "remote": undefined,
       "currentValue": undefined
DEBUG: Checking bazel definition (repository=croachrose/renovate-bazel-docker)
       "def": "container_pull(\n    name = \"nginx\",\n    digest = \"sha256:480395b7be07df06368c93469df41343c1e6285f5b37d387b5a17f2e8708a2a3\",\n    registry = \"docker.io\",\n    repository = \"library/nginx\",\n    tag = \"1.19.10-alpine\",\n)"
DEBUG:  (repository=croachrose/renovate-bazel-docker, dependency=nginx)
       "remote": undefined,
       "currentValue": "1.19.10-alpine"
DEBUG: Found bazel package files (repository=croachrose/renovate-bazel-docker)
DEBUG: Found 1 package file(s) (repository=croachrose/renovate-bazel-docker)
 INFO: Dependency extraction complete (repository=croachrose/renovate-bazel-docker)
       "baseBranch": "master",
       "stats": {
         "managers": {"bazel": {"fileCount": 1, "depCount": 2}},
         "total": {"fileCount": 1, "depCount": 2}
       }
DEBUG: getLabels(https://index.docker.io, library/nginx, latest) (repository=croachrose/renovate-bazel-docker)
DEBUG: getDigest(https://index.docker.io, library/nginx, 1.20.0-alpine) (repository=croachrose/renovate-bazel-docker)
DEBUG: getDigest(https://index.docker.io, library/nginx, 1.19.10-alpine) (repository=croachrose/renovate-bazel-docker)
DEBUG: Package releases lookups complete (repository=croachrose/renovate-bazel-docker)
       "baseBranch": "master"
DEBUG: branchifyUpgrades (repository=croachrose/renovate-bazel-docker)
DEBUG: 2 flattened updates found: nginx, nginx (repository=croachrose/renovate-bazel-docker)
DEBUG: Returning 2 branch(es) (repository=croachrose/renovate-bazel-docker)
DEBUG: config.repoIsOnboarded=true (repository=croachrose/renovate-bazel-docker)
DEBUG: packageFiles with updates (repository=croachrose/renovate-bazel-docker)
       "config": {
         "bazel": [
           {
             "packageFile": "WORKSPACE",
             "deps": [
               {
                 "depType": "http_archive",
                 "managerData": {
                   "def": "http_archive(\n    name = \"io_bazel_rules_docker\",\n    sha256 = \"59d5b42ac315e7eadffa944e86e90c2990110a1c8075f1cd145f487e999d22b3\",\n    strip_prefix = \"rules_docker-0.17.0\",\n    urls = [\"https://github.com/bazelbuild/rules_docker/releases/download/v0.17.0/rules_docker-v0.17.0.tar.gz\"],\n)"
                 },
                 "depName": "io_bazel_rules_docker",
                 "repo": "bazelbuild/rules_docker",
                 "currentValue": "v0.17.0",
                 "datasource": "github-releases",
                 "lookupName": "bazelbuild/rules_docker",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": "https://github.com/bazelbuild/rules_docker",
                 "currentVersion": "v0.17.0",
                 "fixedVersion": "v0.17.0"
               },
               {
                 "depType": "container_pull",
                 "managerData": {
                   "def": "container_pull(\n    name = \"nginx\",\n    digest = \"sha256:480395b7be07df06368c93469df41343c1e6285f5b37d387b5a17f2e8708a2a3\",\n    registry = \"docker.io\",\n    repository = \"library/nginx\",\n    tag = \"1.19.10-alpine\",\n)"
                 },
                 "currentDigest": "sha256:480395b7be07df06368c93469df41343c1e6285f5b37d387b5a17f2e8708a2a3",
                 "currentValue": "1.19.10-alpine",
                 "depName": "nginx",
                 "versioning": "docker",
                 "datasource": "docker",
                 "lookupName": "library/nginx",
                 "registryUrls": ["docker.io"],
                 "depIndex": 1,
                 "updates": [
                   {
                     "newVersion": "1.20.0",
                     "newValue": "1.20.0-alpine",
                     "bucket": "non-major",
                     "newMajor": 1,
                     "newMinor": 20,
                     "updateType": "minor",
                     "newDigest": "sha256:e015192ec74937149dce3aa1feb8af016b7cce3a2896246b623cfd55c14939a6",
                     "branchName": "renovate/nginx-1.x"
                   },
                   {
                     "updateType": "digest",
                     "newValue": "1.19.10-alpine",
                     "newDigest": "sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2",
                     "branchName": "renovate/nginx-1.19.10-alpine"
                   }
                 ],
                 "warnings": [],
                 "currentVersion": "1.19.10",
                 "isSingleVersion": true,
                 "fixedVersion": "1.19.10-alpine"
               }
             ]
           }
         ]
       }
DEBUG: processRepo() (repository=croachrose/renovate-bazel-docker)
```

</details>

**Have you created a minimal reproduction repository?**

https://github.com/croachrose/renovate-bazel-docker

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

It looks like a change was made to request `application/vnd.docker.distribution.manifest.list.v2+json` which is a manifest list from the registry. The server responds with a digest header and that is used as the new image digest. This works fine for regular `docker` commands but bazel looks as the pulled image and computes the digest itself. In that case, the digest matches the image based on the platform. In my case, linux/amd64 contains the right digest.

**Comment by viceice** [comment]
You need to use the amd64 images to get that behavior. The current behavior is working fine for all other docker image usages.

I think there is already a issue about this.
@HonkingGoose do you know it?

**Comment by viceice** [comment]
So this is not a bug, the previous behavior was a bug, as renovate used the docker hub fallback to the amd64 image, which is not working for non amd64 image usage.
This was also not working for other docker registries.

**Comment by viceice** [comment]
Sorry, @HonkingGoose  can you readd the bazel label. Was a same time update. 😅

**Comment by HonkingGoose** [comment]
> I think there is already a issue about this.
> @HonkingGoose do you know it?

I'm not sure about that... I searched for `bazel` OR `amd64` and those terms do get search results, but I don't know enough about this issue to see if any of those issues are the one you meant. So maybe you can try searching yourself? 😉

**Comment by viceice** [comment]
Found discussions. 😏

https://github.com/renovatebot/renovate/discussions/8381

https://github.com/renovatebot/renovate/discussions/8560

**Comment by croachrose** [comment]
Thanks for helpful pointers. Specifying `amd64/nginx` works but a repo like `amd64/python` still returns a manifest list:

```
docker manifest inspect amd64/python:3.6                             renovate/python3.6-3.6 ]
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2217,
         "digest": "sha256:8b463666e3542432f6a0566eb90710d10b266ef56a53e2dad70ad2f9cdd07a08",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

Maybe the bazel manager should start extracting `architecture` and `os` in order to filter the list? I'm unclear on what would be the best behavior here.

**Comment by viceice** [comment]
Yes, i think this is a bazel issue, as the docker tag points to a manifest list instead of a single image. Did you check if python has some other tags with prefix or suffix directly pointing to an image? Renovate will work fine out of the box with suffixes.

**Comment by rohansingh** [comment]
Check out the `container_pull` documentation:
https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_pull

It specifies that the default behavior is to fetch the amd64 architecture if no architecture is specified.

@viceice Based on the above, I think it's not a "Bazel issue" in the sense that Bazel is broken, it's just that this is the specified behavior.

**Comment by viceice** [comment]
It says it uses `linux/amd64` by default, when the image points to a manifest list. 

So I'm sure the rule has a bug if it includes a digest pointing to a manifest list instead of a single image.

So this isn't a bug at renovate.

**Comment by rohansingh** [comment]
Alright, I'll try to open an issue in rules_docker.

**Comment by HonkingGoose** [comment]
@rohansingh Did you find time to open an issue in `rules_docker`? If so can you maybe give us a link to the issue?

**Comment by viceice** [comment]
😕 

https://github.com/bazelbuild/rules_docker/issues/714
https://github.com/bazelbuild/rules_docker/issues/1319

**Comment by rarkins** [comment]
Blocked by #9667

**Comment by ns-ggeorgiev** [comment]
I do not think this is bazel issue. The goal for bazel requesting digest is to assure that the artifact is not going to be updated under your feet.

Defaulting to particular os/architecture can be used as an argument there is no need to hash the whole list, it could hash only the specific image, but this is not an argument not to hash the whole list since this also does the job.

**Comment by ns-ggeorgiev** [comment]
@rarkins how I can disable this reports, if it is not going to be fixed?

**Comment by rarkins** [comment]
You can add a packageRules entry with matchManagers=["bazel"], matchUpdateTypes=["digest"] and enabled=false, but for any follow up configuration help questions please post a discussion rather than adding to this issue.

Docker image digests are mutable and have valid reasons for getting digest updates, such as Debian base images pushing a security update to their base images, which then flows through to downstream library images like node:16.14.0. Keeping yourself pinned to old, potentially vulnerable Docker images would be undesirable in most situations.

**Comment by ns-ggeorgiev** [comment]
@rarkins thank you, will do.

If I create PR to change the logic in renovate to match the current logic in bazel, would you consider merging it in master or you are strongly convinced that this should be reflect in bazel?

**Comment by rarkins** [comment]
It's been a while since we discussed it. Can you or anyone else summarize the difference between bazel's behavior and Renovate's, with a real example of which hash Renovate chooses versus which one Bazel does?

I think in Renovate's case we use the collective hash for all platforms. Is Bazel using a platform-specific hash such as amd64, or is it a different mismatch we're seeing?

**Comment by ns-ggeorgiev** [comment]
Correct, for example in the following bazel WORKSPACE we pull linux/amd64 and linux/386.

```
container_pull(
    name = "alpine",
    digest = "sha256:a777c9c66ba177ccfea23f2a216ff6721e78a662cd17019488c417135299cd89",
    registry = "index.docker.io",
    repository = "alpine",
    tag = "3.15.4",
    architecture = "amd64",
    os = "linux",
)

container_pull(
    name = "alpine2",
    digest = "sha256:51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4",
    registry = "index.docker.io",
    repository = "alpine",
    tag = "3.15.4",
    architecture = "386",
    os = "linux",
)
```
 and the digest is what we see in the manifest inspect: 
 ```
 ...
       {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 528,
         "digest": "sha256:a777c9c66ba177ccfea23f2a216ff6721e78a662cd17019488c417135299cd89",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
...
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 528,
         "digest": "sha256:51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4",
         "platform": {
            "architecture": "386",
            "os": "linux"
         }
      },      
 ```
 Note that if we do not specify os/architecture bazel defaults to linux/amd64 or with other works the following two are equivalent:
 ```
 container_pull(
    name = "alpine",
    digest = "sha256:a777c9c66ba177ccfea23f2a216ff6721e78a662cd17019488c417135299cd89",
    registry = "index.docker.io",
    repository = "alpine",
    tag = "3.15.4",
    architecture = "amd64",
    os = "linux",
)

container_pull(
    name = "alpine",
    digest = "sha256:a777c9c66ba177ccfea23f2a216ff6721e78a662cd17019488c417135299cd89",
    registry = "index.docker.io",
    repository = "alpine",
    tag = "3.15.4",
)
```

Now if we pull with docker two different architectures we can notice that docker reports the same digest for both, which is essentially the a sha of the aggregate manifest.
```
C02GH3G8MD6T:~ ggeorgiev$ docker pull --platform linux/amd64 alpine:3.15.4
3.15.4: Pulling from library/alpine
Digest: sha256:4edbd2beb5f78b1014028f4fbb99f3237d9561100b6881aabbf5acce2c4f9454
Status: Downloaded newer image for alpine:3.15.4
docker.io/library/alpine:3.15.4
C02GH3G8MD6T:~ ggeorgiev$ docker pull --platform linux/386 alpine:3.15.4
3.15.4: Pulling from library/alpine
Digest: sha256:4edbd2beb5f78b1014028f4fbb99f3237d9561100b6881aabbf5acce2c4f9454
Status: Downloaded newer image for alpine:3.15.4
docker.io/library/alpine:3.15.4
```

I hope this makes it clear.

**Comment by viceice** [comment]
All other managers are working with image list digest, only bazel isn't able to use it and needs to pin platform specifig image digest.

So when we change the behavior, it needs to be done in bazel manager, so we don't have any side effect to other managers.

I still think thats a bazel bug.
