### ISSUE TITLE
Support for a new package manager : jsonnet-bundler

### ISSUE THREAD

**Issue by nlamirault** [renovatebot/renovate#9800]
**What would you like Renovate to be able to do?**

What do you think about support a new package manager :  Jsonnet-Bundler ? 

https://github.com/jsonnet-bundler/jsonnet-bundler

**Did you already have any implementation ideas?**

No.

**Comment by nlamirault** [comment]
@rarkins I use Renovate to update my dependencies (Ansible, Helm chart, ...) but for jsonnet file I don't know how do that. :(

```json
{
  "version": 1,
  "dependencies": [
    {
      "source": {
        "git": {
          "remote": "https://github.com/grafana/grafana.git",
          "subdir": "grafana-mixin"
        }
      },
      "version": "v7.5.5"
    }
  ],
  "legacyImports": true
}
```

**Comment by viceice** [comment]
@nlamirault can you please extend the issue description with your concrete samples and describe what you expect.

If i remember correctly json net can contain a kind of scripting, so please provide a more complex file too.


Best is to create a public minimal reproduction repo, so we or the community can test and debug against.

**Comment by nlamirault** [comment]
Like that : https://github.com/nlamirault/monitoring-mixins/tree/master/mixins/grafana-mixin

Theres is a dependency on Grafana project, version 7.5.5, and subdir is use to find the dependency.

**Comment by rarkins** [comment]
Do I understand the following correctly?
- You are interested in updating .jsonnet files which might contain dependencies within
- The syntax/format within these files is not standardized, and is essentially your own "free form"?

**Comment by nlamirault** [comment]
For Helm files, i use comment like that : `# renovate: registryUrl=https://charts.jetstack.io/`
And a configuration : 

```
"regexManagers": [
    {
      "fileMatch": ["kubernetes/.+\\.yaml$"],
      "matchStrings": [
        // helmrelease
        "registryUrl=(?<registryUrl>.*?)\n *chart: (?<depName>.*?)\n *version: (?<currentValue>.*)\n",
```

But how do that in a json file. I can't make comment. Any idea ?

**Comment by rarkins** [comment]
Are you talking json or jsonnet now?

And you didn't answer my questions.

**Comment by nlamirault** [comment]
@rarkins Jsonnet dependencies, but i thinks format of the file is in json, like : https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/jsonnetfile.json or https://github.com/grafana/jsonnet-libs/blob/master/prometheus-ksonnet/jsonnetfile.json

**Comment by viceice** [comment]
https://github.com/jsonnet-bundler/jsonnet-bundler

He is referring to jsonnet-bundler. They also have lock files.

**Comment by rarkins** [comment]
@nlamirault if that's the case then can you update the title and description and we'll then classify it as a new package manager request?

**Comment by rarkins** [comment]
Here's what I think needs to be done:
1. The JSON file can likely be updated with autoReplace like most managers
2. There needs to be an "updateArtifacts()" function added for the new manager
3. That updateArtifacts would need to call `jb`, which therefore needs to be added to https://github.com/containerbase/buildpack. Looks like it's installable via Go, so would need to e.g. run in a Go-compatible sidecar container in the app. Not sure if there's a way to install an exact version?

**Comment by lukasmrtvy** [comment]
What about https://github.com/grafana/tanka? Do We need to implment another manager? Tanka is using jb too.

**Comment by andrein** [comment]
I'm not using tanka, but this manager should work.

**Comment by nlamirault** [comment]
Great ! How can i use this version @rarkins  ? According to my Renovate App Dashboard, execution use an older version:

```json
INFO: Repository started
{
  "renovateVersion": "29.14.1"
}
```

**Comment by nlamirault** [comment]
Works fine ! So good : https://github.com/nlamirault/monitoring-mixins/pull/72/files
Thanks
