### ISSUE TITLE
gomod major update failed without log output

### ISSUE THREAD

**Issue by xoxys** [renovatebot/renovate#9842]
**What Renovate type, platform and version are you using?**

GitHub + Renovate GitHub App

**Describe the bug**

Gomod major update failed without error message in the PR.

**Relevant debug logs**

The error occurs on the GitHub app, the renovate Job ID is `xoxys/test: #347831816`. Let me know if I should paste the job log here anyway.

<details><summary>Click me to see logs</summary>

```
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Repository: https://github.com/xoxys/test/pull/7

**Comment by rarkins** [comment]
There's no "docker run" command in job 347831816, so I think that commit was probably done in an earlier run.

**Comment by xoxys** [comment]
I don't get it. I've closed the liked test PR again. Renovate automatically recreated the PR, nothing else done in the meantime. The last Job ID is now `xoxys/test: #347831987`, and still, no "docker run" command. As you can the in the PR https://github.com/xoxys/test/pull/8 there is no error output posted from Renovate. Just the red status check "Artifact file update failure" nothing else. Part of this issue is "failed without log output" as I was also not able to find any error information in the Job log.

No idea how to debug further, but the result is a failing Renovate artifact update.

**Comment by rarkins** [comment]
Renovate doesn't run `go` every single time it checks a repository. So to find the job log when `go` was run you need to look at the commit timestamp and correlate it. If you close a PR without deleting the underlying branch then most times the PR will be recreated without a new commit (i.e. reusing the same branch).

**Comment by xoxys** [comment]
Thanks. Ok after closing/renaming my PR + deleting the branch it works now. It's a bit strange that renovate stuck in such a "broken" state. Just curious is there another way to re-trigger the go "docker run" part for an existing PR?

**Comment by rarkins** [comment]
Yes, tick the retry/rebase checkbox in the PR description and that tells Renovate to retry the upgrade and commit.

**Comment by xoxys** [comment]
Hmm ok, I was pretty sure I did it yesterday without any change. However, now the error is gone :) thanks again!
