### ISSUE TITLE
Error thrown in simple-git prevents renovate from merging PRs: error: malformed object name

### ISSUE THREAD

**Issue by dylang** [renovatebot/renovate#9880]
**What Renovate type, platform and version are you using?**

**Renovate type**

- [ ] Hosted app
- [X] Self hosted

**Renovate platform**

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server (self-hosted)
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server (self-hosted)
- [ ] Gitea (gitea.com, self-hosted)
- [X] GitHub (github.com, GitHub Enterprise)
- [ ] GitLab (gitlab.com, self-hosted)

**Renovate version (if self hosting)** 

I'm self hosting Renovate with version: `v25.11.0` (I think issue started in `v25.10.0`)

**Describe the bug**

Approved PR's are no longer being merged. Error in the debug logs.

**Relevant debug logs**

An error like this for every single PR in every repo we run renovate:

<details><summary>Click me to see logs</summary>

```json
{
    "name":"renovate",
    "hostname":"60bb6301af72",
    "pid":199,
    "level":20,
    "logContext":"3G6ylLbl-",
    "repository":"MyTeam/myRepoName",
    "branch":"renovate/react-17.0.x",
    "err":{
        "task":{
            "format":"utf-8",
            "commands":[
                "branch",
                "-v",
                "--remotes",
                "--verbose",
                "--contains",
                "9a8fea2d918b08769d5655445d771779f1cfa506\n--"
            ]
        },
        "message":"error: malformed object name 9a8fea2d918b08769d5655445d771779f1cfa506\n--\n",
        "stack":"Error: error: malformed object name 9a8fea2d918b08769d5655445d771779f1cfa506\n--\n\n    at Object.action (/home/jenkins/workspace/renovate_master/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)\n    at PluginStore.exec (/home/jenkins/workspace/renovate_master/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)\n    at /home/jenkins/workspace/renovate_master/node_modules/simple-git/src/lib/runners/git-executor-chain.js:92:45\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/jenkins/workspace/renovate_master/node_modules/simple-git/src/lib/runners/git-executor-chain.js:90:16)\n    at GitExecutorChain.<anonymous> (/home/jenkins/workspace/renovate_master/node_modules/simple-git/src/lib/runners/git-executor-chain.js:74:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/jenkins/workspace/renovate_master/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    },
    "msg":"Converting git error to ExternalHostError",
    "time":"2021-05-05T16:30:01.193Z",
    "v":0
}
```
</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [X] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

The last successful PR merge was the evening of May 3, 2021.
* `renovate to v25.10.0` merged successfully.
* `renovate to v25.11.0` did not merge because of this error.
* Manually merging renovate PRs works, but doesn't make Renovate start merging them again.

**Comment by rarkins** [comment]
Apologies for the regression, it should be fixed in https://github.com/renovatebot/renovate/releases/tag/25.12.2
