### ISSUE TITLE
Dependency dashboard doesn't get updated with open PRs when using `pr-comment` automerge functionality

### ISSUE THREAD

**Issue by mannycarrera4** [renovatebot/renovate#9991]
**Renovate type**

- [ ] Hosted app
- [x] Self hosted

**Renovate platform**

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server (self-hosted)
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server (self-hosted)
- [ ] Gitea (gitea.com, self-hosted)
- [x] GitHub (github.com, GitHub Enterprise)
- [ ] GitLab (gitlab.com, self-hosted)

**Renovate version (if self hosting)**

I'm self hosting Renovate with version:  >=24.116.1 

Reverting back to 24.116.0 fixes the issue

**Describe the bug**

The dependency dashboard does not show an `Open` section when using `  "automergeType": "pr-comment"`.

This is problematic when either the automerge takes time to run as it does not keep the dashboard up-to-date with the current state of reality or if the automerge happens to fail, the dashboard never reflects a PR being opened, the dependency just gets removed from it.

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [x] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I believe that this was introduced by https://github.com/renovatebot/renovate/commit/9ee35de2e1dacc1bde677198b7312c5d097d9ed3#diff-76ca284a58d670d6e91e7a6eafa6cc447fbf2dead9f179c43c01fb2522c465e1L605 and think adding it back will fix things.

**Comment by viceice** [comment]
I think this is a known behavior, as renovate never updates the dependency dashboard when it has done a automerge.

So it always needs a second run to update the dashboard, which is normally one hour later. Did your pr-comment merge need longer than one hour?

**Comment by mannycarrera4** [comment]
The dependency dashboard issue never updates and the “Open” section is never created even when renovate is ran multiple times

**Comment by rarkins** [comment]
Renovate@25.37.1 now runs again automatically after an automerge and *should* update the dashboard afterwards correctly. I'm going to close this as resolved but it can be re-opened if there's something specific about the automergeComment which is not working and a reproduction can be made
