### ISSUE TITLE
Consider singleton utility

### ISSUE THREAD

**Issue by zharinov** [renovatebot/renovate#9996]
**What would you like Renovate to be able to do?**

Avoid ad-hoc module-local state and use some `Singleton<T>` class instead

**Did you already have any implementation ideas?**

**Comment by pret-a-porter** [comment]
I will take this one

**Comment by pret-a-porter** [comment]
I suppose the best way is go through all current module-local state cases and rewrite it to [singletone](https://refactoring.guru/design-patterns/singleton/typescript/example) pattern

**Comment by pret-a-porter** [comment]
I know about next places:
1. `repoCache` in lib/util/cache/memory/index.ts
2. `baseUrl` in lib/util/http/bitbucket-server.spec.ts
3. `baseUrl` in lib/util/http/bitbucket.ts
4. `baseUrl` in lib/util/http/gitea.ts
5. `baseUrl` in lib/util/http/github.ts
6. `baseUrl` in lib/util/http/gitlab.ts
7. `agent` in lib/proxy.ts
8. `returnVal` in lib/config-validator.ts
9. `renovateVersion` in lib/workers/repository/index.ts
10. `limits` in lib/workers/global/limits.ts

**Comment by rarkins** [comment]
Please wait for comments/approval from @zharinov @viceice @JamieMagee

**Comment by pret-a-porter** [comment]
In general I would propose to think about hexagonal architecture and use something for dependency injection. It will allow have separate layers of application and communicate between them by interfaces, instead of implementations.

**Comment by rarkins** [comment]
I'm not an expert in this area, so need to defer to others to decide. However I'd like to point out that future maintainability is always very important for us.

**Comment by JamieMagee** [comment]
@pret-a-porter Could you do one of the conversions as a sample case, so we can see a comparison for readability, maintainability, etc.

In general, I am in favour of dependency injection. I think the most popular JS library for DI is [InversifyJS](https://github.com/inversify/InversifyJS). However, this is a big change and would require a lot of refactoring. We might be able to test it out on a small scale with Datasources, once I complete the conversion to classes.

**Comment by pret-a-porter** [comment]
Basically this code
```ts
let repoCache: Record<string, any> | undefined;

export function init(): void {
  repoCache = {};
}

export function reset(): void {
  repoCache = undefined;
}

export function get<T = any>(key: string): T {
  return repoCache?.[key];
}

export function set(key: string, value: unknown): void {
  if (repoCache) {
    repoCache[key] = value;
  }
}
```
can be replaced by
```ts
export const cache = new Map<string, unknown>();
```
or
```ts
export class Cache {
  private static instance?: Cache;

  public readonly store: Map<string, unknown>;

  private constructor() {
    this.store = new Map();
  }

  public static getInstance(): Cache {
    if (!Cache.instance) {
      Cache.instance = new Cache();
    }

    return Cache.instance;
  }
}

const cache = Cache.getInstance();
cache.store.set('test', 'test');
cache.store.get('test'); // test
cache.store.clear();
```

**Comment by pret-a-porter** [comment]
In this case
```ts
let baseUrl = 'https://api.bitbucket.org/';

export const setBaseUrl = (url: string): void => {
  baseUrl = url;
};

export class BitbucketHttp extends Http {
  constructor(options?: HttpOptions) {
    super(PLATFORM_TYPE_BITBUCKET, options);
  }

  protected override request<T>(
    url: string | URL,
    options?: InternalHttpOptions
  ): Promise<HttpResponse<T> | null> {
    const opts = {
      baseUrl,
      ...options,
    };
    return super.request<T>(url, opts);
  }
}
```
I would move baseUrl inside `BitbucketHttp` class as static field
```ts
export class BitbucketHttp extends Http {
  public static baseUrl = 'https://api.bitbucket.org/';

  constructor(options?: HttpOptions) {
    super(PLATFORM_TYPE_BITBUCKET, options);
  }

  protected override request<T>(
    url: string | URL,
    options?: InternalHttpOptions
  ): Promise<HttpResponse<T> | null> {
    const opts = {
      baseUrl: BitbucketHttp.baseUrl,
      ...options,
    };
    return super.request<T>(url, opts);
  }
}
```
