### ISSUE TITLE
gradle-lite doesn't detect updates in subproject gradle.properties files

### ISSUE THREAD

**Issue by jamesdh** [renovatebot/renovate#9999]
**Renovate type**

- [x] Hosted app
- [ ] Self hosted

**Renovate platform**

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server (self-hosted)
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server (self-hosted)
- [ ] Gitea (gitea.com, self-hosted)
- [x] GitHub (github.com, GitHub Enterprise)
- [ ] GitLab (gitlab.com, self-hosted)

**Describe the bug**

In my project root I have a `settings.gradle.kts` file that's there strictly to assist gradle in finding my gradle-based "backend" project in a subdir, e.g. 

```
rootProject.name = 'myapp'
include 'back'
```

Within the 'back' dir exists a `build.gradle.kts` and `gradle.properties` files. Updates are detected to the `build.gradle.kts` file just fine, but not to `gradle.properties`. This recently caused some major confusion and troubleshooting due to dependencies getting updated in `build.gradle.kts` that were dependent on a certain BOM version also being updated in `gradle.properties`, for which it was not updated. 

`gradle.properties` only contains the following: 

```
micronautVersion=2.4.2
```

.....for which an update is available to 2.5.3

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
"gradle-lite": [
      {
        "packageFile": "settings.gradle",
        "datasource": "maven",
        "deps": []
      },
      {
        "packageFile": "back/gradle.properties",
        "datasource": "maven",
        "deps": []
      },
      {
        "packageFile": "back/build.gradle.kts",
        "datasource": "maven",
        "deps": [
          {
            // ...numerous deps detected here
```

</details>

**Have you created a minimal reproduction repository?**

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

See https://github.com/jamesdh/renovate-9999 for reproducing repo

**Comment by jamesdh** [comment]
@rarkins I just added https://github.com/jamesdh/renovate-9999 which should reproduce this. Just waiting on the initial renovate PR/run.

**Comment by rarkins** [comment]
@jamesdh thanks. Can you add a `readme.md` to that repo which describes expected vs actual behavior?

e.g. you linked to a PR in the repo. Is that PR wrong? Or is the thing that's wrong that there's some other dependency *not* being updated?

**Comment by jamesdh** [comment]
I was under the impression that gradle/gradle-lite would detect version changes in the `gradle.properties` file, but I'm not sure that makes sense now since the variables defined there often have no direct match to an actual dependency out on a maven repository. 

For instance, the [gradle.properties file](https://github.com/jamesdh/renovate-9999/blob/main/back/gradle.properties) in question has a `micronautVersion=2.4.4` defined, but the latest version available is actually 2.5.3. However, that's not picked up by renovate.

**Comment by rarkins** [comment]
Is that string `micronautVersion` referred to anywhere within the reproduction repo?

**Comment by jamesdh** [comment]
Yes, it's in the [gradle.properties](https://github.com/jamesdh/renovate-9999/blob/main/back/gradle.properties) file. 

I'm not sure describing this in a repo readme file is any better than describing it here in the issue itself, unless I'm misunderstanding what's being asked for. Personally, having portions of the problem described in disparate areas just makes things more confusing, not less.

**Comment by rarkins** [comment]
I meant does any *other* file refer to that variable? If not then it's an unused variable and impossible for Renovate to know what it refers to unless you manually configure it using regexManagers
